### ISSUE TITLE
ページ内コンテンツの縦スクロールバー常時表示

### ISSUE THREAD

**Issue by taichi-n** [tokyo-metropolitan-gov/covid19#1001]
## 改善詳細 / Details of Improvement
トップページの「要請患者の属性」のように、コンテンツが縦に長くても、ChromeやSafariでは縦スクロールバーが出ないため、それ以上にコンテンツがあると気づけ無いため、縦スクロールバーを常時表示する

### 現在
<img width="534" alt="スクリーンショット 2020-03-10 14 45 05" src="https://user-images.githubusercontent.com/5411102/76285254-a8106880-62e2-11ea-873d-678cdb7ae22b.png">
これだと、このテーブル部分がスクロールできることが分かりづらい

### 改善案
<img width="515" alt="スクリーンショット 2020-03-10 15 17 00" src="https://user-images.githubusercontent.com/5411102/76285280-b6f71b00-62e2-11ea-80e9-5129ecb36785.png">
このように縦スクロールバーを表示させてあげたい

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome / Safari  / Edge

**Comment by NumLocker-Japan** [comment]
macOSでスクロールバーが非表示になっているのは、OSの仕様です。
[こちら](https://qiita.com/nanocloudx/items/0efba5d35fe5a4cc7230)の記事が参考になるかもしれません。
ただ、確かにスクロールできることを分かりやすくしたほうがいいですね。スクロールバーとは違う部分でそれを表現することになりそうです。

**Comment by taichi-n** [comment]
ありがとうございます！
もしかしたら、「すべて表示する」ボタン用意して、クリックしたら全部表示するか、
スクロールが可能であることを示すデザインを考えたほうが良いかと思いました。

**Comment by NumLocker-Japan** [comment]
そうですね、影を付けてスクロールが可能であることを示す方法がメジャーかと思います。ちょっとやってみますね。

**Comment by NumLocker-Japan** [comment]
この表の場合、スクロールしても常に表示されるヘッダー部分と、スクロールに合わせて動くボディー部分に分かれていましたので、こんな感じで影を落とせばいいかなと思います。(画像はWindowsですが、分かりやすいように一時的に上下スクロールバーを非表示にしています。)

![image](https://user-images.githubusercontent.com/46442187/76321943-10346e00-6326-11ea-8d00-d45a9dfd7dce.png)

また、画面幅が小さい場合、横方向のスクロールバーも表示されますが、画面幅の小さいPCでのみ表示されることと、実装のコストを考えてとりあえず見送りました。
ご意見等あればどなたでもお願いします。

**Comment by taichi-n** [comment]
@NumLocker-Japan 

良いと思います！ありがとうございます！

**Comment by NumLocker-Japan** [comment]
Conflictする可能性があったので、 #1299 のほうで改めてPR出させてもらいました。
