### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowPcSuspect.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1002]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

i18n対応に向けたマークアップの修正およびスタイルの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowPcSuspect.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

なお、以下のissueで懸案事項が提案されています。
#992

### スタイルの修正
- テキストが左寄せになっているので、センター寄せに。
<img width="221" alt="スクリーンショット 2020-03-10 12 15 31" src="https://user-images.githubusercontent.com/14883063/76285549-5d432080-62e3-11ea-9a87-5be9fb47c598.png">

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by kebhr** [comment]
どなたも取りかかられてなければやりますー。

**Comment by kaizumaki** [comment]
@kebhr ぜひぜひ！よろしくお願いします！

**Comment by MaySoMusician** [comment]
追加で`eslint-disable`のコメントも除去出来たらお願いします～

**Comment by kebhr** [comment]
残っていましたね...申し訳ないです。
Mergedなので、修正のPRを作りますー

**Comment by MaySoMusician** [comment]
i18n側としてはこのissueについては作業完了だと思います
close はflow側にお任せします @kaizumaki
