### ISSUE TITLE
「陽性患者数」カードの文字フォーマットを整える

### ISSUE THREAD

**Issue by adamrocker** [tokyo-metropolitan-gov/covid19#1003]
## 改善詳細 / Details of Improvement
- 「陽性患者数」カードの文字情報のフォーマットを他カードに統一する
- 情報提供フォーマットを整えることで享受者の情報処理コストが下がる（分かりやすくなる）

## スクリーンショット / Screenshot
![スクリーンショット_2020-03-10_15_02_46](https://user-images.githubusercontent.com/316463/76285673-ab582400-62e3-11ea-82ef-b0e29b847725.png)

![スクリーンショット_2020-03-10_15_29_14](https://user-images.githubusercontent.com/316463/76285812-feca7200-62e3-11ea-9d3c-b08984ef7171.png)

↓他カードの文字フォーマット
![スクリーンショット_2020-03-10_15_22_24](https://user-images.githubusercontent.com/316463/76285703-b7dc7c80-62e3-11ea-823e-10bb3e7f9384.png)

## 期待する見せ方・挙動 / Expected behavior
- {日付}の[合計|累積値]に統一する
<img width="560" alt="スクリーンショット_2020-03-10_15_02_21" src="https://user-images.githubusercontent.com/316463/76285820-02f68f80-62e4-11ea-9bf9-d60079227386.png">

<img width="559" alt="スクリーンショット_2020-03-10_15_02_29" src="https://user-images.githubusercontent.com/316463/76285832-068a1680-62e4-11ea-8755-0d30a74889a1.png">

## 動作環境・ブラウザ / Environment
- 全てのOS、ブラウザ

**Comment by ocean3fish** [comment]
こちらでご提案頂いた件は https://github.com/tokyo-metropolitan-gov/covid19/pull/2664 で解消されたため、クローズとさせて頂きます。
