### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowPc.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1005]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

i18n対応に向けたマークアップの修正およびスタイルの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowPc.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

なお、以下で懸案事項が提案されています。
#956

### スタイルの修正
- ウィンドウ幅を狭めると、矢印が「陽性」と離れた位置になってしまっている。
<img width="589" alt="スクリーンショット 2020-03-10 12 16 40" src="https://user-images.githubusercontent.com/14883063/76286593-f2dfaf80-62e5-11ea-9f4e-4f75389ad159.png">

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by kaizumaki** [comment]
あ、これはもしかして `components/flowFlowPcPcr.vue` のほうも修正した方がいいかもですね。
 `FlowPcPcr.vue` のリファクタリングのissueはこちら。 #995

**Comment by PichuChen** [comment]
やります！

**Comment by kaizumaki** [comment]
@PichuChen お願いします！

**Comment by PichuChen** [comment]
#970 Ready for merge

**Comment by MaySoMusician** [comment]
Close per #970 merged
