### ISSUE TITLE
flow pageをsafariで表示すると印刷ボタンが横に長い

### ISSUE THREAD

**Issue by mnomura3** [tokyo-metropolitan-gov/covid19#1008]
## 改善詳細 / Details of Improvement
- flow pageをsafariで表示すると印刷ボタンが横に長い

## スクリーンショット / Screenshot
<img width="1095" alt="スクリーンショット 2020-03-10 16 27 29" src="https://user-images.githubusercontent.com/32609333/76289319-2e7d7800-62ec-11ea-835a-5d117f910778.png">

## 期待する見せ方・挙動 / Expected behavior
- Chromeに合わせる
<img width="1167" alt="スクリーンショット 2020-03-10 16 29 02" src="https://user-images.githubusercontent.com/32609333/76289373-55d44500-62ec-11ea-86f2-35659b81d5ae.png">

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari

**Comment by asuchi0819** [comment]
iPad 6th 9.7inch / iPadOS 13.3
でも確認できました。
![3F86DD4C-E2D5-42EE-A8F2-E45033E8C77A](https://user-images.githubusercontent.com/45027336/76289747-2a058f00-62ed-11ea-8233-0cf6558a911e.jpeg)

**Comment by asuchi0819** [comment]
Windowsでウィンドウサイズを変えて確認したところ、横長にはならないのでOSの問題っぽいです。
引き続き確認してみます。

**Comment by bapex** [comment]
自分の環境（Safari 13.0.4） でも同じ現象を確認できました。chrome, firefoxは問題なしです。

<img width="917" alt="スクリーンショット 2020-03-10 16 40 45" src="https://user-images.githubusercontent.com/19667736/76290089-ebbc9f80-62ed-11ea-8753-942f2fe461a4.png">

**Comment by asuchi0819** [comment]
WindowsでUAを変えても特に再現はできませんでした。
Safariのブラウザの問題みたいです。
![image](https://user-images.githubusercontent.com/45027336/76290598-d300b980-62ee-11ea-8754-ac89eeb248a7.png)

**Comment by mnomura3** [comment]
ついでにsafariで印刷するボタン押しても↓これが開かないかな。Chromeだと開く
<img width="988" alt="スクリーンショット 2020-03-10 16 51 40" src="https://user-images.githubusercontent.com/32609333/76291002-a13c2280-62ef-11ea-9f54-ed36fefce7e6.png">

**Comment by asuchi0819** [comment]
UA偽装してスタイルの検証をしてみたけど特に問題となりそうな部分はなさげ？
macOS Safariではどうでしょうか？

**Comment by bapex** [comment]
svgのwidthが効いていない気がします。

<img width="436" alt="スクリーンショット 2020-03-10 17 01 00" src="https://user-images.githubusercontent.com/19667736/76291579-bcf3f880-62f0-11ea-874d-4243c61cd32f.png">

**Comment by mnomura3** [comment]
よし、誰か直してプルリク送るんだw

**Comment by nysopua** [comment]
svgのwidth: 100%;をwidth: auto;にすると良さげ

**Comment by bapex** [comment]
@nysopua ありがとうございます。それでは僕の方で修正しておきますね。

**Comment by asuchi0819** [comment]
お願いします！
（どこかわからなかったのは秘密

**Comment by mnomura3** [comment]
<img width="630" alt="スクリーンショット 2020-03-10 17 24 17" src="https://user-images.githubusercontent.com/32609333/76293256-114ca780-62f4-11ea-8a79-e1977af19bd1.png">

**Comment by bapex** [comment]
@mnomura3 修正したのでレビューしていただてもよろしいでしょうか？

**Comment by mnomura3** [comment]
@bapex どっちのやり方がいいんだろうね？？自分のは適当にこの辺？みたいな感じで直してキャプチャとっただけだから

**Comment by bapex** [comment]
@mnomura3 
DesktopFlowSvgを修正するとdeployエラーになったので、一旦PrinterButtonコンポーネントのsvgを修正するという方向にしようかなと思っています。

![スクリーンショット 2020-03-10 18 08 40](https://user-images.githubusercontent.com/19667736/76296854-3217fb80-62fa-11ea-8436-5cd83eb663df.png)

**Comment by mnomura3** [comment]
@bapex 了解です。お願いします。
