### ISSUE TITLE
サーチコンソール用のhmtlファイル設定

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1009]
サーチコンソール用のhtmlの設定をお願いいたします。
https://codeforjapan.sharepoint.com/sites/covid19/Lists/List2/DispForm.aspx?ID=4&e=biLc14
参考）
https://support.google.com/webmasters/answer/9008080#google_analytics_verification

**Comment by halsk** [comment]
やります！
