### ISSUE TITLE
[i18n]「陽性患者の属性」テーブルのヘッダーの翻訳が正しく切り替わらない

### ISSUE THREAD

**Issue by rozeo** [tokyo-metropolitan-gov/covid19#1012]
## 起こっている問題 / The Problem
- 日本語→他言語への切り替えは正しく翻訳が行われるが他言語→他言語や他言語→日本語の際に正しく翻訳が行われなかったり翻訳が混ざったりする。
- ※ ただしリロードすると正しく翻訳される。また、戻るボタンでの遷移にも影響している

## スクリーンショット / Screenshot

![merge](https://user-images.githubusercontent.com/8382766/76292517-b8304400-62f2-11ea-9b10-03f1f3ea7162.png)
![無題](https://user-images.githubusercontent.com/8382766/76292523-ba929e00-62f2-11ea-97c0-c9a7e39af087.png)

#822 の previewビルドでは特にこれといったwarningやerrorの出力はない(localでのdevelopmentぶビルドも同様)
![SnapCrab_都内の最新感染動向  東京都 新型コロナウイルス感染症対策サイト - Google Chrome_2020-3-10_17-9-58_No-00](https://user-images.githubusercontent.com/8382766/76292634-ef9ef080-62f2-11ea-9a05-69a9b4fd827b.png)

## 期待する見せ方・挙動 / Expected Behavior
- 他言語からの切り替えの際にも正しく翻訳が行われるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
- 画像参照

## 確認環境・ブラウザ / Environment
- Windows 10 + Chrome / Linux Mint 19.3 + Chrome, Firefox

こちらですこし調査してみましたがわからず。よろしくお願いします🙇‍♂️

**Comment by asuchi0819** [comment]
問題の発生個所は、「日付」や「現在地」の部分の翻訳ということでしょうか？
当方の理解力不足申し訳ございません。

**Comment by rozeo** [comment]
「日付」や「現在地」の部分で相違ありません(+ 「年代」、「性別」の部分)。
退院※　の部分に関しては現状で翻訳データにないようです。

**Comment by MaySoMusician** [comment]
こちら、把握しております（忘れてた）
後ほどすぐ修正いたします

**Comment by rozeo** [comment]
了解しました、ありがとうございます🙇‍♂
