### ISSUE TITLE
[i18n] Add Language Switch per Page

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#1016]
## 改善詳細 / Details of Improvement
- 各ページに、表示言語（日、英、韓、簡体字中文、繁体字中文、ほか）をスイッチする UI を加える。
- Add a UI to switch display language in Japanese, English, Korean, Chinese (Simplified/Traditional) etc. in each page

## スクリーンショット / Screenshot
N/A
東京都のモノは、各言語のトップページに飛ばす形式なので正直いただけないです…

## 期待する見せ方・挙動 / Expected behavior
- たとえば、勤務先のコンフィグ方針に沿って OS やブラウザのロケールが ja_JP に定められている場合、外国人ユーザが母国語で情報を参照したいニーズへの対応が期待される。
- It is expected to provide non-Japanese users with his/her own language enabled. Non-Japanese users in Japanese offices used to suffer web language issues, because their PCs are usually configured in Japanese locale settings due to, for instance, Japan HQs' local IT policy.  

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android (perhaps we will not need to take care of smartphone OSs because they are more clever than desktop/laptop computers! lol)
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
> 東京都のモノは、各言語のトップページに飛ばす形式なので正直いただけないです…
https://deploy-preview-822--dev-covid19-tokyo.netlify.com/ から見れる暫定版ですと、各ページも翻訳版をご覧になれますが（一部翻訳途中のものもあり）、それとはまた異なった点のご指摘でしょうか？

**Comment by mcdmaster** [comment]
おお、まさにこれを想定していました。Production Release 前だったのですね。
では、これはいったん取り下げましょう。失礼しました＆ありがとうございました

**Comment by MaySoMusician** [comment]
@mcdmaster ご意見ありがとうございました！ 言語切り替えメニューについては、現在のリンク式は仮実装で、本番用のメニュー型のものの実装が #854 で進んでおります
