### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowSpAccording.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1030]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

flowページ（「新型コロナウイルス感染症が心配なときに」）のモバイル版のコンポーネント修正です。
i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowSpAccording.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

なお、以下で懸案事項が提案されています。
https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-596996548

疑問点などあれば、お気軽にこのissueにコメントしてください！

↓元デザインはこちら
![スクリーンショット 2020-03-10 19 19 08](https://user-images.githubusercontent.com/14883063/76303238-c12a1100-6304-11ea-8aec-39c50de540f3.png)

**Comment by open-osaka** [comment]
＃1030取り掛ります。

**Comment by kaizumaki** [comment]
@open-osaka よろしくお願いします！

**Comment by open-osaka** [comment]
♯1030完了しました。

**Comment by open-osaka** [comment]
コミットが正しく出来ているか確認お願いします。

**Comment by halsk** [comment]
@open-osaka 対応ありがとうございます！
Pull Request は行っておりますでしょうか？

**Comment by kaizumaki** [comment]
@open-osaka さん、↓を参考にプルリクエストを投げてくださーい！
https://qiita.com/FPC_COMMUNITY/items/b9cc072813dc2231b2b2#%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E3%82%92%E9%80%81%E3%82%8B

**Comment by macropygia** [comment]
slackでの要請を受けて引き継ぎます。
作業中に @open-osaka さんのPRがあればそちらを優先します。

**Comment by open-osaka** [comment]
手続きできなくてすみません、帰宅後すぐ処理します

2020年3月11日(水) 14:16 kaizumaki <notifications@github.com>:

**Comment by macropygia** [comment]
ほぼ未着手の段階で open-osaka さんが戻られたため当方は外れます。

**Comment by kaizumaki** [comment]
@open-osaka プルリクできそうですか？何かわからないことがあったら遠慮せずにコメントしてくださいね！

**Comment by kaizumaki** [comment]
@open-osaka #1136 ですかね？

**Comment by open-osaka** [comment]
すいません。そうです。

**Comment by halsk** [comment]
@open-osaka さん、zoom とかで画面共有しながら、一緒に PR しますか？

**Comment by halsk** [comment]
あ、別の方では PR 来てるんですね。

**Comment by halsk** [comment]
@open-osaka さん、https://github.com/tokyo-metropolitan-gov/covid19/pull/1136/files 拝見したのですが、diff とかが壊れてしまっていたため、ちょっと取り込むのが難しそうです。せっかく作業をしていただいたのに大変申し訳無いのですが、この Issue はかなり急いでいるものなので、一旦別の人にアサインさせていただいてもよろしいでしょうか。失礼な話で本当に申し訳ありません。
@macropygia さん、2転3転し申し訳ないのですが、まだ作業は可能でしょうか？

**Comment by macropygia** [comment]
@halsk 承ります

**Comment by open-osaka** [comment]
了解しました。他の方にアサインしてください。 Windows 10 版のメールから送信 差出人: Hal Seki送信日時: 2020年3月11日 21:51宛先: tokyo-metropolitan-gov/covid19CC: open-osaka; Mention件名: Re: [tokyo-metropolitan-gov/covid19] [/flow][i18n] コンポーネントリファクタリング FlowSpAccording.vue (#1030) @open-osaka さん、https://github.com/tokyo-metropolitan-gov/covid19/pull/1136/files 拝見したのですが、diff とかが壊れてしまっていたため、ちょっと取り込むのが難しそうです。せっかく作業をしていただいたのに大変申し訳無いのですが、この Issue はかなり急いでいるものなので、一旦別の人にアサインさせていただいてもよろしいでしょうか。失礼な話で本当に申し訳ありません。@macropygia さん、2転3転し申し訳ないのですが、まだ作業は可能でしょうか？—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by open-osaka** [comment]
＠macropygiaさんよろしくお願いいたします。

**Comment by macropygia** [comment]
@MaySoMusician  FlowSpAccordingのi18nは以下のPC版コンポーネントのi18nを結合したもので問題ないでしょうか。(使う物だけに絞る必要がある？)

- FlowPcRequired
- FlowPcPcr
- FlowPcSuspect

**Comment by kaizumaki** [comment]
@macropygia さん、もしかして作業すすめられない感じですか？

**Comment by kaizumaki** [comment]
> @MaySoMusician FlowSpAccordingのi18nは以下のPC版コンポーネントのi18nを結合したもので問題ないでしょうか。(使う物だけに絞る必要がある？)
> 
> * FlowPcRequired
> * FlowPcPcr
> * FlowPcNotRequired

@MaySoMusician さーん。こちらフォローお願いしますー

**Comment by MaySoMusician** [comment]
@kaizumaki これ、どこに返信すればよいでしょうか？（見つけられなかった）

**Comment by kaizumaki** [comment]
> @kaizumaki これ、どこに返信すればよいでしょうか？（見つけられなかった）

このissueでよいですよ！

**Comment by kaizumaki** [comment]
あ、消えとるw

**Comment by MaySoMusician** [comment]
@kaizumaki 
i18nってのは翻訳の辞書の部分ですよね？
ほとんどPC版のその3つと同じですが
```json
"検査の必要{ifRequired}": "検査の必要{ifRequired}",
"あり": "あり",
"なし": "なし",
```
ここだけPC版と異なるので注意を...（上例はモバイル版のもの）

**Comment by kaizumaki** [comment]
@macropygia だそうです。
i18n化は、 @MaySoMusician さんに全面的におまかせしたほうがいいように思います。 @macropygia さんはとりあえず、タグの構造だけ修正（それにともなうスタイルの修正含む）をやってもらえれば大丈夫です！

**Comment by macropygia** [comment]
翻訳データの件は私の勘違いでした、失礼しました。
これのPRはdevブランチで間違いないでしょうか。

@kaizumaki 報告が漏れましたスミマセン、着手済です。この後DraftPRまで進めて、ツッコミには明朝対応の予定です。

@MaySoMusician FlowSpAccordingとFlowPcRequiredの翻訳データにおいて、日本語以外の全ての言語で「受診が必要」の値が「受診が不要」のものになっているようです。把握されているかも知れませんが念のため報告しておきます。

**Comment by MaySoMusician** [comment]
@macropygia おっと、ありがとうございます。修正しておきます

**Comment by kaizumaki** [comment]
@macropygia いまslackで話し合ってたんですが、いったん作業をペンディングにしてもらっていいですか？ @MaySoMusician さんに、多言語化の作業をflowのモバイル版だけリベースしてもらいます。

**Comment by kaizumaki** [comment]
#1162

**Comment by macropygia** [comment]
@kaizumaki 把握しました。 #1162 にこれまでの作業分を反映してから作業を続行し、完了後にdevelopmentに対するDraftPRを出します。

**Comment by kaizumaki** [comment]
@macropygia ありがとうございます！遅くまですみませんでした 🙇‍♀ 今夜はもう休んでください。

**Comment by kaizumaki** [comment]
@macropygia 明日PRするときは、 `dev-i18n` ブランチに向けてくださるようお願いいたします。
