### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowSpPast.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1033]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

flowページ（「新型コロナウイルス感染症が心配なときに」）のモバイル版のコンポーネント修正です。
i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowSpPast.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

疑問点などあれば、お気軽にこのissueにコメントしてください！

↓元デザインはこちら。
![スクリーンショット 2020-03-10 19 40 06](https://user-images.githubusercontent.com/14883063/76304594-fafc1700-6306-11ea-8314-5b8e919ec3b8.png)

**Comment by kaizumaki** [comment]
以下に修正の要望があがっています。ご確認のほどを！
https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-597062555

**Comment by open-osaka** [comment]
＃1030取り掛かります。

**Comment by open-osaka** [comment]
＃1030修正出来ました

**Comment by halsk** [comment]
@open-osaka さん、Pull Request が来ていないようです。ご確認ください！
Pull Requestの出し方はこちら
https://qiita.com/FPC_COMMUNITY/items/b9cc072813dc2231b2b2#%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E3%82%92%E9%80%81%E3%82%8B

**Comment by macropygia** [comment]
slackでの要請を受けて引き継ぎます。
作業中に @open-osaka さんのPRがあればそちらを優先します。

**Comment by open-osaka** [comment]
プルリクエストが正しくできなくてすみません。macropygiaさん、作業はもう完了されていますか

**Comment by macropygia** [comment]
@open-osaka @kaizumaki
#1033 は下記のような感じで完了済・プルリク準備完了済です。#1030 は着手したばかりです。

![image](https://user-images.githubusercontent.com/3162324/76411016-43cdd180-63d4-11ea-89a0-911534b1ccad.png)

![image](https://user-images.githubusercontent.com/3162324/76410978-30226b00-63d4-11ea-8967-d8e7055e7760.png)

**Comment by open-osaka** [comment]
すみません。＃1030をこちらでプルリクエストしましょうか。

**Comment by macropygia** [comment]
@open-osaka #1030 はそちらで完了済とのことですので、PRしていただいて問題ないはずです。
@halsk @kaizumaki #1033 はどうしましょうか。

**Comment by halsk** [comment]
@macropygia さん、@open-osaka さん、プルリク両方だしちゃってください。確認してどちらかを取り込みます。

**Comment by open-osaka** [comment]
PRしました。

**Comment by kaizumaki** [comment]
@open-osaka あれ？やっぱりPRできてないようですね。
