### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowSpGeneral.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1035]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

flowページ（「新型コロナウイルス感染症が心配なときに」）のモバイル版のコンポーネント修正です。
i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowSpGeneral.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

疑問点などあれば、お気軽にこのissueにコメントしてください！

↓元デザインはこちら。
![スクリーンショット 2020-03-10 19 43 20](https://user-images.githubusercontent.com/14883063/76304847-6cd46080-6307-11ea-9f7f-1210d0ce390f.png)

**Comment by kaizumaki** [comment]
以下に修正の要望があがっています。ご確認のほどを！
https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-597049644

**Comment by MaySoMusician** [comment]
先ほど、修正要望の内容を一部訂正いたしました。ご確認お願いします。
https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-597034032

**Comment by af12066** [comment]
対応しますー

**Comment by MaySoMusician** [comment]
Close per #1078 merged
