### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowSpAdvisory.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1039]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

flowページ（「新型コロナウイルス感染症が心配なときに」）のモバイル版のコンポーネント修正です。
i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowSpAdvisory.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

以下に変更の要望があがっています。
https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-597018080

疑問点などあれば、お気軽にこのissueにコメントしてください！

↓元デザインはこちら。
![スクリーンショット 2020-03-10 19 51 42](https://user-images.githubusercontent.com/14883063/76305517-a063ba80-6308-11ea-9080-0aec7e2884c0.png)

**Comment by af12066** [comment]
対応いたしますー

**Comment by kaizumaki** [comment]
@af12066 よろしくお願いします！

**Comment by MaySoMusician** [comment]
Close per #1057 merged
