### ISSUE TITLE
退院者数／退院者データのグラフと表の追加

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#104]
入院後退院した人のデータも取れるようになったそうです。

感染者数／感染者データと全く同じフォーマットで追加をお願いします。

https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=121%3A709

![image](https://user-images.githubusercontent.com/1301149/75629521-163f9600-5c26-11ea-8996-95abe22edf0a.png)

**Comment by mikkame** [comment]
![スクリーンショット 2020-03-02 18 05 09](https://user-images.githubusercontent.com/13947046/75661292-619e8680-5cb0-11ea-8dac-3488fcc6af4d.png)

提案レベルですがこういう風なグラフの方がよかったりしませんか？

**Comment by ocean3fish** [comment]
@mikkame データ提供側での議論ですが、今後載せたいデータがふえてくるため、まずは追加スピード優先でシンプルな表とグラフで見せて、後ほど複数の数値を組み合わせたグラフなども作り込んで行くのが良いのではないかという方針が提示されていました。

**Comment by mikkame** [comment]
了解です！

**Comment by mikkame** [comment]
退院日データないかも。
発祥日ベースのグラフでいいのかな？

**Comment by mikkame** [comment]
発祥日ベースで退院者数のデータ作成しました。

@halsk できれば退院日ベースが望ましいと思われますが調整可能か聞いてもらえますか

**Comment by halsk** [comment]
こちらも都に確認中です！

**Comment by mikkame** [comment]
そもそも発祥日じゃなくて確認日な気もする

**Comment by halsk** [comment]
都の方からコメントもらいました。

> 退院者データに表示されている日付は退院日ではないので、感染者データに退院のフラグをつけること、どこかに退院者数を表示すること、としましょう。
> (詰まるところ、元データと同じ形です)
> 退院数については、カード型で表示することとし、他のデータ(検査人数、検査数、死亡者数など)と並べたサマリー表示が望ましいと言われていますので、そこに退院者数を表示する形式です。

伝わりますか？オンラインで話す方が良いかな

**Comment by halsk** [comment]
@yokinist 申し訳ないが、今のグラフは一旦落としておいてもらえますか？

**Comment by halsk** [comment]
下山さんとか宇野さんと一旦調整してもらってから取り掛かりましょう。

**Comment by yokinist** [comment]
今日は動けるの夜になるので一旦自分をアサインから外しておきました！

**Comment by ocean3fish** [comment]
#618 で陽性患者の属性に退院フラグを追加する形で対応を進めたことと、現行のデータの持ち方では退院者数を別グラフにすることは難しいため、本件は一旦クローズとさせて頂きます。
