### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowSpElder.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1040]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

flowページ（「新型コロナウイルス感染症が心配なときに」）のモバイル版のコンポーネント修正です。
i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowSpElder.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

疑問点などあれば、お気軽にこのissueにコメントしてください！

↓元デザインはこちら。
![スクリーンショット 2020-03-10 19 55 05](https://user-images.githubusercontent.com/14883063/76305740-12d49a80-6309-11ea-83d4-29bbe367b4d8.png)

**Comment by kaizumaki** [comment]
こちらに修正の要望があがっています。ご確認のほどを！
https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-597034032

**Comment by MaySoMusician** [comment]
要望（https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-597034032 ）について、今しがた追記したのでそちらもご確認ください！

**Comment by af12066** [comment]
対応しますー

**Comment by kaizumaki** [comment]
@af12066 お願いします！

**Comment by MaySoMusician** [comment]
Close per #1068 merged
