### ISSUE TITLE
多言語対応の中国語名称を正式名称に変更

### ISSUE THREAD

**Issue by Didichaoren** [tokyo-metropolitan-gov/covid19#1053]
## 改善詳細 / Details of Improvement
- 多言語の正式名称をご利用ください。

## スクリーンショット / Screenshot
<img width="987" alt="截屏2020-03-1021 46 31" src="https://user-images.githubusercontent.com/8623423/76313607-a1044d00-6318-11ea-89b6-0c0b8f0a7292.png">

## 期待する見せ方・挙動 / Expected behavior
Chinese(Taiwan) → Chinese(Traditional)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by TobyOoO** [comment]
I am here to claim that the original description of this issue, the related PR and the following discussions are severely against the Code of Conduct[1] stated by Code for Japan.

こちらで、この issue と PR で最初の説明と以下の議論が Code for Japan の行動規範[1]に大きく反していると主張しています。

    1. No one left behind
    There is no clue in anywhere of the current website saying that Chinese (Taiwan) is indicating Taiwan as a region or as a state. Instead, it simply says the version is made for people from Taiwan with Chinese language. The original description of this PR for the issue and the following discussions are making further speculations and interpretations which are against the motivation of this project. If this issue and the following PR are accepted, opinions of Taiwanese people will be neglected and far left behind, and Code of Conduct and the good intention of this project will no longer exist.

今のサイトでどこにも、中国語（台湾）が台湾を地域または国として示しているという表現はありません。 ただ、このバージョンは台湾の人々に向かって、中国語で作られていると述べています。このissue の PRで最初の説明と以下の議論は、このプロジェクトの動機に反するさらなる推測と解釈を行っています。 台湾の人々は無視されて、取り残されていう状態になります。更に、行動規範とこのプロジェクトの善意はも存在しなくなります。

    2. International
    According to the latest statistics issued by Ministry of Justice, Japan[2], the number of Taiwanese people living in Japan is ranked the fifth place of all the foreign residents. Chinese (Taiwan) is an intuitive expression for these people who are in need of the information on this website. Changing it has no any realistic meaning towards an international project, but rather the political intention of this issue and the following PR are obvious.

日本法務省が発表した最新の統計[2]によれば、日本に住んでいる台湾人の数は、すべての外国人居住者の5位におります。 在日台湾人には、このサイトに情報を必要としているこれらの人々です。なので、中国語（台湾）はもう直感的な表現があります。 こちらの issue と PR でを変更することは、国際プロジェクトに対して現実的な意味を持ちませんが、むしろこの issue と PR で政治的意図は明らかになります。

[1] https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/CODE_OF_CONDUCT.md
[2] https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00250012&tstat=000001018034&cycle=1&year=20160&month=12040606&tclass1=000001060399

**Comment by mcdmaster** [comment]
たとえば香港も繁体中文を使っているから台湾に限定するのはよろしくない、という配慮に基づく指摘ならわかるんですけど、どうもそうじゃないみたいですね。

私は古い人間なので、オープンソース・リソースは有限で、プロジェクトへの合目的性のない議論（たとえば政治的論争など）に費やせる余裕などない、よそでやれという主張をしておきます

**Comment by Didichaoren** [comment]
@TobyOoO @mcdmaster 
これがIssue側最後のコメント↓

https://en.wikipedia.org/wiki/Traditional_Chinese_characters

> **Traditional Chinese characters are used in Taiwan, Hong Kong and Macau, as well as in Overseas Chinese communities outside Southeast Asia. In contrast, Simplified Chinese characters are used in Mainland China, Malaysia and Singapore in official publications.**

↑本来Chinese(Traditional)（繁体字）は中国地方（Taiwan, Hong Kong and Macau）、海外中国語アリア利用していますから、わざと台湾のみ特別名称の繁体字を支持することは、合目的性のない議論（たとえば政治的論争など）の原因ですよ。もし本当に費やせる余裕などないだと、国際基本常識のChinese(simplified)とChinese(Traditional)を利用すれば良いでしょうね。誰も不満にさせません。

**Comment by mcdmaster** [comment]
台湾を支持するどうこうの話ではありません。そういう発言の仕方が「政治的」なのですよ。

1990 年代から、主に Solaris, AIX などの UNIX プラットフォームでは繁体字中文に zh_TW というエンコーディング識別子を割り当ててきました。
ですので、技術者の作るアーティファクトが Chinese (Taiwan) という表記をしたとしても、少なくともオープンソース・コミュニティでは違和感はありません。

あと、Wikipedia の項目名が国際標準（国際基本常識？）と言えるかどうかについては、私は否定的な立場です。
引用するなら、Wikipedia よりも ISO など国際規格団体のものを持ってきてください。

技術者の慣例で記した Chinese (Taiwan) に意義を唱えるのはまあいいとしても、台湾を支持するというありもしない言いがかりをつけたり thumbs up/down 行為を非難したりといった発言はいかにも過熱気味に見えます。Calm down されることをお勧めします

**Comment by Didichaoren** [comment]
コメントエリアは肺炎についてのジョークと差別になり、
失望しながら、本件クローズします。
