### ISSUE TITLE
トップの「最新のお知らせ」見出しの見出しレベルが `3` ではなく `2` になっている

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#1073]
## 改善詳細 / Details of Improvement
- ページタイトルがh2なので、この白いパネル内の見出しは一段下のh3になっているのが正と考えます。
※ここがh2だと、以下コンテンツのh3の見出しの親は「最新のお知らせ」になってしまい、情報構造が視覚的な意図とズレてしまうと感じます。

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-11 0 13 51](https://user-images.githubusercontent.com/17713513/76327560-825c8100-632d-11ea-8c46-204103992c32.png)

## 期待する見せ方・挙動 / Expected behavior
- `<h2 class="WhatsNew-heading">` を `<h3 class="WhatsNew-heading">` にする

## 動作環境・ブラウザ / Environment
- すべて

**Comment by mikana0918** [comment]
こちら対応させていただきたいです！

**Comment by af12066** [comment]
対応しますー
