### ISSUE TITLE
[/flow]「新型コロナウイルス感染症にかかる相談窓口について」の見出しレベルは `2` ではなく `3` のほうが正しい

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#1074]
## 改善詳細 / Details of Improvement
- 掲題通りで、ページタイトルはh2、白いパネル内の見出しはh3とするのが情報構造的に正だと考えられます

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-11 0 22 41](https://user-images.githubusercontent.com/17713513/76328407-9b196680-632e-11ea-9ee0-b421775cd60c.png)

## 期待する見せ方・挙動 / Expected behavior
- `<div class="Flow-Card">`内の`<h2>新型コロナウイルス感染症にかかる相談窓口について</h2>`を`<h3>新型コロナウイルス感染症にかかる相談窓口について</h3>`にする

## 動作環境・ブラウザ / Environment
- すべて

**Comment by mitohato** [comment]
やります🙋

**Comment by af12066** [comment]
コチラ`dev-i18n`ブランチにてflowページの体裁が変更され、その際にh3に修正されているようです
https://github.com/tokyo-metropolitan-gov/covid19/tree/dev-i18n
https://deploy-preview-822--dev-covid19-tokyo.netlify.com/

**Comment by mitohato** [comment]
そのようですね、教えてくださりありがとうございます
https://github.com/tokyo-metropolitan-gov/covid19/blob/dev-i18n/components/flow/FlowPc.vue

**Comment by magi1125** [comment]
おお、見つけきれずすいません! 確認できました。closeしますね
