### ISSUE TITLE
flowページのデザイン修正提案

### ISSUE THREAD

**Issue by lsd-design** [tokyo-metropolitan-gov/covid19#1076]
## 改善詳細 / Details of Improvement
flowページのチャートが少し理解しづらく感じたので、修正したワイヤーを作ってみました。ビジュアルデザインは行っておらず、スクショを切り貼りした程度の情報設計の案です。

受け入れていただけるようでしたら高忠実度のデザインカンプ制作を行いたいと考えております。画像はデスクトップ版のみですが、モバイル版も同様の設計にする予定です。

また、内容の齟齬などの微調整がありましたら対応します。

## 改善案
![Artboard](https://user-images.githubusercontent.com/1846447/76330448-31e72280-6331-11ea-958d-92da3bd84390.png)

## 元ページ
https://stopcovid19.metro.tokyo.lg.jp/flow

## 改善意図
セクションごとの見出しレベルとレイアウトのルールを統一することで、リズムが生まれ理解しやすくなるようにしました。タイトル→症状→出来事　という順番で整理してみました。

ご検討よろしくお願いいたします。

**Comment by halsk** [comment]
@lsd-design さん
おおおおお、素晴らしい提案をありがとうございます！
ぜひ前向きに検討したいです。ただ、今は我々、多言語化対応でいっぱいいっぱいなので、そちらが片付いたら具体的なお話をさせてください！
おまたせしてしまい申し訳ありません。

**Comment by lsd-design** [comment]
かしこまりました！頑張ってください！

**Comment by kaizumaki** [comment]
当サイトの相談フローへのナビゲーションは現在、東京都福祉保健局のページへのリンクとなっています。実際にflow.vueの中身も削除対応しましたので、関連するこちらのissueもクローズといたします。
