### ISSUE TITLE
[/parent] URLを直接表示せずに、リンク先タイトルにリンクしたほうが良さそう

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#1077]
## 改善詳細 / Details of Improvement
- /parentの「新型コロナウイルス感染症にかかる相談窓口について」がURLリンクになっているが、スクリーンリーダーでの読み上げを考慮すると、カッコ内の文字列にリンクされていたほうがよい

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-11 0 51 55](https://user-images.githubusercontent.com/17713513/76331536-a373a080-6332-11ea-9821-28bb48f197d2.png)

## 期待する見せ方・挙動 / Expected behavior
- `<a href="https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html">新型コロナウイルス感染症にかかる相談窓口について</a>` とする

## 動作環境・ブラウザ / Environment
- すべて

**Comment by sasakihajime** [comment]
項目１の感染予防・健康管理とレベル合わせて、【参考】「新型コロナウイルス感染症にかかる相談窓口について」（東京都福祉保健局）にしましょうか。
