### ISSUE TITLE
お知らせページを追加する

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#1082]
## 改善詳細 / Details of Improvement
1. 過去2ヶ月(または、100件)の「お知らせ」を表示するページ(例えば、「お知らせ一覧」)を追加する。「お知らせ一覧」については、`期待する見せ方・挙動 / Expected behavior`に記載する。
   - [data/news.json](../blob/development/data/news.json)が毎日更新されていますが、過去数日の「お知らせ」を探す術が無くなってしまうので、
1. 「最新のお知らせ」エリアに、「お知らせ一覧」へのリンクを追加する。

## 期待する見せ方・挙動 / Expected behavior

`以下のような情報を持つページを追加する。「陽性患者の属性」パネルのように各列をソート可能だと情報を探しやすいと考える。`

お知らせ一覧

日付 | 要約 | 発信元
------------ | ------------- | -------------
2020/03/09|[都の備蓄マスク20万枚を都内全区市町村へ提供](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/1007462.html)|[東京都新型コロナウイルス感染症対策本部報](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html) > [（第72報）新型コロナウイルス感染症対策に対する都内区市町村へのマスクの提供について](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/1007462.html) 
2020/03/09|[都内医療機関及び保健所等へのマスクの配布について](https://www.fukushihoken.metro.tokyo.lg.jp/oshirase/iryo/maskhaifu0306.html)|[東京都福祉保健局](https://www.fukushihoken.metro.tokyo.lg.jp/index.html) > [お知らせ](https://www.fukushihoken.metro.tokyo.lg.jp/oshirase/index.html) > [医療・保健](https://www.fukushihoken.metro.tokyo.lg.jp/oshirase/iryo/index.html) > [マスクの配布について](https://www.fukushihoken.metro.tokyo.lg.jp/oshirase/iryo/maskhaifu0306.html)

## 動作環境・ブラウザ / Environment
- All OS
- All browsers

**Comment by sugi** [comment]
こちらやります。

data/news.json をソースにするのは変わらないでしょうから、それを更新するのは別の #862 などにおまかせして、ともあれ過去のお知らせを全て残せるようにします。

**Comment by ocean3fish** [comment]
@masanori1102 @sugi 申し訳ありません、新しいコンテンツを追加する場合、関係者での検討・調整が必要になるため、実装を進めるのはお待ち頂けるでしょうか。（もしすでに着手中でしたら申し訳ありません）

**Comment by sugi** [comment]
あら？　うーん、とりあえずほぼやってしまったので、あとでパッチだけ投げておきます。

**Comment by sugi** [comment]
変更自体は #1526 にあげておきました。

**Comment by kaizumaki** [comment]
ご提案いただきありがとうございます。こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/1526#issuecomment-616268320 にコメントいたしました。なにとぞご理解のほどよろしくお願いいたします。

**Comment by kaizumaki** [comment]
都からの正式な回答がありましたので、こちらのissueはクローズさせていただきます。
