### ISSUE TITLE
「陽性患者の属性」を「陽性患者発表情報」に変更する

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#1084]
## 改善詳細 / Details of Improvement
以下の理由から、「陽性患者の属性」を「陽性患者発表情報」に変更する
1. 人に対して、属性という用語を使っているのを(私が)見た事が無い。
1. 基にしている情報で、「陽性患者発表情報」という用語を利用しているので、同じ用語を利用する。

## 期待する見せ方・挙動 / Expected behavior
「陽性患者の属性」が「陽性患者発表情報」に置き換わる

## 動作環境・ブラウザ / Environment
- All OS
- All browsers

**Comment by ocean3fish** [comment]
@masanori1102 ご提案ありがとうございます。
「属性」がどれほど一般的な用語かについては示すのが難しいですが、少なくとも人に対して使うことのある用語であることは確かですね。
例）https://www.macromill.com/research-words/attribute.html

**Comment by halsk** [comment]
こちら、都側のレビュー済のテキストなので、現行のままとさせてください。ありがとうございました。
