### ISSUE TITLE
table提供やcsv提供による、グラフのアクセシビリティへの過渡的な対応

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#1091]
## 改善詳細 / Details of Improvement
- 現在トップページで表示されているグラフはアクセシビリティ的に4つほど大きな課題があります
  1. canvasで描画されているため、スクリーンリーダーでは内容にアクセスすることができない
  2. 詳細情報を得るにはマウスオーバーorタッチ、凡例を選択して内容を変更するにはマウスクリックorタッチが必須であり、いずれもキーボードでは操作できない
  3. 棒グラフの幅が狭いため、操作を行うには非常に微細な操作が必要になる
  4. マウスオーバーで表示した詳細情報を*マウスカーソルを移動せず*に消す方法がない
    - 補足：弱視の方は画面を拡大している場合があり、マウスカーソルに視野が追従するため、読みたいところを探す過程で偶然ホバーすることがあります（[参考映像](https://www.youtube.com/watch?v=p80PJXMPIDY)）。その際にEscキーなどでホバー時の追加コンテンツを消せないと、もともと見たかった箇所がいつまでも見れないということが起きます。[WCAG2.1の1.4.13](https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/content-on-hover-or-focus.html)をご参考ください
- しかし、現在すぐにグラフの改善を検討するのは難しい状況でもあるとも理解しています
- そのため、ひとまずグラフの元となっているデータをtable要素として別途提供する、あるいはcsvとして提供するという代替手段が有効そうだと考えています
- こういったデータが提示されていれば、ユーザーはひとまず内容は取得できるようになります

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-11 3 08 57](https://user-images.githubusercontent.com/17713513/76344906-b17eec80-6345-11ea-8df2-01fbd4943fea.png)

## 期待する見せ方・挙動 / Expected behavior
- グラフの下にtable要素で組まれた元データが表示される（この表は普段は折りたたんであり、「元データを表示する」的なリンクを押すと展開される、という形でもよいと考えます）。
- または、グラフの下に元データのcsvへのリンクが表示される

## 動作環境・ブラウザ / Environment
- すべて

**Comment by mikkame** [comment]
デフォでテーブル、グラフ描画完了後グラフに差し替えにすると
テキストリーダーでも読みやすい&JSなくても読めるように思えます

**Comment by magi1125** [comment]
ご意見ありがとうございます。そういう手もありますね！
デフォはテーブルで、JSオンならグラフが出る＆テーブルは折りたたまれるが呼び出せる、だとよりナイスな気がしました（グラフを見つつ表を見て数字を拾うこともできるため）

**Comment by magi1125** [comment]
メインコンテンツにアクセス不能になっている点を鑑みてhelp wantedラベルをつけました。flowページリファクタと同レベルの重要度を持つ課題だと考えています。

**Comment by magi1125** [comment]
ちなみに、「オープンデータを入手」としてここにリンクが貼られている場合は一応アクセスすることは可能です。ただし以下の点で情報取得は難しそうと考えています。
- 一般の人が使いやすいラベルにはなっておらず、どこに情報があるかわからない可能性が高い
- csvは存在するが探しにくい（データとリソースのページに異動したあとの見出し下のリンク、または「リソースに行く」ボタンだが、気づきづらい）
- データエクスプローラーはtable要素ではなくdiv要素で出来ているため、行列の組み合わせで内容を読み取ることができない

**Comment by ocean3fish** [comment]
@KentarouTakeda さんに実装お願いできることになりました！
（なぜかアサインしようとした時にアカウント出てこないのでコメントで残しておきますー）

**Comment by KentarouTakeda** [comment]
@magi1125 
* テーブルの開閉  
    ui追加（及びそれによる翻訳）等の作業が当方のみで解決できないため対応見送りました。  
    スクリーンリーダー対策としてテーブルはDOMには残し画面外に飛ばす形としました。
* CSVダウンロード
    機能追加の適否を各所に確認する必要があると別の方にお聞きしたため対応見送りしました。
    途中まで作業した内容（ダウンロードは可・UIが仮）を #1464 に残してあります。

**Comment by magi1125** [comment]
@KentarouTakeda 状況共有ありがとうございます！なるほど、そういう確認もあるのですね。あまりそのあたり明るくなくすみません。
