### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowSp.vue

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1093]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

flowページ（「新型コロナウイルス感染症が心配なときに」）のモバイル版のコンポーネント修正です。
i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowSp.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

### 入れ子構造の修正
正しいデザインはこちらですが、

![image](https://user-images.githubusercontent.com/16509/76364242-059ac880-6368-11ea-8416-3a5f857b73d8.png)

今の `dev-i18n` ブランチではこうなっています。

![image](https://user-images.githubusercontent.com/16509/76364300-2531f100-6368-11ea-959e-e9a4672049fb.png)

合わせて修正いただければと思います。

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by af12066** [comment]
対応しますー

**Comment by halsk** [comment]
ありがとうございます！助かります！

**Comment by af12066** [comment]
コチラはFigmaに反映されていましたでしょうか?

**Comment by forestgtree** [comment]
@af12066 申し訳ありません。対応いただきありがとうございます 🙇‍♂️

flowのデザインに関しては、FigmaではなくAdobe XDのデザイン資源がございますが
パスワード認証を設けて管理させていただいております。

現在、公開されている状態に見栄えに合わせていただければと思います。
https://stopcovid19.metro.tokyo.lg.jp/flow/
