### ISSUE TITLE
行動原則への"性別"の追加

### ISSUE THREAD

**Issue by showyou** [tokyo-metropolitan-gov/covid19#1099]
## 改善詳細 / Details of Improvement
- ものすごく重箱の隅かもしれませんが、githubの"行動原則"の"No one left behind"の部分に"国籍や年齢、障害の有無に"だけでなく、"国籍や年齢、性別、障害の有無に"といった形で性別を加えるといいかと感じました。

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by halsk** [comment]
ご提案ありがとうございます。

こちらの行動原則は、どちらかというと、「どんなサイトを目指すか」のための行動原則であり、開発者間のコミュニケーション等には言及しておりません。
サイトの見え方として、外国人（多言語化）や子供（やさしい日本語）といった方々にも対応してようという意味合いで、No one left behind になっています。
ウェブサイト自体、特に性差による影響はそもそも無いものですから、わざわざ明記しなくてもいまのままでも良いかなと思いましたがいかがでしょうか。

開発側の環境ではもちろん、参加する皆が気持ちよくコミュニケーションができる必要がありますので、男女関係なくリスペクトされるべきです。そちらについては、こちらの Code for Japan の Code of Conduct にかかれています。
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/CONTRIBUTING.md#%E5%8F%82%E5%8A%A0%E3%81%AB%E3%81%82%E3%81%9F%E3%81%A3%E3%81%A6

他の言語には入っているというご指摘もありましたが、とりあえずスタンスとしては以上です。

**Comment by showyou** [comment]
ご回答頂きありがとうございます。
自分も特に深くは考えておらず、"国籍や年齢、障害の有無にかかわらず"と並んでいたので、その中で性別への言及が無いのはなぜか？ぐらいの認識でおりました。
ですのでWebサイトに性差が無いようでしたら、無くて大丈夫かと思います。

**Comment by halsk** [comment]
ありがとうございます。ではクローズいたします。
