### ISSUE TITLE
JSONファイルとVueの間に中間層を設ける

### ISSUE THREAD

**Issue by hikyaru-suzuki** [tokyo-metropolitan-gov/covid19#1100]
## 改善詳細 / Details of Improvement
- i18n化や本プロジェクトの拡大に伴ってよりコードの脱日本語化が重要になってきつつあるため、コード上から可能な限り日本語を排除する
  - 現在dataディレクトリ配下にあるJSONファイルを元にページを生成しているが、Vue側ではこれを直接読み込んでいるためキー名などがコード上に出現しているのでそれを排除する
  - jsonデータが日本語なのは仕方がないのでそれをコードへ変換する中間層を設ける
  - **i18nブランチでも割と日本語キーに依存していますし、マッピングの作成コストを考えるとこちらを修正するのは難しそうな気がします**
- JSONからデータを取得する中間層を設けることで型推論を可能とし、コードの保守性を上げる
  - `pages/index.vue`では直接JSONからデータを取得しており型推論が効いていない
  - Vueとしてはリソースの実態をあまり意識したくない
  - 関連
    - https://github.com/tokyo-metropolitan-gov/covid19/issues/621
    - https://github.com/tokyo-metropolitan-gov/covid19/pull/698
    - https://github.com/tokyo-metropolitan-gov/covid19/issues/640

## 期待する見せ方・挙動 / Expected behavior
例：Repositoryパターンなどを用いて実データの実態を意識しないようにする

2つめがメインです。皆様のご意見をお待ちしております
今回の目標的にデータの実態とコードを分離できれば複雑なアーキテクチャでなくてもいいと考えております

**Comment by mcdmaster** [comment]
大まかなところで、一つ確認させてください。

たとえばのアプローチないしはとっかかりとしては、`pages/index.vue` で以下のような部分
```
    <static-info
      class="mb-4"
      :url="localePath('/flow')"
      :text="$t('自分や家族の症状に不安や心配があればまずは電話相談をどうぞ')"
      :btn-text="$t('相談の手順を見る')"
    />
```
を、下記のように書き換え、

`    <static-info class="mb-4" v-bind="staticItem" />`

かつ、以下のような形で `data()` ブロックに出すことを想定していますでしょうか？
```
    const staticItem = (url, text, btnText) => {
      return {
        url: localePath('/flow'),
        text: this.$t('自分や家族の症状に不安や心配があればまずは電話相談をどうぞ'),
        btnText: this.$t('相談の手順を見る')
      }
    }
```
だとしたら、
* VUE のメンテナンス性が向上する
* Props の設定値を別管理できる

といったメリットがあると思われます

**Comment by mcdmaster** [comment]
いろいろ見ていたら、 #774 の対応でおおよそ解決が進んでいますね。
Duplicate Issue にされるか否かのご判断をお任せします

**Comment by hikyaru-suzuki** [comment]
@mcdmaster 
返信遅れて申し訳ありません
いま一通りみたのですが、現在の実装でも未だ解決されていなさそうです
例えば[この部分](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/pages/index.vue#L34)や[この部分](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/pages/index.vue#L63)、jsonファイルを直接インポートしてしまっているのでデータを参照するときに型推論が出来ていません。また、データリソースが変更された際には(例えばjsonではなく何らかの事情でcsvやAPIになった場合など）Vueファイルを直接修正する必要があります。本来VueはUIフレームワークですのでそのあたりのことを気にしたくないはずです

これの解決策としてdata.jsonをインポートするのではなく、Vue側ではデータリソースにアクセスするための中間層であるDataRepositoryなどをimportし、`DataRepository.getDischargesSummary().data`のような形でアクセスすることで、TypeScriptの型推論を活かしつつデータリソースの実装をVueが気にする必要ないということが実現できるかと思います

**Comment by halsk** [comment]
確かに、そうですね。データ層に直接アクセスしている部分は、中間層経由にしたほうが責務が明確になり好ましいと思います。
なるべくシンプルにしておきたいですが、実装のアイデアありますでしょうか？リファレンス実装を示すことは可能ですか？

**Comment by hikyaru-suzuki** [comment]
@halsk 
アイデアとしては↑のような一般的なRepositoryパターンが良いかなと思っています
簡単な例ですが（importなど色々省略）

`@/pages/index.vue`
```vue
<template>
// summaryを使って描画する処理
</template>

<script>
export default {
  data() {
    return {
      summary: Singleton.data.summary // 型推論が効く
    }
  }
}
</script>
```
`@/utils/Singleton.ts`
```ts
export class Singleton {
  // DataRepositoryを使ってリソースを取得し、staticプロパティとして保持しておく
}
```
`@/utils/types.ts`
```ts
export type DataType = {
  summary: string // jsonファイルの型定義
}
```
`@/utils/Repositories/BaseRepository.ts`
```ts
export abstract class BaseRepository<T> {
  abstract getRawData(): T // 型がついた生のデータを返す
}
```
`@utils/Repositories/DataRepository.ts`
```ts
export class DataRepository extends BaseRepository<DataType> {
  getRawData(): DataType {} // data.jsonをパースして型をつけ、その実態を返す処理
}
```

データは確実に単方向で流れ、いわゆるマスターデータのようなデータ()もというルールにするならSingletonで持たなくてもいいかもです
もうちょっと具体的な例が必要なら実装します！

**Comment by hikyaru-suzuki** [comment]
@halsk 
アイデアとしては↑のような一般的なRepositoryパターンが良いかなと思っています
簡単な例ですが（importなど色々省略）

`@/pages/index.vue`
```vue
<template>
// summaryを使って描画する処理
</template>

<script>
export default {
  data() {
    return {
      summary: DataStore.data.summary // 型推論が効く
    }
  }
}
</script>
```
`@/utils/types.ts`
```ts
export type DataType = {
  summary: string // jsonファイルの型定義
}
```
`@/utils/Registry.ts`
```ts
export class DataStore {
  static readonly data: DataType
  constructor() {
    this.data = DataRepository.getRawData()
  }
}
```
`@/utils/Repositories/BaseRepository.ts`
```ts
export abstract class BaseRepository<T> {
  abstract getRawData(): T // 型がついた生のデータを返す
}
```
`@utils/Repositories/DataRepository.ts`
```ts
export class DataRepository extends BaseRepository<DataType> {
  getRawData(): DataType {} // data.jsonをパースして型をつけ、その実態を返す処理
}
```

データは確実に単方向で流れ、(data.jsonのような)いわゆるマスターデータもDependencyInjectionで流すというルールにするならDataStoreで持たなくてもいいかもです。また、data.jsonが動的に更新される可能性があるならこの持ち方だとダメで、基本的にRepositoryは一度取得したらそのデータをキャッシュして2度目以降はそれを利用し、動的に更新された時用に強制的にdata.json読み取る用のメソッドを実装する感じになりそうですね
もうちょっと具体的な例が必要なら実装します！

**Comment by halsk** [comment]
ありがとうございます。型が効くのはいいですね。
他のサイトへの展開も、DataRepository だけ改修すれば良いのでやりやすくなる気はします。
data.json は、少なくとも東京都のサイトでは今の所動的に読み込む予定はありません。
そもそも今は generate した静的ファイルをサイトでホストしているので、データが更新されるときには generate コマンドが再度走ります。
ですので、今の考え方で対応できそうに思えます。

**Comment by mcdmaster** [comment]
あ、レスポンスをすっかり見落としていました。申し訳ありません。
フォローアップをいただき、ありがとうございます！
c++ の auto 属性＋テンプレートとか、あれこれ考えた末に放ったらかしになってしまっていました(汗

**Comment by hikyaru-suzuki** [comment]
@halsk 
こちら、今週目処に実装します！

@mcdmaster 
https://github.com/tokyo-metropolitan-gov/covid19/pull/1468 のcloseを外していただけますと:pray:

**Comment by mcdmaster** [comment]
@hikyaru-suzuki 外しました。メンションありがとうございます！
