### ISSUE TITLE
[i18n] Put on Tokyo Health Care Information Center telephone number for foreigner user 

### ISSUE THREAD

**Issue by PichuChen** [tokyo-metropolitan-gov/covid19#1101]
## 改善詳細 / Details of Improvement
外国人利用者のために東京医療情報センターの電話番号をつける
- The telephone number for "新型コロナ 受診相談窓口" is Japanese only (03-5320-4592)
- I found a telephone number form U.S. embassy in Japan (03-5285-8181)
- This telephone number supports in English, Chinese, Korean, Spanish and Thai

Ref Link: https://jp.usembassy.gov/covid-19-information/
https://japan2.usembassy.gov/pdfs/covid19-what-to-do-e.pdf

## スクリーンショット / Screenshot

![螢幕快照 0002-03-11 11 01 45](https://user-images.githubusercontent.com/600238/76378250-f3c91d80-6387-11ea-82c6-3df8acde97b1.png)

![螢幕快照 0002-03-11 11 02 59](https://user-images.githubusercontent.com/600238/76378246-f1ff5a00-6387-11ea-9628-4a957416682e.png)

**Comment by mikkame** [comment]
Hi.
Thanks your issue.

I ordered confirmation to stakeholders
