### ISSUE TITLE
サイドバー内ソーシャルアカウントのリンク範囲が広い

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1106]
## 起こっている問題 / The Problem
- サイドバー内ソーシャルアカウントのリンク範囲が右にはみ出している

## スクリーンショット / Screenshot

<img width="228" alt="スクリーンショット 2020-03-11 13 49 45" src="https://user-images.githubusercontent.com/8909592/76383468-4c57e500-639f-11ea-9d80-f504a57da66a.png">

## 期待する見せ方・挙動 / Expected Behavior
- 画像の真上のみリンクが効く

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイドバーを見る

## 動作環境・ブラウザ / Environment
すべて

**Comment by hr20k** [comment]
誰も対応されていなければ対応させて頂きます。

**Comment by amotarao** [comment]
@hr20k ありがとうございますー！
