### ISSUE TITLE
多言語の注釈

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1115]
多言語対応にあたり、
都内の最新動向　最終更新日時の左（スマホ版だと下）に
下記の注釈を入れていただけますでしょうか。よろしくお願いいたします。

This is a provisional translation. Please be aware that there may be mistranslations.
（参考　日本語）この翻訳は、仮訳になります。一部、誤訳の可能性もありますが、ご容赦ください。

**Comment by kaizumaki** [comment]
@NaoyaShimizzz 最終更新日時の「右」ですかね？
![スクリーンショット 2020-03-11 16 02 13](https://user-images.githubusercontent.com/14883063/76390990-c98c5580-63b1-11ea-8b13-ff9d5c80e2f4.png)

**Comment by ocean3fish** [comment]
@kaizumaki はい、正しくは「右」とのことです！
（@NaoyaShimizzz MTG中につき代筆を依頼されました）

**Comment by halsk** [comment]
追記です。日本語と英語以外の言語の場合も、取り急ぎ英語のままで注釈を載せていただけますでしょうか。

**Comment by kaizumaki** [comment]
@MaySoMusician すみません！こちらのissueは `dev-i18n` ブランチでの作業となりますよね？

**Comment by kikd** [comment]
作業ブランチが決まったら対応させてください！

**Comment by kaizumaki** [comment]
@kikd ありがとうございます！ `dev-i18n` ブランチでお願いします！

**Comment by MaySoMusician** [comment]
返信遅れました
`dev-i18n` で大丈夫です！

**Comment by kikd** [comment]
ひとまず注釈を追加してみました。

注釈は次のスタイルを当てています。
```
.annotation {  
  font-size: 0.75rem;  
  color: $gray-3;  
  margin: 0 0 0 auto;  
}  
```

日本語の場合は時刻の右に表示されますが、
英語と英語以外の場合、スペースの問題かわかりませんが時刻の右下に表示されてしまいます。

日本語
![日本語](https://user-images.githubusercontent.com/5682821/76409795-3f081e00-63d2-11ea-88f7-783fe7be205b.png)

やさしいにほんご
![やさしい日本語](https://user-images.githubusercontent.com/5682821/76410418-3bc16200-63d3-11ea-8123-5f324c2ddc3e.png)

英語
![英語](https://user-images.githubusercontent.com/5682821/76409835-4d563a00-63d2-11ea-9318-49cf840bb1b3.png)

いいアイデアありましたら知恵を貸してくださるとうれしいです。

**Comment by MaySoMusician** [comment]
この注釈、日本語の場合は表示しなくても良いのではないでしょうか
This is a provisional translation.ですが日本語は原文でありtranslationではないですから。

**Comment by kaizumaki** [comment]
@MaySoMusician 日本語ページは不要みたいです。この場合、i18n的にはどのように書けばよいですか？

**Comment by MaySoMusician** [comment]
```vue
<div class="annotation" v-if="$i18n.locale !== 'ja">
  <span class="ml-4">{{ $t('注釈') }} </span>
</div>
```
これでひとまず日本語の場合は消えるはずです

**Comment by kaizumaki** [comment]
@MaySoMusician ありがとうございます！
@kikd 修正後、プッシュしてもらえますか？

**Comment by kaizumaki** [comment]
やさしいにほんごでも必要なんですかね？ @NaoyaShimizzz

**Comment by kikd** [comment]
@MaySoMusician 
コメントありがとうございます。

@kaizumaki 
やさしいにほんごでの表示有無が決まったらプッシュしようと思います。

**Comment by NaoyaShimizzz** [comment]
ありがとうございます。やさしいにほんごでは、不要です。よろしくお願いします。

**Comment by kikd** [comment]
修正したものPushしました。
