### ISSUE TITLE
[i18n] 検査陽性者の状況 英語表示時のレイアウト崩れの修正

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1117]
**こちらのissueは dev-i18n ブランチですすめます。プルリク先もこちらのブランチとなります。**

## 改善詳細 / Details of Improvement
- `検査陽性者の状況` を英語表記にしたときに、レイアウトが崩れてしまうので崩れないように修正したい。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/76395731-4ff96500-63bb-11ea-946b-41c5c21b2f72.png)

## 期待する見せ方・挙動 / Expected behavior
- 該当ファイルは ConfirmedCasesTable.vue 

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shgtkshruch** [comment]
こちら対応します〜。

**Comment by kaizumaki** [comment]
@shgtkshruch お願いします！
