### ISSUE TITLE
[/flow][i18n] デスクトップ版flowページのスタイル調整

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1123]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

flowページ（「新型コロナウイルス感染症が心配なときに」）のデスクトップ版のスタイル修正です。
- サイドナビ下部にある言語切り替えセレクトボックスで言語を切り替えながら、表示が不自然なところを調整してください（特に英語で崩れます）。
- ソース上でi18n化したところはいじらないように気をつけてください（ `<br />` を追加したりしない）。
- HTMLタグの整合性については、とりあえずこのissueでは気にせずに、cssの調整をすすめてください（後日、別issueでアクセシビリティチェックをします）。
- デザインの再現性はベストエフォートでよいです。

修正するファイルは `components/flow/FlowPc.vue` およびその子コンポーネントです。

疑問点などあれば、お気軽にこのissueにコメントしてください！

↓元デザインはこちら。
https://stopcovid19.metro.tokyo.lg.jp/flow

**Comment by NumLocker-Japan** [comment]
2点質問があります。
- 「サイドナビ下部にある言語切り替えセレクトボックス」とありますが、画像上部の部分ということで合っていますか？

![image](https://user-images.githubusercontent.com/46442187/76403997-1c253c00-63c9-11ea-96e2-cb0d5c37fd68.png)

- デザインですが、htmlタグのlang属性ごとにcssを当てていくという認識で合っていますでしょうか

**Comment by kaizumaki** [comment]
`dev-i18n` ブランチの最新を引っ張ってきてもらうと、サイドナビにセレクトボックスが表示されると思います。
cssは、言語で分けず共通です。なので、いろいろ切り替えてもらって、妥協できる範囲で調整をお願いしたいです 🙇‍♀

**Comment by NumLocker-Japan** [comment]
すいません。更新忘れてました。セレクトボックス表示できました。
cssの方も了解しました。ありがとうございます。

**Comment by kaizumaki** [comment]
@NumLocker-Japan 作業の方お願いしても大丈夫ですか？

**Comment by NumLocker-Japan** [comment]
分かりました。引き受けさせてもらいます。

**Comment by kaizumaki** [comment]
@NumLocker-Japan ありがとうございます！よろしくお願いします！

**Comment by kebhr** [comment]
`components/flow` 以下のコンポーネントには触っていませんが、`/flow` に関わるPRを作成しました。
#1130

**Comment by NumLocker-Japan** [comment]
了解です。ありがとうございます。

**Comment by kaizumaki** [comment]
@NumLocker-Japan #902 を `dev-i18n` ブランチにマージしましたので、最新のものを引っ張ってきてください！

**Comment by NumLocker-Japan** [comment]
分かりました。ありがとうございます！

**Comment by NumLocker-Japan** [comment]
とりあえずPCの方は完成しました。スマホ版の方で全体的にスタイルが崩れているようですが、こちらは別issueでしょうか？

**Comment by kaizumaki** [comment]
@NumLocker-Japan ありがとうございます！スマホ版は別issueでやってて、すでにマージされました。何か気づいた点があればissue立ててもらえますか？

**Comment by kaizumaki** [comment]
@NumLocker-Japan このissueのプルリクは、向き先を `development` にしてもらえますか。

**Comment by NumLocker-Japan** [comment]
分かりました。``development`` の方にプルリクさせてもらいます。

**Comment by NumLocker-Japan** [comment]
エラーが出てしまったので急ぎで修正入れます。
