### ISSUE TITLE
[i18n] 訳が揃っていない言語は選択肢から抜いておく

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1126]
## 改善詳細 / Details of Improvement
今ある言語セレクタの中で、ポルトガル語以外は全部翻訳が揃っている感じでしょうか。
その場合、ポルトガル語だけは選択肢から除いてもらえますでしょうか。

**Comment by kaizumaki** [comment]
`dev-i18n` ブランチで作業のほどお願いします。

**Comment by kebhr** [comment]
翻訳シートを見ると、韓国語が2行、やさしい日本語が1行、未翻訳が残っているようですが、どうしましょうか?

**Comment by halsk** [comment]
未反映分を後で反映させる必要があると思いますので、それまでに反映させましょう！

**Comment by halsk** [comment]
ポルトガル語のみ外しましょう！どなたか対応できますか？

**Comment by kebhr** [comment]
対応可能ですー

**Comment by kaizumaki** [comment]
@kebhr ありがとうございます！

**Comment by kebhr** [comment]
@halsk @kaizumaki 
#822 がMergeされたので、PR先は`development` で大丈夫ですか?

**Comment by kaizumaki** [comment]
@kebhr ですね。 `development` でお願いします。

**Comment by halsk** [comment]
すみません。こちら、「やさしい日本語」だと文字が長くなりコンポーネントが崩れるという報告があり、Reopen させていただきました。
コンポーネントを修正するまで、「やさしい日本語」は外してきたいと思います。
セレクトボックスから、「やさしい日本語」も外していただけますでしょうか。
https://github.com/tokyo-metropolitan-gov/covid19/issues/872#issuecomment-597662957

**Comment by kebhr** [comment]
@halsk 
対応します〜
