### ISSUE TITLE
[i18n] リンクのスタイルが意図せず書き換わる

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#1129]
## 起こっている問題 / The Problem
- 以下のページを開いた後に 「新型コロナウイルス感染症が心配なときに」（以下`/flow`） を開くとリンク部分のスタイルが変わる
  - お子様をお持ちの皆様へ （以下`/parent`）
  - 企業の皆様・はたらく皆様へ（以下 `/worker`）
  - 当サイトについて（以下 `/about`）

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/42484226/76409636-fe100980-63d1-11ea-8685-596fe39688f3.png)
![image](https://user-images.githubusercontent.com/42484226/76409839-4e876700-63d2-11ea-9061-b6cc6b6ab7cf.png)

## 期待する見せ方・挙動 / Expected Behavior
- 各コンポーネントで定義したスタイルで表示される
![image](https://user-images.githubusercontent.com/42484226/76409870-5a732900-63d2-11ea-958f-1f77d9f0f943.png)
![image](https://user-images.githubusercontent.com/42484226/76409691-12540680-63d2-11ea-8444-f2425e63bfb3.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. `dev-i18n`をビルドする
2. `/flow` を開く
3. `/parent`, `/worker`, `/about` のどれかを開く
4. 再び`/flow`を開く

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kebhr** [comment]
原因がわかっている為、修正PRを送ります。

**Comment by kaizumaki** [comment]
@kebhr 対応ありがとうございます！いま #1123 で作業中のものがあるので、 @kebhr さんがプルリク出したら、 #1123 でメンションしてもらえますか？

**Comment by kebhr** [comment]
@kaizumaki 了解しました！

**Comment by amotarao** [comment]
#899 と同じ現象と思われますー

**Comment by kebhr** [comment]
@amotarao 
既出でしたか！
#902 で修正していただいているので、こちらCloseしますね。

**Comment by kaizumaki** [comment]
@amotarao @kebhr たしかに、 #902 のほうがよさそうなので、そちらをマージする方向にしますね。
