### ISSUE TITLE
サイドバーのgithubのリンクのみ別タブで開かないです

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#1145]
## 起こっている問題 / The Problem
- 表題の通り

## 期待する見せ方・挙動 / Expected Behavior
- 特別な意図がない限り別タブで開きたいです

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイドバーのオクトキャットアイコンを押す

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ixap2i** [comment]
対応します。
