### ISSUE TITLE
キーボードフォーカス時にoutlineが表示されるようにする

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#1147]
## 改善詳細 / Details of Improvement
- 以下の箇所でoutlineが0またはnoneと指定されているため、キーボードフォーカス時にフォーカスリングが表示されず、フォーカス位置がわからないため事実上操作不能になります。
- これに類する状態を改善することで、キーボードによる操作が可能になります。
  - サイドメニューのリンク（`.v-list-item`に`outline: 0`の指定あり）
  - サイドメニューの言語選択（`.SelectLanguage-Menu select:focus`に`outline: none`の指定あり）
  - グラフの日別と累計を切り替えるボタン（`.v-btn`に`outline: 0`の指定あり）
- 参考として、[WCAGの2.4.7](https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html)でも達成基準として示されています

## 期待する見せ方・挙動 / Expected behavior
- CSS内から`outline:none`や`outline:0`の指定をすべて削除することでこの問題は解消します。

## 本来の姿の例
![スクリーンショット 2020-03-11 23 38 52](https://user-images.githubusercontent.com/17713513/76428905-a41f3c00-63f1-11ea-9839-a8f383a8a4fd.png)
![スクリーンショット 2020-03-11 23 39 25](https://user-images.githubusercontent.com/17713513/76428910-a5506900-63f1-11ea-9408-95e9c5526c21.png)
![スクリーンショット 2020-03-11 23 39 46](https://user-images.githubusercontent.com/17713513/76428914-a5e8ff80-63f1-11ea-97d1-e5b5e053fed6.png)

## 動作環境・ブラウザ / Environment
- すべて

**Comment by TM82** [comment]
こちら初めてですが対応させていただきます。

**Comment by TM82** [comment]
すみません、不慮の事故でoriginをforce_pushしてしまったので再度PR立て直します
