### ISSUE TITLE
東京都消費生活部の消費者への注意喚起ページをサイドバーに追加したい

### ISSUE THREAD

**Issue by KantaSunaga** [tokyo-metropolitan-gov/covid19#1149]
## 改善詳細 / Details of Improvement

東京都消費生活部が消費者にマスクや買い占め、便乗詐欺に関する注意情報を発信しているのでそれをサイドバーに追加したいす
https://www.shouhiseikatu.metro.tokyo.jp/etc/covid19/info20200309.html

## スクリーンショット / Screenshot

![スクリーンショット_2020-03-11_23_49_13](https://user-images.githubusercontent.com/20673894/76429921-0dec1580-63f3-11ea-8284-b0bb880156b7.png)

## 期待する見せ方・挙動 / Expected behavior
外部サイトに遷移します

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kenmori** [comment]
自分やります！

**Comment by halsk** [comment]
ご提案ありがとうございます！
今後のコンテンツ追加の参考とさせていただきます。
