### ISSUE TITLE
死亡者データのカードを作る

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#115]
データ自体は JSON にあるのかな？ @yokinist さんわかる？
![image](https://user-images.githubusercontent.com/16509/75636121-6129cf80-5c5f-11ea-91be-b863d4081a4e.png)

**Comment by yokinist** [comment]
@halsk シェアポイントのデータをみる限りは東京都患者発生発表数の備考に死亡があるのが唯一の手がかりですかね、いまのところ1人だけですが

**Comment by yokinist** [comment]
一旦ある前提で進めます
