### ISSUE TITLE
ページ内のランドマークを改善しスクリーンリーダーのアクセシビリティを向上する

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#1159]
## 改善詳細 / Details of Improvement
- ページ内で適切に`header`,`nav`,`main`,`footer`といった要素を使用することで、スクリーンリーダーユーザーは該当の要素（≒ランドマーク）にジャンプする機能が使えるようになります（[参考記事](https://website-usability.info/2011/07/entry_110712.html)）。
  - スクリーンリーダーはページ内を線形に読み上げていくため、不要なナビゲーションを飛ばしてメインコンテンツに行けたり、逆にコンテンツからナビゲーションにすぐジャンプしたり、といった機能が使えることは、効率的な閲覧において重要です。
- 現在のサイトでは以下の状態です。
  - header要素：なし
  - nav要素：なし
  - main要素：なし
  - footer要素：`.DataView-Inner`内の最下部にあるが、ランドマークとして機能しない
    - ページ内に複数存在するが、`aria-label`等でユニークなラベルがついていないため、見分けられない。また仮に見分けられたとしてもランドマークとしては有用ではない

## 期待する見せ方・挙動 / Expected behavior
- `.SideNavigation-HeadingContainer`を`header`要素で包む
- `v-list v-sheet v-sheet--tile theme--light v-list--flat`となっている左ナビと`.SideNavigation-LanguageMenu`をまとめてひとつの`nav`要素で包む
- `.mainContainer`を`main`要素で包む
- `.SideNavigation-Footer`を`footer`要素で包む
- `.DataView-Inner`内の最下部にある`footer`要素は`div`要素に置き換える

なおスマホ幅の場合はメニューの構造的に難しい（メニュー呼び出しのボタンとメニュー本体が離れた位置にある）ため、ひとまず`.mainContainer`を`main`要素で包む点のみ実装できれば、それだけでも有意だと考えます。

## 動作環境・ブラウザ / Environment
- すべて

**Comment by af12066** [comment]
対応いたしますー
