### ISSUE TITLE
感染者数のカードをグラフに

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#116]
今の、「本日の感染者35 人」というカードは、こちらの形式に差し替える
![image](https://user-images.githubusercontent.com/16509/75636172-d85f6380-5c5f-11ea-8b6f-805b8c6ad1e6.png)

**Comment by yokinist** [comment]
これは簡単にはいかなそう、もう少しデータいじくりまわしてなんとかこの形で算出してみるようにしてます・・

**Comment by halsk** [comment]
そうなんすね。

> これは簡単にはいかなそう、もう少しデータいじくりまわしてなんとかこの形で算出してみるようにしてます・・

そうなんですね。データ形式の問題ですか？

**Comment by mikkame** [comment]
#130 に感染者小計いれてあります

**Comment by halsk** [comment]
ついでに、「感染者数」の文言を「陽性患者発表者数（累計）」に変更してください

**Comment by halsk** [comment]
あ、すみません。文言については都庁で最終確認中だそうです。とりあえず現状ままでも良いです

**Comment by yokinist** [comment]
@mikkame 小計ってどこから確認できますか？

**Comment by yokinist** [comment]
`date/data.json` をみてますが `リリース日, date, 曜日, w, 居住地, 年代, 性別, 属性, 備考, 補足` までは確認できています

**Comment by mikkame** [comment]
patients_summary
というのが別枠です

**Comment by halsk** [comment]
これはクローズしても良いのかな？

**Comment by mikkame** [comment]
大丈夫です！
