### ISSUE TITLE
英語表示でも文字がかぶらない程度の表示スタイル変更

### ISSUE THREAD

**Issue by showyou** [tokyo-metropolitan-gov/covid19#1169]
## 改善詳細 / Details of Improvement
- 自分が使っている時みたいに、画面の一部をTwitterクライアントの為に空けて、残り部分をブラウザEnglishで表示した時に、文字がかぶってしまう項目があります。
どの辺まで画面幅を許容するかにも依ると思うのですが、Styleを直して被らなくなれば、より見やすくなると思います。

## スクリーンショット / Screenshot

<img width="384" alt="screen1" src="https://user-images.githubusercontent.com/18357/76441808-5b707e80-6403-11ea-9d39-6daab301cd2c.png">
<img width="362" alt="screen2" src="https://user-images.githubusercontent.com/18357/76441792-590e2480-6403-11ea-9895-2a669aeeac55.png">

## 期待する見せ方・挙動 / Expected behavior
- 1枚目ならconfirmedとcaseの間で折り返すように設定すれば被らなくなります。
- 2枚目に関してはActual valueの行を折り返すようにしないといけません。

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by mikkame** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/1151
こちらで対応中のようです

**Comment by showyou** [comment]
大変失礼いたしました。

**Comment by mikkame** [comment]
duplicate to #1146
