### ISSUE TITLE
グラフは、以下の並びに切り替える

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#117]
![image](https://user-images.githubusercontent.com/16509/75636202-152b5a80-5c60-11ea-9b09-11bbae320fd8.png)
![image](https://user-images.githubusercontent.com/16509/75636210-1fe5ef80-5c60-11ea-8612-e3aa4d728844.png)

**Comment by mikkame** [comment]
並び替えはやりました
