### ISSUE TITLE
ブラウザ設定言語が日本語以外で、初回のみ言語選択の動作がおかしくなる

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1175]
## 起こっている問題 / The Problem
- ブラウザ設定言語が日本語以外で、初回のみ言語選択の動作がおかしくなる
- https://stg-covid19-tokyo.netlify.com/ で再現

## スクリーンショット / Screenshot

![image](https://i.gyazo.com/cb8887022713c6ea13d550419780ed81.gif)

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to Reproduce

@sugi 氏により、[こちら](https://github.com/tokyo-metropolitan-gov/covid19/pull/854#issuecomment-597771222)にて報告あり。

develop にマージされたので試してみたんですが、以下の条件で切替時におかしくなります。

ブラウザの言語設定が日本語以外(例えば英語)である
まだサイトにアクセスしていない (言語設定 cookie を持っていない)
この状態でアクセスしてから言語を切り替えると、例えば /ko/en などのパスに飛んでしまって、ページが表示できません。
一度切り替えると cookie がセットされるので。 URL を削ってトップに行ったりすれば直りますが、初回がおかしいので直したほうが良いかと思われます。

## 動作環境・ブラウザ / Environment
- macOS Mojave,言語を英語にした Chrome のプライベートモードで再現しました。

**Comment by halsk** [comment]
言語設定が英語の場合にデフォルトのURLが
`https://stg-covid19-tokyo.netlify.com/en`
などになってますね。
`https://stg-covid19-tokyo.netlify.com/en/`
になってくれれば解決なのですが

**Comment by shgtkshruch** [comment]
こちらの #1178 で取り急ぎ修正してみました。

**Comment by halsk** [comment]
> こちらの #1178 で取り急ぎ修正してみました。

早速ありがとうございます！review コメントしましたが、確かにこれだとバグ自体は解消されますが、他のページを見ている時に翻訳すると index に戻されてしまいますね。

**Comment by halsk** [comment]
すんごく汚いですが、#1180 で一時しのぎをしました。
staging/master のみ適用し、`development` や `i18n` ブランチには適用しません
どなたかちゃんとした修正をいただければ助かります！

**Comment by himatani** [comment]
ご対応ありがとうございます。改良版をただいま実装して検証中です。

**Comment by MaySoMusician** [comment]
これたぶん、`$root.$i18n.locale`に代入するだけで言語切り替えできる気がする
https://kazupon.github.io/vue-i18n/guide/locale.html

**Comment by himatani** [comment]
developからブランチ切ってPR出します。

**Comment by himatani** [comment]
言語ごとにURLに含めている文字列は、意図的にそうしてる感じですかね
すべての言語でURLはそのままでよいのであれば

`nuxt.config.js` のi18n設定でstrategyを `no_prefix` にした上で
`$root.$i18n.locale` にセットしてあげるだけでよさそう

**Comment by himatani** [comment]
ひとまず私の方でPRつくりますので方針が違えばリジェクトしてください

**Comment by halsk** [comment]
なるほど！！
今日リリースはしてしまったので、permalink が気になります。これ切り替えたあと /en とかのURLにアクセスすると、404になりますか？

**Comment by himatani** [comment]
ですね…

URLに言語設定が含まれていれば、設定なしURLにリダイレクトする必要があります。
fx. /en/parent -> /parent (english)

が、後から変更するのはよろしくないですね。。

**Comment by halsk** [comment]
Twitterなどからシェアされた場合、そのままの言語で表示される方が良いかもしれませんよね。
なかなか悩ましいですね。

**Comment by himatani** [comment]
1. URLに言語設定が含まれていれば、設定なしURLにリダイレクト
2. 現状のままURLに言語設定が含め、記述方法だけ改善

のどちらかかですよね。2. の方もPRだけつくっておきますね。

**Comment by himatani** [comment]
@halsk ちょっとだけ綺麗にしました！ https://github.com/tokyo-metropolitan-gov/covid19/pull/1274

> 言語設定が英語の場合にデフォルトのURLが
> https://stg-covid19-tokyo.netlify.com/en
> などになってますね。
> https://stg-covid19-tokyo.netlify.com/en/
> になってくれれば解決なのですが

こちらも含めて修正しておきました。
現時点ではどちらのURLも使用できますので404エラーになることはなさそうですが
表記揺れを防ぐため、別途リダイレクト処理を入れた方がよいかもしれません。

**Comment by himatani** [comment]
@halsk ちょっとだけ綺麗にしました！ https://github.com/tokyo-metropolitan-gov/covid19/pull/1274

> 言語設定が英語の場合にデフォルトのURLが
> https://stg-covid19-tokyo.netlify.com/en
> などになってますね。
> https://stg-covid19-tokyo.netlify.com/en/
> になってくれれば解決なのですが

こちらも含めて修正しておきました。
現時点ではどちらのURLも使用できますので404エラーになることはなさそうですが
表記揺れを防ぐため、別途リダイレクト処理を入れた方がよいです。

ただ、ブラウザのリロードやサイト内のリンクによって / 付きにリダイレクトされるので
どういった方針で修正を進めていくのか検討しなければなりません。

**Comment by himatani** [comment]
@halsk ちょっとだけ綺麗にしました！ https://github.com/tokyo-metropolitan-gov/covid19/pull/1274

> 言語設定が英語の場合にデフォルトのURLが
> https://stg-covid19-tokyo.netlify.com/en
> などになってますね。
> https://stg-covid19-tokyo.netlify.com/en/
> になってくれれば解決なのですが

こちらも含めて修正しておきました。
現時点ではどちらのURLも使用できますので404エラーになることはなさそうですが
表記揺れを防ぐため、別途リダイレクト処理を入れた方がよいです。

ただ、ブラウザのリロードやサイト内のリンクによって / 付きにリダイレクトされるので
どういった方針で修正を進めていくのか検討しなければなりません。
