### ISSUE TITLE
トップページ「都庁来庁者数の推移」とその下部のグラフでidが重複している

### ISSUE THREAD

**Issue by af12066** [tokyo-metropolitan-gov/covid19#1185]
## 起こっている問題 / The Problem
- 次の箇所で、h3要素とcanvas要素に割り当てられているidが重複しています。idはページ内で一意である必要があります
    - https://github.com/tokyo-metropolitan-gov/covid19/blob/256ca448f51d05244d1d47132901274cd8357253/pages/index.vue#L104-L105

## スクリーンショット / Screenshot

ChromeのLighthouseによる説明を添付します
![[id] attributes on the page are not unique. Names and labels: These are opportunities to improve the semantics of the controls in your application. This may enhance the experience for users of assistive technology, like a screen reader.](https://user-images.githubusercontent.com/10768439/76476507-972c3800-6445-11ea-8265-2269846fc88b.png)

## 期待する見せ方・挙動 / Expected Behavior

- ページ全体で一意となるようにidを割り振る

## 起こっている問題の再現手段 / Steps to Reproduce

--

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android: すべて
- Chrome / Safari / Firefox / Edge / Internet Explorer: すべて

**Comment by ixap2i** [comment]
やります

**Comment by halsk** [comment]
これまでに取り込んだPRの中で、修正されているようです。
こちら閉じても大丈夫そうでしょうか？

![image](https://user-images.githubusercontent.com/16509/76682616-e4c0c480-6640-11ea-921b-fcd5d8dfddbd.png)

**Comment by af12066** [comment]
お、大丈夫です！
