### ISSUE TITLE
[i18n]title と description, OGP が多言語化されていない

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1190]
**[i18n] 関連ですが、修正は development ブランチにしてください。**

## 起こっている問題 / The Problem
- title と description, OGP が多言語化されていない

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/76481213-440db180-6454-11ea-9ca3-b60eeeb6b65f.png)

## 期待する見せ方・挙動 / Expected Behavior
- meta tag の要素も多言語化する

- [ ] og:site_name, og:title, apple-mobile-web-app-title: 東京都 新型コロナウイルス感染症対策サイト (翻訳シート 223)
- [ ] description, og:description: 当サイトは新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、東京都が開設したものです。 (翻訳シート 112)
- [ ] og:image: @saladdays さん提供の画像に差し替え

**Comment by saladdays** [comment]
OGP作成担当します

**Comment by MaySoMusician** [comment]
`og:title` の修正PRが昔にあると思いますが無視しちゃってください

**Comment by halsk** [comment]
あ、これですか？ #962 取り込んでOKなのかな

**Comment by halsk** [comment]
@MaySoMusician さんが言及したのはこっちですね。#531

**Comment by MaySoMusician** [comment]
いや、それとは別です
#531

**Comment by halsk** [comment]
#962 だと description は変わらないか。

**Comment by MaySoMusician** [comment]
#962 で titleは修正されるので description と OGP(og:title, og:description)などは別途作業が必要となります

**Comment by saladdays** [comment]
英語：`COVID-19` `Task Force website`
簡体字：`新型冠状病毒` `资讯站`
繁體字：`新型冠狀病毒` `疫情中心`
한국어：`코로나19` `TF 웹사이트`

**Comment by saladdays** [comment]
@halsk 「東京都公式」って翻訳文ありますか？

**Comment by halsk** [comment]
https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw
13行目が近いですが、そのものずばりなものはないですね

**Comment by saladdays** [comment]
おお、それではご依頼頂いてもいいですか？🙇

**Comment by halsk** [comment]
@MaySoMusician さんかどなたか、私いま外出中なので、どなたか翻訳シートアップデートできますか？

**Comment by mikkame** [comment]
これも多分ローダー外さないと子ページごとのタイトル反映されないです

**Comment by mikkame** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/1063

**Comment by MaySoMusician** [comment]
> @MaySoMusician さんかどなたか、私いま外出中なので、どなたか翻訳シートアップデートできますか？

Row 229に入れました

**Comment by halsk** [comment]
期待する見せ方・挙動 / Expected Behavior の部分を修正しました。
どなたか対応いただけると助かります。
@saladdays さん、翻訳揃いました。OGP 画像お願いできますか？（やさしい日本語とかどうするんだろう）
https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0

**Comment by kaizumaki** [comment]
多言語用のOGP画像はこちらになります。
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=6288%3A1046

**Comment by chihirof** [comment]
こちら対応します。
https://github.com/tokyo-metropolitan-gov/covid19/issues/1190#issue-579651019
に書いてあることを行います。

**Comment by chihirof** [comment]
こちら対応範囲としては、トップページ（https://stopcovid19.metro.tokyo.lg.jp/）のみで良いでしょうか？ @halsk

**Comment by amotarao** [comment]
@chihirof 
以下の nuxt.config.ts に書かれているデフォルトのサイト情報が反映されるページ (_card以外) になりそうです
https://github.com/tokyo-metropolitan-gov/covid19/blob/2ab971b5e49a20138b2eea1508069511f6cf71cc/nuxt.config.ts#L16-L82

**Comment by chihirof** [comment]
ありがとうございます！
nuxt.config.ts、対応します！

**Comment by chihirof** [comment]
こちら設定ファイル内で多言語化なのですね
nuxt.config.ts内の多言語化で良い方法ご存知の方いますか？

**Comment by amotarao** [comment]
@chihirof ざっと調べた限りでは、nuxt.config.ts 上での多言語化は無理そうです
どこかのコンポーネントの `head() {}` 内に移すしかないかなと思われます
すべてのページにおいて `/layouts/` 以下の何かしらが読み込まれるのでそちらへの記述が良さそうと思いました

**Comment by chihirof** [comment]
@amotarao 
ありがとうございます！nuxt.config.ts内ではできなさそうですね。

> すべてのページにおいて /layouts/ 以下の何かしらが読み込まれるのでそちらへの記述が良さそうと思いました
こちらで対応進めたいと思います。

**Comment by chihirof** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/1509
こちらのissueがありましたね。
本issueでは仕組みのみ作って、日本語以外の言語はキーを削除しようと思います。
(たまたまなのですが https://github.com/tokyo-metropolitan-gov/covid19/pull/1413#issuecomment-599172017 で同じようなことがあったので、こちらでも合わせた対応を入れます。)

このissueだけは翻訳もいれる、ということであれば入れますので言ってください^^

**Comment by chihirof** [comment]
と、思ったのですが、日本語訳もこちらのissueに書かれているものとずれていました。確認させてください。

「og:site_name, og:title, apple-mobile-web-app-title: 東京都 新型コロナウイルス感染症対策サイト (翻訳シート 223)」とあるのですが、スプレッドシートのA列223の文言は「東京都公式」でした。「東京都 新型コロナウイルス感染症対策サイト」もA列３にありました。どちらが良いでしょうか？
(descriptionは指定通りの場所にありました)

また、画像についても質問させてください。nuxt.config.tsをみるとog:imageにはURLが指定されています。static等に画像を配置するのではなく、別手段でアップロードするのでしょうか？

**Comment by amotarao** [comment]
@chihirof og:image は完全なURLでないと、シェア時にTwitter・Facebook等が画像を引っ張ってこれないです。画像自体はstaticに配置します。

その他は翻訳系は不明です 🙇

**Comment by chihirof** [comment]
<og:image は完全なURLでないと、シェア時にTwitter・Facebook等が画像を引っ張ってこれないです。画像自体はstaticに配置します。
確かにそうですね！ありがとうございます！

翻訳系についてもコメントありがとうございます！！

**Comment by chihirof** [comment]
@MaySoMusician 
翻訳についてSlackで周知されていましたので確認させてください 🙇
こちらのタスクで翻訳適応となっているのですが、#1509 があるので、ここでは仕組みづくりだけで良いでしょうか？
仕組みづくり＝日本語のみ翻訳を入れて、その多言語はキーを入れない(日本語が表示される)
画像については翻訳とはちょっと違う気もするのでここで入れようと思っています

**Comment by halsk** [comment]
トップページの翻訳は、「東京都 新型コロナウイルス感染症対策サイト」をキーに使ってください。
日本語以外の言語は削除して大丈夫です。
はい。画像の指定はこちらの方で修正してください。

**Comment by chihirof** [comment]
@halsk 
ありがとうございます！

**Comment by chihirof** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/1624
プルリク出しました。ご確認をよろしくお願いします！

**Comment by halsk** [comment]
クローズです！ありがとうございました！
明日の朝本番に反映予定です。
