### ISSUE TITLE
検査実施数の積み上げ棒グラフのツールチップ改善（ラベル選択時にわかりづらい）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1195]
## 改善詳細 / Details of Improvement
- ラベルをクリックするとそれぞれの項目でのグラフに切り替わるが、その時のツールチップの表示内容がわかりにくい。

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-12 12 35 18](https://user-images.githubusercontent.com/14883063/76484977-820fd300-645e-11ea-8f84-42c57614c0d9.png)

## 期待する見せ方・挙動 / Expected behavior
- 案１：合計数字の前に「合計」を入れる
```
2/20
合計136件（都内：119）
```
こちらは実装が簡単です（ただし要i18n化）。

- 案２：それぞれの項目の数字のみにする
```
2/20
119件
```

- 案３：それぞれの項目名＋数字にする
```
2/20
都内：119件
```

どの案が適切なのかの意見もください！

**Comment by kaizumaki** [comment]
グラフ数字の表示にかかわるので、 `IMPORTANT` ラベルをつけました。
@ocean3fish どの案がいいですかね？

**Comment by ocean3fish** [comment]
@kaizumaki 
案1で、細かいですが "：" を入れて頂けると良いかと思いますー。
```
2/20
合計：136件（都内：119）
```
案2、案3だと、系列全て表示ONで積み上げ状態の時に、合計値がわからなくなってしまうかと思われたので。
いかがでしょうか？

**Comment by kaizumaki** [comment]
@ocean3fish 系列全て表示ONのときは合計値になるように分岐させることもできると思います。
ここはコーディング次第なのだけど・・・。そうだとしたら、改めてどれが理想ですか？

**Comment by ocean3fish** [comment]
@kaizumaki 少しリセットして考えていたのですが、案1ベースとしつつ、以下の表示にすると自然かと思ったのですがいかがでしょう？

1 系列全て表示ONの時

1-1「都内」にマウスオーバー
```
2/20
都内：119件（合計：136件）
```
1-2「その他」にマウスオーバー
```
2/20
その他：17件（合計：136件）
```


2 「都内発生」のみONの時
```
2/20
都内：119件（合計：136件）
```

マウスオーバーした対象の数値が先に来る形にすれば、ユーザの期待する挙動にもマッチして、必要な情報も提示できることになるかと。

**Comment by kaizumaki** [comment]
> マウスオーバーした対象の数値が先に来る形にすれば、ユーザの期待する挙動にもマッチして、必要な情報も提示できることになるかと。

@ocean3fish たしかに。これはいいかも！

**Comment by shgtkshruch** [comment]
こちらどなたも着手されてなければ、実装させていただきます。

**Comment by kaizumaki** [comment]
@shgtkshruch ぜひお願いします！

**Comment by shgtkshruch** [comment]
ツールチップ内のテキストで利用する「合計」の翻訳データをいただきたいです。
このグラフで対応済みの言語が、en, zh-cn, zh-tw, ko なので、こちらの翻訳があると嬉しいです。

**Comment by kaizumaki** [comment]
> ツールチップ内のテキストで利用する「合計」の翻訳データをいただきたいです。
> このグラフで対応済みの言語が、en, zh-cn, zh-tw, ko なので、こちらの翻訳があると嬉しいです。

@MaySoMusician ご対応いただけますか？

**Comment by MaySoMusician** [comment]
@kaizumaki 翻訳シートに登録しておきました！

**Comment by shgtkshruch** [comment]
@MaySoMusician @kaizumaki 

ありがとうございます！
確認します。
