### ISSUE TITLE
PR Template: 関連issue 英語の古い説明が残っている

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1196]
## 起こっている問題 / The Problem
- https://raw.githubusercontent.com/tokyo-metropolitan-gov/covid19/development/.github/PULL_REQUEST_TEMPLATE.md 7-8行目
- 関連issueの記載が必須ではないという古い説明になっている

## 期待する見せ方・挙動 / Expected Behavior
- 11-12行目のみにする

**Comment by tanigaki39** [comment]
対応致しました :bow: お手すきの際にご確認をお願い致します

**Comment by amotarao** [comment]
別PRにて文言が削除されたのでcloseします
@tanigaki39 対応ありがとうございました！
