### ISSUE TITLE
お問い合わせ先デグレ

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1198]
（都のサイトポリシーについて）がいつの間にか消えています。復活お願いします
https://stopcovid19.metro.tokyo.lg.jp/about

お問い合わせ先（都のサイトポリシーについて）

**Comment by af12066** [comment]
追加の翻訳が必要になります!
https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0&range=205:205

**Comment by af12066** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/324 
`お問い合わせ先（都のHPサイトポリシーについて）`でよいですよね?

**Comment by kaizumaki** [comment]
文言はそれですね。お願いしてもいいですか？

**Comment by af12066** [comment]
いったん日本語だけhotfixでなおします
