### ISSUE TITLE
pages/about.vue: source code reference points to wrong URL

### ISSUE THREAD

**Issue by francisfuzz** [tokyo-metropolitan-gov/covid19#1205]
## 起こっている問題 / The Problem

In https://stopcovid19.metro.tokyo.lg.jp/about/, the `About the source code` section references a GitHub repository. However, the URL doesn't point to this repository but a different page:

https://github.com/tokyo-metropolitan-gov/covid19/blob/32beeada2bfa587ed551c4b860570737cab197e7/pages/about.vue#L162-L171

## スクリーンショット / Screenshot

![about-the-source-code](https://user-images.githubusercontent.com/15894826/76489050-90210d80-63e4-11ea-8195-1f1a9728bea4.png)

## 期待する見せ方・挙動 / Expected Behavior
- This URL should point to https://github.com/tokyo-metropolitan-gov/covid19 instead.

## 起こっている問題の再現手段 / Steps to Reproduce
1. Go to https://stopcovid19.metro.tokyo.lg.jp/about/
2. Navigate to `ソースコードについて` (also known as `About the source code`)
3. Click `GitHub リポジトリ`, which leads to `https://portal.data.metro.tokyo.lg.jp/` instead of this repository.

## 動作環境・ブラウザ / Environment
All environments are affected.

**Comment by kaizumaki** [comment]
@francisfuzz Thanks for the report! It has been corrected in the PR here. #1194

**Comment by francisfuzz** [comment]
@kaizumaki - Amazing! I'll leave this open until #1194 is merged in; I will close https://github.com/tokyo-metropolitan-gov/covid19/pull/1206 for now. 👍

**Comment by francisfuzz** [comment]
Oh whoops! I see https://github.com/tokyo-metropolitan-gov/covid19/issues/1193, making this a duplicate. Will close this out -- sorry for the noise 🙇
