### ISSUE TITLE
[/flow] SP版のマークアップ・スタイル統一と調整

### ISSUE THREAD

**Issue by macropygia** [tokyo-metropolitan-gov/covid19#1225]
## 改善詳細 / Details of Improvement

- コンポーネント毎に差異のあるマークアップ・スタイルを統一する
    - 現在の「発症前2週間以内の出来ごとと症状」と「新型コロナ受診相談窓口 による相談結果」に他を寄せる予定
- vwを使用した擬似スケーリングで極力元のデザインに寄せる
    - ブレークポイント(`600px以下`と`601～768px`)毎に個別に調整
- 共通のcssを外に出す
    - 各コンポーネントの `<style>` の中で `@import` する方法を検討中
- width属性とheight属性を外したsvgを用意する
    - width属性とheight属性があるとcssで拡大・縮小できない
- 日本語以外も考慮して調整する

**Comment by macropygia** [comment]
着手します。何事もなければ明日中にはPRできるかと。

**Comment by kaizumaki** [comment]
@macropygia よろしくお願いします！
