### ISSUE TITLE
日本語表示されました

### ISSUE THREAD

**Issue by aicochow** [tokyo-metropolitan-gov/covid19#1227]
## 起こっている問題 / The Problem
- 日本語表示されました

## スクリーンショット / Screenshot

![chrome_lyB3ZS0YAT](https://user-images.githubusercontent.com/12031804/76508752-4131b180-6492-11ea-8747-e4919be19ed0.png)

![chrome_c6qa45cjxk](https://user-images.githubusercontent.com/12031804/76508969-940b6900-6492-11ea-9600-558f65aab9c1.png)

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by nhidaka** [comment]
対応いたします。

**Comment by ledsun** [comment]
2枚目のスクリーンショットは #1182 と重複しているように思います。

**Comment by nhidaka** [comment]
こちら、日本語以外の全ての言語で同じ現象が発生しております。
各言語版の文言は決まっておりますでしょうか？

**Comment by nhidaka** [comment]
文言につきまして、プロジェクト内に同じ意味の文言がありましたのでそちらで対応します！

**Comment by nhidaka** [comment]
ledsun 様からの指摘もありました様に、重複しておりましたので検査実施数のみ対応させていただきました。
