### ISSUE TITLE
[/flow] [i18n] SP英語版で「n日程度続いている」の日数部分が表示されていない

### ISSUE THREAD

**Issue by macropygia** [tokyo-metropolitan-gov/covid19#1228]
## 起こっている問題 / The Problem

- SP英語版で2箇所ある「n日程度続いている」の日数部分が表示されていない
    - `FlowSpGeneral` と `FlowSpElder` コンポーネント

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/3162324/76510503-15fc9180-6495-11ea-8b04-dd84be5e346b.png)

**Comment by zo30005** [comment]
こちら対応します！

**Comment by MaySoMusician** [comment]
@zo30005 こちら上記の通り既に #1230 来ております！

**Comment by MaySoMusician** [comment]
Close per #1230 merged
