### ISSUE TITLE
翻訳定義をコンポーネントから別ファイルに切り出す

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#1229]
## 改善詳細 / Details of Improvement
- 翻訳定義をコンポーネントから別ファイル（JSONファイル）に切り出す

## なぜやるのか / Motivation
- コンポーネントの`.vue`ファイルの肥大化を防ぐ
  - たとえば、[index.vue](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/pages/index.vue)では、559行中244行が翻訳定義となっている
- 翻訳の更新作業をやりやすくする
  - 翻訳作業をする人はJSONの仕様さえ知っていればよく、`.vue`ファイルを気にする必要がなくなる

## 期待する見せ方・挙動 / Expected behavior
- 翻訳定義がコンポーネントから分離された別ファイル（JSONファイル）で定義されている

### A：コンポーネントと同階層に`<component-name>.lang.json`を配置
```
.
├── components
│   ├── PageHeader.lang.json
│   ├── PageHeader.vue
│   ├── WhatsNew.lang.json
│   └── WhatsNew.vue
└── pages
    ├── flow.lang.json
    ├── flow.vue
    ├── index.lang.json
    └── index.vue
``` 

### B：コンポーネントと同階層に`lang/<component-name>.json`を配置
```
.
├── components
│   ├── PageHeader.vue
│   ├── WhatsNew.vue
│   └── lang
│       ├── PageHeader.json
│       └── WhatsNew.json
└── pages
    ├── flow.vue
    ├── index.vue
    └── lang
        ├── flow.json
        └── index.json
```

```
<i18n src="./lang/flow.json"></i18n>
```

### C：コンポーネントとは別階層に全ページ共通の`lang/<language-code>.json`を配置
```
.
├── components
│   ├── PageHeader.vue
│   └── WhatsNew.vue
├── lang
│   ├── en.json
│   └── ja.json
└── pages
    ├── flow.vue
    └── index.vue
```

## 参考リンク / See also
- [intlify/vue-i18n-loader: vue-i18n loader for custom blocks](https://github.com/intlify/vue-i18n-loader#source-importing)
- [Nuxt.jsのプロジェクトでnuxt-i18nを使ってi18n（国際化）対応する方法 - Qiita](https://qiita.com/munieru_jp/items/d7e9f98b5ab5960e7a93)

**Comment by munierujp** [comment]
こちら、実施してもよろしければ私がやりたいと思います。

**Comment by MaySoMusician** [comment]
ファイル構成なのですが、言語ごとに全Vueファイル共通のファイルを作るのはどうでしょうか。
サイドナビゲーションとページ上部タイトル、スマホ版flowページのNotRequired・Requiredコンポーネント、といった感じで共通の翻訳が存在しており、これらがそれぞれのファイルで管理されるのは本来望ましくないのかなと思っております

**Comment by munierujp** [comment]
@MaySoMusician 全ページ共通にする場合、ページごとにオブジェクトを入れ子にするのか、ページのプレフィックスをつけるのかなどの問題があるかと思っていました。
が、今の翻訳定義であればキーが被る＝同じ意味の言葉であるため、全ページ共通のファイルにしても問題ありませんね :smile:

**Comment by MaySoMusician** [comment]
@munierujp ご指摘の通りです
ただ、既に「日本語では同じ単語だが他の言語では翻訳がわかれる」という例は発生しておりまして
（「都内の最新感染動向」の「件」→「cases・reports」）
現在は `'件.cases'` ・ `'件.reports'` というようにJSON上でオブジェクトを入れ子にして対応しております
（その他、日本語と英語がどうにも対応しなくて英語が翻訳キーになっている部分もあったり... このあたりは近いうちに文書化する必要がありそうです）

---
実際の作業ですが[nuxt-i18n の公式ドキュメント - Lazy-load translations](https://nuxt-community.github.io/nuxt-i18n/lazy-load-translations.html) にあるようなファイル構成・コードで行けるのではないかと思っております
こちらを読みつつ作業をお願いしたいと思います！
もし何か気になる点や「こうしたほうがより良い」ということがありましたら、お気軽にお声がけください！

**Comment by munierujp** [comment]
言語ファイル内にどのコンポーネントから持ってきたものなのかをコメントで書いておきたいので、ひとまずJSファイルにしようと思います。

**Comment by munierujp** [comment]
@MaySoMusician `components/flow`ディレクトリ内にあるコンポーネントで、「新型コロナ受診相談窓口」というキーの翻訳がコンポーネントによってまちまち（「advisory」だったり「Combined telephone advice center」だったり）なのですが、こういったケースはどうしましょう……？

**Comment by munierujp** [comment]
ひとまずキーの重複を避けるために、コンポーネントごとに言語ファイルを作る形式にしました。

**Comment by MaySoMusician** [comment]
@munierujp （すみません、寝てました）
#1244 確認いたしました。個人的にはやはり1ファイルにまとめておきたいかなぁと（見通し的にも）
今回の例に限りますと、そもそも「新型コロナ受診相談窓口 による相談結果」というところで英語版が“advisory”と一般名詞化するのがまずかったかなと（「窓口による相談結果」とは書いていないので）
そういう面から考えると「新型コロナ受診相談窓口 = Combined telephone advice center」で統一してしまっても大丈夫かなと思います
（スマホ側のデザインの問題もありますが... @kaizumaki に要確認）

---
ただ、今回乗り切れたとしても

> 同じキーでもコンポーネントによって文言が異なるケース

というのはやはり必ず出てくるはず（と想定して対応すべき）ですね。
ただ現時点のサイトの規模では、こういった翻訳のバッティングが多発することは無いかなという気がしますので、 `'件.cases'` ・ `'件.reports'` のようにして乗り切っちゃおうかなと考えています
（今回の例で当てはめると、 `新型コロナ受診相談窓口.long` と `新型コロナ受診相談窓口.short` かな？）

---
という感じなので、非常にコピペの作業が多くなって大変申し訳ないのですが、1ファイルにまとめたC案でもPRお願いしてもよろしいでしょうか...？
（ #1244 をCloseするかそこに上書きforce-pushするかは完全にお任せします...）

**Comment by munierujp** [comment]
@MaySoMusician ありがとうございます。翻訳定義はすべてJSONファイル化済みなので、簡単なスクリプトを書けば1ファイルにまとめること自体は半自動的にできそうです。

スクリプトのイメージ：

```js
const INPUT_PATH = 'pages/index.i18n.json'  // 実際にはコマンドライン引数
const OUTPUT_DIR = 'lang'

const obj = readJSON(INPUT_PATH)
Object.entries(obj).forEach([key, value]) => {
  const outputPath = `${OUTPUT_DIR}/${key}.js`
  const vuePath = INPUT_PATH.replace(/\.i18n.json$/, '.vue')
  const comment = `/* ${vuePath} */`
  appendLang(outputPath, value, comment)
})
```

※`appendLang`は、以下のようにファイルに追加する関数

```
    /* pages/index.vue * /
    "都内の最新感染動向": "都内の最新感染動向",
    "自分や家族の症状に不安や心配があればまずは電話相談をどうぞ": "自分や家族の症状に不安や心配があればまずは電話相談をどうぞ",
    "相談の手順を見る": "相談の手順を見る"
```

しかしながら自分が今日は作業できる時間がなさそうなので、翻訳の更新がありそうであればこのタイミングでいったんマージしていただいたほうがいいかもしれません。

**Comment by kaizumaki** [comment]
> そういう面から考えると「新型コロナ受診相談窓口 = Combined telephone advice center」で統一してしまっても大丈夫かなと思います
> （スマホ側のデザインの問題もありますが... @kaizumaki に要確認）

上記の件、統一して大丈夫です。「新型コロナ受診相談窓口 | による相談結果」という区切りは変わりませんよね？（Pc, Spともにそういうマークアップになってます）
変更作業って急ぎますか？いまSpのほうが #1267 で作業中です。

**Comment by MaySoMusician** [comment]
> 上記の件、統一して大丈夫です。「新型コロナ受診相談窓口 | による相談結果」という区切りは変わりませんよね？（Pc, Spともにそういうマークアップになってます）
> 変更作業って急ぎますか？いまSpのほうが #1267 で作業中です。

@kaizumaki 区切りは変わらないです！
#1267 との兼ね合いですがおそらく辞書の部分にのみ影響する変更なのでコンフリクト等は起きないかと思います

**Comment by kaizumaki** [comment]
@MaySoMusician 了解です！では進めてください！

**Comment by munierujp** [comment]
@MaySoMusician Transifexへの移行（#1509）にあたって、nuxt-i18nの翻訳定義はどのようになりますか？（それ次第ではこのイシューは役目を終えるのかなと）

- ファイルの分割単位（言語ごと？コンポーネントごと？）
- ファイル形式（JS？JSON？YAML？）

**Comment by MaySoMusician** [comment]
@munierujp `assets/locales`内に言語ごとにJSONを用意する形を想定しています
[`dev-transifex`](https://github.com/tokyo-metropolitan-gov/covid19/tree/dev-transifex)ブランチでお試し運転中です

**Comment by MaySoMusician** [comment]
言語ごとにJSONを用意するのは #1312 完了後の予定です

**Comment by MaySoMusician** [comment]
@munierujp https://github.com/tokyo-metropolitan-gov/covid19/issues/1229#issuecomment-598456330 のスクリプトと、 munierujpさんのnuxt-i18nのQiita記事のおかげで、ひとまず作業完了いたしました！ありがとうございました
