### ISSUE TITLE
parent.vueのタイトルが多言語対応されていない

### ISSUE THREAD

**Issue by ledsun** [tokyo-metropolitan-gov/covid19#1234]
## 起こっている問題 / The Problem
- 言語設定によらず「お子様をお持ちの皆様へ」ページのページタイトルの前半部分が日本語のまま`お子様をお持ちの皆様へ | 東京都 新型コロナウイルス感染症対策サイト`が表示される

## スクリーンショット / Screenshot

<img width="695" alt="スクリーンショット 2020-03-12 19 48 05" src="https://user-images.githubusercontent.com/1079508/76513930-6d513080-649a-11ea-9f82-a2a97fc30124.png">

## 期待する見せ方・挙動 / Expected Behavior
- ページタイトルの前半部分が多言語対応され、例えば英語であれば、`For families with children | 東京都 新型コロナウイルス感染症対策サイト`が表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 言語設定を英語にして、「お子様をお持ちの皆様へ」ページヘ遷移
2. ページタイトルが英語ではなく「お子様をお持ちの皆様へ | 東京都 新型コロナウイルス感染症対策サイト」が表示される

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by ledsun** [comment]
手元の環境では対応できています。
PRを作成します。

**Comment by kikd** [comment]
about.vue、worker.vueでも同じ現象が起きています。

![image](https://user-images.githubusercontent.com/5682821/76516271-73e1a700-649e-11ea-99e3-546108b04f65.png)

![image](https://user-images.githubusercontent.com/5682821/76516295-8065ff80-649e-11ea-8cd4-355921e0ef9c.png)

**Comment by af12066** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/962 コチラで修正されるようです

**Comment by ledsun** [comment]
#1190 で既知の問題でした。
