### ISSUE TITLE
速報値であることの記載

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#1242]
## 改善詳細 / Details of Improvement
検査陽性者の状況、検査実施数 について、それぞれ既存の注釈の下に、以下の文面を追加してください。
検査陽性者の状況：「検査実施人数は、速報値として公開するものであり、後日確定データとして修正される場合があります」
検査実施数：「検査実施数は、速報値として公開するものであり、後日確定データとして修正される場合があります」

## Background
検査実施数、検査実施人数は、東京都健康研究安全センターが集計した速報値をデータ化しています。報道向けにも速報値として伝えており、サイトにも明記します。

**Comment by kebhr** [comment]
着手しますー。

**Comment by kebhr** [comment]
@MaySoMusician 
このIssue、新たにテキストを翻訳する必要があるため翻訳シートを更新したいのですが、私の方で行っても問題ないですか？

**Comment by halsk** [comment]
@kebhr 取り急ぎ、日本語以外は全て英語で対応していただけますか？
[こちら](https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0)に英文のみ追記させていただきました。

**Comment by kebhr** [comment]
@halsk 
承知しました。更新してDraft外します。
