### ISSUE TITLE
「都営地下鉄の利用者数の推移」のグラフの日付

### ISSUE THREAD

**Issue by shinnosuke-kito** [tokyo-metropolitan-gov/covid19#1245]
## 起こっている問題 / The Problem
Langを変更しても「〜月〜日」の表記のまま

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/62087382/76523795-5ddae300-64ac-11ea-83bf-7376c9ded226.png)

## 期待する見せ方・挙動 / Expected Behavior
○○(月)/〇〇(日)の表記にする

## 起こっている問題の再現手段 / Steps to Reproduce
1. Langを日本語以外に変更

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by shgtkshruch** [comment]
issue の起票ありがとうございます。
現在の本番環境で言語を英語に変更して、グラフの日付が MM/DD 形式になっていることを確認しました。
こちらの issue は解決済みかと思います :)

![スクリーンショット 2020-03-28 21 59 37](https://user-images.githubusercontent.com/5207601/77823573-6f281e80-713f-11ea-83ce-e295bcc07982.png)
