### ISSUE TITLE
各データの最終更新日時の取得場所について

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#1247]
## 改善詳細 / Details of Improvement
各データの最終更新日時は、シート内のdtLastUpdateセルであったり、DataList.xlsx内の各ファイルの最終更新日時であったりしておりますが、基本的にDataList.xlsx内の最終更新日に集約します。
（当面は、両方のデータを更新します）

## 期待する見せ方・挙動 / Expected behavior
それぞれのデータ・グラフの最終更新日時と、DataList.xlsx内のデータ名の関係は以下の通りです。
--サイト内データタイトル--  →   --DataList.xlsxのデータ名--
検査陽性者の状況 → 「東京都患者発生発表数」 の最終更新日時
陽性患者数 →  「東京都患者発生発表数」 の最終更新日時
陽性患者の属性 →  「東京都患者発生発表数」 の最終更新日時
検査実施数 → 「検査実施日別状況-検体」 の最終更新日時
新型コロナコールセンター相談件数 → 「新型コロナコールセンター相談件数」 の最終更新日時
新型コロナ受診相談窓口相談件数  →  「新型コロナ受診相談窓口相談件数」 の最終更新日時
都庁来庁者数の推移 → 「入庁者数」の最終更新日時

## Background
原局現場の方々に、直接データ入力を行うプロセスに移行しておりますが、比較的二つのシート（データシートとDataListのアップデート）の手順で問題がないことが確認できたため、最終更新日時のデータ場所を集約化します。

**Comment by mikkame** [comment]
実装上は対応済みです。

**Comment by mtenjin** [comment]
コールセンター、帰国者・接触者窓口シートから最終更新日を削除しています。
これでうまくいけばOKと判断して良いと思います。

**Comment by mikkame** [comment]
今の所問題が出てなさそうなのでクローズします。
