### ISSUE TITLE
[i18n] ※土・日・祝日を除く庁舎開庁日の1週間累計数 の翻訳の追加

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1262]
## 改善詳細 / Details of Improvement
- 都庁来庁者数の推移の注釈が多言語化されていない

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/76533994-46a3f180-64bc-11ea-9737-0e3e6fc410a8.png)

## 期待する見せ方・挙動 / Expected behavior
- 翻訳ができ次第反映してください。翻訳シートの228行目にあります。
- components/AgencyBarChart.vue

**Comment by kiiita** [comment]
英語、簡体字、繁體字、韓国語の翻訳待ちになります
翻訳が上がってきたらPRに反映致します

**Comment by MaySoMusician** [comment]
Close per #1590 merged
残りの翻訳はTransifexにて
