### ISSUE TITLE
OGP画像生成の保存先を変更

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#1268]
## 改善詳細 / Details of Improvement
- resourceブランチ見たいのを作ってとりあえずそこに置く

## 期待する見せ方・挙動 / Expected behavior
- resourceブランチ見たいのを作ってとりあえずそこに置く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mikkame** [comment]
直pushは厳しかった。
とりあえずアーティファクトに保存するようにしてデプロイ時に手動で回収するように

**Comment by mikkame** [comment]
https://github.com/ad-m/github-push-action
これを使えばいけるのかもしれない。

**Comment by halsk** [comment]
@mikkame さん、この Issue 気づいていませんでした。すみません。

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/workflows/ogp_builder.yml

にあるように、アーティファクトに保存された OGP 画像を `/deploy/new_ogp` ブランチに push するようにしてあります。マージリクエストも出しているはずなのですが、うまく動かず。

**Comment by halsk** [comment]
@mikkame さん、こちら、最終的にこのような形に落ち着きました。

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/workflows/ogp_builder.yml

* 言語毎の OGP 画像を `/ogp/{LANG}/{CARD_ID}.png` に生成し、アーティファクトに保存する
* `staging` を `checkout` し、上記のOGPを `/static/ogp` に配置し、 `deploy/new_ogp` に push する

ということをやっています。`data.json` を更新して `staging` に push し、その後 `deploy/new_ogp` ブランチから再度 `staging` に マージをすれば、OGP 更新完了です。
