### ISSUE TITLE
[i18n] フロー図印刷ページの多言語化

### ISSUE THREAD

**Issue by abekoh** [tokyo-metropolitan-gov/covid19#1270]
## 改善詳細 / Details of Improvement
- 下記ページにて、どの言語であっても印刷ボタンの遷移先が日本語になっている
https://stopcovid19.metro.tokyo.lg.jp/flow

## スクリーンショット / Screenshot
遷移前: https://stopcovid19.metro.tokyo.lg.jp/en/flow
矢印のところをクリック
![スクリーンショット 2020-03-13 01 08 13](https://user-images.githubusercontent.com/20609790/76541800-773d5880-64c7-11ea-8faf-2f01cfa3525a.png)
遷移後: https://stopcovid19.metro.tokyo.lg.jp/print/flow/
![スクリーンショット 2020-03-13 01 08 04](https://user-images.githubusercontent.com/20609790/76541821-7d333980-64c7-11ea-97ab-fd22d35d34a9.png)

## 期待する見せ方・挙動 / Expected behavior
- 選択した言語に合った印刷ページに飛ぶ

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by abekoh** [comment]
印刷ページはSVGに変換したものベタ書きですので、
その変換方法さえ共有されていれば対応できるかと思います。

**Comment by forestgtree** [comment]
Flowページの初期デザイン（SVG）は
私が作成した、Adobe XDからの書き出しによるものです。（非公開ファイルです）

多言語分Adobe XDで作成することは、あまり現実的ではないため
他に良い方法があれば、ご提案いただけると助かります！🙇‍♂️

**Comment by amotarao** [comment]
flowPc への置き換えが一番楽だと思いますが、
1ページに収まらなくなってしまいますね 😢 
<img width="224" alt="スクリーンショット 2020-03-13 1 23 42" src="https://user-images.githubusercontent.com/8909592/76543099-5aa22000-64c9-11ea-9a63-ff1e267999e5.png">

**Comment by amotarao** [comment]
📝 「最新の情報はWebページをご覧ください」の翻訳が必要

**Comment by amotarao** [comment]
flowPc に置き換えた場合、翻訳ができていることを手元で確認しました
http://localhost:3000/zh-cn/print/flow
<img width="407" alt="スクリーンショット 2020-03-13 1 28 26" src="https://user-images.githubusercontent.com/8909592/76543505-f5026380-64c9-11ea-8c10-2c5358bde1f0.png">

**Comment by amotarao** [comment]
flowPc で対応しました #1273 

以下が不足
- 「QRコード」の翻訳
- 「※最新の情報はWebページをご覧ください」の翻訳

**Comment by MaySoMusician** [comment]
@amotarao 確か「QRコード」はデンソーウェーブの登録商標で、一般名詞では「二次元バーコード」とかでしたが、翻訳はどういたしましょうか？

**Comment by amotarao** [comment]
@MaySoMusician 確かにその通りでした。日本語も翻訳も二次元バーコード/二次元コードに寄せたほうがよさそうですね。

**Comment by kaizumaki** [comment]
こちら、現在は印刷ページも多言語化されているように見えますが、あと何がたりない感じでしょうか？
見たところ、

> - 「QRコード」の翻訳

が足りないのかな？とも思いましたが、現在のQRコードのimgのaltには `QRCode` と入っています。

**Comment by kaizumaki** [comment]
> 現在のQRコードのimgのaltには `QRCode` と入っています。

すみません。こちら多言語化されてたんですね。失礼しました。
というわけでこちらのissueはクローズさせていただきます。
