### ISSUE TITLE
翻訳用スプレッドシートURLをCONTRIBUTINGに記載する

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1271]
## 改善詳細 / Details of Improvement
- 翻訳用スプレッドシートのURLを CONTRIBUTING.md に記載する
- [開発に関する情報](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/CONTRIBUTING.md#%E9%96%8B%E7%99%BA%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E6%83%85%E5%A0%B1) 内がよさそう

**Comment by f-koki** [comment]
こちら対応します。
