### ISSUE TITLE
[i18n] 英語で「入院」とすべき箇所が「退院」となっている

### ISSUE THREAD

**Issue by sidemt** [tokyo-metropolitan-gov/covid19#1276]
## 起こっている問題 / The Problem
- 「新型コロナウイルス感染症が心配なときに」のフローにおいて、日本語で「入院となります」と書かれている箇所が、英語では「Need to discharge」（退院）となっている

## スクリーンショット / Screenshot
英語（誤）
![en](https://user-images.githubusercontent.com/25644062/76553708-defb9f80-64d7-11ea-9319-c597a440768c.png)

日本語（正）
![ja](https://user-images.githubusercontent.com/25644062/76550651-d1ddb100-64d5-11ea-97f1-411de2e44275.png)

## 期待する見せ方・挙動 / Expected Behavior
- 翻訳を修正する
（案）Need to be hospitalized

補足：hospitalize (入院させる) や discharge (退院させる) は他動詞で、「入院する必要がある」としたい場合、受動態になるかと思います。
私も英語ネイティブではないので、誤りがございましたら申し訳ございません。

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://i18n-covid-tokyo.netlify.com/en/flow にアクセスする

## 動作環境・ブラウザ / Environment
- Windows 10 Home
- Chrome バージョン: 80.0.3987.132（Official Build） （64 ビット）

## 補足情報
- 現時点での i18n 環境 https://i18n-covid-tokyo.netlify.com/ でも発生しております。
- 翻訳用スプレッドシートは、現在「You need permission」と表示されてアクセスできず、確認できておりません。

他言語について
- 韓国語は、該当箇所が日本語のまま表示されております。
- 中国語（簡体字/繁体字）は、Google翻訳で確認したかぎりでは問題なさそうでした。

**Comment by sidemt** [comment]
取り急ぎ対応します。
既存のIssueは見つけられなかったのですが、すでに翻訳チームで対応済みでしたらこちらはクローズしてください。

**Comment by nuwaa** [comment]
@sidemt 
翻訳用スプレッドシートにて事実確認いたしました。
105行目がこれに該当し、対応するファイルは components/flow/FlowPcHospitalized.vue のようですね。

**Comment by sidemt** [comment]
@nuwaa 
ありがとうございます。対応するファイルはコメントいただいた通りでした。
加えて、スマートフォン版では components/flow/FlowSpHospitalized.vue という別のファイルを参照しているようでしたのでこちらも合わせて修正しておこうと思います。

**Comment by halsk** [comment]
ありがとうございました。修正しました。
