### ISSUE TITLE
[i18n]「都営地下鉄」の中文翻訳の訂正

### ISSUE THREAD

**Issue by nuwaa** [tokyo-metropolitan-gov/covid19#1284]
## 起こっている問題 / The Problem
- 誤字のまま公開されてしまっている

## スクリーンショット / Screenshot

[繁体字]
![image](https://user-images.githubusercontent.com/3688822/76560711-2177a900-64e5-11ea-93b0-bfc8518d0190.png)

[簡体字]
![image](https://user-images.githubusercontent.com/3688822/76560874-79161480-64e5-11ea-89b1-557fcff48af7.png)

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)
- 繁体字: 都營地下鐵 -> 都營地鐵
- 簡体字: 都营地下铁 -> 都营地铁

## 起こっている問題の再現手段 / Steps to Reproduce
https://stopcovid19.metro.tokyo.lg.jp/zh-tw/
および
https://stopcovid19.metro.tokyo.lg.jp/zh-cn/
にアクセスする。

## 動作環境・ブラウザ / Environment
- 全OS
- 全ブラウザ

**Comment by PichuChen** [comment]
In zh-TW, 都營地鐵 and 都營地下鐵 are fine, And it's 都營地下鐵 with wikipedia with zh-TW
https://zh.wikipedia.org/wiki/Talk:%E9%83%BD%E7%87%9F%E5%9C%B0%E4%B8%8B%E9%90%B5

But it also has argument in 2016......

**Comment by nuwaa** [comment]
@PichuChen 
- Evidence
[https://github.com/tokyo-metropolitan-gov/covid19/pull/1286#issuecomment-598400752](https://github.com/tokyo-metropolitan-gov/covid19/pull/1286#issuecomment-598400752)

The TOEI TRANSPORTATION says 都營地鐵 / 都营地铁 on itself.
