### ISSUE TITLE
[周知] 翻訳シートのURLが変わりました（現在閲覧のみ）

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1290]
**※現在、#872 の対応中ため、翻訳シートは更新不可にしてあります。**

100名以上が編集しようとすると編集ができなくなるという制限に引っかかりまして、一旦新しくシートをこちらに作りました。お手数をおかけしますが、皆様こちらをご利用ください。
https://docs.google.com/spreadsheets/d/1avT6QGInyQseYjoc_TxL8RPZfutyvrv4BtJkXfk1Nko/edit?usp=sharing
（翻訳管理については、今後Transifex などの翻訳サイトへの移行を検討中です。）

**Comment by nuwaa** [comment]
@halsk おはようございます。

私はアクセスできているので、設定状態を確認しました。
![image](https://user-images.githubusercontent.com/3688822/76572057-53483a00-64fc-11ea-8160-5fa6fc803ca8.png)

ここを私が「リンクを知っている全員」に変更すればよろしいですか?

**Comment by halsk** [comment]
@nuwaa さん
どうもこちらの制限に引っかかったようです。
![image](https://user-images.githubusercontent.com/16509/76572313-0f096980-64fd-11ea-8c95-a2af2d67fc71.png)
一旦シートを作り直しますので、しばらくお待ち下さい。

**Comment by nuwaa** [comment]
あれ? 私も読めなくなった。。。

**Comment by nuwaa** [comment]
念のため、ノウハウ共有です。
私の場合、複数人でGoogleスプレッドシートをいじる場合は、まず最初に自分自身を招待することを癖付けています。
そうしておくことで、「リンクを知っている全員」のアクセスが変なことになっても、引き続きアクセス可能となるので。

**Comment by halsk** [comment]
オーナーを移したこともあり、シートのURLが変わりました。
大変お手数ですが、今後こちらをご利用ください。
https://docs.google.com/spreadsheets/d/1avT6QGInyQseYjoc_TxL8RPZfutyvrv4BtJkXfk1Nko/edit?usp=sharing
