### ISSUE TITLE
「都庁来庁者数の推移」の凡例が、言語切替時にうまく反映されない

### ISSUE THREAD

**Issue by af12066** [tokyo-metropolitan-gov/covid19#1292]
## 起こっている問題 / The Problem
- トップページ「都庁来庁者数の推移」の凡例「第一庁舎計」「第二庁舎計」「議事堂計」が、言語切替時に選択言語にうまく切り替わらない場合があります。
- 「検査実施数」の凡例は正常に切り替わっています

## スクリーンショット / Screenshot

<img width="1087" alt="Screen Shot 2020-03-13 at 9 04 29" src="https://user-images.githubusercontent.com/10768439/76577754-aa084080-6509-11ea-903a-b2c7d85704f5.png">

## 期待する見せ方・挙動 / Expected Behavior
- 選択した言語の凡例が表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 言語が日本語の状態で、トップページを開く
2. セレクトボックスから、言語を日本語以外にする
3. セレクトボックスから、再度言語を日本語にする

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by rozeo** [comment]
こちらIssue #1227、並びに #1182 に関連するものかと思われます。
PR #1250の Deploy Previewをこちらで確認した限りでは問題なさそうに見受けられます。
https://deploy-preview-1250--i18n-covid-tokyo.netlify.com/

**Comment by halsk** [comment]
取り込んでみました。いかがでしょうか？
dev環境でご確認ください。
http://dev-covid19-tokyo.netlify.com/
解消されていれば、close いただければ。

**Comment by af12066** [comment]
確認できました！ご対応ありがとうございました。
