### ISSUE TITLE
要望：他サイトにある「 医療機関（病院）の状況」を東京都版にも付けて欲しい

### ISSUE THREAD

**Issue by mikage-961pro** [tokyo-metropolitan-gov/covid19#1293]
## 改善詳細 / Details of Improvement
神奈川県（https://www.pref.kanagawa.jp/osirase/1369/ )にある医療機関（病院）の状況を東京都のバージョンを作成して欲しい。

## 期待する見せ方・挙動 / Expected behavior
- 実装すれば近くの病院の状況が見れる

**Comment by halsk** [comment]
申し訳ありません。確認したところ難しいとのことでした。クローズさせていただきます。
