### ISSUE TITLE
「やさしい日本語」のルビタグ対応

### ISSUE THREAD

**Issue by shamrock1976** [tokyo-metropolitan-gov/covid19#1295]
## 改善詳細 / Details of Improvement
- いま用意されてる漢字かな交じりのやさしい日本語ですが、ルビの見せ方を「日本語（にほんご）」ではな<ruby>タグでできたら見やすいと思います。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by furandon-pig** [comment]
この理解で合っていると思うのですが、 `./assets/locales/ja-Hira.json` にある「やさしい日本語」のデータについて念のため仕様を確認させてください。
 * https://github.com/tokyo-metropolitan-gov/covid19/blob/development/assets/locales/ja-Hira.json

ルビを振るべき単語は以下のように、文字列先頭から始まる場合を除き、空白スペースで区切られた単語で始まり、全角の `（` `）` でルビとなる平仮名が記載されているという理解であっていますか？

```
例）
  "検査陽性者の状況": "あたらしいコロナウイルスの 病気（びょうき）になった 人（ひと）",
→「病気」と「人」という単語にそれぞれ「びょうき」と「ひと」というルビを振る。
```

**Comment by MaySoMusician** [comment]
表記の仕様が明確に決まっているわけではありませんが、おおよそそういった形で書かれているはずです。

**Comment by ryo-a** [comment]
今見た限りだと
```
"Apple Safari (macOS) 最新版": "Apple Safari (macOS) 一番（いちばん）新（あたら）しいもの",
```
のように、欧文単語のあとには半角かっこ `(` `)` が含まれているようです。

**Comment by MaySoMusician** [comment]
> 今見た限りだと
> 
> ```
> "Apple Safari (macOS) 最新版": "Apple Safari (macOS) 一番（いちばん）新（あたら）しいもの",
> ```
> 
> のように、欧文単語のあとには半角かっこ `(` `)` が含まれているようです。

こちらに関しては、「Safari」に対して「macOS」とルビを振るようなものではないと思われます

**Comment by MaySoMusician** [comment]
ルビタグの対応なのですが、Transifexとの連携の都合上、GitHub上で `ja-Hira.json` を編集するのが難しい状況です。
（Transifexで更新されて置き換わってしまうため）
翻訳を使用する側でやさしい日本語のときのみ動的にルビタグを生成する、などといった攻め方になるのかなと思っております。（より良い案をお待ちしております）

**Comment by ryo-a** [comment]
`Safari (macOS)` はルビの例としては不適切でしたね。すみません。
ただ、そういったルビ以外のカッコも含まれているようなのでどう対応するか考える必要はありそうです。

ルビにするべき部分のみTransifex側で別の記号を使い（例えば`＜日本語：にほんご＞`など）、やさしい日本語の時のみルビをそこから動的に生成する、とかはアリなのでしょうか

**Comment by MaySoMusician** [comment]
全角の（）がルビではなく注記として用いられてる部分もあるので、漢字の後ろのルビ用の括弧を異なるもので入力する、というルールを作るのは不可能ではないとも思います。
その場合はSlack・GitHub上のissue・TransifexのAnnouncement機能等で告知することになるかと。
ただ、可能であればそういったイレギュラーな対応は少ない方が、翻訳者にとっても楽ではあります

**Comment by furandon-pig** [comment]
ちょっと処理が煩雑ですが、現状の `assets/locales/ja-Hira.json` についても以下のコードで漢字とルビが抽出できるようです。
(考え方としてはルビになる文字列は `<漢字の連続|カタカナの連続|アルファベットの連続>（<ひらがな>）` のパターンであると想定し、このパターンにマッチした漢字・ルビのペアを抽出するというものです)
```js
const fs = require('fs');

parse_rubi = (str) => {
  if (typeof str !== 'string') {
    return [];
  }
  // 「機械（きかい）に 保存（ほぞん）される」ような文字を以下の配列にする。
  // => [ "機械（きかい", "に 保存（ほぞん" ]
  let texts = str.split('）');

  rubi_data = [];
  for(var i in texts) {
    // 文字列が「（」を含む場合は漢字とルビに分けられる。
    if (texts[i].match('（')) {
      // 「免責事項\n（東京都（とうきょうと）の 責任（せきにん） について）」のような、
      // ルビではない「（」を考慮する処理。
      // 文字列に複数の「（」が含まれる場合は、最後の一個を残して「（」を除去する。
      for (var j = 0; j < (texts[i].split('（').length - 2); j++) {
        texts[j] = texts[j].replace(/（/, '');
      }

      // 「（」の右辺左辺がそれぞれ漢字、ルビになる。
      // 「かんがえます\n（ひとつの会社（かいしゃ）」のような文字列を想定し、ここで改行文字を消しておく。
      elm = texts[i].replace(/\n/g, '').split('（');
      if (elm.length > 2) {
        // 「かんがえます\n（ひとつの会社（かいしゃ）」のような文字列は配列要素が2より大きくなる。
        // この場合、最初の要素は不要(漢字でもルビでもない)ので除去する。
        elm.splice(0, 1);
      }
      var word = elm[0];
      var rubi = elm[1];

      // 以下の文字を除去してゆき、連続した漢字で構成される部分を切り出す。
      // 例）「データ の 数字」 => 数字
      word = word
        .replace(/ /g, '')   // 半角スペース
        .replace(/　/g, '')  // 全角スペース
        .replace(/.*?\}/g, '')  // "}"
        .replace(/.*?\)/g, '')  // ")"
        .replace(/\n/g, '')  // 改行
        .replace(/ /g, '')   // 半角スペース
        .replace(/　/g, '')  // 全角スペース
        .replace(/.*?[0-9]/g, '')   // 半角数字
        .replace(/.*?[０-９]/g, '') // 全角数字
        .replace(/.*?\}/g, '')  // "}"
        .replace(/.*?\)/g, '')  // ")"
        .replace(/.*?[あ-ヴ・※]/g, '')  // ひらがなと「・」と「※」
        .replace(/.*?[、。「」]/g, ''); // 句読点とカギカッコ

      word.match(/([ァ-ヶ]*?)$/);
      if (RegExp.$1 !== '') word = RegExp.$1

      word.match(/([A-Za-z]*?)$/)
      if (RegExp.$1 !== '') word = RegExp.$1

      word.match(/([亜-黑]*?)$/);
      if (RegExp.$1 !== '') word = RegExp.$1

      if (word == '' || rubi.match(/[亜-黑]/)) {
        // 以下の「（どうが）」のように、対応する漢字が存在しないもの(ルビではない)や、
        // ここまでの処理で漢字が切り出せなかったものは漢字・ルビのデータから除外する。
        // 「ただしい 手（て）の あらいかた（どうが）」
        continue;
      }

      rubi_data.push({
        'word': word,
        'rubi': rubi
      });
    }
  }
  return rubi_data;
}

// 実際にja-Hira.jsonのデータから漢字・ルビのペアを抽出してみる。
obj = JSON.parse(fs.readFileSync("assets/locales/ja-Hira.json"));
Object.keys(obj).map((key) => {
  let rubi = parse_rubi(obj[key]);
  for (var i in rubi) {
    console.log(`'${rubi[i].word}', '${rubi[i].rubi}'`);
  }
});
```

**Comment by furandon-pig** [comment]
実行例はこんな感じです。
```sh
$ git clone https://github.com/tokyo-metropolitan-gov/covid19.git
$ cd covid19
$ # sample.jsには前述のソースコードが記載されていると想定。
$ node sample.js | sort | uniq | head -n10
'Cookie', 'クッキー'
'プライバシーポリシー', 'あなた のじょうほう を とりあつかう とき の Google の かんがえ、きめていること'
'JavaScript', 'ジャバスクリプト'
'オフ', 'OFF'
'オン', 'ON'
'与', 'あた'
'中', 'なか'
'人', 'ひと'
'人達', 'ひとたち'
'今', 'いま'
$
$ node sample.js | sort | uniq | tail -n10
'除', 'のぞ'
'陰性', 'いんせい'
'陽性', 'ようせい'
'集', 'あつ'
'電話', 'でんわ'
'電話番号', 'でんわばんごう'
'静', 'しず'
'頼', 'たよ'
'風邪', 'かぜ'
'高', 'たか'
```

**Comment by shunito** [comment]
ルビ記法の参考情報として

青空文庫のルビ
青空文庫のルビ記法は「《》」を親文字の後ろにつけます。これだけだと親文字の範囲が不明確なので、親文字の始まる前に「|」を置いて機械的な変換の助けにしています。
https://www.aozora.gr.jp/aozora-manual/index-input.html#markup

でんでんマークダウンのルビ
でんでんコンバータという、マークダウン拡張からValidなEPUBを生成できるサービスで利用されている記法です。「{親文字|るび}」と中括弧とバーティカルバーで親文字とルビの範囲を明確に決めることができます。ただ、中括弧だとi18nの変数置換の機能とかぶっちゃいます。
https://conv.denshochan.com/markdown#ruby

例えば「|親文字（るび）」という記法にすると機械的な変換がしやすいかもしれません。
「|」バーティカルバーは今のところやさしいにほんごでは利用されていないようです。

変換タイミングとしては、SSRで生成しておいて利用するようにしないと言語変更して表示完了後に再度表示がガタガタっと変わっていく感じになってしまいそうですね。

**Comment by takahashim** [comment]
こんにちは、青空文庫記法のparserをいじったりしている者です。

@shunito さんによる青空文庫のルビ記法への指摘について：

> これだけだと親文字の範囲が不明確なので、親文字の始まる前に「|」を置いて機械的な変換の助けにしています。

一般的にはそのとおりなのですが、@furandon-pig さんのsample.jsを手元で試してみた限りでは、今回は`｜`なしの記法だけでも大丈夫なようです。これは、

* 漢字にはとにかくルビをふる（ルビのない漢字とルビのある漢字を区別する必要がない）
* 必要であれば半角空白文字を入れて分かち書きにすることで、親文字の区切りに代用できる
* （小説等でたまにある）長めの節に対する、読みと関係ないルビは必要なさそう（[カクヨムのルビの例](https://kakuyomu.jp/help/entry/notation)にある `｜紅蓮の炎《ヘルフレイム》`みたいなものです）

という今回のルビの特性によるものかと思われます。

青空文庫のルビ記法を使うと、例えば以下のようになります。

```
いつも いく お医者《いしゃ》さんに 相談《そうだん》しても よい です。
免責事項\n（東京都《とうきょうと》の 責任《せきにん》 について）
```

なお、青空文庫のルビ注記での親文字自動判別ルールは、sample.jsとは若干異なり、 `<漢字の連続|カタカナの連続|平仮名の連続|アルファベットの連続>《<任意の文字列>》` となっています。でも、今回は「平仮名の連続」へのルビは不要そうなので、@furandon-pig さんのルールに揃えて `<漢字の連続|カタカナの連続|アルファベットの連続>《<任意の文字列>》` で良さそうです。

他に気になるのは @MaySoMusician さんの書かれている原文との衝突ですが、今のところは`《`も`》`もリポジトリ内で使われていないようです。

**Comment by shunito** [comment]
@takahashim ありがとうございます。
「|」をつける意図としては、文字種での判別が複雑になりそうだったので、`|任意の文字列1《<任意の文字列2>》`で正規表現で一律ヒットさせてしまって `<ruby>任意の文字列1<rt>任意の文字列2</rt></ruby>` にしてしまうのが楽かなぁ、という趣旨でした。

**Comment by takahashim** [comment]
確かに指摘はごもっともで、parserの堅牢さからいくと`｜`のような開始記号がある方が安心・確実ですよね…。

とはいえ、

* Transifexで、マークアップに特に慣れてない人が編集する場合、開始記号がない方が分かりやすそう
* 他にも特殊な記法（外字とか）が入ってくるとさらに解析の難易度が高まる懸念もあるが、今回はそういった記法は考慮しなくて良さそう

という理由で大丈夫かなあ、と思いました。

それと文字種については、ES2018以降では[Unicodeの文字プロパティ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes)が正規表現で使えるようなので、比較的なんとかなりそうな期待があります（Nodeは詳しくないので、package.jsonに書かれている`>=10.19.0`で安定して使えるかはちょっと自信ないです…）。

**Comment by shunito** [comment]
なるほど。こんな感じかな、と思いつつやってみていますが、思ったようにマッチせず。。
`regex = new RegExp('[\s]?(\\p{sc=Han}.*?)《(.*?)》','gu');`
下は安定して取れますね。
`RegExp('[\s]?(.*?)《(.*?)》','ug');`
でも近いところまで来ている感じがします。

SSRのタイミングでテキストノードだけ置換を実行する方法は、ちょっとわかりません。詳しい方いないかな。

**Comment by takahashim** [comment]
パターンでいうと、

```js
const regex_han = new RegExp('(?:^|[^\\p{sc=Han}])(\\p{sc=Han}+?)《(.+?)》','gu');
const regex_kata = new RegExp('(?:^|[^\\p{sc=Kana}])(\\p{sc=Kana}+?)《(.+?)》','gu');
```

みたいな感じでどうでしょうか。

**Comment by MaySoMusician** [comment]
> それと文字種については、ES2018以降では[Unicodeの文字プロパティ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes)が正規表現で使えるようなので、比較的なんとかなりそうな期待があります（Nodeは詳しくないので、package.jsonに書かれている`>=10.19.0`で安定して使えるかはちょっと自信ないです…）。

正規表現については解読に時間がかかるので 😅 取り急ぎこちらのみ
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility)によれば、Unicode property escapesはNode.jsでは10.0.0から使えるようなので、本プロジェクトでも問題なく使用できるはずです

**Comment by MaySoMusician** [comment]
また、正規表現のパターンについてですが、条件分岐が多くて困る！というような場合（例えば、漢字の前にスペースがあったり無かったりしてパターンが書きにくい、など）は、Transifexにある訳文の方を変更することもできます。

基本的に文言の変更が無ければ訳文の方を調整することは可能ですので、こちらでご報告ください。また文言の変更が必要になる場合も、関係各所に事情を説明すれば変更できる場合もあります。

**Comment by MaySoMusician** [comment]
> SSRのタイミングでテキストノードだけ置換を実行する方法は、ちょっとわかりません。詳しい方いないかな。

#2535 にて別件ではありますが `nuxt-i18n` 自体に手を加える必要性が出てきていますので、もしかしたら本件についても `nuxt-i18n` を改造してしまう解法が取れるかもしれません。

**Comment by hello-iamsisi** [comment]
横から失礼します。これから翻訳レビューを担当します。議論のご参考に日本語学校で使う「みんなの日本語」中級N3、N2教科書の画僧を貼っておきます。
ルビは漢字の上にあります。また神戸の震災時の経験から、緊急文はいっそ「ひらがな」と「句読点」で全文を書いたほうが初級レベル（N1）のかたも読めると思います。漢字の後に（ひらがな）の形が決定であればこのコメントは見逃してください。

<img width="722" alt="N3N2" src="https://user-images.githubusercontent.com/62226995/77866209-0fc82c80-726d-11ea-94c1-ab67272db236.png">

**Comment by MaySoMusician** [comment]
@hello-iamsisi 資料を共有していただきありがとうございます。
本件でHTMLの `<ruby>` タグに対応する予定ですので、漢字の上にルビが振られるようになる予定です。

漢字かな交じりかひらがなのみかについてですが、本プロジェクトでももともとひらがなのみの「やさしいにほんご」を使用していました。その後、 https://github.com/tokyo-metropolitan-gov/covid19/issues/595#issue-576688077 にて引用されている島根県資料や https://github.com/tokyo-metropolitan-gov/covid19/issues/848#issuecomment-596465162 などの提案があり、漢字かな交じりの「やさしい日本語」に移行しました。

オリンピック準備局の[多言語対応協議会ポータルサイト](https://www.2020games.metro.tokyo.lg.jp/multilingual/references/easyjpn.html)では弘前大学が研究した『災害時の情報提供としての「やさしい日本語」』というものも紹介されていましたが、これについては惜しくも今年1月に[ホームページが閉鎖](http://human.cc.hirosaki-u.ac.jp/kokugo.html)してしまっていました。災害時・緊急時のやさしいにほんごの扱いに関して何か公開可能な資料があれば、漢字を含めるか否かも検討しやすくなるかもしれません。

**Comment by shamrock1976** [comment]
こちらの件、ご対応ありがとうございます。最初全部ひらがなでしかも片言で書かれてたのでどうしようかなと思ったのですが、改善されてよかったです。「子供も読める」って言う方向性で作るのがいいんですけどね。（全部ひらがなは「漢字が読めない人向け」としてはありだとは思いますが）

「やさしい日本語」に関しては全国で外国人の受け入れで活動している人たちがたくさんいるのでそういう人達の参加を促しても良いと思います。アクセシビリティは（色弱対応などもですが）「正解がないもしくは複数あるもの」でもあります。

やさしい日本語は自動翻訳をかけてもうまくいくケースが多いので、きっと未対応の言語でも読める人が増えると思います。

公開、楽しみにしています。

**Comment by shgtkshruch** [comment]
`<ruby`> タグに置き換えるモックアップを作ってみました。
Vue コンポーネントの `<template>` 内の多言語化している文字列を対象にしています。
グラフ内のツールチップや凡例の対応はまだ調査中です。

正規表現でやさしい日本語をパースして、`<ruby>` タグをつけるコンポーネント（仮で `t-i18n` とします）を試しに作りました。
locale が `ja-basic` 以外の場合は通常通り翻訳した文字列を返します。

今まで `$t` で文字列を埋め込んでいたコードを以下のように変更しています。
```diff
<span>
- {{ $t('hoge') }}
+ <t-i18n :text="$t('hoge')" />
</span>
```
シンプルな Vue コンポーネントなので、SSR した際は以下のようなマークアップを生成します。
（`span` が多いのはなんとかしたい...）
```html
<span>
  <span>あたらしいコロナウイルスの </span>
  <span>
    <ruby>
      病気
      <rp>(</rp><rt>びょうき</rt><rp>)</rp>
    </ruby>
  </span>
  <span>になった </span>
  <span>
    <ruby>
      人
      <rp>(</rp><rt>ひと</rt><rp>)</rp>
    </ruby>
  </span>
 <span>
```

| Before  | After |
| ------------- | ------------- |
| ![スクリーンショット 2020-03-30 20 51 44](https://user-images.githubusercontent.com/5207601/77909432-4c754180-72c8-11ea-94fe-ec8f45f31c56.png) | ![スクリーンショット 2020-03-30 20 51 24](https://user-images.githubusercontent.com/5207601/77909426-4a12e780-72c8-11ea-98fc-fc0c79ebe2c1.png) |

レンダリングパフォーマンスですが、ローカルで動かした感じでは体感速度にあまり違いは無いように感じました。

### development
[![Image from Gyazo](https://i.gyazo.com/bb12ee954e2431e276cc52414b214a0f.gif)](https://gyazo.com/bb12ee954e2431e276cc52414b214a0f)

### local with `<ruby>`
[![Image from Gyazo](https://i.gyazo.com/774a7dc11652235a18422431f7bed31e.gif)](https://gyazo.com/774a7dc11652235a18422431f7bed31e)

**Comment by shunito** [comment]
素晴らしい。恐らくそういう対応が必要だろうな、と思っていましたが、対応箇所が多いので難しいかもと考えていました。
良ければ私も検証お手伝いしますので、試せるリポジトリなりブランチがあれば教えていただければと思います。

**Comment by shgtkshruch** [comment]
ありがとうございます！
一緒に検証いただけると助かります。
commit 整理するので少々お待ち下さい。

**Comment by shgtkshruch** [comment]
@shunito 
#2628 に WIP であげましたので、お時間があるときに検証お願いいたします。

**Comment by hello-iamsisi** [comment]
@MaySoMusician 

>本件でHTMLの <ruby> タグに対応する予定ですので、漢字の上にルビが振られるようになる予定です。
上記ならびに経緯の解説ありがとうございます。とお返事する間に素晴らしいものができていましたね！

**Comment by hello-iamsisi** [comment]
＠shgtkshruch　美しい。ありがとうございます。慣れ親しんだ教科書に近いため、読みやすい画面になっていると思いました。

**Comment by MaySoMusician** [comment]
現在、主な議論・連絡は #3116 に移行しております。issueを一本化させるため本issueはcloseします。

なおこれは本issueの再openを妨げるものではありません。再openが必要な場合はこちらにコメントください。
