### ISSUE TITLE
岐阜県版追加

### ISSUE THREAD

**Issue by rnsk** [tokyo-metropolitan-gov/covid19#1307]
## 起こっている問題 / The Problem

- 岐阜県版がリリースされているのでforkedSites.mdに追加する

**Comment by rikupin1105** [comment]
やります

**Comment by rnsk** [comment]
ありがとうございます。
URL: https://covid19-gifu.netlify.com/
リポジトリ : https://github.com/CODE-for-GIFU/covid19

**Comment by rikupin1105** [comment]
#1309 このプルリクで書き方が変わるかもしれないので、このプルリクの後でいいですか？

**Comment by rnsk** [comment]
はい、大丈夫です。
よろしくお願いいたします。
