### ISSUE TITLE
yarn installでこける

### ISSUE THREAD

**Issue by yokinist** [tokyo-metropolitan-gov/covid19#131]
[![Image from Gyazo](https://i.gyazo.com/e57d05731926a773064bce27ca854b79.png)](https://gyazo.com/e57d05731926a773064bce27ca854b79)
* どうやらvue-spinner周りがうまくいってないぽい

https://github.com/tokyo-metropolitan-gov/covid19/runs/478874299

**Comment by halsk** [comment]
あらら、一旦リバートしますか？
