### ISSUE TITLE
「企業の皆様・はたらく皆様へ」ページ内のリンクが外部リンクであると分かりやすくする

### ISSUE THREAD

**Issue by sidemt** [tokyo-metropolitan-gov/covid19#1317]
## 改善詳細 / Details of Improvement
「企業の皆様・はたらく皆様へ」ページ
https://stopcovid19.metro.tokyo.lg.jp/worker

- 外部リンク・新しいタブが開くリンクであることを示すアイコンを表示する
- 括弧書きでリンク先サイトの組織名などを表示する

このページ内から様々なサイトへリンクされているので、閲覧していて分かりにくく感じました。

## スクリーンショット / Screenshot

![external_link_01](https://user-images.githubusercontent.com/25644062/76597816-b493fb80-6544-11ea-940c-a7c593034f3a.png)

## 期待する見せ方・挙動 / Expected behavior
例えば「新型コロナウイルス感染症が心配なときに」ページ下部のリンクなどは分かりやすく表示されていると思います。
![external_link](https://user-images.githubusercontent.com/25644062/76597513-fe301680-6543-11ea-9932-669f58bc566a.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by sidemt** [comment]
誤って途中で投稿してしまいました…失礼しました。
改善提案ですがよろしくお願いいたします。

**Comment by TM82** [comment]
こちら対応いたします！
