### ISSUE TITLE
新規グラフ追加：新宿区への来訪者数の推移

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#1318]
新規グラフの作成にご協力いただける方を募集しています。
ご不明な点は随時お答えします。

## 利用データ
- 新宿区への来訪者数（日別、7:30-8:30の平均値）
- 期間：2/1〜3月末（毎日更新予定）
- サンプルデータ：[13104_daily_visitor.csv](https://drive.google.com/a/linkdata.jp/file/d/1EO2U50DvNAJg5e3M7_Ea0xTK10JvYJ0H/view?usp=sharing)

## 見せ方
- 棒グラフ
- 集計単位：1週間（月曜〜日曜）
- 演算：1日あたりの平均値
- 実数値と相対値で切替可能にする
- 相対値は2月3日の週を基準に算出（都営地下鉄のグラフと同様）

## 注記事項
- 本番データとの接続部分は別途実装するため、まずはサンプルデータをそのまま使ってください
- グラフタイトルや注釈、ラベル表記等の内容は調整中のため変更となる可能性があります

## 完成イメージ
- 実数値
<img width="543" alt="スクリーンショット 2020-03-14 16 34 25" src="https://user-images.githubusercontent.com/4206675/76677539-d8257780-6612-11ea-8278-72dd79e62a69.png">

- 相対値
<img width="546" alt="スクリーンショット 2020-03-14 16 34 54" src="https://user-images.githubusercontent.com/4206675/76677543-dcea2b80-6612-11ea-97fb-660ae3c8b23f.png">

**Comment by shgtkshruch** [comment]
まだどなたもアサインされていなければ、実装させていただきたいです。

**Comment by ocean3fish** [comment]
@shgtkshruch ありがとうございます！
ぜひよろしくお願いします！

**Comment by shgtkshruch** [comment]
頂いたデータとスクリーンショットを元に実装をすすめました。

- プルリクエスト(WIP) #1335
- Deploy Preview (Netlify): https://deploy-preview-1335--dev-covid19-tokyo.netlify.com/

認識の齟齬などがありましたら、プルリクエストでコメントをいただければと思います。

また、グラフタイトルや注釈、ラベル表記等が確定しましたらこちらの issue でお知らせいただけると嬉しいです。
文言が確定次第、プルリクエストの方に反映させていただきます。

**Comment by ocean3fish** [comment]
@shgtkshruch 早速ありがとうございます！大変正確に仕上げて頂き感謝申し上げます！
3点ほど調整・変更をお願いしたい事項があるのですが、ご対応頂くことは可能でしょうか？

- ツールチップに表示する数値
おそらく現状、百の位で四捨五入した値が表示されているものと思われるので、小数点以下1桁で四捨五入して1の位まで含めて頂くことは可能でしょうか？
例）555,000 人 → 555,143 人
なお、ご確認頂きやすいように、冒頭のグラフの図を月曜始まりの集計値になるように修正いたしました。

- 表示期間
「直近の日曜日まで」として頂けるでしょうか？
平均値で表示する仕様上、7日間揃ってからの集計とする必要があるためです。
例えば本日時点でのグラフとしては、3/2〜3/8の期間の集計値までが表示されるという想定です。

- 相対値の算出方法
以下の方法で算出して頂けるでしょうか？
(`対象の週の平均値` - `2/3の週の平均値`) / `2/3の週の平均値`
例）2/10〜2/16
(500714 - 555143) / 555143 = -9.80%

**Comment by shgtkshruch** [comment]
@ocean3fish 
確認いただきまして、ありがとうございます！
コメントいただいた3点ともに修正可能ですので、これから対応いたします :D
（グラフ図の更新ありがとうございます、わかりやすくて助かりました 🙏 ）

**Comment by shgtkshruch** [comment]
@ocean3fish 
数値処理やグラフの対象データを修正いたしました！
#1318

### 実数値
![スクリーンショット 2020-03-14 19 09 36](https://user-images.githubusercontent.com/5207601/76679867-66a3f400-6627-11ea-92eb-dab90dddfd10.png)

### ツールチップ
![スクリーンショット 2020-03-14 19 09 50](https://user-images.githubusercontent.com/5207601/76679870-6ad01180-6627-11ea-90bd-33f8e0e2d101.png)


### 相対値
![スクリーンショット 2020-03-14 19 09 41](https://user-images.githubusercontent.com/5207601/76679869-69064e00-6627-11ea-9448-0239d2e52099.png)

**Comment by ocean3fish** [comment]
@shgtkshruch ご対応ありがとうございます！
プレビュー拝見しまして、依頼させて頂いた3点の変更について問題ないことを確認しました！

追加で1点だけ申し訳ありません、実数値のグラフの方、
軸に0を含めない実装にご変更頂いているのですが、
数値の大小を比較する目的の棒グラフでは0をカットしない方が良いとされています。
お手数ですが、0を含める形に戻して頂けるでしょうか🙏

**Comment by shgtkshruch** [comment]
@ocean3fish 

ご確認いただきまして、ありがとうございます！
Y軸、確かにスクリーンショットと違いましたね...
こちらのコミットで 0 を含めるように修正いたしました :)
https://github.com/tokyo-metropolitan-gov/covid19/pull/1335/commits/89ddd12fd41bf67c24c76252c7aca26ca2fca5d4

![スクリーンショット 2020-03-14 22 12 18](https://user-images.githubusercontent.com/5207601/76682645-22255200-6641-11ea-8326-417cef602754.png)

**Comment by ocean3fish** [comment]
@shgtkshruch 早速ありがとうございました！
丁寧なご対応感謝いたします！

以降のグラフタイトルや注釈等は週明けに確定する見込みのため、またこちらでお知らせさせてください。
よろしくお願いします。

**Comment by shgtkshruch** [comment]
@ocean3fish 

> 以降のグラフタイトルや注釈等は週明けに確定する見込みのため、またこちらでお知らせさせてください。

承知しました！
文言等の調整ありがとうございます。
引き続き、よろしくお願いします！

**Comment by ocean3fish** [comment]
@shgtkshruch 
表示するテキストの内容が確定したのと、表示するデータの変更の要望があったのですが、ご対応頂くことは可能でしょうか？

## 変更点
1. 実数値のグラフは削除（実装頂いたところ大変申し訳ありません…！）
1. 集計対象データを平日のみにする
→よろしければ2-3月の日付を平日と休祝日に分類したデータを作成してあるのでご利用ください：[calendar.csv](https://drive.google.com/a/linkdata.jp/file/d/1hwiMBznAejLa_uM1WrOr2iXEAR2GaUPf/view?usp=sharing)
1. 棒グラフは2/10の週以降を表示
1. タイトル変更：
`新宿区エリアの来訪者推移（参考値）`
1. 注釈変更：
```
2月3日～2月7日の来訪者数 (※1) の平均値 (※2) を 基準としたときの相対値
※1) ヤフーに蓄積された位置情報データなどを元に算出した参考値
※2) 土・日・祝日を除く7:30~8:30の1週間平均値
```
6. データの掲載期間を明示（グラフと出典表示の間に追加）
`※本データは2020年3月31日までの掲載となります`
7. コーピーライト表記変更
```
 (C)Yahoo Japan
 出典：[ヤフー・データソリューション](https://ds.yahoo.co.jp/datapolicy/)
```
## 実装イメージ
<img width="547" alt="スクリーンショット 2020-03-17 20 49 20" src="https://user-images.githubusercontent.com/4206675/76855510-a3c0ee00-6894-11ea-8688-d54a1b1129d1.png">

**Comment by shgtkshruch** [comment]
@ocean3fish 

文言等の確認ありがとうございます！

> 1. 実数値のグラフは削除

承知しました！
実装シンプルになるので、大丈夫です :)

> 2. 集計対象データを平日のみにする

こちらも対応可能です。
平日と休祝日に分類したデータもありがとうございます 🙏 
内部的に採用している日付関連のライブラリ（day.js）でも平日と休日の判定ができるのですが、こちらを使うと、

- 最初に頂いたデータ構造がそのまま使える（平日・休日のフラグがなくても OK）
- もし休日のデータがあってもプログラム的に入らないことを保証できる

ので、今回はこちらで実装しようと思っています。

また、3 ~ 7 で頂いた表示期間や文言の修正も対応可能です。
文言が少し増えるので、他のグラフと並べたときに余白などの調整が必要かもしれませんが、このあたりはやりながら調整させていただきます。

頂いたイメージを元に実装をすすめて、明日にはこちらの issue で共有させていただきます。

**Comment by shgtkshruch** [comment]
@ocean3fish 

昨日いただいた変更点を実装いたしました！
お手すきの際にご確認お願いいたします。

Netlify のプレビューのリンクはこちらになります。
https://deploy-preview-1335--dev-covid19-tokyo.netlify.com/

![スクリーンショット 2020-03-18 19 08 14](https://user-images.githubusercontent.com/5207601/76949405-d5e15700-694b-11ea-8ee6-db85e2924371.png)

**Comment by ocean3fish** [comment]
@shgtkshruch 迅速に仕上げて頂き本当にありがとうございます！
内部で本番用データの準備に時間を要しているようで、公開までにもう少しお待ち頂く形になってしまい申し訳ありません🙏
PRをオープンにして頂けるタイミングになりましたらまたご連絡させて頂きます。

**Comment by MaySoMusician** [comment]
#1852 で要望があがった翻訳キーを #1857 にて追加しました
```json
"新宿区エリアの来訪者推移（参考値）": "新宿区エリアの来訪者推移（参考値）",
"2月3日～2月7日の来訪者数 (※1) の平均値 (※2) を 基準としたときの相対値": "2月3日～2月7日の来訪者数 (※1) の平均値 (※2) を 基準としたときの相対値",
"※1) ヤフーに蓄積された位置情報データなどを元に算出した参考値": "※1) ヤフーに蓄積された位置情報データなどを元に算出した参考値",
"※2) 土・日・祝日を除く7:30~8:30の1週間平均値": "※2) 土・日・祝日を除く7:30~8:30の1週間平均値",
"※本データは2020年3月31日までの掲載となります": "※本データは2020年3月31日までの掲載となります",
"出典: {source}": "出典: {source}",
"ヤフー・データソリューション": "ヤフー・データソリューション"
```
「出典: ヤフー・データソリューション」については `<i18n>` タグによる入れ子構造が使用できます

`期間：M/D〜M/D` については `期間: {duration}` が既に存在しますのでこちらが使えるはずです
