### ISSUE TITLE
[i18n] グラフの注釈の文章がやさしい日本語に翻訳されていない

### ISSUE THREAD

**Issue by yutaroyoshikawa** [tokyo-metropolitan-gov/covid19#1322]
## 起こっている問題 / The Problem
- グラフに記載されている注釈の一部にやさしい日本語が翻訳されていない。

## スクリーンショット / Screenshot

<img width="546" alt="スクリーンショット 2020-03-13 18 26 53" src="https://user-images.githubusercontent.com/38146004/76608547-270ed680-6559-11ea-9823-e67cf85e107a.png">

<img width="540" alt="スクリーンショット 2020-03-13 18 27 08" src="https://user-images.githubusercontent.com/38146004/76608564-30983e80-6559-11ea-9bb9-4faab77eaf99.png">

<img width="541" alt="スクリーンショット 2020-03-13 18 27 37" src="https://user-images.githubusercontent.com/38146004/76608577-368e1f80-6559-11ea-8fcb-779ee0df1c01.png">

## 期待する見せ方・挙動 / Expected Behavior
- やさしい日本語での文言が反映されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. スマホもしくはPCにて https://stopcovid19.metro.tokyo.lg.jp/ja-basic/ にアクセス

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by yutaroyoshikawa** [comment]
対応します。

**Comment by perpouh** [comment]
土日祝の方は対応中じゃないかと思います。
https://github.com/tokyo-metropolitan-gov/covid19/pull/1300/files

**Comment by yutaroyoshikawa** [comment]
確かにそうでしたね🙇‍♂️確認不足でした
