### ISSUE TITLE
[i18n] 多言語選択プルダウンメニューのselect要素に対してlabel要素(説明文)を設置

### ISSUE THREAD

**Issue by ishimasar** [tokyo-metropolitan-gov/covid19#1325]
## 改善詳細 / Details of Improvement
以下に示したURLも参照いただければと思いますが、
`select` 要素には
```
<label for="multilingual">多言語対応選択メニュー</label>
<select id="multilingual">
  ~
</select>
```
などで説明テキストと紐付けすることで、
選択やフォーカスしやすくなり、スクリーンリーダーでの機能読み上げにも丁寧に対応できます(1)。

上記が不可能(不自然)な場合、代替として `label` 要素は使用せず `title` 属性でも補うことも提案されていますが、推奨というわけではないようです(2)。
```
<select title="多言語対応選択メニュー">
```

- (1) [H44: テキストラベルとフォームコントロールを関連付けるために、label 要素を使用する](https://waic.jp/docs/WCAG-TECHS/H44.html)

- (2) [H65: label 要素を使用できない場合に、フォームコントロールを特定するために、title 属性を使用する](https://waic.jp/docs/WCAG-TECHS/H65.html)

## スクリーンショット / Screenshot

- ページの該当箇所
<img width="238" alt="コメント 2020-03-13 205216" src="https://user-images.githubusercontent.com/10381147/76618856-ed47cb00-656c-11ea-9b96-b50cf0a7ddc8.png">

- developer tool Auditsでのアラート指摘
<img width="572" alt="コメント 2020-03-13 210118" src="https://user-images.githubusercontent.com/10381147/76619271-cdfd6d80-656d-11ea-9525-27435792fecb.png">

## 期待する見せ方・挙動 / Expected behavior
- ラベル(説明文)を選択・フォーカスしたら多言語プルダウンメニューにフォーカスが合う
- 多言語機能があることがあらかじめ文字読み上げされ、視認できない人でも機能が分かる補助になる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by NumLocker-Japan** [comment]
こちら引き受けます。

**Comment by NumLocker-Japan** [comment]
説明文を多言語化する訳にはいかないので、ひとまず英語にしておきますね。
