### ISSUE TITLE
「東京都主催等 中止又は延期するイベント等」リンク先変更

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1326]
「東京都主催等 中止又は延期するイベント等」のリンク先の変更をお願いします

変更前）
https://www.seisakukikaku.metro.tokyo.lg.jp/information/event02.html

変更後）
https://www.seisakukikaku.metro.tokyo.lg.jp/information/event00.html

**Comment by kebhr** [comment]
対応します。
