### ISSUE TITLE
[i18n] 翻訳ファイルの未反映

### ISSUE THREAD

**Issue by NACK4u** [tokyo-metropolitan-gov/covid19#1341]
## 関連issue / Related Issues
- i18n化総合issue: #680
- [i18n] 翻訳が間に合わないままマージされた翻訳の更新: #872
- [i18n] 翻訳ファイルのチェック・更新 03/13 #1312

## 改善詳細 / Details of Improvement
「都庁来庁者数の推移」の「やさしいにほんご」が、スプレッドシートと実際のサイトで異なっているようです（現在OPEN中の別ISSUE（#1312）の修正対象ファイルに入っていなかったため、別途ISSUE作りました）。

スプレッドシート：
https://docs.google.com/spreadsheets/d/1avT6QGInyQseYjoc_TxL8RPZfutyvrv4BtJkXfk1Nko/edit#gid=0
都庁（とちょう）に 来（き）た 人（ひと）の 数（かず）の　時間（じかん）による　変化（へんか）

サイト：
https://stopcovid19.metro.tokyo.lg.jp/ja-basic/
議事堂（ぎじどう）に 来（き）た 人（ひと）の 合計（ごうけい）

都庁来訪者数は「都庁に来た人」であって、「都庁の議事堂に来た人」の数ではない＆議事堂だと「国会議事堂」と誤認される恐れがあるため、スプレッドシートの記載にあわせたほうが良いと思います。
（なお、類似項目の「都営地下鉄4路線の自動改札出場数」等と書き方をあわせるなら「都庁（とちょう）に 来（き）た 人（ひと）の数（かず）」になりますが、現在スプレッドシートを直せないので、そのまま使用させていただきます）

## 期待する見せ方・挙動 / Expected behavior
- スプレッドシートの記載と一致すること

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by NACK4u** [comment]
こちら対応します。

**Comment by MaySoMusician** [comment]
@NACK4u 
https://github.com/tokyo-metropolitan-gov/covid19/issues/1312#issuecomment-598752455 にてコメント差し上げましたのでご確認お願いいたします。

**Comment by NACK4u** [comment]
確認しました、ありがとうございます。
こちらのissue、重複扱いとしておきます。

**Comment by MaySoMusician** [comment]
Duplicate of #1312
