### ISSUE TITLE
陽性患者数（感染者数）のグラフの右上に前日比を表示

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#138]
・前日の値からの増減数を表示
・推移/累積で値を切り替える必要がある
・「推移」選択時はマイナスの値も取ることがある
・「累積」選択時は0以上の値を取る
![陽性患者数（感染者数）](https://user-images.githubusercontent.com/4206675/75654426-0a45e980-5ca3-11ea-8d99-2559638f68ad.png)

**Comment by mikkame** [comment]
ToolTipが出てるのでそうっぽく見えるだけかもしれませんが
グラフにカーソルを合わせて日付を指定した上で右上を変更する訳ではなく
単純な前日比でいいのでしょうか？

**Comment by halsk** [comment]
前日比、っていうわけではないのではないかなぁ。今日+1だった、みたいな感じでは
ツールチップとは別だと思います。
ですかね？ > @ocean3fish

**Comment by ocean3fish** [comment]
はい、右上の数値は、本日時点においての、前日からの増減を表示するということで、ツールチップと連動させて値を変更するといったリクエストは今の所ありません。
（ただ今後その案も出てくるかもしれませんね）

**Comment by halsk** [comment]
こちら、表の確定版です！！ #139 と関連。
![image](https://user-images.githubusercontent.com/16509/75738752-6746ab80-5d46-11ea-97aa-47846a48565a.png)
