### ISSUE TITLE
検査陽性者の状況　をビジュアルに表示（https://github.com/kaz-ogiwara/covid19/issues/23から移動）

### ISSUE THREAD

**Issue by masayasuyamamoto60** [tokyo-metropolitan-gov/covid19#1381]
![アイデアUI](https://user-images.githubusercontent.com/12755558/76677605-787b9c00-6613-11ea-819a-c3e9840b81cd.jpg)
[チャート案.pdf](https://github.com/tokyo-metropolitan-gov/covid19/files/4332383/default.pdf)

## 改善詳細 / Details of Improvement
コロナウイルスの深刻度を表現するために検査陽性者に関する情報を視覚化することが有効だと考える。それによってパニック行動を回避することにも効果があるはず。
現状の都のサイトでは、カテゴリーごとの人数を源氏香の記号のようなスタイルで表示しているが、実績値を見ても全体像を把握することができない。

そこで、2点を提案する：
A.　2種類の情報に分けることを提案する：
　１．テスト被験者対陽性者
　２．陽性者の現状

B.　パイチャートによる表示
すでにサイト全体でバーチャートが多用されており、混乱気味なので、BIツール風に、最初のチャートにパイチャートをつけて、全体の情報のプロポーションを理解できるようにする。
Aを実現するためには2.を二重のパイチャートで表現する。
特に２．に関しては現状の情報表示は構造化しており、わかりにくくなっているためビジュアル化（棒ブラフ、または多層化したパイチャート）することが望まれる。（制限がある場合には、2つのパイチャートの並列）

## スクリーンショット / Screenshot
添付ファイス参照願います

## 期待する見せ方・挙動 / Expected behavior
- ビジュアル・サンプル作成中

## 動作環境・ブラウザ / Environment
全て
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ocean3fish** [comment]
@masayasuyamamoto60
ご提案頂きありがとうございます。
作成頂いたグラフ案で何点か確認させて頂きたいのですが、「入院中」の他に「通院中」とあるのはどちらから取った情報になるでしょうか？
また、「退院数」の表示が抜けていると思われます。
![図3](https://user-images.githubusercontent.com/4206675/78451563-3947e480-76c1-11ea-9498-6353b871b73b.png)

そして現状だいぶ割合も変化してきているため、イメージされているような見え方になるかどうか、現状の値で一度ご確認頂くと良いかもしれません。
視認性が極端に落ちる可能性も考えられます。

それから、以下のコメントにもあるように、この部分の表示を変更するにはかなり時間を要するものと思われるため、その点ご了承頂けるでしょうか。
https://github.com/tokyo-metropolitan-gov/covid19/issues/1692#issuecomment-600361634

**Comment by masayasuyamamoto60** [comment]
図中の「通院」というのは「退院」の読み違えでした。
申し訳ないです。
また、＃1692のような、情報表示としては改善されているにもかかわらず、慣習化など社会要因もあるようなので、本件の実装法も検討したいと思います。
本件の目的は、現実装では同じようなテーブル（源氏香スタイル）と、縦棒グラフな林立し、全体状況を見渡せるツールが不在だという動機から挙げています。
回答にしばらく（1日程度）時間ください。

**Comment by masayasuyamamoto60** [comment]
図中の「通院」というのは「退院」の読み違えでした。
混乱させて申し訳ないです。
ーーーーーーーーーーーーーーーーーーーーーーー
整理しました。
本件を上げてから、都のページの表示項目が増え状況が変化しています。
以下の改訂版を提案します：
・都の場合、クルーズ船やチャーター便からの陽性判定など数字が錯綜していて複雑であるので、削除。
・依然として実数は把握できるが、リスクの把握といった観点からパーセンテージ表示は有用であると思う。自宅やホテル療養のケースもあるのでなおさら。
・実装の容易さからシンプルなパイチャートに変更。
（添付画像、パワポファイルを参照のこと）
＊実数表示が最上段にあるため、最下段にモジュールとして追加を希望する。
![都COVID19陽性UI案](https://user-images.githubusercontent.com/12755558/78735289-60363d00-7985-11ea-9935-7a0c4931a625.png)
[都COVID19陽性UI案.pptx](https://github.com/tokyo-metropolitan-gov/covid19/files/4447744/COVID19.UI.pptx)

**Comment by ocean3fish** [comment]
@masayasuyamamoto60 
他の優先検討事項が多く長らくお時間を頂いてしまいましたが、こちらのissueについて都に確認が取れました。 
「検査陽性者の状況」は一覧性を確保したいという意向があって現行の見せ方が採用されており、パイチャートでの可視化は割合が少ない場合に見にくくなることが懸念されるため、採用するのは難しいという結論に至りました。
今後また状況が変わり公表する数値の種類が変更となることもあると思われますので、今回の貴重な観点からのご提案、ぜひ今後の参考にさせて頂きたく思います。 
よろしくお願いいたします。

**Comment by masayasuyamamoto60** [comment]
ocean3fishさん
ご確認ありがとうございました。
本件を起票時に問題にしていた、リスクを知るうえで実数よりも割合で見せるほうが無用な不安と混乱を防ぐことができるのではという仮説がありましたが、緊急事態宣言等で新感染者数という数字が問題になっていることもあり、ナイス・トゥ・ハブになってきています。
また、現状で割合を表示するリスクも以下のような点もあることも理解してきました。
・都内での全検査数が同時に集計されないためパーセンテージが正確でない
・PCR検査を受けている人は、通常の人よりかなり感染リスクが高い
ただし、陽性患者の内訳をパイチャートで表示することで、メディアを騒がしている誤解を免れることはできた可能性は高かったのではと思います。

いずれにしても、収束気味の昨今ではもはや新しいパイチャートはなくても良いと思います。
ありがとうございました。
