### ISSUE TITLE
ローディングアイコンを復活させる

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#1382]
##  改善詳細 / Details of Improvement
- シェア機能実装のため、ローディングアイコンを一旦削除した経緯がありました。
- ただやっぱり「あった方が良いのでは」という意見が出てきたので、もし方法があればよろしくお願いします！
![slack-imgs com](https://user-images.githubusercontent.com/4206675/76673384-bfec3300-65e7-11ea-908a-fe488e9b6912.png)

**Comment by amotarao** [comment]
genearate 時、 loader のみレンダリングしていたので、各ページの head が反映されていない状態でした
```vue
<loader v-if="loading" />
<contents v-else>...
```

## 改善

contents もレンダリングするようにすれば、各ページの head が反映されそうです。
```vue
<loader v-if="loading" />
<contents>...
```
とか
```vue
<loader v-show="loading" />
<contents>...
```
とかで

**Comment by nichesuch** [comment]
やります
