### ISSUE TITLE
お知らせの日本語の日付表記が海外向けになっている

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1385]
## 起こっている問題 / The Problem
- トップページお知らせの日付表記が海外向けになっている

## スクリーンショット / Screenshot

<img width="549" alt="スクリーンショット 2020-03-14 11 54 11" src="https://user-images.githubusercontent.com/8909592/76673677-a7314c80-65ea-11ea-85d6-c905ac1036a9.png">

## 期待する見せ方・挙動 / Expected Behavior
- 各言語用の日付表記に改める

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページを開く

## 動作環境・ブラウザ / Environment
すべて

**Comment by UrangUrang** [comment]
作業します。

**Comment by asterisk37n** [comment]
タイトル翻訳と修正箇所が同じでした。併せて変更しました。

**Comment by mikkame** [comment]
取り急ぎこちらの件は元データの問題でした（Excelの文字列が日付に変わってしまったようです）
本件はクローズして、#1456については多言語化系の対応に含めてもらう方向でよろしくお願いします
