### ISSUE TITLE
card の埋め込みリンクを各言語版にする

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1389]
## 起こっている問題 / The Problem
- #1376 
- card の埋め込みリンクが全言語日本語ページ

## スクリーンショット / Screenshot

<img width="553" alt="スクリーンショット 2020-03-14 12 09 22" src="https://user-images.githubusercontent.com/8909592/76673858-a994a600-65ec-11ea-919c-a689dd0cea8b.png">

## 期待する見せ方・挙動 / Expected Behavior
- card の埋め込みリンクを各言語ページにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. 日本語以外のトップページを開き、card のシェアリンクを押す

## 動作環境・ブラウザ / Environment
すべて

**Comment by amotarao** [comment]
対応します

**Comment by amotarao** [comment]
@halsk 
こちらの「うまく動かない」の詳細を知りたいです
https://github.com/tokyo-metropolitan-gov/covid19/pull/1376/files#diff-2ec2ef25606844b918ca76f7ad1ec7a3R164

**Comment by halsk** [comment]
@amotarao さん、「うまくいかない」→ 404になる でした。
いただいた #1380 が直れば、戻して良さそうですね

**Comment by amotarao** [comment]
なるほど！

**Comment by amotarao** [comment]
まだrevertがありませんので、reopenしてメモとして残したほうがよさそうと思います。

**Comment by halsk** [comment]
リオープンしました。
重複するIssue,#1455 は閉じますね。

**Comment by halsk** [comment]
必要な対応：

- [ ] [GitHub Action](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/workflows/ogp_builder.yml)を修正し、多言語版の OGP 画像を保存する（`/static/ogp`とかのディレクトリを作った方が良いかも）
- [ ] 各 card のページの `og:image`, `og:description`、`og:description` を各言語版に修正する
- [ ] #1376 のコメントアウトを外し、ロケール対応をさせる

でしょうか。

**Comment by halsk** [comment]
本日リリース版で、OGP 画像の多言語化が実装される予定です。
`og:description` と `og:title` がまだ変わりません。
どなたか引き継いでいただけると助かります。

**Comment by nard-tech** [comment]
@halsk Slack にも書きましたが，こちら未着手でしょうか？でしたら私やります

**Comment by halsk** [comment]
@nard-tech さん、まだ未着手です。よろしくおねがいします！

**Comment by nard-tech** [comment]
@halsk
承知しました！

**Comment by nard-tech** [comment]
@halsk
`og:title` は多言語化対応済みでしたので，`og:description` のみ修正しました（全角括弧を半角括弧に置き換えて一瞬で完了しましたw）．
しかし，その他の meta タグ内の多言語化は（特に card の埋め込みリンク以外のページで）不十分な気がしたので，その点は別の issue を作ろうと思います．
