### ISSUE TITLE
プルリクをどのブランチに出せば良いのかをREADMEから辿りたい

### ISSUE THREAD

**Issue by chihirof** [tokyo-metropolitan-gov/covid19#1394]
## 改善詳細 / Details of Improvement
- README.md、CONTRIBUTING.md あたりを見て、どのブランチにプルリクを出せば良いのかわかるようにしたい
  - 現状、Slackや他のissueを見ないとどのブランチにプルリクを出せば良いか分からなかったので、Githubを見ただけでもパッとわかるようになっていると便利だと思いました

## スクリーンショット / Screenshot
ー

## 期待する見せ方・挙動 / Expected behavior
- CONTRIBUTING.md 等に、プルリクをどのブランチに出せば良いかが書いてある
- 把握しているのは以下
  - 基本的に `development` ブランチへ
  - i18n 系の修正は `dev-i18n` ブランチへ

## 動作環境・ブラウザ / Environment
以下全て
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by chihirof** [comment]
翻訳が必要になるかと思います。
翻訳について作業フローがよくわかっていませんので(翻訳がきてから実装？)、その辺コメントいただけるとありがたいです :woman-bowing:

**Comment by shgtkshruch** [comment]
#1436 で本番反映ようの `dev-hotfix` について言及されていたので、こちらにもはっておきますmm

> 本番系の修正については、dev-hotfix に Pull Request を出すようにしてください。
その際、staging をベースブランチとし、必要な分だけの変更を反映させてください。

**Comment by chihirof** [comment]
ブランチ運用も日に日に進化しているようなので、「ここを見ればわかるよ」という一文が入るのでも良いと思いました
