### ISSUE TITLE
iframe埋め込みがスマホ閲覧時に切れる

### ISSUE THREAD

**Issue by RuinDig** [tokyo-metropolitan-gov/covid19#1395]
## 起こっている問題 / The Problem
- iframe形式での埋め込みに対応したのを受けて、自分のはてなブログで埋め込んでみました。
[東京都新型コロナウイルス感染症対策サイトの各種データの埋め込み - blog-RuinDig](https://ruindig.hatenablog.jp/entry/covid19/metro-tokyo-embed)
幅を600px、高さを平均500px前後に調整して埋め込んだところ、パソコンでは問題なく表示されましたが、スマホではグラフデータや表の項目が途中で切れてしまう事を確認しました。
**現在、「検査陽性者の状況」の項目を除く全ての項目で途中で切れる事を確認しています。**

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/20723919/76675045-fa120080-65f8-11ea-8c4f-cb60ec3ea2ee.png)
![image](https://user-images.githubusercontent.com/20723919/76675049-0ac27680-65f9-11ea-86c3-71ecc387bd4b.png)
![image](https://user-images.githubusercontent.com/20723919/76675054-1746cf00-65f9-11ea-8038-14d5c67ecab0.png)
![image](https://user-images.githubusercontent.com/20723919/76675057-275eae80-65f9-11ea-9603-20e79140f641.png)
![image](https://user-images.githubusercontent.com/20723919/76675069-43625000-65f9-11ea-9701-4ca4431bcac2.png)
![image](https://user-images.githubusercontent.com/20723919/76675079-570db680-65f9-11ea-9930-03820d451661.png)
![image](https://user-images.githubusercontent.com/20723919/76675097-67259600-65f9-11ea-8c94-1daaf0222399.png)
![image](https://user-images.githubusercontent.com/20723919/76675106-73a9ee80-65f9-11ea-92b1-98d896192261.png)

## 期待する見せ方・挙動 / Expected Behavior
- 期待する見え方の改善としては、データや項目が切れてしまう場合に横スクロールで確認できる事です。

## 動作環境・ブラウザ / Environment
- Android 9.0
- Google Chrome 80.0.3987.132
- 使用しているはてなブログのテーマは「[Smooth](https://blog.hatena.ne.jp/-/store/theme/98012380831185515)」です。レスポンシブデザインです。
- 各項目のiframe形式での埋め込みの幅は600pxに調整しています。

**Comment by nichesuch** [comment]
対応してみます。

**Comment by nichesuch** [comment]
#1435 を対応してから、同じように幅に収まるようにします。
embedの`display: grid;`を消せばOK

**Comment by nichesuch** [comment]
分ける予定でしたが、以下で一緒に完了してしまいました。
#1439
