### ISSUE TITLE
退院列の〇が言語によってはわかりにくい

### ISSUE THREAD

**Issue by teikan** [tokyo-metropolitan-gov/covid19#1398]
## 改善詳細 / Details of Improvement
- #622 で追加された陽性患者属性の退院列ですが、該当の場合言語によらず〇が表示されます。
しかし〇は日本語・韓国語特有の記号で、英語・中国語などでは✔にした方がわかりやすいです。

参考: https://ja.wikipedia.org/wiki/%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%83%9E%E3%83%BC%E3%82%AF

## 期待する見せ方・挙動 / Expected behavior
- 日本語・韓国語では〇、英語・中国語などでは✔が表示される

**Comment by NaoyaShimizzz** [comment]
ありがとうございます。こちらの変更案で問題ございません。ご対応お願いします。
