### ISSUE TITLE
サイドナビゲーションの作成

### ISSUE THREAD

**Issue by kenshir0f** [tokyo-metropolitan-gov/covid19#14]

**Comment by saladdays** [comment]
@kenshir0f 各リンク先こちらでお願いしまーす

感染症が心配な方へ
https://www.metro.tokyo.lg.jp/tosei/tosei/news/2019-ncov.html

お子様をお持ちの皆さんへ
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html

※保護者の方を対象にしたページが見つからなかったため、ひとまず相談窓口にしてあります
都民の皆さんへ
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html

企業の皆さんへ
https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/01/30/15.html

公式発表
https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html

東京都公式ホームページ
https://www.metro.tokyo.lg.jp/index.html

**Comment by kenshir0f** [comment]
一旦作成したのでcloseします。
細かい修正は別issue立てましょう。
