### ISSUE TITLE
/enにリダイレクトに日本語が表示されてしまう

### ISSUE THREAD

**Issue by TakayukiCho** [tokyo-metropolitan-gov/covid19#1405]
## 起こっている問題 / The Problem
ブラウザの言語設定が英語にしてトップを踏んだ際に、/en にリダイレクトされるが、サイドバー以外のコンテンツが日本語のままになっている。

Langの部分も日本語が入っている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/8915906/76675850-3d706d00-6601-11ea-8c5b-80097c22a311.png)

## 期待する見せ方・挙動 / Expected Behavior
- すべてenの文言が表示されるになっている。

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザの言語設定が英語にする
2. シークレットブラウザで https://stopcovid19.metro.tokyo.lg.jp/ を踏む

## 動作環境・ブラウザ / Environment
OSXのChromeで確認済み

**Comment by himatani** [comment]
確認しますー

**Comment by himatani** [comment]
@TakayukiCho 

https://github.com/tokyo-metropolitan-gov/covid19/pull/1274 で対応済みで近日反映されます
staging もしくは development で確認していただき、問題なさそうであればこちらの Issue はクローズお願いします

**Comment by TakayukiCho** [comment]
@himatani 

すみません、staging確認できてないままissue立ててしまいました。
只今stagingでfix確認できたためこちらcloseさせていただきます 🙇🙇
