### ISSUE TITLE
「最新のお知らせ」の各ニュースのタイトルの多言語対応

### ISSUE THREAD

**Issue by chihirof** [tokyo-metropolitan-gov/covid19#1408]
## 起こっている問題 / The Problem
- 「最新のお知らせ」の各ニュースのタイトルの多言語対応がされていない
- 現時点(20200314)で公開されている全ての言語で、日本語で表示されていることを確認済み

## スクリーンショット / Screenshot

日本語
<img width="809" alt="スクリーンショット 2020-03-14 14 47 23" src="https://user-images.githubusercontent.com/6346451/76676032-eff4ff80-6602-11ea-988f-f4270a8c281f.png">

English
<img width="1109" alt="スクリーンショット 2020-03-14 14 47 43" src="https://user-images.githubusercontent.com/6346451/76676039-faaf9480-6602-11ea-899b-7d87c603e6e3.png">

## 期待する見せ方・挙動 / Expected Behavior
- 各言語で表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページを開く
2. 各言語を選択する

## 動作環境・ブラウザ / Environment
- macOS 、Chrome

**Comment by chihirof** [comment]
こちら着手します。

**Comment by chihirof** [comment]
20200314 15:00 の時点で翻訳が出ていませんでした。
いったん手放します。

**Comment by asterisk37n** [comment]
やります

**Comment by asterisk37n** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/1385
と激突する可能性ありますが、PR出します。

**Comment by MaySoMusician** [comment]
@asterisk37n ありがとうございます！ ですがこちら #1413 にて既に進行中でした！

**Comment by chihirof** [comment]
@MaySoMusician 
#1413 は翻訳キーのみの修正となっており、実際の翻訳はできていないです（翻訳がないので）。

翻訳がきたら、ニュースのタイトルの翻訳作業が発生すると思うのですが、

1. このissue を翻訳作業のために残しておく
2. #1312 のように大きなissueのなかで他のものとまとめてやる

のどちらかになると思うのですが、どうでしょう？
(2の場合はこちらisuueはクローズ)

**Comment by MaySoMusician** [comment]
実際の翻訳は #1509 にあるとおり今後Transifexに移行するので、そちらでの作業になります
この issueは作業終了後にクローズする予定です

- Transifexでの作業のため、`ja`以外の訳文は空文字列にしておいていただいてもよろしいでしょうか？

**Comment by chihirof** [comment]
> 実際の翻訳は #1509 にあるとおり今後Transifexに移行するので、そちらでの作業になります
> この issueは作業終了後にクローズする予定です
> 
> * Transifexでの作業のため、`ja`以外の訳文は空文字列にしておいていただいてもよろしいでしょうか？

https://github.com/tokyo-metropolitan-gov/covid19/pull/1413 にて対応します

**Comment by MaySoMusician** [comment]
Close per #1413 merged
