### ISSUE TITLE
”オープンデータを入手”が日本語で表示されている

### ISSUE THREAD

**Issue by llr114** [tokyo-metropolitan-gov/covid19#1412]
## 起こっている問題 / The Problem
”オープンデータを入手”の文字列がどの言語でも日本語で表示されている。

## スクリーンショット / Screenshot
<img width="490" alt="スクリーンショット 2020-03-14 14 03 55" src="https://user-images.githubusercontent.com/35295742/76677120-12841a00-65fd-11ea-9f9e-38216b214110.png">

## 期待する見せ方・挙動 / Expected Behavior
言語に対応する文字列の表示

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイドバーの言語選択から各言語を選択

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari

**Comment by MaySoMusician** [comment]
ご報告ありがとうございます。こちら #1312 で合わせて修正される予定です

**Comment by MaySoMusician** [comment]
`dev-i18n` ブランチでは修正済み
後ほど `development` にも取り込まれます
