### ISSUE TITLE
各ページのtitle、OG系のタグが静的出力で反映されない

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1414]
## 起こっている問題 / The Problem
- 各ページのhead内の各タグが静的出力で反映されず、カードページのシェア画像が無くなっている

## 期待する見せ方・挙動 / Expected Behavior
- yarn generate で各htmlのheadに各ページの情報が入っている
- **ローディングアイコンは残したままにする**

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amotarao** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/1401/files#discussion_r392559860
ここらへんの対応をお願いします

**Comment by amotarao** [comment]
経緯

#1063 の対応のため、loader を削除 #1071
#1382 で、loader 復活の検討。↑の問題解決との共存が可能と判断された
#1041 で対応していただいたが、 #1063 #1071 の問題が再発
#1041 がそのままマージされてしまった
マージ後に #1041 へのコードレビューとして https://github.com/tokyo-metropolitan-gov/covid19/pull/1401/files#discussion_r392559860 を残した

**Comment by halsk** [comment]
ご指摘ありがとうございます。
コードレビューにあった内容を #1473 のようにしてみたのですが、loading が終わらず。
コードの内容的にそうだなと思いましたが、すみません。
今は stating では #1063 の問題は起きないんですよね。
明日朝、staging の内容を master

**Comment by amotarao** [comment]
@halsk こちら、7行目を指しています
https://github.com/tokyo-metropolitan-gov/covid19/pull/1401/files#r392559860

**Comment by takoba** [comment]
#1479 で対応してみました。もし良ければご確認ください:pray:

**Comment by amotarao** [comment]
自動 close されなくなった...？
解決されたので close します。
問題があれば reopen をお願いします。
