### ISSUE TITLE
[/flow] SPレイアウトで「新型コロナ受診相談窓口へ」のページ内リンクを押した時にURLにハッシュがつかない

### ISSUE THREAD

**Issue by oti** [tokyo-metropolitan-gov/covid19#1421]
## 改善詳細 / Details of Improvement

#1411 のサブイシューです。

flow ページはSPレイアウトになると「新型コロナ受診相談窓口へ」のページ内リンクが出現し、クリックすることで窓口への電話番号が書かれたセクションへスクロールしますが、URLにハッシュがつきません。

スクロール自体は機能していて必要十分ではあるものの、この時にURLハッシュがつくとハッシュ付きのパーマリンクを生成できるので、電話番号セクションを直接シェアしたい時に有用となります。

## スクリーンショット / Screenshot

ハイライトしているのは該当のページ内リンクです。 `#consult` へリンクしてます。
![スクリーンショット 2020-03-14 16 47 17](https://user-images.githubusercontent.com/710216/76677652-3010ae00-6614-11ea-9891-40294a5eb335.png)

リンクをクリック後にスクロールした様子です。 `#consult` に正しくスクロールされていますが、ブラウザのロケーションバーを見るとURLにハッシュが付与されていません。
![スクリーンショット 2020-03-14 16 48 11](https://user-images.githubusercontent.com/710216/76677653-343ccb80-6614-11ea-9f0c-2bff811061a4.png)

## 期待する見せ方・挙動 / Expected behavior
- ページ内リンクをクリック後、URLにハッシュがつくようにする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by macropygia** [comment]
本件は「SP版flowの `#consult` のアンカーリンク **のみ**」が対象でしょうか。
それとも「サイト全体」や「SP版全体」「SP版flowのみ」といった範囲での調整が必要なものでしょうか。

因みに、アンカーリンク関連の現状の仕様は以下のようになっていると思われます。

- PC版(恐らく全ページ共通)
    - アンカーリンク押下時に **即時スクロールする**
    - アンカーリンク押下時にwindow.locationにhashが **付与される**
    - hashつきURLを開いても **移動しない**
- SP版(恐らく全ページ共通)
    - アンカーリンク押下時に **固定ヘッダー分オフセットした位置にスムーススクロールする**
    - アンカーリンク押下時にwindow.locationにhashが **付与されない**
    - hashつきURLを開いても **移動しない**

SP版のスムーススクロールとオフセットには `vue-scrollto` が使用されています。

**Comment by oti** [comment]
@macropygia 理想では、PC/SPにかかわらずウェブサイト全体で

- アンカーリンク押下時にスムーススクロールする
  - SPレイアウトでは固定ヘッダーの高さをオフセットした
- アンカーリンク押下時にwindow.locationにhashが 付与される
- hashつきURLを開いたらそこに移動する（即時スクロールでOK）

が実装されることなので、ページ全体に影響するプルリクになって良いです。ページごとにプルリクを作れるならページ毎でも大丈夫と思います。 

やれる人が見つけてくれることを祈ります:pray:

**Comment by af12066** [comment]
対応します
