### ISSUE TITLE
レビュー・コンフリクト解消方法の再検討

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1427]
# 改善詳細 / Details of Improvement
- 問題が解消されないまま Issue が閉じられたり、PRがマージされることがある
  - #1389 
  - #1390 
  - #1401 
- 代理のコンフリクト解消で、期待するべき修正が消滅してしまうことがある
  - #755 

コアメンバーの方々へ。
目まぐるしい量の Issue、PR への対応、いつもありがとうございます。
お忙しいところ大変恐縮です。
上記が発生しますと、再修正や修正確認の手間が増えてしまうように感じます。
各方法についてご検討いただけますと幸いです。

**Comment by amotarao** [comment]
確かPRごとにビルドが走り、Netlify で確認できたはずなので、それを必ず見るようにするとか。

**Comment by halsk** [comment]
申し訳ありません！特にOGP関係については今朝のリリースの時に発覚して色々調整しておりました。

**Comment by halsk** [comment]
こちら、運営としては把握したので、閉じさせていただきますね。
