### ISSUE TITLE
chart.js グラフの棒にhoverしたときに色が変わらないようにしたい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1431]
## 改善詳細 / Details of Improvement
- サイトトップの全部のグラフにおいて、棒にhoverしたときに色が変わるので、変わらないようにしたい。
- 色が変わると凡例と結びつきにくくなるため。

## スクリーンショット / Screenshot
例えばこれ↓
![スクリーンショット 2020-03-14 17 06 24](https://user-images.githubusercontent.com/14883063/76677830-31db7100-6616-11ea-9026-12b3a112f191.png)

## 期待する見せ方・挙動 / Expected behavior
- hoverしても色が変わらない

**Comment by shgtkshruch** [comment]
関連チケット#592

**Comment by shgtkshruch** [comment]
hover 時に色を変わらないようにするのはサクッとできます。
ref: https://www.chartjs.org/docs/latest/charts/bar.html#interactions

![スクリーンショット 2020-03-14 20 45 45](https://user-images.githubusercontent.com/5207601/76681281-cf459d80-6634-11ea-939a-44a707427ff0.png)

ただ、選択したことがわかりにくくなるのが気になっています。
#1172 でグラフの色について議論されていますが、border をつけるなど対応が必要であればデザインを含めた検討が必要かと思いました。

取り急ぎ hover 時の色を変わらないようにするということであれば、すぐに実装はできます。

**Comment by kaizumaki** [comment]
提案ありがとうございます！このissueでは、表題の件の修正だけで大丈夫です！

**Comment by shgtkshruch** [comment]
承知しました。
それでは、hover 時に色が変わらないように実装させていただきます :D

**Comment by ocean3fish** [comment]
本件 https://github.com/tokyo-metropolitan-gov/covid19/pull/612 でPR来ています。

**Comment by shgtkshruch** [comment]
なるほど、それでは一旦実装はやめておきます〜。

**Comment by ocean3fish** [comment]
@shgtkshruch せっかくご表明頂いたところ申し訳ありませんでした🙏

**Comment by kaizumaki** [comment]
> @kaizumaki 本件 #612 でPR来ています。

@ocean3fish おお、ありがとうございます！見た目が若干違いますね。#612 は棒に外枠がつくスタイルになっています。ここまでの変更となると、ちょっと検討しないといけないですね。

@forestgtree このissueと #612 を比較してもらって、closeするかしないか指示いただいていいですか？

**Comment by kaizumaki** [comment]
現在の development で #1845 のマージによりグラフのカラーが変わりましたので、こちらのissueはcloseさせていただきます 🙇‍♀
