### ISSUE TITLE
静的(不定形文章)コンテンツのコンポーネントをTextCardからStaticCardに置き換える

### ISSUE THREAD

**Issue by macropygia** [tokyo-metropolitan-gov/covid19#1434]
## 改善詳細 / Details of Improvement

- `/about` `/parent` `/worker` の `TextCard` コンポーネントを `StaticCard` コンポーネントで置き換える
    - マークアップも必要に応じて修正する
    - 見出しはレイアウトのa11y対応の進捗を見てレベルを調整するかどうか判断
        - コンテンツエリアの大見出しがh1になる可能性あり
        - 作業時に方針が決まっていれば従う
- 経緯は #877 #916 を参照のこと

## 期待する見せ方・挙動 / Expected behavior

- 内容は現行ママ
- 要素標準の外観を尊重する

---

- 当方が対応します(3/16夜以降に着手予定)
- `accessibility` ラベルをお願いします
- PR先は `dev-tag-rewrite`

**Comment by kaizumaki** [comment]
@MaySoMusician タグ書き換えについてのissueはこちらです。念のためメンションしておきます。
作業ブランチは `dev-tag-rewrite` となります。翻訳の対応のほうもこちらのブランチでお願いします！
