### ISSUE TITLE
電話相談の画像

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#144]
宮坂さんからのフィードバック

各保健所の電話番号へのリンクがないですので、電話番号をユーザーが獲得できないです。新型コロナ受信相談窓口での相談があってその問診の結果、チャートのしたのほうにいきます。なので、上部のチャートは右側にながれていって右側に電話相談の窓口が記載されてますが、上から下に向けて情報を流して行って、新型コロナ受信相談窓口の箱へ。そしてその箱から下向き↓なりをつけて、新型コロナ受信相談窓口による問診結果　につなぐとどうでしょう？　＃絶対そうしてではなく提案

林さんに確認

**Comment by halsk** [comment]
#167 と関連

**Comment by halsk** [comment]
@kaizumaki #167 終わってるので、これもクローズしてOK？

**Comment by kaizumaki** [comment]
@halsk そうですね。クローズしていいと思います。都のフィードバックがあれば、新たにissue立てるのでよいかと。

**Comment by mikkame** [comment]
しめまーす
