### ISSUE TITLE
[/flow] PC版で矢印の示す順番にコンテンツがスクリーンリーダーで読み上げられない

### ISSUE THREAD

**Issue by oti** [tokyo-metropolitan-gov/covid19#1440]
## 改善詳細 / Details of Improvement

#1411 のサブイシューです。

- スクリーンリーダーで読み上げると、矢印が示す順番に読み上げられない

## スクリーンショット / Screenshot

例えば、下記のセクションを読み上げた後、ビジュアルとしては矢印の示した右側のセクションに読み上げが続くことが期待される。
![スクリーンショット 2020-03-14 16 43 59](https://user-images.githubusercontent.com/710216/76678868-ed080800-661e-11ea-9761-130d1e26ac10.png)

しかし、現状は最初のセクションの下を読み上げる。
![スクリーンショット 2020-03-14 16 44 08](https://user-images.githubusercontent.com/710216/76678884-1032b780-661f-11ea-9f78-06f0a7923f6f.png)

## 期待する見せ方・挙動 / Expected behavior

- 矢印の示す方向通りに読み上げが続くこと
- もしくはSPレイアウトのようにページ内アンカーが貼られ、目的のセクションにジャンプできること

#1438 でデザイン変更をする際は本件も考慮していただけると幸いです。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by macropygia** [comment]
[構成図](https://user-images.githubusercontent.com/3162324/77317363-6950c880-6d4e-11ea-8d30-d991daade5a5.png)

矢印対応ではないのですが――

- 現在存在している要素のみを順番に読み上げたとして、上の構成図におけるAブロックとBブロックにそれぞれ2つの条件が含まれることは正確に伝わるでしょうか
- EからFとHに分岐する部分はどのようにフォローすべきでしょうか

**Comment by oti** [comment]
> 現在存在している要素のみを順番に読み上げたとして、上の構成図におけるAブロックとBブロックにそれぞれ2つの条件が含まれることは正確に伝わるでしょうか

現状だと伝わらないと思います。これをHTMLでスマートに解決する方法はありませんので、ブロックごとに条件項目を重複して書いた方が良いです。

ビジュアルを変更しない前提ですと、visually hidden を使って読み上げ用と見た目用のHTMLを用意するのが早いと思います。

https://a11yproject.com/posts/how-to-hide-content/

利用する場合は見た目用のHTMLに `aria-hidden="true"` をつけてください。

> EからFとHに分岐する部分はどのようにフォローすべきでしょうか

ビジュアルを変更しない前提ですと、ページ内リンクを利用する他ないと思います。

**Comment by macropygia** [comment]
現状のビジュアルってそこそこFigmaのデザインと差異がありますが、どちらに寄せるべきなんでしょうか。（テキストはi18n対応されているので現状ママとして）

**Comment by oti** [comment]
それはリリースタイミング次第ですね。

Figmaのデザインが本番反映されるまで時間があり、それを待つ前に現状をアクセシブルにできるプルリクが早めにでき、かつそれが本番反映されるのであれば、現状のビジュアルで対応をするのは有意義です。

新ビジュアルの反映まであまり時間がないのでしたら、現状のビジュアルについてアクセシビリティを考えるのはおいておき、新ビジュアルの反映（少なくともdevelopmentへの反映）を待っても良いと思います。

僕はリリースタイミングを存じ上げないので判断できません。

結構コストのかかる課題なので、#2113 のイシュー含め道筋が示される必要はあると思います。 

@kaizumaki いかがですか？

**Comment by kaizumaki** [comment]
@oti そうですね...。リリースタイミングについては私も測りかねているところです。ただ、今まで見てきた状況から鑑みると、本番反映まではある程度の猶予は許容されていると思われます。
ちなみにflowについては、Figmaではなく非公開のAdobeXDでデザインされています。

**Comment by macropygia** [comment]
@oti [マークアップの事前検討のためのhackmd](https://hackmd.io/thItbGRzSO-Utm0XXP1gAA?edit)を用意しました。添削をお願いします。直接書き換えていただいて構いません。

以下申し送りです。

- html内での文言の出現順序が変更されていますが外観は現状のままです
- 各所のdivやspanの入れ子はレイアウト用のため、要素の選択が間違っている場合を除いて無視してください
- スクリーンリーダーの読み上げで意味が通るように不可視要素（本件では`.srOnly`）や`aria-label`で文言の追加を行うとして、内容の妥当性はどなたが判断されるのでしょうか

**Comment by macropygia** [comment]
このタイミングで #2357 が。

**Comment by oti** [comment]
@macropygia ありがとうございます。検証用にJSBinにおいてみました。
https://jsbin.com/bapahiqeqa/edit?html,output

ブロックごとに見出しがあったり、リスト要素を使っていてとても良いと思います。が、ここでちょっとPC版としての提供にどこまでこだわらなければならないかが気になってきました。

というのも、SP版が視覚的にもスクリーンリーダー向けとしても十分機能しており、SP版をPC版でも共通して提供できると、かなり低コストでアクセシブルになります。

また、非公開のAdobeXDでデザインが進んでいるということはフロー図の改修が予定されているのだと思いますので、現状のPC版の読み上げの対応もあくまで暫定的なものとなりますよね。

であれば、いっそのこと現状のPC版を思い切って `aria-hidden="true"` にし、読み上げではSP版の図版を参照できるようにする方法を提案したいです。

実は、macropygia さんが提案してくれたHTML案は、現状のSP版のマークアップとブロックの大まかな流れやページ内リンクによる分岐の構造は同じなんですよね。ここまで寄っているHTMLをわざわざSP版とPC版で別だしすることもないだろうと、思ったのです。

@kaizumaki @forestgtree 読み上げにおいてはSP版のHTMLを参照できるようにするという方針、いかがでしょうか？　あくまで、flowページの新デザインが反映されるまでの暫定対応として、です。

**Comment by macropygia** [comment]
確かにSP版はブレークポイントで `display: none;` になっているだけなのですぐに出せますね。こちらでDraftPR出した方がいいでしょうか。

（SP版はいっそのこと [擬似PWA的な感じ](https://www.figma.com/file/fBIwwVV5jhex7L6rGfm1t5/COVID-19-Flow-SP-Card) にすれば変更も楽だしPCからもモーダル等で使えるしスクリーンリーダー対応も最初から完璧だし最強なんじゃないかと思っていたりします）

**Comment by kaizumaki** [comment]
> であれば、いっそのこと現状のPC版を思い切って `aria-hidden="true"` にし、読み上げではSP版の図版を参照できるようにする方法を提案したいです。

これは私も賛成です。SP版はよくマークアップしてくれたと思っています。

そしてフロー図の改修についてですが、現時点で進んではおらず（AdobeXDでのデザインはサイト公開時から手を入れていません）、私たちも #2357 が立って内容を知ったというところです。
ただ、 #2357 で
> 現状、対策サイト上で表示されている相談フローの変更は、改めて作業負担等鑑みながら別Issueでお願いしますので、ここでは考慮しなくて構いません。

とOFFICIALが言ってくれているので、こちらの進捗具合は考慮していただけるのだなという理解です。

ここ最近の状況の急激な変化から鑑みると、もろもろの変更には随時対処していかなくてはならないなと思うとともに、慎重さも求められている場面だと感じています。

なので、ここはスクリーンリーダーについては @oti さん案で対処しつつ、今後に備えるというのでどうでしょう？

ちなみに、今後のflowのデザイン改修作業はFigmaに移行する予定です。

**Comment by oti** [comment]
@kaizumaki ありがとうございます。それでは、「PC版を `aria-hidden="true"` し、読み上げではSP版の図版を参照させる」で進めて行きますね。

@macropygia この方針でDraftPRをお願いいたします。 `display: none` されているとスクリーンリーダーの読み上げ対象にならないので、Visually Hidden で対応が必要です。

- PC図版は、コンテナごと常に `aria-hidden="true"` を維持し、SP幅の時は `display: none` する
- SP図版は、PC幅の時は Visually Hidden、SP幅の時には何もしない

こんな感じの実装でお願いいたします！

**Comment by macropygia** [comment]
一旦コンテナの表示/非表示とaria-hiddenの修正のみでPRを出しました。
[PC版のマークアップで提案](https://jsbin.com/bapahiqeqa/edit?html,output)していた相談結果の分岐が遠い事案等へのフォローは取り込んだ方がいいでしょうか。（[構成図](https://user-images.githubusercontent.com/3162324/77317363-6950c880-6d4e-11ea-8d30-d991daade5a5.png) E→ForHのナビゲーション追加等）

**Comment by oti** [comment]
PRsの方、Visually Hiddenで修正お願いします:bow:

> 相談結果の分岐が遠い事案等へのフォロー

本イシューの主眼はスクリーンリーダー向けの対応をしたいというところなので、PC版は視覚的には矢印を辿れますし、このままで良いと思いました。

**Comment by macropygia** [comment]
>PC版は視覚的には矢印を辿れますし

申し訳ありません言葉足らずでした。「PC版で提案の中でSP版にも反映した方がいいものはあるか」という意味でした。

**Comment by oti** [comment]
なるほど！ありがとうございます。

そちらは別イシューを立て、#2496 がマージされてから対応を整理したいですね。
