### ISSUE TITLE
グラフのシェアURLに言語コードが含まれていない。

### ISSUE THREAD

**Issue by rhk10** [tokyo-metropolitan-gov/covid19#1455]
## 起こっている問題 / The Problem
日本語以外の言語を選択している時、
* グラフのシェアURLに言語コードが含まれていない。
* グラフの左下の更新日時をクリックすると、日本語のグラフに飛んでしまう。

## スクリーンショット / Screenshot
<img width="514" alt="card-share-bug" src="https://user-images.githubusercontent.com/27294041/76681303-ff8d3c00-6634-11ea-8441-0223bae7ddae.png">

## 期待する見せ方・挙動 / Expected Behavior
* グラフのシェアURLに言語コードが含まれていること。
* グラフの左下の更新日時をクリックすると、現在選択している言語のグラフに飛ぶこと。

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/ を開く
2. 日本語以外の言語に切り替える

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nichesuch** [comment]
やってみます。

**Comment by nichesuch** [comment]
以下となっており、コメントを外すと、ロケール付きのURLが生成されますが、iframeで表示させても日本語が出ました。

```
    // localePath にするとうまく動かないので一旦外す
    //permalink = this.localePath(permalink)
```

<img width="1034" alt="スクリーンショット 2020-03-14 21 33 57" src="https://user-images.githubusercontent.com/2096703/76682004-98bf5100-663b-11ea-9a84-ee1b694b32c7.png">

**Comment by nichesuch** [comment]
iframeのsrcを直接叩くと英語で表示されます。

<img width="615" alt="スクリーンショット 2020-03-14 21 36 05" src="https://user-images.githubusercontent.com/2096703/76682034-da4ffc00-663b-11ea-8368-a26815d5c7d7.png">

**Comment by rhk10** [comment]
あ、すいません。
本件、https://github.com/tokyo-metropolitan-gov/covid19/issues/1389 の dupですかね？
Closeしていたので気づきませんでした。

よくわかってないですが、コメントアウトしたやつをrevertすればいいんですかね？

**Comment by halsk** [comment]
すみません。#1389 をリオープンしたので、こちらは閉じさせてください。
