### ISSUE TITLE
印刷ボタンのラベルのテキストが冗長

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#1459]
## 改善詳細 / Details of Improvement
- 印刷ボタンのラベルのテキストが冗長なので、アクションの意味を簡潔に表すようなものにする

### 修正案
- `ja`: `印刷する` -> `印刷`
- `en`: `PRINT THIS PAGE` -> `PRINT`

など（日本語と英語以外は自信がありません）

## スクリーンショット / Screenshot
現在の`dev-i18n`ブランチの最新版(  https://i18n-covid-tokyo.netlify.com/en/flow/ )で確認しました。

- `ja`

|現在|修正案|
|---|---|
|<img width="128" alt="スクリーンショット 2020-03-14 22 06 29" src="https://user-images.githubusercontent.com/20086673/76682536-2e5cdf80-6640-11ea-827f-a0095058b7b4.png">|<img width="99" alt="スクリーンショット 2020-03-14 22 06 55" src="https://user-images.githubusercontent.com/20086673/76682539-3452c080-6640-11ea-8cf3-7e95b6a2c5e2.png">|

- `en`

|現在|修正案|
|---|---|
|<img width="198" alt="スクリーンショット 2020-03-14 22 05 40" src="https://user-images.githubusercontent.com/20086673/76682544-43397300-6640-11ea-8646-8348dc0942a2.png">|<img width="114" alt="スクリーンショット 2020-03-14 22 06 03" src="https://user-images.githubusercontent.com/20086673/76682546-4896bd80-6640-11ea-903b-47798cc0c6ef.png">|

## 期待する見せ方・挙動 / Expected behavior
- 印刷ボタンのラベルのテキストが、アクションの意味を簡潔に表すようなものになっている

## 参考リンク / See alwo
- [ボタンのラベルには分かりやすい文言が重要、ユーザーが使いやすい文言の選び方 | コリス](https://coliss.com/articles/build-websites/operation/work/choosing-the-right-words-on-button-labels.html)

**Comment by syuni** [comment]
こちら対応します

**Comment by TakayukiCho** [comment]
zh-cn は 「打印」、zh-twは 「列印」で良いかと思われます。

**Comment by PichuChen** [comment]
zh-twは「列印」でいいです。
Using 「列印」 with zh-tw is fine.

**Comment by MaySoMusician** [comment]
Close per #1472 merged
