### ISSUE TITLE
フロー上の電話番号がSPレイアウトでクリッカブルに見えるようにしたい

### ISSUE THREAD

**Issue by TakayukiCho** [tokyo-metropolitan-gov/covid19#1460]
## 改善詳細 / Details of Improvement
- フローに記載されている電話番号を青文字等にしてSP版で押せるように見えるようにしたい

## スクリーンショット / Screenshot
現状押せるのかどうかわかりにくい気がする

![image](https://user-images.githubusercontent.com/8915906/76682342-be018e80-663e-11ea-93ee-95c6050e9ccf.png)

## 期待する見せ方・挙動 / Expected behavior
- フローに記載されている電話番号が押せるように見える

## 動作環境・ブラウザ / Environment
すべてのブラウザ

**Comment by munierujp** [comment]
以前同様のイシュー（#553 ）があり、解決済みです

<img width="337" alt="スクリーンショット 2020-03-14 22 33 20" src="https://user-images.githubusercontent.com/20086673/76682989-d58f4600-6643-11ea-985d-167c425f29f0.png">

**Comment by TakayukiCho** [comment]
失礼しました... 🙇🙇
