### ISSUE TITLE
Google アナリティクス の使用意図について

### ISSUE THREAD

**Issue by shka** [tokyo-metropolitan-gov/covid19#1471]
お忙しいところすいません。
Google アナリティクス を使用する意図について教えて下さい。

サイトの意図的には、
例えば東京への出張等を検討する場合の参考になるので、
EU圏からもアクセス出来ることは大変意義あることだと思うのですが。

**Comment by halsk** [comment]
すみません。どのような背景のご質問でしょうか？
Google アナリティクスは、ウェブサイトへのアクセス数や閲覧ページ、どの国からの閲覧か、などサイトの効果測定や今後のコンテンツ開発のための参考として使っております。（一般的なウェブサイトと特に大きな違いはありません）

**Comment by shka** [comment]
GDPRへの対応です。
IPアドレスは記録されていますか?

**Comment by PichuChen** [comment]
From what I know, Google Analytics won't record client's IP address, or show client's IP address on dashboard.
But all server including GitHub, Tokyo Metropolitan Gov. Google, netlify (if you entry staging and dev. site) may record your address. Mostly for security or crime detection reason.

私の知る限り、Google アナリティクスはクライアントのIPアドレスを記録したり、クライアントのIPアドレスをダッシュボードに表示したりしません。
ただし、GitHub、東京都政府、netlify（staging および開発サイトの場合）を含むすべてのサーバーがアドレスを記録する場合があります。 主にセキュリティまたは犯罪検出の理由のため。

**Comment by shka** [comment]
> 私の知る限り、Google アナリティクスはクライアントのIPアドレスを記録したり、クライアントのIPアドレスをダッシュボードに表示したりしません。

それはGoogleの説明する "Google アナリティクスで収集されるデータ" の説明と異なります。
https://support.google.com/analytics/answer/6004245

アナリティクスの機能の一部が必要であれば、IP匿名化等を検討されてはいかがですか?
https://support.google.com/analytics/answer/9019185?hl=ja

**Comment by mcdmaster** [comment]
@shka さんのご意見に賛成です。たとえば、デフォルトで Google Account にサインインしてしまっているデバイス（スマホなどを想定）なんかだと、アカウント ID（メールアドレス）、名前、IP アドレスなどといった個人を識別可能な情報は Google Analytics の収集対象になります。お示しの IP 匿名化（IP Anonymization）は、一つの対応策と言えます。私のアクセス権でどこまで見られるかわからないのですけど、ちょっと Alanytics の設定を見てみますね。

@PichuChen さんがおっしゃるフォレンジックな目的での情報収集は、GDPR で規定しているガバナンスとは別に考えることが求められます。たとえば、個人を識別可能な情報を侵入などの手段によって奪われ、なおかつそれを用いた不正なアクセスが成功したときに財産や生命の維持にかかわるデータの直接的な収奪・改変・消去が懸念されるのであれば、Highest Risk を想定せねばなりません。逆に、もしも誤報やデマがあった場合は人命や財産への脅威となるかもしれないとはいえ、この COVID-19 サイトのようなウェブ情報源から提供される内容は、上記のような直接的な類型に比べれば明らかに severity は低いです

**Comment by mcdmaster** [comment]
試しに、フリーの診断ツールで見てもらいました。サマリから申せば、現状はパーフェクトな GDPR Compliant ではありません。診断レポートは、下記 PDF をご覧ください。
[report-stopcovid19metrotokyolgjp-3542179.pdf](https://github.com/tokyo-metropolitan-gov/covid19/files/4343160/report-stopcovid19metrotokyolgjp-3542179.pdf)

とはいえ、GDPR 対応については、特に Google Analytics を使用する際は予め Google にかなりの割合でリスクを移転した格好になっていると考えることができます。
言い方を変えれば、このプロジェクト独自で GDPR 対応としての実装をできる範囲はごく限定的という見方ないしは主張ができます。
※いちおう CISA 有資格者なので、IT 監査の立場でものを言っているつもりです。

その「GDPR 対応としての実装」の一つには、 @shka さんに示していただいた IP アドレス匿名化などの方法があります。とはいえ、アクセス元などの情報が必要であれば IP アドレス匿名化はアクセス元をたどれない無意味な値に書き換えてしまうものなので、現実解ではないかもしれません。

その他、フィージビリティをあえて無視しつつ実装がしばしば推奨されるモノについては、以下の例が挙げられます。
* Cookie を用いた情報収集を行うことの明示、およびユーザがクリック／タップできる承認ボタン
* 収集される情報には個人を識別可能な情報が含まれることの明示、および承認ボタン（上に同じ）
* 個人を識別可能な情報は、必要な国と地域**以外**に向けて送信**されない**ことの明示

**Comment by shka** [comment]
https://www.johokokai.metro.tokyo.lg.jp/kojinjoho/kojin/gaiyo/2018/documents/0517_04.pdf
東京都公認という事であれば何かしらGDPRへの配慮が必要だと思いますが、
緊急性は低い筈なので、まったり進めます。

nuxt-gdpr component 等色々ソリューションはあるのですが、
GDPR対応を検討する前にまず考えなければならないのは
「その個人情報は、どうしても必要なものなのか」
という事です。

どうですかね？
必須でなければ収集しないようにしたほうが、後々楽ですよ？

**Comment by mcdmaster** [comment]
たしかに、GDPR への配慮は所与の条件、グランドルールという前提を置くとしても、GDPR で会話をすると話が拡散してしまいますね。この Issue の本旨である Google Analytics の使用目的と、ぶっちゃけそれは本当に必要か？といった主旨で議論をコンパクトにできればと私も思います。

で、Google Analytics で取得したアクセス記録をサイト改善に活用しているというコメントを @halsk さんからいただいていました。それが都の requirement であれば、Google Analytics であれ、あるいは他のサードパーティ・ツールであれ、要件を満たす実装は必要です。
Google Analytics で得られるアクセス記録は（もしくは、アクセス記録「で」）なくてはならないものか、それは都の業務目的と合致しているか、話はそこからですかね。

なお、再度のコメント＋余談になりますけど、フォレンジックの目的で収集するアクセス元 IP アドレスなどの情報は、プライバシとは別枠で考えるべしということを申し添えておきます。それは、たとえば Web サーバのアクセスログや侵入箇所等を含む全ての artifacts を、サーバ単位のフラッシュコピーで別メディアに保存するなどの方法で対処します

**Comment by mcdmaster** [comment]
現状、`pages/about.vue` では、「Google Analyticsの利用について」のセクションで下記のように書いているんですね。

> Google Analyticsは、当サイトが発行するクッキー (Cookie) を利用して、**個人を特定する情報を含まずに**Webサイトの利用データ（アクセス状況、トラフィック、閲覧環境など）を収集しております。

その一方で、同じセクションが参照している [Google の Privacy Policy](https://policies.google.com/privacy) では、「Google が収集する情報」のセクションで以下のように記されています。

> Google が収集する情報には、**固有 ID**、（中略）モバイル ネットワークに関する情報（携帯通信事業者名や**電話番号**など）（中略）などが含まれます。また、Google のサービスとお客様のアプリ、ブラウザ、およびデバイスの間の通信についての情報も収集します。たとえば、**IP アドレス**（中略）などです。

個人を特定可能な情報という意味では、Google が収集する上記太字部分のデータ
* 固有 ID（IMEI などを想定）
* 電話番号
* IP アドレス

は、それに該当すると解釈できます。

いったん、about.vue の記事の主旨を Google の Privacy Policy のそれに寄せるべく、PR を出してみますね。おそらく、Google Analytics の使用をやめるというのは今に至っては現実解でないと思われます

**Comment by shka** [comment]
北欧の一部なんかでは未だグローバルIPアドレスと住所、
場合によっては世帯が1対1対応しているので、
完全に(GDPRがそう呼ぶ通り)個人情報なんですよね。

また日本の大学にいた時も、
研究者個々人（の端末）にグローバルIPアドレスが与えられていて...
って、今はもうそんな事ないですかね。

アナリティクスを必須とする意図は未だ謎なので、
サイト毎に違うポリシーで運用できるようにするのが良さそうです。
nuxt.config.ts にトラッキングIDが与えられていない時は、
about.vue にあるアナリティクスの説明が表示されない形が理想でしょうか。
ただ翻訳が進行中なので、PRを出すにはちょっと時期尚早かなとも思ってます。

...しかしまぁ、集めないことにしてしまえば、翻訳の手間も減って楽だと思うんですけどね。

**Comment by mcdmaster** [comment]
ウェブ制作者のお立場では、アクセス元などの情報は大きな関心事の一つであるのは間違いありません。また、それは本プロジェクトのスポンサーである東京都（のご担当者のお立場）としても同様と考えられます。だとすると、解析ツールの中でも多くの実績がある Google Analytics を導入するという動機付けは、IT 監査目線でも納得はできます。あるいは、新規に同等の機能を開発・実装するよりも実績のあるコンポーネントないしはサービスを使う方がより安全という見方もできます。

とはいえ、たとえば先に私が指摘したように pages/about.vue の関連記載内容に整合性を持たせること（トラッキング ID を省略した際の Google Analytics に関する記載のサプレスを含む）とか、あるいは nuxt-gdpr ツールでできるような Cookie 承認／拒否ボタン付きバナーを出したりとかというのは、GDPR Compliance を図るのなら、特に政府および自治体というしかるべき社会的責任と支配力を持つお立場のサイトであればこそ、もれなく検討要件に入れることが求められると私は考えます

**Comment by mcdmaster** [comment]
「documentation」「waiting」のラベルを頂戴したいですね。
私は、repo の書込み権限を持ち合わせておりません

**Comment by mcdmaster** [comment]
こちら、PR #2425 にマージできればと存じます

**Comment by halsk** [comment]
遅くなりすみません。東京都側の確認が撮れました。
以下の文案で行きたい、とのことですがいかがでしょうか。
（新）
当サイトでは、サービス向上やサイトの改善のためにGoogle LLCの提供するアクセス分析のツールであるGoogle Analyticsを利用した計測を行っております。
Google Analyticsでは、当サイトが発行するクッキー (Cookie) 等を利用して、Webサイトの利用データ（アクセス状況、トラフィック、閲覧環境、IPアドレスなど）を収集しております。クッキーの利用に関してはGoogleのプライバシーポリシーと規約に基づいております。
取得したデータはWebサイト利用状況を分析しサービスの改善につなげるため、またはサイト運営者へのレポートを作成するため、その他のサービスの提供に関わる目的に限り、これを使用します。（サイト運営者へのレポートでは、クッキーはブラウザ単位で本サイトのユーザー数をカウントするため、IPアドレスはGoogle Analyticsの分析機能を通じてアクセス元の地域分布（国、州・都道府県、都市）を把握するために利用されています。）
Google Analyticsの利用規約及びプライバシーポリシーに関する説明については、Google Analyticsのサイトをご覧ください。
・Google Analytics利用規約
・Googleのプライバシーポリシー
・Google Analyticsに関する詳細情報
Google Analyticsによる情報送信を回避する場合は、Google がサポートする測定を無効にするブラウザ アドオン (https://tools.google.com/dlpage/gaoptout?hl=ja) をご利用ください。

**Comment by mcdmaster** [comment]
@halsk さん、ありがとうございます。IT 監査目線でもオーケーだと思います。
では、プッシュ元のアップデートを掛けます。しばしお時間を頂戴したく

**Comment by mcdmaster** [comment]
修正対応しました #2425

**Comment by shka** [comment]
お忙しいところ、真摯にご検討頂きありがとうございました。
当面は日本向けの対応（サイト運営側の権利の説明）ということで理解しました。

GDPRに対処すると、
さらにサイトを見ている側の権利と行使に関する説明および配慮が必要です。
例えば東京オリンピックのサイトだと、
下記の「本人の権利とその行使方法」がそれです。

https://tokyo2020.org/ja/privacy-policy-gtwa

...今後の話ではありますが、
例えば同様に皆が集まって公共性の高いウェブサイトを立ち上げる時に、
ここらへんをうまく解消するソリューションってありませんかね？

極端な例を挙げれば、
EUからアクセスするユーザにはAnalyticsに記録された自分のIPアドレスを削除させる権利があり、
しかし削除を受け付ける窓口を維持するのはそれなりに面倒です。
同意の撤回等は窓口なしにできますが、
削除は多分、窓口経由してUser Deletion APIで個別対応になるでしょう。
オプトアウトプラグインに気づくのはきっと、１度はアクセスした後でしょうし...
（という理由で、東京オリンピックサイトは6種類の権利行使方法が記載されているのだと思います）

例えば（言葉は悪いですが）地方自治体が面倒な部分を被って下さると、
きっと我々は動きやすいのですが。

**Comment by mcdmaster** [comment]
窓口という意味では、今や一般的な ITIL ふうサービスデスクを設け、そこを１次受けとしつつ、L2 もしくは L3 部隊が個人識別情報の削除作業を実施する、というのが現実的でしょうね。
とはいえ、その前にサービスデスク、ワークアラウンド、恒久対応のそれぞれの作業を実施する部隊現場の皆さんに教育を実施する、さらに言えば、教育マテリアルの作成をするなんていうのは、それはそれで必要とはいえかなり負担の要る作業です。
非機能要件に関するスレ（イシュー）が立っているみたいなので、ガバナンス、コンプライアンス、セキュリティ目線で何かコメントしておきます

**Comment by mcdmaster** [comment]
#2425 がマージされましたので、お手数でも、いったん本件はクローズしていただけますでしょうか。
ご認識いただいたように、「当面は日本向けの対応（サイト運営側の権利の説明）」となっていることをご容赦ください。
また、GDPR をはじめとするプライバシーの問題については、非機能要件に関するディスカッション用イシュー #2790 で検討要件に上げましょう。
※すみません、私が上げると上のコメントで言っていたのに未だ上げられていません…。

マージ後の development 現状は、[こちらからご確認いただけます](https://dev-covid19-tokyo.netlify.com/about)。
とはいえ、ちょっとしたコスメティック・プロブレムも残っているようなので、そこは個別に修正用イシューを（これは本当に私から）上げていきます。
引き続き、宜しくお願いいたします

**Comment by shka** [comment]
そうですね、（タイトルとして挙げた）意図は明らかになりました。
ただ東京都及びその他市民サイトのテンプレとしてはまだ課題があると思いますので、
スレを変えたほうが良さそうです。
こちらは一旦閉じます。
