### ISSUE TITLE
スマホ閲覧時カードにフォーカスしてスクロールすると思ったように操作できない

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#149]
カード内でスクロールされてしまうような感じです。
最下部が表示できない、ヘッダーが見れない　などが発生します

[再現video.zip](https://github.com/tokyo-metropolitan-gov/covid19/files/4275195/video.zip)

**Comment by kaizumaki** [comment]
@mikkame 再現video見ました。おそらくカード内でスクロール難民になっていたと思うんですが、いまでも同じ現象が起きてますかね？ちなみに私はiphone Safariで見ていますが、最下部・ヘッダーは見れています。
https://stg-covid19-tokyo.netlify.com/

**Comment by halsk** [comment]
@mikkame これって再現しますか？

**Comment by t-yng** [comment]
次の環境では正常に動いてる事を確認できました。

端末: iPhoneSE
iOS: 13.3.1
ブラウザ: Chrome・Safari・Sleipnir

**Comment by halsk** [comment]
@mikkame さんの確認待ちで。

**Comment by halsk** [comment]
多分直っているのでクローズ
