### ISSUE TITLE
Facebook, Twitter のOGP画像のキャッシュを一括で削除するスクリプトを組む

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1497]
## 改善詳細 / Details of Improvement
- #774 の実装により、各グラフの個別のページができ、シェアができるようになりました。
- しかし、URL は同一なため、現行仕様でいくならば、グラフが更新されたタイミングでOGP画像も更新すべきです。
- 現在は、[facebook debugger](https://developers.facebook.com/tools/debug/) 及び [Twitter Card Validator](https://cards-dev.twitter.com/validator) で手動で更新をしているのですが、全てのカードを毎日更新するのは大変です。
- 何らかの方法で自動化させたいと考えています。

## 期待する見せ方・挙動 / Expected behavior
- 理想は、GitHub Actions に組み込めること
- 手動実行バッチ（シェルスクリプトなど）でも、無いよりはまし

ざっと調べた限り、Facebook は cURL で更新することが可能。ただし、アクセストークンは延長しても3ヶ月で切れるので、3ヶ月毎に更新が必要？

```
curl -i -X GET \
 "https://graph.facebook.com/v6.0/https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases/?access_token=${ACCESS_TOKEN}"
```
Twitter は不明

**Comment by halsk** [comment]
Facebook についてはこちらでも一括消去できるみたい。
https://developers.facebook.com/tools/debug/sharing/batch/

**Comment by halsk** [comment]
> Facebook についてはこちらでも一括消去できるみたい。
> https://developers.facebook.com/tools/debug/sharing/batch/

やってみたけど、キャッシュが消去されるわけではなかった。

**Comment by halsk** [comment]
Twitter の方は、`twitter:image` が更新されていれば大丈夫っぽい。
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/troubleshooting-cards

**Comment by halsk** [comment]
> > Facebook についてはこちらでも一括消去できるみたい。
> > https://developers.facebook.com/tools/debug/sharing/batch/
> 
> やってみたけど、キャッシュが消去されるわけではなかった。

#1681 の問題かも

**Comment by halsk** [comment]
関連して、#2002 のエラーも出ています。

APIとかを使うよりも、scrapy とか selenium とか使ってFacebook Debugger や Twitter Validator を操作するほうが早い気がしてきました。

**Comment by t-tajiri** [comment]
@halsk 
はじめまして。
ogp画像が更新されていることを確認する方法ってどうしたらいいでしょうか？

**Comment by cgetc** [comment]
@halsk はじめまして。

> Twitter の方は、twitter:image が更新されていれば大丈夫っぽい。

ある程度時間が立たないと、クロールし直してくれないようなので、Twitter Card Validatorなりでキャッシュを削除する手順は必要なのではないでしょうか？
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/troubleshooting-cards#refreshing

**Comment by halsk** [comment]
@t-tajiri
Facebookであれば Facebook Debugger で確認でき、Twitter では実際にtweetしようとすると分かります。

**Comment by halsk** [comment]
@cgetc
はい。このチケットは、その作業をいちいち手作業でやるのが面倒なので、自動化したいという Issue です。

**Comment by cgetc** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/1497#issuecomment-599815823
Facebookに関しては、OGPのBugfixがマージされており、私の方で試した感じではBatch Invalidatorが正常に動作していそうです。

**Comment by cgetc** [comment]
Twitter Card ValidatorにはAPIはないので、seleniumなどで対応するほうがいいかもしれません。
https://twittercommunity.com/t/how-to-clear-twitter-card-cache-with-api/62974
短縮URLを発行して、ツイートする方法もありますが、どちらにしても、工数がかかりそうです。

**Comment by cgetc** [comment]
短縮URLを発行して、ツイートする方法を一旦試してみましたが、期待した動作ではありませんでした。Twitter Card Validatorは正常に動作するので、seleniumなどで対応する方法が無難そうです。
@halsk 仕事の関係もありますし、半日以上かかってしまってもいいのでしたら、私の方で対応します。

**Comment by halsk** [comment]
ありがとうございます！急ぎませんので、大丈夫です。

**Comment by cgetc** [comment]
@halsk まずはTwitterの方だけでいいですか？

**Comment by halsk** [comment]
はい。大丈夫です

**Comment by cgetc** [comment]
GitHub Actionsにはまだ組み込めていませんが、Mac環境では一発でまとめて手動実行できるぐらいにはできています。
https://github.com/tokyo-metropolitan-gov/covid19/pull/2240
実行するたびにログインのメールが届いてしまうので、捨てメアドでTwitterのアカウントを新規作成するのをお勧めします。

**Comment by cgetc** [comment]
@halsk Facebookは以下のスクリプトをGithub Actionに組み込めば自動化できると思うのですが、その方向で進めたほうがいいですか？
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/ui-test/delete_fbcache.sh

**Comment by halsk** [comment]
@cgetc このスクリプトには2つ問題がありまして、1つには、Access Token が短期間でしか使えないこと、もう一つは、API経由でページキャッシュを消そうとしたときに以下のエラーが出ることです。

````
{
  "error": {
    "message": "Invalid parameter",
    "type": "OAuthException",
    "code": 100,
    "error_subcode": 1611016,
    "is_transient": false,
    "error_user_title": "オブジェクトの値が無効です",
    "error_user_msg": "プロパティ「og:locale:locale」に指定された値「en」はタイプ「enum」としてパースできないため、URL「https://stopcovid19.metro.tokyo.lg.jp/en/cards/details-of-confirmed-cases/」のオブジェクト(タイプ「website」)は無効です。",
    "fbtrace_id": "Am7ZTnacPiXjpHEIUWpH5lT"
  }
}
```

Access Token は、今は下記の画面で取得できるものを使っていますが、永久には使えないようで、すぐに無効になってしまいます。

![image](https://user-images.githubusercontent.com/16509/77842864-4309ad80-71d2-11ea-83bc-0c128e53fc1f.png)

**Comment by cgetc** [comment]
まだ試してはいないですが、無期限のアクセストークンは発行できるらしいです。
https://gist.github.com/xl1/fe779a817a9d4938193d

**Comment by halsk** [comment]
> まだ試してはいないですが、無期限のアクセストークンは発行できるらしいです。
> https://gist.github.com/xl1/fe779a817a9d4938193d
おおお、求めていたものが。。
locale エラーが直れば自動化できそう！

**Comment by halsk** [comment]
試してみましたが、` scope に manage_pages を含んだトークンを取得する` という部分が問題ですね。
この scope を持ったアプリを私が管理していないので、このトークンが取得できません。

**Comment by cgetc** [comment]
Facebookページの管理者にトークンを発行してもらわないと難しいですね。

**Comment by cgetc** [comment]
https://developers.facebook.com/docs/graph-api/reference/v6.0/url#update のAPIは更新しようとしているサイトとアクセストークンは無関係のように思えます。
関係ないFacebookページをもとに発行したアクセストークンを用いて試したところ、同様のog:localeのエラーが発生するので、更新はサイト管理者に限定していないのでは？

**Comment by halsk** [comment]
アプリ作って、テストしてみているのですが、なぜかまだlocale のエラーが出てますね。

![image](https://user-images.githubusercontent.com/16509/77853738-b63a1080-7220-11ea-8c09-cc1203e3b76c.png)

ここで指定している http://dev-covid19-tokyo.netlify.com/ の og:locale が ja_JP になっていることは確認できています。
エラーには、og:locale:locale とか書いてあっておかしい？

**Comment by cgetc** [comment]
私の方ではエラーになりませんでした。
<img width="1827" alt="スクリーンショット 2020-03-30 8 51 13" src="https://user-images.githubusercontent.com/1819135/77864468-a132a100-7263-11ea-8349-d405748697ae.png">

> エラーには、og:locale:locale とか書いてあっておかしい？
これは以前と同じエラーなので関係ないです。

一度エラーが発生したら、FacebookDebuggerでやる必要があったりするのか？
とはいえ、一度エラーが解消していれば、サイト更新をしても正しく反映されるようにはなりそうな気がします。

**Comment by cgetc** [comment]
すでにLocaleの変更は本番に反映済みのようで、`delete_fbcache.sh` を手元で動かしたら、正常に動いていそうです。
以下ログの抜粋です。
```
% 
HTTP/2 200
vary: Accept-Encoding
x-app-usage: {"call_count":2,"total_cputime":0,"total_time":0}
content-type: application/json; charset=UTF-8
facebook-api-version: v6.0
strict-transport-security: max-age=15552000; preload
pragma: no-cache
x-fb-rev: 1001916064
access-control-allow-origin: *
cache-control: private, no-cache, no-store, must-revalidate
x-fb-trace-id: Atlnly9LPk0
x-fb-request-id: ADVbOwHT2PmZGsx2yAfTT_v
expires: Sat, 01 Jan 2000 00:00:00 GMT
x-fb-debug: 7X3GlE+MuM77S/6s2rAgJ8P9bDrANzHo+Xg0YNL4tGghFRRNFOmDiwSa0H2ShHsXG6Vx8wgakjTy5XZbrUFBAg==
date: Mon, 30 Mar 2020 09:16:10 GMT
alt-svc: h3-27=":443"; ma=3600
date: Mon, 30 Mar 2020 09:16:11 GMT

{"url":"https:\/\/stopcovid19.metro.tokyo.lg.jp\/","type":"website","title":"\u6771\u4eac\u90fd \u65b0\u578b\u30b3\u30ed\u30ca\u30a6\u30a4\u30eb\u30b9\u611f\u67d3\u75c7 \u5bfe\u7b56\u30b5\u30a4\u30c8","locale":{"locale":"ja_jp"},"image":[{"url":"https:\/\/stopcovid19.metro.tokyo.lg.jp\/ogp.png"}],"description":"\u5f53\u30b5\u30a4\u30c8\u306f\u65b0\u578b\u30b3\u30ed\u30ca\u30a6\u30a4\u30eb\u30b9\u611f\u67d3\u75c7 (COVID-19) \u306b\u95a2\u3059\u308b\u6700\u65b0\u60c5\u5831\u3092\u63d0\u4f9b\u3059\u308b\u305f\u3081\u306b\u3001\u6771\u4eac\u90fd\u304c\u958b\u8a2d\u3057\u305f\u3082\u306e\u3067\u3059\u3002","site_name":"\u6771\u4eac\u90fd \u65b0\u578b\u30b3\u30ed\u30ca\u30a6\u30a4\u30eb\u30b9\u611f\u67d3\u75c7 \u5bfe\u7b56\u30b5\u30a4\u30c8","updated_time":"2020-03-30T09:16:09+0000","id":"2935876866463721","application":{"id":"2879625188795443","name":"\u6771\u4eac\u90fd\u65b0\u578b\u30b3\u30ed\u30ca\u611f\u67d3\u75c7\u5bfe\u7b56\u30b5\u30a4\u30c8","url":"http:\/\/stopcovid19.metro.tokyo.lg.jp\/"}}
```

長期トークンはこちらのやり方のほうが最新のようでした。
https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing

この方法で関係ないFacebookアプリのapp_idとapp_secretをもとに作成したトークンで、同様に実行して、同様の結果になりました。

**Comment by MasaGon** [comment]
@cgetc @halsk 最終的に利用するトークンですが、「長期ページアクセストークン」という理解で良いでしょうか？「長期ユーザーアクセストークン」の取得まではうまくいったのですが、「長期ページアクセストークンの取得で空データが戻ってくる現象に悩んでいます。何かお気づきの点があれば、教えてください。

```
{"data":[]}
```

**Comment by cgetc** [comment]
@MasaGon 長期ページアクセストークンのほうが正しいと思いますが、長期ユーザーアクセストークンでも動作したと記憶しています。

**Comment by cgetc** [comment]
@MasaGon 長期ページアクセストークンを取得するにはmanage_pagesのスコープが必要のようです。以下の手順で長期ページアクセストークンが取得できました。
1. [Graph API Exploler](https://developers.facebook.com/tools/explorer/) でスコープにmanage_pagesを追加してトークンを発行する
2. 1.のトークンをもとに長期ユーザアクセストークンを取得する
3. 2.のトークンをもとに長期ページアクセストークンを取得する

**Comment by MasaGon** [comment]
@cgetc ありがとうございます！

どうやら具体的にpages_show_listでリンクしているページが一つもないと、/me/accounts には何もデータが出力されないという問題のようでした。ダミーページを作って対応しました。
