### ISSUE TITLE
GoogleSpreadsheet 依存を無くす

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#15]
GoogleSpreadsheet のAPIだと、都庁内のPCから見れないかも？
Deploy 時、Google Spreadsheet からJSONファイルをダウンロードしてきて gh-pages に登録できるとベスト。

**Comment by halsk** [comment]
OneDrive 対応を先に考える

**Comment by halsk** [comment]
とりあえず、#34 で、データをダウンロードしてくお設定をした。
https://stg-covid19-tokyo.netlify.com/data/data.json
にデータが置かれるようになっています。

**Comment by yokinist** [comment]
対応済: masterへ反映次第close
