### ISSUE TITLE
"陽性患者の属性"の"公表日"の翻訳に失敗している

### ISSUE THREAD

**Issue by whisky-shusuky** [tokyo-metropolitan-gov/covid19#1500]
## 起こっている問題 / The Problem
- "陽性患者の属性"の"公表日"の翻訳に失敗している
- 日本語以外でも"公表日"と表示されている

## スクリーンショット / Screenshot
<img width="550" alt="スクリーンショット 2020-03-15 11 35 03" src="https://user-images.githubusercontent.com/20264602/76694051-27ba8080-66b1-11ea-9e7a-3ec817c86c94.png">

## 期待する見せ方・挙動 / Expected Behavior
- 翻訳された状態で表示する

## 起こっている問題の再現手段 / Steps to Reproduce
- ブラウザで日本語以外の言語で表示する(全ての環境で再現される)

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by whisky-shusuky** [comment]
原因を特定したので当方で対応しようと思います。

**Comment by MaySoMusician** [comment]
Close per #1506 merged
