### ISSUE TITLE
グラフと表の高さを揃える

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#151]
隣り合うものの高さを揃えるのがベストですが、一旦は全てグラフの高さに揃えて固定値にするでだいじょうぶです。

![image](https://user-images.githubusercontent.com/1301149/75675392-6ec86f00-5cca-11ea-864e-ddf1c8c57b8a.png)

**Comment by hkomamiy** [comment]
今の作業と合わせてやりますー

**Comment by hkomamiy** [comment]
【ナレッジある方教えてください】以前のissueにもあった「2カラム→1カラムになると2カラムに戻らなくなる」ことや「sp時のクリッカブルな棒の太さ調整」と関係しています。
chart.jsのcanvasがレスポンシブのため高さ固定fixができません。

やりたいこと：横幅レスポンシブで高さのみ固定
試したこと1：mounted()内部でjsで高さ固定
→ canvasの中身(棒グラフや数字ラベル)も一緒に横長になってしまう
試したこと2：cssでのheight固定 → 効果なし

**Comment by hkomamiy** [comment]
別issueやります。

**Comment by hkomamiy** [comment]
もうちょいやります。

**Comment by hkomamiy** [comment]
ちょっと頭休めます。できる人いたたらお願いします。
<img width="841" alt="スクリーンショット 2020-03-02 22 28 16" src="https://user-images.githubusercontent.com/27335198/75690196-c7f1cc00-5ce5-11ea-91dc-7ffc3c9878bb.png">
Doc：https://www.chartjs.org/docs/latest/general/responsive.html#important-note
未実装：resize処理、widthの調整

**Comment by mikkame** [comment]
ちょっとTryします

**Comment by mikkame** [comment]
ちょっと厳しいですね・・・

**Comment by mikkame** [comment]
flexやめて50%/50%にしたら上の内容でうまくいくかも

**Comment by hkomamiy** [comment]
再tryしてみます

**Comment by kaizumaki** [comment]
私の手元ではグラフと表の高さは揃っているのですが、 #264 が関係してませんかね？
![スクリーンショット 2020-03-04 15 09 55](https://user-images.githubusercontent.com/14883063/75850340-6a1acc80-5e2a-11ea-8a7d-7d840c959741.png)

**Comment by kaizumaki** [comment]
ちなみに #310 でプルリク投げています。

**Comment by hkomamiy** [comment]
@kaizumaki こちら#310 確認させていただきました。静止状態では揃っているのですが、レスポンス状態(横幅を縮めていく時)でチャートが240px固定にするのがissueなのかなと思っていました。

**Comment by kaizumaki** [comment]
@hkomamiy おお、なるほど。私がこのissueの目的を理解してないかもしれないですが、DataViewに `height:100%` が入っているので、それが最適解かなとも思っています。

**Comment by hkomamiy** [comment]
@kaizumaki なるほど、ありがとうございます。
DataViewに height:100%はカード全体についてかなと。https://github.com/tokyo-metropolitan-gov/covid19/issues/265 を見るとグラフ(vue-chart.js)のレスポンス時の縦固定かなと思っていました。

**Comment by hkomamiy** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/279で解決されているかもというのもあり、ちょっと時間かかるかもなので、別のタスク取り掛かります。おさわがせしました。

**Comment by madana-1** [comment]
@saladdays @hkomamiy 
https://github.com/tokyo-metropolitan-gov/covid19/pull/407
こちら対応させていただきました。お手すきの際に確認いただければと思います。
