### ISSUE TITLE
[i18n] 中国語 言語名の修正

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#1512]
## 改善詳細 / Details of Improvement
- 現状，言語選択のフォーム内で「簡体字」「繁体字」と表記されている箇所を変更したい
    - 併せて，`README.md` 内の各言語版 README へのリンクの表記も変更してしまいたい (cf. #1103)

https://github.com/tokyo-metropolitan-gov/covid19/issues/1103#issuecomment-598288276

> 簡体字・繁体字は本来文字の種類の名前のはずですので、「中文」の表記はあったほうが良いかと思われます（「日本語」の代わりに「ひらがな・カタカナ」って表記されてしまっているイメージ）

https://github.com/tokyo-metropolitan-gov/covid19/issues/1103#issuecomment-598352798

> 現状では見やすさの観点からひとまず、简体中文・繁體中文でよいかと思いますよ。

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-15 13 40 06](https://user-images.githubusercontent.com/23148331/76695421-7fadb300-66c2-11ea-9655-c00082e34963.png)

## 期待する見せ方・挙動 / Expected behavior
- 「简体中文」「繁體中文」に変更する
![スクリーンショット 2020-03-15 13 38 17](https://user-images.githubusercontent.com/23148331/76695404-3fe6cb80-66c2-11ea-9049-ca48581688a4.png)

## 動作環境・ブラウザ / Environment
- macOS, Chrome

**Comment by MaySoMusician** [comment]
Close per #1513 merged
