### ISSUE TITLE
[周知] Issue の受付について詳細化しました。

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1516]
関です。
皆様、日々様々なご提案やバグ報告、修正コードのコミットなど、誠にありがとうございます。
皆様のおかげで、サイトも大変改善されてまいりました。この場を借りてお礼を申し上げます。

2020/03/15 13:50 頃、`CONTRIBUTING.md` を下記のように修正させていたきました。

（旧）
> * improve(改善提案)がついたIssueについては必ず反映できると限りませんのでご了承ください（特にUI系について)

（新）
> * improve(改善提案)がついたIssueについては必ず反映できると限りませんのでご了承ください
> * 文言変更や見た目の大幅な変更といった、コンテンツの意味を変えるものについては、関係者の確認が必要です。採用される可能性もあまり高くないことをご了承ください。
> * `waiting` ラベルがついた Issue は関係者の確認中ですので、内容が固まるまで実装するのは避けていただく方が無難です。

(他言語への翻訳、お願いできましたら幸いです！)

なぜこのような変更を入れたかというと、Pull Request について、「せっかく実装したのに取り入れられなかった」という事象をなるべく避けるためです。
本リポジトリは東京都の公式ウェブサイトのソースコードであり、都の公式発表をお伝えするものです。
コンテンツの内容まで自由に変えられるわけではありません。皆様の Issue はあくまでご提案として関係者にお伝えさせていただいておりますが、必ずしも反映できるわけではありません。
また、回答を得るまでに時間がかかってしまうケースもございます。

皆様からの Issue は素晴らしいものが多く、実際に取り入れられたご提案も少なくはありません。私も勉強させていただいております。しかしながら、上記のような事情もあり、返答までお時間を要するものもございます。
できるだけ丁寧に対応させていただきたいと思ってはいますが、制約もございます。おまたせしてしまう場合もありますが、ご了承いただけましたら幸いです。

**Comment by PichuChen** [comment]
@halsk zh-TW が完成しました。

**Comment by dg4101** [comment]
英語追加しました。
