### ISSUE TITLE
「検査陽性者の状況」テーブルを横均等7分割から縦の積み上げにする

### ISSUE THREAD

**Issue by macropygia** [tokyo-metropolitan-gov/covid19#1520]
## 改善詳細 / Details of Improvement

- 「検査陽性者の状況」テーブルのレイアウトを横均等7分割から縦の積み上げにする
- #1381 #608 などのより効果的と思われる提案もあるがひとまず次善策として
- CSSだけで対応できるため短時間で実装可能
- 現状の問題点
    - カードの幅が十分に広い限られた表示条件以外ではテキストの可読性が低い
    - 英語とやさしいにほんごでは常に大量の改行が発生しており、一部の条件でははみ出す
        - ~~内容量に応じて高さを可変にするのはcssだけでは対応できなさそう（css力が不足しているだけかも）~~ できました、とはいえ縦長なのは変わらず
- メリット
    - 内容量にセルのサイズが追従する
        - 英語・やさしいにほんごも無理なく収まり他の言語で間延びすることもない
    - 項目が増減しても対応が容易
        - 他地域への展開時に取得できるデータに合わせて調整しやすい
- デメリット
    - 英語・やさしいにほんごの場合、2カラム時に右の「陽性患者数」エリア内の余白がやや大きくなるかも

## スクリーンショット / Screenshot

![COVID-19 検査陽性者の状況](https://user-images.githubusercontent.com/3162324/76698071-d37bc480-66e1-11ea-881f-f117e4e7e612.png)

### 現状のアウトなケース

![image](https://user-images.githubusercontent.com/3162324/76696725-e2f31180-66d1-11ea-978b-baf7bb10fb23.png)

### 英語は単語内の改行が頻繁に発生する

![image](https://user-images.githubusercontent.com/3162324/76872326-a2e98580-68af-11ea-8a22-19a3b90d7cc3.png)

## 期待する見せ方・挙動 / Expected behavior

- DOM構造は現状のままでOK
- コンテンツエリアがシングルカラムの時だけでもOK（cssだけで切り替え可能）
- **デザイン提案歓迎**

---

- #1022 で乗りかかった船なので実施時は担当します
    - `div.gutter` は消す
    - cssをmoduleにする

**Comment by masayasuyamamoto60** [comment]
確かに横レイアウトより、縦レイアウトの方が、構造がわかりやすくなりますね。

この項目の順番は、決まっているのでしょうか？他の都道府県も同じ順番で表示しています。
しかし、この順番は、入院患者が何人いるのか、通院中が何人いるのかに関心が高い為政者に便利ですが、一般市民には様子がわかりにくい順番ですね。
メインの利用者（一般市民）であれば、症状の重さの度合いが知りたいはずです。

**Comment by amotarao** [comment]
縦のままのやさしい日本語の改善は #1699 でされている模様です

**Comment by kaizumaki** [comment]
こちらの要望 https://github.com/tokyo-metropolitan-gov/covid19/issues/1692#issuecomment-600361634 のため、このissueはクローズさせていただきます 🙇‍♀

**Comment by kaizumaki** [comment]
@macropygia こちらのissue、再オープンさせてください。都から正式にこちらの実装の依頼がきました。現状、項目が増えたためかなり見にくくなってしまっており、縦の積み上げにする要望が高まっていました。なにとぞご協力いただきたく思います 🙇‍♀️

**Comment by masayasuyamamoto60** [comment]
素晴らしい

**Comment by macropygia** [comment]
@kaizumaki 承知しました。確認事項をお送りします。

- 対象は「検査陽性者の状況」と「検査実施状況」のいずれか、ないし両方のいずれでしょうか
    - 本issue作成時にはこの体裁のテーブルは「検査陽性者の状況」だけでした
- 「検査実施状況」が対象に含まれる場合、「検査実施件数 (累計)」部分の体裁についてデザインの指定はございますか
    - 添付スクショの通り、本issue作成時にはこの体裁は存在しませんでした
    - 適当に実装してPRしてからブラッシュアップでも構いません

**Comment by kaizumaki** [comment]
@macropygia ありがとうございます！よろしくお願いします 🙏 

> * 対象は「検査陽性者の状況」と「検査実施状況」のいずれか、ないし両方のいずれでしょうか

依頼が来ているのは「検査陽性者の状況」のみです。ただ、「検査陽性者の状況」と「検査実施状況」のカードは横並びになっているので、バランスが悪くなる可能性はありますね。
もし @macropygia さんがそのような懸念をお持ちであれば、都に提案いたしますがいかがでしょう？

**Comment by kaizumaki** [comment]
@macropygia 現在表示されている項目のほか `data.json` には「調査中」という項目が追加されているのですが、今回の改修でこれも表示することになります。表示名は「入院・療養等調整中」です。
以下ダミーイメージです。
![縦組みイメージ](https://user-images.githubusercontent.com/14883063/82265932-39671f80-99a3-11ea-8a5b-22ec376836dd.png)

**Comment by macropygia** [comment]
@kaizumaki カード幅が狭くなるタイミング（1000px前後・600px台前半）における英語・やさしい日本語の外観が大分怪しいため、提案していただいた方がよいかと存じます。なお、見かけ上の大きさについては両方縦にした方が差が大きくなりそうです。

![image](https://user-images.githubusercontent.com/3162324/82265762-c1005e80-99a2-11ea-8351-483344564761.png)

※恐らく施設名が翻訳されると酷いことになります

![image](https://user-images.githubusercontent.com/3162324/82265839-f73dde00-99a2-11ea-8998-343b0d67b4ad.png)

**Comment by masayasuyamamoto60** [comment]
@kaizumaki ダミーのイメージ見たけど
段数が多くダラダラと続くので見にくいと思いますが。

例えば、
宿泊療養、自宅療養、入院・療養等調整中を「入院中」と同じように「療養および調整中」などとカテゴリーにしてはどうでしょう？
一段増えるけど、まとまってみ訳すなると思います。

**Comment by kaizumaki** [comment]
@masayasuyamamoto60 
> 段数が多くダラダラと続くので見にくいと思いますが。縦に並ぶと余計。

たしかにそういう印象はありますね。

> 宿泊療養、自宅療養、入院・療養等調整中を「入院中」と同じように「療養および調整中」などとカテゴリーにしてはどうでしょう？

「宿泊療養」「自宅療養」については[東京都の公式発表](https://www.fukushihoken.metro.tokyo.lg.jp/hodo/saishin/corona358.html)に基づいています。「入院・療養等調整中」を加えたときに、ここの入れ子を変更するのは解釈が変わってきてしまうので、容易ではないように思います。
こちらのissueの実装の後に、別issueで提案という形にするのがよいかと思いますが、どうでしょうね。

**Comment by masayasuyamamoto60** [comment]
理解しました。
一点質問です：
「東京都の公式発表」を見ましたが、見当たらない「入院・療養等調整中」はどこから出てくるのでしょうか？

**Comment by kaizumaki** [comment]
@masayasuyamamoto60 「入院・療養等調整中」は、入院か療養かそれ以外かを精査している最中のもの、というのが私の理解です。なので、こちらの数値が発表された際には他の数値が減るはずです。
