### ISSUE TITLE
【改善提案】Language選択のプルダウンメニューをTopに表示

### ISSUE THREAD

**Issue by maconaco** [tokyo-metropolitan-gov/covid19#1525]
## 改善詳細 / Details of Improvement
- メニューの下のほうにあるのでLanguage選択に気づきにくい
- Language選択のプルダウンメニューをTopに表示
- Topの一番わかりやすいところに多言語対応しました

### PC
<img width="1397" alt="スクリーンショット 2020-03-15 18 02 09" src="https://user-images.githubusercontent.com/46955104/76698515-273cdc80-66e7-11ea-96dd-f68f0da062e0.png">

### sp
<img width="344" alt="スクリーンショット 2020-03-15 18 01 16" src="https://user-images.githubusercontent.com/46955104/76698518-31f77180-66e7-11ea-8d95-51c47070b4b9.png">

## 期待する見せ方・挙動 / Expected behavior
- 多言語選択に対応していることの有無の認知がはっきりできること
- 日本語のわからない人でもすぐにここだとわかるようになること
- 開いた最初のページもしくはメニューの一番上にLanguage選択の導線配置
- 開いた最初のページもしくはメニューの一番上にLanguage選択のプルダウンメニュー配置

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

## お気持ち
twitterのTLでやさしい にほんご すごい！と流れてきて
え！！めっちゃ良さそう！私も見に行こうと見に行った時
多言語対応がどこなのか探すのに時間がかかったので、提案させていただきました！
せっかくの多言語対応が本当に必要としてる人に届かない気がします。
以上で改善提案とさせていただきます！
PRも出してみます！

(事前に検索はして被りがないかは見たのですが見落としていたらすみません)

**Comment by ocean3fish** [comment]
@maconaco こちら以下のissueと重複と思われるため、ご確認頂けるでしょうか？
https://github.com/tokyo-metropolitan-gov/covid19/issues/1177
なお、この変更が受け入れられるかどうかについては現在関係者で確認中です。

**Comment by maconaco** [comment]
@ocean3fish 確認しました！
PRの方も見ましたが少しだけ違いを感じたので
現在実装したものをスクリーンショット載せます。

## pc
<img width="1393" alt="スクリーンショット 2020-03-15 20 06 09" src="https://user-images.githubusercontent.com/46955104/76700343-eb5f4280-66f9-11ea-8b37-59c1f86aa283.png">

## sp
<img width="341" alt="スクリーンショット 2020-03-15 20 10 56" src="https://user-images.githubusercontent.com/46955104/76700345-f0bc8d00-66f9-11ea-96df-be842ec31421.png">

どちらも開いた瞬間にわかるようにと対応しています。
的外れなことをいっていたらすみません。

**Comment by maconaco** [comment]
@ocean3fish 
対応したので一応見ていただけると幸いです！

#1535

**Comment by ocean3fish** [comment]
@maconaco 
ご連絡ありがとうございます！
PR https://github.com/tokyo-metropolitan-gov/covid19/pull/1258 との実装の違いについてはよく理解いたしました。
ただ、issue https://github.com/tokyo-metropolitan-gov/covid19/issues/1516 で周知させて頂いた通り、見た目を大きく変えるような変更については関係者での確認が必要となるため、私の一存で判断することができず、一定のお時間を頂きます。
また、本件は既にissueが立っていて、PRも頂いていることから、そちらが優先という判断になる可能性もございます。
現在大変多くの方々にご協力頂いているため、このような形の運用となる点ご理解頂けますでしょうか。

**Comment by maconaco** [comment]
@ocean3fish

理解して頂けて光栄です😭

はいもちろんです！
mergeされたら嬉しいなとは思っていますが
優先順位などあると思いますのでお手隙でお願いします！
これからも何か貢献できそうなことがありましたら貢献させていただきます！
お忙しい中ご対応ありがとうございました！

**Comment by kaizumaki** [comment]
@maconaco お待たせしてしまってすみません 🙇‍♀ 
似たようなissueが複数立っており、関係各所で検討した結果、 #1866 のほうを採用することになりました。 @maconaco さんにはたいへん失礼なことをしてしまい申し訳ありませんでした。
またご協力いただけたらうれしいです。

**Comment by maconaco** [comment]
@kaizumaki 

ご連絡ありがとうございます！
通った方のPR拝見しました！
そちらのほうが若干コードの変更量も少ないですし異論は無いです！
もしも、余裕があれば
どのような理由でそちらが採用と決まったのか今後のためにも教えていただけたら嬉しいです😭

**Comment by kaizumaki** [comment]
@maconaco ご返事ありがとうございます！おっしゃるとおり、コードの変更量が少ないというのは大きいです。見た目の変更もシンプルですし。見た目に関する変更は、多少のインパクトが伴いますし、オーナーに提案する場合の通りやすさも考えたりします。
こちらの提案内容については、そもそも変更する必要はないのではないかとの判断がくだっていた経緯もあり、今回はインパクトの少ないほうを採用させていただきました（本当にわずかな差だったのですけども...）。申し訳ないです 🙇‍♀

**Comment by maconaco** [comment]
@kaizumaki なるほど、コードの変更点以外にも見た目の変更はプログラマー以外の方の権限もあったのですね。
そうですよね、変更のインパクトで言うと確かに私のはスマホユーザーの方に特にびっくりさせてしまうかもです。
いえ、とても勉強になりました！また何かあれば貢献チャレンジしてみます！
