### ISSUE TITLE
お知らせの外部リンクアイコン部分が改行されてしまっている

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1528]
## 起こっている問題 / The Problem
- お知らせ部分の、外部リンクアイコンが改行されてしまっている。

## スクリーンショット / Screenshot

`development` 環境
![image](https://user-images.githubusercontent.com/16509/76699526-8e5f8e80-66f1-11ea-89e6-b06bceb3df0b.png)

`master` 環境
![image](https://user-images.githubusercontent.com/16509/76699534-ae8f4d80-66f1-11ea-9b5f-961794818af1.png)

## 期待する見せ方・挙動 / Expected Behavior
- 改行しないようにしたい

## 起こっている問題の再現手段 / Steps to Reproduce

dev 環境 (https://dev-covid19-tokyo.netlify.com/) で再現

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome / Safari で確認

**Comment by shgtkshruch** [comment]
#805 の修正が影響していそうです。
まだどなたも着手されてなければ、対応いたします。

**Comment by shgtkshruch** [comment]
#1526 で対応いただいていますが、2点気になるところがありましたので、一旦別にプルリクエストを作成させていただきます。

- `wait` ラベルがついた issue の対応なので、リリースまで時間がかかりそう
- モバイル時のレイアウトが `master` と変わっている

（不要な場合はお手数ですがリジェクトしていただければと思います 🙏 ）

**Comment by halsk** [comment]
ありがとうございます！取り急ぎ、影響の少ない #1534 を取り込ませていただきました。
