### ISSUE TITLE
環境変数を.env.<env-name>ファイルに記述して@nuxtjs/dotenvで読み込む

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#1538]
## 改善詳細 / Details of Improvement
- 環境変数を`config/<env-name>.ts`ファイルではなく`.env.<env-name>ファイル`に記述する
- `@nuxtjs/dotenv`モジュールのオプションで、ビルド時の環境によって読み込む`.env.<env-name>`ファイルを切り替える

## 期待する見せ方・挙動 / Expected behavior
- 環境変数が`.env.<env-name>ファイル`に記述されている
- `@nuxtjs/dotenv`によって環境変数が読みこまれ、アプリケーション内の`context`や`process.env`から取得できる

## 📝 関連する issue / Related Issues
- #1536
- #1537

## 参考リンク / See also
- [nuxt-community/dotenv-module: Loads your .env file into your application context](https://github.com/nuxt-community/dotenv-module)

**Comment by halsk** [comment]
@munierujp さん、
dotenv による方法、generate 時のオプションで切り替えるのがうまくいかなくて、苦肉の策で今の形になりました。よかったらpull requestいただけないでしょうか？
私が何かケアレスミスをしていただけかもしれません。
以下のように動けば完璧です。

本番で叩いているコマンド yarn run generate:deploy
=> NODE_ENV === 'production' にしたい
ステージング等で叩いているコマンド yarn run generate:dev
=> NODE_ENV === 'development' にしたい
ローカル開発 yarn dev
=> NODE_ENV === 'development' にしたい

**Comment by munierujp** [comment]
@halsk 試してみます。

>期待する NODE_ENV値

こちらは`GENERATE_ENV`の間違いでしょうか？

**Comment by halsk** [comment]
あ、一般的に使われている NODE_ENV が使えるわけでは無いのですね。
今は一般的に使われる NODE_ENV じゃなくて GENERATE_ENV を使っていますが、dotenv のやり方だと NODE_ENV が使えるって意味かと思っていました。
結果的に同じになるのであれば、今のやり方でなくdotenv を使うメリットってなんでしょうか。

**Comment by munierujp** [comment]
@halsk 

>あ、一般的に使われている NODE_ENV が使えるようになるってことではないのですね。

はい。dotenvを使用したとしても`NODE_ENV`の値は実行時の環境になります。

>結果的に同じになるのであれば、今のやり方でなくdotenv を使うメリットってなんでしょうか。

もともとこのリポジトリの`nuxt.config.ts`にも`@nuxtjs/dotenv`モジュールが存在しているように、環境変数を設定する場合はdotenvを使用するのが一般的な手法です。

[API: env プロパティ - NuxtJS](https://ja.nuxtjs.org/api/configuration-env/#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0%E3%81%AE%E8%87%AA%E5%8B%95%E6%B3%A8%E5%85%A5)

そのため、`config/<env-name>.ts`ファイルを作る方式よりもコントリビューターがプロジェクトの構成を理解しやすいというメリットがあります。

**Comment by halsk** [comment]
説明ありがとうございます。明日動作確認して、問題なければ取り込みますね。
