### ISSUE TITLE
表(table)headerをスクロール時に固定にする

### ISSUE THREAD

**Issue by hkomamiy** [tokyo-metropolitan-gov/covid19#154]
v-data-tableのスクロール時に表のheader(項目)も一緒にスクロールされてしまいます。

**Comment by sunecosuri** [comment]
> v-data-tableのスクロール時に表のheader(項目)も一緒にスクロールされてしまいます。

おそらく利用箇所が一箇所しかなさそうなのですが、`fixed-header` にtrueと変更されているようなので修正済みのようにみえます 
https://github.com/tokyo-metropolitan-gov/covid19/blob/cbff79f250dc6ec50ec6ac40a1c0e6c1a8b9baeb/components/DataTable.vue#L12

**Comment by anyuKazu** [comment]
3/2 21:21このissueが作られ、3/3 01:02に以下のプルリクエストで該当のコードがstagingブランチにマージされました。
現在はmasterブランチにも反映されているので、現在はこのissueの事象は発生していないと考えられます。
https://github.com/tokyo-metropolitan-gov/covid19/pull/178

実際にChrome, Safari, FireFox, Operaでは事象は発生しておりません。
また以下のドキュメントによるとIE11ではfixed-headerタグは動作しないとのことですが、SafariのユーザーエージェントをIE11に設定しての動作確認では問題ありませんでした。（推奨環境ではないですが、念のため）
参考：https://vuetifyjs.com/ja/components/data-tables

私の環境ではEdgeで動作確認できないため、どなたかにEdgeで問題ないことを確認していただければcloseしてよいと思います。

**Comment by iwamot** [comment]
はじめまして。Edgeだと、下から上にスクロールするとヘッダが崩れてしまいます。

![Edge](https://user-images.githubusercontent.com/16149/75945105-a9a1f100-5edc-11ea-9a68-44d63657f309.png)

**Comment by 4geru** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/178 で対応されているようです 👍

**Comment by potato4d** [comment]
対応済みのためクローズ
