### ISSUE TITLE
グラフ表示の際のアニメーションは不要に見えるので消したい

### ISSUE THREAD

**Issue by him0** [tokyo-metropolitan-gov/covid19#1542]
## 改善詳細 / Details of Improvement
グラフが画面上に表示された際に、高さ 0 から 規定の数値まで棒グラフが伸びるアニメーションが実装されているのです。このサイトが伝えた情報は、正確な数値であり、値に対する驚きではないのでこのアニメーションは不要であると思います。

## スクリーンショット / Screenshot
![Mar-15-2020 22-41-10](https://user-images.githubusercontent.com/8267344/76702579-1d7a9f80-670e-11ea-8d81-731930577946.gif)

## 期待する見せ方・挙動 / Expected behavior
通信を見る感じ非同期処理ではない（まだソースコードちゃんと追えてません）ようなので、chart.js のアニメーションを単純に消すのがいいように見えます。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by RyotaUmebayashi** [comment]
アニメーションを消す方法は、いくつかの方法があるようですが
https://github.com/chartjs/Chart.js/issues/371
個別に安全に消すなら`animation:false`を追加するのが良いと考えます。

issue本文のスクリーンショットの画面例なら
ファイル：components/TimeBarChart.vue

```
   displayOption() {
      const unit = this.unit
      const scaledTicksYAxisMax = this.scaledTicksYAxisMax
      return {
        tooltips: {
          displayColors: false,
          callbacks: {
            label(tooltipItem) {
              const labelText = `${parseInt(
                tooltipItem.value
              ).toLocaleString()} ${unit}`
              return labelText
            },
            title(tooltipItem, data) {
              return data.labels[tooltipItem[0].index]
            }
          }
        },
        responsive: true,
+       animation:false,
        maintainAspectRatio: false,
```

**Comment by pepaperonp** [comment]
アニメーションがないと寂しい気がするので反対だったのですが、直してみたところ案外良かったので、アニメーション賛成派の私が修正します！

**Comment by oti** [comment]
@kaizumaki  本件、確認お願いしたいです。

**Comment by kaizumaki** [comment]
結構影響が大きそうなので、PRのほうをオーナーに確認にまわしますね。ただ、現在 `waiting-for-confirmation` がたまっていますので、こちらのissueは優先度は低めになりそうです。

**Comment by kaizumaki** [comment]
@him0 ご提案ありがとうございます。こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/1863#issuecomment-617669553 にコメントいたしました。ご理解いただきますようよろしくお願いいたします。

**Comment by kaizumaki** [comment]
こちらのissueはクローズさせていただきます。
