### ISSUE TITLE
お知らせと各コンポーネントの更新日の日付のフォーマットが多言語対応されていない

### ISSUE THREAD

**Issue by biga816** [tokyo-metropolitan-gov/covid19#1543]
## 起こっている問題 / The Problem
- お知らせと各コンポーネントの更新日の日付のフォーマットが多言語対応されていない
(お知らせについてはこちら https://github.com/tokyo-metropolitan-gov/covid19/pull/1456 の改修と足並みを揃える必要あり。)

## スクリーンショット / Screenshot
ja
<img width="1436" alt="都内の最新感染動向___東京都_新型コロナウイルス感染症対策サイト" src="https://user-images.githubusercontent.com/10794545/76703254-c11a7e80-6713-11ea-82a9-3df5f3870f5d.png">

en
<img width="1437" alt="スクリーンショット_2020_03_15_23_22" src="https://user-images.githubusercontent.com/10794545/76703270-e1e2d400-6713-11ea-9944-623ea0b6d374.png">

## 期待する見せ方・挙動 / Expected Behavior
- localeに合わせてYYYY/MM/DDやMM/DD/YYYYなど表記を変更さセル。また併せて全ての場所で表記を統一させる。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 各言語で画面を初期表示する。

## 動作環境・ブラウザ / Environment
依存なし。

**Comment by UrangUrang** [comment]
#1456のIssueを扱っているものです。
この件も一緒に作業するようにします。宜しくお願いします。

**Comment by MaySoMusician** [comment]
@UrangUrang ありがとうございます。ブランチに関してですが、 `dev-i18n`からブランチを作成して、PRも `dev-i18n` に向けていただけると大変助かります（`development`とはファイル構造が大きく異なっておりますので）

**Comment by UrangUrang** [comment]
@MaySoMusician 承知いたしました。
ちなみに、英語のDatetimeの最後的な表示形に関して相談したいですが。
”Mar 13, 2020 11:03”のように実装するつもりですがどう思いますか？

**Comment by MaySoMusician** [comment]
日付の表示パターンについては（正確な方針はまだ決まっておりませんが）

- 年月日+日付（2020/03/13 11:03 や Mar. 13, 2020, 11:03）
- 年月日のみ（2020/03/13 や Mar. 13, 2020）
- 月日のみ（03/13 や Mar. 13）

の3種類にまとまると思います（更新日時やグラフのX軸など、使用場所によってスペースや得られる情報の範囲が異なる）

これらがそれぞれ得られると良いかなと思います（関数を分けるか、引数でswitchするかは、現時点ではお任せいたします。後々方針が決定したとき要望があるかもしれません）

https://github.com/tokyo-metropolitan-gov/covid19/pull/1456#issuecomment-599221044 でも言及しましたが、現在使用しているdayjsにも言語別フォーマットの機能があるようなので、そちらを活用する手もあるかもしれません

最後に、繰り返しになりますが、日付に関しては元データの構造が少し不確定なことも影響して、後々方針転換する可能性もありますことをご承知おきください。

**Comment by UrangUrang** [comment]
@MaySoMusician 
反応が遅かったのですみません。
日付けの表示に関しては承知したしました。

ですが、dayjsの言語別フォーマットについて調べてみましたが。
`dayjs(dateString).locale(locale).format()`
のような感じでlocaleの指定はできます。だがformatを指定しないと全ての言語が同じように日付けを表示します。
結局localeの値で判断してformatを切り替えるしかないと思ってます。

もし、他に良い方があれば教えてください。なければ現在のLogicとは大きな変化はないと思います。

**Comment by biga816** [comment]
横から失礼します。
ここのドキュメント見る限りだと、day.jsでもformatに`l`とか`L`とか使えそうな気が。
https://day.js.org/docs/en/i18n/i18n
https://github.com/iamkun/dayjs/blob/dev/src/locale/ja.js

**Comment by biga816** [comment]
こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/1660 クローズとなったようですが、今後どのような対応になるのでしょうか。
必要であれば対応いたします！

**Comment by MaySoMusician** [comment]
こちらの件ですが、都に確認したところ採用したいとのことでした。

実装方法ですが、dayjsやmoment.jsの言語別翻訳だと、英語などは問題ないのですが日本語や中国語などで区切り文字（年、月、日などの文字）を挿入するためにカスタムで形式を指定する必要がありました。
一方、nuxt-i18n（vue-i18n）の日付翻訳機能はJavaScriptのIntlオブジェクトを用いた翻訳を行なっており、そちらは区切り文字を自動で挿入してくれました。導入準備は既に #3838 で完了しており、またローカル環境で検証したところこのプロジェクトではIntlオブジェクトも各言語で有効になっているようなので、今回はnuxt-i18n（vue-i18n）の `$d()` を使用して各所を翻訳していく方針です

**Comment by biga816** [comment]
@MaySoMusician 
こちら、どなたかすでに対応中でしょうか？
私の方で対応も可能です。

**Comment by MaySoMusician** [comment]
@biga816 こちら着手の連絡は来ておりません。
もしお手すきでしたらお願いしてもよろしいでしょうか？

**Comment by biga816** [comment]
@MaySoMusician かしこまりました、対応します。
ちなみにここで定義されているvue-i18nの各言語ごとの日付フォーマットは確定しているので修正不要という認識であっていますでしょうか。
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/nuxt-i18n.config.ts#L12
