### ISSUE TITLE
最新情報のエリアごとタップできるようにする

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#155]
下の「自分の症状に…」の部分でエリアタップをできるようにして頂いたので、こちらも合わせてしまいましょう。

![image](https://user-images.githubusercontent.com/1301149/75676046-cca98680-5ccb-11ea-9b02-cc84bb44d376.png)

**Comment by kenshir0f** [comment]
対応します 🙋
