### ISSUE TITLE
相談フローページの「詳細を見る」ボタンを大きくする

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#156]
![image](https://user-images.githubusercontent.com/1301149/75676312-55c0bd80-5ccc-11ea-9a10-534c9366c1f8.png)

詳細サイズは↓Figmaから
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=219%3A3285

現状のボタンの大きさだと気づかなそうなので大きさを調整します。

**Comment by saladdays** [comment]
ワガママを言うならば、スマホビューにしたときは現状のサイズにしたい。

**Comment by kenshir0f** [comment]
対応しますー
