### ISSUE TITLE
サイドメニュー内リストアイテムのhover時のスタイル調整

### ISSUE THREAD

**Issue by himatani** [tokyo-metropolitan-gov/covid19#1566]
## 改善詳細 / Details of Improvement
- リストアイテムをhoverした際、１行だったテキストが２行になるケースがある

## スクリーンショット / Screenshot

通常時  | hover時
------------ | -------------
<img width="252" alt="スクリーンショット 2020-03-16 1 49 54" src="https://user-images.githubusercontent.com/37978173/76706544-8d4b5300-672b-11ea-8cbc-7d598dce3ae6.png">  | <img width="256" alt="スクリーンショット 2020-03-16 1 50 15" src="https://user-images.githubusercontent.com/37978173/76706546-8fadad00-672b-11ea-807c-ce1f5cb43961.png">

## 期待する見せ方・挙動 / Expected behavior
- hover時でも文字幅が変わらないこと

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by himatani** [comment]
#1481,  #1522 で対応中です

**Comment by kaizumaki** [comment]
関連するPRがマージされていますので、こちらのissueはクローズさせていただきます。
