### ISSUE TITLE
開発者が「するべき」「してはいけない」事を記載したチケットにラベルRULEを付ける

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#1567]
## 改善詳細 / Details of Improvement
1. [Labels](https://github.com/tokyo-metropolitan-gov/covid19/labels)に`RULE`を追加する
1. 開発者が「するべき」「してはいけない」事を記載したチケットにラベル`RULE`を付ける

## 期待する見せ方・挙動 / Expected behavior
開発者が「するべき」「してはいけない」事を記載したチケットにラベル`RULE`が付く事により、開発者が必要な情報をすぐに得る事ができるようになる。

以下は、現在の運用で、私が感じた問題点です。
- [タイトルに`周知`が含まれ、ラベル`IMPORTANT`が付いているチケット](https://github.com/tokyo-metropolitan-gov/covid19/issues?q=is%3Aissue+label%3AIMPORTANT+is%3Aopen+%E5%91%A8%E7%9F%A5)がルール的な扱いになっているが、必要な情報を得る為には、複数回の操作が必要である。
- Pinned Issuesは今後も入れ替わる事が想定されるが、必要な前提知識を等しく得られるようにする必要がある。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
ご提案ありがとうございます。採用します！
