### ISSUE TITLE
相談フローページの図をスマホのときはスマホ用のものにする

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#157]
林さんにスマホ用のものもお作り頂いているのでこちらで！
https://xd.adobe.com/view/ecc67e93-2a3e-4590-64be-6dae523e2e6a-9af7/screen/5897a931-d20e-42f4-8ac9-6f5ee2310fd2/sp-flowimg

**Comment by kenshir0f** [comment]
対応しますー

**Comment by kenshir0f** [comment]
こちら hayashi さんに対応お願いしました 🙏

**Comment by halsk** [comment]
#167 と関連かな？

**Comment by mikkame** [comment]
#167 もそうなんですが
これは画像対応でいいですか？
コーディングで組み直した方がいいですか？

- コーディング
  - 時間が取られる
- 画像
  - すぐ反映できる
  - とりあえずリンクっぽいのはimgmapで対応？

**Comment by forestgtree** [comment]
#167 もそうですね。
@kenshir0f にslackでコーディング引き継ぎしました。

全コーディングするのは結構時間がかかりそうですよね。
画像で組み上げてしまうのが早いと思います。

**Comment by mikkame** [comment]
@forestgtree さん確認ありがとうございます！
@kenshir0f さんは夜組かな？

@halsk 本日11時ぐらいまでにとりあえず更新する必要があるようでしたら画像に差し替える方向で
一旦処理していこうと思いますがどうでしょうか

**Comment by halsk** [comment]
11時の時点では、まだ本番のURLが伝えられるだけなので、夕方のリリースまでに間に合えば大丈夫です！

**Comment by mikkame** [comment]
@halsk 再確認です。夕方時点では画像でOKですか？コーディングの方がいいですか？
or 間に合う方って解釈でしょうか

**Comment by halsk** [comment]
画像で良いです！

**Comment by kaizumaki** [comment]
@forestgtree @kenshir0f @mikkame @yokinist 
フロー図を改めてよく見てみました。モバイルとデスクトップで異なっているディテールが結構あるなと思いました。
とりあえず、今日の夕方に間に合わせるために、
- **デスクトップは１枚画像（電話番号リンクなし）** ←PCから電話番号リンクを使う可能性は少ないだろうと判断
- **モバイルは画像を細かくして配置（電話番号リンク＆アンカーリンクあり）**

という作戦でいこうと思います。これだとモバイルはほぼ縦に並べていくだけでできそうです。
いかがでしょう？

**Comment by mikkame** [comment]
差し替えが楽そうで良いと思います。（ちょいちょい修正来そうですし）
