### ISSUE TITLE
READMEの英語バージョンのリンクがない

### ISSUE THREAD

**Issue by TaigaMikami** [tokyo-metropolitan-gov/covid19#1572]
## 改善詳細 / Details of Improvement
READMEの各言語のバージョンに英語バージョンのリンクがないと思いました。
意図的であったらすみません:bow:

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-16 2 57 08](https://user-images.githubusercontent.com/25325947/76707357-e1593600-6731-11ea-8af3-8387a955f351.png)

## 期待する見せ方・挙動 / Expected behavior
- 各READMEにREADME英語バージョンのリンクを追加する

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by munierujp** [comment]
もしかすると、「現在の言語にはリンクをつけない」という意図だったのかもしれません。

**Comment by halsk** [comment]
前はリンクされていたような気が？修正提案ありがとうございます！
