### ISSUE TITLE
日本語以外の言語設定をしたブラウザで、ローディング画面で止まる問題

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1585]
## 起こっている問題 / The Problem
- ブラウザ言語の設定が日本以外で、初回アクセスの際にローディング画面のまま止まってしまう
- 過去 #1175 で似たような不具合への対応があった。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/76712661-3a3ec380-675e-11ea-93f6-56e76575daa5.png)

## 期待する見せ方・挙動 / Expected Behavior
- 言語の自動判定の時に、`https://stg-covid19-tokyo.netlify.com/en` ではなく `https://stg-covid19-tokyo.netlify.com/en/` に飛ばすのが理想。

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザの言語設定を英語にする
2. Cookie を削除し `https://stg-covid19-tokyo.netlify.com/` にアクセスする

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari
おそらく全ての環境で同様

**Comment by MaySoMusician** [comment]
#1611 にて解決する可能性があります

**Comment by macropygia** [comment]
@halsk 本issueのPR先は `development` と `dev-hotfix` のいずれでしょうか。

**Comment by halsk** [comment]
@macropygia `development` でお願いします。
