### ISSUE TITLE
スマホ表示の余白調整

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#159]
全体的に余白が大きくなっているので調整をお願いします

現在左右28pxを16pxに

![image](https://user-images.githubusercontent.com/1301149/75676801-5c036980-5ccd-11ea-8411-28621de5076d.png)

**Comment by daitasu** [comment]
こちら対応します！

**Comment by halsk** [comment]
> こちら対応します！

ありがとうございます！Issue 始める場合、自分を アサインしておいていただけると見やすくて助かります！

**Comment by daitasu** [comment]
了解しました！アサイン権限がないようなので、どなたか権限いただけますと助かります 🙏

**Comment by halsk** [comment]
> 了解しました！アサイン権限がないようなので、どなたか権限いただけますと助かります 🙏

失礼しました！招待しました

**Comment by daitasu** [comment]
夜分にすみません、ありがとうございます ！！！
