### ISSUE TITLE
スマホ版のメニューを開くとすぐに閉じてしまう

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#160]
ハンバーガーメニューを押すと一旦開けるのですが、数秒後に閉じてしまいます（ステージング環境で確認）

PC版 Chrome
iPhone 11 Pro / iOS 13 Safariで確認

**Comment by kaizumaki** [comment]
確認します！

**Comment by kaizumaki** [comment]
ああ、なるほど、ローディングが作用しているみたいですね。対応します。
