### ISSUE TITLE
stylelintで使用するルールを設定する

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#1600]
## 改善詳細 / Details of Improvement
- stylelintのルールが空なので、[stylelint-config-standard](https://www.npmjs.com/package/stylelint-config-standard)を導入する
  - このプロジェクト固有の書き方があり、修正範囲が多岐にわたる場合は一部のルールをカスタマイズする
- SCSS対応のため、[stylelint-scss](https://www.npmjs.com/package/stylelint-scss)を導入する
- それにともない、ルール違反となる既存のCSS/Sassのコードを修正する 

## 期待する見せ方・挙動 / Expected behavior
- stylelintによってCSS/SCSSのコードがリントされる状態になっている
- stylelintのルールに違反するCSS/SCSSのコードが修正されている

## 📝 関連issue/Related issue
- #856
- #1616

## 📝 関連プルリクエスト/Related Pull request
- #810

## 参考リンク / See also
- [Nuxt.jsのプロジェクトにstylelintを導入する方法 - Qiita](https://qiita.com/munieru_jp/items/ea41284f473ad3669616)

**Comment by munierujp** [comment]
自分がやります！

**Comment by kawokas** [comment]
ESLintのときに、lintのタイミングがpre commit hookだけだとskipされたコミットがdevに入ってしまって該当fileをコミットできなくなる問題がおこってしまったので、CI環境を先に整えた方がいいかも？と思いました〜！！念のため！ 🙇 
https://github.com/tokyo-metropolitan-gov/covid19/issues/539

**Comment by munierujp** [comment]
@kawokas ありがとうございます😄

**Comment by munierujp** [comment]
#1616 を先にやったほうがよさそう

**Comment by munierujp** [comment]
#1651 がマージされたので、今夜やります！
