### ISSUE TITLE
日本語card OGP画像がエラー画面になっている

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1602]
## 起こっている問題 / The Problem
- 日本語card OGP画像がエラー画面になっている

## スクリーンショット / Screenshot
<img width="513" alt="スクリーンショット 2020-03-16 13 33 58" src="https://user-images.githubusercontent.com/8909592/76723500-d54d9280-678a-11ea-8996-c77b64556b41.png">

## 期待する見せ方・挙動 / Expected Behavior
- 日本語版のカードの画像が表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 各カードのシェアリンクをSNSで共有し、展開画像を見る

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amotarao** [comment]
やります

**Comment by halsk** [comment]
頂いた修正で、画像が無事取れるようになったので、そちらで OGP を取り直して本番に反映させました。
Facebook Share Debugger でキャッシュ再生成済です。Twitter Validator でも対応中。
迅速な対応、ありがとうございました！
