### ISSUE TITLE
OGP Builder: データが変わっていないのに画像が変わっている

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1608]
## 起こっている問題 / The Problem
- OGP生成時、vue-chart の描画が終了する前にスクリーンショットが撮影されている模様
- データが変わってないのに画像が変わっている
  - https://github.com/tokyo-metropolitan-gov/covid19/pull/1606/files

### 実際のデータ
<img width="500" alt="スクリーンショット 2020-03-16 16 12 34" src="https://user-images.githubusercontent.com/8909592/76731527-f9b46980-67a0-11ea-9fa5-5e288a427a63.png">

### OGP Builder 生成画像
左右はどちらも OGP Builder だが、毎回画像が変わる様子
<img width="900" alt="スクリーンショット 2020-03-16 14 45 53" src="https://user-images.githubusercontent.com/8909592/76726579-e4394280-6794-11ea-82ab-9f119af4b066.png">

**Comment by amotarao** [comment]
考えられる解決

- OGP撮影時のみ vue-chart のアニメーションをなくす
- vue-chart のアニメーションが終了してからスクリーンショットする

**Comment by nichesuch** [comment]
@amotarao 結局問題が発生してしまいましたね。すみません。

**Comment by amotarao** [comment]
@nichesuch window.load 後に描画されるようなので、あの時点では気づく余地がなかったと思います。selenium の仕様を教えていただき感謝しております！ 🙏

**Comment by mikkame** [comment]
とりあえずsleepを挟む方向で調整してみます

**Comment by shgtkshruch** [comment]
OGP 撮影時は URL パラメータに `embed=true` がつく仕様でしょうか？

https://github.com/tokyo-metropolitan-gov/covid19/blob/01579019ba9fba0ef0f9469abc8dad1694c43a14/ui-test/ogp_screenshot.py#L28

そうであれば、URL で判定して OGP 撮影時のみ vue-chart のアニメーションをなくすこともできそうです。
Chart.js に `duration` のオプションがあるので、これを 0 にすればアニメーションは無効になります。
https://www.chartjs.org/docs/latest/configuration/animations.html

**Comment by amotarao** [comment]
>OGP 撮影時は URL パラメータに embed=true がつく仕様

現状ではその通りです

**Comment by amotarao** [comment]
また別 Issue での検討がよさそうですが、
ブロク等への埋め込み用のquery と スクリーンショット撮影時用のquery がどちらも `embed=true` なのがいかがかなーと思っています
埋め込みパーツでもアニメーションしないことになります

**Comment by mikkame** [comment]
とりあえず急場はsleepでしのぐ方向で・・・
https://github.com/tokyo-metropolitan-gov/covid19/actions/runs/56724148
取り急ぎグラフの線とYスケールはいい感じに揃って見えるようになったはずです。
検証のためリトライ中・・・

**Comment by amotarao** [comment]
card 8枚 x 6言語 = 48枚の生成
sleep秒数によってはとんでもない時間かかりそうですね...。

**Comment by mikkame** [comment]
sleep5秒でとりあえず11分ぐらいですね

**Comment by mikkame** [comment]
中国語のフォントが若干diff出るぐらいでその他は差がでないようになりました。

**Comment by mikkame** [comment]
![diff](https://user-images.githubusercontent.com/13947046/76764747-b7a71a00-67d8-11ea-8aa9-e3b1ab58d8ed.gif)
謎のDIFFです

**Comment by mikkame** [comment]
フォントの読み込み遅れかなぁ・・・

**Comment by amotarao** [comment]
@mikkame 対応ありがとうございます！

フォントっぽいですね...。ただアイコン以外のWebフォント読み込んでないはず...。

**Comment by mikkame** [comment]
中国語表示にした時に中国語っぽいフォントになるような気がします

**Comment by amotarao** [comment]
selenium のページ遷移時に SPA っぽく切り替わるのですかね

**Comment by amotarao** [comment]
#1644 #1646 出てきた話題をIssue化しました
