### ISSUE TITLE
プルリクエスト作成時にGitHub Actionsでstylelintを実行

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#1616]
## 改善詳細 / Details of Improvement
- ESLintと同様に、プルリクエスト作成時にGitHub Actionsでstylelintを実行する

## 期待する見せ方・挙動 / Expected behavior
- プルリクエストを作成すると、GitHub Actionsでstylelintが実行される
- stylelintでエラーが出ている場合、マージできない状態になっている

## 関連Issue/ Related Issues
- #1600

## 関連プルリクエスト / Related Pull Requests
- #650
- #772

## 参考リンク / See also
- [covid19/reviewdog.yml at development · tokyo-metropolitan-gov/covid19](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/workflows/reviewdog.yml)
- [reviewdog/action-stylelint: Run stylelint with reviewdog](https://github.com/reviewdog/action-stylelint)

**Comment by munierujp** [comment]
https://github.com/munierujp-sandbox/covid19 で実験していきます。

**Comment by munierujp** [comment]
https://github.com/munierujp-sandbox/covid19 で実験した結果、`.github/workflows/reviewdog.yml`のみを更新すればよさそう。

https://github.com/munierujp-sandbox/covid19/pull/2

## プルリクエスト作成時の挙動
### sylelintのルールがないとき（現在の`development`ブランチの状態）
- stylelintが実行される
- stylelintによるリントが成功する

![スクリーンショット 2020-03-16 23 49 00](https://user-images.githubusercontent.com/20086673/76770187-ddd0b800-67e0-11ea-9ffc-9c36366527b6.png)

https://github.com/munierujp-sandbox/covid19/pull/4

### sylelintのルールがあるとき
- stylelintが実行される
- stylelintによるリントが失敗する

![スクリーンショット 2020-03-16 23 49 06](https://user-images.githubusercontent.com/20086673/76770210-e6c18980-67e0-11ea-9a47-9eb3b6e8ca26.png)

https://github.com/munierujp-sandbox/covid19/pull/3

**Comment by kawokas** [comment]
ありがとうございます！！ 🙇
