### ISSUE TITLE
Add french translations for README, CODE_OF_CONDUCT, and CONTRIBUTING

### ISSUE THREAD

**Issue by BPetitSurble** [tokyo-metropolitan-gov/covid19#1618]
## 改善詳細 / Details of Improvement
- Add french translations for README, CODE_OF_CONDUCT, and CONTRIBUTING

## 期待する見せ方・挙動 / Expected behavior
- Add pages for french contributors

## 動作環境・ブラウザ / Environment
- https://github.com/tokyo-metropolitan-gov/covid19

**Comment by kaizumaki** [comment]
I close this issue as the related PR has been merged.
