### ISSUE TITLE
[お子様をお持ちの皆様へ]のアイコン 変更

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#162]
| ベビーカーだと未就学児に限定されてしまうため、他のモチーフに変更をお願いします。
-- | --

**Comment by kenshir0f** [comment]
@saladdays コレお願いできますか？

**Comment by forestgtree** [comment]
手が空いたので、私やりますよー

**Comment by forestgtree** [comment]
アイコンsvg、作りました！
[parent_and_child_icon.zip](https://github.com/tokyo-metropolitan-gov/covid19/files/4276114/parent_and_child_icon.zip)

**Comment by saladdays** [comment]
ステキアイコンありがとうございます。
アイコン差し替えやりまっす！

**Comment by saladdays** [comment]
ゴメンなさい、持ち続けてしまった。

ちょっと他作業に手が取られてしまっているので、どなた引き取っていただけると大変助かります🙇

↓svgだけupしてある状態です
https://github.com/tokyo-metropolitan-gov/covid19/tree/feature/issue-162-change-icon

**Comment by yokinist** [comment]
ちょうど今やっているので対応します！

**Comment by saladdays** [comment]
助かります！！
