### ISSUE TITLE
グラフシェア時のテキストに説明文を追加

### ISSUE THREAD

**Issue by yokinist** [tokyo-metropolitan-gov/covid19#1628]
## 改善詳細 / Details of Improvement
- グラフシェア時のデフォルトテキストに説明文もつける
- 現在はURLだけ

## スクリーンショット / Screenshot

[![Image from Gyazo](https://i.gyazo.com/c6bc1b33fdc54753963b042e668ffa0e.png)](https://gyazo.com/c6bc1b33fdc54753963b042e668ffa0e)

## 期待する見せ方・挙動 / Expected behavior
[![Image from Gyazo](https://i.gyazo.com/728347fa88a361a7c4bb89421eea078e.png)](https://gyazo.com/728347fa88a361a7c4bb89421eea078e)
- `{グラフの名称} | 東京都 新型コロナウイルス感染症対策サイト {URL}`
- ハッシュタグあれば合わせてつける

**Comment by halsk** [comment]
ハッシュタグは #StopCovid19JP です
