### ISSUE TITLE
企業の皆様・はたらく皆様へ ページを内部化する

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#164]
当該ページの外部リンクをやめて、以下の構成のページにする

タイトル：「企業の皆様・はたらく皆様へ」に変更

内容：
中小企業者等特別相談窓口 https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/01/30/15.html
資金繰りに関する相談、経営に関する相談（東京都産業労働局 報道発表）

緊急労働相談ダイヤル
https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/02/26/22.html
新型コロナウイルスに関する休暇や休業の取り扱い、職場のハラスメントなどについての相談（東京都産業労働局　報道発表）

新しいワークスタイルや企業活動の東京モデル「スムーズビズ」
https://smooth-biz.metro.tokyo.lg.jp/
テレワーク・時差出勤などスムーズビズの取組は、新型コロナウイルス感染症の対策としても有効です。感染症対策として、東京2020大会時の交通混雑緩和に向けた取組の前倒しをお願いします。

**Comment by kenshir0f** [comment]
いったんページだけ他のテイストに合わせ、詳細のデザインが決まったらあとから修正する前提で作ります。
