### ISSUE TITLE
言語選択メニューのクリック範囲が小さい

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1643]
## 起こっている問題 / The Problem
- 言語選択メニューのクリック範囲が小さい
  - 以下の select 部分のみ

## スクリーンショット / Screenshot
<img width="224" alt="スクリーンショット 2020-03-16 23 10 42" src="https://user-images.githubusercontent.com/8909592/76766566-8bd96380-67db-11ea-84b1-990e91291753.png">

## 期待する見せ方・挙動 / Expected Behavior
- 見た目上の枠全体がクリックできる

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページを開く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shgtkshruch** [comment]
#854 実装時には `select` 要素全体がクリックできていますが、

![スクリーンショット 2020-03-16 23 23 23](https://user-images.githubusercontent.com/5207601/76767601-3736e800-67dd-11ea-9cb6-0a5afaefda4b.png)

#1253 で文字サイズを調整した際に今の状態になったようです。

期待する見せ方は、こんな感じでしょうか。
- `select` 要素全体がクリックできること
- iOSで言語選択のセレクトをタップした際に画面が拡大されない

今 #1334 で言語選択メニューの多言語対応をされているので、そちらの変更を見てから（必要があれば）対応すると良さそうに思いました。

**Comment by amotarao** [comment]
iOS で拡大しないようにするには font-size: 16px 以上にする

参考: https://openameba.github.io/a11y-guidelines/1/4/4/#%E5%85%B7%E4%BD%93%E4%BE%8B

**Comment by kaizumaki** [comment]
現時点で解消されているようなので、こちらのissueはクローズさせていただきます。
