### ISSUE TITLE
[/cards] 埋め込みパーツ用のquery と OGP画像撮影用のquery を分離する

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1644]
## 改善詳細 / Details of Improvement
- 埋め込みパーツ用もOGP撮影用も `embed=true` なので、仕様が同じ
  - OGP撮影用にグラフのアニメーションを停止しようとすると、埋め込みパーツも同じ仕様になる
    - https://github.com/tokyo-metropolitan-gov/covid19/issues/1608#issuecomment-599530484 で検討

## 期待する見せ方・挙動 / Expected behavior
- queryを分け、仕様が変えられるようにする
- 埋め込みパーツのほうは変えるべきではない (既に各所で埋め込み利用されているので)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nichesuch** [comment]
OGP撮影用は`ogp=true`として、しばらくは`embed=true&ogp=true`をqueryとしておくのはどうでしょうか？
OGP撮影で`embed=true`を使っている箇所が無くなったら削除する想定で。

**Comment by amotarao** [comment]
現状の仕様だと全カード撮影に `embed=true` つけているので、一気に置き換えしても問題はないと思われます

**Comment by nichesuch** [comment]
それでは`ogp=true`とつけて、サイドナビゲーションやローディングは出ないように調整します。
