### ISSUE TITLE
トップページ グラフ等の文言変更

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#166]
コールセンター相談件数 →「新型コロナコールセンター相談件数」へ変更してください。

**Comment by halsk** [comment]
ついでにこれも
"自分の症状に不安や心配があればまずは電話相談をどうぞ
↓
自分や家族の症状に不安や心配があればまずは電話相談をどうぞ"

**Comment by halsk** [comment]
庁内調整の結果、死亡については、単独のカードでは表示しないことになりました。削除でお願いします。
とのことです。

**Comment by halsk** [comment]
タイトルの`最新感染動向` を `都内の最新感染動向` に。
メニューの方の`都内の最新動向` も、`都内の最新感染動向` に

**Comment by saladdays** [comment]
やりまーす
