### ISSUE TITLE
相談フローの修正

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#167]
福祉保健局からの赤入れがありましたので、PDFで恐縮ですが下記ファイルをご確認のうえご対応お願いします。
https://drive.google.com/file/d/1FAYKNagaPp07FD0bjp_9BMqU6LgyOYkp/view

**Comment by forestgtree** [comment]
https://xd.adobe.com/view/ecc67e93-2a3e-4590-64be-6dae523e2e6a-9af7/

- PDF右上の平日（夜間）の時間表記は、コールセンターの表記と揃え午前・午後表記としました。
- PDF右下のレイアウト変更内、緑枠内は「新型コロナ外来」とありますが、外来入れていません。

確認ください。

**Comment by yokinist** [comment]
@forestgtree 早速ありがとうございます！XDから画像データってどうやって保存できますか？（見当たらず・・）

**Comment by halsk** [comment]
乗客の中に、 XD 詳しい方は いらっしゃいませんか〜？
サポートいただければー

**Comment by forestgtree** [comment]
@yokinist XDの右側のナビゲーションを展開すると、「アセット」が表示されて、選択したパーツが段ロードできるようになります。Adobeログインしなくても可能です！
![XD操作説明](https://infosign-inc.gyazo.com/5f840f07ff1e9e39698764c905914c5d/raw)

**Comment by halsk** [comment]
@yokinist だそうです！
