### ISSUE TITLE
お子様をお持ちの皆様へ のページ作成

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#168]
以下のページを作成し、外部リンクをやめる

臨時休校中の新型コロナウイルス感染症対応についてのお願い
１　感染予防・健康管理
　〇　不特定多数の人の集まる場所等への外出を避け、基本的に自宅で過ごしてください。
　〇　手洗い、咳エチケット等により、感染予防に努めてください。
　　　【参考】感染症予防のための正しい手洗い方法（動画）
　　　　　　　https://tokyodouga.jp/lViN9C_BS-0.html
　〇　規則正しい生活を心がけ、日常の健康管理に十分気を付けてください。

２　感染症を疑う場合の対応
　〇　風邪の症状や、37.5度以上の発熱が４日以上続いている、強いだるさ（倦怠感）、
　　息苦しさ（呼吸困難）がある場合は、各保健所にご相談ください。
　〇　「新型コロナウイルス感染症にかかる相談窓口について」（東京都福祉保健局）
　　　https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html

３　その他
　〇　詳細は、各学校からの通知をご確認ください。

**Comment by yokinist** [comment]
やっちゃいモス！
