### ISSUE TITLE
多言語版のトップページの og:url が変わっていない

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1681]
## 起こっている問題 / The Problem
- https://stopcovid19.metro.tokyo.lg.jp/en/ をFacebook Debugger に通しても、OGPの変更が反映されない。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16509/76809371-edc2b900-682d-11ea-896c-98925207d3de.png)

## 期待する見せ方・挙動 / Expected Behavior
- `<meta data-n-head="ssr" data-hid="og:url" property="og:url" content="https://stopcovid19.metro.tokyo.lg.jp">` となっており、これが原因ではないだろうか。正しいURLに変更したい

関連: #1672 

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by showyou** [comment]
./pages/cards/_card.vueの
`content: url + this.$route.path + '/'`
辺りか、

./layouts/default.vueの
`href: ｀https://stopcovid19.metro.tokyo.lg.jp${this.$route.path}｀`
辺りが適用されてない気がしますね。

**Comment by YuseiIto** [comment]
やります!

**Comment by halsk** [comment]
> やります!

アサインしました。ありがとうございます！

**Comment by nard-tech** [comment]
ごめんなさい，#1673 で見落としていました…

**Comment by YuseiIto** [comment]
今原因が掴めました。もうすぐ修正してPR出します。
