### ISSUE TITLE
「企業の皆様へ・はたらく皆様へ」更新

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1682]
「企業の皆様へ・はたらく皆様へ」以下の並び順で、追加・更新をお願いします。
-------------------------
新型コロナウイルス感染症対応緊急融資（⇒※全て書き換えでお願いします）
↓
[新型コロナウイルス感染症に対応した制度融資](http://www.sangyo-rodo.metro.tokyo.jp/chushou/kinyu/yuushi/yuushi/new)
感染症により事業活動に影響を受けている中小企業等を対象とした制度融資（「緊急融資」、「緊急借換」、「危機対応融資」）です。いずれも融資限度額は2億8千万円で、信用保証料を都が補助します。

新型コロナウイルスによる経営課題に関する専門家派遣
（※変更なし）

[中小企業従業員融資](https://www.hataraku.metro.tokyo.jp/kansensyo/index.html)
感染症等の影響による休業での収入減等に備え、中小企業の従業員向けに実質無利子の融資を行います（融資限度額100万円）。

[新型コロナウイルス感染症に係る休業等支援事業（専門家派遣）](https://www.hataraku.metro.tokyo.jp/kansensyo/index.html)
感染症の拡大を理由とする従業員の休業等にあたり、国の雇用調整助成金の特例措置等を利用する中小企業等を対象に、社会保険労務士派遣による相談助言を行います（１社５回まで。無料）。

[新型コロナウイルス感染症対策雇用環境整備促進事業](https://www.hataraku.metro.tokyo.jp/kansensyo/index.html)
感染症の拡大を理由として、国の雇用調整助成金等を活用し、非常時における勤務体制づくりなど職場環境整備に取り組む都内中小企業に奨励金を支給します（１事業所10万円）。

[テレワーク導入モデル体験事業](https://www.hataraku.metro.tokyo.jp/kansensyo/index.html)
テレワーク導入を検討している中堅・中小企業等を対象に、テレワークを体験できる端末やツールを無償貸与することにより、テレワークのメリット・効果を体感できる機会を提供します。

事業継続緊急対策（テレワーク）助成金
（※変更なし）

[テレワークオンラインセミナー開催](https://tokyo-telework.jp/)
経済団体と連携したテレワーク導入のきっかけづくりのためのオンラインセミナーを開催します。

[中小企業者等特別相談窓口](http://www.sangyo-rodo.metro.tokyo.jp/attention/2020/0305_13201.html)　（⇒※リンク先の変更をお願いします）
資金繰りに関する相談、経営に関する相談

[フリーランスを含む個人事業主特別相談窓口](http://www.sangyo-rodo.metro.tokyo.jp/attention/2020/0305_13201.html)
資金繰りに関する相談、経営に関する相談（契約におけるトラブル等）

[緊急労働相談ダイヤル](https://www.hataraku.metro.tokyo.lg.jp/sodan/sodan/index.html)　（⇒※リンク先の変更をお願いします）
新型コロナウイルスに関する休暇や休業の取り扱い、職場のハラスメントなどについての相談

新しいワークスタイルや企業活動の東京モデル「スムーズビズ」
（変更なし）

**Comment by nard-tech** [comment]
@NaoyaShimizzz
どういった経緯での変更でしょうか？
都の他のページが更新されたから，あるいは都から直接要請があったということでしょうか．
issue の内容を PR にして実際のコードに反映させるまでに都の承認が必要なケース，都の承認が下りずに反映できないもあるようですので (cf. #1516)，経緯を明確にして頂けると安心して実装できます．

**Comment by NaoyaShimizzz** [comment]
都からの公式な要請になります。ご対応お願いします
（以後わかりやすいように公式ラベル付ける予定です）

**Comment by halsk** [comment]
@nard-tech さん、ご指摘感謝です。
取り急ぎ、`OFFICIAL` ラベルを作りました。このラベルの付いたものは公式に承認が取れており、反映されるものです。

**Comment by macropygia** [comment]
@halsk 文言の追加を伴う更新の場合、i18n対応の準備が整ってからの着手になるのでしょうか。それとも一旦追加部分を日本語だけ反映してからi18n対応を行うのでしょうか。

**Comment by halsk** [comment]
文言の対応について、理想的には以下のように進めたいです

1. `/assets/locale/ja.json` に言語キーを追加、`dev-i18n` ブランチに push しておく
2. vue の実装、修正を行う
3. 並行して、Transifex で翻訳作業を行う
4. 実装できた時点で、Transifex から最新のデータを反映（依頼いただければ Transifex -> dev-i18n にPull Request 出します）
5. 反映させたものを、development ブランチに Pull Request
6. 機能面を Review して、問題なければ development に取り込む
7. 少なくとも、英語が翻訳できていればリリースする
8. 翻訳については、リリース後でも随時更新

**Comment by halsk** [comment]
外部リンク先は、明示的に指定がなければ日本語のままで行きましょう。

**Comment by macropygia** [comment]
@halsk 了解です。/workerは現在 #1642 が進行中のため、 `TextCard` のまま進めるか `StaticCard` でやるかを決めていただいた方がよさそうです。

**Comment by macropygia** [comment]
@NaoyaShimizzz 羅列的になってしまうことを防ぐため、今後も内容が増えるようであれば分類とTOCの設置を提案した方がいいかも知れません（下記参照）。特にSP版は今回の追加の時点でかなり長くなります。

---

# 企業の皆様・はたらく皆様へ

- 融資・助成金 （※対応する項目へのアンカーリンク）
- 専門家の派遣
- 相談窓口
- その他

##  融資・助成金

### 新型コロナウイルス感染症に対応した制度融資

テキスト～

### 中小企業従業員融資

テキスト～

...

## 専門家の派遣

### 新型コロナウイルスによる経営課題に関する専門家派遣

テキスト～

### 新型コロナウイルス感染症に係る休業等支援事業（専門家派遣）

テキスト～

...

**Comment by NaoyaShimizzz** [comment]
ありがとうございます。ご意見を参考に今後構成は検討いたします。
本日の依頼内容については、そのまま反映をお願いいたします。

**Comment by kaizumaki** [comment]
> @halsk 了解です。/workerは現在 #1642 が進行中のため、 `TextCard` のまま進めるか `StaticCard` でやるかを決めていただいた方がよさそうです。

#1642 の反映後、ということにさせてもらってもいいでしょうか。

**Comment by kaizumaki** [comment]
@macropygia #1642 が `development` に反映されました。こちらのissueの作業をお願いしてもいいでしょうか？

**Comment by macropygia** [comment]
@MaySoMusician @halsk 日本語言語ファイルの編集について確認事項をお送りします。

- 新規追加キーの挿入位置はどこか
    - 全てのキーの末尾に追加
    - worker用キーの末尾に追加
    - workerページ内の並び順に合わせて挿入（この場合次項の「使われなくなるキー」はどうするか）
- 置き換えの処理方法
    - 使われなくなる置き換え前のキーはそのままにしておき、置き換え後のキーを前項のルールに従って新規追加でよいか

**Comment by MaySoMusician** [comment]
新規追加キーの追加場所は特に指定はありません
（同じキーが複数箇所で使われる場合もあるので「ファイルごと」という概念があまりない）

置き換えについてですが、他のファイルも含めソースコード上から全く使用されなくなる場合は、古い翻訳キーを削除してください

**Comment by macropygia** [comment]
@MaySoMusician 今回の作業としては以下で間違いないでしょうか。

- 新規追加分と置換追加分のキーと値を **日本語の言語ファイルのみ** に追加する（位置指定なし）
- 置換によりworker上で使用されなくなるキーが他のページ・コンポーネントに使われていないことを確認して **全ての言語ファイルから** 削除する

また、削除したキーの一覧は必要でしょうか。

**Comment by MaySoMusician** [comment]
> * 新規追加分と置換追加分のキーと値を **日本語の言語ファイルのみ** に追加する（位置指定なし）

こちらはその方針で問題ありません

> * 置換によりworker上で使用されなくなるキーが他のページ・コンポーネントに使われていないことを確認して **全ての言語ファイルから** 削除する

日本語の言語ファイルのみでお願いいたします
他の言語ファイルを編集しますとTransifex側からの反映PRでコンフリクトが起きる可能性があります。
他の言語ファイルについては適宜Transifexが自動的に修正してくれます。

> また、削除したキーの一覧は必要でしょうか。

こちらは特に必須ではありません
