### ISSUE TITLE
各カードに、リンク設置

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1686]
各カードに、外部サイトもしくはサイト内ページへのリンクを設置できるよう、ご対応お願いします。

リンクURL：カードごとに異なる。ない場合もあり
リンクテキスト：カードごとに異なる。ない場合もあり。（文字数制限したほうがよいですよね）
位置：全カード共通。シェアボタンの上を想定。（デザイン的により収まりのよいところがあれば）

現時点で、具体的には「都営地下鉄の利用者数の推移」に外部サイトへのリンクをつける検討をしています。

**Comment by shgtkshruch** [comment]
今 #1318 で新しいグラフを実装しているのですが、その中でグラフデータの出典のリンクを設置しようとしています。
まだ仮の実装ですが、グラフの下にリンクを表示しています。
このような表記を追加するイメージでしょうか？

![スクリーンショット 2020-03-18 0 50 58](https://user-images.githubusercontent.com/5207601/76874514-a2062300-68b2-11ea-8d73-f151c067571f.png)

**Comment by NaoyaShimizzz** [comment]
すいません、遅くなりました。
リンク自体はそのようなイメージです。
オープンデータがある場合のレイアウトが気になりますが、上下に重なりますか？

**Comment by shgtkshruch** [comment]
オープンデータとは別のリンクを置くことになると思うので、
今のデザインですとカードによってはリンクが上下に重なってが配置されることになりそうです。

![スクリーンショット 2020-03-21 14 02 44](https://user-images.githubusercontent.com/5207601/77219815-a7968e00-6b7c-11ea-8799-328ff92496ae.png)
