### ISSUE TITLE
検査実施状況チャート、検査実績人数グラフの追加と、検査陽性者の状況の一部修正など

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#1692]
## 改善詳細 / Details of Improvement
これまで検査実績人数の総数だけの表示でしたが、検査実績人数のデータが日別で取得できるようになりました。
そこで提供情報の拡充を図るため、以下の変更をお願いします。

1)「検査陽性者の状況」の一部変更
2)「検査実施状況」の追加 
3)「検査実績人数」グラフの追加
4) 「検査実施数 」 グラフのタイトル・注釈変更
5) 画面上部のレイアウト修正

## スクリーンショット / Screenshot
**1)「検査実績の状況」の一部変更**
左側にある検査実施人数を削除します（別の表に移動します）。
![pic1](https://user-images.githubusercontent.com/54087276/76835503-9266ea00-6872-11ea-9058-8d1babf82c71.png)
注意書き：以下に変更します。
（注）チャーター機帰国者、クルーズ船乗客等は含まれていない 

**2)「検査実施状況」の追加** 
日別の検査実績人数が取得出来るようになったため、検査実施人数・検査実施検体数などを表示する「検査実施状況」を追加します。
![pic2](https://user-images.githubusercontent.com/54087276/76836002-69932480-6873-11ea-89f6-495697ff86b5.png)
各データソースは以下のようになります。
a) 「検査実績人数」 → 検査実施日別状況-人数.xlsx の 「検査実施人数」の総計
b)  検査実績件数 合計 → 検査実施日別状況.xlsx の 「検査検体数」の総計
c)  検査実績件数―都内発生 → 検査実施日別状況.xlsx の（小計①）の総計
d) 検査実績件数―その他 →  検査実施日別状況.xlsx の（小計②） の総計
e) 最終更新日時 → Datalist.xlsx の 検査実施日別状況-人数 の最終更新日時

注意書き：以下の注意書きを加えてください。
（注）医療機関が保険適用で行った検査は含まれていない
（注）検査実施人数には、チャーター機帰国者、クルーズ船乗客等は含まれていない 
（注）速報値として公開するものであり、後日確定データとして修正される場合あり

**3) 「検査実績人数」グラフの追加**
検査実施日別状況-人数.xlsx の 「検査実施人数」をグラフ化してください。
単純な棒グラフ（陽性患者数 のような）で構いません。

注意書き：以下の注意書きを加えてください。
（注）医療機関が保険適用で行った検査は含まれていない
（注）チャーター機帰国者、クルーズ船乗客等は含まれていない 
（注）速報値として公開するものであり、後日確定データとして修正される場合あり

**4) 「検査実施数 」 グラフのタイトル・注釈変更**
既存の検査実数グラフのタイトル・注釈を以下のように変更してください。
タイトル：検査実施件数
注釈：
（注）医療機関が保険適用で行った検査は含まれていない
（注）同一の対象者について複数の検体を検査する場合あり 
（注）速報値として公開するものであり、後日確定データとして修正される場合あり

**5) 画面上部のレイアウト修正**
チャート・グラフが2つ追加することにより、上部の並びを以下のように変更をお願いします。
「検査陽性者の状況」   「検査実施状況」（新規追加）
「陽性患者の属性」　　「陽性患者数」
「検査実施人数」(新規追加) 「検査実施件数」

※なお、大規模な変更になり時間がかかることは原局側も理解しております。

**Comment by macropygia** [comment]
@mtenjin 
現在「検査陽性者の状況」に使われているチャートのデザインは、画面サイズによっては文字サイズが極端に小さくなることがあり、また英語とやさしいにほんごでは #1699 のように大量の改行が発生するという問題があります。（6列になってもほとんど改善されません）
改修が入るこのタイミングで #1520 等の対策を検討していただくことは可能でしょうか。

なお、「検査実施状況」のチャートも翻訳後の文字数によっては似たような状態になる可能性があります。

**Comment by mtenjin** [comment]
こちらのチャートの構成は報道資料にも使われていることもあり、見た目の変更には庁内側の承認を取る時間が必要になってしまいます。
まずはデータを見える形で出したいと思いますので、現状の形式でお願いします。

**Comment by macropygia** [comment]
@mtenjin  承知しました。

---

「検査陽性者の状況(`ConfirmedCasesTable`)」「検査実施状況(`TestedCasesTable`とか？)」のコーディングは一旦ローカルで進めておきます。

**Comment by mtenjin** [comment]
一点だけ、チャート・グラフ内の文字について変更させてください。

「累積」 → 「累計」

でお願いします。

**Comment by macropygia** [comment]
@mtenjin 日本語のチャートの表記はこちらで間違いないでしょうか。

![image](https://user-images.githubusercontent.com/3162324/76933476-893c5280-6930-11ea-95ed-5382a6068370.png)

---

上記スクショの通りマークアップ・スタイルの修正が完了しました。
`ConfirmedCasesTable` コンポーネントのtemplate, styleブロックの編集と、同コンポーネントを複製して調整した `TestedCasesTable` コンポーネントの追加（scriptブロックは空）を行いました。
必要であればPRしますので、PR先のブランチをご指示ください。

なお、ボーダーと文字の色が若干濃いのは、アクセシビリティ対応によるコントラスト調整でサイト共通カラーパレットの `$green-1` が変更になったためです。

**Comment by mtenjin** [comment]
作成ありがとうございます。
原局にも確認し、基本OKです。
文字だけ、二か所訂正させてください。

検査実績人数 → 検査実施人数
検査実績件数（累計） → 検査実施件数（累計）

あとはOKです！よろしくお願いします。

**Comment by kaizumaki** [comment]
@macropygia 表の作成、ありがとうございます。

> 3) 「検査実績人数」グラフの追加
> 4) 「検査実施数 」 グラフのタイトル・注釈変更
> 5) 画面上部のレイアウト修正

これらはそれぞれ別issueを立てたいと思います。よろしいでしょうか？ @mtenjin 
そして、これらはすべて合わせてのリリースということですかね？であればブランチ切ります。

**Comment by mtenjin** [comment]
はい、問題ありません。
また、既存のチャートと新規追加する検査実施のチャートが同時リリースである以外は、順次のリリースで構いません。
よろしくお願いします。

**Comment by kaizumaki** [comment]
では、 @macropygia さんが作業されているチャートは即時リリースでいきましょう。
@macropygia ブランチは `development` でお願いします。サイトトップにチャートを配置の上、PRください！
```
5) 画面上部のレイアウト修正
チャート・グラフが2つ追加することにより、上部の並びを以下のように変更をお願いします。
「検査陽性者の状況」 「検査実施状況」（新規追加）
「陽性患者の属性」　　「陽性患者数」
「検査実施人数」(新規追加) 「検査実施件数」
```

**Comment by kaizumaki** [comment]
@mikkame 
```
2)「検査実施状況」の追加
```
こちらのdataの準備をお願いしてもよろしいでしょうか？

**Comment by macropygia** [comment]
i18nリマインダー。
追加になる「検査実施状況」テーブルの「その他」は、既に存在している「その他: Other information」とは別に「その他: The others」が必要になりそう。

**Comment by mikkame** [comment]
データ準備中です
