### ISSUE TITLE
README_TH.md - TH translation for 'Branch Rules' section

### ISSUE THREAD

**Issue by nat236919** [tokyo-metropolitan-gov/covid19#1694]
## 改善詳細 / Details of Improvement
- Translate English to README_TH in 'Branch Rules' section

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/9074112/76849735-f2fd2380-6880-11ea-9652-999b87dec3e3.png)

## 期待する見せ方・挙動 / Expected behavior
- New translation in README_TH.md, it affects GitHub page

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
I close this issue as the related PR has been merged.
