### ISSUE TITLE
Add Thai (th) to language selector 

### ISSUE THREAD

**Issue by bact** [tokyo-metropolitan-gov/covid19#1696]
## 改善詳細 / Details of Improvement
- Add Thai language option to language selector drop-down in UI

## スクリーンショット / Screenshot
Current language selector drop-down:
<img width="246" alt="Screenshot 2020-03-18 at 09 05 03" src="https://user-images.githubusercontent.com/128572/76943805-dc45e380-68f7-11ea-90d4-e49df1a2582d.png">
<img width="245" alt="Screenshot 2020-03-18 at 09 05 11" src="https://user-images.githubusercontent.com/128572/76943812-de0fa700-68f7-11ea-9e40-0f6eb1cfdcbd.png">

## 期待する見せ方・挙動 / Expected behavior
- A Thai language option, labeled "ภาษาไทย", is available for user to choose in the language selector
<img width="245" alt="Screenshot 2020-03-18 at 09 05 11" src="https://user-images.githubusercontent.com/128572/76944876-a86bbd80-68f9-11ea-8b13-cfd3a63b48de.png">

**Comment by kaizumaki** [comment]
@bact Thank you for your suggestions. There is an answer from the official. I will write it in Japanese below.

ご提案ありがとうございます。こちらのissueの内容について東京都に確認いたしました。東京都の公式サイトでは、５言語（日本語・英語・簡体字・繁体字・韓国語）のみ提供することになっています。その他の言語については品質を担保できないので、提供していないのが現状です。ですので、こちらのissueの採用は難しいです。

**Comment by kaizumaki** [comment]
I've got an answer from the owner, so I would like to close this issue.

**Comment by bact** [comment]
Thank you.
