### ISSUE TITLE
提案: 検査陽性者の状況: 前日からの増減を追加

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1703]
## 改善詳細 / Details of Improvement
- 検査陽性者の状況に前日からの増減を追加
  - 北海道知事のツイートがよさそうと感じた
  - https://twitter.com/suzukinaomichi/status/1239722707907825664

## スクリーンショット / Screenshot
https://twitter.com/suzukinaomichi/status/1239722707907825664 より
![](https://pbs.twimg.com/media/ETRhOPxU8AA65NX?format=jpg&name=large)

**Comment by stihahi** [comment]
どこかしらに前日までのデータを保存していく必要があるかと思います。
日々のデータ更新は #948 にあるように、Excelデータをもとにdata.jsonを生成するスクリプトがやっているようです。
このデータ生成スクリプトに前日比を計算してjsonファイルに書き込むロジックを作りこむのが自然な実装かと思うのですが、どうでしょうか？

**Comment by ocean3fish** [comment]
@amotarao @stihahi ご提案ありがとうございます！
以下のissueが公式依頼として立っているため、そちらの対応完了後の検討とさせて頂けるでしょうか。
https://github.com/tokyo-metropolitan-gov/covid19/issues/1692

**Comment by kaizumaki** [comment]
@amotarao ご提案ありがとうございます。こちらのissueについて都に確認いたしました。検査陽性者の状況の数値は、日によってバラツキがあります。前日からの増減を算出した数値を示すことは、誤解や混乱を生む可能性があると思われますので、こちらの提案を採用するのは難しいです。ご理解いただきますようお願いいたします。
