### ISSUE TITLE
nuxt-i18n.config.tsに型をつける

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#1705]
## 改善詳細 / Details of Improvement
- せっかくTypeScriptで書いているので、`nuxt-i18n.config.ts`に型をつける
  - ただし`nuxt-i18n`の`6.6.0`の型は不十分なので、`6.6.1`にアップデートする[^1]

## 期待する見せ方・挙動 / Expected behavior
- `nuxt-i18n.config.ts`に型がついている

[^1]:https://github.com/nuxt-community/nuxt-i18n/releases/tag/v6.6.1

**Comment by munierujp** [comment]
やります！

**Comment by mcdmaster** [comment]
#2765 のご確認をお願いいたします
