### ISSUE TITLE
提案: 言語別のディレクトリにMarkdownファイルを移動する

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#1717]
## 改善詳細 / Details of Improvement
1. 以下のファイルを`docs/${言語コード}`ディレクトリ以下に移動する。言語コードは小文字でディレクトリのみに付け、ファイルからは取り除く。
   - `README_*.md`: 英語なら、`docs/en/README.md`
   - `.github/CODE_OF_CONDUCT_*.md`: 英語なら、`docs/en/CODE_OF_CONDUCT.md`
   - `.github/CONTRIBUTING_*.md`: 英語なら、`docs/en/CONTRIBUTING.md`
1. 開発環境構築を`README.md`から別のファイルに分け、`README.md`を見やすくする

## 期待する見せ方・挙動 / Expected behavior
対応言語が増えると、プロジェクトのルートディレクトリや`.github`ディレクトリに数多くファイルが増えていくので、該当する言語のファイルを見つけにくくなる。

本変更で、該当の言語のファイルを見つけやすくなる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
良いですね！言語コードは、Transifex に合わせていただけると助かります。
また、ページ間のリンク関係が壊れると思うので、そちらも修正する必要があります。

**Comment by MaySoMusician** [comment]
README 日本語版のみはルートディレクトリに置いておく必要があると思います（GitHubで最初に表示させるため）

**Comment by masanori1102** [comment]
こちら、今晩、やりますね
