### ISSUE TITLE
Use :items data for TimeStackedBarChart.vue

### ISSUE THREAD

**Issue by PichuChen** [tokyo-metropolitan-gov/covid19#1718]
## 改善詳細 / Details of Improvement
- When cursor hover on Bar of Time Stack Bar Chart, it will show "都內" or "その他" now
- But this two line is fixed in TimeStackedBarChart.vue
- So you can't modify it from attribution of time-stacked-bar-chart
- It will make TimeStackedBarChart.vue more useable

## スクリーンショット / Screenshot (Before)
![螢幕快照 0002-03-18 02 05 55](https://user-images.githubusercontent.com/600238/76887352-1b0a7800-68bd-11ea-9fd8-a5d5765de803.png)
![螢幕快照 0002-03-18 02 10 27](https://user-images.githubusercontent.com/600238/76887808-c61b3180-68bd-11ea-8c0f-16680940610b.png)

![螢幕快照 0002-03-18 02 10 39](https://user-images.githubusercontent.com/600238/76887805-c3204100-68bd-11ea-8d53-c4eb9b9e3079.png)
![螢幕快照 0002-03-18 02 10 33](https://user-images.githubusercontent.com/600238/76887807-c4ea0480-68bd-11ea-9d69-7de6d2e5b590.png)

## 期待する見せ方・挙動 / Expected behavior (After)
![螢幕快照 0002-03-18 02 01 51](https://user-images.githubusercontent.com/600238/76887367-23fb4980-68bd-11ea-918f-47a431801e54.png)

**Comment by mmfiber** [comment]
@PichuChen 
Can I try this issue?

**Comment by mmfiber** [comment]
@PichuChen 
I will create draft pull request to notify my progress today. Please give me more time.

**Comment by mmfiber** [comment]
@PichuChen 
Created draft pull request. If it is OK, please push "Ready for review"!
