### ISSUE TITLE
[協力依頼] 翻訳シートからTransifex への転記

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1724]
## 改善詳細 / Details of Improvement
- [翻訳シート](https://docs.google.com/spreadsheets/d/1avT6QGInyQseYjoc_TxL8RPZfutyvrv4BtJkXfk1Nko/edit#gid=766885756) に入っているが、Transifex 上が古いままです。
現在、「やさしい日本語」が残っています。やさしい日本語の内容は、都側のレビュー済みなので、Transifex 上にあるものは現行シートの内容で上書いてください。

その他、シートになくて [Transifex](https://www.transifex.com/stopcovid19-tokyo/stopcovid19tokyo/assets-locales-ja-json--dev-i18n/) にある言語/ワードは、ご自身で翻訳文を記入いただいて結構です。

Transifex への参加のしかたは[こちら](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/TRANSLATION.md)

より詳しい記事をかいていただきました！  
https://qiita.com/iten/items/1274f3b85e11261f3b5c

完全に人海戦術なので、人手が多い方が助かります。転記するだけなので、言語の知識は必要ありません。

**Comment by halsk** [comment]
すみません。最初に貼った翻訳シートへのリンクが、古いものでした。2020/03/18 8:10 に正しいURLに更新しました。

**Comment by showyou** [comment]
ベトナム語転記してます。
幾つか気づいた点を書いていきます。

**Comment by showyou** [comment]
{date}の累計
上記と全く同じセルが見つからないです。
{date}の全体累計か、それとも累計か、どちらでしょう？

**Comment by showyou** [comment]
詳細を見る（東京都福祉保健局）のベトナム語訳
ベトナム語側に()が抜けていますが、合っておりますでしょうか？(警告出てます)

**Comment by showyou** [comment]
公表日
シートに無いです

**Comment by showyou** [comment]
都内
Tokyoになってますが、ベトナム語にはthe metropolitan of ~に相当するものは無いのでしょうか？
(他の言語では相当する文が入っているので気になりました)

**Comment by mira-tech** [comment]
スペイン語今から転記します！

**Comment by halsk** [comment]
早速ありがとうございます。Transifex 上に見つからないもの、またはシート側に見つからないものは無視してもらって大丈夫です。

**Comment by halsk** [comment]
各言語の隣に、移行済かどうかのチェックを付けたので、終わったら yes にしていただけると助かります。

**Comment by showyou** [comment]
> 38 退院*

ロックかかってて更新できないです

> 58 感染症の拡大を理由とする従業員の休業等にあたり、国の雇用調整助成金の特例措置等を利用する中小企業等を対象に、社会保険労務士派遣による相談助言を行います（1社5回まで。無料）。

スプレッドシートは4回となってますので、ベトナム語の4も5に変えてます。ご注意ください。

> 68 資金繰りに関する相談、経営に関する相談

恐らくシートの164行目の（）を取り除いた「Tư vấn liên quan đến dòng tiền và quản trị」が正解だと思うのですが、保留

> 72 新型コロナウイルスに関する休暇や休業の取り扱い、職場のハラスメントなどについての相談

これもシートの方は（東京都）なんたらと入っているので保留

**Comment by mira-tech** [comment]
@showyou 
Transifexの通訳コメントの方に書いた方がいいのでは？

**Comment by halsk** [comment]
基本的な考え方として、Transifex の方が最新です。
Spareadsheet は古い内容が含まれています。
Transifex 側の日本語と Spreadsheet 側の日本語が違っている場合、Transifexが正として扱ってください。
翻訳そのものについての疑問点などは、Transifex へコメントの形で残してください。

**Comment by mira-tech** [comment]
スペイン語転記終わったようです

**Comment by aki-snow** [comment]
ベトナム語、ベトナム側メンバーとともに追加実施します。（転記以外にも進めます）

**Comment by akihanari** [comment]
ベトナム語、現時点で転記されているものは全て、スプレッドシートに移行済みの'Yes'を付けました。

**Comment by sasukeh** [comment]
ベトナム語転記できてなさそうなところを拾って転記しておきました。

**Comment by nyampire** [comment]
Transifexの権限として、[コーディネータとレビュアーというRoleが設定](https://docs.transifex.com/teams/understanding-user-roles)できます。
（現在は多くの言語にて、管理者だけ設定済みの様子。英語は関さんがコーディネータ）

コーディネータは特に現時点で必須ではないと思いますが、レビュアーはもし設定できるとしあわせが増すかも知れません。[レビュー済み](https://docs.transifex.com/translation/reviewing-strings)の語句は、変更が確定され、直接編集ではなく提案だけができるようになります。（確かそのはず。。。）

言語の翻訳が正しく適用されているかをチェックするProofreadingができたほうがよくて、開発環境をローカルで構築して txコマンドとか叩いてTransifexから結果を適用できるとよりしあわせが高いです。

新規Issueとして挙げたほうがよいのかしら？

**Comment by halsk** [comment]
ありがとうございます。レビュアー、是非アサインしたいのですが、誰がレビュアーになるか？が問題です。言語ごとに募集するのが良いのかな。

**Comment by nyampire** [comment]
コーディネータとレビュアーのアサインは言語ごとになります。

その言語が読めてなおかつ自分で環境構築ができて、、、と、単に翻訳者としての貢献度だけでは判断できず、開発能力も少し必要になるので、英語など貢献者の多いところから、後々アサインしてゆく、でもよい気はします。

もし本番環境などで訳語の適用が判定できる場合は、誰か貢献度の高い方をレビューにしてしまう、という考えもあります。（自分で環境構築しなくても、訳語の確認と確定が可能な状態なので、開発能力が特に必要ない）

**Comment by sasukeh** [comment]
やさしい日本語転記されているがyesがついていないところのチェックをします。
ついてでに転記されてなさそうなところがあれば転記します。

**Comment by aki-snow** [comment]
ベトナム語、Transifexに登録されている単語はひとまず転記、翻訳が完了しているかと思います。
* 未翻訳2つは以下でlockされているのでそのままです。
- 38 "退院※"
- 249 "This is a provisional translation. Please be aware that there may be mistranslations."

**Comment by hassaku63** [comment]
シートとTransifexで翻訳が食い違っている場合はTransifexを優先する、とのことですが、
この場合シートの "already in Transifex?" はYesになっているべきでしょうか？

このケースに合致していて、かつ"already in Transifex?" フラグが空欄のままになっているケースが複数あるようなので、念のため確認させてください。

**Comment by halsk** [comment]
ややこしいのですが、「やさしい日本語」については、Spreadsheetの方のテキストを上書きしてください。現行のSpreadsheetは、都側でレビューをした正式版です。

**Comment by halsk** [comment]
翻訳元の日本語の方がTransifexに見つからない場合はNoをつけてください。

**Comment by halsk** [comment]
> ベトナム語、Transifexに登録されている単語はひとまず転記、翻訳が完了しているかと思います。
> 
> * 未翻訳2つは以下でlockされているのでそのままです。
> 
> * 38 "退院※"
> * 249 "This is a provisional translation. Please be aware that there may be mistranslations."

2つのロックを削除しました。

**Comment by MaySoMusician** [comment]
@halsk 249 "This is a provisional translation. Please be aware that there may be mistranslations." は、他の言語でも英語のままですが翻訳可能にしますか？

**Comment by hassaku63** [comment]
> 「やさしい日本語」については、Spreadsheetの方のテキストを上書き

これについては、issueや[qiita](https://qiita.com/iten/items/1274f3b85e11261f3b5c)から読み取れなかったです...。

他にも誤解する人が出そうだと思うので、Issueの最初のコメントに追記で補足していただけないでしょうか？（私が見落としていただけであれば申し訳ないですが）

**Comment by halsk** [comment]
すみません。私の言及漏れですね・・・

**Comment by halsk** [comment]
アップデートしました

**Comment by hassaku63** [comment]
「やさしい日本語」のシートについての質問です。
文章中の一部の語句がTransifex側ではプレースホルダ(?)に置き換わっていると思しき文章を発見しました。

e.g 「やさしい日本語」シートの140行目

シート
> 本サイトで公表しているデータは、東京都オープンデータカタログサイトより誰でも自由にダウンロードが可能です。（データは順次追加予定です）

Transifex
> 本サイトで公表しているデータは、{catalogWebsite}より誰でも自由にダウンロードが可能です。（データは順次追加予定です）

これらは元々同一の文章であろうと思いますが、単純検索では少々見つけにくいパターンかと思います。気づいたものに関しては対応付けしてよしなにできると思いますが、シート側の語句そのままで検索してTransifex側がヒットしなければ問答無用で "Already on Transifex?" = No としてしまった方がよろしいでしょうか？

**Comment by hassaku63** [comment]
上記のコメントですが、これに合致するケースの場合はシートの翻訳文を "提案" として転記し、コメントに対応するシートの行番号を残しておくようにします

**Comment by hassaku63** [comment]
COVID19のサイトを示す用語に表記ゆらぎがあるようです。

一例

- 当 Web サイト
- 当サイト
- 本サイト

Transifexとシートの間でも微妙に食い違いがあるようなので、そのせいで転記チェックから漏れてしまっている文章が存在するかもしれません。詳しくはチェックできていませんが、ひとまずの報告とさｓていただきます。

**Comment by sutefu7** [comment]
sutefu7 と申します。宜しくお願い致します。


Transifex/
  StopCovid19Tokyo/
  Japanese (Hiragana) (ja-Hira) 

のうち、本日（2020/03/19）未翻訳分を翻訳しました。

ただ、翻訳するにあたり、「Transifexのアカウントを作成して東京都 新型コロナウイルス感染症対策サイトの翻訳を手伝う方法（https://qiita.com/iten/items/1274f3b85e11261f3b5c）」 を手順の参考としましたが、covid9_wordstable/SpreadSheet の【やさしい日本語】シートにはない原文ばかりでしたので、既存の翻訳文の書き方に合わせて自己翻訳しています（つまり、東京都様側のレビューを通していない未実施の状態？）。

何かご指示があれば対応させていただきますし、問題であれば自分担当分の全消しも行います（30個くらい翻訳しました）。
よろしくお願いします。

**Comment by aki-snow** [comment]
以下以外は翻訳完了しています。(303レビュー待ち/305中)

- 150 "This is a provisional translation. Please be aware that there may be mistranslations."
- 305 "test"

**Comment by halsk** [comment]
こちら、転記は終了したのでクローズします。皆様ご協力ありがとうございました。
