### ISSUE TITLE
どなたか Transifex の使い方の記事を誰か書いていただけないでしょうか

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1725]
## 改善詳細 / Details of Improvement
- Spreadsheet から Transifex に移行したが、Spreadsheet 時代より翻訳への参加が難しくなった。
- Qiita でも何でも良いので、手順書を書いていただけると嬉しい（このリポジトリ内でも可）
- 英語記事もあると良いと思います。その場合、Qiita じゃないほうが良いかもですね

関連issue #1724

**Comment by resource-sharing** [comment]
とりあえずQiitaで作成してみようと思います。

**Comment by resource-sharing** [comment]
https://qiita.com/iten/items/1274f3b85e11261f3b5c
取り急ぎ作成して投稿しました。
おかしな点などがございましたらご指摘お願いいたします。

**Comment by halsk** [comment]
ありがとうございます！ #1724 からリンク貼りました。
