### ISSUE TITLE
「お問い合わせ先一覧」の追加

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1726]
左カラム ＞ 当サイトについて の下に
「お問い合わせ先一覧」の追加とリンク先となるサイト内ページの作成をお願いします。
掲載内容は以下の資料をご確認ください。
※今後ブラッシュアップ予定ですが、本日時点ではこちらの内容でお願いします。

[お問い合わせ先一覧0318.xlsx](https://github.com/tokyo-metropolitan-gov/covid19/files/4346356/0318.xlsx)

合わせて、「当サイトについて」の
お問い合わせ先（都のHPサイトポリシーについて）は削除でお願いします。

明日19日朝の更新で公開したく、宜しくお願いします。

**Comment by kebhr** [comment]
こちら対応できます。
@NaoyaShimizzz 
確認のために、最初の3件のみExcelシートから起こしてみましたが、このような形で大丈夫でしょうか?
![image](https://user-images.githubusercontent.com/42484226/76919354-f4bff900-690b-11ea-9ab1-d14812bd4b48.png)

**Comment by NaoyaShimizzz** [comment]
早速ご対応ありがとうございます。
Excelの内容と同様に表形式での表示でお願いしたいです。
