### ISSUE TITLE
「企業の皆様・はたらく皆様へ」の自動取り込み

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#1727]
## 改善詳細 / Details of Improvement
新型コロナ感染症対策に関連して、企業向けの助成・融資・各種の支援の新設・増強が行われています。
日々追加変更が発生するため、SharePointサイト上にExcelシートを追加し、自動取り込みを行うことで、追加・変更の迅速化・省力化をおこないます。
庁内側も原局側で直接編集を行うことで、省力化を行います。

## 期待する見せ方・挙動 / Expected behavior
データフォーマットは以下のシートになります。
（3月18日に表示されている内容を想定して各項目を埋めています）
[企業の皆様.xlsx](https://github.com/tokyo-metropolitan-gov/covid19/files/4346434/default.xlsx)

上から順番に、存在するものだけ表示してください。
現在表示している内容を変えるものではありませんので、No,掲載日は表示する必要はありません（管理上の項目）。
項目単位での削除などは行わず、毎回全部リフレッシュすることを想定していますが、
もし自動化などを行う際などに一意となるIDが必要といった場合など、新たに項目の追加が必要な場合はご連絡ください。

**Comment by macropygia** [comment]
#862

**Comment by mikkame** [comment]
はい、#862 を使いまわせそうです。
こちら、バッチ化まではできているのであとは自動化の運用とデプロイ手順のすり合わせが必要です。

**Comment by kaizumaki** [comment]
こちらは運営側のマターとなりますので、issueとしては一旦クローズいたします。
