### ISSUE TITLE
提案: 地図カードの追加

### ISSUE THREAD

**Issue by tichimura** [tokyo-metropolitan-gov/covid19#1735]
## 改善詳細 / Details of Improvement
- 地図カードを追加することで、視覚的に東京を含めた日本の状況を把握できるようにする
- データ入れ替えや、スタイルの変更で、カスタマイズしやすい地図を提供する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1793451/76927495-79b60d00-6922-11ea-9bbf-ede7b347f74c.png)

![covid19-video](https://user-images.githubusercontent.com/1793451/76927886-66f00800-6923-11ea-92b5-2d74419d5f6f.gif)

## 期待する見せ方・挙動 / Expected behavior

- トップページ、あるいはサイトの一部にて、全国状況を簡易的に把握できるようにする
- ズームレベルに応じて表示内容を変更し、各都道府県の状況まで確認できるようにする

## 動作環境・ブラウザ / Environment
- macOS 10.14.6
- Chrome 80.0.3987.132 / Safari Version 13.0.4 (14608.4.9.1.4) / Firefox 70.0.1
*動作確認済み環境です*

**Comment by halsk** [comment]
ご提案ありがとうございます！今後のコンテンツの参考にさせていただきます！
