### ISSUE TITLE
言語選択プルダウンでクリックできない場所がある

### ISSUE THREAD

**Issue by paichi81** [tokyo-metropolitan-gov/covid19#1745]
## 起こっている問題 / The Problem
- サイドメニュー下部の言語選択欄の右寄りがクリックできない
- conponents/LanguageSelectorのselect要素が枠より狭く、展開用ボタンをクリックできない

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4400857/76929835-74f45780-6928-11ea-824f-035291cfafb0.png)
- 赤線部分がクリックできない

## 期待する見せ方・挙動 / Expected Behavior
- 選択枠上・展開用ボタンクリックで、メニューが開いてほしい

## 起こっている問題の再現手段 / Steps to Reproduce
1. 言語欄、EarthIcon～文字部分クリック
2. 〇 期待通りにメニューが開く
3. 言語欄、SelectMenuIcon～文字部分右の余白をクリック
4. × メニューが開かない

## 動作環境・ブラウザ / Environment
- Windows / iOS / Android
- Chrome / Safari

**Comment by amotarao** [comment]
Duplicate of #1643

**Comment by halsk** [comment]
#1653 と同様の内容。解消されているのでクローズします。
