### ISSUE TITLE
主に退院の状態を示す丸の記号について、漢数字のゼロ〇から記号の○に変更

### ISSUE THREAD

**Issue by yhata** [tokyo-metropolitan-gov/covid19#1746]
## 改善詳細 / Details of Improvement
主に退院の状態を示す丸の記号について、漢数字のゼロ〇が使われている。
記号の○に変更したい。

![image](https://user-images.githubusercontent.com/32102/76929893-981f0700-6928-11ea-9b31-eb9465ca1d43.png)

**Comment by kaizumaki** [comment]
今朝のマージ分でこちら #1693 検討されています。

**Comment by halsk** [comment]
こちら、解決されていると思うのでクローズします。問題あればreopen願います。
