### ISSUE TITLE
派生したサイトのレイアウトが崩れている

### ISSUE THREAD

**Issue by nandehu0323** [tokyo-metropolitan-gov/covid19#1752]
## 起こっている問題 / The Problem
- 派生したサイトのレイアウトが崩れている
  https://github.com/tokyo-metropolitan-gov/covid19/blob/development/forkedSites.md

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/19589940/76935478-85123400-6934-11ea-9daa-b87cfa5e8554.png)

## 期待する見せ方・挙動 / Expected Behavior
![image](https://user-images.githubusercontent.com/19589940/76935566-a83ce380-6934-11ea-8644-63e88827f4dd.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. 特になし(ファイルの修正)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by sasukeh** [comment]
着手します。

**Comment by sasukeh** [comment]
すでに @nandehu0323 が着手済みでしたね。失礼しました。
