### ISSUE TITLE
翻訳修正

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1761]
昨日の英訳更新時に、依頼内容に一部内容に不備がありました。
添付の内容について改めて更新をお願い致します。（CSVの区切りがおかしく、無駄な文字等が含まれてました）

[外務部翻訳反映0318追加.xlsx](https://github.com/tokyo-metropolitan-gov/covid19/files/4347943/0318.xlsx)

お手数おかけしますが、宜しくお願い致します。

**Comment by sasukeh** [comment]
#1509 に周知されていますが、Transifex に移行しているのでそちらで翻訳確認→修正ですね。
https://www.transifex.com/stopcovid19-tokyo/stopcovid19tokyo/translate/#en/assets-locales-ja-json--dev-i18n

**Comment by halsk** [comment]
私の方で反映させておきました！
