### ISSUE TITLE
大阪府版を作成しました。

### ISSUE THREAD

**Issue by teppei696** [tokyo-metropolitan-gov/covid19#1766]
## 改善詳細 / Details of Improvement
- 大阪版を作成したので、forkedSites.md に追加させていただきたいと思います。issueを作成しました。このような形で問題ないでしょうか？

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by sasukeh** [comment]
#1483 に従って作業をすれば良いかと思います。
