### ISSUE TITLE
worker内のテキスト「（1社5回まで。無料）」と「（1社あたり4回まで・無料）」の表現統一

### ISSUE THREAD

**Issue by hatsu38** [tokyo-metropolitan-gov/covid19#1773]
## 改善詳細 / Details of Improvement
- /worker ページのテキストに「（1社5回まで。無料）」と「（1社あたり4回まで・無料）」といった表現があります。どちらかに表現を統一することができるときれいかと思います。

- 「（○社あたり○回まで無料）」が適切かと考えています。

## スクリーンショット / Screenshot

<img width="800" alt="スクリーンショット 2020-03-18 21 55 07" src="https://user-images.githubusercontent.com/16137809/76962831-4a73c000-6963-11ea-961a-2e3a032399a7.png">

## 期待する見せ方・挙動 / Expected behavior
- 既存の 「1社5回まで。無料」や「1社あたり4回まで・無料」ではなく、「（○社あたり○回まで無料）」が適切かと考えています。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yuutarou22** [comment]
やります！

**Comment by kaizumaki** [comment]
@hatsu38 ご提案ありがとうございます。たいへんありがたいのですが「企業の皆様・はたらく皆様へ」ページについては、 #3641 #3687 でコンテンツの更新を行っております。こちらのissueについてはクローズさせていただければと思います。
