### ISSUE TITLE
「検査実施人数」グラフの追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1777]
**こちらは #1692 の子issueです。**

#1692 であるように以下の作成をお願いします。

#### 3) 「検査実績人数」グラフの追加（kaizumaki注：「検査実施人数」が正しいです）
検査実施日別状況-人数.xlsx の 「検査実施人数」をグラフ化してください。
単純な棒グラフ（陽性患者数 のような）で構いません。

注意書き：以下の注意書きを加えてください。
（注）医療機関が保険適用で行った検査は含まれていない
（注）チャーター機帰国者、クルーズ船乗客等は含まれていない
（注）速報値として公開するものであり、後日確定データとして修正される場合あり

**レイアウトは以下にようになります。**
「検査陽性者の状況」 「検査実施状況」（新規追加）
「陽性患者の属性」　　「陽性患者数」
**「検査実施人数」(新規追加)** 「検査実施件数」

なにか疑問点あればこのissueにコメントください！

**追記）**
@mikkame 
> 検査実施日別状況-人数.xlsx の 「検査実施人数」をグラフ化してください。

こちらのdataの準備をお願いしてもよろしいでしょうか？

**Comment by shgtkshruch** [comment]
アサインされている方がいらっしゃらなければ、こちらのグラフを実装させていただきたいです！

**Comment by kaizumaki** [comment]
@shgtkshruch ありがとうございます！よろしくお願いします！dataはもうしばらくお待ちください。

**Comment by mikkame** [comment]
お待たせしました
データを作成しました。
data.jsonにinspection_personsを追加しました

**Comment by shgtkshruch** [comment]
ありがとうございます！
実装すすめていきます。
