### ISSUE TITLE
「検査実施数 」 グラフのタイトル・注釈変更

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1779]
こちらは #1692 の子issueです。

#1692 であるように以下の修正をお願いします。

#### 4) 「検査実施数 」 グラフのタイトル・注釈変更
既存の検査実数グラフのタイトル・注釈を以下のように変更してください。
タイトル：検査実施件数
注釈：
（注）医療機関が保険適用で行った検査は含まれていない
（注）同一の対象者について複数の検体を検査する場合あり
（注）速報値として公開するものであり、後日確定データとして修正される場合あり

なにか疑問点あればこのissueにコメントください！

**Comment by nbtomo** [comment]
こちら対応いたします！
@kaizumaki 
各国語への翻訳後の文言はどこかに情報ありますか。
なければ一旦以下のように実装したいと思いますが、よろしいでしょうか。

タイトル：検査実施件数　→ これまでと同じ翻訳を使用
注釈：
（注）医療機関が保険適用で行った検査は含まれていない　→一旦日本語で表示するよう対応
（注）同一の対象者について複数の検体を検査する場合あり　→ これまでと同じ翻訳を使用
（注）速報値として公開するものであり、後日確定データとして修正される場合あり　→一旦日本語で表示するよう対応

**Comment by kaizumaki** [comment]
@nbtomo ありがとうございます！
翻訳はまだないはずなので、 @nbtomo さんのおっしゃるとおり、まずは日本語で表示できるように実装してください。

@MaySoMusician こちらの翻訳の段取りもお願いします！
