### ISSUE TITLE
フォーカス時のスタイルが統一されていない

### ISSUE THREAD

**Issue by oti** [tokyo-metropolitan-gov/covid19#1785]
## 改善詳細 / Details of Improvement
- フォーカス時のスタイルを統一する

## スクリーンショット / Screenshot

| Cap1 | Cap2 | Cap3 |
| :--- | :--- | :--- |
| ![スクリーンショット 2020-03-18 22 31 56](https://user-images.githubusercontent.com/710216/76966652-a6414780-6969-11ea-8fe4-644406517978.png) | ![スクリーンショット 2020-03-18 22 32 01](https://user-images.githubusercontent.com/710216/76966690-b527fa00-6969-11ea-8be6-1eba58bada97.png) | ![スクリーンショット 2020-03-18 22 32 08](https://user-images.githubusercontent.com/710216/76966726-c07b2580-6969-11ea-9c85-b7cfb427b118.png) |
| メニュー内のフォーカスは `border: 1p dotted $gray-3` でした。 | コンテンツエリアのほとんどはブラウザデフォルトのままです。 | トップのグラフ切り替えボタンはテーマカラーに沿った `outline: solid $green-1 2px` になっています。 |

## 期待する見せ方・挙動 / Expected behavior
- フォーカススタイルが統一される

理想としては何も指定せずブラウザデフォルトにしておくのが良いのですが、角丸にそわなかったり親の `overflow: hidden` で見切れてしまったりするので、サイトでレギュレーションを決めて統一した方が良いです。デザインはできるだけ認知コストが低い、「よくあるやつ」であればユーザーが理解しやすくて良いです。

サイドのメニューで指定している `border: 1p dotted $gray-3` か、下記のようなスタイルが良いと思われます。

```
// Scss
:focus {
  outline: none;
  box-shadow: 0 0 0 3px rgba($green-1, 0.75)
}
```

線の色をグリーンで対応した場合のキャプチャです。

| Cap1 | Cap2 | Cap3 |
| :--- | :--- | :--- |
| ![スクリーンショット 2020-03-18 22 56 36](https://user-images.githubusercontent.com/710216/76968125-ba864400-696b-11ea-8c60-3817f82af40e.png) | ![スクリーンショット 2020-03-18 22 56 14](https://user-images.githubusercontent.com/710216/76968178-ce31aa80-696b-11ea-83c7-749945e398f8.png) | ![スクリーンショット 2020-03-18 22 56 08](https://user-images.githubusercontent.com/710216/76968182-d0940480-696b-11ea-92e4-b889631274e3.png) |

サンプルではわかりやすさのためにグリーンにしましたが、色よりも統一されていることの方が大事ですので、`border: 1p dotted $gray-3` にするでも良いと思います。

ご検討いただければ幸いです。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shunito** [comment]
こちら対応個所を調査しました。
Cap2のパターンの指定は、variables.scssの ```$link: #006CA8;```になっています。

画面のチャートや強調個所の多くがグリーンなので、差異をつけるとするとこのlink色に統一の方向でもよいのではないかと考えます。

focusの指定個所は16か所ほど、洗い出し済なので誰も着手していないようであれば私のほうで対応しますので、アサインお願いします。

**Comment by oti** [comment]
調査ありがとうございます。Cap2は失礼しました:bow:

色についてはデザイナーさんの意見もいただきたいです。 @forestgtree いかがでしょうか？

**Comment by shunito** [comment]
あー、タイミングの問題でデザイナさんの意見聞く前にプルリクってしまいました。
すいません。気にせずご意見いただければ、再修正しますので。

**Comment by forestgtree** [comment]
@shunito @oti 
スタイル統一ありがとうございます✨
確認を投げていただき、ありがとうございます！

>画面のチャートや強調個所の多くがグリーン、差異をつけるとするとこのlink色に統一の方向でもよいのではないかと考えます。

仰られている通り、このサイトはmainエリアの情報が最も重要です！

以前の[PR](https://github.com/tokyo-metropolitan-gov/covid19/pull/1522) も大変好評でしたので
focusは `border: 1p dotted $gray-3` で
しっかり役割を果たす状態に統一していただけると助かります！

**Comment by shunito** [comment]
@forestgtree リンク色の```$link``` の: #006CA8;ではなくて、```$gray-3``` のほうで統一ということですね。
一応、念のためプルリクを送った```$link``` 統一のほうも確認いただけると！

**Comment by shunito** [comment]
グレー側に統一してコミットしました。
