### ISSUE TITLE
「やさしい日本語」の言語コードを "ja-simple" に変更

### ISSUE THREAD

**Issue by likibp** [tokyo-metropolitan-gov/covid19#1801]
## 起こっている問題 / The Problem

- 現状、「やさしい日本語」の言語コードは、コード内では "ja-basic" , transifexでは "ja-Hira" を使用しています。
- BCP 47で定義されているIETF言語タグ[[1]](https://ja.wikipedia.org/wiki/IETF%E8%A8%80%E8%AA%9E%E3%82%BF%E3%82%B0)[[2]](https://www.w3.org/International/articles/language-tags/index.ja)において、各下位タグは、 Language Subtag Registry[[3]](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) に登録・管理しています。
- Language Subtag Registryには 「やさしい日本語」やBasic Englishなどのような簡略化された言語を表す異形サブタグ "simple" が登録されています。[[4]](https://www.iana.org/assignments/lang-subtags-templates/simple.txt)
- "basic"というサブタグはLanguage Subtag Registryに登録されておらず、"Hira" はその名のとおり平仮名のみの表記を示すサブタグであるため不適切です。
- よって、「やさしい日本語」の言語コードを "ja-simple" に変更することを提案します。

## 期待する見せ方・挙動 / Expected Behavior

- コード内およびtransifexの「やさしい日本語」の言語コードを "ja-simple" へ変更
- 「やさしい日本語」版のアドレスを https://stopcovid19.metro.tokyo.lg.jp/ja-basic/* から https://stopcovid19.metro.tokyo.lg.jp/ja-simple/* に変更し、旧アドレスから新アドレスへリダイレクトさせる。

**Comment by MaySoMusician** [comment]
少なくともTransifexで使用できる言語は https://www.transifex.com/explore/languages/ に記載されている517個で、日本語関連としては `ja`・`ja-Hira`・`ja_JP`の3種類がサポートされています。

そのため、Transifexの設定としてはやむを得ず「やさしい日本語」に対し `ja-Hira` を割り当てています。

Transifex自体、EnglishとChineseで非常に多くの言語タグを（`en_JP`のようなものまで）用意してはいるものの、`en-simple`・`en-basiceng` などは現在用意されていません。また[FAQ](https://docs.transifex.com/faq/managing-projects#how-do-i-add-a-new-language)によれば、言語サポート追加時にはBCP 47に準拠すると言及しつつも

> The multiple language locales are based on region subtags.

とあることから `ja-simple` についても追加される可能性はあまり高くないのではないかと個人的には思います。

---

一方で、サイトの言語設定およびURLにおいて `ja-simple` を使用するのは技術的には可能ですので、検討の余地は十分にあるのではないかと思います。

**Comment by mcdmaster** [comment]
スミマセン、横入りさせてください。本件、物凄く大雑把に分けると２つのイシューに分割できると思っています：
- Transifex の、ja-simple という識別子への対応制約とどう付き合うか
- 本プロジェクト側で、原則「やさしい日本語」のロケール上の記載（パス名等を含む）は ja-simple で平仄を取るか

２番目は、おおよそ解決しつつある、プロジェクトはほぼ同じページ上にあるとの私の認識です。
※違っていたら、ご指摘をお願いいたします。

順序が前後しますけど、１番目は、Transifex の使用にあたってロケール識別子を都度読み替えるというアクションがたとえばミスや漏れの原因になるとしたら、解決が求められます。
逆に、そうした問題が頻出しない、リスクもそんなに大きくないということなら、Transifex 専用の識別子として残しておくのもアリかと。

私は Transifex にあえて寄せなくてもいい、で、本プロジェクトのスタンダードとして ja-simple を使うのでオーケーと思っています。
皆さんはいかがでしょうか？

**Comment by kaizumaki** [comment]
@likibp ご提案ありがとうございます。こちらのissueの内容について東京都に確認いたしました。すでに定着している/ja-basic/*のurlは、特段問題がなければ現状維持でいきたいとのことでした。ですので、こちらのissueは一旦クローズさせていただければと思います。
もしクリティカルな問題が発生するようであれば、再考の余地はあると思います。

**Comment by kaizumaki** [comment]
東京都の回答がありましたので、こちらのissueはクローズします。
