### ISSUE TITLE
FORKED_SITES.md の整理

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#1802]
## 改善詳細 / Details of Improvement
- FORKED_SITES.md に記載されていないサイトがないかチェックし，あれば追加したい

### 現在把握している，記載されていないサイト

- 福岡市 https://stopcovid19.codeforfukuoka.org/about (by Code for Fukuoka)
    - [GitHub Code-for-Fukuoka/covid19](https://github.com/Code-for-Fukuoka/covid19)
- 千葉市 https://stopcovid19.code4chiba.org/ (by Code for Chiba)
    - [GitHub codeforchiba/covid19](https://github.com/codeforchiba/covid19)
- 長野県 https://stop-covid19-nagano.netlify.com/ （by 有志）
    - [GitHub hisayan/covid19](https://github.com/hisayan/covid19)

**Comment by nard-tech** [comment]
並び順は [全国地方公共団体コード](https://www.soumu.go.jp/denshijiti/code.html) 順でよいか？

**Comment by stihahi** [comment]
やらせて下さい！

**Comment by nard-tech** [comment]
@stihahi ぜひぜひ！お願いします！

こっちにもいろいろ記載がありますのでご参照下さい．
https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg

@halsk
↑のリンクと GitHub 2つのまとめがあって dry ではなく，一本化した方がよいのでは？と思いました．

**Comment by nard-tech** [comment]
@stihahi #1821 も一緒に対応できますか？

**Comment by stihahi** [comment]
承知しました、#1821も対応します。
（ただ、福井県版、今のところどこにも見つかりません。
どなたか見つけたら教えて下さい。）

**Comment by westar7** [comment]
@stihahi 福井県 https://covid19-fukui.bosai-signal.jp/ (by 丹南ケーブルテレビ) 
※プライベートリポジトリです。
私自身で追加しようと思っておりましたが、まとめていただけますと幸いです。

**Comment by sasukeh** [comment]
#1821 mergeですね。

**Comment by stihahi** [comment]
福井県のページも追記致しました。
