### ISSUE TITLE
やさしい日本語で[two]週間と表示される

### ISSUE THREAD

**Issue by kikd** [tokyo-metropolitan-gov/covid19#1810]
## 起こっている問題 / The Problem
- やさしい日本語版 flow の"2週間"の表示が" [two]週間（しゅうかん）" となっている
## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5682821/77017996-63aa5a00-69bf-11ea-9c92-a5b25c8e4087.png)

## 期待する見せ方・挙動 / Expected Behavior
- "2週間（しゅうかん）"と表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 多言語対応選択メニューで"やさしい にほんご"を選択
2.  [コロナウイルス が しんぱいな ときに ](https://stopcovid19.metro.tokyo.lg.jp/ja-basic/flow) を開く

## 動作環境・ブラウザ / Environment
- / Windows  / Android
- Chrome / Firefox / Edge

**Comment by halsk** [comment]
ご報告ありがとうございます！修正します

**Comment by kikd** [comment]
transifexで提案出しました！
