### ISSUE TITLE
「心配なときに」多言語 追記

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1825]
「新型コロナウイルス感染症が心配なときに」多言語ページに、「ひまわり」の電話番号の追加をお願いします。
参考）「ひまわり」https://www.himawari.metro.tokyo.jp/qq13/qqport/tomintop/other/fks230.php

・作業対象URL
英語　https://stopcovid19.metro.tokyo.lg.jp/en/flow
簡体字　https://stopcovid19.metro.tokyo.lg.jp/zh-cn/flow
繁体字　https://stopcovid19.metro.tokyo.lg.jp/zh-tw/flow
韓国語　https://stopcovid19.metro.tokyo.lg.jp/ko/flow

・追記していただきたい文言
```
For support in English, Chinese, Korean, Spanish and Thai, please call the Tokyo Health Care Information Center (Himawari)
０３－５２８５－８１８１(Hours: 9:00 a.m. to 8:00 p.m.  includes weekends and holidays.)
```
なお、簡体字・繁体字・韓国語のページにも上記英語の文言の掲載をお願いします。
それぞれの言語への訳出は現段階では不要です。

・追記していただきたい箇所
 -「受診相談窓口」
　平日（夜間）
　～
　03-5320-4592
　の下
もしくは
 - 別添のキャプチャ画像にある、画面上部
<img width="565" alt="キャプチャ" src="https://user-images.githubusercontent.com/61729733/77025336-2b614680-69d4-11ea-8944-0c93f17da5f2.PNG">
どちらが実装しやすいでしょうか。

**Comment by kaizumaki** [comment]
@halsk こちら #1876 でマージされたようなのでクローズしてもいいですか？

**Comment by halsk** [comment]
クローズします！
