### ISSUE TITLE
「心配なときに」新型コロナ外来（帰国者・接触者外来）翻訳差し替えとマークアップ修正

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1826]
「心配なときに」相談フローの英訳について、
・新型コロナ外来（帰国者・接触者外来）
・医師による判断	
それぞれ別々に翻訳が入ってしまっていますが、２つ合わせて下記の１つの文章に変更お願いします。
 Diagnosis by a doctor at a COVID-19 outpatient facility

**Comment by kaizumaki** [comment]
@NaoyaShimizzz こちら以下のデザインを保つべく２つに分かれている状態なんですが、スタイルがくずれてもよいでしょうか？
![スクリーンショット 2020-03-19 11 38 12](https://user-images.githubusercontent.com/14883063/77026166-59478a80-69d6-11ea-897e-30e172f4be47.png)

**Comment by NaoyaShimizzz** [comment]
正しく伝えるにはこの文章で、という庁内判断です。スタイル崩れてしまっても、こちらでお願い致します。

**Comment by kaizumaki** [comment]
@NaoyaShimizzz 了解しました！

**Comment by shgtkshruch** [comment]
質問です。

こちらは英訳のみを以下のように 1つの文章にして、
![スクリーンショット 2020-03-19 15 01 34](https://user-images.githubusercontent.com/5207601/77036512-ae919500-69f2-11ea-931b-bf1333e90d99.png)

多言語については、これまでどおり 2つの文章で表示するという理解でいいでしょうか？
![スクリーンショット 2020-03-19 15 01 40](https://user-images.githubusercontent.com/5207601/77036575-c9fca000-69f2-11ea-8be2-95348ddb139c.png)
![スクリーンショット 2020-03-19 15 01 51](https://user-images.githubusercontent.com/5207601/77036576-cb2dcd00-69f2-11ea-85af-f1de962ab9db.png)
![スクリーンショット 2020-03-19 15 01 58](https://user-images.githubusercontent.com/5207601/77036577-cbc66380-69f2-11ea-999e-54d906a5c98d.png)
![スクリーンショット 2020-03-19 15 02 04](https://user-images.githubusercontent.com/5207601/77036579-cc5efa00-69f2-11ea-8e1c-d030ce1ce448.png)
![スクリーンショット 2020-03-19 15 02 12](https://user-images.githubusercontent.com/5207601/77036580-ccf79080-69f2-11ea-8c9d-a904b5e0ade4.png)

**Comment by NaoyaShimizzz** [comment]
ご対応ありがとうございます。
英訳のみ1つの文章に変更をお願いします。
それ以外の言語は現状のままで問題ございません。

**Comment by shgtkshruch** [comment]
ご回答ありがとうございます。
それでは英訳のみ1つの文章にする方向で実装させていただきます。
