### ISSUE TITLE
都内発生（疑い例・接触者調査）英訳レイアウト

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1827]
「検査実施数」
都内発生（疑い例・接触者調査）
Outbreaks in Tokyo (confirmed through testing of suspected cases or those in close contact with them)

翻訳は正しく反映されていますが、長文のため、はみ出してしまっており読めない状態です。レイアウトの修正お願いします。

**Comment by nard-tech** [comment]
https://stopcovid19.metro.tokyo.lg.jp/en

**Comment by nard-tech** [comment]
@NaoyaShimizzz 着手します

**Comment by kaizumaki** [comment]
このような状況です。
![スクリーンショット 2020-03-19 11 44 07](https://user-images.githubusercontent.com/14883063/77026520-2e116b00-69d7-11ea-9d6a-acab7eb9c514.png)

**Comment by nard-tech** [comment]
実装完了しました (#1835) が，もう少し良くしたいと思っていますので，どなたかアドバイスお願いします．

**Comment by NaoyaShimizzz** [comment]
ご対応ありがとうございます。
こちらで問題ございません。宜しくお願いします。

**Comment by MaySoMusician** [comment]
Close per #2071 merged
