### ISSUE TITLE
wikiページ内「貢献の仕方」のリンク切れ

### ISSUE THREAD

**Issue by takopon97** [tokyo-metropolitan-gov/covid19#1829]
## 起こっている問題 / The Problem
- wikiページ(https://github.com/tokyo-metropolitan-gov/covid19/wiki)
の「貢献の仕方」ページと英語版の"How to Contribute"がリンク切れになっている。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/47264538/77026888-18e90c00-69d8-11ea-9e16-b51fb4e94a0d.png)

## 期待する見せ方・挙動 / Expected Behavior
- 日本語の場合
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/CONTRIBUTING.md
↓
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/CONTRIBUTING.md
- 英語の場合
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/CONTRIBUTING_EN.md
↓
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/docs/en/CONTRIBUTING.md
こちらにリンクを修正する。

## 起こっている問題の再現手段 / Steps to Reproduce
1. wikiページの「貢献の仕方」ページを開く/open "how to contribute"
2. 本ページは こちらに移動しましたをクリック/click "This page has been moved to here"

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kebhr** [comment]
英語版はここにあるみたいです
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/docs/en/CONTRIBUTING.md

**Comment by takopon97** [comment]
ありがとうございます！修正しました。

**Comment by takopon97** [comment]
メインページのリンク先について。
現状だとHow to contributeのページを経由してますが、メインページに直接リンクさせてもよろしいですか？

**Comment by kaizumaki** [comment]
@takopon97 ご指摘ありがとうございます！どうやらwikiはメンバーしか編集できないみたいなんで、私のほうで修正しますね。

> 現状だとHow to contributeのページを経由してますが、contributing.mdをhomeページに直接リンクさせてもよろしいですか？

そうですね。その方向で修正します。

**Comment by kaizumaki** [comment]
よくよくwikiをみたら、How to contributeの目次があるんですね。目次は残しておいた方がいいと思うので、リンクだけ修正します。

**Comment by takopon97** [comment]
対応ありがとうございます。よろしくお願いします。

**Comment by kaizumaki** [comment]
修正しましたので、ご確認ください！

**Comment by takopon97** [comment]
確認できました。ありがとうございました！

**Comment by halsk** [comment]
本件クローズ済みではありますが、README に情報が展開されている今、Wiki 自体必要ないと判断し、Wiki の機能自体を停止いたしました。
