### ISSUE TITLE
Fix 3 spelling typos in assets/locals/en.json

### ISSUE THREAD

**Issue by standby24x7** [tokyo-metropolitan-gov/covid19#1831]
## 起こっている問題 / The Problem
There are 3 English words spelling typo in assets/locals/en.json
３つの英単語の誤字が assets/locals/en.json の中にあります。

Line 49    diffficulty ->  difficulty
Line 88    recomended -> recommended
Line 182  avairable -> available

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by PichuChen** [comment]
Hello, 

For translation (i18n) problem, please come here: https://www.transifex.com/stopcovid19-tokyo/stopcovid19tokyo/language/en/

Please also see the document about translation: 
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/TRANSLATION.md

Thank you

**Comment by MaySoMusician** [comment]
Close per #1833 closed
