### ISSUE TITLE
遅い回線でのYarnのタイムアウト上限時間を設定する

### ISSUE THREAD

**Issue by huideyeren** [tokyo-metropolitan-gov/covid19#1832]
## 改善詳細 / Details of Improvement

遅い回線だとYarnでダウンロードタイムアウトが発生するので、 `.yarnrc` でネットワークのタイムアウト時間を20分に設定する。

**Comment by sasukeh** [comment]
## 手順
1. .yarnrcをrootに作る
2. .yarnrcに以下を書く
```
network-timeout 1200000
```

**Comment by huideyeren** [comment]
着手します。

**Comment by huideyeren** [comment]
ブランチをプッシュできない状態です。

```
ERROR: Permission to tokyo-metropolitan-gov/covid19.git denied to huideyeren.
```

というエラーメッセージが表示されているので、権限の問題かと思われます。

**Comment by huideyeren** [comment]
なお、ファイルの修正は終わっているので、16:45ごろに権限設定が問題なければプルリクエストを作る予定です。

**Comment by kebhr** [comment]
このリポジトリに直接プッシュすることはできないので、Forkしてもらう必要があるかと思います。
https://qiita.com/FPC_COMMUNITY/items/b9cc072813dc2231b2b2#github%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92fork

**Comment by huideyeren** [comment]
なるほど。フォークして対応します。

**Comment by sasukeh** [comment]
@huideyeren 
簡単に作業するなら

1. フォーク
2. GitHub上からファイル追加

![2020-03-19 16_20_27-sasukeh_covid19_ 東京都 新型コロナウイルス感染症対策サイト _ Tokyo COVID-19 Task Force website_LI](https://user-images.githubusercontent.com/406525/77042119-7bed9980-69fe-11ea-839c-a9bce00a34f4.jpg)

3. ファイル編集
4. プルリクエスト作成

ですかね。
