### ISSUE TITLE
グラフのカラー修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1838]
## 改善詳細 / Details of Improvement
- #1172 で検討されてきたカラーをもとに、グラフの色修正をお願いします。
- 対象グラフは「陽性患者数」「検査実施数」「新型コロナコールセンター相談件数」「新型コロナ受診相談窓口相談件数」「都営地下鉄の利用者数の推移」「都庁来庁者数の推移」です（棒グラフすべて）。
- 色はこちら https://github.com/tokyo-metropolitan-gov/covid19/issues/1172#issuecomment-600979679 を参照してください。
- グラフの色はchart.jsのoptionで直指定しています。各グラフのoptionを修正してください。

庁内からの要望、同様にお問い合わせとして「グラフの色がわかりにくい」というご意見をいただいているそうです。
そこで、急ぎ実装に入りたいと思います。

疑問点などあればこのissueにコメントしてください！

**Comment by shgtkshruch** [comment]
こちら対応します〜。

**Comment by kaizumaki** [comment]
@shgtkshruch ありがとうございます！よろしくお願いします！
