### ISSUE TITLE
「都外」が多言語化されない

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#1843]
## 起こっている問題 / The Problem
- 「陽性患者の属性」の居住地として「都外」というワードがあるが、多言語化されていない
  - `assets/locales/ja.json` から抜けている https://github.com/tokyo-metropolitan-gov/covid19/blob/development/assets/locales/ja.json

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/42484226/77039188-c4a25400-69f8-11ea-900d-71edeabbd369.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「都外」が翻訳される

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://dev-covid19-tokyo.netlify.com/en を開く
2. 「陽性患者の属性」を見る

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kebhr** [comment]
`dev-i18n` で作業します。

**Comment by shgtkshruch** [comment]
現在（2020-03-21）の Production では翻訳されているので、close しても良さそうです。

![スクリーンショット 2020-03-21 17 07 27](https://user-images.githubusercontent.com/5207601/77222441-762abc00-6b96-11ea-9d05-743bffcfbf2d.png)
