### ISSUE TITLE
新規翻訳：新宿区への来訪者数の推移のグラフ（未公開）

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#1852]
現在開発中で未公開のグラフ（#1318）ですが、急ぎ準備を進める必要があるため、先に翻訳のissueを立てます。

## グラフタイトル
`新宿区エリアの来訪者推移（参考値）`

## 注釈（グラフ上部）
```
2月3日～2月7日の来訪者数 (※1) の平均値 (※2) を 基準としたときの相対値
※1) ヤフーに蓄積された位置情報データなどを元に算出した参考値
※2) 土・日・祝日を除く7:30~8:30の1週間平均値
```

## 注釈（グラフ下部）
```
※本データは2020年3月31日までの掲載となります
 出典：ヤフー・データソリューション
```

## ツールチップ
```
期間：M/D〜M/D
## 
%
```

## グラフのイメージ
![76950622-a7647b80-694d-11ea-9e63-c5611e4abfe2](https://user-images.githubusercontent.com/4206675/77058565-f88d7180-6a18-11ea-9973-dec2a0729356.png)

**Comment by MaySoMusician** [comment]
> 2月3日～2月7日の来訪者数 (※1) の平均値 (※2) を 基準としたときの相対値
> ※2) 土・日・祝日を除く7:30~8:30の1週間平均値
> ※本データは2020年3月31日までの掲載となります

@ocean3fish  「2月3日～2月7日」「7:30~8:30」「2020年3月31日」の値は固定ですか？今後変動する可能性はありますか？

**Comment by ocean3fish** [comment]
@MaySoMusician そちらの注釈表記内の値はすべて固定で大丈夫です。
変動はありません。

**Comment by MaySoMusician** [comment]
ありがとうございます。後ほどこちらでPRを立て、翻訳ファイルを更新しておきます

**Comment by MaySoMusician** [comment]
`##`・`%`ですがおそらく全言語共通なので追加していません
