### ISSUE TITLE
「はたらく皆様へ」追記

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#1856]
はたらく皆様へ
https://stopcovid19.metro.tokyo.lg.jp/worker
「緊急労働相談ダイヤル」の説明文に、
下記の「、内定取り消し」の追記をお願いします。

緊急労働相談ダイヤル
新型コロナウイルスに関する休暇や休業の取り扱い、職場のハラスメント、内定取消しなどについての相談

**Comment by kebhr** [comment]
着手します。
