### ISSUE TITLE
新規グラフ追加：千代田区エリアの来訪者推移

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#1860]
## 利用データ
- data/13101_daily_visitors.json
（千代田区への来訪者数）

## 見せ方
#1318 と同じ
（データとグラフタイトルとのみ変更）

### タイトル
`千代田区エリアの来訪者推移（参考値）`

## 関連PR
https://github.com/tokyo-metropolitan-gov/covid19/pull/1335

**Comment by shgtkshruch** [comment]
新宿区のグラフを実装したので、こちらも実装させていただきます！

**Comment by ocean3fish** [comment]
@shgtkshruch ありがとうございます！！
