### ISSUE TITLE
多言語対応選択メニューの位置を変更する

### ISSUE THREAD

**Issue by kzhrk** [tokyo-metropolitan-gov/covid19#1865]
## 改善詳細 / Details of Improvement
- 「多言語対応選択メニュー」を`MenuList`の上に移動する
- 「多言語対応選択メニュー」をファーストビューに収めることでユーザビリティを向上させる
  - 言語変更のニーズがあるユーザにとっては`MenuList`よりも先にアクセスできる必要がある

## スクリーンショット / Screenshot
<img width="761" alt="スクリーンショット 2020-03-20 0 49 39" src="https://user-images.githubusercontent.com/548508/77086677-6d76a080-6a45-11ea-9624-b1d1b5047149.png">

## 期待する見せ方・挙動 / Expected behavior
<img width="876" alt="スクリーンショット 2020-03-20 0 53 02" src="https://user-images.githubusercontent.com/548508/77086725-7cf5e980-6a45-11ea-8d98-c3ba519828bf.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kzhrk** [comment]
こちらのissueの修正内容も含んでしまっています。
https://github.com/tokyo-metropolitan-gov/covid19/issues/1854

**Comment by oti** [comment]
@kaizumaki 良さそうに思いますがいかがでしょうか？　既にPRsが #1866 で作られていますので、ご確認いただければと！
