### ISSUE TITLE
SideNavigationの背景が途切れている

### ISSUE THREAD

**Issue by kzhrk** [tokyo-metropolitan-gov/covid19#1868]
## 改善詳細 / Details of Improvement
- `.SideNavigation`のheightを伸ばす
  - `.SideNavigation`のheightがwindowのheightまでしか伸びていないため、`.SideNavigation`の背景色が切れてしまっている

## スクリーンショット / Screenshot
<img width="1426" alt="スクリーンショット 2020-03-20 1 12 18" src="https://user-images.githubusercontent.com/548508/77090368-62723f00-6a4a-11ea-8b2c-75b3be24bfa2.png">

## 期待する見せ方・挙動 / Expected behavior
- `.SideNavigation`のheightがbodyのheightまで伸びていること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by macropygia** [comment]
着手します。

**Comment by macropygia** [comment]
#1481 で解決していると思われます。

**Comment by kzhrk** [comment]
#1481 で解決していることが確認できたのでCloseします 🙏
