### ISSUE TITLE
シェアアイコンにラベルをつける

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#1885]
## 改善詳細 / Details of Improvement
トップページの各パネル右下にあるシェアアイコンにはラベルがない。スクリーンリーダーで読み上げることができるようラベルを付与する。

## 期待する見せ方・挙動 / Expected behavior
svg要素に
role="img" aria-label="（パネル見出し）のグラフをシェア"
を付与する

## 動作環境・ブラウザ / Environment
すべて

**Comment by yukisato** [comment]
こちら良ければ対応させてください。
