### ISSUE TITLE
外部リンクメニュー追加

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#189]
`【東京都主催等】中止又は延期するイベント・説明会等`を追加。場所は公式の下でよいかと。
リンク先は
https://www.seisakukikaku.metro.tokyo.lg.jp/information/event02.html

**Comment by halsk** [comment]
追加。ロゴ下のコピーを以下に変更
```
東京都
新型コロナウイルス感染症対策本部
```
サイト TITLE も合わせて変更願います。

**Comment by sonatax** [comment]
@halsk これ空き時間でサクッと対応しておこうと思うんですが、2点確認させてください。
1. 順番って公式、中止又は延期するイベント、東京都公式の順で
2. 東京都公式ページのリンク先ってこっちですかね？
今公式発表とリンクが同じになっているのでこっちが正しければ編集しておきます。
https://www.bousai.metro.tokyo.lg.jp/index.html

**Comment by halsk** [comment]
ありがとうございます。別のフィードバックで、
"「公式発表」と「東京都公式ホームページ」どちらもリンク先が
https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html
「東京都公式ホームページ」と「東京都新型コロナウイルス感染症対策本部」に変更すると、重複する「公式発表」は削除がよいですかね？"

という話があって決定待ちですが、順番はそれで良いです

**Comment by mikkame** [comment]
あああ、決定待ちの部分があったんですね
