### ISSUE TITLE
他の地域で多言語化機能をオフにしたい人への対応

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1896]
## 改善詳細 / Details of Improvement
- 他地域でこのサイトを複製する際に、多言語化まではリソース的に対応が難しいケースが多い。したがって、フォーク先で多言語化のオプションを外す方法を考えたい
- 消そうと思ったらエラーになってうまくいかなかったという人がいた

## 期待する見せ方・挙動 / Expected behavior
- オプション1：設定項目を設けて、それをオフにすると多言語化機能が全部オフになる
- オプション2：オフにするための解説をドキュメントで書く

その他アイデアある方がいましたらご提案お待ちしております。

**Comment by PichuChen** [comment]
I think if one string have no corresponded translation, it will be remain Japanese, It's OK.
1つの文字列に対応する翻訳がない場合は、日本語のままになりますが、問題ありません。


If anyone think remaining Japanese string in here will be problem, then he/she can make PR.
ここに残っている日本語の文字列が問題だと思う人がいたら、PRしてください。

Or there can be option 3: make an "Translation Request" place for anyone need to help and want to help.
または、オプション3があります。「翻訳リクエスト」の場所を作成して、支援が必要な人や支援したい人がいます。

By the way, In my [Taiwanese Version](https://jolly-lovelace-dbad84.netlify.com/) it just left news items in Chinese ～
ちなみに、私の[台湾版](https://jolly-lovelace-dbad84.netlify.com/)では、中国語のニュース項目を残しました～

**Comment by PichuChen** [comment]
Or there are Option 4: Make Language menu as navigation item,
または、オプション4：ナビゲーション項目として言語メニューを作成します。

Before:
<img width="635" alt="螢幕快照 0002-03-20 10 34 04" src="https://user-images.githubusercontent.com/600238/77131445-a12de680-6a96-11ea-8e52-8dd24a22e445.png">
<img width="671" alt="螢幕快照 0002-03-20 10 34 34" src="https://user-images.githubusercontent.com/600238/77131451-a4c16d80-6a96-11ea-83b1-1af42483a022.png">

After:
<img width="652" alt="螢幕快照 0002-03-20 10 34 17" src="https://user-images.githubusercontent.com/600238/77131457-ab4fe500-6a96-11ea-8a61-983535b3b511.png">
<img width="628" alt="螢幕快照 0002-03-20 10 35 42" src="https://user-images.githubusercontent.com/600238/77131463-aee36c00-6a96-11ea-844d-1fc75837b672.png">


So others can put the item on anywhere they want #1865 
他の人がアイテムを好きな場所に置くことができます

**Comment by halsk** [comment]
> I think if one string have no corresponded translation, it will be remain Japanese, It's OK.
> 1つの文字列に対応する翻訳がない場合は、日本語のままになりますが、問題ありません。
> 
> If anyone think remaining Japanese string in here will be problem, then he/she can make PR.
> ここに残っている日本語の文字列が問題だと思う人がいたら、PRしてください。
> 
> Or there can be option 3: make an "Translation Request" place for anyone need to help and want to help.
> または、オプション3があります。「翻訳リクエスト」の場所を作成して、支援が必要な人や支援したい人がいます。
> 
> By the way, In my [Taiwanese Version](https://jolly-lovelace-dbad84.netlify.com/) it just left news items in Chinese ～
> ちなみに、私の[台湾版](https://jolly-lovelace-dbad84.netlify.com/)では、中国語のニュース項目を残しました～

すごい！！台湾版できてるんですね！

**Comment by kebhr** [comment]
`SideNavigation.vue` の36行目以降を以下のように書き換えれば、Fork先では`nuxt-i18n.config.ts` の編集のみで多言語化をオフにできそうです。（実際には多言語化の対応言語を日本語のみにする）
```vue
<div
  v-if="this.$i18n.locales.length > 1"
  class="SideNavigation-Language"
>
  <label class="SideNavigation-LanguageLabel" for="LanguageSelector">
    {{ $t('多言語対応選択メニュー') }}
  </label>
  <LanguageSelector />
</div>
```

> 設定項目を設けて、それをオフにすると多言語化機能が全部オフになる

に近いと思いますが、いかがでしょうか？

**Comment by halsk** [comment]
> `SideNavigation.vue` の36行目以降を以下のように書き換えれば、Fork先では`nuxt-i18n.config.ts` の編集のみで多言語化をオフにできそうです。（実際には多言語化の対応言語を日本語のみにする）
> 
> ```vue
> 
> <div
> 
>   v-if="this.$i18n.locales.length > 1"
> 
>   class="SideNavigation-Language"
> 
> >
> 
>   <label class="SideNavigation-LanguageLabel" for="LanguageSelector">
> 
>     {{ $t('多言語対応選択メニュー') }}
> 
>   </label>
> 
>   <LanguageSelector />
> 
> </div>
> 
> ```
> 
> 
> 
> > 設定項目を設けて、それをオフにすると多言語化機能が全部オフになる
> 
> 
> 
> に近いと思いますが、いかがでしょうか？

シンプルで良いソリューションだと思います！こちらPRいただけると助かります！
