### ISSUE TITLE
JavaScriptをオフ状態での表示不具合（真っ白な画面が表示される）、他

### ISSUE THREAD

**Issue by KentarouTakeda** [tokyo-metropolitan-gov/covid19#1907]
## 起こっている問題 / The Problem

* JavaScriptをオフ状態でサイトにアクセスすると何も表示されない
* 原因のDOM要素（ローディング用オーバーレイ？）を非表示にすると従来通りに表示されるが「陽性患者の属性」の表の下部が不適切なレイアウトになっている。

## スクリーンショット / Screenshot

![1_jsオフ](https://user-images.githubusercontent.com/4785040/77139206-6ccb2200-6ab8-11ea-9bc3-f1c6427cb7dc.png)

![2_「陽性患者の属性」表](https://user-images.githubusercontent.com/4785040/77139212-72c10300-6ab8-11ea-9d90-868b579472a0.png)

## 期待する見せ方・挙動 / Expected Behavior

* JavaScriptオフ状態でも従来どおりの表示となる
    * グラフ表示箇所に何も表示されない以外はオン状態とほぼ同じ表示
    * 画面中央に *当サイトではJavaScriptを〜* の表示
* 「陽性患者の属性」の表が下に突き抜けているのを元に戻す

## 起こっている問題の再現手段 / Steps to Reproduce
1. Chrome開発者コンソールを開いた状態で Ctrl+Shift+P でコマンドパレットを表示し Disable Javascript でjsの実行を抑制
2. その状態でページを表示
    「何も表示されない」が再現
3. `.v-overlay` 要素をDOMより除去
    「陽性患者の属性」が再現

## 動作環境・ブラウザ / Environment
* 確認したのは Mac OS Chrome 80
* （未確認だがが発生原因考えるとおそらく全ブラウザで発生）

**Comment by kaizumaki** [comment]
こちらの件、 #1071 で一度ローディングをはずしたという経緯があります。シェア時のOGP画像が正常に動かなかったためです。
このissueを解決する場合、そのあたりをご配慮いただけると助かります！

**Comment by KentarouTakeda** [comment]
@kaizumaki 
対応しました。 #1071 から #1479 にかけての流れも多分問題ないと思います、が、発生していた当時の状況や再現方法、解決に用いた手法をきちんと把握できてないので、どなたか分かる方要らしたら見て頂けると助かります。

**Comment by kaizumaki** [comment]
@KentarouTakeda よいと思います！期待していたとおりかと！
