### ISSUE TITLE
[i18n] 東京都ロゴの多言語化

### ISSUE THREAD

**Issue by teikan** [tokyo-metropolitan-gov/covid19#1909]
## 改善詳細 / Details of Improvement
- 現在は![日本語ロゴ](https://stopcovid19.metro.tokyo.lg.jp/logo.svg)に固定されている東京都ロゴを、言語によって切り替え、都のサイトであることを誰にでもわかりやすくする

## 期待する見せ方・挙動 / Expected behavior
- [東京都の公式ウェブサイト](https://www.metro.tokyo.lg.jp/)のように
英語では ![英語ロゴ](https://www.metro.tokyo.lg.jp/shared/site_foreign/images/hdr_logo_en.png)
簡体中国語では ![簡体中国語ロゴ](https://www.metro.tokyo.lg.jp/shared/site_foreign/images/hdr_logo_cn.png)
韓国語では ![韓国語ロゴ](https://www.metro.tokyo.lg.jp/shared/site_foreign/images/hdr_logo_kr.png)
に切り替わる
- 代案として、![英文入りロゴ](https://www.metro.tokyo.lg.jp/shared/images/header/hlogo.gif)にするだけでもいいと思います

**Comment by PichuChen** [comment]
繁體中文ではこのままいいですよ。

In zh-TW, "東京都" is fine.

**Comment by kaizumaki** [comment]
@teikan ご提案いただきありがとうございます！回答がたいへん遅くなりまして申し訳ありません。
こちらの提案について東京都に確認しましたところ、 @teikan さんが書いていらっしゃる通り、[東京都の公式ホームページの「Language」メニュー](https://www.metro.tokyo.lg.jp/foreignlanguage.html) を切り替えた時に左上に表示されるロゴをダウンロードして使用してよいとのことでした（当サイトが同じ東京都公式のサイトであるため）。
ぜひ実装したいのですが、いかがでしょうか？

**Comment by teikan** [comment]
@kaizumaki approveありがとうございます。コミット更新しました。
各言語のロゴのsvgファイルは別途必要ですが、これらも都のサイトからダウンロードしてコミットしてよいものでしょうか。

**Comment by kaizumaki** [comment]
@teikan ご対応ありがとうございます！ロゴ画像はコメント https://github.com/tokyo-metropolitan-gov/covid19/issues/1909#issuecomment-745929411 のとおりで、当サイトも東京都の公式サイトですのでダウンロードしてコミットしていただいて大丈夫です。
