### ISSUE TITLE
お子様をお持ちの皆様へ ページのマージン調整

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#191]
https://stg-covid19-tokyo.netlify.com/parent

マージンを他のページに合わせてください。

**Comment by kaizumaki** [comment]
調査します！

**Comment by halsk** [comment]
ついでにこちらもお願いしますー
https://stg-covid19-tokyo.netlify.com/worker

**Comment by kaizumaki** [comment]
@halsk 了解です！

**Comment by halsk** [comment]
Issue 見直していたら #187 と重複してました。

**Comment by kaizumaki** [comment]
あ、ヘッダーもですね。
