### ISSUE TITLE
robots.txtが見つかりません, Robots.txt not found

### ISSUE THREAD

**Issue by PichuChen** [tokyo-metropolitan-gov/covid19#1912]
## 起こっている問題 / The Problem
- http://stopcovid19.metro.tokyo.lg.jp/robots.txt return 404

## スクリーンショット / Screenshot
![螢幕快照 0002-03-20 14 40 08](https://user-images.githubusercontent.com/600238/77141726-d64b3080-6ab8-11ea-99f8-0e68bddbd40d.png)
![螢幕快照 0002-03-20 14 35 41](https://user-images.githubusercontent.com/600238/77141732-d8ad8a80-6ab8-11ea-9cb3-282ebbde1d20.png)

## 期待する見せ方・挙動 / Expected Behavior
- It should be found for SEO (Google Search, Search Engine)

## 起こっている問題の再現手段 / Steps to Reproduce
1. Test with [Sitechecker](https://sitechecker.pro/robots-tester/)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yuji-k64613** [comment]
やります！

**Comment by yuji-k64613** [comment]
以下、修正案です。

ファイルを追加する。
./static/robots.txt

ファイルの内容は、
User-Agent:*
