### ISSUE TITLE
<b>タグが利用されている

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#1913]
## 起こっている問題 / The Problem
スクリーンリーダーで読み上げる際に、`<b>`タグを正しく解釈し、強調すべき箇所を強調して読み上げる事ができない

sonarsource Rules: [HTML: "&lt;strong&gt;" and "&lt;em&gt;" tags should be used](https://rules.sonarsource.com/html/RSPEC-1100)

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected Behavior
`<b>`タグを`<strong>`タグに変更する

## 起こっている問題の再現手段 / Steps to Reproduce
ソースコードをSonarCloudで静的解析する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
ローカルのコードで確認いたしましたが、検査状況関連の表内での人数表示の部分に使われているようです

**Comment by macropygia** [comment]
マークアップを基準にするならb要素の代替はspan要素（適当なクラスで外観を調整）が適切なはずですし、「外観上の強調の度合いを基準にするとspanは適切ではない」ということであれば、em要素にするかstrong要素にするかは議論の余地がありそうです。
