### ISSUE TITLE
スマホで見たときに、メニューの文字がはみでる

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#192]
iPhone 11 Pro, Chrome/Safari で確認
スマホの場合のフォントサイズを調整願います

![IMG_5206](https://user-images.githubusercontent.com/16509/75725337-9c8dd200-5d23-11ea-8274-81bc6805f2f6.PNG)

**Comment by kaizumaki** [comment]
これはフォントサイズを小さくしますか？それともテキストを折り返しますか？

**Comment by halsk** [comment]
どっちがいいんだろ。
@saladdays さん？

**Comment by halsk** [comment]
とりあえず小さくしましょうか〜
ちょっと大きすぎる感はあるので
