### ISSUE TITLE
<img>タグにalt属性が無く、正しく読み上げる事ができない

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#1925]
## 起こっている問題 / The Problem
`<img>`タグに`alt`属性が無く、正しく読み上げる事ができない。
対象となるのは、以下のファイル
- `components/DataView.vue`
- `components/flow/FlowPcAdvisory.vue`
- `components/flow/FlowPcDays.vue`
- `components/flow/FlowPcHospitalized.vue`
- `components/flow/FlowPcNotRequired.vue`
- `components/flow/FlowPcPast.vue`
- `components/flow/FlowPcSuspect.vue`

資料: [alt属性 ≪ img要素 ≪ 埋め込みコンテンツ ≪ 要素 ≪ HTML5入門](http://html5.cyberlab.info/elements/embedded/img-alt.html)

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected Behavior
1. `alt`属性に以下のどちらかの文字列を追加するか決める
   1. 全言語共通
   1. 言語依存
1. `<img>`タグに`alt`属性を追加する

## 起こっている問題の再現手段 / Steps to Reproduce
ソースコードをSonarCloudで静的解析する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by masanori1102** [comment]
以下を相談したいです。
1. `<img>`タグに`alt`属性を入れるか入れないか -> もし、入れない場合は、このissueをcloseしてください
1. `alt`属性を入れるか場合は、どの言語で入れるか

**Comment by shunito** [comment]
@masanori1102 Vueのバインド使って以下のように書けば、組み込みのi18nの機能と翻訳チームが何とかしてくれると思います！

```<img src="/line.png" :alt="$t('Line')" class="icon-resize line" />```

```:alt``` のところですね。
