### ISSUE TITLE
サイトタイトルの翻訳修正

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1926]
## 改善詳細 / Details of Improvement
- メニューのサイトタイトルの英文を `Tokyo COVID-19 Information` に変えたい

## 期待する見せ方・挙動 / Expected behavior
- 当該部分は `{{ $t('新型コロナウイルス感染症') }}<br />{{ $t('対策サイト') }}` となっており、`'新型コロナウイルス感染症'` は他の場所でも使われている。タイトルのみ別のキーを設定する必要あり

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by pingineer-jp** [comment]
やります
とりあえずどの言語でも「Tokyo COVID-19 Information」にして構わないですか？

**Comment by halsk** [comment]
ありがとうございます。ただ、こちらはすでに私の方で新しいキーを追加して対応中です。

**Comment by pingineer-jp** [comment]
了解です
頑張ってください！！！

**Comment by MaySoMusician** [comment]
Close per #1941 merged
