### ISSUE TITLE
CSSで同名のプロパティが利用されている

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#1928]
## 起こっている問題 / The Problem
CSSで同名のプロパティが利用されている。

CSSはプロパティの重複を許可しますが、重複する名前の最後のインスタンスのみが、それに使用される実際の値を決定します。したがって、重複した名前の他の出現の値を変更しても効果はなく、誤解やバグを引き起こす可能性があります。

sonarsource Rules: [Properties should not be duplicated](https://rules.sonarsource.com/css/RSPEC-4656)

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected Behavior
重複するプロパティを削除する

## 起こっている問題の再現手段 / Steps to Reproduce
ソースコードをSonarCloudで静的解析する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by masanori1102** [comment]
これ、やります

**Comment by munierujp** [comment]
#1700 で解消される予定です。

**Comment by masanori1102** [comment]
#1700 で解消されたので、Closeする
