### ISSUE TITLE
DataSelectorの外枠の横幅が広がっている

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#1938]
## 起こっている問題 / The Problem
- 「都内の最新感染動向」の時系列グラフの上部に表示されている、「日別」と「累計」を切り替えるボタン群の外枠の横幅が広がりすぎている
  - development で確認、staging ではこれまで通り表示される

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/42484226/77159924-a9634180-6ae9-11ea-8b1d-c8aa253ae41f.png)
![image](https://user-images.githubusercontent.com/42484226/77159689-2a6e0900-6ae9-11ea-8554-c0883187944a.png)

## 期待する見せ方・挙動 / Expected Behavior
- これまで通り表示される
![image](https://user-images.githubusercontent.com/42484226/77159556-eb3fb800-6ae8-11ea-8b39-991728b9a5dc.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://dev-covid19-tokyo.netlify.com/ を開く
2. 「陽性患者数」などのグラフを見る

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@kebhr ご指摘ありがとうございます！どうやら #1443 をマージした際に発生したバグのようです。

**Comment by kaizumaki** [comment]
```
<data-selector
    v-model="dataKind"
    :target-id="chartId"
    :style="{ display: canvas ? 'block' : 'none' }"
/>
```
ここの `block` を `inline-block` にすればよさそうです。

**Comment by kaizumaki** [comment]
私のほうで修正しておきますね。

**Comment by KentarouTakeda** [comment]
@kaizumaki 
すみません、ありがとうございます。
ご迷惑おかけしました。

**Comment by kaizumaki** [comment]
@KentarouTakeda いえいえ！だいじょうぶですよー！
