### ISSUE TITLE
表のツールチップ修正

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#194]
表にマウスオーバーしたときの表示がデザインと違います。

サイト
![image](https://user-images.githubusercontent.com/16509/75725537-ff7f6900-5d23-11ea-87a8-af5b7042aa26.png)

デザイン

![image](https://user-images.githubusercontent.com/16509/75725620-30f83480-5d24-11ea-9169-472fb0ef8860.png)

**Comment by koizoom1** [comment]
他のテーブルでは「m/d」のフォーマットなので、tooltipのデザインに合わせて「m月d日」にするか、他のテーブル等に合わせてtooltipも「m/d」にするか要検討

**Comment by mikkame** [comment]
transition の部分だけ修正してもらいました。
日付フォーマットが決まり次第再開予定です

**Comment by halsk** [comment]
m月d日
にしましょうか！

**Comment by potato4d** [comment]
マージ済みのためクローズ。
