### ISSUE TITLE
新グラフ「新宿区エリアの来訪者推移」にnoscript時の処理を加える

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#1945]
## 改善詳細 / Details of Improvement
- #1443 にて、noscript時にグラフを表として見せる実装がマージされましたが、新規グラフ「新宿区エリアの来訪者推移」には施されていないので、実装してほしいです。

## スクリーンショット / Screenshot
こちらのグラフです（javascript許可時）。
![スクリーンショット 2020-03-20 21 41 31](https://user-images.githubusercontent.com/14883063/77164486-c13fc300-6af3-11ea-8b3d-9dbc1794951d.png)

## 期待する見せ方・挙動 / Expected behavior
例えばこんなふうに、noscript（javascriptブロック時）には表になっているのが期待する動作です。
![スクリーンショット 2020-03-20 21 42 19](https://user-images.githubusercontent.com/14883063/77164640-167bd480-6af4-11ea-9e41-215979d58f61.png)

**Comment by t-tajiri** [comment]
私でよろしければ対応させてください。

**Comment by kaizumaki** [comment]
@t-tajiri お願いします！

**Comment by KentarouTakeda** [comment]
レス書いてたらタッチの差で先越されましたw

@t-tajiri 
大本のnoscript実装は私が書いたので分かりづらい箇所は聞いて下さい！
おかしな実装があったらご遠慮無く変えちゃってください！笑

**Comment by t-tajiri** [comment]
@KentarouTakeda 
お気遣いありがとうございます！

早速質問させてください！
@KentarouTakeda さんの実装を参考にしてみましたが、表のヘッダーがnoscript時のメッセージより上に出力されています。これは実装が間違っていますかね。。。？
具体的には、下のスクリーンショットのようになってしまいます。

<img width="696" alt="sheet" src="https://user-images.githubusercontent.com/40433305/77171958-9019bf80-6b00-11ea-9519-99b66ab74c1d.png">

**Comment by KentarouTakeda** [comment]
@t-tajiri 着手ありがとうございます。ていうか仕事早いw

「noscriptの際のv-tableのの実装」単独としては間違ってない（今の状態で良い）と思います。

ご質問の表示崩れは、 Issue にはまだ無いのですが、もっと前から存在していた「陽性患者の属性」の表でも発生していた（おそらく `v-table` 全てで発生する）ので、仮に直す場合「表のバグとして `v-table` を全箇所修正する」ではなく「モーダルウインドウの表示バグとして別件で修正する」が自然な気がします。（と思いそのままにしてしまってました 汗汗
