### ISSUE TITLE
card-button内のテキストが折り返された時にテキストがはみ出る

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#196]
![スクリーンショット 2020-03-03 9 06 34](https://user-images.githubusercontent.com/13947046/75729879-8afdf780-5d2e-11ea-885e-8f2e6ee4b3ca.png)

heightを外すか
min-heightに変更で直りそうですが影響範囲分からないのでフロント詳しい人教えてください

**Comment by kaizumaki** [comment]
これ調査してみますね。
