### ISSUE TITLE
hardsource を無効化する

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#1964]
## 改善詳細 / Details of Improvement
- `yarn dev` での開発や Netlify のビルド時に hardsource に関するエラーが発生することがあるので無効化する
  - #1855, #1897, #1916, #1920 
  - issue かするか迷いましたが、エラー報告が複数あったので作成しました
- ビルド時間が増加しますが、hardsource に起因するエラーがなくなります
- 導入された経緯がわからないので、無効化するデメリットや弊害等があればコメントお願いします

### Netlify
```
...
9:11:59 PM:  ERROR  [hardsource:01a652d3] Could not freeze ./node_modules/core-js/modules/es6.object.to-string.js: Cannot read property 'hash' of undefined
9:11:59 PM:  ERROR  [hardsource:01a652d3] Could not freeze ./node_modules/core-js/modules/_object-dp.js: Cannot read property 'hash' of undefined
9:11:59 PM:  ERROR  [hardsource:01a652d3] Could not freeze ./node_modules/core-js/modules/_redefine.js: Cannot read property 'hash' of undefined
...
9:12:00 PM: Shutting down logging, 235 messages pending
```
ref: https://app.netlify.com/sites/dev-covid19-tokyo/deploys/5e7361357fdc4900089e7ca1

### `yarn dev`
コンポーネントを修正していると下記のように `variables.scss` の import コンパイルエラーになることがある。
```ERROR  in ./components/SideNavigation.vue?vue&type=style&index=0&id=5b9ce134&lang=scss&scoped=true&
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):   friendly-errors 14:34:51
SassError: Can't find stylesheet to import.
  ╷
2 │ @import '~/assets/variables.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```

## 期待する見せ方・挙動 / Expected behavior
- hardsource を無効にする

## 動作環境・ブラウザ / Environment
- ローカル開発環境
- Netlify

## 参考リンク
- https://ja.nuxtjs.org/api/configuration-build/#hardsource
- https://github.com/mzgoddard/hard-source-webpack-plugin

**Comment by mikkame** [comment]
導入された経緯はビルドの高速化です。
https://github.com/tokyo-metropolitan-gov/covid19/pull/797
を参照のこと

消す対応します！
