### ISSUE TITLE
新宿区、千代田区のグラフはリリースから一時はずす

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#1970]
## 改善詳細 / Details of Improvement
- まだ都側の最終チェックが終わっていないため、明日明後日のリリースからは、新宿区/千代田区のグラフははずしておきます。

**Comment by nichesuch** [comment]
リリースの際は以下気をつけてください。
#1971

**Comment by halsk** [comment]
リリース終わったので戻しておきました。
明日も同じなのでIssueは残しておきます。
