### ISSUE TITLE
新宿区エリアと千代田区エリアの来訪者推移のOGP画像が自動生成されていない

### ISSUE THREAD

**Issue by nichesuch** [tokyo-metropolitan-gov/covid19#1971]
## 起こっている問題 / The Problem
- GitHub Actionsのワークフローで新宿区エリアの来訪者推移のOGP画像が自動生成されていない

## 期待する見せ方・挙動 / Expected Behavior
- 新宿区エリアの来訪者推移のOGP画像を自動生成する

ogp_screenshot.pyのPATHSに追加すればよいと思われる。

## 起こっている問題の再現手段 / Steps to Reproduce
1. git checkout staging
2. git push
3. OGP Builder の結果を確認

## 動作環境・ブラウザ / Environment
- GitHub Actions

**Comment by shgtkshruch** [comment]
#1944 で千代田区エリアの来訪者数推移のグラフを追加したので、合わせて対応いただければと思います。

**Comment by nichesuch** [comment]
やります。
千代田区のグラフが新宿区と同じタイミングで公開になるかわからないので、ひとまず分けて対応します。

**Comment by halsk** [comment]
@nichesuch さん、ありがとうございます！両グラフのリリースタイミングは同じになりますので、まとめてしまっても構いません

**Comment by nichesuch** [comment]
了解です。こちらにまとめます。

**Comment by nichesuch** [comment]
#2015 にまとめました。
