### ISSUE TITLE
VisitorBarChartがType Error

### ISSUE THREAD

**Issue by t-tajiri** [tokyo-metropolitan-gov/covid19#1974]
## 起こっている問題 / The Problem
-  コンソール上に下記スクリーンショットの通りエラーメッセージが表示されている。
- このコンポーネントは新宿区エリアの来訪者推移のグラフにて参照されている。

## スクリーンショット / Screenshot
<img width="780" alt="Screen Shot 2020-03-21 at 0 37 28" src="https://user-images.githubusercontent.com/40433305/77179709-2c958f00-6b0c-11ea-9ecd-fd682f4db59c.png">

## 期待する見せ方・挙動 / Expected Behavior
- コンソールに表示されているエラーの解消

## 起こっている問題の再現手段 / Steps to Reproduce
1. `yarn dev` にて起動
2. コンソールにエラー出力される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by t-tajiri** [comment]
確認します。

**Comment by masanori1102** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/VisitorsBarChart.vue#L132 で`chartData`が配列として判断できない為に、この`ERROR`が出ているようです。

**Comment by t-tajiri** [comment]
@masanori1102 無事、解決しました！ありがとうございました。
