### ISSUE TITLE
DockerfileのCOPY命令の送信先のパスを絶対パスに変更

### ISSUE THREAD

**Issue by sorairolake** [tokyo-metropolitan-gov/covid19#1989]
## 改善詳細 / Details of Improvement
- `Dockerfile`の`COPY`命令の送信先のパスが相対パスになっていますが、絶対パスにした方が分かりやすいと思います。
- この場合、`WORKDIR`と`COPY`で指定するパスが同じものになるので、`ENV`命令でパスを指定するのが良いと思います。

**Comment by skakepi** [comment]
こんにちは！
間違いでしたら申し訳ないですが
docker-compose.yml 12行目でホスト側カレントディレクトリとコンテナ側のappディレクトリをマウントしているにも関わらず
Dockerfile 5行目、9行目でCOPYする理由が無いと思ったのですが、何か理由があるんですかね？
さらにはdocker-compose.yml 13行目を実装している理由も分かりません。。

**Comment by sorairolake** [comment]
@skakepi 
`COPY`については、`Dockerfile`単体での利用を想定したものだと思います。
