### ISSUE TITLE
トラッキングIDの追加

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#200]
下記トラッキングIDになります。設定お願いします。

トラッキング ID
UA-159417676-1

グローバル サイトタグ  

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src=""https://www.googletagmanager.com/gtag/js?id=UA-159417676-1""></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-159417676-1');
</script>
```

合わせて、「このサイトについて」に以下を追加

"クッキー (Cookie) についての下に追加をお願いします。
-----
GoogleAnalytics の利用について

当サイトでは、サービス向上やWebサイトの改善のためにGoogle Inc.の提供するアクセス分析のツールであるGoogle Analyticsを利用した計測を行っております。
Google Analyticsは、当サイトが発行するクッキー(Cookie)を利用して、個人を特定する情報を含まずにWebサイトの利用データ（アクセス状況、トラフィック、閲覧環境など）を収集しております。クッキー(Cookie)の利用に関してはGoogleのプライバシーポリシーと規約に基づいております。
取得したデータはWebサイト利用状況の分析、サイト運営者へのレポートの作成、その他のサービスの提供に関わる目的に限り、これを使用します。

Google Analyticsの利用規約及びプライバシーポリシーに関する説明については、Google Analyticsのサイトをご覧ください。
・Google Analytics利用規約（外部サイトを表示する）→ https://marketingplatform.google.com/about/analytics/terms/jp/
・Googleのプライバシーポリシー（外部サイトを表示する）→ https://docs.google.com/spreadsheets/d/1trOT3C-XFk_NVQTDNNDibscEVWLRDd3VUfz95ofbY-U/edit#gid=0
・Google Analyticsに関する詳細情報（外部サイトを表示する）→https://support.google.com/analytics/answer/6004245"

**Comment by halsk** [comment]
これやりますねー

**Comment by mikkame** [comment]
あ、ちょうどやってますー

**Comment by mikkame** [comment]
> ・Googleのプライバシーポリシー（外部サイトを表示する）→

これのリンク先おかしいきがします

**Comment by halsk** [comment]
とりあえずこれ貼っといてください。あとで確認してもらいmす。
https://policies.google.com/privacy?hl=ja
