### ISSUE TITLE
個別グラフページが、Facebook Graph API Explorer でエラー

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#2002]
## 起こっている問題 / The Problem
- Facebook Graph API Explorer で、https://stopcovid19.metro.tokyo.lg.jp/en/agency/ などをチェックすると、以下のエラーが起きる

```
{
  "error": {
    "message": "Invalid parameter",
    "type": "OAuthException",
    "code": 100,
    "error_subcode": 1611016,
    "is_transient": false,
    "error_user_title": "オブジェクトの値が無効です",
    "error_user_msg": "プロパティ「og:locale:locale」に指定された値「ja」はタイプ「enum」としてパースできないため、URL「https://stopcovid19.metro.tokyo.lg.jp/」のオブジェクト(タイプ「website」)は無効です。",
    "fbtrace_id": "A7QDLBuuFNKBSmzYS5L-rMv"
  }
}
```

## 期待する見せ方・挙動 / Expected Behavior
- エラーが出なくなる

## 起こっている問題の再現手段 / Steps to Reproduce
1. [https://developers.facebook.com/tools/explorer/?method=POST&path=%3Fscrape%3Dtrue%26id%3Dhttps%3A%2F%2Fstopcovid19.metro.tokyo.lg.jp%2Fcards%2Fagency%2F&version=v6.0](デバッガーページ) にアクセス
2. 送信ボタンを押す

**Comment by kaizumaki** [comment]
そもそも `https://stopcovid19.metro.tokyo.lg.jp/en/agency/` が404ですね。

**Comment by kaizumaki** [comment]
> そもそも `https://stopcovid19.metro.tokyo.lg.jp/en/agency/` が404ですね。

あ、 `https://stopcovid19.metro.tokyo.lg.jp/en/cards/agency` でしたね。失礼しました。

**Comment by kaizumaki** [comment]
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fstopcovid19.metro.tokyo.lg.jp%2Fen%2Fcards%2Fagency%2F

こちらでは200のようです。

**Comment by halsk** [comment]
なぜかAPIから叩くとエラーになるんですよね。キャッシュ更新をコマンドラインから行うシェルスクリプトがあるのですが、それが機能しなくなってしまったのです。


https://github.com/tokyo-metropolitan-gov/covid19/blob/development/ui-test/delete_fbcache.sh

**Comment by cgetc** [comment]
@halsk 指定するog:localeの値が間違っているのが原因のようです。
http://kira-ism.com/archives/3064
Facebookのドキュメントでもそうなってました。
https://developers.facebook.com/docs/sharing/webmasters/?locale=ja_JP

**Comment by halsk** [comment]
`ja` とかじゃなくて `ja_JP` とかじゃないと駄目なんですかね。Pull Request いただくことはできますか？

**Comment by cgetc** [comment]
はい、そのつもりでした。
