### ISSUE TITLE
[i18n] 千代田区への来訪者数の推移のグラフの翻訳

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#2005]
## 改善詳細 / Details of Improvement
- 「千代田区エリアの来訪者推移（参考値）」が日本語のままなので多言語対応する

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-21 11 32 55](https://user-images.githubusercontent.com/5207601/77217703-bde61f00-6b67-11ea-8e33-7dd7617f0c1c.png)

## 期待する見せ方・挙動 / Expected behavior
- 言語選択に応じてグラフタイトルが翻訳されてること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by adakou** [comment]
>#1985 で議論されている通り、
>ja.json 以外のファイルは GitHub 側で修正はできません。

>ja.json にキーを追加 (dev-i18n ブランチ)
>Transifex 側で翻訳
>Transifex 側から変更を dev-i18n へ push
>dev-i18n を development にマージ
>という流れになります。
>Transifex 側では修正はされていたので、次回反映時に取り込まれます。

**Comment by shgtkshruch** [comment]
本番環境で翻訳されていることが確認できましたので close します。
翻訳してくださった方々、ありがございました！

![スクリーンショット 2020-03-27 14 56 15](https://user-images.githubusercontent.com/5207601/77726466-461e6580-703b-11ea-940b-4f01f40b5ee2.png)
