### ISSUE TITLE
データテーブルにタブキーでフォーカスできるようにする

### ISSUE THREAD

**Issue by shunito** [tokyo-metropolitan-gov/covid19#2011]
## 改善詳細 / Details of Improvement
- スクリーンリーダー用に埋め込まれているテーブルにタブでフォーカスをあてられるようにする。
- テーブルに利用しているv-data-tableに「tabindex="0"」をまとめて付与する。
- 関連イシュー： #1155 #65

## 期待する見せ方・挙動 / Expected behavior
- タブキーを利用してページ内を移動した場合に、テーブルにフォーカスがあたる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shunito** [comment]
対応が必要な個所は確認済みです。対応するようであればアサインしていただければ。

**Comment by kaizumaki** [comment]
@shunito 実装する方向でよいかと思います。お願いします！

**Comment by shunito** [comment]
あ、自分のプルリクのこれとちょっとコンフリクト起こりそうなので、マージされたらやります。
#1984

**Comment by shunito** [comment]
セルフチェックではよさそうです。よろしくお願いします。
