### ISSUE TITLE
OGP画像のフォントが汚い

### ISSUE THREAD

**Issue by nichesuch** [tokyo-metropolitan-gov/covid19#2022]
## 改善詳細 / Details of Improvement
- OGP画像のフォントを綺麗にしたい

## スクリーンショット / Screenshot

![agency_staging](https://user-images.githubusercontent.com/2096703/77221969-37930280-6b92-11ea-85b3-0e3a52519fc7.png)

## 期待する見せ方・挙動 / Expected behavior
- Webと同等のフォントになる

![agency](https://user-images.githubusercontent.com/2096703/77221986-614c2980-6b92-11ea-885f-c4402d702509.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nichesuch** [comment]
@halsk お疲れ様です。
これ、うまく出来たのですが、原因は不明なのと、stagingに上げないといけないです。
`.github/workflows/ogp_builder.yml`

ローカル環境だと綺麗に出来たので、runs-on環境をmacos-latestにして、コマンドも少し変えました。
`pip`→`pip3`
`python`→`python3`

ForkしたGithub Actionsでは動作しました。
<img width="1311" alt="スクリーンショット 2020-03-21 16 35 40" src="https://user-images.githubusercontent.com/2096703/77222092-783f4b80-6b93-11ea-9d8b-5f3e2c0d25b8.png">


developmentにPRを送ればいいでしょうか？

**Comment by nichesuch** [comment]
おそらくWebフォントがインストールできていないのは変わりなく、標準フォントがそれなりなmacにすることで、解決したように見えるというのが実情だと思います。

参考
https://1000ch.net/posts/2016/web-font.html

**Comment by halsk** [comment]
ありがとうございます！気になっていました。development に上げてもらって大丈夫です。
