### ISSUE TITLE
data/data.jsonを公開サイトから参照できるURLが欲しい

### ISSUE THREAD

**Issue by wakasamasao** [tokyo-metropolitan-gov/covid19#2023]
## 改善詳細 / Details of Improvement
- 現在は公開サイトはdata.jsonが内部に取り込まれているため、直接見るのは頑張ればできるがdeploy毎にURLが変わるなどあり、そのまま参照する静的なURLを作りたい
- GitHubを直接参照するということはあるかもしれないが、GitHubを利用しているか不明な公開サイトが出てきてもデータを参照できるようにしたい

## やりたいこと
- forkされて複数の地域で作成されているが、同じフォーマットでデータが綺麗なデータとして作成されているのに、隣県の情報をグラフなどで同時に並べて表示しようとした場合に参照することができない。（参照時には直接アクセスし負荷がかかるので相互の理解も必要ではある事案なので、利用に際しては注意が必要ではあるため、ON/OFFが必要な可能性はある）

## 期待する見せ方・挙動 / Expected behavior
- /data/data.json などのパスでアクセスすると、作成されたdata.jsonを表示できる

## 動作環境・ブラウザ / Environment
- RESTでアクセス or ブラウザでアクセス

**Comment by yuji-k64613** [comment]
以下の対応でどうでしょうか。

1. シンボリックリンクを作成する
ln -s ./data/data.json ./static/data.json

2. 以下のURLでアクセス可能になる
https://stopcovid19.metro.tokyo.lg.jp/data.json

**Comment by usk81** [comment]
先程、#2148 でデータをGoogleSpreadSheetなどで管理する案を出しました。
これだったら、多少整形はいりますが外部利用できるようになると思います。
いかがでしょう？

**Comment by kaizumaki** [comment]
@wakasamasao ご提案ありがとうございます。こちらのissueについて東京都と相談いたしましたが、現在、[オープンデータカタログサイト](https://portal.data.metro.tokyo.lg.jp/)のほうでAPI化の検討がされているところであり、対策サイトでデータの参照urlを提供することはしないという方針です。今後のオープンデータカタログサイトをご参照いただければと思います。

**Comment by kaizumaki** [comment]
東京都から回答がありましたので、こちらのissueはクローズいたします。
