### ISSUE TITLE
開発環境でアニメーションの処理が重たい

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#2027]
## 改善詳細 / Details of Improvement
- **開発環境**でグラフの表示切り替え（日別 || 累計）や言語を変更した際にスムーズにレンダリングされない
- 本番環境や Netlify の Deploy Preview では発生していないので、優先度が高いわけではないです

## スクリーンショット / Screenshot
グラフの表示切り替え時のパフォーマンスを Chrome の Developer Tools で計測しました。

[Profile-20200321T181905.json.zip](https://github.com/tokyo-metropolitan-gov/covid19/files/4362654/Profile-20200321T181905.json.zip)
![スクリーンショット 2020-03-21 18 19 34](https://user-images.githubusercontent.com/5207601/77223508-9a8b9600-6ba0-11ea-9744-f1ffca2beca7.png)

おもに vue-axe に関連する処理で時間がかかっていて、FPS が 1 になっています。
（違和感なくアニメーションしているように見えるのは、60 FPS が目安です）

## 期待する見せ方・挙動 / Expected behavior
- 開発環境でもアニメーションがなめらかに動くと嬉しい
- vue-axe はアクセシビリティ関連のエラーを console に出力してくれるので、無効にするのも違うかなと思っています ref: #798
  - オプションなどで改善できるといいかも

## 動作環境・ブラウザ / Environment
- macOS Catalina 10.15.3
- Chrome 80.0.3987.116（Official Build） （64 ビット）

**Comment by shunito** [comment]
導入に関わった伊藤です。
いまはenvがdevelopの場合にaxeが必ず動きますがアニメーションとかの検証には困るでしょうね。

``` > yarn dev-no-axe``` とか準備すればよさそうですか？

**Comment by shgtkshruch** [comment]
vue-axe を有効にした上でレンダリングをブロックしないのが理想だと思いますが、個人的にはご提案頂いたコマンドがあると嬉しいです。

1つ伺いたいのですが、アクセシビリティ関連の改善をすすめることで vue-axe の処理速度も改善されることはあるのでしょうか？

**Comment by shunito** [comment]
残念ながらaxeは全ノードベタなめしながらチェック項目を全量実行しちゃうので、パフォーマンスはノード数に応じてどうしても重くなってしまいます。
特にvue-axeはNuxtのルーターの変更を検知して動きますので、何か再表示するたびチェックが働きます。まぁ、そういうツールなのですが。

基盤に近いところの変更も少し必要ですが、対応は可能です。
管理者の方の判断で必要そうであればアサインしていただければ対応しますー。

**Comment by shgtkshruch** [comment]
回答ありがとうございます。

> axeは全ノードベタなめしながらチェック項目を全量実行しちゃうので、パフォーマンスはノード数に応じてどうしても重くなってしまいます。

そうなんですね。
vue-axe について知らなかったので勉強になりました！

個人的には、必須ではないですが早くなったらいいなくらいの温度感です〜。

**Comment by shunito** [comment]
はい、ちょっとウザいときはアドホックに
```\plugins\axe.js``` の二行目あたりに ```return true``` とか突っ込んでいただければ。

**Comment by shunito** [comment]
こちら、自分で開発していてもやっぱり重いので、自分でも欲しくなってきました。
私はA11y主体でやっているのでしょうがないのですが、開発者の皆さんみなストレスなのもよくないので、やっぱりAxeが動かないコマンド準備させていただこうかと思います。
