### ISSUE TITLE
このサイトのソースコードの著作権者について

### ISSUE THREAD

**Issue by sorairolake** [tokyo-metropolitan-gov/covid19#2030]
## 改善詳細 / Details of Improvement
[LICENSE.txt](https://github.com/tokyo-metropolitan-gov/covid19/blob/5950d0027f3eb1721684477874a6ab8ff454f140/LICENSE.txt)で著作権者が東京都 (Tokyo Metropolitan Government) 単独になっていますが、このサイトの著作権者は東京都及び貢献者ではなく、東京都単独という認識で正しいでしょうか?
もし、東京都及び貢献者が著作権者の場合は、LICENSE.txtの著作権者の部分を修正した方が良いと思います。

## 期待する見せ方・挙動 / Expected behavior
- 東京都単独の場合は、東京都への著作権の譲渡を明記。
- 東京都及び貢献者の場合は、`Tokyo Metropolitan Government`を`Tokyo Metropolitan Government and other contributors`へ修正。また、貢献者が[CONTRIBUTORS.md](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/CONTRIBUTORS.md)で確認できることを`(see CONTRIBUTORS.md)`のようにして示すもの良いと思います。

**Comment by mcdmaster** [comment]
あくまで個人的な興味でコメントします。論点がズレているようでしたらご容赦ください。

おそらく、オープンソース・ソフトウェア開発案件の場合の東京都のガイドラインがあると察します。通常、そういったガイドラインには著作権がらみの（あるいは著作権に留まらない）dispute があった際の東京都における受付窓口が示されます。

本プロジェクトで採用されている MIT ライセンスは、ライセンス・スキームの中でもハイレベルなポリシ、ないしはライセンスの「考え方」の大枠を構成するものと考えます。

上記を踏まえつつ、たとえば
所有者：東京都
著作権者：貢献者
という（本プロジェクトとしての）定義を、LICENSE.txt ではなく pages/about.vue 中に示しておくことができます。また、MIT ライセンスに記されているように、本プロジェクトの成果を他の案件で使用する、また、そのために改訂や再配布を行うことも、所有者は貢献者に対し認める、という主旨を明記できます。

仮にこれを実現する場合、どういった制約条件が東京都と貢献者との間にあるでしょうか？

**Comment by mcdmaster** [comment]
MIT LICENSE.txt には、こんな書き方もあるみたいですね。

Copyright 2020 Tokyo COVID-19 Task Force Website Developers.
See the CONTRIBUTORS.md file at the top-level directory of this distribution and at https://github.com/tokyo-metropolitan-gov/covid19/CONTRIBUTORS.md.

出典は[こちら](https://opensource.stackexchange.com/a/8624)

**Comment by mcdmaster** [comment]
たびたびすみません。

サイトの Ownership、特にデータ・オーナーシップという観点であれば、スポンサーでもある東京都が「所有者」の立場を担うことには、IT 監査目線で見ても違和感はありません。
一方で、ソースコードの著作権はデベロッパー・コミュニティに帰属するという表現は、東京都がそれ、すなわち MIT ライセンスの記載内容に合意したことが明示されていれば（`pages/about.vue` 「ソースコードについて」のセクションあたりで）、それも IT 監査的にはオーケーです。
現時点の MIT `LICENCE.txt` は東京都が著作権者という建付けになっているため、直前の投稿で示したような書き方を東京都が許容できるのかどうか、東京都側のお考えを頂戴したいところです

**Comment by mtzhiro** [comment]
関連が薄い話題ですいません・・「tokyo-metropolitan-gov/covid19」の”名前”ってありますか？「Nuxt COVID-19 Tokyo App」的な感じかな、と思っているのですが・・

**Comment by mtzhiro** [comment]
> 「tokyo-metropolitan-gov/covid19」の”名前”ってありますか？「Nuxt COVID-19 Tokyo App」的..
 transifex.com "StopCovid19Tokyo" が少しヒントになったかもです・・

**Comment by mcdmaster** [comment]
StopCovid19Tokyo は、アプリケーションの名前としてはクールですね。
プロジェクトのミッションも端的に表されているので、ナイスです

**Comment by ocean3fish** [comment]
@sorairolake @mcdmaster 
本件ご提案・ご検討頂きありがとうございます。
都側の検討の結果、[LICENSE.txt](https://github.com/tokyo-metropolitan-gov/covid19/blob/5950d0027f3eb1721684477874a6ab8ff454f140/LICENSE.txt)の表記をご提案の通り以下に変更したいとのことでした。

`Tokyo Metropolitan Government`
↓
`Tokyo Metropolitan Government and other contributors`

「コミットいただいている皆様になかなか御礼申し上げる機会がないですが、せめてこの表記に残していただければ」というコメントもありました。

**Comment by mcdmaster** [comment]
@ocean3fish 様

ご配慮をいただき、ありがとうございます。また、レスポンスが遅くなってしまい、申し訳ございません。
可及的速やかに、プルリクエストを発行いたします
