### ISSUE TITLE
スクリーンリーダー向け隠しtableのマークアップ改善

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#2049]
## 改善詳細 / Details of Improvement
#1019 からの #1443 で、グラフに対してスクリーンリーダー向けに隠しtableが挿入された。このtableのマークアップを改善（列見出しの追加および最適化）することで、より適切に情報取得できるようにする。

## スクリーンショット / Screenshot

列見出しの追加が必要なtable
<img width="320" alt="スクリーンショット 2020-03-21 22 37 42" src="https://user-images.githubusercontent.com/17713513/77227589-b5700180-6bc4-11ea-816b-1048db66b250.png">

列見出しはあるが不完全な部分があったり、ノイズがあったりするtable
※th要素はtable内のセルを読み上げるときに毎回読まれるため、ノイズがあると情報取得に支障を来す恐れがある
<img width="799" alt="スクリーンショット 2020-03-21 22 38 01" src="https://user-images.githubusercontent.com/17713513/77227591-b6a12e80-6bc4-11ea-8a55-4dc2ec9fe7f0.png">

### 陽性患者数, 検査実施人数, 新型コロナコールセンター相談件数, 新型コロナ受診相談窓口相談件数

列見出しが無い状態なので、`tbody`の前に以下のマークアップを追加する。
```
<thead>
<tr>
<th>日付</th>
<th>人数</th> or <th>件数</th>
</tr>
</thead>
```

### 検査実施件数, 都営地下鉄の利用者数の推移, 都庁来庁者数の推移, 新宿区エリアの来訪者推移（参考値）, 千代田区エリアの来訪者推移（参考値）
列見出しはあるが不完全な部分があったり、ノイズがあったりするので、以下のように調整する。

- 1つ目の列見出しにラベルが入っていない＆ソートに関するラベルが入っているため、`aria-label=": Not sorted. Activate to sort ascending."` を `aria-label="日付"`とする
- その他の列見出しの`aria-label`から、すべて`: Not sorted. Activate to sort ascending.`を削除する

参考：このソートの状態を表すテキストは本来不要であり、thにaria-sort属性により状態が明示され、かつth内のラベルがbutton要素になっていればそれでソートボタンのインタラクションを表現できる。下記URLのExample 2: Sortable Data Grid With Editable Cellsを参照。
https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html

## 動作環境・ブラウザ / Environment
すべて

**Comment by hogesuke** [comment]
このissueやりたいです
