### ISSUE TITLE
各種グラフの月表示が常に日本語になっている

### ISSUE THREAD

**Issue by biga816** [tokyo-metropolitan-gov/covid19#2059]
## 起こっている問題 / The Problem
- 言語を切り替えても下記グラフにて月の表示が日本語になっている。
  - 「陽性患者数」
  - 「検査実施人数」
  - 「検査実施件数」
  - 「新型コロナコールセンター相談件数」
  - 「新型コロナ受診相談窓口相談件数」

## スクリーンショット / Screenshot
<img width="1435" alt="Latest_updates_on_COVID-19_in_Tokyo___東京都_新型コロナウイルス感染症対策サイト" src="https://user-images.githubusercontent.com/10794545/77238011-36a0b600-6c10-11ea-8d0f-23a521c1d1b6.png">

## 期待する見せ方・挙動 / Expected Behavior
- 各言語に対応する(日本語であれば「2月」、英語であれば    - February)

## 起こっている問題の再現手段 / Steps to Reproduce
1. 言語を切り替える

## 動作環境・ブラウザ / Environment
- 依存なし

**Comment by teikan** [comment]
#2052 のduplicateですね

**Comment by MaySoMusician** [comment]
duplicate of #2052
