### ISSUE TITLE
スクリーンリーダー向け隠しtableのtabindexをはずす

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#2066]
## 改善詳細 / Details of Improvement
- #1443 にてサイトトップの各グラフに隠しtableが実装されました。
- #2019 にてキーボード操作用に `tabindex` が実装されました。
- このissueでは、こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/2019#issuecomment-602036969 の提案により、隠しtableからは `tabindex` をはずしたいです。

## 期待する見せ方・挙動 / Expected behavior
- 見えているグラフ・表だけフォーカスがあたる（ `tabindex` 指定）状態になる

**Comment by shunito** [comment]
こちら了解です。
ちょっと勘違いで先走った対応しちゃいましたね、すいません。
ちょっと外出中ですが、夕方には。

**Comment by shunito** [comment]
こちら対応しました。
v-data-tableのソートをキーボードで操作できるように検討していたのですが、かなり時間かかりそうだったので、テーブル見出しのtabindexもあわせて外しています。
