### ISSUE TITLE
[i18n] dev-i18n廃止以後にja.jsonに追加された翻訳キーがTransifexに登録されていない

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#2067]
## 起こっている問題 / The Problem
- `dev-i18n` 廃止以後に `ja.json` に追加された翻訳キーがTransifexに登録されていない
  - `多言語対応選択メニュー` (#2029)
  - `test` (#2056)

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/42484226/77239167-c2b7db00-6c1a-11ea-9a49-1f117db8cfbc.png)

## 期待する見せ方・挙動 / Expected Behavior
- `ja.json` に追加した翻訳キーがTransifexに登録される

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://www.transifex.com/stopcovid19-tokyo/stopcovid19tokyo/translate/ を開く
2. `dev-i18n` 廃止以後に追加された翻訳キーを検索する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
ありがとうございます。設定確認してみます。

**Comment by halsk** [comment]
うーん。設定は合っているように見えるのですが、なぜか Transifex 側に変更が認識されません。
一旦手動で更新しておきました

**Comment by huideyeren** [comment]
<img width="562" alt="スクリーンショット 2020-03-23 19 58 07" src="https://user-images.githubusercontent.com/1094632/77309866-b4fc7580-6d40-11ea-93f0-1307952768c6.png">

とりあえず、見当違いだったら申し訳ないのですが……。
追跡しているブランチが `dev-i18n` ブランチのままになっているってことはありませんか？

**Comment by halsk** [comment]
あー多分これですね。後からブランチ変えてもリソースは変わらないのか

**Comment by halsk** [comment]
設定を修正したら、(development) というリソースが追加されました！
