### ISSUE TITLE
スクリーンリーダー向け隠しtableと通常時のグラフを表示切り替えできるようにしたい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#2068]
## 改善詳細 / Details of Improvement
- #1443 にてサイトトップの各グラフに隠しtableが実装されました。
- これらの隠しtableは、通常時（javascript有効）は `top: '-9999px'` で画面外にとばしています。
- こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/2019#issuecomment-602041498 の指摘より、`top: '-9999px'` で画面外にとばすのではなく、通常時グラフと隠しtableの表示切り替えを実装したいです。
- UIの実装になると思いますので、まずはご提案いただく形ですすめたいと思います。

## 期待する見せ方・挙動 / Expected behavior
- noscript時には隠しtableが表示される
- 通常時（javascript有効）ではグラフと隠しtableの表示が切り替えられるようになっている
- **UIについては要検討**

**Comment by shgtkshruch** [comment]
陽性患者数や検査実施件数などのグラフは日別・累計を切り替えるボタンがあるので、このラインにグラフ・テーブルの表示切り替えを持ってくると、コントロール系の UI がまとめられそうだと思いました。

![スクリーンショット 2020-03-25 23 30 00](https://user-images.githubusercontent.com/5207601/77547531-a94fb100-6ef0-11ea-8abd-5e188436accb.png)

試しにボタンを置いて動作を見てみました。
テーブル表示の際にもグラフと同じように日別・累計の切り替えをする場合は、このボタンの位置は変えないほうがいいかなと思いました。

[![Image from Gyazo](https://i.gyazo.com/5023643d9f09fc22b229d63738e1e0f8.gif)](https://gyazo.com/5023643d9f09fc22b229d63738e1e0f8)

**Comment by kaizumaki** [comment]
@shgtkshruch ご提案ありがとうございます！ビジュアル貼っていただき助かります！
なるほど、これだと https://github.com/tokyo-metropolitan-gov/covid19/pull/2019#issuecomment-602041498 の要件は見たしそうですね。

あとは、この実装で、通常時も隠しtableにアクセスできるようになるわけですが（まあそういうissueなんですが 😅 ）、データの見せ方としてこの実装でいいかどうか、 @ocean3fish さん、ご意見ください！

**Comment by magi1125** [comment]
@shgtkshruch ご提案ありがとうございます。現在のデザインを大きく変えずに行くならこれが最善手に近いと感じました。
追加頂いたボタンのインタラクションですが、いわゆる[フリップフロップ問題](https://www.sociomedia.co.jp/9502)の懸念が若干あるので、「日別 | 累計」に合わせて「グラフ | 一覧」として頂くとよりよいかと思いました。ご検討ください。

なお、実装的には、グラフ表示がデフォルトになると思うので、こちら側の表示になっている際にはグラフエリアには今までと同様の隠しtableを入れておくことになるかなと思います。
あるいは「スクリーンリーダーをご利用の場合は一覧表示に切り替えてください」と書くか、ですね。これは運用面でのメリットがある一方、操作が増えるのでスクリーンリーダーユーザーのユーザビリティは下がります。同一ソースから生成するなら運用漏れも起きにくそうなので、見えない方と見える方で両方tableを提供してもいいような気がしました。

**Comment by shunito** [comment]
![画面外に飛ばしているテーブルをそのままグラフと両方表示](https://user-images.githubusercontent.com/32133/77650677-2e999b00-6faf-11ea-8dd8-88b99cdf6a00.png)

参考までに、現在 ```top: -9999px;``` で画面外に飛ばしているテーブルをそのまま表示したパターンです。
画面表示領域が非常に広くなりますが、一案として。

**Comment by magi1125** [comment]
@shunito ありがとうございます。私はこれアリ派です。GoogleAnalyticsとかで見慣れてるっていうのもありそうですが。これだと隠しtableと表示するものを重複させずに、片方だけでよくなりますね。

**Comment by ocean3fish** [comment]
@kaizumaki @shgtkshruch @shunito @magi1125 ご検討ありがとうございます。
グラフ下部にアコーディオンで表示するという方法はいかがでしょうか？

また、テーブルは日別/累計の切替をする必要はなく、複数列で表示できれば良いのではないかと考えております。

## 初期表示
<img width="576" alt="スクリーンショット 2020-03-27 1 43 52" src="https://user-images.githubusercontent.com/4206675/77675250-0a9a8180-6fd0-11ea-9971-718d43130355.png">

## 「▶︎ テーブルを表示」クリック後
<img width="579" alt="スクリーンショット 2020-03-27 1 45 46" src="https://user-images.githubusercontent.com/4206675/77675357-30278b00-6fd0-11ea-80b5-28dbc313f949.png">

**Comment by ocean3fish** [comment]
なお、積み上げ棒グラフの「検査実施件数」の場合は以下のようなテーブルが良いかと考えておりますが、いかがでしょうか。

<img width="532" alt="スクリーンショット 2020-03-27 2 23 00" src="https://user-images.githubusercontent.com/4206675/77676776-21da6e80-6fd2-11ea-9d71-88f97eb90e05.png">

**Comment by kaizumaki** [comment]
みなさまご提案ありがとうございます！
たしかに、グラフとtableは隣接して表示させたほうが、データの提示として誤解が発生しにくい良い手だと思いました。そしてデフォルトではtableは折り畳まれている状態がいいですね。
それとtableにおいて、「日別」と「累計」の切り替えがかえってわかりにくくなっている点は私も気になっていました。これについては、tableでは「日別」「累計」を切り替えせず両方を表示させることで解決しそうです。
@shgtkshruch さん、実装を試していただいてもいいですか？

**Comment by shgtkshruch** [comment]
@kaizumaki 

承知しました！
いただいた案で実装してみます :)

WIP で作成して変更点があれば随時取り込んでいければと思います。

**Comment by magi1125** [comment]
@ocean3fish @shgtkshruch @kaizumaki ありがとうございます。私も #1091 でもともとアコーディオンが良さそうと考えていたので、いいと思います!
「テーブルを表示」のUIもシンプルでよさそうです。グラフが見にくい人もこれを使うので、現状よりももう少し主張を強めて、コントラストはハッキリしているとよさそうだなと思いました。
あとはラベルとして、テーブルがいいか、一覧がいいか、表がいいか…とかでしょうか。アクションを含まずに「▶ 一覧表」でいいのかも。

**Comment by ocean3fish** [comment]
@magi1125 ありがとうございます！
テキスト表示は迷ったのですが、ある程度文字数を使った方がより視認性が高くなるだろうという目論見で「▶︎テーブルを表示」としました。
また、操作によって何が起こるのかユーザにクリアに伝えられる方が良いかと思い、アクション表現を含めています。
「表」「一覧表」の方がわかりやすいかもしれないと私も思ったのですが、上述の理由でアクションを含めようと思った時に「一覧表を表示」だと漢字の重複があり微妙かと思いまして。

あとは、運営側の方々の意見も聞いた上でテキスト表現は調整できればと思っています。

**Comment by magi1125** [comment]
@ocean3fish アクションラベルの意図了解です！「テーブル」という表現はウェブの人寄りで、世間的にはテーブルといえば机で、表をイメージされにくい気がするので、ここは何か別の言い回しがあるといいなと思ってます（そうすると一覧か表か一覧表になる…）。
アクション側を変えて「一覧表を開く」とかもありかも？
いずれにせよ後ほど調整で大丈夫です！

**Comment by forestgtree** [comment]
テーブル表示について、表示方法や振る舞いなど
細かくご意見いただき、ありがとうございます！🙇‍♂️

アコーディオンでの表示切り替えで、是非実装していただきたいです！

ただ、一般ユーザーには、できるだけ簡潔に情報をお伝えしたいので…
弱視の方向けに、モード切り替えを行った場合にのみ
今回実装していただいたナビゲーションを出現させたら良いのではないかと
考えているのですが、これはまた別のissueで検討したいです！

**Comment by shunito** [comment]
表示について二点ほど提案です。

- 公表日、日付は最新が上として日付順で並ぶのが良いかと思います。（データ作ってるところで `.reverse()` するだけなので対応としても簡単かと）
- 件数の数字は右揃えが良いと思います（これはすでにデザイン案に反映されていますね）

**Comment by ocean3fish** [comment]
ご参考までに、日付のソート順に関してはこれまでにも色んな意見が出ていました。
ソート順の切替機能が実装されているので対応しなくても良いのでは、ということでissueがクローズとなったこともありました。
#275 #582

もしテーブルで降順をデフォルトとする場合、陽性患者属性のテーブルも併せて変更するのが良さそうです。

**Comment by kaizumaki** [comment]
隠しtableについては #2132 でソートできないようにしているので、改めて検討したほうがよさそうです。

**Comment by magi1125** [comment]
@forestgtree 
すいません、別Issueでと思いつつ、いったんお返事を。

> 弱視の方向けに、モード切り替えを行った場合にのみ今回実装していただいたナビゲーションを出現させたら良いのではないか

これは（どういうUIになるかは別として）、通常表示→弱視モードに切り替え→テーブルを表示を押す→表が表示される、的な挙動のイメージでしょうか？違ってたらすいません。

表設置の目的をどこに置くかで考え方は変わってきそうだなと思うので、いったん私の考えとして。
私はこの表自体はグラフを普通に読める人にとっても有用（表のほうが見やすい人もいる、数字をコピーしたりできるなど）なので、特定のモードに入れるよりも、誰でもアクセスしやすい状態が望ましいと考えています。なので、現状の提案のようにグラフの下に「認知もできるが、要らなければほっとける」ぐらいの感じでリンクを置いておくのが良さそうだなと感じていますが、いかがでしょう。

**Comment by forestgtree** [comment]
@magi1125 
ご意見、ありがとうございます！

一般ユーザーにとってもtableの情報が有用という部分を失念しておりました
大変失礼いたしました！

弱視の方には、アコーディオンを開く操作をショートカットしていただき
常に全てのカードのteble要素を全開でお見せする。（操作不要）

一般ユーザーには、各々にお任せする形で
現状のアコーディオン表示を採用というのは、いかがでしょうか？

**Comment by shgtkshruch** [comment]
#2447 で以下の要件を取り込んで WIP で実装いたしました。

- 隠しテーブルがあったグラフ下部にアコーディオンでテーブルを設置
- アコーディオン開閉のラベルは「▶︎テーブルを表示」
- テーブルのカラムはデータ種別 と 日別・累計の組み合わせ
- JavaScript 無効時はアコーディオンを開いた状態で表示
- 件数の数字は右揃え

ソートについてはもう少し検討が必要そうなので、一旦現状の実装から変えずに日付の昇順にしています。

弱視の方向けのアコーディオンについては、それを判定するモードが無い?と思うので、今の段階では対応できていません（違ってたらすみません）
それを判定する方法があれば実装できそうですが、スコープが広がりそうなので別の issue のほうがいいかもしれないと思いました。

![スクリーンショット 2020-03-28 1 16 32](https://user-images.githubusercontent.com/5207601/77778532-79d9a980-7094-11ea-8293-1dde1046b7e6.png)
![スクリーンショット 2020-03-28 1 16 40](https://user-images.githubusercontent.com/5207601/77778540-7c3c0380-7094-11ea-99b9-a83b97cfb09c.png)

**Comment by kaizumaki** [comment]
@shgtkshruch 方向性はいい感じです！ありがとうございます！細かい提案はPR #2447 のほうでコメントしますね。

モード切り替えについては、#2364 で議論が進んでいるカラーチャートの実装も合わせて、検討する意義があるのではないかと思っています。もちろんそれは別issueで。

**Comment by ocean3fish** [comment]
メモ： https://github.com/tokyo-metropolitan-gov/covid19/pull/2498 のマージ待ちの状態。
