### ISSUE TITLE
Safariで各種グラフの月ラベルが表示されない

### ISSUE THREAD

**Issue by mu373** [tokyo-metropolitan-gov/covid19#2076]
## 起こっている問題 / The Problem
- Safari（iPhone/iPadなどのMobile Safari含む）閲覧時に各種グラフの月ラベルが表示されない
- どの言語設定でも再現された

## スクリーンショット / Screenshot
Safari（Mac）閲覧時
![image](https://user-images.githubusercontent.com/2176670/77245466-20234a80-6c62-11ea-8a5c-d1482e3ea833.png)

Safari（Mac）閲覧時のコンソール
![image](https://user-images.githubusercontent.com/2176670/77245430-e5211700-6c61-11ea-881a-c03103a49b08.png)

参考：Google Chrome閲覧時（通常）
![image](https://user-images.githubusercontent.com/2176670/77245425-ddfa0900-6c61-11ea-877c-cf5378548299.png)

## 期待する見せ方・挙動 / Expected Behavior
- その他のブラウザでの閲覧時と同様、月ラベルが表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. Safariで閲覧する

## 動作環境・ブラウザ / Environment
- macOS / iOS
- Safari

**Comment by tomopict** [comment]
#2052 #2054 #1966 あたりで議論されている内容で影響が出そうですね

**Comment by shgtkshruch** [comment]
Mac, iPhone, iPad で月ラベルが表示されるようになりましたので、こちらの issue は解決済みかと思います :)

![スクリーンショット 2020-03-28 13 54 18](https://user-images.githubusercontent.com/5207601/77815184-c0162380-70fb-11ea-8d60-571addb45cc7.png)

![スクリーンショット 2020-03-28 13 56 07](https://user-images.githubusercontent.com/5207601/77815199-e4720000-70fb-11ea-9a99-6c621172df6b.png)

**Comment by kaizumaki** [comment]
@shgtkshruch ご確認ありがとうございます！ではこちらのissueはクローズしますね。
