### ISSUE TITLE
chart.jsが依存しているmoment.jsをday.jsに置き換える

### ISSUE THREAD

**Issue by t-tajiri** [tokyo-metropolitan-gov/covid19#2079]
## 改善詳細 / Details of Improvement

- https://github.com/tokyo-metropolitan-gov/covid19/issues/486 にてday.jsに移行したが、`yarn build --analyze`にて解析結果を確認すると、moment.jsが存在している。
  - chart.jsはデフォルトでmoment.jsに依存しているので、これが原因だと考えられる。

- 一案として、大まかに次の手順でmoment.jsからday.jsに移行する (他にアイデアがあればぜひ 😄 )
  1. day.jsを利用するようにcustom adapterを作成し、デフォルトで使用している`chartjs-adapter-moment` を上書きする。
  1. webpackのexternalsオプションにmoment.jsを追加する

## スクリーンショット / Screenshot

- 改善前の解析結果
<img width="1673" alt="before" src="https://user-images.githubusercontent.com/40433305/77246178-0422a780-6c68-11ea-81ca-187bf09cb8bd.png">

## 期待する見せ方・挙動 / Expected behavior
1. `yarn build --analyze`にて解析結果を確認したときに、moment.jsが存在しないこと
<img width="1672" alt="after" src="https://user-images.githubusercontent.com/40433305/77246182-0d137900-6c68-11ea-823c-fd42e292168d.png">

1. 修正前のチャートの表示と相違がないこと

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by t-tajiri** [comment]
作業します！

**Comment by t-tajiri** [comment]
下のissueに影響しますね。。。
> https://github.com/tokyo-metropolitan-gov/covid19/issues/2052 Month displayed in Japanese on graph x-axis on all language
> https://github.com/tokyo-metropolitan-gov/covid19/issues/1966 実行時に、Deprecation warning(value provided is not in a recognized RFC2822 or ISO format)が発生する

**Comment by MaySoMusician** [comment]
#2054 でグラフX軸部分については `moment` `dayjs` ともに使用しない案が提案されました
いずれにせよ `chart.js` 内の `moment.js` は使用せずに済むかなと思います

**Comment by t-tajiri** [comment]
@MaySoMusician 
https://github.com/tokyo-metropolitan-gov/covid19/pull/2054 の修正は`moment.js`に渡すためのデータの形式を`M月`からnativeの`Date`に変更してるように見えますね。。。

**Comment by MaySoMusician** [comment]
このプロジェクトで使われてる`chart.js`は（少なくともNode.js v10.19.0だと）`v2.9.3`で、またadapterの分離が終わってないみたいですね
これって上書きできるのだろうか...

**Comment by t-tajiri** [comment]
@MaySoMusician 
ちょうど今完成したので、表示に問題ないか確認中です。
問題なければPR出しますね。

**Comment by t-tajiri** [comment]
ちなみに、上書きする方法はdate-fnsのadapterを参考にしました。
https://github.com/chartjs/chartjs-adapter-date-fns/blob/master/src/index.js

**Comment by t-tajiri** [comment]
ざっと1割~2割削減ってところですね。
開発環境で確認しているのか原因はわかっていませんが、若干レンダリングが遅いのが気になります。
