### ISSUE TITLE
サイドバークリック時の下線

### ISSUE THREAD

**Issue by asuchi0819** [tokyo-metropolitan-gov/covid19#2083]
## 起こっている問題 / The Problem
- サイドバーをクリックすると「当サイトについて」と「お問い合わせ先一覧」の間には線が出てくる。

## スクリーンショット / Screenshot

![3D515B9F-5B52-495B-899C-F87FEE41DDD7](https://user-images.githubusercontent.com/45027336/77255156-c72ad500-6ca8-11ea-8909-49c84886c653.jpeg)

## 期待する見せ方・挙動 / Expected Behavior
- これらの波線をなくす

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイドバーのクリック（サイト外リンクの場合は再現しません

## 動作環境・ブラウザ / Environment
- iPad 6th / iPadOS 13.3 Safari

もし、他のと被ってたらすみません。

**Comment by asuchi0819** [comment]
補足で、本番環境でも同様の症状が出ています。

**Comment by macropygia** [comment]
着手します。
