### ISSUE TITLE
新型コロナ受診相談窓口相談件数あたりの検査実施人数の割合(%)のグラフを追加したい

### ISSUE THREAD

**Issue by applideveloper** [tokyo-metropolitan-gov/covid19#2092]
## 改善詳細 / Details of Improvement
- 新型コロナ受診相談窓口相談件数あたりの検査実施人数の割合(%)のグラフを追加したい

## スクリーンショット / Screenshot

<img width="531" alt="スクリーンショット 2020-03-23 18 17 21" src="https://user-images.githubusercontent.com/1066618/77301189-9d1df500-6d32-11ea-96d3-c094097d07b0.png">

## 期待する見せ方・挙動 / Expected behavior

- 新型コロナ受診相談窓口相談件数あたりの検査実施人数の割合(%)が棒グラフで表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@applideveloper ご提案ありがとうございます。こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/2106#issuecomment-627816704 にコメントいたしました。都に確認し、採用は難しいという結論になりました。ご理解いただければと思います。

**Comment by kaizumaki** [comment]
#2106 と同様、こちらのissueもクローズさせていただきたく思います。
