### ISSUE TITLE
最新のお知らせの並びについて

### ISSUE THREAD

**Issue by totoro721** [tokyo-metropolitan-gov/covid19#2093]
## 改善詳細 / Details of Improvement
- 最新のお知らせの並びを日付の降順(新しいお知らせを上)にする
- 掲載3日くらいまでの新しいお知らせは太文字にして目立たせる

## 期待する見せ方・挙動 / Expected behavior
- 最新のお知らせの並びを日付の降順(新しいお知らせを上)にする
- 掲載3日くらいまでの新しいお知らせは太文字にして目立たせる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by totoro721** [comment]
多言語対応選択メニューを English にしても、お知らせの内容が日本語

**Comment by furandon-pig** [comment]
提案と調査ありがとうございます。こちら着手してみます。

**Comment by kaizumaki** [comment]
こちら `waiting` ラベルをつけさせていただきました。関係各所の確認が必要ですので、いましばらくお待ちいただけますようお願い申し上げます。

**Comment by furandon-pig** [comment]
承知しました。いったん着手はペンディングします。
`waitng` ラベルが外されたら着手OKという認識で良いでしょうか？

**Comment by kaizumaki** [comment]
@furandon-pig はい。そのときはラベルのつけかえとともにコメントいたします。
ちなみに、未翻訳の部分についてはTransifexをご確認ください。翻訳作業はとりかかっていただいて大丈夫です。

**Comment by furandon-pig** [comment]
@kaizumaki 確認ありがとうございます。翻訳作業の方、(Transifexがよく分かっていなので)まずは自分にできそうか調べてみます。

**Comment by totoro721** [comment]
@kaizumaki 色々勉強させていただいております。Transifex について私も確認します。

**Comment by mikkame** [comment]
現在の仕様ですが
元データの並び順の通り表示するように、という仕様です。
並び順については運用にて調整できるようにするという意図を込めて、ソート機能がありません。

**Comment by furandon-pig** [comment]
@mikkame 確認ありがとうございます。現在の仕様とその意図について理解しました。
対応としては現状のままとする(ソート機能は実装しない)という認識で合っていますか？

**Comment by NaoyaShimizzz** [comment]
ご検討いただきありがとうございます。
庁内で確認いたしましたが、お伝えしたい「最新のお知らせ」の順番について、
必ずしも発表日順とは限らないため、現状の仕様のままでお願いいたします。

**Comment by halsk** [comment]
正式に回答があったので、クローズさせていただきます。ご協力ありがとうございました。

**Comment by totoro721** [comment]
@halsk 対応ありがとうございました。
