### ISSUE TITLE
検査実施件数のグラフについて、多言語対応選択メニューで English を選択しても一部に日本語が残る

### ISSUE THREAD

**Issue by totoro721** [tokyo-metropolitan-gov/covid19#2095]
## 起こっている問題 / The Problem
- 多言語対応選択メニューで English を選択してもグラフの一部に日本語が残る

## スクリーンショット / Screenshot
<img width="376" alt="コメント 2020-03-23 113602" src="https://user-images.githubusercontent.com/2782936/77275839-9d9b9900-6cfc-11ea-8d6a-faa8aa6720e9.png">

## 期待する見せ方・挙動 / Expected Behavior
- 全て選択された言語で表記する

## 起こっている問題の再現手段 / Steps to Reproduce
1. 多言語対応選択メニュー > English を選択
2. 検査実施件数を表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by huideyeren** [comment]
着手します。

**Comment by huideyeren** [comment]
ひとまずですが、 `TesterNumberCard.vue` の検査数の注釈（14行目〜18行目）とグラフの凡例（38行目〜41行目）は訳を当てるJSONにキーがないようです。
訳し忘れという可能性があります。

なお、 `TimeStackedBarChart.vue` の2行目についてはキーがありますが、うまく翻訳があたっていない状態です。

続きは18:30以降に着手できそうです。

**Comment by huideyeren** [comment]
訂正します。
`TimeStackedBarChart.vue` にある「（注）同一の対象者について複数の検体を検査する場合あり」についても `en.json` にキーがありません。

キーを追加することが必要かと思われます。

**Comment by kaizumaki** [comment]
@huideyeren 翻訳作業はTransifexに移行していますので、こちら #1509 を参照いただいて、Transifexのほうをご確認いただけると幸いです。

**Comment by huideyeren** [comment]
@kaizumaki ありがとうございます。Transifexのほうも見てみます。

**Comment by huideyeren** [comment]
Transifexを見たのですが、developmentブランチの `ja.json` にある原文がTransifexになく、翻訳ができない状態です。
どうすれば原文をTransifexに追加することができますか？

**Comment by kaizumaki** [comment]
`ja.json` にはあるのですね。タイミングの問題で、まだTransifexに反映されてないのかもしれません。また、 #2067 という報告もあがっています。よければ、何のキーが反映されていないか教えてもらえると助かります！

**Comment by huideyeren** [comment]
翻訳キーは以下の通りになります。

`components/TimeStackedBarChart.vue`

- （注）同一の対象者について複数の検体を検査する場合あり

`components/cards/TestedNumberCard.vue`

- 都内発生（※1）
- その他（※2）
- ※1: 疑い例・接触者調査
- ※2: チャーター便・クルーズ船

この計5つです。

**Comment by kaizumaki** [comment]
ありがとうございます！なるほど、どちらも昨日午前（3月22日11:31、11:32）に `development` ブランチにマージされてますね。たしかにTransifexの反映が遅いですね。ちょっと調査します。

**Comment by halsk** [comment]
なぜか Transifex から自動で取り込まれなくなってしまっていますね。取り急ぎでアップロードしました。

**Comment by halsk** [comment]
取り込まれない問題については解決しました。

**Comment by huideyeren** [comment]
とりあえず翻訳もやってみました。
取り込まれれば問題はなさそうです。

**Comment by huideyeren** [comment]
https://i18n-covid-tokyo.netlify.com/ を見ました。
いつの間に凡例と注釈がまとまっていましたが、私の環境だと凡例が見切れています。

<img width="513" alt="スクリーンショット 2020-03-24 08 07 44" src="https://user-images.githubusercontent.com/1094632/77371713-53232680-6da7-11ea-9045-18916d152e82.png">

なお、私の環境は以下の通りです。

- MacBook Pro (Retina, 13-inch, Early 2015)
- Google Chrome 80.0.3987.149（Official Build） （64 ビット）
- ディスプレイサイズは内蔵Retinaディスプレイのデフォルト

**Comment by huideyeren** [comment]
おそらく、一つにまとめてしまうと前のコメントのように長くなって見切れてしまうので、凡例と注釈は分けた方がよい気がしますが、どうでしょう？

**Comment by kaizumaki** [comment]
https://dev-covid19-tokyo.netlify.com/
こちらを最新として見ていただいたほうがよいかと思います。件については未翻訳という理解です。

**Comment by huideyeren** [comment]
ありがとうございます。今回の翻訳キーはTransifexでレビュー待ちになっている状態です。
レビューが通れば https://dev-covid19-tokyo.netlify.com/ に反映されるのでしょうか？
それとも、ブランチの変更でしなければならない作業とかありますか？

**Comment by huideyeren** [comment]
続きがあればお昼に担当します。

**Comment by huideyeren** [comment]
<img width="511" alt="スクリーンショット 2020-03-24 12 12 06" src="https://user-images.githubusercontent.com/1094632/77384460-c4270600-6dc8-11ea-9b1e-64af1613ffeb.png">

英語の訳文が `development` ブランチに反映されていることを確認しました。
レビューお願いします。

**Comment by halsk** [comment]
こちら、解決済みということでクローズしてもよろしいでしょうか？ご協力ありがとうございました！

**Comment by huideyeren** [comment]
@halsk 解決済みなのでクローズしても大丈夫かと思われます。
ありがとうございます。

**Comment by totoro721** [comment]
@halsk ありがとうございました！
