### ISSUE TITLE
[i18n]埋め込み用コードのボタンに付与したaria-labelを翻訳する

### ISSUE THREAD

**Issue by shunito** [tokyo-metropolitan-gov/covid19#2105]
## 起こっている問題 / The Problem
- DataView.vueに追加したaria-labelについて、すべて日本語で表示・読み上げされる。
- 翻訳キーも未登録。

## スクリーンショット / Screenshot
![英語ページの埋め込みコードのボタン、aria-labelが日本語](https://user-images.githubusercontent.com/32133/77297409-8eccda80-6d2c-11ea-835c-8870d8ec98a3.png)

## 期待する見せ方・挙動 / Expected Behavior
- ボタンのaria-labelを翻訳し、各言語で正しく読み上げされる。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 日本語以外の言語に切り替え、埋め込み用コードのボタンをクリックする。
2. ボタンにフォーカスをあてる、スクリーンリーダーで読み上げる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shunito** [comment]
おそらく```good first issue``` かと思います。

**Comment by huideyeren** [comment]
夕方（18:30以降）着手開始でよければ着手します。

**Comment by huideyeren** [comment]
着手します。

**Comment by huideyeren** [comment]
あとは訳が入力されたら各言語で確認します。
お恥ずかしながら英語すら得意でないのでどうしたらよいものか困ってしまいますが。

**Comment by shunito** [comment]
いま確認したところ、各言語翻訳終わってるようです。
翻訳レビューは別途だと思うので、本対応は終了でよいかと思います。
ありがとうございました。
