### ISSUE TITLE
（PC版）「新型コロナウイルス感染症にかかる相談窓口について」の表現がわかりにくい

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#2113]
## 起こっている問題 / The Problem
- 「発症前2週間以内の出来ごとと症状」に関し，PC版での表示内容がわかりにくい．
    - SP版を参照する限り，感染者との濃厚接触者については「発熱または呼吸器症状」，流行地域に滞在した本人およびその濃厚接触者については「呼吸器症状かつ発熱37.5℃以上」の場合に窓口への相談を求めるのだと思われるが，PC版の表示はそれをデザイン上明確に示せていないと感じる．（「呼吸器症状」が左右どちらにもかかるというのが作成者の意図と推察するが…）
    - 「発熱または呼吸器症状かつ発熱37.5℃以上」という，「Aまたは「BかつC」」とも「「AまたはB」かつC」とも取れる文章にも読める．
        - 一般に「Aまたは「BかつC」」と「「AまたはB」かつC」は論理的に意味が異なるので，なおさら正確な意味が汲み取りづらい
- 伝えるべき情報の重要性を考えると，このような曖昧な表現は排除すべきであり，SP版と同様の表示が望ましいと考える．

### PC 版
<img width="793" alt="スクリーンショット 2020-03-23 20 36 19" src="https://user-images.githubusercontent.com/23148331/77312791-022f1600-6d46-11ea-9f78-fa2f52f56cd1.png">

### SP 版
<img width="344" alt="スクリーンショット 2020-03-23 20 35 47" src="https://user-images.githubusercontent.com/23148331/77312779-fe9b8f00-6d45-11ea-9f32-c38c89a133ba.png">

## 期待する見せ方・挙動 / Expected Behavior
- SP版と同様に，感染者との濃厚接触者については「発熱または呼吸器症状」，流行地域に滞在した本人およびその濃厚接触者については「呼吸器症状かつ発熱37.5℃以上」の場合に窓口への相談を求めるということが明確になるようデザインを変更する．

**Comment by nard-tech** [comment]
cf. #556

**Comment by kaizumaki** [comment]
flowについては #3315 で全面改修を行いました。こちらのissueは前バージョンについてのものとなりますので、クローズさせていただきます。
