### ISSUE TITLE
新宿区&千代田区の来訪者推移グラフの横軸の日付範囲を平日のみにする

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#2114]
## 改善詳細 / Details of Improvement
- 現行の実装では、横軸の日付範囲が休日を含んだ範囲になっています
例）2/10〜2/16

- この部分を土日を含まない範囲で表示するように変更したいとの要望が来ました
例）2/10〜2/14

- 対象
1. 新宿区の来訪者推移（棒グラフ：開発環境のみで公開中）
2. 千代田区の来訪者推移（棒グラフ：開発環境のみで公開中）

## Before
<img width="582" alt="スクリーンショット 2020-03-23 20 33 56" src="https://user-images.githubusercontent.com/4206675/77314065-50ddaf80-6d48-11ea-8cb2-2dd549734b26.png">

## After
<img width="582" alt="screenshot_shinjuku_visitors" src="https://user-images.githubusercontent.com/4206675/77314073-55a26380-6d48-11ea-9bc5-f9c5632ee39b.png">

**Comment by shgtkshruch** [comment]
こちら対応いたします。

日付の範囲ですが、平日のみですと以下のようになると思いますが、いかがでしょうか？
- 2/10 ~ 2/14
- 2/17~2/21
- 2/25 ~ 2/28（2/24は祝日なので除外）
- 3/2 ~ 3/6
- 3/9 ~ 3/13

**Comment by halsk** [comment]
祝日をうまく反映できればそれはベストですが、最悪月〜金でも大丈夫とのことです。

**Comment by shgtkshruch** [comment]
承知しました！
祝日を反映するのは `holiday` フラグを利用すればできると思うので、その方向で実装してみます。
