### ISSUE TITLE
dev-i18nブランチの廃止がドキュメントに反映されてない

### ISSUE THREAD

**Issue by sorairolake** [tokyo-metropolitan-gov/covid19#2127]
## 起こっている問題 / The Problem
`dev-i18n`ブランチは廃止されたが、`README.md`及び`TRANSLATION.md`にこれが反映されていない。

## 期待する見せ方・挙動 / Expected Behavior
これらのドキュメントを更新し、`dev-i18n`ブランチの廃止を反映する。

**Comment by usk81** [comment]
確認します。
