### ISSUE TITLE
サイト名変更

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#213]
左上の
新型コロナウイルス感染症対策本部→新型コロナウイルス対策サイトに戻す
あわせて、サイトタイトルも（<TITLE>属性の部分）
（すみません。以前の私の指示が間違ってました。）

**Comment by mikkame** [comment]
すみません！
勢い余ってマージしてしまった件です。

`公式` の表記に関してはどうでしょうか

**Comment by halsk** [comment]
公式
も戻しましょう
