### ISSUE TITLE
都営地下鉄の利用者数の推移の3月6日、13日、19日

### ISSUE THREAD

**Issue by dg4101** [tokyo-metropolitan-gov/covid19#2135]
## 改善詳細 / Details of Improvement
- 都営地下鉄の利用者数の推移のグラフで3月6日、13日、19が抜けているように見えます。３日とも平日の木・金曜日ですので、提供されているオリジナルのデータに含まれているのでしたら、表示されるべきかと思います。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/1219688/77367175-e2a1e880-6d59-11ea-8915-951bd0c43e30.png)

**Comment by NaoyaShimizzz** [comment]
ご指摘ありがとうございます。修正予定ですので今しばらくお待ちください。

**Comment by dg4101** [comment]
#2169 
修正されたようですので、クローズしておきます。
