### ISSUE TITLE
多言語対応選択メニュークリック時の破線

### ISSUE THREAD

**Issue by yuuton414** [tokyo-metropolitan-gov/covid19#2137]
## 起こっている問題 / The Problem
サイドメニューの「多言語対応選択メニュー」をクリックすると破線が現れる。
他言語を選択するとスクロールできる幅が変わるため発生してるように思います。
#2083 と似た現象

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/59001145/77375370-a188f300-6db0-11ea-8787-f1aeedd87fc1.png)

## 期待する見せ方・挙動 / Expected Behavior
- これらの破線をなくす

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイドメニューの「多言語対応選択メニュー」をクリック。
2. 他言語を選ぶ。
3. 翻訳されるとスクロールできる幅が変わっており破線が発生する。

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

OSS初参加ですが何卒。

**Comment by halsk** [comment]
解決していない、という報告があったので、リオープンしました。

**Comment by furandon-pig** [comment]
私の環境でも現象が再現することを確認できました。
以下の修正で報告されている現象が解消するようです。 `$Side.focus()` でフォーカスを当てた後(Chromeではサイドバーの上部にスクロールするため残しています)、 `$Side.blur()` でフォーカスを外すという処理になっています。
(プルリクのほうは今日の夜くらいに出すようにします)

```javascript
$ git diff ./components/SideNavigation.vue
diff --git a/components/SideNavigation.vue b/components/SideNavigation.vue
index 1c30145..dd578ca 100644
--- a/components/SideNavigation.vue
+++ b/components/SideNavigation.vue
@@ -194,6 +194,7 @@ export default Vue.extend({
         const $Side = this.$refs.Side as HTMLEmbedElement | undefined
         if ($Side) {
           $Side.focus()
+          $Side.blur()
         }
       })
     }
```

**Comment by furandon-pig** [comment]
修正方法の目途がついておりますので、本件、着手いたします。

**Comment by furandon-pig** [comment]
本件自体は [#2085](https://github.com/tokyo-metropolitan-gov/covid19/pull/2085) のプルリクで修正されたようです(お騒がせしてすみません)。

**Comment by furandon-pig** [comment]
ただ、不具合修正前後で左サイドバーのスクロールの挙動がちょっと変わっている気がします。
Windows+Chromeでのみ発生。多言語選択時に左サイドバーの一番上までスクロールする挙動が修正後はそうならなくなっているように見えます。
(本件以外にも修正が入っているはずなので、どのコミットで挙動が変わるようになったのかは現時点では不明です)

![sample](https://user-images.githubusercontent.com/772589/77430063-edbe4c80-6e1d-11ea-812a-56a10a5df0b8.gif)

**Comment by furandon-pig** [comment]
> 本件自体は #2085 のプルリクで修正されたようです(お騒がせしてすみません)。

報告されていた現象が解消していることを確認できましたので、お手数ですがこのissueを再度closeしてもらえればと思います。
(先述したスクロールまわりの挙動の件は別途issueを立てようと思います)
