### ISSUE TITLE
データをjsonからオンライン管理に変える

### ISSUE THREAD

**Issue by usk81** [tokyo-metropolitan-gov/covid19#2148]
## 改善詳細 / Details of Improvement
- covid19japanというところで、日本のcovid-19のデータをGoogle Spread Sheetで管理していました。
- covid-19に関するサイトが点在してきたので、データをオンラインサービスで管理してデータを集約・相互利用できるようにしたほうがいいと思うのですがどうでしょうか？
  - 別途Backupのためデータをgithubで管理するはありだと思います

ref)
- https://github.com/reustle/covid19japan
- https://docs.google.com/spreadsheets/d/1jfB4muWkzKTR0daklmf8D5F0Uf_IYAgcx_-Ij9McClQ/edit#gid=0

**Comment by perpouh** [comment]
SpreadSheet→GASでWebアプリケーション化→GETでjson取得にすれば読み込みはあまり変えずに済みそう？[参考](https://qiita.com/taichi0514/items/ee6dedff45f9d9e58ef4)
各種オープンデータをどうやってSpreadSheetにするかを固めたいですね。

**Comment by halsk** [comment]
本サイトのデータ自体は、今のワークフロー（東京都が更新したExcelを取り込む）から変えるのは難しいです。サイト更新単体自動化ができているので、このサイトの取り込み方式を変更することは、現状の優先順位的に難しいです。
確かにGASからデータを取ってくる処理に変えるのは難しくないですが、東京都のExcelデータをGoogle Spreadsheet に自動で反映させるスクリプトを組まねばならず、取り込み処理がかなり複雑になります。
また、他の都市のデータも入ってくる、責任範囲が明確にならない Google Spreadsheet に、東京都の公式サイトが依存するのは好ましくありません。

また、他のサイトについても似たような状況だと思います。
したがって、現実的に望ましいのは、各サイトで使っているデータをGoogle Spreadsheet に集積する形かと思います。

全てではないですが、サイトからもリンクしてあるように、いくつかのデータセットについてはオープンデータカタログからダウンロードできます。
https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000071
また、#2023 にて提案された、データセット単体を取り出すことを検討中です。

そして、東京都だけで検討しても意味がないので、こちらについては Slack の  `#stopcovid19jp` チャンネルで投げかけていただければと思いますがいかがでしょうか。

**Comment by l15n** [comment]
こんにちは

reustle/covid19japan から来ました。

こちらの管理方法ですが、現在は Google Spreadsheets で入力して、 https://github.com/reustle/covid19japan-data/ にimportしてるような流れです。

しかし、感染拡大に伴って、管理の限界が見えてきてるので、対応策を探ってる最中です。Google Spreadsheetsで全国の患者DBを統一するのはなかなか大変になってきてる段階です。

ちょっと趣旨が違うのですが、データ連携について相談がしたいところです・・・

**Comment by kaizumaki** [comment]
データについては東京都はSharePoint管理で更新フローがまわっており、こちらのissueの趣旨と外れてきている現状がありますので、一旦クローズといたします。
