### ISSUE TITLE
新型コロナウイルス対策ダッシュボードへのリンクを追加

### ISSUE THREAD

**Issue by ayasuda** [tokyo-metropolitan-gov/covid19#2153]
## 改善詳細 / Details of Improvement
- 日本国内の全国版の情報ダッシュボードへのリンクを追加する
- https://www.stopcovid19.jp/

## スクリーンショット / Screenshot

<img width="371" alt="スクリーンショット 2020-03-24 15 59 41" src="https://user-images.githubusercontent.com/219491/77397699-6d7df400-6de9-11ea-910d-48534830a245.png">

## 期待する見せ方・挙動 / Expected behavior
- サイドバーにリンクを追加し、クリックすることで上記サイトへ遷移する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
ご提案ありがとうございます！申し訳ありませんが、本公式サイトから、コミュニティサイトに直接リンクを貼ることは難しいということになっております。ご意見としてお伝えさせていただきます。
