### ISSUE TITLE
感染者の増加が明確になるよう，トップページのグラフについてデフォルトで「累計」を表示させる

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#2162]
## 改善詳細 / Details of Improvement
- 感染者の増加が明確になるよう，トップページのグラフについてデフォルトで「累計」を表示させる．
    - 現状は「日別」がデフォルト．
    - 「感染者が増えていること」を明確に伝え，見る人に正しく危機感を持ってもらうためには，「累計」をデフォルトとした方が適切ではないかと考える．

### 「累計」を表示させるときの例
![screencapture-127-0-0-1-3000-2020-03-24-18_01_09](https://user-images.githubusercontent.com/23148331/77407472-868ea100-6df9-11ea-9937-e4aa2970cc06.png)

## 期待する見せ方・挙動 / Expected behavior
- トップページのグラフについて，「日別」「累計」が選択可能な場合は，デフォルトで「累計」を表示させる．

**Comment by NaoyaShimizzz** [comment]
ご提案ありがとうございます。
庁内で確認の結果、日別の発表数・増加傾向をまずはお伝えするという観点を重視し、従来通り「日別」をデフォルトとさせていただきます。ご了承のほどよろしくお願いいたします。

**Comment by halsk** [comment]
正式に回答があったので、クローズさせていただきます。ご協力ありがとうございました。
