### ISSUE TITLE
陽性患者数のグラフに週別を追加する / Adding weekly chart to the confirmed cases

### ISSUE THREAD

**Issue by hidehiro98** [tokyo-metropolitan-gov/covid19#2170]
## 改善詳細 / Details of Improvement
- 陽性患者数のグラフに週別を追加するのはいかがでしょうか。理由としましては、日別だと変動もあり、指数関数的に伸びてきてしまったときパッとわかりにくいかと思いました。
- データがある1/24から7日ごとに計算しています。

## スクリーンショット / Screenshot
ここの日別と累計の間に入れるイメージです。
![image](https://user-images.githubusercontent.com/5709877/77419249-71bb0900-6e0b-11ea-83cc-7acedcde428d.png)

追記
ローカルで作ってみたところこんな感じです
![image](https://user-images.githubusercontent.com/5709877/77434381-1ea18000-6e24-11ea-87a0-f6b750064eec.png)

**Comment by awsiitchs** [comment]
コメント失礼します。
私も最近同じ懸念を持ってissueを開こうかと思ったところ、既存のこのチケットを見つけました。
もし今の状況が念単位で長期化した場合「月別」を設けてもいいかもしれませんね。
ただ中国の収束の様子を見る限り三ヶ月スケールで落ち着いていきそうですが(そう願うばかりです)...

写真を見る限りすでに実装済みでプルリク許可を待っている感じでしょうか？

**Comment by agrexgh** [comment]
本issueに大賛成です。
賛成の理由としては、
毎週土日はクローズしている医療機関もあり、
日別だと感染者数の推移を、
グラフの増減だけでは見られなくなるためです。

**Comment by kaizumaki** [comment]
@hidehiro98 ご提案ありがとうございます。こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/2207#issuecomment-627819347 にコメントいたしました。結論として、採用を見送ることになりました。ご理解いただければと思います。

**Comment by agrexgh** [comment]
横槍ですが。。
#2207 を拝見いたしましたが、
都からの要望なのですね。残念に思います。

**Comment by kaizumaki** [comment]
都からの回答がありましたので、こちらのissueはクローズしたいと思います。
