### ISSUE TITLE
トップページニュースセクションの変更

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#218]
トップページ 
![image](https://user-images.githubusercontent.com/16509/75750421-8144b600-5d67-11ea-9e33-43f1f4633dd5.png)
の部分の変更

```
３月２日 新型コロナウイルスに関連した患者の発生について（第53報）
```
リンク先：https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html

**Comment by mikkame** [comment]
これひょっとしてそのうち自動化必要なのでは・・・

**Comment by halsk** [comment]
そもそもCMS機能的なのが必要となる可能性がありますね

**Comment by halsk** [comment]
MicroCMSとかのヘッドレスCMSを試してみたいと思ってたのでやってみたい感はある
