### ISSUE TITLE
コード内で「陽性物数」という間違った日本語が使われているので「陽性者数」に変更する

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#2208]
## 改善詳細 / Details of Improvement
- コード内で「陽性物数」という間違った日本語が使われている．明らかに「陽性者数」の誤りなので，正しいものに変更する

### 該当箇所
- `components/ConfirmedCasesTable.vue`
- `utils/formatConfirmedCases.ts`

**Comment by pingineer-jp** [comment]
やりましょうか

**Comment by kaizumaki** [comment]
@pingineer-jp すでにPRきております！ #2215

**Comment by pingineer-jp** [comment]
ほんとだ
すいません見落としてました
