### ISSUE TITLE
左側メニューの並びとリンク先の変更

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#222]
以下でお願いします！！

・公式発表
・【東京都主催等】中止又は延期するイベント・説明会等
・東京都公式ホームページ
・知事からのメッセージ
・このサイトについて
↓
・東京都新型コロナウイルス感染症対策本部報 https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html
・【東京都主催等】中止又は延期するイベント・説明会等 （リンク変更なし）
・知事からのメッセージ （作成中につき別途指定します）
・このサイトについて （リンク変更なし）
・東京都公式ホームページ https://www.metro.tokyo.lg.jp/

**Comment by mikkame** [comment]
> ・東京都新型コロナウイルス感染症対策本部報 ?> > https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html

これについては現行と違いがないようです

**Comment by mikkame** [comment]
ああ、すみません、公式発表から変わったよってことですね
