### ISSUE TITLE
グラフの上部に余裕をもたせる

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#223]
各グラフの縦軸 | 現状、最大値に合わせてた縦軸が表示されていますが、縦軸の上部に余裕を持たせたく、最大値×1.2～1.5倍ぐらいで設定いただけないでしょうか

**Comment by mikkame** [comment]
ついでに対応

**Comment by halsk** [comment]
`陽性患者数` にも余白つけてほしいです〜

**Comment by mikkame** [comment]
@osoken お気づきかもしれませんがここのheight場当たり的な感じでちょいハックな対応になってます。
v-toolbar外した方がいいかもしれません

**Comment by mikkame** [comment]
すみません、対応内容を間違っていたようです。
chartjsのy軸の最大値を調整してほしい！という内容です
