### ISSUE TITLE
陽性患者数を年代別に可視化したい

### ISSUE THREAD

**Issue by yuuton414** [tokyo-metropolitan-gov/covid19#2279]
## 改善詳細 / Details of Improvement
陽性患者数を年代別に可視化したい。  
既にある「陽性患者の属性」ではどの年代の人に陽性の人が多いのかがわかりづらい。  

## 期待する見せ方・挙動 / Expected behavior
- 人口ピラミッド?みたいなイメージで年代ごとに可視化
![image](https://user-images.githubusercontent.com/59001145/77488463-a618de80-6e78-11ea-816a-a02fd784dd23.png)

- 他に良い可視化方法があれば挙げてほしい

## 将来的に
年代別に可視化した後、tooltipなどで重傷者数、退院者数、死亡者数の割合とか見れたら良いですね。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by llongmane584** [comment]
グラフ見せ方として、今Excelのピボットグラフで個人的に作成しているイメージを提案します。
![age](https://user-images.githubusercontent.com/46396892/77824216-69810780-7144-11ea-9718-501569979ece.jpg)

**Comment by inuinana** [comment]
Plotlyを利用したヒストグラムを提案させていただきます。
PythonやJavaScriptを用いて、HTMLや画像ファイルとしてエクスポートすることも可能です。
![Screenshot 2020-03-29 at 22 29 19](https://user-images.githubusercontent.com/28846850/77860006-eecfef00-720c-11ea-91c0-290828f6283e.png)

**Comment by hanyo** [comment]
それから、亡くなった方の情報がほしい。![Image](https://i.imgur.com/ojXsIzi.jpg)

**Comment by y-chan** [comment]
こんにちは、兵庫県版のグラフやデータの管理を行っている者です。
兵庫県版では年代別グラフを以下のように取り入れています。(年代別に注意を呼び掛けるデータとしての目的なので、性別は分けていません。)
参考になれば幸いです。
![image](https://user-images.githubusercontent.com/34832037/77996197-23a48900-7368-11ea-9b50-a7ea38432a5e.png)

**Comment by tkmrkt** [comment]
今これを少し作ってみてますが、
mockデータはdata/patientsを使おうかと思っています。
ただ、deadフラグのようなデータが無いので、
dead数をどうしようかと思っています。

こちらで勝手にdata/patientsにdeadフラグのようなものを追加してprすれば、
バックエンドの開発者さんがapiに追加してくれるのでしょうか？

**Comment by kaizumaki** [comment]
こちら `need-official-confirmation` ラベルをつけさせていただいております。関係各所の確認が必要ですので、お待ちいただけますようお願い申し上げます。

**Comment by tkmrkt** [comment]
了解です〜

**Comment by llongmane584** [comment]
オープンデータCSVをここ数日チェックしていますが、項目の値に揺れが発生した場合の対応が必要そうです。例えば、
患者_性別 : 「女性」「女」(3/31版)
患者_性別 : 「男性」「男」、「不明」「-」(4/2版)
患者_年代 : 「不明」「-」(4/1版, 4/2版)

年代・性別とは無関係ですが、
「患者_居住地」 :  「-」「-」「―」(4/2版)
もありました。

**Comment by nichesuch** [comment]
#412 
関連です。

**Comment by kaizumaki** [comment]
みなさまご提案ありがとうございます。こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/454#issuecomment-617671788 にコメントいたしました。ご理解いただきますようよろしくお願いいたします。

**Comment by kaizumaki** [comment]
都からの正式な回答がありましたので、こちらのissueはクローズさせていただきます。
