### ISSUE TITLE
新宿区/千代田区エリアの来訪者推移（参考値）グラフについて、言語をEnglishにしても一部日本語が残る

### ISSUE THREAD

**Issue by totoro721** [tokyo-metropolitan-gov/covid19#2284]
## 起こっている問題 / The Problem
- ”出典”という日本語が残ったままになっている

## スクリーンショット / Screenshot
<img width="754" alt="コメント 2020-03-25 123018" src="https://user-images.githubusercontent.com/2782936/77501385-4253dd00-6e9b-11ea-8492-149bb507b6c8.png">

## 期待する見せ方・挙動 / Expected Behavior
- "出典" ⇒ "Source"

## 起こっている問題の再現手段 / Steps to Reproduce
1. 言語を English に切り替える

## 調査 / Research
VisitorsBarChar.vue:L44 が $t('出典') となっていますが、
- ja.json    <img width="188" alt="Japanese217" src="https://user-images.githubusercontent.com/2782936/77502653-c8255780-6e9e-11ea-9e30-7874eb517d42.png">

- en.json  <img width="190" alt="en03-25 134300" src="https://user-images.githubusercontent.com/2782936/77502713-ef7c2480-6e9e-11ea-9581-db786bee5bdb.png">

となっている。
ja.json ："出典": "出典: "
en.json ："出典": "Source: "
に修正すればよいのではないでしょうか？{source}は使われていない？

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
`a` タグに `place="source"` の属性が必要そうですね。

**Comment by MaySoMusician** [comment]
GitHub上で `ja.json` を変更すれば良いのですが、一部翻訳文字列が想定とは異なる指定をされているようですね... 確認します

**Comment by totoro721** [comment]
了解です。回答をお待ちします。

**Comment by MaySoMusician** [comment]
もともと
```vue
<i18n path="出典: {source}">
  <a place="source" ... >
    {{ $t('ヤフー・データソリューション') }}
  </a>
</i18n>
```
というように使われる予定で登録していたのですが、今の実装をみると「出典:」「ヤフー・データソリューション」がそれぞれ分離している形になっています。この形でも他の言語では問題ないはずですので、 `ja.json` の
```json
"出典: {source}": "出典: {source}",
```
を
```json
"出典:": "出典:",
```
に変更すれば解決すると思われます。
なお他の言語の言語ファイル（ `en.json` など）はTransifex側で自動的に修正されるので、GitHub側での変更は必要ありません。

**Comment by MaySoMusician** [comment]
別で解消されているようなのでclose
なおreopenを妨げるものではありません
