### ISSUE TITLE
滋賀県のサイトがなくなっているようです

### ISSUE THREAD

**Issue by hidehiro98** [tokyo-metropolitan-gov/covid19#2285]
## 起こっている問題 / The Problem
- [サイト一覧](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md)の[滋賀県サイト](https://stopcovid19.pref.shiga.jp/)がなくなっているようです

**Comment by kaizumaki** [comment]
見たところ、滋賀県サイトはあるようですが、いかがでしょう？

**Comment by mikkame** [comment]
存在しているように見えます。

**Comment by okuryu** [comment]
VPNを利用していると名前解決できないようですね。
```
$ dig +short stopcovid19.pref.shiga.jp
$ ping stopcovid19.pref.shiga.jp
ping: cannot resolve stopcovid19.pref.shiga.jp: Unknown host
```

**Comment by hidehiro98** [comment]
失礼しました。今確認したところ見れました。。
Closeさせていただければと思います。
