### ISSUE TITLE
グラフ新規追加：帰国者・接触者電話相談センター相談件数

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#229]
タイトル：新型コロナ受診相談窓口（帰国者・接触者電話相談センター）相談件数
デザイン：新型コロナコールセンター相談係数と同じ形
データ：
htps://codeforjapan.sharepoint.com/sites/covid19/DocLib/帰国者・接触者センター相談件数-RAW.xlsx

**Comment by mikkame** [comment]
データの追加対応するのでアサインだけしておきます！
tool以下で生成しているので興味がある人はやってみてみてください

**Comment by ocean3fish** [comment]
グラフの形はこんな感じになるはずです。
<img width="1246" alt="スクリーンショット 2020-03-03 18 21 54" src="https://user-images.githubusercontent.com/4206675/75761203-02a64380-5d7c-11ea-8394-8cfc8685e717.png">

**Comment by mikkame** [comment]
変数名は何にしたらいいですかね・・・
疑いがある人みたいな感じだと差別的ですよね

**Comment by ocean3fish** [comment]
querent（相談者）とかでしょうかー

**Comment by mikkame** [comment]
マクロ書いてあるっぽい・・・

**Comment by mikkame** [comment]
やっときます
