### ISSUE TITLE
モバイル版のフロー図に誤字

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#232]
受信が不要　→　受診が不要

**Comment by forestgtree** [comment]
issue作ってコミットしようかと思いましたが、権限がなく…
![sp_flow_06_03@2x](https://user-images.githubusercontent.com/55567929/75764160-cc1ef780-5d80-11ea-9335-b9270bd2e7cf.png)

**Comment by mikkame** [comment]
ちょうどxdから拾ってきたところです！

**Comment by forestgtree** [comment]
ありがとござます！

**Comment by mikkame** [comment]
やっときますよー
