### ISSUE TITLE
CCBY URL should be put on transifex

### ISSUE THREAD

**Issue by PichuChen** [tokyo-metropolitan-gov/covid19#2325]
## 起こっている問題 / The Problem
- In #1189 we change the url for cc-by links
- But we didn't put it into transifex
- So the string is missing
- The other string such as "https://marketingplatform.google.com/about/analytics/terms/jp/" is in transifex

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
こちらも #2425 にマージしましょうか。
ja.json に、CC/BY の URL を Key/Value エントリとして追加すればよろしいですよね？

**Comment by PichuChen** [comment]
OK

**Comment by mcdmaster** [comment]
Done.

@PichuChen, can you please close this as merged to #2425? Thank you for cooperation in advance.

**Comment by PichuChen** [comment]
OK

**Comment by mcdmaster** [comment]
Unfortunately, I do not have proper privilege in this project to merge an Issue created by another expert like you to mine. I am convinced that you can make it done. Thank you anyway

**Comment by mcdmaster** [comment]
Hi @PichuChen,

Since the issue #2425 has just been merged into development environment, we are only waiting for the translation.
I think, as you mentioned above, we are set to close this now (if you think that the translation will be worked on shortly.) Thank you in advance anyway
