### ISSUE TITLE
【flow】一部の言語にて矢印の位置が崩れる

### ISSUE THREAD

**Issue by ShuntaNakajima** [tokyo-metropolitan-gov/covid19#2336]
## 起こっている問題 / The Problem
- flow画面で一部の言語において、矢印の位置が崩れてしまう

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-26 16 24 59](https://user-images.githubusercontent.com/17024754/77620961-d5197800-6f7e-11ea-871c-1ec4e4748fbd.png)

## 期待する見せ方・挙動 / Expected Behavior
![スクリーンショット 2020-03-26 16 25 05](https://user-images.githubusercontent.com/17024754/77620975-db0f5900-6f7e-11ea-96c4-fdee427d0c11.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. 700px ~ 1000px あたりで確認できます。

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari

**Comment by kazat** [comment]
左右の列をautoautoではなく70%30%で分けているのは何か理由があるのでしょうか？

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/flow/FlowPc.vue#L114

**Comment by kaizumaki** [comment]
> 左右の列をautoautoではなく70%30%で分けているのは何か理由があるのでしょうか？

これは元デザインを再現するためにこうしています。狭いviewpointだと無理はくるかもしれないですね。

**Comment by kzhrk** [comment]
矢印の位置を解消するという観点であれば、左右のコンテンツの高さに依存している`.CardBlock`の`.CardBlock::after`で矢印アイコンのスタイルを定義するのではなく、各`FlowPc***.vue`の`.Flow::after`で矢印アイコンのスタイルを定義すれば、左側の箱の中央に矢印アイコンを置くことは可能だと思います。
しかし、各`FlowPc***.vue`で矢印アイコン用のスタイルが定義されてしまうため、`FlowPcArrow.vue`のような矢印アイコンコンポーネントを定義して各`FlowPc***.vue`で読み込ませるのがベターな対応かと思います。
