### ISSUE TITLE
時系列チャートにて、本来「M月」と表示される部分が「Invalid Date」と表示される

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#2347]
## 起こっている問題 / The Problem
- 「都内の最新感染動向」に存在する時系列チャートにて、月を表示している部分に「Invalid Date」と表示される
- development, staging でのみ確認

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/42484226/77635141-73183d00-6f95-11ea-9f74-9a5f92d153a5.png)

## 期待する見せ方・挙動 / Expected Behavior
- これまで通り月が表示される
![image](https://user-images.githubusercontent.com/42484226/77635333-c094aa00-6f95-11ea-9ea1-7c01d732d0d7.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/ を開く

**Comment by MaySoMusician** [comment]
i18n関連だと思いますので、調査してみます

**Comment by MaySoMusician** [comment]
削除された軸ラベル用callbackが復活してしまっていることが原因でした。すぐに修正PRを出します
