### ISSUE TITLE
相談フロー変更に伴う「新型コロナウイルス感染症が心配なときに」ページの修正

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#2357]
## 改善詳細 / Details of Improvement
福祉保健局の相談フローが変更になりました。
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html
渡航歴がある方などが削除され、新たに「かかりつけ医のいる方」が増えました。
そのほか軽微な修正が行われています。
フロー自体の修正は時間がかかることもあり、ひとまずは添付画面のように、画面下部にある「詳細を見る（東京都福祉保健局）」を画面上部に移動し、文章を追加して上記サイトへの誘導を行います。

## スクリーンショット / Screenshot
<img width="854" alt="Flow" src="https://user-images.githubusercontent.com/54087276/77640358-9646ea80-6f9d-11ea-8693-8265f85115fd.png">

## 期待する見せ方・挙動 / Expected behavior
現状、対策サイト上で表示されている相談フローの変更は、改めて作業負担等鑑みながら別Issueでお願いしますので、ここでは考慮しなくて構いません。

**Comment by macropygia** [comment]
@mtenjin 暫定措置とのことで急ぎと思われるためリリース優先の内容でPRを作成します。PC版の印刷ボタンの位置はどうしても指示の位置でなければならないようであれば修正します。

## PC

![image](https://user-images.githubusercontent.com/3162324/77681139-4b969400-6fd8-11ea-9ef2-2eb2700bb76d.png)

## SP

![image](https://user-images.githubusercontent.com/3162324/77681258-6b2dbc80-6fd8-11ea-859a-2f843eac20da.png)

**Comment by mtenjin** [comment]
「印刷」ボタンの位置は、特に制約はありませんので、ご指定の方法で構いません。
よろしくお願います。
