### ISSUE TITLE
「陽性患者の属性」年代に不明代と表示される（代は不要）

### ISSUE THREAD

**Issue by oke-py** [tokyo-metropolitan-gov/covid19#2371]
## 起こっている問題 / The Problem
- 「陽性患者の属性」の年代が不明の場合に「不明代」と表示されています。

## スクリーンショット / Screenshot

![ss_ 2020-03-26 21 55 45](https://user-images.githubusercontent.com/4710215/77649411-2a6c7e00-6fad-11ea-95c9-216e14edaa4b.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「不明」と表示する

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページにアクセスする

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kebhr** [comment]
#2312 で修正しましたが、ロールバックしているみたいですね...。

**Comment by kaizumaki** [comment]
こちら、 #2312 で解決しております。

**Comment by kaizumaki** [comment]
あ、なるほど。デグレったんですね！

**Comment by oke-py** [comment]
お、そうなんですね。承知しました。
ご確認ありがとうございます。

**Comment by kaizumaki** [comment]
`development` ブランチで修正されているのを確認しました。明日のリリースをお待ちください。

**Comment by oke-py** [comment]
修正されていることを確認しました。ご対応ありがとうございます。
