### ISSUE TITLE
棒グラフの右端が見切れている

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#2384]
## 起こっている問題 / The Problem
- 棒グラフの右端、最新の日付部分が他の日付と比べて細くなっているように見える
- 以下のコンポーネントで起こっている模様
  - TimeBarChart
  - TimeStackedBarChart

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-27 0 03 14](https://user-images.githubusercontent.com/5207601/77661809-77a51b80-6fbe-11ea-89a6-b0c8b883674a.png)

## 期待する見せ方・挙動 / Expected Behavior
- 棒グラフが適切に表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://dev-covid19-tokyo.netlify.com/ を開く

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by macropygia** [comment]
#2081 （ f828223 ）で発生したようです。

**Comment by NaoyaShimizzz** [comment]
庁内でも確認しておりましたが、戻していただきたいです。宜しくお願いします。

**Comment by kaizumaki** [comment]
@NaoyaShimizzz  PRがきているので、次のリリースにのる予定ですが、それより急ぎますでしょうか？

**Comment by NaoyaShimizzz** [comment]
次のリリースに乗るのであれば、そのタイミングでOKです。よろしくお願いします。
