### ISSUE TITLE
X軸の文字列の角度が揃っていない

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#2385]
## 改善詳細 / Details of Improvement
- [development](https://dev-covid19-tokyo.netlify.com/) 環境で確認したところ、グラフによってX軸の文字列が斜めになっているものがありました
  - TimeBarChart でこの事象が発生しているように見えます

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-27 0 12 49](https://user-images.githubusercontent.com/5207601/77662987-e33bb880-6fbf-11ea-800e-6091501ac055.png)
![スクリーンショット 2020-03-27 0 12 54](https://user-images.githubusercontent.com/5207601/77662994-e5057c00-6fbf-11ea-96c4-71caede8856b.png)

## 期待する見せ方・挙動 / Expected behavior
- issue 起票時点の [Production](https://stopcovid19.metro.tokyo.lg.jp/) では X軸の文字列に角度がついていませんでした
- 個人的にはこちらのほうが角度が揃っていて読みやすいと感じました

![スクリーンショット 2020-03-27 0 15 09](https://user-images.githubusercontent.com/5207601/77663145-15e5b100-6fc0-11ea-80a4-2679369520dd.png)

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari / Firefox

**Comment by macropygia** [comment]
着手します。
