### ISSUE TITLE
[i18n] About this site ページに日本語が残っているので翻訳する

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#2386]
## 起こっている問題 / The Problem
- About this site ページで Browser compatibility の部分に未翻訳の文章がありました

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-27 0 27 51](https://user-images.githubusercontent.com/5207601/77664770-0b2c1b80-6fc2-11ea-917a-74afaa279544.png)

## 期待する見せ方・挙動 / Expected Behavior
- 日本語部分が翻訳されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/en/about を開く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
こちら、私がやりましょう。
見てみたところ、上記２つのストリングは pages/about.vue と assets/locales/en.json の間で、キー値に差異があります。
翻訳が漏れるのは、そうしたキー値の差異によるものです。pages/about.vue の記載内容に寄せることとします。
そちらの方が up-to-date と思われるためです。違っていたらご指摘をお願いします。

**Comment by MaySoMusician** [comment]
#766 の変更が翻訳ファイル側に反映されていなかったようです
`ja.json` を変更して `development` に取り込めば、Transifexが自動的に認識し新しい翻訳文字列が翻訳可能となります

**Comment by MaySoMusician** [comment]
`en.json` 自体は、上述のように翻訳が終わった後のsync（翻訳100%完了時もしくは手動でのsync時）で、Transifex側から変更PRが発行される仕組みになっています

**Comment by mcdmaster** [comment]
りょうかいしました。アドバイスありがとうございます。
では、追って ja.json の PR 上げますね

**Comment by mcdmaster** [comment]
他のイシューとまとめているため、お待たせしております。
PR #2425 をフォローしていただけますようお願いいたします。

**Comment by mcdmaster** [comment]
引き続き、お待たせしております。
#2425 が development にマージされたため、あとは英訳作業を待つのみとなります。
あともうしばらくお待ちいただけますようお願いいたします。
development 環境のアウトプットは、以下でご確認をいただけます。
https://dev-covid19-tokyo.netlify.com/en/about

**Comment by mcdmaster** [comment]
翻訳を実施しました。上記リンクからご確認をいただき、オーケーならイシュークローズをお願いいたします。
念のため、スクショを添付しておきます
![2020-04-05 133942](https://user-images.githubusercontent.com/10361533/78467032-7d7bc900-7743-11ea-8e8d-a7ac2053ba24.png)

**Comment by shgtkshruch** [comment]
返信が遅れて申し訳ありません

本番環境でも Browser compatibility が翻訳されていることを確認しました。
（英語以外は未翻訳ですが、今後対応されるものと思っています）
ご対応ありがとうございました！
