### ISSUE TITLE
「やさしいにほんご」の「陽性患者の属性」の注記がおかしい

### ISSUE THREAD

**Issue by yoshimaru7** [tokyo-metropolitan-gov/covid19#2393]
## 起こっている問題 / The Problem
- 「陽性患者の属性」の注記が「3/26（●月/●日）まで これまでのぜんぶで」と表示される

## スクリーンショット / Screenshot
![やさしいにほんご表示バグ](https://user-images.githubusercontent.com/7779389/77693058-15164480-6feb-11ea-80d1-2b4d734f0904.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 通常の日本語表記：3/26の累計
↓
（●月/●日）を削除、後半も簡略化して、「3/26までのぜんぶ」でいかがでしょうか。

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイドバーの多言語選択メニューで「やさしいにほんご」を選択
https://stopcovid19.metro.tokyo.lg.jp/ja-basic/
2. トップ画面の「コロナウイルスの 病気（びょうき）になった 人（ひと）について」へ

## 動作環境・ブラウザ / Environment
- macOS / iOS 
- Chrome / Safari

**Comment by kos31de** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/blob/f1e78d0f4faf90c1ebd1764c6cbbfb85f187855d/assets/locales/ja-Hira.json#L17

ここの`（●月/●日)`の部分が不要なのでしょうかね？
ここの修正だけで良いならすぐに直せそうです。

**Comment by halsk** [comment]
修正されたのでクローズします。
