### ISSUE TITLE
地図の日付が、スマホで見た時に重なっている

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#2394]
## 改善詳細 / Details of Improvement
- 最近追加した地図の日付部分が、スマホで見ると重なってしまう。正しく表示されるようにしたい

## スクリーンショット / Screenshot

![IMG_5237](https://user-images.githubusercontent.com/16509/77706604-36d0f500-7006-11ea-94e7-1659ac47ba51.PNG)

## 期待する見せ方・挙動 / Expected behavior
- 可能であれば、他のグラフと同様のスタイルに合わせたい
![IMG_5238](https://user-images.githubusercontent.com/16509/77706641-510ad300-7006-11ea-8ca1-ffe2d489fb30.PNG)

- ただし、この機能はなるべく早めに公開したく、時間がかかりそうならとりあえずフォントサイズ調整くらいの緊急避難でも可

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yuuton414** [comment]
フォントサイズを調整して対応してみます

**Comment by Nyoho** [comment]
これ、対応できるかソースを見ていたんですが、`rotate` が `rorate` というtypoになっているのに加えて、`.v-slider__tick-label` が scoped sylte で効いていないのではないかというところまでわかりました。
ご参考までに。

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/MapCard.vue#L175-L177 です。

**Comment by halsk** [comment]
SELECT BOXを使う実装が提案されており、そちらで進める予定です。

![image](https://user-images.githubusercontent.com/16509/77713127-e911b800-7018-11ea-973b-23adfb4f1cc0.png)
