### ISSUE TITLE
お問い合わせ一覧の「role="presentation"」について

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#2411]
## 改善詳細 / Details of Improvement
pages/contacts.vue
の&lt;table&gt;タグに、属性 role="presentation" が設定されていますが、
&lt;table&gt;タグの要素に&lt;th&gt;やscope属性が使用されているので、
role="presentation"を設定すべきではないケースにあたるのではないでしょうか。

…とここまで書いて気付きましたが、履歴を見ると
role="presentation"が設定された後にtd→thにされていますね。

このtableはrole="presentation"が設定されているので、

- &lt;caption&gt;タグ
- &lt;th&gt;タグ
- &lt;td&gt;タグにheaders, scope属性を設定する

といった、セマンティックマークアップは入れてはいけません。

**Comment by kebhr** [comment]
本件対応します。

**Comment by masuP9** [comment]
@goki90210 @kebhr 横からすみません。`<table>` に `role="presentation"` が設定されていてもモダンブラウザでは子要素の `role` はすべて修正されるため `<caption>`, `<th>`, `<td>` への `headers`, `scope` があっても問題無さそうです。

<img width="1436" alt="Chrome Devtoolで該当箇所の td 要素の role をAccessbility パネルで確認したスクリーンショット。roleはgeneralになっている" src="https://user-images.githubusercontent.com/6724665/77724282-e83b4f00-7035-11ea-87c2-cee31ae0cb3e.png" />

逆に `role` 属性の指定による role の上書きに対応していないブラウザや支援技術のためにデフォルトのセマンティクスを残しておくのは有用に思います。

もし改善するのであれば、 `table` によるマークアップから見出しと文章の構造に直すのが良さそうに思えます。

**Comment by kebhr** [comment]
@masuP9 @goki90210 
なるほど、そうなんですね。
一旦作業は保留にします。

ちなみに、`table`によるマークアップを採用している背景には都側の要望があるため https://github.com/tokyo-metropolitan-gov/covid19/issues/1726#issuecomment-600405224 、見出しと文章による構造に変更するためには都に対して提案をまとめる必要があります。

**Comment by masuP9** [comment]
@kebhr ありがとうございます！  https://github.com/tokyo-metropolitan-gov/covid19/issues/1726#issuecomment-600405224 について理解しました！

現状の仕様通り = 広い画面では `table` で、狭い画面では見出しと文章の構造、とした場合にセマンティクスもそれに合わせるにはブレイクポイントで `role` の有無をコントロールするのが良さそうですー！

**Comment by kebhr** [comment]
@masuP9 
> ブレイクポイントで role の有無をコントロールする

こちらについてもう少々ご教示いただけますでしょうか！

現状は広い画面・狭い画面ともに`role`によって見出しと文章による構造に近づけていますが、これでは不十分でしょうか？
（role追加のPR: #1981）

**Comment by masuP9** [comment]
@kebhr おそくなりました🙏

狭い画面では視覚的な表示をCSSによって見出しと文章の構造に変えているので、セマンティクスも変えたほうが良いのですが、広い画面では視覚的な表示が表形式ですし `thead` 要素も表示しているので、セマンティクスも表であることが望ましいかなと考えています。

詳細な点で言うと `thead` 内の `お問い合わせ` `内容局名` `電話番号` と各セルの関連付けが消えてしまうためです。

ただ現状、致命的な問題と言うよりは、可能であればそうしたほうが良さそうぐらいです！

**Comment by kebhr** [comment]
@masuP9 
> thead 内の お問い合わせ 内容局名 電話番号 と各セルの関連付けが消えてしまう
たしかに現状そうなっていますね。
対応可能に見えますので、この方向でPRを出してみます！

**Comment by goki90210** [comment]
>可能であればそうしたほうが良さそうぐらいです！

その認識です。

- role="presentation"をつけるならthの使用はやめた方がよい。
- thを使用するならrole="presentation"は外した方がよい。

です。

**Comment by halsk** [comment]
とりこみました。意図通りの動作になっているかご確認ください。
