### ISSUE TITLE
簡体字中国語（zh_CN）のREADMEファイルのMarkdown構文に抜けがある

### ISSUE THREAD

**Issue by el-hoshino** [tokyo-metropolitan-gov/covid19#2416]
## 起こっている問題 / The Problem
- Markdownのコードブロックは最後 \` が3つなければならないですが、zh_CNのREADMEファイルで最後のコードブロックだけ最後の \` が1つ抜けてて2つしかない
- それによってREADMEファイルのレンダリングがバグってる

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-27 13 08 39](https://user-images.githubusercontent.com/3942121/77720726-1a47b380-702c-11ea-8b13-278d86651092.png)

## 期待する見せ方・挙動 / Expected Behavior
- コードブロック構文を `$ docker-compose run --rm app yarn install` で終わり、それ以降は通常のMarkdownとしてレンダリングされる

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://github.com/tokyo-metropolitan-gov/covid19/blob/development/docs/zh_CN/README.md に行く
2. READMEを読む

## 動作環境・ブラウザ / Environment
- macOS
- Safari

**Comment by skakepi** [comment]
こんにちは。当方初心者ですが、こちら対応してみてもよろしいでしょうか？？

**Comment by el-hoshino** [comment]
@skakepi おきもちありがとうございます！今私の方で対応しております 🙋‍♂

**Comment by skakepi** [comment]
@el-hoshino 承知致しました！
