### ISSUE TITLE
[要確認] flowページのアンカー文字列（モバイル版）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#243]
@halsk @ocean3fish
flowページのモバイル版は、ページ内アンカーがふってあるのですが、そのアンカー文字列が適切かどうかご確認ください。
- 新型コロナ受診相談窓口
↓
https://stg-covid19-tokyo.netlify.com/flow#sodan
- 受診が不要と判断された場合
↓
https://stg-covid19-tokyo.netlify.com/flow#jushinfuyo
- 入院となります
↓
https://stg-covid19-tokyo.netlify.com/flow#nyuin

**Comment by halsk** [comment]
英語にしましょうかー

新型コロナ受診相談窓口
↓
https://stg-covid19-tokyo.netlify.com/flow#`consult`
受診が不要と判断された場合
↓
https://stg-covid19-tokyo.netlify.com/flow#`not_required`
入院となります
↓
https://stg-covid19-tokyo.netlify.com/flow#`hospitalized`

**Comment by kaizumaki** [comment]
了解です！修正します。

**Comment by kaizumaki** [comment]
@halsk すみません、あとひとつありました。
- PCR検査
↓
https://stg-covid19-tokyo.netlify.com/flow#kensa

**Comment by halsk** [comment]
#pcr でいいんじゃないでしょうかー
