### ISSUE TITLE
IE11 検査実施状況

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#2444]
IE11で見ると、（チャーター機・クルーズ船）がはみ出してしまっています。
修正お願いします。
![17EF5473-1A05-4E51-88A2-325107AC5C1C](https://user-images.githubusercontent.com/61729733/77738970-1af44000-7054-11ea-8dbb-75afcb0ff0ed.jpeg)

**Comment by masanori1102** [comment]
IE11は、当サイトについて | 東京都 新型コロナウイルス感染症対策サイト( https://stopcovid19.metro.tokyo.lg.jp/about )で推奨されていません。

IE11は、以下のどのスタンスで対応していくのでしょうか?
1. 推奨ブラウザーに追加する
1. 極端にひどくなった所は直す
1. 対応しない

**Comment by kaizumaki** [comment]
IE11対応については、当初は対象ブラウザから外すことで回避していたのですが、都庁内からの要望があり、 #890 で対応したという経緯があります。
#890 で対応はしましたが、要望元が限定的であったこともあり、広くは宣言せず、対象ブラウザ一覧には当初のままで載せないこととした、というのが私の理解です（とはいえ私の記憶では、対象ブラウザ一覧に載せるかどうかを議論したことはないと思います）。
実際、IE11に対応しているとは言い切れない、表示上のバグはたくさんあります。
なので、 @masanori1102 さんの質問に答えると「2」というところです。

**Comment by masanori1102** [comment]
ご説明ありがとうございます > @kaizumaki
