### ISSUE TITLE
グラフにaria-labelを付与する

### ISSUE THREAD

**Issue by shunito** [tokyo-metropolitan-gov/covid19#2448]
## 改善詳細 / Details of Improvement
- 関連：#2364
- canvasで表示されているグラフにラベルが付与されておらず、スクリーンリーダーでは画像があることしかわからない。
- role="img"およびaria-labelを付与して、何が表示されているか分かるようにする。
- ついでにフォールバックコンテンツも追加したいが、議論が長くなりそうなのでとりあえず上記まで。
- なお、グラフで利用されているChart.jsにはラベルを追加する機能がないようなので、DOMが描画されたタイミングで付与する必要がある。

参考
https://developer.mozilla.org/ja/docs/Web/API/Canvas_API/Tutorial/Hit_regions_and_accessibility
http://pauljadam.com/demos/canvas.html

## スクリーンショット / Screenshot
![開発者ツールでcanvasを選択、Accessibilityパネルでラベルにあたるテキスト類がない](https://user-images.githubusercontent.com/32133/77755618-f6f32780-7070-11ea-8397-7bf285851158.png)

## 期待する見せ方・挙動 / Expected behavior
- 各グラフが、グラフであることがわかるようにする。

## 動作環境・ブラウザ / Environment
- 環境による制約なし

**Comment by shunito** [comment]
ざっくり方法は調査済みです。
明日午前でよければ対応可能なので、対応するようであればアサインしていただければ。

**Comment by shunito** [comment]
あ、今回は同時にi18nテキストも追加したいと思いますので、ラベルの規約も相談したいです。
「t( `{title}のグラフ` ,title)」として各ボックスのタイトルが入るイメージです。

**Comment by oti** [comment]
イシューありがとうございます！

> ・なお、グラフで利用されているChart.jsにはラベルを追加する機能がないようなので、DOMが描画されたタイミングで付与する必要がある。

こちらは `aria-label` ではなく`aria-describedby` にすれば楽になると思います。

まず[Visually Hidden](https://a11yproject.com/posts/how-to-hide-content/)な見出し要素を起き、`id` 属性を付与し、`aria-describedby` で `id` 属性値を参照すれば、`aria-label` と同じように機能します。

DOM描画のタイミングに依存せずに済みますし、テキストノードになっていれば、現状の他言語のセレクトボックスにない言語でページごと機械翻訳した時にも翻訳がかかります。属性値のテキストは機械翻訳がされません。

@shunito PRs作成をお願いします！

**Comment by shunito** [comment]
なるほど、globalで使えるvisually-hiddenなクラスが無さそうなので、このタイミングで追加するのもよいですね。最初はタイトルにID付与して `describedby` も考えたんですが「～のグラフ」の表現にしたかったので独自ラベルを考えました。
あとは見出しの規約が上記ラベルと同じでOKであれば、明日できそうです。
階層的には `h4` ですかね。

**Comment by shunito** [comment]
いま`<h4>`でグラフに見出しつけて、canvasに ` aria-describedby` つけてチェック中。
axeさんからは `aria-label` か `aria-labelledby` つけろとエラーが出ますね。
確かに説明というほどの内容がないので、`aria-labelledby` のほうがよさそう。
ということで、いったんそちらの方向で先に進めます。
