### ISSUE TITLE
香川県版のサイトを作成

### ISSUE THREAD

**Issue by Kaniyama-t** [tokyo-metropolitan-gov/covid19#2455]
# 改善詳細 / Details of Improvement
香川版のサイトを作成しました。
http://www.covid19-kagawa.jp/

# スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/28642008/77760680-19d60980-707a-11ea-8657-ffcd94c15bce.png)

# 期待する見せ方・挙動 / Expected behavior
- URLが FORKED_SITES.md に追加される

# 動作環境・ブラウザ / Environment
    macOS / Windows / Linux / iOS / Android
    Chrome / Safari / Firefox / Edge

**Comment by nomunomu0504** [comment]
リンクが動いていないようでした！

**Comment by Kaniyama-t** [comment]
@nomunomu0504 解決しました！
連絡ありがとうございました！<(_ _)>
