### ISSUE TITLE
deprecatedになるvue-i18nのplaceプロパティが使われている

### ISSUE THREAD

**Issue by kzhrk** [tokyo-metropolitan-gov/covid19#2470]
## 改善詳細 / Details of Improvement
- `place`プロパティを`v-slot`プロパティに置き換える
  - 確認できたのはflowページとaboutページ、`SourceLink.vue`

## スクリーンショット / Screenshot
ref. [Places syntax usage](https://kazupon.github.io/vue-i18n/guide/interpolation.html#places-syntax-usage)
<img width="1257" alt="スクリーンショット 2020-03-28 2 45 08" src="https://user-images.githubusercontent.com/548508/77784629-2ec49400-709e-11ea-8919-25176409fb79.png">

## 期待する見せ方・挙動 / Expected behavior
- 見た目に変化はなし
- 現状と同じ翻訳が出力されること

## 補足
`span`タグや`a`タグに`place`プロパティは許容されていないのでHTMLとして正しくない状態です。

**Comment by kzhrk** [comment]
問題なければ明日の昼くらいに着手します。

**Comment by MaySoMusician** [comment]
slots syntaxは公式docによれば `vue-i18n@8.14.0` からサポートとのことですが、このプロジェクトで使用している `nuxt-i18n@6.6.0` は `vue-i18n@8.12.0` に依存しているようです

**Comment by kzhrk** [comment]
ご指摘ありがとうございます。
こちらで[nuxt-i18n@6.6.0のpackage.json](https://github.com/nuxt-community/nuxt-i18n/blob/v6.6.0/package.json#L87)を確認したところ、[キャレットでのバージョン指定](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004)になっているようなので`vue-i18n@8.14.0`以降でも問題なく動作するように思います。
また、[本リポジトリのyarn.lock](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/yarn.lock#L12109)を確認したところ、すでに`vue-i18n@8.15.4`で動作しているようです。

**Comment by MaySoMusician** [comment]
ご確認ありがとうございます！それでしたら問題無さそうですね

---

実は私もi18n化実装初期段階でどちらのsyntaxを使おうか検討していたのですが、前述した通りに `vue-i18n` の使用バージョンを勘違いしていたので `place syntax` を採用していました。

**Comment by kzhrk** [comment]
アサインありがとうございます。PR作成しました 😺
