### ISSUE TITLE
グラフの一番右の列のみ、線が細く描画される

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#2474]
## 起こっている問題 / The Problem
グラフの一番右の列のみ、線が細く描画される。

現象が発生しているのは、以下のグラフ
- 陽性患者数
- 検査実施人数
- 検査実施件数
- 新型コロナコールセンター相談件数
- 新型コロナ受診相談窓口相談件数

## スクリーンショット / Screenshot
<img width="1094" alt="スクリーンショット 2020-03-28 4 13 52" src="https://user-images.githubusercontent.com/6235307/77792169-39d1f100-70ab-11ea-82af-b6a7322ce8bb.png">

## 期待する見せ方・挙動 / Expected Behavior
棒が全て同じ幅で表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. Webサイトを開く
1. `都内の最新感染動向`を表示する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by macropygia** [comment]
Duplicate of #2384

**Comment by tkmrkt** [comment]
これクローズしていいんじゃないでしょうか？
<img width="1440" alt="スクリーンショット 2020-03-28 14 41 05" src="https://user-images.githubusercontent.com/306861/77815964-5d745600-7102-11ea-9dd2-e6959b90de10.png">
