### ISSUE TITLE
陽性患者の属性で、居住地データが空白の場合は「調査中」にする

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#2475]
## 起こっている問題 / The Problem
陽性患者属性データ中の「居住地」が空白だった場合、「不明」となっているかと思います。
これを「調査中」としてください。
（これまで居住地が空白だったことはありませんが、このところの陽性者の増加で調査が追い付いていないため、空白のまま速報がされている影響です）

## 期待する見せ方・挙動 / Expected Behavior
居住地が空白の場合→調査中
そのほかはデータ通りに表示してください（本当に不明の場合はデータ入力側で「不明」と入力します）

**Comment by khsacc** [comment]
対応します！

**Comment by khsacc** [comment]
（急ぎ「居住地」について対応しました。そのうえで、）@mtenjin さんに質問なのですが、現在のソースコードですとリリース日・年代・性別についても空欄の場合に「不明」と表記される仕様になっています。これらについても何かしらの対応したほうがよろしいでしょうか？

**Comment by mtenjin** [comment]
福祉保健局の担当の方に確認しました。
居住地などの情報は、患者本人に確認を取ったうえで公表可能なものを記載していますが、時間的に間に合わないため、当日分はリリース日、年代、性別のみとする、とのことでした。
ですので、居住地のみで構いません。
よろしくお願いします。
（金曜日分、土曜日分は同意分については少しずつ調査中から更新されています）
