### ISSUE TITLE
地図の日付変更スライダーのハンドルにラベルがない

### ISSUE THREAD

**Issue by shunito** [tokyo-metropolitan-gov/covid19#2483]
## 改善詳細 / Details of Improvement
- 日付変更のスライダーのハンドル（input）にラベルが付与されておらず、スクリーンリーダーでは何の入力か判断ができない。
- Vuetyfy のv-sliderにはlabelというpropsがあるので設定する。
- ラベルは「日付」がよいかな？非表示にしたい場合にはCSSで対応が必要。

参考）https://vuetifyjs.com/ja/components/sliders/

## 期待する見せ方・挙動 / Expected behavior
- スライダーのインプットにラベルが付与される。

## 動作環境・ブラウザ / Environment
- 環境による制約なし

**Comment by kaizumaki** [comment]
#2468 の作業とバッティングしませんか？

**Comment by shunito** [comment]
あっと、そちらのイシューを認識してませんでした。失礼、取り下げますね。
