### ISSUE TITLE
人口推移マップの翻訳が ja.json に未登録

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#2485]
## 起こっている問題 / The Problem
- 以下の文字列が `ja.json` に未登録
  - `"東京駅周辺の人口推移（参考値）"`
  - `"新宿駅周辺の人口推移（参考値）"`
  - `"※ ヤフーに蓄積された位置情報データなどを元に算出した参考値"`
  - `"※ 土・日・祝日を除く7:30~8:30の平均値"`
  - `"東京23区の人口推移（参考値）"`
  - `"※7:30〜8:30の平均値"`

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/34566290/77816189-fb1c5500-7103-11ea-8c42-ec14e30737cb.png)

## 期待する見せ方・挙動 / Expected Behavior
- `ja.json` に登録し、Transifexで翻訳可能とする

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://dev-covid19-tokyo.netlify.com/en などにアクセスする

## 動作環境・ブラウザ / Environment
- 検証環境: Windows 10 Home 1903 64 bit + Chrome 80.0.3987.149

## 作業時の注意
- 日本語以外の言語ファイル（ `en.json` など）はTransifexで修正されるため、GitHub上では変更しない

**Comment by kazat** [comment]
こちら当方で着手してもよろしいでしょうか。

**Comment by MaySoMusician** [comment]
@kazat よろしくお願いします！
