### ISSUE TITLE
ハンバーガーメニューから他のページに遷移した際、ヘッダーの下部に点線が出る問題

### ISSUE THREAD

**Issue by Genbuchan** [tokyo-metropolitan-gov/covid19#2493]
## 起こっている問題 / The Problem
- ハンバーガーメニューから他のページに遷移した際に、ヘッダーの下部に点線が出る

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/44745974/77817585-50119880-710f-11ea-8183-6e71ea4aa380.png)

## 期待する見せ方・挙動 / Expected Behavior
- 点線の表示を無くす

## 起こっている問題の再現手段 / Steps to Reproduce
1. モバイル端末で表示、またはビューポートの横幅を 600px 以下にする
2. 画面左上のハンバーガーメニューから、他のページへ遷移する
3. ヘッダー下部に点線が出る

## 動作環境・ブラウザ / Environment
- Windows / iOS
- Chrome / Safari

**Comment by masuP9** [comment]
@Genbuchan こちらバグではなく意図した挙動かと思いますー。

これはページ遷移をした際に、キーボードのフォーカスが開始する位置を先頭に戻す処理があり、そのために遷移後サイドバーにフォーカスを当てています。

通常のウェブページだと遷移するとページの一番上からフォーカス開始するのですが、シングルページアプリケーションだとフォーカスがクリックした箇所に残ってしまうためです。

https://github.com/tokyo-metropolitan-gov/covid19/blob/64b02163dabf1fbed66622396c3741cfab593df5/components/SideNavigation.vue#L204-L208

また、すべてのフォーカスされた要素に点線の装飾が付与されますので、サイドバーに点線が表示される形になっています。よってサイドバーから遷移した後、ヘッダーに点線が表示されます。

**Comment by Genbuchan** [comment]
私も、これは意図した挙動なのではないか、と考えております。

しかし、表示上これをバグと捉えることもできるのではないかと思い、幅広い意見を伺うため Issue として上げさせていただきました。

**Comment by oti** [comment]
[discuss] なイシューラベルってないんですねぇ。欲しいですねぇ。

**Comment by oti** [comment]
僕も仕様という理解です。こちらは[#1522 の途中](https://github.com/tokyo-metropolitan-gov/covid19/pull/1522#issuecomment-600384665)でのやりとりを受けての対応でした。

リンクやボタンではない、インタラクティブ要素でない `div` 要素に、フォーカスが当たる・フォーカススタイルが指定される点は、静的なウェブサイトではあまりやらない所作ですので、そこに違和感を持たれ、バグとされるかもしれないことは、同意します。

1522の要求を受け、処理をコンポーネント内で完結させたかったので、コンポーネントルートの `.SideNavigation` に `tabindex="-1"` を与えてフォーカス可能にしました。この実装ではなく親に なんらかを emit していってもよかったのですが、目まぐるしくコードの改善がなされている中、コンフリクトの解消でうっかり他のコンポーネントをデグレさせてしまうリスクを避けたかったのでそうしました。

とはいえ、この時に`.SideNavigation:focus {...}` のスタイルを追加したのは勝手な判断だったな、と今振り返ると思うところではあります。

僕も皆さんの意見が気になりますので、引き続きこのイシューをウォッチさせてください。

**Comment by furandon-pig** [comment]
(もし対応するなら)以下の修正方法が参考になったりしますか？単純に `$Side.blur()` でフォーカスを外すという対応方法です。
この修正自体は別issueとの兼ね合いでcloseしたためプルリクは出していませんが、今回のissueで有効な修正方法かもしれません。

 * [多言語対応選択メニュークリック時の破線 #2137](https://github.com/tokyo-metropolitan-gov/covid19/issues/2137#issuecomment-603000320)

(以下、上記issueからコメントの再掲です)
```js
$ git diff ./components/SideNavigation.vue
diff --git a/components/SideNavigation.vue b/components/SideNavigation.vue
index 1c30145..dd578ca 100644
--- a/components/SideNavigation.vue
+++ b/components/SideNavigation.vue
@@ -194,6 +194,7 @@ export default Vue.extend({
         const $Side = this.$refs.Side as HTMLEmbedElement | undefined
         if ($Side) {
           $Side.focus()
+          $Side.blur()
         }
       })
     }
```

**Comment by halsk** [comment]
`discussion` フラグを付けさせていただきました。
@kaizumaki さん、この辺の挙動はどうなんでしょう。

**Comment by kaizumaki** [comment]
実装の経緯を知っているので、この現象は把握しています。こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/1522#issuecomment-600384665 で、SPAのデフォルトの挙動をご説明いただき、なるべく通常のHTMLページに寄せた感じで実装してもらいました。
こちらのissueの指摘は、たしかにSPAとしての挙動としては正しいと思います。
ただ、多くの閲覧者からしてみると、このサイトがSPAであるかどうかは関係ないわけで...
そうすると、今後も似たような指摘があるだろうということは想像できます。
なので今回の場合は、ヘッダーの下部に点線が残らないように見せることがベターかなと思います。

**Comment by furandon-pig** [comment]
> なので今回の場合は、ヘッダーの下部に点線が残らないように見せることがベターかなと思います。

以下のような修正方法で対応できそうです。追ってプルリクを出そうと思います。

```diff
$ git diff
diff --git a/components/SideNavigation.vue b/components/SideNavigation.vue
index bc0798b..4aac440 100644
--- a/components/SideNavigation.vue
+++ b/components/SideNavigation.vue
@@ -202,13 +202,18 @@ export default Vue.extend({
     $route: 'handleChageRoute'
   },
   methods: {
+    eraseLinkUnderLine() {
+      const $Side = this.$refs.Side as HTMLEmbedElement | undefined
+      if ($Side) {
+        $Side.focus()
+        $Side.blur()
+        $Side.addEventListener('click', this.eraseLinkUnderLine)
+      }
+    },
     handleChageRoute() {
       // nuxt-link で遷移するとフォーカスが残り続けるので $route を監視して SideNavigation にフォーカスする
       return this.$nextTick().then(() => {
-        const $Side = this.$refs.Side as HTMLEmbedElement | undefined
-        if ($Side) {
-          $Side.focus()
-        }
+        this.eraseLinkUnderLine();
       })
     }
   }
```

**Comment by masuP9** [comment]
> なので今回の場合は、ヘッダーの下部に点線が残らないように見せることがベターかなと思います。

本件をSPAのまま解決するベストは、キーボードのフォーカス開始位置を先頭（付近）に戻すために、 `.SideNavigation` にフォーカスを当てるのではなく、`body` 直下の一番先頭にフォーカスをあてるためだけの不可視の要素を配置して、その要素にフォーカスを当てることです。

またその要素の中に、 `<title>` のテキストを入れておくことで、スクリーンリーダーユーザーにとってもSPAでなければページ遷移した際にページのタイトルが通知されるのですが、それを代替することも可能です。

実際に実装されている例として [WinTicket](https://www.winticket.jp/) が参考になります（手前味噌ですみません）

----

上記のベストな実装に関しては時間がかかると思いますので、その前にとりあえずヘッダーの点線を表示させないというベターな対応をするのであれば、CSSで `.SiteNavigation` の `outine` を非表示にするだけで問題なさそうです。 @furandon-pig

**Comment by furandon-pig** [comment]
@masuP9 情報ありがとうございます。CSSで対応するという方法もありそうですね。
ただ、本件のデバッグ中にもう一件フォーカス周りの処理に起因する軽微な不具合(※1)を見つけており、そちらも合わせて修正できる見通しが立っております。
※1：PC向けの表示において、Webページが表示された後、クリックするリンクによっては `handleChangeRoute()` が発火しない場合があるという不具合です。

具体的な修正コードの用意と動作確認ができておりますので、まずはその修正内容にて検討させてもらえればと思います。
