### ISSUE TITLE
棒グラフの一番右端のレコードが極端に細く表示されてしまう

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#2495]
## 起こっている問題 / The Problem
- 棒グラフの一番右端のレコードが極端に細く表示されてしまっている
- 以前はこのような現象は発生していなかったはず

## スクリーンショット / Screenshot
![Screenshot_2020-03-28 東京都 新型コロナウイルス感染症 対策サイト](https://user-images.githubusercontent.com/4206675/77817801-2f4a4280-7111-11ea-8aa0-6756401b8894.png)
<img width="579" alt="スクリーンショット 2020-03-28 16 25 38" src="https://user-images.githubusercontent.com/4206675/77817944-f494da00-7111-11ea-8c18-ce30ca73e683.png">

## 期待する見せ方・挙動 / Expected Behavior
- https://github.com/tokyo-metropolitan-gov/covid19/pull/636 の横スクロール反映で解決されるかもしれない

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Firefox 最新バージョンで確認

**Comment by kaizumaki** [comment]
こちら、対応策 #2392 が16時間前にマージされています。まだ本番に反映されてないんですかね？

**Comment by ocean3fish** [comment]
@kaizumaki すみません重複でしたね。こちらは一旦クローズしておきます。
