### ISSUE TITLE
交通情報の掲載を検討したい

### ISSUE THREAD

**Issue by ryo-a** [tokyo-metropolitan-gov/covid19#2497]
## 改善詳細 / Details of Improvement
- 現時点で東京都内における交通機関の大規模な減便は行われていないが、仮にロックダウンが行われるなどして交通機関の運休や減便が行われた場合、「人口推移」と並んで交通機関の運行情報も重要になると考えられる
- 交通情報を掲載することについて予め考慮しておきたい
- [公共交通オープンデータ協議会](https://tokyochallenge.odpt.org/)が公開しているAPIを用いれば首都圏の運行情報は取得可能

## 課題
- 公共交通オープンデータ協議会から得られる運行情報にはCOVID-19関連以外の情報も含みます。COVID-19関連以外の情報をどう扱うかは要議論だと思います。たとえば、以下のようなデータが流れてきます。残念ながら運行情報自体は日本語のテキストで書かれており、機械判読可能ではありません。
```
{
    "@id": "urn:uuid:d1f14457-42c4-40bf-9ddf-0b911e7b3928",
    "@type": "odpt:TrainInformation",
    "dc:date": "2020-03-28T23:58:01+09:00",
    "@context": "http://vocab.odpt.org/context_odpt.jsonld",
    "dct:valid": "2020-03-29T00:03:01+09:00",
    "owl:sameAs": "odpt.TrainInformation:JR-East.Takasaki",
    "odpt:railway": "odpt.Railway:JR-East.Takasaki",
    "odpt:operator": "odpt.Operator:JR-East",
    "odpt:railDirection": "odpt.RailDirection:BothDirections",
    "odpt:trainInformationText": {
        "ja": "高崎線は、降雪の影響により、運転見合わせや遅れまた運休が発生する可能性があります。最新の運行情報に注意してください。高崎線は、籠原～熊谷駅間での人身事故の影響で、高崎～上野駅間の上下線で運転を見合わせています。運転再開見込は１時００分頃に変更になりました。運転再開見込時刻は前後する場合があります。"
    },
    "odpt:trainInformationCause": {
        "en": "Human-related accident",
        "ja": "人身事故"
    },
    "odpt:trainInformationStatus": {
        "en": "Operation will resume",
        "ja": "運転見合わせ"
    }
}
```

-  公共交通オープンデータ協議会のデータは `開発者が、公共交通データAPI、公共交通データ開発者サイトおよび本データを利用する目的が本チャレンジに応募すること以外(ただし、本チャレンジに応募したうえで、主催者が認定したコンテストへ応募することは除く)にもあると本チャレンジの主催者が判断した場合、本センターは、当該開発者が公共交通データAPI、公共交通データ開発者サイトおよび本データを利用することを終了させることができるとともに、当該開発者に対して法的措置を講ずることができるものとします。` という規約が設けられています。要は「このデータはコンテストのために公開しているので、第4回 東京公共交通オープンデータチャレンジコンテストに応募しなければ規約違反」ということになります。コンテストへの応募は目的ではないのですが、ライセンスに適合させるために便宜上 Code for Japan あるいは東京都などの名義でコンテストに応募する必要が生じるかもしれません。

## 期待する見せ方・挙動 / Expected behavior
- 東京都に乗り入れる交通各社の運行情報が集約された状態で閲覧できるようになる

**Comment by nard-tech** [comment]
API から流れてくる路線名（`odpt.Railway:JR-East.Takasaki` など）と日本語（「高崎線」など）を対応させる辞書，私が以前作ったものがありますので，提供できます．

**Comment by hanyo** [comment]
もっと簡単に、yahooのページから拾うという手はどうでしょうか？

**Comment by ryo-a** [comment]
Yahooからのスクレイピングは規約的に不安があります。もしYahooさんからデータが入手できるならそれでも良いのですが。

**Comment by GinSanaduki** [comment]
こんにちは。
Yahoo! Japanの運行情報サイトは特にWebスクレイピングは禁止されていないです。ヤフー的には、グレーゾーンだね、といって、お目こぼし状態なのでしょうかね。
https://qiita.com/hirohiroto522/items/6ff29be1344be805ecb0
yahoo路線の運行情報を取得したい - Qiita
```

後日談：yahooの人に見せたら、「グレーゾーンだね」と言われたのは内緒

```

Yahoo! Japanの運行情報サイトのrobots.txt、HTMLコードにもrobotsに関する記述はないので、半日に1回なり、3時間に1回なり、取り直してやればいいんじゃないでしょうか。書かれたら、また考え直す、と。

公共交通オープンデータ協議会がらみのは、アクセストークン出さなければソースコード公開可能、というルールがあるので、アクセストークンをいちいちユーザー登録しないともらえないので、おすすめしません。お膳立てがややこしすぎるので。

https://qiita.com/richmikan@github/items/6de979e7608180956862
東京メトロのWebAPIを叩くシェルスクリプト書いてみた - Qiita

```
WebAPIの仕様はコンテスト応募予定者限定公開なので作ったソースコードも公開はできないのかなと思っていたら、開発者フォーラム内で「アクセストークン(後述)出さなければソースコードも公開OK」という回答があったので、
（・・・）
あ、ユーザー登録をして、アクセストークンを貰ってくるのを忘れんようにな。それがないとこのアプリは動かせないぞ。

```

**Comment by kaizumaki** [comment]
@ryo-a ご提案ありがとうございます。たいへんお待たせしてしまい申し訳ありません。こちらのissueについて東京都に確認いたしました。件については東京都交通局の確認が必要になりますが、現時点では重要度が下がってきておりますので、今後状況の変化に応じて必要になれば再検討したいと思います。ですので、こちらのissueは一旦クローズさせていただければと思います。

**Comment by kaizumaki** [comment]
東京都からの回答がありましたので、こちらのissueはクローズいたします。
