### ISSUE TITLE
TITLE 修正

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#250]
今は

`東京都 新型コロナウイルス対策サイト - covid19`

となっていますが、` - covid19` はいらないですよね。

**Comment by kaizumaki** [comment]
そうですね。
逆に、全ページ同じタイトルですが、それはそれでいいのでしょうか？

**Comment by forestgtree** [comment]
トップページから遷移した場合、アクセシビリティ的には、本文初めの見出しにh1が振られているのが望ましいです。

**Comment by halsk** [comment]
確かに、`ページタイトル | 東京都 新型コロナウイルス対策サイト` にしましょうか

**Comment by sonatax** [comment]
@halsk こちら対応します。
各ページタイトルはサイドメニューに書いてある文字列で対応しときます。
もし他にタイトル変更してくれってのがあれば対応しますので言ってください。
