### ISSUE TITLE
print対応

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#251]
印刷されることを少し考えた方がいいかもしれません。
いまのところ、flowページがデスクトップ版とモバイル版の両方が印刷されてしまうようです（ `display: none` で処理している部分）。

**Comment by halsk** [comment]
おおお。そうですね

**Comment by hkomamiy** [comment]
再現してtryしてみます。

**Comment by hkomamiy** [comment]
印刷ページごとに1枚にフロー図が途中で切れないようにします。
メニューリンクとスマホを印刷から版消します。

現状、SVGが一枚の高さなので途中で画像が
切れないように、1ページ目の下部分が空白ができます。
PDF印刷時のプレビューを添付します。こちらでも取り急ぎ大丈夫でしょうか？
[新型コロナウイルス感染症が心配なときに _ 東京都 新型コロナウイルス対策サイト.pdf](https://github.com/tokyo-metropolitan-gov/covid19/files/4286506/_.pdf)

**Comment by kaizumaki** [comment]
@hkomamiy おお！すばらしい！ありがとうございます。念のため他のページも確認してもらっていいでしょうか？

**Comment by hkomamiy** [comment]
@kaizumaki 
他ページ部分の印刷スクショです。一応tableの中身も全て印刷されるように対応しました。
都内の最新感染動向 _ 東京都 新型コロナウイルス対策サイト.pdf
