### ISSUE TITLE
都内の最新感染動向ページが読み込まれた時、陽性患者の属性の公表日を降順(現在から過去へ)で表示する

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#2525]
## 改善詳細 / Details of Improvement
`都内の最新感染動向`ページが読み込まれた時、`陽性患者の属性`の`公表日`を降順(現在から過去へ)で表示する。

2020/03/29現在は、並び替えられていない為、`公表日`は最初の日から列挙され、昨日どうだったかを知るのに時間がかかっている。

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected behavior
「誰が、どこで、発症したのか」を、最初から見るよりも、現在から過去に遡って見る方が、短時間で最近の動向を把握できる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
すみません。現在、陽性患者の属性の表は降順になっていませんか？

**Comment by masanori1102** [comment]
現象は、私のmacOS Xでは、FireFoxのみスーパーリロードが効いていなかった事が原因と分かりました。
(SafariとChromeはOKでした)

バージョン
- macOS X
   ```bash
   $ sw_vers
   ProductName:	Mac OS X
   ProductVersion:	10.15.4
   BuildVersion:	19E266
   ```
- FireFox
   ```bash
   $ cd /Applications/Firefox.app/Contents/MacOS
   $ ./firefox -version
   Mozilla Firefox 74.0
   ```

**Comment by kaizumaki** [comment]
@masanori1102 すみません！こちらの件、IE11とEdgeで昇順になってしまっていることが確認されました。よろしければ原因を調査していただけますと助かります。

**Comment by nouka** [comment]
@kaizumaki @masanori1102 横からで申し訳ありません。
調査してみたところ、Firefoxで再現できましたのでPRを立てました。
原因に関してはPRに記載しましたので、ご参照ください。

自分の環境ではEdgeでは再現しませんでした。

**検証環境**

- macOS Catalina 10.15.4
- Firefox 74.0
- Chrom 80.0.3987.149
- Edge 80.0.361.106
