### ISSUE TITLE
陽性患者の属性の各列にフィルターを追加する

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#2526]
## 改善詳細 / Details of Improvement
陽性患者の属性の各列にフィルターを追加する

## スクリーンショット / Screenshot
無し

## 期待する見せ方・挙動 / Expected behavior
フィルタリングを追加する事によって、条件別の人数などを探しやすくなる

フィルタリングの条件
- Must
   - 現在列に表示されている項目を元に、列をフィルタリングできる
   - フィルタリングを解除できる
   - フィルタリングは解除されるまで保持される
   - `都内の最新感染動向`ページを読み込んだ時に、全てのフィルタリングを解除する
- Want
   - フィルタリングする際、テキスト入力により、候補を制限することができる
   - フィルタリングする際に、候補の隣に一致する数を表示する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@masanori1102 ご提案ありがとうございます。こちらのissueについて都に確認しまして、採用しないという結論にいたりました。詳細はこちら https://github.com/tokyo-metropolitan-gov/covid19/pull/3516#issuecomment-617530810 にコメントいたしました。どうかご理解のほどお願いいたします。

**Comment by kaizumaki** [comment]
都からの正式な回答がありましたので、こちらのissueはクローズさせていただきます。
