### ISSUE TITLE
[Improvement] Wanted to know figures per Ward out of 23 区毎の数値を知りたい

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#2527]
## 改善詳細 / Details of Improvement
- (EN) At least, wanted to know the number of cfm'd cases per Ward plus its chart as well
- (JA) 少なくとも陽性患者数は、区ごとの数値とグラフを見たい

## 期待する見せ方・挙動 / Expected behavior
- (EN) Each number would be broken down into 23 Wards and other areas in Tokyo so that people in each Ward/area can see the progress of increase/decrease
- (JA) 数値が 23 区および都内の他地域に分割されることで、各地域における感染者数の増減度合いを当該地域の住民が知るところとなる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
いちおう改善提案ということで上げてみましたけれども、出した端から、これ、いろいろと問題を孕んでいると思っています。
- そもそも、区ごとのデータが取れるのか？
- あるいは、それぞれの区や地域が持つデータとのインターフェースが必要なのでは？
- 区や地域ごとに数値を示すことで、とくに数字の上昇度が高い地域への差別感情をオーディエンスに惹起させないか？

**Comment by mcdmaster** [comment]
上記の私のコメントの特に三番目を踏まえた上で、 #2706 にマージしましょうか？
地図上にプロットされるなら、なおさら三番目の懸念は増すと私は考えます

**Comment by hanyo** [comment]
区だけでなく、市区町村の状況が確認できると、尚良いと思います。
地域間差別の問題もありますが、緊急事態ということもあり、
そういうことを言える時間は無いものと考えます。

**Comment by mcdmaster** [comment]
@hanyo さん

もちろん、私は 23 区外、いわゆる「都下」と呼ばれる地域についても言及するつもりでした。言葉足らずでしたね。

ちなみに、`need-official-confirmation` `waiting-for-confirmation` の両タグがついているイシューは都の職員の方のご判断を仰いでいる最中であることを示しています。まずは、お答えを待ちましょう。

蛇足ですけど、スピードと差別リスクの有無とを天秤に掛けるのは少なくとも私にとっての納得感を欠きます。これは、近しい親族内に重度障害者がいることで一族郎党差別を受けた経験から言っています。まあ、心の片隅にでも置いておいていただけますとありがたいです。

**Comment by hanyo** [comment]
@mcdmaster
確かに、そうですよね。
大変難しい問題です。

もう少し、ほかの意見も聞きたいと思います。

**Comment by mcdmaster** [comment]
本件、クローズを提案します。その根拠は、以下のページの公表によります。
https://www.fukushihoken.metro.tokyo.lg.jp/hodo/saishin/corona148.html

オープンソースとはいえ、本プロジェクトのサイトも「都のサイト」です。
形や部局の違いはあれど、結果として一個の自治体からのアウトプットが冗長になるとしたら、ダブルワークの印象をオーディエンスに与えかねません。

現時点で `waiting-for-confirmation` のラベルがついています。本件のクローズの可否についても併せてご検討をいただけますなら幸いです

**Comment by ocean3fish** [comment]
ありがとうございます。
このあたりは内部でも色々検討を進めている中なので、お申し出頂いた通り一旦クローズとさせて頂きます。
ご検討進めて頂いた内容はぜひ参考にさせて頂きたいと思います。

**Comment by mcdmaster** [comment]
早速のご対応をいただき、ありがとうございます
