### ISSUE TITLE
Axe を無効にするオプションをREADMEに追記する

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#2549]
## 改善詳細 / Details of Improvement
- #2545 で、`yarn dev-no-axe` のオプションが追加されたので、README も更新したほうが良い

**Comment by shunito** [comment]
こちら、日本語版だけでよろしければ自分で書かせていただきます。

**Comment by halsk** [comment]
ありがとうございます！日本語だけでOKです。
他の言語には、
[PLEASE TRANSLATE ME]
[/PLEASE TRANSLATE ME]
で囲って、記入しておいていただけると良いです。
