### ISSUE TITLE
トップページのHeatmap.vueの遅延読み込み

### ISSUE THREAD

**Issue by kzhrk** [tokyo-metropolitan-gov/covid19#2573]
## 改善詳細 / Details of Improvement
- 人口推移マップが画面に表示されてから読み込みを開始する
  - トップページアクセス時にマップ表示に関わるpbfファイルが約25MBロードされている

## スクリーンショット / Screenshot
<img width="1440" alt="スクリーンショット 2020-03-30 0 41 22" src="https://user-images.githubusercontent.com/548508/77853495-5a22bc80-721f-11ea-8ba7-65b87ae133db.png">

## 期待する見せ方・挙動 / Expected behavior
- Heatmapコンポーネントが画面に入るまで、マップデータの取得を行わない

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
ありがとうございます！この辺、色々チューニングできていません。

**Comment by kzhrk** [comment]
[Intersection Observer API](https://developer.mozilla.org/ja/docs/Web/API/Intersection_Observer_API)を使えば対応できそうです。
IE11非対応のAPIなので「IE11では遅延読み込みをしない」 or 「windowのload/scroll/resizeイベントでFallback対応」する必要があります。
モバイル通信時のパケット消費が一番の問題かと思いますので、ひとまず「IE11では遅延読み込みをしない」でPRつくろうかと思いますがいかがでしょうか。
（PR出せるのは夜中になるかと思います… 😿）
