### ISSUE TITLE
埋め込み時に「日別/累計」のデフォルト値を変更したい

### ISSUE THREAD

**Issue by takahashim** [tokyo-metropolitan-gov/covid19#2574]
## 改善詳細 / Details of Improvement
- TimeBarChart.vueを使ったcardを埋め込み用コードを使って他サイトに埋め込んだ際、「日別/累計」のデフォルト値を変更できるようにしたいです
    - ちなみに派生サイトでは「日別/累計」のデフォルトを変更している場合があったりします

## 期待する見せ方・挙動 / Expected behavior
- `https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases?embed=true&dataKind=cumulative` にアクセスする
    - 累計で表示される
- `https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases?embed=true&dataKind=transition` にアクセスする
    - 日別で表示される
- #2162 で通常表示時のデフォルト値の変更が検討されていますが、それにも依存しないようになっていると良さそうです。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by halsk** [comment]
このオプションの存在をどこかに記しておきたいですが、どうするのが良いですかね

**Comment by takahashim** [comment]
* pages/about.vue に書く（サイト利用者向け）
* README.md に書く （開発者全般向け）
* README.mdの内容を整理しつつ開発者向けドキュメントを新たに作り、そこに書く （一部開発者向け）

のどれかでしょうか…？

**Comment by takahashim** [comment]
「当サイトへのリンクについて」で埋め込み機能について触れておくのも良いかもしれません。あとで文言書いてPRしてみます。
