### ISSUE TITLE
新型コロナコールセンター相談件数の棒グラフから1日分の値が抜け落ちている

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#258]
1/29：23
が入るはずです。

もしかすると、この日だけ時間帯によってNULLなのが集計処理に影響しているかもしれません。
9-13時：NULL
13-17時：NULL
17-21時：23

#248 より。

**Comment by NaoyaShimizzz** [comment]
29日のデータをNullから0にしておきました。これでどうでしょうか？

**Comment by mikkame** [comment]
こっちでバッチ修正してます〜

**Comment by halsk** [comment]
反映されましたので確認してもらえますか？ @ocean3fish

**Comment by ocean3fish** [comment]
不具合が解消されていることを確認しました！
累計値もピッタリになったので、このデータに関しては異常なしです！

**Comment by halsk** [comment]
確認ありがとうございました！
