### ISSUE TITLE
グラフの縦対数化

### ISSUE THREAD

**Issue by yu1ro** [tokyo-metropolitan-gov/covid19#2580]
## 改善詳細 / Details of Improvement
- 増加数が指数関数的に増えている状況ですので、縦軸を対数グラフにするオプションを設けると良いかと考えます。

## スクリーンショット / Screenshot
こちらなどです
![image](https://user-images.githubusercontent.com/5813112/77867617-f629e380-7272-11ea-8d55-265776f9dba9.png)

## 期待する見せ方・挙動 / Expected behavior
- 対数グラフを選択できること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

## 備考
例えばこういった記事では対数グラフでの比較がなされています
https://blogs.itmedia.co.jp/honjo/2020/03/post_55.html

**Comment by ocean3fish** [comment]
@yu1ro 
ご提案頂きありがとうございます。
対数軸はやや専門的な見せ方になるため、ミスリーディングにつながらないように注意を払う必要がありますね。

その点で懸念しているのが、まずすでにミスリーディングを促すコンテンツが世の中に出回ってしまっていることです。
指数関数的な増加傾向から外れたら安心！といった誤解をしている人も多く見受けられます。

また、東京都単体の場合、グラフを見て頂けるとわかるように、曜日によって検査実施数が異なるため、検出される陽性患者数にも曜日による影響が出るはずです。
その点を考慮せずに対数軸に陽性患者数を載せてしまうと、おそらく実際の傾向とは無関係に傾向線から外れるプロットが出てくるはずなので、ミスリーディングにつながる恐れがあります。

そういった曜日による影響を考慮して処理を行う方法も考えられますが、さらに専門性の高い分析になるため、様々な方がご覧になるコンテンツとして適さないものになってしまう懸念があります。
また、多くの検証が必要になるため、日々の迅速な情報発信に支障をきたす可能性もあります。

以上の観点から、公式情報としての発信は難しいグラフではないかと考えます。

**Comment by kaizumaki** [comment]
@yu1ro ご提案ありがとうございます。こちらのissueについて都に確認いたしました。対数グラフは読み解くのが難しいという懸念があります。しかもデータが日ごと・曜日ごとにバラツキがあるので、対数グラフが誤解を生む可能性があります。ですので、こちらの提案を採用するのは難しいです。ご理解いただきますようお願いいたします。

**Comment by yu1ro** [comment]
@ocean3fish @kaizumaki 
不採用とその理由承知しました。
ご検討いただきありがとうございます。
