### ISSUE TITLE
トップページ上部の「最終更新 」の時間表記が日本標準時になっていない

### ISSUE THREAD

**Issue by 0x0u** [tokyo-metropolitan-gov/covid19#2586]
## 起こっている問題 / The Problem
- トップページ上部の「最終更新 」の時間表記が日本標準時になっていない

## スクリーンショット / Screenshot
<img width="542" alt="スクリーンショット 2020-03-30 13 43 59" src="https://user-images.githubusercontent.com/34241526/77875952-9b9d8100-728c-11ea-8545-0940cbf9a224.png">

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by jun-a** [comment]
見る限り、動的更新ではなくdata.jsonに記載の最終更新日時を取得しているように見受けられた。

以下の部分を変更すれば解消されるかと思います。
https://github.com/tokyo-metropolitan-gov/covid19/blob/1275b69e628a463c5daf30f59a6a2b4fee9ceb0d/data/data.json#L5472

**Comment by kaizumaki** [comment]
ご指摘ありがとうございます！こちら現在、調査中です。

**Comment by kaizumaki** [comment]
表題の件、こちらの入力ミスでした。修正しました。ご指摘感謝です 🙇‍♀ 
こちらのissueはクローズさせていただきます。
