### ISSUE TITLE
meta descriptionタグへ「更新日」の記載を追加する

### ISSUE THREAD

**Issue by jun-a** [tokyo-metropolitan-gov/covid19#2587]
### 1. <head>タグへ記載の以下2箇所におけるcontent属性へ「更新日」を文頭へ追加する
`<meta data-n-head="ssr" data-hid="description" name="description" content="当サイトは新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するために、東京都が開設したものです。">`

`<meta data-n-head="ssr" data-hid="og:description" property="og:description" content="当サイトは新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するために、東京都が開設したものです。">`
　
　
### 2. 追加する更新日のフォーマット
`YYYY年MM月DD日更新：`
　
## スクリーンショット / Screenshot
<details>
<summary>PCでのビフォーアフター</summary>

#### ビフォー
<img width="747" alt="PC-ビフォー" src="https://user-images.githubusercontent.com/9759922/77879543-a0b2fe00-7295-11ea-83bd-fbe90cdae135.png">

#### アフター
<img width="737" alt="PC-アフター" src="https://user-images.githubusercontent.com/9759922/77879555-a577b200-7295-11ea-853c-a32fc6dd3c37.png">

</details>

<details>
<summary>SPでのビフォーアフター</summary>

#### ビフォー
<img width="418" alt="SP-ビフォー" src="https://user-images.githubusercontent.com/9759922/77879635-c93af800-7295-11ea-96ee-ec90e7c26aa6.png">

#### アフター
<img width="421" alt="SP-アフター" src="https://user-images.githubusercontent.com/9759922/77879641-cf30d900-7295-11ea-8e6c-63fad41f5170.png">

</details>

## 期待する見せ方・挙動 / Expected behavior
- Googleの検索結果表示欄・サイト説明文(descripiton)へ「最終更新日」の記載があること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by f-koki** [comment]
こちら着手いたします。

**Comment by devrolerole** [comment]
@jun-a 
[default.vue](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/layouts/default.vue) に最終更新日を付記するイメージで実装してみればよいでしょうか？
であれば着手したいと思います。

**Comment by jun-a** [comment]
@devrolerole 
> @jun-a
> [default.vue](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/layouts/default.vue) に最終更新日を付記するイメージで実装してみればよいでしょうか？
> であれば着手したいと思います。

左様です！大変うれしいです。ぜひよろしくお願いいします。

**Comment by devrolerole** [comment]
@jun-a 
ローカルの開発環境が具合悪く自己テストに時間を要してしまいそうです。
軽くテストができる環境などお知恵があればください。
その他、確認したいこと
- i18n 対応は今回は無しでよいですか？　例：最終更新日　⇒　Last Update
- 最終更新日は javascript の document.lastModified で取得しようとしておりますが、この場合、ページは動的生成なので、アクセスした現在時刻が表示されてしまいそうで、イメージが異なりますでしょうか？  

的外れでしたら申し訳ありません。

**Comment by kaizumaki** [comment]
ご提案ありがとうございます！こちらの件、現在関係各所に確認にまわしています。
最終更新日については、サイトでは `data.json` を参照していますので、meta descriptionも同様にしてもらえるといいかなと思っています。
https://github.com/tokyo-metropolitan-gov/covid19/blob/0eb19dfcb674ff7398f39159f9136b458fd98d62/pages/index.vue#L7-L9

**Comment by kaizumaki** [comment]
こちら、都側の確認済みです。ぜひ実装していただきたく、よろしくお願いいたします。

**Comment by jun-a** [comment]
@devrolerole 
僭越ながら、コメントさせていただきます。

>i18n 対応は今回は無しでよいですか？　例：最終更新日　⇒　Last Update
今回は無しでお願いします。

>最終更新日は javascript の document.lastModified で取得しようとしておりますが、この場合、ページは動的生成なので、アクセスした現在時刻が表示されてしまいそうで、イメージが異なりますでしょうか？
@kaizumaki さんがおっしゃるとおり、`{{ Data.lastUpdate }}`のような、data.jsonから取得する形式でいただければと思います。
( 動的に時間を表示する必要はございません )

**Comment by devrolerole** [comment]
@kaizumaki @jun-a 
アドバイスありがとうございました。
 `{{ Data.lastUpdate }}` を用いて以下のように実装を試みたところ、`Cannot read property 'lastUpdate' of undefined` が生じてしまいました。 
回避策を調査中です。お知恵あれば拝借したいです。

    --- default.vue  
    +++ default.vue
      35 import Vue from 'vue'
      36 import { MetaInfo } from 'vue-meta'
    + 37 import Data from '@/data/data.json'
      38 import ScaleLoader from 'vue-spinner/src/ScaleLoader.vue'
      39 import SideNavigation from '@/components/SideNavigation.vue'
      40 import NoScript from '@/components/NoScript.vue'
      41 import DevelopmentModeMark from '@/components/DevelopmentModeMark.vue'
    + 42 import { convertDateToISO8601Format } from '@/utils/formatDate'
      43
      44 type LocalData = {
      (snip)
      114           hid: 'description',
      115           name: 'description',
    - 114           content: this.$tc(
    + 116           content:
    + 117             this.$t('最終更新日：') +
    + 118             convertDateToISO8601Format(this.$data.Data.lastUpdate) +
    + 119             ' ' +
    + 120             this.$tc(
      121               '当サイトは新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するために、東京都が開設したものです。'
      122             )
      123         },
      (snip)
      150         {
      151           hid: 'og:description',
      152           property: 'og:description',
    - 148           content: this.$tc(
    + 153           content:
    + 154             this.$t('最終更新日：') +
    + 155             convertDateToISO8601Format(this.$data.Data.lastUpdate) +
    + 156             ' ' +
    + 157             this.$tc(
      158               '当サイトは新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するために、東京都が開設したものです。'
      159             )
      160         },

**Comment by jun-a** [comment]
@devrolerole 
ありがとうございます！

ごめんなさい...vueに対して全くの無知なので、エラー文を検索することぐらいでしかお力になれそうにありません...

`Cannot read property 'lastUpdate' of undefined` というエラーは、以下の記事によると、
[Cannot read property 'fuga' of undefined　とは](https://qiita.com/nakamaru/items/3e11bb5b0d586a6d5545)

> fuga がundedinedなんじゃなくて、
> 「undefinedにある'fuga'property（名前付きの値）は読み込めません。」
> という意味になる。
> ということはfugaの前のオブジェクトがundefinedだということ。
> 

とのことでしたので、今回のケースでは、
`this.$data.Data.lastUpdate`  のDataオブジェクトがundefinedなのかなと思います。

後は推測になってしまいますが、このDataオブジェクトがundefinedになるのは、this.$dataから引いてる可能性があるのかな...と推察しました。(他ファイルにてimportした関数の使い方を見ているとです...)

`{{ Data.lastUpdate }}`  をそのまま記載いただいて、動かない場合は僕の方ではこれ以上お力になれそうにありません...。よろしくお願いします！

**Comment by devrolerole** [comment]
@jun-a 
ありがとうございます。おっしゃる通り `Data.lastUpdate` をそのまま呼ぶことで、エラーは解消しました。このあとプルリクを発行しますので、一度レビューいただけるでしょうか？
※書式はもともと定義済みのメソッド `convertDateToISO8601Format` が流用できたので 最終更新日：YYYY-MM-DD の形式としましたが、当初の指示 YYYY 年 MM 月 DD 日更新の書式が必要でしたらご指示ください。

**Comment by jun-a** [comment]
@devrolerole 
大変、ありがとうございます！


>当初の指示 YYYY 年 MM 月 DD 日更新

こちら、ユーザビリティを考慮すると日本語表記にした方が、優しいと思いますので...ぜひ当初のフォーマットで処理いただけると嬉しいです。

**Comment by jun-a** [comment]
@devrolerole 
ただ、このサービス全体を通してフォーマットを統一しているようなので(多言語化も踏まえてでしょうか...)、YYYY-MM-DD フォーマットでも大丈夫です。

その場合、以下の様に変更可能でしょうか？

### 変更する表示形式
`YYYY/MM/DD 更新：　`
※DDと更新の間に半角スペース / ダブルコロンは全角 / ダブルコロン直後に全角スペースの追加

お願いばかりとなり、すみません。

上記を反映すると、SPで見た場合このような表示になる予定です。
![変更](https://user-images.githubusercontent.com/9759922/78317404-2936e480-759d-11ea-938e-1fb7d1a7dadf.png)

**Comment by kaizumaki** [comment]
ディスカッション中すみません！コードの修正指示などは、PR #2780 のほうに残しておいてもらうと、管理側もわかりやすいです。

**Comment by jun-a** [comment]
> ディスカッション中すみません！コードの修正指示などは、PR #2780 のほうに残しておいてもらうと、管理側もわかりやすいです。

こちら、承知しました！

**Comment by devrolerole** [comment]
@jun-a 
ご指示ありがとうございます。
以下書式で追加コミットしましたので確認をお願いします。

`YYYY/MM/DD 更新：　`　
※DDと更新の間に半角スペース / ダブルコロンは全角 / ダブルコロン直後に全角スペースの追加`

日付フォーマット`YYYY/MM/DD`を追加するために utils/formatDate.ts にフォーマット`convertDateToSimpleFormat`を追加しました。

PR#2780 にも転記します。
