### ISSUE TITLE
【iOS】言語選択セレクトボックスにフォーカスの際に画面がズームしてしまう

### ISSUE THREAD

**Issue by rm-labo** [tokyo-metropolitan-gov/covid19#2591]
## 改善詳細 / Details of Improvement
- iPhoneにおいて、ハンバーガーメニュー内、言語選択を押した際に画面がズームしてしまう
- ページをスムーズに閲覧するために、ピンチで画面を戻さなければならない

## スクリーンショット / Screenshot
![camp](https://user-images.githubusercontent.com/12590315/77891632-33f72e00-72ac-11ea-8d63-a0925cc88a33.jpg)

## 期待する見せ方・挙動 / Expected behavior
- ズームを発生を抑える

### 解決案
`.LauguageSelector-Menu` の `font-size` が `16px` 以上であればズームは発生しなくなるが、PCで閲覧した際に `やさしい にほんご` がギリギリ入らないため、スマホサイズの画面でのみ `font-size` を大きくするなどの工夫が必要。

▼ PCで見た際の注意
<img width="255" alt="スクリーンショット 2020-03-30 17 12 21" src="https://user-images.githubusercontent.com/12590315/77891648-3b1e3c00-72ac-11ea-9d4d-1b8da789ed04.png">

## 動作環境・ブラウザ / Environment
- iOS

**Comment by amotarao** [comment]
issue / PR
#681 / #854 で実装
#1204 / #1253 で今回と同様のズーム問題修正も、別の問題が発生(タップ可能範囲が狭くなった)
#1643 #1745 / #1775 でタップ可能範囲の問題修正も、ズーム問題再発

**Comment by rm-labo** [comment]
@amotarao 
経緯をまとめて頂きありがとうございます。
重複大変恐れ入ります。大変お手数をおかけいたしました 🙇

**Comment by amotarao** [comment]
@rm-labo 重複ではないと思いますー！

#1775 では
>iPhone8 iOS13.3.1上のSafari/ChromeおよびiPad Pro iOS13.3.1 Safari/Chromeにて #1204 を再現しないことを確認。

とあるのですが、環境を詳細に記載していただけると！

**Comment by Takas0522** [comment]
iPhone 7 Plus / iOS 13.3.1 / Safari / Chrome で発生を確認。
iPad Gen6 / iOS 13.3.3 / Safar /Chromeは発生しませんでした。

こちら。対応しようと思います。
