### ISSUE TITLE
i18n vi-VN ベトナム語対応に関して

### ISSUE THREAD

**Issue by vochicong** [tokyo-metropolitan-gov/covid19#2603]
#1985 関連です。

ベトナム語への翻訳がほぼ完成していたのですが、日本語が混じっていたりしたので、#2596 修正して、数値としては100%完成の状態になりました。ただし、誤訳や言葉遣いの不統一が散見されます。お手伝いできればと思うので、進め方についてご相談させてください。

## 改善詳細 / Details of Improvement

- フィーチャーブランチで、言語選択にベトナム語を追加して、翻訳者が目視確認できる環境を作る
- ベトナム語翻訳のレビュー・修正のフローを定義（Transifix でのレビュー含む）

### 325 unreviewed on transifex
![image](https://user-images.githubusercontent.com/123111/77908301-35cdeb00-72c6-11ea-9116-6ce7e6d6f96f.png)

### ローカル開発環境におけるベトナム語の表示
![image](https://user-images.githubusercontent.com/123111/77907660-f226b180-72c4-11ea-9c85-6f2b57c3f792.png)

### エンドユーザーとして
- ベトナム語を選択できる
- 正しいベトナム語訳が表示される

### 翻訳者・開発者として
- できれば、レビュー作業は Transifix で効率的に行いたい
- 翻訳結果を簡単にテスト環境のサイトで確認したい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by vochicong** [comment]
nuxt-i18n.config.ts などで `if (process.env.NODE_ENV == 'development')` なら、ベトナム語を locales に追加するというやり方はどうでしょうか。開発環境とステージング環境でベトナム語が確認できるようになるのでしょうか。

**Comment by kaizumaki** [comment]
ご提案ありがとうございます。 PRにコメントしましたとおり（ https://github.com/tokyo-metropolitan-gov/covid19/pull/2636#issuecomment-932852593 ）こちらの対応は難しいです。ですので、こちらのissueはクローズとします。申し訳ありません。
