### ISSUE TITLE
WebPush対応してください

### ISSUE THREAD

**Issue by Mizogaki** [tokyo-metropolitan-gov/covid19#2604]
## 改善詳細 / Details of Improvement
- WebPushでサイト内の更新データを毎日送ってください。

## 期待する見せ方・挙動 / Expected behavior
![download](https://user-images.githubusercontent.com/11548811/77909557-89d9cf00-72c8-11ea-89d6-433f6ede68f0.jpg)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / Android
- Chrome / Safari / Firefox / Edge

**Comment by kazuhirokomoda** [comment]
もし実装するなら、[OneSignal](https://onesignal.com/)か[Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging)で定期的にプッシュ通知を実行、というのがおそらく有力な選択肢になるんでしょうか。
`@nuxtjs/pwa`が導入済みなので、[導入だけならOneSignalの方が簡単](https://pwa.nuxtjs.org/modules/onesignal.html)なのかもしれないですね。

**Comment by Mizogaki** [comment]
@kazuhirokomoda 
>導入だけならOneSignalの方が簡単
そうですね！ インフラ環境にもよりますが、GCP使っていないと思うので！
OneSignalの方が早いですね！

WebPushの内容は「東京都コロナウイルス対策サイト内のデータが更新されました。」だけで良いと思います。
WebPushの開封率が高くなれば、様々な施策を提案できると思います。

**Comment by kaizumaki** [comment]
こちらはだいぶ時間が経ってしまったのと、実現可能性が低いと思われますので、クローズといたします。
