### ISSUE TITLE
都知事の3/30の記者会見を「最新のお知らせ」に追加

### ISSUE THREAD

**Issue by asterisk37n** [tokyo-metropolitan-gov/covid19#2605]
## 改善詳細 / Details of Improvement
- 「最新のお知らせ」に3/30 20:30-21:30の知事の緊急記者会見のリンクを追加 (現在まだ知事のサイトでは動画もリンクもない。知事のサイトが更新されたら作業開始。Youtubeに動画を載せている通信、報道社があるが、二次ソースとなるので、できれば知事のサイトへのリンクがよい。)

https://www.metro.tokyo.lg.jp/tosei/governor/governor/index.html

## 期待する見せ方・挙動 / Expected behavior
- 「最新のお知らせ」のリンクをふむと、記者会見の動画へ飛ぶ

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
「最新のお知らせ」については、都側が入力する元データを自動で反映させていますので、こちらでの対応は難しいと思います。

**Comment by asterisk37n** [comment]
そうだったのですね！失礼しました。

**Comment by kaizumaki** [comment]
@asterisk37n ご理解いただきありがとうございます。こちらのissueはクローズさせていただきますね。
