### ISSUE TITLE
スクロールバーがコンテンツのすぐ横に来ている

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#261]
こちらコンテンツ側に `overflow-y` をかけるのではなく、ナビゲーションを固定してページ全体をスクロールするようにしてください。

不自然な見た目になってしまうのと、ウインドウ幅を狭くした時にスクロールバーが２本並んでしまうのをさけたいです。

<img src=https://user-images.githubusercontent.com/1301149/75778897-021da500-5d9c-11ea-9b59-bf82a85adb2c.png width=30%>

**Comment by kaizumaki** [comment]
これ私が施した処理なので、私に修正させてください！ナビゲーションの固定については相談させてください。

**Comment by kaizumaki** [comment]
@saladdays 単純にメインコンテンツのoverflowをとったものが以下になります。
サイドナビのアイテムが増えたのもあって、サイドナビを固定するいい方法が思いつきません・・・
どういう表示が理想ですか？
![remove_overflow](https://user-images.githubusercontent.com/14883063/75841540-56af3780-5e11-11ea-8f9d-b35113e7dfb0.gif)

**Comment by saladdays** [comment]
@kaizumaki ありがとうございます！いつのまにやらたしかにサイドナビが多くなりましたね（汗

ではがサイドナビは位置固定しつつ、その中でスクロールをできるようにしましょうか。
ブラウザ側のスクロールにはコンテンツのみ追従して、サイドナビはその中でだけoverflow-yをかけましょう！

**Comment by kaizumaki** [comment]
@saladdays 了解です！

**Comment by kaizumaki** [comment]
@saladdays このようにしてみました（プルリク中）。いかがでしょうか？（わかりにくかったらごめんなさい！）
![fixed-sidenavi](https://user-images.githubusercontent.com/14883063/75874950-1faf4500-5e56-11ea-90e1-dc3c4ae724f0.gif)
