### ISSUE TITLE
地図の塗り分けのカラーユニバーサルデザイン対応

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#2624]
## 改善詳細 / Details of Improvement
https://github.com/tokyo-metropolitan-gov/covid19/issues/2364?fbclid=IwAR1_vjcxryJAgiAZZTui7s8d_5tpYUISGDTsijxNoFSKTY5VIxG23sjQpCA#issuecomment-605622474 にて @Koiggy より指摘。地図の塗り分けにおいて、特定色覚では人口数と色のグラデーションが対応していないように見える。また建物の有無の表現において誤認の恐れがある。

以下転載：

地図の塗り分けについて。P型（１型２色覚）とD型（２型２色覚）の印象を申し上げます（参考にアドビシステムズの色覚シミュレーション画像を提示します）
![77847882-44030500-71fb-11ea-8c51-d58929ebc69a](https://user-images.githubusercontent.com/17713513/77920362-594e6100-72d9-11ea-8d3c-664c21d6f001.jpeg)

４段階の地図の塗り色の内
凡例において
0〜75000と150000〜225000と225000〜の３色は同系色（黄色系）の濃度差として捉えられます。
75000〜15000だけは別の色相の色（青い色系列）として捉えられます。

そうしますと、これらは薄黄、薄青、中黄、濃黄　の順に並んで感じられます。
これがもし　薄青、薄黄、中黄、濃黄　なら自然なグラデーションに感じられると思います。

※１元になった地図に「建物の無いところは白、あるところは灰色（あるいは灰色に見える細かいハッチング）」がありますと、色弱の人には誤認が生じます。この例で言いますと、色弱の人は黄色系の薄い黄色、中黄色、濃い黄色と３色の濃度差で見分けていた物が、背景に2色あると、薄い黄色、薄い黄色に灰色が重なった色、中黄色、中黄色に灰色が重なった色、濃い黄色、濃い黄色に灰色が重なった色　と６種の濃淡を判別することになります。たとえば薄い黄色に灰色が重なった色と、濃い黄色が同じ色に見えるなどの問題が起きてきます。そういったことから、必要が無ければ白地図は白のままで灰色部分がない事が望ましいと思います。

※　地図に色を付ける場合に、ハザードマップなどの場合には、その危険度合いが多様な色覚にも対応して危険度合いの傾斜度が感じられるように調整します。気象庁　気象庁ホームページにおける気象情報の配色に関する設定指針　平成２４年報告　
![77848047-c2ac7200-71fc-11ea-9fe9-78841e898a98](https://user-images.githubusercontent.com/17713513/77920379-5d7a7e80-72d9-11ea-851d-2dbef4cb3298.jpeg)

## 期待する見せ方・挙動 / Expected behavior
- 色覚特性があっても情報取得に差が生じないよう、色の置き換えを検討する

## 動作環境・ブラウザ / Environment
すべて

**Comment by ocean3fish** [comment]
@magi1125 検討を進めて頂きありがとうございます。
念のためのリマインドですが、現在掲載中の地図は注釈にある通り、2020年3月31日（本日）までの掲載となっております。

現在のところ予定はありませんが、今後もしまた地図でデータを見せるものが出て来た時のために検討を続けて頂くという方法もあると思いますので、本件をクローズするかどうかのご判断はお任せしたいと思います。

**Comment by magi1125** [comment]
@ocean3fish なるほど、ありがとうございます。新しく地図が出てきた際は本件にmentionしつつ新Issueで良さそうなので、本件はcloseしますね。
@Koiggy
