### ISSUE TITLE
お知らせ欄にホバーしたときにリンクの下線を表示

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#263]
下の「自分の家族の〜」はそのような挙動になっているので合わせましょう。

<img src=https://user-images.githubusercontent.com/1301149/75779115-67719600-5d9c-11ea-8e62-f123ad9915e3.png width=50%>

**Comment by kenshir0f** [comment]
本番確認しましたがすでに対応されていました。 🙏
