### ISSUE TITLE
ウインドウ幅を狭くた後にもとに戻しても、グラフの並びがもとに戻らない

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#264]
狭めたときと広げたときでブレイクポイントが違う？

**Comment by halsk** [comment]
#51 と同じ不具合でしょうか？

**Comment by kaizumaki** [comment]
原因わかりました。vuetifyのattributeの設定が違ってました。

**Comment by kaizumaki** [comment]
@saladdays ２カラムの切り替えはbreakpoint 960pxでいいでしょうか？（以下の画像）
グラフの中身が細かいので、これぐらいが適当かなと思いまして。
![responsive_graph](https://user-images.githubusercontent.com/14883063/75842640-392f9d00-5e14-11ea-8589-76693eba49e4.gif)

**Comment by mikkame** [comment]
LGTM
これなおしたら #267 もなおるきがするんです

**Comment by kaizumaki** [comment]
@mikkame ですね。私の手元では表示うまくいってます。
