### ISSUE TITLE
島根県版をFORKED_SITES.mdに追加する

### ISSUE THREAD

**Issue by junkboy0315** [tokyo-metropolitan-gov/covid19#2640]
## 改善詳細 / Details of Improvement
- 島根県版を個人で作成したので、派生サイト一覧に追加したい
- https://covid19-shimane.netlify.com/

追ってPRも作成いたします。

**Comment by halsk** [comment]
#2653 でも島根県版について上がっていますが、全く別の動きでしょうか。
今後の更新も考えると、合流をするのも手ですが、いかがでしょうか？
