### ISSUE TITLE
グラフと表の高さを合わせたい

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#265]
グラフの高さに合わせましょう

ただ、もしやこのグラフは縦横比率を保ちつつ可変、、？

![image](https://user-images.githubusercontent.com/1301149/75779298-bb7c7a80-5d9c-11ea-93d9-4493840b158d.png)

**Comment by halsk** [comment]
#151 で色々試行錯誤しているので、サポートいただけると良いかも。
