### ISSUE TITLE
最新情報がグラフごとにバラバラで一貫性が無く誤解を招きやすい状態を改善したい

### ISSUE THREAD

**Issue by atsushieno** [tokyo-metropolitan-gov/covid19#2652]
## 改善詳細 / Details of Improvement

現在このサイトの設計では、最新情報を素朴にグラフ化して表示しているため、グラフごとに最新情報の日付が異なること（スクリーンショット参照）が、注意深く見ないとわかりません。そのため、「検査数は大きく増大しているのに陽性患者数が激減している??」といった信頼性の低い数字を出しているように見えてしまいます。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/53929/77998713-78e29980-736c-11ea-83da-b257edde619e.png)

![image](https://user-images.githubusercontent.com/53929/77998777-931c7780-736c-11ea-8df3-a3cae48666e8.png)

## 期待する見せ方・挙動 / Expected behavior

- グラフ表示コンポーネントをいじるのは多分しんどいので、人数などを表示している箇所の横に日付を表示するなどの対処ではどうでしょう?
  - 現在: "13人"
  - 提案: "3/30 13人"

## 動作環境・ブラウザ / Environment
- ChromeOS Version 83.0.4091.0 (Official Build) dev (64-bit)
- Chrome

**Comment by kaizumaki** [comment]
@atsushieno ご提案ありがとうございます！たしかにおっしゃるとおりですね。さっそく都側に確認とりまして、フィードバックをいただきました。
「実績値」と書かれている部分に日付をいれてはどうか、とのことです。
`3/30 実績値（前日比:-55人）`
「陽性患者の属性」↓は 「3/30の累計」としているので、それに合わせた形です。
![コメント 2020-03-31 164821](https://user-images.githubusercontent.com/14883063/78000884-e80dbd00-736f-11ea-9ab8-faf75b5fbebb.jpg)

**Comment by atsushieno** [comment]
よさそうです…! 表示変更のインパクトも小さくかつ必要十分そうな大きさになってますね。

**Comment by Aqua-ix** [comment]
こちら、もし未着手であれば私の方で実装してみます。

**Comment by kaizumaki** [comment]
@Aqua-ix お願いします！
