### ISSUE TITLE
島根県サイトの作成

### ISSUE THREAD

**Issue by TaigaMikami** [tokyo-metropolitan-gov/covid19#2653]
## 改善詳細 / Details of Improvement
- 島根県サイトを作成します。

## スクリーンショット / Screenshot
![screencapture-shimane-covid19-netlify-2020-03-31-17_44_01](https://user-images.githubusercontent.com/25325947/78005935-40948880-7377-11ea-98c9-7c3ef16a301f.png)

## 期待する見せ方・挙動 / Expected behavior
https://shimane-covid19.netlify.com/

**Comment by halsk** [comment]
#2640 でも島根県版について上がっていますが、全く別の動きでしょうか。
今後の更新も考えると、合流をするのも手ですが、いかがでしょうか？

**Comment by TaigaMikami** [comment]
気づきませんでした。
全く別の動きですね。

**Comment by halsk** [comment]
一度話し合ってみてはいかがでしょうか。

**Comment by junkboy0315** [comment]
@TaigaMikami 
はじめまして。もう一つの方のサイトを作成した田村です。
少しタイミングが悪かったですね。

誰もやり手がいないのであれば、というくらいの気持ちで作ったものなので
当方のサイトは喜んで閉鎖したいと思います。

既にいくらかユーザーが存在するため、
私のサイトから @TaigaMikami さんの作成されたサイトへリダイレクトしたいと思いますが、
既に運営は開始されている認識でよろしいですか？

リダイレクト元 https://covid19-shimane.netlify.com/
リダイレクト先 https://shimane-covid19.netlify.com/

**Comment by TaigaMikami** [comment]
@junkboy0315 
はじめまして。出雲出身の三上です。

友人や中学校の先生などにも宣伝してしまったので、ありがたいです:bow:
>誰もやり手がいないのであれば、というくらいの気持ちで作ったものなので
当方のサイトは喜んで閉鎖したいと思います。

運営しております。よろしくお願いいたします:bow:
お手数おかけして申し訳ございません。
>既にいくらかユーザーが存在するため、
私のサイトから @TaigaMikami さんの作成されたサイトへリダイレクトしたいと思いますが、
既に運営は開始されている認識でよろしいですか？
リダイレクト元 https://covid19-shimane.netlify.com/
リダイレクト先 https://shimane-covid19.netlify.com/

**Comment by junkboy0315** [comment]
@TaigaMikami 
承知しました。

@halsk 
当方のIssueとPRは取り下げましたので、
こちらの方を進めていただければと思います。
よろしくお願いいたします。

**Comment by halsk** [comment]
中学生！！すごいですね
話がまとまってよかったです。
@junkboy0315 さん、@TaigaMikami さん、今後の運営を一緒にやれれば素敵だと思いました。
こういったサイトは立ち上げるよりもちゃんとサイトを運営していくほうが大変です。
もしよかったら力をあせていただければ。
とりあえず、PRについてはマージしておきます。stopcovid19.jp のサブドメイン、発行できますので必要であればシートに記入してご連絡ください。

**Comment by TaigaMikami** [comment]
@junkboy0315 
ありがとうございます:bow:

@halsk 
写真が中学生なだけで、本体は中学生ではないです:sweat_smile:
仲介ありがとうございました！
