### ISSUE TITLE
新型コロナコールセンター相談件数と帰国者・接触者電話相談センター相談件数が大きいグラフになっている

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#267]
横幅いっぱいのグラフになっていますが意図的なものでか？
@halsk 

MacのChrome最新版で見ています

![image](https://user-images.githubusercontent.com/1301149/75779684-67be6100-5d9d-11ea-8ff5-8ab82b043efb.png)

**Comment by halsk** [comment]
いえ、意図的ではないと思います。2列にしますか？

**Comment by mikkame** [comment]
初期実装時は２列だったはずです・・・

**Comment by ocean3fish** [comment]
ブラウザによるのでしょうか。
こちらFirefoxで表示したものです。
[
<img width="1680" alt="スクリーンショット 2020-03-03 22 27 37" src="https://user-images.githubusercontent.com/4206675/75780226-4ca02100-5d9e-11ea-91af-2fc31a20a272.png">
](url)

**Comment by saladdays** [comment]
一瞬2列で表示されてその後この状態になるようです。なんだろ。

**Comment by saladdays** [comment]
2列にするでお願いします！

**Comment by mikkame** [comment]
ひょっとしてMacでならないのはスクロールバーが出ないからでは？
Windows→スクロールバー出る→リサイズ発火
#51 のリサイズしたらでかくなるバグを踏む

みたいな流れ？
