### ISSUE TITLE
CONTRIBUTING.md 内の URL ミス / Wrong URL in CONTRIBUTING.md

### ISSUE THREAD

**Issue by aximov** [tokyo-metropolitan-gov/covid19#2699]
## 起こっている問題 / The Problem
- CONTRIBUTING.md の「good first issue ラベルのついたものは初心者におすすめです」という文言の、good-first-issue ラベルへのリンクが次のものになっています。/ CONTRIBUTING.md has a link to good-first-issue label, but its URL is wrong: https://github.com/tokyo-metropolitan-gov/covid19/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

## スクリーンショット / Screenshot
- Not applicable

## 期待する見せ方・挙動 / Expected Behavior
- 正しい URL は以下です / The correct URL is: https://github.com/tokyo-metropolitan-gov/covid19/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue

## 起こっている問題の再現手段 / Steps to Reproduce
1. Open [CONTRIBUTING.md](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/CONTRIBUTING.md)

## 動作環境・ブラウザ / Environment
- Not applicable

**Comment by y-yoshida8823** [comment]
こちら着手してもよろしいでしょうか

**Comment by yuuton414** [comment]
こちら着手してもよろしいでしょうか
