### ISSUE TITLE
感染者分布マップが欲しい

### ISSUE THREAD

**Issue by Tao4free** [tokyo-metropolitan-gov/covid19#2706]
## 改善詳細 / Details of Improvement
見回りがどのくらいの感染リスクを把握できれば、市民の生活活動あるいは生産活動に指導できるます。
以下二つサイトで掲示したような感染者マップが欲しいです。
https://coromap.info/index.html
https://gis.jag-japan.com/covid19jp/

PS：正直に言って感染数にはあまり生活活動や生産活動に有意味とは言えないです。感染リスクマップが欲しいです。

**Comment by kaizumaki** [comment]
@Tao4free ご提案ありがとうございます。こちらのissueについて都に確認いたしました。地図としての可視化は慎重にせねばなりません。首都圏で活動している人の特徴として、居住地と職場、生活圏といったものが異なることがあるからです。単純に区市町村別の陽性患者数をマッピングすることによって誤解を生むことが考えられます。ですので、こちらの提案を採用するのは難しいです。どうかご理解いただきますようお願いいたします。

**Comment by kaizumaki** [comment]
都からの回答がありましたので、こちらのissueはクローズさせていただきます。
