### ISSUE TITLE
サイトタイトルの改行位置を変えたい

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#271]
iPhone SE（幅320）で見た時の改行位置の調整

```
東京都
新型コロナウイルス
対策サイト
```
↓
```
東京都
新型コロナウイルス
対策サイト
```

`新型コロナウイルス` と `対策サイト` をそれぞれ`inline-block`にすれば良さそう。

@halsk これって「東京都」は省略可能ですか？

ロゴをサイト名の一部として利用するのはNGかと思うのですが、近くにありすぎるので見た目上は消したいですね

![image](https://user-images.githubusercontent.com/1301149/75779945-efa46b00-5d9d-11ea-8148-9a57a12ae831.png)

**Comment by halsk** [comment]
省略可能ではと思います。対応しますね
