### ISSUE TITLE
新規グラフ（累積件数 vs 成長率）追加の可能性について

### ISSUE THREAD

**Issue by akiyama708** [tokyo-metropolitan-gov/covid19#2712]
皆様，大変お世話になっております．

2020年3月27日にYoutubeに公開されました「How to tell if We're Beating COVID-19」のグラフ表示法が非常に効果的です．このグラフを追加できないでしょうか．
https://www.youtube.com/watch?v=54XLXg4fYsc

表示は東京都のデータだけよいと思いますので，東京都のデータを加工して，以下のグラフを更新していくプログラムを作れないでしょうか．
・x軸は，累積件数
・y軸は，1週間当たり新しい件数（成長率）
・スケールは，xyともに対数

こうすれば，流行が拡大していっているのか，縮小に向かっているのかが明らかとなります．tと件数の一般的なグラフではみえない傾向が明らかになります．

よろしくご検討頂けたら幸いです．

**Comment by ocean3fish** [comment]
@akiyama708 
ご提案頂きありがとうございます。
リンクで張っていただいたYouTubeのコンテンツは「新型コロナウイルス（COVID-19）を倒したかを知る方法」と非常にキャッチーでわかりやすいですね。
ただ、そちらは疫学の専門家が作成されたわけではないんですよね。
実際に、指数関数的な増加傾向から外れたからと言ってCOVID-19を克服したとは言えないはずです。

また、東京都単体の場合、グラフを見て頂けるとわかるように、曜日によって検査実施数が異なるため、検出される陽性患者数にも曜日による影響が出るはずです。
その点を考慮せずに対数軸に陽性患者数を載せてしまうと、おそらく実際の傾向とは無関係に傾向線から外れたりするプロットが出てくるはずなので、ミスリーディングにつながる恐れがあります。

以上の観点から、公式情報としての発信は難しいグラフではないかと考えます。
ご検討いただけますと幸いです。

**Comment by akiyama708** [comment]
> @akiyama708
> ご提案頂きありがとうございます。
> リンクで張っていただいたYouTubeのコンテンツは「新型コロナウイルス（COVID-19）を倒したかを知る方法」と非常にキャッチーでわかりやすいですね。
> ただ、そちらは疫学の専門家が作成されたわけではないんですよね。
> 実際に、指数関数的な増加傾向から外れたからと言ってCOVID-19を克服したとは言えないはずです。
> 
> また、東京都単体の場合、グラフを見て頂けるとわかるように、曜日によって検査実施数が異なるため、検出される陽性患者数にも曜日による影響が出るはずです。
> その点を考慮せずに対数軸に陽性患者数を載せてしまうと、おそらく実際の傾向とは無関係に傾向線から外れたりするプロットが出てくるはずなので、ミスリーディングにつながる恐れがあります。
> 
> 以上の観点から、公式情報としての発信は難しいグラフではないかと考えます。
> ご検討いただけますと幸いです。

お返事を頂きまして，まことに有難うございます．

先ずこのYoutubeコンテンツの表現方法のいくつかには問題があると考えていますが，対数グラフの有効性については検討の余地があると考えております．

一次データを取得する研究者の立場から申し上げますと，できるだけ加工の少ないデータをグラフ化することは基本と考えていますが，いずれにせよミスリーディングは生じ得ます．例えば陽性患者数のグラフにおきましても，調査方法（検査数や検査方法など）によって，現実との齟齬が生じます（現実世界の陽性患者数と検査で判明した陽性患者数との違いという意味です．これをミスリーディング①と定義します）．したがいまして，グラフ化する際の条件や仮定とセットで，グラフを提供すればよいのではないかと思います．

ここで提案するグラフは，例えば陽性患者数のグラフで生じ得るミスリーディング①を逆に防ぐ方向に機能させ得ると考えています．なぜなら対数で表示するからです．

根拠の検討がさらに必要ならば，以下のような可能性もあるかと思います．このスレッドの範囲を超える内容かもしれませんが，いかがでしょうか．
1）当面はCode for Japanのメンバー間だけで閲覧できるようにする．
2）Code for Japanに研究者チームをつくり，最新の研究論文などに照らしながら，対数グラフの検討を行う．

よろしくご検討頂けたら幸いです．

**Comment by akiyama708** [comment]
> @akiyama708
> ご提案頂きありがとうございます。
> リンクで張っていただいたYouTubeのコンテンツは「新型コロナウイルス（COVID-19）を倒したかを知る方法」と非常にキャッチーでわかりやすいですね。
> ただ、そちらは疫学の専門家が作成されたわけではないんですよね。
> 実際に、指数関数的な増加傾向から外れたからと言ってCOVID-19を克服したとは言えないはずです。
> 
> また、東京都単体の場合、グラフを見て頂けるとわかるように、曜日によって検査実施数が異なるため、検出される陽性患者数にも曜日による影響が出るはずです。
> その点を考慮せずに対数軸に陽性患者数を載せてしまうと、おそらく実際の傾向とは無関係に傾向線から外れたりするプロットが出てくるはずなので、ミスリーディングにつながる恐れがあります。
> 
> 以上の観点から、公式情報としての発信は難しいグラフではないかと考えます。
> ご検討いただけますと幸いです。

@ocean3fish
お返事を頂きまして，まことに有難うございます．

先ずこのYoutubeコンテンツの表現方法のいくつかには問題があると考えていますが，対数グラフの有効性については検討の余地があると考えております．

一次データを取得する研究者の立場から申し上げますと，できるだけ加工の少ないデータをグラフ化することは基本と考えていますが，いずれにせよミスリーディングは生じ得ます．例えば陽性患者数のグラフにおきましても，調査方法（検査数や検査方法など）によって，現実との齟齬が生じます（現実世界の陽性患者数と検査で判明した陽性患者数との違いという意味です．これをミスリーディング①と定義します）．したがいまして，グラフ化する際の条件や仮定とセットで，グラフを提供すればよいのではないかと思います．

ここで提案するグラフは，例えば陽性患者数のグラフで生じ得るミスリーディング①を逆に防ぐ方向に機能させ得ると考えています．なぜなら対数で表示するからです．

根拠の検討がさらに必要ならば，以下のような可能性もあるかと思います．このスレッドの範囲を超える内容かもしれませんが，いかがでしょうか．
1）当面はCode for Japanのメンバー間だけで閲覧できるようにする．
2）Code for Japanに研究者チームをつくり，最新の研究論文などに照らしながら，対数グラフの検討を行う．

よろしくご検討頂けたら幸いです．

**Comment by ocean3fish** [comment]
@akiyama708 ご返信ありがとうございます。
> 一次データを取得する研究者の立場から申し上げますと，できるだけ加工の少ないデータをグラフ化することは基本と考えていますが，いずれにせよミスリーディングは生じ得ます．
おっしゃる通りで、ミスリーディングを完全に防ぐことは不可能と考えています。
挙げて頂いた通り「できるだけ加工の少ないデータをグラフ化することは基本」と考えております。
特に公的機関としての情報発信であるため、根拠のないデータ加工の結果を公表することは難しいのではないかと考えております。

>グラフ化する際の条件や仮定とセットで，グラフを提供すればよいのではないかと思います．
こちらもおっしゃる通りで、前提条件の提示は必須と考えています。
現在グラフの解釈に必要な解説やFAQコンテンツの検討を進めて頂いているところです。

>ここで提案するグラフは，例えば陽性患者数のグラフで生じ得るミスリーディング①を逆に防ぐ方向に機能させ得ると考えています．なぜなら対数で表示するからです．
上述のYouTubeのように、「指数関数的な増加傾向から外れれば安心！」といった誤解をしている人が多く見受けられる以上、ミスリーディングを増長する効果が懸念されます。
また、研究者の方であれば対数は一般的だと思いますが、本サイトは様々な方がご覧になるコンテンツであるため、対数の概念が全員に正しく伝わるかというと難しい面があると考えます。
対数の概念を知っていたとしても、グラフの軸や注釈を読まず、一見した印象で解釈されてしまう可能性もあります。

> 根拠の検討がさらに必要ならば，以下のような可能性もあるかと思います．このスレッドの範囲を超える内容かもしれませんが，いかがでしょうか．
> 1）当面はCode for Japanのメンバー間だけで閲覧できるようにする．
> 2）Code for Japanに研究者チームをつくり，最新の研究論文などに照らしながら，対数グラフの検討を行う．

貴重なご提案だと思いますが、疫学の専門家を入れたチームでの検討が必要になると考えています。
そうでないと、対数軸の傾向線に乗る/外れるでどのようなことが言えるのか、正確に解釈できないためです。
そして、このサイトの運営に携わっているメンバーにも限りがあり、日々の迅速な情報発信が最優先となります。

そういったご検討を自由に行って頂くためのオープンデータでもあるため、ぜひご所属の研究機関等で専門家のチームを立ち上げて取り組んで頂けると良いかと考えますが、いかがでしょうか。

**Comment by akiyama708** [comment]
@ocean3fish
ご返答有難うございました．承知致しました．今後ともどうぞよろしくお願い申し上げます．

**Comment by ocean3fish** [comment]
@akiyama708 
ご理解頂き感謝申し上げます。
本件は一度クローズとさせて頂きますが、様々な専門性をお持ちの方の観点は貴重であるため、今後も色々なトピックの議論にご参加頂けたら嬉しく思います。
今後ともどうぞよろしくお願いいたします。
