### ISSUE TITLE
相談フロー 印刷レイアウトが崩れている

### ISSUE THREAD

**Issue by maccyo12** [tokyo-metropolitan-gov/covid19#2718]
## 改善詳細 / Details of Improvement
https://stopcovid19.metro.tokyo.lg.jp/print/flow/ のページで印刷を行うと、好ましくない位置で2ページに分断されている。

## スクリーンショット / Screenshot
Chromeの「PDFに保存」でPDF出力した後、画像に変換
![bad_page1](https://user-images.githubusercontent.com/21338006/78114115-bb26dc00-743b-11ea-8e9b-fd2566212d39.png)

![bad_page2](https://user-images.githubusercontent.com/21338006/78114134-c11cbd00-743b-11ea-953f-249d0220281d.png)

## 期待する見せ方・挙動 / Expected behavior
1ページに収まるように調整して頂きたいです。
※3/10に一度印刷した際には1ページに収まっていました。
Chromeの「PDFに保存」でPDF出力した後、画像に変換
![good](https://user-images.githubusercontent.com/21338006/78114288-ff19e100-743b-11ea-8923-f06c214cf636.png)

## 動作環境・ブラウザ / Environment
- Windows 10
- Chrome バージョン: 80.0.3987.162（64 ビット）
- Firefox Developer Edition バージョン: 75.0b11（64 ビット）

**Comment by khsacc** [comment]
Chromeの「PDFに保存」でPDF出力しても、スクリーンショットのようにならず（9ページにわたって細かく分割されてしまう）、再現できないのですが、どのような印刷設定で書き出していらっしゃいますか？

**Comment by maccyo12** [comment]
印刷設定は以下のように設定しています
![image](https://user-images.githubusercontent.com/21338006/78188619-85214080-74ab-11ea-9ea9-f8c593176189.png)

**Comment by yuuton414** [comment]
印刷プレビューするとここのflexがきいてない？感じがします。
![image](https://user-images.githubusercontent.com/59001145/78205876-4655af80-74d8-11ea-9b16-49e7dd0f8215.png)

**Comment by khsacc** [comment]
すこしさかのぼって調べてみると、多言語化に伴い、印刷が2ページにわたってしまう問題は認識されているようです（ Issue #1270  Pull Request #1273）。おそらくこれを修正するためにはFlowPc.vueの大規模な破壊的変更が必要と思われるため、FlowPrint.vueみたいな複製ファイルを作成するほうが現実的な気がしますが、そうするとneed-official-confirmationになるんでしょうか？
