### ISSUE TITLE
data/metro.jsonの更新日がアップデートされていない

### ISSUE THREAD

**Issue by nullnull** [tokyo-metropolitan-gov/covid19#2719]
## 起こっている問題 / The Problem
data/metro.jsonの更新日 `date` がアップデートされていない。
そのため、トップページの「都営地下鉄の利用者数の推移」にて、3/26までのデータが表示されているが、最終更新日が3/19になっている。

## スクリーンショット / Screenshot
[![Screenshot from Gyazo](https://gyazo.com/7add024f6c873df8cab5bc3de051ddab/raw)](https://gyazo.com/7add024f6c873df8cab5bc3de051ddab)

## 期待する見せ方・挙動 / Expected Behavior
最終更新日が、更新日となっていること。
一旦の対応としては、 https://github.com/tokyo-metropolitan-gov/covid19/blob/development/data/metro.json#L2 を直接修正すればOKだと思います。
根本的な原因としては、 https://github.com/tokyo-metropolitan-gov/covid19/pull/2428 のBOTによる更新で、dateが更新されていないのが問題に見えます。

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
@nullnull ご指摘ありがとうございます！こちら調査いたします。

**Comment by nullnull** [comment]
開発チームのみなさま、対応お疲れ様です！
自身で対応したいところでしたが、BOTをどこで管理しているかパッと見で把握できませんでしたので、お任せ致します。
どうぞ宜しくお願いいたします！

**Comment by kaizumaki** [comment]
@nullnull こちらの件ですが、元データの入力ミスでした。次にBOTが走るときに修正されると思います。ご指摘いただき感謝です！

**Comment by kaizumaki** [comment]
修正されたことを確認しました。こちらのissueはクローズさせていただきます。
