### ISSUE TITLE
スマホ表示にしたときのヘッダーに罫線が入っている

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#274]
左右に余白のある罫線が重なって表示されているようです。
PC表示の時に使われているdividerですね。非表示でお願いします。

![image](https://user-images.githubusercontent.com/1301149/75780640-1b742080-5d9f-11ea-98c7-329eb286278b.png)

**Comment by kenshir0f** [comment]
はーい
