### ISSUE TITLE
FORKED_SITES.mdを元に地域別COVIDサイト一覧を設置したい

### ISSUE THREAD

**Issue by y2naranja** [tokyo-metropolitan-gov/covid19#2747]
## 改善詳細 / Details of Improvement
- FORKED_SITES.mdを元に、地域別COVID19対策サイトの一覧を設置したい
- GitHubやSpreadsheet直では、一般人にはハードルが高いので、一覧を設けたい
- 更新はFORKED_SITES.mdを元に手作業で行う
- ドメインは未取得だが、stopcovid19-sites.info か stopcovid19-sites.siteを予定

## 期待する見せ方・挙動 / Expected behavior
- FORKED_SITES.mdの、都道府県名・公開サイト・運営者のみを一覧表示する
- 静的サイト・レスポンシブ対応
- 地図等は表示しない

**Comment by kaizumaki** [comment]
> ドメインは未取得だが、stopcovid19-sites.info か stopcovid19-sites.siteを予定

サイトの作成は自由ですが、こちらの東京都のサイトにはどのように影響しますか？

**Comment by y2naranja** [comment]
> サイトの作成は自由ですが、こちらの東京都のサイトにはどのように影響しますか？

東京都のサイトには、他地域へのリンクがないので、影響はないと思われます。
Code for Japanへメールで相談したところ、GitHubにて議論の上、最終的に東京都が判断する形になるとのことでしたので、こちらにissueとしてあげました。
ドメインは取得しましたので、今日中に一覧をアップしてお知らせします。
ドメイン：
stopcovid19-sites.site

**Comment by kaizumaki** [comment]
東京都のサイトに影響するものでなければ、当リポジトリで議論することは必要ないですし、東京都が判断することもありません。
ですので、こちらのissueはクローズさせていただきたく思います。
