### ISSUE TITLE
表は日付降順で表示する

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#275]
表は原則日付降順で表示した方が、アップデートがわかりやすくて良いかと思ったのですが、いかがでしょう？
現状は日付昇順で表示されています。
<img width="527" alt="スクリーンショット 2020-03-03 22 36 54" src="https://user-images.githubusercontent.com/4206675/75780911-95a4a500-5d9f-11ea-8200-326b584ee53d.png">

**Comment by NagaoKyota** [comment]
https://stopcovid19.metro.tokyo.lg.jp/

降順・昇順の表示を切り替えることができるように修正されている(対応早い...)ため、close しても良いかと思います。

**Comment by potato4d** [comment]
すべて切り替えることができていそうです。

[![Image from Gyazo](https://i.gyazo.com/07264996f5744945fbb9773d064d613e.gif)](https://gyazo.com/07264996f5744945fbb9773d064d613e)
