### ISSUE TITLE
言語選択メニュー以外で言語変更すると言語選択メニューの表示が更新されない

### ISSUE THREAD

**Issue by ksk1015** [tokyo-metropolitan-gov/covid19#2754]
## 起こっている問題 / The Problem
- ブラウザの戻る等、言語選択メニュー以外で言語変更すると言語選択メニューの表示が更新されない

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-02 10 28 09](https://user-images.githubusercontent.com/2456718/78201496-b4947500-74cc-11ea-98fb-e50e5c01b168.png)

## 期待する見せ方・挙動 / Expected Behavior
- 言語選択メニュー以外で言語変更しても言語選択メニューが現在の言語が表示されるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. 言語選択メニューで言語を変更
2. ブラウザで戻り前の言語になっても言語選択メニューは更新されず

## 動作環境・ブラウザ / Environment
MacOS: Chrome, Safari
Android

**Comment by seuharuka** [comment]
こちら対応致します。
