### ISSUE TITLE
コールセンターの推移件数

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#276]
２つのコールセンターの「推移」件数について、
前日比 は「前日までの累計」との比較が正しいです。
（前日の件数と比べてマイナス～ではなく）

**Comment by ocean3fish** [comment]
すみません、グラフの「推移」と「累積」の意味に合わせて解釈した場合に、「推移」の時の前日比はマイナスの値も取りうるという理解でおりました。
混乱を招かない表現/表示に調整したいですね。
https://github.com/tokyo-metropolitan-gov/covid19/issues/138

**Comment by NaoyaShimizzz** [comment]
@ocean3fish 確かに表現がわかりにくいので、今後要調整ですね。出すべき数字はデイリーでどれだけ増えたかだと思うので、修正お願いいたします。

**Comment by NaoyaShimizzz** [comment]
対応状況はいかがでしょうか

**Comment by halsk** [comment]
@osoken 対応できますか？

**Comment by halsk** [comment]
ちょっと見てみます

**Comment by osoken** [comment]
すいません、見ます！

**Comment by halsk** [comment]
ありがとうございます！これが終わればリリースできます！

**Comment by osoken** [comment]
@NaoyaShimizzz @ocean3fish 一応リマークとして、陽性患者数に対しても、デイリーでどれだけ増えたかの処理に変更します。（昨日0件だったため、今日の分の見た目の変更はありませんが）
