### ISSUE TITLE
[ruby] トップページの「やさしい日本語」のルビタグ対応する

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#2764]
## 改善詳細 / Details of Improvement
- トップページの「やさしい日本語」をルビタグ対応する
  - 関連 issue: #1295
- プロトタイプで作成した実装は、#2628 にプルリクエストを作成しています
- こちらのプルリクエストで基本となるコンポーネントや実装が固まってから、他ページへ展開する issue を立てる予定です

## スクリーンショット / Screenshot
| Before  | After |
| ------------- | ------------- |
| ![スクリーンショット 2020-03-30 20 51 44](https://user-images.githubusercontent.com/5207601/77909432-4c754180-72c8-11ea-94fe-ec8f45f31c56.png) | ![スクリーンショット 2020-03-30 20 51 24](https://user-images.githubusercontent.com/5207601/77909426-4a12e780-72c8-11ea-98fc-fc0c79ebe2c1.png) |

## 期待する見せ方・挙動 / Expected behavior
- やさしい日本語がルビタグつきで表示されること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
対応すべき箇所で、 #2628 に含まれてないもののリスト等あれば助かります！

**Comment by shgtkshruch** [comment]
> 対応すべき箇所で、 #2628 に含まれてないもののリスト等あれば助かります！

僕の方で把握しているのは以下のリストになります！

| ページ名  | URL |
| ------------- | ------------- |
| 都内の最新感染動向（グラフ） |   https://stopcovid19.metro.tokyo.lg.jp/ja-basic  |
| 新型コロナウイルス感染症が心配なときに | https://stopcovid19.metro.tokyo.lg.jp/ja-basic/flow |
| お子様をお持ちの皆様へ | https://stopcovid19.metro.tokyo.lg.jp/ja-basic/parent |
| 企業の皆様・はたらく皆様へ | https://stopcovid19.metro.tokyo.lg.jp/ja-basic/worker |
| 当サイトについて | https://stopcovid19.metro.tokyo.lg.jp/ja-basic/about |
| お問い合わせ先一覧 | https://stopcovid19.metro.tokyo.lg.jp/ja-basic/contacts |

**Comment by shgtkshruch** [comment]
#2628 で動作確認をしていて気づいたのですが、Flow ページでは `<i18n>` タグを使って以下のようにマークアップしている箇所が多数ありました。

```vue
<i18n
  :class="$style.Catch"
  tag="p"
  path="新型コロナ外来 {advice} と判断された場合"
>
  <template v-slot:advice>
    <span :class="$style.Emphasis">
      {{ $t('受診が必要') }}
    </span>
  </template>
</i18n>
```

このマークアップですと #2628 で実装した `<t-i18n>` コンポーネントではルビタグ対応できないので、コンポーネントを修正する必要がありそうです。

Vue の `render` 関数を使できそうなので、そちらで書き換えてみます。
ref: https://vuejs.org/v2/guide/render-function.html

これに伴って `<t-i18n>` コンポーネントのインターフェースが変わるので、他ページへの展開はこちらの修正が終わってからすすめられればと思います 🙏 
おそらく翻訳文字列や VNode を `slot` で渡す形になると思います。

**Comment by MaySoMusician** [comment]
#2897 を `dev-ja-hira-ruby` にまでマージしました
https://ja-hira-covid19-tokyo.netlify.com/ja-basic でご確認いただけると思います

---

レビュー時に見つかった課題としては（PR自体とは別の箇所）、下記のように `<script>` 側で翻訳を指定している例をどうするか、という点です。
https://github.com/tokyo-metropolitan-gov/covid19/blob/e1399820cd9d12f606d47ee15baf5e2b8f6278d7/components/AgencyBarChart.vue#L125-L131

**Comment by shgtkshruch** [comment]
マージありがとうございます！
#2897 で実装した箇所は大丈夫そうです。

コメントいただいた `<script>` 側の翻訳ですが、今の段階で以下の2通りの対応方法があると思います。
1.  #2498 で凡例を`<canvas>` の外に出す修正をしているので、これを他のグラフにも展開すると通常の `<template>` 内の多言語対応と同様にルビタグ対応できます
https://github.com/tokyo-metropolitan-gov/covid19/pull/2498/files#diff-bb76f9fdb7cf526444278cf1a64c9d8cR41
1. Chart.js に凡例を `<canvas>` 外に生成する API があるので、こちらを利用してルビタグをつけた HTML を生成する
ref: https://www.chartjs.org/docs/latest/configuration/legend.html
この場合は、`<t-i18n>` コンポーネントに実装したような、ルビタグを生成するヘルパーメソッドを用意します

最初は 2 の方向で考えていましたが、1 がマージされるならこちらを活かす形のほうがいいと思います。
1 には以下のようなメリットがあります。
1. グラフ間で凡例と多言語対応の実装が揃えられる
1. 既存の実装を活かせるので工数の削減が期待できる

**Comment by MaySoMusician** [comment]
もし（技術的に）1.が可能ならそちらでお願いしたいと思います！

**Comment by shunito** [comment]
こちら、一度「日本語」で表示させてから「やさしいにほんご」に変更すると問題ないですが
https://ja-hira-covid19-tokyo.netlify.com/

直接「やさしいにほんご」のURLで開こうとするとエラーが発生してローディングが終わらない状態になるようです。
https://ja-hira-covid19-tokyo.netlify.com/ja-basic/

原因不明ですが、いったん事象のご報告まで。
以下、その時のコンソールの状態です。
![開発者ツールのキャプチャ](https://user-images.githubusercontent.com/32133/78673792-993ac700-791d-11ea-88a0-0cbea182379e.png)

環境はWindows10 Chrome最新（80.0.3987.163）です。

**Comment by KentarouTakeda** [comment]
#2498 を作成した者です。
平日あまり時間取れないので少し乱暴な案内になってしまうんですが、
グラフ凡例の外出しを他に展開するとしたら

https://github.com/tokyo-metropolitan-gov/covid19/pull/2498/commits/29949e1d8d3b24af5605e5588f91f167c0829ac3#diff-bb76f9fdb7cf526444278cf1a64c9d8c
こちらの変更を各グラフに適用していく感じになると思います。
（上のcommitの後に a11y 対応で色指定が増えたのでそこだけ微調整必要）

同じcommitでpluginやscssにも修正入ってますが言わば「共通部分」なので、
各グラフへの適用に関しては上に挙げた1ファイルのみで大丈夫です。

**Comment by shgtkshruch** [comment]
@MaySoMusician 
> もし（技術的に）1.が可能ならそちらでお願いしたいと思います！

はい、1 の方向で検討します！

@KentarouTakeda  san も共有ありがとうございます。
こちらの commit を参考に検討させていただきます。

---

@shunito  
確認ありがとうございます。
エラーメッセージとリロード時に起こる問題ということで、ハイドレーションで問題が起きていそうなきがします。
この後調査して対応します。

**Comment by MaySoMusician** [comment]
クロスブラウザ対応も `dev-ja-hira-ruby` に反映させました！

**Comment by shgtkshruch** [comment]
ありがとうございます！
共通部分の実装ができたので他ページへ展開できればと思います。

明日以降でよろしければ僕の方で issue を作成しますが、（個人的な都合で恐縮ですが）日中は業務があるので質問などが来た場合に返答にお時間をいただくと思います。
スムーズに進めるのであれば、コアチームの方や対応できる方に作成いただいたほうがいいかもしれません。
