### ISSUE TITLE
[Hotfix] nuxt-i18n Upgrade

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#2765]
## 起こっている問題 / The Problem
- See #2535 
- Fix has been done: nuxt-community/nuxt-i18n#651
- Need to apply fix to this so that it can be a persistent fix for locale-switching issue

## 期待する見せ方・挙動 / Expected Behavior
- Switching web display local can be made easy

## 起こっている問題の再現手段 / Steps to Reproduce
1. Changing locale on browser configuration does not take effect
2. Ambiguous charsets e.g. zh-cn vs. zh-tw have not been distinguished
3. In the case 2, web display language falls back to Japanese (default)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
対応としては、nuxt-i18nを[v6.8.0](https://github.com/nuxt-community/nuxt-i18n/releases/tag/v6.8.0)にアップグレードすれば良いのでしょうか？ 他にすべきことはありますか？

**Comment by mcdmaster** [comment]
ありがとうございます。`nuxt-i18n` アップグレードのみでお願いいたします。念のため、こちらのローカル環境で `zh-cn`, `zh-tw` に切り替えた際の動作は確認できました。

とはいえ、もしかしたら類似の不具合がさらに出てくるリスクはあります。今回の件をきっかけに、
- `nuxt-i18n` デベロッパとのコミュニケーション・チャネルの確保
- コミュニケーション・チャネルを活かした、早期対応依頼のプロセス
- 当プロジェクトの外部モジュール依存イシュー対応リスクを、モジュール類のオリジナル・デベロッパに移転する

といったあたりをプロセスとして固めつつ、もしも `nuxt-i18n` 以外のモジュールにも問題が発生した際はそのプロセスのノウハウを横展開できればという狙いがあります

**Comment by MaySoMusician** [comment]
@mcdmaster 6.8.0でも中国語に関しては上手く動作しなかったのでいろいろと調べてみましたが、どうやら検証環境のFireFox 74.0 (64-bit)だとブラウザ言語設定が `zh-CN` というように国コード部分が大文字で送られるようです。このプロジェクトの中国語（簡体字）の `code` は `zh-cn` なので（URLなどに使われる文字列）、単に比較した場合は不一致となります。

国コードは「表記上は大文字が推奨されるが、 case sensitive ではない（小文字表記も許容される）」と解説してるサイトもあるので、 `nuxt-i18n` に case insensitive で比較してもらうのが一番良いのかなと思います（事実、言語コードのみの比較のときは `toLowerCase()` を使用している）

こちらの設定を `zh-CN` を変えるとなるとURLも `zh-CN` になってしまうので、そこが変わってよいのかどうか、という問題もあります。また `dayjs` のlocale設定では全部小文字で渡さなければいけないようで、その対処も必要となります

**Comment by mcdmaster** [comment]
おお、そうだったのですね。ちなみに、私の Firefox は nightly なので、76a1 というバージョンです。

たしかに、たとえば UNIX シェルの `LANG` 環境変数は `ja_JP` のように言語（小文字）＋アンダースコア＋国・地域（大文字）という書き方をしていました。
でも、`nuxt-i18n` は元々そこまで厳密な制約を設けてはいません。言語コードと国・地域コードも、アンダースコアでなくハイフンでつなげる、のようなことをマニュアルで書いています。[このあたり](https://nuxt-community.github.io/nuxt-i18n/options-reference.html)とかです。

だとしたら、我々が case-insensitive を要求した際にそれを頑なに却下すべき理由も特にないはずです。
ちょっと nuxt-i18n にイシューを上げてみましょうか？

**Comment by MaySoMusician** [comment]
@mcdmaster 向こうでissueあげるのは結構面倒な手順を要求されてて（cmty.app経由 + 再現用のCodeSandboxを提出しなきゃいけない）、 https://github.com/nuxt-community/nuxt-i18n#contributing 読む限りいきなりPR出した方が早いのではないかと思っています

私が出しても良いし @mcdmaster さんが出しても、どちらでも問題無いと思います。いかがいたしましょうか？

**Comment by mcdmaster** [comment]
じゃあ、このイシューを出した責任もありますので、私が PR を出しましょう。
実は、国・地域コード対応も、私がク●コードをイキナリ PR したので進展があったのでは、と勝手に推測しています(笑)

**Comment by MaySoMusician** [comment]
@mcdmaster ありがとうございます。🙇‍♂️
おっと、そんな経緯もあったのですね。

**Comment by MaySoMusician** [comment]
@mcdmaster 対応ありがとうございます！ あとは先方のテスト実装待ちですね

**Comment by mcdmaster** [comment]
いえいえ、力不足で何だか申し訳ないです…。
スコープ逸脱だ！と最初から主張しておけばよかったです。
今さらですけど(笑)

**Comment by mcdmaster** [comment]
おかげさまで、`6.8.1` へのアップグレードが完了しましたね。
さっそく私の個人環境でもテストしました。オーケーです。
ただ、私の環境の特殊性はおそらく排除できないので、他の方の環境でのテストを経た上で、アップデートをお願いいたします。

**Comment by MaySoMusician** [comment]
遅くなりましたが、こちらの環境でも `6.8.1` で正常に言語判定ができましたので、ひとまずPRを提出したいと思います。
