### ISSUE TITLE
サイドメニューの並べ方

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#277]
「当サイトについて」の位置が若干中途半端ですね。
性格上見なくても良いものなので、一番下に持ってきてはいかがでしょう？

@halsk 

<img src=https://user-images.githubusercontent.com/1301149/75781374-63e00e00-5da0-11ea-87dd-a3a1ed330bde.png width=50%>

**Comment by mikkame** [comment]
一応 #222 
でこの順番という指示がでております

**Comment by halsk** [comment]
オフトピ気味ですが、【東京都主催等】の部分がきれいに左揃えできてなくてちょっと気持ち悪くないです？

**Comment by mikkame** [comment]
【
こいつが曲者ですね

**Comment by hkomamiy** [comment]
これやりますー。
>【東京都主催等】の部分がきれいに左揃えできてなくてちょっと気持ち悪くないです？

**Comment by hkomamiy** [comment]
一旦「【」付きのtextのみ-0.5emされるように揃えました。とりあえずsidebarのみの反映なので、他にもあればcomputed{ のjsを真似していただくと

<img width="207" alt="スクリーンショット 2020-03-04 19 38 37" src="https://user-images.githubusercontent.com/27335198/75871371-cba16200-5e4f-11ea-9a82-7f25590bc43d.png">
<img width="370" alt="スクリーンショット 2020-03-04 19 38 49" src="https://user-images.githubusercontent.com/27335198/75871373-ccd28f00-5e4f-11ea-9c1c-d4988328db6e.png">
