### ISSUE TITLE
スクリプト無効環境の表示不具合とnoscriptの必要性について

### ISSUE THREAD

**Issue by SaekiTominaga** [tokyo-metropolitan-gov/covid19#2789]
## 起こっている問題 / The Problem

- noscript の表示が常に画面中央に表示されており、コンテンツの閲覧に大きな支障がある。
- .noscript-heading の背景が透過なので、ロゴとタイトルが読みにくい。
- [/flow](https://stopcovid19.metro.tokyo.lg.jp/flow/)のページにおいて、矢印アイコンの画像が noscript より手前に表示される。

## スクリーンショット / Screenshot

/flowページにおいて矢印が手前に来ている様子
![Screenshot_2020-04-03 東京都 新型コロナウイルス感染症 対策サイト](https://user-images.githubusercontent.com/4138486/78317996-b2025000-759e-11ea-97d8-60371157b806.png)

### 取り急ぎの対応案

- .noscript-heading に background-color を設定する。
- .noscript に対して、矢印アイコン画像の z-index と同じ値（1）、ないしより大きな値の z-index を設定する。

### 本質的な対応策

- noscript の必要性を検討する（後述します、長くてすみません）。
- （noscript が必要な場合）その表示方法を検討する。例えば画面中央でなく、昨今GDPR対応でよく見られるCookie使用の案内のような、下端での全幅表示なら現状よりは邪魔にならないと思います。

### noscript の必要性について

noscript の表示は #846 で追加されたようですが、当時はスクリプト無効環境で情報がまったく閲覧できない状況だったものが、現在それは解消されています。
言語切り替え機能など、依然スクリプトが有効でないと動かない機能が存在したり、トップページの表が崩れたりする不具合はありますが、警告表示を常に前面に表示して、コンテンツの閲覧を阻害する必要性はないと思います。

そもそも、本来 noscript とはスクリプト無効環境向けに代替となるコンテンツを提供するためのものであり、注意文を表示してブラウザの設定変更を誘導するためのものではありません。
（&lt;noscript&gt; 以外の別のHTML要素を使うべきと言いたいのではなく、ユーザーに対して環境を変えさせようとする考え方自体がウェブの理念とかけ離れているのはないか、と思う次第です。）

またこれは個人的な感覚ですが、私自身、長年スクリプト無効でネットサーフィンしていた経験がありますが、他のサイトでも多く見られるこのような注意文を見て「じゃあこのサイトではスクリプトを有効にしよう」と思ったことは一度もありません。
スクリプトを無効にしているユーザーは「多くのサイトが正常に動かなくなることを承知のうえで、なぜそれでもスクリプトを無効にしているのか」と考えれば、代替機能の提供が難しく文章での説明に頼らざるを得ないケースでも、必要なことは「JavaScriptを有効にしてください」とただ平身低頭することではなく、「スクリプトが無効なことによってどんな支障があるのか」具体例を示し、スクリプトを有効にするかどうかの**判断基準をユーザーに示す**ことが重要ではないでしょうか。

あるいは、今どきあえてスクリプトを無効にしているユーザーは大方リテラシーも高く自己解決能力もあると期待して「何も表示しない」（単に noscript を削除する）という対応でもいいと思います。私自身、スクリプトが動かず表示が崩れたり、真っ白になったサイトに遭遇した際、そこに注意書きがあろうとなかろうと、特に何も感じたことはありません（そんなことでいちいち悲しんだり怒ったりしていては身が持ちません）。普段からスクリプトを無効にしていらっしゃる他の皆さんはどうでしょうか。こういった文言の必要性、感じますか?

取り急ぎの改善として、 background-color や z-index によるCSS変更という手段も挙げましたが、上記のような理由から noscript 自体の必要性、あるいは表示方法や文言の変更といった面についてもご意見、ご検討をいただきたいと思います。

## 動作環境・ブラウザ / Environment

すべてのOS、ブラウザ

**Comment by koukimetal** [comment]
とりあえず、それっぽいものを作ってみました。
画像はPRの方に貼り付けたので、よかったら見てみて下さい。

**Comment by SaekiTominaga** [comment]
ご対応ありがとうございます。
スクリプト無効環境で各ページ確認しましたが、大きな問題はなさそうです。
