### ISSUE TITLE
MetroCard.vueに実装されているgetWeekLabelが月をまたぐケースが考慮されていない

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#2797]
## 起こっている問題 / The Problem
- 03/30~02
- のようなデータを入れた場合に
- 03/30~03/02のような表示になってしまう

## 期待する見せ方・挙動 / Expected Behavior
- 03/30~02
- がのように月をまたぐ場合は
- 03/30~04/02のようにしたい

## 起こっている問題の再現手段 / Steps to Reproduce

実装箇所はここで確認できます
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/cards/MetroCard.vue#L82

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mikkame** [comment]
元データを治す場合は
元データと合わせてフロントを同時に変更する必要あり。

**Comment by seuharuka** [comment]
該当箇所のみ修正する場合は、開始日が終了日よりも小さかった場合後ろの月を+1するみたいな安直な実装で問題ないですかね？

**Comment by mikkame** [comment]
@seuharuka はい、フロント側でそのようにしていただけるとフロントの修正だけで済むかと思われます
