### ISSUE TITLE
[HTML] 陽性患者の属性の表の公表日を絞り込みできるようにしたい

### ISSUE THREAD

**Issue by kota-yata** [tokyo-metropolitan-gov/covid19#2799]
# 改善詳細 / Details of Improvement

- 陽性患者の属性で縦スクロールで表示される表にプルダウン等絞り込み要素を追加したい

## 期待する見せ方・挙動 / Expected behavior

- プルダウンで陽性患者の属性（公表日、居住地、年代、性別）それぞれ絞り込みできる
- もしくは表内の色分けなど、属性によって見分けやすくする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by masanori1102** [comment]
フィルタリング: #2526

**Comment by kaizumaki** [comment]
@kota-yata ご提案ありがとうございます。こちらのissueについて都に確認しまして、採用しないという結論にいたりました。詳細はこちら https://github.com/tokyo-metropolitan-gov/covid19/pull/3516#issuecomment-617530810 にコメントいたしました。どうかご理解のほどお願いいたします。

**Comment by kaizumaki** [comment]
都からの正式な回答がありましたので、こちらのissueはクローズさせていただきます。
