### ISSUE TITLE
都内の最新感染動向ページに、治療終了者数を追加する

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#2801]
## 改善詳細 / Details of Improvement
都内の最新感染動向ページに、治療終了者数を追加する

## スクリーンショット / Screenshot
北海道のサイト( https://stopcovid19.hokkaido.dev/ )のサイト参照

## 期待する見せ方・挙動 / Expected behavior
北海道のサイトでは、`陽性患者数≒現在患者数 +治療終了者数`と見せているので、「現在の増え方だけでなく、どれくらい治ったのかを合わせて理解する」事ができるので、サイト閲覧者が「どれくらいの期間で治療が完了するのか」を把握できる。
今は、退院までの期間を表示されたグラフや表から読み解く事が難しいので、それへの改善提案です。

以下の情報を基にすれば、過去に遡って、グラフを描けるのでは無いでしょうか?
- 陽性患者の属性の基になっているファイルの履歴から、退院フラグが立った時
- 検査陽性者の状況の基になっているファイルの履歴から、死亡を引く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by sutefu7** [comment]
技術的な意見ではなく、感情的な意見です。

もしこのカードが見られるようになれば、日々増加していく数字を眺める恐怖だけの他に、治療を終えたという希望を持つことができます（精神的なことかもですが）。ぜひご検討をお願い致します。

**Comment by kaizumaki** [comment]
@masanori1102 ご提案ありがとうございます。治療終了者数とは意味が異なりますが、 #4001 #4104 にて、「入院」と区別して「宿泊療養」「自宅療養」を表示するようになりました。内訳がより細かくなったと思います。北海道のサイトのように推移を示したグラフではありませんが、最新の数値は出せるようになりました。ご確認いただき、またご提案ありましたらコメントいただければと思います。

**Comment by kaizumaki** [comment]
こちらのissueは https://github.com/tokyo-metropolitan-gov/covid19/issues/2801#issuecomment-629593335 をもってクローズとさせてください 🙇
