### ISSUE TITLE
サイドメニューの著作権表示に著作権マークを追加

### ISSUE THREAD

**Issue by sorairolake** [tokyo-metropolitan-gov/covid19#2837]
## 改善詳細 / Details of Improvement
著作権表示であることを分かりやすくするために、著作権マークを追加
「2020 Tokyo Metropolitan Government」 → 「&copy; 2020 Tokyo Metropolitan Government」

**Comment by kaizumaki** [comment]
こちらの件ですが、こちら #832 #1132 の経緯があり、現在の表記となっています。ご理解いただけると幸いです。

**Comment by MaySoMusician** [comment]
CCはライセンス（＝著作物の使用法）であり著作権そのものには関知していないので、CCと©表示を併用することは可能ではあるようです。ただベルヌ条約により、著作権は（明示的に放棄しない限り）自動で発生しているので、©表示が必須というわけではないのも事実です（著作権表示であることをわかりやすくすることを目的にすることも多い）

**Comment by mcdmaster** [comment]
ソースコードの著作権については、同じく @sorairolake さんに起票していただいた #2030 の件がありましたね。
とはいえ、Web テキストやグラフといったアウトプットの著作権は誰に帰するかと言えば、それはデータオーナーたる東京都にほかならないというのが私の考えです。
そういう著作権を主張することで、たとえばメディアが安易に剽窃するのを阻む狙いはあってもいいと思います。

以上、蛇足でした

**Comment by ocean3fish** [comment]
ご提案ありがとうございます！
@MaySoMusician のご意見のようにCCライセンスにおいて©表示はたしかに必須ではないですね。
ただ、@sorairolake @mcdmaster お二方のご提案のように、このサイトのWebコンテンツとしての著作権者は誰なのか、つまりCC BY「誰」なのかを明確にした方が良いというのもよくわかります。
ソースコードの著作権とWebコンテンツの著作権は別物として考えて良いという理解でいます。

以上の点を踏まえて、本件は一旦関係者でどのように対応するか確認を取ります。

**Comment by ocean3fish** [comment]
ちなみにCC BYライセンスで©で著作権者を明示する例としては、こちらの解説がわかりやすいです。
https://find47.jp/ja/credit/

**Comment by munierujp** [comment]
コピーライト表記をするにせよ、「©」があれば「Copyright」は不要です。

- [年号と©マークと何が必要？Copyright（コピーライト）表記の正しい書き方 | 東京のWeb制作会社LIG](https://liginc.co.jp/designer/archives/11313)

**Comment by sorairolake** [comment]
CC BY 4.0の利用条件である「表示」は、著作権情報が**示されている場合**はこれを表示する必要が有るようです。

- 著作権表示が表記されていない → 「Tokyo Metropolitan Government / [東京都 新型コロナウイルス感染症対策サイト](https://stopcovid19.metro.tokyo.lg.jp/) / [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)」
- 万国著作権条約に基づく著作権表示が表記されている → 「Copyright &copy; 2020 Tokyo Metropolitan Government / [東京都 新型コロナウイルス感染症対策サイト](https://stopcovid19.metro.tokyo.lg.jp/) / [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)」

**Comment by sorairolake** [comment]
CC BY 4.0の利用条件である「表示」は、著作権情報が**示されている場合**はこれを表示する必要が有るようです。
現在の表記 (2020 Tokyo Metropolitan Government) だと利用者が表示の必要なものなのか迷う可能性があるので、「&copy;」が表記されているされている方が利用者としては助かると思います。

**Comment by ocean3fish** [comment]
@sorairolake 関係者での承認が通ったため、ご提案頂いた通りに変更を進められればと思います。

```
このサイトの内容物は クリエイティブ・コモンズ 表示 4.0 ライセンス の下に提供されています。
2020 Tokyo Metropolitan Government 
```
↓
```
このサイトの内容物は クリエイティブ・コモンズ 表示 4.0 ライセンス の下に提供されています。
© 2020 Tokyo Metropolitan Government 
```

**Comment by mayuritanaka** [comment]
着手します
