### ISSUE TITLE
スマホ 言語変更したらサイドナビを閉じる

### ISSUE THREAD

**Issue by ksk1015** [tokyo-metropolitan-gov/covid19#2841]
## 改善詳細 / Details of Improvement
- スマホビューのサイドナビを開いた状態で言語変更してもサイドナビが閉じないので閉じるようにしたい

## 期待する見せ方・挙動 / Expected behavior
- サイドナビを開いた状態で言語変更したらサイドナビが閉じる

## 動作環境・ブラウザ / Environment
- iOS / Android

**Comment by ksk1015** [comment]
やります

**Comment by kaizumaki** [comment]
ご提案ありがとうございます！もうちょっと詳しく知りたいです。言語変更したときにメニューを閉じた方がいいのでしょうか？動作として、不自然な感じにはならないでしょうか？

**Comment by ocean3fish** [comment]
そのままサイドメニューの内容を見たい場合もあると思うので、自動で閉じるとかえってユーザの意図しない挙動となってしまう可能性がありますね。
その点ご検討頂けるでしょうか。

**Comment by ksk1015** [comment]
言語を変更する操作は、その言語のページに移動するイメージがあったので、通常メニューのクリックでページ移動のときと同じ動作がベターと思い改善案を出しました。

> 不自然な感じにはならないでしょうか？
不自然と感じるのは意外だったんですが、不自然なのは、言語の変更はページ移動ではなくて文字がその言語に置き換わるイメージだからですかね？

> 自動で閉じるとかえってユーザの意図しない挙動
少なくとも私にとっては閉じないのが意図しない挙動でした。

> サイドメニューの内容を見たい場合もある
その可能性も否定はできませんが、そのコンテンツそのものを見たくてサイトにいると思うので、素直にコンテンツを見せるほうがいいかなと思います。

※些末な改善案なので通らなくても全然いいですが、いろいろ意見を知れておもしろいです。

**Comment by mcdmaster** [comment]
皆さま

スミマセン、PR #3618 でサイドメニューをいろいろイジっています。
本件に関しても、以降 #3618 で引き取ってしまおうかと。
いかがでしょうか？

**Comment by kaizumaki** [comment]
すみません、#2844 のPRを一旦クローズにさせていただきましたので、issueも一旦クローズとします。
