### ISSUE TITLE
スマホ版のサイドナビゲーションを表示したままPC版に切り替えるとコンテンツがスクロールできない

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#2843]
## 起こっている問題 / The Problem
- スマホ版のサイドナビゲーションを閉じずに、PC版に表示を切り替えた場合、コンテンツがスクロールできない

## スクリーンショット / Screenshot

![output2](https://user-images.githubusercontent.com/42484226/78422094-b8c0be00-7697-11ea-95b1-ca070615c7e1.gif)

## 期待する見せ方・挙動 / Expected Behavior
- PC版に切り替わった後、コンテンツがスクロールできる

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://dev-covid19-tokyo.netlify.com/ を開く
2. ウィンドウ幅を狭め、スマホ版に切り替える
3. サイドナビゲーションを開く
4. ウィンドウ幅を広げ、PC版に切り替える

Landscapeモードの場合にPC版が表示される画面幅を持つスマートフォンでは、以下の手順でより簡単に再現します。（iPhone XSで確認）
1. Portraitモードで https://dev-covid19-tokyo.netlify.com/ を開く
2. サイドナビゲーションを開く
3. 端末を回転させ、Landscapeモードに切り替える

## 動作環境・ブラウザ / Environment
以下の環境で確認済み
- macOS 10.15 / Chrome 80.0.3987.149
- iOS 13.3 (iPhone XS) / Safari

**Comment by Aqua-ix** [comment]
PC表示に切り替わった際にサイドナビゲーションを閉じるようにすれば解決できるかもしれません。
私の方で対応してみます。
