### ISSUE TITLE
Production と Development でカードの `box-shadow` のスタイルが異なる

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#2861]
## 起こっている問題 / The Problem
- Production, Staging でグラフカードの `box-shadow` が濃くなっています
- Development のみ他のカードと同様に薄い `box-shadow` になっています

### Production: https://stopcovid19.metro.tokyo.lg.jp/
![スクリーンショット 2020-04-04 22 28 52](https://user-images.githubusercontent.com/5207601/78452003-c7bd6580-76c3-11ea-942a-f9423b100a4b.png)

### Staging: https://stg-covid19-tokyo.netlify.com/
![スクリーンショット 2020-04-04 22 34 40](https://user-images.githubusercontent.com/5207601/78452144-84afc200-76c4-11ea-90a2-b0d39e941069.png)

### Development: https://dev-covid19-tokyo.netlify.com/
![スクリーンショット 2020-04-04 22 31 05](https://user-images.githubusercontent.com/5207601/78452053-03582f80-76c4-11ea-97d2-d0500ae5a74b.png)

## 期待する見せ方・挙動 / Expected Behavior
- 各環境でグラフカードの `box-shadow` のスタイルが統一されること
- サイト全体のデザインや [Figma のデザイン](https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=121%3A156) をみると development が正しいと思われる

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/ を開いてグラフが表示されたカードを確認

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome / Safari / Firefox

**Comment by f-koki** [comment]
developmentに揃える、で良さそうですかね。
こちら対応します！

**Comment by f-koki** [comment]
`.DataVue` に指定している `0 0 2px rgba(0, 0, 0, 0.15)` がvuetifyのCSSに上書きされている。
　
PROD/STG環境とDEV環境でsassのbuild方法が違い、
読み込み順番に差異があるため起こっている問題の模様。

↓vuetifyのCSS

```css
.v-card {
   ...
  box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12);
}
```

どう修正するかはひとまず検討中。

**Comment by shgtkshruch** [comment]
同じ原因かはわかりませんが、Nuxt.js にも似たような issue がありました。
https://github.com/nuxt/nuxt.js/issues/4219

**Comment by kaizumaki** [comment]
こちら、だいぶvuetifyのバージョンも上がってきているので、再現しないかもしれません。一旦issueはクローズといたしますね。一方で、vuetifyのパッチアップデートは要注意という認識でいます。
