### ISSUE TITLE
「都営地下鉄の利用者数の推移」グラフにテキストを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#2877]
以下画像の赤枠部分に、次のテキストとリンクの追加をお願いします。

テキスト `鉄道利用者数の推移（新宿、東京、渋谷、各駅エリア）`
リンク `https://smooth-biz.metro.tokyo.lg.jp/archive/date.pdf`

![開発項目7](https://user-images.githubusercontent.com/14883063/78468381-714b3800-7752-11ea-9b16-ac13a58f4fd3.png)

なにか疑問点あれば、このissueにコメントしてください！

**Comment by fukubaya** [comment]
はじめまして。

試しにやってみたのですが、日本語以外はどうすればいいでしょう?

<img width="545" alt="スクリーンショット 2020-04-05 18 00 40" src="https://user-images.githubusercontent.com/1461773/78470855-7e265680-7767-11ea-99af-3767a6df9e82.png">

**Comment by masnagam** [comment]
すでに他の方が修正されているようですが，２点確認があります．

* `<a>`に適用するスタイルはありますか？
* リンククリック時は新しいタブ（ウィンドウ）を開いたほうがよいですか？

**Comment by kaizumaki** [comment]
@fukubaya ありがとうございます！日本語以外はTransifex側で対応する流れになっています。ですので、こちらでは `ja.json` に翻訳キーを追加するまでの作業になります。

スタイルについては、他のグラフにある「オープンデータを入手」の見栄えとそろえていただくのがいいかなと思います。

**Comment by fukubaya** [comment]
@kaizumaki  了解です。それで進めてみます。
