### ISSUE TITLE
「お子様をお持ちの皆様へ」ページへコンテンツの追加・修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#2886]
### 追加
「お子様をお持ちの皆様へ」ページに以下のコンテンツの追加をお願いします。
追加する位置は一番先頭（下記画像の赤枠）です。
新たにカード `<StaticCard>` を設置するイメージです。
![開発項目8](https://user-images.githubusercontent.com/14883063/78473530-52fa3200-777c-11ea-84a4-20eacc359ee7.png)

追加するタイトル `学びの支援サイト`
タイトルに貼るリンク `https://www.kyoiku.metro.tokyo.lg.jp/school/content/learning_support.html`
※リンクは `target="_blank"` にしてください。
※説明文は後日追加予定です。

***
### 修正
現状の「お子様をお持ちの皆様へ」ページの各コンテンツのタイトル先頭のナンバリングを削除します。

結果的に以下のようなコンテンツ構成になります。
```
学びの支援サイト
感染予防・健康管理
感染症を疑う場合の対応
その他
```

なにか疑問点ありましたらコメントしてください！

**Comment by fukubaya** [comment]
できそうなのでやります。
