### ISSUE TITLE
「当サイトについて > Google Analyticsの利用について」文字列が正常に表示されていない

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#2887]
## 起こっている問題 / The Problem
- https://dev-covid19-tokyo.netlify.com/about/ にて，「Google Analyticsによる情報送信を回避する場合は、Google がサポートする 測定を無効にするブラウザ アドオン をご利用ください。」と表示されるべきところが，「$t('Google Analyticsによる情報送信を回避する場合は、Google がサポートする 測定を無効にするブラウザ アドオン をご利用ください。')」となっている．

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-05 21 13 54](https://user-images.githubusercontent.com/23148331/78487724-8475fc00-7782-11ea-8d24-e0673d8499c1.png)
## 期待する見せ方・挙動 / Expected Behavior
- 「Google Analyticsによる情報送信を回避する場合は、Google がサポートする 測定を無効にするブラウザ アドオン をご利用ください。」と表示されるよう修正する．

## 起こっている問題の再現手段 / Steps to Reproduce
https://dev-covid19-tokyo.netlify.com/about/

**Comment by nard-tech** [comment]
着手します

**Comment by kaizumaki** [comment]
#2875 で修正されています。

**Comment by nard-tech** [comment]
@kaizumaki 失礼しました．close します．
