### ISSUE TITLE
開発環境で、WorkingCopyの同期などの操作を効率良くおこなう

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#2906]
## 改善詳細 / Details of Improvement
開発環境で、WorkingCopyの同期などの操作を効率良くおこなう
1. 指定したブランチの同期
1. マージコンフリクト解消後のコミット(https://github.com/tokyo-metropolitan-gov/covid19/issues/2016#issuecomment-605468596)

## スクリーンショット / Screenshot
無し

## 期待する見せ方・挙動 / Expected behavior
シェルスクリプトを追加し、1行で操作できるようにする

## 動作環境・ブラウザ / Environment
開発環境

**Comment by kaizumaki** [comment]
開発環境も落ち着いてきているので、こちらのissueは一旦クローズさせてください。
