### ISSUE TITLE
fontawesomeのcss削除

### ISSUE THREAD

**Issue by yokrh** [tokyo-metropolitan-gov/covid19#2911]
## 改善詳細 / Details of Improvement
- fontawesomeのcssが不要ならば削除する
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/nuxt.config.ts#L58

## スクリーンショット / Screenshot
Chrome開発ツールのAuditsを見る限り使ってなさそう
![image](https://user-images.githubusercontent.com/10173918/78531435-f51b2800-7817-11ea-9545-9a82fcbbee84.png)

**Comment by mcdmaster** [comment]
セキュリティ担当（と、勝手に名乗っています）としてお尋ねします。教えてクレクレ君で申し訳ありません。

この CSS は、`@mdi/font` パッケージをインストールすると勝手についてくるものと私は理解しているのですけど、これは正しいでしょうか？
いずれにしても、CSS が脆弱性となる例もこれまでにはありましたので（下記参照）、未使用の CSS の削除には賛成です。

【参考事例】
Drupal にインストールされた fontawesome CSS で、フィールドのサニタイズが正常でないためリモートからコードを実行される可能性のある脆弱性について
https://www.drupal.org/sa-core-2019-003

**Comment by yokrh** [comment]
mdi（Material Design Icons）とfontawesomeは別々のアイコンセットですね。両方Vuetifyと相性が良いようです。（今知りました）
https://vuetifyjs.com/en/customization/icons/

mdiはこの時に追加されていて、
https://github.com/tokyo-metropolitan-gov/covid19/commit/d27734c1f73f44e835f000ff1934beea5fc01331

fontawesomeはこの時に追加されていました。
https://github.com/tokyo-metropolitan-gov/covid19/commit/2f641487010240f510c85f7a4bb29642527c06e1
初期のLINEアイコンのために使われていますね。

現在、SNSアイコンは画像が使われています。
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/DataView.vue#L86
なので、fontawesomeのcssは差し替えた時の残骸のようですね。

**Comment by mcdmaster** [comment]
丁寧なご説明、ありがとうございます。
私の方でも grep してみましたけれども、特に他で `import` しているような箇所も見当たりませんでした。
後で、PR 出しておきます

**Comment by yokrh** [comment]
早々にご対応いただきありがとうございました！
