### ISSUE TITLE
相談件数が多い際にカードタイトルがはみ出る

### ISSUE THREAD

**Issue by daitasu** [tokyo-metropolitan-gov/covid19#293]
## 概要
相談件数が多く、3行になるとカードタイトルがはみ出ます。
タイトル部が固定値 `80px` になっているのですが、特に決まりがなければ `auto` に変えたいです。
<img width="361" alt="スクリーンショット 2020-03-04 1 15 31" src="https://user-images.githubusercontent.com/28728602/75795639-f212bf00-5db5-11ea-899a-694ac0ab61f3.png">

**Comment by halsk** [comment]
確認して不具合がでなければやりましょう！

**Comment by daitasu** [comment]
こちら途中のようなので、いただきますね！

**Comment by kaizumaki** [comment]
#391 で修正プルリクマージ済みです。
