### ISSUE TITLE
一部の環境で多言語対応選択メニューが正しく開けない

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#2933]
## 起こっている問題 / The Problem
- PR #2878 の commit https://github.com/tokyo-metropolitan-gov/covid19/commit/49b8482344bf0aed9ded7751488f64e56a79d76f 以降、多言語対応選択メニューが特定環境で期待している挙動を示さない
- 環境によって異なる挙動が発生する
- #2935 で一旦Revertされているため、再現方法については「起こっている問題の再現手段」を参照してください

### 挙動1. 多言語対応選択メニューが開いた直後に閉じられる
- macOS 10.15 / Chrome 80.0.3987.149
- Windows 10 1809 / Chrome 80.0.3987.149

### 挙動2. 多言語対応選択メニューのクリック判定領域が狭い
- iPhone XS / iOS 13.3 / Safari
- Windows 10 1809 / Edge 44.17763.831.0

### 挙動1
![output5](https://user-images.githubusercontent.com/42484226/78572381-5962d980-7862-11ea-97b6-3edff0d3545a.gif)

### 挙動2
iPhone XS / iOS 13.3 / Safari で反応する領域
![IMG_0311](https://user-images.githubusercontent.com/42484226/78576783-215e9500-7868-11ea-9887-ad0564c89015.PNG)

Windows 10 1809 / Edge 44.17763.831.0 で反応する領域
- `.LanguageSelector-Background` の padding 部分（図中の赤い領域）
![無題](https://user-images.githubusercontent.com/42484226/78576853-363b2880-7868-11ea-8fdf-20685e36a3c6.png)

## 期待する見せ方・挙動 / Expected Behavior
- どの環境でも多言語対応選択メニューが開ける

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://5e8b34efb8829d000729f3ef--dev-covid19-tokyo.netlify.com/ を開く
2. 多言語対応選択メニューを開く

### 発生する環境
- macOS 10.15 / Chrome 80.0.3987.149
- Windows 10 1809 / Chrome 80.0.3987.149
-  iPhone XS / iOS 13.3 / Safari
- Windows 10 1809 / Edge 44.17763.831.0

### 発生しない環境
- macOS 10.15 / Firefox 73.0.1
- macOS 10.15 / Safari 13.0.2

**Comment by kaizumaki** [comment]
ご報告ありがとうございます！もしかして #2878 のマージで発生しているのでしょうか。フォーカスについてのPRだったので、多言語メニューまでは確認していませんでした 🙇‍♀

**Comment by kebhr** [comment]
@kaizumaki 
履歴を戻して確認すると、#2878 に含まれるコミット https://github.com/tokyo-metropolitan-gov/covid19/commit/49b8482344bf0aed9ded7751488f64e56a79d76f から問題が発生しました。
他の環境で調査したところ、iOS / Safari や Windows / Edge (EdgeHTML) では多言語選択メニューに関してまた異なる挙動を示すようです。
一旦PR本文を整理します。

**Comment by kaizumaki** [comment]
@kebhr ありがとうございます。とりいそぎ、 #2878 をリバートするPR #2935 を作成しました。いまはこちらをマージして対応しようと思います。

**Comment by furandon-pig** [comment]
すみません、私の方でプルリクを出していた #2878 での修正確認が不十分でした。
原因調査・修正を行いますので今しばらくお待ちいただければと思います。

**Comment by kaizumaki** [comment]
こちらのissueについては、現在解決しているためクローズといたします。フォーカスの見た目に関する事象は、現時点では特に問題になっていないと思われますが、あまりに気になるということであれば、別途の対応でお願いしたく思います 🙏
