### ISSUE TITLE
バタフライチャート の追加

### ISSUE THREAD

**Issue by TOSUKUi** [tokyo-metropolitan-gov/covid19#2937]
## 改善詳細 / Details of Improvement
- 年齢と男女の感染者数の分布を一目でわかるようにしたい

## 期待する見せ方・挙動 / Expected behavior
- 以下のように
![image](https://user-images.githubusercontent.com/12374481/78579579-1c9be000-786c-11ea-881c-af53b7a71468.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@TOSUKUi ご提案ありがとうございます。こちらのissueについて都に確認いたしました。同様の #454 でもコメントしましたが、現在、他の検討事項が優先されている状況です。採用されることが現時点では見込めないため、こちらのissueはクローズさせていただいてよろしいでしょうか。

**Comment by kaizumaki** [comment]
都からの回答がありましたので、こちらのissueはクローズさせていただきます。ご提案いただいた内容につきましては、今後の参考としたいと思います。
