### ISSUE TITLE
「都営地下鉄の利用者数の推移」グラフのリンクテキストの修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#2947]
「都営地下鉄の利用者数の推移」グラフのリンクテキストとリンク先の修正をお願いします。
- テキスト修正
```
鉄道利用者数の推移（新宿、東京、渋谷、各駅エリア）
　↓
鉄道利用者数の推移（新宿、東京、渋谷、各駅エリア）[PDF]
```
- リンク先修正
```
https://smooth-biz.metro.tokyo.lg.jp/archive/date.pdf
　↓
https://smooth-biz.metro.tokyo.lg.jp/pdf/202004date3.pdf
```
![コメント 2020-04-07 104119](https://user-images.githubusercontent.com/14883063/78620976-62809480-78bc-11ea-8ffd-7b26b4223f5e.jpg)

**Comment by kebhr** [comment]
対応しますー。
