### ISSUE TITLE
「陽性患者の属性」表の年代のソートの不具合

### ISSUE THREAD

**Issue by HiroshiKijima** [tokyo-metropolitan-gov/covid19#2949]
## 起こっている問題 / The Problem
- 「陽性患者の属性」表にて、年代でsortすると、10代の後に10歳未満が出てくる

## スクリーンショット / Screenshot
![sortResult](https://user-images.githubusercontent.com/37971245/78630414-a2537600-78d4-11ea-999d-97b8d6237771.png)

## 期待する見せ方・挙動 / Expected Behavior
- 10歳未満、10代、20代、と並ぶこと

## 起こっている問題の再現手段 / Steps to Reproduce
1. 「陽性患者の属性」表にて年代でsortする

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by mcdmaster** [comment]
@halsk こちら、「10歳未満」でなく「0～9歳」のような表示値を用いれば、 @HiroshiKijima さんにご指摘をいただいたカラムソートの問題を解決できます。いかがでしょうか？

あるいは、他に何かアイディアがありましたら、ぜひともお知らせいただけますようお願いいたします

**Comment by kebhr** [comment]
@mcdmaster 
`v-data-table`の`custom-sort` Propを用いてソート関数を以下のように再定義すると、テキストの変更を行うことなくIssueが解決できました。
既に着手されているところ申し訳ありませんが、関係部署への確認が不要な解決策として、こちらでPRを作成してもよろしいでしょうか？
```typescript
customSort: (items: Object[], index: string[], isDesc: boolean[]) => {
  items.sort((a: any, b: any) => {
    if (index[0] === '年代') {
      if (a[index[0]] === '10歳未満') {
        if (b[index[0]] === '10歳未満') {
          return a['公表日'] > b['公表日'] ? -1 : 1
        } else {
          return !isDesc[0] ? -1 : 1
        }
      } else if (b[index[0]] === '10歳未満') {
        if (a[index[0]] === '10歳未満') {
          return a['公表日'] < b['公表日'] ? -1 : 1
        } else {
          return !isDesc[0] ? 1 : -1
        }
      } else if (!isDesc[0]) {
        return a[index[0]] < b[index[0]] ? -1 : 1
      } else {
        return b[index[0]] < a[index[0]] ? -1 : 1
      }
    } else if (!isDesc[0]) {
      return a[index[0]] < b[index[0]] ? -1 : 1
    } else {
      return b[index[0]] < a[index[0]] ? -1 : 1
    }
  })
  return items
}
```

実行例
![image](https://user-images.githubusercontent.com/42484226/78710457-5ba36180-7950-11ea-80a3-0938c557c5eb.png)
![image](https://user-images.githubusercontent.com/42484226/78710501-665df680-7950-11ea-978d-242682f76646.png)

**Comment by mcdmaster** [comment]
@kebhr あ、もちろんです。ぜひとも PR 提出をお願いいたします。

私のやり方だと、データ・アイテムの値に手を加えるのでイケてないなあと思っていたところでした。
本当に助かります。ありがとうございます！
