### ISSUE TITLE
レスポンシブのリファクタリング

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#295]
現在 `layouts/default.vue` でresizeイベントをとり、 `this.isMobile = window.innerWidth < 600;` としているのですが、MediaQueryのmixinがあるのでそちらに統一したいと思っています。
そこでご相談なんですが、どのbreakpointからモバイル表示に切り替えたらいいでしょうか？
いま `assets/variables.scss` にあるbreakpointの変数は以下のとおりです。
```
$huge: 1440;
$large: 1170;
$medium: 768;
$small: 450;
```

**Comment by yokinist** [comment]
@kaizumaki mobileが判断するのが目的でしたらsmallがSP幅を想定しているので以下の書き方がいいかなと思います！また、breackpointの値は仮で置いたものなので都合が悪ければ更新しちゃって問題ないです！
```scss
@include lessThan($small) {
}
```

**Comment by kaizumaki** [comment]
@yokinist  ですね！ありがとうございます！とりあえず `$small` のmixinにおきかえて、値は様子見て変更するなりすればいいかなと思いました。着手します！
