### ISSUE TITLE
zh-TW document symbol typo

### ISSUE THREAD

**Issue by louis70109** [tokyo-metropolitan-gov/covid19#2952]
## 起こっている問題 / The Problem
- zh-TW ducoument symbol typo，[URL](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/docs/zh_TW/README.md#%E7%94%9F%E7%94%A2%E7%92%B0%E5%A2%83%E5%85%B6%E4%BB%96%E7%92%B0%E5%A2%83%E7%9A%84%E5%88%A4%E5%AE%9A)

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by kaizumaki** [comment]
#2953 をマージしましたので、こちらのissueはクローズします 🙏
