### ISSUE TITLE
「お問い合わせ先一覧」に注意書きを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#2954]
「お問い合わせ先一覧」ページ内「新型コロナウイルス感染症の予防・検査・医療に関すること」の項目の電話番号の下「（新型コロナコールセンター）」の下に以下の注意書きの追加をお願いします。
```
電話のおかけ間違いが多くなっております。発信の際は今一度電話番号をお確かめの上、お間違えのないようお願いいたします。
```
↓デスクトップ表示の場合はこの赤枠の位置
![コメント-2020-04-07-153429](https://user-images.githubusercontent.com/14883063/78637661-ccf9fa80-78e5-11ea-83b5-912466aa706f.jpg)

↓モバイル表示の場合はこの赤枠の位置になる
![注意書き追加](https://user-images.githubusercontent.com/14883063/78637679-d4210880-78e5-11ea-9640-a84750ce43b5.png)

**Comment by whisky-shusuky** [comment]
対応させて頂きたいと思います！
