### ISSUE TITLE
PC・タブレット（横位置）表示での「検査陽性者の状況」「検査実施状況」チャートの垂直方向ズレ

### ISSUE THREAD

**Issue by masayasuyamamoto60** [tokyo-metropolitan-gov/covid19#2955]
## 起こっている問題 / The Problem
- PCやタブレット（横置き）で見たときに「検査陽性者の状況」「検査実施状況」のチャートの水平位置が微妙にずれている。

## スクリーンショット / Screenshot
添付画像参照
![sample chart_misaligned](https://user-images.githubusercontent.com/12755558/78637964-6b865b80-78e6-11ea-9463-fda3ded27a38.jpg)

## 期待する見せ方・挙動 / Expected Behavior

「検査陽性者の状況」「検査実施状況」はフレームが同形状、チャート高さも同サイズなので、垂直にそろって見えるべき。その結果コンテンツに集中できる画面になる。

解決方法：
１．「検査陽性者の状況」下の注のスペースを調整して、「検査実施状況」のチャートと高さをそろえる。
２．「検査陽性者の状況」、「検査実施状況」ともに注をチャートの下に移動する。

## 起こっている問題の再現手段 / Steps to Reproduce
1. PCで画面を表示する
2. iPadなどで、横位置にして画面を表示する

## 動作環境・ブラウザ / Environment
- Windows 10 Pro/ iOS 13.3.1
- Chrome (win) / iCabMibile(iOS)

**Comment by mcdmaster** [comment]
たしかに、グラフィカルな表示にちょっとしたズレがあるとストレスの源になることがありますね。
ご指摘ありがとうございます。

イメージ的には、下の画像のようになればよろしいでしょうか？
グラフ上部のテキスト部分の高さを 80px に固定してみました。

オーケーでしたら、プルリクエストを起票します。ご確認をお願いいたします
![2020-04-08 181228](https://user-images.githubusercontent.com/10361533/78766698-921ac400-79c4-11ea-9a44-773dc1cf73a8.png)

**Comment by masayasuyamamoto60** [comment]
早速のご対応ありがとうございます。OKです。
ちょっとしたズレほど気になって中身が見れなくなります。

**Comment by mcdmaster** [comment]
@kaizumaki こちら、discussion ラベルを付けていただけますでしょうか。
私は、ラベリングの権限をどうやら持ち合わせていないようです。
お手数ですけれども、宜しくお願いいたします

**Comment by mcdmaster** [comment]
@masayasuyamamoto60 @kaizumaki ちょっと長めのコメントをさせてください。

まことに勝手ながら、本イシューは、今後においても東京都 COVID-19 情報サイトにおけるヒューマン・インターフェースを議論する場、今ふうに言えば UI/UX を議論する場として使っていきます。ちなみに、プルリクエストは取り下げています。なぜなら、まさにそうした議論が未だ不十分と思われたためです。

まず極論から申し上げれば、我々開発チームの使命は、都から提供された COVID-19 関連データを正確かつスピーディに「人の見える（読める）形で」提供することのみと私は考えています。少しこぼれ話をすると、ちょうど 2020 東京五輪の延期が決まって以降急激に感染者数が増大したことにつき、知事が数字を隠していたのではないか？ということを私の周りでも、それもかなり社会的地位の高い職業に就いている人からも聞かされました。私はそのとき、たいへん悔しい思いをしました。で、そこで収まらないのが私の悪いところで(笑)、そのしっかりとした職業の人に「だったら GitHub アカウントを取ってログインしてみてください。そんな恣意的なデータ操作ができないことくらいすぐにわかりますよ」とタンカを切ったものです。

とはいえ、そういうタンカを切るにあたっては、データを集めてアウトプットするという、我々の用語で言えばデータ・カストディアンとして振舞うだけでなく、まさに @masayasuyamamoto60 さんにご指摘をいただいたように、それを心地よく参照するための UI/UX を提供できるかが今後の鍵になってきます。
正直に申し上げれば、私も企業システム、特に株式を公開しているような大企業のシステムばかりでキャリアを積んできましたので、オープンソース・コミュニティ活動は結構斜に構えて見ていました。でも、このプロジェクトに関わるようになってからは、その種の考えは 100% なくなりましたね。

私は、企業システムにおいてはまさに out-of-box のシステムに日本のユーザさんにご満足いただくためのカスタム UI を実装するといったプロジェクトにも携わってきました。対するオープンソース的には、おそらくそこは乱暴に言えば「気に入らなきゃ自分で好きに直してください」的な感覚なのだろう、というところまでわかってきました(笑)。でも、皆が皆それをできるわけではありません。当然ですね。

そうした、オープンソース・コミュニティに参加できない、あるいは端から参加するつもりがない人も、本サイトがもたらすメリットを等しく享受する権利があります。UI/UX のカイゼンとは、大上段に構えれば、まさにそうした権利の擁護のためにオープンソース・コミュニティは何ができるかの挑戦でもあります。どうか、継続的な議論にお付き合いをいただけますなら幸いです

**Comment by nard-tech** [comment]
@mcdmaster 抽象的・理論的な話も含めて UI/UX を議論したいのであれば，別の issue をご自分で作られた方がよろしいと思います．
このレポジトリでは基本的に issue と PR をセットで扱っていて，PR が merge されたら issue を close するという運用になっていますし，この issue は単に個別のチャートのデザインを扱うためのものですので，ここで勝手に議論を始められても誰の目にも付きませんし，運用の基本ルールを逸脱するようなことをしても誰も付いてこないと思いますよ．

**Comment by mcdmaster** [comment]
@nard-tech 「勝手に議論」のくだりは、事実誤認があるためご訂正をお願いしたいところです。詳細は関連する PR を追っていただけるとわかりますけど、私が「勝手に議論」を始めたのではありません。

あるいは、一般的なイシューと PR の関係、別の視座で見ればイシューやリスクとそれへの対応策（レスポンス）といった業務プロセスにまるで疎いかのように指弾されるのは、正直穏やかな気持ちがしません。まあ、そういうご印象を持たれたのであれば、それはそれで私がこの GitHub という場でプロとして振舞えていなかったことをご指摘いただけたのかもしれませんけれども。

いずれにしても、別イシューに留まらず、リポジトリまで独立させて議論なんてこともあるかもしれませんね。とはいえ、そういうアクションの端緒として本イシューがあるので、そこでまずいったんは説明を尽くすというのが私の考えでした。

それにしても、新型コロナ禍は憎いですね。こういう話は F2F ですればとてもわかりみだと思うのですけど。オンライン・コミュニケーションがまだまだ不得手な私はもっと勉強せんといかんですね(笑)

**Comment by masayasuyamamoto60** [comment]
@mcdmaster 主張は理解できました。
十分な議論がなされていないということですが、プルリクエストは取り下げたあと、今後どのように進められるのでしょうかお示しください。

『都から提供された COVID-19 関連データを正確かつスピーディに「人の見える（読める）形で」提供することのみ』ということですが、提供側からはそれでいいのかもしれませんが、享受者側が正確かつスピーディに受けてれるのかという点ではどうでしょうか。例えば「正確に」ということで、数字の3桁ごとにカンマを追記したり、テーブルを使って情報をそろえたりといった配慮はしているわけで、モジュール間での垂直方向のアラインメントも（情報を受ける側からすれば）同じ次元の配慮だと思います。
（いわゆるUX的な観点から）指摘できることは多々ありますが、最初に目に飛び込み、気になる点ですので指摘しております。

**Comment by kaizumaki** [comment]
すみません。現在、都から新規グラフ・表の追加およびグラフ・表の並べ替えの依頼がきています（データの関係でまだ起票していません）。それにより、こちらの表題のチャートについては現在の位置から変更される可能性が大きいです。なので、こちらの表題については一度クローズしていただくことをおすすめします。
新たな表題でissueを立て、議論していただくことはもちろんかまいません。

**Comment by masayasuyamamoto60** [comment]
承知しました。
一旦クローズ

**Comment by mcdmaster** [comment]
@masayasuyamamoto60 さん、ご協力ありがとうございます。

差し支えなければ、UI/UX に関するディスカッション用の新イシューを起票していただくのは可能でしょうか？
そのイシューの中で、議論を続けましょう。お尋ねいただいた、私が考える UI/UX カイゼンのプロセス（あるいはロードマップ）についてもそこでお伝えしたいです。

とはいえ、スポンサーたる東京都のオーソライズが未だないプランなど、まさに @nard-tech さんがおっしゃる「勝手な議論」の域を出ません。そういうのは、あるいはそう評されるのは、私としても堪え難いです。
ですので、 @kaizumaki さんにはご面倒でも次の議論にもご参加をいただけるとありがたいです

**Comment by masayasuyamamoto60** [comment]
承知しました。
本スレッドを少し私なりに読み返して、何かできることをやってみましょう

**Comment by mcdmaster** [comment]
心強いお言葉をいただき、たいへんおそれ入ります。
まあ、私もとやかくチームに注文を出したりましてや「ご意見番」として振舞ったりする立場ではないのですけれども…。
このリポジトリに来ちまった以上、手を動かしてナンボだと思っています

**Comment by masayasuyamamoto60** [comment]
UX/Usability関連ディスカッションにつきイシューとしてあげました
https://github.com/tokyo-metropolitan-gov/covid19/issues/3350#issue-600686745
