### ISSUE TITLE
「東京都緊急事態措置について」のリンクボタンをサイトトップに設置

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#2966]
「東京都緊急事態措置について」というボタン（外部URLにリンク）をサイトトップに設置する実装をお願いします。

アイコン：mdi-bullhorn
テキスト：東京都緊急事態措置について
テキストカラー：$gray-2（ `#4d4d4d` ）※hover時も同様
背景色：`#FFE200` （`assets/variables.scss` に新たに変数を定義してください）
リンク：https://www.bousai.metro.tokyo.lg.jp/1007617/index.html

#### 実装イメージ
- デスクトップ表示のとき
![2020407_corona_pc-1](https://user-images.githubusercontent.com/14883063/78662422-5243d600-790b-11ea-9997-82d46e02922c.png)

- モバイル表示のとき
![2020407_corona_sp-1](https://user-images.githubusercontent.com/14883063/78662436-5839b700-790b-11ea-97c1-3141ca9722c7.png)

- ボタンhover時
![2020407_corona_pc-1-hov-2](https://user-images.githubusercontent.com/14883063/78662445-5f60c500-790b-11ea-88d9-85ca3ddfc167.png)

※ リンクは `target="_blank"` にしてください。イメージ図にはありませんが、他の外部リンクと同様に外部リンクアイコン `mdi-open-in-new` をつけてください。

なにか疑問点あれば、こちらのissueにコメントしてください！

**Comment by nard-tech** [comment]
着手します

**Comment by nard-tech** [comment]
@kaizumaki すみません，Vuetify のバージョンのせいか，`mdi-bullhorn` アイコンが使えません．他のアイコンで代用したいのですが，何かいいものはありますでしょうか．

**Comment by nyagihime** [comment]
@nard-tech どうも、ビルドし直すと出るっぽいです
ためしに一度Dev Server落としてnuxt再起動してみてもらってもよいでしょうか？

**Comment by nard-tech** [comment]
ただ再起動するだけではダメでしたが，
```
$ yarn cache clean nuxt
```
することで出るようになりました．ありがとうございます．

**Comment by nyagihime** [comment]
ビルドというよりは、Nuxtのキャッシュでしたか
なんにしても出るようになってよかったです

**Comment by nard-tech** [comment]
@kaizumaki 完成しました．レビューお願いします．
