### ISSUE TITLE
メタタグの変更

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#297]
![google検索結果](https://user-images.githubusercontent.com/61729733/75832652-07a9d800-5dfa-11ea-8891-51fe205a72d3.png)

Google検索結果がこの状態ですので、メタタグを下記の説明文に変更お願いします。

当サイトは新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、東京都が開設したものです。

**Comment by yokinist** [comment]
なんと！対応します！

**Comment by NaoyaShimizzz** [comment]
よろしくお願いします！
