### ISSUE TITLE
「陽性患者の属性」表における居住地の表記揺れ

### ISSUE THREAD

**Issue by ham-ham-8** [tokyo-metropolitan-gov/covid19#2984]
## 改善詳細 / Details of Improvement
「陽性患者の属性」表にて、居住地に「-」「‐」「―」など見た目は似ているがことなる文字が使用されている。居住地でソートすると簡単に確認可能。
また、それらが何を意味するのかわかりにくい（「調査中」というレコードがあることを確認して、初めて「-」などが「不明」を意味する事がわかる）

## スクリーンショット / Screenshot
<img width="483" alt="「陽性患者の属性」表における居住地の表記揺れ" src="https://user-images.githubusercontent.com/25416222/78736171-7ba24780-7987-11ea-8d8c-96f1e96e697c.png">

## 期待する見せ方・挙動 / Expected behavior
「-」「‐」「―」を一律「不明」などの表記に修正する

## 動作環境・ブラウザ / Environment
- macOS / iOS
- Chrome / Safari

**Comment by kaizumaki** [comment]
@ham-ham-8 ご提案ありがとうございます！ハイフン問題については運営側でも認識しており、改善しようと検討しているところです。
>それらが何を意味するのかわかりにくい

ハイフンについては現状、複数の意味を指しているのですが、非常にセンシティブなデータのため、なかなか明らかにしにくいという事情があります。こちらも運営側で検討している最中です。

**Comment by nichesuch** [comment]
おそらく既に「―」に統一されたものと思われます。
Closeお願いします。
![image](https://user-images.githubusercontent.com/2096703/79682703-4dfaaf80-825f-11ea-9e1a-66985420e1c4.png)

**Comment by kaizumaki** [comment]
@ham-ham-8 ご提案ありがとうございます。
@nichesuch フォローありがとうございます。
こちらのissueはすでにクローズしていただいていますが、念のため、都に確認をとりました。ハイフン問題（異なる字形が存在する）については、庁内のもともとのデータがそのようになっているため、異なる字形のハイフンの混在は避けようがない、とのことでした。
また、ハイフンが何を意味するかについては、何かしらの方法で提示できるように検討しているそうです。
