### ISSUE TITLE
感染経路の掲載を検討したい

### ISSUE THREAD

**Issue by anharu2394** [tokyo-metropolitan-gov/covid19#2987]
## 改善詳細 / Details of Improvement
- 感染経路が不明なのかどうか、特定されているならばどこで起こったのかを掲載してほしいです。注意喚起に繋がると思います。

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected behavior
なし

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by khsacc** [comment]
感染経路の特定が難航していると予想される現在において、公表するためのデータ整形を行政に依頼すること自体に、あまり賛同できないのが正直なところです……。他のissueにも言えるものはあるとは思うのですが、データを公表するということに伴うコストというのは相当なものであり、外出自粛要請が出される中、所詮「過去の情報」でしかない感染経路を公開することの優先度はそこまで高くないのではないでしょうか、、。

**Comment by kaizumaki** [comment]
@anharu2394 ご提案ありがとうございます。感染経路ではありませんが、接触歴等不明率というデータがモニタリング指標という形で公式に公開となりました。別issue #4324 を立てております。

**Comment by kaizumaki** [comment]
こちらのissueについて都に確認いたしましたところ、感染経路については個人の特定につながる可能性があるので公表は難しいとのことでした。ご理解いただきますようお願いいたします。せっかくのご提案に申し訳ありませんが、こちらのissueはクローズさせていただきます。
