### ISSUE TITLE
新型コロナコールセンター相談件数 右上の数字がおかしい

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#300]
+399件 となっているが、前日からの増加数を出すはず

**Comment by ocean3fish** [comment]
@halsk タイトルとスクショがあっていないようですが、こちらの件ですか？
昨日以下の修正が入ったため、仕様としては想定通りのはずです。
10,550 - 10,151 = 399
https://github.com/tokyo-metropolitan-gov/covid19/issues/276
<img width="581" alt="スクリーンショット 2020-03-04 10 08 00" src="https://user-images.githubusercontent.com/4206675/75834687-18f5e300-5e00-11ea-961d-2adde0509a4d.png">

**Comment by ocean3fish** [comment]
相談件数が日に日に増えていることを示したい意図はよくわかるのですが、やはり「推移」を表しているグラフにおいて「累計」での差分を示しているのは少々混乱を招きますね。
改善案を考えてみます。

**Comment by halsk** [comment]
あ、すみません。色々間違ってましたね。先方にも伝えておきます！

**Comment by ocean3fish** [comment]
@NaoyaShimizzz 以下のような変更を加えるのはいかがでしょうか？
案1：現行仕様で、下の説明を変える：**399** 前日比 → **399** 前日比（累計での差分）
案2：推移としての前日比を出す：**-75** 前日比
案3：本日の実績値を出す：**399** 3/2 実績値

**Comment by NaoyaShimizzz** [comment]
「推移」の見直しを考えています。

データとしては日別の実績データ（の推移）なので、
「推移」を「日別」に変えたほうが、よいかなと。ついでに「累積」も「累計」に。

「日別」　399   3/2 実績値
「累積」　15,500 3/2の累計

にすると伝わりやすいと考えますが、いかがでしょうか。

**Comment by mikkame** [comment]
少し長くなりますが

本日のお問い合わせ件数399件
（前日比-10件）

という表記なら分かりやすいのではないでしょうか？

**Comment by NaoyaShimizzz** [comment]
ありがとうございます。以下の案ではいかがでしょう。

399件
3/2 実績値（前日比-10件）

**Comment by ocean3fish** [comment]
イメージとしてはこんな感じでしょうか？
<img width="585" alt="スクリーンショット 2020-03-04 15 04 33" src="https://user-images.githubusercontent.com/4206675/75850003-8ec27480-5e29-11ea-9d01-e46800e959b2.png">

**Comment by ocean3fish** [comment]
同じルールで行く場合、累計はこんな感じに。
（余白の調整が必要ですね）
<img width="581" alt="スクリーンショット 2020-03-04 15 08 27" src="https://user-images.githubusercontent.com/4206675/75850206-0e504380-5e2a-11ea-8fe9-aba911ea2df8.png">

**Comment by NaoyaShimizzz** [comment]
ありがとうございます。-10件は
3/2 実績値 （前日比-10件）で同じサイズ・色をイメージしてました。前日比は大きいほうがいいですかね。

**Comment by ocean3fish** [comment]
@NaoyaShimizzz このような理解で合っているでしょうか？
前日比が少々小さいかもしれませんが、サイズは後ほど微調整ということで、一旦要素が表示できる状態まで進めて頂くのが良いでしょうかね。
<img width="580" alt="スクリーンショット 2020-03-04 18 28 05" src="https://user-images.githubusercontent.com/4206675/75864949-1fa74900-5e46-11ea-9ad5-3c5045459932.png">

**Comment by NaoyaShimizzz** [comment]
@ocean3fish ありがとうございます！要素としてはこちらでお願いします

**Comment by ocean3fish** [comment]
@NaoyaShimizzz ちなみに、すべての棒グラフで同じ仕様に切り替えるということでOKでしょうか？
陽性患者数の変更例：
<img width="576" alt="スクリーンショット 2020-03-04 18 41 19" src="https://user-images.githubusercontent.com/4206675/75866017-c5a78300-5e47-11ea-9b0c-ab45aa43c9da.png">

**Comment by NaoyaShimizzz** [comment]
@ocean3fish はい、こちらも併せてお願いします

**Comment by NaoyaShimizzz** [comment]
「前日比」ではない、わかりにくい、という意見を複数いただくので、早めに対応いただけるとありがたいです。

**Comment by nysopua** [comment]
「前日比」でなく「前日差」ということですかね

**Comment by halsk** [comment]
#359 で修正完了
