### ISSUE TITLE
[参考] Lighthouse によるレポート

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#301]
Lighthouse でチェックしてみました。スコアは63、改善の余地ありますね。
特にパフォーマンス。レポート添付しておきます。

![image](https://user-images.githubusercontent.com/16509/75835238-a6860280-5e01-11ea-974a-49c37bf9a700.png)

[Lighthouse Report Viewer.pdf](https://github.com/tokyo-metropolitan-gov/covid19/files/4284534/Lighthouse.Report.Viewer.pdf)

**Comment by halsk** [comment]
#477  で早くなったかな？と思ったらあまり変わらないですね。。
![image](https://user-images.githubusercontent.com/16509/75983372-c6b1e080-5f2b-11ea-867a-e9ecbf750167.png)

**Comment by MaySoMusician** [comment]
Desktopの方はこれより若干高いようです
![image](https://user-images.githubusercontent.com/34566290/75984324-87848f00-5f2d-11ea-8e61-3eeae125c5bf.png)
![image](https://user-images.githubusercontent.com/34566290/75984429-b7339700-5f2d-11ea-9688-26f194ecc3cd.png)
