### ISSUE TITLE
Canvasの代替の隠しテーブルのデータの行がすべて同じ値になっている

### ISSUE THREAD

**Issue by kzhrk** [tokyo-metropolitan-gov/covid19#3014]
## 起こっている問題 / The Problem
- Canvasの代替として用意されている隠しテーブルの行の値がすべて同じ値になっている

## スクリーンショット / Screenshot
<img width="1168" alt="スクリーンショット 2020-04-08 21 58 25" src="https://user-images.githubusercontent.com/548508/78786831-5859b580-79e4-11ea-896f-a5019b25f57f.png">

## 期待する見せ方・挙動 / Expected Behavior
- Canvasのグラフと同じ値がテーブルに出力されること

## 起こっている問題の再現手段 / Steps to Reproduce
ブラウザの開発ツールで.cardTableのstyleプロパティをリセットすると隠されたテーブルが表示確認できる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by KentarouTakeda** [comment]
@kzhrk @ymrl @kaizumaki 
すみません！光の速さで修正します！
