### ISSUE TITLE
日別/累計ボタンがbuttonタグで定義されている

### ISSUE THREAD

**Issue by kzhrk** [tokyo-metropolitan-gov/covid19#3021]
## 改善詳細 / Details of Improvement
日付/累計ボタンはbuttonタグで定義されていますが、どちらかが選択された場合にもう一方が解除されるUIであれば、`input[type="radio"]`で定義をしてステータス変更を予見できるようにしておくのがベターかと思います。

## スクリーンショット / Screenshot
<img width="1440" alt="スクリーンショット 2020-04-08 23 07 39" src="https://user-images.githubusercontent.com/548508/78794141-4ed54b00-79ee-11ea-9a3f-c78245fc990e.png">

## 期待する見せ方・挙動 / Expected behavior
- `label > input[type="radio"][name="name"]`でボタンのUIを定義
  - 見た目上の変化はありません

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
一つ、確認させてください。

愚直にラジオを実装すると、添付画像のようになります。
こうではなく、従前のボタン切換のルック＆フィールを踏襲するという理解でよろしいでしょうか？

![2020-04-09 201728](https://user-images.githubusercontent.com/10361533/78890095-f78fb300-7a9f-11ea-8c4f-8ef3f8a954cc.png)

**Comment by kzhrk** [comment]
> 従前のボタン切換のルック＆フィールを踏襲する

こちらの実装の想定です。デザインの変更はしないで、タグの変更のみを行う想定です。

**Comment by mmmmmmmmn** [comment]
こちら、どなたも着手されていないようであれば自分が対応しようかと思ったのですが、 @mcdmaster  さん、対応されますでしょうか。

**Comment by mcdmaster** [comment]
@mmmmmmmmn さん、はい、その想定です

**Comment by mmmmmmmmn** [comment]
かしこまりました、お騒がせいたしました…。
よろしくお願いします！

**Comment by mcdmaster** [comment]
@mmmmmmmmn さんをはじめ開発者の方々にお尋ねしたいのですけれども（今さら）、もしもこれを実装される場合、現状の `v-btn` を `v-radio` に置き換えるところから始めますか？あるいは `input` タグで書いてしまいますか。

私の方でもいろいろ試してみたのですけど、前者の方法、すなわち Vuetify のパーツを使うやり方は、ルック＆フィールが上手く引き継げないなど、予想以上に手間ですね。
あるいは、たとえば `v-btn` のままで radio 化させる方法があったりするのでしょうか。

そもそもの本件の目的は、２つの値が互いに exclusive であることを保障する、ならびのそのための機能を実装するというところだと私は思っています。それらプラス、ルック＆フィールの維持（もしくは向上）ができるのなら、方法は何でもいいと（極論すれば）思います。

皆さんのご意見をいただきたく

**Comment by mcdmaster** [comment]
…と思って見ていたら、こんなモジュールを見つけました。
https://uiv.wxsm.space/button/

ちょっと試してみようと思っているのですけど、このモジュールの実装にあたっての制約条件はあったりするでしょうか？

**Comment by mmmmmmmmn** [comment]
@mcdmaster さん
認識が合っているかが分からないのですが、もし自分が実装するとしたら、input タグで実装することを考えると思います。
簡単にコードを書いてみますので、少々お待ちください。

**Comment by mmmmmmmmn** [comment]
お待たせいたしました、
大雑把ですが、例えば次のようなコードで、ボタンの見た目をしたラジオボタンを作ることはできるかと思いますが、いかがでしょうか。

```html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>radio looks like button</title>
    <style>
        .wrapper {
            display: flex;
        }

        .wrapper>div {
            background: #fff;
            display: flex;
            flex-grow: 0;
            padding: 2px;
            border: 1px solid #4d4d4d;
        }

        .wrapper>div>div+div {
            margin-left: 2px;
        }

        .wrapper label {
            display: block;
            color: #fff;
            line-height: 1;
            padding: 5px;
            cursor: pointer;

            transition: .1s;
            background: #4d4d4d;
        }

        .wrapper label:hover {
            opacity: .8;
        }

        .wrapper input[type=radio]:checked+label {
            background: #008830;
        }

        .wrapper input[type=radio] {
            position: absolute;
            z-index: -1;
        }
    </style>
</head>

<body>
    <div class="wrapper">
        <div>
            <div>
                <input type="radio" name="type" id="selection1" checked>
                <label for="selection1">æ—¥åˆ¥</label>
            </div>
            <div>
                <input type="radio" name="type" id="selection2">
                <label for="selection2">ç´¯è¨ˆ</label>
            </div>
        </div>
    </div>
</body>

</html>
```

このコードは、ブラウザでは次のように見えるかと思います。
<img width="300" alt="スクリーンショット 2020-04-10 20 49 48" src="https://user-images.githubusercontent.com/51997429/78988825-f1b3d380-7b6c-11ea-95a8-dc9f75be476c.png">

**Comment by mmmmmmmmn** [comment]
コードを少し変更しました。

**Comment by magi1125** [comment]
ご対応ありがとうございます。

```
.wrapper input[type=radio] {
            display: none;
        }
```

display:noneにするとスクリーンリーダーでこのラジオボタンが操作できなくなるので、存在は残しつつ画面外に飛ばすというやり方に変更いただけるとよいかと思いました。
こちらが参考になるかと。https://github.com/tokyo-metropolitan-gov/covid19/pull/2496#discussion_r399637986

**Comment by oti** [comment]
> 存在は残しつつ画面外に飛ばすというやり方

Visually Hiddenというテクニックで、 `variables.scss` に mixin がありますので、これを利用していただけると！
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/assets/variables.scss#L151-L168

**Comment by mmmmmmmmn** [comment]
Visually Hidden のスタイルについて、質問です。

現状のスタイル定義ですと、見せないようにしたい要素が左上に残ってしまっており、やろうと思えば、下記動画のようにクリックできてしまうように思います。

![Kapture 2020-04-11 at 0 08 01](https://user-images.githubusercontent.com/51997429/79001042-bde6a700-7b88-11ea-84d7-8de9a060972b.gif)

完全に画面外に配置するならば、
```scss
@mixin visually-hidden() {
  …
  top: 100% !important;
  left: 100% !important;
  …
}
```

などとするのが良いのではないかと思いましたが、いかがでしょうか。

この issue からは少し話が逸れますが、少し気になったため、確認させていただきたいです。

**Comment by mmmmmmmmn** [comment]
申し訳ありません、
https://github.com/ampproject/amphtml/blob/2e9a940e78df8de38a6c06a0772aeaa4839a24d1/css/ampshared.css#L172-L173
に、
> \* element needs to have a defined size and be on viewport otherwise TalkBack
> \* does not allow activation of buttons.

との説明があることに気がつきました。

要素が画面内に存在することに意味があるのですね。
失礼いたしました…。🙇

**Comment by mcdmaster** [comment]
皆さんありがとうございます！

では、いただいたノウハウを components/DataSelector.vue に反映させた上で、プルリク出しますね。
なんだかちゃっかりしているようでスミマセン…。

**Comment by mcdmaster** [comment]
皆さんおつかれさまです。

途中報告です。遅々としていてスミマセン…でも、ほぼ９割方はできています。何につまづいているか？それは、同時に表示される複数の DataSelector ブロックの最後のものにしか checked 属性が効かないところです。それらは、１個のグループの中のラジオボタン群とみなされてしまうんですね。

それを個々にぶった切るために、ラジオボタンのペアを <form></form> で囲むとかの工夫をしています。それにしても、何しろ時間が取れません。在宅勤務なんですけどね。あ、在宅勤務だからなおさら、という事情はあるかもです。別イシューで心無い言葉を浴びせられてちょっとヘコんでたなんてこともありました。おっさんなのに(笑)

**Comment by MaySoMusician** [comment]
今は普通の（Vuetifyではない） `<input>` で実装しているのでしたっけ？
https://developer.mozilla.org/ja/docs/Web/HTML/Element/Input/radio#Defining_a_radio_group で `name` 属性に同じ値を割り当てるとそこでグループが形成されるようです。これで上手くいくかはわかりませんがお試しください。
`DataSelector` 側でradioボタンname属性用の値を受け取るようにすると実装可能だと思います。

**Comment by mcdmaster** [comment]
おお、素早い！ありがとうございます。

「今」とおっしゃるのは、現状の本番ページのことを指しておいででしょうか？だとしたら、答は `v-btn` です。
このイシューで私が実装を試みているのは、`input type=radio` を用いたものです。
ちなみに、当初は `v-radio` + `v-radio-group` を使おうとしていました。`v-radio` なら、ラベル値をタグ属性に書けてしまいますので。
あと、Vuetify を使い続ける、本プロジェクトのスタンダードとして定着させるなら、修行^H^Hプラクティスを積んだ方がいいとの狙いもありました

**Comment by MaySoMusician** [comment]
@mcdmaster 
> 「今」とおっしゃるのは、現状の本番ページのことを指しておいででしょうか？

@mcdmaster が今実装しようとしている方の「今」という意味でした

**Comment by mcdmaster** [comment]
やっと PR 上げました(汗 詳細はそちらをご覧ください。大まかに言うと、以下のポイントが挙げられます：
- 結局 `v-radio` の使用に踏み切りました。せっかくこれまで Vuetify の実績を積んできたのであれば、そこにあえて依存することでノウハウの散逸防止やリスクの移転をする狙いがあります
- `visually-hidden` はしっかりと使わせていただきました。たいへん助かりました。ありがとうございます！
- その `visually-hidden` を生の `<input>` 文と Vuetify コンポーネントに適用する場合とで、いくらかのお作法の違いが見受けられました（これの解決にけっこう時間が掛かりました）。最も顕著なのは、Vuetify 中では `visually-hidden` はクラスにしか適用できない、エレメントに適用しようとすると弾かれる、というところでした
- あと、Vuetify で用意されるデフォルト CSS テンプレがボタンとラジオでいくぶん異なるため、ある程度無理やりラジオ側に寄せています。ルック＆フィールの継続性を重視したためです
