### ISSUE TITLE
企業のみなさまへページのコンテンツ追加

### ISSUE THREAD

**Issue by yhstvhd** [tokyo-metropolitan-gov/covid19#3051]
## 改善詳細 / Details of Improvement
4/10公表予定の「都内休業要請」における該当事業者のコンテンツを追加

企業のみなさまへのページに休業要請に該当するかどうかを一覧で表示、
または質問に答えていくことで判断できるようにする。

休業要請に該当するかどうかの都への問い合わせの負担を軽減できるようにする。

## 期待する見せ方・挙動 / Expected behavior
（追加項目）
- 休業要請の対象業種
- **現時点での休業事業者一覧**
  - （登録制にした上で、マップで表示するのも良いかも）
## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer
（すべてのOSに対応）

どうぞよろしくお願いいたします。

**Comment by kaizumaki** [comment]
@yhstvhd ご提案ありがとうございます。「企業の皆様・はたらく皆様へ」ページについては、 #3641 #3687 でコンテンツの整理と更新を行っております。当サイトではリンク集にとどめ、リンク先でコンテンツを展開するという方向性になりました。こちらのPRについてはクローズさせていただければと思います。

**Comment by kaizumaki** [comment]
上記コメントにより、こちらのissueはクローズいたします。
