### ISSUE TITLE
時事情報を表示したい

### ISSUE THREAD

**Issue by moscwa** [tokyo-metropolitan-gov/covid19#3060]
## 改善詳細 
- 何らかの形で時事（学校が休業開始・緊急事態宣言発令　等）の情報が欲しい。
- これによって、あとから見た時に、例えば「〇〇政策の後急激に減り始めた」等のような分析がしやすくなる。

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected behavior
- グラフの中、もしくはx軸に表示（要議論）
- 表示/非表示の切り替えが可能

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@moscwa ご提案ありがとうございます。こちらのissueについて都に確認いたしました。時事情報をグラフに併記するのは、技術的にも運用的にも難しいと思われます。ですので、こちらの提案を採用するのは難しいです。ご理解いただきますようお願いいたします。

**Comment by kaizumaki** [comment]
都からの回答がありましたので、こちらのissueはクローズさせていただきます。
