### ISSUE TITLE
How to localize about 'canonical' URL?

### ISSUE THREAD

**Issue by air-h-128k-il** [tokyo-metropolitan-gov/covid19#3062]
I greatly appreciate having your source code in public.

I have a question about its localization.

In layouts/default.vue , we can read the following:

>   head(): MetaInfo {
>     const { htmlAttrs } = this.$nuxtI18nSeo()
>     return {
>       htmlAttrs,
>       link: [
>         {
>           rel: 'canonical',
>           href: `https://stopcovid19.metro.tokyo.lg.jp${this.$route.path}`
>         }
>       ]
>     }
>   } 

Should I modify 'stopcovid19.metro.tokyo.lg.jp' into _LocalizedSiteURL_ , for example 'hogehoge.org', in localizing your great site?

**Comment by mcdmaster** [comment]
Can you please let me give you my opinion in Japanese? わかりやすくするために、日本語で回答したいです。よろしいですよね？

まず、長野県のサイトはあくまで長野県のサイトなので、この東京都のサイトが "Canonical" （正式版、みたいな意味合いでしょうか）とはかならずしもならない、というのが私の考え方です。
違う言い方をすれば、もしも東京都のサイトが長野県のサイトに対し "Canonical" であるなら、東京都の側にも "Canonical" としての責任が発生します。
たとえば、長野県に留まらず他道府県のサイトの進捗度合いを、"Canonical" な東京都のチームメンバーが監視するなんてことが求められるわけです。それは、違いますよね？

むしろ、既に各所でも報道されているように、改変と再配布が自由なオープンソース・ライセンスを元に各道府県の開発者の皆さんが次々と、もしかしたら東京都よりも優れた COVID-19 対策サイトを作れる、という利点に目を向けていただければと願います

**Comment by air-h-128k-il** [comment]
Hi, @mcdmaster 

I can get it!
We will change the Tokyo site URL into our localized one.

Thank you.

**Comment by mcdmaster** [comment]
Hi @air-h-128k-il,

Great to hear that! Can you please close this issue? Thank you for cooperation anyway

**Comment by kikd** [comment]
@mcdmaster 
一応、長野県のものは本日修正しました。

**Comment by mcdmaster** [comment]
ご対応ありがとうございます！

**Comment by kikd** [comment]
お騒がせしてすみません。。。

**Comment by mcdmaster** [comment]
いえ、とんでもないです。

イシューのクローズをお願いしますね

**Comment by air-h-128k-il** [comment]
Thank you all
