### ISSUE TITLE
累積感染者数グラフの対数表示

### ISSUE THREAD

**Issue by yusuke596** [tokyo-metropolitan-gov/covid19#3063]
感染拡大のペースを可視化するために、累積感染者数のグラフを片対数で表示出来ると良いと思います。また、それに付随して直近7日間における感染者数の増加の倍加時間もあるとよいと思います。

**Comment by asterisk37n** [comment]
サイエンス出身の方々には片対数グラフは慣れておられるかと思いますが、本ページに訪れる多くの一般の方々は片対数グラフに慣れていないのではないでしょうか。そのような方々には、片対数グラフにすると、爆発的に増えていることが伝わりづらくなるのでしょうか。

同様のIssueがこちらにあります。
https://github.com/tokyo-metropolitan-gov/covid19/issues/2580

**Comment by kaizumaki** [comment]
@yusuke596 ご提案ありがとうございます。同様の #2580 とともに、こちらのissueについて都に確認いたしました。対数グラフは読み解くのが難しいという懸念があります。しかもデータが日ごと・曜日ごとにバラツキがあるので、対数グラフが誤解を生む可能性があります。ですので、こちらの提案を採用するのは難しいです。ご理解いただきますようお願いいたします。

**Comment by kaizumaki** [comment]
都からの回答がありましたので、こちらのissueはクローズさせていただきます。
