### ISSUE TITLE
FORKED_SITES.mdに鳥取県版を追加

### ISSUE THREAD

**Issue by kou029w** [tokyo-metropolitan-gov/covid19#3065]
## 改善詳細 / Details of Improvement
- URL: https://tottori-covid19.netlify.com/
  - 私を中心に[鳥取県に縁のある有志](https://github.com/tottori-covid19)が開設したものです
  - いまのところ鳥取県自治体関係者とは無関係です
- 差し支えなければFORKED_SITES.mdに追加したいと考えております

**Comment by rikupin1105** [comment]
やります
