### ISSUE TITLE
Release 自動作成でエラーが発生している

### ISSUE THREAD

**Issue by shnskfjwr** [tokyo-metropolitan-gov/covid19#3066]
## 起こっている問題 / The Problem
- GitHub Actionsのproduction deploy の [Create GitHub release](https://github.com/tokyo-metropolitan-gov/covid19/blob/5d8d77bc00439ca2865a4f605ea4905a25826a93/.github/workflows/deploy.yml#L63) でエラーが発生しています。
- リリースタグに `1.5.1` が設定されているため、重複エラーとなっているようです。
- `1.5.1` 以降のリリースは[すべて作成されていません](https://github.com/tokyo-metropolitan-gov/covid19/releases)。

## スクリーンショット / Screenshot

https://github.com/tokyo-metropolitan-gov/covid19/runs/574028742?check_suite_focus=true

![スクリーンショット 2020-04-10 14 14 26](https://user-images.githubusercontent.com/43740325/78964582-a6320300-7b35-11ea-8bd3-6e442d2721dd.png)

```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Release",
      "code": "already_exists",
      "field": "tag_name"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/releases/#create-a-release"
}
```

## 期待する見せ方・挙動 / Expected Behavior
- GitHub Actionsが動作するたびに新しいリリースが発行されること

### 備考
- 独自検証を行いました
- `rymndhng/release-on-push-action` は直近の `Latest release` を参照してバージョンが加算していく仕様のようです
- しかし、`rymndhng/release-on-push-action` が発行するリリースは `Pre-release` であるため、連続実行された場合はバージョンが更新されず、重複エラーになります
- [issues](https://github.com/rymndhng/release-on-push-action/issues/29)

## 起こっている問題の再現手段 / Steps to Reproduce
1. masterブランチにmergeする

## 動作環境・ブラウザ / Environment
- GitHub Actions

**Comment by MasaGon** [comment]
なるほど。Pre-releaseになっていることで問題となるのですね。

**Comment by shnskfjwr** [comment]
`rymndhng/release-on-push-action` リポジトリに報告した[issue](https://github.com/rymndhng/release-on-push-action/issues/29)が解決されました。
自動作成されるreleaseが `Latest release` になったことを、私の環境でも確認済みです。

後は管理者の方にリリースタグ `1.5.1` を `Pre-release`  から `Latest release` に変更いただければ、
自動的にリリースが行われる状態に復旧する……と思われます。

**Comment by MasaGon** [comment]
@shnskfjwr `1.5.1` Releaseから`Pre-release`フラグを外せば良いという理解で間違いないでしょか？

**Comment by shnskfjwr** [comment]
@MasaGon 
はい、そのとおりです
わかりにくく申し訳ない

**Comment by MasaGon** [comment]
@shnskfjwr ありがとうございます。Pre-releaseフラグを外しました。次回リリースをお待ちください。

**Comment by MasaGon** [comment]
@shnskfjwr 無事リリース生成が確認できました。ありがとうございます！
