### ISSUE TITLE
開発版サイトで開発中マークが表示されない

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3068]
## 起こっている問題 / The Problem
- 開発版サイトで開発中マークが表示されない
![image](https://user-images.githubusercontent.com/34566290/78966637-4fc7c300-7b3b-11ea-9519-17490e57e51b.png)

## スクリーンショット / Screenshot
- 修正前
    ![image](https://user-images.githubusercontent.com/34566290/78966578-3a529900-7b3b-11ea-8041-857138a44612.png)

## 期待する見せ方・挙動 / Expected Behavior
- 開発中マークを表示させる
   - ~下記のコードで `GENERATE_ENV` を `NODE_ENV` に変更する~
       - 異なるアプローチが必要と判明

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://dev-covid19-tokyo.netlify.com/ へアクセスする

## 動作環境・ブラウザ / Environment
- 検証環境: Windows 10 Home 1903 64 bit + Chrome 80.0.3987.163

**Comment by kaizumaki** [comment]
@MaySoMusician この件について、こちら #2758 の経緯があります。調査していただけますか？

**Comment by MaySoMusician** [comment]
確認しました。現状は以下のような感じです
- ステージング版は開発中マークが表示される。IE11でも表示できる
- 開発版は開発中マークが表示されない。IE11ではローディング表示が消えない
  - `yarn dev-no-axe` で実行すると、サーバー側では `process.env.GENERATE_ENV` が `development` に正常になっている。クライアント側で `process.env` を評価できない（空になる）のが原因か？

**Comment by munierujp** [comment]
`NODE_ENV`が`development`の場合、`.env.development`ファイルに定義されている値が`process.env`に追加されます。

```ts
const environment = process.env.NODE_ENV || 'development'
```

```ts
['@nuxtjs/dotenv', { filename: `.env.${environment}` }],
```

現在、`.env.development`ファイルには`GENERATE_ENV`が定義されていないので、`DevelopmentModeMark.vue`の算出プロパティ`isDevelopmentMode`は`false`になります。

```js
isDevelopmentMode: () => {
  if (process && process.env && process.env.GENERATE_ENV) {
    return process.env.GENERATE_ENV === 'development'
  }
  return false
}
```

解決策としては、以下が考えられます。

1. 各`.env.<env-name>`ファイルに`GENERATE_ENV`を定義する
2. `@nuxtjs/dotenv`モジュールのオプションで`systemvars`を`true`にする

>By default this is false and variables from your system will be ignored. Setting this to true will allow your system set variables to work.

https://github.com/nuxt-community/dotenv-module#systemvars

**Comment by ksk1015** [comment]
#2758 で直したときは、npm scriptsで設定した環境変数がクライアント側からアクセスできたと思うんですが、`['@nuxtjs/dotenv', { systemvars: true }]`の記述もなかったようだし、幻だったのか。。。

なんにせよ以下で

> * 各`.env.<env-name>`ファイルに`GENERATE_ENV`を定義する
> * `@nuxtjs/dotenv`モジュールのオプションで`systemvars`を`true`にする

意図通り動くので、この方向性で修正するのでいいと思うんですが、NODE_ENVを見て.envファイルを切り替えるのは #2758 のIE11で表示できない問題を引き起こす可能性あるので、.envファイルを切り替えるための新たな環境変数をnpm scriptsで指定するのはどうでしょう？
（ついでにcross-envは使ってないのっぽいので削除する）

`"dev": "SCRIPT_ENV=dev nuxt-ts",`
```
VUE_AXE=true
GENERATE_ENV=development
```

`"dev-no-axe": "SCRIPT_ENV=dev-no-axe nuxt-ts",`
```
VUE_AXE=false
GENERATE_ENV=development
```

`"build": "SCRIPT_ENV=build nuxt-ts build",`
```
GENERATE_ENV=development
```

`"generate:dev": "SCRIPT_ENV=generate-dev nuxt-ts generate",`
```
GENERATE_ENV=development
```

`"generate:deploy": "SCRIPT_ENV=generate-deploy nuxt-ts generate",`
```
GENERATE_ENV=production
```

**Comment by munierujp** [comment]
Nuxt側で使われている`process.env.NODE_ENV`を明示的に指定しているのがよくないのかもしれません。

- [Nuxt.jsでprocess.env.NODE_ENVを参照する際の挙動についてまとめてみた - Qiita](https://qiita.com/y-temp4/items/84bb16e2ccf8efaf82fc)

一つの案として、以下のようにするのはどうでしょうか。

- `package.json`の `scripts`で環境変数`ENV`を指定
  - `"dev": "cross-env ENV=development nuxt-ts"`
  - `"dev-no-axe": "cross-env ENV=dev-no-axe nuxt-ts"`
  - `"start": "cross-env ENV=production nuxt-ts start"`
  - `"generate:deploy": "cross-env ENV=production nuxt-ts generate"`
  - `"generate:dev": "cross-env ENV=development nuxt-ts generate"`
- 各`.env.<env-name>`で`SHOW_DEVELOPMENT_ALERT`のような環境変数を定義
  - `SHOW_DEVELOPMENT_ALERT=true`
  - `SHOW_DEVELOPMENT_ALERT=false`
- `process.env.NODE_ENV`を使っている部分を`process.env.ENV`に置き換え
- `DevelopmentModeMark.vue`の表示条件に` process.env.SHOW_DEVELOPMENT_ALERT`を使用
  - 現在はコンポーネント自体の算出プロパティで表示条件を定義しているが、本来はコンポーネントを使用する側 で定義すべきなので、ついでになおしたほうがいいかもしれない
    - `<development-mode-mark v-if="showDevelopmentAlert" />`

**Comment by soutaito** [comment]
- プロダクト版ではない時に開発中マークを出す
- プロダクト版ではない時にもIE11で動作させる
という2点を満たすにあたり、なるべくシンプルな調整でできそうなのがこちらの差分でした。

```diff
diff --git a/.env.dev-no-axe b/.env.dev-no-axe
index 60f853aa2..ff854832d 100644
--- a/.env.dev-no-axe
+++ b/.env.dev-no-axe
@@ -1 +1,2 @@
 VUE_AXE=false
+GENERATE_ENV=development
diff --git a/.env.development b/.env.development
index 904666d9e..e465852b0 100644
--- a/.env.development
+++ b/.env.development
@@ -1 +1,2 @@
 VUE_AXE=true
+GENERATE_ENV=development
diff --git a/.env.production b/.env.production
index 8b1378917..3aaa9f03a 100644
--- a/.env.production
+++ b/.env.production
@@ -1 +1 @@
-
+GENERATE_ENV=production
diff --git a/nuxt.config.ts b/nuxt.config.ts
index f680d1793..c9278c99f 100644
--- a/nuxt.config.ts
+++ b/nuxt.config.ts
@@ -51,6 +51,12 @@ const config: Configuration = {
         content: 'summary_large_image'
       }
     ],
+    script: [
+      {
+        src:
+          'https://polyfill.io/v3/polyfill.min.js?features=NodeList.prototype.forEach%2CMath.cbrt%2Ces2015'
+      }
+    ],
     link: [
       { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
       { rel: 'apple-touch-icon', href: '/apple-touch-icon-precomposed.png' }
diff --git a/package.json b/package.json
index c8fbf67b1..bb87daf73 100644
--- a/package.json
+++ b/package.json
@@ -8,12 +8,12 @@
     "node": ">=10.19.0"
   },
   "scripts": {
-    "dev": "cross-env NODE_ENV=development GENERATE_ENV=development nuxt-ts",
-    "dev-no-axe": "cross-env NODE_ENV=dev-no-axe GENERATE_ENV=development nuxt-ts",
+    "dev": "cross-env NODE_ENV=development nuxt-ts",
+    "dev-no-axe": "cross-env NODE_ENV=dev-no-axe nuxt-ts",
     "build": "nuxt-ts build",
     "start": "cross-env NODE_ENV=production nuxt-ts start",
-    "generate:deploy": "cross-env GENERATE_ENV=production nuxt-ts generate",
-    "generate:dev": "cross-env GENERATE_ENV=development nuxt-ts generate",
+    "generate:deploy": "cross-env NODE_ENV=production nuxt-ts generate",
+    "generate:dev": "cross-env NODE_ENV=development nuxt-ts generate",
     "generate": "eslint './**/*.{js,ts,vue}' && nuxt-ts generate",
     "lint-and-generate": "eslint './**/*.{js,ts,vue}' && nuxt-ts generate",
     "test": "echo 'skip tests (there is no test)'",
```

> 各.env.<env-name>ファイルにGENERATE_ENVを定義する

の方針で`GENERATE_ENV`をenvファイルに移設する形です。
vuetifyはproduction用のbuildをしないとIE11で動かない経験があり、`yarn dev-no-axe` や `yarn generate:dev` でもIE11で動かすためにpolyfill.ioから必要なpolyfillを持ってきました。
IE11で動作することを確認しています。

polyfill.ioはブラウザを検出して必要なpolyfillを返すそうなので、モダンブラウザなら負荷にはならないはずです。

また、将来的には`GENERATE_ENV`自体廃止して`NODE_EN`V一本で良いのでは、、と見えます。
`cross-env`はwindows環境で環境変数つきnpm scriptsを動かすのに必要だったので、残しました。

**Comment by kaizumaki** [comment]
こちらのissueは現在解決していると思われるので、いったんクローズしますね。もし、今後同様の問題が発生した場合は再オープンいたします。
