### ISSUE TITLE
やさしいにほんごの「あたらしいコロナウイルス」の意味がわかりづらい

### ISSUE THREAD

**Issue by asterisk37n** [tokyo-metropolitan-gov/covid19#3071]
## 改善詳細 / Details of Improvement
- やさしいにほんご訳の「あたらしいコロナウイルス(略)」は、コロナウイルスの新種のように読めます。「きのうコロナウイルスかどうか調べた人」のように書くとわかりやすい。 (ちなみに、日本語ページの見出しも同様にして、累計か一日あたりなのかぱっと見わかりづらい気がするのは気のせいでしょうか。)

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/16299750/78972039-ce2a6200-7b47-11ea-843c-90b7dd6376fb.png)

## 期待する見せ方・挙動 / Expected behavior
- 「あたらしいコロナウイルスかどうか しらべた かず」を「きのうコロナウイルスかどうか しらべた かず」とする

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by MaySoMusician** [comment]
「あたらしいコロナウイルス」は「新型コロナウィルス」のやさしい日本語訳ですので

> やさしいにほんご訳の「あたらしいコロナウイルス(略)」は、コロナウイルスの新種のように読めます。

その読み方で問題ないとも思います。少し長いかもしれませんが、新型ではないコロナウィルスも存在するので、それと区別するための措置だと解釈できます。

**Comment by asterisk37n** [comment]
ありがとうございます。たしかに新型コロナウイルスと呼ばれてますね。本Issueは、「あたらしく昨日おこなわれた件数、感染者数」の意味で「あたらしい」を使ってるつもりが、「新型コロナウイルスの新種」と誤解されるんじゃないかと思った次第でありました。

**Comment by shuuji3** [comment]
こんにちは。気になって調べてみたのですが、たとえば、利用者の多そうな[NHKのやさしい日本語のニュース](https://www3.nhk.or.jp/news/easy/k10012293221000/k10012293221000.html)では、「新(あたら)しいコロナウィルス」や「新(あたら)しいウィルス」という表現が使われていました。なので、「あたらしいコロナウイルス」という表現は馴染みがあるものなのではないかと思います。

一般には「新型コロナウィルス」という表現をするので、ひょっとしたら「新」を漢字にした方が見慣れていて読みやすいという可能性はあるかもしれません。(私自身はやさしい日本語に詳しくないのでどちらがいいのかは判断が付きかねますが。)

**Comment by kaizumaki** [comment]
やさしい日本語については東京都側の管理下になりましたので、こちらのissueはクローズといたします。
