### ISSUE TITLE
Youtubeへのリンクを追加

### ISSUE THREAD

**Issue by ononao0** [tokyo-metropolitan-gov/covid19#3077]
## 改善詳細 / Details of Improvement
sidebarのsocial一覧にyoutubeリンクの追加
https://www.youtube.com/user/tokyo/videos

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by satoss** [comment]
着手します
