### ISSUE TITLE
表の追加：検査陽性者の状況

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#309]
累計数をそのまま表で出したいという局からのご要望。
階層構造がわかるように見せる必要があると思われます。
<img width="691" alt="スクリーンショット 2020-03-04 11 49 54" src="https://user-images.githubusercontent.com/4206675/75840890-b278c100-5e0f-11ea-8a94-6c00422ae415.png">

**Comment by ocean3fish** [comment]
まず以下進めています。
・元データの場所の確認
・用語の確認
・データ構造の整理

**Comment by ocean3fish** [comment]
参照するデータ：
2ファイルに分かれている。
1. 検査実施サマリ.xlsx
https://codeforjapan.sharepoint.com/:x:/s/covid19/Ec4iCUaXKeRPocRomUPYk_cBYdUziwQOEg20OyyDN5yLvQ?e=O8QulL
2. 東京都患者発生数-RAW.xlsx 
https://codeforjapan.sharepoint.com/:x:/s/covid19/ERnuge04NZRPvimfOL0j_bYBPN6O0KWaA5PasvV2BGvkeg?e=mF2P1U

データ構造の整理：
https://docs.google.com/presentation/d/1zwOsU8G0p8synjqzXXz4tacNRp95lu6HV56qOBBTaLs/edit?usp=sharing
<img width="739" alt="スクリーンショット 2020-03-04 13 11 47" src="https://user-images.githubusercontent.com/4206675/75844560-bd385380-5e19-11ea-892e-e628b05d311f.png">

**Comment by ocean3fish** [comment]
こんなイメージでしょうか。
表のヘッダを入れ子表示にする方法があるのか、ご存知の方がいたら教えてください。
<img width="787" alt="スクリーンショット 2020-03-04 13 44 34" src="https://user-images.githubusercontent.com/4206675/75846048-549fa580-5e1e-11ea-8e63-873978f55780.png">

**Comment by ocean3fish** [comment]
可能でしたら、デザイン @saladdays さんにお願いしたいです！
データに関してご不明な点があればお知らせください。
よろしくお願いします！

**Comment by madana-1** [comment]
@ocean3fish 
https://www.w3schools.com/code/tryit.asp?filename=GCI37XP23VOE
かなり無理矢理ですができないこともないですね。
もっといい方法もあるのかもしれませんが...

**Comment by saladdays** [comment]
デザインやりまーす！

**Comment by osoken** [comment]
コンポーネントのコーディング、着手します。

**Comment by saladdays** [comment]
このグラフ、どこを足したら陽性者数になるんでしょう、、🤔
ちょっと確認とりますねー

**Comment by ttakenaka** [comment]
入院中が邪魔ですね

**Comment by saladdays** [comment]
昨夜Slackで共有はしておりましたが、グラフのデザインデータこちらです
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=121%3A709

**Comment by NaoyaShimizzz** [comment]
上記デザイン案の修正のお願いです。基本的には元の表のとおりでお願いします。

- 検査実施人数は単独の箱（どこにもかからない
- 色も全部同じ濃度でお願いします（これだと重症に注目されてしまう

**Comment by halsk** [comment]
本日は #436 にて対応。V3のマイルストーンは削除します。

**Comment by amotarao** [comment]
#493 にて数値をデータから引っ張ってくるようにしました
