### ISSUE TITLE
READMEにタイポ

### ISSUE THREAD

**Issue by TeepaBlue** [tokyo-metropolitan-gov/covid19#3092]
## 起こっている問題 / The Problem
docs/en/README.mdの89行目、 environmentが "enviroinment"と間違って入力されている
- xxxx(できるだけ簡潔に/as concise as possible)

## 期待する見せ方・挙動 / Expected Behavior
enviroinment を environmentに修正
- xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by rikupin1105** [comment]
やります
