### ISSUE TITLE
/bin/sh が bashでないユーザーはpre-commit.shでエラーが出る

### ISSUE THREAD

**Issue by koukimetal** [tokyo-metropolitan-gov/covid19#3106]
## 起こっている問題 / The Problem
- 一部開発者はpre-commitでエラーが出る

## スクリーンショット / Screenshot
`git commit`をすると以下のようなエラーが起きる
```
pre-commit.sh: 4: pre-commit.sh: Syntax error: "(" unexpected
```

## 期待する見せ方・挙動 / Expected Behavior
commitできるべき。

## 起こっている問題の再現手段 / Steps to Reproduce
1. `git commit`

## 動作環境・ブラウザ / Environment
少なくとも私のUbuntu 18

**Comment by kou029w** [comment]
私も同じ問題あって https://github.com/tottori-covid19/covid19/commit/6e1ebe978c154519b9175544e1a7ea36bfc18934 こんな感じで修正しています
macOSもWindowsもおそらくbashあるので問題ないかと考えますが、Ubuntu以外の環境で実際に試したわけではないです

**Comment by koukimetal** [comment]
ほとんど同じ変更ですね。どっちにするかはReviewerにおまかせしたいと思います。

**Comment by MasaGon** [comment]
@koukimetal さんに頂いたプルリクで `env` の方で行きましょうか。
@kou029w さんもありがとうございます！
