### ISSUE TITLE
グラフ下部のラベルをデザインに合わせる

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#311]
chart.jsで再現できるか分からないんですが
それっぽい情報をメモ程度においておきます

https://stackoverflow.com/questions/47179085/displaying-labels-for-grouped-datasets-in-chartjs-clustered-column-graph
https://stackoverflow.com/questions/55108513/grouped-bar-chart-with-label-in-chart-js
https://stackoverflow.com/questions/29925431/chartjs-draw-chart-with-label-by-month-data-by-day

**Comment by koji-koji** [comment]
こんなイメージでしょうか。方向性間違ってなければプルリク出せます。

なお、日付の表示数が多くて数字がくっつくので、表示数を20 => 15にしてます。
15でも画面幅500pxぐらいだとかなりくっついて見えますね。

![スクリーンショット 2020-03-05 3 39 25](https://user-images.githubusercontent.com/28003697/75911912-aafafb80-5e93-11ea-8fed-d567fc968387.jpg)

**Comment by mikkame** [comment]
Issue適当すぎましたすみません。
おお！すごいです。
はい、意図としてはそのような感じで月と日を表したかった感じです。
カンプデータ引っ張ってきますので少々お待ちください・・・

**Comment by mikkame** [comment]
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3
こちら、figmaになりますがちょっとlimitにかかっているようなので

取り急ぎ #104 の添付をご確認いただけますでしょうか

**Comment by koji-koji** [comment]
承知しました。忙しい中即レスありがとうございます！

font-sizeを10px => 8pxにしているのですね。
月のラベルの位置調整と線をグラフから出すみたいですね。
ちょっとchart.jsの項目調べてみてやってみます！
