### ISSUE TITLE
tableの日付をth要素にする

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#3110]
## 改善詳細 / Details of Improvement
現在表示されている「陽性患者の属性」や、グラフの代替コンテンツとして入っている隠しtable（https://github.com/tokyo-metropolitan-gov/covid19/pull/2447 で見た目にも表示される予定）の日付がtdでマークアップされている。このため、スクリーンリーダーでデータセルを読み上げる際に、何日のことを読み上げているのかがすぐには判断しにくい。

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-11 1 59 08](https://user-images.githubusercontent.com/17713513/79008445-63554700-7b98-11ea-9a66-364c02d7f3c3.png)

## 期待する見せ方・挙動 / Expected behavior
table内の日付にあたるセルをtd要素からth要素に変更する

## 動作環境・ブラウザ / Environment
すべて

**Comment by kzhrk** [comment]
こちら着手します。

https://vuetifyjs.com/en/components/data-tables/#slots
v-slot:bodyで`tbody`タグに書き出される`td`タグを`th`タグに置き換えます。

**Comment by magi1125** [comment]
@kzhrk ありがとうございます！よろしくお願いします。
