### ISSUE TITLE
SideNavigationにfooterが含まれている

### ISSUE THREAD

**Issue by kzhrk** [tokyo-metropolitan-gov/covid19#3112]
## 改善詳細 / Details of Improvement
- SideNavigationに含まれているfooterを`div.naviContainer`と`div.mainContainer`と同じ階層に移動
  - footerタグは一般的にページコンテンツの末尾に設置されているため、音声ブラウザでブラウジングするユーザにページコンテンツの末尾であることを予見させる効果がある

## スクリーンショット / Screenshot
<img width="1198" alt="スクリーンショット 2020-04-11 2 00 07" src="https://user-images.githubusercontent.com/548508/79008777-132ab480-7b99-11ea-9e6d-84caeae35d75.png">

## 期待する見せ方・挙動 / Expected behavior
タグ構造の参考のキャプチャを添付します。スタイリングは開発ツールで一時的に作成しました。
デザインの変更になるのでデザイナさんの確認も挟む必要があると思います。

<img width="1440" alt="スクリーンショット 2020-04-11 2 10 01" src="https://user-images.githubusercontent.com/548508/79009170-e2974a80-7b99-11ea-930d-664ddd43924a.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ocean3fish** [comment]
@kzhrk ご提案ありがとうございます。
footerに関しては、 https://github.com/tokyo-metropolitan-gov/covid19/issues/1159 で議論されていた通り、すでにアクセシビリティを考慮した実装になっているという認識でおります。
こちらご確認頂いて、もし問題が無さそうでしたらissueのクローズをご検討頂けるでしょうか。

**Comment by kzhrk** [comment]
@ocean3fish 
ご指摘ありがとうございます。 #1159 の議論を確認しました。
すでにアクセシビリティが考慮されているとのこと、理解しました。
こちらのissueはクローズします。
