### ISSUE TITLE
累計のtableの設置

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#3114]
## 改善詳細 / Details of Improvement
https://github.com/tokyo-metropolitan-gov/covid19/pull/2447 にて、グラフの元データとしてのtableの表示が実装されるが、現在（隠しtableとして埋め込まれていたもの）は日別のtableのみであり、累計のtableは設置されていない。

## 期待する見せ方・挙動 / Expected behavior
日別と累計の切り替えボタンは、パネルの冒頭の人数・件数と、グラフの両方を切り替えている。そのためこのパネル自体の表示モードを切り替えていると解釈されるため、それに準じてtableも日別と累計に切り替わるのが適切だと考えられる。

## 動作環境・ブラウザ / Environment
すべて

**Comment by kaizumaki** [comment]
こちら #2447 で実装しており、リリース待ちです。

**Comment by magi1125** [comment]
@kaizumaki ありがとうございます。すいません見落としでした。列を並べるということでしたね。closeします。
