### ISSUE TITLE
[ruby] 当サイトについて のルビタグ対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3118]
**プルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**

[「当サイトについて」](https://ja-hira-covid19-tokyo.netlify.com/ja-basic/about) ページを「やさしい日本語」で表示した際のルビタグ対応をお願いします。

進め方・実装方法については、#3116 にまとめています。
こちらを確認の上、実装をお願いいたします。

疑問点があればこの issue 内でコメントください！

**Comment by shgtkshruch** [comment]
@shunito 
こちら実装をお願いしてもよろしいでしょうか？

**Comment by shunito** [comment]
はい、対応します！

**Comment by shgtkshruch** [comment]
ありがとうございます！

**Comment by shgtkshruch** [comment]
> **ルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**
> 
> [「当サイトについて」](https://ja-hira-covid19-tokyo.netlify.com/ja-basic/about) ページを「やさしい日本語」で表示した際のルビタグ対応をお願いします。
> 
> 進め方・実装方法については、#3116 にまとめています。
> こちらを確認の上、実装をお願いいたします。
> 
> 疑問点があればこの issue 内でコメントください！
