### ISSUE TITLE
「当サイトについて」の英語訳

### ISSUE THREAD

**Issue by hiro-ishi** [tokyo-metropolitan-gov/covid19#312]
「当サイトについて」のうちウェブサイトの一般的な文言である以下のパートの英訳を、英語サイト作成経験のある方にお願いしたい。
・ブラウザ環境について
・当サイトへのリンクについて
・クッキーについて
・Google Analytics
・免責事項
https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0

**Comment by MaySoMusician** [comment]
既に記入されている英訳を修正する場合、コメントの挿入などは必要でしょうか？
Are we required to add some comments when we edit the translation already in the sheet?

**Comment by hiro-ishi** [comment]
修正する際は意図を含めてコメントを残しましょう！その方がコミュニケーションのすれ違いが少なくなるとおもいます。提案ありがとうございます。

**Comment by crispytaffy** [comment]
「当サイトについて」内で2箇所、「データについて」「ソースコードについて」がGoogle Docs未反映ですが、本日（3/6）のソースコード公開などのアップデートに伴う新規追加かと思います。こちら反映して翻訳できればと思いますが、行追加になるので念のためご確認ください。

**Comment by crispytaffy** [comment]
前述コメントの件、関さんとも相談して、行追加いたします。それに伴い、翻訳箇所が増えますので適宜ご対応いただけると嬉しいです。
I talked with Hal. Some items had added related to yesterday's update, so I'll add some rows in Google Docs. Please translate in each language. Thank you!

**Comment by crispytaffy** [comment]
3/8時点でi18n対応に伴い翻訳箇所が増えていますので、サポートいただきたい言語については別イシューもご確認ください。
