### ISSUE TITLE
[ruby] お問い合わせ先一覧 のルビタグ対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3120]
**プルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**
[「お問い合わせ先一覧」](https://ja-hira-covid19-tokyo.netlify.com/ja-basic/about) ページを「やさしい日本語」で表示した際のルビタグ対応をお願いします。

進め方・実装方法については、#3116 にまとめています。
こちらを確認の上、実装をお願いいたします。

本 issue については既知の問題（後述）がありますので、実装の前にそちらの解決策をご提案頂く形ですすめていきたいと思います。

疑問点があればこの issue 内でコメントください！

## 既知の問題
テーブル内の文字列にルビタグをつけると、分量によっては高さが揃わないセルがあります。
マークアップや CSS の修正など、解決策があればご提案いただけると助かります！

![スクリーンショット 2020-04-11 11 05 27](https://user-images.githubusercontent.com/5207601/79032827-61b17080-7be4-11ea-9a86-97b5530607cd.png)

現状のルビタグ対応時のマークアップ

```html
<tr>
  <td class="content">
    <span>
      <ruby>
        全体
        <rp>（</rp>
        <rt>ぜんたい</rt>
        <rp>）</rp>
      </ruby>
      を
      <ruby> 
        通
        <rp>（</rp>
        <rt>とお</rt>
        <rp>）</rp>
      </ruby>
      して 、
      <ruby>
        疑問
        <rp>（</rp>
        <rt>ぎもん</rt>
        <rp>）</rp>
      </ruby>
      に
      <ruby> 
        思
        <rp>（</rp>
        <rt>おも</rt>
        <rp>）</rp>
      </ruby>
      ったこと
    </span>
  </td>
  <td class="bureau">
    <span>
      <ruby>
        政策企画局
        <rp>（</rp>
        <rt>せいさく きかく きょく</rt>
        <rp>）</rp>
      </ruby>
    </span>
  </td>
  <td class="tel">
    <a href="tel:03-5388-2171">03-5388-2171</a>
  </td>
</tr>
```

**Comment by shunito** [comment]
こちら対応してみます

**Comment by shgtkshruch** [comment]
ありがとうございます！
