### ISSUE TITLE
[ruby] お子様をお持ちの皆様へ のルビタグ対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3123]
**プルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**

[「お子様をお持ちの皆様へ」](https://ja-hira-covid19-tokyo.netlify.com/ja-basic/parent/) ページを「やさしい日本語」で表示した際のルビタグ対応をお願いします。

進め方・実装方法については、#3116 にまとめています。
こちらを確認の上、実装をお願いいたします。

疑問点があればこの issue 内でコメントください！

**Comment by kebhr** [comment]
対応します。

**Comment by shgtkshruch** [comment]
よろしくお願いいたします！
