### ISSUE TITLE
[ruby] 企業の皆様・はたらく皆様へ のルビタグ対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3124]
**プルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**

[「企業の皆様・はたらく皆様へ」](https://ja-hira-covid19-tokyo.netlify.com/ja-basic/worker/) ページを「やさしい日本語」で表示した際のルビタグ対応をお願いします。

進め方・実装方法については、#3116 にまとめています。
こちらを確認の上、実装をお願いいたします。

疑問点があればこの issue 内でコメントください！

**Comment by kebhr** [comment]
対応します！

**Comment by shgtkshruch** [comment]
ありがとうございます。
よろしくお願いいたします！
