### ISSUE TITLE
[ruby] 新型コロナウイルス感染症が心配なときに のルビタグ対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3125]
**プルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**

[「新型コロナウイルス感染症が心配なときに」](https://ja-hira-covid19-tokyo.netlify.com/ja-basic/worker/) ページを 「やさしい日本語」で表示した際のルビタグ対応をお願いします。

PC, SP のコンポーネントについてはそれぞれ別に issue を立てますので、本 issue では `pages/flow.vue` コンポーネントの修正をお願いします。

進め方・実装方法については、#3116 にまとめています。
こちらを確認の上、実装をお願いいたします。

疑問点があればこの issue 内でコメントください！

**Comment by kebhr** [comment]
やります！

**Comment by shgtkshruch** [comment]
ありがとうございます！
