### ISSUE TITLE
[ruby] 新型コロナウイルス感染症が心配なときに（PC） のルビタグ対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3127]
**プルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**

[「新型コロナウイルス感染症が心配なときに」](https://ja-hira-covid19-tokyo.netlify.com/ja-basic/worker/) ページを **PC** で「やさしい日本語」表示した際のルビタグ対応をお願いします。

対象は `components/flow/` ディレクトリにある以下のコンポーネントになります。
- FlowPcAdvisory.vue
- FlowPcAdvisory2.vue
- FlowPcDays.vue
- FlowPcHospitalized.vue
- FlowPcNotRequired.vue
- FlowPcPast.vue
- FlowPcPcr.vue
- FlowPcRequired.vue
- FlowPcSuspect.vue

進め方・実装方法については、#3116 にまとめています。
こちらを確認の上、実装をお願いいたします。

疑問点があればこの issue 内でコメントください！

**Comment by ryuckel** [comment]
こちら対応させていただいてもよろしいでしょうか？

**Comment by shgtkshruch** [comment]
ありがとうございます、よろしくお願いいたします！

分量が多いので、途中でも PR いただければ私の方で引き継ぎますので、お気軽におっしゃってください。

**Comment by ryuckel** [comment]
@shgtkshruch 
1点確認させてください。
scriptタグが入っていないコンポーネントについては以下のscriptタグを入れる認識で宜しかったでしょうか

`<script lang="ts">
import TI18n from '@/components/TI18n.vue'
export default {
  components: {
    TI18n
  }
}
</script>`

**Comment by shgtkshruch** [comment]
@ryuckel  

> scriptタグが入っていないコンポーネントについては以下のscriptタグを入れる認識で宜しかったでしょうか

はい、このように対応いただけると嬉しいです！

**Comment by ryuckel** [comment]
@shgtkshruch
ありがとうございます！
一通り置き換えましたのでPR出しました！
