### ISSUE TITLE
[ruby] 新型コロナウイルス感染症が心配なときに（SP） のルビタグ対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3128]
**プルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**

[「新型コロナウイルス感染症が心配なときに」](https://ja-hira-covid19-tokyo.netlify.com/ja-basic/worker/) ページを **SP（スマホ）** で「やさしい日本語」表示した際のルビタグ対応をお願いします。

対象は `components/flow/` ディレクトリにある以下のコンポーネントになります。
- FlowSp.vue
- FlowSpAccording.vue
- FlowSpAdvisory.vue
- FlowSpElder.vue
- FlowSpGeneral.vue
- FlowSpHospitalized.vue
- FlowSpPast.vue
- FlowSpSuspect.vue

進め方・実装方法については、#3116 にまとめています。
こちらを確認の上、実装をお願いいたします。

疑問点があればこの issue 内でコメントください！

**Comment by kebhr** [comment]
対応します。

**Comment by shgtkshruch** [comment]
ありがとうございます。

分量が多いですが、よろしくお願いいたします！
（途中でも PR いただけば僕の方で引き継がせていただきます mm）
