### ISSUE TITLE
[ruby] TI18n コンポーネントの正規表現改善

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3133]
## 改善詳細 / Details of Improvement
- 漢字とルビタグがずれる箇所があるので改善します
- 今わかっているパターンとしては、漢字の前に中点や空白がある場合が該当します
- 以下の正規表現を改修すれば良さそうに思います
https://github.com/tokyo-metropolitan-gov/covid19/blob/d7f4f34790f3574ba157b103f415d36970b9cc4e/components/TI18n.vue#L37
- 全ページのふりがな対応をしてパターンを洗い出してから対応しようと思います

## スクリーンショット / Screenshot

| ページ名 | screenshot | PR |
| --- | --- | --- |
| 企業の皆様・はたらく皆様へ | ![](https://user-images.githubusercontent.com/5207601/79034800-d9d36280-7bf3-11ea-82a7-da556a01d5d9.png) | https://github.com/tokyo-metropolitan-gov/covid19/pull/3121#issuecomment-612317958
| 当サイトについて | ![](https://user-images.githubusercontent.com/5207601/79034953-a2b18100-7bf4-11ea-9512-ce7084d85e02.png) | https://github.com/tokyo-metropolitan-gov/covid19/pull/3126#issuecomment-612319132
| お子様をお持ちの皆様へ |  ![](https://user-images.githubusercontent.com/5207601/79035407-3d13c380-7bf9-11ea-86a4-0ada34a7f69f.png) ![](https://user-images.githubusercontent.com/5207601/79035406-3be29680-7bf9-11ea-84b5-26af79972587.png) | https://github.com/tokyo-metropolitan-gov/covid19/pull/3130#issuecomment-612325891

## 期待する見せ方・挙動 / Expected behavior
- 中点・空白があった場合でも漢字とふりがなが一致していること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
正規表現と関連するかは微妙なのですが、ルビを付けた漢字の前後にあった半角スペースが消えてしまっています。これは #3133 に含められるか、それとも別にissue立てたほうが良いでしょうか？

**Comment by shgtkshruch** [comment]
> ルビを付けた漢字の前後にあった半角スペースが消えてしまっています。

こちらも正規表現に関連しているので、一旦この issue でまとめておきたいと思います。

正規表現で対応が難しい場合は、例えば `<ruby>` タグに padding をつけるなどの対応も考えられるかと思いました。

**Comment by shgtkshruch** [comment]
正規表現を以下のように編集すると中点・空白、漢字の前後の半角スペースに対応できそうです。

```ts
const regp = /([\p{sc=Han}][\p{sc=Han}|・]*?)（([\p{sc=Hiragana}][\p{sc=Hiragana}|・|\s]*?)）/gu
```
ref: https://github.com/shgtkshruch/covid19/blob/b94faea546fb6dd6d86a8f0e214b04f6e562dd4f/components/TI18n.vue#L37

![スクリーンショット 2020-04-11 23 54 06](https://user-images.githubusercontent.com/5207601/79047218-41b79680-7c50-11ea-9a31-ec2279397d7b.png)
![スクリーンショット 2020-04-11 23 55 29](https://user-images.githubusercontent.com/5207601/79047219-42e8c380-7c50-11ea-9dba-4226f7578f0e.png)
![スクリーンショット 2020-04-11 23 55 37](https://user-images.githubusercontent.com/5207601/79047220-43815a00-7c50-11ea-8f54-7804eb026861.png)
![スクリーンショット 2020-04-11 23 57 04](https://user-images.githubusercontent.com/5207601/79047221-4419f080-7c50-11ea-9544-5cd955547f91.png)



主要ページのルビタグ対応が終わって動作確認ができてから PR を作成します。

**Comment by MaySoMusician** [comment]
Close per #3609 merged
