### ISSUE TITLE
[ruby] 印刷ボタンのテキストがWindows/Chrome環境で下にズレる

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#3140]
**`dev-ja-hira-ruby` ブランチが対象のIssueです。
Pull-Requestは `dev-ja-hira-ruby` に向けて作成してください。**

## 起こっている問題 / The Problem
- #3129 にて対応した /flow のルビタグ対応にて、「やさしい日本語」で表示時に印刷ボタンのテキストが Windows / Chrome で閲覧した時のみ下にズレる

## スクリーンショット / Screenshot

@MaySoMusician さんより https://github.com/tokyo-metropolitan-gov/covid19/pull/3129#issuecomment-612347786
![image](https://user-images.githubusercontent.com/42484226/79038760-dbfae880-7c16-11ea-8768-feb0d486f032.png)

## 期待する見せ方・挙動 / Expected Behavior
- macOS環境と同様に表示される

上=Firefox, 下=Chrome
<img src="https://user-images.githubusercontent.com/42484226/79038766-e2896000-7c16-11ea-9ac6-98b8886a58c9.png" width="200">

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://deploy-preview-3129--ja-hira-covid19-tokyo.netlify.com/ja-basic/flow を Windows / Chrome で開く

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by kebhr** [comment]
着手しています。

**Comment by kebhr** [comment]
CSS力の足りなさ故解決できないためAssignを外れます...。
labelを付けられる方、`help-wanted`など付けていただけると助かります。

**Comment by mcdmaster** [comment]
上記、 #3464 で引き取りました。
こちらの手持ちの環境のバリエーションが少なく、確認が不十分になるのは避け得ないため、レビューをいただいた上でもう少しイジる余地があると覚悟して（？）います

**Comment by mcdmaster** [comment]
@kebhr 本件、 #3464 をご確認いただき、オーケーでしたらイシュークローズをお願いできますでしょうか？

**Comment by kebhr** [comment]
@mcdmaster お引き取りいただきありがとうございました！
