### ISSUE TITLE
各カードのオープンデータへのリンク

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#315]
グラフ・リスト化したデータについては、それぞれオープンデータにしていく予定です。

実データcsvもしくは、オープンデータカタログサイトへのリンクを各カードにつけていただきたいです。

場所は左下のスペースが開いているのでそのあたりがいいかなと思ってます。
リンクテキストは、オープンデータへのリンク　として、デザインお願いします。

**Comment by Jxck** [comment]
@NaoyaShimizzz 軽く実装をしてみたのですがこんな感じで要件は満たしていたでしょうか？
WIP にしている理由は PR にも書いてますが、肝心の URL がわからなかったのでダミーを埋めています。
適宜コメントをいただければ修正致します。

**Comment by NaoyaShimizzz** [comment]
ありがとうございます！イメージ通りです！URLはまだ未確定です。

**Comment by Jxck** [comment]
了解です。では以下の二択という感じでしょうか？(都合の良い方を選んで頂ければ対応します)

1. URL が確定するまでこのまま置いておく
2. URL を空文字列にしておき、その場合リンクを非表示にする分岐を入れてマージ。のちに URL が決まったら埋めればリンクが表示されるようにする。

**Comment by NaoyaShimizzz** [comment]
URLが確定するまではこのままにしていただきたいです。

ちゃんと理解してなくて申し訳ないですが、カードごとに設定可能ということでよいですか？

**Comment by Jxck** [comment]
> カードごとに設定可能ということでよいですか？

下記ファイルで、 `:url` の部分(ダミーとして https://example.com を埋めている)を、それぞれのカードの URL に変えてもらえれば良いです。

https://github.com/tokyo-metropolitan-gov/covid19/pull/360/files#diff-b19fa22add3de9cd0b98b05366479d92


もしかしたらこちらが勘違いしていたかも知れませんが、 URL はカードごとではなかったですかね？
あと、データの取得元として外部に URL  が設置されるのかと思い、外部へのリンクのアイコンをつけたのですが、データをサイト内部の別の場所において、そこにリンクを貼りたいという要求だったでしょうか？(その場合外部向けアイコンはいらなかったですね)

**Comment by halsk** [comment]
ありがとうございます！データソースは将来的に外になる可能性がありますが、直近では本サイト内に置くことになりました。
`/static/data/**.csv` という形でそれぞれのデータを置くことにします。

**Comment by NaoyaShimizzz** [comment]
ちょっとややこしいですが

・本サイト内に置いたデータソースに対して、カタログサイトからリンクを張る
・本サイトの各カードには、カタログサイトへのリンクを張る

ということにします。
なので外部向けアイコンはお願いいたします。

「陽性患者数」と「陽性患者の属性」のカードに下記URLの設定をおねがいいたします。
https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068
#現時点では404

**Comment by halsk** [comment]
あ、そうなんですね。失礼しました！
@Jxck さん、これがFixです。

> 「陽性患者数」と「陽性患者の属性」のカードに下記URLの設定をおねがいいたします。
> https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068

対応可能でしょうか？

**Comment by NaoyaShimizzz** [comment]
こちらも明日の更新に合わせたく、よろしくお願いします

**Comment by Jxck** [comment]
１時間後くらいには push できます

**Comment by Jxck** [comment]
- 新型コロナコールセンター相談件数
- 帰国者・接触者電話相談センター相談件数

この二件はどうしましょう？

**Comment by NaoyaShimizzz** [comment]
リンクなし でお願いします！

**Comment by Jxck** [comment]
無しということはリンクを表示しない分岐がいりますね。了解です。

**Comment by NaoyaShimizzz** [comment]
そうなりますね、お手数ですがご対応お願いします

**Comment by halsk** [comment]
@Jxck さん、状況どんな感じでしょうか。もし時間かかりそうなら引き継ぎます！今日のリリースに含めたい意向があるようです。

**Comment by halsk** [comment]
あ、失礼しました。PR出していただいているのですね
