### ISSUE TITLE
データが4/11に更新されているが更新日付が4/10になっている

### ISSUE THREAD

**Issue by hikarine3** [tokyo-metropolitan-gov/covid19#3155]
## 起こっている問題 / The Problem
- データが4/11に更新されているが更新日付が4/10になっている

## スクリーンショット / Screenshot
![都内の最新感染動向   東京都 新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/197538/79046415-c8b64000-7c4b-11ea-9851-b612c28407ad.png)

## 期待する見せ方・挙動 / Expected Behavior
- 4/11に明らかに更新されているので、4/10ではなく4/11を更新日時とするべき

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/　にアクセスして、データの中身と更新日時を確認

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
ご報告ありがとうございます！こちら調査しますね。

**Comment by kaizumaki** [comment]
@hikarine3 本番に正しい日付が反映されました。原因は調査中です。ご報告感謝です。

**Comment by kaizumaki** [comment]
こちらの件ですが、データ作業中にgithubの[障害](https://www.githubstatus.com/incidents/2wx06v7dbzhg)が起こっていたようです。
ご報告ありがとうございました。こちらのissueはクローズさせていただきます。
