### ISSUE TITLE
棒グラフチャートのbar幅固定+グラフ内横スクロール

### ISSUE THREAD

**Issue by hkomamiy** [tokyo-metropolitan-gov/covid19#316]
スマートフォン時にグラフ幅が細くなってしまうので実数確認のためのツールチップ数値が見にくくなってしまう。横スクロール縦のメモリをposition固定がいいかなと。

**Comment by saladdays** [comment]
こちらのプラグインでできるのではないかという話先日していました。
ご参考までに！
https://github.com/chartjs/chartjs-plugin-zoom
