### ISSUE TITLE
[やさしいにほんご]理解できない文章として表示されている部分がある

### ISSUE THREAD

**Issue by sutefu7** [tokyo-metropolitan-gov/covid19#3168]
## 起こっている問題 / The Problem
- 理解できない文章として表示されている部分があります。

>グーグルアナリティクスに情報(じょうほう)をおしえたくないときは、グーグルの[addom]をつかってください。

## スクリーンショット / Screenshot
- なし

## 期待する見せ方・挙動 / Expected Behavior

正しくは、以下のようにプレースホルダーのまま翻訳することだと思いました。
>グーグルアナリティクスに情報(じょうほう)をおしえたくないときは、グーグルの{addon}をつかってください。

以下を見ると、原因は、Transifex 側で誤翻訳したからかなと思いました。

>/assets/locales/ja-Hira.json
>"Google Analyticsによる情報送信を回避する場合は、Google がサポートする{addon}をご利用ください。": "グーグルアナリティクスに情報(じょうほう)をおしえたくないときは、グーグルの[addom]をつかってください。",

対応としては、Transifex 側で翻訳し直すことだと思います。ただ、”採用ルールがTransifex で翻訳したうち、最初に翻訳した1つ目の文章を採用するルールみたい？”なので、どうしたらいいものかと思っています。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 「多言語対応選択メニュー」で”やさしい にほんご”に変えた後、「このウェブサイトについて」ページの「Google Analytics について」の説明文章

- 開発サイト https://dev-covid19-tokyo.netlify.com/ja-basic/about
- ステージングサイト https://stg-covid19-tokyo.netlify.com/ja-basic/about
- 本番サイトhttps://stopcovid19.metro.tokyo.lg.jp/ja-basic/about

## 動作環境・ブラウザ / Environment
- Windows, Chrome でしか目視確認できていませんが、全ての環境で現象再現すると思います。
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nard-tech** [comment]
こちら，Transifex の翻訳設定を修正します．

**Comment by nard-tech** [comment]
「情報(じょうほう)」（半角括弧を使用）を，他に合わせて「情報（じょうほう）」（全角括弧を使用）に変更しました．

**Comment by sutefu7** [comment]
ご対応ありがとうございます。

理解できなくてすみません、直すのは以下だと思うのですが、カッコの半角・全角違いが原因でしたでしょうか？それとも別の問題から来た同じところの修正の話でしょうか？？
間違い→[addom]
正解　→{addon}

角かっこと波かっこ。addo【m】ではなく、addo【n】のスペルミス

**Comment by sutefu7** [comment]
上記３つのサイトすべて直っていることを確認しました！
本issueをcloseします。

ありがとうございました！
