### ISSUE TITLE
FORKED_SITES.mdから九州を削除

### ISSUE THREAD

**Issue by y2naranja** [tokyo-metropolitan-gov/covid19#3169]
## 改善詳細 / Details of Improvement
- FORKED_SITES.mdの九州の公開URIがNOT FOUNDになる
- スプレッドシート上は開発中となっているため、FORKED_SITES.mdに記載するのは不適切ではないか
- GitHub上のリソースを確認したが、1ヶ月前から進展がない
- 手をつけて良ければ、当該行を削除します。スプレッドシートはとりあえずそのままにしておきます。

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by y2naranja** [comment]
すみません、当方のローカル環境が今壊れているので、どなたかお願いいたします。

**Comment by goki90210** [comment]
再度リクエストしました。

**Comment by goki90210** [comment]
度々申し訳ありません。再度PRしました。
