### ISSUE TITLE
PWAのアイコンを設定する

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#317]
現状は Nuxt のアイコン

<img width="316" alt="スクリーンショット 2020-03-04 16 20 56" src="https://user-images.githubusercontent.com/8909592/75854747-2c22a600-5e34-11ea-973d-3a0fdb48c6a7.png">

**Comment by kaizumaki** [comment]
@amotarao あ、その件、現在のstagingでは修正されています！リリースまでお待ちいただけると！
https://stg-covid19-tokyo.netlify.com/

**Comment by amotarao** [comment]
失礼しました 🙏
