### ISSUE TITLE
「陽性患者数」のグラフに注意書きを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3198]
「陽性患者数」のグラフに以下の注意書きの追加をお願いします。

```
（注）医療機関が保険適用で行った検査も含む
（注）チャーター機帰国者、クルーズ船乗客等は含まれていない
```

追加する場所は以下の画像の赤枠部分です（他のグラフと同様）。
![陽性患者数グラフ](https://user-images.githubusercontent.com/14883063/79086323-99e8b880-7d76-11ea-8c45-561f80aaa4d4.jpg)

**Comment by yogurito** [comment]
対応します。

**Comment by kaizumaki** [comment]
@yogurito ありがとうございます！こちらhotfixとしたいので、 `staging` をベースブランチとしていただき、`staging` 向けに１つPRをご提出ください。
それとは別に、`development` をベースブランチとした `development` 向けPRもご提出いただけるとうれしいです。
ややこしくてすみません！
