### ISSUE TITLE
感染者数はpatients_summaryの方のdateを参照する

### ISSUE THREAD

**Issue by YuseiIto** [tokyo-metropolitan-gov/covid19#3207]
## 起こっている問題 / The Problem
- `components/cards/ConfirmedCasesNumberCard.vue`　で、`date` の指定が　`:date="Data.patients.date"`　となっている

## スクリーンショット / Screenshot
UIに出てこないのでコードを添付。  `b22bb573e`　時点でのコード。

```vue
<template>
  <v-col cols="12" md="6" class="DataCard">
    <time-bar-chart
      :title="$t('陽性患者数')"
      :title-id="'number-of-confirmed-cases'"
      :chart-id="'time-bar-chart-patients'"
      :chart-data="patientsGraph"
      :date="Data.patients.date"
      :unit="$t('人')"
      :url="'https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068'"
    />
  </v-col>
</template>

<script>
import Data from '@/data/data.json'
import formatGraph from '@/utils/formatGraph'
import TimeBarChart from '@/components/TimeBarChart.vue'

export default {
  components: {
    TimeBarChart
  },
  data() {
    // 感染者数グラフ
    const patientsGraph = formatGraph(Data.patients_summary.data)

    const data = {
      Data,
      patientsGraph
    }
    return data
  }
}
</script>

```
## 期待する見せ方・挙動 / Expected Behavior
- このカードは `patients_summary`を参照しているから、`patients_sumamry.date`　を参照する方が自然である

## 起こっている問題の再現手段 / Steps to Reproduce
少なくともコミット`b22bb573e` までの状態に存在する問題。

## 動作環境・ブラウザ / Environment
全環境(コード上の問題)

**Comment by YuseiIto** [comment]
自己解決します

**Comment by YuseiIto** [comment]
失礼しました。commit IDですが、私の環境のものを参照していました。　`b4f5300 ` が正しいです。

**Comment by asuchi0819** [comment]
`pages/cards/_card.vue`もpatientsを利用しています。
ご確認いただければ幸いです。

https://github.com/tokyo-metropolitan-gov/covid19/blob/ce310eb96abdc9c4232f18fdb14d3b3c45addd31/pages/cards/_card.vue#L91

**Comment by YuseiIto** [comment]
ご指摘ありがとうございます。修正します。
