### ISSUE TITLE
パフォーマンス目標の明確化

### ISSUE THREAD

**Issue by ymkjp** [tokyo-metropolitan-gov/covid19#3219]
## 改善要望 / Improvement requirements

- 目標となるパフォーマンス指標を策定する
  - 背景: 非機能要件の議論 #2790 ではスコープ外となっていますが、直近で Lighthouse のパフォーマンス指標はモバイル・デスクトップともに **20-40** と改善の余地がある
  
## スクリーンショット / Screenshot

<img width="1792" alt="audit-ja-20200411" src="https://user-images.githubusercontent.com/992558/79109560-8d368580-7db3-11ea-92e9-84bf6c576b65.png">

## 期待する見せ方・挙動 / Expected behavior

1. はじめに「計測できないものは制御できない」([DeMarco, 1982](https://en.wikiquote.org/wiki/Tom_DeMarco)) という経験則に習い、CIなどで見える化する
    - 明らかに指標が悪化する diff を取り込んでしまうことを避けられる
    - 改善のイテレーションが回しやすくなる
1. その後 Lighthouse の [Performance Budgets](https://developers.google.com/web/tools/lighthouse/audits/budgets) あるいは、より広範な [Apdex](https://en.wikipedia.org/wiki/Apdex) といった指標を策定する

**Comment by kaizumaki** [comment]
こちらのissueが起票された頃に比べるとだいぶ改善されてきていますので、一旦クローズといたします。
