### ISSUE TITLE
Copyrightにlang="en" を追加

### ISSUE THREAD

**Issue by yoshi1125hisa** [tokyo-metropolitan-gov/covid19#322]
英語であることを明示するために、lang属性を追加します。

**Comment by ramandeepB** [comment]
Hi @yoshi1125hisa san
Please provide more information. Where to add lang=en ?

**Comment by yoshi1125hisa** [comment]
Hi @ramandeepB san:
Thank you for your reply.
Even for Japanese sites, adding lang=en to the English part (the copyright part in this case) is considered to be recommended from the viewpoint of accessibility.
