### ISSUE TITLE
[dev] tableの日付ソートがおかしい（「陽性患者の属性」・グラフの下の「テーブルを表示」）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3259]
## 起こっている問題 / The Problem
- [devサーバー](https://dev-covid19-tokyo.netlify.com/) で起こっています。
- グラフの下の「テーブルを表示」で開くtableの日付ソートが、２桁目で判定されてしまっているようです。
- **追記：**「陽性患者の属性」の表でも同様です。

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-14 9 40 22](https://user-images.githubusercontent.com/14883063/79174234-01653d80-7e35-11ea-9170-ce6ea9c77249.png)

## 期待する見せ方・挙動 / Expected Behavior
- 日付の降順でソートされる

## 起こっている問題の再現手段 / Steps to Reproduce
1. [devサーバー](https://dev-covid19-tokyo.netlify.com/) 
2. グラフの下の「テーブルを表示」をクリック

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
付属tableが存在しない「陽性患者の属性」の表でも同じ現象が起こっていますね。

**Comment by shgtkshruch** [comment]
@kaizumaki 

申し訳ありません、日付の降順でソートできていませんでした...
#3261 に修正の PR を作成させていただきましたので、ご確認お願いします！
