### ISSUE TITLE
「陽性患者数（区市町村別）」の表を新規作成＆グラフ・表の並べ替え

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3265]
「陽性患者数（区市町村別）」の表の新規作成をお願いします。
こちらの表を配置する際に、サイトトップのグラフ・表の並べ替えも同時にお願いいたします。

### 実装イメージ
※この画像では一部にしか背景色がついていませんが、実装では行全体（交互）に背景色がつきます。
<img width="485" alt="陽性患者数（区市町村別）イメージ" src="https://user-images.githubusercontent.com/14883063/79180290-8ad03c00-7e44-11ea-9fbe-30d275bf7888.png">

### 使用するデータ
```
data/patient.json
```
※こちらのデータは現時点ではダミーです。

### 気をつける点
- デフォルトで「ふりがな」の昇順にしてください。
- ソート機能は以下の２点を満たす形でお願いします。
```
 - ふりがなと自治体コードでのソートを可能にする
 - 陽性患者数のソートはできないようにする
```
- いずれのソートを実行したときにも、「調査中」が一番下になるようにカスタムソートを実装してください。

### 表の配置場所および並べ替え
以下の順番になるように配置・並べ替えを行ってください。
```
1) 検査陽性者の状況
2) 陽性患者数
3) 陽性患者の属性
4) 区市町村別患者数　★こちらのissueで新設
5) 検査実施状況
6) 検査実施人数
7) 検査実施件数
```
**※追記：**「新型コロナコールセンター相談件数」以下のグラフは順番はそのままで、上記の `7)` 以降に配置してください。

なにか疑問点あれば、遠慮なくこのissueにコメントしてください！

**Comment by kebhr** [comment]
本件対応します！

**Comment by kaizumaki** [comment]
@kebhr よろしくお願いします！

**Comment by kaizumaki** [comment]
@kebhr 作業中にすみません。いましがた都からデータの仕様変更依頼があったため、ただいま内容を精査中です。申し訳ありませんが、実装作業のほうを中断していただければと思います 🙇‍♀️

**Comment by kebhr** [comment]
@kaizumaki 
承知しました！

**Comment by kaizumaki** [comment]
@kebhr お待たせしました。仕様変更後の `patient.json` をdevelopmentブランチに反映させました。作業を再開していただけるとうれしいです。
実装の指示は以下のとおりです。

1. 「自治体コード」の列は表示しない。
1. 「地域」の列を追加。内訳は特別区/多摩地域/島しょ地域の3種類とし、特別区の五十音順、多摩地域の五十音順、島しょ地域の五十音順、調査中の順とする。
列の並び順イメージは以下のとおり。
 
　　地域　　　　　ふりがな　　　　　区市町村　　　陽性患者数
　　特別区　　　　あだちく　　　　　足立区　　　　　●
　　特別区　　　　あらかわく　　　　荒川区　　　　　●
　　　：
　　（省略）
　　　：
　　多摩地域　　　あきしまし　　　　昭島市　　　　　●
　　　：
　　（省略）
　　　：
　　島しょ地域　　あおがしまむら　　青ヶ島村　　　　●
　　　：
　　（省略）
　　　：
　　　　　　　　　　　　　　　　　　調査中　　　　　●

1. ソート機能はすべて無効にする。

以上になります。なにかわからないことがあればコメントください！

**Comment by kebhr** [comment]
@kaizumaki 
`patients.json` には「都外」と「小計」のデータがありますが、これらは表示しないということで問題ないでしょうか？
```json
...
{
    "code": null,
    "area": null,
    "label": "都外",
    "ruby": null,
    "count": 50
},
...
{
    "code": null,
    "area": null,
    "label": "小計",
    "ruby": null,
    "count": 1902
}
```

**Comment by kaizumaki** [comment]
@kebhr おっと、確認しますね！

**Comment by kaizumaki** [comment]
@kebhr 確認しました。
- 「都外」は「調査中」の上に入れる
- 「小計」は表示しない

だそうです。
それと、 `patients.json` には元データに入力されたすべての日付分が含まれていますが、サイトに表示するのは最新の日付分のみで大丈夫です。

**Comment by kebhr** [comment]
@kaizumaki 
もう一点確認です。
カードの左下に表示する更新日時ですが、`patient.json`では`"date": "2020\/4\/11"`と、日付しか与えられていません。
時間の部分は決め打ちにして、`Data.slice(-1)[0].date + " 11:00"` のようなイメージで表示してよいのでしょうか？

**Comment by kebhr** [comment]
すみません更にもう一点です。
実装イメージに
`（注）チャーター機、クルーズ船乗客等は含まれていない。`というテキストがありますが、既に類似するテキスト
`（注）チャーター機帰国者、クルーズ船乗客等は含まれていない`が「検査陽性者の状況」などで使用されています。
意味合いは同じかと思いますので、どちらかに表現を統一したいと思いますが、いかがでしょうか？

**Comment by kaizumaki** [comment]
@kebhr ご指摘ありがとうございます！
更新日時については元データが存在するのですが、こちらでjsonに反映させるのを失念しておりました。現在、修正版のjsonを準備しております。これによって構造が若干変わりますことご了承ください 🙇‍♀️  準備できたらお知らせしますね。
そしてこちらの注釈については、すでに存在するテキストに統一しましょう。
`（注）チャーター機帰国者、クルーズ船乗客等は含まれていない` のほうでお願いします。

**Comment by kaizumaki** [comment]
@kebhr お待たせしました。 `patient.json` を更新しました。更新日時を付与するとともに、最新の日付分のみのデータにしました。
更新日時 `date` とデータの集計日 `datasets.date` がずれているのは間違いではありません（しかも現在のjsonは最新の状態ではないので日付が前後しています）。実際には、集計日は更新日時の前日になります。

そして、データの集計日も追加表示してほしいです。
位置は以下の赤枠部分です。
「4/14の累計」のように「の累計」というテキストを追加してください。
スタイルは「陽性患者の属性」の表の右上の累計表示と同じようにしてください。
![200415_区市町村別感染者数](https://user-images.githubusercontent.com/14883063/79335062-5e0f4800-7f5c-11ea-982d-e09f34746cf3.png)

どうぞよろしくお願いいたします 🙇‍♀️
