### ISSUE TITLE
スマートフォンのブラウザで表示がとても重くなっている

### ISSUE THREAD

**Issue by amay077** [tokyo-metropolitan-gov/covid19#3267]
## 起こっている問題 / The Problem
- スマートフォン（Android）のブラウザで当サイトを開き、スクロールしていくと、ブラウザがフリーズ状態になり、その後「応答なし」となります。

## スクリーンショット / Screenshot

再現手段の動画（ZIP）です。

[20200414_122654.zip](https://github.com/tokyo-metropolitan-gov/covid19/files/4472950/20200414_122654.zip)

## 期待する見せ方・挙動 / Expected Behavior
- 根本から原因が解決できればベストですが、スマートフォンで見る場合は、表示内容を簡略化してもよいかと考えます
- 例えば情報量が多いと思われる「陽性患者の属性」は、スマートフォンでは閲覧できなくてもよいかなと思います

## 起こっている問題の再現手段 / Steps to Reproduce
1. Android の Chrome で https://stopcovid19.metro.tokyo.lg.jp/ を開く
2. トップページが表示されたら下へ徐々にスクロールする
3. とちゅうでフリーズ状態となり、しばらくすると「応答がありません」と表示される

## 動作環境・ブラウザ / Environment
- Android 9
- Chrome
- 機種1: Xperia XZ1 Compact（発売から２年半ほど経過した機種ではありますが、現役と呼べる性能と認識しています）
- 機種2: HUAWEI nova lite 3 (Android 10)

複数台で試しましたが、私個人の端末・環境に依存するかも知れませんので、他の方の状況も確認・提供いただけますとありがたいです。

**Comment by shgtkshruch** [comment]
issue の起票ありがとうございます。
[Slack で共有](https://cfj.slack.com/archives/CUX3F56LF/p1586824666367800) されていましたが、「陽性患者の属性」はテーブルの行数がかなり多いので、こちらのレンダリングが重いのが関連していると思います。

また、#2068 の対応で各グラフごとにテーブルを表示するようにしたので、今後こちらのデータが増えることで同じ現象が起こることも想定されます。（こちらは日次でテーブルの行数が増えていきます）

テーブルの表示はページネーションをつけるなど、一度に表示する情報量をコントロールするのも一つの方法として検討してもいいかもしれません。

**Comment by sukobuto** [comment]
【共有】こちらの環境では特に指摘されている問題は見られませんでした。
- Android 10
- Chrome
- Pixel 3

「テーブルの表示」をタップしても問題なく動作しました。

**Comment by amay077** [comment]
関連あるかなとおもうので #3219 にリンクしておきます。

**Comment by koogawa** [comment]
【共有】こちらの環境では特に指摘されている問題は見られませんでした。

- Android 10
- Pixel 3

「テーブルの表示」をタップしても問題なく動作しました。

**Comment by koukimetal** [comment]
確かに「陽性患者の属性」は、テーブル部分を「表示する」ボタンに置き換え、ボタンが押された後JSONをフェッチしてきて、レンダーするとかでも良い気がします。

**Comment by koukimetal** [comment]
#shgtkshruch さんが述べていたページネーションが一番良い気がします。
#3177でも議論されているのですが、そのテーブルが大量のDOMを持つせいで、開発環境にも悪影響を及ぼしています。ページネーションを導入すれば、「フェイクデータで起動」などを実装する必要も無くなり、一石二鳥だと思います。v-data-taleにもページネーションがあるみたいですし。
https://vuetifyjs.com/ja/components/data-tables/
どう思いますか？ @kaizumaki

**Comment by amay077** [comment]
一応確認として、 1ae0d71e028c85e3958d450e4ad3ed0ff71811ae のソースコードをローカルで ``yarn dev`` で動作させ、ngrok 経由で当該機種のスマホブラウザで表示させてみました。

``pages/index.vue`` に
 
- ``<confirmed-cases-attributes-card />`` がある場合: 重く、「応答なし」になる
- ``<confirmed-cases-attributes-card />`` をコメントアウトした場合: 快適に表示できる

となりました。
やはり「陽性患者の属性」が原因である、事が確認できました。

**Comment by kaizumaki** [comment]
ご提案ありがとうございます！ただ、何が原因であるか具体的な数値やデータがないように思いますので、すぐに判断できかねますね...
「陽性患者の属性」の表は重要なデータの１つであるので、端末によって非表示になるのは避けたいところです。
`data.json` 自体は容量的にもいわゆる画像データに比べたらそんなでもないんですよね。
いずれにせよ、ちゃんと検証しないとなんとも言えないのですが...

**Comment by amay077** [comment]
はい、少しふわっとした issue でした。
iPhone XS Max でも問題ないとも聞きましたし、意外と皆さん（ハイエンド端末しか持ってない人が多くて）問題になっていないのかな？

指標については  #3219 など別の issue に譲りますので、
こちらは運営の方の任意のタイミングで close していただいて結構ですー。

**Comment by kaizumaki** [comment]
@amay077 かしこまりました。ではこちらのissueはクローズしますね。

**Comment by amay077** [comment]
報告ですが、 #3867 を対応していただいたので、本件も解決され、Xperia XZ1 Compact でも快適に閲覧できるようになりました。

ありがとうございました。
