### ISSUE TITLE
[Improvement] [Nice-to-Have] X-Axis Density Switch (D/W/M) Especially in Confirmed Cases Chart

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#3268]
## 改善詳細 / Details of Improvement
- (JA) 陽性患者数のスイッチ「日別」に、「週別」「月別」を加える
- (EN) Add switch items "Weekly" and "Monthly" to the switch of Confirmed Cases (Daily) chart

## スクリーンショット / Screenshot

(Now Planning)

## 期待する見せ方・挙動 / Expected behavior
- (JA) 日別/週別/月別に陽性患者数グラフを切り替えることで、過去データに沿った傾向分析と予測のチャンスがもたらされる
- (EN) Switching chart periods in per day, week and month may provide people (according med/stat experts assumed) with useful data in which they would be able to find statistic trends

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster ご提案ありがとうございます。こちらのissueについて都に確認いたしました。現時点では日別のデータを一覧できるようにしたいという意向があり、週別・月別のデータはまだ検討する時期ではないと考えます。しばらく週別・月別の実装は見送ることになりますので、こちらはクローズさせていただければと思います。ご理解のほどよろしくお願いいたします。

**Comment by mcdmaster** [comment]
りょうかいしました！ご確認をいただきありがとうございます。
では、クローズいたします
