### ISSUE TITLE
netlifyのデフォルトのエラーページが表示されてしまう

### ISSUE THREAD

**Issue by szk18** [tokyo-metropolitan-gov/covid19#327]
## 概要
存在しないページにアクセスするとnetlifyのデフォルトのエラーページが表示されてしまいます。

![スクリーンショット 2020-03-04 18 27 36](https://user-images.githubusercontent.com/39793156/75865011-33eb4600-5e46-11ea-84a3-a9a2ffa73002.png)

**Comment by potato4d** [comment]
これもわかるのでもらいます！！！

**Comment by mikkame** [comment]
こちらの件はエラーページ自体は作成してあるようなのですが
SSR時にしか効かないようです。
generate時に静的に404.htmlを作成する感じかと思うのですが・・・

**Comment by potato4d** [comment]
そうですね、 404.html を設定して、 Netlify の redirects でやる形になると思います。
目処は立ってるのですぐできるかと〜

**Comment by potato4d** [comment]
よろしければ、 Netlify Deploy Preview を設定いただけると助かります……！（負担なら結構です！）

**Comment by mikkame** [comment]
設定するための準備中です。
申し訳ないのですがもうしばらくお待ちください

**Comment by potato4d** [comment]
@mikkame 
手間かけさせてしまうのもなんですので、私の方で個人の環境作って確認。 PR 発行しました :pray:
