### ISSUE TITLE
サイドナビに「新型コロナウイルス感染症に関する東京都の支援策」外部リンクを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3274]
サイドナビに以下の外部リンクのメニューの追加をお願いします。

- テキスト：新型コロナウイルス感染症に関する東京都の支援策
- URL：https://www.seisakukikaku.metro.tokyo.lg.jp/information/corona-support.html
（本日（4/14）19時Openとなります）
- 位置：「東京都新型コロナウイルス感染症対策本部報」と「東京都主催等 中止又は延期するイベント等」の間に入れてください。

**Comment by yogurito** [comment]
対応します。

**Comment by yogurito** [comment]
PR #3276 を用意しました。Hotfix にする場合は staging 向けの PR を別途用意しますので、ご連絡ください。

**Comment by kaizumaki** [comment]
@yogurito 迅速なご対応ありがとうございます！hotfixにはしなくてすみそうです。

**Comment by yogurito** [comment]
了解です。ご確認ありがとうございます!
