### ISSUE TITLE
「埋め込みコードをコピーしました」の文言について

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3275]
## 起こっている問題 / The Problem
- `components/DataView.vue` にて
    https://github.com/tokyo-metropolitan-gov/covid19/blob/4b7fe62612fd0288cb470ebc634806c5069211f5/components/DataView.vue#L148-L152 上記のように「埋め込みコード」と指定されているが、 `assets/locales/ja.json` では
    https://github.com/tokyo-metropolitan-gov/covid19/blob/4b7fe62612fd0288cb470ebc634806c5069211f5/assets/locales/ja.json#L153-L156 上記のように「埋め込み用コード」と指定されている
- 開発時にどちらが先だったかはさておき、この部分は `<h4>{{ $t('埋め込み用コード') }}</h4>` とタイトルがついているので、「埋め込み**用**コードをコピーしました」の方が自然だと思われる

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/34566290/79200800-f4b30a80-7e71-11ea-9ae8-23e58b46d690.png)

## 期待する見せ方・挙動 / Expected Behavior
- 上記「起こっている問題 / The Problem」の通り

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/ にアクセスする
2. いずれかのグラフ・表の右下のシェアボタンをクリック
3. 埋め込み用コード右上に表示されているコピーボタンをクリック

## 動作環境・ブラウザ / Environment
- 検証環境: Windows 10 Home 1903 64 bit + Chrome 80.0.3987.149

**Comment by khsacc** [comment]
対応しますー。
