### ISSUE TITLE
[周知] コントリビューターの皆様へ

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#328]
現在、様々なメッセージや Issue、 Pull Reuest をいただいています。
ありがとうございます！嬉しいです！
こちらの、[貢献の仕方](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/CONTRIBUTING.md) ページをご確認いただき、貢献いただけましたら幸いです！

**Comment by 515hikaru** [comment]
おせっかいかもしれませんが、周知 Issue は Pin しておくといいかもです。

[Issue をリポジトリにピン止めする \- GitHub ヘルプ](https://help.github.com/ja/github/managing-your-work-on-github/pinning-an-issue-to-your-repository)

**Comment by potato4d** [comment]
@515hikaru 
Pin しておきました。ありがとうございます！

**Comment by dhgrs** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/blame/2dcd301e4e137490bef5a904943872ce27ebd8b5/.github/CONTRIBUTING.md#L20

Issue のアサインに関する記述がありますが、現状ではすべてのコントリビュータが自身をアサインできるようにすることができないです。以下のサイトを参照すると、アサインにはリポジトリへの書き込み権限が必要です。
https://help.github.com/ja/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users

英語版には同様の記載がないため、英語版に合わせて削除するか、実現可能な代替案を記述するのが良いと思います。

**Comment by mikkame** [comment]
ご指摘ありがとうございます。
たしかにアサインできない状況のようです。

文言を削除し、issueに宣言していただく形で運用していった方が良さそうですね。

明日の対応になってしまいますがよろしくお願いします

**Comment by smellman** [comment]
Assignの前にDraft Pull Requestを投げれば誰がやってるかはわかると思いますがどうでしょう？
