### ISSUE TITLE
[ruby] トップページのルビタグ追加対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3296]
**プルリクエストはdev-ja-hira-ruby ブランチに向けて作成してください。**

トップページの以下の項目のルビタグ対応をお願いします。
https://ja-hira-covid19-tokyo.netlify.com/ja-basic/

ルビタグの実装方法については、#3116 にまとめています。
こちらをご確認の上、実装をお願いいたします。

疑問点があればこの issue 内でコメントください！

### 1. 東京都緊急事態宣言へのリンク
![スクリーンショット 2020-04-14 20 22 42](https://user-images.githubusercontent.com/5207601/79220117-6600b680-7e8e-11ea-85f3-b5fdfdd6a218.png)

### 2. 各グラフ下部にあるテーブルのヘッダー部分
- 陽性患者数
- 検査実施人数
- 検査実施件数
- 新型コロナコールセンター相談件数
- 新型コロナ受診相談窓口相談件数
- 都営地下鉄の利用者数の推移
- 都庁来庁者数の推移

例えば、陽性患者数のグラフでは以下の部分が該当します。

![スクリーンショット 2020-04-14 20 22 46](https://user-images.githubusercontent.com/5207601/79220445-f3440b00-7e8e-11ea-8282-300a50c6e578.png)

テーブル部分は Vuetify の Data Tables コンポーネントで実装しているので、
必要があればこちらの API を利用してください。
ref: https://vuetifyjs.com/en/components/data-tables/

### 3. 都営地下鉄の利用者数の推移 の下部にある PDF へのリンク
![スクリーンショット 2020-04-14 20 22 51](https://user-images.githubusercontent.com/5207601/79220121-68631080-7e8e-11ea-89b9-0c547f59a64e.png)

**Comment by MaySoMusician** [comment]
3. についてルビの括弧が半角になっている件は、既にTransifexにて修正済みです（反映待ち）

**Comment by shgtkshruch** [comment]
@MaySoMusician 
#3265 でトップページに「陽性患者数（区市町村別）」の表が追加されましたが、こちらの対応はいかがいたしましょうか？

こちらの issue でまとめて対応する場合は、`development` を `dev-ja-hira-ruby` にマージいただいてから着手しようと思います。

![スクリーンショット 2020-04-16 20 24 20](https://user-images.githubusercontent.com/5207601/79450750-47cac000-8020-11ea-8250-5aae5c853784.png)

**Comment by MaySoMusician** [comment]
後ほど `development` を `dev-ja-hira-ruby` に取り込みます。それまでしばらくお待ちください...

**Comment by shgtkshruch** [comment]
こちらでマージいただいたので、着手いたします。
https://github.com/tokyo-metropolitan-gov/covid19/issues/3116#issuecomment-615582746

**Comment by MaySoMusician** [comment]
Close per #3471 merged
