### ISSUE TITLE
[/flow][全面改修]ページマークアップ

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3315]
「新型コロナウイルス感染症が心配なときに」ページ（flow）が全面改修になります。
デザインカンプはこちらです。
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=32770%3A3521

- 現状のflowページは、デスクトップサイズ版（PC）とモバイルサイズ版（SP）とが別々のコンポーネントになっていますが、こちらの改修では分けずにレスポンシブでいこうと思います。
- デザインカンプにある上部の３つ横並びのイラスト入り緑枠はナビゲーションです。クリックしたときにスクロールに追従する形になります。（こちらの仕様の詳細は後ほどお伝えします -> **figma内に指示を記入しました**）
- 印刷対応、やさしい日本語のルビ対応は、こちらのissueでは考慮しません。まずは日本語でサイトに載せることが最優先です。
- 17日（金）のリリースを目指します。もし作業途中でしばらく離れる場合は、Draft PRを出しておいてください。

レスポンシブにする際のレイアウト調整やマークアップについて、なにか疑問点があれば遠慮なくこのissueにコメントしてください！

**Comment by macropygia** [comment]
着手します。

**Comment by kaizumaki** [comment]
@macropygia ありがとうございます！よろしくお願いします！

**Comment by macropygia** [comment]
@kaizumaki 確認事項をお送りします。

- font-sizeが12種類（10-12,14,16-20,22,26,29px）あり、「日本語決め打ちで外観のバランスを取るため」に指定されているものが多いように見受けられるため、内容の重みに応じて統廃合しても構わないでしょうか
- 各所の緑色がa11y対応のコントラスト修正前の旧カラーですが、現行パレットに合わせて問題ないでしょうか
- グレーの太枠の色が variables.scss にないもの（恐らく同上）ですが、現行パレットの近いものに合わせて問題ないでしょうか
- 文中の明示的な改行は全て完全再現で問題ないでしょうか（i18n対応で面倒なことになる奴だったような？）

**Comment by forestgtree** [comment]
@macropygia デザイン担当（Figma作成者）です。
実装ありがとうございます🙇‍♂️

以下、確認事項についてです。

- フォントサイズについては、統廃合していただいて構いません。（特に10pxについては小さすぎますので12pxなどにサイズアップしていただきたいです。）
- 色味に関しては、現行パレットに合わせてください。
- グレーの太枠については、現行パレットで同等の色に合わせてくださ。
- 改行に関しては、完全再現は求めません。（i18n対応を意識してやっていただけるのが最良です！）

不備が多々あり申し訳ありませんでした。
よろしくお願いします！

**Comment by khsacc** [comment]
おつかれさまです。figma、実装ともに拝見させていただきました、素晴らしいですね！
以前、このページに関連する改修を行った者として気になったのですが、印刷用ページ/print/flowの改修については、運営の方や東京都の方はどのようにお考えでしょうか。
個人的には、新しいUIベースで印刷用ページも改修してみたいと思ったのですが、UIデザイナーの方をはじめ、意見をお聞きしたいです。

**Comment by kaizumaki** [comment]
@khsacc フォローいただきありがとうございます！印刷対応、やさしい日本語のルビ対応、それぞれ別issueで行っていただきたく思います。今回は急ぎの案件でしたので、このような形ですすめさせていただきました。

**Comment by khsacc** [comment]
別issueを立ててそれぞれ対応する方針、承知いたしました。ひとまず @macropygia さんのPull Requestが閉まるのを待ちたいと思います。
