### ISSUE TITLE
やさしい日本語のときに都営地下鉄のツールチップで数値が消えている

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3319]
## 起こっている問題 / The Problem
- やさしい日本語で表示した際に、都営地下鉄の推移グラフのツールチップで数値部分が消えています
- 英語など他の言語では数値が表示されていました

### やさしい日本語
![スクリーンショット 2020-04-15 17 15 13](https://user-images.githubusercontent.com/5207601/79314836-32309a00-7f3d-11ea-8530-65307cc6119a.png)

### 日本語
![スクリーンショット 2020-04-15 17 15 39](https://user-images.githubusercontent.com/5207601/79314843-33fa5d80-7f3d-11ea-915d-863551716e51.png)

### 英語
![スクリーンショット 2020-04-15 17 16 39](https://user-images.githubusercontent.com/5207601/79314847-3492f400-7f3d-11ea-8e5c-a58a6f71cb55.png)

## 期待する見せ方・挙動 / Expected Behavior
- やさしい日本語で表示した際に、ツールチップに数値が表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/ja-basic を開いて都営地下鉄のグラフにマウスホバーする

## 動作環境・ブラウザ / Environment
おそらくすべての環境で起こっています。

**Comment by k-kawane** [comment]
やります！

**Comment by MaySoMusician** [comment]
やさしい日本語のほうで変数が埋め込まれていないのが原因でした。
Transifexで修正したので、翻訳が反映されれば解決されるはずです

**Comment by shgtkshruch** [comment]
ご対応ありがとうございます！
やさしい日本語でツールチップに数値が表示されていることを確認できましたので、クローズします。

![スクリーンショット 2020-04-18 10 14 28](https://user-images.githubusercontent.com/5207601/79624575-6bdfeb80-815d-11ea-9c58-a9b0e9dd3ecc.png)
