### ISSUE TITLE
（棒グラフ共通）右上に表示する数値の変更

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#334]
棒グラフの右上には以下の数値を表示

・「推移（日別）」選択時
**[最新日付の実績値] [単位]**
**[最新日付]** 実績値（前日比： **[最新日付と前日の値の差分] [単位]**）

例）新型コロナコールセンター相談件数 
<img width="580" alt="スクリーンショット 2020-03-04 18 28 05" src="https://user-images.githubusercontent.com/4206675/75869384-d4dcff80-5e4c-11ea-8faa-f1e60730800e.png">

**Comment by ocean3fish** [comment]
・「累積（累計）」選択時
[最新日付の累計値] [単位]
[最新日付] 累計値（前日比： [最新日付と前日の累計値の差分] [単位]）

例）新型コロナコールセンター相談件数
<img width="579" alt="スクリーンショット 2020-03-04 19 20 51" src="https://user-images.githubusercontent.com/4206675/75869901-9562e300-5e4d-11ea-863e-1f011d1bae36.png">

**Comment by sunecosuri** [comment]
対応しますー🙋

**Comment by halsk** [comment]
#359 で修正されました。
