### ISSUE TITLE
47都道府県の対策サイトへのリンク集を設置する

### ISSUE THREAD

**Issue by hide-G** [tokyo-metropolitan-gov/covid19#3344]
## 「各都道府県の対策サイトへのリンク集」へのページを設けていただきたいです。

有志の方がすでに作成されていますが、このようなページへのリンクが、
イメージ画像の赤枠のようにあると、各県との状況比較が出来ると思います。

StopCovid19 全国版
[https://stopcovid19.code4japan.org/](url)
全国の新型コロナウイルス対策サイト
[https://stopcovid19japan.com/](url)

- イメージ画像
<img width="173" alt="対策サイト" src="https://user-images.githubusercontent.com/29442843/79348172-9e2bf600-7f6f-11ea-9626-827b0c82c94a.png">

**Comment by kaizumaki** [comment]
@hide-G ご提案ありがとうございます。こちらのissueについて都に確認いたしました。当サイトは東京都の公式サイトである点、各地域のサイトは公式/非公式のものが混在している状況を踏まえると、サイドナビに「各都道府県の対策サイトへのリンク集」を配置するのは難しいです。ご理解のほどよろしくお願いいたします。

**Comment by hide-G** [comment]
ご確認いただき誠にありがとうございます。
