### ISSUE TITLE
都営地下鉄の利用者数の推移

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#337]
こちらのデータを下記の公表されているグラフに準拠して、グラフ化したく、デザイン作成お願いします。データは週次更新予定です。
https://codeforjapan.sharepoint.com/sites/covid19/Lists/List2/DispForm.aspx?ID=2&e=s6ATHI

公表されているグラフ
https://www.bousai.metro.tokyo.lg.jp/_res/projects/default_project/_page_/001/007/425/2020030316.pdf

**Comment by ocean3fish** [comment]
グラフ案：
（公表されているグラフ形に準拠）
<img width="905" alt="スクリーンショット 2020-03-05 3 16 36" src="https://user-images.githubusercontent.com/4206675/75909609-c19f5380-5e8f-11ea-8a57-93f04dcb323d.png">

**Comment by ocean3fish** [comment]
公表されているグラフに記載されていたデータ注記事項：
※ 都営地下鉄4路線の自動改札出場数
※ 「1月20日から24日の週の平均」との比較

**Comment by mikkame** [comment]
地下鉄計 |   |   |  
-- | -- | -- | --
  | 6：30～7：30 | 7：30～9：30 | 9：30～10：30
2月10日～14日 | -0.96% | -2.94% | -7.48%
2月17日～21日 | -0.36% | -4.11% | -6.95%
2月25日～28日 | 3.06% | -9.47% | -7.31%

想定されるデータ形式は上記の通りです。
とりあえず固定のjsonを/data/metro.js
みたいな感じで置いておく方向でお願いしたいです

**Comment by shgtkshruch** [comment]
Slack で @halsk san とコミュニーケーションを取らせていただいたのですが、データをいただければ Chart.js で以下のような棒グラフを実装させていただきます。

![スクリーンショット 2020-03-05 10 29 48](https://user-images.githubusercontent.com/5207601/75938908-4314d700-5ecc-11ea-807f-0fdc56235669.png)
ref: https://www.chartjs.org/samples/latest/charts/bar/vertical.html

色やデザインは既存のグラフに揃える方向で実装しようと思います。

**Comment by mikkame** [comment]
@shgtkshruch 早速ご確認ありがとうございます。
データですが、取り急ぎ
固定の
jsonを/data/metro.json
に置いていただき実装いただけますでしょうか。

下記のようなイメージです（手書きしたのでJSONとして成立していなさそうです）
```
datasets: [{
            label: '6:30~7:30',
            data: [-0.86, -2.94, -7.48]
        }, {
            label: '7:30~9:30',
            data: [-0.36, -4.11, -6.95],
        }, {
            label: '9:30~91030',
            data: [3.05, -9.37, -7.31],
        }],
        labels: ['2月10日～14日', '2月17日～21日', '2月25日～28日']
}
```

**Comment by mikkame** [comment]
@shgtkshruch 
すみません、
#430 こちらでmetro.json
がきていますのでどちらか好きな方で対応お願いします

**Comment by halsk** [comment]
あ、すみません。かぶってしまった。
@mikkame さんの方が綺麗かもしれませんね

**Comment by shgtkshruch** [comment]
了解しました。
#430 の `date` を @mikkame さんのデータ構造に追加する形で実装してみます！

**Comment by mtenjin** [comment]
都営地下鉄利用者数推移のデータですが、SharePointサイトにデータをアップロードしました。
https://codeforjapan.sharepoint.com/sites/covid19/DocLib4/都営地下鉄利用者数推移.xlsx

当初のフォーマットは大きく変えず、期間開始日を追加して日付処理を行いやすくしています。

**Comment by shgtkshruch** [comment]
@mikkame @halsk 

こちらで #442 仮のデータ実装したプルリクエストを出させていただきました。
データ構造は以下のような一旦以下のような形にしております。

お手すきの際にご確認お願いします。

```json
{
  "date": "2020\/3\/5 10:00",
  "datasets": [
    {
      "label": "2月10日~14日",
      "data": [-0.96, -2.94, -7.48]
    },
    {
      "label": "2月17日~21日",
      "data": [-0.36, -4.11, -6.95]
    },
    {
      "label": "2月25日~28日",
      "data": [3.06, -9.47, -7.31]
    }
  ],
  "labels": ["6:30~7:30", "7:30~9:30", "9:30~10:30"],
  "base_period": "1月20日~1月24日"
}
```

**Comment by mikkame** [comment]
ありがとうございますグラフの種類が増えてきていいですね！
