### ISSUE TITLE
「検査実施件数」のグラフで医療機関からの報告分をわかりやすく表示してほしい

### ISSUE THREAD

**Issue by atsushieno** [tokyo-metropolitan-gov/covid19#3374]
## 改善詳細 / Details of Improvement

現在「検査実施件数」のグラフの数字の更新は次のような状況になっていると想像します。

- 保健所等からのレポートは1,2日(?)遅れで毎日上がってくる
- 医療機関からの更新分が金曜日に加算される（「医療機関が保険適用で行った検査については、４月８日分までを計上（毎週金曜日に、前週木曜日から当該週水曜日までの日々の件数を反映） 」とある通り） ※本issue作成時点での表記

現在のグラフではこれらがひとまとめになっているので、注意深く見ないと「こんな状況なのに検査実施件数がここ数日で激減している…?」と誤った解釈がなされやすいように思います。

また医療機関から届くレポートがどれくらいの割合なのか、個人的には興味がありますし、他にもそういう人はいるのではないかと思います。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/53929/79441440-311d6c80-8012-11ea-9d9e-0fcaa4c8336e.png)

## 期待する見せ方・挙動 / Expected behavior

医療機関からのレポート分を色分け・数字を区別して表示してみてはどうでしょう。「都庁来庁者数の推移」では実現できているようなので、実装が困難ということはないと想像します。

## 動作環境・ブラウザ / Environment

- Linux (Ubuntu 19.10)
- Firefox 75.0

**Comment by methane** [comment]
タイトルの「検査実施人数」は「検査実施件数」の間違いですよね。

「検査実施人数」の方も、「（注）医療機関が保険適用で行った検査は含まれていない」を太字にするか赤字にして目立たせたほうが良いと思います。「陽性患者数 / 検査実施人数」を陽性率だと勘違いしてパニックになっている人が見受けられます。

**Comment by kaizumaki** [comment]
@atsushieno ご提案ありがとうございます。東京都からの依頼により、 #3957 にて積み上げ棒グラフとして実装することで、保険適用分の検査実施件数をわかりやすく表示するように変更いたしました。ご指摘ありがとうございました。こちらのissueはクローズさせていただきます。また何かお気づきの点ありましたらお寄せください。
