### ISSUE TITLE
[ruby] 都庁来庁者数グラフY軸のルビ対応

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3378]
**プルリクエストは`dev-ja-hira-ruby` ブランチに向けて作成してください。**

## 概要

「都庁来庁者数の推移」グラフの Y軸 のルビ対応をします。

![](https://user-images.githubusercontent.com/5207601/79246811-a541fe00-7eb4-11ea-9626-29a16a641f49.png)

グラフの軸に直接ルビを振るのは実装難度が高いので、漢字部分を注釈に逃してそちらにルビを振ります。

## 対応方法
- y軸の目盛りから単位を抜く
- 注釈に「単位：人」と記載する

ref: https://github.com/tokyo-metropolitan-gov/covid19/issues/3116#issuecomment-614511037

ルビの実装方法については、#3116 にまとめています。
こちらを確認の上、実装をお願いいたします。

疑問点があればこの issue 内でコメントください！

**Comment by khsacc** [comment]
対応してみますー
