### ISSUE TITLE
【Safari】帰国者・接触者電話相談センター相談件数の「推移/累積」を切り替えると、スクロールが一番上に戻ってしまう。

### ISSUE THREAD

**Issue by you0518** [tokyo-metropolitan-gov/covid19#338]
## 確認環境
- MacBook Pro (15-inch, 2018)
- Catalina 10.15.3
- Safari 13.0.5 (15608.5.11)

![image](https://user-images.githubusercontent.com/45566895/75869912-97c53d00-5e4d-11ea-8aa9-9962a4302b09.gif)

**Comment by task-k0414** [comment]
[ステージング環境](https://stg-covid19-tokyo.netlify.com)で若干戻りはするものの、
TOPまで戻るのは確認できませんでした。
レスポンシブが崩れるのが改善してますね

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32471740/75884266-da940e80-5e67-11ea-8800-d4f1d6be20bb.gif)


環境
- MacBook Pro (13-inch, 2017)
- Catalina 10.15.3
- Safari 13.0.5 (15608.5.11)

**Comment by ocws-gh** [comment]
私もstgブランチで確認しましたが、挙動が確認できませんでした。（本番ではもちろん指摘の内容は確認できました。）
ウィンドウ幅を縮めた際の動きもstgと本番では少し違うようでしたので、もしかしたらstg環境で何か（レイアウト調整など）をマージしたことで今回の挙動が正されたのかもしれません。

**Comment by you0518** [comment]
Safariをフルスクリーンにすると「帰国者・接触者電話相談センター相談件数」だけが折返され、その状態だとボタン切り替えでスクロールが発生するかと思います。

あくまで私の確認環境だけで起こるものでしたら申し訳ありません...

**Comment by ocws-gh** [comment]
もう一回見直したら、やっぱstgでも動きますね！一番上までではないですが、task-k0414 さんと同じ状態になりました！失礼しました！
私の調べたところによると、
「帰国者・接触者電話相談センター相談件数」に限らず、カードコンポーネントを一番下付近までスクロールしてボタントグルで切り替えると少し戻るという感じですね。

**Comment by madana-1** [comment]
こちらですが、現在グラフの高さが固定されていないため、トグルによって描画されるグラフが変わることで、カードコンポーネント全体の高さが変わってしまっていることが原因ではないかなと思います。
自分が出させていただいたp-rで、グラフの高さを固定するように修正を行ったため、こちらのIssueも解決されるのではないかなと思います。（自分の環境では改善されているように思いますが、どなたか確認いただければと思います🙇‍♂️）
https://github.com/tokyo-metropolitan-gov/covid19/pull/407
