### ISSUE TITLE
ＰｏｗｅｒＢＩでグラフを連動させて表示させませんか

### ISSUE THREAD

**Issue by skyrise1308** [tokyo-metropolitan-gov/covid19#3383]
## 改善詳細 / Details of Improvement
- xxxx(できるだけ簡潔に/as concise as possible)
マイクロソフトのＰｏｗｅｒＢＩを使って、複数のグラフを連動させて、ドリルダウンなどの分析も簡単にできるようにしませんか。
マイクロソフトのアカウントを払い出してもらえれば、私が作成してＵＰします。
![tokyo_covid19_1](https://user-images.githubusercontent.com/19974588/79453643-eb1dd400-8024-11ea-9b41-51b49c6b75c4.jpg)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@skyrise1308 ご提案ありがとうございます。こちらの件ですが、東京都に確認しましたところ「マイクロソフトのアカウントを払い出し」が難しいとのことです。たいへん恐縮ですがクローズといたします。
