### ISSUE TITLE
トップページ内容の微変更

### ISSUE THREAD

**Issue by raamenzurururu** [tokyo-metropolitan-gov/covid19#3389]
## 改善詳細 / Details of Improvement
「新型コロナウイルス感染症**対策**サイト」と素晴らしいタイトルがあるのに
トップページの内容が「検査陽性者の状況」や「陽性患者数」などのグラフだけだと
タイトルと内容が一致していないように感じたので、
トップページには「手洗いでコロナウイルスを防げること」や「マスクの使用を促す」などの**対策**についても表示されている方がわかりやすいのではと感じた。

## 期待する見せ方・挙動 / Expected behavior
トップページの訴求ポイントに「手洗い」や「マスク使用を促す」など対策を含めた内容を加える。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@raamenzurururu ご提案ありがとうございます。こちらのissueについて都に確認いたしました。当サイトは「データを事実ベースで伝える」というコンセプトがあります。まず現状を客観的なデータで把握してもらうことを目的としているため、トップページにグラフを配置する設計としています。コンテンツについては状況に応じて追加していく予定です。ですので、こちらのissueはクローズさせていただければと思います。ご理解いただきますようお願いいたします。
