### ISSUE TITLE
群馬県公式サイトへの移行対応

### ISSUE THREAD

**Issue by y2naranja** [tokyo-metropolitan-gov/covid19#3390]
## 改善詳細 / Details of Improvement
- FORKED_SITES.mdの群馬県のサイトが4/7付で群馬県公式に移行されているため、FORKED_SITES.mdの変更が必要。
-- 旧（個人） https://stopcovid19-gunma.netlify.com/
-- 新（県公式） http://stopcovid19.pref.gunma.jp/

## スクリーンショット / Screenshot

旧
![Screenshot_20200416-215707-picsay](https://user-images.githubusercontent.com/912713/79459445-3f798180-802e-11ea-975f-96e698ba58ee.jpg)
新
![Screenshot_20200416-215801-picsay](https://user-images.githubusercontent.com/912713/79459477-4d2f0700-802e-11ea-8f39-c892e274f064.jpg)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kebhr** [comment]
どなたも対応されていないようなので、着手します。
