### ISSUE TITLE
【機能提案】陽性患者数と一緒に退院数も日毎で可視化する。

### ISSUE THREAD

**Issue by ritvik1512** [tokyo-metropolitan-gov/covid19#340]
新しいグラフまたは同じ感染者数グラフで色分けで表示することができます。

退院数の公開データ：[厚労省最新情報](https://www.mhlw.go.jp/stf/newpage_09925.html)

**Comment by TakehiroTada** [comment]
こちら，よろしければ是非対応させて頂きたいのですが
- 新しいグラフ
- 同じ感染者グラフ内

何方がよろしいでしょうか？

**Comment by ritvik1512** [comment]
ありがとうございます！個人的に同じ感染者グラフ内で表示するのが簡潔で陽性数にも比較しやすいだと思います。
若しくは別のやり方であればそちらも聞かせて頂ければと嬉しいです。

よろしくお願いします。

**Comment by mikkame** [comment]
すみません
着手については一旦止めていただけますでしょうか

**Comment by TakehiroTada** [comment]
@mikkame 
方針が固まっていないので、未着手状態です。よろしくお願いします
