### ISSUE TITLE
「お子様をお持ちの皆様へ」ページ内「学びの支援サイト」に説明文を追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3405]
「お子様をお持ちの皆様へ」ページ内の「学びの支援サイト」の項目に、以下の説明文の追加をお願いします。

![スクリーンショット 2020-04-17 15 02 01](https://user-images.githubusercontent.com/14883063/79537262-dbea6500-80bc-11ea-85c1-dcb6095f757d.png)

追加するテキスト
```
・臨時休業期間における子供たちの学びを支援する様々なウェブサイトを紹介しています。
・学習の基本的な内容を身に付けられる「東京・ベーシック・ドリル」や動画教材等があります。
```

**Comment by khsacc** [comment]
着手します
