### ISSUE TITLE
「陽性患者の属性」表において、公表日に使用される日付の処理がおかしい

### ISSUE THREAD

**Issue by y-chan** [tokyo-metropolitan-gov/covid19#3422]
## 起こっている問題 / The Problem
- 「陽性患者の属性」表において、jsonから日付を正しく取得できなかった場合に、「不明」となるべきだが、「Invalid Date」になってしまっている。
- dayjsが日付を抽出するのに失敗した場合にnullではなく「Invalid Date」が返されていることにより起きている。

## 関連する issue / Related Issues
https://github.com/tokyo-metropolitan-gov/covid19/pull/3304#issuecomment-613881147

## スクリーンショット / Screenshot

※ダミーデータを代入した際の挙動です。
![image](https://user-images.githubusercontent.com/34832037/79312723-46bf6300-7f3a-11ea-8b9a-8096ec2a5741.png)

## 期待する見せ方・挙動 / Expected Behavior
- 日付取得に失敗した際は「不明」と表記するよう修正する。

## 起こっている問題の再現手段 / Steps to Reproduce
1. data.json内の"patients"に以下のようなダミーデータを挿入する。
```
{
    "リリース日": null,
    "居住地": null,
    "年代": "10代",
    "性別": "男性",
    "退院": null,
    "date": null
}
```
2. ローカルで環境を立ち上げ、「陽性患者の属性」表を見る

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by iamkun** [comment]
Yes, Day.js treats dayjs(null) as an invalid input.
https://day.js.org/docs/en/parse/now

**Comment by mcdmaster** [comment]
FYI
こっちにも打診しています iamkun/dayjs#874

**Comment by y-chan** [comment]
一旦こちら側で修正する形にします。
dayjs側のの動作に関しては @mcdmaster さんにお任せしますね。

**Comment by mcdmaster** [comment]
@y-chan りょうかいです。ご対応ありがとうございます
