### ISSUE TITLE
[/flow] 追従時のメニューの色

### ISSUE THREAD

**Issue by khsacc** [tokyo-metropolitan-gov/covid19#3423]
## 改善詳細 / Details of Improvement
- 追従した際に、メニューの色も緑色で塗られるようにしたほうが、現在どの項目を見ているのかが明らかになりよいのではないかと思いました。

### cf.
- #3315 
- #3348 

### 現在のデザイン
![現在のデザイン](https://user-images.githubusercontent.com/49582774/79548187-02fe6200-80d0-11ea-90b7-40160c6b814b.png)
### 改善提案
![改善提案](https://user-images.githubusercontent.com/49582774/79547925-9f743480-80cf-11ea-8bb2-5fbfb8e09740.png)

## 期待する見せ方・挙動 / Expected behavior
↑の通り

## 動作環境・ブラウザ / Environment
すべて

## 備考
- デザインを担当された @forestgtree さんにぜひご意見をいただきたいです。
- 上記のスクリーンショットの内容であれば、PRを出せる準備をしてありますが、 #3348 の中で行っていただいても大丈夫です。

**Comment by forestgtree** [comment]
@khsacc ありがとうございます！
ご提案いただいた改善内容で問題ないと思います！
