### ISSUE TITLE
[/flow] IE11の表示不具合（右側が切れている＆イラストsvgがhover時に消える）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3424]
## 起こっている問題 / The Problem
- 新flowページがIE11で表示した時に右側がウィンドウからはみでています。
- ウィンドウ幅が広いときに起きる現象のようです。
![キャプチャ](https://user-images.githubusercontent.com/14883063/79551338-7a35f500-80d4-11ea-9268-d5c6a0709bf8.PNG)
- 上部の３連ナビゲーション内のイラストsvgがhover時に消えます。
https://infosign-inc.gyazo.com/25741634b534775cd9c384e4b55adf2f

## 期待する見せ方・挙動 / Expected Behavior
- IE11でも右側がはみださずに表示される。
- ３連ナビゲーション内のイラストsvgがhover時には白線で表示される。

新flowページは、 #3315 #3348 #3415 でhotfixにて4/17にリリースされました。

**Comment by macropygia** [comment]
担当します。

@kaizumaki flowのリリースが急ぎだったため、一旦積み残し（本件やPRで指摘されているi18n対応準備、その他現時点で未出の細かい修正等）を期間を区切って当方が回収する形にした方が面倒がなさそうですが、いかがでしょうか。

**Comment by kaizumaki** [comment]
ありがとうございます！ @macropygia さんのほうで回収していただいて大丈夫です。よろしくお願いします 🙇‍♀️

**Comment by macropygia** [comment]
@kaizumaki 承知しました。段取りとしては以下の想定ですがいかがでしょうか。

- 積み残し対応専用のissueを作成
- 19日までに出てきた課題のうち20日一杯までに対応可能なものをまとめて作業
- リリースの都合で個別のissueに切り分けた方がいいものは分かる方に判断していただいて都度外に出す
- PRは #3424 を引き続き使用 or 新規に用意

**Comment by kaizumaki** [comment]
@macropygia リリースは急ぐものと急がないものとがありそうなので、そこを切り分けていくというのでいいと思います。例えばこちらのissueは都からのオーダーなので、やや急ぎです。

**Comment by macropygia** [comment]
@kaizumaki なるほど、混乱しそうですが並列で進めてみます。因みに本issueのPRはどういう形で出すべきでしょうか。

**Comment by kaizumaki** [comment]
@macropygia ありがとうございます。こちらのissueについては通常PRで大丈夫です。hotfixにはしないつもりでいます。

**Comment by macropygia** [comment]
>新flowページがIE11で表示した時に右側がウィンドウからはみでています。

@kaizumaki この件は共通レイアウトでの対処が必要な事案と思われるため、別issueが適切かと存じます。

![image](https://user-images.githubusercontent.com/3162324/79578695-86847700-8101-11ea-8dc5-4f040b3c4455.png)

※因みに最新のお知らせのテキストを長くするとトップでも発生します

![image](https://user-images.githubusercontent.com/3162324/79579344-6dc89100-8102-11ea-8b47-d13b9c9e142d.png)

**Comment by kaizumaki** [comment]
@macropygia 調査ありがとうございます。IE11でのレイアウト崩れはflowのページだけの問題ではないのですね。それでしたら、別issueにしますね。
