### ISSUE TITLE
[/print/flow] 新UIの印刷対応

### ISSUE THREAD

**Issue by khsacc** [tokyo-metropolitan-gov/covid19#3425]
## 改善詳細 / Details of Improvement
- 印刷ページについても、新しいUI（ #3315  ）に対応してデザインの更新を行ったほうがよいかと思っています。

## 期待する見せ方・挙動 / Expected behavior
- 新しいUIの趣旨を汲み取った印刷用レイアウトデザインを制作し、実装する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

## 備考
- これまで、印刷用ページ /print/flow/ については以下の修正が行われていると認識しており、これらで改善された点については、デザインを変更しても破壊されないよう配慮するべきと考えます。
 - 印刷用の別ページを用意する。その際、最新情報はwebを見るようにという旨の注意書きを附記 #401 
 - 多言語対応 #1270
 - 日本語であればA4一枚におさまる #2718

**Comment by khsacc** [comment]
運営側で、印刷用レイアウトデザインの検討はなされているかを教えていただきたいです。今回のUIであれば、印刷用レイアウトをある程度別個に制作する必要がある気がしています。
もしレイアウトがない場合、運営のデザイナーさんが制作されますでしょうか？ それともそれを含めて本issueで対応してよいという感じになるでしょうか？

**Comment by kaizumaki** [comment]
いままでflowページの印刷対応はコントリビューターさんの間でやっていただいています。最初のsvgバージョンは、ページがほどなくコーディングされましたので、そのときに入れ替えとなりました。
基本的に、印刷用に別コンポーネントを設けるということはしません。デザイナーの負担になるという点もありますが、内容が現状に合わせて細かく修正が入りますので、サイトのページと印刷用のページを二重に修正する手間を省くため、何より修正漏れ・修正ミスが起こるのを防ぐためでもあります。
できるかぎり、印刷用cssでご対応いただけたらと思います。印刷用レイアウトは、ページの意図が反映されていることが望ましいです（都と運営側で練りに練ったレイアウトであるため、できればそのままでお願いしたいです）。

**Comment by nichesuch** [comment]
#3447 で対応されるとのことなので、assignedかclosed
にしておいていただけますか？

**Comment by macropygia** [comment]
#3447 における関連作業は `pages/print/flow.vue` の参照先を `components/flow/FlowPc.vue` から `pages/flow.vue` に変更するだけですので、印刷用の最適化は行いません。
仮に `pages/print/flow.vue` に変更を加えるのであれば、本issueで進行し #3460 のマージ後にPRしていただく段取りになるかと存じます。

**Comment by nichesuch** [comment]
失礼しました。では継続でお願いします。

**Comment by khsacc** [comment]
issueを立てた者です、遅くなってすみません。
本issueを立てた意図としては、
1. デザインを変更するにあたって、印刷用レイアウトについてはどの程度考慮されているのかを確認したい
2. 印刷用レイアウトそのものの検討をしたい
という2つがありました。

あまりレイアウトの変更は望ましくないということですが、「印刷用ページ」を設ける以上
は「印刷したときに不自然ではない程度の対応」は求められると私は考えます。いずれにせよ、一通り対応が終わってから状況を見て検討するということには変わりはないと思います。

**Comment by macropygia** [comment]
積み残し対応が完了し特に問題もないようですので、本issue着手可能かと存じます。念のためお知らせしておきます。

**Comment by khsacc** [comment]
お疲れさまです。お知らせありがとうございます。
他に対応する方がいらっしゃらなければ少し考えてみます（少し日にちかかると思います、すみません）。

**Comment by kaizumaki** [comment]
当サイトの相談フローへのナビゲーションは現在、東京都福祉保健局のページへのリンクとなっています。実際にflow.vueの中身も削除対応しましたので、関連するこちらのissueもクローズといたします。
