### ISSUE TITLE
[/flow] 4/17版リリース時積み残し対応

### ISSUE THREAD

**Issue by macropygia** [tokyo-metropolitan-gov/covid19#3447]
## 改善詳細 / Details of Improvement

- スケジュールの制約による #3315 #3348 における積み残し・チェック漏れを処理する
- 4/19夜頃までに洗い出せた軽微な修正・調整を一括して扱う

### 内訳

- アンカーリンクボタンのカレント表示の不具合修正
    - https://github.com/tokyo-metropolitan-gov/covid19/pull/3348#issuecomment-615093843
- i18n対応準備
    - https://github.com/tokyo-metropolitan-gov/covid19/pull/3348#pullrequestreview-395268312
- カレント表示の外観調整
    - #3423
- マークアップ修正
    - 相談窓口の案内下段は「平日（夜間）～土日祝 終日」までがdt要素
        - コロンの意味が上段と下段で異なる（情報設計の瑕疵）
- 印刷版の参照先を `/pages/flow.vue` に変更
- 不要コンポーネント削除
- 画像整理
- SVGの設置方法をインラインSVGに統一

### 別途進行（先行）

- #3424 IE11対応東京都リクエスト分

### 別途進行（後続）

- #3425 印刷対応
- #3467 i18n/ルビタグ対応

## 動作環境・ブラウザ / Environment

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

---

- 当方が担当します
- ~~不具合を発見した場合は単独のissueを立てる前に本issueでお知らせいただけますと幸いです~~
- PRに移りました（4/19 20:16）

**Comment by khsacc** [comment]
積み残しを対応してくださるとのことで、#3423 もちょっとしたCSSの改修ですので、一緒に対応いただけますでしょうか…？

**Comment by macropygia** [comment]
@kaizumaki 本issueの範囲ではありませんが、受診相談窓口ブロックの窓口案内において上段と下段で文章構成が異なっており混乱を招きそうです（特にコロンの使い方）。

- 上段
    - 平日（日中）: 各保健所の電話番号は福祉保健局HPに掲載しています
- 下段
    - 平日（夜間）：午後5時から翌朝午前9時/土日祝 終日 03-5320-4592
- 構成比較
    - [曜日（時間帯）] : [連絡先]
    - [曜日（時間帯）] : [時間帯詳細] / [曜日] [時間帯] [連絡先]

仮に上段に寄せるとすると、下記のようにすべきかと存じます。

- 平日（日中）: 各保健所の電話番号は福祉保健局HPに掲載しています
- 平日（午後5時から翌朝午前9時）/ 土日祝（終日）: 03-5320-4592

また、相変わらず平日日中の連絡先が保健所であることを認識するために読み手の推測が必要な文章のままです。

- 福祉保健局のチャートの内容
    - 「平日（日中）: 各保健所 ※電話番号は福祉保健局HPに掲載しています」
        - 連絡先が保健所であることが明確に記述されており、補足として電話番号の案内がある
- 現行本番の文言（旧本番も同様）
    - 「平日（日中）: 各保健所の電話番号は福祉保健局HPに掲載しています」
        - 保健所の電話番号が案内されていることから連絡先が保健所であることを読み手側が推測して補完する必要がある
        - 下段の電話番号だけが強調されているためそちらに視線が吸われる

**Comment by macropygia** [comment]
@kaizumaki `/components/flow` 以下の旧flow用コンポーネント、および `/static/flow` 以下の使用していない画像は削除しても問題ないでしょうか。

**Comment by kaizumaki** [comment]
@macropygia 不要なコンポーネント、使用していない画像は削除してOKです。よろしくお願いします。
