### ISSUE TITLE
ページ遷移時に先頭から表示されない

### ISSUE THREAD

**Issue by kai-ono** [tokyo-metropolitan-gov/covid19#345]
ページ下までスクロールを行ってから遷移すると、遷移後のページもスクロールされた状態で遷移しますので、scrollBehaviorの調整が必要だと思われます。

**Comment by shun91** [comment]
突然失礼します、リポジトリ拝見していたら気づいたのでコメントさせてくださいmm

こちらの現象ですが、https://github.com/tokyo-metropolitan-gov/covid19/pull/346 で改善されているようです。

**Comment by munierujp** [comment]
どちらかというと、`.mainContainer`の`height`が`100vh`になっていることによってスクロール位置がトップになっていない、ということのようですね。

**Comment by kaizumaki** [comment]
みなさま、ご指摘ありがとうございます！とりあえず #346 のプルリクのマージ待ちです。またお気づきの点ありましたらissueでお願いします！
