### ISSUE TITLE
「検査実施件数」グラフの注釈の追加・修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3456]
「検査実施件数」グラフに以下の注釈の追加・修正・移動をお願いします。

- 画像の「注釈１」の位置
```
（注）日々の速報値（医療機関が保険適用で行った検査は含まない）は、毎日更新
（注）医療機関が保険適用で行った検査件数を含む検査実施件数は、毎週金曜日に前週木曜日から当該週水曜日までの日々の保険適用分の件数を反映して更新
（注）医療機関が保険適用で行った検査については、４月１５日分までを計上
```

- 画像の「注釈２」の位置
```
（注）同一の対象者について複数の検体を検査する場合あり
（注）速報値として公開するものであり、後日確定データとして修正される場合あり
```
※「４月１５日」の部分は近いうちに変数化する予定です。こちらのissueではベタ書きでOKです。
![注釈追加修正](https://user-images.githubusercontent.com/14883063/79618647-9aea6300-8145-11ea-928b-ca7a50cf00ef.jpg)

**Comment by kzhrk** [comment]
こちら着手してもよいでしょうか。

**Comment by kaizumaki** [comment]
@kzhrk お願いします！
