### ISSUE TITLE
[ruby] /flow のルビタグ対応

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#3467]
## 改善詳細 / Details of Improvement
- #3348 で全面的に改修された`/flow`をルビタグに対応させる

## 期待する見せ方・挙動 / Expected behavior
- ふりがなが括弧書きではなくルビタグを用いて表示される

**Comment by kebhr** [comment]
着手します

**Comment by MaySoMusician** [comment]
Close per #3468 merged
