### ISSUE TITLE
医療崩壊を理解するための致死率のグラフの追加

### ISSUE THREAD

**Issue by supertask** [tokyo-metropolitan-gov/covid19#3469]
## 改善詳細 / Details of Improvement
日本が他国よりも致死率が低く，大丈夫だと思っている人は多いと私は考えています．そのため，人々の行動変異を起こす方法の一つとして，医療崩壊が起こっていることを可視化する必要があると個人的に思っています．可能でしょうか？

可視化方法はシンプルに日毎の致死率がどのくらい増加しているのかを見れば，その傾向がわかると思います．例えば，ヨーロッパであれば，致死率はそれぞれイタリアが13.19%, ドイツが3.08% という状態になっており，医療崩壊の有無をある程度つかむことができます（[参考サイト](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)）．

<img width="753" alt="スクリーンショット 2020-04-18 15 55 31" src="https://user-images.githubusercontent.com/5733604/79630717-a9a93800-818e-11ea-8da3-2a5cfd53bd6b.png">
<img width="663" alt="スクリーンショット 2020-04-18 16 06 07" src="https://user-images.githubusercontent.com/5733604/79630715-a746de00-818e-11ea-8d23-ececa345ef91.png">

ドイツは1月中旬から[医療方面への財政支援などにより，医療崩壊を防げています](https://news.tbs.co.jp/newsi_sp/seikatsu-bousai/archive/20200408_01.html
) が，イタリアはご存知の通り医療崩壊しており，今も致死率は増加しています．<- 毎日致死率を見ています．

このままロックダウンしないまま放っておくと日本も確実に医療崩壊が起こり，ドイツなど一部を除いたヨーロッパ諸国のように致死率が増加すると考えられます（[参考](https://news.tbs.co.jp/newseye/tbs_newseye3956410.html)）．

そのため，致死率の増加傾向の可視化が医療崩壊してるか否かの基準，そして崩壊後ロックダウンを仮にした際にどのくらい崩壊していくのかを把握するのに，必要だと個人的に考えています．どうでしょうか？

**Comment by hanyo** [comment]
医療崩壊の度合いと同様に、物質の状況も把握できると良いかなと
思います。

**Comment by kaizumaki** [comment]
@supertask ご提案ありがとうございます。こちらのissueについて都に確認いたしました。一般的に割合を可視化するには比較対象がないと意味をなさないと考えます。そして、医療崩壊と致死率に関係性を見出すのは難しいと思います。ですので、こちらの提案を採用するのは難しいです。

**Comment by kaizumaki** [comment]
都から回答がありましたので、こちらのissueはクローズさせていただきます。
