### ISSUE TITLE
「検査陽性者の状況」チャートおよび「陽性患者の属性」表の注釈の追加・修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3470]
「検査陽性者の状況」「陽性患者の属性」の注釈を以下のように追加・修正をお願いします。
「検査陽性者の状況」については、取得dataが別管理となるため、「更新日時」の指定の変更もお願いします。さらにチャート内の注意書き（カッコ書き）の追加もお願いします。

### 「検査陽性者の状況」注釈
現在の注釈２つの下に以下を追加
```
（注）退院者数の把握には一定の期間を要しており、確認次第数値を更新している
```

### 「検査陽性者の状況」 更新日時
https://github.com/tokyo-metropolitan-gov/covid19/blob/b224318be64f824a20f38901bd0ff2dd2c92c955/components/cards/ConfirmedCasesDetailsCard.vue#L6
こちらを以下のスクリーンショットで示した箇所を割り当てるように修正してください。
![更新日時](https://user-images.githubusercontent.com/14883063/79631207-78cb0200-8192-11ea-9f32-18f7dc3984eb.png)

※ `data.json` は、こちらの実装と同時のタイミングでリリースします。

### 「検査陽性者の状況」チャート内カッコ書き
「退院」のテキストの下にカッコ書きで以下を追加
``` 
（療養期間経過を含む）
```

### 「陽性患者の属性」注記
下部の注記を以下に変更
```
※退院は、保健所から報告があり、確認ができているものを反映
※死亡退院を含む
```

**Comment by kebhr** [comment]
着手します
