### ISSUE TITLE
チャート右下のアイコンが何を挙動するのか分かりづらい

### ISSUE THREAD

**Issue by skm-isy** [tokyo-metropolitan-gov/covid19#3472]
## 改善詳細 / Details of Improvement
- 各チャートの右下に表示されるアイコンが何を挙動するのか一意に分かりづらい。
  - 個人的には、データをcsv形式等でエクスポートする挙動なのかと期待した。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/53833076/79632239-175a6180-8199-11ea-8b5e-4c847298a3a2.png)
![image](https://user-images.githubusercontent.com/53833076/79632722-21319400-819c-11ea-9f96-6f905375aebe.png)

## 期待する見せ方・挙動 / Expected behavior
A、B案を示す
全て対応しても良いし、それぞれ対応しても良さそう。

- A案 : ツールチップで、マウスオーバーした際に詳細(*)を説明するようにする。
  - 詳細(*)の例 : 「情報をシェアする」等
- B案 : エクスポートを期待するアイコンなので、アイコンを変える。
  - ![image](https://user-images.githubusercontent.com/53833076/79632583-3fe35b00-819b-11ea-9bc2-aaf0a2de5f64.png)
  - [Material Design Icons](https://materialdesignicons.com/)

## 動作環境・ブラウザ / Environment
- macOS / iOS / Android
- Chrome

**Comment by telumo** [comment]
私がやります！

**Comment by forestgtree** [comment]
@skm-isy ご提案ありがとうございます！
@telumo 素早い着手、助かります！

ご提案いただいたシェアアイコンについてですが
恐らく、Androidユーザーには見慣れているシェアアイコンなのだと思います。
私などは、現行のアイコンはiOSのシェアアイコンとして見慣れている状況です。

また、現行のアイコンが実装してから大分経ちますので
当サイトにおけるアイコンとしては、定着しつつあるのではないかと思っています。

急な変更を行うよりは、今回はツールチップまでの対応として
今後も議論していきたいと思いますがいかがでしょうか？

ツールチップの対応については
Vuetify での対応など参考にしていただけると助かります。
https://vuetifyjs.com/ja/components/tooltips/

**Comment by telumo** [comment]
@forestgtree 了解しました。
それでは、上記のA案「ツールチップで、マウスオーバーした際に詳細(*)を説明するようにする。」までを対応いたします。

**Comment by skm-isy** [comment]
@forestgtree

> また、現行のアイコンが実装されてから大分経ちますので
> 当サイトにおけるアイコンとしては、定着しつつあるのではないかと思っています。
> 
> 急な変更を行うよりは、今回はツールチップまでの対応として
> 今後も議論していきたいと思いますがいかがでしょうか？

御確認ありがとうございます！
異論ございません！

@telumo 
上記対応にて進行の程何卒宜しくお願いします。  🙇
