### ISSUE TITLE
「最新のお知らせ」枠を作る

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#348]
![トップのお知らせ jp](https://user-images.githubusercontent.com/61729733/75874739-b7606380-5e55-11ea-9cdc-61f0a3905478.png)

トップにあるお知らせ枠について。
このお知らせ枠を2つ並べて、さらに枠で囲み「最新のお知らせ」というタイトルをつけたエリアを作っていただきたいです。

**Comment by takanakahiko** [comment]
やります〜

**Comment by takanakahiko** [comment]
Figma の変更がされていないようですが，先に実装します．
