### ISSUE TITLE
ja.jsonの自動生成

### ISSUE THREAD

**Issue by y-chan** [tokyo-metropolitan-gov/covid19#3482]
## 改善詳細 / Details of Improvement
- PRマージ時などに、ja.jsonに記載されていない文章/語句がある場合は追加を、またja.jsonに記載されているが既にvueファイル内などで削除済みの文章/語句がある場合は削除をするスクリプトを作成することで、翻訳に関しての作業を簡略化させる。
- vue内の記載と、日本語訳に差がある場合(`menu/対策サイト`が`対策サイト`など)は個別に修正するか、PRなどの段階で個別に追加しておく運用にすることで、スクリプトを併用可能とする

## 期待する見せ方・挙動 / Expected behavior
- PRマージ時などにja.jsonを自動で生成させる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by y-chan** [comment]
現状、地域版での運用において似たPythonスクリプトを使用しており、それを東京都版向けに改良してPRしたいと思っています。
ただ、 https://github.com/tokyo-metropolitan-gov/covid19/issues/2790#issuecomment-608983799 でPHPのプログラムはTS or JSで置き換える等、このサイト内で使われるプログラムを一定の言語に統一する動きがあるように感じます。
Pythonでのスクリプトに問題がないのであれば、改良次第PRしたいと思っていますが、そうでない場合は別の方にプログラムを書いていただくか、そもそもこの改善提案が不要である場合はIssueクローズを考えています。
運用の方の意見をお伺いしたいです。

**Comment by mcdmaster** [comment]
コメントの主です。ちょっと本題から外れますけど、どうかご容赦を。

PHP のコードについては、他のプロジェクトでもあったのですけど、他にその言語を扱える人がいないのでメンテナンスが叶わないという属人化の問題を懸念しました。
ですので、PHP については TS/JS への書き換えを提案した経緯があります。

一方、py だと今後のノウハウ（を持つエキスパート）の調達に差し障りがないという観測が可能であれば、私は混在もアリだと思っています。
あるいは、本プロジェクトのような形でオープンに開発者を募れるようなら、マルチランゲージでも維持は可能かもしれませんね

**Comment by y-chan** [comment]
なるほど、そういうことだったのですね。

ogp builderやogp Invalidatorに関してはPythonで書かれていますので、今後もPythonは使われ続けるのかなと個人的には思っています。

ただ、PHPを取りやめる意見を見かけたため、現状どのような方向性なのかを知りたい意味も含め、Issueを立ててみました。

とりあえずはPythonでスクリプトを書く方針で行きたいと思います。

**Comment by mcdmaster** [comment]
#3272 #3273 あたりと関係があったりしますでしょうか？

**Comment by y-chan** [comment]
おっしゃる通りです。
また、地域版の翻訳スクリプトにおいて、東京都版で含み忘れた翻訳がこちら側に含まれることがあるので、それも解消したくてですね。
