### ISSUE TITLE
「検査実施件数」グラフ下部の注釈のフォントカラーが異なる

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3494]
## 起こっている問題 / The Problem
- 「検査実施件数」グラフ下部の注釈のフォントカラーが、他のものと異なっています。
- コンポーネントで指定しているcolorのスタイルが適用されておらず、vuetifyのデフォルトになっているようです。

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-19 10 09 58](https://user-images.githubusercontent.com/14883063/79676991-0bb57c00-8227-11ea-90e9-338d55ee0f49.png)

## 期待する見せ方・挙動 / Expected Behavior
- 他の注釈のフォントカラー（$gray-3）と同じ指定になる。

**Comment by Aqua-ix** [comment]
こちら対応します
