### ISSUE TITLE
[ruby] #3461 取り込み分へのルビタグ対応

### ISSUE THREAD

**Issue by kebhr** [tokyo-metropolitan-gov/covid19#3502]
## 改善詳細 / Details of Improvement
- #3461 によって`development`から`dev-ja-hira-ruby`に取り込まれた・変更された部分の`<t-i18n>`タグへの対応を行う

## 期待する見せ方・挙動 / Expected behavior
- ルビが括弧書きではなくrubyタグによりマークアップされる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kebhr** [comment]
対応します

**Comment by MaySoMusician** [comment]
Close as per #3503 merged
