### ISSUE TITLE
全国版をFORKED_SITES.mdに追加する

### ISSUE THREAD

**Issue by mm0202** [tokyo-metropolitan-gov/covid19#3507]
## 改善詳細 / Details of Improvement
- 全国版を作成したので、派生サイト一覧に追加をお願いしたいです。
- 都道府県名: 全国
- 公開サイト: https://covid19.wlaboratory.com
- 運営者: 個人
- プロジェクト: https://github.com/mm0202/covid19-jp

## スクリーンショット / Screenshot
[![Image from Gyazo](https://i.gyazo.com/1a9e60aba048d10de95d29287b4bfbbf.png)](https://gyazo.com/1a9e60aba048d10de95d29287b4bfbbf)

**Comment by mm0202** [comment]
すみません、公開サイトが403エラーで表示できていなかったようです。
リンク先サイトを修正しました。

**Comment by y2naranja** [comment]
こちらは公式のものではないですよね？
見た人が誤解する可能性があるので、どこか目立つところに、非公式である旨と、問い合わせ先を記載しないと、保健所や厚労省などに問い合わせが行くことにならないでしょうか。

**Comment by mm0202** [comment]
ご指摘ありがとうございます。

調整しましたので、確認していただけると助かります。
調整内容は以下の３つです。

    favicon調整 mm0202/covid19-jp#10
    非公式表記の追加 mm0202/covid19-jp#12
    連絡先追加 mm0202/covid19-jp#14

よろしくお願いします。
