### ISSUE TITLE
各国語のページで日本語のまま表示されている

### ISSUE THREAD

**Issue by dg4101** [tokyo-metropolitan-gov/covid19#3512]
## 起こっている問題 / The Problem
- 各国語のページで日本語のまま表示されている文言がある
- #3198, #3315 などの変更で新たに追加された翻訳キーの翻訳がされていないか、反映されていないようです。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/1219688/79689303-2baf6480-8254-11ea-9179-e780e14ccd8c.png)

![image](https://user-images.githubusercontent.com/1219688/79689309-35d16300-8254-11ea-82f0-913ada101d2a.png)
![image](https://user-images.githubusercontent.com/1219688/79689311-38cc5380-8254-11ea-821a-85df96ac4d6b.png)

## 注釈
-  上のスクリーンショットは例で、他いくつかの箇所に同じような現象が見られます。
- すでに変更の予定をされていると思いますが、Issueを上げることにより可視化できると考えあげました。

**Comment by whisky-shusuky** [comment]
`/flow`は他のissueで対応されるようですが、トップページのみ日本語のままのものが残っていたので対応しました！
