### ISSUE TITLE
tool/convert.php内の正規表現について

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#3528]
## 起こっている問題 / The Problem
tool/convert.php の20行目のfunction formatDate(string $date) :string
における正規表現にセキュリティリスクがあります。

22行目
`if (preg_match('#(\d+/\d+/\d+)/ (\d+:\d+)#', $date, $matches)) `

このパターンマッチでは数字を何桁でも入れられるという問題があります。
桁数を絞らない理由はなにかあるのでしょうか？

例えば
`if (preg_match('#(\d{1,4}/\d{1,2}/\d{1,2})/ (\d{1,2}:\d{1,2})#', $date, $matches)) `
としてはだめなのでしょうか？

## 動作環境・ブラウザ / Environment
制限なし

**Comment by kaizumaki** [comment]
ご提案ありがとうございます。こちらのスクリプトは現在使用していません。古いスクリプトをそのままにしてしまっていました。申し訳ありません。スクリプトファイルの削除など検討いたします。

**Comment by kaizumaki** [comment]
@goki90210 `tool/` 以下のスクリプトですが、長らく使用していないものを放置してしまっていたので、運営側で削除する対応といたしました。ご指摘ありがとうございました。

**Comment by goki90210** [comment]
承知しました。
