### ISSUE TITLE
サイドナビに「新型コロナウイルスの感染が判明した方へ」の外部リンクを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3529]
サイドナビに「新型コロナウイルスの感染が判明した方へ」の外部リンクを以下の内容で追加お願いします。

- テキスト：新型コロナウイルスの感染が判明した方へ
- リンク：https://www.fukushihoken.metro.tokyo.lg.jp/oshirase/corona_0401.html
- アイコン：「新型コロナウイルス感染症が心配なときに」と同じアイコン
- 位置：「新型コロナウイルス感染症が心配なときに」の下（ボーダーの上）
以下の画像の赤枠部分です。

![サイドナビ](https://user-images.githubusercontent.com/14883063/79710503-214aa480-8300-11ea-9a5e-ba52a8ed35f8.jpg)

**Comment by kebhr** [comment]
対応します
