### ISSUE TITLE
[/flow]「新型コロナウイルス感染症が心配なときに」ページ内テキスト修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3532]
flowページ（「新型コロナウイルス感染症が心配なときに」）のテキスト以下２点（合計３か所）修正をお願いします。

（１）新型コロナコールセンターの対応時間の変更
修正前：午前9時から午後9時（土日祝含む）
↓
修正後：午前9時から午後10時（土日祝含む）

![①コールセンター対応時間](https://user-images.githubusercontent.com/14883063/79733280-d21c6800-832f-11ea-8a21-11d2403e2e12.png)

（２）「陽性の場合」の変更
修正前：感染症指定医療機関等に入院となります
↓
修正後：感染症指定医療機関等への入院、又は宿泊施設等での療養となります

![②陽性の場合](https://user-images.githubusercontent.com/14883063/79733315-dba5d000-832f-11ea-8c30-374cb1ad8308.png)

**Comment by macropygia** [comment]
着手します。
