### ISSUE TITLE
陽性患者数を週別/曜日別に比較する

### ISSUE THREAD

**Issue by Tea-and-Coffee** [tokyo-metropolitan-gov/covid19#3545]
## 改善詳細 / Details of Improvement
- 陽性患者数（日別）を週別に比較し易くする。
- 陽性患者数（日別）を曜日別に比較し易くする。
    - 前週の同じ曜日と比べたときに、今週は増減したかを比較するのに活用したい。

## 期待する見せ方・挙動 / Expected behavior
- 曜日ごとに区切ったレーダーチャートを追加する。

<img width="619" alt="スクリーンショット 2020-04-21 12 46 08" src="https://user-images.githubusercontent.com/8828318/79823221-342baa80-83ce-11ea-809e-990fffab996c.png">
(Google スプレッドシートで作成)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hanyo** [comment]
累積データよりも、その週ベースのデータが欲しいです。
ご検討をお願いします。

**Comment by Tea-and-Coffee** [comment]
@hanyo 
ご指摘されている内容はよそらく https://github.com/tokyo-metropolitan-gov/covid19/issues/2170 の提案の方に、マッチしているのではないとか思われます。

**Comment by hanyo** [comment]
わかりました。
確認します。

**Comment by kaizumaki** [comment]
@Tea-and-Coffee ご提案ありがとうございます。こちらのissueについて都に確認いたしました。ご提案いただいたような可視化は、一般の方には直感的にわかりにくいと思われますので、採用するのは難しいです。ご理解いただきますようお願いいたします。

**Comment by Tea-and-Coffee** [comment]
@kaizumaki 
ご確認して頂き感謝いたします。このIssueはクローズします。
