### ISSUE TITLE
検査実績のサマリ グラフ表示

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#355]
検査実施日別状況
https://codeforjapan.sharepoint.com/:x:/r/sites/covid19/_layouts/15/Doc.aspx?sourcedoc=%7BBC63F13E-E6F7-4457-8623-198D4059B9E1%7D&file=%E6%A4%9C%E6%9F%BB%E5%AE%9F%E6%96%BD%E6%97%A5%E5%88%A5%E7%8A%B6%E6%B3%81.xlsx&action=default&mobileredirect=true

「資料シート」にある 実施日別状況 （サマリ）黄色い列のデータのグラフ化をお願いします。

各項目のデータソース及び計算式です。  
検体実施数：「入力シート」の 検査検体数の合計 
都内発生分：「入力シート」の（小計①）の合計 もしくは 疑い例検査＋接触者調査＋陰性確認 の合計 
疑い例検査：「入力シート」の 疑い例検査の合計 
接触者調査：「入力シート」の 接触者調査の合計 
陰性確認：「入力シート」の 陰性確認の合計 
その他：「入力シート」の （小計②）の合計 もしくはチャーター便＋クルーズ船＋陰性確認2の合計

**Comment by ocean3fish** [comment]
以下進めています。
・データ構造の整理
・用語の確認

**Comment by ocean3fish** [comment]
グラフ案：
・検体実施数
の内訳として以下の2系列のデータを積み上げた棒グラフ

・都内発生分
・その他

<img width="1440" alt="スクリーンショット 2020-03-05 1 28 50" src="https://user-images.githubusercontent.com/4206675/75905086-a597b400-5e87-11ea-84bc-0e617c0ecb6c.png">

**Comment by ocean3fish** [comment]
案：他の棒グラフと仕様を統一して、日別/累計の切り替えを可能にする
（累計の場合の表示）
<img width="1440" alt="スクリーンショット 2020-03-05 1 45 30" src="https://user-images.githubusercontent.com/4206675/75905256-e8598c00-5e87-11ea-8436-ae497f4242e2.png">

**Comment by NaoyaShimizzz** [comment]
・都内発生（疑い例・接触者調査）
・その他（チャーター便・クルーズ便）
としていただけますか

**Comment by kaizumaki** [comment]
@NaoyaShimizzz 了解です！

**Comment by kaizumaki** [comment]
いまこんな感じです。右上の数字はダミーです。右上の数字は何を表示すべきですか？
![スクリーンショット 2020-03-05 14 17 00](https://user-images.githubusercontent.com/14883063/75950281-1375c700-5eec-11ea-9f69-af0b1d26b5cf.png)
![スクリーンショット 2020-03-05 14 17 13](https://user-images.githubusercontent.com/14883063/75950290-196ba800-5eec-11ea-8210-8754a91f10bf.png)

**Comment by NaoyaShimizzz** [comment]
@kaizumaki ありがとうございます！検査実施数（都内＋その他の合計値）でお願いします！

**Comment by kaizumaki** [comment]
@NaoyaShimizzz こんな感じでどうですか？（文言がむずかしい。。）
![スクリーンショット 2020-03-05 15 14 12](https://user-images.githubusercontent.com/14883063/75953382-913dd080-5ef4-11ea-8790-1634b9cb397d.png)
![スクリーンショット 2020-03-05 15 17 08](https://user-images.githubusercontent.com/14883063/75953396-9733b180-5ef4-11ea-9750-7dd983b6c121.png)

**Comment by NaoyaShimizzz** [comment]
@kaizumaki ありがとうございます！こちらでお願いいたします！
