### ISSUE TITLE
ルートディレクトリ構成の変更

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#357]
現在ルートには
- Nuxtアプリのコードが入っているディレクトリ 11件
- GitHub用 `.github` `docs`
- Netlify用 `.netlify`
- test系 `test` `ui-test`
- その他 `tool`

合計 17ディレクトリが並列しています

Nuxt の [srcDir](https://ja.nuxtjs.org/api/configuration-srcdir/) を利用することで、Nuxtアプリに関わるディレクトリをひとまとめにできます

## 👍 メリット
- ルートのディレクトリ数が 7件になり簡潔になる
- srcDir で指定したディレクトリ内は、Nuxtアプリで必要なディレクトリだけが並列になる

## 👎 懸念
- 現在多くの Contribution があるためすぐの変更は危険
- 現ディレクトリ構成で慣れている方の混乱を招く

すぐに必要な行為ではありませんし、賛否両論もあると思われますが、書いてみました 🙇

**Comment by potato4d** [comment]
確かに srcDir を設定するメリットは大きいと思うので、折を見て行っていければよいかと思います。
具体的には

- Prettier / ESLint などを正しく導入する場合に glob を書きやすい

などですね。

あわせて不要な store/ や middleware/ ディレクトリの削除も行うと良さそうな気がするので、落ち着いたら進められればと！

**Comment by kaizumaki** [comment]
開発環境が落ち着いてきているので、こちらのissueは一旦クローズとします。
