### ISSUE TITLE
「死亡」と「退院」の値が逆のように見えます。

### ISSUE THREAD

**Issue by yhor1e** [tokyo-metropolitan-gov/covid19#3570]
## 起こっている問題 / The Problem
- 「死亡」と「退院」の値が逆のように見えます。

## スクリーンショット / Screenshot

![Screenshot_20200421-184009](https://user-images.githubusercontent.com/10266230/79851264-08291d00-8400-11ea-92a8-0aa852c4654d.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「死亡」と「退院」が正しい表示になること

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/cards/details-of-confirmed-cases/ へのアクセス

## 動作環境・ブラウザ / Environment
- Android
- Chrome

**Comment by kaizumaki** [comment]
@yhor1e ご報告ありがとうございます。現在、運営側で対応しております。

**Comment by kaizumaki** [comment]
表示が正常化いたしました。データの構造の変更による不具合でした。ご指摘ありがとうございました。こちらのissueはクローズさせていただきます。

**Comment by yhor1e** [comment]
ありがとうございました！！
