### ISSUE TITLE
検査実施数、2種類の積み上げバーチャートにした方がいいのではないかと…

### ISSUE THREAD

**Issue by kazu-kitamura** [tokyo-metropolitan-gov/covid19#3579]
個人的に、3月上旬からこういうチャート集（国内版 http://bit.ly/2W6PYC2 ／世界版 http://bit.ly/3b7seSy ）を垂れ流している者でして、このサイトはじめ、COVID-19周りのオープンデータやデータサイエンスには一定の関心を持っています。
そんな中、今日、拝見して思ったのが、検査実施数、注釈に記載があるように「衛生検査所（ですかえね？）実施分はほぼその日に」「でも民間医療機関実施分は翌週金曜に前週木曜からその週の水曜までを」計上されるみたいですね、たぶん、都の公表値として。
最近、「新規感染者数が高水準とは言え、少し減少しているのは検査を抑制しているからではないか？」という議論が一部であるようですが、そういった議論に影響しているかどうかわかりませんけど、そのような議論からするにこの公表タイミングが異なる両者（衛生検査所等都の機関でやっている検査数と、そこから遅れて積み上げられる民間の検査数）を区別なく見せるのは果たして、どうなんだろうかな、と。つまり、その週の金曜までは前週木曜からの数字は民間の数字が入っていない分、「少なく見える」面もあるでしょうから。
もっとも、民間の検査数が都の場合、どの程度なのかわかりませんが、厚労省のサイトのPDFを見る限りは増えているようですし、直近だと全体の1/4～1/3を占める日もあるようですしね。例えば色の違う積み上げバーチャートにして、「この期間はこの分（遅れて公表される民間検査分）の数字はまだ乗っていないから」というのが目で見てわかる（もちろん、注釈は入れてありますが、データを出す側はこういうの気を遣いますけど、見る側はあんまり読んではくれないでしょうから）ようにした方が、変なミスリードを招かないで済むのではないかなと思ったところでした。
当事者側でかかわっている人間ではないので、的を射ているかどうかわかりませんがご参考になれば…

**Comment by kaizumaki** [comment]
@kazu-kitamura ご提案ありがとうございます。#3957 にて、ご指摘いただいたように積み上げ棒グラフとして実装することで、保険適用分の検査実施件数をわかりやすく表示するように変更いたしました。こちらのissueはクローズさせていただきます。また何かお気づきの点ありましたらお寄せください。
