### ISSUE TITLE
[/flow] 新flowページの文章を翻訳キーとして登録

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3590]
## 作業内容
- `pages/flow.vue` が改稿されたので、新規文字列を `assets/locales/ja.json` に登録する
    - 具体的には `{{ $t('翻訳する文章') }}` となっている部分で「翻訳する文章」を `ja.json` に登録する
- 以下の5つは既に登録済みなので、新たに追加する必要はありません
    - `新型コロナウイルス感染症が心配なときに`
    - `新型コロナウイルス感染症にかかる相談窓口について`
    - `新型コロナコールセンター`
    - `電話のおかけ間違いが多くなっております。発信の際は今一度電話番号をお確かめの上、お間違えのないようお願いいたします。`
    - `詳細を見る（東京都福祉保健局）`

## その他
- 旧版で使用していた翻訳キーの除去は今回は不要です（別途作業issueを立てます）
- 他の言語のファイル（例: `en.json` ・ `ja-Hira.json`）についてはTransifexによって自動的に修正されるので編集せずにしておいてください。
- ご質問等ありましたらこちらでコメントお願いいたします！

**Comment by ryuckel** [comment]
私対応しますよ！

**Comment by MaySoMusician** [comment]
@ryuckel ありがとうございます！お願いします！
