### ISSUE TITLE
ESlint --fixの結果とリポジトリに登録されている内容に矛盾がある（改行コード）

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#3610]
## 起こっている問題 / The Problem
- ESlint をfixオプションで実行する(yarn lint:fix)と、改行コードがCR+LFからLFに変換され、リポジトリの登録内容と矛盾する。

## 期待する見せ方・挙動 / Expected Behavior
- yarn lint:fixで結果が変わらないこと

## 起こっている問題の再現手段 / Steps to Reproduce
1. yarn lint:fixを実行する。

## 動作環境・ブラウザ / Environment
- Windows 10（package.jsonはWindowsで実行できるよう一部修正しています。）

**Comment by Nekoya3** [comment]
git for Windowsの設定でリポジトリ上でLFで保存されていてもCR+LFに変換するという仕様がありますがそれが有効になっていませんか？

**Comment by munierujp** [comment]
FYI: [.editorconfig](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.editorconfig)では`end_of_line = lf`となっています。

**Comment by goki90210** [comment]
> git for Windowsの設定でリポジトリ上でLFで保存されていてもCR+LFに変換するという仕様

失礼しました。
Git for Windowsのインストールを初期設定のまますすめると
チェックアウトで改行はLF→CR+LF変換を行い、
コミットの際にLFに戻すようになっていました。
ありがとうございました。
