### ISSUE TITLE
「企業の皆様・はたらく皆様へ」の内容更新（2020/04/24）

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3641]
## 作業内容
- /workerページの内容の更新です。対象ファイルは  `pages/worker.vue` です。
- 作業元データは ~こちら~ (方針変更により混乱を避けるため削除) です。
    - 「タイトル」「説明」「URL」欄の内容を https://github.com/tokyo-metropolitan-gov/covid19/issues/3641#issuecomment-619325475 の通り入力していきます。
    - ESLint・Prettierの影響で上記のような見た目にならない場合がありますが、その場合は整形結果のままで大丈夫です。
    - 現在の内容は全て破棄し、新しい内容に入れ替えます。
    - 内容の順番は、元データで上から並んでいるままでお願いします。
- 本来は翻訳キーファイルの `assets/locales/ja.json` も修正しますが、今回はひとまず編集無しでお願いします（タイミングがあえば #3594 の自動修正ツールを試験的に使用します）。

なにか不明点などあればこちらでご質問ください。

**Comment by shgtkshruch** [comment]
サンプルコードに `<t-i18n>` タグがありますが、こちらの issue は `dev-ja-hira-ruby` に向けてプルリクエストを出すという理解でいいでしょうか？

また、データついては `data/worker.json` のようなファイルを用意して、そちらから読み込む形にすると Data と View を分離できてメンテナンスしやすくなると思いますが、いかがでしょうか？

**Comment by MaySoMusician** [comment]
おっと。失礼しました。現段階ではまだルビ化が `development` に取り込まれていないので、 `<t-i18n>` は使用しない方針でいきたいです。

```vue
<static-card>
  <h3>
    <external-link
      url="ここにURL"
      :icon-size="24"
      >{{ $t('ここにタイトル') }}
    </external-link>
  </h3>
  <p>
    {{
      $t(
        'ここに説明'
      )
    }}
  </p>
</static-card>
```

`data/worker.json` の件については現在相談中です。データの更新フローの修正も伴う可能性があり、本PRでは今まで通り直接Vueファイルを編集する形になるのではないかと思われます。

**Comment by MaySoMusician** [comment]
今回はVueファイル直接編集でお願いします！ JSON化については別issueにて取り扱う予定です

**Comment by shgtkshruch** [comment]
個人的には `data/worker.json` を作らなくても、Vue の `data` に元データを配列で入れて `<static-card>` を `v-for` で回すだけでも DRY になりそうだと思いました。

作業内容について整理したほうが良さそうだったので少し質問させていただきましたが、実際の実装はどなたかにおまかせできればと思います mm
（これから作業時間がとれそうにないので...）

**Comment by Aqua-ix** [comment]
こちら私の方で対応します

**Comment by mcdmaster** [comment]
元 Excel に、行を追加してもよろしいのでしょうか。

ちなみに私は、公認会計士協会のリリースを加えたいと思っています。
もしも何事もなければ、例年３／末の決算は、おおよそゴールデンウイーク前に開示がなされます。
しかしながら、今回はそれが叶わなくなっています。
その状況における、監査対応に留まらず企業の経理担当者が取り得るアクション（決算発表の延期等）の指針を、会計士協会が示しています。
それは、経済へのインパクトに留まらず、人命への配慮といった原則論に及んでいます。
企業会計や決算作業に関わることのない人も目を通す価値のあるものです

![94221491_2915431658537012_8206419047831568384_n](https://user-images.githubusercontent.com/10361533/80311383-5718ed00-881a-11ea-8dcc-04aefc7d5254.jpg)

**Comment by MaySoMusician** [comment]
@mcdmaster ご提案ありがとうございます。本issueは都からの指示を受けての内容更新ですので、追加の要望は別途issueを立てていただけると大変助かります（issue管理の都合上）。

**Comment by mcdmaster** [comment]
@MaySoMusician りょうかいしました。
default.xlsx の扱いがちょっとよくわからなかったため、お尋ねしました。ありがとうございます
