### ISSUE TITLE
都営地下鉄の利用者数の推移で帰りの時間帯も出せないか

### ISSUE THREAD

**Issue by nichesuch** [tokyo-metropolitan-gov/covid19#3664]
## 改善詳細 / Details of Improvement
- 現状6:30-10:30の通勤の時間帯を提示しているが、16:30-20:30の帰宅の時間帯も提示して欲しい。
- 都内に行った際に、行きは空いていたが、帰りはそれなりに混んでいて、戸惑った。

## 期待する見せ方・挙動 / Expected behavior
- 見せ方は応相談。今のグラフに追加するか、別のカードとして見せるか。

**Comment by kaizumaki** [comment]
@nichesuch ご提案ありがとうございます。東京都に確認いたしました。こちらのコメント https://github.com/tokyo-metropolitan-gov/covid19/issues/2497#issuecomment-650721336 のとおり、交通情報については現時点で重要度が下がっております。ですので、こちらのissueは一旦クローズさせていただければと思います。今後状況に応じて再検討したいと思います。

**Comment by kaizumaki** [comment]
東京都からの回答がありましたので、こちらのissueはクローズします。
