### ISSUE TITLE
FORKED_SITES.mdに静岡市を追加

### ISSUE THREAD

**Issue by kazuomatz** [tokyo-metropolitan-gov/covid19#3665]
## 改善詳細 / Details of Improvement

静岡市公式サイトがオープンしたのでFORKED_SITES.mdに静岡市を追加したい。

## スクリーンショット / Screenshot
<img width="1408" alt="スクリーンショット 2020-04-25 11 57 12" src="https://user-images.githubusercontent.com/2704723/80269615-466a5900-86ec-11ea-8560-4b5f383e30c3.png">

**Comment by goki90210** [comment]
すでに追加されているのでクローズで良いのではないでしょうか？

**Comment by kazuomatz** [comment]
すみません。クローズします。
