### ISSUE TITLE
グラフの埋め込み用コードをコピーした際に更新時刻が表示される

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3667]
## 起こっている問題 / The Problem
- グラフの埋め込み用コードをコピーするアイコンをクリックすると、更新時刻や「オープンデータを入手」など文字が表示されます
- クリックボードにコピーした際のフィードバックとして、（おそらく）これらの文字列は不要ではないかと思います
- こちらのコードが更新時刻などを表示しています
https://github.com/tokyo-metropolitan-gov/covid19/blob/251dd638e696550b1cd67ecf2c69114279cebc61/components/DataView.vue#L175-L178

## スクリーンショット / Screenshot
[![Image from Gyazo](https://i.gyazo.com/ed75c1143f8db79f306361d57359a481.gif)](https://gyazo.com/ed75c1143f8db79f306361d57359a481)

![スクリーンショット 2020-04-25 12 16 11](https://user-images.githubusercontent.com/5207601/80269906-e6c17d00-86ee-11ea-99bd-8b2dd71b22bb.png)

## 期待する見せ方・挙動 / Expected Behavior
- クリップボードにコピーしたら、「埋め込み用コードをコピーしました」の文言のみ表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. 本番環境でグラフの埋め込み用コードをコピーする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by tetuya1231** [comment]
初めてですが、このissueに取り組ませていただきます。
