### ISSUE TITLE
「都営地下鉄の利用者数の推移」グラフに外部リンクを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3668]
「都営地下鉄の利用者数の推移」グラフの下部に外部リンクの追加をお願いします。

- テキスト：`主要駅の改札通過人数の推移（東京、新宿、渋谷、池袋ほか）[内閣官房HP]（ページ下部）`
- リンク先URL：https://corona.go.jp/
- 位置：「鉄道利用者数の推移（新宿、東京、渋谷、各駅エリア）[PDF] 」の下
以下画像の赤線部分です。
![都営地下鉄利用者数推移グラフ](https://user-images.githubusercontent.com/14883063/80271467-4a51a780-86fb-11ea-887c-5da2b3f40cce.jpg)

**Comment by Aqua-ix** [comment]
対応します

**Comment by Aqua-ix** [comment]
@kaizumaki 日本語以外のテキストについて指定はありますか？

**Comment by kaizumaki** [comment]
@Aqua-ix ご対応ありがとうございます！日本語以外のテキストについては特に指定はないので、 `ja.json` に翻訳キーを登録するということでいいと思います。
