### ISSUE TITLE
[refactor] 未使用のメソッド `getAdjustX` を削除

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3670]
## 改善詳細 / Details of Improvement
- 以下のコンポーネントで未使用のメソッド定義 `getAdjustX` が残っているので、削除すると良さそうです。
- `ConfirmedCasesDetailsTable.vue` 
https://github.com/tokyo-metropolitan-gov/covid19/blob/251dd638e696550b1cd67ecf2c69114279cebc61/components/ConfirmedCasesDetailsTable.vue#L118-L140

- `TestedCasesDetailsTable.vue`
https://github.com/tokyo-metropolitan-gov/covid19/blob/251dd638e696550b1cd67ecf2c69114279cebc61/components/TestedCasesDetailsTable.vue#L91-L113

## スクリーンショット / Screenshot
リファクタリングなので、スクリーンショットはありません。

## 期待する見せ方・挙動 / Expected behavior
- `getAdjustX` メソッドを削除すること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
これやっちゃいます!
