### ISSUE TITLE
「東京都緊急事態措置について」のボタンのクリック領域が狭い

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3675]
## 改善詳細 / Details of Improvement
- 「東京都緊急事態措置について」のボタンのクリック領域が見た目より少し狭くなっています
- テキストと枠線の余白や、`bullhorn` のアイコンをクリックしてもリンクとして反応しません
- ボタン全体がクリックできるようなっていると使いやすいと思います

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-25 15 30 07](https://user-images.githubusercontent.com/5207601/80274260-159e1a00-8714-11ea-8489-aaee315aadba.png)

## 期待する見せ方・挙動 / Expected behavior
- ボタン全体がクリックできること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
やります
