### ISSUE TITLE
[/flow] 「新型コロナコールセンター」の文言変更

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3676]
## 改善詳細 / Details of Improvement
- 下記スクリーンショットのあるような「`新型コロナコールセンター`」を「`新型コロナコールセンター（対応言語：日本語・英語・中国語・韓国語）`」に変更
    - 現在の英語版では「`Tokyo Novel Coronavirus Call Center (Support in English, Chinese, Korean and Japanese)`」と表示されており、日本語でも対応言語を表示したほうが良いとなったため
- (追記) コロンは全角です

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/34566290/80274972-4896dc80-8719-11ea-84b9-67131c3bedec.png)

## 作業内容
- `pages/flow.vue` 内の `{{ $t('新型コロナコールセンター') }}` （2か所）を上記「改善詳細」の通り変更
- `assets/locales/ja.json` L279 の翻訳キーを同様に変更
    - 他の言語ファイルについてはTransifexにて修正

**Comment by itohtsu** [comment]
このissue私がやりたいです！
