### ISSUE TITLE
「入院中数」「重症者数」推移グラフの追加

### ISSUE THREAD

**Issue by takainou** [tokyo-metropolitan-gov/covid19#3679]
## 改善詳細 / Details of Improvement
- 「死亡者数を抑える」事が都全体の最大目標であり、陽性者数を減らし検査実施件数を増やすだけでは達成出来ません。患者自身と医療関係者の努力が反映され、感染拡大が収束し0人になるまで管理する数値「入院中数」「重症者数」を指標とするのが良いと考えます。
- 「入院中数」増は感染症病床への負荷増、「重症者数」増はICUへの負荷増となります。
- ３月下旬の都知事の大切な自粛依頼会見にて、「感染者数累積」と「退院者数累積」だけの折れ線グラフを出し「この間が、入院中の方々になりますが・・・」と説明しづらそうにしていて、「入院中数」の推移をシンプルに掲載する必要があると考えた次第です。
- 東京都サイトだと「検査陽性者の状況」の次に「入院中数」「重症者数」を表示するのが良いと考えます。北海道サイトでは「現在患者数」を先頭に表示しており同じ考え方です。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/80278719-8dc80800-8733-11ea-8257-ba1e677a9e83.png)
![image](https://user-images.githubusercontent.com/63571899/80278725-94ef1600-8733-11ea-893d-b0b668a90883.png)

## 期待する見せ方・挙動 / Expected behavior
- 「入院中」「重症」の日次データを、愛知県サイトの「入院中」「重症」と同じ見せ方・挙動の棒グラフ２つを表示する。
- その日の値を棒グラフで表示し、右上には最新の値を表示する。
- 値が取得出来なかった日は、グラフ横軸の日は抜かず、空白とする。

**Comment by kaizumaki** [comment]
@takainou ご提案ありがとうございます。モニタリング指標という形で公式にデータが公開となりましたので、こちらの提案のグラフが作成されることになりました。
２つの間で実装が若干異なるため、２つに分けて別issue（ #4316 #4317 ）を立てさせていただきました。

**Comment by takainou** [comment]
都への確認ありがとうございます。公式にデータ公開となり良かったです。
なお、別Issueが立てられたので、本IssueはClose頂いて構いません。

**Comment by kaizumaki** [comment]
ありがとうございます。こちらのissueはクローズしますね。
