### ISSUE TITLE
「区市町村別感染状況」のカラム地図の追加

### ISSUE THREAD

**Issue by takainou** [tokyo-metropolitan-gov/covid19#3680]
## 改善詳細 / Details of Improvement
- 「陽性患者数（区市町村別）」がありますが、より見やすくするため、ダッシュボード向けの「カラム地図」での掲載が適当と考えます。
- 塗り分けは、感染者数で行うと人口が多い特別区が目立つだけなので、感染率(10万人あたりの感染者数)で塗り分ける必要があると考えます。感染率の意味を理解していただく必要はあるが、感染拡大してくると感染者数だけでは状況判断がしにくくなります。

## スクリーンショット / Screenshot

1.都の報道発表と同じ形式 
![image](https://user-images.githubusercontent.com/63571899/80280057-83f6d280-873c-11ea-82fc-aaf1611b448a.png)
2.日本カラム地図の東京版
![image](https://user-images.githubusercontent.com/63571899/80280059-88bb8680-873c-11ea-95b0-460d22cd87ba.png)

## 期待する見せ方・挙動 / Expected behavior
- 「陽性患者数（区市町村別）」で掲載しているデータを利用する。 
- 住民基本台帳上の人口(2020年3月1日時点)を感染率算出に利用する。
　https://www.toukei.metro.tokyo.lg.jp/juukim/2020/jm20010000.htm 
- 感染率を以下の通り算出する。
　感染率 ＝ （ 感染者数 ÷ 人口 ) × 100,000
- 「カラム地図」の市町村の配置は、２案ある。
1.都の報道発表と同じ形式 https://www.fukushihoken.metro.tokyo.lg.jp/hodo/saishin/corona258.html
2.日本カラム地図の東京版 https://tabularmaps.github.io/areamap/tabularmaps_japan.html#Tokyo
- カラム内の表示は上から、以下の通りである。
　[区市町村名]
　[感染者数]
　[感染率]
- 感染率により、カラム全体の背景色・文字色を塗り分ける。
　感染率：背景色：文字色
　0人：#FFFFFF：黒
　128人以上：#00429D：白
　32人以上：#4771B2：白
　8人以上：#73A2C6：白
　2人以上：#8ABCCF：黒
　2人未満：#C5EDDF：黒

**Comment by takainou** [comment]
愛知サイトでリリースされました。
![image](https://user-images.githubusercontent.com/63571899/80664610-311d7200-8ad2-11ea-90b7-5ca07f0d056d.png)

**Comment by kaizumaki** [comment]
@takainou ご提案ありがとうございます。検討がたいへん遅くなりまして申し訳ありません。ご提案について東京都に確認いたしました。
人口あたりの陽性者数というデータは東京都として発表していないので、ご提案いただいた内容を採用するのは非常に難しいです。
また、同様のissueの検討する際、東京都からこちらのコメントを得ています。→https://github.com/tokyo-metropolitan-gov/covid19/issues/2706#issuecomment-627821352
当サイトでは「報告日別による陽性者数の推移」グラフにおいて福祉保健局発表の「[届出保健所別の内訳](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/todokedehcyouseisya.html)」へリンクを貼っており、こちらを参照いただくようになっています（こちらもあくまで届出保健所別なので、当該地域の住民とは限りません）。
どうかご理解いただけますようお願いいたします。

**Comment by kaizumaki** [comment]
東京都からの回答がありましたので、こちらのissueはクローズいたします。
