### ISSUE TITLE
カードの共有ボタンから表示するSNSボタンの表示がズレている

### ISSUE THREAD

**Issue by Tatsumi0000** [tokyo-metropolitan-gov/covid19#3688]
## 起こっている問題 / The Problem
- カードの共有ボタンから表示するSNSボタンの表示がズレている

## スクリーンショット / Screenshot
![タイトルなし](https://user-images.githubusercontent.com/19218690/80287223-4cebe580-876b-11ea-88c5-8f4f4c39276b.gif)

## 期待する見せ方・挙動 / Expected Behavior
- カードの共有ボタンをクリックした際に表示されるSNSボタンが中央に表示する

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stg-covid19-tokyo.netlify.app/ にアクセス
2. いずれかのカードの共有ボタンをクリック
3. するとSNSボタンがズレて表示されている

## 動作環境・ブラウザ / Environment
- macOS Catalina 10.15.4
- Firefox 75.0 (64 ビット)

**Comment by Tatsumi0000** [comment]
私にやらせて下さい．

**Comment by MaySoMusician** [comment]
こちら Windows 10 Home 1909 64 bit + Chrome  81.0.4044.122 ですが、そこまでズレておりません
![image](https://user-images.githubusercontent.com/34566290/80287347-0a76d880-876c-11ea-90c3-6357e2ec5758.png)

念のため @Tatsumi0000 さんの検証環境をご提示いただくことは可能でしょうか？

**Comment by Tatsumi0000** [comment]
@MaySoMusician 
かしこまりました．
環境はこちらになります．
## 動作環境・ブラウザ / Environment
- macOS Catalina 10.15.4
- Firefox 75.0 (64 ビット)

**Comment by Tatsumi0000** [comment]
@MaySoMusician さん

上の方も環境を更新しておきます．

**Comment by Tatsumi0000** [comment]
自分がやると言っておきながら大変申し訳ございませんが，
どなたかこのイシューをやっていただけないでしょうか？

`yarn dev`すると，ブラウザが重すぎて全く作業が出来ませんでした...

上の方にある
> 私にやらせて下さい．

こちらのコメントも修正しておきます．

**Comment by MaySoMusician** [comment]
`yarn dev-no-axe` の場合、比較的動作が軽くなります。こちらもご活用ください

**Comment by Tatsumi0000** [comment]
@MaySoMusician さん
ありがとうございます！
そちらで，試してみます！

**Comment by Tatsumi0000** [comment]
@MaySoMusician さん
ありがとうございました！
おかげさまで確認出来ました！

今からPR出したいと思います．
