### ISSUE TITLE
Firefoxで「東京都緊急事態措置について」のボタンの外部リンクアイコンがずれている

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3725]
## 起こっている問題 / The Problem
- #3675 #3678 で「東京都緊急事態措置について」のボタンのクリック領域を修正しました。
- OSX Firefoxにて、当該ボタンの外部リンクアイコンがカラム落ちしています。
- 同時に、クリッカブルな範囲が意図通りになっていません。

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-27 9 34 28](https://user-images.githubusercontent.com/14883063/80324378-94599b00-886b-11ea-8a55-e4da4395fd69.png)

## 期待する見せ方・挙動 / Expected Behavior
- 外部リンクアイコンがカラム落ちしない。
- ボタン全体がクリックできるようになる。

## 起こっている問題の再現手段 / Steps to Reproduce
1. OSX Firefoxで閲覧

**Comment by goki90210** [comment]
Chromiumなブラウザだと起こらないようです（Firefoxのみ）。
spanタグ内で white-space: nowrap;
が効けば折り返さないですね。

**Comment by Nekoya3** [comment]
たいおうします
