### ISSUE TITLE
「検査陽性者の状況」チャートに注釈を追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3737]
「検査陽性者の状況」チャートに以下の注釈の追加をお願いします。

- 注釈テキスト： `（注）「重症」は、集中治療室（ICU）等での管理又は人工呼吸器管理が必要な患者数を計上`
- 位置：「（注）「入院中」には、入院調整中・宿泊療養に移行した方を含む 」と「（注）退院者数の把握には一定の期間を要しており、確認次第数値を更新している 」の間にお願いします。
以下画像の赤線部分です。

![検査陽性者の状況](https://user-images.githubusercontent.com/14883063/80334664-db0bbd00-888c-11ea-9228-ac9c5b0d156b.jpg)

※ GitHub Actionsで `Auto-i18n Generator` が動いていますので、従来の `ja.json` への翻訳キーの登録は不要です。

**Comment by itohtsu** [comment]
対応します
