### ISSUE TITLE
ナビゲーションに「ご家庭でのマスク等の捨て方」・「東京都における滞在人口の増減」を追加

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3740]
ナビゲーションに以下の2項目を追加してください
（作業対象ファイル: `components/SideNavigation.vue` L142以降）

- 1個目
    - テキスト: ご家庭でのマスク等の捨て方
    - リンク先: https://www.kankyo.metro.tokyo.lg.jp/resource/500200a20200221162304660.files/200327_chirashi.pdf
    - アイコン: `'CovidIcon'`
    - dividerを `true` にする
    - 位置: 「新型コロナウイルスの感染が判明した方へ」の真下
- 2個目
    - テキスト: 東京都における滞在人口の増減
    - リンク先: https://www.seisakukikaku.metro.tokyo.lg.jp/information/corona-people-flow-analysis.html (この後リンクが開通する予定)
    - アイコンは無し
    - dividerの設定も無し
    - 位置: 「東京都主催等 中止又は延期するイベント等」と「知事からのメッセージ」の間

また、上記2項目追加に伴い、「新型コロナウイルスの感染が判明した方へ」の `divider: true` (K159)を除去。

以上3点、よろしくお願いいたします。

**Comment by junjunjunk** [comment]
やります！assignよろしくお願いいたします。

**Comment by MaySoMusician** [comment]
@junjunjunk ありがとうございます！よろしくお願いいたします

**Comment by junjunjunk** [comment]
review よろしくお願いいたします！
