### ISSUE TITLE
ルーティングによるページ切替時にページタイトルが変わっていない

### ISSUE THREAD

**Issue by yamanoku** [tokyo-metropolitan-gov/covid19#377]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
ページ共有する際にtitleタグが変更されていないので、 `/worker` に アクセスしても
「企業の皆様・はたらく皆様へ - covid19」のようにはならない。

各ページコンポーネントには `head()` にてtitleが入力されているが、こちらが反映されていない。

## スクリーンショット / Screenshot

<img width="1275" alt="スクリーンショット 2020-03-04 23 09 38" src="https://user-images.githubusercontent.com/1996642/75887507-4036c980-5e6d-11ea-8652-7cf9c6306bcf.png">

## 期待する見せ方・挙動 / Expected behavior
各ページに遷移した時にタイトルタグを `head()` のtitleにあるものが反映されるようにする。

**Comment by potato4d** [comment]
報告ありがとうございます！
確認させていただきます。

**Comment by potato4d** [comment]
nuxt.config.js に titleTemplate があれば十分なのに title があるのが原因っぽい

**Comment by potato4d** [comment]
@yamanoku 
#384 にて対応しました。ありがとうございます ✨
