### ISSUE TITLE
移動平均線の表示

### ISSUE THREAD

**Issue by twata701** [tokyo-metropolitan-gov/covid19#3780]
## 改善詳細 / Details of Improvement
- 日別の陽性患者数、検査実施人数は曜日によるばらつきが大きいため、7日移動平均線を表示することで増加・減少の傾向がわかりやすくなる。

## 期待する見せ方・挙動 / Expected behavior
日別の陽性患者数、検査実施人数のグラフに重ねる形で表示することで、傾向に沿っているのかどうかがわかりやすくなる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kdnw** [comment]
棒グラフに移動平均線を追加する方法が、分かりません。
以下の図のように、日別の陽性患者数の移動平均(7日)のグラフを追加するのは、いかがでしょうか？
![covid_ma](https://user-images.githubusercontent.com/64766962/80940441-c5f9d580-8e1a-11ea-85d4-f6a08b2a8b7b.png)

**Comment by twata701** [comment]
@kdnw ありがとうございます。私の方でこのようなグラフは表示させることはできたのですが、判例を表示させることができず。。

![スクリーンショット 2020-05-05 18 03 44](https://user-images.githubusercontent.com/2725331/81050398-df724e80-8efa-11ea-8249-e8f12a9466a5.png)

**Comment by twata701** [comment]
参考までに、変更内容をコミットしました。

**Comment by kdnw** [comment]
@twata701さん、ありがとうございます。
参考にさせていただきます。

感染者の移動平均を棒グラフで表示するバージョンは、以下にコミットしました。
https://github.com/kdnw/covid19

**Comment by twata701** [comment]
凡例を表示させたところグラフのレイアウトが崩れてしまいます。どなたか解決できないでしょうか？
![スクリーンショット 2020-05-05 22 30 35](https://user-images.githubusercontent.com/2725331/81072649-69cda900-8f21-11ea-872a-4c92917de501.png)

**Comment by kaizumaki** [comment]
@twata701 ご提案ありがとうございます。モニタリング指標という形で公式にデータが公開となりましたので、こちらの提案のように７日間移動平均の折れ線グラフが作成されることになりました。
別途データが提供されることになりましたので、別issue（ #4323 #4319 ）で対応させていただければと思います。

**Comment by kaizumaki** [comment]
モニタリング指標関連の実装がリリースされました。７日間移動平均の折れ線グラフについてはそちらを参照していただけるとうれしいです。こちらのissueはクローズさせていただきます。
