### ISSUE TITLE
[Recommendation] Adding an Rt Chart 実効再生産数のグラフの追加

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#3797]
## 改善詳細 / Details of Improvement
- (EN) Adding an Rt chart to the top page
- (JA) 実効再生産数グラフのトップページへの追加

## スクリーンショット / Screenshot

![コメント 2020-04-29 222825](https://user-images.githubusercontent.com/10361533/80601439-c8e67600-8a68-11ea-8692-7fb4093a1b7b.png)
- (EN) [See here](https://rt-live-japan.com/) for entire Prefectures and details.
- (JA) 全都道府県データおよび詳細は、[こちらをご覧ください](https://rt-live-japan.com/)。

## 期待する見せ方・挙動 / Expected behavior
- Rt Chart was released in Apr 24 and is going to be one of yet another COVID-19 project's outcome instead of the number/graph of the "positive" of coronavirus. The value of Rt addresses how many people may be affected by one patient confirmed "positive."
- 去る 4/24 にリリースされた実効再生産数データおよびグラフは、１人の新型コロナウイルス感染者が何人の他者に感染させ得るか（実効再生産数 Rt）に着目した指標です。当然 Rt が低くなるほど感染拡大の確率は下がるという判断を助けるものになります

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster ご提案ありがとうございます。こちらのissueについて東京都に確認いたしました。東京都としてはモニタリング指標として情報を提供しておりますので、そちらをご参照いただきたく思います。
ですので、こちらのissueはクローズさせていただければと思います。ご理解いただけますようよろしくお願いします。

**Comment by mcdmaster** [comment]
ご確認をいただき、ありがとうございます。
それでは、クローズいたします
