### ISSUE TITLE
「陽性患者数」推移グラフに「感染経路不明者数」を掲載する

### ISSUE THREAD

**Issue by takainou** [tokyo-metropolitan-gov/covid19#3805]
## 改善詳細 / Details of Improvement
- 感染経路不明者の発生は市中感染が起きている事を示し、クラスター化すると感染拡大する恐れがあります。陽性患者数全体に占める感染経路不明者の割合が増えるのは危ない兆候です。陽性患者数全体の推移を見るのも大切ですが、その中の感染経路不明者の推移もきちんと見ていく必要があります。
- 既に多くのマスメディアでも、日別感染者数推移棒グラフに、感染経路不明者を載せて連日報道しており(添付画像はNHK)、都民の理解も深まっており、一般的となっていると考えます。
- 「陽性患者数」推移グラフに「感染経路不明者数」を掲載するのが良いと考えます。
- 既に大阪府サイトでは実装済みです。

なお、 #2987 と関連しますが、感染経路の掲載に重点は置かず、「感染経路不明者数」の把握のみに焦点を当てる為、別Issueとして起票しています。 

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/80663883-311c7280-8ad0-11ea-8ac0-9e0f0635f2eb.png)
![image](https://user-images.githubusercontent.com/63571899/80663888-34176300-8ad0-11ea-94d7-315e332b9c48.png)

## 期待する見せ方・挙動 / Expected behavior
- 「陽性患者数」推移グラフに「感染経路不明者数」を掲載する
- 系列の重なり100%とし、「陽性患者数」の手間に表示する
- 凡例をクリックした際「感染経路不明者数」を非表示化出来るようにして、従来の「陽性患者数」だけでも見られるようしておく

**Comment by kaizumaki** [comment]
@takainou ご提案ありがとうございます。モニタリング指標という形で公式にデータが公開となり、接触歴等不明率のグラフが作成されることになりました。実装の仕様が異なることから、別issue #4324 を立てております。

**Comment by takainou** [comment]
都への確認ありがとうございました。
別Issueが立てられたので、本IssueはClose頂いて構いません。

**Comment by kaizumaki** [comment]
ありがとうございます。こちらのissueはクローズいたします。
