### ISSUE TITLE
「検査実施件数」グラフのデザイン修正（保険適用分をわかりやすく）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3806]
「検査実施件数」グラフは現在「都内発生」と「その他」の積み上げ棒グラフになっていますが、それを「都内発生」「その他」の合計値の棒グラフに変更します。
さらにそれを **「最新の検査実施日の一週間前の木曜日から今日まで」** を薄い緑色にします。
下記イメージ画像のように、左右で色分けされたグラフにします。

![検査実施件数リデザイン](https://user-images.githubusercontent.com/14883063/80671358-86627f00-8ae4-11ea-97a1-dd0ccdbbd32c.png)

凡例については以下のように変更します（長いですが、このissueではママでお願いします）。
- 濃い緑： `健康安全研究センター及び医療機関が保険適用で行った検査件数の合計`
- 薄い緑： `健康安全研究センターの検査件数のみの速報値（保険適用分を含まない未確定値）`

※これにともない、グラフ下部にある「※1」「※2」の注釈は削除します。

-----

#3374 #3579 でも要望があがっていました。都と検討し、こちらのissueのようなデザインにすることになりました。

-----

なにか疑問点あれば遠慮なくコメントしてください！

**Comment by kaizumaki** [comment]
@soutaito お願いしてもいいですか？

**Comment by kenmoeconomics** [comment]
test

**Comment by kenmoeconomics** [comment]
はじめまして。検査実施件数の定義について確認させてください。
今回の更新により削除された「※１ 疑い例・接触者調査」は、[東京都の4月6日付会議資料](https://www.bousai.metro.tokyo.lg.jp/_res/projects/default_project/_page_/001/007/612/2020040608.pdf)の記載から考えると、「陰性確認検査を含まない検査実施件数」を意味すると認識していました。
今回の更新で※１の表記が削除されましたが、今後も「陰性確認検査を含まない検査実施件数」を表示しているという理解でよろしいでしょうか。
お忙しいところ恐れ入りますが、ご回答いただけると幸いです。

**Comment by knzm** [comment]
@kenmoeconomics ここにコメントしてもおそらく開発者は気がつかないので、新しい issue を立てたほうがよろしいかと思います。

**Comment by kaizumaki** [comment]
@kenmoeconomics ご質問ありがとうございます。
@knzm フォローありがとうございます。
ご質問の件、ただいま東京都の確認を待っております。正確な回答をするようにしておりますので、しばらくお待ちいただけますでしょうか。

**Comment by kenmoeconomics** [comment]
@knzm githubに不慣れなもので、失礼いたしました。
@kaizumaki ご対応いただきありがとうございます。
おそれいりますが、よろしくお願いいたします。

**Comment by kaizumaki** [comment]
@kenmoeconomics 
[ご質問](https://github.com/tokyo-metropolitan-gov/covid19/issues/3806#issuecomment-622305388)の件、たいへんお待たせして申し訳ありません。
東京都福祉保健局に確認しましたところ、

> 検査実施件数については、対策サイト開設当初から陰性確認検査数も含んで計上しており、現在まで変更されておりません。（補足：検査実施人数については、陰性確認を除いての計上となっております。）

とのことです。

**Comment by kenmoeconomics** [comment]
@kaizumaki 
お忙しい中ご対応いただきありがとうございます。
情報収集に関して制約がある以上、陰性確認を件数から除くことは困難であったと認識しております。
個人的には「※１疑い例・接触者調査」は誤解を招く表現だったと思いますが、当時の状況を考えれば仕方ないようにも感じております。
リソースが限られている中、積極的な情報開示に努めていただきありがとうございます。
今後も大変な状況が続くとは思いますが、皆様のご尽力のおかげでよい方向に向かいつつあると感じております。
引き続きよろしくお願いいたします。
