### ISSUE TITLE
「自宅安静となり、医療機関を受診していただきます」の変更

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3808]
flowページの「自宅安静となり、医療機関を受診していただきます」（下図参照）を「自宅で安静に過ごし、必要に応じて医療機関を受診してください。」に変更していただきたいです。

![image](https://user-images.githubusercontent.com/34566290/80676576-05aa7f80-8af2-11ea-8649-d3be190a5542.png)

- `pages/flow.vue` のみの変更になります。
- 言語ファイルはPRマージ時に自動的に更新されます。

**Comment by kaizumaki** [comment]
私のほうで引き取ります。
