### ISSUE TITLE
「新型コロナウイルス感染症に関する東京都の支援策」のアイテム変更

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3809]
サイドナビゲーション内の「新型コロナウイルス感染症に関する東京都の支援策」（下図参照）を下記の通り変更していただきたいです。
![image](https://user-images.githubusercontent.com/34566290/80681520-d4cf4800-8afb-11ea-833b-720b058146cf.png)

変更後
- タイトル: `東京都 新型コロナウイルス感染症 支援情報ナビ`
- リンク先: https://covid19.supportnavi.metro.tokyo.lg.jp/

そのほかの部分は変更なし

---

- `components/SideNavigation.vue` のみの変更になります。
- 言語ファイルはPRマージ時に自動的に更新されます。

**Comment by ryuckel** [comment]
こちら対応しますね
