### ISSUE TITLE
ライブラリの自動アップデートのためにRenovateを導入

### ISSUE THREAD

**Issue by mikan3rd** [tokyo-metropolitan-gov/covid19#3841]
## 改善詳細 / Details of Improvement
- Renovateを導入することでライブラリのアップグレードがある場合に自動的にPRを作成&mergeさせることができ、保守・運用の手間を省いて開発効率を上げることができる
  - https://github.com/apps/renovate
- 設定は `renovate.json` で調整可能
  - https://docs.renovatebot.com/configuration-options/
- 例えば次の場合はmajorアップデート以外の場合に自動PR作成&自動mergeし、majorアップデートの場合はPRのみ作成される
##### renovate.json
```json
{
  "extends": ["config:base"],
  "timezone": "Asia/Tokyo",
  "labels": ["renovate"],
  "packageRules": [
    {
      "updateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    }
  ]
}
```

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected behavior
- ライブラリの自動アップデート

## 動作環境・ブラウザ / Environment
- なし

**Comment by MasaGon** [comment]
私やります。
