### ISSUE TITLE
フォントサイズを相対的に指定する

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3865]
## 改善詳細 / Details of Improvement
ブラウザの表示設定（拡大・縮小）により文字サイズが変更できるようにしたいです。
現状ではmiCheckerでテストした時に指摘される項目です。
サイト全体をとおして修正する必要があります。

## 期待する見せ方・挙動 / Expected behavior
- ブラウザを拡大・縮小したときに、文字サイズも拡大・縮小する
- 標準サイズ（100%）表示の際は、現状のフォントサイズと変わらないようにする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
対応します。

**Comment by mcdmaster** [comment]
#904, #915 とも関係がありますね
