### ISSUE TITLE
使用していないYahooデータ使用関連のコンポーネントの削除

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3875]
## 内容

以下の9ファイルの削除と、それらを読み込んでいる箇所の記述の除去

## 対象ファイル

- `components/cards/ChiyodaVisitorsCard.vue`
- `components/cards/ShinjukuStMapCard.vue`
- `components/cards/ShinjukuVisitorsCard.vue`
- `components/cards/TokyoCityMapCard.vue`
- `components/cards/TokyoStMapCard.vue`
- `components/Heatmap.vue`
- `components/HeatmapLegend.vue`
- `components/MapCard.vue`
- `components/VisitorsBarChart.vue`

## 理由

自動で `assets/locales/ja.json` を更新するツールを導入した影響で、上記9ファイル内に含まれている文字列も再び `ja.json` に含まれるようになってしまった。使用していない文字列が `ja.json` に含まれTransifexに登録されてしまうと、翻訳・レビューのコストが増えてしまうため。

**Comment by kozayupapa** [comment]
@MaySoMusician  はじめまして竹原と申します　こちらのIssue対応させていただきます。
ファイル削除とogp_screenshot.py からの削除を対応しました。　通常のyarn devで動作確認は実施いたしました。　他に必要な確認方法等あるようでしたら教えて下さい。のちほどpull request 登録いたします。
