### ISSUE TITLE
検査陽性者の状況への病床数の追加

### ISSUE THREAD

**Issue by feuxfollets1013** [tokyo-metropolitan-gov/covid19#3925]
## 改善詳細 / Details of Improvement
- 入院者数だけではなく、病床数も表示することで、現在の負荷状況(病床使用率)を見えるようにする。

## スクリーンショット / Screenshot
![screenshot](https://user-images.githubusercontent.com/34957741/81132444-653cdb00-8f89-11ea-99af-92bdbc94f9cf.png)
- 上記サンプルにおける病床数は、[COVID-19 Japan](https://www.stopcovid19.jp/)の新型コロナウイルス対策病床オープンデータ(5/6時点)を元に記載した。都公式ページとして表示する際は、マスターデータへの病床数追加が必要と想定する。

## 期待する見せ方・挙動 / Expected behavior
- 検査陽性者の状況に、医療病床数(うち重篤重傷者用病床数)、軽症者用宿泊医療室数を表示する。

**Comment by linuxmetel** [comment]
やります

**Comment by linuxmetel** [comment]
病床数　医療病床　うち重症重篤　宿泊医療施設　それぞれ名前を何にしますか？

**Comment by linuxmetel** [comment]
#4412 まだ修正が必要なところもあるのですが。一旦プルリクを送りました。

**Comment by kaizumaki** [comment]
@feuxfollets1013 ご提案ありがとうございます。こちらのissueについて東京都に確認いたしました。東京都としてはモニタリング指標の中で「重症患者数」「入院患者数」の参考数値として病床数の目安を提示しています。

<img width="667" alt="スクリーンショット 2020-06-28 18 07 04" src="https://user-images.githubusercontent.com/14883063/85943360-84912c80-b96a-11ea-81ff-59d43fc20dbc.png">

これが東京都として出している正式な数値になりますので、こちらのissueを採用するのは難しいです。ご理解いただけましたら幸いです。

**Comment by linuxmetel** [comment]
@kaizumaki 分かりました。プルリクはクローズして良いでしょうか？

**Comment by kaizumaki** [comment]
PRのクローズありがとうございます。東京都の回答がありましたので、こちらのissueはクローズさせていただきます。
