### ISSUE TITLE
[ruby] TI18nコンポーネント内に<br>タグがあるとそれ以降の要素が表示されない

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#3947]
## 起こっている問題 / The Problem
- `<t-i18n>` コンポーネント内に `<br>` がある場合、`<br>` 以降の要素が表示されない
- 具体的には、下記のようなコードで https://github.com/tokyo-metropolitan-gov/covid19/blob/daf0dc29b98400ab6f1a1bc4da4b709ba2979fe0/components/ConfirmedCasesDetailsTable.vue#L68-L72 `（療養期間経過を含む）` が表示されない

## スクリーンショット / Screenshot
- 表示例
![image](https://user-images.githubusercontent.com/34566290/81247070-06906380-9054-11ea-9ac4-a3240527207f.png)
- 開発者ツールでの表示
![image](https://user-images.githubusercontent.com/34566290/81247096-190a9d00-9054-11ea-8b7c-9b7857d8df80.png)

## 期待する見せ方・挙動 / Expected Behavior
- `<br>` 以降の要素も表示される

## 動作環境・ブラウザ / Environment
- 検証環境: Windows 10 Home 1909 64 bit + Chrome 81.0.4044.129

**Comment by mcdmaster** [comment]
対応しました。
詳細は、 #4038 をご覧ください

**Comment by MaySoMusician** [comment]
@mcdmaster 確認しました！ ご対応ありがとうございました

**Comment by mcdmaster** [comment]
本件、クローズをお願いしてもよろしいでしょうか？
