### ISSUE TITLE
DataTable用のデータのsort処理を正しくする

### ISSUE THREAD

**Issue by miyaoka** [tokyo-metropolitan-gov/covid19#395]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem

https://github.com/tokyo-metropolitan-gov/covid19/blob/83a5d4aaae049298c626371e56c48c66843e7250/utils/formatTable.ts#L35-L44

- DataTable用のデータフォーマット関数処理においてarrayのsortを行っているが、object同士の比較のため `(a, b) => (a === b ? 0 : a < b ? 1 : -1)` は全ての判定がfalseとなって必ず-1を返し、結果として元のJSONデータの逆順ソートとなっている
  - 元データが過去→現在の順に格納されているため、たまたまDataTableでは新しい順になっている
- `moment(d['リリース日']).format('MM/DD')` は invalidな日付の場合 `'Invalid date'` になるため `?? '不明'` になることがない

## 期待する見せ方・挙動 / Expected behavior

- ここではソートを行わず、DataTableでソートを行う
- sort用に数値化した日付情報をもたせる

**Comment by anyuKazu** [comment]
各objectのdata.jsonのリリース日の値を持たせておけば、以下のコードでソートできると思われます。
`tableDate.datasets.sort((a, b) => moment(b['リリース日']).diff(a['リリース日']))`

ただ期待する見せ方・挙動にある数値比較ではなく文字列比較なので、data.jsonのフォーマット変更に弱いです。

**Comment by ocean3fish** [comment]
#582 の議論で、コンフリクトが解消されないためクローズするという方針になりましたので、一旦閉じさせて頂きます。
