### ISSUE TITLE
「検査実施件数」グラフを保健所分と民間分の積み上げ棒グラフに変更

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#3957]
**こちらのissueの作業は、 `data/update-inspections_summary` ブランチをチェックアウトして行ってください。PRを出す先もこちらのブランチになります。**

#3806
#3828
#3851
#3906
これらのissueおよびPRで「検査実施件数」グラフを速報値がわかりやすくなるように左右色分けグラフにしましたが、「健康安全研究センターが行った検査件数」と「医療機関等が行った検査件数」の2色の積み上げ棒グラフにすることになりました。

## 積み上げ棒グラフの実装
【データ】
- 健康安全研究センターが行った検査件数
→ data.json `inspections_summary` の「都内」と「その他」の合計
- 医療機関等が行った検査件数
→ data.json `inspections_summary` の「保険適用分」

【色分け】
- 健康安全研究センターが行った検査件数
→濃い緑色（下）
- 医療機関等が行った検査件数
→薄い緑色（上）

## 注釈削除
グラフ上の3つの注釈を削除します。
```
（注）日々の速報値（医療機関が保険適用で行った検査は含まない）は、毎日更新
（注）医療機関が保険適用で行った検査件数を含む検査実施件数は、毎週金曜日に前週木曜日から当該週水曜日までの日々の保険適用分の件数を反映して更新
（注）医療機関が保険適用で行った検査については、４月２９日分までを計上
```
 
## テーブルの表示
#3851 の [こちら](https://github.com/tokyo-metropolitan-gov/covid19/pull/3851/files) でいったん削除した `dataTable` を復活させます。

***

#3374 #3579 でも要望があがっていたものです。ご提案ありがとうございました。

**Comment by Aqua-ix** [comment]
対応します
