### ISSUE TITLE
帰国者・接触者電話相談センター相談件数にて累積のタグに切り替えた時にタイトルがずれる

### ISSUE THREAD

**Issue by ebarakazuhiro** [tokyo-metropolitan-gov/covid19#398]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
端末サイズが375ポイント以下の場合に帰国者・接触者電話相談センター相談件数のタグを累計に切り替えると表示がずれてしまう。

## スクリーンショット / Screenshot
<img src="https://user-images.githubusercontent.com/7248391/75894745-06b78b80-5e78-11ea-97cb-f2c44a72aa83.png" width="300px">

## 期待する見せ方・挙動 / Expected behavior
タグを切り替えた場合でも枠内にtextが収まるようになる。

## 起こっている問題の再現手段 / Steps to reproduce
1. 375ポイント以下の端末にて https://stopcovid19.metro.tokyo.lg.jp/ を開く
2. 帰国者・接触者電話相談センター相談件数のタグを累計に切り替える

## 動作環境・ブラウザ / Environment
* iPhone6s safari

**Comment by daisuke-fukuda** [comment]
#293 

もしかしたら、こちらと同件かもしれません。（動作確認をしたわけではなく、issueを並べて見ただけなので、確実ではないです）

**Comment by kaizumaki** [comment]
@ebarakazuhiro ご指摘ありがとうございます！グラフのタイトルについては #391 で修正プルリクがマージ済みです。リリースをお待ちください！

**Comment by ebarakazuhiro** [comment]
@daisuke-fukuda @kaizumaki 
あ、確かにhttps://github.com/tokyo-metropolitan-gov/covid19/issues/293 と同じ事象ですね。
ありがとうございます。
