### ISSUE TITLE
「検査実施状況」チャートに保健所分と民間分を掲載

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4005]
**こちらのissueの作業は、 `data/update-inspection_status_summary` ブランチをチェックアウトして行ってください。PRを出す先もこちらのブランチになります。**

現在の「検査実施状況」チャートには「都内発生」と「その他」という分け方をしていますが、これを「健康安全研究センター実施分」と「医療機関等実施分」という分け方に変更します。

1. 修正前：都内発生分
↓
修正後：健康安全研究センター実施分
データ：data.json `inspection_status_summary` の「健康安全研究センター実施分」

1. 修正前：その他（チャーター機・クルーズ船等）
↓
修正後：医療機関等実施分
データ：data.json `inspection_status_summary` の「医療機関等実施分」

**Comment by ryuckel** [comment]
こちら対応しますね。
参照先のデータ(件数)と文言の変更をしたら`data/update-inspection_status_summary`PR出します。
認識に齟齬があったらご指摘ください
