### ISSUE TITLE
相談フローsvgのみを印刷できるようにする

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#401]
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
- Webサイトのみでしか情報を確認できない

## 期待する見せ方・挙動 / Expected behavior
- [flow](https://dev-covid19-tokyo.netlify.com/flow) の 相談フローsvgが単独でも有益で簡潔な情報のため、#251 の対応とは別に、この部分だけを印刷できるようにするとよさそう

試しに他の要素をすべて取り除いたら、調節せずともちょうどA4に収まり素敵でした (下記添付)

### PDFのスクショ
<img width="427" alt="スクリーンショット 2020-03-05 0 42 32" src="https://user-images.githubusercontent.com/8909592/75896316-41222800-5e7a-11ea-8da4-daa453feac5a.png">

**Comment by amotarao** [comment]
情報のアップデートができないのが欠点

印刷日時や最新情報はWebを見るようになどという注意書きの表示は必要そう

**Comment by barcarunrun** [comment]
とりあえず、できそうです。
<img width="1338" alt="Screen Shot 2020-03-05 at 1 12 16" src="https://user-images.githubusercontent.com/34545521/75899186-8a747680-5e7e-11ea-8cb7-a03ae80b2752.png">

**Comment by takanakahiko** [comment]
`page/flow.vue` の style で

```
@media print{
  .Flow-Heading, .only-sp, .SideNavigation {
    display: none;
  }
  .only-pc {
    display: block !important; 
  }
}
```

追加するといけますね

**Comment by barcarunrun** [comment]
@takanakahiko 
そうですね。微妙に違うのですが、コメントつきで作ったのでブランチ切って、プルリク投げます。
<img width="1219" alt="Screen Shot 2020-03-05 at 1 19 38" src="https://user-images.githubusercontent.com/34545521/75900087-bcd2a380-5e7f-11ea-9394-4ff60beaf3d7.png">

**Comment by amotarao** [comment]
#251 のようにページ全体を印刷する需要と、図のみを印刷する需要がありそうなので、
ページ全体にスタイルを追加すると危険そうな気がしています。

同じような事例では、時刻表サイトで時刻表部分のみを印刷できる機能があります。
https://www.jreast-timetable.jp/2002/timetable/tt1039/1039010.html

**Comment by amotarao** [comment]
別のものとして用意する場合、プリント用の汎用 layout コンポーネントを作成してページを用意するのではよいのではないかと考えます

雑にこんな感じ
```layouts/print.vue
<tempate>
  <div>
    <p>印刷日時: {{ Date }}</p>
    <p>最新の情報はWebをご覧ください</p>
    <nuxt />
  </div>
</tempate>
```

**Comment by amotarao** [comment]
||flowページ自体に図のみの印刷するstyleを掛ける|図のみを印刷する別ページを用意する|
|:--|:--|:--|
|:+1:|<ul><li>印刷を押すだけで勝手にキレイな印刷物ができている|<ul><li>layoutファイルを用意することで、他の図にも対応できる<li>通常ページの仕様を統一できる|
|:-1:|<ul><li>ページ全体を印刷する需要に対応できない<li>ページごとに仕様が異なる</ul>|<ul><li>図のみを印刷できることに気づいてもらえない可能性がある</ul>|

@barcarunrun @takanakahiko 上記、どちらにもメリデメがあると思うのですが、いかがでしょうー？

**Comment by takanakahiko** [comment]
個人的な意見としては「図のみを印刷する別ページを用意する」が良いかなと思います．
大きめに「印刷はこちらからどうぞ」みたいな文言があれば誘導は可能かと．

「flowページ自体に図のみの印刷するstyleを掛ける」のデメリットとして，例えば東京都生活文化局で「印刷することでWebページ全体の見た目を確認する」ような業務があった場合に混乱するかもしれません．
また，万が一サイドバーの class が変更されたときに，この機能についての修正が忘れ去られる可能性が高いと思います．

そのため，印刷機能は切り出して別ページにしたほうが良いかなと思います．

**Comment by amotarao** [comment]
#534 で図のみ印刷する別ページを作成してみました
