### ISSUE TITLE
[/flow] 相談フローページのテキスト全面修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4030]
相談フローページのテキスト修正をお願いします。
[東京都福祉保健局のHPの相談フロー図](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html) が修正されたことにともない、当サイトの相談フローページ（flow）も修正することになりました。

以下のエクセルが、変更前・変更後の対照表です。
[相談フロー図新旧対照表.xlsx](https://github.com/tokyo-metropolitan-gov/covid19/files/4603448/default.xlsx)
「変更後」の黄色いセルが、修正箇所です。

***
こちらの修正とともに、タイトルの黄色い部分「現在改修中」を削除してください。
![スクリーンショット 2020-05-09 23 10 18](https://user-images.githubusercontent.com/14883063/81475991-55075300-924a-11ea-94b7-397e3164cc34.png)
***

なにか疑問点あればコメントしてください！

**Comment by kaizumaki** [comment]
@MaySoMusician 文章中の下線部分を表現するi18nマークアップを指示していただけますか？

（以下、相談フロー図新旧対照表.xlsxからのスクショ）

![スクリーンショット 2020-05-10 8 48 27](https://user-images.githubusercontent.com/14883063/81487751-793f5000-929b-11ea-9d5e-d36a8535e26e.png)

**Comment by MaySoMusician** [comment]
該当部分を `<span class="someClass">` で囲い、 `.someClass` に対して `text-decoration: underline` のがHTML5での方法の様です

```vue
<i18n path="発熱や咳などの{mildSymptom}がある">
  <template v-slot:mildSymptom>
    <span class="class1">
      {{ $t('比較的軽い風邪の症状') }}}
    </span>
  </template>
</i18n>

<i18n path="息苦しさ（呼吸困難）、強いだるさ（倦怠感）、高熱等の{severeSymptom}がある">
  <template v-slot:severeSymptom>
    <span class="class1">
      {{ $t('強い症状') }}}
    </span>
  </template>
</i18n>

<style>
.class1 {
  text-decoration: underline;
}
</style>
```

**Comment by mcdmaster** [comment]
為念確認です。修正対象ファイルは、以下の２つでよろしいでしょうか？
- pages/flow.vue
- assets/locales/ja.json

**Comment by kaizumaki** [comment]
@mcdmaster ありがとうございます！i18n関係は、現在自動で翻訳キーの登録・削除を行っていますので、 `pages/flow.vue` だけ修正してもらえれば大丈夫です。
