### ISSUE TITLE
インフォメーションのリンク箇所の要素整理

### ISSUE THREAD

**Issue by chanoha** [tokyo-metropolitan-gov/covid19#4036]
## 改善詳細 / Details of Improvement
- リンク先が同じなのにリンク箇所が2つありややこしいため、まとめて一つの言葉にしてリンクするのはいかがでしょうか。

## スクリーンショット / Screenshot
<img width="768" alt="スクリーンショット 2020-05-10 12 56 21" src="https://user-images.githubusercontent.com/16644982/81490762-faf5a480-92c0-11ea-9c74-475d4b008630.png">

## 期待する見せ方・挙動 / Expected behavior
- 左のテキストリンクを「自分の家族や症状に不安がある方はこちら」として、右の「相談の手順を見る」ボタンを取る。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ooshimizu** [comment]
このissue私がやりたいです！

**Comment by ooshimizu** [comment]
対応してみました。  
こちらでよろしいでしょうか。 #4118

**Comment by chanoha** [comment]
@ooshimizu 
対応いただきありがとうございます！
イメージ通りです 🙇

**Comment by kaizumaki** [comment]
@chanoha ご提案ありがとうございます。お待たせしてしまい申し訳ありません。こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/4118#issuecomment-678956089 にコメントしましたが、東京都に確認しましたところ、ボタンはなくさずに左のテキストのリンクを外す方向でお願いしたいとのことでした。
↓イメージ
![スクリーンショット 2020-08-24 16 27 42](https://user-images.githubusercontent.com/14883063/91015842-c9fa6f00-e626-11ea-8969-cc3ea7236509.png)
