### ISSUE TITLE
新規グラフ「判明日別陽性患者数」の作成

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4037]
**こちらのissueの作業は、 `data/add-positive_rate-and-diagnosed` ブランチをチェックアウトして行ってください。PRを出す先もこちらのブランチになります。**

５月８日から [東京都のホームページ](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/1007844.html) において陽性率を公表するようになりました。
当サイトでも陽性率に関連するグラフを追加します。

こちらのissueでは、判明日ベースの陽性患者数のグラフの新規作成をお願いします。
陽性率の算出は、判明日を基準としているためです。
従来の「陽性患者数」のグラフは、報道発表ベース（保健所からの届出日ベース）なので、このまま残します。

- データは `data/positive_by_diagnosed.json` となります。
- 注釈は後ほどお知らせします（こちらのissueでコメントします）。
- 配置する位置ものちほどお知らせします。

なにか疑問点あればコメントしてください！

**Comment by ryuckel** [comment]
こちら対応しますね。bar-chartで作成する認識でおりますが、誤っていたらご指摘ください。

**Comment by kaizumaki** [comment]
@ryuckel ありがとうございます！現在ある「陽性患者数」のグラフと同様、bar-chartでOKです。

**Comment by ryuckel** [comment]
@kaizumaki 
グラフの描画まではできました。
参考までにスクショを載せておきます。
配置と注釈が決まりましたらお知らせください！

<img width="431" alt="スクリーンショット 2020-05-10 23 54 47" src="https://user-images.githubusercontent.com/36391432/81502608-e85b8980-9319-11ea-954e-9f0fcfbfb9c3.png">

**Comment by kaizumaki** [comment]
@ryuckel 注釈の件、お待たせしております。いつになるかわからないので、とりあえず現時点での実装をDraft Pull Requestとして提出しておいてもらえますか？（明日リリースを予定しているため、緊急の場合は運営で引き取ります。）

**Comment by ryuckel** [comment]
@kaizumaki 
上記のスクショのスタイルで一番下に配置した状態でDraft Pull Request出しました
