### ISSUE TITLE
翻訳キーの修正

### ISSUE THREAD

**Issue by y-chan** [tokyo-metropolitan-gov/covid19#4070]
## 起こっている問題 / The Problem
- 複数あった「その他」が一つになった(「その他.graph」が消えた)ことで、翻訳ファイル自動生成スクリプトに問題が生じた
https://github.com/tokyo-metropolitan-gov/covid19/pull/4062/files#diff-bfc7fda8df09e3e9ec8810b8bff5bf77R399
- これにより、今まで「その他」と表記されていた部分が「その他.parent」と表記されてしまっている
- 「その他.parent」を「その他」に変え、元の翻訳を復元する(ja.jsonは編集せず、使われている部分を編集してください)
https://github.com/tokyo-metropolitan-gov/covid19/blob/a4b108aac273f0353003f7a184169bae379b7c81/pages/parent.vue#L75

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/34832037/81520938-b9c4c980-9380-11ea-8f22-77f1b74e223b.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「その他.parent」が「その他」と表記されるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/parent にアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@y-chan ご指摘ありがとうございます！気づきませんでした。`help-wanted` のラベルをつけておきますね。

**Comment by y-chan** [comment]
good-first-issue も良いかと思います
私が今対応出来ないので、他の方に対応していただければ助かります。

**Comment by izzymaru** [comment]
対応します

**Comment by izzymaru** [comment]
これで宜しいでしょうか。
https://github.com/tokyo-metropolitan-gov/covid19/pull/4074

**Comment by y-chan** [comment]
@izzymaru 問題ないです！

**Comment by izzymaru** [comment]
@y-chan ご確認ありがとうございます 🙇‍♂️
