### ISSUE TITLE
お問い合わせ先一覧ページのコンテンツ修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4078]
お問い合わせ先一覧（contacts）ページのコンテンツについて、以下のWordファイルのものへの差し替えをお願いします。

[お問い合わせ先一覧の変更イメージv6.docx](https://github.com/tokyo-metropolitan-gov/covid19/files/4609120/v6.docx)

- スタイルは現状のものを踏襲してください。
- ただし、現在 `height` がpx固定になっている部分は、`height` を指定しないように修正したほうがよさそうです（高さ固定にしない）。セル内は `padding` で余白をとってください。
- Word内で太字・文字サイズ大きめの部分は、指示通りに太字・フォントサイズ大きめにしてください。

なにかわからないことがありましたら、こちらのissueにコメントしてください！

**Comment by izzymaru** [comment]
@kaizumaki 対応します

**Comment by kaizumaki** [comment]
@izzymaru よろしくお願いします！

**Comment by izzymaru** [comment]
@kaizumaki これで宜しいでしょうか。https://github.com/tokyo-metropolitan-gov/covid19/pull/4080
