### ISSUE TITLE
「陽性患者数」グラフのデザイン変更（遅延判明分をわかりやすく）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4092]
5/11に[東京都の発表](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/1007863.html) があり、いままでに陽性患者情報の報告漏れと二重計上があったことがわかりました。
当サイトでも「陽性患者数」のグラフに遅延判明分をわかりやすく表示するようにデザインを修正します。
現時点では積み上げ棒グラフの形式を予定しています。

※データの準備がある上、至急対応でリリースしますので、こちらのissueは運営で引き取ります。

**Comment by kaizumaki** [comment]
@soutaito さん、お願いします。

**Comment by kaizumaki** [comment]
@soutaito グラフのタイトル修正と注釈がきました。
- グラフタイトル
```
陽性患者数（保健所届出日別）
```
- 注釈
```
（注）保健所から発生届が提出された日を基準とする
（注）医療機関等が行った検査も含む
（注）チャーター機帰国者、クルーズ船乗客等は含まれていない
```

**Comment by kaizumaki** [comment]
@soutaito それと都から指摘があり、右上の数字の下の「実績値」という文言を「日別値」に修正してほしいです（「累積値」のほうはそのままで大丈夫です）。
ちなみに同様の修正を #4079 でやってもらっています。

**Comment by kaizumaki** [comment]
@soutaito グラフタイトルの修正の依頼が来ました。以下でお願いできますでしょうか。
- グラフタイトル
```
新規患者に関する報告件数の推移
```

**Comment by soutaito** [comment]
@kaizumaki 
手元で実装してみました。積み上げ棒グラフの表現はわかりづらく、利用者を混乱させてしまうかもしれません。


![都内の最新感染動向_東京都_新型コロナウイルス感染症対策サイト (2)](https://user-images.githubusercontent.com/1763230/81646525-5745f900-9466-11ea-8f16-39b7c080787f.png)

**Comment by kaizumaki** [comment]
@soutaito ありがとうございます！そうですね、確かに積み上げである意味がよくわからなくなっていますね。凡例もスイッチしたときによくわからない感じになりそうですし。
なにより二重計上分の削除の表現ができないですね。
これは単純棒グラフに戻したほうがいいかもしれません。都に相談してみます。

**Comment by kaizumaki** [comment]
@soutaito スクショを都に見てもらいました。やはりよくわからないということで、混乱を避けるためにも単純棒グラフへ戻すこととなりました。お手数おかけしますが、ご対応お願いします。
結果、 [グラフタイトル](https://github.com/tokyo-metropolitan-gov/covid19/issues/4092#issuecomment-627122523) と [注釈](https://github.com/tokyo-metropolitan-gov/covid19/issues/4092#issuecomment-627082156) のみの変更となります。
あと、注釈はグラフの上部の位置に移動してください。
右上数字の下の [「日別値」への文言修正](https://github.com/tokyo-metropolitan-gov/covid19/issues/4092#issuecomment-627083753) もお願いします。
