### ISSUE TITLE
「検査実施件数」グラフに注釈を追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4105]
「検査実施件数」グラフに、以下の注釈の追加をお願いします。
位置は、いまある注釈の一番上（以下画像の赤枠部分）です。

```
（注）検査結果の判明日を基準とする。ただし、一部検体採取日に基づくものを含む
```
![検査実施件数](https://user-images.githubusercontent.com/14883063/81690490-4f9e4880-9496-11ea-889f-593b117531bc.jpg)

**Comment by Nekoya3** [comment]
#4103 に合わせて対応します！

**Comment by kaizumaki** [comment]
@Nekoya3 ありがとうございます！ 🙏

**Comment by Nekoya3** [comment]
![image](https://user-images.githubusercontent.com/17000370/81692022-c0466480-9498-11ea-80f7-3a944f4a92e9.png)
:+1:
