### ISSUE TITLE
陽性患者の人数を年齢別でグラフで表示する

### ISSUE THREAD

**Issue by intomyam** [tokyo-metropolitan-gov/covid19#412]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem

- 都内の最新感染動向ページの `陽性患者の属性` は、一人一人の属性が書いてあるものの、属性ごとの人数がわからない

## スクリーンショット / Screenshot

<img width="1440" alt="スクリーンショット_2020-03-05_1_55_36" src="https://user-images.githubusercontent.com/10085763/75903140-7f244980-5e84-11ea-851c-abd465b80d0c.png">

## 期待する見せ方・挙動 / Expected behavior

- 年齢ごとの陽性患者数を見せる

<img width="312" alt="スクリーンショット 2020-03-05 2 28 14" src="https://user-images.githubusercontent.com/10085763/75905857-fe1b8100-5e88-11ea-89f2-d8b6676c249d.png">

## 動作環境・ブラウザ / Environment

- mobileは別のUIになっているので、別のデザインが必要

**Comment by garily** [comment]
前日この Issue を以下のようにして、その修正を PR で提出いたしました。
![Screen-Recording-2020-03-06-at-6 21 56-PM](https://user-images.githubusercontent.com/15998246/76135027-164de600-5fd8-11ea-9655-a309290db0d2.gif)

ただいま `development` の[最新 commit (6e176c1)](https://github.com/tokyo-metropolitan-gov/covid19/commit/6e176c19267f32af8da87d5a00acb1cfad9e8e83) によって PR をアップデートしました。

**Comment by kaizumaki** [comment]
@intomyam ご提案ありがとうございます。こちら https://github.com/tokyo-metropolitan-gov/covid19/pull/454#issuecomment-617671788 にコメントいたしました。ご理解いただきますようよろしくお願いいたします。

**Comment by kaizumaki** [comment]
都からの正式な回答がありましたので、こちらのissueはクローズさせていただきます。

**Comment by intomyam** [comment]
@kaizumaki 
ご確認ありがとうございます 😸
