### ISSUE TITLE
英語版で検査陽性者の状況の右側が切れていて読めない

### ISSUE THREAD

**Issue by capra314cabra** [tokyo-metropolitan-gov/covid19#4124]
## 起こっている問題 / The Problem
言語を英語に設定した状況で、検査陽性者の状況(英語版: Details of people testing positive)のコンテンツの右側が切れている

## スクリーンショット / Screenshot
![Chrome](https://user-images.githubusercontent.com/28725713/81758376-87d87200-94fc-11ea-998c-19314ab8f134.png)

## 期待する見せ方・挙動 / Expected Behavior
退院した人の数字を英語版でも難なく見ることができるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
サイトをEnglishに切り替える

## 動作環境・ブラウザ / Environment
- Windows
- Chrome / Firefox / Edge で確認

**Comment by izzymaru** [comment]
@kaizumaki 日本語版でもそうです。

<img width="940" alt="Screen Shot 2020-05-13 at 14 59 10" src="https://user-images.githubusercontent.com/3105613/81778390-bcb0ed00-952d-11ea-9528-f4ac90e97eac.png">

対応します。

**Comment by kaizumaki** [comment]
@capra314cabra issueありがとうございます。こちらの現象は認識していたのですが、急ぎリリース準備を進めたので、あとまわしになっていました。
@izzymaru よろしくお願いします！

**Comment by izzymaru** [comment]
@kaizumaki 修正しました https://github.com/tokyo-metropolitan-gov/covid19/pull/4139

**Comment by goki90210** [comment]
具体的にどうすればいいかはわからないですが、
縦横を入れ替えると折返しが少なくなって読みやすくなるかもと思いました。
