### ISSUE TITLE
pages/card/_card.vue の重複処理

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4128]
## 起こっている問題 / The Problem
- pages/card/_card.vue の 138～140行目、146～148行目、150～152行目の処理が重複している。

## スクリーンショット / Screenshot

なし

## 期待する見せ方・挙動 / Expected Behavior
 pages/_card.vue の132～152行目
<pre>
      case 'agency':
        title = this.$t('都庁来庁者数の推移')
        updatedAt = agencyData.date
        break
      case 'positive-number-by-diagnosed-date':
        title = this.$t('陽性患者数（検査結果判明日別）')
        updatedAt = PositiveByDiagnosedData.date
        break
      case 'positive-rate-first':
        title = this.$t('都庁来庁者数の推移')
        updatedAt = agencyData.date
        break
      case 'positive-rate-second':
        title = this.$t('都庁来庁者数の推移')
        updatedAt = agencyData.date
        break
</pre>
を
<pre>
      case 'agency':
      case 'positive-rate-first':
      case 'positive-rate-second':
        title = this.$t('都庁来庁者数の推移')
        updatedAt = agencyData.date
        break
      case 'positive-number-by-diagnosed-date':
        title = this.$t('陽性患者数（検査結果判明日別）')
        updatedAt = PositiveByDiagnosedData.date
        break
</pre>
とすべきではないか。

## 起こっている問題の再現手段 / Steps to Reproduce
なし

## 動作環境・ブラウザ / Environment
- 動作環境に依存しない

**Comment by kaizumaki** [comment]
@goki90210 ご指摘ありがとうございます。現在、マージ待ちのPRがあるので、 `pages/card/_card.vue` の内容も変わると思います。しばらくお待ちいただいて、ご確認いただければと思います。

**Comment by goki90210** [comment]
わかりました。

**Comment by Nekoya3** [comment]
@goki90210  
ご指摘ありがとうございます。
私の実装ミスです。
First Secondについては削除され、一つのカードに統合されたタイミングで正しい状態に変更しました。

**Comment by Nekoya3** [comment]
#4108 にて修正を行っていますので確認いただけますと幸いです

**Comment by goki90210** [comment]
@Nekoya3 
差分を見たところ問題なさそうです。
ありがとうございます。

**Comment by kaizumaki** [comment]
@goki90210 こちらのissueはクローズでよろしいでしょうか？

**Comment by goki90210** [comment]
@kaizumaki マージも確認できましたので問題ありません。
ありがとうございました。
