### ISSUE TITLE
Buildの失敗

### ISSUE THREAD

**Issue by izzymaru** [tokyo-metropolitan-gov/covid19#4137]
## 起こっている問題 / The Problem
- axe-coreがpackage.jsonに入ってない為Build失敗します。

## スクリーンショット / Screenshot

<img width="765" alt="Screen Shot 2020-05-13 at 15 16 28" src="https://user-images.githubusercontent.com/3105613/81778915-a22b4380-952e-11ea-9f5f-fda174b8beda.png">

localhost:3000 👇

![core-axe](https://user-images.githubusercontent.com/3105613/81778920-a5beca80-952e-11ea-93ee-69bdefaa9ac1.png)

## 期待する見せ方・挙動 / Expected Behavior
- Build成功

## 起こっている問題の再現手段 / Steps to Reproduce
1. Fork
2. Build

## 動作環境・ブラウザ / Environment
- macOS

**Comment by goki90210** [comment]
yarn.lockにはaxe-coreはありますよね…。

<pre>
axe-core@3.5.3:
  version "3.5.3"
  resolved "https://registry.yarnpkg.com/axe-core/-/axe-core-3.5.3.tgz#5b7c0ee7c5197d546bd3a07c3ef701896f5773e9"
  integrity sha512-HZpLE7xu05+8AbpqXITGdxp1Xwk8ysAXrg7MiKRY27py3DAyEJpoJQo1727pWF3F+O79V3r+cTWhOzfB49P89w==
</pre>

yarn upgradeを実行すると上記のエラーが出ることがあるのは確認しています。

**Comment by izzymaru** [comment]
@goki90210 npm 6.13.6でインストールしました。すみませんでした 🙇‍♂️
yarn 1.22.4で確認出来ました。問題ないです。
