### ISSUE TITLE
「陽性率」グラフのテーブルに陽性者数と陰性者数の合計値を載せたい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4140]
## 改善詳細 / Details of Improvement
「検査実施人数（陰性確認を除く）と陽性率の推移」のグラフが実装されました。
グラフ下部のテーブルに「陽性者数」と「陰性者数」の合計値の列を表示させたいです。

## 期待する見せ方・挙動 / Expected behavior
- テーブルに、陽性者数＋陰性者数の値の列を入れる
- 列見出しの文言は、のちほど都から指示があります

![陽性率グラフ](https://user-images.githubusercontent.com/14883063/81784371-b7f13680-9537-11ea-9201-d7153fc217b3.jpg)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
対応します

**Comment by Nekoya3** [comment]
![image](https://user-images.githubusercontent.com/17000370/81794917-72883580-9546-11ea-915a-77086864076c.png)
一時的に陽性者数＋陰性者数という列見出しにしてありますが、実装終了したのでPRにします。
