### ISSUE TITLE
PositiveRateMixedChart.vue の thタグに scope属性がない

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4141]
## 起こっている問題 / The Problem
- #3950 と同じ対応を components/PositiveRateMixedChart.vue でも行う必要がある。

## 期待する見せ方・挙動 / Expected Behavior
- thタグにscope="row"を追加する。

## 起こっている問題の再現手段 / Steps to Reproduce
なし

## 動作環境・ブラウザ / Environment
- 動作環境に依存しない

**Comment by Nekoya3** [comment]
対応します
