### ISSUE TITLE
「検査実施件数」グラフの注釈を修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4178]
「検査実施件数」グラフの以下の注釈の修正をお願いします。

修正前： `（注）検査結果の判明日を基準とする。ただし、一部検体採取日に基づくものを含む`
↓
修正後： `（注）検体採取日を基準とする。ただし、一部検査結果判明日に基づくものを含む`

**Comment by dymori** [comment]
こちらやらせて頂きたいです！（まだ開発環境設定してません）

**Comment by kaizumaki** [comment]
@dymori ありがとうございます！開発環境でなにかわからないことがあれば遠慮なくコメントしてくださいね。

**Comment by dymori** [comment]
@kaizumakiさん、遅れてすみません！環境せってした後、会社のパソコンに液体を溢してしまい、トラブってしまいました。

翻訳のJSONは自動？に作成されるかと思ったので、触らなかったです！もし追加の必要でしたら、ご指摘いただければ対応します！
