### ISSUE TITLE
本リポジトリのOGP変更

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#419]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* [本番サイト](https://stopcovid19.metro.tokyo.lg.jp/) とOGPが同じなので、紛らわしい。

## 期待する見せ方・挙動 / Expected behavior
* こちらのOGPには開発用リポジトリとわかる文字を追加したい。「東京都公式 COVID-19 対策サイト 開発用リポジトリ」かなぁ

**Comment by ocean3fish** [comment]
多言語化進行中のため、このあたりが落ち着いてから検討が良さそうですね。
https://github.com/tokyo-metropolitan-gov/covid19/issues/1190

**Comment by ocean3fish** [comment]
優先度あまり高くないと思われるのと、かなり状況が変わってきているため、一旦クローズします。
必要になった際にre-openか別issueでも良いかと。
