### ISSUE TITLE
退院列の「〇」に別の文字が含まれる

### ISSUE THREAD

**Issue by y-chan** [tokyo-metropolitan-gov/covid19#4194]
## 起こっている問題 / The Problem
- 陽性患者の属性の退院列の「〇」に誤差(別の文字)があるので、翻訳されていない
- 以下のコミットから。
  - https://github.com/tokyo-metropolitan-gov/covid19/commit/b9aa85d57adbf617b50639e78292bcb72bf1fd7f
  - https://github.com/tokyo-metropolitan-gov/covid19/commit/a52491f65a363de9eb6f0c43e95e26671861bf29

- なお、この問題は元のデータの問題と思われ、このrepoにPRを送ることでは解決できないと思われる。なお、別の文字を正しい文字に置き換える処理にすることは可能と思われる。

## 期待する見せ方・挙動 / Expected Behavior
- 文字が統一される

**Comment by kaizumaki** [comment]
@y-chan こちらの件、元データが修正されましたので、 `data.json` も修正されたと思います。ご確認いただけれるとうれしいです。

**Comment by y-chan** [comment]
確認しましたー！
解決したという認識なので、このIssueはcloseします！
