### ISSUE TITLE
「このサイトから派生したもの」に記載するサイト条件の明確化

### ISSUE THREAD

**Issue by tanakaKSUK** [tokyo-metropolitan-gov/covid19#4198]
## 改善詳細 / Details of Improvement

- 派生したサイトは複数あるが記載されていないサイトとされているサイトの違いが判らず管理しにくいので、記載するサイトの条件を明確化し、FORKED_SITES.mdに記載する

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected behavior

> 記載条件
> 
> - 定期的に管理されていること
> 
> - [Principle/行動規範](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/CODE_OF_CONDUCT.md)を遵守していること

（注）記載条件については議論が必要だと思います。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
> Build with people
> - 都庁の人だけではなく、様々な人々とともに作る

が厳密にはフォークサイトには当てはまらないですよね…。

**Comment by kaizumaki** [comment]
FORKED_SITES.mdの更新もだいぶ落ち着きましたので、こちらのissueは一旦クローズとしますね。
