### ISSUE TITLE
「判明日別陽性者数」グラフの最新人数に対する説明文を変更したい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4199]
「PCR検査陽性者の発生動向（確定日別による陽性者数の推移）」（通称：判明日別陽性者数）グラフの右上の値に対する説明文を変更したいです。
このグラフの最新値は、「新規患者に関する報告件数の推移」グラフと違い、過去にさかのぼって修正される値だからです（最新値は、報告があった時点のものであり、陽性と判明した日に計上するのは後日となるため）。
なので、「前日比」という表現が実質意味をなさなくなります。

![判明日別陽性者数](https://user-images.githubusercontent.com/14883063/82109051-44853a00-976e-11ea-93f0-436f5b17292b.jpg)

変更したい文言は以下です。
- 日別の場合（カッコ内が変わります）
```
5/14 日別値（現在判明している人数であり、後日修正される場合がある）
```
- 累計の場合（カッコは削除です）
```
5/14 累計値
```
***
コンポーネントの構成上、この部分は `components/DataViewBasicInfoPanel.vue` で共通化しており、このグラフのコンポーネントのみ表示を変更するのは少々コツがいると思います。
うまい実装方法の提案を募集しています。

**Comment by izzymaru** [comment]
対応します

**Comment by kaizumaki** [comment]
@izzymaru ありがとうございます！よろしくお願いします！

**Comment by izzymaru** [comment]
@kaizumaki PR出しました
