### ISSUE TITLE
グラフの全体像を見ることができるようにしたい

### ISSUE THREAD

**Issue by Nekoya3** [tokyo-metropolitan-gov/covid19#4208]
## 改善詳細 / Details of Improvement
- 現在、横スクロール機能の実装の関係でグラフの全体像を見ることができない

## 期待する見せ方・挙動 / Expected behavior
- 全体像が見えるような形にしたい。
- 北海道版のスライダ・apexchartなどでの2段のグラフなどで対応可能？

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by linuxmetel** [comment]
全体像と横スクロールは別に作るのですか、それとも置き換えるのですか？

**Comment by linuxmetel** [comment]
[北海道のサイト](https://stopcovid19.hokkaido.dev/)のようにするということでしょうか？

**Comment by kaizumaki** [comment]
@Nekoya3 例えばapexchartだとどのようなビジュアルになるのか、提示してもらえるとうれしいです。

**Comment by Nekoya3** [comment]
![image](https://user-images.githubusercontent.com/17000370/82731041-0de78a80-9d3f-11ea-833a-08f337b979d8.png)
ダミーデータですが、apexchartで実装するとしたら下段が全体、上段が一部の表示ですね。
北海道版のようにsliderのようにしてもよいかなと思います1
