### ISSUE TITLE
オープンデータcsvファイルの置き場

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#423]
オープンデータ（csvファイル）を下記ディレクトリに置き、公開したいです。

本日時点では
- 都側でオープンデータ（csvファイル）を用意する
- csvをsharepointに上げる（予定）
- 下記ディレクトリでcsv公開する
URL例：https://stopcovid19.metro.tokyo.lg.jp/data/xxx.x.csv 
カタログサイトには、こちらをデータリソースとして登録します。

**Comment by halsk** [comment]
まず URL を確定しましょう。

| データ名 |  URL |
| -------- | ---- |
| 陽性患者数 | `/data/patients_summary.csv` |
| 陽性患者の属性 | `/data/patients.csv` |
| 新型コロナコールセンター相談件数 | `/data/contacts` |
| 帰国者・接触者電話相談センター相談件数 | `/data/querents.csv` |

@mikkame さんか @osoken さん、これで JSON 側と合っていますか？

**Comment by NaoyaShimizzz** [comment]
URL確定させるので、少々お待ちください。
https://docs.google.com/document/d/1XWz7UCe9RQTAD3XFOKh_GY-llUwembRr-1Bv5bltG9U/edit#
例）東京都患者発生発表数
130001_tokyo_infected_per_date
命名規則はこちらで。

陽性患者発表者数のファイルをアップデートしてこれをCSV化します
https://codeforjapan.sharepoint.com/:x:/r/sites/covid19/_layouts/15/Doc.aspx?sourcedoc=%7BED81EE19-3538-4F94-BE29-9F38BD23FDB6%7D&file=%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%82%A3%E8%80%85%E7%99%BA%E7%94%9F%E7%99%BA%E8%A1%A8%E6%95%B0-RAW.xlsx&action=default&mobileredirect=true

**Comment by NaoyaShimizzz** [comment]
陽性患者数も陽性患者の属性の同じデータソースになるので、
どちらも
/data/130001_tokyo_covid19_patients.csv
でお願いします。V3時点でオープンデータ化されるのはこれのみです。

**Comment by halsk** [comment]
ありがとうございます！

**Comment by halsk** [comment]
@NaoyaShimizzz さん
こういうことで良いですか？
陽性患者数 | /data/130001_tokyo_covid19_patients.csv
陽性患者の属性 | /data/130001_tokyo_covid19_patients.csv
新型コロナコールセンター相談件数 | まだ無し
帰国者・接触者電話相談センター相談件数 | まだ無し

**Comment by NaoyaShimizzz** [comment]
データリソースという意味ではそうです。
ややこしいんですが、カードへのリンクは都のカタログサイトのほうへお願いします。こちらにも記載しました。
https://github.com/tokyo-metropolitan-gov/covid19/issues/315#issuecomment-595048384

**Comment by mtenjin** [comment]
元データはこちらです。
SharePointフォルダー：「オープンデータ」
ファイルパス： https://codeforjapan.sharepoint.com/sites/covid19/DocLib5/130001_tokyo_covid19_patients.csv

流れとしては、以下を想定しています。
1) SharePoint上の東京都患者発生発表数.xlsx を読み取って、CSV化
2) 上記のフォルダーにアップロード
3) そこから https://stopcovid19.metro.tokyo.lg.jp/data/xxx.x.csv にコピー
4) 上記をScheduledの自動実行で（午前8時のページ更新と同時に。ゆくゆくはです）

**Comment by halsk** [comment]
@mtenjin さん
先行して本番サーバの以下の場所にCSVファイルを置きました。データセットのページは先に作ってしまったらまずいものですか？
https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients.csv

**Comment by mtenjin** [comment]
作ってしまってください！よろしくお願いします！！
