### ISSUE TITLE
37.5℃以上の発熱が4日以上 の受診目安を修正 [お子様をお持ちの皆様へ]

### ISSUE THREAD

**Issue by rikupin1105** [tokyo-metropolitan-gov/covid19#4266]
## 改善詳細 / Details of Improvement
- お子様をお持ちの皆様へ のページの  37.5℃以上の発熱が4日以上続いている の という部分を削除する
## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@rikupin1105 ご指摘ありがとうございます。たしかにそうですね。おそらくテキスト差し替えとなると思います。確認しますね。

**Comment by kaizumaki** [comment]
都に確認とりました。以下のように修正いただければと思います。

**修正前：**
風邪の症状や、37.5℃以上の発熱が4日以上続いている、強いだるさ（倦怠感）、息苦しさ（呼吸困難）がある場合は、各保健所にご相談ください。
　↓
**修正後：**
息苦しさ（呼吸困難）、強いだるさ（倦怠感）、高熱等の強い症状がある場合、または発熱や咳などの比較的軽い風邪の症状が続いている場合は、各保健所にご相談ください。

**Comment by rikupin1105** [comment]
asset > locales > ja.json をそのまま編集すればいいのでしょうか？

**Comment by kaizumaki** [comment]
@rikupin1105 おっしゃるとおり、 `ja.json` の翻訳キーはそのままで、原文を編集していただく形になります。
