### ISSUE TITLE
やさしいにほんご　でコードらしき物がページに出ている件について

### ISSUE THREAD

**Issue by linuxmetel** [tokyo-metropolitan-gov/covid19#4267]
## 起こっている問題 / The Problem
- [学校（がっこう）が 休（やす）みの あいだ、きをつける こと
](https://stopcovid19.metro.tokyo.lg.jp/ja-basic/parent) で「**そのほかのことについて**」が「**{"parent": "そのほかの こと について", "graph": "そのほかの こと について" }**」と表示されている。
## スクリーンショット / Screenshot
![Screenshot from 2020-05-19 16-27-04](https://user-images.githubusercontent.com/61399424/82297580-cf279c80-99ed-11ea-811e-274f2e003534.png)

## 期待する見せ方・挙動 / Expected Behavior
- 単に「そのほかのことについて」と表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. [学校（がっこう）が 休（やす）みの あいだ、きをつける こと](https://stopcovid19.metro.tokyo.lg.jp/ja-basic/parent)を開く

## 動作環境・ブラウザ / Environment
macOS / Windows / Linux / iOS / Android
Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by linuxmetel** [comment]
開発版サイトも同じ問題が起きています。
[開発版サイトのリンク](https://dev-covid19-tokyo.netlify.app/ja-basic/parent)

**Comment by junya-ishibuchi** [comment]
こちら対応させていただきます。

**Comment by junya-ishibuchi** [comment]
こちら確認しました。
結論としましてはコード上(GitHub上)での修正ではないようなので、一旦私は作業から離れます。

**原因：**
#4070 にて、翻訳キーの修正が行われたことにより、
```"その他"``` のキーの値がそのまま出ている状態。
日本語では、```"その他"```の値は```"その他"```のため、問題なく表示されますが、
"やさしいにほんご" のみならず、その他の言語では、以前の値のままであるため、
コードらしき物が出現しております。

**解決方法：**
Transifexで、日本語以外の言語の```"その他"``` の翻訳内容を正しく修正する。
※翻訳先の言語に対する追加・変更・削除は全てTransifexで行うとのことですので、GitHub上で取り扱うものでないと存じております。
