### ISSUE TITLE
function customSort の処理が複雑すぎる

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4268]
## 起こっている問題 / The Problem
- components/cards/ConfirmedCasesAttributesCard.vue の function customSort のコードの複雑度(Cognitive Complexity)が29になっている（理想は15以下）

（優先度は高くありません。）

このメソッドのコードが長すぎるというのもあると思います。

## スクリーンショット / Screenshot

![ConfirmedCasesAttributesCard1](https://user-images.githubusercontent.com/30145857/82304161-ec149d80-99f6-11ea-8da0-aa0dc56e8cc0.png)
![ConfirmedCasesAttributesCard2](https://user-images.githubusercontent.com/30145857/82304178-f20a7e80-99f6-11ea-9bae-81d5aaa07fe0.png)

## 期待する見せ方・挙動 / Expected Behavior
- Cognitive Complexityを15以下にする。

## 起こっている問題の再現手段 / Steps to Reproduce
1. SonarQube 8.xでTypeScriptのルール設定を"Sonar way recommended"にして解析させる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
やってみました。上記 #4338 をご確認ください

**Comment by goki90210** [comment]
ありがとうございます。確認したところ19まで減っていました。
（何故か33と表示されていますが…、カウントは19です）
![ConfirmedCasesAttributesCard3](https://user-images.githubusercontent.com/30145857/82520399-05385e00-9b5f-11ea-9458-e3621ec6d0c4.png)
![ConfirmedCasesAttributesCard4](https://user-images.githubusercontent.com/30145857/82520406-08334e80-9b5f-11ea-8e67-4a136ab7d3c5.png)

**Comment by mcdmaster** [comment]
むむっ。私の見方が悪かったのか、もっと低減できていると思い込んでしまっていました。
もう少し頑張ってみましょうか

**Comment by Nekoya3** [comment]
これを行う理由はコードのメンテナンス性を高めるためでしょうか？
もしそれが目的なのであれば、3項演算子を利用してコードを短くするのではなく、CustomSortを行っている理由のdata.jsonの形を変更する方向に考えるべきではないでしょうか？

**Comment by mcdmaster** [comment]
@Nekoya3 ごもっともですね。ただ、`data.json` の構造変更は影響範囲が大きいとにらんでいます。
正しいか正しくないか、という観点だと、今やっていることは実は筋悪なのかもしれません。
ただ、いったんワークアラウンドとしてやってみるというアプローチも受容してみました

**Comment by Nekoya3** [comment]
data.jsonの影響範囲についてはかなり大きいのですが、提案してみる価値はあるのかなと思っています。
使われていないデータなどが多く入っているのでそこの削除と共にできればなと思いますね....

**Comment by goki90210** [comment]
> これを行う理由はコードのメンテナンス性を高めるためでしょうか？

私もその認識です。
作った人しかわからないという状況は作りたくないですよね。

**Comment by mcdmaster** [comment]
@goki90210 もう少し手を入れてみましたので、お手すきの時にでもご確認をお願いいたします

**Comment by Nekoya3** [comment]
CustomSortをつかわないアプローチを行ってみましたがいかがでしょう？

**Comment by mcdmaster** [comment]
いいですね。 @Nekoya3 のアプローチの方が今後においての合目的性にも叶うように私には見えます。とはいえ、 @goki90210 にご判断をお願いしたいですね。本イシューは可読性の向上が主眼にあるので、お手数でも SonarQube スキャンで数値をご確認いただきたいです。私のところにもコミュニティ版を入れてみたのですけど、なんだかヘンな数値が出ます(笑)

**Comment by goki90210** [comment]
問題ないことを確認しました。
![ConfirmedCasesAttributesCard5](https://user-images.githubusercontent.com/30145857/82743417-10c99600-9da6-11ea-801c-69244b8ba101.png)
![ConfirmedCasesAttributesCard6](https://user-images.githubusercontent.com/30145857/82743419-132bf000-9da6-11ea-8542-d81eba55a11d.png)

- 赤マークはカバレッジが通っていないことを意味しているだけ
- code smellが1件ありますが、これは 変数定義をしたあとすぐにreturnすることに意味あるの？というものですが、constにしたいという意図を含んでいるものとして一旦保留です。（言語仕様もちゃんと理解していないので…。）

**Comment by goki90210** [comment]
年代の翻訳とsort-descの値で問題が出てしまっているようですね…。

**Comment by MaySoMusician** [comment]
> code smellが1件ありますが、これは 変数定義をしたあとすぐにreturnすることに意味あるの？というものですが、constにしたいという意図を含んでいるものとして一旦保留です。（言語仕様もちゃんと理解していないので…。）

こちらですが、Vue.jsの仕様としてもわざわざ変数に格納する必要は無かったかと思われます... ので直接 `return` するように修正しても問題ないはずです

**Comment by goki90210** [comment]
少し調べました。
<pre>
    const data = {
      Data,
      patientsTable,
      sumInfoOfPatients
    }
    return data
</pre>
を
<pre>
return {
      Data,
      patientsTable,
      sumInfoOfPatients
}
</pre>
とすることはできますが、constがなくなってしまいます。（これで良いのかはわかりません。）
また、
<pre>
return {
      Data,
      patientsTable,
      sumInfoOfPatients
} as const
</pre>
とするとビルドエラーとなります。

**Comment by MaySoMusician** [comment]
JavaScript・TypeScriptでの `const` は、C言語系で一般的な定数定義ではなく「再代入不可能な変数の宣言」の予約語なので、return前にわざわざ一度代入する必要が無くなる＝ `const` を使う必要はなくなる、ということです。

また、 `as const` については
```ts
const foo = {
  x: 1,
  y: 2
} as const;
foo.y = 3 // エラー（as constでない場合はエラーにならない）
```
上記のように「変数のプロパティに対する再代入は通常の `const` では禁止できない」というJavaScriptの仕様のもとでプロパティ再代入すら禁止するときのためのものなので、今回の事例では不要となります。

**Comment by goki90210** [comment]
> JavaScript・TypeScriptでの const は、C言語系で一般的な定数定義ではなく「再代入不可能な変数の宣言」の予約語なので、return前にわざわざ一度代入する必要が無くなる＝ const を使う必要はなくなる、ということです。

理解しました。
別のIssueで修正提案します（同じ指摘が全部で15箇所あります。）

**Comment by kaizumaki** [comment]
こちらのissueの件は #4441 のPRを採用する方向ですすめてよろしいでしょうか？

**Comment by mcdmaster** [comment]
返答が遅れました。
問題ございません

**Comment by kaizumaki** [comment]
陽性者の属性はオープンデータAPIからのデータ取得となったとともにcustomSortは廃止となりましたので、こちらのissueはクローズします。
