### ISSUE TITLE
繁体字中国語を使用する場合、日本語のタイトルはまだ存在します

### ISSUE THREAD

**Issue by bomin0624** [tokyo-metropolitan-gov/covid19#4313]
## 起こっている問題 / The Problem
- When change to Traditional Chinese ,新規患者に関する報告件数の推移とPCR検査陽性者の発生動向（確定日別による陽性者数の推移）title is still Japanese, it may cause some problem when people didn't understand the Japanese well.

## スクリーンショット / Screenshot

https://imgur.com/a/7N4odVw.jpg

## 期待する見せ方・挙動 / Expected Behavior
- You can change 新規患者に関する報告件数の推移 to  新增患者相關報告件數趨勢
- PCR検査陽性者の発生動向 to PCR陽性確診趨勢（以確診日期為準）

-（注）患者発生の動向をより正確に分析するため、各保健所から報告があった患者の発生情報を、PCR検査により陽性であることを医師が確認した日別（確定日別）に整理したものである。 
（注）為了正確分析感染情況，各個保健所報告的患者確診信息是在醫生根據陽性的PCR檢測結果確診的那一天（按確診日期）整理的。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by PichuChen** [comment]
Hello, 

Thank you for your report, The text has been translated on Transfix, and waiting for sync to code base now.

There are translation table: https://www.transifex.com/stopcovid19-tokyo/stopcovid19tokyo/translate
