### ISSUE TITLE
[モニタリング指標] 総括表 [新規] テーブル組み

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4315]
5/15（金）に東京都から[新型コロナウイルス感染症を乗り越えるためのロードマップ](https://www.metro.tokyo.lg.jp/tosei/governor/governor/kishakaiken/2020/05/documents/20200515_01.pdf)が公表されました。これをふまえ当サイトではモニタリング指標に関するデータを掲載することになりました。

**5/22（金）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

### 実装イメージ
![モニタリング指標イメージ](https://user-images.githubusercontent.com/14883063/82439229-46842b80-9ad5-11ea-8cc8-0cb267c35d17.png)

項目は以下となります。
```
（１）新規陽性者数
（２）新規陽性者数における接触歴等不明率
（３）週単位の陽性者増加比
（４）重症患者数
（５）入院患者数
（６）PCR検査の陽性率
（７）受診相談窓口における相談件数
```
データは `monitoring_status.json` の `value` キー、 `go_threshold` キー、 `stop_threshod` キーとなります。

### タイトル
`モニタリング指標`

### 注釈
**注釈は表の下部に配置してください**
```
※（１）（２）（６）（７）は、７日間移動平均で算出
※（１）（２）（３）（６）は、確定日別陽性者数を基に算出
※各保健所からの報告を集計しているため、過去に遡って修正する場合がある
※（６）は、日曜日、祝祭日は更新しない。（７）は、土曜日、日曜日、祝祭日は更新しない。
```
※注釈は変更になる可能性があります。変更の際はこちらのissueにコメントします。

### 配置する位置
モニタリング指標関係のカードは３番目以降（「検査実施状況」の次）に並びます。他のissueとコンフリクトを起こすと思いますが、運営でカバーしますので、とりあえず３番目の位置に配置してください。

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by MaySoMusician** [comment]
@kaizumaki モバイル版もこの表示で大丈夫でしょうか？（横幅が狭くなっても耐えられるのかどうか？）

**Comment by kaizumaki** [comment]
@MaySoMusician たしかに、懸念されるとおりですね。都の意向としては、**「数値」と「目安となる数値」を横並びで見せたい**ということで、そのかわり「項目」列のグラフタイトルが折り返してもいいそうです。
いったん、このとおりで実装してみて、あまりに見にくいようだったら別issueという対応がよいかと思います。

**Comment by MaySoMusician** [comment]
こちら、宣言してませんでしたがやります

**Comment by kaizumaki** [comment]
@MaySoMusician ありがとうございます！よろしくお願いします！
