### ISSUE TITLE
[モニタリング指標]（４）重症患者数 [新規] 単純棒グラフ

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4316]
5/15（金）に東京都から[新型コロナウイルス感染症を乗り越えるためのロードマップ](https://www.metro.tokyo.lg.jp/tosei/governor/governor/kishakaiken/2020/05/documents/20200515_01.pdf)が公表されました。これをふまえ当サイトではモニタリング指標に関するデータを掲載することになりました。

**5/22（金）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

### タイトル
`（４）重症患者数`

### 注釈
**注釈はグラフ下部に配置してください**
```
（注）入院患者数のうち、集中治療室（ICU）等での管理又は人工呼吸器管理が必要な患者数を計上
上記の考え方で重症患者数の計上を開始した4月27日から作成
```

### グラフ
* 単純棒グラフ
    * 単位：人
    * データ： `positive_status.json` の `severe_case` キー
    * 色： `#00a040`

※4月27日分からグラフ化してください。

### 配置する位置
モニタリング指標関係のカードは３番目以降（「検査実施状況」の次）に並びます。他のissueとコンフリクトを起こすと思いますが、運営でカバーしますので、とりあえず３番目の位置に配置してください。

***
「入院中数」「重症者数」のグラフ化については、#3679 で提案がありました。ありがとうございます。
今回、モニタリング指標という形で公式にデータが公開となりましたので、こちらのissueとなりました（２つの間で実装が若干異なるため、２つのissueに分けました）。
***

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by Nekoya3** [comment]
やります

**Comment by kaizumaki** [comment]
@Nekoya3 ありがとうございます！よろしくお願いします！

**Comment by Nekoya3** [comment]
@kaizumaki 累計表示と日別表示両方可能のままでOKでしょうか？

**Comment by kaizumaki** [comment]
@Nekoya3 切り替え表示もそのまま実装でお願いします。

**Comment by Nekoya3** [comment]
了解しました１

**Comment by Nekoya3** [comment]
@kaizumaki オープンデータへのリンクはなしで大丈夫でしょうか？

**Comment by kaizumaki** [comment]
@Nekoya3 はい、オープンデータへのリンクはなしでOKです。

**Comment by Nekoya3** [comment]
MEMO: 
ui-test/ogp_screenshot.pyのPATHSに追加
pages/cards/_card.vueに他のカードと同様に追加する
nuxt.config.tsの169行目からのpagesに追加
