### ISSUE TITLE
[モニタリング指標]（５）入院患者数 [新規] 単純棒グラフ＋破線矩形で境界分け

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4317]
5/15（金）に東京都から[新型コロナウイルス感染症を乗り越えるためのロードマップ](https://www.metro.tokyo.lg.jp/tosei/governor/governor/kishakaiken/2020/05/documents/20200515_01.pdf)が公表されました。これをふまえ当サイトではモニタリング指標に関するデータを掲載することになりました。

**5/22（金）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

### タイトル
`（５）入院患者数`

### 注釈
**注釈はグラフ下部に配置してください**
```
（注）当サイトにおいて入院患者数の公表を開始した3月6日から作成
（注）5月11日までの入院患者数には宿泊療養者・自宅療養者等を含んでいるため、参考値である
```

### グラフ
* 単純棒グラフ
    * 単位：人
    * データ： `positive_status.json` の `hospitalized` キー
    * 色： `#00a040`
    * 破線矩形： `#1B4D30`

※3月6日分からグラフ化してください。
※「日別／累計」切り替えスイッチはなしで、累計グラフもなしでお願いします。（5/21 0:25追記）
※グラフの起点〜5月11日までの分を破線矩形で囲んでください。
破線矩形は `plugins/vue-chart.ts` にplugin（rectangularLinePlugin）を追加作成するイメージだと思います。

参考イメージ
![境界分け](https://user-images.githubusercontent.com/14883063/82439892-6700b580-9ad6-11ea-8a4b-771a3c607606.png)

### 配置する位置
モニタリング指標関係のカードは３番目以降（「検査実施状況」の次）に並びます。他のissueとコンフリクトを起こすと思いますが、運営でカバーしますので、とりあえず３番目の位置に配置してください。

***
「入院中数」「重症者数」のグラフ化については、#3679 で提案がありました。ありがとうございます。
今回、モニタリング指標という形で公式にデータが公開となりましたので、こちらのissueとなりました（２つの間で実装が若干異なるため、２つのissueに分けました）。
***

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by y-chan** [comment]
破線矩形について、プラグインでは無い実装案がありますが上手くいく確証がありません。一旦Assignしていただいて、不可なら他の方にお願いするというのは可能でしょうか...?

**Comment by kaizumaki** [comment]
@y-chan ありがとうございます！ぜひ試してみてください！もしものときはアサインを外しますので、ご心配なく。

**Comment by kaizumaki** [comment]
@y-chan ２点修正がきました。
1. グラフタイトル修正
`モニタリング指標(5)入院患者数`
（記号・数字は半角にします）

1. 注釈の順番修正
以下のようにしてください。
```
（注）5月11日までの入院患者数には宿泊療養者・自宅療養者等を含んでいるため、参考値である
（注）当サイトにおいて入院患者数の公表を開始した3月6日から作成
```

ご対応のほどよろしくお願いします 🙇‍♀️

**Comment by kaizumaki** [comment]
@y-chan こちら進捗はいかがですか？よかったらキリがいいところでDPRを出しておいてもらえると。

**Comment by y-chan** [comment]
了解しましたー、キリの良いところでDPRだします
