### ISSUE TITLE
[モニタリング指標]（６）ＰＣＲ検査の陽性率 [修正] タイトル変更＋注釈位置変更

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4318]
5/15（金）に東京都から[新型コロナウイルス感染症を乗り越えるためのロードマップ](https://www.metro.tokyo.lg.jp/tosei/governor/governor/kishakaiken/2020/05/documents/20200515_01.pdf)が公表されました。これをふまえ当サイトではモニタリング指標に関するデータを掲載することになりました。

**5/22（金）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

### タイトル変更
`（６）ＰＣＲ検査の陽性率`

### 注釈位置変更
注釈をグラフ下部に移動してください

**Comment by yuu26jp** [comment]
初めてではありますがこちら対応します。

@kaizumaki 
修正対象は `検査実施人数（陰性確認を除く）と陽性率の推移` の項目で間違いないでしょうか？

**Comment by kaizumaki** [comment]
@yuu26jp ありがとうございます！私が元タイトルを書くのを失念していました 🙇‍♀️  ご指摘のとおり、`検査実施人数（陰性確認を除く）と陽性率の推移` で合っています。よろしくお願いします！
