### ISSUE TITLE
[モニタリング指標]（７）受診相談窓口における相談件数（旧：新型コロナ受診相談窓口相談件数）[改修] 折れ線グラフ追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4319]
5/15（金）に東京都から[新型コロナウイルス感染症を乗り越えるためのロードマップ](https://www.metro.tokyo.lg.jp/tosei/governor/governor/kishakaiken/2020/05/documents/20200515_01.pdf)が公表されました。これをふまえ当サイトではモニタリング指標に関するデータを掲載することになりました。

**5/22（金）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

## [モニタリング指標]（７）受診相談窓口における相談件数　実装内容
（現在の「新型コロナ受診相談窓口相談件数」グラフです）

### タイトル修正
`（７）受診相談窓口における相談件数`

### 注釈追加
**注釈はグラフ下部に配置してください**
```
（注）曜日などによる件数のばらつきにより、日々の結果が変動するため、こうしたばらつきを平準化し全体の傾向を見る趣旨から、過去７日間の移動平均値を相談件数として算出
（注）新型コロナ受診相談窓口 （帰国者・接触者電話相談センター）を開設した2月7日から作成
```

### グラフ
* 単純棒グラフ　**実装済み**
    * ラベル：相談件数
    * 単位：件
    * データ： `data.json` の `querents` キー配下の `小計` キー
    * 色： `#00a040`
* 折れ線グラフ
    * ラベル：７日間移動平均
    * 単位：件
    * データ： `data.json` の `querents` キー配下の `７日間平均` キー
    * 色： `#1b4d30`

※折れ線グラフはベジェ曲線ではなく直線でお願いします。
※折れ線グラフを前面表示でお願いします。

### 配置する位置
モニタリング指標関係のカードは３番目以降（「検査実施状況」の次）に並びます。他のissueとコンフリクトを起こすと思いますが、運営でカバーしますので、とりあえず３番目の位置に配置してください。

***
７日間移動平均の折れ線グラフについては、#3780 #3909 で提案がありました。ありがとうございます。
今回、モニタリング指標という形で公式にデータが公開となりましたので、こちらのissueとなりました。
***

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by Nekoya3** [comment]
やります

**Comment by Nekoya3** [comment]
「新型コロナ受診相談窓口相談件数」カードを編集して3番目に持っていくのでOkでしょうか？
別カードとして作成した方が良いでしょうか？

**Comment by kaizumaki** [comment]
@Nekoya3 ありがとうございます！すごいスピードですね 🚀  よろしくお願いします！

**Comment by Nekoya3** [comment]
@kaizumaki 日別・累計のスイッチについてですが、移動平均の累計というのもおかしな感じがするのですが、日別表示のみにしますか？

**Comment by kaizumaki** [comment]
@Nekoya3 はい、たしかにおっしゃるとおりですね。こちらも「日別／累計」切り替えスイッチはなしでいいと思います。モニタリング指標の項目として支障ないはずです。

**Comment by Nekoya3** [comment]
了解しました！
