### ISSUE TITLE
[モニタリング指標]（１）新規陽性者数（旧：新規患者に関する報告件数の推移）[改修] 折れ線グラフ追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4323]
5/15（金）に東京都から[新型コロナウイルス感染症を乗り越えるためのロードマップ](https://www.metro.tokyo.lg.jp/tosei/governor/governor/kishakaiken/2020/05/documents/20200515_01.pdf)が公表されました。これをふまえ当サイトではモニタリング指標に関するデータを掲載することになりました。

**5/22（金）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

## [モニタリング指標]（１）新規陽性者数　実装内容
（現在の「新規患者に関する報告件数の推移」グラフです）

### タイトル修正
`（１）新規陽性者数`

### 注釈追加
**以下の注釈はグラフ下部に配置してください**
```
（注）集団感染発生や曜日による件数のばらつきにより、日々の結果が変動するため、こうしたばらつきを平準化し全体の傾向を見る趣旨から、過去７日間の移動平均値を陽性者数として算出
```

### グラフ
* 単純棒グラフ　**データの参照元を変更してください**
    * ラベル：陽性者数
    * 単位：人
    * データ： `daily_positive_detail.json` の `count` キー
    * 色： `#00a040`
* 折れ線グラフ
    * ラベル：７日間移動平均
    * 単位：人
    * データ： `daily_positive_detail.json` の `weekly_average_count` キー
    * 色： `#1b4d30`

※「日別／累計」切り替えスイッチはなしで、累計グラフもなしでお願いします。（5/21 2:23追記）
※折れ線グラフはベジェ曲線ではなく直線でお願いします。
※折れ線グラフを前面表示でお願いします。

### 配置する位置
モニタリング指標関係のカードは３番目以降（「検査実施状況」の次）に並びます。他のissueとコンフリクトを起こすと思いますが、運営でカバーしますので、とりあえず３番目の位置に配置してください。

***
７日間移動平均の折れ線グラフについては、#3780 #3909 で提案がありました。ありがとうございます。
今回、モニタリング指標という形で公式にデータが公開となりましたので、こちらのissueとなりました。
***

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by Nekoya3** [comment]
やります

**Comment by kaizumaki** [comment]
@Nekoya3 もろもろすみません！ありがとうございます 🙇‍♀️

**Comment by Nekoya3** [comment]
@kaizumaki これも #4331 と同様にy軸を左側のみにしますか？

**Comment by kaizumaki** [comment]
@Nekoya3 はい、左側のみでお願いします！
