### ISSUE TITLE
[モニタリング指標]（２）新規陽性者における接触歴等不明率 [新規] 折れ線グラフ＋積み上げ棒グラフの２軸グラフ

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4324]
5/15（金）に東京都から[新型コロナウイルス感染症を乗り越えるためのロードマップ](https://www.metro.tokyo.lg.jp/tosei/governor/governor/kishakaiken/2020/05/documents/20200515_01.pdf)が公表されました。これをふまえ当サイトではモニタリング指標に関するデータを掲載することになりました。

**5/22（金）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

### タイトル
`（２）新規陽性者における接触歴等不明率`

### 注釈
**注釈はグラフ下部に配置してください**
```
（注）PCR検査により陽性であることを医師が確認した日別（確定日別）の新規陽性者数について、接触歴等の不明者、判明者に区分したものである。
（注）集団感染発生や曜日による件数のばらつきにより、日々の結果が変動するため、こうしたばらつきを平準化し全体の傾向を見る趣旨から、過去７日間の移動平均値を不明率として算出
（注）陽性者が1月24日、25日、30日、2月13日にそれぞれ１名、2月14日に２名発生しているが、有意な数値がとれる2月15日から作成
```

### グラフ
* 折れ線グラフ
    * ラベル：接触歴等不明率（７日間移動平均）
    * 単位：%
    * データ： `daily_positive_detail.json` の `untracked_percent` キー
    * 色： `#CC7004`
* 積み上げ棒グラフ（下）
    * ラベル：接触歴等判明者数
    * 単位：人
    * データ： `daily_positive_detail.json` の `reported_count` キー
    * 色： `#1b4d30`
* 積み上げ棒グラフ（上）
    * ラベル：接触歴等不明者数
    * 単位：人
    * データ： `daily_positive_detail.json` の `missing_count` キー
    * 色： `#c5e2c6`

※2月15日分からグラフ化してください。
※「％」が左軸、「人」が右軸です。
※「日別／累計」切り替えスイッチはなしで、累計グラフもなしでお願いします。（5/21 2:25追記）
※折れ線グラフはベジェ曲線ではなく直線でお願いします。
※折れ線グラフを前面表示でお願いします。

### 配置する位置
モニタリング指標関係のカードは３番目以降（「検査実施状況」の次）に並びます。他のissueとコンフリクトを起こすと思いますが、運営でカバーしますので、とりあえず３番目の位置に配置してください。

***
感染経路や感染経路不明者数のグラフ化については、#2987 #3805 で提案がありました。ありがとうございます。
今回、モニタリング指標という形で公式にデータが公開となりましたので、こちらのissueとなりました。
***

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by yuu26jp** [comment]
こちら対応します。

**Comment by kaizumaki** [comment]
@yuu26jp ありがとうございます！よろしくお願いします！
