### ISSUE TITLE
[モニタリング指標]（３）週単位の陽性者増加比 [新規] 折れ線グラフ

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4325]
5/15（金）に東京都から[新型コロナウイルス感染症を乗り越えるためのロードマップ](https://www.metro.tokyo.lg.jp/tosei/governor/governor/kishakaiken/2020/05/documents/20200515_01.pdf)が公表されました。これをふまえ当サイトではモニタリング指標に関するデータを掲載することになりました。

**5/22（金）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

### タイトル
`（３）週単位の陽性者増加比`

### 注釈
**注釈はグラフ下部に配置してください**
```
（注）直近１週間の新規陽性者数とその前の１週間の新規陽性者数の比率。１を上回ると増加し、１を下回ると減少する
（注） １週間前の新規陽性者数と比較した際の増加比について、有意な数値がとれる2月22日から作成
```

### グラフ
* 折れ線グラフ
    * ラベル：週単位陽性者増加比
    * 単位：なし
    * データ： `daily_positive_detail.json` の `weekly_gain_ratio` キー
    * 色： `#1B4D30`
    * 塗り： `#CBE1C8`

※2月22日分からグラフ化してください。
※折れ線グラフはベジェ曲線ではなく直線でお願いします。

参考イメージ
![折れ線グラフ](https://user-images.githubusercontent.com/14883063/82449658-83a4e980-9ae6-11ea-87c6-3f3c70df6d2a.png)

### 配置する位置
モニタリング指標関係のカードは３番目以降（「検査実施状況」の次）に並びます。他のissueとコンフリクトを起こすと思いますが、運営でカバーしますので、とりあえず３番目の位置に配置してください。

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by y-chan** [comment]
やります

**Comment by kaizumaki** [comment]
@y-chan ありがとうございます！よろしくお願いします！
