### ISSUE TITLE
「お子様をお持ちの皆様へ」に「TOKYO おはよう スクール」を追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4337]
「お子様をお持ちの皆様へ」ページへの項目の追加をお願いします。

- タイトル： `TOKYO おはよう スクール`
- タイトルのリンク先URL：https://tokyodouga.jp/playlist/ohayoschool.html
- 説明文： `学校休校中の子供たちの生活や学習を応援するテレビ番組です。`
- 位置：「お子様をお持ちの皆様へ」の一番上

**Comment by yuu26jp** [comment]
🙋

**Comment by yuu26jp** [comment]
こちら対応します 🙋

リンク先では `TOKYOおはようスクール` と表示されますが、リンク文字列はスペースありの `TOKYO おはよう スクール` で良いでしょうか？

**Comment by kaizumaki** [comment]
@yuu26jp ありがとうございます！都からの依頼がスペースありなので、それが正しいのかと思っていたのですが、ちょっと確認しますね。

**Comment by kaizumaki** [comment]
@yuu26jp 都から回答がありました。スペースなしの `TOKYOおはようスクール` でお願いします 🙏

**Comment by yuu26jp** [comment]
ご確認ありがとうございます。承知しました！
