### ISSUE TITLE
/en/parent の｢その他｣の翻訳の表示が｢{ "parent": "Other information", "graph": "Elsewhere" }｣になっている

### ISSUE THREAD

**Issue by WataruMatsuoka** [tokyo-metropolitan-gov/covid19#4340]
## 起こっている問題 / The Problem
/assets/locales/en.jsonの[キー](https://github.com/tokyo-metropolitan-gov/covid19/blob/042be4f10395e9c12916bb62d6340feb16df04d3/assets/locales/en.json#L75)と、/pages/parent.vueの[キー](https://github.com/tokyo-metropolitan-gov/covid19/blob/042be4f10395e9c12916bb62d6340feb16df04d3/pages/parent.vue#L75)が異なるため、表示がおかしい

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/62194885/82529946-168d6480-9b77-11ea-9fe7-904bb48db322.png)

## 期待する見せ方・挙動 / Expected Behavior
Other information と表示される

## 起こっている問題の再現手段 / Steps to Reproduce
https://stopcovid19.metro.tokyo.lg.jp/en/parent へのアクセス

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by WataruMatsuoka** [comment]
初めてなので、アサインまでの流れがわかりませんが、私に対応させていただけますか?

**Comment by MaySoMusician** [comment]
ご指摘ありがとうございます！

`en.json` 系のファイルについては、 https://github.com/tokyo-metropolitan-gov/covid19/issues/1985#issue-585199034 にも少し書いてありますが、基本的にはTransifex上で編集し、GitHubでは編集しない方針で作業しています（GitHubとTransifexでコンフリクトが発生するため）
当該箇所（「その他」の部分）についてはTransifex上では既に直っており、TransifexからGitHubへの反映待ちとなっていました。（Transifex側の仕様により、他の文字列も含めて翻訳の進捗率が100%にならないと自動反映されない）。

アサイン希望をいただいたところ恐縮ですが、これからTransifexから手動反映コマンドを実行するので、特にGitHub上での作業は行わなくて大丈夫になります。 🙇‍♂️

**Comment by WataruMatsuoka** [comment]
なるほど! 反映待ちだったのですね。対応ありがとうございます。

**Comment by linuxmetel** [comment]
補足ですが、#4267 など、日本語以外の全言語で起きています。

**Comment by kaizumaki** [comment]
@WataruMatsuoka ご指摘ありがとうございます！翻訳ファイルもだいぶ整理されましたので、こちらのissueの不具合は解消されていると思います。こちらはクローズさせていただきますね。また何かお気づきの点がありましたらお知らせください！
