### ISSUE TITLE
OGPのページタイトルが切り替わらない

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#435]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* #377 に類似して、ページを切り替えしてもOGP側のページタイトル（`og:title`）が変わらない

## スクリーンショット / Screenshot

![開発者ツールでの表示](https://user-images.githubusercontent.com/34566290/75941887-385e4000-5ed4-11ea-948e-b32fe6d4f6c1.png)
↑開発者ツールでの表示

![埋め込み表示（Discord）](https://user-images.githubusercontent.com/34566290/75941973-7ce9db80-5ed4-11ea-853e-07f0e7b386b8.png)
↑埋め込み表示（Discord）

## 期待する見せ方・挙動 / Expected behavior
* `<title>`の中身と同じにする（上記例では「新型コロナウイルス感染症が心配なときに | 東京都 新型コロナウイルス対策サイト」）
* (追記) or サイト名を含まないページ名にする（「新型コロナウイルス感染症が心配なときに」）

## 起こっている問題の再現手段 / Steps to reproduce
1. トップページ以外を開く

## 動作環境・ブラウザ / Environment
* Windows 10 Home 64 bit
* Chrome 80.0.3987.122

**Comment by MaySoMusician** [comment]
Facebookの[OGP実装](https://developers.facebook.com/docs/sharing/webmasters)だと`og:title`は「サイト名などのブランド情報を含まない」そうなのですが、どうしましょうか
ちなみに（Facebookに逆らって）サイト名を入れた場合は`titleTemplate`を使わない方がスマートに実装できそうです

**Comment by MaySoMusician** [comment]
Facebookの実装に従って修正案は作成済みですが、 #507 #515 関連でコミット前でストップしてます

**Comment by munierujp** [comment]
Facebook自身も守ってなさそうですね🤔

```html
<meta name="og:site_name" content="Facebook for Developers">
<meta name="og:title" content="ウェブ管理者 - シェア機能 - ドキュメンテーション - Facebook for Developers">
```

**Comment by halsk** [comment]
不具合自体は #1479 で解消されました。
「サイト名などのブランド情報を含まない」については、別途考えましょう！
