### ISSUE TITLE
表の追加：検査陽性者の状況[仮版]

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#436]
## 起こっている問題 / Occurred problem
* #309 のように見せ方を変えるのはデータの確認や実装に時間がかかりそうなので、とりあえずは元の表に合わせた形の表を表示する

## スクリーンショット / Screenshot
こちらです。
![image (3)](https://user-images.githubusercontent.com/16509/75942663-5f1d7600-5ed6-11ea-80c6-a0c68a370f28.png)

## 期待する見せ方・挙動 / Expected behavior
* こちらの svg データを使ってください。
https://github.com/tokyo-metropolitan-gov/covid19/blob/feature/436-add-new-table/static/confirmed-cases-table.svg

**Comment by NaoyaShimizzz** [comment]
![image](https://user-images.githubusercontent.com/61729733/75943103-71e47a80-5ed7-11ea-831a-fe813188cd19.png)
並び順も元の表に合わせた形で、お願いいたします！
