### ISSUE TITLE
モニタリング指標関連PRをマージした際の問題

### ISSUE THREAD

**Issue by y-chan** [tokyo-metropolitan-gov/covid19#4382]
## 起こっている問題 / The Problem
- コード上の問題
  - 絶対パス(`@/....`)ではなく相対パス(`../../....`)でインポートされているコンポーネントがある(動いてはいるので優先度低)
  - ogp builderのスクリプトに問題が生じている(カンマ忘れ、動かないので優先度高)
- 表示上の問題
  - `モニタリング指標(2)新規陽性者における接触歴等不明率`が、PRの際データにはなかった`null`のせいで表示できていない(動いていないので優先度高)
  - サイトにアクセスした際のローディングが表示できていない(上記問題によるもの)
  - `モニタリング指標(6)PCR検査の陽性率`のみ順番にならんでいない(要確認、動いてはいる上に私には判断できないので優先度不明)

## スクリーンショット / Screenshot

(2)が表示できていない問題
![image](https://user-images.githubusercontent.com/34832037/82624907-bf42cf00-9c1e-11ea-9dca-dae5930ffc3e.png)

## 期待する見せ方・挙動 / Expected Behavior
- 問題がすべて解決される

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://dev-covid19-tokyo.netlify.app にアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@y-chan ご指摘ありがとうございます！ただいま運営でも対応を検討中です。

**Comment by y-chan** [comment]
一旦、全部対応してPRします。
マージするか否かは運営側で検討いただければと...

**Comment by kaizumaki** [comment]
とりあえず、
> モニタリング指標(2)新規陽性者における接触歴等不明率が、PRの際データにはなかったnullのせいで表示できていない(動いていないので優先度高)

これを先にPRいただければと思います！

**Comment by kaizumaki** [comment]
>モニタリング指標(6)PCR検査の陽性率のみ順番にならんでいない(要確認、動いてはいる上に私には判断できないので優先度不明)

グラフの並び順については、現在運営で作業中なので大丈夫ですよ！

**Comment by y-chan** [comment]
取り急ぎ、`モニタリング指標(2)新規陽性者における接触歴等不明率が、PRの際データにはなかったnullのせいで表示できていない(動いていないので優先度高)`を解決しました。
また、まだPRしていませんが、そのほかの問題も即時PR出来るように準備済みです。

**Comment by kaizumaki** [comment]
@y-chan ありがとうございます！並び順以外のものを、個別にPRいただいてもいいですか？

**Comment by y-chan** [comment]
了解しました！
