### ISSUE TITLE
[モニタリング指標：残作業] 前日比の表示

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4413]
モニタリング指標関連のグラフ７つのうち４つにおいて、右上の数値の下部に「（前日比: 〇〇）」がない状態なので、これを追加したいです。

### 「前日比」がないグラフ
![スクリーンショット 2020-05-22 16 42 22](https://user-images.githubusercontent.com/14883063/82644301-0f845600-9c4c-11ea-99ec-37acf8d3c8d9.png)
![スクリーンショット 2020-05-22 16 42 58](https://user-images.githubusercontent.com/14883063/82644311-14490a00-9c4c-11ea-9644-17dbeeada1fe.png)
![スクリーンショット 2020-05-22 16 43 19](https://user-images.githubusercontent.com/14883063/82644320-190dbe00-9c4c-11ea-9b87-72487d67f103.png)
![スクリーンショット 2020-05-22 16 43 32](https://user-images.githubusercontent.com/14883063/82644336-1d39db80-9c4c-11ea-801b-90ebda234e24.png)

### [参考]「前日比」があるグラフ
![スクリーンショット 2020-05-22 16 43 56](https://user-images.githubusercontent.com/14883063/82644404-38a4e680-9c4c-11ea-99f3-67b996237256.png)

**Comment by InadomeLabo** [comment]
初心者ですがチャレンジしてみます。
