### ISSUE TITLE
[モニタリング指標：残作業] 補助線の実装

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4414]
モニタリング指標関連のグラフのうち３つのグラフに補助線を引きたいです。

参考イメージ（オレンジの線が補助線）
![draft3](https://user-images.githubusercontent.com/14883063/82650725-13b57100-9c56-11ea-9efc-a2f6bdcbde94.png)

## モニタリング指標(1)新規陽性者数
補助線２本を実装
1. ラベル：緩和の目安
	位置：Y軸 20（人）
	線の種類：破線
	線の色： `#1B4D30`
2. ラベル：再要請の目安
	位置：Y軸 50（人）
	線の種類：直線
	線の色： `#1B4D30`

## モニタリング指標(2)新規陽性者における接触歴等不明率
補助線１本を実装
1. ラベル：緩和・再要請の目安
	位置：Y軸 50（%）
	線の種類：破線
	線の色： `#1B4D30`

## モニタリング指標(3)週単位の陽性者増加比
補助線２本を実装
1. ラベル：緩和の目安
	位置：Y軸 1の目盛り
	線の種類：破線
	線の色： `#CC7004`
2. ラベル：再要請の目安
	位置：Y軸 2の目盛り
	線の種類：直線
	線の色： `#CC7004`

※補助線の太さは2pxでお願いします。

**Comment by y-chan** [comment]
やります
