### ISSUE TITLE
utils/colors.ts のswitch-case文のdefault:の位置がおかしい

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4419]
## 起こっている問題 / The Problem
- utils/colors.ts のswitch-case文が変です。

## スクリーンショット / Screenshot

<pre>
export function getGraphSeriesColor(series: string) {
  switch (series) {
    case 'A':
    default:
      return surfaceStyleA
    case 'B':
      return surfaceStyleB
    case 'C':
      return surfaceStyleC
    case 'D':
      return surfaceStyleD
  }
}
</pre>
default:の位置がおかしい。

## 期待する見せ方・挙動 / Expected Behavior
<pre>
export function getGraphSeriesColor(series: string) {
  switch (series) {
    case 'B':
      return surfaceStyleB
    case 'C':
      return surfaceStyleC
    case 'D':
      return surfaceStyleD
    default:
      return surfaceStyleA
  }
}</pre>
では駄目なのでしょうか？

## 起こっている問題の再現手段 / Steps to Reproduce
上記ソースの通り

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by y-chan** [comment]
ごめんなさい、私がJavaScript及びTypeScriptに不慣れなため、一般的に不適切なコードを書いてしまいました...
そちらの方がコード的に綺麗ですし、動作的にも問題ないでしょうから、書き換えてくださると幸いです。

**Comment by goki90210** [comment]
わかりました。修正します。

**Comment by goki90210** [comment]
#4420 で別の修正方法が提案されましたが、具体的にどう対応すればよいのか私にはわからないので別の方にバトンタッチします。

**Comment by MaySoMusician** [comment]
#4420 で提案のあった文字列リテラル型に関して https://github.com/tokyo-metropolitan-gov/covid19/pull/4420#discussion_r429597782 をこちらにも転記しておきます

---

文字列リテラル型 `Series` を使用することにより
- 定義されていない `Series` の指定を型チェックで発見できる（今の実装だと `getGraphSeriesColor('F')` を型チェックエラー扱いにできる）
- `Series` に E, F... を増やしたときに `getGraphSeriesColor` のswitch文も同時に変更するのを忘れないようにできる
    - `getGraphSeriesColor` の返り値の型を明示的に `SurfaceStyle` のみにすれば、case文の増やし忘れを型チェックで発見できる
        たとえば
        ```ts
        type Series = 'A' | 'B' | 'C' | 'D' | 'E'
        
        export function getGraphSeriesColor(series: Series): SurfaceStyle {
          switch (series) {
            case 'A':
              return surfaceStyleA
            case 'B':
              return surfaceStyleB
            case 'C':
              return surfaceStyleC
            case 'D':
              return surfaceStyleD
          }
        }
        ```
        というように `Series` に `E` を増やしたけど `case 'E':` を書き忘れた場合、 `getGraphSeriesColor` は `undefined` を返すことができないので型チェックエラーになります。

別の観点として、switch文をJavaScriptでは連想配列に置き換えるショートハンドがよくありますが、

```ts
type Series = 'A' | 'B' | 'C' | 'D' | 'E'

export function getGraphSeriesColor(series: Series) {
  const styles: { [key in Series]: SurfaceStyle } = {
    A: surfaceStyleA,
    B: surfaceStyleB,
    C: surfaceStyleC,
    D: surfaceStyleD
  }
  return styles[series]
}
```
先ほどのように `E` を「定義したけど実装し忘れた」場合、 `styles` 変数のプロパティとして `E` が存在しなければならないというエラーが出るので、この方法でも実装し忘れに対処可能です。（この場合、 `getGraphSeriesColor` の返り値を明示的に `SurfaceStyle` 型のみと指定する必要はありません）
