### ISSUE TITLE
pages/cards/_card.vue のimportしているjsonファイルの重複

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4421]
## 起こっている問題 / The Problem
- pages/cards/_card.vue のimportしているjsonファイルに重複が発生している。
88-89行目
<pre>
import DailyPositiveDetail from '@/data/daily_positive_detail.json'
import UntrackedRate from '@/data/daily_positive_detail.json'
</pre>
同じ/data/daily_positive_detail.jsonをimportしているのにDailyPositiveDetail , UntrackedRate の2つの名称を用いている。（どちらか一方では駄目なのでしょうか？）

90－92行目
<pre>
import PositiveStatus from '@/data/positive_status.json'
import positiveStatus from '@/data/positive_status.json'
import monitoringStatusData from '@/data/monitoring_status.json'
</pre>

PositiveStatus と positiveStatus を分けて使っている理由はなにかあるのでしょうか？
あとimportの名前が(Lower) Camel Case だったりUpper Camel (Pascal) Caseだったり…
これもなにか理由があるのでしょうか？

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected Behavior
- 重複の解消

## 起こっている問題の再現手段 / Steps to Reproduce
上記ソースの通り

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@goki90210 ご指摘ありがとうございます！ #4410 でディスカッションしていますので、ぜひ。

**Comment by goki90210** [comment]
#4410と重複していましたのでクローズします。
