### ISSUE TITLE
グラフの報告件数が0人だと0人の日がわからない

### ISSUE THREAD

**Issue by youkidearitai** [tokyo-metropolitan-gov/covid19#4422]
## 起こっている問題 / The Problem
- 新規患者に関する報告件数の推移 を見たところ、0人の日にマウスオーバーしても0人と表示されないため、何月何日に0人だったかが分かりづらいです。

これから報告件数が0人になる日が続くというケースが発生するかと思うので、0人である日がわかると良いと考えます。

## スクリーンショット / Screenshot

こちらは一人以上のときのスクリーンショットです。
![stopcovid19-tokyo-issue-bug-report-nothing-1](https://user-images.githubusercontent.com/305368/82684116-0d8eb700-9c8d-11ea-870c-78a40dd8f39a.png)

こちらは0人のスクリーンショットです。2月の0人の日をマウスオーバーしました。
![stopcovid19-tokyo-issue-bug-report-nothing-2](https://user-images.githubusercontent.com/305368/82684164-1d0e0000-9c8d-11ea-99fd-21c12503c2eb.png)

## 期待する見せ方・挙動 / Expected Behavior
- 0人の日もマウスオーバーして0人であることを表示してほしい

## 起こっている問題の再現手段 / Steps to Reproduce
1. 新規患者に関する報告件数の推移の2月ごろの0人のところをマウスオーバーする（スマホの場合はタップ）
2. 1人以上いれば表示される「5/1 0人」などが表示されない

## 動作環境・ブラウザ / Environment
私は以下の環境で確認しました。
- Windows / Firefox
- Android / Firefox

**Comment by goki90210** [comment]
今は棒グラフの棒の部分のマウスオーバーでと吹き出しで人数が出るという仕様ですよね。
0人だと棒そのものがないから人数が出ない。

折れ線グラフの場合は線があるので値が0でもマウスオーバーで吹き出しが出る。

棒グラフでも値が0であっても何かが出てればよいということですよね？

**Comment by youkidearitai** [comment]
はい、0であることがわかる、何かが出てれば良いと思います。

**Comment by youkidearitai** [comment]
アイデアが思いついたので #4512 を作ってしまいました。
事後報告になってしまってすみません。
