### ISSUE TITLE
「東京都緊急事態措置について」をコンポーネント化

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4425]
## 改善詳細 / Details of Improvement
現在、「東京都緊急事態措置について」の黄色いボタンが `components/WhatsNew.vue` のコンポーネントの内部に置かれています。
これを別コンポーネントに分離して、簡単に表示非表示が切り替えられるようにしたいです。

![スクリーンショット 2020-05-23 12 33 23](https://user-images.githubusercontent.com/14883063/82720783-c25abf80-9cf1-11ea-9ffb-8a0a0f6baa7d.png)

## 期待する見せ方・挙動 / Expected behavior
- 「東京都緊急事態措置について」の黄色いボタンの表示非表示切り替えが簡単になる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nard-tech** [comment]
ボタンを付けたの私なので，こちらも私がやりますね

**Comment by nard-tech** [comment]
@kaizumaki 完了しました．ご確認お願いします．

**Comment by kaizumaki** [comment]
@nard-tech ご対応ありがとうございます。PRにコメント https://github.com/tokyo-metropolitan-gov/covid19/pull/4429#issuecomment-632991770 しましたので、ご確認いただければと思います。
