### ISSUE TITLE
<script lang="ts">は意味がない

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4426]
## 起こっている問題 / The Problem
- lang="ts"はTypeScriptの意味ではありません。実際には無視されているのでこれといった問題は起きませんが…。

#4410 でVue.jsのスタイルガイドの話題が上がったので、思い出したのですが、
`<script lang="ts">`
はスタイルガイドには書かれていませんし、これって意味ないんですよね。

HTML5ではscriptタグはtype属性が省略されるとtype="type/javascript"(JavaScript)として扱われ、
TypeScriptはブラウザ上ではJavaScriptになるので問題は発生しません。

確かにHTML5 ではlang属性はどこでも使えるので
scriptタグにも使えるのですが、この場合の"ts"は「ツォンガ語」になるはずです。
（参考）
https://reference.hyper-text.org/html5/attribute/lang/

検索すると
`<script lang="ts">`と記載されたサンプルが結構出てくるのですが、
HTML4.xにあったlanguage属性のつもりで書いているのかもしれません。

## 期待する見せ方・挙動 / Expected Behavior
- <script lang="ts">→<script>に修正する。

## 起こっている問題の再現手段 / Steps to Reproduce
なし

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
`<script lang="ts">` については最終的に表示されるHTMLファイルというより、Nuxt（もしくはVue）がbuildする際にTypeScriptの文法を認識するための属性だと思われます。

現に何も他の設定を変更しないまま `lang="ts"` に変更するとServer側のbuildに失敗します

Vue.jsのスタイルガイドに書かれていない件は、Vue.jsが公式としてはJavaScriptで記述されることを想定しているからではないかと思います

**Comment by goki90210** [comment]
確かにそうでした。
失礼しました。
