### ISSUE TITLE
[モニタリング指標] 小数点以下の桁数を揃えたい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4427]
## 改善詳細 / Details of Improvement
モニタリング指標では７日間移動平均や割合など、小数点以下の数値が求められる値がいくつかあるのですが、その桁数を揃えたいです。
元データからのjson変換スクリプト上では限界があり、フロント側で対応したいです。

例えば（1）新規陽性者数だと、
モニタリング指標の値は「○.○人」という小数点以下１桁の扱いなのですが、

![スクリーンショット 2020-05-23 12 52 42](https://user-images.githubusercontent.com/14883063/82721669-6b0d1d00-9cfa-11ea-9e54-39ae8fe99b2b.png)

実際の数値をみると「43」などといった小数点以下が出ていないものがあります。

![スクリーンショット 2020-05-23 12 53 14](https://user-images.githubusercontent.com/14883063/82721679-82e4a100-9cfa-11ea-9a3b-e26e5d13b8ec.png)

これを「43.0」という感じにしたいです。

## 期待する見せ方・挙動 / Expected behavior
- グラフのツールチップの数値、テーブルの数値、右上の最新の数値いずれにおいても、現在のモニタリング指標に表示されている数値の小数点以下桁数に合わせた値になる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nard-tech** [comment]
やります

**Comment by nard-tech** [comment]
@kaizumaki これ試してみましたが，`SimpleMixedChart` が `MonitoringConfirmedCasesNumberCard`（モニタリング(1)新規陽性者数）, MonitoringConsultationDeskReportsNumberCard`（モニタリング指標(7)受診相談窓口における相談件数）での2つで利用されているため，「新規陽性者数」のために `SimpleMixedChart` の実装を変えると意図しない影響が「受診相談窓口における相談件数」に出てしまいます．

やはり表示する値を JSON にもたせて，JSON の値をコントロールする方がよいのではないかと思いました．

このまま作業を進めてもいいのですが，設計方針がない状態で私の独断でこれ以上スパゲッティコードにするのは避けたいので，一旦ストップさせてください．

**Comment by kaizumaki** [comment]
@nard-tech わかりました。いましばらく検討させてください。

**Comment by Keyhoh** [comment]
`SimpleMixedChart`にデータ表示フォーマット関数の受け口を追加する。  
`SimpleMixedChart`を利用するコンポーネントでgetFormatter関数を定義して渡す。 
getFormatter関数は引数にカラム番号を受け取って各カラムに適切なフォーマッタを返す関数。  

以下、モニタリング指標(1)新規陽性者数の7日間移動平均を小数点第一位でfixedする例。

***SimpleMixedChart.vue***
```vue
...
<script>
type Props = {
  ...
  getFormatter: Function
  ...
}
...
const options: ThisTypedComponentOptionsWithRecordProps<
  Vue,
  Data,
  Methods,
  Computed,
  Props
> = {
  props: {
    ...
    getFormatter: {
      type: Function,
      required: false,
      default: () => (_: number) => (d: any) => d
    },
...
}
...
    tableData() {
       ...
                return {
                  [j]: this.getFormatter(j)(data[i])
                }
```

***MonitoringConfirmedCasesNumberCard.vue***
```vue
<template>
...
    <simple-mixed-chart
    ...
      :getFormatter="getFormatter"
    ...
    >
...
</template>

<script>
...
  data() {
    ...
    const getFormatter = j => {
      if (j === 1) return d => d.toFixed(1)
      return d => d
    }
...
</script>
```

**Comment by kaizumaki** [comment]
@Keyhoh ご提案ありがとうございます！こんなにすっきり書けるのですね。ちなみに桁数は各Card内の `const getFormatter` 内の関数に指定していく、ということになるのでしょうか？

**Comment by Keyhoh** [comment]
@kaizumaki 
`getFormatter`関数は各カラムに対応するフォーマッタを返す関数として定義しているので、  
桁数は`getFormatter`内の関数に指定していくで良いと思います。

**Comment by kaizumaki** [comment]
@Keyhoh 「ここの数値は小数点桁数ですよ！」とわかりやすいようにできるといいですね。変数で定義するとか。（漠然としててすみません。）
いちどPRを出してみてもらえますか？
