### ISSUE TITLE
[refactor] `DataView.vue` から SNS シェアに関するコードを分離する

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#4436]
## 改善詳細 / Details of Improvement
- [`DataView.vue`](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/DataView.vue) の責務が大きい
  - チャートや説明文のレイアウト
  - チャートデータのテーブル
  - SNS シェア
- SNS シェアに関するコードが半分程度を占めているので、これを別コンポーネントに切り出すと見通しが良くなりそう
  - `template`
  - `data`, `computed`, `watch`, `methods`
  - `style`

## スクリーンショット / Screenshot
リファクタリングなので見た目の変更はありません。

## 期待する見せ方・挙動 / Expected behavior
- `DataView` から SNS シェアに関するコードが分離されること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
#4176 の件と一緒にやれませんかね…。

**Comment by shgtkshruch** [comment]
#4716 と一緒にやると影響範囲がかなり広がるので、別々に進めたほうがいいと思います。
