### ISSUE TITLE
【改善提案】日付の表示を統一する

### ISSUE THREAD

**Issue by fussy113** [tokyo-metropolitan-gov/covid19#444]
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 日付の表示が`YYYY/mm/dd`と`YYYY年mm月dd日`の二種類が混在しています。

## スクリーンショット / Screenshot

<img width="637" alt="提案箇所" src="https://user-images.githubusercontent.com/15154105/75948583-36ea4300-5ee7-11ea-87a5-0aadbc4b97b4.png">

グラフ内は`mm/dd`で表示されています。

## 期待する見せ方・挙動 / Expected behavior
* 日付を/区切りに統一する。
  * 年月日でももちろん良いが、グラフのx軸が煩雑化してしまうのではと考えてます。
  * [多言語対応](#62)を考えるなら/で統一しておくと後々楽になると考えてます。

**Comment by mikkame** [comment]
YYYY/mm/dd に統一する方向で進めようと思います。
グラフなど、表示領域が狭い場所は mm/dd で統一していきます

**Comment by fussy113** [comment]
@mikkame 

判断ありがとうございます。

[日付処理系ライブラリの決定版「Moment.js」を使ってNuxt.jsでの日付操作を楽にしよう](https://papadays.com/post/4mbkrhvhxh1gvdpf7bswnm/)

すでにプロジェクト内で`@nuxt/moment`導入されているのでそちらを利用しての実装を検討しています。

**Comment by mikkame** [comment]
@fussy113 ありがとうございます！
現状元データに正規化された日付がないので
一旦参照データに正規化（Y-m-d H:i:s形式など）したデータを追加し
順次対応後、参照データから未整形の日付を消す方向で検討しています。
その上でmomentで正規化された日時をパースして使うのがよいのかな、と考えております

**Comment by fussy113** [comment]
@mikkame 
> 現状元データに正規化された日付がないので
> 一旦参照データに正規化（Y-m-d H:i:s形式など）したデータを追加し
> 順次対応後、参照データから未整形の日付を消す方向で検討しています。

順次進めていくこと、理解いたしました！

**Comment by ocean3fish** [comment]
ちなみに、元データの方も順次政府標準に合わせて正規化を進める予定で、日付に関してはISO8601 及び JIS X 0301(日付及び時刻の表記)に準拠した
`YYYY-MM-DD`
の形式になる予定です。

**Comment by ocean3fish** [comment]
データ標準については色々なデータに対応したガイドラインが作られていたりするので、よろしければご参照ください！
https://cio.go.jp/guides#renkeimodel

**Comment by daitasu** [comment]
こちら #486 と一緒に対応します！

**Comment by ocean3fish** [comment]
#486 でご対応いただけたので、クローズさせて頂きます！ありがとうございました！
