### ISSUE TITLE
Issue Template を内容で分ける

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#445]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* バグ、改善提案とも同じテンプレートになっている
* それぞれで必要な情報が異なる

## 期待する見せ方・挙動 / Expected behavior
* バグ、改善提案それぞれでテンプレートを作成する
  * `.github/ISSUE_TEMPLATE.md` を削除
  * `.github/ISSUE_TEMPLATE` ディレクトリを作成し、各テンプレート.mdを作成

参考: https://help.github.com/ja/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates

**Comment by amotarao** [comment]
@potato4d https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
name:, about: が必須のようです

**Comment by yokinist** [comment]
#475 で再対応🙏
ありがとうございました！
