### ISSUE TITLE
[refactor] `SevereCaseBarChart.vue` から累計値に関するコードを削除

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#4450]
## 改善詳細 / Details of Improvement
- issue 起票時点では、「モニタリング指標(4)重症患者数」に累計値を表示していません
  - 日別の値のみ表示
- 「モニタリング指標(4)重症患者数」を実装している [`SevereCaseBarChart.vue`](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/SevereCaseBarChart.vue) には、累計値に関するコードがいくつかあります
- もし累計値を表示する必要がないなら、これらのコードを削除するとコードの見通しが良くなりそうです
  - 100行くらい消せると思います
- 近い将来累計値を表示する予定があるなど、これらのコードを残しておく理由があれば issue を close してくださいmm

![スクリーンショット 2020-05-24 8 52 04](https://user-images.githubusercontent.com/5207601/82742659-df4bcd00-9d9b-11ea-8180-52f749cae1c8.png)

## スクリーンショット / Screenshot
今は `dataKind` が `transition` しかないので、以下のような条件分岐は不要ではないかと思っています。
（というよりも、データの種類が 1つであれば `dataKind` 自体なくてもいいと思います）

https://github.com/tokyo-metropolitan-gov/covid19/blob/d2523cf334e2f4711e7c46d8b3ac91b9ada7f8ed/components/SevereCaseBarChart.vue#L206-L229

https://github.com/tokyo-metropolitan-gov/covid19/blob/d2523cf334e2f4711e7c46d8b3ac91b9ada7f8ed/components/SevereCaseBarChart.vue#L230-L265

https://github.com/tokyo-metropolitan-gov/covid19/blob/d2523cf334e2f4711e7c46d8b3ac91b9ada7f8ed/components/SevereCaseBarChart.vue#L355-L384

## 期待する見せ方・挙動 / Expected behavior
- もし不要なら `SevereCaseBarChart.vue` から累計値に関するコードを削除する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
急ぎの対応だったためそのあたりをすっ飛ばしていました。
対応いただきありがとうございます！
