### ISSUE TITLE
[refactor] `PositiveRateMixedChart.vue`, `SimpleMixedChart.vue` から未使用メソッドを削除

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#4451]
## 改善詳細 / Details of Improvement
- [`PositiveRateMixedChart.vue`](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/PositiveRateMixedChart.vue) と [`SimpleMixedChart.vue`](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/SimpleMixedChart.vue) から、以下の未使用メソッドを削除
  - `sum`
  - `cumulative`
  - `cumulativeSum`
  - `eachArraySum`

## スクリーンショット / Screenshot
https://github.com/tokyo-metropolitan-gov/covid19/blob/d2523cf334e2f4711e7c46d8b3ac91b9ada7f8ed/components/PositiveRateMixedChart.vue#L613-L651

https://github.com/tokyo-metropolitan-gov/covid19/blob/d2523cf334e2f4711e7c46d8b3ac91b9ada7f8ed/components/SimpleMixedChart.vue#L530-L568

## 期待する見せ方・挙動 / Expected behavior
- [`PositiveRateMixedChart`](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/PositiveRateMixedChart.vue) と [`SimpleMixedChart.vue`](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/SimpleMixedChart.vue) から未使用メソッドが削除されること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
こちらも急ぎの対応だったためそのあたりをすっ飛ばしていました。
対応いただきありがとうございます！
