### ISSUE TITLE
[refactor] PositiveRateCard.vue および UntrackedRateCard.vue の定数統合

### ISSUE THREAD

**Issue by yuu26jp** [tokyo-metropolitan-gov/covid19#4459]
## 改善詳細 / Details of Improvement
- 下記ファイル内で重複している定数の~整理~ 統合
  - components/PositiveRateMixedChart.vue
  - components/UntrackedRateMixedChart.vue
  - components/cards/PositiveRateCard.vue
  - components/cards/UntrackedRateCard.vue

## スクリーンショット / Screenshot
リファクタリングのため画面の変更はありません。
該当ソースコードは以下の部分です。

https://github.com/tokyo-metropolitan-gov/covid19/blob/07ca38924ef41451cc62a16dad0bd988453791a5/components/cards/PositiveRateCard.vue#L87-L96
https://github.com/tokyo-metropolitan-gov/covid19/blob/07ca38924ef41451cc62a16dad0bd988453791a5/components/cards/UntrackedRateCard.vue#L70-L79

## 期待する見せ方・挙動 / Expected behavior
- 挙動に影響を与えずに対象4ファイルの定数が~整理~統合されること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yuu26jp** [comment]
手元で作業を進めてはいますが、#4423, #4424 とのコンフリクトするため待機中です。

**Comment by goki90210** [comment]
確認ですが、作業的には定数を統合する方向ということですよね？
（整理だと例えば全て別のキーにばらすことも考えられるので）

**Comment by yuu26jp** [comment]
@goki90210 はい、定数を一つにまとめる方向で修正しています。
