### ISSUE TITLE
元データ.xslx のダミーをリポジトリに追加する

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#446]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 元データ.xslx を json に変換する `tool/` に xslx がない
* 元データがどういうファイルか分からない

## 期待する見せ方・挙動 / Expected behavior
* 形式が同じなダミーの.xslx を追加する

**Comment by mikkame** [comment]
現在、xlsxにアクセス制限がありコアスタッフのみアクセスできる状況となっています。
確かにダミーデータがないと属人的に（すでになってしまっているんですが）なってしまうので

公開して良い範囲を確認します。

**Comment by mikkame** [comment]
確定ではありませんが状況を俯瞰すると
アクセルではなくcsvを置いていくようになるようなので次第に脱エクセルをする方向が理想のようです
