### ISSUE TITLE
Vuetify の css を削減

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#448]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* [index.html](https://stopcovid19.metro.tokyo.lg.jp/) の 254KB (gzip前) のうち、248KB が Vuetify の CSS
* Vuetify のCSSのうち、97.4% が不使用 (下記)

## スクリーンショット / Screenshot

<img width="586" alt="スクリーンショット 2020-03-05 15 29 27" src="https://user-images.githubusercontent.com/8909592/75954076-25f4fe00-5ef6-11ea-86ca-6ce84e5883e3.png">

## 期待する見せ方・挙動 / Expected behavior
* 必要なセレクタのみが出力されるようにする

**Comment by Hee-San** [comment]
**vuetify-loder**を使うことで、使用しているコンポーネントのみがインポートされるようです。
https://vuetifyjs.com/en/customization/a-la-carte#vuetify-loader

しかし、nuxtでVuetifyを使う場合、デフォルトでvuetify-loderが入るようです。
https://github.com/nuxt-community/vuetify-module#treeshake

> Enabled only for production by default.
> `Default: process.env.NODE_ENV === 'production'`

このあたりが怪しそうですね

**Comment by shun91** [comment]
こちら少し調べてみたのですが、

> Enabled only for production by default.
> Default: process.env.NODE_ENV === 'production'

の通り、`process.env.NODE_ENV === 'production'` なら treeShake が有効になります。
https://stopcovid19.metro.tokyo.lg.jp/ は `process.env.NODE_ENV === 'production'` でビルドされており、つまりtreeShakeが有効な状態で上記のような不使用なCSSが吐き出されているので、こちらは関係ないのかなと思われます。

97.4%も不要なCSSが読み込まれているのは何とかしたいですね。。

**Comment by halsk** [comment]
#31 のスコアが悪いのもそれが原因ですね。なんとかしたい。。

**Comment by halsk** [comment]
IMPORTANT ラベルつけときました。

**Comment by potato4d** [comment]
ちょっとやってみます(20分くらいでダメだったら一旦手を話します)

**Comment by shun91** [comment]
まだ全然核心はないのですが、themeを無効にしたらいけるのではと思っており、調査してみますーmm

**Comment by potato4d** [comment]
PurgeCSS で倒したほうが最小になるかと思いますので、私の方からはそのアプローチで試しますね

**Comment by potato4d** [comment]
できちゃった
https://github.com/tokyo-metropolitan-gov/covid19/pull/477
