### ISSUE TITLE
[refactor] `DataView.vue` から DataTable に関するコードを分離する

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#4484]
## 改善詳細 / Details of Improvement
- [`DataView.vue`](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/DataView.vue) から DataTable（各カードのテーブルを表示する部分） に関するコードを分離します
- DataTable 専用の `data` や `methods` などがあるので、これらを分離すると `DataView` 自体は状態を持たない、レイアウトを制御するだけのコンポーネントになります

## スクリーンショット / Screenshot
リファクタリングなので見た目の変更はありません

## 期待する見せ方・挙動 / Expected behavior
- `DataView.vue` から DataTable に関するコードが分離されること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
これが終わったらDataViewのの名前自体を変えられるということですね。

**Comment by shgtkshruch** [comment]
一連の修正は `DataView` の責務を整理するのが目的です。
コンポーネントの切り出し自体はこれで終わりなので、`DataView` については適切なコンポーネント名に変えていただいて大丈夫です。
