### ISSUE TITLE
[モニタリング指標] レスポンシブ時のグラフの大きさや軸の表示が崩れている

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#4486]
## 起こっている問題 / The Problem
- 画面の横幅を 770px ~ 959px の際に以下のグラフで表示が崩れている箇所があります
  - 最初から上記画面幅で表示したら問題なさそう
  - ブラウザで画面幅を変えた場合のみ起こる？
- グラフの横幅が小さい
  - `モニタリング指標(2)新規陽性者における接触歴等不明率`
  - `モニタリング指標(4)重症患者数`
  - `モニタリング指標(5)入院患者数`
- Y軸がグラフに重なっている
  - `モニタリング指標(6)PCR検査の陽性率 `

## スクリーンショット / Screenshot
グラフの横幅が小さい
![スクリーンショット 2020-05-25 14 00 14](https://user-images.githubusercontent.com/5207601/82779824-2915df80-9e90-11ea-8b44-7e21e72880cc.png)

グラフの横幅が小さい
![スクリーンショット 2020-05-25 14 00 39](https://user-images.githubusercontent.com/5207601/82779831-2d41fd00-9e90-11ea-8189-a6526ef840ca.png)

グラフの横幅が小さい
![スクリーンショット 2020-05-25 14 10 55](https://user-images.githubusercontent.com/5207601/82780264-97a76d00-9e91-11ea-8611-a7fe71de2f3a.png)

Y軸がグラフに重なっている
![スクリーンショット 2020-05-25 13 59 28](https://user-images.githubusercontent.com/5207601/82779836-303ced80-9e90-11ea-9670-8f14d2b076ee.png)

## 期待する見せ方・挙動 / Expected Behavior
- グラフの横幅が他のグラフと揃うこと
- Y軸がグラフに重ならないこと

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/ を開く
1. 画面の横幅を 770px ~ 959px にする

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari / Firefox

**Comment by goki90210** [comment]
ブラウザで画面幅を変えた場合のみ起こるようですね。

各モニタリング指標のcanvasの上位で設定されるstyle="width: ...px;"の値がばらついてます。

BootstrapのようにCSSでなんとかならないものでしょうか？

**Comment by kikd** [comment]
vuetify使っているのであれば、https://vuetifyjs.com/en/styles/display/ が適用できる気がします。

**Comment by Nekoya3** [comment]
(6)の場合はmountedの際にグラフ幅を取得し、オーバーレイしているグラフ軸を描画しているため、mounted後に画面サイズが変更されるとそれに追従できません。（対応策があればお教えください）
横スクロール機能の関係でこのような処理が必要となっています。
