### ISSUE TITLE
サイドナビの外部リンクを変更（緊急事態宣言解除対応）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4490]
サイドナビゲーション内の以下の外部リンクの変更をお願いします。

（変更前）
リンクタイトル：東京都主催等 中止又は延期するイベント等
リンク先URL：　https://www.seisakukikaku.metro.tokyo.lg.jp/information/event00.html
↓
（変更後）
リンクタイトル：休止中の都民利用施設の再開等
リンク先URL：　https://www.seisakukikaku.metro.tokyo.lg.jp/information/facility02.html
※リンク先の政策企画局HPについては、本日の夜に開通予定です。

**Comment by InadomeLabo** [comment]
やります。
