### ISSUE TITLE
カードとその個別ページでタイトルや更新時刻が異なる

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#4491]
## 起こっている問題 / The Problem
- カードとその個別ページで タイトル || 更新時刻 が異なるものがあります
- 更新時刻が異なるもの
  - [`検査陽性者の状況`](https://stopcovid19.metro.tokyo.lg.jp/cards/details-of-confirmed-cases/)
- タイトルが異なるもの
  - [`モニタリング指標(6)PCR検査の陽性率`](https://stopcovid19.metro.tokyo.lg.jp/cards/positive-rate/)
  - [`モニタリング指標(7)受診相談窓口における相談件数`](https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-number-of-reports-to-covid19-consultation-desk/)
- 更新時刻が異なるのはバグだと思っているのですが、タイトルが異なるのは意図した実装なのでしょうか？

### 更新時刻が異なる

- [`検査陽性者の状況`](https://stopcovid19.metro.tokyo.lg.jp/cards/details-of-confirmed-cases/)
![スクリーンショット 2020-05-25 16 44 05](https://user-images.githubusercontent.com/5207601/82790697-75204e80-9ea7-11ea-9c1a-8d06aa91dfbc.png)

### タイトルが異なる

- [`モニタリング指標(6)PCR検査の陽性率`](https://stopcovid19.metro.tokyo.lg.jp/cards/positive-rate/)
![スクリーンショット 2020-05-25 16 44 51](https://user-images.githubusercontent.com/5207601/82790703-7782a880-9ea7-11ea-9a8e-ab667f67edac.png)

-  [`モニタリング指標(7)受診相談窓口における相談件数`](https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-number-of-reports-to-covid19-consultation-desk/)
![スクリーンショット 2020-05-25 16 45 23](https://user-images.githubusercontent.com/5207601/82790707-78b3d580-9ea7-11ea-9a95-94e63e2e408c.png)

## 期待する見せ方・挙動 / Expected Behavior
- 仕様を確認したいですが、個人的にはカードとページについては、タイトルと更新時刻は一致していたほうがわかりやすいと思いました
- （一致させる場合は）今の実装のようにベタに書かずに、カードコンポーネントからタイトルと更新時刻を取得する実装に変えるのも手だと思います
  - このような実装にすると、更新時刻を取得するために データjson を読み込む必要がなくなります ref: #4410

https://github.com/tokyo-metropolitan-gov/covid19/blob/6d7036fd26e21c476cd2a61b27bf9308a17ab9e8/pages/cards/_card.vue#L140-L143

## 起こっている問題の再現手段 / Steps to Reproduce
1. 本番環境で、上記各カードの詳細ページを開く
1. Developer Tools で `head` 要素内の `title` や `description` を確認

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
ご指摘ありがとうございます。実装した本人ですが、ただただ実装ミスをしただけです...本当に申し訳ありません。

>（一致させる場合は）今の実装のようにベタに書かずに、カードコンポーネントからタイトルと更新時刻を取得する実装に変えるのも手だと思います

もし、この実装が可能なのであれば今後のカード追加の際にこのようなミスが減るため、PRを立てていただいても良いでしょうか？
タイトルと更新日時を修正しようかと思いましたが、今後のことを考えると私がただ直すよりも上記機能を実装いただいた方がよいかと思います。
（私には実装方法がわからないためお任せする形になり申し訳ありません。）

**Comment by shgtkshruch** [comment]
コメントありがとうございます。
`page/cards/_card.vue` はカード本体に修正があっても忘れがちだったりするので、難しいですよね..

カードからタイトルと更新時刻を取得する方法で #4499 に実装してみましたので、お時間があるときに見ていただけると嬉しいです。
