### ISSUE TITLE
「企業の皆様・はたらく皆様へ」内の文章訂正

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#4508]
## 起こっている問題 / The Problem
[企業の皆様・はたらく皆様へ](https://stopcovid19.metro.tokyo.lg.jp/worker)ページの「新しいワークスタイルや企業活動の東京モデル「スムーズビズ」」は現在以下のような文章ですが、

> テレワーク・時差出勤などスムーズビズの取組は、新型コロナウイルス感染症の対策としても効果的です。感染症対策として、東京2020大会時の交通混雑緩和に向けた取組の前倒しをお願いします（助成率：5分の4以内）。

このうち、文章末尾の「（助成率：5分の4以内）」については不要でした。

訂正後の文章は以下のようになります。

> テレワーク・時差出勤などスムーズビズの取組は、新型コロナウイルス感染症の対策としても効果的です。感染症対策として、東京2020大会時の交通混雑緩和に向けた取組の前倒しをお願いします。

## 期待する見せ方・挙動 / Expected Behavior
- 上記「訂正後の文章」が表示される

## 動作環境・ブラウザ / Environment
- どの環境でも

**Comment by InadomeLabo** [comment]
やります。
