### ISSUE TITLE
「検査実施人数」グラフタイトル変更・「モニタリング指標」注釈修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4515]
「検査実施人数」グラフタイトルと「モニタリング指標」注釈の変更をお願いします。

- 「検査実施人数」グラフタイトル変更
変更後： `検査実施人数（健康安全研究センターによる実施分）`

- 「モニタリング指標」注釈修正
１番目の注釈を修正してください。
修正前
`※（1）、（2）、（6）、（7）は、7日間移動平均で算出（たとえば、5月7日の移動平均値は、5月1日から5月7日までの実績値を平均したもの）`
↓
修正後
`※（1）、（2）、（6）、（7）は、7日間移動平均で算出（たとえば、5月7日の移動平均値は、5月1日から5月7日までの実績値を平均したもの）。また、（1）の数字が10人以下となった場合は、（2）及び（3）は参考値とする`

**Comment by InadomeLabo** [comment]
やります。
