### ISSUE TITLE
plugins/vue-chart.tsで引数のnullチェックをしていない

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4534]
## 起こっている問題 / The Problem
https://github.com/tokyo-metropolitan-gov/covid19/blob/bb8d44755c9678fc70b561bfe5acebd2bd157080/plugins/vue-chart.ts#L149-L152

https://github.com/tokyo-metropolitan-gov/covid19/blob/bb8d44755c9678fc70b561bfe5acebd2bd157080/plugins/vue-chart.ts#L202-L208

`chartInstance`のnullチェックをしていないとSonarQubeで指摘されています。
（この手の指摘はplugins/vue-chart.tsのみです。）

chartInstanceのnullチェックを行うべきです。
（chartInstanceがnull/undefinedになることは100%ないのであればこの限りではありません。）

## 期待する見せ方・挙動 / Expected Behavior
- chartInstanceのnullチェックを行う。

## 起こっている問題の再現手段 / Steps to Reproduce
なし

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
やってみました。
ご確認をお願いいたします

**Comment by goki90210** [comment]
この件とは別にnull assertion (!. operation) の使用の是非もあると思います。
（別のIssueにしたほうがいいですよね？）

**Comment by MaySoMusician** [comment]
@goki90210 SonarQubeに関してお伺いします。本プロジェクトでは下記コードの通り
https://github.com/tokyo-metropolitan-gov/covid19/blob/1c64b1188211bba64750504bb102f82c2732282a/tsconfig.json#L15
となっており、これには `--strictNullChecks` が含まれます。このオプションにより明示的に `null` 型・ `undefined` 型が割り当てられていない変数や引数にはそれらの値が代入できなくなります。
https://github.com/tokyo-metropolitan-gov/covid19/pull/4561#issuecomment-635077933 にて `chartInstance === null` の場合にchartInstanceが `never` 型になるのもこの理由によるものです。

つまり

> （chartInstanceがnull/undefinedになることは100%ないのであればこの限りではありません。）

については「TypeScriptの仕様とその設定上は100%ない」が回答となります。
以上を踏まえた上で、SonarQubeとしては `--strictNullChecks` が有効になっていることを想定してコード解析を実施するような設定はあるのでしょうか？

---

なお、 `--strictNullChecks` は明示的に `null` との共用体にすれば代入できるため、例えば `chartInstance.canvas` については
```ts
canvas: HTMLCanvasElement | null
```
と定義されており `null` の可能性は十分あり得るので、

> null assertion (!. operatorなど) の使用

などに関しては引き続き検討する必要があります。

**Comment by goki90210** [comment]
この件に関しては
> （chartInstanceがnull/undefinedになることは100%ないのであればこの限りではありません。）
に該当しますのでクローズします。

> SonarQubeとしては --strictNullChecks が有効になっていることを想定してコード解析を実施するような設定はあるのでしょうか？

調べましたが、知る限りではルールの変更以外にはないようです…。
