### ISSUE TITLE
グラフ・表の並び順変更

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4545]
サイトトップのグラフ・表のカードの並べ替えをお願いします。
順番は以下のイメージの通りです。緑ベタのカードの順番が大きな変更点です。

![200527-2グラフカード順](https://user-images.githubusercontent.com/14883063/82983919-05879c00-a02c-11ea-8b5a-194f4c989ca6.png)

**Comment by InadomeLabo** [comment]
やります。
