### ISSUE TITLE
Google Chromeで閲覧すると翻訳するかどうかの確認ダイアログが出てしまう

### ISSUE THREAD

**Issue by koizoom1** [tokyo-metropolitan-gov/covid19#455]
- [ ] バグ / Bug

## 起こっている問題 / Occurred problem
* Google Chromeでサイトを立ち上げると「翻訳しますか」のダイアログが表示される
* htmlソースを確認すると「lang="en"」になっているのでここを修正すると良さそう
<img width="499" alt="スクリーンショット 2020-03-05 16 47 39" src="https://user-images.githubusercontent.com/1808750/75959466-a8cf8600-5f01-11ea-9362-ee0e825c3349.png">

## スクリーンショット / Screenshot

<img width="632" alt="スクリーンショット 2020-03-05 16 47 30" src="https://user-images.githubusercontent.com/1808750/75959342-63ab5400-5f01-11ea-8a8d-e6a5d780b8dd.png">

## 期待する見せ方・挙動 / Expected behavior
* Googleの翻訳しますかダイアログが出ないようにする

## 起こっている問題の再現手段 / Steps to reproduce
1. Chromeの翻訳モードをオンにして閲覧すると再現

## 動作環境・ブラウザ / Environment
* MacOS 10.14.6 Chrome 80.0.3987.122

**Comment by okawa-h** [comment]
こちら対応します〜。

**Comment by koizoom1** [comment]
ありがとうございます！

**Comment by mikkame** [comment]
すみません！同じIssueがあってマージされたような気がします。
こちらテストサイトです。
https://dev-covid19-tokyo.netlify.com/
こちらでも再現しますでしょうか

**Comment by mikkame** [comment]
本日〜明日にかけて本番更新予定です。

**Comment by mikkame** [comment]
次回の更新で反映される予定です

**Comment by koizoom1** [comment]
テストサイトでは再現しませんでした。お騒がせしてすみません！

**Comment by potato4d** [comment]
lang 対応済みなので、今日リリースされると修正される認識です
