### ISSUE TITLE
都営地下鉄の利用者数の推移グラフの更新日がダミーなので正しい日付に直す

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#456]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* /data/metro.json を修正
- 正しい日付は`2020/2/28  19:10:00`

## 期待する見せ方・挙動 / Expected behavior
* `2020/2/28  19:10:00`　に修正

**Comment by okawa-h** [comment]
こちらですが、`2020/2/28 19:00`の間違いですかね？
