### ISSUE TITLE
[モニタリング指標] 総括表の「項目」の括弧を半角で表示する

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#4571]
## 改善詳細 / Details of Improvement
- 現在、モニタリング指標総括表の項目では `（1）`  というように **全角括弧+半角数字** 、対応する各グラフタイトルでは `(1)` というように **半角括弧+半角数字** と表示されていますが、これをどちらも **半角括弧+半角数字** で表示するようにしたい。
- 元データJSONでは **全角括弧+全角数字** で表記されており、下記コードで半角に置き換えている。 https://github.com/tokyo-metropolitan-gov/covid19/blob/1c64b1188211bba64750504bb102f82c2732282a/components/MonitoringStatusOverviewTable.vue#L67-L72 この部分の正規表現に全角括弧を含めることで対応可能と思われる。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/34566290/83084972-83e44c80-a0c5-11ea-8397-895a85f2e3bb.png)

## 期待する見せ方・挙動 / Expected behavior
- `（1）新規陽性者数` が `(1)新規陽性者数` と表示されるようになる

## 動作環境・ブラウザ / Environment
- 依存なし

**Comment by goki90210** [comment]
個人的には賛同するのですが、
このあたりの基準はどこかで決めているのでしょうか？

- 括弧の使い方について（半角文字のみで構成している場合は半角、それ以外の文字が含まれる場合は全角？）
だけでなく、
- 全角英数字の使用の是非（使わない？）

にもかかわります。

1.  (1) 新規陽性者数
2. （1）新規陽性者数
3. （１）新規陽性者数
のどれが良いかということですよね？

**Comment by MaySoMusician** [comment]
全体的な方針としては確定していませんが、本件については翻訳レビューチームから
`（1）` （全角括弧+半角数字）を `(1)` （半角括弧+半角数字）に都度直すよりは初めから半角括弧+半角数字である方が良いとの要望がありました

**Comment by goki90210** [comment]
なるほど…。
翻訳レビューチームからの要望ということで理解しました。

ISO/IEC 8859な人々にとっては全角文字はいらないですからね…。
