### ISSUE TITLE
Non-Null Assertion Operatorの使用の是非について

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4573]
## 改善詳細 / Details of Improvement
**（注：他のIssueより優先度は低いです）**
https://github.com/tokyo-metropolitan-gov/covid19/blob/1c64b1188211bba64750504bb102f82c2732282a/plugins/vue-chart.ts#L207
（これが代表的なので提示しますが、他にもあります。）

非nullアサーション演算子(Non-Null Assertion Operator)
[https://typescript-jp.gitbook.io/deep-dive/intro/strictnullchecks#nullasshonnon-null-assertion-operator](url)

! ポストフィックス式演算子の使用については

> これは単なるアサーションであり、型アサーションと同じように、あなたは値がnullでないことを確認する責任があることに注意してください。非nullアサーションは、本質的にはコンパイラに"それはnullでないことが分かっているから、nullではないものとして使います"と伝えるものです。

とあります。
「それはnullでないことが分かっている」というのはどこかで共有されているのでしょうか？

すべてのプロパティについてnull/undefinedのチェックを行えといっているのではないのですが、何らかの形で担保されていることは示すべきだろうとは思います。

! ポストフィックス式演算子が使用されているのは 
- components/AgencyBarChart.vue
- components/ConfirmedCasesIncreaseRatioByWeekChart.vue
- components/DashedRectangleTimeBarChart.vue
- components/MetroBarChart.vue
- components/MonitoringConfirmedCasesChart.vue
- components/MonitoringConsultationDeskReportChart.vue
- components/PositiveRateMixedChart.vue
- components/SevereCaseBarChart.vue
- components/TimeBarChart.vue
- components/TimeStackedBarChart.vue
- components/UntrackedRateMixedChart.vue
- pages/flow.vue
- plugins/vue-chart.ts 

があるので影響範囲は大きいですね。
なにか良い方法はないでしょうか。

## 期待する見せ方・挙動 / Expected behavior
- ! ポストフィックス式演算子を使用している箇所に対して何らかの形でnull/undefinedにならないことを担保する、あるいは、! ポストフィックス式演算子の使用をやめnull/undefinedチェックを行う。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by munierujp** [comment]
型がNullableな値の`null`を無視しているので、実行時にエラーが発生する可能性はありますね。
該当箇所でエラー処理をしているのであれば、動作としてはひとまず問題ないでしょう（コード的にはあまりよろしくありませんが）。
たとえば、例示されている`vue-chart.ts`ではtry-catchでキャッチしたエラーを単に無視しているので、いずれかの値が存在しない場合は何もせずに終了します。

いくつか、ベターな書き方が考えられます。

## Optional Chaininhainingを使用
[Optional Chaininhaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining)を使えば、型安全なコードが書けそうです。

例（動作は未検証）：

```ts
const element = chartInstance.canvas
  ?.parentElement
  ?.parentElement
  ?.parentElement
if (element == undefined) {
  return
}
// NOTE: Type Guardにより、ここから先は element の型は HTMLElement

const { width } = chartInstance
if (width == undefined) {
  return
}
// NOTE: Type Guardにより、ここから先は width の型は number

element.scrollLeft = width
```

## DOM操作用のライブラリを使用
あるいは、[Cash](https://github.com/fabiospampinato/cash)などのDOM操作をラップしたライブラリを使うという方法もあります（Cashは、jQueryライクなAPIでDOM操作ができる軽量ライブラリです）。

例（動作は未検証）：

```ts
$(chartInstance.canvas)
  .parent()
  .parent()
  .parent()
  .prop('scrollLeft', chartInstance.width)
```

個人的にはバニラJS派ですが、簡潔に書けるのを好む人もいるでしょう。

---
ところで、そもそもVue.jsを使っていながらこのようなDOM操作をしていることに違和感があるのですが、vue-chartjsを使う場合はそういうものなのでしょうか？

**Comment by goki90210** [comment]
> ところで、そもそもVue.jsを使っていながらこのようなDOM操作をしていることに違和感があるのですが、vue-chartjsを使う場合はそういうものなのでしょうか？

私もそう思います。#4486 も関係あるのでしょうか？
