### ISSUE TITLE
plugins/vue-chart.ts に処理の重複がある

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4574]
## 改善詳細 / Details of Improvement
- plugins/vue-chart.ts に処理の重複がある。

## スクリーンショット / Screenshot
https://github.com/tokyo-metropolitan-gov/covid19/blob/1c64b1188211bba64750504bb102f82c2732282a/plugins/vue-chart.ts#L60-L61
の
https://github.com/tokyo-metropolitan-gov/covid19/blob/1c64b1188211bba64750504bb102f82c2732282a/plugins/vue-chart.ts#L78-L81
と
https://github.com/tokyo-metropolitan-gov/covid19/blob/1c64b1188211bba64750504bb102f82c2732282a/plugins/vue-chart.ts#L86-L87
の
https://github.com/tokyo-metropolitan-gov/covid19/blob/1c64b1188211bba64750504bb102f82c2732282a/plugins/vue-chart.ts#L104-L107
が重複しています。

## 期待する見せ方・挙動 / Expected behavior
- 統合が可能なら統合したい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
`mounted:` は Vue インスタンスそれぞれのライフサイクルフックなので、それをいったん外して他のどこかに統合するといったアプローチは取れない前提を置きます。

たとえば、以下のような書き方をするとしたら可読性、維持管理のしやすさという点では現実的でしょうか？

```
      mounted() {
        this.renderChart(this.chartData, this.options)
      }

```

もしもいけそうであれば、 #4561 に統合しようかと思います

**Comment by goki90210** [comment]
> 統合が可能なら統合したい。
ですので、

> mounted: は Vue インスタンスそれぞれのライフサイクルフックなので、それをいったん外して他のどこかに統合するといったアプローチは取れない前提を置きます。

という理由で不可能ということであればよいです。
SonarQubeで指摘されているのは、mounted()の部分だけなのですが
気になっているのは'bar'と'line-chart'で違いがextends:だけなんですよね。
こちらの観点でも統合するのは難しいでしょうか？

私の方で具体的な修正が思い浮かばないので申し訳ないですが…。

**Comment by mcdmaster** [comment]
なるほど、いくつかある Vue.component を統合してしまおうという主旨ですね。
気づきませんでした。ちょっと見てみましょうか

**Comment by mcdmaster** [comment]
たいへんお待たせしました。
上記 PR で、Vue.component のチャート描画部分を切り出して一つにまとめるのをやってみました。
ご確認をお願いいたします
