### ISSUE TITLE
types/chart.d.tsで使用しているクラス名が一般的でないものがある

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4581]
## 起こっている問題 / The Problem
https://github.com/tokyo-metropolitan-gov/covid19/blob/52d8e648ee6ab64bbb150b45b9f10b614dbf28a5/types/chart.d.ts#L3-L6

クラス名がアンダースコア始まりになっているため、SonarQubeにより ^[A-Z][a-zA-Z0-9]*$（＝Pascal (Upper Camel) Case）でないと指摘されています。

これは、なにか意図があるのでしょうか？
これを修正することによる影響は
- plugins\chartjs-adapter-dayjs.ts
のみのようです。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/30145857/83108289-8745fb00-a0fa-11ea-95d4-c376a532100c.png)

## 期待する見せ方・挙動 / Expected Behavior
- クラス名をPascal (Upper Camel) Caseにする。

## 起こっている問題の再現手段 / Steps to Reproduce
なし

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
chart.jsが使用する日付関連ライブラリを強制的にmoment.jsからdayjsに置き換えるために、本来publicではない `Chart.__adapters` にアクセスする必要がありました（使用している chart.js のバージョンではまだadapterの分離が終わっていなかったため。参考: https://github.com/tokyo-metropolitan-gov/covid19/issues/2079#issuecomment-602187102 ）

主な議論は #2079 、 PRは #2081 となります。

当該クラス名はchart.js側で命名されているためおそらく変更できないかと思われます

**Comment by goki90210** [comment]
修正できないということで承知しました。
ありがとうございます。
