### ISSUE TITLE
Build がコケても deploy が止まらず、サイトを更新してしまう

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#46]
これはいかん。
https://github.com/tokyo-metropolitan-gov/covid19/runs/477478266?check_suite_focus=true

**Comment by yokinist** [comment]
[![Image from Gyazo](https://i.gyazo.com/b8c936d8c0ebed39a1bf7577a1fd28d9.png)](https://gyazo.com/b8c936d8c0ebed39a1bf7577a1fd28d9)
いけてるきがする・・

**Comment by yokinist** [comment]
[![Image from Gyazo](https://i.gyazo.com/e6319f50f2cc0d4bf556b232ea978e5b.png)](https://gyazo.com/e6319f50f2cc0d4bf556b232ea978e5b)

bulidでfailしてるはずなのにsuccessになっている真相を解明する

**Comment by yokinist** [comment]
https://nuxtjs.org/guide/commands/#static-generated-deployment-pre-rendered-
`--fail-on-page-error` オプションで解決
