### ISSUE TITLE
各グラフの累計表記がNaNになってしまう

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#460]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 検査実施日別状況以外で発生
* https://dev-covid19-tokyo.netlify.com/
* 現在のテスト環境で確認できます

## スクリーンショット / Screenshot

![スクリーンショット 2020-03-05 18 02 57](https://user-images.githubusercontent.com/13947046/75965204-d3264100-5f0b-11ea-8863-49b764c7b212.png)

## 期待する見せ方・挙動 / Expected behavior
* 確認中です

## 起こっている問題の再現手段 / Steps to reproduce
1. テスト環境にて再現 https://dev-covid19-tokyo.netlify.com/

## 動作環境・ブラウザ / Environment
*

**Comment by kaizumaki** [comment]
調査します！

**Comment by kaizumaki** [comment]
typo修正が影響してました。
