### ISSUE TITLE
サイト名の変更

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#462]
サイトタイトルの変更のお願いです。
影響カ所が複数あるかと思いますが、ご対応お願いいたします。。

（変更前）
東京都 新型コロナウイルス対策サイト

（変更後）
東京都 新型コロナウイルス感染症対策サイト

長くなりますが、対策本部 などと表現を合わせることになりました。
https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html

**Comment by kaizumaki** [comment]
着手します！
