### ISSUE TITLE
サイトトップのグラフ類をグルーピングしてタブ切替を実装

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4637]
**こちらのissueは6/2（火）の朝にリリース予定です。もし作業からしばらく離れる場合はDraft Pull Requestを出しておいてもらえると助かります。**

サイトトップのグラフ類が多く見づらくなってきたので、グルーピングしタブ切替で表示するようにします。
[デザインデータ（Figma）はこちら](https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=35813%3A0)

[実装イメージ]
<img width="1102" alt="スクリーンショット 2020-05-30 17 03 31" src="https://user-images.githubusercontent.com/14883063/83323607-fe19fa00-a29a-11ea-8bd6-7c69cfa54553.png">

[カードのグルーピングについてはこちら]
![タブ化（グラフカード順）](https://user-images.githubusercontent.com/14883063/83323645-2f92c580-a29b-11ea-86fc-398e64724718.png)

- 各タブはパーマリンクで表示できるようにしたいです。
	各URL（パス）は以下でお願いします。
	- モニタリング指標 `/` （サイトトップ）
	- その他 参考指標 `/reference`
- Vuetifyの[v-tabs](https://vuetifyjs.com/ja/components/tabs/)で実装し、スタイルを上書きするのが手っ取り早そうですが、もちろん独自実装でもかまいません。

なにか疑問点あれば遠慮なくこちらのissueにコメントしてください！

**Comment by shgtkshruch** [comment]
タブの色に関して質問です。デザインでは、
- 選択しているタブ: グレー
- 未選択のタブ: グリーン

になっていますが、ナビゲーションなどの UI に合わせて
- 選択しているタブ: グリーン
- 未選択のタブ: グレー

の方がわかりやすいかなと思ったのですが、いかがでしょうか？

![スクリーンショット 2020-05-31 8 04 31](https://user-images.githubusercontent.com/5207601/83340621-66a5bd00-a315-11ea-9195-404ff92e8df2.png)

**Comment by forestgtree** [comment]
@shgtkshruch 
ご指摘ありがとうございます🙇‍♂️
確かに、左メニューのエリアと右のコンテンツエリアの振る舞いが異なるのですが…

右側のコンテンツエリアでは、リンク先が存在するボタンの視認性を上げる為
グリーンのボーダー・文字色で表現しています。

このボタンは、ロールオーバー時にボタン領域全てグリーンとなり文字色を白となります。
今回は、そのルールに従ったボタンとなります。

**Comment by shgtkshruch** [comment]
コメントありがとうございます。

> 右側のコンテンツエリアでは、リンク先が存在するボタンの視認性を上げる為
> グリーンのボーダー・文字色で表現しています。

リンク先があるタブ（ボタン）の視認性を上げるためだったのですね。
現状のようにタブが 2つの場合、アクティブなタブとそのパネルの結びつきよりも、グリーンの未選択のタブがパッと目に入ったので気になってしまったんだと思います :pray:
（タブが 3つ以上になった場合はパターンが見えるので、それが識別の手助けになる気もしました）

リンクがあるタブとボタンでデザインを一致させるということで理解いたしました。

**Comment by mcdmaster** [comment]
ドラフト PR 出しています。
これからしばらく作業に着手できないため、好きに加工していただいて結構です(笑)

**Comment by kaizumaki** [comment]
@mcdmaster DPRありがとうございます！明日（6/1）中であれば間に合います。ぜひとも続きをお願いしたいです 🙇‍♀️ もし明日動けなさそうでしたらコメントください 🙏

**Comment by mcdmaster** [comment]
@kaizumaki DPR に TODO として挙げた項目につき、実装方法のアドバイスをいただけますでしょうか。特に、タブに URI を関連付ける方法がよくわかりません。
そこを乗り越えられれば、スピードアップができる可能性がかなり高まります。ご検討ください

**Comment by kaizumaki** [comment]
@mcdmaster おそらくですが、以下のようになると思います。
1. ルーティングを設定する。
`pages/index.vue` と `pages/reference.vue` を作成する。
1. `v-tab` のpropsに `to` と `nuxt` を指定してnuxt-linkにする。
```
<v-tab to="/" nuxt>
  <v-icon>
    mdi-chart-timeline-variant
  </v-icon>
  {{ $t('モニタリング指標') }}
</v-tab>
<v-tab to="/reference" nuxt>
  <v-icon>
    mdi-chart-timeline-variant
  </v-icon>
  {{ $t('その他 参考指標') }}
</v-tab>
```

私も動作を試してみたわけではないのですが、参考にしていただければと思います。

**Comment by mcdmaster** [comment]
おお！ありがとうございます！
参考にさせていただきますね

**Comment by kaizumaki** [comment]
@mcdmaster こちらのissueは引き取りました。ご協力いただきありがとうございます！

**Comment by mcdmaster** [comment]
@kaizumaki こちらこそありがとうございます！
そして週末に完遂できず申し訳ありませんでした。
もっと早くイシューに気づき、そして着手できていたらと悔やまれます
