### ISSUE TITLE
Safari で表示する際に TypeError

### ISSUE THREAD

**Issue by nyagihime** [tokyo-metropolitan-gov/covid19#4653]
## 起こっている問題 / The Problem
- Safariでアクセスすると、「TypeError: undefined is not an object (evaluating 'this.payload.dataView.$el')」が表示される

## スクリーンショット / Screenshot

こちらは、ロードが完了してからデベロッパーツールを開いた状態でのコンソールです

- デベロッパーツールをひらいたままリロードすると何故かこのエラーは出ません。
- また、デベロッパーツールを開いたままリロードするとロードが極端に遅くなります（関連してるかわからないため別 issue にします→#4654）
- デベロッパーツール開いてる状態ではエラーが出なくなるというよりは、そこまで到達していない可能性も考えられます

![image](https://user-images.githubusercontent.com/807519/83369569-bd83c300-a3f7-11ea-89ad-f04865cea3f2.png)

## 期待する見せ方・挙動 / Expected Behavior
- コンソールに表示されている TypeError の解消

## 起こっている問題の再現手段 / Steps to Reproduce
1. Safariで当該サイトにアクセスする
2. サイトが表示されたらデベロッパーツールを開くと表題のエラーが出ている
3. デベロッパーツールを開いたままリロードすると何故かエラーが出ない（上記スクリーンショットの項も参照してください）

## 動作環境・ブラウザ / Environment
- macOS / Safari

**Comment by goki90210** [comment]
#4646 と同じかもしれませんね。

1. デベロッパーツールを開くとリサイズされる
2. #4646 と同じ状態になりTypeError

という構図かと…。
