### ISSUE TITLE
Safariでデベロッパーツールを開いていると、読み込みが極端に遅くなる

### ISSUE THREAD

**Issue by nyagihime** [tokyo-metropolitan-gov/covid19#4654]
## 起こっている問題 / The Problem
- Safariでデベロッパーツールを開いたままサイトをリロードするとサイトが表示されるまでに 30 秒以上待たされる

デベロッパーツール開いてるときだけ発生してるっぽいので、一般ユーザーが利用する上ではさほど影響はないかもしれませんが、なんかのはずみで通常時にも起こるようになるとまずいので、原因は特定しておきたいです

## スクリーンショット / Screenshot

<img width="285" alt="Screen Shot 2020-06-01 at 11 22 38" src="https://user-images.githubusercontent.com/807519/83370387-3edc5500-a3fa-11ea-9d83-82b67a08d793.png">

上段：Safari（1分以上かかってます）
下段：Mobile Safari（このときは35秒でした）

## 期待する見せ方・挙動 / Expected Behavior
- デベロッパーツール使用時でも通常の速度で読み込める

## 起こっている問題の再現手段 / Steps to Reproduce
1. Safari / Mobile Safari で本サイトにアクセス
2. デベロッパーツールを開いた状態でサイトをリロードする

## 動作環境・ブラウザ / Environment
- macOS / Safari
- iOS / Mobile Safari

**Comment by goki90210** [comment]
@nyagihime さん

この問題はまだ改善されていませんか？
IEではNuxtJSなどのバージョンアップなどでややマシになったように見えます。

**Comment by kaizumaki** [comment]
@goki90210 フォローありがとうございます！
SafariでWebインスペクタを開いてリロードしてみましたが、改善しているようですね。こちらのissueはクローズしたいと思います。
