### ISSUE TITLE
Safariでローディングアニメーションがおかしい

### ISSUE THREAD

**Issue by nyagihime** [tokyo-metropolitan-gov/covid19#4655]
## 起こっている問題 / The Problem
- Safariで開いた際に、ローディング中の東京都ロゴのしたのアニメーションが変な動きをする

## スクリーンショット / Screenshot

![Untitled](https://user-images.githubusercontent.com/807519/83370868-8fa07d80-a3fb-11ea-8db9-2093c2f5c375.gif)

動画キャプチャ→Gif 変換したのですが、私が変換ツールを使いこなせておらずアニメーション速度とかがちょっと変ですが、実際には速度は正常っぽくて、
起こってる問題としては**バーの動きだけがおかしい**状態です。

これ以外にも、左1本と残り全部とか、色んなパターンがありますが、本来のような波打つ動きにはなりませんでした

## 期待する見せ方・挙動 / Expected Behavior
- 他のブラウザ同様のアニメーションとなる

## 起こっている問題の再現手段 / Steps to Reproduce
1. SafariまたはMobile Safari で本サイトにアクセスする

## 動作環境・ブラウザ / Environment
- macOS / iOS
- Safari / Mobile Safari

**Comment by youkidearitai** [comment]
vue-spinnerのサンプルをmacOSのSafariで度々ロードしても同じ現象を確認できました。
http://greyby.github.io/vue-spinner/

**Comment by kaizumaki** [comment]
@youkidearitai フォローありがとうございます！ということは、vue-spinnerのそもそもの挙動である可能性が高いかもしれませんね。

**Comment by mcdmaster** [comment]
すいません、こちら `vue-spinner` 側に打診しています。もう少々お待ちいただくことは可能でしょうか？

**Comment by tokyo-citizen** [comment]
めでたくupstreamでマージされて、[v1.0.4がリリース](https://github.com/greyby/vue-spinner/releases/tag/v1.0.4)されましたね。

**Comment by goki90210** [comment]
#5041 のPR（このIssueも含めます）でvue-spinner 1.0.4を取り込みます。
手元にSafariの動作環境がないのでどなたか確認をお願いします…。
