### ISSUE TITLE
東京アラート・緩和ステップの実装

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4678]
**こちらのissueは6/4（木）にリリースします。**

モニタリング指標に基づいて、「施設別休止要請の緩和ステップ」と「東京アラート」を表示することになりました。

[**デザイン（Figma）はこちらです**](https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=36012%3A3332)

実装イメージ
<img width="1434" alt="東京アラート・緩和ステップ_実装イメージ" src="https://user-images.githubusercontent.com/14883063/83522069-15ffb100-a51b-11ea-93ca-ef37160e9528.png">

**データは `data/tokyo_alert.json` になります。**

**A**： `alert` が `true` のときにこのカードを表示します。`false` のときは非表示です。
**B**：日本語ページ・やさしい日本語ページで `description['@ja']` を表示させます。その他の言語のページでは `description['@en']` を表示させます。
**C**：外部リンクです。現在「最新のお知らせ」カードの中に配置してあるものと同様のものです。なお「最新のお知らせ」カードからは削除します。
**D**：外部リンクです。現在「最新のお知らせ」カードの中に配置してあるものと同様のものです。なお「最新のお知らせ」カードからは削除します。
**E**：`step` の値にともなって状態が変わります。cssで作るパンくずリストの要領でコーディングするといいと思います（ただしリンクではありません）。
**F**：`changed` のdatetimeの値と `step` の値を組み合わせて文章にします。i18n化するのにマークアップに気をつけてください。ちなみにこのモックのとおりのテキストにならなくてOKです。日時とステップがわかれば大丈夫です。

- 色は適宜 `assets/variables.scss` から利用してください。
- なにか疑問点あれば遠慮なくこのissueにコメントしてください！

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by y-chan** [comment]
ステップの部分が実装できるか少し微妙ですが、やります。

**Comment by kaizumaki** [comment]
@y-chan ありがとうございます！なにかあれば遠慮なくコメントしてくださいね。
