### ISSUE TITLE
本番サイトでバーチャートが表示されず、エラーが発生している

### ISSUE THREAD

**Issue by youkidearitai** [tokyo-metropolitan-gov/covid19#4679]
## 起こっている問題 / The Problem
- 本番サイトでの新規患者に関する報告件数の推移 が、Firefoxで動作していない
    - （おそらく関連しているものだと思いますが）Chrome / Safariでは、テーブルの日付が一番上に「1月6日」のデータが発生している
- Firefoxで出ているエラーは以下3つ

```
RangeError: "date value is not finite in DateTimeFormat.format()"
    NuxtJS 11
6bf988fd6cb05674ca14.js:2:11800
TypeError: "this.$refs.barChart is undefined"
    NuxtJS 19
6bf988fd6cb05674ca14.js:2:11800
RangeError: "date value is not finite in DateTimeFormat.format()"
    NuxtJS 19
6bf988fd6cb05674ca14.js:2:11800
```

## スクリーンショット / Screenshot

こちらはFirefoxでみたものです。
![Screenshot_2020-06-02 東京都 新型コロナウイルス感染症 対策サイト](https://user-images.githubusercontent.com/305368/83521636-780be680-a51a-11ea-81a3-066df029abdd.png)

![covid-19-site-bug-on-firefox-2020-06-02](https://user-images.githubusercontent.com/305368/83522052-0f713980-a51b-11ea-86e7-42b48faf8faa.png)

こちらはChromeで「テーブルを表示」をみたものです。1月6日になっています。
![covid-19-site-bug-on-chrome-2020-06-02](https://user-images.githubusercontent.com/305368/83526866-03d54100-a522-11ea-878b-85b556a4b16e.png)

こちらはSafariで「テーブルを表示」をみたものです。1月6日になっています。
<img width="1436" alt="covid-19-site-bug-on-safari-2020-06-02" src="https://user-images.githubusercontent.com/305368/83527172-63335100-a522-11ea-995e-2a8414abe0dd.png">

## 期待する見せ方・挙動 / Expected Behavior
- 3つのエラーがFirefoxのコンソール上から消える
- 新規患者に関する報告件数の推移がFirefox上で表示される
- 6月2日のデータ、34件がテーブル上で表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 本番サイト https://stopcovid19.metro.tokyo.lg.jp/ を閲覧する

## 動作環境・ブラウザ / Environment
- Firefox (macOS / Windows / Android)
- Chrome (macOS / Windows)
- Safari (macOS)

ただし、本番サイトのみ発生する問題で、 https://dev-covid19-tokyo.netlify.app/ と、私のローカルの開発環境では再現しませんでした。

**Comment by kaizumaki** [comment]
@youkidearitai ご指摘ありがとうございます！こちら、今朝のリリース作業中に起こった不具合のようです。調査いたしますので、しばらくお待ちいただければと思います。

**Comment by youkidearitai** [comment]
今日の14時に確認したときは正常に動作していたのですが、先程19時ごろに確認したところまたこの現象になりました。

**Comment by kaizumaki** [comment]
@youkidearitai フォローありがとうございます。たしかに今朝から夕方にかけて現象が再現されていなかったので、こちらでも検証できずにいました。先ほど原因がわかりましたので、hotfixをあてようとしているところです。対応が終わりましたらまたコメントします。

**Comment by kaizumaki** [comment]
@youkidearitai さきほどhotfixをあてました。正常な表示になったと思いますので、ご確認いただけるとうれしいです。

**Comment by youkidearitai** [comment]
@kaizumaki ありがとうございます！WindowsとMac、Androidのそれぞれのブラウザで正常な表示になったことを確認しました。クローズします。
