### ISSUE TITLE
6月1日の次が1月6日になっている

### ISSUE THREAD

**Issue by takusan23** [tokyo-metropolitan-gov/covid19#4680]
## 起こっている問題 / The Problem
- **新規患者に関する報告件数**の推移の棒グラフのツールチップが6月1日の次が1月6日になっている

間違いでしたらすいません

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/32033405/83529973-12bdf280-a526-11ea-86f6-c3f37c20a4a3.png)

## 期待する見せ方・挙動 / Expected Behavior
- 6月2日になるべき

## 起こっている問題の再現手段 / Steps to Reproduce
- Google Chrome 83.0.4103.61 / Windows 10

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@takusan23 ご指摘ありがとうございます！ #4679 と関連していますが、こちら今朝のリリース作業中に起こった不具合のようです。調査いたしますので、しばらくお待ちいただければと思います。

**Comment by kaizumaki** [comment]
@takusan23 こちら、さきほどhotfixをあて正常な表示に戻りました。ご指摘いただき感謝です。こちらのissueはクローズさせていただきますね。
