### ISSUE TITLE
タブUIの改善

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4682]
## 改善詳細 / Details of Improvement
- スマホで見たときに、タブのラベルテキストが切れることがあり、これを切れないようにしてほしいという要望がありました。
![コメント 2020-06-03 095448](https://user-images.githubusercontent.com/14883063/83583988-cd7ade80-a580-11ea-8af0-dd8b6c4ff239.jpg)

- タブがモバイルサイズのときにスクロールするということがわかりにくいようです。
- タブは２つしかないので、スクロールさせずに両方並べてしまってはどうかと思いました。
- hover時のスタイルも見直したいです。
- IE11での表示も整えたいです。

## 期待する見せ方・挙動 / Expected behavior
- タブをスクロールさせずに並べる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
私のほうで対応しますが、「こうしたほうがよいのでは？」というご意見・アイディアをお寄せいただけるとうれしいです！

**Comment by asuchi0819** [comment]
> スマホで見たときに、タブのラベルテキストが切れることがあり、これを切れないようにしてほしいという要望がありました。

個人的には、テキストが切れて表示されていると、
「あっ、まだ左右に項目があるんだ！」
となって良いと思います。

もし、「消える部分が不自然」と言うのが今回の提案の理由な場合は、端に影をつける等すると自然な感じになると思いました。

**Comment by kaizumaki** [comment]
> 個人的には、テキストが切れて表示されていると、
> 「あっ、まだ左右に項目があるんだ！」
> となって良いと思います。

私も同意見です。

影をつけるのはいいアイディアですね。
まあ、折衷案として、今回は２つのタブしかないので並べちゃおう、という考えにいたったわけなんですが...

**Comment by kaizumaki** [comment]
それと、タブそれぞれのページをルーティングさせて `nuxt-link` で切り替えているんですが、タブをクリックしたらページ遷移して画面が一番上にもってかれてしまう挙動をどうにかしたいなとも思います。タブをクリックしたら、その場所でとどまっているほうが自然かなと。
これについて実装のアイディアがあったらお知らせいただけるとうれしいです。

**Comment by nyagihime** [comment]
タブ切り替えは、動的コンポーネント（あるいはもっとシンプルに v-if とか v-show でもよいのかも？）と、URLクエリなどでつくるのがよいのかなと思ったのですがいかがでしょう？
たとえば、ですが
通常時（モニタリング指標）：/
参考指標：/?tab=reference

みたいな感じにして、クエリ文字列からとってコンポーネントを入れ替えれば、参考指標側から表示を開始させることも可能かな、と思ったのですが

**Comment by kaizumaki** [comment]
そういえば「参考指標」を表示しているときって、サイドナビゲーションからもcurrentが外れるんですよね。サイドナビゲーションでは「都内の最新感染動向」がcurrentになっていてほしいところ。
クエリだとそのあたりも解決するんでしょうか...？

**Comment by nyagihime** [comment]
@kaizumaki 
 `.nuxt-link-exact-active` で current のスタイルをあてていて、これが、ルーターのパスと完全に一致してないとつかないみたいため、クエリがついてもダメみたいです

かといって、 `.nuxt-link-active` にスタイルを当ててしまうと、他のページを表示中も常に「都内の最新感染動向」が current になってしまうため、ちょっと仕込みが必要になりそうな気がします…

**Comment by kaizumaki** [comment]
@nyagihime そうなんですね。サイドナビゲーションの対応は別issueに分けたほうがよさそうですね。
