### ISSUE TITLE
タブのリンク先が必ず日本語になる

### ISSUE THREAD

**Issue by y-chan** [tokyo-metropolitan-gov/covid19#4685]
## 起こっている問題 / The Problem
- タブのリンク先が、他言語を選択中であっても日本語になります。

## スクリーンショット / Screenshot

![tokyo_tabs](https://user-images.githubusercontent.com/34832037/83595324-a5997400-a59c-11ea-97f5-db29fd9adf7c.gif)

## 期待する見せ方・挙動 / Expected Behavior
- リンク先が多言語対応される
  - ここの`""`内を`localePath()`で囲ってあげるだけで対応できるはずです。
https://github.com/tokyo-metropolitan-gov/covid19/blob/8368c843f7b70d4d682b8f20c40888e6df9626fe/components/CardsTabs.vue#L6
    

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/en/ などの日本語以外の言語でサイトにアクセス
2. タブを切り替える

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@y-chan いま #4682 で `CardsTabs.vue` をさわっているので、こちらも試してみていいですか？

**Comment by y-chan** [comment]
大丈夫です！
