### ISSUE TITLE
日本語以外でトップページのタブをクリックすると日本語ページに戻ってしまう

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#4692]
## 起こっている問題 / The Problem
- 英語などの言語で「モニタリング指標」や「その他 参考指標」のタブをクリックすると、日本語版のページが表示されてしまう

## スクリーンショット / Screenshot
画面推移を伴うため省略

## 期待する見せ方・挙動 / Expected Behavior
- もともと閲覧していた言語のままタブが切り替わる

## 起こっている問題の再現手段 / Steps to Reproduce
英語版を例に説明
1. https://stopcovid19.metro.tokyo.lg.jp/en にアクセスする
2. 「その他 参考指標」をクリックする
3. https://stopcovid19.metro.tokyo.lg.jp/en/reference/ ではなく https://stopcovid19.metro.tokyo.lg.jp/reference にアクセスしてしまう

## 動作環境・ブラウザ / Environment
- 依存なし

## 予想される変更すべきコード（動作未検証）
https://github.com/tokyo-metropolitan-gov/covid19/blob/aa38cda3ba68491f8c34f59b33fac200236faa34/components/CardsTabs.vue#L21-L26

下記のように `this.localePath` を使用すれば良いはずです。

```diff
-        { label: this.$t('モニタリング指標'), path: '/' },
-        { label: this.$t('その他 参考指標'), path: '/reference' }
+        { label: this.$t('モニタリング指標'), path: this.localePath('/') },
+        {
+          label: this.$t('その他 参考指標'),
+          path: this.localePath('/reference')
+        }
```

（※上記コード自体は動作検証しておらず、またeslintによるチェックもする必要あり）

**Comment by kaizumaki** [comment]
@MaySoMusician #4685 と同様ですね。 #4684 で修正PR出しています。

**Comment by MaySoMusician** [comment]
おっと、確認不足でした。 #4685に任せます
Duplicate of #4685
