### ISSUE TITLE
getComplementedDate で本日の日付が去年のものとしてreturnされている

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#4693]
## 起こっている問題 / The Problem
- `getComplementedDate` 関数は `MM/DD` 形式のように年情報が無い日付文字列からDateオブジェクトを生成するために、年情報を補完するためのもの。
- 大まかには「 `MM/DD` 部分が今日より後だったら去年、それ以外の場合は今年とする」という処理内容
- 詳細は https://github.com/tokyo-metropolitan-gov/covid19/pull/4232#discussion_r426284615 を参照
    - 上記コメントで
        > 最新のデータは翌日以降に取得するので、現在と同じ日付のデータも去年のものと考えられる。

        とあるが #4680 から推測するに当日中に取得されるデータも存在していた

## 期待する見せ方・挙動 / Expected Behavior
- 上述の処理内容において「 `MM/DD` が本日（＝実行したときの日付）と同じだったら今年とする」になるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
現在発生してる問題は無し。

## 動作環境・ブラウザ / Environment
- 依存なし

**Comment by goki90210** [comment]
ここの
https://github.com/tokyo-metropolitan-gov/covid19/blob/6d630dcf7870ba712e9d62497fa572ed7c53f611/utils/formatDate.ts#L53-L67

特に
https://github.com/tokyo-metropolitan-gov/covid19/blob/6d630dcf7870ba712e9d62497fa572ed7c53f611/utils/formatDate.ts#L65-L67
が対象ですね。

<pre>
 if (currentMonth < month || (currentMonth == month && currentDate < date)) { 
   targetYear -= 1 
 } 
</pre>
でしょうか。

**Comment by MaySoMusician** [comment]
@goki90210 そのような形で問題無いと思います。
（ `currentMonth == month` は `currentMonth === month` の方が良いかも）

**Comment by goki90210** [comment]
@MaySoMusician ===にします。
