### ISSUE TITLE
緩和ステップの日付に曜日を表示できるように設定

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#4696]
## 改善詳細 / Details of Improvement
- #4678 で提案されている「緩和ステップ」要素Fにて表示する「M月D日（曜日） 午前(午後)H時」フォーマットを `nuxt-i18n.config.ts` の `dateTimeFormatsCommon` に定義する

```ts
dateTimeRelaxationSteps: {
  hour12: true,
  weekday:'short',
  month: 'short',
  day: 'numeric',
  hour:'numeric'
}
```

### 変換サンプル
![image](https://user-images.githubusercontent.com/34566290/83703486-bf919000-a64a-11ea-8eaa-1832dd48b484.png)

- 今のところ「緩和ステップ」のみで使用するので `dateTimeRelaxationSteps` と命名していますがもし他に案があればご提案ください
- ブラウザによって若干変換結果が異なる可能性があります。報告があり次第都度パラメーターは調整したいと思います。

**Comment by MaySoMusician** [comment]
こちら対応します

**Comment by goki90210** [comment]
午前・午後表記は0時12時問題があるので個人的には好きではないのですが、都の要望であるなら致し方なしです。

このあたりのお話です。
http://jjy.nict.go.jp/QandA/FAQ/12am-or-0pm-J.html

**Comment by MaySoMusician** [comment]
IEでちょっと時刻表示の仕様が異なるようなので、時刻部分は旧来の `$t()` の方を使おうと思います

**Comment by kaizumaki** [comment]
> IEでちょっと時刻表示の仕様が異なるようなので、時刻部分は旧来の `$t()` 式のやり方を使おうと思います

「午前／午後」の表記は都から要望がありましたので、その方向で12時間表記ができるように実装を進めていただけるとうれしいです。
