### ISSUE TITLE
auto i18n generatorに components/RelaxationStepCard.vue 内の翻訳キーを認識させる

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#4729]
## 起こっている問題 / The Problem
- 以下のコードで使用されている翻訳キーのうち「`午後 {hour12h}時`」と「`午前 {hour12h}時`」が認識されない https://github.com/tokyo-metropolitan-gov/covid19/blob/00b44a814767e7e8c58c1f585ec2e00a22f13884/components/RelaxationStepCard.vue#L64-L85

## 期待する見せ方・挙動 / Expected Behavior
- 「`午後 {hour12h}時`」と「`午前 {hour12h}時`」が認識されるように auto i18n generator を変更する
- もしくは、 auto i18n generator が認識できるように `components/RelaxationStepCard.vue` 内のコードを書きなおす

**Comment by y-chan** [comment]
対応します
