### ISSUE TITLE
map-test.htmlのhtmlタグにlang属性がない→mapbox-glの削除

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4764]
## 改善詳細 / Details of Improvement
https://github.com/tokyo-metropolitan-gov/covid19/blob/51734f04b87eeb85a59ad1a940e9b9aa5da4d9ac/static/map-test.html#L1-L3

lang属性がありません。Nuxt.jsだと`<html {{ HTML_ATTRS }}>`でlang属性が入ることになっている認識です。
map-test.html とファイル名もテスト用に見えるのですが、不使用でしょうか？

## 期待する見せ方・挙動 / Expected behavior
- （使用しているなら）lang属性が入るようにする。
- （不使用なら）削除する。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@goki90210 ご指摘ありがとうございます！ `static/map-test.html` は現在不使用ですね。本来であれば、関連するライブラリ（mapbox-gl）まわりも削除してしまいたいところなのですが...

**Comment by goki90210** [comment]
`yarn remove mapbox-gl-vue`
`yarn remove mapbox-gl`
`static/map-test.html`の削除
の3点セットでPRします。（`package.json`, `yarn.lock`も差分が出ます。）
