### ISSUE TITLE
tableタグに関するアクセシビリティの向上

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4765]
## 改善詳細 / Details of Improvement
https://github.com/tokyo-metropolitan-gov/covid19/blob/51734f04b87eeb85a59ad1a940e9b9aa5da4d9ac/components/MonitoringStatusOverviewTable.vue#L1-L10

https://github.com/tokyo-metropolitan-gov/covid19/blob/51734f04b87eeb85a59ad1a940e9b9aa5da4d9ac/pages/contacts.vue#L1-L7

でtableタグを使用していますが、aria-describedby属性がありません。
後者は
https://github.com/tokyo-metropolitan-gov/covid19/blob/51734f04b87eeb85a59ad1a940e9b9aa5da4d9ac/pages/contacts.vue#L3
にidを振って、
https://github.com/tokyo-metropolitan-gov/covid19/blob/51734f04b87eeb85a59ad1a940e9b9aa5da4d9ac/pages/contacts.vue#L7
でaria-describedby属性を設定すれば解決します。

前者はどうすればいいのかわかりません。
（role="presentation"で回避するのは違うような気がします。）

## 期待する見せ方・挙動 / Expected behavior
- tableタグを表として使用する際はaria-describedby属性を使用する。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
意味合い的には、`aria-labelledby` との併用で、以下のようになるのではないでしょうか。

[MonitoringStatusOverviewTable.vue]
```
<template>
  <table
    :class="$style.table"
    aria-labelledby="tableHeader"
    aria-describedby="tableBody"
  >
    <thead id="tableHeader">
    ...
    </thead>
    <tbody id="tableBody">
    ...
    </tbody>
    ...

```
[contacts.vue]
```
<template>
  <div
    class="Contacts"
    aria-labelledby="pageHeader"
    aria-describedby="contactsCardTable"
  >
    <page-header id="pageHeader" class="mb-3">
      {{ $t('お問い合わせ先一覧') }}
    </page-header>
    <div class="Contacts-Card">
      <table
        id="contactsCardTable"
        class="Contacts-Card-Table"
        v-bind="tableAttrs"
      >
      ...

```

**Comment by goki90210** [comment]
そうですね。失礼しました。

**Comment by mcdmaster** [comment]
PR つくりました
