### ISSUE TITLE
 v-overlayの表示切替をvalue属性にする

### ISSUE THREAD

**Issue by Nekoya3** [tokyo-metropolitan-gov/covid19#4770]
## 改善詳細 / Details of Improvement
-  v-overlay の表示切替を現在v-ifで書かれているがvalue属性にする。

## 期待する見せ方・挙動 / Expected behavior
- v-overlay の表示切替を :value にする。
- オーバーレイの挙動は変えない。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
PR つくりました
