### ISSUE TITLE
東京都新型コロナウイルス感染症対策本部報に関する誤植

### ISSUE THREAD

**Issue by kotobuki** [tokyo-metropolitan-gov/covid19#479]
## 起こっている問題 / Occurred problem
「東京都新型コロナウイルス感染症対策本部報」へリンクされているテキストが「東京都新型コロナイルス感染症対策本部報」になっているようです。

**Comment by halsk** [comment]
ご報告ありがとうございます！
どなたか良ければー

**Comment by MaySoMusician** [comment]
#450 で対応済みの可能性アリ

**Comment by halsk** [comment]
devサーバでは修正されていました！
でも、ご指摘ありがとうございました！
こちらはクローズしますね。
