### ISSUE TITLE
削除予告のあるグラフ・チャートを削除する

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4790]
削除予告をしてあるグラフおよびチャートを削除します。
（削除日時は6月15日（月）17時ごろです）

削除対象は以下の３つです。
- 検査実施状況
- 検査実施人数（健康安全研究センターによる実施分）
- 新型コロナ受診相談窓口相談件数

![検査実施状況](https://user-images.githubusercontent.com/14883063/84475226-22c49780-acc7-11ea-99c2-40830aebe10c.jpg)
![検査実施人数](https://user-images.githubusercontent.com/14883063/84475236-26581e80-acc7-11ea-982b-fb666643d6e5.jpg)
![相談件数](https://user-images.githubusercontent.com/14883063/84475240-2821e200-acc7-11ea-8c8d-070b18b96443.jpg)

`components/CardsReference.vue` （indexページ）と、`pages/cards/_card.vue` （パーマリンク設定）と、`nuxt.config.ts` （OGP生成の設定）から該当するカードの記述を削除していただければと思います。

**Comment by shgtkshruch** [comment]
`pages/cards/` に削除対象のグラフのカードコンポーネントがありますが、こちらは削除しなくても大丈夫でしょうか？

- [TestedCasesDetailsCard.vue](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/cards/TestedCasesDetailsCard.vue)
- [InspectionPersonsNumberCard.vue](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/cards/InspectionPersonsNumberCard.vue)
- [ConsultationDeskReportsNumberCard.vue](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/cards/ConsultationDeskReportsNumberCard.vue)

**Comment by kaizumaki** [comment]
@shgtkshruch `components/cards` ですね？そうですね、こちらのコンポーネントも削除でよいかと思います。

**Comment by shgtkshruch** [comment]
> components/cards ですね？そうですね、こちらのコンポーネントも削除でよいかと思います。

path を書い間違えました...、 `components/cards/` でした 🙏 
それでは、こちらも削除する形で対応します。

**Comment by kaizumaki** [comment]
@shgtkshruch よろしくお願いします！
