### ISSUE TITLE
ツールチップの位置をフレキシブルにできないですか？

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4807]
## 改善詳細 / Details of Improvement
- #4793 はcloseされてしまったのですが、ツールチップを左側に表示させると見切れる場合には右側に出すということはできないのでしょうか？（バグではないので改善提案です）

## スクリーンショット / Screenshot

#4793 と同じのため省略します。

## 期待する見せ方・挙動 / Expected behavior
- 例えば、標準では左側とするが左側で表示できる<del>よう生き</del><ins>領域</ins>が取れない場合は右側に表示する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by y-chan** [comment]
フレキシブルには出来ないと思いますが、dev-ja-hiraにおいて、カスタムツールチップにて見切れないように上書きする仕組みがあります。そちらを採用すれば良いかなぁと思います(ちゃんとは見ていないので、チェリーピックなんかで対応できる保証は無いです)

**Comment by shgtkshruch** [comment]
> ツールチップを左側に表示させると見切れる場合には右側に出すということはできないのでしょうか？

dev-ja-hira でカスタムツールチップを実装しましたが、多分できると思います。

あちらはふりがな対応のコードも混ざっているのでそのまま使うのは難しいと思いますが、基本的な仕組みのところは流用できると思います。

**Comment by goki90210** [comment]
モニタリング指標(2)新規陽性者における接触歴等不明率、モニタリング指標(4)重症患者数、モニタリング指標(5)入院患者数については
下側や右側に出る場合があるんですよね。
![image](https://user-images.githubusercontent.com/30145857/85966839-e188f300-b9fb-11ea-83ac-0422a32cacf8.png)

![image](https://user-images.githubusercontent.com/30145857/85966702-88b95a80-b9fb-11ea-8c4c-1e91dc30f16f.png)

![image](https://user-images.githubusercontent.com/30145857/85966646-61fb2400-b9fb-11ea-8300-f85802ae3440.png)

新規患者に関する報告件数の推移、モニタリング指標(1)新規陽性者数、モニタリング指標(3)週単位の陽性者増加比、モニタリング指標(6)PCR検査の陽性率、モニタリング指標(7)受診相談窓口における相談件数
が常に左側になるようです。

**Comment by goki90210** [comment]
dev-ja-hira-rubyはChart.jsのoptions.tooltips.customでカスタマイズをしているのは確認しました。

表示位置のカスタマイズであれば
Chart.Tooltip.positionersに新たなモードを追加するか、
Chart.Tooltip.positioners.averageをオーバーライドするかでもできそうですね。

**Comment by goki90210** [comment]
dev-ja-hira-rubyはTooltipModelを変更しているのはわかりましたが、
xAlignやyAlign（ツールチップの表示位置）の調整はしていないんですよね？

Chart.js内のfunction
determineAlignment(tooltip, size)
でどこに表示するか決めていて、canvasの中央か、より左側なら右、canvasの中央より右側なら左に表示するよう定義されています。
（例外はtooltipのオプションで指定された場合はそのオプション通り、左右に表示させた場合にcanvasからはみ出す場合は上または下になります。）

https://stackoverflow.com/questions/43211497/change-tooltip-positioning-in-doughnut-chart-using-chart-js
あたりも参考にはなりそうです。

**Comment by goki90210** [comment]
https://github.com/chartjs/Chart.js/blob/master/src/plugins/plugin.tooltip.js#L331-L334
<pre>
/**
 * Helper to get the alignment of a tooltip given the size
 */
function determineAlignment(chart, options, size) {
</pre>
の

https://github.com/chartjs/Chart.js/blob/master/src/plugins/plugin.tooltip.js#L347-L348
<pre>
	const midX = (chartArea.left + chartArea.right) / 2;
	const midY = (chartArea.top + chartArea.bottom) / 2;
</pre>

この値をスクロールするdiv（tooltip._chart.canvas.closest('.scrollable')）のscrollLeft, clientWidth, scrollTop, clientHeightで算出するだけでできそうですが、TypeScript的にどうすべきか…。

**Comment by goki90210** [comment]
…とここまではわかったのですが、customでどう実装すべきかわからなくなってしまいました…。

**Comment by kaizumaki** [comment]
こちらは解消されているように思いますので、一旦クローズとさせてください 🙇
