### ISSUE TITLE
google検索結果にtitleとdescriptionが正しく反映されていない

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4808]
## 起こっている問題 / The Problem
- 東京都から以下の報告がありました。
> Googleで「対策サイト」で検索した場合
> ![image002](https://user-images.githubusercontent.com/14883063/84722105-3fa9e500-afbd-11ea-9abb-af91e1ebd0f1.png)
> titleが「東京都」となってしまっており、description にはJavaScript無効の際のメッセージが出ています。
> また、「対策サイト 東京都」で検索した場合には
> titleは「東京都」、descriptionは「Last update: 2020/06/14: This website was opened by the Tokyo Metropolitan Government to provide the latest information of COVID-19.」が表示されます。
> ちなみにBingではどちらのワード検索でも
> title:東京都 新型コロナウイルス感染症 対策サイト
> description:2020/06/12 更新: 当サイトは新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するために、東京都が開設したものです。
> と、metaタグに記述したとおり表示されるようです。

- サイトトップにグラフ類のタブ切替を実装した際に、タブにパーマリンクを持たせたのですが、[「その他参考指標」タブに直接アクセス](https://stopcovid19.metro.tokyo.lg.jp/?tab=reference)できなかったために（ #4706 ）`client-only`  を使ったのが副作用をもたらしているのではないかと思っています。

## スクリーンショット / Screenshot
現在のgoogle検索結果
<img width="850" alt="スクリーンショット 2020-06-16 10 29 14" src="https://user-images.githubusercontent.com/14883063/84722717-f65a9500-afbe-11ea-96c8-bb6c56d6aeaf.png">
<img width="850" alt="スクリーンショット 2020-06-16 10 31 16" src="https://user-images.githubusercontent.com/14883063/84722733-007c9380-afbf-11ea-8058-552a37d7b39c.png">

## 期待する見せ方・挙動 / Expected Behavior
- google検索結果にtitleとdescriptionの内容が反映されるようになる

## 起こっている問題の再現手段 / Steps to Reproduce
1. googleで検索（検索ワードは「対策サイト」「東京都 コロナ サイト」）

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nyagihime** [comment]
こちら対応します

**Comment by kaizumaki** [comment]
こちらの件、 #4810 のPRにより解決したようなのでクローズします。
![google検索](https://user-images.githubusercontent.com/14883063/84863369-c9d27600-b0af-11ea-9ff9-2905e0cebc8f.jpg)
