### ISSUE TITLE
/?tab=referenceに直アクセスできない

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4822]
## 起こっている問題 / The Problem
- サイトトップの「その他 参考指標」のタブにあてているパーマリンク（ https://stopcovid19.metro.tokyo.lg.jp/?tab=reference ）に直接アクセスしようとすると、ローディングで止まったままになり、コンソールにエラーがはかれます。

![コンソール](https://user-images.githubusercontent.com/14883063/84863777-7ca2d400-b0b0-11ea-8d1e-44e7682292bd.jpg)

- 実はタブを実装した際にこの現象は把握していて、解消するためにタブのコンテンツに対して `client-only` を施した経緯があります（ #4706 ）。
- すると今度はSEOまわりが正しく反映しない現象が起こり（ #4808 ）、 `client-only` を外す修正をしました。

## 期待する見せ方・挙動 / Expected Behavior
- できればタブにパーマリンクを持たせたいですが、方法がなければパーマリンクなしで構いません。
- とにかくエラーがでないようにしたいです。

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/?tab=reference に直接アクセス。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
https://dev-covid19-tokyo.netlify.app/?tab=reference
https://stg-covid19-tokyo.netlify.app/?tab=reference
は同じように出ますが、

yarn dev/yarn dev-no-axeだと再現しないんですよね…。

**Comment by mcdmaster** [comment]
しまった！ @goki90210 さんのコメントを見る前に PR を起こしてしまいました…うーん。
でも、念のため試していただけるとありがたいです

**Comment by MasaGon** [comment]
恐らくですが、generate しないと再現しないのではないかと思います。

**Comment by kaizumaki** [comment]
> https://dev-covid19-tokyo.netlify.app/?tab=reference
> https://stg-covid19-tokyo.netlify.app/?tab=reference
> は同じように出ますが、
> 
> yarn dev/yarn dev-no-axeだと再現しないんですよね…。

そうなんです。ローカル環境で再現しないので、具体的な解決法が思い浮かばずにいたのです。

**Comment by MasaGon** [comment]
yarn generate:deploy で /dist に静的ファイルが生成されると思います。

**Comment by mcdmaster** [comment]
`yarn generate:deploy` からの `yarn start` したみたのですけど、私の側ではエラーにならないですね。
うーん…ちなみに Win10 x64 環境です

**Comment by goki90210** [comment]
@mcdmaster  さん
私も同じですね。Win10 x64 環境ですが、諸事情によりDocker環境が整備できません。
Visual Studio Codeで起動してみたりもしたいのですが上の事情で無理なんです…。

**Comment by MasaGon** [comment]
`yarn start` だとSSRが動いてしまう気がします。/dist をドキュメントルートとした静的ウェブサーバーを立ち上げられると良いのですが、もしお手元の環境にphpがインストールされていれば、このあたりがお手軽ではと思うのですが、いかがでしょう？
https://www.php.net/manual/ja/features.commandline.webserver.php

もし他に良いやり方をご存じの方がいらっしゃれば、教えてください。

**Comment by shgtkshruch** [comment]
ちゃんと検証していませんが、現象からするとハイドレーションに関するエラーかもしれません。
https://ssr.vuejs.org/ja/guide/hydration.html

仮にエラーの原因がタブだとすると、クエリパラメータを元に `v-if` で出し分けている部分が少し気になります。

<https://github.com/tokyo-metropolitan-gov/covid19/blob/501588e9a7f9161f5e0ec5b01618c73808fc4996/pages/index.vue#L5-L6>

Production でエラーになってローカル環境で動作する理由はこちらかと思います。

> 開発モードでは、Vue はクラインアントサイドで生成された仮想 DOM が、サーバで描画された DOM の構成と一致しているかアサートを行います。もしこれが一致しない場合、 Vue はハイドレーションを取りやめ、サーバーが生成した既存の DOM を破棄して一から DOM の描画を行います。開発モードでは、Vue はクラインアントサイドで生成された仮想 DOM が、サーバで描画された DOM の構成と一致しているかアサートを行います。もしこれが一致しない場合、 Vue はハイドレーションを取りやめ、サーバーが生成した既存の DOM を破棄して一から DOM の描画を行います。プロダクションモードでは、パフォーマンスの最大化のため、このアサーションは無効に設定されています。
ref: https://ssr.vuejs.org/ja/guide/hydration.html

動作確認については、Node.js のプロジェクトなので `npx` で [http-server](https://www.npmjs.com/package/http-server) を使うのもいいと思います。
```
yarn generate:deploy
npx http-server ./dist
```

パッと思いつくもので、以下のような修正方法があると思います。（動作確認・検証はしていません :pray:）
1. クエリパラメータではなく、URL のパスでわける https://github.com/tokyo-metropolitan-gov/covid19/pull/4665
1. タブに URL の区別をつけずに Vuetify のデフォルト実装に寄せる
1. `v-if` -> `v-show` に変更する

1 は初期実装と同じようになると思いますが、https://github.com/tokyo-metropolitan-gov/covid19/issues/4682 で懸念されていたスクロール位置の保持が懸念点です。

2 は実装はシンプルになると思いますが、パーマリンクを外す形になります。

3 は修正は手軽ですが、`v-show` は DOM の生成をしてしまうのでレンダリングがいくらか重くなると思います。

**Comment by kaizumaki** [comment]
みなさん、検証ありがとうございます！
@shgtkshruch さん、解決策のご提示ありがとうございます 🙇‍♀️ 

東京都に確認したところ、
> 2 は実装はシンプルになると思いますが、パーマリンクを外す形になります。

これで構わないということでした。
私も、他の懸念点（UIやパフォーマンス）が発生するよりは、あっさりパーマリンクをあきらめるのは手かなと思っています。

**Comment by mcdmaster** [comment]
皆さん

既にお気づきかもしれませんけれども、PR をアップデートしました。
ご確認をいただけるとありがたいです。詳細は、PR の中を覗いてみていただけますでしょうか

**Comment by goki90210** [comment]
#4824 の修正内容を適用して、

`npx http-server ./dist`

で確認しましたが、
<pre>
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:41274)
    at m (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:54197)
    at v (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:53828)
    at _ (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:54283)
    at N (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:57669)
    at N (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:57604)
    at N (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:57604)
    at N (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:57604)
    at f.__patch__ (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:58081)
    at f.t._update (http://localhost:8080/_nuxt/b5ffb77f2b5e9c4cca1f.js:2:35020)
</pre>
は変わりませんね。

Windows 10, Chromeです。

**Comment by mcdmaster** [comment]
@shgtkshruch さん、ありがとうございます！
