### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」の上のボタンが大きい

### ISSUE THREAD

**Issue by Tree-frog-code** [tokyo-metropolitan-gov/covid19#4839]
## 改善詳細 / Details of Improvement
(新型コロナウイルス感染症が心配なときに)[https://stopcovid19.metro.tokyo.lg.jp/flow/]
のページの上のボタンが大きい。
## スクリーンショット / Screenshot

![2020-06-19-211349_1024x768_scrot](https://user-images.githubusercontent.com/57087325/85132947-c50aef00-b274-11ea-9b96-e9a05620103b.png)

## 期待する見せ方・挙動 / Expected behavior
上のボタンが3分の2くらいのサイズになればもっと見やすくなると思います。

## 動作環境・ブラウザ / Environment
Linux Raspbian
Chrome Chromium

**Comment by Tree-frog-code** [comment]
追記で、画面の解像度の関係もあると思います。

**Comment by youkidearitai** [comment]
Windows 10, Google Chromeで300%程度に拡大したところ、同じような事になりました。


![chrome-300-percent-expansion-on-tokyo-gov](https://user-images.githubusercontent.com/305368/85207584-a08e4000-b364-11ea-94b6-e29ca3096e5f.png)

**Comment by kaizumaki** [comment]
ご指摘ありがとうございます！なるほどですね。確かにメインのコンテンツが見えづらくなっているかもしれません。
試しに、修正案をご提案いただけますでしょうか？スクリーンショットでもPRでもOKです。デザイナーと検討したいと思います。

**Comment by youkidearitai** [comment]
個人的には、特定の幅以下のときにmarginやpaddingなどのスペースを小さくする、というのが一つ考えられるかなと思いますが、スマートフォンも影響します。
![chrome-300-percent-expansion-remove-spaces-responsize](https://user-images.githubusercontent.com/305368/85221362-4df96600-b3ee-11ea-91fc-9b2e2c3720af.png)

**Comment by kaizumaki** [comment]
> 個人的には、特定の幅以下のときにmarginやpaddingなどのスペースを小さくする、というのが一つ考えられるかなと思いますが、スマートフォンも影響します。

なるほどですね。ためしにPRを出してもらって、実装プレビューを見ながら検討したいと思うのですがいかがでしょう？

**Comment by youkidearitai** [comment]
@kaizumaki https://github.com/tokyo-metropolitan-gov/covid19/pull/4884 作成しました！
