### ISSUE TITLE
ESLintでエラーが発生する

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4864]
## 起こっている問題 / The Problem
- ver 1.5.431のソースに対してyarn lintを実行すると
<pre>
nuxt.config.ts
  4:7  error  'webpack' is assigned a value but never used  @typescript-eslint/no-unused-vars
  4:7  error  'webpack' is assigned a value but never used  no-unused-vars

pages\parent.vue
  29:16  error  Replace `⏎··············'子供たちの学びを支援する様々なウェブサ イトを紹介しています。'⏎············` with `'子供たちの学びを支援する様々なウェ ブサイトを紹介しています。'`  prettier/prettier
</pre>
のエラーが発生する。

## 期待する見せ方・挙動 / Expected Behavior
- nuxt.config.ts についてはこの行を削除するとビルドが通らないので、暫定的に当該行に`// eslint-disable-line`をつけます。
- pages\parent.vue についてはyarn lint:fix実行後のソースに改めます。

## 起こっている問題の再現手段 / Steps to Reproduce
1. ver 1.5.431のソースに対してyarn lintを実行する

## 動作環境・ブラウザ / Environment
- Windows 10
- Node.js 12.18.1

**Comment by kaizumaki** [comment]
@goki90210 ご対応ありがとうございます！ところで、なぜPull Request作成時のCIでreviewdogが通ってたんでしょうね...？

**Comment by goki90210** [comment]
@kaizumaki  私もそこがわからないんですよね…。ルールが違うのか、バージョンが違うのか…。

**Comment by goki90210** [comment]
少し調べたところmapbox-glの削除で
<pre>
    plugins: [
      new webpack.ProvidePlugin({
        mapboxgl: 'mapbox-gl'
      })
    ],
</pre>
を削除したためwebpackを使用している箇所がなくなったためESLintでエラーとなりました。
<pre>
const webpack = require('webpack')  // eslint-disable-line
</pre>
を
<pre>
require('webpack') 
</pre>
とすることでESLintのエラーも出力されず、yarn buildも成功します。
