### ISSUE TITLE
制御構造には中括弧を使用する

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4869]
## 改善詳細 / Details of Improvement
- if-else文など制御構造のある箇所では1行であっても中括弧を使用すべきです。

https://github.com/tokyo-metropolitan-gov/covid19/blob/a273589dee5ec82a0fd0ac16689408abe8a6bf8e/components/cards/MonitoringConfirmedCasesNumberCard.vue#L76-L80

https://github.com/tokyo-metropolitan-gov/covid19/blob/a273589dee5ec82a0fd0ac16689408abe8a6bf8e/components/cards/PositiveRateCard.vue#L119-L123

https://github.com/tokyo-metropolitan-gov/covid19/blob/a273589dee5ec82a0fd0ac16689408abe8a6bf8e/components/cards/UntrackedRateCard.vue#L88-L92

https://github.com/tokyo-metropolitan-gov/covid19/blob/a273589dee5ec82a0fd0ac16689408abe8a6bf8e/utils/monitoringStatusValueFormatters.ts#L10-L14
（注）10行目の`(digit: number = 0)`については`(digit = 0)`で十分です（リテラルを使用している時点でnumberであることが自明であるため）

SonarQubeのルールの説明
https://rules.sonarsource.com/typescript/RSPEC-121
（意訳：技術的には誤りではないが、中括弧の省略は誤解を招く可能性があり、今後修正があった場合に新たな障害を起こすおそれがある。）

https://rules.sonarsource.com/typescript/RSPEC-3257
（意訳：不必要に冗長な宣言と初期化を行うと、コードが読みにくくなるため簡略化すべきです。具体的には、プリミティブ（数値、文字列、ブールなど）の型は、初期化された値またはデフォルトの値から簡単に推測できるので、変数およびパラメーターの宣言から省略しましょう。）

## スクリーンショット / Screenshot

ありません。

## 期待する見せ方・挙動 / Expected behavior
- 改善詳細の通り

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
対応します。

**Comment by kaizumaki** [comment]
@goki90210 いつもありがとうございます！コード品質の担保について、たいへん助かっています。
ところで素朴な疑問なのですが、こういった改善はコードを書いたときにフォーマッターでなんとかならないのでしょうか？

**Comment by goki90210** [comment]
整形のレベルであればprettier, eslint, stylelintなどで担保できますが、
今回挙げたものは難しいかもしれません。

**Comment by kaizumaki** [comment]
ESLintのドキュメントに [中括弧の規則に関する記述](https://eslint.org/docs/rules/curly) を見つけたのですが、このあたりでも実現できないでしょうか。
