### ISSUE TITLE
最新のおしらせ更新

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#487]
下記2件でお願いします

日付：3月5日
マスク及び消毒液の寄贈しました！
https://www.2020games.metro.tokyo.lg.jp/news/2020/0305_3108.html

日付：3月5日
（第70報）事業継続緊急対策（テレワーク）助成金募集を開始します！
https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/1007458.html

**Comment by halsk** [comment]
やります
