### ISSUE TITLE
グラフのスクロールバーがドラッグしづらい

### ISSUE THREAD

**Issue by t-tecsoc** [tokyo-metropolitan-gov/covid19#4872]
## 改善詳細 / Details of Improvement
「新規患者に関する報告件数の推移」などのグラフのスクロールバーが細く、ドラッグしづらい。
また、色も薄いため見づらい

## スクリーンショット / Screenshot

<img width="2489" alt="スクリーンショット" src="https://user-images.githubusercontent.com/25559838/85512931-6a3b1400-b635-11ea-86f1-9e2407e4a433.png">

## 期待する見せ方・挙動 / Expected behavior
スクロールバーのheightを4px→10pxぐらいにするとだいぶ違うかなという印象です。
色が薄い問題については、（スクロールバーの部分を）全体的に不透明度を上げれば見やすくなるかと思います

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by goki90210** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/blob/83a2fd91e64b3769dc9781d2fd57c5be2d1c4944/components/ScrollableChart.vue#L109-L120

ここを修正すればできそうですね。
Firefoxは上記の設定は効かないので
<pre>
scrollbar-color
scrollbar-width
</pre>
を使う必要がありますね。

現在の設定ではFirefoxではこうなってます。
![image](https://user-images.githubusercontent.com/30145857/85565290-f830f200-b669-11ea-8cba-414878588ce2.png)

**Comment by kaizumaki** [comment]
ご提案ありがとうございます！スクロールバーについてはブラウザ依存かと思っていました。スクロールがわかりやすくなるようにアピアランスを変えられるなら、ぜひお願いしたいです。

**Comment by goki90210** [comment]
scrollbar-color, scrollbar-widthについては指定しないことにしました。
- この設定自体がMacOSではデフォルトでは無効になるらしい。
- 指定することでFirefoxではスクロールバーの上下左右ボタンのスタイルがなくなってしまう（矢印がなくなる）。
のが理由です。

Chromium/Webkit系のみのカスタマイズです。

こんな感じでいかがでしょう？
Chrome
![image](https://user-images.githubusercontent.com/30145857/85648096-f3f0ed00-b6da-11ea-85c6-d1641cf0f33c.png)

Edge (Chromium)
![image](https://user-images.githubusercontent.com/30145857/85648133-0b2fda80-b6db-11ea-90e1-dcab3c90028e.png)

他のブラウザは後ほど…

**Comment by goki90210** [comment]
Opera
![image](https://user-images.githubusercontent.com/30145857/85648886-b42b0500-b6dc-11ea-9cee-3f0e781c6953.png)

Safariは手元に環境がないので出せません。

一旦PR出しますので、デザイン等さらに修正を必要だと思われる場合はお願いします。

**Comment by kaizumaki** [comment]
@goki90210 かなりいい感じですね！
しかしながら、iPhone SafariでPRのpreviewを拝見したところ、アピアランスは変わっていないようでした。これについては引き続きの課題かもしれません。

**Comment by goki90210** [comment]
@kaizumaki 気づいたのですが、縦スクロールはスタイルを指定していないのでブラウザの初期状態のままになっています。ということは、スクロールバーの設定を外してしまえばよいのではないかと考えます。

スクロールバーに関するスタイルを削除したバージョンも確認してみます。

**Comment by goki90210** [comment]
スクロールバーの設定を削除したらこうなります。

Chrome
![image](https://user-images.githubusercontent.com/30145857/85679051-03d0f700-b704-11ea-9ca2-7f4e066e9642.png)

Edge (Chromium)
![image](https://user-images.githubusercontent.com/30145857/85679305-41358480-b704-11ea-9b22-c470e524d7f0.png)

Opera
![image](https://user-images.githubusercontent.com/30145857/85679879-c5880780-b704-11ea-8e2d-c49a8ccb2567.png)

Firefox
![image](https://user-images.githubusercontent.com/30145857/85679668-95406900-b704-11ea-8c85-655f88e1eb08.png)

私はこのほうが良いと思います。
