### ISSUE TITLE
英訳の問題点を修正

### ISSUE THREAD

**Issue by fritz-c** [tokyo-metropolitan-gov/covid19#4873]
## 改善詳細 / Details of Improvement
- 英訳に「Other Indexs」などの入力ミスやちょっと文法が変なところがあります。それを修正する提案です。（PRは既にできています）
## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/4413963/85536977-87301100-b64e-11ea-8adc-87698a54277d.png)

## 期待する見せ方・挙動 / Expected behavior
- より正しい英語になること

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by hello-iamsisi** [comment]
@fritz-c こんにちは！多言語翻訳レビューチームの＠Sisiです。翻訳は正しいことももちろんなのですが、文字長などもあり「納得する範囲」で表記しているものもあります。PRを決定する前に”Transifex”というツールでご提案いただいておるのですが、こちらからfritz-cさんをご招待して,ほかの部分でも修正すべきところを教えていただきたいのですがいかがでしょうか？

**Comment by fritz-c** [comment]
わかりました。ご招待をよろしくお願いします。

**Comment by hello-iamsisi** [comment]
@fritz-c 
ありがとうございます。#4874 も拝見しました！修正できることは、やってしまいますね。
次回から、直接修正していただけるように、Transifexにご招待いたしますね。

**Comment by fritz-c** [comment]
@hello-iamsisi ありがとうございます！

**Comment by kaizumaki** [comment]
@fritz-c Transifexの方にご参加いただけるとのこと、感謝です！ #4874 のPRはクローズしますね。

**Comment by kaizumaki** [comment]
#4874 をクローズしましたので、こちらのissueもクローズします。
