### ISSUE TITLE
NuxtJS等のバージョンアップ

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#4896]
## 改善詳細 / Details of Improvement
- #4888で他のバージョンを上げるとビルドエラーが起こると書きましたが、調べたところ
https://github.com/tokyo-metropolitan-gov/covid19/blob/4215ed7732f65df26735588737171ab1cc16329d/nuxt.config.ts#L144
の`_`を`_: any`にするだけでした。（NuxtJS, @nuxt/typesのバージョンを上げると暗黙的なanyが駄目になってanyで型定義しなければならない。）

ということで、6月19日にNuxtJSが2.13.0になり（6月24日に2.13.1、<del>近々</del><ins>6月27日</ins>に2.13.2にな<del>るようです</del><ins>りました</ins>。）
今使っているバージョン2.11.0からマイナーバージョンが2つ上がっているのでバージョンアップを考えてもよいかと思います。
（2.13.xのバージョンアップのペース早すぎますか？）
https://github.com/nuxt/nuxt.js/releases

そのほかでは、
@nuxt/types: 0.6.4 → 2.13.<del>1</del><ins>2</ins>
（一見メジャーバージョンアップに見えますが、nuxtのバージョン表記に合わせただけのようです。）

cross-env: 5.2.0 → 7.0.2
メジャーバージョンが2つ上がっていますが、内容はnode.js 8以前のサポート停止と依存関係の見直しなので問題なし。
https://github.com/kentcdodds/cross-env/releases

nodemon: 1.18.9 → 2.0.4
https://github.com/remy/nodemon/releases
chokidar@3へのアップグレードのためなので問題なし

nuxt-purgecss: 0.2.1 → 1.0.0
https://github.com/Developmint/nuxt-purgecss/blob/master/CHANGELOG.md
（確認中ですが悪いことはしてなさそうに見えます。）

babel-jest: 24.1.0 → 25.5.1
jest: 24.1.0 → 25.5.4
vue-jestを4.0.0-beta3にするとjest: ^25.x < 26となるため
https://github.com/vuejs/vue-jest/releases

prettierがメジャーアップグレード（1.19.1→2.0.5）していますが、
適用するとESLintで大量にエラーが出る（jsonで末尾に必ず","を書くように修正されるため）
保留です。

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
私も、かねてからアップデートしたいと思っていたコンポーネントがいくつかあります。

- `core-js3` へのアップグレード
- `vue-server-renderer` から `@vue/server-renderer` への変更
- `source-map-resolve 0.6.0` へのアップグレードと、`"resolutions"` セクション（`package.json`）への切り出し
- その他、`@mdi/font`, `nuxt-i18n` などの最新化

最後の項目を除くと、いずれもコンパイルの都度出てくる deprecated とか no longer maintained とかといったワーニングが気になっていたものです。
後でイシュー＆ PR 起こしてみますね

**Comment by goki90210** [comment]
@mcdmaster 
 > * その他、@mdi/font, nuxt-i18n などの最新化
こちらについては今回のPRでバージョンアップしています。

nuxt-i18n: 6.8.1 → 6.12.2
@mdi/font: 5.0.45 → 5.3.45
express: 4.16.4 → 4.17.1
vue-scrollto: 2.17.1 → 2.18.1
などです。
ESLint以外はワーニングが出ないようにすべてバージョンを変えています。
ESLintについては6.8.0のままでも7.3.1にしてもワーニングが出るのであえて上げています。

上3つについては本体の修正も必要になるという認識ですがあってますか？

**Comment by kaizumaki** [comment]
@goki90210 @mcdmaster 詳細と検証、ありがとうございます！提出いただいたPR #4898 のあともライブラリのアップデートおよび調整は続くということでよかったでしょうか？

**Comment by mcdmaster** [comment]
@goki90210 
情報ありがとうございます。

`core-js3`, `@vue.server-renderer`, `source-map-resolve 0.6.0` は、ご認識の通りですね。
とはいえ、為念「本体」の主旨については確認させてください。
たとえば nuxt のようなコア中のコアな部分のアップグレードが不可避とか、あるいはソースに手を入れる必要があるとか、そういったことを指しておいででしょうか？

**Comment by goki90210** [comment]
@mcdmaster 

> ソースに手を入れる必要がある

こちらの意図です。
これまでの私の作業では、package.json, yarn.lock以外では
* nuxt.config.ts
* .eslintrc.js
くらいしか触っていません。

@kaizumaki
今後NuxtJSなどがバージョンアップしたら追随するための作業が必要になるという認識ですが、
これについては別にPRを起こします。このIssueで対応するのは今日時点のバージョンまでとします。

**Comment by mcdmaster** [comment]
@goki90210 

理解できました。ありがとうございます。挙げていただいたコンフィグ系のファイル
- `package.json`
- `yarn.lock`
- `nuxt.config.ts`
- `.eslintrc.js`

から見える範囲に限定する、なおかつそれによって上記以外を触るべき影響が出ないことが確認できるなら、「歯止め」となる効果が期待できます
