### ISSUE TITLE
FAQが404

### ISSUE THREAD

**Issue by monsieur-677** [tokyo-metropolitan-gov/covid19#4899]
## 起こっている問題 / The Problem
- FAQのリンク先が404

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/65798125/85915968-0c056f80-b887-11ea-8870-638d26101253.png)

## 期待する見せ方・挙動 / Expected Behavior
- FAQリンクを飛ぶとFAQのサイトに飛ぶ

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
新型コロナウイルス感染症FAQ（よくある質問）　令和2年3月19日現在
https://www.metro.tokyo.lg.jp/tosei/tosei/news/covid-19_faq.html
は読めます。

PDF版 FAQ(よくある質問）はこちら（福祉保健局　PDF）
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.files/corona_faq.pdf
が404ですね。

**Comment by monsieur-677** [comment]
@goki90210 ありがとうございます。このスクショの部分のリンクの修正です。

**Comment by kaizumaki** [comment]
こちらのissueの件は、東京都の対策サイトに関連していますか？
