### ISSUE TITLE
chart.jsのツールチップが見切れる

### ISSUE THREAD

**Issue by ryo-a** [tokyo-metropolitan-gov/covid19#4901]
## 起こっている問題 / The Problem
- chart.jsで描画されているグラフにおいて、左端などの要素にカーソルを合わせたとき表示されるツールチップが見切れています
- 日付などを確認するのが困難です
- グラフ自体が左右にスクロール可能なので、スクロールすれば見えるようにはなります。もしこれで正しい仕様（or chart.js側の問題）ということであれば、案内が若干不親切かなと思います。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/26864545/85943847-a809a680-b96d-11ea-86d9-bbdb589cec9a.png)

## 期待する見せ方・挙動 / Expected Behavior
- どの要素をポイントしてもツールチップが読めるようになる

## 起こっている問題の再現手段 / Steps to Reproduce
1. 「新規患者に関する報告件数の推移」などで左端の要素にマウスカーソルを合わせる

## 動作環境・ブラウザ / Environment
- Windows 10
- Chrome 83.0.4103.116

**Comment by goki90210** [comment]
@ryo-a
#4807 と重複しています。
（解決策もここで議論されています。）

よろしくお願いします。

**Comment by goki90210** [comment]
Duplicate of #4807

**Comment by ryo-a** [comment]
@goki90210 すみません、検索漏れでした（`chart.js`のみで検索しておりました。）closeいたします。
