### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」のコンテンツを読みやすくする

### ISSUE THREAD

**Issue by tetsugi** [tokyo-metropolitan-gov/covid19#4902]
新型コロナウイルス感染症対策にご尽力されているすべての方々に心より感謝いたします。

## 改善詳細 / Details of Improvement
関連Issue: #4839

「新型コロナウイルス感染症が心配なときに」ページのデザインに対する改善要望です。
- 上部のfixedのアンカーリンクの専有面積が大きいため、コンテンツが見づらい状態になってしまっています。
特にスマートフォンの横画面ではほとんどコンテンツが隠れてしまいます。
カード自体は見やすいので、アンカーリンクのfixedを外して上部に固定しないようにすると、読みやすくなるのではないかと感じました。
- スマートフォンの縦画面で閲覧したときにフォントサイズが10pxになってしまい、少し読みづらく感じます。
画面幅に依らず、常に16pxくらいあると読みやすくなるのではないかと思いました。

## スクリーンショット / Screenshot
**Mac Chrome 画面幅375px**
<img width="377" alt="縦" src="https://user-images.githubusercontent.com/38849987/85945544-9201e300-b979-11ea-9c23-f51452dff4ba.png">

**iPhone 8 横画面**
![横](https://user-images.githubusercontent.com/38849987/85945555-a5ad4980-b979-11ea-8962-cdd78a1b4c3f.png)

## 期待する見せ方・挙動 / Expected behavior

上部のアンカーリンクを固定しないようにすると次のようなUIになります。

![PC改善](https://user-images.githubusercontent.com/38849987/85945657-3ab04280-b97a-11ea-8053-d8fd5d0230e1.png)

画面幅375pxでは次のようになります。
また、一部の文字のサイズを16pxに変更した例も載せておきます。

<img width="379" alt="スマホ改善" src="https://user-images.githubusercontent.com/38849987/85945611-f91f9780-b979-11ea-8f0d-b5c89b396316.png"><img width="378" alt="スマホ文字改善" src="https://user-images.githubusercontent.com/38849987/85945625-0e94c180-b97a-11ea-9aee-2862f16923ae.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / iOS
- Chrome

**Comment by kaizumaki** [comment]
@tetsugi ご提案ありがとうございます！flowのページについては、全面改修 #3315 の際にレスポンシブを優先し、特にモバイルサイズ時の指示をしなかったこともあって、現在のようになっています。
フォローいただいている #4839 の改善PR #4884 をマージしましたので、こちらのissueについても検討をすすめたほうがいいかもしれないですね。

**Comment by asuchi0819** [comment]
以前、こちらのissueを見たとき気になってました。
改めて、見てみるとボタンが画面の4割程度を占めていて見づらいのと、選択肢の句切れがわかりづらいような気がします。

個人的には、ページを分けたほうが見やすいのではないか？と思っております。
![03E13E43-7A63-4A30-9F89-7F1BCAEE6E9F](https://user-images.githubusercontent.com/45027336/87742480-cbfc3180-c821-11ea-85c8-550747ac0189.png)

**Comment by kaizumaki** [comment]
@asuchi0819 コメントありがとうございます！相談フローのページは、元々は[東京都のホームページに掲載されているフロー図](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html)を落とし込んだものなので、１ページに収める方向性は変えられないかなあという感じがしています。
むしろナビゲーションボタンのあり方を見直す、という方向ならできるかもしれません（デザイナーと東京都の確認は必要になりますが）。
アイディアありましたらコメントください！

**Comment by tokyo-citizen** [comment]
スクロールした場合にはSVGを表示しないという方向性はどうでしょうか？

**Comment by asuchi0819** [comment]
> スクロールした場合にはSVGを表示しないという方向性はどうでしょうか？
@tokyo-citizen 

個人的には、表示領域が大きくなるので良いと思います。
ただ、右下に「上に戻るボタン」は用意したほうが良いと思います。

あとは、それぞれの要素同士が近づきすぎているのでもう少し離すと別の要素であると認識がしやすくなるかと思います。

**Comment by tokyo-citizen** [comment]
@asuchi0819 さん

交通整理ですが、このIssueの方向性として、例えば以下はいかがでしょうか。
- スクロールした場合にはSVGを表示しない
- それぞれの要素同士が近づきすぎているのでもう少し離す

右下に「上に戻るボタン」については「じゃぁ、他のページは？」とややこしくなるので別Issueにするとかもアリかなと。

**Comment by asuchi0819** [comment]
良いと思われます！ありがとうございます！
（ただ、issueを立てたのは私ではないので。。。

**Comment by kaizumaki** [comment]
@tokyo-citizen さん、 @asuchi0819 さん、ご検討ありがとうございます！
より具体的な状態を見ながら検討したいので、PRを出していただくか実装イメージを貼っていただくかすると進めやすいかなと思います（採用するかどうかは要検討になってしまいますが...）。
さらに適宜別issueを立てていただいてもOKです。いかがでしょうか？
もちろんどなたでもディスカッションを続けていただくのは大歓迎です。

**Comment by asuchi0819** [comment]
了解しました。

> それぞれの要素同士が近づきすぎているのでもう少し離す

こちら、やってみます。

**Comment by munierujp** [comment]
別のアプローチとして、ボタンの追従自体は有効なままで、スクロール時にアイコンを非表示にすることで縦幅を小さくするというのはどうでしょうか。

|before|after|
|---|---|
|![](https://user-images.githubusercontent.com/20086673/87874936-c01e9400-ca08-11ea-9ab8-f676c55d634a.png)|![](https://user-images.githubusercontent.com/20086673/87874938-c3b21b00-ca08-11ea-992f-6695b709d5c8.png)|

このようにスクロール時に追従する要素が通常時よりも簡素になるようなUIを採用しているウェブサイトはいくつかあり、GitHubのプロフィールページもその1つです。

![画面収録 2020-07-19 21 47 01 mov](https://user-images.githubusercontent.com/20086673/87875092-b5b0ca00-ca09-11ea-9f24-f80d7ee4e5a4.gif)

**Comment by kaizumaki** [comment]
@munierujp 
> 別のアプローチとして、ボタンの追従自体は有効なままで、スクロール時にアイコンを非表示にすることで縦幅を小さくするというのはどうでしょうか。

これはいいアイディアですね！実装を試すことはできますでしょうか？
いま #5053 のPRを提出してもらっていますが、相談フローのページは当サイトの中でも大事なページですので、じっくり検討したく思います。
@asuchi0819 さん、こちらの実装も試してみることは可能でしょうか...？

**Comment by munierujp** [comment]
@kaizumaki 

>これはいいアイディアですね！実装を試すことはできますでしょうか？

はい、こちらで実装してみます。
