### ISSUE TITLE
「相談の手順を見る」ボタンの余白が狭い

### ISSUE THREAD

**Issue by yuxxxx** [tokyo-metropolitan-gov/covid19#4903]
## 起こっている問題 / The Problem
- 上の「ロードマップについて」ボタンに比べて、「相談の手順を見る」ボタンの余白が狭くなっているように見えます。
- 直上のリンクが1行に表示され、ボタンがその下に表示されるとき、リンクとの余白が十分に取れていないように見えます(Android版Chromeのスクリーンショット参照)。

## スクリーンショット / Screenshot

iOS 13.5.1 Safari
![E3F96AFC-CCF5-4C18-80EB-05D5EFFD6725](https://user-images.githubusercontent.com/1780191/85958410-5d6d4600-b9d0-11ea-9042-3f147aed7f52.png)

Android 10 Chrome 83.0.4103.106
![8F69AAB5-42F0-4D9E-AE1A-229311B33C41](https://user-images.githubusercontent.com/1780191/85958735-a920ef00-b9d2-11ea-8fe3-ec72e6e193f3.png)

## 期待する見せ方・挙動 / Expected Behavior
- 余白を「ロードマップについて」ボタンと同じにします。

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページを表示します。

## 動作環境・ブラウザ / Environment
- iOS 13.5.1 / Safari
- Android 10 / Chrome 83.0.4103.106

**Comment by kaizumaki** [comment]
@yuxxxx ご指摘ありがとうございます！単純にフォントサイズが違うのだと思います。「ロードマップについて」は、その前 #2977 に作成された「東京都緊急事態措置について」のコンポーネントと体裁を揃える形にしてあります（そちらのコンポーネント `components/LinkToInformationAboutEmergencyMeasure.vue` は、いつでも復活できるように残してあります）。
そういう経緯もありますので、「相談の手順を見る」を合わせるかどうかは検討したほうがいいかもですね。

**Comment by goki90210** [comment]
「ロードマップ」については
class="TextLink_10s4k" → padding: 4px 8px

「相談の手順を見る」について
class="StaticInfo-Button" > span → padding: 4px 8px
で余白は同じです。（実際に適用されている余白も確認済みです。）

kaizumakiさんの仰るとおりフォントサイズ（1.6remと1.4rem）の差ですね。

**Comment by kaizumaki** [comment]
８月末のサイトリニューアルで対象の箇所も改修されましたので、こちらのissueはクローズにします。
