### ISSUE TITLE
「検査陽性者の状況」カードで「退院」が重複している

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#491]
## 起こっている問題 / Occurred problem
* SSIA

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/34566290/75984945-b3ecdb00-5f2e-11ea-948e-ead55a43db26.png)

## 期待する見せ方・挙動 / Expected behavior
* #309 より、「入院中」内の「退院」が「重症」となるべき

## 起こっている問題の再現手段 / Steps to reproduce
1. https://dev-covid19-tokyo.netlify.com/ へアクセス

## 動作環境・ブラウザ / Environment
* Windows 10 Home 64 bit
* Chrome

**Comment by osoken** [comment]
ご報告ありがとうございます！こちら #309 とまとめて対応中です
