### ISSUE TITLE
Add accepted languages in how to contribute translation page

### ISSUE THREAD

**Issue by wiennat** [tokyo-metropolitan-gov/covid19#4935]
## 改善詳細 / Details of Improvement
The answer in https://github.com/tokyo-metropolitan-gov/covid19/issues/1696#issuecomment-650719771 should be explicitly written in [How to contribute translations
 page](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/TRANSLATION.md)

Instead of stating that new languages might not be accepted, it should specify that only Japanese, English, Simplified Chinese, Traditional Chinese, and Korean can be provided in the website due to reviewing capacity.
 
## スクリーンショット / Screenshot

<img width="1102" alt="Screen Shot 2020-07-04 at 16 47 52" src="https://user-images.githubusercontent.com/56550/86507800-25be2e00-be16-11ea-95dc-df9de4fcbb15.png">

## 期待する見せ方・挙動 / Expected behavior
- Following messages should be added 
```
Due to reviewing capacity, we allow only Japanese, English, Simplified Chinese, Traditional Chinese, and Korean can be provided in the website
```

## 動作環境・ブラウザ / Environment
-

**Comment by MaySoMusician** [comment]
@wiennat, thank you for your suggestion! I totally agree to add an explanation to the document.
Could you make changes to the document? If not, I'm willing to do that.
