### ISSUE TITLE
アプリをアンインストールしても通知が来る不具合

### ISSUE THREAD

**Issue by funwarioisii** [tokyo-metropolitan-gov/covid19#4937]
## 起こっている問題 / The Problem
アプリをアンインストールしましたがまだアプリの通知が来ます
具体的にはスマートフォンのBluetoothをオフにした時に通知が来ます

## スクリーンショット / Screenshot
![Screenshot_20200705-205038~3.png](https://user-images.githubusercontent.com/20943066/86532178-c558ea80-bf02-11ea-9175-1f906012f1e8.png)

通知をタップすると以下の画面になります
![Screenshot_20200705-205802.png](https://user-images.githubusercontent.com/20943066/86532122-54193780-bf02-11ea-847d-dc60827ceca4.png)

## 期待する見せ方・挙動 / Expected Behavior
通知機能もオフになってほしいです

## 起こっている問題の再現手段 / Steps to Reproduce
1. Bluetoothをオンにしておく
2. アプリをアンインストールする
3. Bluetoothをオフにする

この手順で通知が来ます

## 動作環境・ブラウザ / Environment
- Pixel 3 / Android 10

**Comment by MaySoMusician** [comment]
@funwarioisii こんにちは！
本issueは接触確認アプリに関するものでしょうか？

こちらは[東京都 新型コロナウイルス感染症対策サイト](https://stopcovid19.metro.tokyo.lg.jp/)の開発レポジトリとなります。

接触確認アプリの不具合・要望につきましては https://github.com/Covid-19Radar/Covid19Radar にて取り扱っているものと思われます。お手数おかけいたしますがご確認のほどよろしくお願い申し上げます。

**Comment by funwarioisii** [comment]
@MaySoMusician 
送り先間違えていました、申し訳ないです。
そちらにIssue立ててきます。案内ありがとうございます。
