### ISSUE TITLE
テーブル内のフォントサイズが小さい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4942]
## 起こっている問題 / The Problem
- グラフ下部の「テーブルを表示」内の表の文字サイズが小さすぎて読みにくいです。
**追記**：「陽性患者の属性」「陽性患者数（区市町村別）」のテーブルも同様。
- Vuetifyのデフォルトのスタイルが効いてしまっていると思われます。

## スクリーンショット / Screenshot

こちらはIE11で見た場合。Windows10 Chromeでもフォントサイズは小さくなってしまっている。
![コメント 2020-07-06 102735](https://user-images.githubusercontent.com/14883063/86547336-9cbd0900-bf73-11ea-94db-8a91c0bc2f47.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 12pxくらいにするといいかなと思います。
- padding, heightもデフォルトが効いてしまっているので、要検討です。

## 起こっている問題の再現手段 / Steps to Reproduce
1. グラフ下部の「テーブルを表示」をクリック

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
@kaizumaki さんの指摘通り


https://github.com/tokyo-metropolitan-gov/covid19/blob/745414d56da22042031e8ce0fd1020589066aaf4/components/DataTable.vue#L65-L78
の.cardTable.v-data-table thより

Vuetifyのnode_modules\vuetify\src\components\VDataTable\VSimpleTable.sass
.v-data-table > .v-data-table__wrapper > table > tbody > tr > th, .v-data-table > .v-data-table__wrapper > table > thead > tr > th の設定
```
          > th
            padding: 0 16px
            transition: height $secondary-transition

          > th
            user-select: none
            font-size: $data-table-regular-header-font-size
            height: $data-table-regular-header-height

            +ltr()
              text-align: left

            +rtl()
              text-align: right

          > td
            font-size: $data-table-regular-row-font-size
            height: $data-table-regular-row-height
```
が勝ってしまっていますね。

**Comment by kaizumaki** [comment]
@goki90210 フォローありがとうございます！てっきりグラフ下部のテーブルのみかと思っていたら、メインのテーブルも同じことが起こっていたのですね。

**Comment by kaizumaki** [comment]
> Sassなので
> $data-table-regular-header-font-sizeや$data-table-regular-row-heightの値を変えるというのも1つのアプローチかと思います。

それはアリですね。コンポーネント内でグローバルなcssを書くよりもいいかもしれません。

**Comment by kaizumaki** [comment]
私のほうで対応します。
