### ISSUE TITLE
[モニタリング項目]総括表[大幅改修]table組み

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4961]
現在、[東京都のホームページで試行中のモニタリング項目](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.html)を、従来のモニタリング指標に代わり当サイトに掲載することになりました。

**7/9（木）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

### 実装イメージ
**幅狭のモバイルサイズの時はtableが横スクロールできるようにしたいです。**
![モニタリング項目実装イメージ](https://user-images.githubusercontent.com/14883063/86773589-c28c0000-c090-11ea-8ba8-931330646291.png)

* データ： ` monitoring_items.json`
* 緑色： `#008830` （$green-1）
* 小数桁数（またはフォーマット）：
(1)新規陽性者数　１桁
(2)#7119（東京消防庁救急相談センター）における発熱等相談件数　１桁
(3)新規陽性者における接触歴等不明者（人数）　１桁
(3)新規陽性者における接触歴等不明者（増加比）　１桁
(4)PCR・抗原検査（陽性率）　１桁
(4)PCR・抗原検査（検査人数）　１桁
(5)救急医療の東京ルールの適用件数　１桁
(6)入院患者数　整数
(6)入院患者確保病床数　文字列
(7)重症患者数　整数
(7)重症患者確保病床数　文字列

※上記画像の元となったexcelファイルはこちらです。テキストの抽出にお使いください。
[モニタリング項目実装イメージ.xlsx](https://github.com/tokyo-metropolitan-gov/covid19/files/4884538/default.xlsx)
※注釈はダミーです。
※「感染状況・医療提供体制の分析について」の部分は外部リンクボタンです。リンク先urlは後ほどお知らせします。
※小数桁数は `utils/monitoringStatusValueFormatters.ts` にある関数を使って実装してください。
※データの値は現時点ではダミーです。

### 注釈
後ほどお知らせします。

### 配置について
ここでは位置を変えなくてOKです。リリース直前に運営側で並べ替えます。

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by MaySoMusician** [comment]
こちら、取り掛かりたいと思います

**Comment by kaizumaki** [comment]
@MaySoMusician ありがとうございます！よろしくお願いします！

**Comment by MaySoMusician** [comment]
@kaizumaki 旧モニタリング指標の総括表は残しておいた方がよいでしょうか？ 完全に置き換えてしまっても良いでしょうか？

**Comment by kaizumaki** [comment]
@MaySoMusician 完全に置き換えてしまって大丈夫です！

**Comment by kaizumaki** [comment]
注釈は以下となります。配置は表の下部で、スタイルは「旧モニタリング指標(6)」と同様です（先頭に「・」がついたリスト形式）。
```
（注）
・ 「＃7119」・・・急病やけがの際に、緊急受診の必要性や診察可能な医療機関をアドバイスする電話相談窓口
・ 救急医療の東京ルールの適用件数・・・救急隊による5医療機関への受入要請又は選定開始から20分以上経過しても搬送先が決定しない事案の件数
・ (6)確保病床・・・レベル1→1,000床、レベル2→3,000床、レベル3→4,000床
・ (7)確保病床・・・レベル1→100床、レベル2→300床、レベル3→700床
・ (1)～(5)は7日間移動平均で算出
・ (2)(4)(5)は報告日の前日時点の数値
・ 速報値として公表するものであり、後日修正する場合がある
・ (2)(5)は土曜日、日曜日、祝日は更新しない。(4)は日曜日、祝日は更新しない
```

**Comment by MaySoMusician** [comment]
@kaizumaki 注釈ですが「・・・」の部分は書籍等では3点リーダーを2個連続で用いるのが正書法とされていたはずです

例
```
・ 「＃7119」 …… 急病やけがの際に、緊急受診の必要性や診察可能な医療機関をアドバイスする電話相談窓口
```
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.html だと3点リーダー1個ですが、これを2個連続に変えたものになるかと思います。
ただ、用語解説の場合はコロン「：」の方がわかりやすいような気もします。

**Comment by kaizumaki** [comment]
@MaySoMusician 都の指示は東京都のホームページから引っ張ってきたのだと思いますが、対策サイトではこの部分を変えても構わないと思います。
「：」がいいかもですね。

**Comment by MaySoMusician** [comment]
以下のような感じになる予定です

3点リーダー（1個）版
![image](https://user-images.githubusercontent.com/34566290/86911550-7905e880-c156-11ea-9387-48e8a6a76814.png)

コロン版
![image](https://user-images.githubusercontent.com/34566290/86911713-b8ccd000-c156-11ea-8f2c-7ee554813813.png)

**Comment by kaizumaki** [comment]
@MaySoMusician ありがとうございます！こう見ると、まあどちらでもいいっちゃいい感じではあるのですが...。コロンのほうがスマートな感じがします。
