### ISSUE TITLE
「施設別休止要請について」カード削除

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4970]
「施設別休止要請について」のカードの削除をお願いします。
コンポーネントのファイルも削除して大丈夫です。

<img width="838" alt="スクリーンショット 2020-07-08 20 20 42" src="https://user-images.githubusercontent.com/14883063/86912871-b23f5800-c158-11ea-99eb-d2636ee67710.png">

**Comment by dmamira** [comment]
こちら、対応します。

**Comment by kaizumaki** [comment]
@dmamira ありがとうございます！
