### ISSUE TITLE
「モニタリング指標」タブ名変更

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4972]
「モニタリング指標」のタブ名を「モニタリング項目」に変更をお願いします。
タブ下部の黄色背景の注意書き部分も削除します。

<img width="838" alt="スクリーンショット 2020-07-08 20 26 15" src="https://user-images.githubusercontent.com/14883063/86913666-ef581a00-c159-11ea-856a-443754696540.png">

**Comment by mcdmaster** [comment]
やってます！
