### ISSUE TITLE
左カラム リンクタイトル変更

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#498]
左カラム
【東京都主催等】中止又は延期するイベント・説明会等
が長いので、短縮することにしました。
下記でお願いします。

（変更後）
東京都主催等　中止又は延期するイベント等
https://www.seisakukikaku.metro.tokyo.lg.jp/information/event02.html

**Comment by yokinist** [comment]
対応します！
