### ISSUE TITLE
google検索・yahoo検索でmetaタグの設定が反映されていない

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4991]
## 起こっている問題 / The Problem
google検索・yahoo検索で「コロナ　対策サイト」と検索したとき、当サイトの情報が英語タイトル＋最新のお知らせになっている。

## スクリーンショット / Screenshot

google検索
<img width="851" alt="スクリーンショット 2020-07-09 20 02 04" src="https://user-images.githubusercontent.com/14883063/87032654-e7fb4400-c21f-11ea-88aa-8d518641b1c2.png">

yahoo検索
<img width="677" alt="スクリーンショット 2020-07-09 20 03 39" src="https://user-images.githubusercontent.com/14883063/87032687-f5183300-c21f-11ea-9775-35f809bf3912.png">

## 期待する見せ方・挙動 / Expected Behavior
- 設定してあるmetaタグの内容が検索結果に出るようになる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Nekoya3** [comment]
nuxtのバージョンアップで`nuxt generate`の挙動が変更されたので`nuxt.config.ts`に `target: 'static'`を追加すると治る可能性はあるかもですね（先に#4954のマージでnuxt-tsのアップデート必要ですが....)

**Comment by kaizumaki** [comment]
> nuxtのバージョンアップで`nuxt generate`の挙動が変更されたので`nuxt.config.ts`に `target: 'static'`を追加すると治る可能性はあるかもですね（先に#4954のマージでnuxt-tsのアップデート必要ですが....)

@Nekoya3 情報ありがとうございます！なるほどですね。
#4933 でnuxtのアップデートを対応してくださった @goki90210 さんにもご意見を伺いたく。こちらの件、いかがでしょう？

**Comment by goki90210** [comment]
@kaizumaki @Nekoya3 
nuxt-config.tsにtarget: 'static'を追加することで対応できそうです。（`nuxt generate`の確認を見落としていました。）
#4954 に、nuxt-config.tsの修正も含めます。

**Comment by Nekoya3** [comment]
@goki90210 ありがとうございます！
もし可能であればなのですが`nuxt generate`コマンド自体がNuxt 3 以降で廃止予定になっています。`nuxt build & nuxt export`に変更いただくことは可能でしょうか？
いつまで続くかわからない関係上、廃止される可能性があるものを使用しないで済むのであればしたくないという思いです。

https://nuxtjs.org/blog/going-full-static#notes

**Comment by goki90210** [comment]
@Nekoya3 
ありがとうございます。

package.jsonの
`nuxt-ts generate` を` nuxt-ts build && nuxt-ts export`
に修正し、問題がないか確認します。

**Comment by goki90210** [comment]
先程の補足で
`nuxt.config.ts`に`target: 'static'`を追加すると
`nuxt-ts build && nuxt-ts export`に変えないといけないようです。

その上で確認したところ、この修正で&lt;html&gt;タグの内容が変わりました。

修正前
`<html prefix="og: http://ogp.me/ns#" lang="ja-JP">`

修正後
`<html prefix="og: http://ogp.me/ns#" lang="ja-JP" data-n-head="%7B%22prefix%22:%7B%22ssr%22:%22og:%20http://ogp.me/ns#%22%7D,%22lang%22:%7B%22ssr%22:%22ja-JP%22%7D%7D"`

**Comment by goki90210** [comment]
Full Static Generationの導入でブラウザからはページ構築のためのAPIリクエストがなくなるようで、
レスポンス向上にもつながるかもしれません。
https://microcms.io/blog/nuxt-full-static-generation/

**Comment by harmo-snipe** [comment]
初めて投稿します。無礼があったら、すいません。
多言語実装を、IPアドレスで出し分けていると外部から（ソースで確認したわけではありません）確認しました。
多言語実装をIPアドレスで行うと、googlbotのあるアメリカのIPアドレスになり、全てのコンテンツが英語と判断されます。
従って、検索結果はすべて英語になり、日本での検索順位も付かなくなり下げられてしまいます。

正しい多言語実装をして下さい。
正しい方法は、サイトマップを使ったりhreflangを実装したりします。
https://support.google.com/webmasters/answer/189077
わかりやすい方法はGoogleヘルプの「htmlタグ」を利用した方法です。
マイリーさんの動画とGoogleのヘルプをみて、htmlタグでhreflangの実装作業をしてみて下さい。

私が、海外からのアクセスで英語になると判断したのは
https://www.webpagetest.org/result/200711_EZ_4a91e873d24269cace95f719c74562fe/
の結果です。

是非サイトにhreflangの実装をお願いします。

**Comment by MaySoMusician** [comment]
@harmo-snipe コメントありがとうございます！ 取り急ぎ言語判定の部分のみ回答いたします。
本サイトでは多言語化に [nuxt-i18n](https://nuxt-community.github.io/nuxt-i18n/) を使用しています。nuxt-i18nでは前回設定された言語をCookieに記憶しており、初回読み込み時（or Cookieが無い場合）は「ブラウザの言語設定」「HTTPリクエストヘッダーのaccept-language」の順に設定を参照します。

該当するnuxt-i18nのコードは[こちら](https://github.com/nuxt-community/nuxt-i18n/blob/e60b62350e10ca993078e232a954c2ea940dd778/src/templates/plugin.main.js#L161-L192)です。
上記実装によれば、本サイトではIPアドレスによる言語判定は行なっていないという認識です。

**Comment by MaySoMusician** [comment]
`<head>` 内に `<link rel="alternate" hreflang="lang_code" href="url_of_page" />` を記述する場合、nuxt-i18nの `Vue.localePath` メソッドと `VueI18n.locales` を組み合わせることで実現可能だと思われます。

と思いましたがnuxt-i18nの機能にそもそも[SEO対策のものがありました](https://nuxt-community.github.io/nuxt-i18n/seo.html)。
まず `isCatchallLocale` （ともしかしたら `baseUrl` ）の設定が必要です。さらにパフォーマンス低下を回避するため、そのまま `seo: true` にするのではなく、[こちらのドキュメント](https://nuxt-community.github.io/nuxt-i18n/seo.html#improving-performance)の記述に従い各layoutの `head` hookで `$nuxtI18nSeo()` を使用するのが良いと思われます。

**Comment by harmo-snipe** [comment]
MaySoMusician さん。こんばんは。
Googlebotのアクセスする応答にalternateで複数の言語が実装されている事を伝えることができれば、検索エンジンを利用している地域に応じてその言語で検索結果が表示されます。
nuxt-i18nというものを私は知りませんが、該当のページを見る限り、適切な実装ができそうですね。

**Comment by Nekoya3** [comment]
@harmo-snipe 上記で @MaySoMusician さんが言語判定・hreflangに関する部分については回答いただいていましたのでそのほかの部分について....
現在サイトはhreflangではなくlangタグを指定している状態で、sitemapについても生成は行っていません。
（その二点については当issueでの内容とは関係がないと思われますので別なissueを立てていただけますと幸いです。）
また、現状下記サイトの「gTLD を使用するサブディレクトリ」という実装であると思われるため特別対応が必要なレベルではないように思うのですが、いかがでしょうか？（対応が行えるのであればしたほうが良いのかもしれません）
https://support.google.com/webmasters/answer/182192?hl=ja&ref_topic=2370587

**Comment by harmo-snipe** [comment]
lang設定は、bingでは有効かもしれませんが、少なくてもYahooとGoogleに関しては使用していません。
（html lang=は、Chromeは見ている可能性があります）
また、話題になっているhttp-equiv="content-language"などのmetaタグはGoogleのヘルプにもサポートされているものに入っていません。
https://support.google.com/webmasters/answer/79812?hl=ja

私はBingの仕様を知りませんが現状のlang設定を残せるなら、Bingのために残しておいた方が良いと思います。
（あってもGoogle/Yahooは無視しますので問題はありません）

ヘルプの内容ですが、現状サブディレクトリでの言語設定になっており、クロールを繰り返すウチに判断されると思われ、相当の期間を要すると思います。
やはり、早期の日本語検索結果の回復のため、hreflangの実装が必要ではないかと思います。

**Comment by Nekoya3** [comment]
なるほど。知らなかった部分でしたのでとても勉強になりました。ありがとうございます。

そちらへの対応のissue #5001 を立てさせていただきました！

**Comment by kaizumaki** [comment]
みなさん、ご指摘ご検討ありがとうございます！こちらのissueについては #4954 のPRで解決されるかと思っています。
SEOについてはとても大事なところですので、引き続きの検討については #5001 で行いたいと思います。よろしくお願いします 🙇‍♀️

**Comment by harmo-snipe** [comment]
すいません。
しつこいようですが、全く問題は解決されていないです。
まず、googlebotに対して返却するhtmlは
https://search.google.com/test/mobile-friendly?id=oYG7-PNxUzrirGij3ENnOw
（初めてこの画面を見る方はhtmlタブを選択して、googlebotに対して返却しているhtmlを確認する事ができます）
の様になります。
見てのとおり完全な英語版を返却しています。
（htmlが lang="en-US" を返却しているのは分かりますがタイトルタグなどはすべて英語）

私は当初IPアドレスの出し分けと間違った想定をしてしまいましたが、
その想定は特に関係無く、
googlebotに返却するhtmlが英語版になってる以上、
日本での検索結果が英語になるのは必然と言えます。

あと、ドメインについてです。
tokyo.lg.jp
これは日本語のccTLDです。
従って、このコンテンツは「日本でen-US言語でマークアップしたWebサイト」という判断をGoogleは行います。
検索上でも、とても奇妙な状態です。

本来であれば、日本語のサイトなので日本語でマークアップを行い、代替としてenやzh等を実装していると
検索エンジンには伝えなければなりません。
その手法が、hreflangです。

Googleが自動で現在のページが日本語と判断するまで、恐らく数ヶ月単位の期間が必要です。
（とても需要のあるサイトなので現在の状態でももっと早く認識するようになる「かも」しれませんが）
以前は何故Googlebotに正しい日本語返却していたのに、現在は英語を返すようになったのでしょうか。
それがすべての原因です。
そこの部分が元に戻せれば、すぐに解決すると思いますけど。

**Comment by Nekoya3** [comment]
@harmo-snipe 
hreflangに対する対応については以前にお伝えした通り、 #5001 にて対応を行いたいと思っております。
（もし可能であれば変更のPRをいただけますと早めの対応が行えるかと思います）
英語版のサイトをGoogle Botによるクロール時に返してしまう問題への対応は上記の対応が必要かと思います。

本issueにはmetaタグのDescriptionが認識しないという部分も含まれているかと思うんですが、そこの部分も現状修正できていないかと思います。そちらへの対応として何か方法をお持ちではないでしょうか？（HTML的にはDescriptionをしっかりと返しているためhreflangとは別な理由であると考えているのですが、何か関連があったりしますでしょうか？）

> 以前は何故Googlebotに正しい日本語返却していたのに、現在は英語を返すようになったのでしょうか。
> それがすべての原因です。
> そこの部分が元に戻せれば、すぐに解決すると思いますけど。

これについては毎日/毎週多くの変更が行われているため原因となっている点の特定にはかなり時間がかかりそうな印象です...
あまりSEOに関して知識がないため、的外れなことを言っていましたら申し訳ありません。

**Comment by harmo-snipe** [comment]
@Nekoya3 さん返信ありがとうございます。
hreflangの実装について #5001 了解しました。

descriptionについては、昨晩は
<meta data-n-head="ssr" data-hid="description" name="description" content=" Last update: 2020/07/13: This website was opened by the Tokyo Metropolitan Government to provide the latest information of COVID-19." />
と入っていましたが、現在はないですね。

Googleがdescriptionをどう認識するかをお伝えします。
まず、descriptionをマークアップしていても100％検索結果で表示される訳ではありません。
アルゴリズムで検索者がわかりやすいと判断した内容を表示します。
従って、descriptionのマークアップと検索結果をあわせようと試行錯誤するのはナンセンスになります。
descriptionは、記事の概要なので、このページで何を表示し、このタイトルをクリックすることで
どんな情報が得られるかを記述します。
昨日マークアップされてているようなので良いかと思います。

＞これについては毎日/毎週多くの変更が行われているため原因となっている点の特定にはかなり時間がかかりそうな印象です...

乱暴かもしれませんが、まずはHTTPリクエストがなんであろうと、日本語のページを返却するのが
先だと思います。#5001 をみていても、すぐに実装できるかどうか分からない状態です。

すべて日本語を返却するのは、識者であればそう難しい事ではないような気がします。
こういう時のトラブルシューティングは、大多数が影響しないように施策を打ちます。

httpレスポンスに対して、日本語で返却しても、言語選択やクッキーを消すわけではないので
多言語しか分からない方も、そうそう問題になる事は無いと思います。

**Comment by goki90210** [comment]
＠harmo-snipe さん
> descriptionについては、昨晩は
> 
> と入っていましたが、現在はないですね。

確かに
`<html prefix="og: http://ogp.me/ns#" lang="ja-JP">`
に戻っていますね。

※このことを書きたかったんですよね？（平文でタグを書くとだめなんです。）

**Comment by harmo-snipe** [comment]
@goki90210 さん
ご指摘ありがとうございます。
コードのボタンでエスケープできるのが分かりました(*^-^*)
先ほどみたら、descriptionは出力されていました。

**Comment by tokyo-citizen** [comment]
そもそも本件について何が起きているかと言う切り分けについて、まずはGoogle Search Consoleにて確認いただくのが良いのではないでしょうか。
(おそらく本サイトのGoogle Analyticsに関するアカウントをお持ちの方に確認いただくのが簡便かと思います)

関係ない気がしますが、[https://stopcovid19.metro.tokyo.lg.jp](https://stopcovid19.metro.tokyo.lg.jp)をGoogle Translateにかけてみると、splashの表示で応答がなくなることから、ふと思いました。

**Comment by harmo-snipe** [comment]
@tokyo-citizen さん
発生している事は、以下で述べています。
https://github.com/tokyo-metropolitan-gov/covid19/issues/4991#issuecomment-657597243
現状は、日本語ドメインに外国語をマークアップしているWebサイトと認識しています。

>そもそも本件について何が起きているかと言う切り分け
本件をサーチコンソールで切り分けするような機能を私は知りません。
英語のQueryが無いことで、圧倒的多数の使用者は日本語を理解し入力できる等は、分かると思います。

ちなみにサードパーティツール（ahrefs）でこんな感じです
![image](https://user-images.githubusercontent.com/40130590/87384789-8cdaa000-c5d7-11ea-9279-b2c2172db24f.png)

**Comment by tokyo-citizen** [comment]
言葉足らずでしたね。
[URL 検査ツール](https://support.google.com/webmasters/answer/9012289)をイメージしておりました。
見えている現象の裏には複数の原因が絡み合っている場合が時々あるので、運営サイドでもし可能ならばと言う意味でございます。

**Comment by kaizumaki** [comment]
運営側で確認すべきことがありましたらお知らせくださいね。ちなみにGoogle Analyticsを管理しているのは東京都なので、確認事項については詳細を書いていただくと伝えやすいです。

**Comment by harmo-snipe** [comment]
URL検査ツールは、インデックスデーターベースの登録状態を表示するツールです。
・いつクロールしたのか
・クロール後どうなったのか
・正規URLはなんなのか
などでいずれも、本件を切り分ける手段にはなり得ません。
唯一役立つのが、「クロール済みのページを表示」する機能です。
それを使うとGoogleが認識している(インデックスレコードに登録されている)htmlを表示する事ができます。
しかしそれの機能は、昨日私が既に提示しているモバイルフレンドリーテストとほぼ同一だと考えられます。
https://search.google.com/test/mobile-friendly?id=WDYssYKPrlclgdGGveljwQ

**Comment by tokyo-citizen** [comment]
@kaizumaki さん

> 運営側で確認すべきことがありましたらお知らせくださいね。ちなみにGoogle Analyticsを管理しているのは東京都なので、確認事項については詳細を書いていただくと伝えやすいです。

お手を煩わせるピンポンゲームになりそうなので、Mobile-Friendly Test Toolでほぼ目的が達せました。
Google Search Consoleで同様のことを確認できますが、リダイレクトエラーが出てますね。
(@Nekoya3 さんが[#5001のコメント](https://github.com/tokyo-metropolitan-gov/covid19/issues/5001#issuecomment-657989863)で提示いただいた内容と同じと思います)

<img width="783" alt="sample" src="https://user-images.githubusercontent.com/68139470/87521843-dacad300-c6bf-11ea-87d8-da5d884bbb6d.png">

**Comment by kaizumaki** [comment]
検索結果については #5001 #5056 で解決したようですので、こちらのissueはクローズします。
