### ISSUE TITLE
モニタリング項目のテーブルをモバイルサイズでも全体が見えるようにしたい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#4992]
## 改善詳細 / Details of Improvement
- モニタリング項目のテーブルは、モバイルサイズ時に横スクロールするようになっています。
- 横スクロールは、テキストが長くなる言語でも不自然な表示にならないようにする配慮からでした。
- リリース後に、「やはりこのテーブルは全体が見えていたほうがいいのではないか」という意見が東京都からありました。

## スクリーンショット / Screenshot

以下はiPhoneXSで見た場合

![モニタリング項目テーブルiPhoneXS](https://user-images.githubusercontent.com/14883063/87103670-ab1b6580-c290-11ea-9249-2b69bfe24921.jpg)

## 期待する見せ方・挙動 / Expected behavior
- `overflow-x: auto;` をせず、テーブル全体が見えるようにしたいです（せめてiPhoneXのサイズのスマホでそうなっているのが理想）。
- どのような実装がベターなのか、ご提案いただきたいです 🙏 
- 例えば `潜在・市中感染` を `潜在・<br>市中感染` に、 `検査体制` を `検査<br>体制` というふうに途中で改行するといいのではないかという意見もありましたが、この場合、多言語化で苦労しそうです。
- ほかに、モバイルサイズ時にフォントサイズを小さくするという案もありました。

## 動作環境・ブラウザ / Environment
- iOS / Android
- Chrome / Safari

**Comment by goki90210** [comment]
グリッドシステムで
xs, sm, md, lg, xl
でスタイルを変えられるようにできればいいのかなと思います。

言うは易く行うは難しですが…。

**Comment by ShunIshii** [comment]
少し論点をずらしてしまうかもしれませんが、数値の列の単位がバラバラであるため、そもそも表である必要がないようにも思います。
![image](https://user-images.githubusercontent.com/39784917/87151413-bd2bf100-c2ee-11ea-9767-9f547461ff1e.png)
これと同様の形式にすれば、モバイル対応は必要ありません。

**Comment by kaizumaki** [comment]
たしかに表というのは何かと厄介で、セマンティックにコーディングするのは難しかったりしますよね。
ただ、東京都の元のイメージが表の形式なので、そこを変えるのはかなりの説得力がいるかと...

**Comment by tokyo-citizen** [comment]
東京都の意向を鑑みつつ、「検査陽性者の状況」を参考にして、例えば以下のようなアプローチはいかがでしょうか。
(一部の文字列を短くしていることはアプローチの本質ではないかもしれません)

![sample](https://user-images.githubusercontent.com/68139470/87217043-214ac580-c380-11ea-9a60-6992f7d916c0.png)

**Comment by kaizumaki** [comment]
@tokyo-citizen おお！これはすごいアイディアですね！テーブルの１列目をヘッダー的に扱った感じですね。これは都に提案してみる価値はありそうです。

**Comment by macropygia** [comment]
横槍すみません、予め文字数の多い英語が違和感なく収まるように設計していただけると助かります（英語が収まればやさしいにほんごも概ね収まります）。日本語でも今後長い文言が入る可能性はありますし。
@tokyo-citizen さんの案を元にすると、例えば以下のようなレイアウトであればほどよく収まります。（文言は実際に使われているものを適当に組み合わせたダミーです）

![image](https://user-images.githubusercontent.com/3162324/87842444-7ee29300-c8e7-11ea-8b5d-96318da75825.png)

**Comment by kaizumaki** [comment]
@tokyo-citizen さんから提案いただいたデザインを、都に検討してもらいました。以下、担当の方からのフィードバックです。

-----

いただいた御提案について検討したのですが、以下のような理由から現在の形式のほうがよいのではないかと考えております。
- 「(1)新規陽性者数」は「潜在・市中感染」などの大項目がなく、新規で作成する必要があり、それに伴い[元の資料](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.html)も修正する必要があります。庁内調整に大変時間がかかることが予想されます。
- 「検査陽性者の状況」のつくりと同様の考え方で行くと、1行に1つの項目（数値）が入っていたほうが見やすいように思います。いただいた形式だと、例えば「増加比」はパッと見たときになんの数値か分かりにくいのではないかと思いました。
モニタリング項目(3)(4)(6)(7)は、1つの項目に対して2つの数値があり、「潜在・市中感染」などと同様の形で階層化して見せることもできると思いますが、かえって煩雑な表になってしまうことを危惧しています。

現在の形式を生かしたまま、モバイルサイズに対応させていただけると幸いです。

-----
↑ここまで

「１行に１つの値」という意味でいけば、 @macropygia さんのアイディアは一つの方法としてアリのような気がします。

一方で、すでに公式で発表されているものが表形式なので、それをなるべく保ったほうがいいというのも納得できます。
テーブルをモバイルサイズでおさめるには、やはりフォントサイズをギリギリまで小さくするしかないでしょうか...

**Comment by tokyo-citizen** [comment]
@kaizumaki さん
フィードバックありがとうございます。
ドサクサに紛れてアピアラアンスの全体統一とコードの再利用を狙ったのですが、
例えば以下のようなことを想像できますし、東京都からいただいたご回答も納得できます。
- 原局(おそらく福祉保健局)から上がって[東京都の対策本部会議](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007288/1009642.html)を通った資料が元ネタ
- [モニタリング会議](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1009676/index.html)で資料の運用が始まっており体裁も広く知られている
- 仮に変更するにしても局をまたがる調整になるであろう事が想像できる

「もし可能でしたら」の話ですが、仮に現行を限りなく踏襲と言う方向性の場合でも、
以下のような方向性はいかがでしょう。
- 「検査陽性者の状況」の表とフォントサイズを合わせる(もしくはそれより小さくする)
- いわゆる罫線の太さを「検査陽性者の状況」の表と合わせる

**Comment by kaizumaki** [comment]
@tokyo-citizen ご提案ありがとうございます。
私としては、**誤解を生まない体裁（1行に1つの項目（数値））かつモバイルサイズで収まっている**、という条件を満たせば説得できるのではないかと思っています。
できればpreviewで提案したいところです（多少手間はかかりますが）。

**Comment by kaizumaki** [comment]
私のほうで @macropygia さんの案で組んでみますね。
もちろん、他のアプローチやご意見も引き続きお待ちしています。

**Comment by macropygia** [comment]
因みに、「テーブルでは収まらない場合だけ体裁を変える」といった処置は不可なのでしょうか。

**Comment by kaizumaki** [comment]
@macropygia 
> 「テーブルでは収まらない場合だけ体裁を変える」といった処置は不可なのでしょうか。

なるほどですね。その発想はなかったです。誤解を生じない表現であればアリだと思います。

**Comment by kaizumaki** [comment]
みなさんフォローありがとうございます！みなさんのアイディアを元に私のほうでPRを作成し、#5089 と #5093 を東京都に検討いただいたところ、 #5089 の案が採用となりました。 @tokyo-citizen さん、 @macropygia さんのアイディアが反映される形となります。
東京都の担当の方も「今回の御提案は庁内関係者の発想では出てこなかった案ですので、コントリビューターさんの御提案に感謝いたします。」とのことでした。
みなさん本当にありがとうございます！
