### ISSUE TITLE
カードによって日付表示形式の揺れがある

### ISSUE THREAD

**Issue by tokyo-citizen** [tokyo-metropolitan-gov/covid19#4995]
## 改善詳細 / Details of Improvement
- 都内の最新感染動向のカードによって日付表示形式が「M/D」と「M月D日」で混在しています。

## スクリーンショット / Screenshot
現在の日付フォーマットの表示形式一覧にします。
NULLは該当する項目が存在しないことを表しています。

| カード | 右上表記 | テーブル表記 |
| --- | --- | --- |
| 検査陽性者の状況 | NULL | NULL | 
| 新規患者に関する報告件数の推移 | M/D | M月D日 |
| モニタリング項目 | NULL | NULL |
| モニタリング項目(1)新規陽性者数 | M/D | M/D |
| モニタリング項目(2)#7119における発熱等相談件数 | M/D | M/D |
| モニタリング項目(3)新規陽性者における接触歴等不明者数 | M/D | M/D |
| モニタリング項目(4)検査の陽性率 | M月D日 | M/D |
| モニタリング項目(5)救急医療の東京ルールの適用件数 | M/D | M/D |
| モニタリング項目(6)入院患者数 | M/D | M/D |
| モニタリング項目(7)重症患者数 | M/D | M/D |
| 陽性患者の属性 | M/D | M月D日 |
| 陽性患者数（区市町村別） | M月D日 | NULL |
| 確定日別による陽性者数の推移 | M/D | M月D日 |
| 検査実施件数 | M/D | M月D日 |
| 受診相談窓口における相談件数 | M/D | M/D |
| 新型コロナコールセンター相談件数 | M/D | M月D日 |
| 都営地下鉄の利用者数の推移 | NULL | M月D日 |
| 都庁来庁者数の推移 | NULL | M月D日 |

## 期待する見せ方・挙動 / Expected behavior
- 日付表示形式が「M/D」または「M月D日」に統一されている。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@tokyo-citizen ご提案ありがとうございます！日付表記については issue #1543 と PR #4232 によって多言語対応と表記統一をしたのですが、その後、グラフの入れ替わりが多数発生し、その分については手付かずになっています。できれば #4232 で実装した内容がこれ以降に実装されたグラフ（モニタリング項目関連）にも適用されていると望ましいかなと思います。

**Comment by shgtkshruch** [comment]
多言語対応を考慮しつつ `M月D日` 形式に揃える感じで対応します。

また、今のように各グラフで日付表記を指定すると今後もずれてくる可能性があるので、共通コンポーネントなどで表記をコントロールする方向で実装しようと思います。

**Comment by kaizumaki** [comment]
@shgtkshruch ありがとうございます！よろしくお願いします 🙇‍♀️
