### ISSUE TITLE
カードによって注釈の形式と位置の揺れがある

### ISSUE THREAD

**Issue by tokyo-citizen** [tokyo-metropolitan-gov/covid19#4996]
## 改善詳細 / Details of Improvement
- 都内の最新感染動向のカードによって注釈の形式と位置の揺れがあります

## スクリーンショット / Screenshot
現在の注釈の形式と位置が以下の条件を共に満たしていないものを一覧にします。
(ただし、注釈が存在しないカードは除外しています)
- 注釈の形式が「（注）+リスト」の形式である
- 注釈の位置がカードの下部である

| カード | 注釈の形式 | 注釈の位置 |
| --- | --- | --- |
| 検査陽性者の状況 | （注）のリスト | 上部 | 
| 新規患者に関する報告件数の推移 | （注）のリスト | 上部 |
| 陽性患者の属性 | ※のリスト | 下部 |
| 陽性患者数（区市町村別） | （注）のリスト | 上部 |
| 都営地下鉄の利用者数の推移 | 各種混在 | 上部 |
| 都庁来庁者数の推移 | ※のリスト | 上部 |

## 期待する見せ方・挙動 / Expected behavior
- 注釈の形式を「（注）+リスト」、注釈の位置を下部に統一する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@tokyo-citizen ご提案ありがとうございます！たしかに、体裁は `「（注）+リスト」、注釈の位置を下部` に揃えていっている最中です。ただ、東京都のほうで文言の表記揺れの修正も同時に行っていますので、こちらのissueはしばらくお待ちいただけると幸いです。単純に文頭の「（注）」を削除すると、その部分の翻訳キーが新しく生成され翻訳がリセットされてしまうので、東京都からの指示を待ったほうがいいという判断です。

**Comment by tokyo-citizen** [comment]
少なくとも以下の考慮事項がありそうだということは推測しておりましたのでお気になさらずに。
- 行政として他の文書等との一貫性
- 翻訳への影響
- 段階的な移行(他の優先事項との兼ね合い)
- カードそのもののライフサイクル

**Comment by nard-tech** [comment]
@kaizumaki @tokyo-citizen 私も本件について気になりました．実際に修正してみてイメージをつかめた方がよいと思いましたので，修正案として PR (#5274) を作成しました．ご確認ください．

**Comment by tokyo-citizen** [comment]
@nard-tech
修正案ありがとうございます。

@kaizumaki
修正案(@nard-tech)をきっかけとして、比較対象のたたき台ですが、以下はどうでしょうか。

基本的な考え方は 、なるべく意味や文言を変えない方が多少なりとも受け入れられる可能性が
大きくなると期待しながら、PR (#5274)  と PR (#5260) の合作です。

PR (#5260)で太字が導入された意図はいわゆる約物を使わずに、誤解が生まれる可能性があったり、
認知度が低い用語について、用語定義を強調する意図と読み取りました。

現状からの変更案の内容は以下です。
- 注釈をグラフやテーブルの下方に移動して他のカードとフォーマットを統一する
- 再帰的な注釈を避けてPR (#5260)で導入された注釈の太字を用いたり
  - 「陽性者の属性」カードのテーブルにある「退院※」の「※」
  - 「都営地下鉄の利用者数の推移」カードの注釈にある「利用者数*」の「*」
- もし長い文章となる場合は文章を分割して別の注釈項目にする
- 注釈項目の各項を、内容に応じて、例えば以下の順に並べ変える(あくまで並べ替え)
  - 概要
  - 用語定義
  - 抽出基準
  - 例外事項
  - 更新頻度

全体感の中で個人的に違和感を感じている「陽性者の属性」「都営地下鉄の利用者数の推移」
「都庁来庁者数の推移」を先出しすると以下のようになります。
(ここではあえて全角の約物について議論対象にしません)

**陽性者の属性**
（注）
- 保健所から報告があり、確認ができているものを反映
- **退院**：死亡退院を含む

**都営地下鉄の利用者数の推移**
（注）
- 1/20~1/24の利用者数の平均値を基準としたときの相対値
- **利用者数**：都営地下鉄4路線の自動改札出場数
- 速報値として公開するものであり、後日確定データとして修正される場合あり

**都庁来庁者数の推移**
（注）
- 土・日・祝日を除く庁舎開庁日の1週間累計数

**Comment by kaizumaki** [comment]
@tokyo-citizen ご提案ありがとうございます！この３つのカードの注釈については他のカードのものと様相が異なるので、判断が難しいところですね。

また、用語定義についてですが、初期の頃に東京都のほうでも「用語集」の追加を検討していた経緯があります（おそらく、多忙ゆえに優先度が低くなっています）。こちらは別途issueを立てていただければ、再度検討のフェーズに持っていけるのではないかと思います。

**Comment by tokyo-citizen** [comment]
@kaizumaki
用語集となると結構大変になると思うので、現状の注釈で用語定義的になっている部分で、
文章を極力変えずに見せ方の修正にスコープを絞ってます！
