### ISSUE TITLE
Chromeブラウザでは"東京都 新型コロナウイルス陽性患者発表詳細"のcsvデータをDLできない (can't dl csv data on Chrome)

### ISSUE THREAD

**Issue by Cartman0** [tokyo-metropolitan-gov/covid19#4998]
hi, dev-teams!

## 起こっている問題 / The Problem
Chrome側の問題かわかりませんが，
Chromeブラウザでは"東京都 新型コロナウイルス陽性患者発表詳細"のcsvをDLできません．
(I don't know as if this is a Chrome's problem,
Chrome browser can't dl the csv file of "東京都 新型コロナウイルス陽性患者発表詳細".)

データのプレビューは問題ないです．

また，Edgeでは問題なくDLできました．

## スクリーンショット / Screenshot

"ダウンロード"をクリックすると以下の画面になります．

![キャプチャ](https://user-images.githubusercontent.com/10578703/87221981-1a857800-c3ab-11ea-938d-6ba5949f72ec.PNG)

## 起こっている問題の再現手段 / Steps to Reproduce
1. access https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068 on Chrome
2. click "探索" > click "ダウンロード"

## 動作環境・ブラウザ / Environment
- Windows10 home 2004
- Chrome

**Comment by kaizumaki** [comment]
@Cartman0 ご指摘の内容はオープンデータカタログに関する問い合わせですね？こちらのリポジトリでは、オープンデータカタログについての不具合はどうにもできないのです。
正式なお問い合わせフォームがあるようなので、よろしければこちらから送ってみていただけますでしょうか？
https://www.shinsei.elg-front.jp/tokyo2/uketsuke/form.do?id=1490076764800

**Comment by Cartman0** [comment]
@kaizumaki  返信有り難うございます．

csvのファイル元は別サービスなんでしょうか？
URLは"https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients.csv" になってますが

**Comment by kaizumaki** [comment]
@Cartman0 当サイトが使用しているものとオープンデータカタログで載せているものの元となっているデータは同じですが、ご報告の内容からみると、データそのものの不具合ではなさそうです。オープンデータカタログサイトの不具合かと思われますので、こちらのリポジトリでは対処できないのです。

**Comment by Cartman0** [comment]
@kaizumaki 

そのcsvのリンクをChrome上でクリックしても同じ問題が起きるのですがこれってオープンカタログの問題なのでしょうか？

**Comment by kaizumaki** [comment]
@Cartman0 そうですね。csvをホスティングしているのは対策サイトと同じドメインです。
ちなみに、私のWindows10 Home Chorome 最新版ではダウンロードできていますね。

**Comment by Cartman0** [comment]
@kaizumaki 
こちらも最新でバージョン: 83.0.4103.116（Official Build） （64 ビット）ですが挙動が謎ですね．．．

**Comment by kaizumaki** [comment]
@Cartman0 さんのネットワーク環境でDHCPが固定で割り振ってあるとか、PCがVPNの内部にあるとかいうことはないでしょうか...？まあ、いずれにせよEdgeではダウンロードできているということなので、ネットワーク環境は関係なさそうですが...

**Comment by Cartman0** [comment]
@kaizumaki 
github上のcsvのrawデータはこちらのChrome上でテキスト表示されるので確かにオープンカタログの方の問題ぽいですね．
ちなみにそちらの環境ではこのCSVを開くとDLが始まる感じでしょうか？

**Comment by MaySoMusician** [comment]
Chromeを介して別のプログラムでネットワーク上のCSVファイルを直接開こうとしている可能性はありませんか？
何となくですがChromeのエラー画面のデザインとは少し違う気がするので、別のエラーかも？と思いました
（"Can't open a file", "Cannot open a file", "Couldn't open a file", "Could not open a file", "Unable to open a file", "Failed to open a file" で画像検索しましたが同じようなエラー画面は見つかりませんでした...）

**Comment by Cartman0** [comment]
＠MaySoMusician

返信ありがとうございます．
この拡張機能が影響してるぽいです．
https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj?hl=ja

しかしこの拡張機能はｃｓｖサポート外，オープンカタログのほうでエクセルファイルを直接扱ってるのだろうか？？

**Comment by MaySoMusician** [comment]
https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients.csv のcontent-typeは `text/csv` で返ってきますね

![image](https://user-images.githubusercontent.com/34566290/87223712-0c8b2380-c3ba-11ea-8821-7523f6bf4a52.png)

**Comment by goki90210** [comment]
Microsoft Officeが入っているWindows 10だと（関連付けの変更をしない限りは）`text/csv`はExcelと関連付けられているのでその辺りも関係あるかもしれませんね。

**Comment by Cartman0** [comment]
拡張機能側の問題のようなのでcloseしておきます．

ただ，ChromeOSではデフォで入ってる拡張機能らしいのでChromeOS利用者からは同様の問題が発生する可能性が高いです．
