### ISSUE TITLE
発症日別による陽性者数の推移を追加

### ISSUE THREAD

**Issue by tokyo-citizen** [tokyo-metropolitan-gov/covid19#4999]
## 改善詳細 / Details of Improvement
- 感染動向をより詳細に把握するために、現状の報告日別・確定日別陽性者数推移の他に、発症日別陽性者数推移を追加する

例えば以下の事情(推測)等でwontfixとなることも想定しております。
(wontfixとなる場合には詳細な理由をご回答いただかなくでも問題ございません)
- 発症日別陽性者数のデータが非公開
- 発症日別陽性者数のデータ準備がすぐには難しい
- asymptomatic case等で発症日を確定できない場合があるため、累積値が報告日別・確定日別陽性者数と一致せず、混乱を招くと判断

## スクリーンショット / Screenshot
「確定日別による陽性者数の推移」と同等のアピアランスのカードを追加する。

## 期待する見せ方・挙動 / Expected behavior
- 発症日別による陽性者数の推移を表すグラフを追加する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@tokyo-citizen ご提案ありがとうございます。こちらの内容については、正式に実装することが決まりました。
細かい指示がありますので、別issueとさせていただきたく思います。

**Comment by tokyo-citizen** [comment]
発症日データの必要性はコンセンサスであったと思いますが、データの公開にあたっては関係者の
皆様のご尽力があったからと思います。
(特に感染症法や個人情報保護条例関連を含む調整が大変だったと推察いたします)

既に[新型コロナウイルス感染症対策に関するオープンデータ項目定義書](https://www.code4japan.org/activity/stopcovid19)でフィールドは定義済みですが、
`data/positive_by_developed.json`の他に、`static/data/130001_tokyo_covid19_patients.csv`にも
データが含まれることを待ち望んでいる方々もいらっしゃると思いますので、先々にも期待させていただきます。

**Comment by tokyo-citizen** [comment]
別のissue(#5194)に引き継いでいただいたのでクローズさせていただきます。
ありがとうございます。
