### ISSUE TITLE
機械的アクセシビリティテストの組み込み

### ISSUE THREAD

**Issue by shunito** [tokyo-metropolitan-gov/covid19#500]
## 改善詳細 / Improve details
vue-axeを導入し、開発サーバ上でアクセシビリティチェックをしやすくする。
今後も複数開発メンバーで作業するにあたって、セルフチェックしやすくなるため。

参考
https://yamanoku.net/vue-a11y/

**Comment by shunito** [comment]
プルリク再チャレンジしました。
イシューにaccessibility タグを追加したいですが、あとから更新はできなそうですね。

**Comment by halsk** [comment]
入れてみました。ご確認ください！

**Comment by shunito** [comment]
確認しました、ありがとうございます。
のちほど関連イシューをあげます。
