### ISSUE TITLE
7日移動平均の算出と表示について

### ISSUE THREAD

**Issue by Cartman0** [tokyo-metropolitan-gov/covid19#5000]
## 改善詳細 / Details of Improvement
モニタリング指標(1)-(5)について，その日＋前6日分の7日移動平均が使われていますが，
こちらの指標の算出方法はどのように決まったのでしょうか？

感染してから約2週間後に発症という特性を考えると，
個人差により2週間+前後の誤差があり（おそらく正規分布ぽくなる），
前6日分でなく前後3日分で算出するほうが適切ではないでしょうか？
（つまり今の移動平均を左に3日分シフトして対応・表示させたほうが適切）

**Comment by kaizumaki** [comment]
@Cartman0 こちらのissueはご質問ということでよろしかったでしょうか？
７日間移動平均については統計学的な手法だと思いますが、[こちらの東京都の資料](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/youseiritsu.files/020512youseiritsu.pdf)に、
> 集団感染発生や曜日による件数のばらつきにより、日々の結果が変動するため、こうしたばらつきを平準化し全体の傾向を見る趣旨から、過去7日間の移動平均値を陽性率として算出

とあります（こちらの資料は当サイトで７日間移動平均グラフを掲載する際に元となったものです）。
これは陽性率について書かれていますが、他の数値についても「曜日による値のばらつき」は以前から指摘されていました。
こうした理由からの７日間移動平均となっています。回答になっていなかったらすみません。

**Comment by Cartman0** [comment]
@kaizumaki 
資料情報ありがとうございます．

前6日分を利用した等平均の7日移動平均は株式の時系列分析ではよく見られる手法ですが，疫学統計の世界でも一般的ということでしょうか？

7日移動平均の計算自体には特に縛りがないので，
- 極端なことを言うと，後6日分で計算しても問題ない
- 等平均である必要もないので日数が離れた分を重みを小さくした重み付け平均も可能（実際は適切な重みを見つけるのが難しいので等平均が一般的ですが）

あたりも可能ですが前6日分で計算しないといけない根拠はありますか？

現在の7日移動平均の計算は最新値として間違いないのですが，
感染してから2週間後±誤差x日（個人差）で発症するケースで考えると，
均すべき誤差は前6日分でなく前後3日分のほうが適切ではないでしょうか？

例えば，現在のケースですと，5/7に最新データが入るとすると，
5/1-5/7分で7日移動平均が計算されて5/7の値が確定扱いになりますが，
実際は3日前の5/4分が確定されたと考えるほうが適切ではないでしょうか？

|データ|-3日|-2日|-1日|±0日|+1日|+2日|+3日|
|:------:|:----:|:----:|:---:|:-----:|:----:|:-----:|:----:|
|日別   |5/1  |5/2  |5/3 |5/4   |5/5  |5/6    |5/7|
|7日移動平均|4/28-5/4|4/29-5/5|4/30-5/6|5/1-5/7|-|-|-|

**Comment by kaizumaki** [comment]
@Cartman0 これについては専門家がついている東京都に聞いてみる必要がありますね。申し訳ありませんが、回答にしばらくお時間いただくことになります。

**Comment by Cartman0** [comment]
@kaizumaki 
対応ありがとうございます．
お手数おかけしますがよろしくお願いします．

**Comment by tokyo-citizen** [comment]
東京都に確認とのステータスと思いますので、参考情報としてお捕らえください。

データの可視化にあたっては例えば以下のようにいくつかの目的があるかと思います。
- 大きなトレンドを広く一般の方がわかりやすいように伝える
- 例えばサイエンスとしての立場で分析を行う

私の推測ではありますが、本サイトのポジションは前者かと思います。

移動平均の目的として、東京都の資料には「ばらつきを平準化し全体の傾向を見る趣旨」と記載されています。
(ばらつきの原因はいくつかあるとは思うのですが、COVID-19の統計データの一部ではウイークエンドバイアスがよく指摘されています)

**Comment by Cartman0** [comment]
@tokyo-citizen さん，図の提供ありがとうございます．

一応私の指摘としては，移動平均の使用する日数の問題でなく，
今の計算では7日移動平均が右にシフトしてしまってるのではないかという部分です．
左に3日分シフトさせたほうが自然に見えませんかね？

**Comment by tokyo-citizen** [comment]
おっしゃるように、ご指摘の点については、待ちかと思います。
(お気を悪くさせてしまったのであれば申し訳ありません)

広く市民にご理解いただくにあたっては、見せ方をどこに着地するかはするかは難しいですね...

**Comment by kaizumaki** [comment]
@Cartman0 ご提案ありがとうございます。こちらのissueについて、東京都に確認いたしました。
当サイトの７日間移動平均の考え方についてですが、[東京都のモニタリング会議資料](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1009676/1011435.html)で前６日分を使った７日間移動平均を使用しているため、当サイトもそれに準じているというのが実際のところです。[資料](https://www.bousai.metro.tokyo.lg.jp/_res/projects/default_project/_page_/001/011/435/7kai/2020082004.pdf)にも記載のとおり、集団感染発生や曜日によるばらつきを平準化する目的です。
また、前後３日間にした場合のデメリットとして、移動平均値を出せるのが３日分遅れてしまうことになろうかと思います。[@tokyo-citizen さんもご指摘](https://github.com/tokyo-metropolitan-gov/covid19/issues/5000#issuecomment-657175062)のように、いち早く数値を伝える目的のサイトであるため、最新値を出すのと同時に参考値として移動平均値を提示したいと考えています。ご理解いただけたらと思います。

**Comment by kaizumaki** [comment]
こちら、東京都からの回答がありましたのでクローズいたします。

**Comment by Cartman0** [comment]
@kaizumaki さん　
対応ありがとうございます．gmailのトラブルでご返事が遅れてすみません．

いまのデータ利用そのままで可能かわかりませんが，
曜日ごとの差があるので曜日ごとの新規感染者の遷移グラフ（凡例が7曜日分）を表示をするというのはどうでしょうか？モニタリング指標になっていないと難しいでしょうか？

**Comment by kaizumaki** [comment]
@Cartman0 そうですね、「曜日によるばらつきを平準化する目的」であるのが現在のモニタリング項目の７日間移動平均なので、そこで別途、曜日ごとに表示させるという案をとおすのは難しいような気がします。
サイトに表示されている情報はすべて東京都の広報としてのものです。そこを説得できる案があれば、東京都の担当の方に目を通してもらいますので、新たにissueを立てていただくのがよいかと思います。
