### ISSUE TITLE
docker-compose.ymlの軽微な改善

### ISSUE THREAD

**Issue by hakozaru** [tokyo-metropolitan-gov/covid19#5011]
## 改善詳細 / Details of Improvement
`docker-compose.yml` の以下の箇所ですが

https://github.com/tokyo-metropolitan-gov/covid19/blob/942f6fcbee3f8c7060602df83a54a5a1b63a018d/docker-compose.yml#L5-L7

コロナ対策サイトでは

- デフォルト名称である `Dockerfile` のまま使用している
- `docker-compose.yml` と `Dockerfile` が同じディレクトリに存在している

なので `build: .` とだけ記述すれば同じ指定となると思います

大変軽微で動作に変化もありませんが、不要なオプション指定を消すことができ、設定ファイルが少しシンプルになるので提案させていただきました

内容に問題なければPR送らせていただきますので、ご確認いただけますと幸いです

## スクリーンショット / Screenshot

ありません

## 期待する見せ方・挙動 / Expected behavior
挙動に変化はありません

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@hakozaru ご提案ありがとうございます！たしかにおっしゃるとおりですね。問題ないと思いますので、PRを送っていただけますでしょうか？

**Comment by hakozaru** [comment]
ご確認ありがとうございます 🙏 
承知いたしました
