### ISSUE TITLE
モニタリング項目の分析・総括コメント[新規実装]

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5016]
7/9から当サイトにてモニタリング項目関連の表およびグラフを掲載しています。
[東京都で週次で掲載している分析・総括コメント](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.html) について、当サイトでもコメント部分を掲載することになりました。

**7/16（木）リリースです。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいてください。**

### デザイン・レイアウト
「最新のお知らせ」の下に配置をお願いします。

* デスクトップサイズの場合
![総括コメントイメージ_デスクトップサイズ](https://user-images.githubusercontent.com/14883063/87301660-f3fe4300-c54a-11ea-943b-f9de24751fae.png)

* モバイルサイズの場合
![総括コメントイメージ_モバイルサイズ](https://user-images.githubusercontent.com/14883063/87301688-ff516e80-c54a-11ea-8125-ec97e9c2512b.png)

上記画像内のテキストはダミーです。テキストは以下のデザインデータからコピーしてください。
[デザインデータ（figma）はこちらです。](https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=37313%3A3282)

「最新のモニタリング項目の分析・総括コメントについて」のリンク先は以下です。
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.html

### データ
データは `monitoring_items.json` の中にあります。
- `総括コメント-感染状況` ： `level` 「感染状況」のカラーを指定・ `label` 「感染状況」コメント
- `総括コメント-医療提供体制` ： `level` 「医療提供体制」のカラーを指定・ `label` 「医療提供体制」コメント
- `総括コメント-更新日` ：「○月○日付の総括コメントは以下のとおりです。」の日付部分

<img width="792" alt="スクリーンショット 2020-07-13 20 27 55" src="https://user-images.githubusercontent.com/14883063/87301750-15f7c580-c54b-11ea-9c18-53cf95048b27.png">

※カラーは以下のパターンになります。

### レベル（４段階）のカラー
**以下の色はこちらの実装以外には使いませんので、`assets/variables.scss`内での変数化はしないでＯＫです。**
* レベル１： `#96CD5F`
* レベル２： `#FFFC4E`
* レベル３： `#FDBE40`
* レベル４： `#FA1629`

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by y-chan** [comment]
やりまーす(細かい修正なんかに対応できない可能性がありますが....)

ちなみにjsonの内容は翻訳対応しますか...?(でもしちゃうと文が変わるたびに更新が行われちゃうのでまずい...?)

**Comment by kaizumaki** [comment]
@y-chan ありがとうございます！jsonで出力しているテキストは数パターンしかないので、そのまま翻訳対応しちゃって大丈夫です。
