### ISSUE TITLE
プロジェクトで設定したESLintのバージョン・ルールとreviewdog / check_eslint_errorのルールが一致していない

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#5038]
## 改善詳細 / Details of Improvement
- #5037 でESLintが通っていないソースがあることが判明したが、それ以前のPRでreviewdog / check_eslint_errorが通ってしまっいる。#5037 ではESLintのバージョンは変更していない。

## 期待する見せ方・挙動 / Expected behavior
- プロジェクトで設定したESLintのバージョン・ルールとreviewdog / check_eslint_errorのルールが一致すること

## 動作環境・ブラウザ / Environment
- なし

**Comment by goki90210** [comment]
具体的には（注：パスはセキュリテ上の理由により編集しています。）
```
> yarn lint
yarn run v1.22.4
$ eslint ./**/*.{js,ts,vue}

covid19\components\PositiveRateMixedChart.vue
  691:41  error  'i' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  696:41  error  'i' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

✖ 2 problems (2 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
という結果になりました。

このルールはおそらく、ESLint@7で適用されていると思われます。

**Comment by goki90210** [comment]
reviewdog / check_eslint_errorのルールがわからないのですが、知る方法はあるのでしょうか？

**Comment by goki90210** [comment]
[reviewdog/action-eslint](https://github.com/reviewdog/action-eslint)は2020/05/09（[1.2.0](https://github.com/reviewdog/action-eslint/releases/tag/v1.2.0)）以降はESLint@7依存になっています。（現在のバージョンは[1.8.0](https://github.com/reviewdog/action-eslint/releases)です。）

https://github.com/tokyo-metropolitan-gov/covid19/blob/18e471cb0c047e193a47448def03b3d41e368093/.github/workflows/reviewdog.yml#L8-L19

reviewdogとreviewdog/action-eslintのバージョンは今は何でしょうか？（GitHubの情報でだけではわかりません）

**Comment by tokyo-citizen** [comment]
これを書いている時点で一番最後にreviewdogが動いたPRで見てみました。
[https://github.com/tokyo-metropolitan-gov/covid19/actions/runs/179516582](https://github.com/tokyo-metropolitan-gov/covid19/actions/runs/179516582)

詳細なログ(View raw logs)は[ここ](https://pipelines.actions.githubusercontent.com/CDXX2OOl4uv1tuqPOUxsyQuw9DzsCPmWF1dC2MDPXztJGWkhLQ/_apis/pipelines/1/runs/10079/signedlogcontent/5?urlExpires=2020-07-24T03%3A40%3A57.4251815Z&urlSigningMethod=HMACV1&urlSignature=5uqQc9hTgwXzW6bSIKx7VO9pOrHz2slf58zGPrWwwQE%3D)で見れるようです。(もっと詳細にはDebug Modeで動かす必要があるでしょうが)

> 2020-07-23T07:38:39.6610216Z` Step 2/6 : ENV REVIEWDOG_VERSION=v0.10.1
2020-07-23T07:38:43.2116706Z  ---> Running in b20616738fd9
2020-07-23T07:38:44.3017598Z Removing intermediate container b20616738fd9
2020-07-23T07:38:44.3023076Z  ---> 1527a0fecdc8
2020-07-23T07:38:44.3061388Z Step 3/6 : RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}

reviewdogはv0.10.1のようです。

> 2020-07-23T07:38:33.6051230Z Download action repository 'reviewdog/action-eslint@v1'

action-eslintはこれしかわかりませんが、[Marketplace](https://github.com/marketplace/actions/run-eslint-with-reviewdog)では、v1.0.0しかないようです。

> 2020-07-23T07:39:52.9430548Z v7.5.0

この時点ではeslintはv7.5.0のようです。
([https://github.com/reviewdog/action-eslint/blob/v1.0.0/entrypoint.sh](https://github.com/reviewdog/action-eslint/blob/v1.0.0/entrypoint.sh)での`$(npm bin)/eslint --version`の返り値)

**Comment by goki90210** [comment]
@tokyo-citizen ありがとうございます。

> この時点ではeslintはv7.5.0のようです。

最新ですね。7.5.0のリリースは7/21なので、8日前は7.4.0であったことが推測されます。（ログがないのでわかりません…）
package.jsonのESLintのバージョンは7.4.0なので合わせたほうが良いかもしれません。
#5068 がマージされないようでしたら合わせますが…。

**Comment by tokyo-citizen** [comment]
> 最新ですね。7.5.0のリリースは7/21なので、8日前は7.4.0であったことが推測されます。（ログがないのでわかりません…）

[8日前](https://github.com/tokyo-metropolitan-gov/covid19/runs/876155898)は以下のように7.4.0でした。
```
2020-07-16T04:33:53.7808437Z v7.4.0
```

> - reviewdog, reviewdog/action-eslintは最新のものをリポジトリから取得して、Docker上にインストールして実行しているようです。

action-eslintはリリースタグとは関係なく以下のように常にv1.0.0というやり方のようで、
workflowを動かしたときに依存してeslintのバージョンが決まるという事ですね。
https://github.com/reviewdog/action-eslint/blob/v1.8.0/package.json#L2-L3
```
"name": "action-eslint",
"version": "1.0.0",
```

**Comment by kaizumaki** [comment]
@goki90210 @tokyo-citizen フォローありがとうございます！
こちらの件、なんとかしたいですね。  #5068 をマージしましたが動作するタイミングがわからず、ちゃんと動くかどうかわからない状態です。そもそも #5068 が正常動作したところで、こちらの件が解決するのかどうかもよくわかっていないのですけど...
今後どういった対応方法が考えられるでしょうか？

**Comment by tokyo-citizen** [comment]
@goki90210 @kaizumaki
#5068 では、まずRenovateの設定ファイル導入が終わりましたが、動作させるにはGitHub Appの導入と実行周期の設定が必要だと思います。その他、Renovateの実行結果としてPRが出たときにどのように適用するかの運用ですね。

これが整うまでの間は、eslintを手動でupgradeするのもあるかと思います。

**Comment by goki90210** [comment]
@kaizumaki 
PR実施時に動くreviewdog, reviewdog/action-eslintは最新のものを取ってくるという仕様は変えられないと思われるので、
reviewdog, reviewdog/action-eslintのバージョンアップに合わせて、package.json の ESLintのバージョンを更新していくしかないと思います。

まずは、package.jsonを更新しましょうか？

@tokyo-citizen
> その他、Renovateの実行結果としてPRが出たときにどのように適用するかの運用ですね。

そうですね。例えばdayjs@1.8.30の問題（#5087）のようなことが発生した場合ですよね

**Comment by kaizumaki** [comment]
@goki90210 
> まずは、package.jsonを更新しましょうか？

そうですね。package.jsonの更新については、@mcdmaster さんが検討に検討を重ね #5061 でがんばってくださっている最中ですが、ESLintについてはどのように進めましょう？

Renovateの設定については、別途すすめる感じでしょうか。こちらについてもご教示いただけるとうれしいです。 @tokyo-citizen

**Comment by tokyo-citizen** [comment]
@kaizumaki
Renovateの設定と運用についてはこれが参考になると思います。
[https://engineer.recruit-lifestyle.co.jp/techblog/2019-12-10-renovate/](https://engineer.recruit-lifestyle.co.jp/techblog/2019-12-10-renovate/)

**Comment by tokyo-citizen** [comment]
@kaizumaki
Renovateの運用についてはこれの「パッケージ更新の運用」も参考になるかと。
[https://user-first.ikyu.co.jp/entry/2018/05/07/193755](https://user-first.ikyu.co.jp/entry/2018/05/07/193755)

**Comment by goki90210** [comment]
@kaizumaki 
#5061 はdayjsの問題(#5087)も解消しないとリリースできないと考えているので別PRでお願いします。

**Comment by tokyo-citizen** [comment]
いろいろ混ざってきましたが、例えば以下の流れに順番を整理するのはいかがでしょうか。
- reviewdog/check_eslint_errorの問題解消 (#5038) **←このIssue**
  - PRややリリースエンジニアリングが混乱するので優先する
  - eslintの更新という観点に絞って`package.json`を更新(もしdayjsの問題が出る場合は`package.json`で`"dayjs": "1.8.29"`とstaticに指定して回避)
- Renovateのアクティベート (#3841)
  - GitHubの設定変更が必要で少し時間がかかるのでreviewdogの問題解決の後に運用開始
- dayjsの問題解消(#5087)
  - 1.8.31のリリースを待って`package.json`を更新(`package.json`で`"dayjs": "1.8.29"`とstaticに指定したのを戻す)
- `package.json`の全体更新 (#5061)
  - corejs3への更新という観点に絞ってpackage.jsonを更新

**Comment by goki90210** [comment]
すでに、ESLint@7.5.0、@nuxtjs/eslint-config-typescript@3.0.0は適用されているようです。

また、prettierもメジャーアップデートしたことによって、eslintで大量にエラーが発生します。
prettierもメジャーアップデートするさいにルールを再検討しなければいけなかったですね。

**Comment by goki90210** [comment]
prettierをメジャーバージョンアップしたことによって、デフォルトのルールが変わっています。
具体的にどのルールが変わっているのかは調べきれていませんが、少なくとも

1. JSONデータは末尾も","をつける。（これが最も多い）
2. ラムダ式のfunction引数のカッコは省略しない
3. リテラル文字列の途中に改行を入れない
4. importの順序のルールが追加された

があるようです。
今のところはfixオプションですべて修正可能ですが、
特に1.については（設定の有無も含め）ルールを決める必要があります。

現在のlintのエラーは
[lint.txt](https://github.com/tokyo-metropolitan-gov/covid19/files/4998050/lint.txt)
のとおりです。

**Comment by kaizumaki** [comment]
@goki90210 フォローありがとうございます！prettierのルールは考えておくべきでしたね。失念していました。ご指摘感謝です 🙏 
1.については、jsonの末尾も","をつける、の方向でいいのではないかと私は思います（そのほうがjsonに追記したときのミスが減るような気がします）。

**Comment by mcdmaster** [comment]
[Prettier のドキュメント](https://prettier.io/docs/en/options.html)で `v2.0.0` でページ内検索をかけると、いくつか見つかりました。
ご参考までに、列挙しておきますね。 @goki90210 さんに挙げていただいたポイントとカブります。
これらから取捨選択することが求められそうです。
- 末尾のカンマ：`v2.0.0` からの `es5` ルールの適用に伴い、必要になった
- ラムダ式関数の引数のカッコ：`v2.0.0` からは必須 i.e. `(x) => {}` : OK, `x => {}` : NG
- `babel-ts` をトランスレータとして選択可能になった
- 行末のエスケープシーケンスは LF のみ、CR+LF は禁止

**Comment by goki90210** [comment]
@mcdmaster @kaizumaki 
> * `babel-ts` をトランスレータとして選択可能になった

これですね。

> Both the babel and flow parsers support the same set of JavaScript features (including Flow type annotations). They might differ in some edge cases, so if you run into one of those you can try flow instead of babel. Almost the same applies to typescript and babel-ts. babel-ts might support JavaScript features (proposals) not yet supported by TypeScript, but it’s less permissive when it comes to invalid code and less battle-tested than the typescript parser.

（意訳・babel-ts might～）
babel-tsは、TypeScriptでまだサポートされていないJavaScript機能（プロポーザル）をサポートしている可能性があるが、不正なコードに関しては許容度が低くなり、typescriptパーサーよりも実戦経験がない。

デフォルトはNoneなので、私はデフォルトのままでもいいと考えます。

> jsonの末尾も","をつける、の方向でいいのではないかと私は思います（そのほうがjsonに追記したときのミスが減るような気がします）。

これは私もそう思います。
もう少し待って、他の意見がなければデフォルトのままで、eslint --fixしましょうか？

**Comment by kaizumaki** [comment]
@mcdmaster  @goki90210 詳細ありがとうございます。 
> もう少し待って、他の意見がなければデフォルトのままで、eslint --fixしましょうか？

はい、その方向でお願いします 🙏

**Comment by kaizumaki** [comment]
@goki90210 #5061 もマージしました。eslint --fixをお願いしてもいいでしょうか？
明日にはstaging, masterまで反映させたいと思っています。

**Comment by kaizumaki** [comment]
@goki90210 こちらのissueの内容は解決しましたでしょうか？

**Comment by goki90210** [comment]
@kaizumaki RenovateによってESLintと設定系のライブラリが常に最新化される前提であれば問題ありません。

**Comment by kaizumaki** [comment]
@goki90210 了解しました。では引き続きRenovateの運用方法の検討 #5142 にて持ち越したいと思います。

**Comment by kaizumaki** [comment]
Renovateの運用により、こちらのissueは解決していると思われるので、一旦クローズとしますね。また問題が再発したら再オープンいたします。
