### ISSUE TITLE
検査実施日別状況のグラフ内の単位を人→件に

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#504]
検査実施数のグラフなので、単位は「人」ではなく「件」で表示するのが正しい。
![C11F1F5B-60E2-4B76-939D-AB19B77A7159](https://user-images.githubusercontent.com/4206675/75990459-46de4300-5f38-11ea-99e8-9e62ea43141c.jpeg)

**Comment by kaizumaki** [comment]
着手します！

**Comment by kaizumaki** [comment]
@ocean3fish タイトルは変更しなくていいですか？
