### ISSUE TITLE
接触歴等不明者数の割合表示について

### ISSUE THREAD

**Issue by kackey621** [tokyo-metropolitan-gov/covid19#5043]
## 改善詳細 / Details of Improvement
- 全体に占める接触歴等不明者数の割合を表示する．
(Show the rate of untracked cases)

## スクリーンショット / Screenshot
![スクリーンショット 2020-07-17 17 55 04](https://user-images.githubusercontent.com/16284932/87768127-a76e7c80-c856-11ea-8956-e333a751ede7.png)

現在は，「新規陽性者における接触歴等不明者数」と「増加比」に関しては表示されるが，
全体に占める接触歴等不明者数が表示されていない．
報道などでよく用いられるデータの一つとなっているので，表示した方が，一つの指標になると感じる．

## 期待する見せ方・挙動 / Expected behavior
-ここの画像で表示されている増加比と同じ形式で，
全体比　　XX %   7/16の数値
と表示できると良いかと思う．

![スクリーンショット 2020-07-17 17 58 21](https://user-images.githubusercontent.com/16284932/87768457-1d72e380-c857-11ea-8b70-2928cca17571.png)

## コメント
こんにちは，最近の報道では「感染経路不明者数」を用いた報道が増えてきており，実際に都民の関心事の一つとなっています．
そのため，全体に占める感染経路不明者数の割合を表示した方が参考にしやすいと考えております．
いかがでしょうか．

**Comment by kaizumaki** [comment]
@kackey621 ご提案ありがとうございます。１点確認させてください。現在は接触歴等不明者の人数（７日間移動平均）を表示させていますが、割合も追加するというご提案内容でよろしかったでしょうか？
ご指摘のグラフは[東京都が設定しているモニタリング項目](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.html)に基づいていますので、こちらの項目を変更するには東京都の確認が必要になり、かなりのお時間いただくことになろうかと思います。

**Comment by kackey621** [comment]
@kaizumaki ご確認いただきありがとうございます。確認必要な旨承知いたしました。しかしながら、必要だと感じておりますので、このまま公式確認のフェーズへお願いしたく思います。よろしくお願いいたします。

**Comment by kaizumaki** [comment]
@kackey621 返信たいへん遅くなりまして申し訳ありません。ご提案いただいた内容について東京都に確認いたしました。
モニタリング項目の指標に関することは、東京都福祉保健局の所管であり、専門家によるモニタリング会議と連携して進めているので、変更するのは非常に難しいです。当サイトだけで判断できるものではない、との回答でした。ただ、ご意見として所管には伝えさせていただきます、とのことでした。
ご理解いただけますと幸いです。

**Comment by kaizumaki** [comment]
東京都から回答がありましたので、こちらのissueはクローズいたします。
