### ISSUE TITLE
2軸グラフ右側のフェードする方向が逆

### ISSUE THREAD

**Issue by saccho** [tokyo-metropolitan-gov/covid19#5052]
## 起こっている問題 / The Problem
- グラフを横スクロールした際に，外側に向かって横軸がフェードアウトするが，2軸グラフの場合，右側は外側に向かってフェードインしている．

## スクリーンショット / Screenshot

|macOS 10.15.5 / Chrome 83.0.4103.116|iOS 13.5.1 / Safari|
|---|---|
|<img src="https://user-images.githubusercontent.com/36199796/87850690-20400800-c92d-11ea-90d8-a286ce34f4f6.gif" width=500px>|<img src="https://user-images.githubusercontent.com/36199796/87850918-c5a7ab80-c92e-11ea-8115-a8fa6b9dfe7b.gif" width=500px>|

## 期待する見せ方・挙動 / Expected Behavior
- 2軸グラフの横軸が適切にフェードする

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページのモニタリング項目を表示
2. モニタリング項目(3)や(4)のグラフを横にスクロールする

## 動作環境・ブラウザ / Environment
- macOS 10.15.5 / Chrome 83.0.4103.116
- iOS 13.5.1 / Safari

**Comment by goki90210** [comment]
グラフの横軸マスクが左右で同じになっているからですね。

https://github.com/tokyo-metropolitan-gov/covid19/blob/66767c44433796a7208420f04986ab0d42c7f2e7/components/UntrackedRateMixedChart.vue#L56-L77
この辺りの問題のように見えますね。

**Comment by saccho** [comment]
@goki90210 ありがとうございます．修正してPR投げます．
