### ISSUE TITLE
グラフタイトル変更: 検査実施日別状況→検査実施数

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#506]
グラフタイトルを以下の通り変更

検査実施日別状況→検査実施数
![F20CAD39-20B3-4034-8984-84B958AB0C93](https://user-images.githubusercontent.com/4206675/75990695-a4728f80-5f38-11ea-8c8a-3b4cece214c7.jpeg)

**Comment by kaizumaki** [comment]
着手します！
