### ISSUE TITLE
グラフのツールチップが表示させにくい

### ISSUE THREAD

**Issue by itakumaru** [tokyo-metropolitan-gov/covid19#5062]
## 改善詳細 / Details of Improvement
ツールチップ表示の条件はグラフ要素のマウスホバーまたは押下ですが、小さくて表示させづらいときがあります。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/62002085/87937331-7f3d8280-cacf-11ea-857a-20a9ddbcc086.png)

## 期待する見せ方・挙動 / Expected behavior
- ポインタの水平位置によって表示する。
- 複合グラフでは、1つのツールチップに両方の情報を入れる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
> * 複合グラフでは、1つのツールチップに両方の情報を入れる。
こちらは、#5058 #4807 が解消したらですかね…。
文字を詰め込みすぎると枠からはみ出しそうなので。

**Comment by itakumaru** [comment]
> グラフは棒グラフだけではありません。線グラフの場合線の位置から離れた位置で表示させても意味ないですよね。

確かにそうですね！この変更は棒グラフのみを対象にするのがいいと思います。
@mcdmasterさんのおっしゃる通り、ツールチップ表示を発火する範囲を広げるというよりは、発火条件そのものを変更する形が望ましいと思います。
今考えているところでは、大まかに棒グラフの`tooltips`の`options`にプロパティ`intersection: false` `axis: x`を追加することで、グラフ上のどこをホバーしてもツールチップが表示されるようにできそうです。

**Comment by itakumaru** [comment]
棒グラフと積み上げ棒グラフのほうは実現できました。
```
tooltips: {
  position: 'nearest',
    intersect: false,
      axis: 'x',
      //同じ内容が重ねて表示されるのを防ぐ
      filter(tooltipItem) {
        return tooltipItem.datasetIndex === 1
      },
```
![image](https://user-images.githubusercontent.com/62002085/88244057-6e5a6000-cccd-11ea-8f76-a6a39c11fc4c.gif)
が、棒グラフと折れ線グラフが混ざったグラフでどうやって棒グラフのみ対応するべきか…
