### ISSUE TITLE
【Lint周りに関して】ESLint・Prettierの競合？

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#507]
1. Win10・VSCodeにてESLintとPrettierの自動修正がお互いに上手くいかないのですが、推奨設定や拡張機能との競合等の情報がありましたらご教示お願いいたします。（ちなみにVeturのFormatはdisabledです）
2. 現在のESLintの設定だと、例えば `flow.vue` の
```vue
<img
  src="/flow/sp/sp_flow_01_02@2x.png"
  alt="流行地域への渡航・居住歴がある方　ご本人か濃厚接触をした方／呼吸器症状かつ発熱37.5℃以上"
/>
```
が`eslint(no-irregular-whitespace)`に引っかかったりするのですが、これはソースコードがESLintに合うように修正されていないのでしょうか？ それともこちら側の設定ミスでしょうか？

お手数おかけいたしますが、よろしくお願いいたします。

**Comment by MaySoMusician** [comment]
導入済み拡張機能（関係ありそうなもの）
* ESLint `dbaeumer.vscode-eslint`
* Prettier - Code formatter `esbenp.prettier-vscode`
* Vetur `octref.vetur`

**Comment by MaySoMusician** [comment]
上記2番については #515 で解決するので取り下げます

**Comment by ocean3fish** [comment]
1. の自動修正が走らない問題、MacOS Sierra / VSCode 1.43.0 でも再現しました。
こちらも解決方法を見つけられずにおります。

**Comment by cheezenaan** [comment]
> Win10・VSCodeにてESLintとPrettierの自動修正がお互いに上手くいかない

vuejs/eslint-plugin-vue に挙がってる issue を参考に PR を作ってみました。
https://github.com/tokyo-metropolitan-gov/covid19/pull/1128
