### ISSUE TITLE
「新規患者に関する報告件数の推移」グラフの注釈体裁整理・外部リンク追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5070]
「新規患者に関する報告件数の推移」グラフの注釈の体裁の整理と、外部リンクの追加をお願いします。

### 注釈の体裁の整理
- 現在グラフ上にある注釈をすべてグラフ下部に移動
- 文頭の「（注）」を「・」にする
- １行目の注釈の上に「（注）」と入れる

以下のようになります。
```
（注）
・保健所から発生届が提出された日を基準とする
・医療機関等が行った検査も含む
・チャーター機帰国者、クルーズ船乗客等は含まれていない
```

### 外部リンク追加
- グラフと注釈の間に、以下の外部リンクテキストを追加する
タイトル： `届出保健所別の内訳`
URL：https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/todokedehcyouseisya.html
※URLは7/22（水）に開通します。

イメージとしては以下の画像のとおりです。
<img width="736" alt="スクリーンショット 2020-07-21 17 06 23" src="https://user-images.githubusercontent.com/14883063/88029160-971b1200-cb74-11ea-8643-ab30c4ea047e.png">

**Comment by kaizumaki** [comment]
対応します。

**Comment by Cartman0** [comment]
ちなみにこの項目って速報値ですか？それとも確定値ですか？

**Comment by kaizumaki** [comment]
@Cartman0 
こちらの項目は日々の保健所からの報告件数そのものを発表しているものなので、遡及して件数が変動することを予定しているものではありません。
これまで、[過去の報告件数を修正したこと](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/1007863.html)はありますが、これは未報告の事案があったことによります。
よって、速報値か確定値か、ということですと、確定値ということになります。

**Comment by Cartman0** [comment]
@kaizumaki さん返信ありがとうございます．

- "新規患者に関する報告件数の推移"（このグラフ）：7月16日は286人
- "モニタリング項目(4) 検査の陽性率"でのPCR検査陽性者数（グラフの深緑色）:7月16日は314人

てっきり速報値と確定値による違いかと思ってましたがこの違いは何なのでしょうか？

**Comment by kaizumaki** [comment]
@Cartman0 
ご質問について、東京都の方に回答をいただきました。

> 「新規患者に関する報告件数の推移」の陽性者数は保健所から発生届が提出された日を基準としたもの、
> 「モニタリング項目(4)」の陽性者数は検査結果の判明日を基準としたもので
> 検査結果の判明日＝保健所から発生届が提出された日となるとは限らないため、両者の数値は一致しません。

とのことです。

**Comment by Cartman0** [comment]
@kaizumaki さん問い合わせ頂いてありがとうございます．
このグラフにも回答のように（4）のような基準日の注釈を追加するのはどうでしょうか．

**Comment by kaizumaki** [comment]
@Cartman0 そうですね、注釈の追加修正は関係者内の調整に時間がかかる印象です。
いずれにせよ、こちらのissueの内容とは話題がそれますので、別途issueを立てていただけるとよいかと思います。
