### ISSUE TITLE
Lighthouseスコアの改善（パフォーマンス改善）

### ISSUE THREAD

**Issue by soutaito** [tokyo-metropolitan-gov/covid19#5075]
## 改善詳細 / Details of Improvement
- Lighthouseのスコアを改善する。主にPerformanceの数値を良くして体感速度を改善する。

## スクリーンショット / Screenshot
production環境とローカル環境だとHTTP2を使用しているかどうかなどの違いがあって評価できないので、
現状のソースをローカルでstatic generateしてnuxt serveした結果に対するLighthouseを比較の基礎とします。
![現状](https://user-images.githubusercontent.com/1763230/88142350-5254b100-cc30-11ea-8ec6-e907c5c8dbd1.png)

## 期待する見せ方・挙動 / Expected behavior
- Lighthouseのスコア改善

**Comment by kaizumaki** [comment]
こちらのコメント https://github.com/tokyo-metropolitan-gov/covid19/pull/5076#issuecomment-664072957 にあるように、パフォーマンス面ではまだまだ対応が必要なようなので、このissueは再オープンします。

**Comment by mcdmaster** [comment]
シンプルなアプローチとしては、以下の２つがすぐに思いつきます。
- コンテンツの圧縮（`gzip`, `deflate`, `brotli`）
- `HTTP/2.0` の使用

このうち、比較的簡単に実現できるコンテンツ圧縮を、[nuxt-compress](https://github.com/robcresswell/nuxt-compress) を使ってやってみました。

スクショでは、まあそれはそれは重たいローカル環境でやっているのでパフォ数値は相応に悪いのですけど、実は `nuxt-compress` を入れる前後でスコアに４倍くらいの開きがあるんですね。
そうした意味では、検討の余地ありかと
![スクリーンショット 2020-07-30 150038](https://user-images.githubusercontent.com/10361533/88886722-1051ed80-d276-11ea-8d8a-710157c491b3.png)

**Comment by kaizumaki** [comment]
@mcdmaster なるほどですね。圧縮はひとつの手かもしれないですね。ちなみにLighthouseのスコアのビフォーアフターが見たいのですが、ありますでしょうか...？

**Comment by mcdmaster** [comment]
@kaizumaki 
nuxt-compress を入れる前、ビフォーは、下のスクショをご覧ください。
パフォのスコアは、16 vs. 44 で３倍にほんの少し届かずですね。ぜひ、ご参考としていただければ
![スクリーンショット 2020-07-30 211750](https://user-images.githubusercontent.com/10361533/88922006-6fc9f080-d2aa-11ea-9b62-76c9164a442a.png)

**Comment by shgtkshruch** [comment]
#5715, #5718, #5720, #5722 で、今の段階で改善できそうな Lighthouse の警告を修正する PR を出しました。
更に改善する場合は、以下のような観点があるかと思いました。

- Chart.js でレンダリングしているグラフのアニメーションの設定
- 非同期ローディング・非同期レンダリングを導入して、First contentful paint (FCP) に必要なものを優先的に読み込む

グラフのアニメーションについては、初期の頃はそこまで重くなかったのですが、カードの数とデータの数が増えているので、初回レンダリングやタブの切替時のアニメーションが重くなってきています。
FPS も10以下になっているので、ほぼアニメーションがない状態になっているように見えます。

非同期ローディング・非同期レンダリングは、ちゃんとやればスコアが 90点近くになると思います。
画面が小さい割に多くのリソースを読み込んでいるので、PC よりもモバイルのほうが相対的に効果が高そうです。
非同期レンダリングを導入すると、スクロールするなどコンテンツを表示する必要があると判定するまでは DOM がレンダリングされないので、そちらが問題ないかどうかが判断基準の一つになると思います。

**Comment by kaizumaki** [comment]
@shgtkshruch PRありがとうございます！遅延レンダリングはぜひ導入したいですね。

**Comment by shgtkshruch** [comment]
@kaizumaki 
> 遅延レンダリングはぜひ導入したいですね。

承知しました。パフォーマンス関連の PR マージ後に実装してみます 🚀

**Comment by kaizumaki** [comment]
だいぶ改善されたので、こちらのissueはいったんクローズとします。
