### ISSUE TITLE
An Error related to dayjs Upgrade

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#5087]
[訂正あり：当初 `nuxt-i18n` 関連と勘違いしていました。`dayjs` がらみですね]
## 起こっている問題 / The Problem
- ビルド時に、ファイル `plugins/chartjs-adapter-dayjs.ts` が TS エラーを吐く

## スクリーンショット / Screenshot

![コメント 2020-07-23 095328](https://user-images.githubusercontent.com/10361533/88243201-8d0b2780-ccca-11ea-93ef-d9476485785d.png)

## 期待する見せ方・挙動 / Expected Behavior
- エラーの解消

## 起こっている問題の再現手段 / Steps to Reproduce
- `yarn dev` （または `yarn dev-no-axe`）の実行
- コンソールメッセージを確認

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster ご指摘ありがとうございます！私のローカル環境で `yarn dev` をやってみたところ、こちらのエラーは再現しないのですが、どうなんでしょう...？

**Comment by goki90210** [comment]
@mcdmaster 私の環境でも出ません。#4918 の作業の関連でnode_modulesやyarn.lockが違っていたりしませんか？

**Comment by goki90210** [comment]
@mcdmaster 今のバージョンからdayjsをアップグレードして、dayjs@1.8.30に上げたら出ましたね。

**Comment by goki90210** [comment]
@mcdmaster 
ここで報告されていたので、dayjsを1.8.29から1.8.30に上げると発生する問題で確定です。
https://github.com/iamkun/dayjs/issues/964
上記のエラーは型をstringからロケールのtypeに変更したため発生した問題のようで、dayjs@1.8.31でロールバックされる予定です。
したがって、dayjs@1.8.30には上げずに、dayjs@1.8.31のリリースを待って対応しましょう。
（ソースの修正は不要になるっぽいです。）

**Comment by mcdmaster** [comment]
りょうかいです。返答が遅くなってしまい失礼しました

**Comment by mcdmaster** [comment]
[dayjs@1.8.31](https://github.com/iamkun/dayjs/releases/tag/v1.8.31) のリリースに伴い、問題の解決が見られたと判断しました。
よって本イシューはクローズします。
