### ISSUE TITLE
グラフカードの余白調整

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#509]
## 起こっている問題 / Occurred problem
* グラフカード間の余白がデザインよりも広くなってしまっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1301149/75991381-be60a200-5f39-11ea-94f1-e875a97d695d.png)

PC版では横の余白と縦の余白は↓の様に一緒になるのが正です。

![image](https://user-images.githubusercontent.com/1301149/75991467-d89a8000-5f39-11ea-9fcf-f8db2f019bbf.png)

## 期待する見せ方・挙動 / Expected behavior
* PC：20px
* スマホ：8px

上記寸法に調整

## 動作環境・ブラウザ / Environment
* Mac Chrome
* iPhone 11 Pro
上記で確認

**Comment by shun91** [comment]
こちら対応します。
