### ISSUE TITLE
mapbox-gl のスタイルシートの読み込み処理を削除

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#5090]
## 改善詳細 / Details of Improvement
- #4848 で mapbox-gl を削除しているので、レイアウトに残っているスタイルシートを読み込むコードも削除して良さそうです

## スクリーンショット / Screenshot
https://github.com/tokyo-metropolitan-gov/covid19/blob/64155c3365a3adcef212213dd8f60aad4a131bf4/layouts/default.vue#L120-L123

## 期待する見せ方・挙動 / Expected behavior
- 上記コードが削除されること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by tokyo-citizen** [comment]
関連して[古いデータファイル](https://github.com/tokyo-metropolitan-gov/covid19/tree/development/static/tiles)も消去するのはいかがでしょうか。

**Comment by shgtkshruch** [comment]
@tokyo-citizen 
フォローありがとうございます！

https://github.com/tokyo-metropolitan-gov/covid19/blob/64155c3365a3adcef212213dd8f60aad4a131bf4/static/tiles/20200201/corona_heatmap/hourly/8/metadata.json#L11-L12

上記コードから、こちらで作られた GeoJSON のようでした。
https://github.com/mapbox/tippecanoe

mapbox 関連のコードだと思うので一緒に削除しようと思います。

**Comment by kaizumaki** [comment]
@shgtkshruch @tokyo-citizen フォローいただきありがとうございます！削除したコンポーネントまわりについてはなかなか手がまわっていないので、ご提案助かります 🙏
