### ISSUE TITLE
古いファイルのクリーンアップ

### ISSUE THREAD

**Issue by tokyo-citizen** [tokyo-metropolitan-gov/covid19#5092]
## 改善詳細 / Details of Improvement
- リポジトリ(development branch)に古いと思われるファイルが残っている

## スクリーンショット / Screenshot
- [ディレクトリ:static/](https://github.com/tokyo-metropolitan-gov/covid19/tree/development/static)
  - `static/.well-known/pki-validation/06c9242ba3a94dc1e48d8ea4ad24b59c.txt`
    - TLS証明書発行時の確認ファイルで証明書発行完了後には不要と考えられる
  - `static/confirmed-cases-table.svg`
    - 過去に存在したカードの画像ファイルで不要と考えられる
- [ディレクトリ:static/data/](https://github.com/tokyo-metropolitan-gov/covid19/tree/development/static/data)
  - `static/data/13104.csv`
    - 過去に存在したカードの人流関連データファイルで不要と考えられる
- [ディレクトリ:static/ogp/](https://github.com/tokyo-metropolitan-gov/covid19/tree/development/static/ogp)
  - `static/ogp/*`
    - development branchを除いてworkflow(OGP Builder)で最新化(git add/commit)している
    - development branchは追従していないので不要またはrelease tagを打つタイミングで再生成するのが良いと考えられる
    - 既に存在しないカードの画像ファイル(OGP関連)が残り続けていることの是非についてはご意見頂ければと思います
- [ディレクトリ:data/](https://github.com/tokyo-metropolitan-gov/covid19/tree/development/data)
  - `data/13101_daily_visitors.json`
  - `data/13104_daily_visitors.json`
    - 過去に存在したカードの人流関連データファイルで不要と考えられる
  - `data/test.json`
    - workflow(Data Builder)のテスト時に作成した中身がほぼ空のテスト用データファイルで不要と考えられる
- [ディレクトリ:dist/data/](https://github.com/tokyo-metropolitan-gov/covid19/tree/development/dist/data)
  - `dist/data/130001_tokyo_covid19_call_center.csv`
  - `dist/data/30001_tokyo_covid19_combined_telephone_advice_center.csv`
  - `dist/data/130001_tokyo_covid19_patients.csv`
    - 最新のデータは[別のディレクトリ](https://github.com/tokyo-metropolitan-gov/covid19/tree/development/static/data)を用いている
    - workflow(screenshot)でディレクトリを使っているためにCSVファイルを削除するにしても空のディレクトリ(`dist/data`)を維持する必要があると考えられる

## 期待する見せ方・挙動 / Expected behavior
- 少なくとも古いと思われるファイルが外部公開されている状態を是正する(例:[confirmed-cases-table.svg](https://stopcovid19.metro.tokyo.lg.jp/confirmed-cases-table.svg))

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nard-tech** [comment]
こちら対応します

**Comment by nard-tech** [comment]
`static/ogp/*` については削除せず残しました．
その他，https://github.com/tokyo-metropolitan-gov/covid19/issues/5092#issue-664250923 で記載されているもの以外に

* `components/SourceLink.vue`
* `utils/formatMonitoringStatus.ts`
* `data/positive_by_developed.json`

が不使用と思われるので削除しました．

**Comment by y-chan** [comment]
@nard-tech #5194 で`data/positive_by_developed.json`は使用します。

**Comment by tokyo-citizen** [comment]
@nard-tech
ご対応いただきありがとうございます。

プロダクション環境では削除は慎重にしたいところですのでOGP関連の画像ファイル
については現状のままでこのIssueをクローズという事でお願いいたします。

**Comment by tokyo-citizen** [comment]
古いOGPの画像ファイルの件に関連して、話を戻すわけではなく、記録としてです。

ご存知の方々は多いとは思いますが、下記のURIにアクセスした時の動きです。
(404の場合はこうじゃなかったはずと焦りましたが`static/ogp/tokyo-st-heatmap.png`が表示されただけというオチでした)

- [https://stopcovid19.metro.tokyo.lg.jp/ogp/tokyo-st-heatmap.png](https://stopcovid19.metro.tokyo.lg.jp/ogp/tokyo-st-heatmap.png)

<img width="912" alt="sample" src="https://user-images.githubusercontent.com/68139470/90106171-0229c400-dd82-11ea-9263-92bbed0c80af.png">

**Comment by tokyo-citizen** [comment]
私がOGP関連については削除要否を明確にできませんでしたが、その他について
不要なファイルを削除していただいたためクローズ致します。

ご対応いただきありがとうございました。
