### ISSUE TITLE
FORKED_SITES.mdに富山県版サイトを追加

### ISSUE THREAD

**Issue by Terachan0117** [tokyo-metropolitan-gov/covid19#5094]
## 改善詳細 / Details of Improvement
- FORKED_SITES.mdに富山県版サイトの追加をお願いいたします。

都道府県名：富山県
公開サイト：https://stopcovid19-toyama.netlify.app/
運営者：有志（**富山県公認**）
プロジェクト：[Terachan0117/covid19-toyama](https://github.com/Terachan0117/covid19-toyama)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HisashiNishino** [comment]
対応させてください。
手順や環境に慣れていないので、不備などあればご指摘くださいませ。
