### ISSUE TITLE
一度ウィンドウ幅を縮めるとカードのレイアウトがおかしい

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#51]
縮めたときに1列になるのは良いのだけど、それがなかなか2列にもどらない

![55b51e18ceb1f8a9570588329414a41c](https://user-images.githubusercontent.com/16509/75620226-94218400-5bc9-11ea-99bb-c7a7032fc869.gif)

**Comment by osoken** [comment]
これ、chartjsのコンポーネントにmax-widthが設定されていない？のが原因かもしれません。chartjsの再描画より早くウィンドウサイズ広げると、2-columnに戻ります 笑

**Comment by halsk** [comment]
他の人ができるかもしれないので、一旦 @osoken さんのアサイン外しておきました。チャートの方に注力いただければ！

**Comment by osoken** [comment]
#96 の対応過程で自然と解消されると思います！

**Comment by halsk** [comment]
解消されていたのでクローズします

**Comment by halsk** [comment]
うーむ。この Issue がいつの間にか再現するようになってますね
