### ISSUE TITLE
更新日時をカードの下固定にする

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#512]
## 改善詳細 / Improve details
* 更新日時がグラフのカードごとにバラバラになっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1301149/75992135-e0a6ef80-5f3a-11ea-82b9-8f3b75621b71.png)

## 期待する見せ方・挙動 / Expected behavior
* カードの補足情報という見せ方（高さの高いカードがなっている状態に統一する）

![image](https://user-images.githubusercontent.com/1301149/75992283-15b34200-5f3b-11ea-856d-5b1af87b9e26.png)
を統一するために、カードの下固定にする

**Comment by imaichiyyy** [comment]
こちら対応します！

**Comment by imaichiyyy** [comment]
@shgtkshruch 

なるほど！  
承知しました。
ただ #516 も対応していたのですが、おそらく #458 で対応いただいたスタイルと兼ね合いが生じる部分かと思いますので、いったん私が対応したPRはどちらもクローズしますね。
