### ISSUE TITLE
@nuxtjs/eslint-config-typescript@3.0.0の適用

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#5126]
## 改善詳細 / Details of Improvement
- ESLint@7に対応した、@nuxtjs/eslint-config-typescript@3.0.0がリリースされたため、アップグレードしたい。
詳細：
https://github.com/nuxt/eslint-config/releases
https://github.com/typescript-eslint/typescript-eslint/releases/
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0
メジャーアップデートはRenovateの対象外とのことなので、手動で対応したいです。
- 関連した議論は#4918(#5061), #5038, #3841(#5068)にもあります。

なお、#4918(#5061)とは別の対応でお願いします。

## 期待する見せ方・挙動 / Expected behavior
#5123 適応後の状態で `yarn add -D @nuxtjs/eslint-config @nuxtjs/eslint-config-typescript` を実行し、
* @nuxtjs/eslint-config@3.1.0
* @nuxtjs/eslint-config-typescript@3.0.0

にアップグレードします。

## 動作環境・ブラウザ / Environment
- なし

**Comment by kaizumaki** [comment]
@goki90210 フォローありがとうございます！ #5137 でRenovateがPRを立てていますので、そちらをマージするということでいいでしょうか？

**Comment by goki90210** [comment]
@kaizumaki 
> #5137 でRenovateがPRを立てていますので、そちらをマージするということでいいでしょうか？

メジャーアップデートも行うんですね。
わかりました。

**Comment by kaizumaki** [comment]
@goki90210 ありがとうございます。 #5137 をマージしましたので、こちらのissueはクローズしますね。
Renovateの運用については別途検討したいと思っています。
