### ISSUE TITLE
スマホ表示のグラフ内の余白の調整

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#516]
## 改善詳細 / Improve details
* スマホ表示時にグラフの中の余白が非常に広い。PCと違いカードの高さをそろえる処理は不要のため、余白をつめる

## スクリーンショット / Screenshot

<img src=https://user-images.githubusercontent.com/1301149/75993449-cff77900-5f3c-11ea-9f82-69ceeded638e.png width=50%>

## 期待する見せ方・挙動 / Expected behavior
* スマホ表示時のみ、カード内のグラフの上下の余白を `24px` に設定
<img src=https://user-images.githubusercontent.com/1301149/75993355-b22a1400-5f3c-11ea-9372-f680ca65a15e.png width=50%>

↓デザインデータ
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=151%3A439

## 動作環境・ブラウザ / Environment
*

**Comment by imaichiyyy** [comment]
#512 と合わせて対応しますー

**Comment by imaichiyyy** [comment]
#512 と同時に対応を行っていましたが、 #458 で別の方が対応いただいた部分とスタイルに兼ね合いが生じそうなためこちらの対応は #458 がマージ後に行ったほうが良いかと思われます。

申し訳ないのですが、上記の理由からいったんアサインはずれさせていただきます。

**Comment by ocean3fish** [comment]
現状解決していそうなことが確認できたため、本件はクローズさせて頂きます。
![5446D843-540A-4FE0-9B10-50B3E9F33741](https://user-images.githubusercontent.com/4206675/76676864-0010dd00-660b-11ea-98e9-c95e83b97240.jpeg)
