### ISSUE TITLE
感染者数についての質問

### ISSUE THREAD

**Issue by tamitami5c** [tokyo-metropolitan-gov/covid19#5161]
感染者数について少しお尋ねしたいことがあったのですが、どこで聞けばよいのかわからなかったので、ここで質問させてください。

感染者数は1つではなく、下の異なる基準で計測した3つの感染者数があるという認識でいいのでしょうか？

1. [保健所から発生届が提出された日を基準としたもの](https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases/)
2. [検査により陽性であることを医師が確認した日別（確定日別）のもの](https://stopcovid19.metro.tokyo.lg.jp/cards/positive-number-by-diagnosed-date/)
3. [検査結果の判明日を基準としたもの](https://stopcovid19.metro.tokyo.lg.jp/cards/positive-rate/)

また、(1)～(3)の時間的な位置は、下の図のような位置でいいのでしょうか？
画像中の左側と右側が対応しています。

![corona-kakikomi](https://user-images.githubusercontent.com/68597117/89038379-3319fa00-d37b-11ea-84e2-64d08cf784c8.png)
<https://www.nikkei.com/article/DGXMZO62014130Y0A720C2EA2000/> にある公表までの流れの図をお借りしています。

**Comment by mcdmaster** [comment]
こんにちは。私はここではあくまで一介の技術者で、都の方針・指針を代弁する立場にいません。
そもそも、都民でさえありません。（アイコンを目を凝らしてご覧ください）
ですので、私のコメントはあくまでいち技術者の意見、たわ言の類と捉えていただけるとありがたいです、と前振り（ディスクレーマーともいう）をしておきます。

まず、本プロジェクトの「成果物」である [COVID-19 対策サイト](https://stopcovid19.metro.tokyo.lg.jp/)に「感染者数」なる言葉は一度も出てこない、ということは確認されましたでしょうか？
その前提に基づけば、かならずしも日経新聞さんの記事が正確を期したものかどうか、私としては何とも申し上げられません。

さらに私見を加えると、「感染者」、英語で言う The Infected という表現は、個人の印象でどうにでもなる恣意的な要素を含意すると思っています。たとえば、いわゆる「夜の街」に行った人が「お前、感染者じゃないか？」というふうに決めつけて言われかねないということです。
一方で、このサイトでも使われている「陽性者」、英語で言う The Positive という表現は、検査を経て判断された、すなわち専門家という第三者の判断や評価を経たという含意があるので、より適切というのが私の考えです。

まずは「感染者数」という言葉遣いへの指摘をさせていただいたうえで、数値の捉え方は、「感染者数」を「陽性者数」に置き換えたと仮定しつつ、時間の許す範囲で別コメントをできればと存じます

**Comment by kaizumaki** [comment]
@tamitami5c こんにちは。運営です。こちらのissueの内容はご質問ということでよろしかったでしょうか？
内容からして、正確な回答をするためにも東京都への確認が必要かと思います。
issueでは基本的に当サイトの実装に関する提案や質問を受け付けておりまして、その中でも東京都に確認が必要なものについては、検討するのにお時間をいただいています。いままでの経験上、回答を得るのにだいたい１ヶ月以上かかることがほとんどです。
こちらのご質問の内容でしたら、たぶん直接東京都にお電話されたほうが早いと思います。お問い合わせ先は以下に一覧があります。
https://stopcovid19.metro.tokyo.lg.jp/contacts
内容からすると、政策企画局が一番近いでしょうか。

以上を踏まえた上で、私の個人的な見解を書きます。
グラフや表については、それぞれに書かれている注釈がすべてです。
そして、「モニタリング項目(4)」の注釈には「速報値として公表するものであり、後日確定データとして修正される場合がある」とあります。
ですので、日経新聞さんの図に単純に時系列であてはめるのは難しいかなあという印象です。

**Comment by tamitami5c** [comment]
@mcdmaster 
コメントありがとうございます。
確認してみましたが、確かにサイトの方では感染者数という言葉はなく、陽性の方で統一されているのですね。
感染者数と陽性者数を同じ意味と考えていおり、あまり深く考えずに使っていました。
質問の場合ですと陽性者とした方が適切ですね。

**Comment by tamitami5c** [comment]
@kaizumaki 
コメントありがとうございます。

> そして、「モニタリング項目(4)」の注釈には「速報値として公表するものであり、後日確定データとして修正される場合がある」とあります。
> ですので、日経新聞さんの図に単純に時系列であてはめるのは難しいかなあという印象です。

「PCRセンターで検査」＝＞「医師が確認」＝＞「都が集計、公表」
という時系列は変わることはないと思っているので、それぞれの部分に3つの基準を当てはめた
(3) ＝＞(2)＝＞(1)
という順序も、たとえ修正が入ったとしても、時系列が逆転することはないと思っています。
何か間違えているかもしれませんが。。

都に連絡してみるのがいいみたいですね。
連絡してみようと思います。
ありがとうございました 。
