### ISSUE TITLE
8月1日分を反映した感染者報告データで、7月13日分の報告内容の一部が消えている

### ISSUE THREAD

**Issue by dgakane** [tokyo-metropolitan-gov/covid19#5169]
## 起こっている問題 / The Problem
- 8/1分が反映された 130001_tokyo_covid19_patients.csv で7月13日のデータに漏れがあります。
- 昨日までは7/13の報告数は119件でしたが、8/1の更新分では19件しか存在しません。

## スクリーンショット / Screenshot

```
7731,130001,東京都,,2020-07-12,日,,都内,90代,男性,,,,,,
7829,130001,東京都,,2020-07-13,月,,都外,20代,男性,,,,,,1
7839,130001,東京都,,2020-07-13,月,,都外,30代,男性,,,,,,1
7827,130001,東京都,,2020-07-13,月,,都内,20代,女性,,,,,,1
7835,130001,東京都,,2020-07-13,月,,都内,20代,女性,,,,,,
7838,130001,東京都,,2020-07-13,月,,都内,20代,女性,,,,,,1
7842,130001,東京都,,2020-07-13,月,,都内,20代,女性,,,,,,
7824,130001,東京都,,2020-07-13,月,,都内,20代,男性,,,,,,
7828,130001,東京都,,2020-07-13,月,,都内,20代,男性,,,,,,
7830,130001,東京都,,2020-07-13,月,,都内,20代,男性,,,,,,
7831,130001,東京都,,2020-07-13,月,,都内,20代,男性,,,,,,1
7833,130001,東京都,,2020-07-13,月,,都内,20代,男性,,,,,,
7834,130001,東京都,,2020-07-13,月,,都内,20代,男性,,,,,,
7826,130001,東京都,,2020-07-13,月,,都内,30代,女性,,,,,,
7837,130001,東京都,,2020-07-13,月,,都内,30代,男性,,,,,,
7840,130001,東京都,,2020-07-13,月,,都内,40代,女性,,,,,,
7832,130001,東京都,,2020-07-13,月,,都内,40代,男性,,,,,,1
7836,130001,東京都,,2020-07-13,月,,都内,40代,男性,,,,,,
7825,130001,東京都,,2020-07-13,月,,都内,50代,男性,,,,,,
7841,130001,東京都,,2020-07-13,月,,都内,70代,男性,,,,,,
7865,130001,東京都,,2020-07-14,火,,都外,10代,女性,,,,,,1
```

![スクリーンショット 2020-08-02 10 19 03](https://user-images.githubusercontent.com/12721248/89113937-0fa59b00-d4b2-11ea-98b5-6ec4074cad55.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正しい報告内容（119件）を表示する

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページにアクセスし、報告件数のグラフを見る
2. もしくは、130001_tokyo_covid19_patients.csv の7/13の報告を確認する

## 動作環境・ブラウザ / Environment
- macOS 
- Safari

**Comment by kaizumaki** [comment]
@dgakane ご指摘ありがとうございます！こちらの件、調査いたしますのでしばらくお待ちください。

**Comment by dgakane** [comment]
@kaizumaki いつもご尽力ありがとうございます。よろしくお願いいたします。

**Comment by kaizumaki** [comment]
@dgakane お待たせしまして申し訳ありません。東京都の担当に報告しましたところ、8月1日更新の際のミスだったことが判明しました。元データを修正し、[こちら](https://github.com/tokyo-metropolitan-gov/covid19/compare/5ae89aa26502...8a7fd90a614e) のとおり反映いたしました。オープンデータ「130001_tokyo_covid19_patients.csv」も追って修正される予定です。
ご指摘いただきありがとうございました。感謝です。

**Comment by kaizumaki** [comment]
> オープンデータ「130001_tokyo_covid19_patients.csv」も追って修正される予定です。

修正されました。

**Comment by dgakane** [comment]
@kaizumaki グラフ、CSVファイル共に、修正されたことを確認しました。ご対応ありがとうございました！
