### ISSUE TITLE
モニタリング項目(3)の７日間移動平均のプロットスケールが目盛りと不一致

### ISSUE THREAD

**Issue by zfukuoka** [tokyo-metropolitan-gov/covid19#5171]
## 起こっている問題 / The Problem
- モニタリング項目(3)の７日間の移動平均の人数を示す破線のスケールがグラフ右にある縦線の人数を示す目盛りのスケールが一致していない
  - 8/1の事例で７日間移動平均の人数は190.0人であり、グラフの右にある縦線の目盛りに合わせると300人くらいを指しており不具合に見える
  - 一方同じ8/1の事例で接触歴等不明者数は305人であり、グラフの右にある縦線の目盛りに合わせると300人くらいを指しており正常動作に見える

## スクリーンショット / Screenshot
![MonitoringItem-3_Screenshots_20200802](https://user-images.githubusercontent.com/19209858/89118527-3f1fcc00-d4e1-11ea-9f8e-8257b938907c.png)

## 期待する見せ方・挙動 / Expected Behavior
- 棒グラフ（新規感染者数）と破線（７日間平均の人数）は共に人数を指しているので、同じスケールで表示し、目盛りと一致する

## 起こっている問題の再現手段 / Steps to Reproduce
https://stopcovid19.metro.tokyo.lg.jp/ をウェブブラウザで開く

## 動作環境・ブラウザ / Environment
- Windows
- Chrome 84.0.4147.105 / Firefox 79.0

**Comment by tokyo-citizen** [comment]
接触歴等不明者数（７日間平均の人数）のグラフ描画時におけるy-axis指定が違っている気がします。
(現状は左側のy-axis(単位は%)を指定、正しくは右側のy-axis(単位は人)を指定)

以下はオプショナルな話です。

さらに可能であれば、主観的かもしれませんが、接触歴等不明者数のカードでは左側のy-axisの
単位は「人」で右側のy-axisの単位は「%」になっている方が、他のカードとの流れでの視線の
移動と思考の切り替えが統一されて、ある程度理解がスムーズになる気がします。
(他のカードは左側のy-axisの単位は「人」または「件」を指定、ただし都営地下鉄の利用者数の
推移(%)ですがそれは見なかったことに...)

さらに細かいことを言うと、カード上部で値を示す場合に多値の場合は、1行目が「人」、2行目が
「%」に統一されていると、複雑なモニタリング項目も少しだけスッと入ってくる気がしますが、
これは諦めどころかもしれません。(具体的には検査の陽性率のカードが該当)

**Comment by kaizumaki** [comment]
@zfukuoka ご指摘ありがとうございます！たしかにおかしいですね。
@tokyo-citizen フォローありがとうございます。

こちら私のほうで対応しますね。
> 左側のy-axisの単位は「人」で右側のy-axisの単位は「%」になっている方が、

これは私もそのとおりだと思います。

> さらに細かいことを言うと、カード上部で値を示す場合に多値の場合は、1行目が「人」、2行目が
> 「%」に統一されていると、複雑なモニタリング項目も少しだけスッと入ってくる気がしますが、
> これは諦めどころかもしれません。(具体的には検査の陽性率のカードが該当)

項目の順番については、[元になっている東京都のモニタリング項目](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.html)に合わせているので、変更するのは容易ではなさそうです 😅

**Comment by zfukuoka** [comment]
@tokyo-citizen 現象のみから原因の推測および、期待する見せ方に対してのフォロー、感謝いたします。

@kaizumaki 現象の確認ありがとうございます。ご対応、お願いいたします。
