### ISSUE TITLE
flowのprint画面における翻訳(en)を改善する

### ISSUE THREAD

**Issue by tokyo-citizen** [tokyo-metropolitan-gov/covid19#5176]
## 改善詳細 / Details of Improvement
- flowのprint画面において「対策サイト」の翻訳(en)が「COVID-19」になっている

## スクリーンショット / Screenshot
<img width="912" alt="sample" src="https://user-images.githubusercontent.com/68139470/89148728-9a12fb00-d595-11ea-9f90-6b252e6997f2.png">

## 期待する見せ方・挙動 / Expected behavior
- Transifexで以下のように翻訳(en)を修正する
```diff
--- assets/locales/en.json.orig	2020-08-03 14:23:11.000000000 +0900
+++ assets/locales/en.json	2020-08-03 14:24:00.000000000 +0900
@@ -133,7 +133,7 @@
   "東京都": "Tokyo Metropolitan Government",
   "新型コロナウイルス感染症": " COVID-19",
   "menu/新型コロナウイルス感染症": "COVID-19",
-  "対策サイト": "COVID-19",
+  "対策サイト": "The Information website",
   "menu/対策サイト": "The Information website",
   "最終更新": "Last update",
   "注釈": " This is a provisional translation. Please be aware that there may be mistranslations.",

```

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
ありがとうございます！ 翻訳チームに修正を依頼し #5188 にて取り込まれました
開発版ですがこちらで確認可能です https://dev-covid19-tokyo.netlify.app/en/print/flow/

本番環境については次回リリース時に反映される予定になります

---

また別件ですが `menu/新型コロナウイルス感染症` `menu/対策サイト` は現在使用していない（ `新型コロナウィルス＜改行＞感染症対策サイト` だったときの名残り）のでこちらの削除も後々行うことになると思います（メモ）

**Comment by MaySoMusician** [comment]
ひとまず次回リリース待ちになります。また何かありましたらre-openしてください～

**Comment by tokyo-citizen** [comment]
翻訳チームの皆様含めてご対応いただきありがとうございました！
