### ISSUE TITLE
発症日別による陽性者数の推移グラフ[新規実装]

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5194]
「発症日別による陽性者数の推移」グラフが追加になります。
こちらは #4999 で @tokyo-citizen さんが要望を上げてくれていました。ありがとうございます！

**なるはやの案件です。8/11にはリリースする予定です。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいていただけると助かります。**

## カードのパーマリンク名
「新規患者に関する報告件数の推移」カードからこちらの新規実装グラフカードにリンクを貼りますので（別issueで対応します）、以下をパーマリンク名としておいてください。
`positive-number-by-developed-date` 

## グラフ
- 単純棒グラフ
  - データ： `positive_by_developed.json` の `developed_date` （日付）、 `count` （値）
  - 色： `#00a040` (surfaceStyleB)
  - `TimeBarChart.vue` の実装に準じます

## テーブル
ラベル名は以下です。
|日付|発症日別による陽性者数の推移（日別）|発症日別による陽性者数の推移（累計）|
|---|---|---|
|〇月〇日|（数値）|（数値）|

## タイトル実装イメージ
※日付部分はダミーです。日付フォーマットは現在のものに準じます。

### 日別スイッチがONのとき
![日別ON時タイトル](https://user-images.githubusercontent.com/14883063/89359763-84224900-d701-11ea-84a5-49e9fab66731.jpg)

上記イメージのテキスト部分（「確定日別による陽性者数の推移」グラフのスタイルに準じます）
```
〇月〇日 日別値（現在判明している人数であり、後日修正される場合がある）
```

### 累計スイッチがONのとき
![累計ON時タイトル](https://user-images.githubusercontent.com/14883063/89359786-90a6a180-d701-11ea-9a06-f2980d6cafec.jpg)

  - 「発症日不明者」のデータ： `positive_by_developed.json` の `unknown_count` キー
（「発症日不明者」は日別推移の数字が取れないため、最新の数値のみしかデータがありません。）

## 注釈
グラフの下部に配置します。
```
（注）
　・各保健所から報告があった患者の発生情報を、発症日別に整理したものである
　・発症日不明者（検査結果が陽性であっても症状がない、発症日を覚えていないなど）はグラフから除いている
```

## 配置
「その他参考指標」タブのグループの３番目（「陽性患者数（区市町村別）」と「確定日別による陽性者数の推移」の間）に配置します。
さらに「検査実施件数」カードで区切ります。
「その他参考指標」グラフ配置イメージはこちら。
![その他参考指標グラフ配置](https://user-images.githubusercontent.com/14883063/89359902-de230e80-d701-11ea-9c5d-39f75e598c0e.png)

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by y-chan** [comment]
対応します

**Comment by kaizumaki** [comment]
@y-chan ありがとうございます！よろしくお願いします！
