### ISSUE TITLE
新型コロナウイルス感染症が心配な方へのページタイトルサイズ調整

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#520]
## 起こっている問題 / Occurred problem
* [新型コロナウイルス感染症が心配な方へ](https://stg-covid19-tokyo.netlify.com/flow)のタイトルフォントサイズが大きい

## スクリーンショット / Screenshot

<img src=https://user-images.githubusercontent.com/1301149/75993588-0cc37000-5f3d-11ea-9ae3-ee1dd6067b36.png width=50%>

## 期待する見せ方・挙動 / Expected behavior
* 20pxになるように調整

<img src=https://user-images.githubusercontent.com/1301149/75994148-dafed900-5f3d-11ea-9553-3818c90596f0.png width=50%>

## 起こっている問題の再現手段 / Steps to reproduce
1. スマホで[新型コロナウイルス感染症が心配な方へ](https://stg-covid19-tokyo.netlify.com/flow)を閲覧

## 動作環境・ブラウザ / Environment
* iPhone 11 Pro

**Comment by kawoka** [comment]
@mikkame 
お世話になっております。こちらissueのPR、rebaseミスしてしまい一旦closeしてしまったのですが、 https://github.com/tokyo-metropolitan-gov/covid19/issues/576 こちらの対応を待った方がよいでしょうか。
bugのため対応すべきでしたら再度PR作らせていただきたく思います！

**Comment by kawoka** [comment]
@saladdays 
こちらの問題ですが、issueタイトルの新型コロナウイルス感染症が心配な方へのページ以外のページでもおこっているようです。
タイトルのページは  #576 の関係で着手は確認してからがよいと思うのですが、他のページは対応できそうですので対応してよいでしょうか？
よろしくおねがいいたします。

<img width="315" alt="スクリーンショット 2020-03-07 09 49 44" src="https://user-images.githubusercontent.com/4666330/76132975-1b06ae80-6059-11ea-823d-96a18302c811.png">
<img width="311" alt="スクリーンショット 2020-03-07 09 49 13" src="https://user-images.githubusercontent.com/4666330/76132977-1d690880-6059-11ea-99a7-6c2257455a00.png">
<img width="314" alt="スクリーンショット 2020-03-07 09 48 53" src="https://user-images.githubusercontent.com/4666330/76132978-1e019f00-6059-11ea-927f-23c7d1922304.png">

**Comment by halsk** [comment]
@kawoka さん、まだこのバグが解消されていないようであれば、/flow 以外のページは対応できると思いますので手掛けていただいても大丈夫かと思います。

**Comment by kawoka** [comment]
@halsk さん、ご確認ありがとうございます！
#520 で/flow以外のページを対応完了しております！
しかし、i18n対応、ts化対応などと競合しそうな感じがしております。

適時コンフリクト解消していきますので、優先順位的に大丈夫なタイミングでマージしていただければと思います！ :bow:
よろしくお願いします！

**Comment by kawokas** [comment]
@halsk さん、i18n、ts化のご対応ありがとうございました！ 😄 
ともにマージされたようでしたので、 #658 のプルリクエストのコンフリクト解消しております！
お忙しいところ大変恐縮ですが、お手隙でご確認いただけると幸いです :bow:
よろしくおねがいします！
