### ISSUE TITLE
「陽性者」への用語の統一

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5202]
「陽性者」「新規患者」「陽性患者」と用語の表記ゆれが起こってしまっているため、これらを「陽性者」へ統一します。

### 「陽性患者の属性」カード
- タイトルを `陽性者の属性` に変更

### 「陽性患者数（区市町村別）」カード
- タイトルを `陽性者数（区市町村別）` に変更
- 表見出し「陽性患者数」を `陽性者数` に変更
- 注釈「前日までに発生した患者数の累計値」を `前日までに報告された陽性者数の累計値` に変更
※注釈は以下の体裁にして、**表の下部に移動**します。
```
（注）
・前日までに報告された陽性者数の累計値
・チャーター機帰国者、クルーズ船乗客等は含まれていない
```

**Comment by tokyo-citizen** [comment]
細かい話で申し訳ないですが、「陽性患者の属性」カードの注釈を修正する際には、
テーブルの「退院※」を「退院」に変更する修正を含めた方がいいと思います。
(このカードの注釈はテーブルの「※」から注釈に飛ばす発想で実装されていたのですね)

<img width="484" alt="sample" src="https://user-images.githubusercontent.com/68139470/89493568-6e8b4d00-d7ef-11ea-8c94-3b4c87c53b5a.png">

**Comment by tokyo-citizen** [comment]
変更仕様には「陽性患者の属性」カードの注釈変更は含まれていませんでしたね。
失礼しました。

**Comment by yuu26jp** [comment]
対応します。
