### ISSUE TITLE
確定日別による陽性者数の推移グラフ注釈の修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5203]
「確定日別による陽性者数の推移」グラフの注釈を以下にように修正します（ #5194 で実装される「発症日別による陽性者数の推移」グラフと表現を揃えるためです）。

修正前：`患者発生の動向をより正確に分析するため、各保健所から報告があった患者の発生情報を、検査により陽性であることを医師が確認した日別（確定日別）に整理したものである`
↓
修正後：`各保健所から報告があった患者の発生情報を、検査により陽性であることを医師が確認した日別（確定日別）に整理したものである`

**Comment by Murayu0225** [comment]
やります。
