### ISSUE TITLE
カードによって注釈の字下げスタイルの揺れがある

### ISSUE THREAD

**Issue by tokyo-citizen** [tokyo-metropolitan-gov/covid19#5204]
## 改善詳細 / Details of Improvement
- 都内の最新感染動向のカードによって注釈の字下げスタイルの揺れ(字下げされない)があります

## スクリーンショット / Screenshot
<img width="912" alt="sample" src="https://user-images.githubusercontent.com/68139470/89480968-aa171e80-d7d1-11ea-8d64-723a22092d38.png">

## 期待する見せ方・挙動 / Expected behavior
- 字下げに問題があるカードでの指定
  - モニタリング項目(1) 新規陽性者数 (MonitoringConfirmedCasesNumberCard.vue)
  - モニタリング項目(6) 入院患者数 (HospitalizedNumberCard.vue)
  - モニタリング項目(7) 重症患者数 (SevereCaseCard.vue)
```
        <template v-slot:additionalDescription>
          <ul class="ListStyleNone">
            <li>
              {{ $t('（注）') }}
              <ul>
                <li>
```

- 多くのカードでの指定
```
        <template v-slot:additionalDescription>
          <span>{{ $t('（注）') }}</span>
          <ul>
            <li>
```

- Issue:カードによって注釈の形式と位置の揺れがある(#4996)の対応方針に依存するため保留
  - 陽性患者の属性 (ConfirmedCasesDetailsCard.vue)
  - 陽性患者数（区市町村別） (ConfirmedCasesByMunicipalitiesCard.vue)
  - 都営地下鉄の利用者数の推移 (MetroCard.vue)
  - 都庁来庁者数の推移 (AgencyCard.vue)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@tokyo-citizen ご指摘ありがとうございます！
おっしゃるとおりでして、以下のカードについては修正していただけると助かります。

> * 字下げに問題があるカードでの指定
>   
>   * モニタリング項目(1) 新規陽性者数 (MonitoringConfirmedCasesNumberCard.vue)
>   * モニタリング項目(6) 入院患者数 (HospitalizedNumberCard.vue)
>   * モニタリング項目(7) 重症患者数 (SevereCaseCard.vue)

**Comment by jSm449g4d** [comment]
修正してみました
