### ISSUE TITLE
ツールチップに日付表記の揺れがある

### ISSUE THREAD

**Issue by tokyo-citizen** [tokyo-metropolitan-gov/covid19#5208]
## 改善詳細 / Details of Improvement
- グラフのツールチップにおける日付表示形式が「M月D日」「M/D」「YYYY-MM-DD」と混在しています

## スクリーンショット / Screenshot
- 現在のグラフのツールチップにおける日付表記を一覧にします(NULLは該当する項目が存在しないことを表しています)

|カード|ツールチップの日付表記|
|:---|:---|
|検査陽性者の状況|NULL|
|新規患者に関する報告件数の推移|M月D日|
|モニタリング項目|NULL|
|モニタリング項目(1)新規陽性者数|M/D|
|モニタリング項目(2)#7119における発熱等相談件数|M/D|
|モニタリング項目(3)新規陽性者における接触歴等不明者数|M/D|
|モニタリング項目(4)検査の陽性率|M月D日|
|モニタリング項目(5)救急医療の東京ルールの適用件数|M/D|
|モニタリング項目(6)入院患者数|YYYY-MM-DD|
|モニタリング項目(7)重症患者数|YYYY-MM-DD|
|陽性患者の属性|NULL|
|陽性患者数（区市町村別）|NULL|
|確定日別による陽性者数の推移|M月D日|
|検査実施件数|M月D日|
|受診相談窓口における相談件数|M/D|
|新型コロナコールセンター相談件数|M月D日|
|都営地下鉄の利用者数の推移|M月D日|
|都庁来庁者数の推移|M月D日|

## 期待する見せ方・挙動 / Expected behavior
- 日付表示形式を「M月D日」に統一するのがよいと思います

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by jSm449g4d** [comment]
修正してみました
