### ISSUE TITLE
検査の陽性率の表をcsvファイルでも公開して欲しい

### ISSUE THREAD

**Issue by standby24x7** [tokyo-metropolitan-gov/covid19#5217]
## 改善詳細 / Details of Improvement
モニタリング項目(4) 　検査の陽性率　の中で
「テーブルを表示」をクリックすると見ることが出来る表の
データを別のプログラムからも使用できるようなフォーマットで
公開する仕組みを追加していただきたい。

## 現在の状態 ## /  Current format
「テーブルを表示」をクリックすると表が表示される。
日付が新しい物が上に追加されている。
2/15-5/12 において、データがない項目は空白となっているが、
csv (例 カンマ区切り)などではないので、カット&ペーストした
データをそのまま使用するわけにはいかない。

Firefox (version 79)だと、この表をコピペできない。
Google Chrome (84.0.4147.105 )であれば、この表をコピペできる。

## 期待する見せ方・挙動 / Expected behavior
CSVフォーマットのファイルがダウンロードできるようなリンクをwebページに追加する。
CSVファイルでは、日付は最下行に新しい日付が追加されるように改める。
日付のフォーマットを 2020-08-01 などのようなフォーマットとする(RFC-3339)
2/15-5/12 におけるデータがないカラムはNaN とする。
データとデータの区切りはカンマ区切りとする。
データの文字コードはUTF-8とする。

## 動作環境・ブラウザ / Environment
- Linux  (Fedora 32)
- Chrome 84.0.4147.105  / Firefox 79

**Comment by kaizumaki** [comment]
@standby24x7 ご提案ありがとうございます。こちらは東京都の確認が必要になりますので、しばらくお待ちいただけますようお願いいたします。
１点確認なんですが、csvで提供して欲しいのはモニタリング項目(4)のみということでしょうか？

**Comment by kaizumaki** [comment]
@standby24x7 反応がたいへん遅くなりました。ご提案いただいた陽性率のデータが東京都オープンデータカタログサイトでオープンデータとして公開されました。今後はこちらをご活用いただけますと幸いです。

- 陽性率：モニタリング項目(4)
130001_tokyo_covid19_positivity_rate_in_testing.csv
https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000088

こちらのissueはクローズさせていただきます。またご意見あればお寄せください！
