### ISSUE TITLE
翻訳(en)にいわゆるASCII以外が含まれている

### ISSUE THREAD

**Issue by ghost** [tokyo-metropolitan-gov/covid19#5218]
## 改善詳細 / Details of Improvement
- 翻訳(en)にいわゆるASCII以外が含まれています(ただし一部例外あり)

## スクリーンショット / Screenshot
- 以下のように確認しました
   - 簡易的に`jq '.[]' assets/locales/en.json | hoge | LANG=C grep -v '^[[:cntrl:][:print:]]*$'`のような雰囲気で翻訳(en)を抽出しました
   - 現在は利用されていない翻訳キーを可能な限り除外しました
   - キャラクタの範囲のみに着目したもので翻訳内容に踏み込んでいません

- `※`(REFERENCE MARK) --> `*`
  "※土・日・祝日を除く庁舎開庁日の1週間累計数": "※Cumulative of visitors to Tokyo Government Office Tower in public day (on weekdays)",
  "※死亡退院を含む": "※ including leaving hospital for passing away",
- `“”`(LEFT DOUBLE QUOTATION MARK/RIGHT DOUBLE QUOTATION MARK) --> `\"`
  "TOKYOおはようスクール": "TOKYO”OHAYO”SCHOOL",
  "退院等（療養期間経過を含む）": "“Discharged,etc.” (including recuperation period)",
  "東京アラート発動中": "A “Tokyo Alert” has been issued.",
  "東京アラート": "“Tokyo Alert”",
  "東京都では、都内の「感染状況」と「医療提供体制」を2つの柱として7つのモニタリング項目を設定しています。": "In the Tokyo Metropolitan Government, there are 7 items being monitored, based on the two core pillars of ”Infection Trends in Tokyo\" and ”Medical System Provisions”.",
  "感染状況・医療提供体制の分析": "Analysis of ”The Infection trends in Tokyo\" and ”Medical System Provisions”.",
- `　`(IDEOGRAPHIC SPACE) --> trailing whitespaceなので削除 (?)
  "新型コロナ受診相談窓口、またはかかりつけ医によって新型コロナ外来（帰国者・接触者外来）またはPCR検査センターの受診が必要だと判断された方": "If you are asked by The Tokyo COVID-19 Consultation Hotline to visitOutpatient Facilities for Returnees and Potential Contact Persons or the PCR Test Center　",
  "息苦しさ（呼吸困難）、強いだるさ（倦怠感）、高熱等の{majorSymptom}がある": "{majorSymptom} such as shortness of breath, severe sense of fatigue, or high fever　",
- `…`(HORIZONTAL ELLIPSIS)  --> `...` (?)
  "テレワーク・時差出勤などスムーズビズの取組は、新型コロナウイルス感染症の対策としても効果的です。感染症対策として、東京2020大会時の交通混雑緩和に向けた取組の前倒しをお願いします。": "\"Smooth Biz\" initiatives such as \"WFH\", \"Going to work later than usual\",etc…, are also effective against COVID-19. For preventing the spread of COVID-19, we need your help to take measures in advance of the Tokyo Olympic Games to avoid transportation congestion.",
- `＃`(FULLWIDTH NUMBER SIGN) --> `#`
  "「＃7119」：急病やけがの際に、緊急受診の必要性や診察可能な医療機関をアドバイスする電話相談窓口": "「＃7119」: In case of sudden illness or injury, there is a telephone consultation service that advises both the necessity of emergency consultation, and on medical institutions that can examine such patients.",
- `「」`(LEFT CORNER BRACKET/RIGHT CORNER BRACKET) --> `\"`
  "「＃7119」：急病やけがの際に、緊急受診の必要性や診察可能な医療機関をアドバイスする電話相談窓口": "「＃7119」: In case of sudden illness or injury, there is a telephone consultation service that advises both the necessity of emergency consultation, and on medical institutions that can examine such patients.",
- `✔`(HEAVY CHECK MARK)  --> "Details of test positives"で利用(ASCIIにこだわると代案なく変更なしが妥当)
  "〇": "✔",
- `－`(FULLWIDTH HYPHEN-MINUS) --> "Details of test positives"の4月16日に出現(マスターデータのダッシュ/ハイフン問題をクレンジングするのが妥当)
  "－": "－"

## 期待する見せ方・挙動 / Expected behavior
- Transifexで翻訳(en)をいわゆるASCIIに修正するのが良いと思います(`✔`と`－`を除く)
    - `✔`については現状のままとする
    - `－`についてはマスターデータを修正する(8月7日時点でHYPHEN-MINUS/HORIZONTAL BAR/FULLWIDTH HYPHEN-MINUSが混在)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@tokyo-citizen ご指摘ありがとうございます！

> ✔については現状のままとする

こちらについては #1398 で反映されたとおりとなります。

> －についてはマスターデータを修正する(8月7日時点でHYPHEN-MINUS/HORIZONTAL BAR/FULLWIDTH HYPHEN-MINUSが混在)

こちらは #2984 でコメント https://github.com/tokyo-metropolitan-gov/covid19/issues/2984#issuecomment-618157721 しましたが、現状では修正は難しい状況です。

残りにつきましては、翻訳チームに検討してもらうようにしますね。

**Comment by tokyo-citizen** [comment]
@kaizumaki
> こちらは #2984 でコメント #2984 (comment) しましたが、現状では修正は難しい状況です。

一般的にマスターデータに手を入れるのは難しい場合がありますし、pythonスクリプトの
ワークアラウンドで逃していることから空気は察しております！

**Comment by tokyo-citizen** [comment]
ハイフン/ハイフンマイナス/ダッシュについて既にオフトピックのためあくまで参考情報です。
(生産的でないかもしれず申し訳ないです)

- ハイフン/ハイフンマイナス/ダッシュの例外処理(現状)
  - 対象文字
    `-`  HYPHEN-MINUS(U+002D)
    `‐` HYPHEN(U+2010)
    `―` HORIZONTAL BAR(U+2015)
  - 例外処理の実装場所
    components/cards/ConfirmedCasesAttributesCard.vue
    auto-i18n/i18n_generator.py

- [7月30日夜のデータ投入](https://github.com/tokyo-metropolitan-gov/covid19/commit/be5d1535377289c184e5a2ed2f53489d4f53c575)
  - データにグリフが似ている文字が追加された(複数の人員での手入力あるある？)
    `－` FULLWIDTH HYPHEN-MINUS(U+FF0D)
  - 対象ファイル
    data/data.json
    data/130001_tokyo_covid19_patients.csv

- [7月30日夜のデータ投入と同時のメッセージカタログ自動生成](https://github.com/tokyo-metropolitan-gov/covid19/commit/48bd8284f26a31855e4369fc90e1ed37f518072f)

以下は7月30日夜のデータ投入時における差分抜粋です。
```diff
--- a/data/data.json
+++ b/data/data.json
@@ -25183,7 +25205,7 @@
             },
             {
                 "リリース日": "2020-04-16T08:00:00.000Z",
-                "居住地": null,
+                "居住地": "－",
                 "年代": "40代",
                 "性別": "女性",
                 "退院": "〇",
--- a/static/data/130001_tokyo_covid19_patients.csv
+++ b/static/data/130001_tokyo_covid19_patients.csv
@@ -2509,7 +2509,7 @@
 2335,130001,東京都,,2020-04-15,水,,―,20代,女性,,,,,,1
 2366,130001,東京都,,2020-04-15,水,,―,50代,女性,,,,,,1
 2368,130001,東京都,,2020-04-15,水,,―,80代,女性,,,,,,1
-100082,130001,東京都,,2020-04-16,木,,"",40代,女性,,,,,,1
+100082,130001,東京都,,2020-04-16,木,,－,40代,女性,,,,,,1
 2457,130001,東京都,,2020-04-16,木,,都外,20代,男性,,,,,,1
 2523,130001,東京都,,2020-04-16,木,,都外,40代,男性,,,,,,1
 100121,130001,東京都,,2020-04-16,木,,都外,40代,男性,,,,,,1
```

**Comment by kaizumaki** [comment]
> データにグリフが似ている文字が追加された(複数の人員での手入力あるある？)
> `－` FULLWIDTH HYPHEN-MINUS(U+FF0D)

なるほど。これはコンポーネントとスクリプト側でフォローせねばですね。

**Comment by tokyo-citizen** [comment]
ちなみに、8月8日夜のデータでは以下のようになっています。
```console
$ cut -d, -f8 130001_tokyo_covid19_patients.csv | sort | uniq

-
―
－
都内
都外
患者_居住地
調査中
湖北省武漢市
湖南省長沙市
$ cut -d, -f10 130001_tokyo_covid19_patients.csv | sort | uniq
-
―
不明
女性
男性
患者_性別
```

**Comment by MaySoMusician** [comment]
### 米印（ `※` ）・全角スペース（和字間隔）・全角ナンバーサイン
ご指摘の通り修正するのが良いと思います。

### LEFT DOUBLE QUOTATION MARK/RIGHT DOUBLE QUOTATION MARK
文字コード関連についてあやふやなのですが、これらはHTMLでは本来 `&ldquo;` `&rdquo;` とマークアップされるもので、直接指定だと文字化けの可能性がある、という感じでしょうか？ 特に強いこだわりは無いですが、可能であれば英語の曲線型の方が良いのかなと思っております。

### `「＃7119」`
こちらについては、語句の説明の際にどう表現するのが良いのか、他の言語の表記も含めて翻訳チームで再検討しようと思います（カギカッコ無しで `#7119` を太字にする、など）

**Comment by tokyo-citizen** [comment]
@MaySoMusician
ご検討いただきありがとうございます。また、細かい話ばかりで申し訳ないです。

まず前提として、翻訳チームの皆様の思いを尊重させていたきます。

ご質問いただいた括弧系については、翻訳(en)のカタログファイルに既に以下のバリエーションが
あったので、`"`:QUOTATION MARKに揃えるのはどうかなという主観的なものでした。
- `"`:QUOTATION MARK(U+0022)」
- `'`:APOSTROPHE(U+0027)
- `“”`LEFT DOUBLE QUOTATION MARK(U+201C)/RIGHT DOUBLE QUOTATION MARK)(U+201D)

**Comment by tokyo-citizen** [comment]
@MaySoMusician
エスケープするのか悩まなくていい`“”`:LEFT DOUBLE QUOTATION MARK(U+201C)と
RIGHT DOUBLE QUOTATION MARK)(U+201D)がいい気がしてきました！

**Comment by MaySoMusician** [comment]
`「＃7119」`  の部分は、カギカッコをとって太字にすることで翻訳チームと合意が取れたので #5260 を出しました

**Comment by kaizumaki** [comment]
ハイフン問題 https://github.com/tokyo-metropolitan-gov/covid19/issues/5218#issuecomment-670844722 については、PR #5263 を出しました。

**Comment by goki90210** [comment]
> 文字コード関連について自分の知識があやふやなのですが、これらはHTMLでは本来 &ldquo; &rdquo; とマークアップされるもので、

HTML 5/UTF-8で書かれていれば"&amp;"(&amp;amp;)、"&lt;"(&amp;lt;), "&gt;"(&amp;gt;)以外は縛りはないはずですよ。

**Comment by kaizumaki** [comment]
こちらのissueは解決済みと思われますので、クローズとします。
