### ISSUE TITLE
8/8のmain_summaryのdateが更新されていない

### ISSUE THREAD

**Issue by s5ml** [tokyo-metropolitan-gov/covid19#5220]
## 起こっている問題 / The Problem
- 8/8のmain_summaryのdateが更新されていない
- これにより東京都発表の8/8の429人が8/7に合算されてしまっている

## スクリーンショット / Screenshot
- 東京都の発表では8/8が429人
![image](https://user-images.githubusercontent.com/68819514/89715861-cc808600-d9e3-11ea-8749-3feafe7dd84d.png)

- data.json上は"lastUpdate"は更新されているが、陽性患者数の"date"は8/7のまま
![image](https://user-images.githubusercontent.com/68819514/89715752-08671b80-d9e3-11ea-891f-a5fbea3983fc.png)

- 「新規患者に関する報告件数の推移」の更新は8/8だが「検査陽性者の状況」は8/7のまま
![image](https://user-images.githubusercontent.com/68819514/89716120-4cf3b680-d9e5-11ea-9aa0-9bdec2fda7c4.png)

## 期待する見せ方・挙動 / Expected Behavior
- 陽性者429人が追加されたのは8/8なので、data.jsonの陽性患者数の"date"も更新されるべき

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページを表示する（https://stopcovid19.metro.tokyo.lg.jp/）
2. 「新規患者に関する報告件数の推移」と「検査陽性者の状況」の更新日の違いを確認する

## 動作環境・ブラウザ / Environment
- 表示データ誤りのため環境に依らない

**Comment by s5ml** [comment]
本来想定する使い方ではないのかもしれないが、Githubの変更履歴から日々の変化を追っている身としては、今回のミスにより、8/7の新規陽性者が8/6との差で891人になってしまう。
このまま放置する8/8が0人になる。可能であれば"date"を8/8として一度修正した上で、8/9分の更新を行っていただきたい

**Comment by kaizumaki** [comment]
@s5ml ご指摘ありがとうございます。先ほど修正いたしました。 1089e0e66a198b4f788fe62b6526b8f84657c844
運営側のデータ変換の際のスクリプトのミスでした。ご指摘いただき感謝です。

**Comment by s5ml** [comment]
修正確認できましたのでcloseします。ご対応感謝します。
