### ISSUE TITLE
ページ内リンクにスムーススクロールを設定

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#523]
## 改善詳細 / Improve details
* [新型コロナウイルス感染症が心配な方へ](https://stg-covid19-tokyo.netlify.com/flow)ではページ内のアンカーリンクへの遷移があるが、スムーススクロールをすることでどのように遷移したのかをユーザーに知らせることができる
 
## スクリーンショット / Screenshot

<img src=https://user-images.githubusercontent.com/1301149/75994313-1e594780-5f3e-11ea-8d7e-bfd9a7a49da8.png width=50%>

## 期待する見せ方・挙動 / Expected behavior
* スムーススクロールの実装<br>
利用するライブラリなどはおまかせ

## 動作環境・ブラウザ / Environment
* スマホ表示時（iPhone 11 Proで確認）

**Comment by nard-tech** [comment]
"nuxt js smooth scroll" で検索してみると，[vue-scrollto](https://github.com/rigor789/vue-scrollto)が人気のようですので，これを使って実装してみます．

**Comment by yhay81** [comment]
すみません、気づかず実装してしまいました。
少しでも良い実装で進んでおられましたら、こちら取り下げます。

**Comment by nard-tech** [comment]
@yhay81 いえいえ，まだ全然着手してないのでお気になさらず．
