### ISSUE TITLE
更新負荷低減のために未使用ライブラリを整理する

### ISSUE THREAD

**Issue by ghost** [tokyo-metropolitan-gov/covid19#5237]
## 改善詳細 / Details of Improvement
- 更新負荷低減のために`package.json`にある未使用ライブラリが何かを整理します
- Renovate（依存ライブラリ更新）の運用方法を考える(#5142)からライブラリ整理関連トピックの分岐です
   (分岐するのはよろしくないとのご意見があればはこのIssueはクローズ致します)

## スクリーンショット / Screenshot
- `package.json`の[変更履歴](https://github.com/tokyo-metropolitan-gov/covid19/commits/development/package.json)(参考)

## 期待する見せ方・挙動 / Expected behavior
- 更新負荷低減のために未使用ライブラリの削除と関連修正を行うことが考えられます

## 動作環境・ブラウザ / Environment
- 本番環境/開発環境

**Comment by tokyo-citizen** [comment]
- 対象
  - dependencies
    - @types/d3
- 経緯
  - マップ関連のコンテンツ用に[追加](https://github.com/tokyo-metropolitan-gov/covid19/commit/f4de8a7e3eaa170662b5835b085e7bb18e1d65b2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
  - 既に以下のコンテンツは削除済
    - 新宿区/千代田区エリアの来訪者推移（参考値）
    - 新宿駅/東京駅周辺の人口推移（参考値）
- ライブラリ削除に伴う関連修正
  - `ui-test/ogp_screenshot.py`の以下も削除可能と考えられます
```python
       if ('heatmap' in path):
            time.sleep(20)
```
  - その他の関連データファイルについては(#5092)にて削除することも考えられます

**Comment by tokyo-citizen** [comment]
- 対象
  - devDependencies
    - rimraf
- 経緯
  - hardsource用に[追加](https://github.com/tokyo-metropolitan-gov/covid19/commit/1cd0719ea27c3aa7b27eb96c00ca25f98b42f343#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
  - `yarn dev`での開発やNetlifyのビルド時にhardsource に関するエラーが発生するため[無効化](https://github.com/tokyo-metropolitan-gov/covid19/pull/1980)
- ライブラリ削除に伴う関連修正
  - `nuxt.config.ts`の以下も削除可能と考えられます
```typescript
    // https://ja.nuxtjs.org/api/configuration-build/#hardsource
    // hardSource: process.env.NODE_ENV === 'development'
```
  - `package.json`の以下も削除可能と考えられます
```json
    "clean-hardsource": "rimraf ./node_modules/.cache/hard-source"
```

**Comment by tokyo-citizen** [comment]
- 削除候補
  - devDependencies
    - nodemon
- 経緯
  - `create-nuxt-app`で[追加](https://github.com/tokyo-metropolitan-gov/covid19/commit/16e4924af613281c21b0b25a74843c6116b15669#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
  - ほぼ直後に`package.json`の`dev`を以下から[変更](https://github.com/tokyo-metropolitan-gov/covid19/commit/21a161cb8e5dfd17700ca82276f0bc159eeebffa#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)して`nodemon`を使わなくなった
```typescript
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server"
```
  - 現在の`package.json`の`dev`は以下のようになっている
```typescript
    "dev": "cross-env NODE_ENV=development GENERATE_ENV=development nuxt-ts",
    "dev-no-axe": "cross-env NODE_ENV=dev-no-axe GENERATE_ENV=development nuxt-ts",
```
- ライブラリ削除に伴う関連修正
  - 無いと考えられます

**Comment by tokyo-citizen** [comment]
- 削除候補
  - dependencies
    - express
- 経緯
  - `create-nuxt-app`で[追加](https://github.com/tokyo-metropolitan-gov/covid19/commit/16e4924af613281c21b0b25a74843c6116b15669#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
  - `yarn.lock`で`webpack-bundle-analyzer`の`dependencies`に`express`があります
  - 東京都コロナ対策サイトのソースコードからは`express`を直接利用していないと考えられます
  - `yarn remove express && yarn dev`を実行してWebブラウザで確認しても正常に動作しているように見えます
- ライブラリ削除に伴う関連修正
  - 無いと考えられます

**Comment by tokyo-citizen** [comment]
- 削除候補
  - devDependencies
    - babel-jest
    - jest
    - vue-jest
- 経緯
  - `create-nuxt-app`で[追加](https://github.com/tokyo-metropolitan-gov/covid19/commit/16e4924af613281c21b0b25a74843c6116b15669#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
  - その後`package.json`の`test`を以下から[変更](https://github.com/tokyo-metropolitan-gov/covid19/commit/fe5696072ee1d724b92252551640441b1019de4b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)して`jest`を使わなくなりました(`echo`するのみで返るように変更)
    ```json
        "test": "jest"
    ```
  - 現在は`yarn test`を実行すると以下のようになります
    ```console
    tokyo-citizen@macos covid19 % yarn run test
    yarn run v1.22.4
    $ echo 'skip tests (there is no test)'
    skip tests (there is no test)
    ✨  Done in 0.06s.
    ```
  - 東京都コロナ対策サイトのソースコードからは`jest`を直接利用していないと考えられます
  - `yarn remove babel-jest jest vue-jest && yarn dev`を実行しても正常に動作しているように見えます
  - **今後`jest`でテストの自動化を行わないのであればという条件付きで削除可能と考えられます**
- ライブラリ削除に伴う関連修正
  - 以下のファイルも不要になると考えられます
    - `jest.config.js` (`jest`の設定ファイル)
    - `.babelrc` (`create-nuxt-app`で自動作成されたのちに微修正はあれど以下のように`test`のエントリしか存在しません)
    ```typescript
    {
      "env": {
        "test": {
          "presets": [
            [
              "@babel/preset-env",
              {
                "useBuiltIns": "usage",
                "corejs": 3,
              },
            ],
          ]
        },
      },
    }
    ```
   - 必要に応じてworkflowで`yarn run test`を実行している部分(`echo`して返るので放置する考え方もあります)
    ```console
    tokyo-citizen@macos covid19 % grep -R "yarn run test" .github
    .github/workflows/staging.yml:      - run: yarn run test
    .github/workflows/deploy.yml:      - run: yarn run test
    .github/workflows/screenshot.yml:      - run: yarn run test
    .github/workflows/ogp_builder.yml:      - run: yarn run test
    .github/workflows/build.yml:      - run: yarn run test
    ```

**Comment by mcdmaster** [comment]
@tokyo-citizen まとめありがとうございます。
`.babelrc` ファイルは、 #5061 で私が変更を掛けたものなので、コメントさせてください。
結論から言えば、こんごは「不要」というご理解でオーケーです。（という、私の考え方です）

出典はこちらです。
- [feat(webpack): auto detect core-js version](https://github.com/nuxt/nuxt.js/pull/7785)

#5061 の修正の目的は、`core-js` のバージョン番号の `3` への固定化でした。
現状、`nuxt >= 2.14.0` が `core-js` バージョンを自動検出してくれるということであれば、以下が期待できます。
- `.babelrc` をはじめとする、コードの削減
- `core-js` バージョン依存のリスクを `nuxt` に移転する

ですので、我々としては `.babelrc` の呪縛から逃れる（？）ために、削除をするのがいいと思います

**Comment by kaizumaki** [comment]
まとめありがとうございます！助かります 🙏 

> 今後 `jest` でテストの自動化を行わないのであればという条件付きで削除可能と考えられます

jestでやるかどうかは別として、自動テストは導入したいのですよね...
ただこちら https://github.com/tokyo-metropolitan-gov/covid19/issues/5142#issuecomment-670371090 でもコメントしたとおり、自動テストがどういうものになるのか、私がわかっておらず。
どなたか別途ご提案いただけると、たいへんうれしいです 🙇‍♀️

**Comment by tokyo-citizen** [comment]
jestの要否に関連するネタという理屈でここに付けます。

@kaizumaki
モダンなWebアプリケーションのテストは私もよくわからないので、まずはGoogle検索大明神に少しだけ
お伺いを立ててみたところ、程良いところで以下を見つけました。
(単体テストや結合テストはなかなか手を出しにくいと思いますのでやるとしてもUIテストあたりがターゲットかなと...)
- [Nuxt.jsの新規プロジェクトでいい感じのテスト環境をつくる@2018](https://qiita.com/okmttdhr/items/48e8d4db1a7827d44ec4)
- [フロントエンドのテストについて考える](https://qiita.com/okmttdhr/items/c1e80353928e121c4761)

ざっと読みながら、なんか似たネタのOpen Issueを垣間見たぞと思い出したので以下も参考として。
- JestのSnapshot Testingを導入したい (#3122)
- storybookの導入 (#756)

**Comment by kaizumaki** [comment]
@tokyo-citizen リファレンスありがとうございます。
なるほど、UIテストをターゲットにするのはよさそうですね。別途issueを立ててもらえると助かります 🙏 

本題の「jestが必要かどうか」ですが、「必要そうだけどもテスト導入時に周辺ライブラリも含めて改めて検討」でよいような気がします。
なので、このissueを進めるにあたっては「削除」でいいんじゃないですかね。

**Comment by tokyo-citizen** [comment]
@kaizumaki
このIssueの方向性について大体まとまったと思いますので、とりあえずテスト方法の検討についてIssueを立てました！
(更新負荷低減のためにリグレッションテスト方法を検討する #5246)

**Comment by tokyo-citizen** [comment]
@goki90210 さんが挙げていたdependenciesとdevDependenciesのカテゴリ整理が残っていました。
(そもそも論の他にRenovateでdependenciesとdevDependenciesのルールを変えるという応用も考えられます)

カテゴリ整理について情報お持ちしております！

**Comment by tokyo-citizen** [comment]
さらに @shgtkshruch さんが挙げていた直接依存していないライブラリも`package.json`に追加されているというのも残っていました。
(RenovateからのPRについての対応対象を減らすという観点でこれも大事です)

こちらについても情報お待ちしております！

**Comment by shgtkshruch** [comment]
公式ドキュメントにもあるとおり、Vue と Vue Meta は Nuxt.js に含まれています。

> Nuxt.js はリッチなウェブアプリケーションを構築するために下記のものを含んでいます
>
> • [Vue 2](https://vuejs.org/)
> • [Vue Router](https://router.vuejs.org/ja/)
> • [Vuex](https://vuex.vuejs.org/ja/)（[ストアオプション](https://ja.nuxtjs.org/guide/vuex-store)を利用している場合に限る）
> •  [Vue Server Renderer](https://ssr.vuejs.org/ja/)（[mode: 'spa'](https://ja.nuxtjs.org/api/configuration-mode) を利用している場合を除く）
> • [Vue Meta](https://github.com/nuxt/vue-meta)
>  ref: https://ja.nuxtjs.org/guide

また TypeScript と ts-loader は `@nuxt/typescript-build` に含まれています。
こちらも[ドキュメント](https://typescript.nuxtjs.org/guide/setup.html#installation)にありますが、Nuxt.js の TypeScript 対応で必須のライブラリは `@nuxt/typescript-build` と `@nuxt/types` です。
（`package.json` から TypeScript と ts-loader を削除しても、`yarn generate:deploy` などのコマンドは通ります）

Nuxt.js などのフレームワークを採用することのメリットの 1つは、ライブラリの管理や汎用的な処理を任せることで、プロジェクト固有の部分にリソースを割けることだと思います。

フレームワークに任せるよりも自分たちで管理したほうが保守性が上がる場合や新機能を使う場合は良いと思いますが、特別な理由がない限りフレームワークとプロジェクトで同じライブラリを二重管理するのはおすすめしません。

[こちら](https://github.com/tokyo-metropolitan-gov/covid19/issues/5142#issuecomment-667668945)にも書きましたがリソースやポリシーによるので、管理したい方がいらっしゃる場合はおまかせします :pray:

**Comment by kaizumaki** [comment]
@shgtkshruch 
> 特別な理由がない限りフレームワークとプロジェクトで同じライブラリを二重管理するのはおすすめしません。

この点、私も同意です。それがエコシステムのいいところではないかと思っています。

そしてなにより保守の労力が軽減される方向に持っていきたいです。現在の体制（みなさんがご協力いただいている）がいつまでも続くとは限らないと思っているので...。

**Comment by tokyo-citizen** [comment]
以下については、ドキュメントで明示的に指定されているのでdependenciesからdevDependenciesに
移動で良いと思います。
- @nuxtjs/dotenv
  - [https://github.com/nuxt-community/dotenv-module/blob/master/README.md](https://github.com/nuxt-community/dotenv-module/blob/master/README.md)
- axe-core
  - [https://axe.vue-a11y.com/guide/](https://axe.vue-a11y.com/guide/)
- cross-env
  - [https://github.com/kentcdodds/cross-env/blob/master/README.md](https://github.com/kentcdodds/cross-env/blob/master/README.md)

**Comment by tokyo-citizen** [comment]
ここまでをまとめると以下のようになります。
- 削除
@types/d3
@vue/test-utils
babel-jest
express
jest
nodemon
rimraf
ts-loader
typescript
vue
vue-jest
vue-meta
- devDependenciesに移動
@nuxtjs/dotenv
axe-core
cross-env

以下のように削除と移動を行った後でbuildやgenerateを行ってWebブラウザ(Safari)で
確認しましたが問題ないようです。
(移動するときにバージョン指定しているのはRenovateの導入時にpin留めしたためです)

```console
tokyo-citizen@macos covid19 % node --version
v12.18.3
tokyo-citizen@macos covid19 % yarn --version
1.22.4
tokyo-citizen@macos covid19 % yarn remove @types/d3
tokyo-citizen@macos covid19 % yarn remove express
tokyo-citizen@macos covid19 % yarn remove vue
tokyo-citizen@macos covid19 % yarn remove vue-meta
tokyo-citizen@macos covid19 % yarn remove @vue/test-utils
tokyo-citizen@macos covid19 % yarn remove babel-jest
tokyo-citizen@macos covid19 % yarn remove jest
tokyo-citizen@macos covid19 % yarn remove nodemon
tokyo-citizen@macos covid19 % yarn remove rimraf
tokyo-citizen@macos covid19 % yarn remove ts-loader
tokyo-citizen@macos covid19 % yarn remove typescript
tokyo-citizen@macos covid19 % yarn remove vue-jest
tokyo-citizen@macos covid19 % grep \"@nuxtjs/dotenv\": package.json
    "@nuxtjs/dotenv": "1.4.1",
tokyo-citizen@macos covid19 % yarn remove @nuxtjs/dotenv
tokyo-citizen@macos covid19 % yarn add -D @nuxtjs/dotenv@1.4.1
tokyo-citizen@macos covid19 % grep \"axe-core\": package.json
    "axe-core": "4.0.1",
tokyo-citizen@macos covid19 % yarn remove axe-core
tokyo-citizen@macos covid19 % yarn add -D axe-core@4.0.1
tokyo-citizen@macos covid19 % grep \"cross-env\": package.json
    "cross-env": "7.0.2",
tokyo-citizen@macos covid19 % yarn remove cross-env
tokyo-citizen@macos covid19 % yarn add -D cross-env@7.0.2
```

**Comment by tokyo-citizen** [comment]
横道にそれますがgenerateするときに、いつの日からか以下のエラーが出ているようです。
```console
 ERROR  window is not defined                                         00:37:38

  at a.setWidths (pages/index.js:23841:7)
  at un.run (node_modules/vue/dist/vue.runtime.common.prod.js:6:27543)
  at sn (node_modules/vue/dist/vue.runtime.common.prod.js:6:25554)
  at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.prod.js:6:12260)
  at Wt (node_modules/vue/dist/vue.runtime.common.prod.js:6:11661)
  at runNextTicks (internal/process/task_queues.js:62:5)
  at listOnTimeout (internal/timers.js:518:9)
  at processTimers (internal/timers.js:492:7)
```

どうもyarn.lockが腐っているようで、以下のようにして再生成したら解決したようです。
(勘違いだったらすいません)
```console
tokyo-citizen@macos covid19 % mv yarn.lock yarn.lock.bak
tokyo-citizen@macos covid19 % yarn install
tokyo-citizen@macos covid19 % diff -q yarn.lock.bak yarn.lock
Files yarn.lock.bak and yarn.lock differ
tokyo-citizen@macos covid19 % rm yarn.lock.bak
tokyo-citizen@macos covid19 % yarn build
tokyo-citizen@macos covid19 % yarn generate
```

**Comment by tokyo-citizen** [comment]
ライブラリ整理に伴う関連修正についてもまとめます。

- `@types/d3`関連
  - `ui-test/ogp_screenshot.py`から以下のコードを削除
    ```python
           if ('heatmap' in path):
                time.sleep(20)
    ```

- `rimraf`関連
  - `nuxt.config.ts`から以下のコードを削除
    ```typescript
        // https://ja.nuxtjs.org/api/configuration-build/#hardsource
        // hardSource: process.env.NODE_ENV === 'development'
    ```
  - `package.json`から以下のコードを削除
    ```json
        "clean-hardsource": "rimraf ./node_modules/.cache/hard-source"
    ```

- `jest`関連       
    - `jest.config.js`をファイル削除
    - `.babelrc`をファイル削除
    - GitHub Actionsの設定ファイルにある`yarn run test`の部分は削除しない
      (`package.json`に`test`が残してあり、`echo`して返るだけで現状でも実害はなく、
      GitHub Actionsの設定ファイルから削除すると後から戻すのも厄介と考えられるため)

**Comment by mcdmaster** [comment]
こちら、実は[本家 Vuetify に PR](https://github.com/vuetifyjs/vuetify/pull/12017/files/4d904e0324bbf9c47742b88f84afe416c16f52df..248b21a572eb9f138ab7575e438fee9eba7c8f2e#) を上げたりしています。
私も同じエラーに遭遇したため、そもそも Vue 内で DOM オブジェクトの window を頭に見るとか、ポリシに一貫性を欠くよね？と思ったのがキッカケです

> 横道にそれますが、generateするときに、いつの日からか以下のエラーが出ているようです。
> (NetlifyのDeploy関連ログにも似たようなエラーが出ています)
> 
> ```
>  ERROR  window is not defined                                         00:37:38
> 
>   at a.setWidths (pages/index.js:23841:7)
>   at un.run (node_modules/vue/dist/vue.runtime.common.prod.js:6:27543)
>   at sn (node_modules/vue/dist/vue.runtime.common.prod.js:6:25554)
>   at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.prod.js:6:12260)
>   at Wt (node_modules/vue/dist/vue.runtime.common.prod.js:6:11661)
>   at runNextTicks (internal/process/task_queues.js:62:5)
>   at listOnTimeout (internal/timers.js:518:9)
>   at processTimers (internal/timers.js:492:7)
> ```
> 
> どうもyarn.lockが腐っているようで、以下のようにして再生成したら解決したようです。
> (勘違いだったらすいません)
> 
> ```
> tokyo-citizen@macos covid19 % mv yarn.lock yarn.lock.bak
> tokyo-citizen@macos covid19 % yarn install
> tokyo-citizen@macos covid19 % diff -q yarn.lock.bak yarn.lock
> Files yarn.lock.bak and yarn.lock differ
> tokyo-citizen@macos covid19 % rm yarn.lock.bak
> tokyo-citizen@macos covid19 % yarn build
> tokyo-citizen@macos covid19 % yarn generate
> ```

**Comment by kaizumaki** [comment]
@tokyo-citizen まとめありがとうございます！
> ここまでをまとめると以下のようになります。
> このIssueのコメントに出ていていない@vue/test-utilsを削除対象にしたのは、テスト方針が
> 定まるまではjestを一旦削除するとなったので、使いどころがないと考えたためです。
> 
> * 削除
>   @types/d3
>   @vue/test-utils
>   babel-jest
>   express
>   jest
>   nodemon
>   rimraf
>   ts-loader
>   typescript
>   vue
>   vue-jest
>   vue-meta
> * devDependenciesに移動
>   @nuxtjs/dotenv
>   axe-core
>   cross-env

ご提案の通りでいいのではないかと思いますが、みなさんいかがでしょう？

**Comment by goki90210** [comment]
私は、
https://github.com/tokyo-metropolitan-gov/covid19/issues/5142#issuecomment-668890513
で述べた点が守られていればpackage.jsonから削除してもいいです。

再掲します。

>ソースから直接使用しているものはpackage.jsonから削除してはいけません。
ただし、依存関係を正しく理解することがどこかで担保されている場合はこの限りではありません。
（yarn.lockを見ろはナシです。）

理由はたとえフレームワーク側で依存しているからと言っても、
そのフレームワークが依存をやめれば使えなくなるおそれがあります。
（ビルドで失敗するからそれでいいのではという意見もあるかと思いますが）

**Comment by tokyo-citizen** [comment]
@goki90210
コメントありがとうございます。
下記から考えて、指摘いただいた点は削除対象としたvue-metaが該当しますが、[#5237 (comment)](https://github.com/tokyo-metropolitan-gov/covid19/issues/5237#issuecomment-672295667)にて
コメント頂いたように、「Vue Meta は Nuxt.js に含まれています」ということで、削除してOKということ
ですかね？(長いのとコマンドがちょっとダサいのは大変申し訳ないです)

```console
tokyo-citizen@macos covid19 % egrep '(reuire\(|import.*from.*)' ./**/*.{js,ts,vue} | cut -d\' -f2 | sort -r | uniq
~/utils/monitoringStatusValueFormatters
~/components/ConfirmedCasesByMunicipalitiesTable.vue
vue/types/options
vue-spinner/src/ScaleLoader.vue
vue-scrollto
vue-meta
vue-i18n
vue-chartjs
vue
nuxt-i18n/types/nuxt-i18n
nuxt-i18n
dayjs/plugin/duration
dayjs/plugin/customParseFormat
dayjs
chart.js
@nuxt/types/app
@nuxt/types
@/utils/tab-event-bus.ts
@/utils/monitoringStatusValueFormatters
@/utils/i18nUtils
@/utils/formatTable
@/utils/formatMonitoringItems
@/utils/formatGraph
@/utils/formatDayBeforeRatio
@/utils/formatDate.ts
@/utils/formatDate
@/utils/formatConfirmedCases
@/utils/colors
@/utils/card-event-bus
@/static/selectmenu.svg
@/static/printer.svg
@/static/printer-white.svg
@/static/parent.svg
@/static/masktrash.svg
@/static/flow/phone.svg
@/static/flow/cond_sydr.svg
@/static/flow/cond_sy.svg
@/static/flow/cond_anx.svg
@/static/flow/bed.svg
@/static/earth.svg
@/static/covid.svg
@/static/antenna.svg
@/plugins/vue-chart
@/pages/flow.vue
@/data/tokyo_rule.json
@/data/tokyo_alert.json
@/data/positive_status.json
@/data/positive_rate.json
@/data/positive_by_diagnosed.json
@/data/positive_by_developed.json
@/data/patient.json
@/data/news.json
@/data/monitoring_items.json
@/data/metro.json
@/data/data.json
@/data/daily_positive_detail.json
@/data/consultation_about_fever.json
@/data/agency.json
@/components/cards/UntrackedRateCard.vue
@/components/cards/TokyoRulesApplicationNumberCard.vue
@/components/cards/TestedNumberCard.vue
@/components/cards/TelephoneAdvisoryReportsNumberCard.vue
@/components/cards/SevereCaseCard.vue
@/components/cards/PositiveRateCard.vue
@/components/cards/PositiveNumberByDiagnosedDateCard.vue
@/components/cards/PositiveNumberByDevelopedDateCard.vue
@/components/cards/MonitoringItemsOverviewCard.vue
@/components/cards/MonitoringConsultationDeskReportsNumberCard.vue
@/components/cards/MonitoringConfirmedCasesNumberCard.vue
@/components/cards/MetroCard.vue
@/components/cards/HospitalizedNumberCard.vue
@/components/cards/ConsultationAboutFeverNumberCard.vue
@/components/cards/ConfirmedCasesNumberCard.vue
@/components/cards/ConfirmedCasesDetailsCard.vue
@/components/cards/ConfirmedCasesByMunicipalitiesCard.vue
@/components/cards/ConfirmedCasesAttributesCard.vue
@/components/cards/CardRow.vue
@/components/cards/AgencyCard.vue
@/components/WhatsNew.vue
@/components/UntrackedRateMixedChart
@/components/TokyoAlertCard.vue
@/components/TimeStackedBarChart.vue
@/components/TimeBarChart.vue
@/components/StaticInfo.vue
@/components/StaticCard.vue
@/components/SiteTopUpper.vue
@/components/SideNavigation.vue
@/components/SevereCaseBarChart.vue
@/components/ScrollableChart.vue
@/components/PrinterButton.vue
@/components/PositiveRateMixedChart
@/components/PageHeader.vue
@/components/OpenDataLink.vue
@/components/NoScript.vue
@/components/MonitoringItemsOverviewTableValueWithTranslatableUnit.vue
@/components/MonitoringItemsOverviewTableMedicalSystem.vue
@/components/MonitoringItemsOverviewTableInfectionStatus.vue
@/components/MonitoringConsultationDeskReportChart.vue
@/components/MonitoringConfirmedCasesChart.vue
@/components/MonitoringCommentFrame.vue
@/components/MonitoringCommentCard.vue
@/components/MixedBarAndLineChart.vue
@/components/MetroBarChart.vue
@/components/MenuList.vue
@/components/LinkToInformationAboutEmergencyMeasure.vue
@/components/LanguageSelector.vue
@/components/ExternalLink.vue
@/components/DevelopmentModeMark.vue
@/components/DataViewShare.vue
@/components/DataViewExpantionPanel.vue
@/components/DataViewDataSetPanel.vue
@/components/DataViewCustomInfoPanel.vue
@/components/DataViewBasicInfoPanel.vue
@/components/DataView.vue
@/components/DataTable.vue
@/components/DataSelector.vue
@/components/DashedRectangleTimeBarChart.vue
@/components/ConfirmedCasesDetailsTable.vue
@/components/CardsReference.vue
@/components/CardsMonitoring.vue
@/components/AgencyBarChart.vue
@/components/ActiveTokyoAlert.vue
./nuxt-i18n.config
./chartjs-adapter-dayjs
```

**Comment by mcdmaster** [comment]
ここまでの検討で、`dependencies` にまだある（はずの）モジュールの中でも、`devDependencies` に下ろせるものがないかどうか少し調べてみました。
`@nuxt/types` ([参考](https://typescript.nuxtjs.org/guide/setup.html)) がいけそうです。ぜひ、ご検討をば。

ちなみに、他の `dependencies` アイテムも個別に調べ済みです。
`yarn -D` オプションを明示したものは、`@nuuxt/types` 以外にはありませんでした。以上、ご参考になりましたら

**Comment by kaizumaki** [comment]
@tokyo-citizen Renovate関連でいろいろあった結果、 #5350 でyarn.lockをリフレッシュするに至りました。こちらのissueが進められるかなと思うのですが、どうですかね？

**Comment by kaizumaki** [comment]
こちらのissueを段階的に進めようと思います。私のほうでも依存ライブラリのひとつひとつを調べていたところでした。
すでにみなさんが検討・検証していただいていたので助かりました。
まずは第一弾として明らかにどこからも参照されていないライブラリ＋test関連から削除したいと思います。
### 削除予定
- @types/d3
- @vue/test-utils
- babel-jest
- express
- jest
- nodemon
- vue-jest

（#5432 についてはすでに #5443 で進めてもらってOKです）

**Comment by kaizumaki** [comment]
こちらのissueは一旦クローズとします。
