### ISSUE TITLE
スマホ表示時のヘッダーを固定表示

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#524]
## 改善詳細 / Improve details
* 他ページへの遷移動線をヘッダーが含んでいるため、`position:fixed` にしたい

## スクリーンショット / Screenshot

<img src=https://user-images.githubusercontent.com/1301149/75994680-a93a4200-5f3e-11ea-8356-8f882986ee65.png width=50%>

## 期待する見せ方・挙動 / Expected behavior
* スマホ表示時にヘッダーを上固定にする

**Comment by nard-tech** [comment]
こちら PR 作成します．

**Comment by nard-tech** [comment]
ちょっと手を動かしてみたんですが，画面右下にトップへ戻るリンクのアイコンを表示させておけばよいような気がしてきました．
どうしましょう．

**Comment by shinchit** [comment]
@nard-tech さん、
すみません、手を動かしてしまいました。
勝手がわからず。。。。

PRを作るところまでいったのですが、進めて良いでしょうか。

https://github.com/tokyo-metropolitan-gov/covid19/pull/559

**Comment by nard-tech** [comment]
@shinchit どうぞ！

**Comment by shinchit** [comment]
@nard-tech ありがとうございます！
