### ISSUE TITLE
npm scriptsの generate と lint-and-generate の内容が同じになっている

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#5244]
## 改善詳細 / Details of Improvement
- npm scriptsの `generate` と `lint-and-generate` の内容が同じになっている
  - `eslint './**/*.{js,ts,vue}' && nuxt-ts generate`

https://github.com/tokyo-metropolitan-gov/covid19/blob/6f0bc74dee5eb59c93b840e86a2db620aa15d1bf/package.json#L17-L18

- この2つのスクリプトが存在していると、名前からして `generate` のほうではリントが走らないように見えてしまう（しかし、実際には `generate` でもリントが走る）
- 2つのスクリプトを1つにまとめるか、一方をリントなしにして差別化をすべき
  - 少なくともこのプロジェクトのコード上では `lint-and-generate` は使われていないようなので、削除できそう

**Comment by kaizumaki** [comment]
@munierujp ご指摘ありがとうございます！
> 少なくともこのプロジェクトのコード上では lint-and-generate は使われていないようなので、削除できそう

私もそれでいいんじゃなかなと思います。
