### ISSUE TITLE
data.jsonの肥大化にともない、陽性患者の属性についてオープンデータのAPIに切り替える

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5245]
## 改善詳細 / Details of Improvement
- data.jsonの `patients` が肥大化しています。
- 陽性患者の属性についてはオープンデータが存在し、こちらは最近[API](https://portal.data.metro.tokyo.lg.jp/opendata-api/)経由で取得できるようになりました。
- 当サイトの「陽性患者の属性」の表において、データをdata.jsonの読み込みからAPI取得に切り替えたいと思います。
- data.jsonから `patients` を除外することで、バンドルされたファイル容量の軽減を期待しています。
- 同時にパフォーマンスの向上も期待します。

## スクリーンショット / Screenshot

東京都オープンデータカタログサイト　[オープンデータAPIについて](https://portal.data.metro.tokyo.lg.jp/opendata-api/)
![オープンデータAPI](https://user-images.githubusercontent.com/14883063/89759790-ed50f480-db25-11ea-9366-893bba713a64.png)

## 期待する見せ方・挙動 / Expected behavior
- カスタムソートの実装が難しくなると思います。ここではいったん現状のカスタムソートは外し、オープンデータAPIからのデータ取得に主眼をおきます。
- `cursor` でpaginationの実装は可能ですが、こちらも工夫が必要かと思います。件数でのpaginationではなく、ここでは単純に「日別のデータ取得」で切り替えられるといいかなと思っています。
（ちなみに `endCursor` をパラメーターに入れる場合にはURL Encodeが必要です）

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

大きな変更になると思いますので、みなさんのご意見を伺いながら進めたいと思います。

**Comment by mcdmaster** [comment]
これは、やってみましょうかね。とても面白そうです

**Comment by kaizumaki** [comment]
@mcdmaster おお、ぜひぜひお願いします！パフォーマンス向上のひとつのカギになるんじゃないかと思っています。

**Comment by y-chan** [comment]
i18n_generatorの翻訳キーの取得回りがかなりめんどくさくなりそうですね...
新たな陽性者の属性の実装がどうなるかは不明ですが、おおよそ使われるデータは分かるので、オープンデータを取得して翻訳キーデータを抽出するような変更を試してみます。

**Comment by kaizumaki** [comment]
@y-chan フォローありがとうございます！多言語化のことは失念していました...

> 新たな陽性者の属性の実装がどうなるかは不明ですが、おおよそ使われるデータは分かるので、オープンデータを取得して翻訳キーデータを抽出するような変更を試してみます。

すみませんが、よろしくお願いします！アイディアあったらどしどしお寄せください 🙏

**Comment by goki90210** [comment]
カスタムソートも実装内容とパフォーマンスが良くないと思っているので、
一旦外すのは賛成です。（できればメソッド分割したいです。）

**Comment by Nekoya3** [comment]
#5285 
参考になればと思い現在のページネーションのままの実装も試しました。
PRを上げさせていただきましたので煮るなり焼くなりしていただければと！

**Comment by mcdmaster** [comment]
@Nekoya3 おお、ありがとうございます！

**Comment by kaizumaki** [comment]
パフォーマンスについて、#5293 のPRを私の手元にfetchしてきてdata.jsonのpatientsを削除し（dateはそのまま）、generate:deployしてIE11で見てみました。現在の本番サイトと比較してみて大して変わらないですね...。

（サイトを開いてトップがすべて表示された後に「その他参考指標」タブをクリックして表示されるまでのものです）
- localhostをIE11の開発者ツールで見た場合
![localhost](https://user-images.githubusercontent.com/14883063/90475855-4c84b980-e163-11ea-9b0b-01d867903036.png)

- 本番サイトをIE11の開発者ツールで見た場合
![stopcovid19](https://user-images.githubusercontent.com/14883063/90475992-91105500-e163-11ea-8e8b-020e2e064adb.png)

まあ、何と何を比較すればいいか、よくわかってないんですが...
わかっているのはIE11とAndroid機での表示が重たいとのことで、東京都からも言われており、なんとかしたいと思っています。
data.jsonの軽量化は必要だと思っているので、APIへの切り替えを進めたいのですが、なんとも現状では説得材料に欠けてしまうような気がしています。
まずはパフォーマンス測定は何を比較材料とすればいいのでしょう？

**Comment by mcdmaster** [comment]
@kaizumaki ごくシンプルに考えると、以下のように分別できるはずです。
- JSON API の適用：サーバサイドのデータハンドリング効率化
- ブラウザ依存の UI 改善：クライアントサイドのレンダリング高速化

モダンな(笑) Web アプリでは、サーバ設定でレンダリングまでイジれるようになってきました。
あとは、厳密な意味でのサーバサイドとクライアントサイドのどちらに重きを置くかという、キメの問題かと思われます。
たとえば、サイドメニュー（モバイルではオーバレイメニュー）の mdi アイコンなんてのは頻出するコンテンツですよね。であれば、そやつのレンダリングを軽くするコーディングをする、といった工夫があります。
そのあたり（SVG）の解決策を、今ちょっと試してみています

**Comment by Nekoya3** [comment]
あとは、
- Dynamic Importへの対応
- WepPに変更
- MDIを必要なもののみの読み込みに変更
でしょうか....

**Comment by Nekoya3** [comment]
Dynamic Importについてはためしてみますね

**Comment by Nekoya3** [comment]
@mcdmaster mdiの部分で @mdi/fomt-build を利用して指定アイコンのみをビルドする手法があります...もしよければお試しください
https://qiita.com/amishiro/items/02959d88f1de290ea6ed

**Comment by kaizumaki** [comment]
@mcdmaster @Nekoya3 ありがとうございます！
APIへの切り替え＝data.jsonの軽量化については、通信データ量がごそっと減るのでメリットはあるはずなんです。まずはそれで都に掛け合ってみますね。
あとは、わかりやすい形で体感速度が速くなることを示せればバッチリでしょう！
