### ISSUE TITLE
検査対象者の属性と検査結果区分との関係を明らかにしてください

### ISSUE THREAD

**Issue by nnawata** [tokyo-metropolitan-gov/covid19#5251]
## 改善詳細 / Details of Improvement
- 検査の陽性率の解釈をするために、検査対象の濃厚接触者（や有症者などの検査対象の属性による）数を明らかにしていただきたい。
- 今後、検査数が増えるほど、陽性中の非濃厚接触割合が増えたとき、それが非濃厚の検査数拡大によるものなのか、非濃厚の陽性率の上昇によるものなのかを明らかにすることは、濃厚接触や感染状況に対する理解を深めるために必要。
- 濃厚接触者か否かに関わらず、必要な対象者に検査リソースを集中し、公費を使ってやみくもに余計な検査をしていないこと（wise spending)を証明する唯一の手段は、検査の母集団の属性がハイリスクであることを明らかにすることです。

## スクリーンショット / Screenshot

||濃厚接触|不明|計|
|----|----|----|----|
|陽性|50|30|80|
|陰性|??|??|920|
|検査対象|X|??|1000|

上記Xが明らかになれば、他は推計可能。

## 期待する見せ方・挙動 / Expected behavior

- 日別の検査データの内訳として
- 個別の陽性者の属性として

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nnawata** [comment]
[都内感染者の詳細が週報として出されるようになりました。](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/todokedehcyouseisya.html)
こちらの情報を `data.jsonに` 反映することはできませんか。

**Comment by kaizumaki** [comment]
@nnawata ご提案ありがとうございます。ご指摘いただいた週報の内容については、近日、[東京都オープンデータカタログサイト](https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068)に反映される予定です。
また、当サイトの「陽性者の属性」についても近日中にオープンデータAPIからのデータ取得に変更します。（ #5245 #5293 ）
なので、data.jsonに取り込まれる予定はないのですが、代わりにオープンデータカタログおよびオープンデータAPIの更新をお待ちいただけますと幸いです（当サイト上に項目が追加されるかどうかは未定です）。

**Comment by nnawata** [comment]
わざわざのお返事ありがとうございます。またご対応感謝いたします。
data.jsonの肥大化対応の解決と合わせてですね。
PS 先日のCode for Japan Conferenceも拝聴しました。今後ともご活躍を祈念いたします。

**Comment by kaizumaki** [comment]
> [都内感染者の詳細が週報として出されるようになりました。](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/todokedehcyouseisya.html)
> こちらの情報を `data.jsonに` 反映することはできませんか。

@nnawata たいへんお待たせしました。本日より、東京都オープンデータカタログサイトの[オープンデータAPI](https://portal.data.metro.tokyo.lg.jp/opendata-api/) に福祉保健局の週報で発表されていた項目が反映されるようになりました。是非ともご活用いただけたらと思います。また、当サイトの陽性者の属性にも同様に項目を追加するissue #5674 を立てています。

**Comment by nnawata** [comment]
ご対応とご連絡に感謝いたします。早速活用させていただきます。

**Comment by kaizumaki** [comment]
こちら解決されたと思いますのでクローズいたします。解決に至っていない場合は再オープンしていただいてかまいません。
