### ISSUE TITLE
「企業の皆様・はたらく皆様へ」ページの一部コンテンツ差し替え

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5269]
「企業の皆様・はたらく皆様へ」ページの一部コンテンツ（２つ目の項目）の差し替えをお願いします。

【修正前】
タイトル：`東京都感染拡大防止協力金（第2回）`
本文：`新型コロナウイルス感染拡大防止のため、都の要請や協力依頼に応じて、施設の使用停止や営業時間の短縮に全面的に協力いただける中小事業者の皆様に対し、協力金を支給いたします（支給額50万円〈2事業所以上で休業等に取り組む事業者は100万円〉）。`
リンク：https://kyugyo.metro.tokyo.lg.jp/dai2kai/index.html
　↓
【修正後】
タイトル：`東京都家賃等支援給付金`
本文：`事業者における家賃等の負担を軽減し、事業の継続を下支えするため、国の家賃支援給付金に独自の上乗せ給付（３ヶ月分）を実施します。`
リンク：https://tokyoyachin.metro.tokyo.lg.jp

![No005企業の皆様・はたらく皆様へ（東京都家賃等支援給付金）](https://user-images.githubusercontent.com/14883063/90230391-72a11580-de54-11ea-87b2-897a219425f8.png)

**Comment by nard-tech** [comment]
やります

**Comment by nard-tech** [comment]
@kaizumaki PR 作成しましたのでご確認お願いします．
