### ISSUE TITLE
PC表示時のサイドナビゲーションの左右のボーダーを追加

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#527]
## 起こっている問題 / Occurred problem
* PC表示時のサイドナビゲーションに、デザインでは入っているボーダーが消えてしまっている

## スクリーンショット / Screenshot

<img src=https://user-images.githubusercontent.com/1301149/75995090-3ed5d180-5f3f-11ea-9cf9-56abec7c0fbf.png width=50%>

## 期待する見せ方・挙動 / Expected behavior
<img src=https://user-images.githubusercontent.com/1301149/75995027-28c81100-5f3f-11ea-885a-3a20e4b053e5.png width=50%>

* 左右にボーダーを追加（`1px solid $gray-4`)

## 起こっている問題の再現手段 / Steps to reproduce
1. PCブラウザで表示

## 動作環境・ブラウザ / Environment
* Mac版Chrome

**Comment by mokuzuu** [comment]
はじめまして！
着手してもよろしいでしょうか？

**Comment by mokuzuu** [comment]
issueとは直接関係ないのですが、サイドメニューのスクロールバーは表示してもいいのでしょうか。Figmaのデザインを見る限り、なさそうですね。

**Comment by kaizumaki** [comment]
サイドナビのスクロールバーはこちらのissueで実装したものです。
#261

**Comment by nake226** [comment]
横からすみません、ボーダーだけでなくシャドーもですね。
こちら、お二方がご担当されますか？

**Comment by mokuzuu** [comment]
> サイドナビのスクロールバーはこちらのissueで実装したものです。
> #261

なるほど！デザインでは、スクロールバーはないと思うのですが、スクロールの機能を残したまま、スクロールバーを非表示にするのはどうでしょうか？

**Comment by mokuzuu** [comment]
> 横からすみません、ボーダーだけでなくシャドーもですね。
> こちら、お二方がご担当されますか？

難しいissueではないと思うので、差し支えなければ、私が担当します！

**Comment by kaizumaki** [comment]
スクロールバーの非表示については、 @saladdays に確認したく！

**Comment by kaizumaki** [comment]
@mokuzuu 実装はお願いします！

**Comment by mokuzuu** [comment]
セルフアサインの方法がわからないので、できません。。。（オーナーかコラボレーターでなければならない？）
オーナーかコラボレーターの方、気づいたらアサインよろしくお願いします！

**Comment by mokuzuu** [comment]
実装しました！ついでにスクロールバーも取ってみました（PRの時には含めない予定です）

![noScrollBarDemo](https://user-images.githubusercontent.com/41939914/76000525-90865800-5f4f-11ea-95ee-1aaa7df57f88.gif)

**Comment by mokuzuu** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/541
↑がマージされたら、こちらもマージします

**Comment by nake226** [comment]
皆さん素早い..!!
OSS初心者なのですが、僕も他にできることを探します^^

**Comment by saladdays** [comment]
スクロールバーまで気にして頂いてありがとうございます！
今回は @kaizumaki に僕がお願いしてスクロールバーを付けてもらいました。
ですので今のままで大丈夫です！

むしろFigmaが本体の進化についていけていない状態ですね。お恥ずかしい。。
Figmaの方に反映をしておきます。ありがとうございました！！

**Comment by saladdays** [comment]
![image](https://user-images.githubusercontent.com/1301149/76091600-3940c000-6001-11ea-9273-9ba847d69a21.png)

このようなイメージが正しいものになります！
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=121%3A709

**Comment by mokuzuu** [comment]
了解致しました(^o^)
