### ISSUE TITLE
「都内の最新感染動向」ページ内の外部リンクに外部リンクであることを示すアイコンがついていない

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#5271]
## 改善詳細 / Details of Improvement
- 「[都内の最新感染動向](https://stopcovid19.metro.tokyo.lg.jp/)」ページ内の「最新のモニタリング項目の分析・総括コメントについて」に外部リンクであることを示すアイコン（[mdi-open-in-new](https://materialdesignicons.com/icon/open-in-new)）がついていない
  - 他の外部リンクにはすべてアイコンがついているようなので、つけ忘れ？

https://github.com/tokyo-metropolitan-gov/covid19/blob/65263cd70904156aeb2da68574bca5951ca844b3/components/MonitoringCommentCard.vue#L27-L33

## スクリーンショット / Screenshot

![スクリーンショット 2020-08-14 23 47 42](https://user-images.githubusercontent.com/20086673/90261934-99793f00-de88-11ea-8889-ee124bc2bbc4.png)

## 期待する見せ方・挙動 / Expected behavior
- 「都内の最新感染動向」ページ内の「最新のモニタリング項目の分析・総括コメントについて」に外部リンクであることを示すアイコンがついている

## 解決策 / How to resolve
- ExternalLink.vueを使う

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
@munierujp ご指摘ありがとうございます！そうですね、実装の際の指示忘れでした。ExternalLink.vueを使う方向で修正していただけると助かります。

**Comment by tokyo-citizen** [comment]
@kaizumaki
タイトルの先頭「(ココ)都内の最新感染動向」にアイコンをつけていないのは意図的ですか？
(私の乏しいセンスではmdiの[text-box-search](https://materialdesignicons.com/icon/text-box-search)しか思いつきませんが...)
