### ISSUE TITLE
「最新のお知らせ」リンクが外部サイトだった場合に、外部サイトアイコンを末尾に追加

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#528]
## 改善詳細 / Improve details
* 「最新のお知らせ」リンクが新規ウインドウを開いているが、ここには新規ウインドウアイコンが付与されていない（サイドナビゲーションにはある）

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1301149/75995372-aa1fa380-5f3f-11ea-9c0a-e0d66388b3d4.png)

## 期待する見せ方・挙動 / Expected behavior
* サイドナビゲーションのように末尾にアイコンを付与
![image](https://user-images.githubusercontent.com/1301149/75995399-b572cf00-5f3f-11ea-93d5-fea7bb6a4c04.png)

**Comment by kebhr** [comment]
本件着手します。
