### ISSUE TITLE
ExternalLink コンポーネントを使っていない外部リンクがある

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#5281]
## 改善詳細 / Details of Improvement
- 外部リンク用の[ExternalLink](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/ExternalLink.vue)コンポーネントがある
  - `target`属性、`rel`属性などを適切に設定し、末尾にアイコン（[mdi-open-in-new](https://materialdesignicons.com/icon/open-in-new)）をつけるためのもの
- 外部リンクの要素に`ExternalLink`コンポーネントを使わず、直接`ExternalLink`コンポーネントと同じようなことをしている箇所がいくつかある

### 例

https://github.com/tokyo-metropolitan-gov/covid19/blob/0191c0e8e2ca15e148acbb83472574f4de81d438/components/OpenDataLink.vue#L2-L13

## 期待する見せ方・挙動 / Expected behavior
- 外部リンクにはExternalLink コンポーネントが使われている

**Comment by kaizumaki** [comment]
@munierujp ご指摘ありがとうございます！たしかにおっしゃるとおり、ExternalLinkで置き換えた方がよさそうです。

**Comment by nichesuch** [comment]
`_blank`とか`mdi-open-in-new `で探してみればいいですかね？
やってみます。

**Comment by nichesuch** [comment]
この辺り

`_blank`
- components/DevelopmentModeMark.vue
- components/OpenDataLink.vue
- components/MenuList.vue
- components/PrinterButton.vue
- components/SideNavigation.vue
- components/WhatsNew.vue
- pages/flow.vue


`mdi-open-in-new `
- components/OpenDataLink.vue
- components/MenuList.vue
- components/WhatsNew.vue
- pages/flow.vue

`linkAttrs`methodsでなんかやってるところは、`isExternal`methodsでnuxt-linkとexternal-linkで切り分けた方が良さそう。

`mdi-open-in-new`が不要なものもいくつかある模様。

**Comment by nichesuch** [comment]
外部URLかどうかを、`isInternalLink`か`isExternal`っていうmethodを各vueに作ってますね。
utilsに持っていってどちらかに統一したい。

**Comment by kaizumaki** [comment]
@nichesuch フォローありがとうございます！
ExternalLinkではない `_blank` って結構あるんですね。スタイルによって結果的にそうなった感じでしょうか。

> 外部URLかどうかを、`isInternalLink`か`isExternal`っていうmethodを各vueに作ってますね。
> utilsに持っていってどちらかに統一したい。

これはおっしゃるとおり、utilsにしたほうがよさそうですね。

**Comment by munierujp** [comment]
いっそのことリンク用コンポーネントををくって、そのpropsでboolean型の`external`を受け取るか、受け取ったURLをもとに外部リンクかどうかを判定して分岐させるのもアリかと思います。

**Comment by nichesuch** [comment]
@munierujp それも考えました。
あと、nuxt-linkとの整合性合わせるために、external-linkのURL渡すプロパティはtoにする予定です。

**Comment by nichesuch** [comment]
`受け取ったURLをもとに外部リンクかどうかを判定する場合`がスマートですかね。
propsは一応作って、設定があれば強制でそっちになるようにします。
外部リンクのアイコンも。

**Comment by kaizumaki** [comment]
`nuxt-link` については #5292 でバグが報告されていますが、これのPR #5295 を先に取り込んでもいいですか？

**Comment by nichesuch** [comment]
@kaizumaki 了解です。

**Comment by nichesuch** [comment]
@kaizumaki 
だいたいできそうなんですが、一部、子コンポーネントまでstyleが適用されてくれないところがあって調整中です。
#5295 は明日あたりにマージですか？

**Comment by kaizumaki** [comment]
@nichesuch #5295 をマージしました。こちらの件よろしくお願いします 🙏

**Comment by nichesuch** [comment]
@kaizumaki コンポーネントごとにScoped CSSを使っているのですが、子コンポーネントにデザイン適用するのに、`::v-deep`を使う必要があるようです。
ただ、これを使うには`stylelint.config.js`にignoreのルールをつける必要があります。

```yaml
  rules: {
    'selector-pseudo-element-no-unknown': [
      true,
      {
        ignorePseudoElements: ['v-deep']
      }
    ]
```

この辺り、影響範囲が増えてしまいそうですが、Scoped CSS使っていくなら入れた方がデザインは調整しやすそうです。
`flow.vue`ではCSS modulesを使っていて、こちらが増えてくるのなら、今回の為だけに入れるほどではないかもしれません。
今回も`MenuList.vue`で一箇所のみ使ってます。
ひとまずドラフトでPR出しますので、確認してもらえますか？

**Comment by nichesuch** [comment]
あと、#5295 の件は、methods内で頑張っているのが問題のようで、今回のAppLink.vueでは普通に指定しても`$ yarn generate:dev`で対象のエラーは出ないようです。

```
✔ Generated route "/"                                                                                                                                     23:07:32
✔ Generated route "/worker"                                                                                                                               23:07:32
✔ Generated route "/contacts"                                                                                                                             23:07:32
✔ Generated route "/about"                                                                                                                                23:07:32
✔ Generated route "/parent"                                                                                                                               23:07:32
✔ Generated route "/cards/number-of-hospitalized"                                                                                                         23:07:32
✔ Generated route "/cards/monitoring-number-of-confirmed-cases"                                                                                           23:07:32
✔ Generated route "/cards/number-of-tokyo-rules-applied"                                                                                                  23:07:32
✔ Generated route "/ko"                                                                                                                                   23:07:32
✔ Generated route "/flow"                                                                                                                                 23:07:32
✔ Generated route "/en/about"                                                                                                                             23:07:32
✔ Generated route "/print/flow"                                                                                                                           23:07:32
✔ Generated route "/cards/details-of-confirmed-cases"                                                                                                     23:07:32
✔ Generated route "/ja-basic"                                                                                                                             23:07:32
✔ Generated route "/en/cards/details-of-confirmed-cases"                                                                                                  23:07:32
✔ Generated route "/zh-cn/cards/details-of-confirmed-cases"                                                                                               23:07:32
✔ Generated route "/zh-tw/cards/details-of-confirmed-cases"                                                                                               23:07:32
✔ Generated route "/en"                                                                                                                                   23:07:32
✔ Generated route "/zh-cn"                                                                                                                                23:07:32
✔ Generated route "/ja-basic/cards/details-of-confirmed-cases"                                                                                            23:07:32
✔ Generated route "/ja-basic/cards/positive-number-by-developed-date"                                                                                     23:07:32
✔ Generated route "/ja-basic/print/flow"                                                                                                                  23:07:32
✔ Generated route "/zh-tw/print/flow"                                                                                                                     23:07:32
...
```

**Comment by nichesuch** [comment]
@munierujp ちょっと使い方が変わってしまっているところもありますが、ご提案いただいた`AppLink.vue`で実装してみました。
ご確認お願いします。

**Comment by kaizumaki** [comment]
@nichesuch もろもろご対応ありがとうございます！
> この辺り、影響範囲が増えてしまいそうですが、Scoped CSS使っていくなら入れた方がデザインは調整しやすそうです。
> `flow.vue`ではCSS modulesを使っていて、こちらが増えてくるのなら、今回の為だけに入れるほどではないかもしれません。

私個人的にはCSS modulesを推奨していきたいですが、Scoped CSSのほうが断然多いでしょうし、stylelint.config.jsにignoreのルールを入れていいのではないかと思います。

**Comment by munierujp** [comment]
close via #5314
