### ISSUE TITLE
[i18n] Data Binding Variables w/ nuxt-link

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#5292]
## 起こっている問題 / The Problem
- `<nuxt-link>` タグの設定が一部正しくなく、コンパイルエラーが生じる
参考 https://github.com/nuxt/nuxt.js/issues/7277

## スクリーンショット / Screenshot

エラーのスクリーンショット（VS Code 画面）
![スクリーンショット 2020-08-17 185113](https://user-images.githubusercontent.com/10361533/90383169-bbf29e80-e0ba-11ea-9956-476b5bfaea45.png)

## 期待する見せ方・挙動 / Expected Behavior
- `<nuxt-link>` のある i18n アプリのコンパイルエラーの解消

## 起こっている問題の再現手段 / Steps to Reproduce
1. `yarn generate:dev` をする
※ `yarn dev` / `dev-no-axe` では出てきません
※ 国際化ページのみでしか出てきません

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by goki90210** [comment]
@mcdmaster 
これってNuxtが直らないとだめということですか？
であれば、Nuxtのバージョンをロールバックするというのも手だと思いますが…。

**Comment by kaizumaki** [comment]
なるほど、nuxtのバグなんですね。ご提案いただいたPR #5295 のとおりにテンプレートリテラルで回避するしかないでしょうか。

**Comment by mcdmaster** [comment]
@kaizumaki 
`nuxt` の修正を待つ間我々の作業の推進に差し支えるかもしれないと考えると、我々は独自に対策前進で進むのが良いように思います
