### ISSUE TITLE
カードの表示値にthousands separatorがない

### ISSUE THREAD

**Issue by ghost** [tokyo-metropolitan-gov/covid19#5307]
## 改善詳細 / Details of Improvement
- カードの表示値にthousands separatorがありません
- Webブラウザの表示にて目視確認できた対象は以下です
  - モニタリング項目 [医療提供体制->受入体制->(6)入院患者数->確保病床]
  - 陽性者数（区市町村別） [テーブルの陽性者数]
  - 受診相談窓口における相談件数 [グラフのツールチップ]
- グラフの一部については目視では確認できていません(値が1,000以上のデータに依存するため)

## スクリーンショット / Screenshot
<img width="912" alt="sample1" src="https://user-images.githubusercontent.com/68139470/90747821-5990dc80-e30c-11ea-885c-2d536823a73b.png">
<img width="912" alt="sample2" src="https://user-images.githubusercontent.com/68139470/90747860-67466200-e30c-11ea-8bfd-bbf64d2dbd9b.png">
<img width="912" alt="90612701-5d0c6100-e243-11ea-8188-c812494e8658" src="https://user-images.githubusercontent.com/68139470/90748191-d3c16100-e30c-11ea-8175-09202edc790c.png">

## 期待する見せ方・挙動 / Expected behavior
- 表示値にthousands separatorをつけるように統一する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
こちら、いったんクローズします。
