### ISSUE TITLE
<template>, <script>, <style> の記述順序を統一する

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#5321]
## 改善詳細 / Details of Improvement
- コード内での `<template>`, `<script>`, `<style>` の記述順序が component によって異なっており，コードの統一感がない．
- [スタイルガイド — Vue.js | 単一ファイルコンポーネントのトップレベルの属性の順序](https://jp.vuejs.org/v2/style-guide/index.html#%E5%8D%98%E4%B8%80%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%81%AE%E3%83%88%E3%83%83%E3%83%97%E3%83%AC%E3%83%99%E3%83%AB%E3%81%AE%E5%B1%9E%E6%80%A7%E3%81%AE%E9%A0%86%E5%BA%8F-%E6%8E%A8%E5%A5%A8) にもあるように，同一プロジェクト内では記述の順序を統一することが望ましい
  - また，`<style>` は最後にすべきとされている
- 調査したところ，
  - `<template>` -> `<script>` -> `<style>` の順: 41件
  - `<template>` -> `<style>` -> `<script>` の順: 8件
- したがって，多数派であり「`<style>` は最後」の原則にも則っている `<template>` -> `<script>` -> `<style>` に統一したい．

## 期待する見せ方・挙動 / Expected behavior
- コード内での `<template>`, `<script>`, `<style>` の記述順序が `<template>` -> `<script>` -> `<style>` に統一されていること．

**Comment by goki90210** [comment]
本当は個別に<style>やstyle属性は使うべきではないんですけどね…。
（本来は外部CSSですべて書けるはずで、リンクで実現できればベスト。）
