### ISSUE TITLE
data/monitoring_items.json の String の値を Integer にする

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#5329]
## 改善詳細 / Details of Improvement
[data/monitoring_items.json](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/data/monitoring_items.json#L12) に
```
"(6)入院患者確保病床数": "2500床",
```

```
"(7)重症患者確保病床数": "150床",
```
と単位も含めた文字列がベタ書きされているので，#5323 で thousands separator を入れるにあたり，「床」を除去して `parseInt` で Integer に変換するという処理を入れた．(cf. https://github.com/tokyo-metropolitan-gov/covid19/pull/5323/files#diff-efd4f86cb292769b6e2b9f5b1179422eR127)
#5323 が merge された後は，`data/monitoring_items.json` の仕様を変更して JSON に Integer の値を保持するのが好ましいので，データ更新スクリプトを更新する対応をお願いしたい．

#5323 については，`data/monitoring_items.json` の仕様を変更する前も後も変わらず動作するように対応している．

cf. https://github.com/tokyo-metropolitan-gov/covid19/issues/5307#issuecomment-678411154

## 期待する見せ方・挙動 / Expected behavior
- [data/monitoring_items.json](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/data/monitoring_items.json#L12) で，「(6)入院患者確保病床数」「(7)重症患者確保病床数」についての値が Integer になっていること．

**Comment by kaizumaki** [comment]
@nard-tech ご提案ありがとうございます。「(6)入院患者確保病床数」「(7)重症患者確保病床数」については、実装当初の仕様として文字列を入力するというオーダーでしたので、現状のようになっています。
おっしゃるとおり長らくの間「（数値）＋床」でしか入力されてはいないのですが、東京都に改めて確認したところ、「今後病床数について詳細に記載する可能性はある」とのことでした。ですので、現状のままString型でいきたいと思います。ご理解いただけますようお願いいたします。

**Comment by nard-tech** [comment]
@kaizumaki 
ご確認ありがとうございます．

PR のコードをベースにお話した方がよいと思うので，#5323 で返信させて頂きます．

**Comment by nard-tech** [comment]
@kaizumaki 
ご確認ありがとうございます．

PR のコードをベースにお話した方がよいと思うので，#5323 で返信させて頂きます．

**Comment by nard-tech** [comment]
@kaizumaki #5323 を merge していただきありがとうございます。この issue のご対応お願いします。

**Comment by kaizumaki** [comment]
@nard-tech jsonのほう、対応しました。 https://github.com/tokyo-metropolitan-gov/covid19/compare/28ce6ff0dcb3...5d78f0b61ead
続きをよろしくお願いします！ 🙏
