### ISSUE TITLE
オープンデータのリンク文言の変更

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#533]
## 改善詳細 / Improve details
* 「リンク」という文言は遷移するという機能の説明なので、コンテンツの説明やアクションの説明にした方が良いのではないか

## スクリーンショット / Screenshot

<img src=https://user-images.githubusercontent.com/1301149/75996021-9d4f7f80-5f40-11ea-9b1d-85a6eb1eb2d8.png width=50%>

## 期待する見せ方・挙動 / Expected behavior
* 押すと起こるアクションの説明「オープンデータの閲覧」
* 遷移先のタイトル名「東京オープンデータカタログサイト」

上記いずれかでいかがでしょう？

**Comment by ocean3fish** [comment]
あるいは
「オープンデータを入手」
などはいかがでしょうか？

おそらくこのワードに反応するのは自分でデータを使いたいと思っているエンジニアや分析屋さんなどであろうと思うので、ゲットできる感を出せると良いかなーと。

**Comment by nard-tech** [comment]
「東京オープンデータカタログサイト」と「東京都オープンデータカタログサイト」どちらが正しいのでしょう．
https://catalog.data.metro.tokyo.lg.jp/dataset ではページタイトルが前者，ヘッダーのロゴが後者になっていますね．

**Comment by nard-tech** [comment]
> 自分でデータを使いたいと思っているエンジニアや分析屋さんなど
よりも，まずは一般向けに情報発信をするWebサイトであること，「出典：○○」という表記が一般的であることから，
`出典: <a href="xxxx">東京オープンデータカタログサイト 「東京都 新型コロナウイルス患者発表者数」</a>`
などとするのが適切だと思います．

**Comment by nard-tech** [comment]
という訳で，修正の上コミット致します．

**Comment by ocean3fish** [comment]
@nard-tech 貴重なご意見と迅速なご対応ありがとうございます。
ただこちら元々の要望の経緯やデザイン上の検討も必要になりますので、変更させて頂く可能性があります。
どうぞご了承ください。

**Comment by ocean3fish** [comment]
本リンクの掲載の依頼元との調整の結果、表示上長くなることを避けたいという希望もあり、文言は
オープンデータへのリンク→オープンデータを入手
に変更することになりました。

**Comment by nard-tech** [comment]
@ocean3fish 管理者の方でしょうか？いろいろ気になるので，長くなりますが書かせてください．

*   そもそも，一般向けのサイトで「オープンデータ」という言葉が相応しいか，という議論があると思います．オープンデータの利活用を推進される立場であれば（お名前は存じております）「オープンデータ」という言葉は自然と使いたくなるものだと思いますが，このプロジェクトの本来の目的は，オープンデータ屋さんたちの研究・実践・遊びではなく，「一般の人に向けてわかりやすく情報を届ける」のはずです．失礼を承知で申し上げると，「オープンデータ」という言葉は一般にそれほど浸透しておらず（私はエンジニアでオープンデータを使うこともあるので当然知っていますが），わかりやすさを考慮すると「出典」という言葉の方がより相応しいと思います．
    *   「表示上長くなることを避けたい」という希望があるのでしたら，「出典はこちら」という表記に留めることもできます．
    *   今後オープンデータではないところへリンクを貼る可能性，リンクは貼らないけれど出典を明記したい可能性を考慮すると，なおさら「オープンデータ」という表記は避けた方がよいと思います．
        *   「オープンデータ」という言葉を使う・使わないの是非はともかく，以上の可能性を考慮すると，従前の実装や #609 より，動的に文言を変更できる #548 の方が相応しいと思います．

**Comment by nard-tech** [comment]
@ocean3fish
*   「本リンクの掲載の依頼元」というのは東京都の担当部署でしょうか？東京都も含めた意思決定フローが明確になっていないこと，issue, pull request と異なるところで話が進行していることに違和感を覚えます．まあ，当然 GitHub 上以外でサイト運営上の調整が必要になることもあるでしょうし，明文化されていない意思決定フローが存在することくらい想像できるだろうと言われればそれまでですが，「遠くからコードを書くしかできないけれどコードを書くことはできる」「技術的な面も考慮してよい提案をすることができる」という立場で参加している身からすると，「変更することになりました。」の一言で作業が全部なかったことになるのは大変残念です．
*   加えて，誰が管理者・プロジェクトオーナーなのか明確にされていないのが問題だと思います．意見が対立したときに最終的に決定を下す権限を誰が持っているのか分からないと困惑します．GitHub の機能で owner であることを表示できるはずですし，そうでなくても README.md あたりに記載しておいた方がよいと思います．

**Comment by nard-tech** [comment]
@ocean3fish すみません，#591 で既に議論されていたようですね．今回は私がPRを作ったのが早すぎたともいえるのでその点は反省しますが，少なくとも，誰がどのような立場・経緯で何を判断しているかという点が明確でないと，余計な混乱と不信感が生まれると思います．
不明確であるということは GitHub での OSS 開発の文化とは馴染まないと思いますし，それで困惑する人，参加を躊躇する人，怒って出ていってしまう人が出ないとも限りません．
行政が関与し生命に関わる情報を扱うプロジェクトゆえの特殊な事情は理解しますが，その点配慮をいただければと思います．

**Comment by ocean3fish** [comment]
@nard-tech 
まず、結果として作業して頂いた内容を取り込むことができなかった点、お詫びいたします。
また、私の方からの説明不足な点があったことについてもお詫びいたします。

前提として、私は特に本プロジェクトの決定権を持っているわけではなく、プロジェクトに対して提案を行う権限しかありません。
本プロジェクトは東京都の公式サイトであるため、行政機関としてどのようにメッセージを伝えていきたいかという観点で最終的な精査が行われることになります。
そのため、[貢献の仕方](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/CONTRIBUTING.md)にも以下のように記載させて頂いております。

> improve(改善提案)がついたIssueについては必ず反映できると限りませんのでご了承ください



ご指摘頂いたように、管理者やオーナーが明示されていなかったため、今回のケースでは私が管理者と勘違いさせるような事態になってしまいました。
この点は早急に改善を進めます。

今回はエンジニアの方々だけではなく、行政の中でもとても頑張っている方々がいて、今回のプロジェクトに様々な想いを託されています。
@nard-tech さんは、オープンデータについてとても的確なご認識をされているので、行政側でオープンデータを推進する上でいかに苦難があるかもご存知なのではと思います。
そういった状況の中で、シビックテックに携わる人間として、東京都の方々の想いを大事にしたいと思っています。

> 遠くからコードを書くしかできないけれどコードを書くことはできる
> 技術的な面も考慮してよい提案をすることができる

という姿勢とても素晴らしいと思いますし、同じプロジェクトで関わって頂けること大変心強く思います。
今回は申し訳ないことにご提案を受け取れなかったのですが、引き続きご参加頂けたら嬉しく思います。

**Comment by MasaGon** [comment]
> @saladdays 「東京オープンデータカタログサイト」と「東京都オープンデータカタログサイト」どちらが正しいのでしょう．
> https://catalog.data.metro.tokyo.lg.jp/dataset ではページタイトルが前者，ヘッダーのロゴが後者になっていますね．

当該サイト管理している者です。「東京都」が正です。ページタイトルにミスがありましたので、訂正させて頂きました。ご指摘ありがとうございます。
