### ISSUE TITLE
[FYI] 陽性者の属性データ（data.jsonのpatients）を直近１週間分だけにしてみる（比較検討のため）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5331]
## 改善詳細 / Details of Improvement
- #5245 で陽性者の属性をオープンデータAPIに切り替える提案を出しています。
- ただし、陽性者データの入力とオープンデータAPIの更新タイミングが大幅にずれる懸念があります。
- 東京都から「陽性者の属性は直近１週間以内のものだけ表示する（全体を見たい場合はオープンデータカタログに誘導する）」パターンと比較検討したいとの意見がありました。
- パフォーマンス改善の比較のためです。

## 期待する見せ方・挙動 / Expected behavior
- 比較検討のためですので、data.jsonの `patients` の `data` を１週間分だけにしてみます。

**Comment by kaizumaki** [comment]
対応します。

**Comment by nnawata** [comment]
提案
patientsデータを退院ステータスによって分ければよい。おそらく退院ステータスがついたらその後はエラー修正以外の更新はないため。その結果として、現在の入院者データと、退院済みデータとができることになる。

**Comment by kaizumaki** [comment]
@nnawata ご提案ありがとうございます！こちらのissueは #5245 との比較検討のためですので、#5245 が採用されればこちらは却下になります。もしこちらのほうが採用されるとなったら @nnawata さんの案も検討いたしますね。
私の個人的には、陽性者の属性と入院者と退院済みとわけるのは当サイトの目的の範囲から外れるかなという印象です。

**Comment by nnawata** [comment]
@kaizumaki お返事いただき恐縮です。私もデータを分けることには基本的には賛成していませんが、負荷を落とす関係からどうしても分けなければならないのであればと言う観点で、コメントいたしました。ご放念いただいて構いません。

**Comment by nnawata** [comment]
data.json自体がいろいろなデータの寄せ集めで重くなっているのですが、結局のところ個別患者データが必要なくとも他のサマリデータが必要なのでdata.json全体を取得するというケースが発生しているのではないでしょうか。csvのほうは退院フラグが急になくなったため、data.jsonに急遽切り替えたところで使い始めたところです。趣旨と違っていたらスミマセン。

**Comment by kaizumaki** [comment]
@nnawata ご指摘ありがとうございます。
> csvのほうは退院フラグが急になくなったため、

これについては気づいていませんでした。csvから退院フラグがなくなったのはいつ頃からか、わかりますでしょうか？

**Comment by nnawata** [comment]
CSVから作ったデータが変だと気がついたのは３日前ですので、フラグが実際になくなったのはそれ以前だと思います。正確な記憶ではありませんが、お役に立てれば。

**Comment by kaizumaki** [comment]
@nnawata 運営側でも8/25の時点で退院フラグが消えた旨、確認しました。調査しましたところ、元データの入力ミスが原因で、csvへの変換が上手くいっていなかったようです。@nnawata さんからのご指摘がなければ気づいていませんでした。感謝です！ 🙇‍♀️

**Comment by kaizumaki** [comment]
#5293 がマージされましたので、こちらのissueはクローズします。
