### ISSUE TITLE
パソコンの雑誌の記事を読んだ人がissueに投稿する練習

### ISSUE THREAD

**Issue by takuyatahata** [tokyo-metropolitan-gov/covid19#5340]
@kaizumaki  　さんへ
アットマーク　半角の@マークは〇　全角の＠マークは多分✖だと思う。をつけて通知されるようにしました。
何かお手伝いできることがあれば連絡ください。
git hubが統計データを取り扱うのに使い勝手が良いとは正直思えないです。

**Comment by kaizumaki** [comment]
こちらは当サイトへの提案ではないですかね...？すみませんが、クローズさせていただきますね。

**Comment by takuyatahata** [comment]
@kaizumaki  さんへ　
software designであなたの記事を読みました。専門的に詳しいわけじゃないんですけど、プログラミングを勉強するためにGIThubをちょっといじってます。何か初心者でもできることはありますか？

**Comment by kaizumaki** [comment]
@takuyatahata おお！ありがとうございます！興味を持っていただいて恐縮です。
issueの一覧を見てもらえると、各issueにラベルが付いているのがわかると思います。

![スクリーンショット 2020-09-01 18 28 35](https://user-images.githubusercontent.com/14883063/91833046-21c95380-ec81-11ea-9e65-4c3e54a08578.png)

この中でも `help-wanted` や `IMPORTANT` が付いているissueは、解決策を求めているものになります。プルリクエストもお待ちしています。
また `officially-approved` も東京都からの直接の依頼となりますので、プルリクエストを送っていただけるとうれしいです。

プルリクエストを送らなくても、各issueのディスカッションに参加していただくという貢献の形もあります。ぜひ興味のわいたissueにコメントを投稿してみてください！
