### ISSUE TITLE
メニュー下部が点線になります

### ISSUE THREAD

**Issue by kyoya0819** [tokyo-metropolitan-gov/covid19#5347]
## 起こっている問題 / The Problem
- スマートフォンでメニューを選択するとメニュー下部が点線になってしまいます。

## スクリーンショット / Screenshot

![34169FF9-BBA5-4B05-BFB9-454869A9B752](https://user-images.githubusercontent.com/45027336/91236331-9cbad780-e772-11ea-849d-73fac0a892df.jpeg)

## 期待する見せ方・挙動 / Expected Behavior
- 点線を出さないようにする。

## 起こっている問題の再現手段 / Steps to Reproduce
1. スマートフォンでハンバーガーメニューを展開
2. メニューを選択

## 動作環境・ブラウザ / Environment
iOS13.6

**Comment by kaizumaki** [comment]
@kyoya0819 ご指摘ありがとうございます！こちらは以前に挙げられていた #2493 と同様のものだと思うのですが、#2493 で議論されているとおりこの挙動はいちおう仕様通りということになっています。それでも #2878 で修正を試みたのですが、別の不具合が発生してしまい（ https://github.com/tokyo-metropolitan-gov/covid19/pull/2878#issuecomment-610056538 ）、こちらはリバートしています。
#2493 #2878 を参照いただいて、もし解決する方法があればご提案いただけるとうれしいです。
