### ISSUE TITLE
StaticInfo.vueをAppLinkコンポーネントを使ったソースコードに修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5356]
## 改善詳細 / Details of Improvement
- #5314 で、リンク系のコンポーネント `AppLink.vue` を作ってもらいました。
- 一方で #4118 で `StaticInfo.vue` を修正してもらいましたが、#5314 とコンフリクトしてしまい、#5314 の修正を戻す形になってしまいました。
-  `StaticInfo.vue` を `AppLink` を使った形に修正したいです。 

## スクリーンショット / Screenshot

この部分です。
![コメント 2020-08-28 102346](https://user-images.githubusercontent.com/14883063/91510631-a0885e80-e918-11ea-9d3c-f16407885de8.jpg)

## 期待する見せ方・挙動 / Expected behavior
- 右のボタン部分が `AppLink` を使ったソースコードにする。
- 見た目の変更はなし。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nichesuch** [comment]
了解です。
