### ISSUE TITLE
「企業の皆様・はたらく皆様へ」ページへのコンテンツ追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5357]
「企業の皆様・はたらく皆様へ」ページにコンテンツの追加をお願いします。

- タイトル：`営業時間短縮に係る感染拡大防止協力金`
- 本文：`新型コロナウイルス感染拡大防止のため、酒類の提供を行う飲食店及びカラオケ店に対する都の営業時間短縮の要請に全面的に協力いただける中小の事業者の皆様に対し、協力金を支給します。`
- リンク：https://jitan.metro.tokyo.lg.jp/index.html
- 配置：２番め（「東京都　新型コロナウイルス感染症　支援情報ナビ」と「東京都家賃等支援給付金」のあいだ）

**Comment by Murayu0225** [comment]
やります。
