### ISSUE TITLE
[FYI] [Not Ours] Typescript 4.x でエラー発生

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#5381]
## 起こっている問題 / The Problem
- 既に開発版 `package.json` にも乗っている `Typescript` バージョン `4.x` で、下記のようなエラーが起きます
- デイリービルドされている `4.1.x` も、このイシューを書いている時点で同様です
- MS 側では、トピック（イシュー）がもう立っています
https://github.com/microsoft/TypeScript/issues/40261

## スクリーンショット / Screenshot

- エラーメッセージを転載します…と思ったら、コンソールのスクショがどこかに行ってしまいました
- 基本的に、上記 MS のイシューで触れられている内容と大差ありません

## 期待する見せ方・挙動 / Expected Behavior
- どうやら、以下の条件で起きるようです
-- Node モジュールとソースの `import` あるいは `require` が混在していいる
-- Node モジュールで参照可能だったデータ・オブジェクト（ここでは `kind` という何かのプロパティらしきもの）がソース・モジュール側で親の値を正常に参照できず、コケる
- MS 側のイシューではレアケースと言っています
-- でも、本プロジェクトではカード・モジュールの呼び出しとか、結構頻繁な気がしています
- `Typescript` バージョン `3.x` ではこのエラーが起きないことを確認しています
-- `package.json` の展開も、`Typescript 3.x` でした方がよさげです

## 起こっている問題の再現手段 / Steps to Reproduce
(上記参照)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster 報告ありがとうございます！
MS側のissueのコメントには
> Last working version is 3.1.6. All tested versions after that (several from 3.2 to latest nightly) have this issue.

とありますが、3.1.6ってだいぶ前ですよね...

**Comment by mcdmaster** [comment]
@kaizumaki とりあえず私は今のところ 3.9.7 で大丈夫っぽいです。

イシューのコメントが MS オフィシャルならば、たとえ超 obsoleted なバージョンでもそれを使うのが無難です。
とはいえ、4.x も GA しているわけですから、要は使う側のリスク許容度がいかばかりかが条件になると思います

**Comment by goki90210** [comment]
メジャーアップデートはほぼほぼマイグレーション作業が発生するので慎重にですね。

**Comment by goki90210** [comment]
一応、公式にはIE11はサポートしないことになっていますが、
TypeScript 4.0になることでいよいよIE11では動作しなくなります。

本当に良いのですね？

**Comment by kaizumaki** [comment]
@goki90210 ご指摘ありがとうございます。そうなんですね。現実的にIE11で動かなくなるのは困ってしまいますね。
現在はIE11で動いていますが、将来的に動かなくなる可能性があるということですか？
例えばどんなメソッドを使用すると動かない、とか詳細が書かれているドキュメントがあればご提示いただけると助かります 🙏 
ちなみにこちらのドキュメントは見ました。
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#breaking-changes
この「old versions of IE」の中にIE11は含まれていないと認識していますが、違っていますでしょうか...？

**Comment by goki90210** [comment]
https://codezine.jp/article/detail/12759

> なお、重大な変更点としては、lib.d.tsにおけるDOM型において、旧バージョンのInternet Explorerのみで動作する機能が削除された

とありますが、これはIE10以前のことですね…。

**Comment by kaizumaki** [comment]
@goki90210 ご提示ありがとうございます。私も勉強になりました。いずれにせよ、ライブラリのアップデートは慎重にやりますね。

**Comment by munierujp** [comment]
ところで、[推奨環境](https://stopcovid19.metro.tokyo.lg.jp/about)にはIEの記載はなく「Microsoft Edge 最新版」とありますが、本サイトの要件にIEは入っているのでしょうか？

**Comment by kaizumaki** [comment]
@munierujp そうですね。以前こちら https://github.com/tokyo-metropolitan-gov/covid19/issues/2444#issuecomment-605319025 でコメントしたことがあるのですが、IE11対応はオーナーである東京都の要望なのです。ですので、要件に入っていると言っていいと思います。ただ https://github.com/tokyo-metropolitan-gov/covid19/issues/2444#issuecomment-605319025 にも書いていますが、実際、IE11に対応しているとは言い切れない表示上のバグはたくさんあるので、推奨環境には書かずにおいています。

**Comment by mcdmaster** [comment]
たぶん、これのトップにあるネタはもうほとんど遭遇しなくなったので、クローズします。

ブラウザ委rストについては、別イシューでお願いいたします
