### ISSUE TITLE
huskyのESLintがこけてコミットできない

### ISSUE THREAD

**Issue by kawoka** [tokyo-metropolitan-gov/covid19#539]
## 改善詳細 / Improve details

下記ファイルがpre commit scriptのlint errorでコミットできませんでした。

```
components/DataView.vue
components/DesktopFlowSvg.vue
components/ListItem.vue
components/PageHeader.vue
components/TimeStackedBarChart.vue
components/WhatsNew.vue
layouts/default.vue
pages/flow.vue
pages/index.vue
```

## 期待する見せ方・挙動 / Expected behavior
pre commit scriptが走った状態でコミットできるようになること

## 動作環境・ブラウザ / Environment
*

**Comment by kawoka** [comment]
これらのfileを修正しようとすると余計なdiffが含まれてしまい、コントリビューターもレビュアーもコストが上がってしまいます。。
より多くのコントリビューターの方々がコントリビュートしやすくするために、修正できると嬉しいです！:bow:

**Comment by yokinist** [comment]
@kawoka 
issue&対応ありがとうございます！すでにあるPRとの兼ね合いもあるので今あるPRのなかで取り込めそうなものを取り込んでから #515 を取り込む予定です！尚、明日の朝に確認済のPRなど含め多くがマージされると思うので、もうしばらくお待ちください :bow:

**Comment by kawoka** [comment]
@yokinist 
ご確認ありがとうございます！！
承知いたしました！大きなPRになってしまったので、コンフリクト解消など、

**Comment by yokinist** [comment]
今、取り込むタイミングについてチームで確認中です！

**Comment by kawoka** [comment]
@yokinist
ありがとうございます！取り急ぎコンフリクトの解消いたしました。
https://github.com/tokyo-metropolitan-gov/covid19/issues/576
こちらの `flow.vue` の件など、対応必要であれば対応いたしますのでご指摘いただければと思います！
よろしくおねがいいたします。

**Comment by yokinist** [comment]
v3ださきほどリリースされたのと品質に関わる部分なので早めがいいということで、取り込むことになりました！コンフリクトについては担当者が直してもらうといった流れになるかと思います！取り急ぎ共有です
