### ISSUE TITLE
フォントとか余白とかの調整

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#54]
デザインとくらべ、揃ってないので修正する必要あり
https://www.figma.com/proto/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=121%3A709&scaling=min-zoom

**Comment by kaizumaki** [comment]
variables.scssでフォントサイズを３〜４種類、変数で用意するのがいいですかね。余白はvuetifyに備わっているclassを限定して使うといいと思います。
