### ISSUE TITLE
[Suggestion] Autoprefixer@10 への対応方針

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#5432]
## 改善詳細 / Details of Improvement
- #5431 で起きている、`Autoprefixer` 9.x -> 10.0.0 へのアップグレード・エラーについての対処案

## スクリーンショット / Screenshot
(snipped)

## 期待する見せ方・挙動 / Expected behavior
- `Autoprefixer` は、今後は `Nuxt.js` バンドル版を使用する。参考：
https://nuxtjs.org/api/configuration-build/#postcss

> **Note**: `Nuxt.js` has applied `PostCSS` Preset Env. By default it enables Stage 2 features and `Autoprefixer`, you can use `build.postcss.preset` to configure it.

・バンドル版の使用に伴い、`package.json` から `autoprefixer` エントリをドロップする
・バンドル版を使うことで、 #5237 などで議論された更新負荷の軽減に寄与する
・言うまでもなく、`@9.x` からの機能は継承されること
※詳しい方のお力添えをいただきたいです…。`jest` でテストケースを書いてテストしてもいいかも

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster ご提案ありがとうございます！方向性としては私は賛成です。とりあえず #5431 はクローズしておきますね。
