### ISSUE TITLE
「検査陽性者の状況」カードに外部リンク設置

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5438]
「検査陽性者の状況」カードに、東京都福祉保健局HPの「死亡日別による死亡者数の推移」ページへのリンクを追加します。

- テキスト： `死亡日別による死亡者数の推移はこちら`
- URL：https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/shibou.html
（※9/16 12:55現在、リンク先は404です。いつオープンするかは未定です。）
- 位置：以下の画像のとおり

リンクボタンのデザインは、「モニタリング項目」の「最新のモニタリング項目の分析・総括コメントについて」ボタンと同様です。
<img width="469" alt="検査陽性者の状況カードに外部リンク設置" src="https://user-images.githubusercontent.com/14883063/93290562-f9625d00-f81b-11ea-954d-ba1614901e8d.png">

**Comment by yuu26jp** [comment]
対応します。
