### ISSUE TITLE
チャットボットの表示を抑制できない

### ISSUE THREAD

**Issue by tokyo-citizen** [tokyo-metropolitan-gov/covid19#5452]
## 起こっている問題 / The Problem
- チャットボットをクローズしても再度表示され続けるためサイト閲覧の妨げとなる

## スクリーンショット / Screenshot
- 平易に再現可能のためなし

## 期待する見せ方・挙動 / Expected Behavior
- チャットボットをクローズした場合に表示が抑止される

## 起こっている問題の再現手段 / Steps to Reproduce
1. Webブラウザで[https://stopcovid19.metro.tokyo.lg.jp](https://stopcovid19.metro.tokyo.lg.jp)にアクセスする
2. チャットボットをクローズする
3. スクロールする
4. チャットボットが表示される

## 動作環境・ブラウザ / Environment
- macOS / iOS
- Safari

**Comment by kaizumaki** [comment]
@tokyo-citizen ご指摘ありがとうございます！チャットボットは対策サイトとは別に担当課があります。こちら #5455 にまとめましたのでお読みいただければと思います。
こちらのご指摘については今回は私のほうから報告いたしましたので、issueをクローズさせていただきますね。
