### ISSUE TITLE
チャットボットで英語表示したときに、日本語表示のままの所がある

### ISSUE THREAD

**Issue by lacrosse91** [tokyo-metropolitan-gov/covid19#5454]
## 改善詳細 / Details of Improvement
- 日本語対応のサイトでチャットボットを開き、英語を選択しても「はじめから」というボタンは日本語のままになっている。
- 「beginning」や「back」のような単語に変更をしたほうがよいのではないでしょうか。
## スクリーンショット / Screenshot

日本語選択時
<img width="594" alt="スクリーンショット 2020-09-18 0 51 11" src="https://user-images.githubusercontent.com/19372617/93496907-c5d22080-f94a-11ea-9b09-2e95df325566.png">
---
英語選択時
<img width="593" alt="スクリーンショット 2020-09-18 0 51 27" src="https://user-images.githubusercontent.com/19372617/93496935-cd91c500-f94a-11ea-8461-2d7d614bf79e.png">

## 期待する見せ方・挙動 / Expected behavior
- 英語対応にしたときに、「はじめから」というボタンを英語表示にする
## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
@lacrosse91 ご提案ありがとうございます！チャットボットは対策サイトとは別に担当課があります。こちら #5455 にまとめましたのでお読みいただければと思います。
こちらのご提案については今回は私のほうから報告いたしましたので、issueをクローズさせていただきますね。

**Comment by lacrosse91** [comment]
しっかり確認せず申し訳ありません。
また、報告してくださりありがとうございます。
