### ISSUE TITLE
[performance] materialdesignicons.min.css のダイエット

### ISSUE THREAD

**Issue by Jxck** [tokyo-metropolitan-gov/covid19#546]
## 改善詳細 / Improve details

* materialdesignicons.min.css がほとんど使われてない模様
* しかしサイズがそれなりにあり redering を邪魔している

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/322289/76000429-0934e680-5f47-11ea-85ff-d7aac62d0e84.png)

## 期待する見せ方・挙動 / Expected behavior

* materialdesignicons を使っているものだけにビルドするなりできれば、パフォーマンス改善になると思われる
* おそらく '@nuxtjs/vuetify' から読まれていると思われるのでこれをなんとかできればよさそう

## 動作環境・ブラウザ / Environment
* Mac Book Pro
* Chrome 80

**Comment by amotarao** [comment]
現状読み込まれている [Webフォント](https://cdn.jsdelivr.net/npm/@mdi/font@latest/fonts/materialdesignicons-webfont.woff2?v=4.9.95) が gzip されておらず、276KBもありますね

一旦サイト持ちにするだけでも Netlify が gzip してくれるので読み込みが早くなりそうです
https://vuetifyjs.com/en/customization/icons#install-material-design-icons

この場合、フォントデータから不要アイコンの削除までは簡単にはできなさそう。

**Comment by amotarao** [comment]
[Material Icon Font で必要なアイコンだけ読み込む - Qiita](https://qiita.com/macoshita/items/aae7bcbe86363064f426) 
このような記事もありましたが、 Material Icons と Material Design Icons は違うようで... 🤔 

https://fonts.googleapis.com/icon?family=Material+Design+Icons
こちらは 400になってしまいました

**Comment by amotarao** [comment]
https://vuetifyjs.com/en/customization/icons#install-material-design-icons-js-svg
svg で読み込めば必要なアイコンのみ扱うのが簡単そうでした

**Comment by amotarao** [comment]
https://vuetifyjs.com/en/customization/icons#install-material-design-icons-js-svg

こちらの `@mdi/js` について

- 必要なアイコンのみのインポートが不可能
- svg の height width が 24px 決め打ちなので別でサイズ変更する必要がある
- color が反映されてない

のでよくなさそうでした

**Comment by amotarao** [comment]
https://vuetifyjs.com/en/customization/icons#install-material-design-icons
`@mdi/font` をローカルに入れても CDN の materialdesignicons.min.css が読み込まれてしまう仕様
https://github.com/nuxt-community/vuetify-module/blob/master/src/icons.ts

vuetify-module に関連Issue有り
https://github.com/nuxt-community/vuetify-module/issues/290

**Comment by Jxck** [comment]
materialdesign とそこから読まれてる roboto font などが、最適化されないまま CDN から来てるので、プラグイン経由をやめて、自前で material design 関連のアセットを配布/設置するというのもありかもしれません。
ただ vuetify を抜くのがどの程度の影響があるか読みきれてないので、やるならそれなりに調整が必要そうです。

**Comment by amotarao** [comment]
ローカルインストールしているのに CDN読み込みしている点の解消は Vuetify というより @nuxt/vuetify が原因なので解決待ちですかね...。
Issue は投げときました。 https://github.com/nuxt-community/vuetify-module/issues/294

アセットの最適化は Vuetify 残したままでもできることだと思いますので、いい方法を探っていきたいですね

**Comment by Jxck** [comment]
すいません、まだ nuxt/vuetify の構成が把握しきれてないのですが、既にフォントはローカルにあるんでしょうか？
もしあるなら、それを static などに置いて、 nuxt.config.js では

```
    ['@nuxtjs/vuetify', {
        defaultAssets: {
          icons: false,
          font: false
        }
      }
    ],
```

として CDN のリンクを吐かないようにし、 link タグを自分で書けば、ローカルのを読むことができるという理解で良いでしょうか？

**Comment by Jxck** [comment]
それとは別に、やはり mdi に移行して treeshake させる方が良さそうではありますね。

**Comment by Jxck** [comment]
すいませんが、土日は作業ができなさそうなので、こちらは手放させていただきます。

**Comment by amotarao** [comment]
`defaultAssets.icon = false` で CDN読み込まないようにできましたね :sweat_drops:
Vuetify 自体にそのような指定方法がなかったので勘違いしてしましました。
ご指摘ありがとうございます。

ローカルにインストールしたのは手元で試しただけですので、現リポジトリにはありません。
一旦、読み込みの最適化のためにもCDN読み込みをしないようにしてみます。
