### ISSUE TITLE
Vue@3.0.0 対応

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#5463]
## 改善詳細 / Details of Improvement
- タイトルのとおりです。
- ユーザ目線で注目すべきは、IE11 対応を 2020/4Q (2020/10-12) の期間に予定しているというところです。

## スクリーンショット / Screenshot

こちらをどうぞ。RC も Beta もつかない正真正銘 Vue@3.0.0 です。One Piece って何でしょうね(笑)
https://github.com/vuejs/vue-next/releases/tag/v3.0.0

## 期待する見せ方・挙動 / Expected behavior
- 現行 2.x の機能が損なわれないこと
- アップグレードに伴う明確なメリット、特にユーザ・エクスペリエンスにおけるそれが見られること
※パフォ改善等
- IE11 対応

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
そんなこんなのうちに、webpack@5 が GA になっていたりします。
https://webpack.js.org/blog/2020-10-10-webpack-5-release/

`vue@3` と `webpack@5` のそれぞれのメリデメを評価したうえで機能の取捨選択をするというのがおそらくプロの仕事なんでしょう。ただ、個人的には以下の要件を優先したいと考えています。
- パフォーマンス向上、具体的にはレンダリング速度の向上
- コーディングの「お作法」の急激な変更をもたらさない
- でも、コーディングが楽になるならオーケー
- 統合できるものは統合する（モジュール名が `vue` なんちゃらとか `nuxt` なんちゃらとかのモノ）
- 統合先は、`nuxt` を想定（たとえば `vue-property-decorator` じゃなく `nuxt-property-decorator` にする、など）
- `vue@3` 以降に実装されなくなる機能の代替（イベントハンドラ系など）

いずれにしても、上記をビッグバン的に一気にやるのは実現性が乏しいです。現行の `vue@2` + `webpack@4` にも既にある機能から徐々に移行していけるといいかと思います。
いかがでしょうか？

差し当たっては、私としては以下の PR を上げてみたいです。
- `vue-meta` の `nuxt` への統合、および‘ `package.json` からのエントリ削除
- イベントエミッタ（`$on`, `$off`）の、`vue@3` に向けたリニューアル

**Comment by kaizumaki** [comment]
@mcdmaster フォローありがとうございます！要件的には私も賛成です。
あまりガチガチな感じでパーフェクトを目指さず、しかしながら将来的には `vue@3` に移行できるようにしていきたいです。もちろん、パフォーマンスの向上も考慮しないといけないですね。
というわけで、私も様子をみながらなので、できる限り小分けにしてPRを上げてもらえると助かります 🙏

**Comment by mcdmaster** [comment]
これは長期戦になりそうなので、PR で追跡する代わりにこちらはクローズしますね
