### ISSUE TITLE
ナビゲーションメニューのスクロールをし続け、天井、もしくは底につくとメインコンテンツをスクロールする

### ISSUE THREAD

**Issue by mokuzuu** [tokyo-metropolitan-gov/covid19#547]
## 起こっている問題 / Occurred problem
理想の挙動を把握してないのですが、ナビゲーションメニューをスクロールし続け、天井もしくは底につくとメインコンテンツを同じ方向にスクロールしています。

## スクリーンショット / Screenshot
![scrollOverflow](https://user-images.githubusercontent.com/41939914/76003811-4c498680-5f54-11ea-9138-94c6316142d1.gif)

## 期待する見せ方・挙動 / Expected behavior
できればナビゲーションメニューをスクロールしているときにはメインコンテンツはスクロールしたくないのが一般的かなと。

## 起こっている問題の再現手段 / Steps to reproduce
アプリを起動し、ナビゲーションメニューを一方向にスクロールしつづける

## 動作環境・ブラウザ / Environment
windows 10 chrome

**Comment by nake226** [comment]
> ## 動作環境・ブラウザ / Environment
> windows 10 chrome

こちら、macのchromeで確認しましたが再現しませんでした。
windows固有のものかもしれません。ご参考まで。

**Comment by mokuzuu** [comment]
windowsのfirefoxで確認してみたらさらに変な挙動でした。。。
底に着いたとき、すぐにメインコンテンツがスクロールされることはありませんでしたが、時間をおいてスクロールされました。
スクロール下方向
メニュー　→　メインコンテンツ　
そのままスクロール上方向
メインコンテンツ　→　メニュー
という感じでスクロールしていきました。。。
macでも少し長めにスクロールしたら挙動は変わるのでしょうか。
gif貼っておきます
![scrollOverFlow2](https://user-images.githubusercontent.com/41939914/76005555-ec081400-5f56-11ea-9742-8496635bbdc7.gif)

**Comment by nake226** [comment]
これはひどい、寝ぼけ眼で笑ってしまいました。笑
スクロールする頻度と回数を考えると費用対効果的に二の足を踏みますね‥

**Comment by mokuzuu** [comment]
ですねー笑
優先順位的にはそんなに高くないですね。

**Comment by miiiii-ide** [comment]
Macユーザーです。
Chorme, FireFox, Edge Betaで、ナビゲーションメニューを下部までスクロール→放置してもGifのような挙動は見えませんでした。ご参考までに...

**Comment by Yu0614** [comment]
Mac ユーザーです。

Chrome で現象再現確認しました。参考のため動画も添付しておきます。
以下環境情報と 再現？方法です。

◆ 環境

* macOS Catarina 10.15.3
* 80.0.3987.122（Official Build） （64 ビット）

◆ 再現方法

1. 左側のコンテナ (具体的には`<div class="naviContainer">` ) が すべて表示されていない状態にする （タブの大きさを小さくする etc...）

2. 左側のコンテナ及び メインコンテナで それぞれ 最上部までスクロール

3. 左側のコンテナで 最下部までスクロール、そのままスクロールし続ける

4. 本来動いてほしくない メインコンテナでもスクロールされる  (現象再現)


◆ 動画
[AwesomeScreenshot-2020-3-6-1583466813534_covid19_tokyo-metropolitan-gov.webm.zip](https://github.com/tokyo-metropolitan-gov/covid19/files/4296376/AwesomeScreenshot-2020-3-6-1583466813534_covid19_tokyo-metropolitan-gov.webm.zip)

**Comment by pppp606** [comment]
正確にはメインコンテンツ `<div class=mainContainer>`がスクロールするのではなく
ページ全体 `<html>`がスクロールしている状態です。
そのため下記の通り `html` のスクロールを止め、`.mainContainer` をスクロールさせる形にstyleを設定すると、問題の挙動はなくなります。

```css
html{
  overflow-y: hidden;
}
.mainContainer{
  overflow-y: auto;
  height: 100vh;
}
```

ただサイトの性格上、推奨環境ブラウザ以外で多少表示が崩れても最低限の閲覧性を確保したいという意味では、ルートの html を`overflow-y: hidden;` にするのは不安が残ります。
その点判断を頂いたほうが良いかと思います。

**Comment by mokuzuu** [comment]
こちら、windows chrome, firefoxで解決しました。
解決策としては、layouts/default.vueに `overscroll-behavior: contain;` を下記のように追加します。
```
@include largerThan($small) {
  .naviContainer {
    grid-column: 1/2;
    position: fixed;
    top: 0;
    overflow-y: auto;
    width: 240px;
    height: 100%;
    overscroll-behavior: contain;
  }
}
```

下のURLに `overscroll-behavior: contain;`の詳細が載っています。おそらくsafariでも動くと思いますが、macを持っていないので、申し訳ないのですがだれかmacで試していただけたら嬉しいです！

https://developers.google.com/web/updates/2017/11/overscroll-behavior

**Comment by ypresto** [comment]
PRにしていただけるとnetlifyのデプロイ結果で簡単に確認できる、気がしております・・！

**Comment by mokuzuu** [comment]
なるほど。。。OSSが初めてなので慣れていませんでした('◇')ゞ
PR作らせていただきます！

**Comment by mokuzuu** [comment]
#778 
でPRを開きました！よろしくお願いします

**Comment by ypresto** [comment]
ありがとうございます！netlifyのdeployが終わったらiPad、Mac、iPhone Simulator、Android Chromeで確認させていただきます

**Comment by ypresto** [comment]
- iPadOS 13.3.1 Safari: 左のみ、スクロールの終端に達して、**完全に停止している状態**で終端方向へスクロールしようとすると、右がスクロールします。また右が慣性スクロール中に左をスワイプすると、右側がスクロールされます。
- iPadOS 13.3.1 Chrome: 左右のスクロールは完全に独立。右が慣性スクロール中に左をスワイプすると、右側がスクロールされます。
- macOS 10.15.3 Chrome (stable): 左右スクロールは完全に独立。
- macOS 10.15.3 Safari 13.0.5: iPadOS Safariに同じ、ただし右の慣性スクロール中に左をスクロールもできます		
- iPhone Simulator 13.1 Safari（横）: iPadOS Safariに同じ
- Android 10 (OnePlus 6 Oxygen OS Beta 33) Chrome (stable) （横）: 左右スクロールは完全に独立。

左：ナビゲーションメニュー、右：メインコンテンツ

**Comment by mokuzuu** [comment]
なるほど。。。
CDNでoverscroll-behaviorの対応状況を調べたところ、safariでは対応してないみたいですね。
![image](https://user-images.githubusercontent.com/41939914/76146660-59937c00-60e0-11ea-84cd-4e790ab76653.png)

**Comment by ypresto** [comment]
あとこれはなぜだかわからないのですが、iPad or iPhoneで左を慣性スクロール中に終端の向こう側へスワイプする（バウンススクロールする）とスクロール位置がバウンスを無視していきなり0に戻るケースがありました。繰り返しやると↓みたいになります。
![ezgif com-optimize](https://user-images.githubusercontent.com/400558/76146666-0ae1e400-60d8-11ea-80ae-2cb6e130632e.gif)

**Comment by mokuzuu** [comment]
> あとこれはなぜだかわからないのですが、iPad or iPhoneで左を慣性スクロール中に終端の向こう側へスワイプする（バウンススクロールする）とスクロール位置がバウンスを無視していきなり0に戻る謎挙動がありました。繰り返しやると↓みたいになります。（慣性スクロールが完全に止まった後のスワイプはメインコンテンツがスクロールします
> ![ezgif com-optimize](https://user-images.githubusercontent.com/400558/76146666-0ae1e400-60d8-11ea-80ae-2cb6e130632e.gif)

なぞですね。。。簡単な解決策であれば、ナビゲーションメニューのバウンススクロールを無効にできれば解決できると思います。

**Comment by mokuzuu** [comment]
safariでの解決策を考えますね！

**Comment by mokuzuu** [comment]
私の開発端末がwindowsなこともあり、safari対応が難しいです。。。、対応できる方募集中です(+_+)

**Comment by ypresto** [comment]
Safariでメインコンテンツの方がスクロールされるのは、「スクロールの終端に達して、**（バウンススクロールが）完全に停止している状態**」が条件なので、Windows（は止まるという概念ないですよね・・？）よりは大丈夫な挙動かなぁと思っております。個人的にはこのままmergeでもいい気がしてきました。

**Comment by mokuzuu** [comment]
なるほど。。。ではこのままmergeを待ちましょうか(^o^)
