### ISSUE TITLE
チャットボット画像の表示位置を、iPhoneのセーフエリアにかぶらないようにする

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#5471]
## 改善詳細 / Details of Improvement
- iPhone X / 11 などのホームボタンがないiPhoneでの表示時に、チャットボットの画像がセーフエリアに入っていしまいホームインジケーターにかぶってしまっている

## スクリーンショット / Screenshot
<img src=https://user-images.githubusercontent.com/1301149/94088924-a6f0f400-fe4c-11ea-99ec-24c5b21ec346.jpeg width=30%>

## 期待する見せ方・挙動 / Expected behavior
- セーフエリアを避けて配置する
- `safe-area-inset-bottom` を追加すればセーフエリアの高さをよしなに挿入してくれると思います

ex)
```
#chat_banner {
  bottom: calc(10px + constant(safe-area-inset-bottom)); // iOS 11.1以前用
  bottom: calc(10px + env(safe-area-inset-bottom)); // iOS 11.2以降用
}
```
<img src=https://user-images.githubusercontent.com/1301149/94089369-f71c8600-fe4d-11ea-9498-efa8d45cf65d.png width=30%>

## 動作環境・ブラウザ / Environment
- iOS Safari （13.5にて確認）

**Comment by saladdays** [comment]
このposition指定がチャットボット側のコードで生成されている場合は対応が難しいかもしれません

**Comment by kaizumaki** [comment]
@saladdays さん、ご提案ありがとうございます！チャットボットのご提案については #5455 に書いているのですが、担当課がありまして、そこからベンダーさんに連絡がいくようになっています。
みたところ、ベンダーさんのスクリプトからstyleが読み込まれているようなので、 @saladdays さんのご提案も担当課にご連絡いただくほうが早いと思います 🙇‍♀️

**Comment by kaizumaki** [comment]
こちらはいったんクローズさせていただきますね。
