### ISSUE TITLE
相談ページを作る

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#55]
このリンク先。

![image](https://user-images.githubusercontent.com/16509/75620788-90453000-5bd0-11ea-9d4d-847bd874a725.png)

そもそもこれはメニューになくて良いのでしたっけ？

**Comment by halsk** [comment]
あー、これはたぶん「感染症が心配な方へ」の内容ですね。
これのフローチャートなので。
チャート以外にも色々入ってるから、どこまでこちらのページで持つのか考えないといけない。。
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html

**Comment by yokinist** [comment]
ページ内リンクにで飛ぶ
画像となにかしらの情報がはいったページを用意する必要あり
残りのコンテンツは決まり次第進めていく
