### ISSUE TITLE
package-lock.json の取り扱い

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#551]
## 質問
このレポジトリでは，`package-lock.json` の取り扱いはどのようにされていますか？

`package-lock.json` を Git で管理する・しないについては議論・流派・メリット・デメリットがありますが，方針はあるのでしょうか．

質問の背景としては，
*   #523 対応のために新たに `npm install` したい
*   このレポジトリに `package-lock.json` が存在せず，それならば `.gitignore` に `package-lock.json` が記載されているのだろう…と思ったが，そうではなかった
という感じです．

宜しくお願い致します．

**Comment by nard-tech** [comment]
##  追記

issue の template に「質問」もあるとありがたいです．
（私作りましょうか？）

**Comment by kawoka** [comment]
yarn.lockが入っているので、バージョンのロックはyarnでやっていそうな雰囲気がありますね！

**Comment by nard-tech** [comment]
あ，yarn なのにいつもの癖で `npm install` してたのがよくなかったですね…
失礼しました．
