### ISSUE TITLE
電話番号のスタイルをタップ可能であることが直感的に分かるようにする

### ISSUE THREAD

**Issue by Shagamii** [tokyo-metropolitan-gov/covid19#553]
## 改善詳細 / Improve details
* モバイルの電話番号をタップすると電話をかけることができるが他のテキストと同様のスタイルになっているため視覚的にタップ可能であることが分かりにくくなっている

## スクリーンショット / Screenshot
<img width=320 alt=電話番号 src=https://user-images.githubusercontent.com/18458057/76009988-794a6900-5f55-11ea-994e-2e5ea4fb6df3.png />

## 期待する見せ方・挙動 / Expected behavior
* アンダーライン等、電話番号が直感的にタップ可能であることが分かる

**Comment by nard-tech** [comment]
着手します

**Comment by nard-tech** [comment]
こんな感じでいかがでしょうか
![Screenshot 2020-03-06 04 26 44](https://user-images.githubusercontent.com/23148331/76017895-b79a5500-5f62-11ea-89ce-5464a9fe87bb.png)
![Screenshot 2020-03-06 04 26 52](https://user-images.githubusercontent.com/23148331/76017901-b9641880-5f62-11ea-802f-76b684a95fe5.png)

**Comment by nard-tech** [comment]
## その他
「新型コロナ受診相談窓口」について
*   背景色は，PC画面に合わせて少し薄くしました．
*   「平日（夜間）」に合わせ，「平日（日中）」のレイアウトと文言を修正しています．

**Comment by nard-tech** [comment]
とりあえずPRは作らないでおきます．

**Comment by Shagamii** [comment]
もしかしたら別issueにした方がいいかもしれませんが、文言の修正良いと思います！

背景色に関しては、#576 にあるように変更が行われるようですので、そちらでのbg colorをもとに修正する形で良いのではないかなと思いました！

また、本題の電話番号のスタイルに関しては、他のサービスでも多くみられるようにanchorのスタイルを適応して、下線を引く程度でいいのではないかなと思いました。
このサービスでは、ボタン要素はscroll toのようなアクション的な場合に用いられているような印象を受けますのでそういった考えもあります。
デザインに関しては、もう少し検討・議論を受け付けたいですね🤔

**Comment by nard-tech** [comment]
@Shagamii 
#576 の件，承知しました．

電話番号のスタイルですが，もともとの実装と修正の内容・意図を補足の上でご説明したいと思います．
ソースを見ていただければわかる通り，もともと画像を埋め込んでいるんですよね．

cf. https://github.com/tokyo-metropolitan-gov/covid19/blob/development/static/flow/sp/sp_flow_tel_01%402x.png

本来であれば，
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/static/flow/sp/sp_flow_04_nav%402x.png
のように画像に枠線・影を追加するのが望ましいとは思いましたが，それはそれで手間がかかるので，CSSで「押せるボタン」っぽさを表現しています．

ご意見にあった，画像を使わないようにして
> anchorのスタイルを適応して、下線を引く程度

にすると，重要な情報である電話番号の強調ができなくなってしまいます．
最初の作成者もおそらくそういう意図でわざわざ画像にして埋め込んだと思いますので，私が実装したボタンっぽいデザインの方がよいのではないかと思っています．

**Comment by Shagamii** [comment]
ここでなぜ画像を埋め込んでいるかというのは、 https://github.com/tokyo-metropolitan-gov/covid19/issues/157#issuecomment-593730089 にあるように、まず最初の段階でいかに早くデザイン通りにリリースするかといったことが考えられ、工数を削減するために取られた処置のようです。
また、#576 #659  の文脈で /flow ページの画像部分をHTMLに書き直すといったことが行われています。

ゆえに、この電話番号箇所の実装は、anchorと電話のicon(fontawesome?) + テキストで実装され直すことが予想されます。
そのため、この箇所はanchorのスタイルである下線が引かれることになると思われますので、そちらで実装もしくは実装の過程( #736  )で、電話番号がタップ可能であることが分かりにくいデザインである場合に再度提案していくという形でどうでしょうか？

**Comment by Shagamii** [comment]
指針が示されました https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596079517 のでクローズさせていただきます！

**Comment by nard-tech** [comment]
@Shagamii 承知しました．ありがとうございます．
