### ISSUE TITLE
最終更新日時が正しくない

### ISSUE THREAD

**Issue by myakura** [tokyo-metropolitan-gov/covid19#5537]
## 起こっている問題 / The Problem
- 「都内の最新感染動向」横の「最終更新」の日時が、このバグ報告時点で未来の日時を指しています

## スクリーンショット / Screenshot

![スクリーンショット：最新動向ページを表示したChromeとWindowsのタスクバー](https://user-images.githubusercontent.com/413984/96399771-22568300-120a-11eb-8259-641e899df866.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正しい最終更新日時が表示されている

## 起こっている問題の再現手段 / Steps to Reproduce

現時点ではアクセスするだけですが、表示されている日付の時刻以降では確認できなくなるはずです

## 動作環境・ブラウザ / Environment
- Windows, ChromeOS
- Chrome, Firefox

**Comment by kaizumaki** [comment]
@myakura ご指摘ありがとうございます！こちら、東京都の入力データが間違っている可能性があります。調査いたしますので、しばらくお待ちください。

**Comment by kaizumaki** [comment]
@myakura やはり東京都側の元データの入力ミスでした。本来入力したかった「11:00」に修正して反映しました。ご報告感謝です！

**Comment by myakura** [comment]
@kaizumaki データ側の問題だったのですね。ありがとうございます！
