### ISSUE TITLE
「発症前２週間以内」という表現の改善の提案

### ISSUE THREAD

**Issue by task-jp** [tokyo-metropolitan-gov/covid19#554]
## 改善詳細 / Improve details
* 発症しているかどうかわからない状態の方が対象なので、「発症前」という表現は適切ではない。

## スクリーンショット / Screenshot
<img width="577" alt="新型コロナウイルス感染症が心配なときに___東京都_新型コロナウイルス感染症対策サイト" src="https://user-images.githubusercontent.com/5221601/76011270-9f710880-5f57-11ea-8d18-aa07200a5164.png">

## 期待する見せ方・挙動 / Expected behavior
* ここ２週間以内の
* 直近２週間の

**Comment by shinchit** [comment]
本件、対応します！

**Comment by mikkame** [comment]
ご提案ありがとうございます！
実装に関しましては一度 #576 をご確認いただきたいです

**Comment by shinchit** [comment]
@mikkame さん、ありがとうございます。
確認しました。本件は動かないようにしておきますね。

**Comment by halsk** [comment]
こちらは、都側のレビュー済のテキストですので変更は無しでお願いします。クローズさせていただきます。
