### ISSUE TITLE
スマホで陽性患者の属性が崩れる

### ISSUE THREAD

**Issue by tyouuu3** [tokyo-metropolitan-gov/covid19#5540]
## 起こっている問題 / The Problem
・スマホ表示、陽性患者の属性で年代に"10歳未満"が含まれる場合、表示が崩れる。

## スクリーンショット / Screenshot
![stopcovid19](https://user-images.githubusercontent.com/72135670/96535642-3a430b00-12cd-11eb-934c-f5853c2c426e.png)

## 期待する見せ方・挙動 / Expected Behavior
・"10歳"と"未満"の、２段で表示する。

## 起こっている問題の再現手段 / Steps to Reproduce
・スマホで陽性患者の属性の"10歳未満"を表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@tyouuu3 ご提案ありがとうございます！
たしかにご指摘の箇所は見た目は美しくないのですが、データから読み込んでいる要素に改行をいれるのは難しいですね。改行をいれるロジックを書くのもよくないような気がします。
文字列の見た目を整えるのであれば、逆に文字列を `white-space: nowrap;` で「折り返さない」ようにするのが得策かと思います。また、そのようにすると全体的に横幅がはみ出るので、そこは横スクロールを表示させる（現在すでに `overflow-x: auto;` になっています）のがよいかと思いますが、いかがでしょう？

**Comment by munierujp** [comment]
FYI: 英語だとより長くなるので、こんな感じです。

<a href="https://user-images.githubusercontent.com/20086673/96602395-efa5ab00-132d-11eb-9ffb-fdeefff313d6.png">
<img src="https://user-images.githubusercontent.com/20086673/96602395-efa5ab00-132d-11eb-9ffb-fdeefff313d6.png" width="300">
</a>

**Comment by munierujp** [comment]
この手のテーブル（あらかじめ表示内容が決まっていないもの）は、スマホ（ビューポートの横幅が狭い場合）では折り返しを無効（`white-space: nowrap;`）にしたほうが見やすいように思います。

<details>
<summary>英語版で折り返しを無効にした例（クリックで展開）</summary>

![画面収録 2020-10-20 23 49 18](https://user-images.githubusercontent.com/20086673/96604048-9e96b680-132f-11eb-9711-0338d31f6aed.gif)

</details>

一覧で表示する項目を一部に留め、クリックしたときに詳細を表示するというアプローチもありますが、少なくともこのテーブルでは項目の内容的に適さないかと思われます。

cf. 
[Data table component — Vuetify](https://vuetifyjs.com/en/components/data-tables/#expandable-rows)

**Comment by kaizumaki** [comment]
@munierujp フォローありがとうございます！こちら https://github.com/tokyo-metropolitan-gov/covid19/issues/5251#issuecomment-709673066 にあるように項目追加の要望もあり、ぜひ実現したいので、このissueについてはご指摘の通り折り返しを無効にして横スクロールを表示させるのが現実的だと思っています。
ただ現在 #5293 のオープンデータAPI取得実装が進行中で（確認事項が多く、遅々として進まない状況ではあるのですが）、そちらをリリースしてからの対応にしたほうがいいかなと考えています。

**Comment by kaizumaki** [comment]
@tyouuu3 #5676 で横スクロールするように実装いたしました。ご指摘の内容は解消されたと思いますので、こちらクローズさせていただきます。もし、まだ解決に至っていない場合は再オープンしていただいてかまいません。
