### ISSUE TITLE
スマホ表示の場合，都営線・都庁来庁者のグラフが見づらくなる

### ISSUE THREAD

**Issue by Meiryo7743** [tokyo-metropolitan-gov/covid19#5542]
## 起こっている問題 / The Problem

スマートフォンでページを閲覧する際，**都営地下鉄の利用者数の推移**と**都庁来庁者数の推移**のグラフが縦横ともに窮屈な表示になっており，見づらくなっています。

開発者ツールで確認したところ，PC 表示とスマホ表示では当該グラフの `height` が異なる値を示していました。恐らくですが，Chart.js のレスポンシブ設定が悪さをしているのではないかと思われます。

### スマホ表示

<img src="https://user-images.githubusercontent.com/46659204/96565204-0aacf680-12ff-11eb-8024-1ebe29cbbc68.png" width="50%" alt="都営線グラフ（スマホ）"><img src="https://user-images.githubusercontent.com/46659204/96564814-91150880-12fe-11eb-8b6a-adf7423cac49.png" width="50%" alt="都庁グラフ（スマホ）">

### PC 表示（参考）

<img src="https://user-images.githubusercontent.com/46659204/96565665-a2124980-12ff-11eb-8646-a7b099bf5d7f.png" width="50%" alt="都営線グラフ（PC）"><img src="https://user-images.githubusercontent.com/46659204/96564805-8fe3db80-12fe-11eb-82c8-a462e849b435.png" width="50%" alt="都庁グラフ（PC）">

## 期待する見せ方・挙動 / Expected Behavior

-   当該グラフの `height` を PC 表示と同じ値に設定する
-   可能であれば，グラフを横スクロールできる形に変更する

## 起こっている問題の再現手段 / Steps to Reproduce

1. スマートフォンでページを表示する

## 動作環境・ブラウザ / Environment

-   Windows / Android
-   Chrome / Firefox / Edge

**Comment by kaizumaki** [comment]
@Meiryo7743 ご提案ありがとうございます！
この２つのグラフは他のグラフと実装が違っているかもです。ともあれ横スクロールはぜひ実装したいところです。

**Comment by kaizumaki** [comment]
@Meiryo7743 #5632 で件のグラフに横スクロールを実装しましたが、いかがでしょう。見づらさは解消されていますでしょうか？

**Comment by Meiryo7743** [comment]
実機で表示を確認しました。
グラフの視認性は確かに改善されたと思います。

**Comment by kaizumaki** [comment]
@Meiryo7743 ご確認いただきありがとうございます。こちらのissueはクローズさせていただきますね。もしまだ解決に至っていない場合は再オープンしていただいてかまいません。
