### ISSUE TITLE
「発症前 2 週間以内 の出来ごとと症状」の条件がわかりづらい

### ISSUE THREAD

**Issue by task-jp** [tokyo-metropolitan-gov/covid19#556]
## 改善詳細 / Improve details
* 左側（濃厚接触をした方）は「発熱 または 呼吸器症状」が条件
* 右側（ご本人か濃厚接触をした方）は「呼吸器症状 かつ 発熱 37.5℃ 以上」が条件
ということが、左右で「呼吸器症状」をデザイン的に共有しているために分かりづらくなっている

## スクリーンショット / Screenshot
<img width="810" alt="新型コロナウイルス感染症が心配なときに___東京都_新型コロナウイルス感染症対策サイト" src="https://user-images.githubusercontent.com/5221601/76012070-00e5a700-5f59-11ea-88ab-d9a745d231d0.png">

## 期待する見せ方・挙動 / Expected behavior
* 左は左専用に A or B と記載し、右は右専用に B and C と明記した方が分かりやすい

**Comment by mikkame** [comment]
ご提案ありがとうございます！
実装に関しましては一度 #576 をご確認いただきたいです

**Comment by nichesuch** [comment]
flowの昔のデザインについてのIssueなのでCloseでよいと思います。
#3315

**Comment by kaizumaki** [comment]
ありがとうございます。こちらのissueはクローズさせていただきます。
