### ISSUE TITLE
「一般の方」と「ご高齢な方」他の分かりやすさについて

### ISSUE THREAD

**Issue by task-jp** [tokyo-metropolitan-gov/covid19#557]
## 改善詳細 / Improve details
* 左側に「一般の方」と書いてあるが、何を持って一般なのかがその後に右側を見ないとわからないので、分かりづらいのを改善したい

## スクリーンショット / Screenshot
<img width="818" alt="新型コロナウイルス感染症が心配なときに___東京都_新型コロナウイルス感染症対策サイト" src="https://user-images.githubusercontent.com/5221601/76012447-a3058f00-5f59-11ea-913a-90922d33abde.png">

## 期待する見せ方・挙動 / Expected behavior
* 左側に「ご高齢な方」「基礎疾患のある方」「妊娠中の方」を移動し、右側の表現を「それ以外の方」や「それ以外の一般の方」とした方が分かりやすい。

**Comment by mikkame** [comment]
ご提案ありがとうございます！
実装に関しましては一度 #576 をご確認いただきたいです

**Comment by nichesuch** [comment]
flowの昔のデザインについてのIssueなのでCloseでよいと思います。
#3315

**Comment by kaizumaki** [comment]
ありがとうございます。こちらのissueはクローズさせていただきます。
