### ISSUE TITLE
受診の要否の分岐の分かりやすさの改善の提案

### ISSUE THREAD

**Issue by task-jp** [tokyo-metropolitan-gov/covid19#558]
## 改善詳細 / Improve details
* 「受診が必要」「受診が不要」の差を強調して分かりやすくしたい

## スクリーンショット / Screenshot
<img width="1135" alt="新型コロナウイルス感染症が心配なときに___東京都_新型コロナウイルス感染症対策サイト" src="https://user-images.githubusercontent.com/5221601/76012905-6e460780-5f5a-11ea-893e-a02dba15e94b.png">

## 期待する見せ方・挙動 / Expected behavior
* 「必要」「不要」に違う色をつけたり、下線をつけてポイントを強調したりといった工夫で違いを直感的に分かりやすくしたい。

**Comment by mikkame** [comment]
ご提案ありがとうございます！
実装に関しましては一度 #576 をご確認いただきたいです

**Comment by nichesuch** [comment]
flowの昔のデザインについてのIssueなのでCloseでよいと思います。
#3315

**Comment by kaizumaki** [comment]
ありがとうございます。こちらのissueはクローズさせていただきます。
