### ISSUE TITLE
「発症日別による陽性者数の推移」グラフが非表示になっている

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#5583]
## 起こっている問題 / The Problem
- [本番環境](https://stopcovid19.metro.tokyo.lg.jp/) で「発症日別による陽性者数の推移」グラフが非表示になっている
- Chrome のコンソールに以下のようなエラーが出ています
```
TypeError: d.data.map is not a function
    at f.data (0cee4b2.js:1)
    at b54eb7f.js:2
    at b54eb7f.js:2
    at Sn (b54eb7f.js:2)
    at f.t._init (b54eb7f.js:2)
    at new f (b54eb7f.js:2)
    at b54eb7f.js:2
    at init (b54eb7f.js:2)
    at b54eb7f.js:2
    at v (b54eb7f.js:2)

TypeError: Cannot read property 'date' of undefined
    at f.<anonymous> (0cee4b2.js:1)
    at f.t._render (b54eb7f.js:2)
    at f.r (b54eb7f.js:2)
    at _n.get (b54eb7f.js:2)
    at new _n (b54eb7f.js:2)
    at t (b54eb7f.js:2)
    at f.$n.$mount (b54eb7f.js:2)
    at init (b54eb7f.js:2)
    at b54eb7f.js:2
    at v (b54eb7f.js:2)
```
- こちらの [commit](https://github.com/tokyo-metropolitan-gov/covid19/commit/54293003ee4a50d09bb450a4040539e0d81a4e38#diff-f4468ae53d563ff470dbcc440b6ac0842087a8f6a49d8e49fd17780805e9ce46) でデータ型が配列からハッシュに変更されているのが影響していると思います

## スクリーンショット / Screenshot
過去の[開発環境](https://deploy-preview-5547--dev-covid19-tokyo.netlify.app/) では「発症日別による陽性者数の推移」グラフが表示されていますが、

![スクリーンショット 2020-10-22 9 27 01](https://user-images.githubusercontent.com/5207601/96804334-b4000380-1449-11eb-97cb-97882e034393.png)

issue 起票時点の本番環境では非表示になっています。

![スクリーンショット 2020-10-22 9 27 29](https://user-images.githubusercontent.com/5207601/96804341-b6faf400-1449-11eb-8a47-42e6f810902c.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「発症日別による陽性者数の推移」グラフが表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/ を開く
2. 「その他 参考指標」のタブを選択

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@shgtkshruch お知らせいただきありがとうございます！
> こちらの commit でデータ型が配列からハッシュに変更されているのが影響していると思います

具体的にはどこの部分になるでしょうか？

**Comment by kaizumaki** [comment]
@shgtkshruch あ、リンクしてありましたね。状況把握しました。データの出力のほう対応いたしますので、しばしお待ちください。

**Comment by kaizumaki** [comment]
@shgtkshruch 原因がわかりました。東京都側の元データに空のセルが入ってしまい、そこをフィルタリングするphpのスクリプト側の処理が上手くいっていなかったようです。取り急ぎデータのほうを修正しました。現在phpのスクリプトを調査しています。
お知らせいただき感謝です！ 🙏

**Comment by shgtkshruch** [comment]
@kaizumaki 素早い対応ありがとうございます！
東京都の担当者さんも継続的にデータ更新いただき、ありがとうございます 🙏
