### ISSUE TITLE
「新型コロナウイルスの感染が判明した方へ」のリンク先が「新型コロナウイルス感染症でこれから入院される方へ」

### ISSUE THREAD

**Issue by cyoshihara** [tokyo-metropolitan-gov/covid19#5587]
## 改善詳細 / Details of Improvement
- トップページ（https://stopcovid19.metro.tokyo.lg.jp/）の左サイドバーにある「新型コロナウイルスの感染が判明した方へ」のリンク先が、「新型コロナウイルス感染症でこれから入院される方へ」になっており、文言とリンク先に齟齬がある。
- 「新型コロナウイルスの感染が判明した方へ」→「新型コロナウイルス感染症でこれから入院される方へ」への変更をすべきと提案いたします

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/30677541/96880847-9cac2f00-14b8-11eb-886d-3e3918231936.png)

## 期待する見せ方・挙動 / Expected behavior
- トップページ左バナーにおいて、
「新型コロナウイルスの感染が判明した方へ」→「新型コロナウイルス感染症でこれから入院される方へ」への変更をすべきと提案いたします

## 動作環境・ブラウザ / Environment
- Windows10
- Chrome

**Comment by kaizumaki** [comment]
@cyoshihara ご提案ありがとうございます！文言の変更については東京都の確認が必要になりますので、しばらくお待ちいただけると幸いです。

**Comment by kaizumaki** [comment]
@cyoshihara たいへんお待たせしました。こちらのご提案について、東京都から回答がありました。
リンク先の中でも「01　新型コロナウイルス感染症にり患された方へ （PDF：371KB）」に誘導したいこともあり、以下のように変更をお願いできればと思います。

- タイトル： `新型コロナウイルス感染症で入院・宿泊療養される方へ`
- リンク先：https://www.fukushihoken.metro.tokyo.lg.jp/oshirase/corona_0401.files/050101.pdf

**Comment by Murayu0225** [comment]
@kaizumaki このIssueに、_officially-approved_ のラベルがついてから1ヶ月たっているのですが、Issueの投稿者の方からのコメントを待った方が良いでしょうか。

**Comment by kaizumaki** [comment]
@Murayu0225 フォローありがとうございます！すっかり失念してしまっていました。特にissueを起票した方を待たなくても大丈夫です！

**Comment by Murayu0225** [comment]
@cyoshihara このIssue、私が対応しても大丈夫ですか。
