### ISSUE TITLE
(3)新規陽性者における接触歴等不明者数の「増加比」は名前がおかしい

### ISSUE THREAD

**Issue by foomin10** [tokyo-metropolitan-gov/covid19#5595]
## 改善詳細 / Details of Improvement
- 新規陽性者における接触歴等不明者数の「増加比」が「１週間前の接触歴等不明者数（移動平均値）との比較」となっていますが、これは実数の比率なので増加分の比率（増加率）ではありません。
- 「増加比 80%」だと一週間前と比べて実数が減っているのではなく1.8倍に急増しているように読み取れます。
- 前週との実数の比率として表すなら、増加なのか減少なのかもっとわかりやすくしてほしいです。

## 期待する見せ方・挙動 / Expected behavior
以下のいずれかだと思います。

- a) 前週との実数の比率をやめて、前週との増加数の比率（増加率）にする。50人から60人になった場合は +20%、50人から40人になった場合は -20% となる。
- b) タイトルを「前週比」などとする。100%にラインを引く。

私の感覚が間違っていたらすみません。

**Comment by kaizumaki** [comment]
@foomin10 ご提案ありがとうございます。ご提案いただいた内容は東京都の確認が必要になりますが、グラフの変更・文言の変更はかなり難しいと思います。
ちなみに、私は「増加比」に違和感を感じていないのですが、実際はどうなんでしょう？みなさんのご意見も聞きたいところです。

**Comment by MaySoMusician** [comment]
@foomin10 さんのコメント通り、「増加比」は「 **増加した差分が** 基準値に対してどれぐらいの割合か」を表すので、
- 「100人 → 100人」が「増加比 0%」
- 「100人 → 120人」が「増加比 20%」
- 「100人 → 80人」が「増加比 -20%」

になります。
一方で、先述の各例でそれぞれ「100%」「120%」「80%」という表記をしたい場合は、「 **現在値が** 基準値に対してどれぐらいの割合か」の意味で「前週比」といった表現が適切と思われます。

**Comment by kaizumaki** [comment]
@foomin10 ご提案いただいた内容について東京都に確認いたしました。
モニタリング項目の指標や用語に関することは、東京都福祉保健局の所管であり、専門家によるモニタリング会議と連携して進めているので、変更するのは非常に難しいです。当サイトだけで判断できるものではない、との回答でした。ただ、ご意見として所管には伝えさせていただきます、とのことでした。
ご理解いただけますと幸いです。

**Comment by kaizumaki** [comment]
東京都からの回答がありましたので、こちらのissueはクローズいたします。
