### ISSUE TITLE
サイドナビに東京iCDCのnoteへのリンクを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5638]
サイドナビに以下の外部リンクの追加をお願いします。現在「最新のお知らせ」に入っている項目です。

テキスト：`東京iCDC（東京感染症対策センター）からのお知らせ`
リンク先：https://note.com/tokyo_icdc
配置位置：「東京都新型コロナウイルス感染症 支援情報ナビ」と「都民利用施設・都主催イベントに関する情報」の間

![スクリーンショット 2020-11-03 8 55 47](https://user-images.githubusercontent.com/14883063/97932183-bbf96500-1db2-11eb-9bc6-dec39ccaea72.png)

**Comment by Murayu0225** [comment]
やります。

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！よろしくお願いします 🙏
