### ISSUE TITLE
陽性者の属性のソートが降順になっていない

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5648]
ページ内の表示の順番が少し違和感があったので、直せるとベターだと思います。APIは降順で出力しているはずなので、そのままの順序で出力すれば良いと思います。

![image](https://user-images.githubusercontent.com/3581778/97797944-c7d71100-1c64-11eb-8ae9-faadc26bbe70.png)
![image](https://user-images.githubusercontent.com/3581778/97797947-cc032e80-1c64-11eb-89bc-51d0e1d83c74.png)

_Originally posted by @MasaGon in https://github.com/tokyo-metropolitan-gov/covid19/pull/5293#issuecomment-720051674_

**Comment by Murayu0225** [comment]
やります。
