### ISSUE TITLE
「感染状況・医療提供体制の分析」の説明文修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5660]
「感染状況・医療提供体制の分析」の説明文の修正をお願いします。`○月‎○‎日付の` を `最新の` に修正します。

≪修正前≫
`東京都では、都内の「感染状況」と「医療提供体制」を2つの柱として7つのモニタリング項目を設定しています。毎週、専門家による状況分析を項目ごとに行い、都内の感染状況と医療提供体制それぞれについて「総括コメント」として4段階で評価します。○月‎○‎日付の総括コメントは以下のとおりです。`
　↓
≪修正後≫
`東京都では、都内の「感染状況」と「医療提供体制」を2つの柱として7つのモニタリング項目を設定しています。毎週、専門家による状況分析を項目ごとに行い、都内の感染状況と医療提供体制それぞれについて「総括コメント」として4段階で評価します。‎最新の総括コメントは以下のとおりです。`

![スクリーンショット 2020-11-09 16 16 59](https://user-images.githubusercontent.com/14883063/98511528-28d79800-22a8-11eb-8dba-a6e76471d165.png)

**Comment by Murayu0225** [comment]
やります。
