### ISSUE TITLE
陽性者の属性表に項目を追加（職業・接触歴・発症日・確定日）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5674]
## 改善詳細 / Details of Improvement
- 陽性者の属性データを取得している東京都オープンデータカタログサイトの[オープンデータAPI](https://portal.data.metro.tokyo.lg.jp/opendata-api/) に、11月12日から公表項目が追加になりました。https://github.com/tokyo-metropolitan-gov/covid19/issues/5631#issuecomment-725805247
- 当サイトの「陽性者の属性」にも追加項目を反映します。
- 同時に `white-space: nowrap;` でセル内の折り返しを無効にし、tableに横スクロールを実装したいと思います。https://github.com/tokyo-metropolitan-gov/covid19/issues/5540#issuecomment-712918313
- 追加項目のイメージは以下のとおりです。
赤枠内が今回の実装です（**「※2」や注釈は無視してください**）。
<img width="977" alt="感染者情報の公表内容の追加について" src="https://user-images.githubusercontent.com/14883063/98893346-97ee0000-24e5-11eb-896d-66f0c376ae7f.png">

項目の読み替えは以下のとおりです。

オープンデータAPI|当サイトの陽性者の属性
-----|-----
患者_職業|職業
患者_接触歴の有無フラグ|接触歴
発症_年月日|発症日
確定_年月日|確定日

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shgtkshruch** [comment]
対応します！

**Comment by kaizumaki** [comment]
@shgtkshruch ありがとうございます！よろしくお願いします 🙏
