### ISSUE TITLE
Auto-i18n Builderワークフローが自動的にPull Requestを作成できない

### ISSUE THREAD

**Issue by Genbuchan** [tokyo-metropolitan-gov/covid19#5680]
## 起こっている問題 / The Problem
- Auto-i18n Builder ワークフローがプルリクエストの作成に失敗している

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/44745974/99394767-c2471f80-2922-11eb-9936-809cd9abd48a.png)

## 期待する見せ方・挙動 / Expected Behavior
- i18n_builder.yml 内の `uses: peter-evans/create-pull-request@v2` を `uses: peter-evans/create-pull-request@v3` に変更する

## 起こっている問題の再現手段 / Steps to Reproduce
1. Auto-i18n Builder をトリガーする

**Comment by kaizumaki** [comment]
@Genbuchan ご指摘ありがとうございます！Actionsのエラー、すっかりスルーしてしまっていました。助かります。
具体的には、こちら↓のGitHub ActionsのDeprecationに対応した `peter-evans/create-pull-request` にアップデートする、ということですね？
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by Genbuchan** [comment]
具体的なアップデート内容については、仰る通りです。

京都府版でも同様の問題が発生していましたので、そちらの方でも同じ修正を行い、問題なく動作するようになりました。

今回お送りしたプルリクエストの内容は、先述の create-pull-request のバージョンを2から3にアップデートすることにより、仰っていた GitHub Actions の Deprecated になった機能の問題を修正するのが狙いです。

確認よろしくお願いいたします🙇‍♂️
