### ISSUE TITLE
感染状況の警戒レベル引き上げに対応する

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#5683]
## 改善詳細 / Details of Improvement
11月19日に感染状況の警戒レベルが引き上げられる見込みであることから，引き上げが決定したタイミングで即サイトに反映ができるよう対応する．

https://www3.nhk.or.jp/news/html/20201118/k10012718181000.html

**Comment by nard-tech** [comment]
こちら対応します．

**Comment by kaizumaki** [comment]
こちら、東京都のほうで対応致しましたので（ https://github.com/tokyo-metropolitan-gov/covid19/pull/5686#issuecomment-730114621 ）クローズいたします。
