### ISSUE TITLE
運用上必要な GitHub Actions の失敗を検知できるようにする

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#5684]
## 改善詳細 / Details of Improvement
- 多言語対応や OGP 画像の生成になど運用に関わる GitHub Actions が失敗していたことに気づきにくい https://github.com/tokyo-metropolitan-gov/covid19/issues/5680
  - [Auto-i18n Generator](https://github.com/tokyo-metropolitan-gov/covid19/actions?query=workflow%3A%22Auto-i18n+Generator%22)
  - [OGP Builder](https://github.com/tokyo-metropolitan-gov/covid19/actions?query=workflow%3A%22OGP+Builder%22)
- README に status badge を追加すると失敗していても視覚的にわかるので見落としにくくなると思いました

## スクリーンショット / Screenshot
現在の README に「production deploy」のバッチがついているので、これと同様に落ちていたら困る GitHub Actions のバッチがあるとわかりやすいと思います。

![スクリーンショット 2020-11-18 21 30 29](https://user-images.githubusercontent.com/5207601/99531008-701b0280-29e5-11eb-8786-2c0ca42be32b.png)

status badge は各 Actions のジョブ一覧のページ右上の「create status badge」からマークダウン形式でコピーできます。

![スクリーンショット 2020-11-18 21 29 18](https://user-images.githubusercontent.com/5207601/99531050-8032e200-29e5-11eb-8d8a-3bec3752d8aa.png)

![スクリーンショット 2020-11-18 21 29 28](https://user-images.githubusercontent.com/5207601/99531055-81fca580-29e5-11eb-9048-385f7dd2a31b.png)

![Auto-i18n Generator](https://github.com/tokyo-metropolitan-gov/covid19/workflows/Auto-i18n%20Generator/badge.svg)

## 期待する見せ方・挙動 / Expected behavior

- 運用上落ちていると困る GitHub Actions の失敗が検知できること
- その一例として、README に追加する方法を提案しました

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@shgtkshruch ご提案ありがとうございます！これはいいアイディアですね！ぜひ導入したいです。運営側でやるべきことはありますか？

**Comment by shgtkshruch** [comment]
> 運営側でやるべきことはありますか？

運営側の視点で、どのブランチに対してどの GitHub Actions が成功していることを期待しているか、を整理していただけると助かります。

個人的には以下のものがあると良さそうに思うのですが、過不足などがあればご指摘いただけると嬉しいです。

- `development` ブランチの [Auto-i18n Generator](https://github.com/tokyo-metropolitan-gov/covid19/actions?query=workflow%3A%22Auto-i18n+Generator%22)
- `master` ブランチの [OGP Builder](https://github.com/tokyo-metropolitan-gov/covid19/actions?query=workflow%3A%22OGP+Builder%22)

**Comment by kaizumaki** [comment]
そうですね、少し観点が違いますが、東京都の担当者がデータの反映具合の状況（update dataが成功しているかどうか）をわかるようにしたいところです。

**Comment by shgtkshruch** [comment]
> 東京都の担当者がデータの反映具合の状況（update dataが成功しているかどうか）
 
こちらは、`master` ブランチの [production deploy](https://github.com/tokyo-metropolitan-gov/covid19/actions?query=workflow%3A%22production+deploy%22)  ですかね。
それでは先に上げた 2つと合わせて、こちらをのバッチを README に追加する形で PR 出そうと思います :octocat:
