### ISSUE TITLE
本番環境で未使用の CSS を削除する

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#5685]
## 改善詳細 / Details of Improvement
- 本番環境で読み込んでいる CSS のサイズが 586KB とかなり大きいです
  - このうち 571KB は未使用の CSS です
- ローディングやコードのパース時にパフォーマンス面で影響があるので、未使用の CSS を削除すると良さそうです
- [PurgeCSS が導入されています](https://github.com/tokyo-metropolitan-gov/covid19/blob/45437c1fddb2f76876272f55264bc667c7c71ed0/package.json#L57)が、こちらが適応されていないように見えます

## スクリーンショット / Screenshot
![スクリーンショット 2020-11-18 21 56 49](https://user-images.githubusercontent.com/5207601/99533420-3815be80-29e9-11eb-8995-1102d3fb642e.png)

## 期待する見せ方・挙動 / Expected behavior
- [`yarn generate:deploy`](https://github.com/tokyo-metropolitan-gov/covid19/blob/45437c1fddb2f76876272f55264bc667c7c71ed0/package.json#L15) でビルドしたコードから、未使用の CSS が削除されること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@shgtkshruch ご提案ありがとうございます 🙏 PurgeCSS、効いてないんですね。これはなんとかしたいですね...
