### ISSUE TITLE
「このサイトから派生したサイト」の表の更新

### ISSUE THREAD

**Issue by yukiyalien** [tokyo-metropolitan-gov/covid19#5702]
## 起こっている問題 / The Problem
- [このサイトから派生したサイト](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md)の一覧に千葉県のサイトが2つ掲載されているが、うち1つ(まいぷれが運営していた方)がリンク切れになっている
- もう一つの方(CivicTechZenChibaの方)は[千葉県から公認をもらっている](https://www.pref.chiba.lg.jp/seisaku/ict/coronajyouhousaito.html)が、それについての記述がない。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/36108601/99900123-55040780-2cf1-11eb-8004-23a5c705b28f.png)

## 期待する見せ方・挙動 / Expected Behavior
- まいぷれが運営していたリンク切れの方を削除する
- CivicTechZenChibaの方に「（**千葉県公認**）」の文字列を追記する

## 起こっている問題の再現手段 / Steps to Reproduce
1.  [このサイトから派生したサイト](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md)を表示します

## 動作環境・ブラウザ / Environment
- 全ての環境

**Comment by yukiyalien** [comment]
この方法でよろしかったら私がやってもいいでしょうか？

**Comment by kaizumaki** [comment]
@yukiyalien ご提案ありがとうございます！PR出していただいてOKですよ！
