### ISSUE TITLE
lighthouseのActionsがエラー

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5708]
## 起こっている問題 / The Problem
- stagingにマージした際に走るlighthouseのActionsがエラーになっています。
https://github.com/tokyo-metropolitan-gov/covid19/pull/5707/checks?check_run_id=1445148612
- [GitHub Actionsのアップデート](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) が影響しているようです。
- `treosh/lighthouse-ci-action@v2` を `treosh/lighthouse-ci-action@v3` にすれば正常に戻ると思われます。
https://github.com/treosh/lighthouse-ci-action

## スクリーンショット / Screenshot

Actionsでコケている↓
![スクリーンショット 2020-11-24 9 32 12](https://user-images.githubusercontent.com/14883063/100031282-93580e80-2e38-11eb-9901-b81241c54f77.png)

## 期待する見せ方・挙動 / Expected Behavior
- Actionsでlighthouseが正常に走る

## 起こっている問題の再現手段 / Steps to Reproduce
1. stagingにマージ

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nard-tech** [comment]
対応します
