### ISSUE TITLE
「受診相談窓口における相談件数」カードの上部注釈変更

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5710]
「受診相談窓口における相談件数」カードの上部注釈（現在、黄色背景で表示させているところ）を変更します。

変更後テキスト：`「東京都発熱相談センター」の開設に伴い、「新型コロナ受診相談窓口」は終了したため、10月30日（金曜日）17時をもって本グラフの数値更新を終了しました。「東京都発熱相談センターにおける相談件数グラフ」はこちら。`

- 位置はグラフ上部のまま変更ありません。
- 黄色背景はなしにします。（`attentionNote` ではなく `description` のslotに入れる）
- `「東京都発熱相談センターにおける相談件数グラフ」はこちら。` のテキストをリンクとします。リンク先は以下になります。
`/cards/number-of-reports-to-tokyo-fever-consultation-center`

実装イメージ↓
![スクリーンショット 2020-11-24 11 04 25](https://user-images.githubusercontent.com/14883063/100038245-fc468300-2e46-11eb-8ad5-c1c1ce4ce394.png)

**Comment by Murayu0225** [comment]
やります。

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！よろしくお願いします 🙏
