### ISSUE TITLE
陽性者数の表示をカラーマップにしてほしい

### ISSUE THREAD

**Issue by DN360** [tokyo-metropolitan-gov/covid19#5712]
## 改善詳細 / Details of Improvement
- 「その他　参考指標」にある `陽性者数（区市町村別）` が表だけだと見にくい
- 区市町村ごとにカラーマップを表示すると視覚的にわかりやすい

## スクリーンショット / Screenshot

- 特になし

## 期待する見せ方・挙動 / Expected behavior
- [参考ツイート](https://twitter.com/mur0_ta1/status/1331077603797549057)

![参考イメージ](https://pbs.twimg.com/media/Enjv1GLUYAIXqnc?format=png&name=900x900)

## 動作環境・ブラウザ / Environment

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@DN360 ご提案ありがとうございます！こちらの内容は #2706 に類似していますでしょうか？ #2706 については東京都の確認をとっており、コメント https://github.com/tokyo-metropolitan-gov/covid19/issues/2706#issuecomment-627821352 を得ています。ですので、このご提案を採用するのはむずかしいように思われるのですが、もし先の東京都からのコメントとは別の視点でのご提案といったことであれば、再確認する方向でいきたいと思います。いかがでしょう？

**Comment by DN360** [comment]
なるほど、先に同じようなissueが上がっていたんですね。確認不足でした申し訳ないです。確かに

> 地図としての可視化は慎重にせねばなりません。首都圏で活動している人の特徴として、居住地と職場、生活圏といったものが異なることがあるからです。

という問題があることを承知しました。一旦closeします。
