### ISSUE TITLE
metro.json 325 行目の日付に入力ミスが存在する

### ISSUE THREAD

**Issue by Meiryo7743** [tokyo-metropolitan-gov/covid19#5716]
## 起こっている問題 / The Problem
[`metro.json` 325 行目](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/data/metro.json#L325)について，`label` の日付が `"11\/16~11"` となっており，日付の大小関係が逆転しているように思えます。

このため，サイト上では `11 月 16 日 ～ 12 月 11 日` と表示されてしまっている状態です（cf. スクリーンショットの黄枠部分）。

- 当該ファイルの 324～331 行目：

```json
        {
            "label": "11\/16~11",
            "data": [
                -9.01,
                -29.31,
                -31.03
            ]
        }
```

## スクリーンショット / Screenshot

![スクショ](https://user-images.githubusercontent.com/46659204/100087567-47d24e80-2e92-11eb-9dde-f858c89c3bab.png)

## 期待する見せ方・挙動 / Expected Behavior
- 日付を正しい値に修正する

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/ を開く
2. **その他 参考指標**へ移動する
3. **都営地下鉄の利用者数の推移**のある位置までスクロールする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@Meiryo7743 ご指摘ありがとうございます！こちら東京都の元データが間違っている可能性があります。調査いたしますので、しばしお待ちください 🙇‍♀️

**Comment by kaizumaki** [comment]
@Meiryo7743 こちらの件、東京都の元データの入力方法に誤りがありました。期間終了日は月を入れないことになっているところ、「11月」と入ってしまっていました。なのでデータ変換スクリプトの誤変換により、「11」を拾ってしまっていました。先ほど元データを修正いたしました。ご指摘いただき感謝です！ 🙏

**Comment by kaizumaki** [comment]
こちら、解決しましたのでクローズします。
