### ISSUE TITLE
月・日を表示している箇所に年を追加する

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#5750]
## 改善詳細 / Details of Improvement
- この Web サイトは来年 2021 年に入っても引き続き運用されることが確定的なので，現在「○月○日」と表示されている（暗黙的に2020年であることを示している）箇所に年も表示するようにする

## 期待する見せ方・挙動 / Expected behavior
- 「○月○日」と表示されている箇所を「○年○月○日」という表示に修正する

**Comment by nard-tech** [comment]
該当箇所は各グラフのラベル，ツールチップ，表など多岐に渡るので，リストアップして，issue，PRを細分化した上で対応すべきかと思います．

年内に間に合わせるのでよければ私がすべて対応できると思います．

**Comment by kaizumaki** [comment]
@nard-tech おお、ご提案ありがとうございます！私たちも気になっていたところです。
dataフォルダ内のjsonファイルで、グラフの値に紐づいている日付についてはすべてYYYY-MM-DDに変換しています（都営地下鉄・都庁来庁者の期間については `period` という新たなkeyを付与しました）。まずは**翻訳に関わらない部分から**進めていただければと思います。私が思うに、グラフのX軸に年の軸を追加するところからでしょうか。

**Comment by nard-tech** [comment]
@soutaito @kaizumaki こちらの issue は #5859 から close されましたが，#5827 はいかが致しましょうか．

**Comment by kaizumaki** [comment]
@nard-tech はい、 #5827 はこれから都に確認まわすので、しばらくお待ちください 🙇 こちらのissueは再オープンしておきますね。
