### ISSUE TITLE
[周知] /flow のページの対応について

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#576]
コントリビュータのみなさま
フローページ（/flow）　「新型コロナウイルス感染症が心配なときに」（以下/flowと記載します）
についてのお知らせです。

こちらのページについては脱SVG化や多言語対応の検討を行なっており
大きな変更が加えられる予定です。

/flow についての実装、PRについては複雑なコンフリクトが予想されますので着手はしないようお願いします。
（改善案の起票については歓迎いたします！）
また、現在PRをいただいている分に関してはできる限り活かせる方向で進めさせていただきます。

本告知についてご連絡が遅れてしまい申し訳ございません

**Comment by kaizumaki** [comment]
flowページをコーディングする方針になりました。
詳しくはこちら→ #659
