### ISSUE TITLE
「企業の皆様・はたらく皆様へ」のコンテンツ修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5764]
「企業の皆様・はたらく皆様へ」のコンテンツの修正をお願いします。

【修正前】
タイトル：営業時間短縮に係る感染拡大防止協力金（９月実施分）
本文：新型コロナウイルス感染拡大防止のため、特別区内の酒類の提供を行う飲食店及びカラオケ店に対する都の営業時間短縮の要請に全面的に協力いただいた中小の事業者の皆様に対し、協力金を支給します。
リンク：https://jitan.metro.tokyo.lg.jp/sep/index.html

　　↓

【修正後】
タイトル：`営業時間短縮に係る感染拡大防止協力金（11/28～12/17実施分）`
本文：`新型コロナウイルス感染拡大防止のため、特別区及び多摩地域の各市町村の飲食店等に営業時間の短縮要請が行われることに伴い、要請に全面的にご協力いただける中小の事業者の皆様に対し、協力金を支給します。`
リンク：https://jitan.metro.tokyo.lg.jp/nov/index.html

![スクリーンショット 2020-12-08 9 57 10](https://user-images.githubusercontent.com/14883063/101423309-1a7aab80-393c-11eb-9ad2-20b966c8d7ee.png)

**Comment by Murayu0225** [comment]
やります。
