### ISSUE TITLE
区市町村別 陽性者数の日付が福祉保健局のものと異なります

### ISSUE THREAD

**Issue by Nobukuni-Hyakutake** [tokyo-metropolitan-gov/covid19#5769]
## 起こっている問題 / The Problem
- 区市町村別 陽性者数の日付が、東京都福祉保健局発表のものと違っています。
本サイトでは、表の右上に「12月7日の累計」となっているが福祉保健局では12月8日時点と書いてあります。
本日12/10 5:00に気がつきました。

## スクリーンショット / Screenshot
本サイトのもの：
![ScreenShot 2020-12-10 5 00 34](https://user-images.githubusercontent.com/74386805/101682714-53835f00-3aa7-11eb-9be8-de6deb8b2e7c.png)
福祉保健局のもの：
![fukushihoken](https://user-images.githubusercontent.com/74386805/101683622-88dc7c80-3aa8-11eb-9b2a-9b28239fecea.png)
ちなみにJSONデータは下記です　 
何らかの不具合で4行目だけが、更新されていないのかもしれません。
![ScreenShot 2020-12-10 5 15 34](https://user-images.githubusercontent.com/74386805/101682810-757ce180-3aa7-11eb-87ce-2148e6843a8d.png)

## 期待する見せ方・挙動 / Expected Behavior
東京都福祉保健局と本サイトのどちらが正しいのか調べて、修正いただく。
一般の人は日付だけが違っていてもあまり気にならないかもしれませんが、
私は区市町村別のデータを取り込み、ダッシュボードとして公開している関係で整合性が取れていた方が良いためです。

## 起こっている問題の再現手段 / Steps to Reproduce
下記を開く。
https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases-by-municipalities/
https://www.fukushihoken.metro.tokyo.lg.jp/hodo/saishin/corona1155.html

## 動作環境・ブラウザ / Environment
- macOS
- Safari

**Comment by kaizumaki** [comment]
@Nobukuni-Hyakutake ご指摘ありがとうございます！当サイトの元データが間違っている可能性があります。調査いたしますので、しばらくお待ちください。

**Comment by Nobukuni-Hyakutake** [comment]
ありがとうございます。よろしくお願いします。

**Comment by kaizumaki** [comment]
@Nobukuni-Hyakutake 調査したところ、東京都が入力している当サイトの元データが間違っていました。先ほど修正して反映されました。https://github.com/tokyo-metropolitan-gov/covid19/commit/1c561e70760b7d5ca363245519fa410453be5760
ご指摘いただき感謝です。ご確認いただければと思います。

**Comment by Nobukuni-Hyakutake** [comment]
サイトを見ました。直っていますね。どうもありがとうございます！
