### ISSUE TITLE
東京都が発表する感染者と死亡者データの統合

### ISSUE THREAD

**Issue by nnawata** [tokyo-metropolitan-gov/covid19#5776]
## 改善詳細 / Details of Improvement
- 東京都社会福祉保健局が日々発表している死亡者のデータと、日々更新される感染者データの統合

## 期待する見せ方・挙動 / Expected behavior
- APIで取得できるデータおよびCSVデータの中に反映
- 更新したことが分かるようにデータに更新日付を入れる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@nnawata ご提案ありがとうございます！「死亡者のデータ」とは「死亡者数の値」ということでしょうか？

**Comment by nnawata** [comment]
早速ご回答いただきありがとうございます。東京都社会福祉保健局が、件別（診断日付・死亡日・居住地・性別）に死亡者を公表しています。
直近はこちらです。https://www.fukushihoken.metro.tokyo.lg.jp/hodo/saishin/corona1160.html
APIの件別データは「退院等」になっていて死亡との区別がつかないので、福祉保健局の日々のデータをコピペするしかデータが得られません。またそのコピペしたデータと、CSVとの関連性がとれない不便さを改善できれば。

**Comment by kaizumaki** [comment]
@nnawata なるほどです。そうすると純粋にオープンデータのみの要望と見受けられますので、[東京都オープンデータカタログサイト](https://portal.data.metro.tokyo.lg.jp/) の「リクエストボックス」に投稿していただくのが近道かもしれません。お手数ですが、ご検討いただけますと幸いです。

**Comment by nnawata** [comment]
そうですか。勘違いをしてしまいました。では、カタログサイトの方に要望を上げることといたします。ありがとうございます。

**Comment by kaizumaki** [comment]
@nnawata こちらのissueはクローズでよろしかったでしょうか...？いったんクローズいたしますので、もし解決されていない場合は再オープンしていただいてかまいません。
