### ISSUE TITLE
クラスタ情報の提供

### ISSUE THREAD

**Issue by nnawata** [tokyo-metropolitan-gov/covid19#5777]
## 改善詳細 / Details of Improvement
- 感染者データにクラスタ項目を加える

## 期待する見せ方・挙動 / Expected behavior
- APIで取得できる感染者データに、クラスタに番号を紐付ける
- 三重県の例参照(https://www.pref.mie.lg.jp/YAKUMUS/HP/m0068000066_00002.htm)

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@nnawata ご提案ありがとうございます！クラスタの番号って、東京都福祉保健局のサイトなどで公開しているものなのでしょうか？東京都が公開しているものではないとなると、庁内の確認と調整にかなりのお時間いただくことになりそうです。
そして、https://github.com/tokyo-metropolitan-gov/covid19/issues/5776#issuecomment-742913793 にもコメントしましたが、純粋にオープンデータのみのご提案は[東京都オープンデータカタログサイト](https://portal.data.metro.tokyo.lg.jp/) の「リクエストボックス」に投稿していただくのが近道かと思います。

**Comment by nnawata** [comment]
クラスタ番号は公開されていませんが、おそらく持っているはずです。他の都市の公表データでは、感染者に振られた一意の番号を使って、濃厚接触が分かるようにしているケースもあり、またそれを用いて分析を公表しているケースも見られますが、所属クラスタをつけるのがいちばん簡単かなとおもって提案してみました。こちらも場違いだったようなので、カタログサイトの方に要望をあげることとします。ありがとうございます。

**Comment by kaizumaki** [comment]
@nnawata こちらのissueもいったんクローズといたします。解決されていない場合は、再オープンしていただいてかまいません。

**Comment by nnawata** [comment]
未解決ですので再度オープンします。

**Comment by kaizumaki** [comment]
@nnawata こちらは変わらずオープンデータおよびオープンデータAPIへの要望ということでよろしかったでしょうか？カタログサイトのリクエストボックスには投稿されましたか？その上で、解決されない、ということですかね。

issueの再オープンは、コメントテキストエリアの右下の「Reopen」ボタンを押します。

**Comment by nnawata** [comment]
そのはずなのですが、Commentボタンだけで、REOPENボタンがありません。

**Comment by kaizumaki** [comment]
ああ、adminしかReopenできないかもです。では私のほうでReopenします。
ただ、東京都からは回答がきているのですね。こちらからも最終的には同じ東京都戦略政策情報推進本部ICT推進部企画課に伝えることになりますので、進展はあまり見込めないと思われます...。そして回答にかなりのお時間いただくことになりますこと、どうかご了承ください。

**Comment by kaizumaki** [comment]
@nnawata たいへんお待たせしました。東京都から回答がありました。クラスタ情報と患者情報の紐づけは、患者の個人情報保護の観点から、対応することは難しい状況とのことです。申し訳ありませんが、こちらのご提案を採用することは難しいです。ご理解いただけますようよろしくお願いいたします。

**Comment by nnawata** [comment]
他の自治体でクラスタ情報の開示例があることから依頼したものです。
報道されるクラスタとデータとがリンクせず、飲食店の営業短縮と（クラスタの高割合を占めると想像する）介護施設内感染との関係がよくわからないままです。クラスタの追跡をやめてしまったので、いまとなってはデータすらないのかもしれませんが、事実が不透明のままなのは残念でなりません。

**Comment by kaizumaki** [comment]
東京都から回答がありましたので、こちらのissueはクローズさせていただきます 🙏
