### ISSUE TITLE
都営地下鉄の利用者数の推移の縦軸の単位

### ISSUE THREAD

**Issue by 44u** [tokyo-metropolitan-gov/covid19#579]
## 起こっている問題 / Occurred problem
「都営地下鉄の利用者数の推移」の縦軸ですが、2桁少ないんじゃないでしょうか？
https://www.bousai.metro.tokyo.lg.jp/_res/projects/default_project/_page_/001/007/425/2020030316.pdf

**Comment by kaizumaki** [comment]
ありがとうございます！確認します！

**Comment by kaizumaki** [comment]
こちら対応いたします。ご報告ありがとうございました！
