### ISSUE TITLE
グラフのX軸に年の軸を追加（「都営地下鉄の利用者数の推移」「都庁来庁者数の推移」グラフ以外）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5790]
## 改善詳細 / Details of Improvement
- グラフのX軸に、年（year）の軸を追加します（「都営地下鉄の利用者数の推移」「都庁来庁者数の推移」グラフ以外）。
- 参考 #5786

## スクリーンショット / Screenshot

参考までに、#5786 で実装をしてみています。
![X軸サンプル](https://user-images.githubusercontent.com/14883063/102581700-6ef40700-4144-11eb-85c4-d6c17a3ef1f5.png)

## 期待する見せ方・挙動 / Expected behavior
- グラフのX軸に年の軸が表示される。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nard-tech** [comment]
こちら，対応します．明日までには対応できると思います．

**Comment by kaizumaki** [comment]
@nard-tech ありがとうございます！よろしくお願いします 🙏

**Comment by nard-tech** [comment]
@kaizumaki グラフの軸は手間取っていてまだ実装できていませんが，取り急ぎ，#5825 を作成しました．

**Comment by kaizumaki** [comment]
@nard-tech 参考として、私のほうでTimeBarChart.vueに年の軸を追加してみました。 #5841
実際やってみると、データそのものが年をまたいでいないと難しいことに気づきました。なので、2021年になってからの実装としたほうがいいかもしれません。
もちろん、何かいい方法があればぜひ！

**Comment by nard-tech** [comment]
@kaizumaki ありがとうございます．Y軸がずれる事象を私も確認して挫折したのですが，改めてチャレンジしようと思います．

**Comment by kaizumaki** [comment]
@nard-tech 東京都に確認したところ、こちらの実装は年明けてからでいいそうです。データが年をまたいだ状態になってから試してみてください 🙏
