### ISSUE TITLE
表「陽性患者の属性 」を日付の降順に表示させる提案

### ISSUE THREAD

**Issue by m-tano** [tokyo-metropolitan-gov/covid19#582]
## 改善詳細 / Improve details
* 昇順（古い順）になっているところを、降順（新しい順）にしたい

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/47078380/76043993-614a0800-5f9c-11ea-8632-5330172a4f57.png)

## 期待する見せ方・挙動 / Expected behavior
* 新しい日付の情報が上に表示される

**Comment by MaySoMusician** [comment]
着手してみます

**Comment by ocean3fish** [comment]
一応 #275 で「ソート出来るから良いのでは」という結論になりましたが、デフォルト降順にするのが良いでしょうかね。

**Comment by m-tano** [comment]
すでに議論があったのですね。見落としていました。
しかしやはり、デフォルト降順が良いと思います。

**Comment by MaySoMusician** [comment]
いま、もしかして何もしなくても降順になってます？

**Comment by MaySoMusician** [comment]
#397 を `dayjs` 用に書き換えると解決するみたいです

**Comment by halsk** [comment]
@m-tano こちら、降順になっているのでクローズしても良いですか？
@MaySoMusician 一方、#397 の Conflict になったままのやつはどう関係してきます？

**Comment by MaySoMusician** [comment]
@MaySoMusician 調査してみます

**Comment by m-tano** [comment]
@halsk クローズしてよいです。タイミングはお任せしてよいでしょうか。

**Comment by MaySoMusician** [comment]
@halsk もともと、データのソート処理に不具合にあり、たまたま降順になっていたのを、 `moment`を使って解決したのが #397 のようです
日付関連の処理は以下のとおり

ファイル | 現在のdevelopmentの処理 | #397 の処理
----------|--------------------------------|----------------
`formatTable.ts`|`dayjs`を使って日付を整形してコンポーネント側に返す| JSのDate型にしてコンポーネント側に渡す
`DataView..vue`|受け取った日付文字列をそのまま表示| `moment`を使って受け取ったDateを文字列に変換して表示

それと #397 で `formatTable.ts` から送られてくるデータのkeyが英語になるので、取り込むならそこも要修正となります

**Comment by halsk** [comment]
@MaySoMusician さん、なるほど。 #397 もコンフリクトが放置されているので、一旦クローズさせていただきます。
