### ISSUE TITLE
検査陽性者の状況、検査実施数に注釈追加

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#584]
「検査陽性者の状況」の表の下部に
> （注）都内において疑い例または患者の農耕接触者として検査を行ったものについて掲載
> 　　　（チャーター機帰国者、クルーズ船乗客等は含まれていない。）

「検査実施数」のグラフの下部に
> `（注）同一の対象者について複数の検体を調査する場合あり`

それぞれ追加をお願いいたします

**Comment by kaizumaki** [comment]
対応します！

**Comment by NaoyaShimizzz** [comment]
依頼内容にも不備が。。
農耕　→ 　濃厚 でお願いします

**Comment by MaySoMusician** [comment]
こちら、 hotfixとして#590で`staging`ブランチにマージされたきり`development`にbackportされていないので対応お願いします。（TS化・多言語化に影響あり？）

**Comment by af12066** [comment]
> こちら、 hotfixとして#590でstagingブランチにマージされたきりdevelopmentにbackportされていないので対応お願いします。（TS化・多言語化に影響あり？）

対応します
