### ISSUE TITLE
.gitpod.ymlの追加, FOR_DEVELOPERS.mdへbadgeの追加

### ISSUE THREAD

**Issue by twtwtw-gj** [tokyo-metropolitan-gov/covid19#5847]
## 改善詳細 / Details of Improvement
- .gitpod.ymlファイルの追加
（nodeイメージ指定・ワークスペース作成時に自動でyarn developコマンドの起動）

- FOR_DEVELOPERS.mdへのbadge追加

## 利点 / merit
- 簡易にプロジェクト開発環境を立ち上げられる手筈をこちら側で整えることで、新規プロジェクト参加者（非プログラマを含む）を呼び込みやすくできる

**Comment by kaizumaki** [comment]
@twtwtw-gj ご提案ありがとうございます！Gitpodというのを初めて知りました。クラウドIDEなのですね。私も知ったばかりなので、よくわからないのですが、Pull Requestのフローなどはどのようになるのでしょうか？
それと有償or無償の制限などありますか？

**Comment by twtwtw-gj** [comment]
GitPodのサービス概要や私の目的意識について、説明不足でしたね。失礼しました。
他の方もご覧になるでしょうから、GItPod自体の紹介から詳しく説明します。

### GitPodとは

kaizumakiさんがおっしゃった通り、GitPodとはクラウドIDEサービスの名称です。

他サービスと大きく離れた特徴として、`https://gitpod.io/#` のURLのあとにGitHubリポジトリのサイト名を入力すると、（このプロジェクトの場合、 https://gitpod.io/#https://github.com/tokyo-metropolitan-gov/covid19 と入力しただけで）自動で開発環境が立ち上がるという点が挙げられます。
（ただし使用に関してGitHubアカウントが必要。無償利用者の制限は後述）

ワークスペースの立ち上げが非常に簡便であり、こちらを使えば、非プログラマの方や、プログラマでもNode.jsやDockerのインストールをしていない方・タブレット利用者でも楽に開発をすることが出来ると考えてissueを提出しました。

GitHubアカウントがあれば無償で、月50時間まで利用することが出来ます。

OSSコントリビューターは個別に申請すれば、月100時間に上限を緩めてくれるそうですので、
もしかしたらプロジェクト参加者の中にも当てはまる方はいらっしゃるのではないでしょうか。

GitPodの仔細については、以下の記事『Gitpodが最強過ぎる件について』（ https://qiita.com/mouse_484/items/394a4984f749cc201422 ）で説明やスクリーンショットが見られます。ご参考までにどうぞ。

### こちらの要望

- .gitpod.yml追加

GitPodはそのまま立ち上げると、gitpod/workspace-fullというDockerイメージを取得して、そのコンテナ内部で動きます。
これは何でもアリの環境でして、Node.jsはもちろんRubyやPHPやPythonやその他もろもろの開発環境が入っています。
むろんこれでも問題なく作業は出来るのですが、我々にはNode.js環境だけあれば十分でしょう。

その指定をするのが.gitpod.ymlファイルです。
これを追加するべきだというのが私の主張です。

- GitPod用badge

さらに、GitPod用のBadgeを追加するとよりスムーズに立ち上げられます。

```markdown
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/tokyo-metropolitan-gov/covid19)
```
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/tokyo-metropolitan-gov/covid19)


### ご質問事項

> Pull Requestのフローなどはどのようになるのでしょうか？

所詮はただの開発環境ですので、特に開発フローの影響はないと思います。

> 有償or無償の制限などありますか？

前述のとおり、無償利用者は月50時間まで利用可能です。

以上です。よろしくお願いします。

**Comment by kaizumaki** [comment]
@twtwtw-gj 解説ありがとうございます！ 🙏 私も個人的にGitpodを使い始めてみました。なかなかいいですね。
こちらのissue、進めていただいていいでしょうか？（ただ、年末年始シフトに入っているため、リリースは年が明けてからになります）

**Comment by twtwtw-gj** [comment]
了解しました。ぜひやらせてください。

**Comment by twtwtw-gj** [comment]
MRを提出しました。レビューお願いします。
https://github.com/tokyo-metropolitan-gov/covid19/pull/5852
