### ISSUE TITLE
区市町村別 陽性者数の日付が福祉保健局のものと異なります

### ISSUE THREAD

**Issue by Nobukuni-Hyakutake** [tokyo-metropolitan-gov/covid19#5857]
## 起こっている問題 / The Problem
- 本サイトでは、表の右上に「1月1日の累計」となっているが福祉保健局では12月31日時点と書いてあります。
本日1/2 5:00に気がつきました。

## スクリーンショット / Screenshot
![site positive](https://user-images.githubusercontent.com/74386805/103445627-0a938480-4cba-11eb-9982-bae2254bd3bf.png)
![fukushihoken positive](https://user-images.githubusercontent.com/74386805/103445631-0ff0cf00-4cba-11eb-9232-ad18c3e72eb7.png)

## 期待する見せ方・挙動 / Expected Behavior
東京都福祉保健局と本サイトのどちらが正しいのか調べて、修正いただく。

## 起こっている問題の再現手段 / Steps to Reproduce
ブラウザで下記を開く
https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases-by-municipalities/
https://www.fukushihoken.metro.tokyo.lg.jp/hodo/saishin/corona1302.html

## 動作環境・ブラウザ / Environment
- macOS
- Safari

**Comment by mcdmaster** [comment]
@Nobukuni-Hyakutake さん、

> 東京都福祉保健局と本サイトのどちらが正しいのか調べて、修正いただく

という要件を、東京都庁のサポート窓口でなくこの GitHub でご発言をいただけた時点で、あえて下世話な表現をするなら同じ穴のムジナ、自ら手を動かしてする問題解決が求められるというお立場になるというご理解、あるいはご覚悟はお持ちでしょうか？
この年末・年始休暇中にできることは皆限られているという制約条件がおおよそ等しくある中、上記引用部分にあるように作業を半ば一方的にご依頼いただくというよりも、まずはソースコードを覗くなりして出所を突き止めてみる。そうしたスキルをお持ちなら、元からいる開発者も助かるかと思います。

なお、私も市井のいち開発者ですので、このプロジェクトそのものに留まらず、自らが所属している組織等を一切代弁してはいません。そこは、どうかご認識ください。
ご指摘の件は問題なしとはできない点には、私も同意します。どうか、共に手を動かして解決を図りませんか？

**Comment by Nobukuni-Hyakutake** [comment]
mcdmasterさん、"手を動かして"のご指摘ありがとうございます。申し訳ありません。
ソースは下記の4行目のdateが12/30の次は本来12/31となるべきところ、飛んで1/1となってしまっています
(福祉保健局サイト側に間違いがなく、本サイト側が間違っているとしたら。おそらくそうだと思いますが)。
同様の事例 #5769 を見ると東京都が入力している当サイトの元データからの修正が必要なようで、外部の人が直せないみたいですので
東京都担当者(または東京都へ取り次いでいただける方)のご返答を待ちたいと思います。
なおスケジュール的には月曜日以降の修正でも私は全く構わないですし、さらにいうと感染加速のなかで
東京都の方も大変お忙しい状況でしょうから
この不一致の状況だけ東京都担当者へお伝えだけ頂くことで今後公開分が正しくなれば、historyまで遡って治さなくても
私は構いません。私は取り込んでデータ分析に使っているのですが、自分で書き換えるので大丈夫です。
https://github.com/tokyo-metropolitan-gov/covid19/commit/d8a7b5c7d656c7d990bceaa5c788bcbcaf5183e4#diff-519ff60e2d780fdd24435b4be6f818d06e319310c29e2084992f1d71066c71e2
![patient](https://user-images.githubusercontent.com/74386805/103467363-b3f97980-4d91-11eb-88be-31fa82dcfa7d.png)

なお、今日1/3 7:00時点でも両者の日付が違ってしまっていました。
![fukushihoken1-3](https://user-images.githubusercontent.com/74386805/103468010-54529c80-4d98-11eb-8508-6f9929feee17.png)
![site1-3](https://user-images.githubusercontent.com/74386805/103468014-57e62380-4d98-11eb-825a-8c79e70f7924.png)

**Comment by Nobukuni-Hyakutake** [comment]
日付の不一致が無くなっていましたので、解決したためクローズします。
(1月4日 5:00現在、1月2日時点の数値において)
以下はその画面とソースです。
福祉保健局のもの：
![fukushihoken](https://user-images.githubusercontent.com/74386805/103487917-1c0c9600-4e4c-11eb-939e-43c046059536.png)
本サイト：
![tokyomet](https://user-images.githubusercontent.com/74386805/103487920-1fa01d00-4e4c-11eb-86d5-14d65fb4008a.png)
ソース：
![patient](https://user-images.githubusercontent.com/74386805/103487922-22027700-4e4c-11eb-9be1-096e7b707e28.png)

**Comment by kaizumaki** [comment]
@Nobukuni-Hyakutake ご指摘ありがとうございます。返信遅くなりましてすみませんでした。東京都に確認しましたら、おっしゃる通り当サイトのほうのデータの日付がずれていたようです。フォローしていただき、ありがとうございます。

**Comment by Nobukuni-Hyakutake** [comment]
@kaizumaki さん、ご確認いただきましてありがとうございました。
