### ISSUE TITLE
厚生労働省の発表するデータの項目を加える

### ISSUE THREAD

**Issue by nnawata** [tokyo-metropolitan-gov/covid19#5875]
## 改善詳細 / Details of Improvement
- [厚生労働省のオープンデータ](https://www.mhlw.go.jp/stf/covid-19/open-data.html)では、PCR検査の内訳として検査機関別の数字を発表しているので東京都も報告していると考えられます。

## 期待する見せ方・挙動 / Expected behavior
- 民間検査機関の検査数がどの程度入っているのか分かるようにしてください。
- 
## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@nnawata すみません、「民間検査機関の検査数」とは、民間の医療機関によるものとは違うのでしょうか？

**Comment by nnawata** [comment]
最近の検査数の急増状態をみると、医療機関外の検査もあるのではないでしょうかと推定できます。言い換えれば、その辺のことがデータの中に入っているかどうか、内数が見えないのでまったくわかりません。

> 5月7日以降は(1)東京都健康安全研究センター、(2)PCRセンター（地域外来・検査センター）、(3)医療機関での保険適用検査実績により算出。4月10日～5月6日は(3)が含まれず(1)(2)のみ、4月9日以前は(2)(3)が含まれず(1)のみのデータ 

お願いしている背景
保健所別にも陽性者数のみが発表されていて、対象となった検査数や属性（有症・濃厚接触・社会的検査など）がわからないので、「陽性者が増えている」ことの意味が、よく理解できない状況になっています。２３区別には世田谷区の累計陽性者が一番多いのは世田谷のリスクが高いのではなく検査を独自にしているからとの理解ですが、区別検査数はないのでデータからは読み取れません。また会食がリスクを高めているという発表もどういうデータを見て言っているのか、少なくとも公開されているデータからは判断しかねるので、きちんと検査母集団を基礎データを示しておくべきかと考えます。

**Comment by kaizumaki** [comment]
なるほどですね。 @nnawata さんが引用されている部分は「検査人数」のグラフの注釈ですが、当サイトの「検査実施件数」のグラフでは民間の医療機関の件数を分けています。
お示しの厚生労働省のオープンデータを拝見しましたが、こちらも内訳が公表されているのは「PCR検査の実施件数」のほうですね。
当サイトの「検査実施件数」の内訳をさらに詳細に、といったところでしょうか？

**Comment by nnawata** [comment]
特に東京は日本全体の２割前後の影響力があるので、代表して東京を見ているのですが、厚労省と東京都で要約方法が違う（しかも東京がより要約されている）とデータが理解しづらいです。
ウィルスがあまねく広がってきているのであれば、検査機関を問わず陽性率は一定の誤差でほぼ同じになるはずですが、ここのところの陽性率（数ではなく）の変動が、保健所などの検査機関の結果とどの程度違っているのか（あるいは同じなのか）には関心があります。また検査数が増えるほど陽性率は本来なら安定した動きになるはずですが、かえってブレが大きくなってきているので、どこに要因があるのかなと。

**Comment by kaizumaki** [comment]
要望としては、「検査人数」ではなく「検査実施件数」グラフの内訳をさらに詳細に、ということで合っていますか？

**Comment by nnawata** [comment]
グラフの見せ方ではなくgithubのデータで提供してくだされば幸いです。
件数は検査機関別内訳を、人数は市区別検査数と対象属性を、というのが希望です。

**Comment by kaizumaki** [comment]
githubのソースコードだけ提供するというのは話として持っていくのは難しそうですね。当サイトのフロント側にも実装するのが筋かと思います。
現在、検査人数に関してはモニタリング項目に入っているので、そこを変更するのは難しいと思いますが、それ以外に何か方法があるかどうか確認してみます。
ともあれ、かなりのお時間をいただくことになると思うので、どうかご了承ください 🙇‍♀️

**Comment by nnawata** [comment]
ご対応に感謝します。気長に待ちます。それまでにコロナの終息を祈りつつ。

**Comment by kaizumaki** [comment]
@nnawata たいへんお待たせして申し訳ありません。こちらの提案について東京都から回答がありました。検査実施件数及び人数について、東京都としては現在公開しているデータで十分と考えているため、これ以上の細分化はいたしかねます、とのことです。よって、こちらの提案を採用するのは難しいです。ご理解いただけましたら幸いです。

**Comment by nnawata** [comment]
ご対応ありがとうございます。
陽性者数が民間検査の増減によってかなり影響を受けているにも関わらず、連日「今日はｘｘｘ人」という報道に辟易しています。
緊急事態宣言解除されたいま、きちんとした分析をしておくことは、これまでと同じ対応ではすまされない第四波への備えとなるはずなのですが、残念です。

**Comment by kaizumaki** [comment]
東京都から回答がありましたので、こちらのissueはクローズさせていただきます 🙏
