### ISSUE TITLE
お問い合わせ先一覧ページ内「感染防止徹底宣言ステッカー、感染拡大防止協力金等に関すること」の項目修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5881]
お問い合わせ先一覧ページ内「感染防止徹底宣言ステッカー、感染拡大防止協力金等に関すること」の項目の修正をお願いします。

【修正前】
- お問い合わせ内容： `感染防止徹底宣言ステッカー、感染拡大防止協力金等に関すること`
- 局名： `東京都ステッカー申請・感染拡大防止協力金相談センター`
　
↓

【修正後】
- お問い合わせ内容： `東京都緊急事態措置等・感染拡大防止協力金等に関すること`
- 局名： `東京都緊急事態措置等・感染拡大防止協力金相談センター`

![お問い合わせ先一覧](https://user-images.githubusercontent.com/14883063/104395592-60a2da80-558c-11eb-8485-7ffba13f5319.png)

**Comment by Murayu0225** [comment]
やります。
