### ISSUE TITLE
企業の皆様・はたらく皆様へページにコンテンツ追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5882]
企業の皆様・はたらく皆様へページに以下の２つのコンテンツの追加をお願いします
追加する位置は「営業時間短縮に係る感染拡大防止協力金（11/28～12/17実施分）」と「東京都家賃等支援給付金」のあいだです。

【追加項目１】
- タイトル：`営業時間短縮に係る感染拡大防止協力金（12/18～1/7実施分）`
- 本文：`新型コロナウイルス感染拡大防止のため、特別区及び多摩地域の各市町村の飲食店等に営業時間の短縮要請が行われることに伴い、要請に全面的にご協力いただいた中小の事業者の皆様に対し、協力金を支給します。`
- リンク：https://jitan.metro.tokyo.lg.jp/dec/index.html

【追加項目２】
- タイトル：`営業時間短縮に係る感染拡大防止協力金（1/8～2/7実施分）`
- 本文：`新型コロナウイルス感染拡大防止のため、緊急事態宣言が発令され、営業時間短縮が強化されることに伴い、要請に全面的にご協力いただける中小の飲食事業者等に対し、新たに協力金を支給いたします。`
- リンク：https://www.sangyo-rodo.metro.tokyo.lg.jp/attention/2021/0107_14118.html

![企業の皆様](https://user-images.githubusercontent.com/14883063/104396017-3e5d8c80-558d-11eb-9b4f-62d67faa52fc.png)

追記：現在の「**営業時間短縮に係る感染拡大防止協力金（11/28～12/17実施分）**」の本文も修正が必要になりましたので、合わせてお願いします。

修正前：
`新型コロナウイルス感染拡大防止のため、特別区及び多摩地域の各市町村の飲食店等に営業時間の短縮要請が行われることに伴い、要請に全面的にご協力いただける中小の事業者の皆様に対し、協力金を支給します。`

　↓

修正後：
`新型コロナウイルス感染拡大防止のため、特別区及び多摩地域の各市町村の飲食店等に営業時間の短縮要請が行われることに伴い、要請に全面的にご協力いただいた中小の事業者の皆様に対し、協力金を支給します。`

**Comment by Murayu0225** [comment]
やります。

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！先ほど追記をしたところなので、ご確認よろしくお願いします 🙏

**Comment by Murayu0225** [comment]
@kaizumaki 
わかりました！そちらも含めて編集します！
