### ISSUE TITLE
nodeのアップデートに伴う各ドキュメント類の修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5888]
## 改善詳細 / Details of Improvement
- #5515 でnodeをv10.19.0からv10.23.1へアップデートしたので、各ドキュメントの記述も修正したいと思います。

## 期待する見せ方・挙動 / Expected behavior
- 各ドキュメント内と.gitpod.yml内のnodeのバージョンの記述が10.23.1になる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by roottool** [comment]
やります。
