### ISSUE TITLE
ローカル環境でGマークが表示されない

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#5892]
## 起こっている問題 / The Problem
- ローカル環境で `yarn dev` を実行するとき，`functions/g-mark.js` がローカル環境の referer を許容しないためGマークが表示されない

## スクリーンショット / Screenshot
![スクリーンショット 2021-01-14 18 54 01](https://user-images.githubusercontent.com/23148331/104574937-f4160180-5699-11eb-9aff-6b240c18b5c8.png)

## 期待する見せ方・挙動 / Expected Behavior
- ローカル環境でもGマークが表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. ローカル環境で `yarn functions:dev` を実行 
2. ローカル環境で `yarn dev` を実行 
3. http://127.0.0.1:3000/ を開く

## 動作環境・ブラウザ / Environment
- macOS, Chrome

**Comment by kaizumaki** [comment]
@nard-tech お、すみません、ローカル環境でGマークが表示されないのは、何か支障がありますか？

**Comment by nard-tech** [comment]
@kaizumaki 特に困ることはありませんが，#5893 について実装しようとしたときに画像が表示されなかったので違和感を覚えました．
基本的に，ローカル環境でも本番と同じ見た目を再現できるようにするのが原則だと思います．

**Comment by kaizumaki** [comment]
@nard-tech 本番環境と違うという点では、チャットボットもローカルでは表示されないようにしています。
Gマークはかなりデリケートな扱いになるため、東京都とも話し合った上で、ホワイトリスト対応していますので、ご理解いただければ幸いです 🙏

**Comment by nard-tech** [comment]
@kaizumaki 承知しました．では，#5893 のみ対応します．
