### ISSUE TITLE
Gマークの画像から受賞理由が記載されたWebサイトへリンクする

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#5893]
## 改善詳細 / Details of Improvement
- Gマークの画像から https://www.g-mark.org/award/describe/51112 へリンクする

**Comment by kaizumaki** [comment]
@nard-tech ご提案ありがとうございます！個人的には素敵なアイディアだと思うのですが、Gマークの扱いはかなりデリケートになるため、東京都を通じて公益財団法人日本デザイン振興会に確認をとってもらいますね。しばしお待ちいただけると助かります 🙏

**Comment by nard-tech** [comment]
@kaizumaki 承知しました．よろしくお願いします．実装は簡単だったので #5894 を作ってしまいました．確認が取れましたら merge お願いします．
