### ISSUE TITLE
Issue運用についての検討 Improveを全て対応できない旨を記載したい

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#591]
## 改善詳細 / Improve details
* 現在たくさんの改善提案をいただいている
* 中には関係各位について確認しないといけない事があり、採用できない事もある
* 上記に関連して既にPRを作っていただいている方がいる

OSSという性質上全てのImprove/PRを採用する事が出来ないのは出来ないのはみなさんご理解いただいていると思いますが
初めてOSSに貢献したいという方もいらっしゃると思いますので
できればその旨について案内したく思います。

うまく言葉にできないのでどなたか手伝っていただきたいです

## 期待する見せ方・挙動 / Expected behavior
* 全てのImproveを採用できない事を伝えたい
* せっかくPRをいただいたのに上記の都合でマージ出来ない事がある事を伝えたい
* 最終的にHOW TO CONTRIBUTE に記載したい

**Comment by MaySoMusician** [comment]
官公庁関連の仕事には詳しくないのですが、

> 中には関係各位について確認しないといけない事があり、採用できない事もある

この場合、「確認中の公表すらできない」などの場合はありますか？

もしほとんどの場合で公表が可能なら、Watingラベルや独自の確認待ちラベルを付与で、やり取りを簡略化できるのではないかと思いました。

---

文面についてですが、個人的にはこのまま敬体に書き直すだけでも問題ないかと思います。

**Comment by mikkame** [comment]
> 「確認中の公表すらできない」などの場合はありますか？

こちらについてはあいにくまず「確認したほうがいいのではないか？」というところから始まっておりましてそこから誰に確認しなければならないのかを調べる流れになっており
どうしても文言やデザインの変更、機能追加については確認する事が多くなってしまいます。

**Comment by mikkame** [comment]
> Watingラベルや独自の確認待ちラベルを付与で、やり取りを簡略化できるのではないかと思いました。

こちらについては
基本Waitingな気がするので
やってくださいラベルのようなものをつけた方が良さそうですね

**Comment by MaySoMusician** [comment]
少し書いてみました。
```diff
## Issue へのコメントや Pull Request について
* Issue へのコメントはご自由にどうぞ！新しい質問や提案なども受け付けます。
* わかりやすい簡単な修正をスポット的に行うだけであれば、自分のリポジトリに Fork をして、修正版を Pull Request いただいてもかまいません。
+ * 現在非常に多くの改善提案issue・PRをいただいております。修正内容については、
内容を当局側と協議しなければならない場合もあるため、受理までの時間がかかったり、
ご提案通りに受理できない場合もあります。あらかじめご了承のほどよろしくお願いいたします。
```
---
> こちらについてはあいにくまず「確認したほうがいいのではないか？」というところから始まっておりましてそこから誰に確認しなければならないのかを調べる流れになっており
どうしても文言やデザインの変更、機能追加については確認する事が多くなってしまいます。

GitHubのラベルのベストプラクティスからは外れてしまうのですが、「確認したほうがよいかもしれない・確認の準備中」「実際に確認中」「確認済み（OK）」「確認済み（NG）」などの複数ラベルを作る手もあると思います

**Comment by daisuke-fukuda** [comment]
参加したいな〜とは思いつつ、スピード感がものすごいので、現状見て応援しているものです。

基本的には、ご提案いただいた内容をそのまま書いていただければ、要点は十分伝わると思います。

**Comment by bells17** [comment]
可能であれば、ラベルとは別にREADMEかHow to Contributeに

- どういったことは確認が絶対に必要と思われるか(e.g. UI変更など)
- どういったことであればおそらくあまり確認などは不要と思われるか(e.g. HTMLタグのメタデータ追加など)

などの具体例をあげておいて頂いておくと、コントリビュートしたい方がどういった事柄ならコントリビュートしやすいかがわかりやすいかと思いました

**Comment by MaySoMusician** [comment]
ラベルにするなら以下のようになるかと
「確認したほうがよいかもしれない・確認の準備中」 = `need-official-confirmation`
「実際に確認中」 = `currently-confirming`
「確認済み（OK）」 = `officially-approved`
「確認済み（NG）」 = `officially-rejected`

逆に #309 のような当局からの依頼はすぐ着手できるかと思うので `help-wanted` を使うか `officially-requested` を別に作って明示しても良いと思います。

**Comment by mikkame** [comment]
ご意見ありがとうございます

> 内容を当局側
> official

こちらについては明示的にだれをというのを指定する事が難しいです。

**Comment by MaySoMusician** [comment]
「当局側」は「関係各所」ぐらいでも大丈夫でしょうか？（これよりもぼかす必要あり？）
チーム内の決定事項か、関係各所との決定事項かは分離するべきかと思っていましたが、そうでもなさそうですかね... もしなければ単に `need-confirmation` `approved` でも大丈夫だと思います（ラベル付けの負担がかかる、という問題はありますが...）

**Comment by mikkame** [comment]
みなさまありがとうございます。
取り急ぎ

- help wanted
- good first issue
- bug 

から着手してもらうような方向で調整したく思います。

**Comment by nard-tech** [comment]
@mikkame close になっているところを蒸し返すようですみません．#533 の議論の過程で気になる点がありコメントさせて頂きましたので，お手数ですが #533 にも目を通して頂けるとありがたいです．
