### ISSUE TITLE
【要再デザイン？】地下鉄利用者数推移のハイライト表示が凡例の色と異なる

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#592]
## 起こっている問題 / Occurred problem
* グラフ上にマウスポインタを載せるとグラフが明るくなりますが、上の判例と色が異なってしまうため読み取りにくい

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/34566290/76046785-382d7580-5fa4-11ea-8783-8fa015162ffa.png)

## 期待する見せ方・挙動 / Expected behavior
* マウスポインタを載せたときの挙動をハイライト以外にする（例: その部分の背景色を変える・枠を付ける？）
* アクセシビリティ方面は詳しくないのですが、6色（非選択時3色+選択時3色）がそれぞれ似通っているので色覚多様性（色覚異常）の方に優しくないかも
* 上記2点を総合的に評価して、もしかしたら再デザインの可能性アリ？

## 起こっている問題の再現手段 / Steps to reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/
2. 「都営地下鉄の利用者数の推移」のグラフ上にマウスポインタを合わせる

## 動作環境・ブラウザ / Environment
* Windows 10 Home 64 bit
* Chrome 80.0.3987.132

**Comment by juggra** [comment]
> アクセシビリティ方面は詳しくないのですが、6色（非選択時3色+選択時3色）がそれぞれ似通っているので色覚多様性（色覚異常）の方に優しくないかも

自分も疎いのでそこは一旦置いておいて、ハイライトだけ修正しました。
ですので、前述の点が問題なければマージ、再デザインするのであればお手数ですがリジェクトしていただけると助かります。

**Comment by nard-tech** [comment]
#544 も合わせてご確認ください．

**Comment by kaizumaki** [comment]
すでにPRがきているので `important` ラベルをはずしました。

**Comment by kaizumaki** [comment]
現在の `development` で #1845 のマージによりグラフのカラーが変わりましたので、こちらのissueはcloseさせていただきます 🙇‍♀
