### ISSUE TITLE
サイトトップのファーストビュー改修

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5937]
サイトトップのファーストビューを改修します。
**こちらのissueは東京都の方が対応します。**

- 最新のお知らせに表示している【●●時点の都内患者数】【●●の状況】の別カード化
- 【滞在人口の増減状況】の１地点表示・カード化
- モニタリング会議資料の一部をスライドバナー表示

改修後イメージはこちら↓

<img width="1360" alt="202101281050_pc" src="https://user-images.githubusercontent.com/14883063/106103460-5421a300-6184-11eb-8680-f800e873f662.png">

**Comment by kaizumaki** [comment]
こちらは東京都の @tmatsuno さんが対応します。

**Comment by tmatsuno** [comment]
対応いたします。
