### ISSUE TITLE
ESLintをCIで回すようにしたい

### ISSUE THREAD

**Issue by kawoka** [tokyo-metropolitan-gov/covid19#594]
## 改善詳細 / Improve details
現状、ESLintが回るのがhuskyによるpre commitのタイミングのみで、skipが容易にできてしまう。
また、それをレビューで気づくことも難しいので、CIでESLintのエラーチェックをおこないたい。

https://github.com/tokyo-metropolitan-gov/covid19/pull/515
こちらせっかくマージいただいたので、今後の品質の担保もできると幸いです！ 🙇 

## 期待する見せ方・挙動 / Expected behavior
* CIでESLintを回すことでマージ前にESLintのエラーに気づけるようにすること

## 動作環境・ブラウザ / Environment
*

**Comment by kawoka** [comment]
試してみていたのですが、こちらのnetlifyのCIログをみたところ、package.jsonのものではなく、直接nuxtコマンドが叩かれていそうな感じがするので、gitのリポジトリ上からCIタスクに触ることは難しいでしょうか？

https://app.netlify.com/sites/dev-covid19-tokyo/deploys/5e61d5b5684ca7000b148660
`1:47:07 PM: Executing user command: nuxt generate`

**Comment by mikkame** [comment]
確かに yarn generate にした方がいい気がします
（あってますか？）

**Comment by kawoka** [comment]
その認識です！
（ `yarn generate` は `nuxt-ts` で、deploy taskはnuxtコマンドを使っているように見えるので、この辺の背景がわからないのが不安ですが、、）

`yarn generate` にしていただけると、下記PRでいろいろ試せますので嬉しいです！
https://github.com/tokyo-metropolitan-gov/covid19/pull/597

**Comment by mikkame** [comment]
すみません、その件はとりあえずぐぐって設定しちゃった感じです

**Comment by mikkame** [comment]
yarn generateに変えてみました
空コミットプッシュして確認してもらえますか？（push検知しないと多分まわらないですよね？）

**Comment by kawoka** [comment]
ありがとうございます！！
試してみます！

**Comment by kawoka** [comment]
落ち方が禍々しいですが、lintでエラーになること確認できました！ありがとうございます！

<img width="866" alt="スクリーンショット 2020-03-06 15 40 54" src="https://user-images.githubusercontent.com/4666330/76058903-e515eb80-5fc0-11ea-85b5-47ac7e039745.png">
<img width="680" alt="スクリーンショット 2020-03-06 15 40 10" src="https://user-images.githubusercontent.com/4666330/76058907-e7784580-5fc0-11ea-9abe-910ff3c9a741.png">

https://app.netlify.com/sites/dev-covid19-tokyo/deploys/5e61efde2468c0000ca70b87


（travisなど入れていい感じにできるともっとよいかもしれないですが...！取り急ぎ！）
