### ISSUE TITLE
リモート上で改行コードが混在している

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#5940]
## 起こっている問題 / The Problem
- 本レポジトリ上のファイルの改行コードが統一できておらず、「CR+LF」と「LF」が混在しているようです。（例: `yarn.lock` の改行コードが CR+LF）

## 期待する見せ方・挙動 / Expected Behavior
- LFに統一する（本プロジェクトにはWindows用のスクリプトなどは無いので、LFに合わせたほうが良いと思います）
- （可能であれば）開発者向けドキュメントに、コミット時に改行コードが「LF」となるようにお願いする（gitの `core.autocrlf` 設定が `true` / `input` の場合、コミット時に改行コードがLFに統一できます。）

## Notes
- #5927 対応中に発見

**Comment by munierujp** [comment]
>（可能であれば）開発者向けドキュメントに、コミット時に改行コードが「LF」となるようにお願いする

- 各自が使用するエディタで[EditorConfig](https://editorconfig.org/)の導入を推奨する
- VS Codeユーザー向けに`.vscode/extensions.json`で`recommendations`に`EditorConfig.EditorConfig`を指定する

などもありかと思います。

**Comment by kaizumaki** [comment]
@munierujp たしかに、EditorConfigはないときついものがありますね。

**Comment by Foo-x** [comment]
対応します。
