### ISSUE TITLE
サイドナビへ外部リンク項目「自宅療養者向けハンドブック」の追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5941]
サイドナビに以下の外部リンク項目の追加をお願いします。

テキスト： `新型コロナウイルス感染症自宅療養者向けハンドブック`
リンク先：https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/zitakuryouyouhandbook.html
位置：「新型コロナウイルス感染症都民向け感染予防ハンドブック」と「都民利用施設・都主催イベントに関する情報」の間

![スクリーンショット 2021-01-29 10 36 56](https://user-images.githubusercontent.com/14883063/106220323-95ff2780-621e-11eb-87ea-222d250200da.png)

**Comment by Murayu0225** [comment]
やります。
