### ISSUE TITLE
記述されている日本語を「やさしい日本語」にできないか

### ISSUE THREAD

**Issue by k018c1077** [tokyo-metropolitan-gov/covid19#595]
## 改善詳細 / Improve details
サイトに記述されている日本語の表現が外国人の方や、お年寄り、子どもには難しいように思います。
例）都内の最新感染動向

公的機関も関わっているもので、「優しい日本語」と言うものがあります。

>どんなときに使う？
>●災害時・緊急時（急病・ケガ・事件等）
>翻訳する時間がなく、急いで情報を伝えないといけないとき
引用：https://www.sic-info.org/wp-content/uploads/2014/02/easy_japanese.pdf

まさに今が優しい日本語を使う時だと思います。

## 期待する見せ方・挙動 / Expected behavior

例）都内の最新感染動向　→　とうきょう　の　ウイルス　の　ひろがりかた

**Comment by MaySoMusician** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/62#issuecomment-594329698 のスプレッドシートに、やさしいにほんごが含まれているようです

**Comment by yuhkih** [comment]
少しだけ参加させて頂きました。
NHKの「やさしい日本語で書いたニュース」を参考にしたのと、日本語能力検定 JLPT (日本語能力試験コース）の N5 (一番優しいグレード）で出てくる単語で置き換えられそうなのは、できるだけ置き換えるようにしました。

「やさしい日本語で書いたニュース」：https://www3.nhk.or.jp/news/easy/
 JLPT N5 単語 : https://jlptstudy.net/N5/?vocab-list
