### ISSUE TITLE
モバイル版ブラウザでハンバーガーメニューを押してもリストが出てこない

### ISSUE THREAD

**Issue by butsuli-shine** [tokyo-metropolitan-gov/covid19#5956]
## 起こっている問題 / The Problem
ハンバーガーメニューを押してもリストが出てこない

## スクリーンショット / Screenshot
![Screenshot_2021-02-01-19-14-27-736_com android chrome](https://user-images.githubusercontent.com/66987550/106445379-4b9dd500-64c2-11eb-840d-c246261f7143.jpg)

## 起こっている問題の再現手段 / Steps to Reproduce
1. ハンバーガーメニューを押す

## 動作環境・ブラウザ / Environment
-  iOS / Android
- Chrome / Safari

**Comment by kaizumaki** [comment]
@butsuli-shine ご指摘ありがとうございます！私のほうでもこちらの現象を確認しました。
safariのエミュレーターでコンソールをみたところ、今日のリリース #5927 で起こっていたようです。
https://github.com/tokyo-metropolitan-gov/covid19/blob/766814f93c68e4ed38a3a4dd50471549a4ab6abd/layouts/default.vue#L82-L88

<img width="943" alt="スクリーンショット 2021-02-01 19 37 47" src="https://user-images.githubusercontent.com/14883063/106447713-2a8ab380-64c5-11eb-85b0-a8d9f57e64e6.png">

**Comment by kaizumaki** [comment]
上記のエラーにしたがって私のほうで対応しますが、もし他に原因となるものがあった場合はコメントお寄せください 🙏

**Comment by butsuli-shine** [comment]
ありがとうございました！
