### ISSUE TITLE
Add English Localization

### ISSUE THREAD

**Issue by ashcoding** [tokyo-metropolitan-gov/covid19#596]
## 改善詳細 / Improve details
* xxxx(できるだけ簡潔に/as concise as possible)

Have a button to change everything to English on the website.

## スクリーンショット / Screenshot

None.

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

All Japanese text becomes English.

## 動作環境・ブラウザ / Environment
*
All

**Comment by MaySoMusician** [comment]
As far as I know, we've completed translation into English, but some texts need to be checked by the authorities or other related organizations. Once the translation is approved, we're probably going to commit these changes.

Our core members may also add some details here; I'm just a contributor.

**Comment by mikkame** [comment]
HI. thanks your issue 

same reaming issue has been opened #60

**Comment by MaySoMusician** [comment]
@mikkame #60 はfaviconの話のようなので #62 かも...

**Comment by mikkame** [comment]
sorry my bad. updated my comment
