### ISSUE TITLE
サイトトップのファーストビュー改修翻訳表示対応

### ISSUE THREAD

**Issue by tmatsuno** [tokyo-metropolitan-gov/covid19#5965]
#5937 の継続Issueです。
#5937 で作り込んだ表示の翻訳表示の対応を実施します。
Transifex対応やテンプレートやスクリプトに作り込みを行います。

**Comment by tmatsuno** [comment]
言語別の単位対応をどうするか方針決定待ち at 東京都 政策企画局
https://github.com/tokyo-metropolitan-gov/covid19/pull/5939#issuecomment-769652488

**Comment by kaizumaki** [comment]
#6347 で解決したと思われるので、こちらのissueはクローズといたします。
