### ISSUE TITLE
「企業の皆様・はたらく皆様へ」ページコンテンツ修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#5970]
「企業の皆様・はたらく皆様へ」ページのコンテンツを以下のように修正をお願いします。

1. 「営業時間短縮に係る感染拡大防止協力金（11/28～12/17実施分）」削除

1. 「営業時間短縮に係る感染拡大防止協力金（1/8～2/7実施分）」URL差替
修正前：https://www.sangyo-rodo.metro.tokyo.lg.jp/attention/2021/0107_14118.html
↓
修正後：https://jitan.metro.tokyo.lg.jp/jan/index.html

1. 「TOKYOテレワークアプリ」追加
タイトル：`TOKYOテレワークアプリ`
本文：`テレワークの導入・実践に必要な情報を入手できるほか、セミナー等のお申込みやサテライトオフィス等の検索など、テレワークの推進を支援する東京都公式アプリです。`
リンク先：https://tokyo-telework.jp/lp/2002app/index.html　
配置：「新しいワークスタイルや企業活動の東京モデル「スムーズビズ」」の下

**Comment by Murayu0225** [comment]
やります。
