### ISSUE TITLE
日付のフォーマットを統一

### ISSUE THREAD

**Issue by akihironagai** [tokyo-metropolitan-gov/covid19#5973]
## 改善詳細 / Details of Improvement
- YYYY/MM/DD 形式や YYYY年MM月DD日 形式、YYYY年mm月dd日 形式が混在しているため統一する。

## スクリーンショット / Screenshot
<img width="895" alt="Screen Shot 2021-02-04 at 13 05 20" src="https://user-images.githubusercontent.com/77012577/106843731-14117180-66ea-11eb-8cea-c9ac9159ce77.png">

## 期待する見せ方・挙動 / Expected behavior
- 日付のフォーマットを統一する

**Comment by kaizumaki** [comment]
@akihironagai ご提案ありがとうございます！フォーマットが異なっているのは主に先日追加したファーストビューのコンポーネントだと思います。グラフカード内の日付フォーマットが当サイトでは最も使われているように思うので、それに揃えるのがよさそうですが、いかがでしょう？
ちなみに、一番上のタイトル横の最終更新については #5109 で議論された流れがあるので、できればそこはそのままにしたいです。

**Comment by nard-tech** [comment]
@kaizumaki こちら，着手します．
