### ISSUE TITLE
[リファクタ]TimeBarChart.vueのbyDateを消す

### ISSUE THREAD

**Issue by kobatakuJP** [tokyo-metropolitan-gov/covid19#5976]
## 改善詳細 / Details of Improvement
`TimeBarChart.vue`にPropで定義されている`byDate`は使われていないPropのようです。消しませんか。  
たぶん以下のプルリクの消し忘れかなと思います。  
https://github.com/tokyo-metropolitan-gov/covid19/pull/4079

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/36495393/106866263-96605c80-670f-11eb-9edf-940fe4d14762.png)

## 期待する見せ方・挙動 / Expected behavior
`TimeBarChart.vue`にPropで定義されている`byDate`がない

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

曜日ごとのグラフを表示できるといいなと思いコード見ていたところで気になったので。

**Comment by kaizumaki** [comment]
@kobatakuJP すみません、そのpropsはこちらで使われているようです。「報告日別による陽性者数の推移」グラフのカードで「日別値」と出すためですね。
https://github.com/tokyo-metropolitan-gov/covid19/blob/89ff14ad684f5323ecaa40ae803b236469d4395c/components/cards/ConfirmedCasesNumberCard.vue#L11

**Comment by kobatakuJP** [comment]
@kaizumaki 
ご指摘ありがとうございます。すみません、grepの方法が悪かったです。
本件、取り下げます。
