### ISSUE TITLE
FORKED_SITES.md のリンク切れを自動検知する

### ISSUE THREAD

**Issue by Meiryo7743** [tokyo-metropolitan-gov/covid19#5983]
## 改善詳細 / Details of Improvement

-   「[このサイトから派生したサイト](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md)」のリンク切れを確認する作業を自動化し，ドキュメントのメンテナンス性を向上させる。
-   GitHub Actions を使って，これを定期的に実行する。

当該ページは，主に派生サイトのリンクが追加される時にしか更新されません。ただ，その更新頻度の低さと派生サイト数の多さゆえに，リンク切れを見かけることがあります（現行の版で 5 つのリンク切れを確認しました）。

恐らく，今後も同様のことが起こりうる可能性は無きにしもあらずです。ただ，それに気づいた誰かが issue と PR を出す，という流れを毎回行うのは煩雑に見えます。それならば，いっそのこと GitHub Actions で定期的に実行した方が良策だろうと考えた次第です。

もしこの機能が必要であるとお考えでしたら，当方で実装し，PR を出します。

## 期待する見せ方・挙動 / Expected behavior

-   `FORKED_SITES.md` に掲載されている派生サイトのリンクを定期的に確認し，リンク切れを発見した場合，該当箇所を自動で削除する。

**Comment by kaizumaki** [comment]
@Meiryo7743 ご提案ありがとうございます！自動化、いいですね。私としてはactionsに組み込む場合、マニュアル起動あるいは月１くらいのスケジューリングで動くといいなと思っています。
またリンク切れ分の削除について運営で話し合いましたが、削除するのではなく、「ステータス」という列を追加し、そこに `（リンク切れ）` と入れておくのがいいのでないかということになりました。過去に派生して作られた事実は残しておきたいですし、一時的にサーバが落ちてしまっていてリンク切れ状態になっているケースとかもあると思います。

こんな感じで実装をお願いできればと思いますが、いかがでしょう？

**Comment by Meiryo7743** [comment]
@kaizumaki

> またリンク切れ分の削除について運営で話し合いましたが、削除するのではなく、「ステータス」という列を追加し、そこに （リンク切れ） と入れておくのがいいのでないかということになりました。過去に派生して作られた事実は残しておきたいですし、一時的にサーバが落ちてしまっていてリンク切れ状態になっているケースとかもあると思います。

なるほど，了解しました。

ところで，`FORKED_SITES.md` 側に「GitHub Actions を使って定期的にリンク切れの有無を確認しています」という旨の注釈を挿入すべきでしょうか……？

**Comment by kaizumaki** [comment]
> ところで，`FORKED_SITES.md` 側に「GitHub Actions を使って定期的にリンク切れの有無を確認しています」という旨の注釈を挿入すべきでしょうか……？

手動でPRを出さなくていいですよ、という意味合いですね。そうですね、入れておいてもらえると良いかと思います。

**Comment by Meiryo7743** [comment]
draft ですが PR 出しました。
