### ISSUE TITLE
陽性者数の推移グラフに「曜日毎」を追加する

### ISSUE THREAD

**Issue by kobatakuJP** [tokyo-metropolitan-gov/covid19#5992]
## 改善詳細 / Details of Improvement
- 陽性者数の推移グラフに「曜日毎」を追加する
     現在の感染者数推移は曜日ごとに差があり、都民もそれを認識している。  
     そこで、グラフを曜日ごとの表示に切り替えられる機能を入れたらどうでしょう。 

## スクリーンショット / Screenshot
例えば以下の感じで
![image](https://user-images.githubusercontent.com/36495393/107111075-58d70d00-6890-11eb-9d69-27453d14d8d3.png)
![byDay](https://user-images.githubusercontent.com/36495393/107111140-d9960900-6890-11eb-9863-90e1d548badc.gif)

## 期待する見せ方・挙動 / Expected behavior
- スクリーンショット参照

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@kobatakuJP 運営です。ご提案ありがとうございます！グラフの変更やデザイン・見た目のご提案については、オーナーである東京都の確認が必要になります。ですので、しばらくお待ちいただけると幸いです。

**Comment by kobatakuJP** [comment]
@kaizumaki ご確認ありがとうございます。見た目はご指摘あれば修正していきます。よろしくお願いいたします:smile:

**Comment by kaizumaki** [comment]
@kobatakuJP ご提案ありがとうございます。たいへんお待たせしました。こちらについて東京都に確認いたしました。
当サイトでは、曜日による差を平準化するために7日間移動平均値を公式としてご案内しています。一部の報道で見られるような曜日ごとの値をグラフ化して見せることは公式としては提供しないという判断となります。ですので、こちらのご提案を採用するのは難しいです。ご理解いただけましたら幸いです。

**Comment by kobatakuJP** [comment]
@kaizumaki ご確認いただきありがとうございます。また、遅くまで業務お疲れ様です。  
個人的には、7日間移動平均よりも曜日ごとのグラフが見えた方が一般の方向けにほしい情報を直感的に表示するには随分良いかと思っております（恥ずかしながら「移動平均」の意味を存じ上げませんでした）。  
ただ既に行政として判断されたとのことですので、承知いたしました。  
ご検討いただきありがとうございました。

**Comment by kaizumaki** [comment]
東京都から回答がありましたので、こちらのissueはクローズさせていただきますね。ご提案ありがとうございました 🙇‍♀️
