### ISSUE TITLE
[i18n] 感染状況・医療提供体制（サマリ）の多言語化

### ISSUE THREAD

**Issue by teikan** [tokyo-metropolitan-gov/covid19#5994]
## 改善詳細 / Details of Improvement
- 感染状況・医療提供体制（サマリ）の「人」「件」「床」が多言語化されていないため、日本語以外でもそのまま表示される

## スクリーンショット / Screenshot
![before](https://user-images.githubusercontent.com/115516/107113372-ec650980-68a1-11eb-948b-98ce68ae542f.png)

## 期待する見せ方・挙動 / Expected behavior
- その言語で表示される
- (スペースをどう入れるかという問題はありますが)

![after](https://user-images.githubusercontent.com/115516/107113661-b2950280-68a3-11eb-8d28-bec99715ba5c.png)

**Comment by kaizumaki** [comment]
@teikan ご提案ありがとうございます！こちら #5939 の残課題となっています。こちらのコメント https://github.com/tokyo-metropolitan-gov/covid19/pull/5939#discussion_r567406077 に沿った形にしたいと思っています！

**Comment by teikan** [comment]
ありがとうございます。見落としていました。こちらはcloseします。
