### ISSUE TITLE
滞在人口の増減状況カードの中の v-icon mdiChevronRight の位置が入れ違いになっている

### ISSUE THREAD

**Issue by tmatsuno** [tokyo-metropolitan-gov/covid19#5996]
## 起こっている問題 / The Problem
- ●緊急事態宣言中の都内の滞在人口の増減状況　の　詳細はこちら　の v-icon mdiChevronRightが文字の後ろに来ている

## スクリーンショット / Screenshot

<img width="523" alt="スクリーンショット 2021-02-08 18 08 17" src="https://user-images.githubusercontent.com/1682239/107198668-c1f98480-6a38-11eb-8c97-8bed0e8bce8a.png">

## 期待する見せ方・挙動 / Expected Behavior
- 正しくは文字の頭に v-icon mdiChevronRightを持ってくる

## 起こっている問題の再現手段 / Steps to Reproduce
1. ファーストビューの表示で再現

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Murayu0225** [comment]
このIssueやってもよろしいでしょうか？

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！ぜひお願いします！

**Comment by Murayu0225** [comment]
教えていただきありがとうございます！やらせていただきます。
