### ISSUE TITLE
favicon を変える

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#60]
忘れがち！

**Comment by saladdays** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/32

**Comment by saladdays** [comment]
お手すきでこちらの素材DLしていただければと思いますー。
お願いしまっす！

**Comment by saladdays** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/32#issuecomment-593063560
faviconと一緒にWebクリップアイコンも設定ください！

**Comment by kaizumaki** [comment]
反映されているようなので、こちらのissueは閉じますね。
