### ISSUE TITLE
Divide the README into each language

### ISSUE THREAD

**Issue by sorairolake** [tokyo-metropolitan-gov/covid19#601]
## 改善詳細 / Improve details
* READMEは言語毎に分かれている方が良いと思います。<br>I think that the README should be divided into each language.

## 期待する見せ方・挙動 / Expected behavior
* READMEが日本語版と英語版で分かれている。<br>The README is divided into Japanese and English.

**Comment by yokinist** [comment]
間違いないですね・・PRつくります！
