### ISSUE TITLE
lint でエラー多発

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#6010]
## 起こっている問題 / The Problem
- `yarn lint` を実施すると、`error  Definition for rule 'simple-import-sort/sort' was not found` なるエラーが多発する

## スクリーンショット / Screenshot

![スクリーンショット 2021-02-17 022411](https://user-images.githubusercontent.com/10361533/108099075-7d6c8980-70c7-11eb-9b0b-9661b0103457.png)

## 期待する見せ方・挙動 / Expected Behavior
- 上記エラーの抑止
- #5858 等、関連すると思われるアップデートは巻き戻さない（対策前進で）

## 起こっている問題の再現手段 / Steps to Reproduce
1. 本イシュー時点の内容で、`development` ブランチをローカルにフェッチ
2. `yarn lint` もしくは `yarn lint:fix` を実行
3. エラー発生

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster 反応遅くなりました 🙏 ご指摘のlintエラー、私の手元では再現しないのですが、どうなんでしょう？

**Comment by mcdmaster** [comment]
@kaizumaki どうか、ご無理をなさらぬよう。

個別の環境の相違はあると思います。
とはいえ、私の場合は #5858 のタイミング以降、とくにこちら側で変更を加えていない環境で突然エラーが多発したので、いささかたじろぎました。
あと、関連 PR #6011 本文にある文献も幸か不幸か見つけるに至りましたので、私の立ち位置は「変更すべし」というものです

**Comment by kaizumaki** [comment]
eslint-plugin-simple-import-sortのドキュメントを見ましたが、どうやらv6.0.0からの変更点みたいですね。
https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/CHANGELOG.md#version-600-2020-11-15
現在、当リポジトリ内のeslint-plugin-simple-import-sortはv5.0.3なので、こちらのアップデートも同時にやってもらう必要がありますね。
ただ、現時点で @mcdmaster さんの環境にエラーが多発しているということは、yarn.lockが壊れているのかと思いますので、そのあたり注意してもらえると助かります。
