### ISSUE TITLE
アクセシビリティ方針および試験結果を掲載したい（miChecker）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6018]
当サイトに「サイトポリシー」「アクセシビリティ方針」「試験結果」を掲載することになりました。
そこでmiCheckerにかけてみたところ、遅延読み込みにしたグラフが認識されないらしいことがわかりました。

そもそも、いわゆるSPAライクなサイトでmiCheckerをどのように使えばいいかもわかっておらず…

試験後のアクセシビリティ対応もさることながら、まずはmiCheckerでちゃんと検査結果を取得するところを目指したいです。

みなさんのアドバイス・ご意見をいただきたく思います。
@magi1125 さん、いかがでしょうか？

（miCheckerをかけてみた結果）
![miChecker_sitetop_1](https://user-images.githubusercontent.com/14883063/108646248-91b1eb80-74f8-11eb-96bb-f5e07c2eba99.png)

![miChecker_sitetop_2](https://user-images.githubusercontent.com/14883063/108646268-9aa2bd00-74f8-11eb-98fa-8c6a5897b6c8.png)

ちなみに「サイトポリシー」と「アクセシビリティ方針」は東京都のほうで案を作成するそうです。こちらについても、もしアドバイス等あればコメントお寄せください！

（参考）https://www.metro.tokyo.lg.jp/concept/index.html

**Comment by magi1125** [comment]
@kaizumaki ふたたび召喚いただきありがとうございます！

> 「サイトポリシー」「アクセシビリティ方針」「試験結果」

了解しました。
Webアクセシビリティの試験については以下が参考になると思います。
https://waic.jp/docs/jis2016/test-guidelines/202012/
https://waic.jp/docs/jis2016/test-guidelines/202012/example.html

よくあるFAQはこちらです。
https://waic.jp/qa_category/test/

大まかにいうと、

- ちゃんと試験できそうであれば誰が試験してもよい
- チェックに際しどのツールを使ってもよい（アクセシビリティチェックツールで分かる課題は全体の2割程度と言われていて、主には個別に見ていくやりかたになります）
- 事前に達成基準チェックリストを作る
- 事前に実装チェックリストを作る（JISの達成基準に対してどういう実装方法でクリアするのかをまとめたもの）
- 試験の際は適切に対象ページをサンプリングする（が、このサイトの場合はページ数は多くないので全部になりそう）

という感じです。そんな中で、まずは前提の確認なのですが

> まずはmiCheckerでちゃんと検査結果を取得するところを目指したいです。

というところ、チェックはmiCheckerでの実施が必須という形でしょうか？
いま手元にwindowsがなくてパッと手元では試せないのですが、チェックが走るタイミングが固定されているとするとSPAではうまく使えないかもしれません（遅延読み込み外したバージョンを用意するとかが必要になりそう）。

チェックツールを変えて良ければ、やりようはありそうかなと思います。たとえばaxeを使えば、Chromeで画面を出しつつ、状態変化させつつ、devtoolのように画面の個別コンポーネント単位でチェックを掛けることができます。
https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd
ツールごとにチェックのやり方はそう大きく変わるわけではないので、これが許容されれば

>いわゆるSPAライクなサイトでmiCheckerをどのように使えばいいかもわかっておらず…

これはごもっともで、そもそも動的な状態変化があるSPAにおける「ページ」とは何なのか？というあたりから考える必要がでてきそうですよね。ユニークURLがある＝ページとも言い切れないですし。
このあたりは結局、アクセシビリティを必要とする人が実用になるかが重要なので、URL単位でチェックしつつ、そのURLのなかでの状態変化はそれを再現しつつ個別にチェックしていく、ということになろうかと思います。

SPAで試験をやって結果を公開している例としては @masuP9 が関わったWinTicketが参考になるかと思います。
https://www.winticket.jp/accessibility

**Comment by kaizumaki** [comment]
@magi1125 ありがとうございます！詳細な解説、とても助かります 🙏 

miCheckerで、と思ったのは総務省からの指示があるからかもしれないということで、私もちゃんと確認していませんでした。他のツールでチェックできるのならmiCheckerでなくてもいいと私は思います。東京都に確認しますね。

そもそも今回の話となったのは、都の運営しているウェブサイトが「東京都公式ホームページ作成に関する統一基準」に準拠しているかどうかという調査が最近あったらしく、「サイトポリシー」「アクセシビリティ方針」「試験結果」の公開がされていないとの指摘があったからなのでした。
しかも年度末までの対応との希望がありまして、少々焦っております 💦 

> ・事前に達成基準チェックリストを作る
> ・事前に実装チェックリストを作る（JISの達成基準に対してどういう実装方法でクリアするのかをまとめたもの）

この点、重要だと思いましたが、当サイトでは東京都の担当課といっしょに作る必要がありそうですね。どのように進めるのがよいでしょうか？

> このあたりは結局、アクセシビリティを必要とする人が実用になるかが重要なので、

これは全くおっしゃる通り。本末転倒にはしたくないですね。

@masuP9 さんのWinTicketはすごく参考になりそうだと思いました。

**Comment by masuP9** [comment]
@kaizumaki @magi1125 呼ばれた気がしましたので、横から失礼します。

年度末までに「アクセシビリティ方針」とその「試験結果」ページを作成する、という点なかなかのハードスケジュールに思いました。

昨年の3月に実施した有志による試験においては、運営主体でないため方針こそ作成していませんが、東京都のアクセシビリティ方針と同様の等級「AA」を基準にチェックしています（自治体が運営するサイトではAAが求められるため）

- 有志による試験 = [オンラインアクセシビリティもくもく会 - 東京都新型コロナウイルス対策サイト改善](https://ca11y.connpass.com/event/169901/)
- [試験結果[Google Spreadsheet]](https://docs.google.com/spreadsheets/d/1htJAZQ4ylX0jMY2SHjTEdSIQFEW-SsVqmjaJ1uB3KZ0/edit#gid=0)

ページ自体は昨年3月の試験時点からかなり変わっているとはいえ上記の試験結果をベースに

- 前回試験時点で問題だった箇所が改善されたかどうかの確認
- 新規箇所の試験実施

という進め方の方がイチから検討し実施するよりリーズナブルかもしれません。

**Comment by kaizumaki** [comment]
@masuP9 おお！なんとありがたいご提案ありがとうございます！その進め方、東京都の担当課には激推ししておきます！
有志のみなさんには本当に大感謝です 🙏

**Comment by magi1125** [comment]
#6246 が立ったのでこちらはcloseしますね
