### ISSUE TITLE
「企業の皆様・はたらく皆様へ」ページにコンテンツ追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6019]
「企業の皆様・はたらく皆様へ」ページに以下のコンテンツの追加をお願いします。

タイトル：`営業時間短縮に係る感染拡大防止協力金（2/8～3/7実施分）`
リンク先：https://www.sangyo-rodo.metro.tokyo.lg.jp/attention/2021/0205_14245.html
紹介文：`新型コロナウイルス感染拡大防止のため、緊急事態宣言が延長され、引き続き、営業時間の短縮が要請されることに伴い、要請に全面的にご協力いただける飲食事業者等に対し、新たに協力金を支給いたします。`　
配置：「営業時間短縮に係る感染拡大防止協力金（1/8～2/7実施分）」と「東京都家賃等支援給付金」の間

**Comment by Atria64** [comment]
こちら、自分やってみてもよろしいでしょうか。

**Comment by kaizumaki** [comment]
@Atria64 ありがとうございます！ぜひお願いします！ちなみに当リポジトリでは `assets/locales/ja.json` といった翻訳ファイルには触らなくて大丈夫ですので、そこだけ気にしておいてください 🙏

**Comment by Atria64** [comment]
[PR#6020](https://github.com/tokyo-metropolitan-gov/covid19/pull/6020)を開きました。よろしくお願いいたします。
