### ISSUE TITLE
ナビゲーションメニューのスクロールバー表示について

### ISSUE THREAD

**Issue by mokuzuu** [tokyo-metropolitan-gov/covid19#602]
## 改善詳細 / Improve details
Figmaのデザインではナビゲーションメニューにスクロールバーはなかったのですが、最新のdevelopmentブランチには表示されていたので、変更した方がいいのかと！

**Comment by kaizumaki** [comment]
ご指摘ありがとうございます！スクロールについては #261 で実装した経緯があります。
@saladdays さんのご意見をうかがいたく思います！

**Comment by mokuzuu** [comment]
おお！なるほど！
承知いたしました！

**Comment by saladdays** [comment]
こちらでお返事させて頂きました！
https://github.com/tokyo-metropolitan-gov/covid19/issues/527#issuecomment-595781833
