### ISSUE TITLE
明示的にimportされていないcomponentsがある・componentsのimport手法にブレがあることに関する対処

### ISSUE THREAD

**Issue by y-chan** [tokyo-metropolitan-gov/covid19#6021]
## 改善詳細 / Details of Improvement
- #5982 で、`MonitoringCommentCard.vue`内で元々明示的に`import`されていて、現在も使用されているcomponent(AppLink)の`import`が外されてしまいました。現状、このプロジェクトではcomponentsのオートインポートが適用されているおかげで何の支障もなく動作していますが、一部IDEでは警告表示が出ますし、あくまで私の主観かもしれませんが、可読性に欠けるとも思います。
- LazyComponentsに関しては仕方がないと思いますが、せめて普通に動作しているcomponentsだけでも統一して明示的にインポートすべきではないかなと考えます。
- また、先ほど挙げたPRで、`import`手法が相対パスであり、こちらもプロジェクト最上層からの絶対パスに統一すべきと考えます
- 今回の提案はリファクタであり、機能追加等の提案ではないので、優先順位は低めです。

**Comment by kaizumaki** [comment]
@y-chan ご提案ありがとうございます！AppLinkが使用されているにも関わらずimportが削除されているのは、私のチェックミスでした。
こちらのリファクタのPRを出していただくことはできますか？

**Comment by y-chan** [comment]
OKです、後で出しておきます！

**Comment by munierujp** [comment]
相対パスによるインポートについては、ESLintで警告を出すようにできそうですね。

- [TypeScirptのプロジェクトにエイリアスを設定して絶対パスでimportするメモ · nametake.info](https://nametake.github.io/posts/2019/10/07/typescript-absolute-imports/)
- [ESLintで特定のimportを禁止する | blog.mahoroi.com](https://blog.mahoroi.com/posts/2019/03/eslint-no-restricted-import/)

**Comment by kaizumaki** [comment]
@munierujp フォローありがとうございます！たしかに、eslint通すのはよさそうですね。
