### ISSUE TITLE
キャッシュ問題（ローディングで止まってしまう）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6023]
## 起こっている問題 / The Problem
- 最近、ローディング画面で読み込みが止まってしまう現象がよく起こります。
- Chromeでコンソールを見たところ、おそらくNetlifyのキャッシュかService Workerのキャッシュかと思われます。
- 運営側で探っていますが、まだはっきりと原因をつかめていないので、観察を続行します。

## スクリーンショット / Screenshot

![スクリーンショット 2021-02-22 18 44 27](https://user-images.githubusercontent.com/14883063/108826268-7255b400-7607-11eb-9168-7dab9cce955a.png)

## 期待する見せ方・挙動 / Expected Behavior
- ローディングで止まることがなくなる

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページをリロード

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MasaGon** [comment]
NetlifyからのResponseヘッダーは下記の通りなので、ブラウザーキャッシュは持たないはずではないかと思っています。
```
cache-control: public, max-age=0, must-revalidate
```

そうすると、Service worker cache かCDNのキャッシュか、あるいは注記に記載されている memory cache かというあたりだと思います。ちなみに、Chrome以外で目撃された方はいらっしゃいますか？

(参考)
https://web.dev/service-worker-caching-and-http-caching/

**Comment by mcdmaster** [comment]
よく、何かバグっているときに `vue-spinner` 画面で止まってしまうアレ（何）と関係はありますか？

**Comment by kaizumaki** [comment]
@mcdmaster ここでは本番環境のことを指していますが、ローディングで止まるのはだいたいキャッシュ問題だと思います。古いjsを読もうとしてしまうという現象ですね。

**Comment by kaizumaki** [comment]
どうやらService Workerが影響しているようですね。

![スクリーンショット 2021-03-07 17 41 07](https://user-images.githubusercontent.com/14883063/110234472-07449f80-7f6e-11eb-8222-16160122ceb0.png)

なにか設定を追加＆調整する必要がありそうです。
[参考](https://qiita.com/gyarasu/items/b5c34b6aac02cb325b79)

**Comment by suzuryo** [comment]
岩手版の場合は、いろいろ試してみましたが結局、PWAをやめました

https://github.com/MeditationDuck/covid19/issues/1112

**Comment by mcdmaster** [comment]
こういうのもあります。`@nuxtjs/pwa` と併用するようです。
https://github.com/nuxt-community/onesignal-module#change-onesignal-sdk-script-url

OneSignal という、高速大容量のプッシュデータ（株価とか為替データが想定でしょうか）を扱うための SDK の一部を CDN として使うアプローチだそうです。
試してみる余地はありそうです。ご興味はありますか？

**Comment by kaizumaki** [comment]
@suzuryo @mcdmaster 情報ありがとうございます 🙏 
CDNまではやらなくていいかなあという感じですね。やっぱりService Workerをやめる方向が妥当なような気がします。

**Comment by mcdmaster** [comment]
ドラフト PR を作ってみました。

どなたか、ScaleLoader で待たされる画面を再現していただくのは可能でしょうか？

**Comment by suzuryo** [comment]
@kaizumaki @mcdmaster 

あと同様の問題として「スマホでサイトのショートカットをホーム画面に追加`Add to Home Screen`している場合」についても調査が必要かもです。

サイトをホーム画面に追加してアイコン化したものを起動すると、いわゆるWebサイトをネイティブアプリのように扱える（アドレスバーが非表示になり画面いっぱいにコンテンツが表示される）などの本来の？PWA機能がモバイルブラウザにあります。

当issueの「ローディングが止まってしまう」症状が「スマホのホーム画面に追加したPWA」で発生する場合、
- Androidの場合は、Pull to refreshがMobile Chromeに実装されているので、画面を下に引っ張ることを知っていればリロードできて回避できる
- iPhoneの場合は、Pull to refreshがMobile Safariに実装されておらず、アドレスバーも非表示になっているのでリロードボタンも表示されていないので詰む

という症状が、一般ユーザーに発生している可能性があります。


スマホではなく、PCのChromeにはサイトをアプリ化して「インストール」という「スマホのホームスクリーンにPWAを追加」と同様の仕組みがあります。
macOSの場合は `/Users/username/Applications/Chrome Apps/東京都 新型コロナウイルス感染症対策サイト.app` という形でアプリ化されます。

このデスクトップ版Chromeでの app化 の場合も、当issueの問題が発生すると、ServiceWorkerが効いていると、一般ユーザーは回避できないかもしれません。


まとめると、

1. PC で ブラウザを普通に使っている
2. スマホ で ブラウザを普通に使っている
3. iPhone の Mobile Safari をホーム画面に追加してアプリ化
4. Android の Chrome をホーム画面に追加してアプリ化
5. PC の Chromeで サイトをアプリ化

のパターンについて、当issueがどのように影響しているか検証が必要かもです。

**Comment by kaizumaki** [comment]
@suzuryo 情報ありがとうございます！#6134 をマージしたのでこちらのissueが自動的にクローズされましたが、引き続き観察していこうと思います。

**Comment by suzuryo** [comment]
@kaizumaki @mcdmaster 
このプルリクのマージで
https://stopcovid19.metro.tokyo.lg.jp/sw.js
が生成されなくなりました。これは良くない状態です。

- 初めてアクセスしてきた人は問題ありません
- ブラウザのキャッシュを削除した人、Shift押しながらリロードボタン(またはCmd + Shift + R)でスーパーリロードを知って出来る人は回避できます

ですが、普通の検索結果やブックマークから `https://stopcovid19.metro.tokyo.lg.jp/` に2回目以降にアクセスしてきた人(ServiceWorker登録済の人)は sw.js が ServiceWorker としてブラウザに登録されたままになっています。けどこのPRでsw.jsが404になっている

登録済のServiceWorker が /_nuxt/[chunk].js の読み込みを制御しているので

<img width="1274" alt="Screen Shot 2021-03-30 at 5 04 48 PM (3)" src="https://user-images.githubusercontent.com/242669/112955410-5bf8c600-917a-11eb-91c6-603f0bc4b91b.png">

のように、必要な .js が読み込まれずグラフが表示されていない人たちが多くいる可能性があります
