### ISSUE TITLE
Feature: FROM nuxt-ts TO nuxt EX. nuxt generate

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#6026]
## 改善詳細 / Details of Improvement
- #6024 をボンヤリと見ていて思いました。これ、`package.json` に書いてある `nuxt-ts` を動かすためのものですよね？
- そろそろ、`nuxt-ts` じゃなく `nuxt` でいけるんじゃないかと思っています。確認します
- そうすると、`@nuxt/typescript-runtime` は不要になる、モジュール更新モニタリングの手間も少し減る、というのが期待値になります

## スクリーンショット / Screenshot

N/A

## 期待する見せ方・挙動 / Expected behavior
- `package.json` ファイル中の `nuxt-ts` の、`nuxt` への置換
- これに伴う、同ファイル `Dependencies` ブロックからの `@nuxt/typrscript-runtime` のエントリ削除
- 結果として更新監視対象モジュール数が減るので、維持管理の容易さが増すという想定

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster なるほどですね。 #6008 をマージしてnuxtをアップデートすればいけそうですね。

こちらは別プロジェクトのものですが、参考まで。
<img width="786" alt="スクリーンショット 2021-02-26 8 32 42" src="https://user-images.githubusercontent.com/14883063/109233485-515eb000-780d-11eb-954e-eb56b7dc0726.png">

**Comment by mcdmaster** [comment]
@kaizumaki はい、そのスクショ、私も同じものを撮った記憶があります(笑)

それはさておき、`Nuxt.js 2.15.x` からは、留意しなけれならない変更があると本家の relnote に示されていますね。
https://nuxtjs.org/docs/release-notes

特にインパクトがありそうなのは、`Nodejs@^12.0.0` に制限されるといったあたりでしょうか。
ただ、私としては `yarn install --ignore-engines` でどんなリスクがあるかを見てみたい気はしますｗ

**Comment by MaySoMusician** [comment]
> 特にインパクトがありそうなのは、`Nodejs@^12.0.0` に制限されるといったあたりでしょうか。

Node.js の v10 が来月末にはサポート終了なので、どこかのタイミングで v12 にバージョンアップする必要がありますね

**Comment by kaizumaki** [comment]
こちらのissueは運営で引き取らせてください。nodeのバージョンアップとともに対応しましょう。

**Comment by mcdmaster** [comment]
@kaizumaki はい。お言葉に甘えつつ、お譲りいたします。
お手数とは存じますけれども、宜しくお願いいたします

**Comment by munierujp** [comment]
@MaySoMusician 

>Node.js の v10 が来月末にはサポート終了なので、どこかのタイミングで v12 にバージョンアップする必要がありますね

@kaizumaki 

>こちらのissueは運営で引き取らせてください。nodeのバージョンアップとともに対応しましょう。

Node.jsのバージョンアップについてのイシューを立てました（ #6048 ）。
