### ISSUE TITLE
（スマホやタブレットでの閲覧時）メニュー表示について

### ISSUE THREAD

**Issue by ayamurata093** [tokyo-metropolitan-gov/covid19#603]
## 改善詳細 / Improve details
* xxxx(できるだけ簡潔に/as concise as possible)

PC以外の一番アクセスが多いであろうスマホやタブレットで閲覧時に最初に確認するであろう『都民の皆様へ』や『お子さんをお持ちの皆様へ』の項目をメニューの中だけではなく、表に持ってきた方がわかりやすいと思います

## スクリーンショット / Screenshot

<img width="346" alt="スクリーンショット 2020-03-06 14 28 26" src="https://user-images.githubusercontent.com/33918307/76055561-5486dd80-5fb7-11ea-8fbe-e529283646a7.png">

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
*
macbookpro

**Comment by DJYoko** [comment]
エンドユーザーの要望として、２回目以降の閲覧では「お知らせ」を優先的に情報収集したいと想定すると、
以下の位置に掲載するのが妥当ではないでしょうか
<img width="207" alt="cc521478832d75c7a037eb05ae709ae1" src="https://user-images.githubusercontent.com/47216665/76102613-96de0800-6013-11ea-8f0f-60826e6106a8.png">
ファーストビューには入りきると思います

**Comment by DJYoko** [comment]
こちら上記内容でやるのであれば僕が対応可能です。

**Comment by DJYoko** [comment]
アサインの処理がよくわからないのですが。。

**Comment by kaizumaki** [comment]
@ayamurata093 ご提案ありがとうございます。お待たせして申し訳ありません。
こちらのissueについて都と検討いたしました。サイドナビゲーションはグローバルメニューとしての役割をしていますので、現行のままでいきたいと考えています。
ただ、モバイル版においてサブページへのアクセスを誘導したいという考えも確かにあります。それについては、デザイン含め、こちらのissueとは別途検討したいと思います。

**Comment by kaizumaki** [comment]
都からの回答がありましたので、こちらのissueはクローズしたいと思います。
