### ISSUE TITLE
サイドナビにワクチンページへの外部リンクを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6036]
サイドナビに以下の項目の追加をお願いします。

リンク文言：`新型コロナウイルスワクチンの接種について`
URL：https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronavaccine.html
位置：「新型コロナウイルス感染症自宅療養者向けハンドブック」と「都民利用施設・都主催イベントに関する情報」の間

![スクリーンショット 2021-02-26 21 13 26](https://user-images.githubusercontent.com/14883063/109298974-b64ef000-7877-11eb-9944-24ce20db8e21.png)

**Comment by Murayu0225** [comment]
やります。
