### ISSUE TITLE
スマートフォン版「相談結果」ページの画面遷移の差異が分かりづらい

### ISSUE THREAD

**Issue by k2font** [tokyo-metropolitan-gov/covid19#604]
## 改善詳細 / Improve details
* 「新型コロナウイルス感染症が心配なときに」ページの下部「新型コロナ受診相談窓口による相談結果」欄において、「陰性」を押したときと「陽性」を押したときの差異が分かりづらいと感じた。

陽性を押した場合、上部の「自宅で安静に過ごす」等を指すのか、「入院となります」を指すのか理解することが難しい。

## スクリーンショット / Screenshot
* 「陰性」を押した場合
<img src="https://user-images.githubusercontent.com/6561417/76055917-5d2be380-5fb8-11ea-950a-130267464591.PNG" width="320px">

* 「陽性」を押した場合
<img src="https://user-images.githubusercontent.com/6561417/76055937-6ddc5980-5fb8-11ea-8f7b-41d0266fbb01.PNG" width="320px">

特に「陽性」をタップした場合、一体どちらを指しているか分かりづらい

## 期待する見せ方・挙動 / Expected behavior
* 「受診が不要」ブロックと「入院となります」ブロックの距離が近いように思える。単純に距離を空けることが望ましいと考える。
* もしくは、各ブロックに直接「陰性の場合」「陽性の場合」と記載する。

## 動作環境・ブラウザ / Environment
* iPhone 11 Pro
* Google Chrome

**Comment by mikkame** [comment]
ご提案ありがとうございます！
実装に関しましては一度 #576 をご確認いただきたいです

**Comment by ANNotunzdY** [comment]
アンカーリンクで遷移した際、該当コンポーネントに太枠等を付与するのはいかがでしょうか。

**Comment by k2font** [comment]
いいですね。大規模にコードを修正せずとも実装できそうですね。

**Comment by kaizumaki** [comment]
一度、デザイン担当の @forestgtree に確認させてください！

**Comment by ocean3fish** [comment]
フローのページは #659 にある通りコード化されたので、本件は一旦クローズさせて頂きますね。

**Comment by kaizumaki** [comment]
現在こちらのページは画像レイアウトからコードに置き換わりましたので、あらためて現在のサイトをご確認いただき、気になるようでしたら新たにissueを立てていただけますでしょうか。

**Comment by k2font** [comment]
ありがとうございます！
