### ISSUE TITLE
対策サイトで言語を変えた時に日本語のままの場所がある

### ISSUE THREAD

**Issue by rihitosan** [tokyo-metropolitan-gov/covid19#6040]
## 改善詳細 / Details of Improvement
「感染状況・医療提供体制の分析の場所」の下の文が翻訳されていない。

## スクリーンショット / Screenshot

日本語
![3](https://user-images.githubusercontent.com/76610702/109383425-c6270c80-7929-11eb-86ea-0d9b203f8722.png)

English
![1](https://user-images.githubusercontent.com/76610702/109383379-86602500-7929-11eb-9969-d2abf77da05c.png)

やさしいにほんご
![2](https://user-images.githubusercontent.com/76610702/109383385-8d873300-7929-11eb-8653-903b3aeaf439.png)

## 期待する見せ方・挙動 / Expected behavior
翻訳されていない場所を翻訳する。

## 動作環境・ブラウザ / Environment
windows
chrome

**Comment by kaizumaki** [comment]
@rihitosan ご指摘ありがとうございます！そこの部分は週次で変わるので（昨日リリースしたばかりでして）、翻訳をどうするかは検討しますね。
