### ISSUE TITLE
Node.jsをv12またはv14にアップデートする

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#6048]
## 改善詳細 / Details of Improvement
- 現在このプロジェクトで使用しているNode.js v10は、2021/4/30にサポートが終了する[^1]
- それまでに次のLTSバージョンであるv12またはv14にアップデートすべき

[![](https://user-images.githubusercontent.com/20086673/109482011-d58c8e00-7ac0-11eb-954c-ada464b2e401.png)](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true)

## やること / To do

- このプロジェクトで使用しているライブラリやツールがどのNode.jsバージョンをサポートしているのか調べる
- メジャーアップデートによるこのプロジェクトへの影響を調べる
	-	[The Difference Between Node.js 10 LTS and Node.js 12 LTS | Node.js](https://nodejs.org/tr/blog/uncategorized/10-lts-to-12-lts/)
- 更新すべきファイルを調べる
- 今後マイナーバージョンやパッチバージョンのアップデートに追従していくために、Node.jsのバージョンをアップデートする方法のドキュメントをつくる（Wikiでもいいかも）

[^1]: https://nodejs.org/ja/about/releases/

**Comment by kaizumaki** [comment]
@munierujp issueありがとうございます！運営側でやろうと思っていましたが、お願いしてもいいでしょうか？

**Comment by munierujp** [comment]
@kaizumaki おおむね問題ないのですが、メジャーアップデートによるこのプロジェクトへの影響について、よりこのプロジェクトについて理解度の高い方の助力が必要と思われます。
一般的なプロジェクトであればユニットテストテストによって動作が担保された状態でアップデートをするかと思いますが、このプロジェクトの場合はどうなんでしょう？
少なくともJS/TSのユニットテストはないものと理解していますが、 #5961 でUIテストが実装されたことでそこはクリアされているものとしていいのでしょうか？

**Comment by kaizumaki** [comment]
@munierujp もちろん、私もみなさんの御助言をいただきながら進めていこうと思っていました。
#5961 のUIテストの導入目的の一つとして、ライブラリアップデートを円滑に進める、というのがありましたので、nodeのアップデートについても同様に考えています。
たしかに、ユニットテストはないですが、今のところはカバーできるだろうと思っています。

**Comment by mcdmaster** [comment]
私の `vue@3` チャレンジ #5667 も合流させていただきたくオナシャス(＞＜;)

`vue@3` に実際に移行するかどうかについては、私が上記 PR でいろいろ試したこと、あるいは `Vue` のロードマップ
https://github.com/vuejs/vue/projects/6#card-16117796
と併せて見ても、拙速に移行するよりも次に登場するはずの `vue@2.7` を待つのが良い、という観測を私はしています。
実際にやってみたら…というところの outcome ではあるのですけれども、当初の想定からはメジャーバージョンに限って言えば退縮しています。
また、`Vuetify` が `vue@3` 対応に実に消極的という現状は、なかなか手ごわい制約事項になっています。

また、何よりも公共サイト構築に高いシステムリスク選好度を求めるのも違和感ありまくりですよね

**Comment by munierujp** [comment]
@mcdmaster 

>また、Vuetify が vue@3 対応に実に消極的という現状は、なかなか手ごわい制約事項になっています。

このプロジェクトではVuetifyのコンポーネントにそこまで依存していないように見受けられるので、いざとなれば脱Vuetifyするのも手だと思います（他のUIフレームワークの状況は存じ上げませんが）。

**Comment by mcdmaster** [comment]
> いざとなれば脱Vuetify

為念、[Vuetify 3 - Titan](https://github.com/orgs/vuetifyjs/projects/7) というプロジェクトが「いちおう」走っていることは共有しておかねばなりません。
さらに言うと、たとえば `Vuetify` とは大なり小なり関係がある `vue-router` なども、`vue@3` 対応を「いちおう」謳っている `vue-router@4` のソースの中で `Vue.use()` メソッドという、`vue@3` では廃止（禁止）されるモノをなぜか見つけたりしていちいちゲンナリできます。

開発者の皆さんをそんなストレスフルな目に遭わせるのを避けつつも、`nuxt/vue/vuetify` からの開発スタイルの継続性を維持する、なおかつ既存ノウハウを用いればナレッジ・トランスファの面倒さを軽減できるという期待も込め、`vue@2.x` に留まるのを支持するのが今の私の立ち位置です。あくまで個人の意見ですのでｗ

**Comment by kaizumaki** [comment]
@mcdmaster さんがいろいろ調査してくださって助かっています。わたしもvue@3はまだまだ早いと思っています。

**Comment by suzuryo** [comment]
岩手版は 14.16.0 で運用していますが、問題なさそうです
https://github.com/MeditationDuck/covid19/pull/1344/files
https://github.com/MeditationDuck/covid19/pull/1363/files

**Comment by munierujp** [comment]
@suzuryo 貴重な情報ありがとうございます :bow:

**Comment by munierujp** [comment]
>更新すべきファイルを調べる

ファイル中にフルバージョンを記載しているものについては、`10.23.2`で検索すればいいですね。

<img width="607" alt="スクリーンショット 2021-03-08 19 20 21" src="https://user-images.githubusercontent.com/20086673/110308434-70e2ad80-8043-11eb-8057-8a13b84cf3ae.png">

もし`v10`のようにメジャーバージョンのみを指定しているような箇所があったら漏れてしまいますが、`10[\n'"]`で検索してもそれらしきものはないので、問題なさそうです。

**Comment by munierujp** [comment]
>今後マイナーバージョンやパッチバージョンのアップデートに追従していくために、Node.jsのバージョンをアップデートする方法のドキュメントをつくる（Wikiでもいいかも）

このプロジェクトではWikiは使われていないようなので、ひとまず[FOR_DEVELOPERS.md](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FOR_DEVELOPERS.md)あたりに書くのがよさそうです。

**Comment by munierujp** [comment]
というわけで、ひとまずv14にアップデートするプルリクエストをつくり、そのときの手法で問題がないようであれば、アップデート方法についてのドキュメントを追加するプルリクエストをつくろうと思います。
