### ISSUE TITLE
翻訳が正しく動作しない箇所がある

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#6050]
## 起こっている問題 / The Problem
「自分や家族の症状に不安や心配があればまずは電話相談をどうぞ」の文言について，Transifex の辞書 JSON ファイルのキーを指定する箇所で`"自分や家族の症状に不安や心配があれば\nまずは電話相談をどうぞ"`という，改行が含まれる文字列が与えられているが，日本語以外の Transifex の辞書 JSON ファイルには `"自分や家族の症状に不安や心配があればまずは電話相談をどうぞ"`（改行なし）に対応する文字列が定義されているため，翻訳が正しく動作していない．

（開発環境では，改行が含まれるせいで CLI にエラーが表示される）

また，Transifex の日本語辞書には

* `"自分や家族の症状に不安や心配があればまずは電話相談をどうぞ"`（改行なし）
* `"自分や家族の症状に不安や心配があれば\nまずは電話相談をどうぞ"`（改行あり）

の2つについて対応する文字列が指定されており，不自然である．

## スクリーンショット / Screenshot
![スクリーンショット 2021-03-01 21 59 18](https://user-images.githubusercontent.com/23148331/109500394-8ef75d80-7ad9-11eb-938e-fecd973fd85d.png)

## 期待する見せ方・挙動 / Expected Behavior
- 該当する箇所で，日本語以外でも正しい表示がなされること

## 起こっている問題の再現手段 / Steps to Reproduce
- 言語設定を日本語以外の言語に切り替える

## 動作環境・ブラウザ / Environment
- macOS, Chrome

## その他
- 以下のように対応するのがよいと思うが，Transifex では日本語辞書を編集できないため，よい方法を考えたい．
  - 辞書定義のキーおよびキーを指定する箇所では改行なしの文字列とする．
  - 日本語辞書でキーに対応する値は改行ありの文字列とする．

**Comment by kaizumaki** [comment]
こちらの改行は意図的に行ったものですが（翻訳的にはよくない状態だとわかった上で）、現在transifexでの作業が進んでいないので翻訳関係は他にももろもろ不備が起こっています。
改行については、なにかいい案があればご提案いただけるとうれしいです。

**Comment by PichuChen** [comment]
I have translated it form `若您或家人出現疑似症狀，請即刻撥打電話諮詢` to `若您或家人出現疑似症狀，\n請即刻撥打電話諮詢`

**Comment by kaizumaki** [comment]
@PichuChen Thank you for the translation work and supporting line breaks!

**Comment by y-chan** [comment]
> また，Transifex の日本語辞書には
>
> - "自分や家族の症状に不安や心配があればまずは電話相談をどうぞ"（改行なし）
> - "自分や家族の症状に不安や心配があれば\nまずは電話相談をどうぞ"（改行あり）
>
> の2つについて対応する文字列が指定されており，不自然である．

これに関して、以前`auto-i18n`上で使われなくなったキーを削除しないようにしたことが原因ですが、確か理由が微妙なニュアンスの変更時などにも翻訳を引き継げるように、Transifexの文字列の一致率による翻訳の提案を使いたいから、のようだったと思います。ですがTransifexでは、1度翻訳された単語や文章は履歴として登録されるはずで、jsonのキーを消しても翻訳の提案は働くはずなので、未使用のキーの削除は復活させてもいいように思います。

**Comment by kaizumaki** [comment]
@y-chan なるほどですね。実際Transifexで作業している方がやりやすいようにするのがよいかと思っています。東京都の方もTransifex編集作業をするようになったので、未使用のキーについて削除していいか確認してみます。

**Comment by kaizumaki** [comment]
こちらの件、現在翻訳については東京都側のタスクとして運用していますので、当リポジトリの対応範囲外としたく、issueはクローズとさせてください。
