### ISSUE TITLE
「緊急事態宣言中の都内の滞在人口の増減状況」の地名の縦書き表記について

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#6054]
## 改善詳細 / Details of Improvement
- 「緊急事態宣言中の都内の滞在人口の増減状況」では英語も含め地名が縦書き表記されているが，地名の文字数によってその外の枠で囲まれた領域の高さが変化してしまい，隣の「自分や家族の症状に不安や心配があればまずは電話相談をどうぞ」の領域とのデザインのバランスが変化してしまう．

### 銀座
<img width="1098" alt="スクリーンショット 2021-03-02 19 41 12" src="https://user-images.githubusercontent.com/23148331/109636836-692c9000-7b8f-11eb-92c5-8448d2cfa667.png">

### 歌舞伎町
<img width="1103" alt="スクリーンショット 2021-03-02 19 41 56" src="https://user-images.githubusercontent.com/23148331/109636857-6cc01700-7b8f-11eb-83d1-8c9af32a37de.png">

### Ginza
<img width="1098" alt="スクリーンショット 2021-03-02 19 41 22" src="https://user-images.githubusercontent.com/23148331/109636877-70539e00-7b8f-11eb-853b-4a16e5053038.png">

### Kabukicho
<img width="1100" alt="スクリーンショット 2021-03-02 19 42 05" src="https://user-images.githubusercontent.com/23148331/109636888-721d6180-7b8f-11eb-8ab7-7f53a5ae1058.png">

## 期待する見せ方・挙動 / Expected behavior
- 地名を横書きにし，文字数によってスタイルが変化しないようにする

## 動作環境・ブラウザ / Environment
- macOS, Chrome

**Comment by nard-tech** [comment]
とりあえず，改善案を作ってみたいと思います．

**Comment by kaizumaki** [comment]
PRのほうにコメントいたしました。 https://github.com/tokyo-metropolitan-gov/covid19/pull/6100#issuecomment-804830633
ファーストビューが全面的に見直されるみたいなので、こちらは一旦クローズにさせていただければと思います。

**Comment by nard-tech** [comment]
@kaizumaki 承知しました．ありがとうございます．
