### ISSUE TITLE
期待しないthisエイリアスの使用

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#6068]
## 改善詳細 / Details of Improvement
- 意味のないthisの代入が行われています。
https://github.com/tokyo-metropolitan-gov/covid19/blob/7e62608af26d7023b899ab11a7e2bf9b131199c9/components/StayingPopulation.vue#L51-L60
SonarQubeによって指摘されています。

実装者にこう実装した意図を確認したいです。

## 期待する見せ方・挙動 / Expected behavior
- 51行目は不要、57行目のselfはthisで問題ないはず。

## 動作環境・ブラウザ / Environment
- 特に指定しません

**Comment by kaizumaki** [comment]
@goki90210 ご指摘ありがとうございます！たしかにarrow function内なので、thisでよさそうです。

**Comment by nard-tech** [comment]
@goki90210 @kaizumaki こちら対応しました．
