### ISSUE TITLE
「都内の最新感染動向」の情報のカテゴリ分け

### ISSUE THREAD

**Issue by task-jp** [tokyo-metropolitan-gov/covid19#608]
## 改善詳細 / Improve details
- 現在「検査陽性者の状況」や「陽性患者数」など、フラットに（ランダムに？）並んでいる情報を分かりやすく整理したい

## 期待する見せ方・挙動 / Expected behavior
以下のように実際のプロセスの流れに沿ってカテゴリ化し、そこに属する情報が表示されていると分かりやすい
- 相談に関する情報
- 検査に関する情報
- 陽性患者
- その他（地下鉄など）

**Comment by mira-tech** [comment]
https://xd.adobe.com/view/055ec402-6a23-49bb-55aa-0635cf3988fb-736f/

軽くUIだけ作ってみたのですがどうでしょうか？
　・値が関連している(例:相談窓口相談件数(コールセンター)と相談窓口相談件数(窓口))と円がくっついています
　・上から下にかけてがプロセスの流れ(間違ってるかも)

<img width="307" alt="スクリーンショット 2020-03-14 12 52 14" src="https://user-images.githubusercontent.com/30523995/76674415-aac8d180-65f2-11ea-8aa7-d1be8f24893e.png">

**Comment by task-jp** [comment]
ありがとうございます！！

相談をした人は数万人でした
↓
検査をした人は数千人でした
↓
陽性の人は数十人でした
（陽性の内訳は〜）

のような感じで、流れとともに人数のオーダー感が掴みやすいように可視化できると分かりやすいと思います。

**Comment by mira-tech** [comment]
あーなんか勘違いしてました...一から作り直したのですがどうでしょうか？

https://xd.adobe.com/view/055ec402-6a23-49bb-55aa-0635cf3988fb-736f/
<img width="449" alt="スクリーンショット 2020-03-14 21 13 11" src="https://user-images.githubusercontent.com/30523995/76681654-a7f0cf80-6638-11ea-8e95-9a728b306dcb.png">

**Comment by task-jp** [comment]
おぉ、すごい。

重要な部分の情報の階層構造と、周辺の情報が一目で分かるレベルできれいに可視化されていて、とても分かりやすいです。

**Comment by mira-tech** [comment]
僕が実装したいのですが...
これはどこから始めたら良いのですかね...ご教授願います
  ・ファーストビュー全更新となると...今あるIssueとかプルリクとか全部消えるし...
  ・タブを追加するにも僕の力だけだと大きく時間がかかる...

**Comment by kaizumaki** [comment]
お申し出ありがとうございます！こちら、 `waiting` ラベルがついています。関係各所の確認が必要ですので、しばらくお待ちください。

**Comment by halsk** [comment]
すみません。後ほど `CONTRIBUTING.md` の方でも詳しく書きますが、

`waiting` ラベルがついた Issue は関係者の確認中ですので、内容が固まるまで実装するのは避けていただく方が無難です。

また、言葉の変更やコンテンツの追加、新規グラフの追加、デザインの変更などは取り入れられる可能性は低いこと、ご了承ください。

**Comment by kaizumaki** [comment]
@task-jp @mira-tech ご提案ありがとうございます。こちらのissueについて都に確認いたしました。グラフ・表のレイアウトにつきましては、現時点で東京都として想定している関心度の高い順序に並べ替えを行っております。こちらの提案の採用は見込めない状況です。ご理解いただきますようお願いいたします。

**Comment by kaizumaki** [comment]
都からの回答がありましたので、こちらのissueはクローズさせていただきます。
