### ISSUE TITLE
MonitoringCommentCardImageSwipe.vue のデリミタの視認性が低い

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#6083]
## 改善詳細 / Details of Improvement

- #5964 で [MonitoringCommentCardImageSwipe.vue](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/MonitoringCommentCardImageSwipe.vue) が実装された
  - [v-carousel](https://vuetifyjs.com/en/components/carousels/) コンポーネントでいくつかの画像をカルーセル表示している
  - デリミタの背景が非表示に設定されているため、デリミタが画像の背景と同化してしまって見づらい

## スクリーンショット / Screenshot

<img width="547" alt="スクリーンショット 2021-03-10 19 11 00" src="https://user-images.githubusercontent.com/20086673/110613235-61df3500-81d4-11eb-9ff5-2e9df47aa24c.png">

一見分かりづらいですが、ページの要素を全選択などすると、デリミタ自体は存在することがわかります。

<img width="547" alt="スクリーンショット 2021-03-10 19 20 49" src="https://user-images.githubusercontent.com/20086673/110614507-c0f17980-81d5-11eb-8af0-93fc3ee5d731.png">

## 期待する見せ方・挙動 / Expected behavior

デリミタを見やすくする。

- デリミタの背景を表示した場合の例：

<img width="547" alt="スクリーンショット 2021-03-10 19 28 02" src="https://user-images.githubusercontent.com/20086673/110615444-c8fde900-81d6-11eb-8137-86906444d10e.png">

- デリミタの背景を表示したうえで画像自体に被らないようにした場合の例：

<img width="547" alt="スクリーンショット 2021-03-10 19 30 06" src="https://user-images.githubusercontent.com/20086673/110615849-3447bb00-81d7-11eb-91a5-367506b03c66.png">

**Comment by munierujp** [comment]
@kaizumaki 画像の総数と現在位置を示すために下部に表示される丸いアイコンのことです。
[Vuetifyのドキュメント](https://vuetifyjs.com/en/components/carousels/)でdelimitersと呼ばれているものです。

<img width="786" alt="スクリーンショット 2021-03-11 19 17 26" src="https://user-images.githubusercontent.com/20086673/110772111-991a1880-829e-11eb-861a-5919628d5f66.png">

**Comment by kaizumaki** [comment]
@munierujp おお、なるほどです。
> デリミタの背景を表示したうえで画像自体に被らないようにした場合の例：

こちらのご提案のように、画像自体に被らない方向で修正できるとよいかなと思います。

**Comment by kaizumaki** [comment]
サイトリニューアルにより、カルーセルはなくなりました。よってこちらのissueはクローズにさせてください 🙏  ご提案ありがとうございました。
