### ISSUE TITLE
kyoto.stopcovid19.jpの公式化に伴い、表記を変更

### ISSUE THREAD

**Issue by Genbuchan** [tokyo-metropolitan-gov/covid19#6092]
## 改善詳細 / Details of Improvement
- FORKED_SITES.mdのkyoto.stopcovid19.jpの運営体制が京都府の公式になったため、「京都府（**公式**）」に変更する

## 期待する見せ方・挙動 / Expected behavior
- 有志 → 京都府（**公式**）

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
#6093 をマージしましたので、こちらのissueはクローズしますね。
