### ISSUE TITLE
FORKED_SITES.mdの秋田県のサイトのプロジェクトについて

### ISSUE THREAD

**Issue by momizi06** [tokyo-metropolitan-gov/covid19#6094]
## 改善詳細 / Details of Improvement
- FORKED_SITES.mdで秋田県のサイトが学生の有志の方のプロジェクト(現時点で記載されているもの)からCodeForAkitaの方の[プロジェクト](https://github.com/code4akita/covid19-akita)に引き継がれたとのことです。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/63577263/110906933-29655700-82b9-11eb-909b-371026bc3f1a.png)

## 期待する見せ方・挙動 / Expected behavior
- 旧プロジェクトから新プロジェクトへURLの変更

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
こちら、秋田県のサイトの関係者からのご提案であれば受け付けたいと思います。

**Comment by nard-tech** [comment]
@momizi06 @kaizumaki https://github.com/code4akita/covid19-akita/issues/94 こちらに書き込んでおきました．

**Comment by dzonesasaki** [comment]
Code for Akitaのメンバです。 主力メンバが時間が全くとれないため、私が対応しております。
ただ、Githubの使い方。。。というか、このissuesの使い方など、判らずにおります。
具体的に何をすべきなのかを教えて頂けますか？

**Comment by kaizumaki** [comment]
@dzonesasaki フォローありがとうございます。 @dzonesasaki さんからFORKED_SITES.mdを修正したものをこちらのリポジトリにPRしてもらうとよいのですが、もし難しいようであれば、すでに @momizi06 さんのPR #6095 が出ていますので、そちらに修正依頼内容をコメントしていただくのでも大丈夫です。
