### ISSUE TITLE
不要になったJSONファイルの削除

### ISSUE THREAD

**Issue by tmatsuno** [tokyo-metropolitan-gov/covid19#6098]
## 改善詳細 / Details of Improvement
- 不要になったJSONファイル、/data/monitoring_comment_summary_temporary.json の削除

**Comment by nard-tech** [comment]
`data/monitoring_status.json` も不使用のようです。

**Comment by kaizumaki** [comment]
> `data/monitoring_status.json` も不使用のようです。

そうですね。そちらも削除でいいと思います。

**Comment by nard-tech** [comment]
@kaizumaki `data` ディレクトリのファイルは自動更新されるので触らないで欲しいとおっしゃっていた気がしますが、使用されていない2ファイルを削除する PR を作ってしまってもよろしいでしょうか？

**Comment by kaizumaki** [comment]
@nard-tech はい、これらのjsonは元データもまったく動いていないので、削除して大丈夫です。

**Comment by nard-tech** [comment]
@kaizumaki 承知しました。それでは後ほど私が対応します。
