### ISSUE TITLE
「企業の皆様・はたらく皆様へ」内容追加

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#610]
企業の皆様・はたらく皆様へ https://stopcovid19.metro.tokyo.lg.jp/worker に
下記の並びで、上から追加をお願いします。
----

新型コロナウイルス感染症対応緊急融資
https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/03/05/26.html
新型コロナウイルス感染症により事業活動に影響を受けている中小企業等を対象とした緊急融資制度です。

新型コロナウイルスによる経営課題に関する専門家派遣
https://www.tokyo-kosha.or.jp/topics/2003/0001.html
新型コロナウイルス感染症により経営面の影響を受けている中小企業を対象に、中小企業診断士等の専門家を無料で派遣し、経営改善等に向けたアドバイスを実施します。

事業継続緊急対策（テレワーク）助成金
https://www.shigotozaidan.or.jp/koyo-kankyo/
都内中堅・中小企業に対し、テレワークの導入に必要な機器やソフトウェア等の経費を助成します。

**Comment by NaoyaShimizzz** [comment]
すいません、既存コンテンツの上に追加をお願いします。
下記の並び順です。

中小企業者等特別相談窓口
https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/01/30/15.html
資金繰りに関する相談、経営に関する相談（東京都産業労働局　報道発表）

緊急労働相談ダイヤル
https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/02/26/22.html
新型コロナウイルスに関する休暇や休業の取り扱い、職場のハラスメントなどについての相談（東京都産業労働局　報道発表）

新しいワークスタイルや企業活動の東京モデル「スムーズビズ」
https://smooth-biz.metro.tokyo.lg.jp/
テレワーク・時差出勤などスムーズビズの取組は、新型コロナウイルス感染症の対策としても効果的です。感染症対策として、東京2020大会時の交通混雑緩和に向けた取組の前倒しをお願いします。

中小企業者等特別相談窓口
https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/01/30/15.html
資金繰りに関する相談、経営に関する相談（東京都産業労働局　報道発表）

緊急労働相談ダイヤル
https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/02/26/22.html
新型コロナウイルスに関する休暇や休業の取り扱い、職場のハラスメントなどについての相談（東京都産業労働局　報道発表）

新しいワークスタイルや企業活動の東京モデル「スムーズビズ」
https://smooth-biz.metro.tokyo.lg.jp/
テレワーク・時差出勤などスムーズビズの取組は、新型コロナウイルス感染症の対策としても効果的です。感染症対策として、東京2020大会時の交通混雑緩和に向けた取組の前倒しをお願いします。

**Comment by rozeo** [comment]
申し訳ないです、再PRさせていただきました、よろしくお願いしします
