### ISSUE TITLE
FORKED_SITES.mdに、福山市公式サイトを追加

### ISSUE THREAD

**Issue by nnaoko126** [tokyo-metropolitan-gov/covid19#6119]
## 改善詳細 / Details of Improvement
FORKED_SITES.mdに、福山市の公式サイトを新規追加する。

都道府県名：広島県福山市
公開サイト：https://usecase.data.city.fukuyama.hiroshima.jp/covid-19/
運営者：福山市（公式）

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nnaoko126** [comment]
後ほどPull Request致します。不慣れなため、何か不備等あればご指摘ください。

**Comment by kaizumaki** [comment]
#6120 をマージしましたので、こちらのissueはクローズします。
