### ISSUE TITLE
カルーセルをアクセシブルにしたい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6125]
## 改善詳細 / Details of Improvement
- ファーストビューのカルーセルについて、デリミタの改善提案 #6083 がありましたが、そもそも現在のカルーセルはアクセシビリティ的に検討の余地ありでは、と考えています。
- オートプレイしているので、停止再生ボタンが必要だというのが一番の課題です。
- カルーセルを（できる限り）アクセシブルにするべくデザインを再考します。

## スクリーンショット / Screenshot

![スクリーンショット 2021-03-20 13 45 58](https://user-images.githubusercontent.com/14883063/111859231-b2982000-8982-11eb-95ce-9da03c2312a2.png)

## 期待する見せ方・挙動 / Expected behavior
- カルーセルを（できる限り）アクセシブルにする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by magi1125** [comment]
アクセシビリティのプレ試験を行ったところ、以下のような課題が見つかりました。

- 画像のリンク先がすべて同じながら代替テキストが個別についている（リンクラベルが別なのにリンク先が一緒なので混乱する可能性がある）。同じa要素でくくって、かつ装飾とみなして代替テキストをカラにする等の対応が必要（達成基準1.1.1）
- カルーセルであることがマークアップで表現されていない。WAI-ARIA Authoring practiceを参考に実装が必要（達成基準1.3.1）
- 更新速度を調整できない、停止できない（達成基準2.2.1、2.2.2）
- インジケーターにフォーカスしたことがわからない、左右ボタンのフォーカス時の明度差が少ない（達成基準2.4.7）

これらを個別に調整してアクセシブルなカルーセルにするという方向もあり得るものの、けっこう作り直す必要がありそうです。
また、「更新速度を調整できない、停止できない」に対しては例えば停止ボタンを置くなどの改修が考えられますが、これはアクセシビリティとしては「ギリギリ達成基準を満たすなら、という妥協策」で、そもそもここが自動更新されることで視線を奪われて集中できない人にとっては停止ボタンを押すこと自体が困難な可能性があります。

また、このカルーセルはリンク先のグラフのいくつかをサムネイルイメージとして紹介しているものなので、停止ボタンなどを付けても、それぞれを個別に切り替えて見る理由が薄いものだと考えられます。

たとえばサムネイルをタイル状に並べるなど、同じ目的を満たす別のUIへの変更を検討できればと考えました。こちらをカルーセルUIにした当時の経緯など鑑みつつ、議論したいと考えます。

**Comment by kaizumaki** [comment]
@magi1125 フォローありがとうございます！以前から計画されていたファーストビューの大幅改修案が来月にもできるそうです。そこで、現在のカルーセルの改善も東京都に伝えようと思います。追記があればどしどしお寄せください！

**Comment by magi1125** [comment]
@kaizumaki コチラ何か動きあればお知らせください〜

**Comment by kaizumaki** [comment]
@magi1125 お待たせしています 🙏 
現状の問題点 https://github.com/tokyo-metropolitan-gov/covid19/issues/6125#issuecomment-856793142 は東京都に共有しています。来週か８月上旬にもファーストビューおよびサイトトップの大幅改修案ができるそうで、その時にこちらについても回答をもらう予定でいます。回答次第で、またディスカッションできればと！

**Comment by kaizumaki** [comment]
@magi1125 カルーセルの件、東京都から回答があり、「自動ループではなく、アクセスするたびに（正確にはF5を押すたびに）ランダムにタイルが変わる（アクセスしている間は同じタイルのまま）という対応はいかがでしょうか。」とのことでした。カルーセルはやめて、その方向で実装しなおそうかと思うのですがいかがでしょう？

**Comment by kaizumaki** [comment]
サイトリニューアルにより、カルーセルはなくなったのでこちらのissueはクローズします。
