### ISSUE TITLE
「緊急事態宣言中の都内の滞在人口の増減状況」の地名の中国語表記について

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#6128]
## 改善詳細 / Details of Improvement
- 「緊急事態宣言中の都内の滞在人口の増減状況」で表示する地名は，現在言語設定を日本語，やさしいにほんご以外にした場合はローマ字表記のもの（例：Shinjuku）を表示しているが，中国語（简体中文，繁體中文）については日本語のものを表示した方がよいと思われる．（理想としては簡体字，繁体字表記のものを Transifex に登録したい）

### Before
![スクリーンショット 2021-03-21 15 11 10](https://user-images.githubusercontent.com/23148331/111896032-17727980-8a5a-11eb-97a4-1f2fdd8cb561.png)

### After
![スクリーンショット 2021-03-21 15 11 26](https://user-images.githubusercontent.com/23148331/111896035-1b060080-8a5a-11eb-98b5-50658fc8d2d4.png)

## 期待する見せ方・挙動 / Expected behavior
- 「緊急事態宣言中の都内の滞在人口の増減状況」の地名は，言語設定を中国語（简体中文，繁體中文）にした場合は日本語のものを表示する．

**Comment by nard-tech** [comment]
PR を作ってみました．

**Comment by kaizumaki** [comment]
ご提案ありがとうございます！こちらは東京都に確認とりますね。
