### ISSUE TITLE
死亡日別による死亡者数の推移グラフ[新規実装]

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6137]
「死亡日別による死亡者数の推移」グラフが追加になります。スタイルは「確定日別による陽性者数の推移」グラフに準じます。

**3/30午前にはリリースする予定です。実装完了前にしばらく離れる場合はDraft Pull Requestを出しておいていただけると助かります。**

### カードのパーマリンク名
「検査陽性者の状況」カードからこちらの新規実装グラフカードにリンクを貼りますので（別issueで対応します）、以下をパーマリンク名としておいてください。
`deaths-by-death-date` 

### グラフ
- 単純棒グラフ
	- データ： `data/deaths.json` の `death_date` （日付） `count` （値）
	- 色： `#00a040` (surfaceStyleB)
	- `TimeBarChart.vue` の実装に準じます

### テーブル
ラベル名は以下です。
|日付|死亡日別による死亡者数の推移（日別）|死亡日別による死亡者数の推移（累計）|
|---|---|---|
|〇月〇日|〇〇|○○○|

### タイトル部分
※「確定日別による陽性者数の推移」グラフのスタイルに準じます

- 日別スイッチがONのとき
```
○○年○月○日 日別値（現在判明している人数であり、後日修正される場合がある）
```

- 累計スイッチがONのとき
```
○○年○月○日 累計値
```

### 注釈
グラフの下部に配置します。
```
（注）
　・各保健所から報告のあった死亡者について、死亡日別に整理したものである
```

### 配置
「その他参考指標」タブのグループの５番目（「確定日別による陽性者数の推移」と「検査実施件数」の間）に配置します。
さらに「新型コロナコールセンター相談件数」カードの後ろで区切ります。

![その他参考指標グラフカード順](https://user-images.githubusercontent.com/14883063/112398044-a2978c00-8d46-11eb-9e37-0189d32e8a90.png)

わからないことなどあったら、遠慮なくこちらのissueにコメントしてください！

**Comment by Murayu0225** [comment]
このIssue対応します。
質問なのですが、

> さらに「新型コロナコールセンター相談件数」カードの後ろで区切ります。

というのは、新型コロナコールセンター相談件数の隣は、カードを設置せずに空白の状態にすれば良いと言うことでしょうか。

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！

> 新型コロナコールセンター相談件数の隣は、カードを設置せずに空白の状態にすれば良いと言うことでしょうか。

はい、その通りです。
よろしくお願いします！ 🙇‍♀️

**Comment by Murayu0225** [comment]
@kaizumaki わかりました！PRを作成します！
