### ISSUE TITLE
感染状況・医療提供体制の分析のコメント部分は翻訳対象に含めなくていい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6138]
## 改善詳細 / Details of Improvement
- 感染状況・医療提供体制の分析のコメント部分はjsonから日本語と英語をあてているので、翻訳対象に含めなくていい。
- 現在、$tタグで囲まれているので、それを外す。

https://github.com/tokyo-metropolitan-gov/covid19/blob/2aa0eb1fd3ea3b8fc16f6c1879f2f8cac65c4a91/components/MonitoringCommentFrame.vue#L7

## スクリーンショット / Screenshot

![スクリーンショット 2021-03-25 13 58 58](https://user-images.githubusercontent.com/14883063/112421510-827dc200-8d72-11eb-9586-b686a05fc600.png)

## 期待する見せ方・挙動 / Expected behavior
- $tタグを外せば、 `yarn dev` した時にブラウザのコンソールから[vue-i18n]のワーニングが減るはず。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nard-tech** [comment]
@kaizumaki こちら対応します
