### ISSUE TITLE
開発者向け情報(FOR_DEVELOPERS.md)にページ内リンクを作成する

### ISSUE THREAD

**Issue by MochiMochiTosiki** [tokyo-metropolitan-gov/covid19#6139]
## 改善詳細 / Details of Improvement
- 「開発者向け情報(FOR_DEVELOPERS.md) 1.環境構築」にある各インストール情報で、ページ内リンクがあると親切だなと思いました。

## スクリーンショット / Screenshot
<img width="1243" alt="スクリーンショット 2021-03-25 16 22 58" src="https://user-images.githubusercontent.com/37738987/112434261-b531b580-8d86-11eb-9984-9eb078dff26d.png">

## 期待する見せ方・挙動 / Expected behavior
- yarnなら[2-1. yarn を使う場合](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FOR_DEVELOPERS.md#2-1-yarn-%E3%82%92%E4%BD%BF%E3%81%86%E5%A0%B4%E5%90%88), docker-compose なら [docker compose を使う場合
](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FOR_DEVELOPERS.md#2-2-docker-compose-%E3%82%92%E4%BD%BF%E3%81%86%E5%A0%B4%E5%90%88)、というように各環境へ飛ぶようにする。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@MochiMochiTosiki ご提案ありがとうございます！いいですね！こちらやってみましょうか。

**Comment by MochiMochiTosiki** [comment]
@kaizumaki ありがとうございます！ それではこちr

**Comment by MochiMochiTosiki** [comment]
@kaizumaki 一点質問なのですが、こちら[Visual Studio Code + Remote Containers](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FOR_DEVELOPERS.md#2-4-visual-studio-code--remote-containers%E3%81%A7%E9%96%8B%E7%99%BA%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88)と[Vagrant](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FOR_DEVELOPERS.md#2-5-gitpod%E3%81%A7%E9%96%8B%E7%99%BA%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88)が「1. 環境構築」に含まれていないため追加しようと思っています。こちら同一PRに含めていいでしょうか？

**Comment by kaizumaki** [comment]
@MochiMochiTosiki お、たしかにそうですね。同時に修正していただいて大丈夫ですよ！
