### ISSUE TITLE
GitHub Actionsのビルドでこける

### ISSUE THREAD

**Issue by yokinist** [tokyo-metropolitan-gov/covid19#615]
## 起こっている問題 / Occurred problem
- GitHub Actionsのビルドでこける
  - 取り込んだPR: #614 問題なくビルドが通っている(Netlify)
  - develop: ビルドの際lintでエラーが起きてビルドが通っていない(GitHub Actions)

## スクリーンショット / Screenshot
[![Image from Gyazo](https://i.gyazo.com/9b2ef50fb1b1e65d9b3f051728b48793.png)](https://gyazo.com/9b2ef50fb1b1e65d9b3f051728b48793)

## 期待する見せ方・挙動 / Expected behavior
- PRにESLintでエラーがあった時
  - PRでNetlifyでビルドが失敗する

## 起こっている問題の再現手段 / Steps to reproduce
1. #597 マージ以前につくったPRで、ESLintのエラーがある状態をつくる
2. Netlifyではビルドが通る
3. マージ後 `development` ではビルドが失敗してしまう

## 考えられる対応策
- ~#597 マージ以前につくったPRについては最新のdevelopmentをpullするフローを踏む~
- eslintも含まれてしまっている `yarn generate` を分けて
  - NetlifyのDeploy PreviewだけにESLintのエラーでビルド失敗させるように変更(#620 で対応)

**Comment by yokinist** [comment]
これについてですが、PR送る前に一度 `development` をpullもらうようなフローを踏んでもらう必要があるようです

**Comment by yokinist** [comment]
ひとまずdevelopのエラーが起きている箇所を直すPRを送って対処します

**Comment by yokinist** [comment]
最新のdevelopmentを取り込んでいたらNetlifyでもlintが走っているのでerrorがあったらビルドに失敗するはず
[![Image from Gyazo](https://i.gyazo.com/00577eeccb5e84ffb20fef3c4073c1de.png)](https://gyazo.com/00577eeccb5e84ffb20fef3c4073c1de)

**Comment by mikkame** [comment]
@yokinist そもそもnetlifyでlint/buildしているので
actionsでビルドしているのは二度手間かもしれないです。
どう思われますか？

**Comment by yokinist** [comment]
@mikkame そうでしたね...!!actions使っていないのであればおっしゃるとおり二度手間なので削除してしまっても問題ないと思います！

**Comment by mikkame** [comment]
@yokinist 逆に今の状態でactions落ちるって事は次回のデプロイ失敗してしまうのではないかという懸念が・・・・

**Comment by yokinist** [comment]
@mikkame 
今のままでは考えられますね・・
対応としては2択なんじゃないかなと思っていますが、いかがでしょうか？
- #597 マージ以前につくったPRについては最新のdevelopmentをpullするフローを踏む
- CIを外す

(分かりづらかったのでissueを更新しました)

**Comment by mikkame** [comment]
@yokinist 

現在本番デプロイはCI経由なので今の所外せません。 それを触るのは@halsk さんと相談です
developmentからは外してOKだと思います。

しばらく本番デプロイに気をつけつつ1案を採用しつつ
デプロイ系actionsからlintチェックを外すのはどうでしょうか

**Comment by yokinist** [comment]
@mikkame あ、すいません言葉足らずでしたがCIからリントを外すでした！

**Comment by yokinist** [comment]
>しばらく本番デプロイに気をつけつつ1案を採用しつつ
デプロイ系actionsからlintチェックを外すのはどうでしょうか

賛成です！こちらについてやることを洗い出して対処していきますね！
ご意見ありがとうございました！！🙏

**Comment by mikkame** [comment]
一応 @halsk さんにも確認の上

**Comment by yokinist** [comment]
まずは `eslint ~` と `nuxt-ts generate` が合わさってしまっている `yarn generate` を分けて本番関係のビルドコマンドにはlintでビルドが失敗されることがないように修正します！🛠

**Comment by kawoka** [comment]
遅くなりました！すみません！！
ありがとうございます！！！

**Comment by kawoka** [comment]
> まずは eslint ~ と nuxt-ts generate が合わさってしまっている yarn generate を分けて本番関係のビルドコマンドにはlintでビルドが失敗されることがないように修正します！🛠

こちらが最適だと思います！！！
申し訳ありません...! 🙇

**Comment by rozeo** [comment]
こちらも少々うかつでした…申し訳ないです🙇

**Comment by yokinist** [comment]
@rozeo こちらの確認不足なので気にならさないでください！
よい良いものを一緒につくっていきましょう🙌

**Comment by kawoka** [comment]
> よい良いものを一緒につくっていきましょう🙌

@yokinist さんがいい人すぎて涙しか出ないです 😭
本当にありがとうございます！！ :bow:
