### ISSUE TITLE
【スマートフォン】タイトル部分のアイコンの大きさがページによって異なる

### ISSUE THREAD

**Issue by emusute1212** [tokyo-metropolitan-gov/covid19#616]
細かくて恐縮ですが。。。

## 改善詳細 / Improve details
スマートフォン表示にしたときに、homeとflowでタイトル部分のアイコンの大きさが違うことが気になりました。

### home

![image](https://user-images.githubusercontent.com/12194829/76070296-9f185200-5fd7-11ea-9945-ffb7189dceab.png)

### flow

![image](https://user-images.githubusercontent.com/12194829/76070349-b6efd600-5fd7-11ea-883a-453bbbc21e56.png)

## 期待する見せ方・挙動 / Expected behavior

homeとflowは同じ大きさのアイコンが表示されるべきであると思います。

## 動作環境・ブラウザ / Environment
- Windows & Android
- Chromeのデバッグモードのモバイル表示 & Chrome

**Comment by himatani** [comment]
@emusute1212 
homeのアイコンの大きさが正かと思いましたが
flowは以下のissueの通り、手を付けない方が良さそうですね。
https://github.com/tokyo-metropolitan-gov/covid19/issues/576

**Comment by emusute1212** [comment]
あ、本当ですね・・・。 :innocent:

クローズしておきます。 :bow:
