### ISSUE TITLE
トップページにおいて components/PageHeader.vue は components/SiteTopUpper.vue ではなく pages/index.vue からアクセスすべき

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#6165]
## 改善詳細 / Details of Improvement
- トップページにおいて `components/PageHeader.vue` は `components/SiteTopUpper.vue` から参照されているが，`pages/**.vue`（`pages/index.vue`以外）と同様に `pages/index.vue` から参照できるようにする
  - ページ最上部に表示される header を `pages/index.vue` 内で定義できるようにする
  - `components/SiteTopUpper.vue` で定義している最終更新日時および翻訳に関する注釈を，component の props として定義できるようにする
  - `pages/**.vue`（`pages/index.vue`以外）でも翻訳に関する注釈を表示できるようにする（実際，翻訳ができていない箇所があるので表示することが望ましい）

## 期待する見せ方・挙動 / Expected behavior
- `pages/**.vue`（`pages/index.vue`以外）でも翻訳に関する注釈を表示できるようにする
- 他に見た目の変更はなし

**Comment by nard-tech** [comment]
#6102 の merge 後に対応

**Comment by kaizumaki** [comment]
@nard-tech ご提案ありがとうございます！ `SiteTopUpper.vue` って、確か私がタブ切り替えを実装している時に試行錯誤して作ったものだと思うんですよね。タブ切り替えのパーマリンクを頑張って試していた時だと記憶しています。（このあたり #4637 #4822）
結局パーマリンクをあきらめたので、 `SiteTopUpper.vue` でコンポーネント化しなくてもいいのですよね。なので、 `SiteTopUpper.vue` の中身をすべて `pages/index.vue` に展開してもらってかまいません。

**Comment by nard-tech** [comment]
@kaizumaki なるほど．承知しました．いますぐに着手すると #6102 と conflict するのが目に見えているので，#6102 が merge されたら対応します．
