### ISSUE TITLE
陽性患者の属性 の一覧に「退院」列を追加したい

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#618]
東京都患者発生発表数データ列にある、退院フラグのデータが取れるようになったため、「陽性患者の属性」一覧に退院列を表示してほしい。
表示は、退院された方の行に「〇」を表示してください。

**Comment by mikkame** [comment]
データはすでに用意されています。

**Comment by mikkame** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/data/data.json#L647

**Comment by kikd** [comment]
列の追加位置は一番右でしょうか？

**Comment by mtenjin** [comment]
はい、1番右でお願いします。

**Comment by ihcugamay** [comment]
@kikd   
すみません。PR出してしまいました。。。

**Comment by mtenjin** [comment]
画面見ました。素早い！
で、○はセンタリングされてますでしょうか？
ちょっと左寄りかな、と。

**Comment by ihcugamay** [comment]
センタリングはしておりませんので、対応いたします！

**Comment by kikd** [comment]
@ihcugamay お気になさらず！

**Comment by ihcugamay** [comment]
@mtenjin 
ライブラリ(Vuetify)の[仕様](https://vuetifyjs.com/ja/components/data-tables)に沿って指定してみましたが、センタリングされないため、
個別にCSSを書いてスタイルを当てて修正いたしました。

**Comment by mtenjin** [comment]
こちらのハンドリング不足ですみません、列名を 退院※ として、表の下に
※退院には、死亡退院を含む
の文章を追加していただけないでしょうか。
場所は、オープンデータへのリンク の上が良いですが、下でもかまいません。

**Comment by ihcugamay** [comment]
いえいえ！
以下のようなデザインで問題ないでしょうか。
![スクリーンショット 2020-03-06 22 10 26](https://user-images.githubusercontent.com/40651754/76086402-60928f80-5ff7-11ea-85e9-d9a368b31cc9.png)

**Comment by mtenjin** [comment]
はい、ばっちりです。
ありがとうございます！

**Comment by ihcugamay** [comment]
修正コミットいたしました！

**Comment by halsk** [comment]
こちら、多言語化終了後改めて確認が必要です。
