### ISSUE TITLE
新型コロナウイルス感染症が心配なときに (flow) の取り扱い

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#6188]
## 改善詳細 / Details of Improvement
- 現在，かつての「新型コロナウイルス感染症が心配なときに」のページ（https://stopcovid19.metro.tokyo.lg.jp/flow ，以下単に flow ページという）にアクセスすると https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html にリダイレクトされる．
- flow ページはもはや使われておらず，メンテナンスもほとんどされていない状態になっているので，リダイレクトが発生しなかった場合を考慮した最低限の案内だけ残して内容の大部分を削除するべきだと思う．

### 現在（リダイレクトをしない場合）
<img width="1617" alt="スクリーンショット 2021-04-20 0 15 40" src="https://user-images.githubusercontent.com/23148331/115261391-8b459600-a16e-11eb-9cd9-3e7814b74ab9.png">

## 期待する見せ方・挙動 / Expected behavior
- リダイレクトが発生しなかった場合を考慮した最低限の案内だけ残して内容の大部分を削除する

### 例
<img width="1618" alt="スクリーンショット 2021-04-20 0 51 53" src="https://user-images.githubusercontent.com/23148331/115266124-e24d6a00-a172-11eb-8c9e-7e9d209b06f9.png">

**Comment by kaizumaki** [comment]
@nard-tech ご提案ありがとうございます！
このリダイレクト、東京都から依頼があった時は「flowページをざっくり削除してほしい」ってことだったんですよね。まあ、htmlファイルがあるわけではないですし、また状況が変わるかもしれないと思い、私の方でflowページは残してリダイレクトにしました。
なので、リダイレクトが発生しなかった時の代替の表現というのは考えてなかったですね。
ところで、「リダイレクトが発生しない」というのは、どういう場合が考えられるでしょうか？

**Comment by kaizumaki** [comment]
@nard-tech 

> 実際，components/PageHeader.vue を修正しようとしたときにこれが flow で使われていたため，どのようにするのが最善かで迷って，この issue を出した経緯があります．

それは申し訳ありませんでした。

いずれにせよ、コンテンツの追加は東京都の確認が必要になりますので、しばしお待ちいただければと思います。

**Comment by taka1985** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/5641
元のIssueはこちらかと思いますが、一時的に振り替えた様に見受けられます。
またflowページを作り直して戻す、という方針にもみえるのですが…どんなもんでしょうか…＿

**Comment by kaizumaki** [comment]
@taka1985 フォローありがとうございます！ #5641 の頃は状況が不透明でしたので、私のほうでflowページを改修する可能性も考えて残しておいたのですよね。flowページは厚生労働省の方針も関係してきますので、改修の決定は簡単にはできない状況でした。とはいえ、もう半年経ちましたので、混乱を避けるためにもいったん削除するのがよいかと思っています。

**Comment by taka1985** [comment]
@kaizumaki さん
なるほど、承知しました。
Fork側のCodeforNiigataさんでも同様にflowページをどうするか、というissueがいくつかあり、
ちょうど議論をしていたところでした。
https://github.com/CodeForNiigata/covid19/issues/307
https://github.com/CodeForNiigata/covid19/issues/308
https://github.com/CodeForNiigata/covid19/issues/315
