### ISSUE TITLE
多言語対応

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#62]
作っておきます。

**Comment by osoken** [comment]
とりあえず `i18n` 使って予備調査します

**Comment by osoken** [comment]
```
yarn add nuxt-i18n 
```

`nuxt.config.js` の `modules` に以下を追加で英語日本語の切り替え準備ができる。

```
    [
      'nuxt-i18n',
      {
        locales: [
          { code: 'ja', iso: 'ja_JP' },
          { code: 'en', iso: 'en-US' },
        ],
        defaultLocale: 'ja',
        vueI18n: {
          fallbackLocale: 'ja',
        },
        vueI18nLoader: true
      }
    ]
```
問題なく導入できそう。

`vueI18nLoader` のおかげで文字列だけ json や yml に書き出して読み込むこともできるので、分業も可能で導入しやすそうです

**Comment by osoken** [comment]
```
ℹ Generating pages
✔ Generated /flow
✔ Generated /en/
✔ Generated /about
✔ Generated /en/about
✔ Generated /en/flow
✔ Generated /
```

`/en` ルートがサイト生成時に自動で作られるようになった。実際に言語対応していないので、日本語のままだが。

対応予定言語用の設定をして、言語ファイルをどう扱うか決め、1箇所どこか多言語対応したらこのissueはクローズして、ページごとのissueを立てたりするのが良いかもしれない。

https://github.com/tokyo-metropolitan-gov/covid19/commit/c90c8ad8bb3ed943b4a10440dcd383be23921d8e

**Comment by hiro-ishi** [comment]
既存のページに関しては「このサイトについて」以外は英訳完了し、現在レビュー中。
以下のスプレッドシート、D列のEnglish(revised)が最終版です。
https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit?usp=sharing

**Comment by hiro-ishi** [comment]
以下のスプレッドシートに英語訳確定版をまとめました。
「当サイトについて」の英語訳( #312  )はこれから（V4以降?）
A列：ウェブサイトのページ名
B列：日本語
C列：英語訳（確定版）
https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit?usp=sharing

**Comment by potato4d** [comment]
単純に i18n やるだけだといくつか罠があるので、よければ貢献させてください！

**Comment by takaaki-kanetsuki** [comment]
中国語版などの必要があればお手伝いするので、お声がけください！

**Comment by potato4d** [comment]
@osoken @kenshir0f @fanjia38
こちらひとまず導入し、並列作業できるようにするまでです。
よろしくお願いいたします！
https://github.com/tokyo-metropolitan-gov/covid19/pull/329

**Comment by hiro-ishi** [comment]
「新型コロナ受診相談窓口 combined telephone advice center」
「新型コロナコールセンター COVID-19 Telephone Advisory Center」
の正式英語訳を都庁に決定してもらう必要あり

新型コロナ受診相談窓口の訳は以下の都のサイトから引用しています。
[Frequently asked questions about the novel coronavirus (COVID-2019) (information current as of 18 February 2020)](https://www.metro.tokyo.lg.jp/english/topics/2020/0214_00covid19.html)

**Comment by yamanoku** [comment]
以下Issueでもコメントしましたが、現状スクリーンリーダーで日本語が読まれない問題があるため、htmlの `lang`属性指定などは早い対応であると助かります。
https://github.com/tokyo-metropolitan-gov/covid19/issues/65#issuecomment-594555464

よろしくお願いいたします。

**Comment by sonialiang** [comment]
中国語の場合、私も手伝えます。
繁体字がネイティブです。（簡体字もできます。）

**Comment by hiro-ishi** [comment]
都がどこまでの言語に対応するかはわかりませんが、逐語訳テーブルに中国語（簡体字）、中国語（繁体字）の列を追加しました。私は監修できない上、実装されるかはわかりませんが、訳者の方の裁量で作業を進めても問題はないと思います。

**Comment by IkarosuTsubasa** [comment]
簡体字の方がネイティブです、もし問題がなければ翻訳の作業を始めます。

**Comment by halsk** [comment]
@IkarosuTsubasa さん、
ぜひよろしくおねがいします！！！

**Comment by lisaky** [comment]
> 都がどこまでの言語に対応するかはわかりませんが、逐語訳テーブルに中国語（簡体字）、中国語（繁体字）の列を追加しました。私は監修できない上、実装されるかはわかりませんが、訳者の方の裁量で作業を進めても問題はないと思います。

ありがとうございました、皆の力で完成しましたよ
https://g0v-tw.slack.com/archives/C02G2SXKX/p1583417141240700

**Comment by misogihagi** [comment]
@hiro-ishi さんにききたいのですがどうやって文字列を抽出したのですか？
どう反映するにしてもテンプレートに埋め込む識別子が必要です。
なければ「{テンプレートファイル}_{文字列のハッシュ}」で作っておきますが

**Comment by hiro-ishi** [comment]
文字列抽出は完全にマニュアル操作、目視で抽出しております、、、
始めた当初はコンテンツが少なかったのでなんとかなってたのですが、今後苦労する可能性があります。
便利な方法があるのであればぜひ実装お願いします！
私めに知見をお与えてください！！
> @hiro-ishi さんにききたいのですがどうやって文字列を抽出したのですか？
> どう反映するにしてもテンプレートに埋め込む識別子が必要です。
> なければ「{テンプレートファイル}_{文字列のハッシュ}」で作っておきますが

**Comment by kikd** [comment]
「やさしい日本語」の中に、ひらがなとカタカナで表記ブレしている単語（ページ、アドバイス）があるのですが、
どちらに統一するのが無難でしょうか。

**Comment by sonialiang** [comment]
> 文字列抽出は完全にマニュアル操作、目視で抽出しております、、、
> 始めた当初はコンテンツが少なかったのでなんとかなってたのですが、今後苦労する可能性があります。
> 便利な方法があるのであればぜひ実装お願いします！
> 私めに知見をお与えてください！！
> 
> > @hiro-ishi さんにききたいのですがどうやって文字列を抽出したのですか？
> > どう反映するにしてもテンプレートに埋め込む識別子が必要です。
> > なければ「{テンプレートファイル}_{文字列のハッシュ}」で作っておきますが

ソースコード読めてなくてすみませんが、
crowdin でどうにかなりませんかね?
確か oss は無料で使えます。

**Comment by takaaki-kanetsuki** [comment]
カタカナ だと未就学児や、外国の方が読めない場合もあるので、「やさしいにほんご」だったらひらがなの方がいいかもですね。この辺は幼児教育に従事されてる方や、日本語学校の方がいらっしゃれば聞いてみたいです

**Comment by MaySoMusician** [comment]
#595 にある島根県の資料によるとカタカナ外来語は避けるべきとあるので、「アドバイス」については「おしえてもらう」など動詞に置き換えるのが良いかと思います。

**Comment by kikd** [comment]
アドバイスをなくした文章になおしました。
（意味が変わってしまっていたらすみません。。。）

**Comment by k018c1077** [comment]
質問です。
翻訳のファイル、拝見させていただきました。
「新型コロナウイルス感染症が心配なときに」
の訳がそのまま、「コロナウイルスを心配に思っている」といった意味で翻訳されていますが
リンク先のページに書いてあることは
「**新型コロナウイルスへの感染**」を不安に思っている人への情報なのではないかと思います。

こちら、「新型コロナウイルスへの**感染**が心配なときに」という意味で捉えて翻訳したほうが
ページ内容に即したものなのではないかと思います。

あまり言語学には詳しくなく、ニュアンスに基づく部分で恐縮ですがいかがでしょうか？

**Comment by dongsiku** [comment]
日本語の原文について質問があります．
当サイトのWeb環境について`Apple Safari (OS X) 最新版`との記載がありますが，`macOS`でなくても問題ないのでしょうか．

**Comment by ryo-a** [comment]
[Electron](https://electronjs.org/) などでCrowdinを用いた翻訳・校閲に携わっております。
もし何かお手伝いできることがあればお声掛けください。
https://github.com/tokyo-metropolitan-gov/covid19/issues/62#issuecomment-595609394


また、i18n関連や翻訳に関する様々な議論がこのIssue (#62) に集中しつつあるようなので、議論を明確にするためにも "国際化/internationalization" などのラベルを作成して個別のIssueを作成するように誘導するほうが良さそうに見えます。

**Comment by MaySoMusician** [comment]
サイトのi18n化に関しては #680 を立てましたので、技術的な内容はこちらでもお伺いします
