### ISSUE TITLE
refactor: コードベースを TypeScript 化する

### ISSUE THREAD

**Issue by potato4d** [tokyo-metropolitan-gov/covid19#621]
ひとまず落ち着きを見せているため、これまで導入だけしてほぼ行われてこなかった TypeScript を実施したい。

## 改善詳細 / Improve details

以下を順番に行う

- [x] 最新版の TypeScript 環境(3.8) で書くために Nuxt.js をアップデート
- [x] nuxt.config.js を nuxt.config.ts へと書き換える
- [x] すべての .js ファイルを .ts ファイルへと置き換え、型定義を書き終える
- [ ] CI 上で tsc または nuxt build を実行して型エラーを検知できるようにする
- [ ] .vue ファイルを TS 化する

## 期待する見せ方・挙動 / Expected behavior

- コードベースがすべて TypeScript 化されている状態

## 詳細 / Details

以下を方針として提案する。

### Vue Component では Vue.extend の形を取る

- Vue 3.0 において Class API はコアに取り込まれなかったため
- Vue 3.0 においてデファクトとなることが予想される Composition API が現状の Object の形式に非常に近いため
- 単純にコンフリクトを最小限に抑えるため

### Vue Component については、まとめて TS 化を行わない

- Vue Component では、 computed の戻り値などを含め詳細に型情報を付与してやる必要がある
  - 現状の This Types の補完の仕様上
  - それなりに変更が大きくなりインパクトがある変更となってしまうため、できるところから進める

### 共通型定義は ./types/ の置く

- TS 移行のために作成しておいたディレクトリ
- 共通的なものは無理に他の部分で named export せずに、`import { Foo } from '~/types'` から import してくる

### プラグインで増える型定義も積極的に書く

- `vue-shim.d.ts.` に頑張って `this.$xxx` 系の定義を書いていきましょう

**Comment by mikkame** [comment]
一度に全てのファイルをts化してしまうとレビューが難しくなるためファイルごとに対応いただけるとたすかります！

**Comment by potato4d** [comment]
2,3 個 class-component があるけどまぁそこは徐々にやっていくで良いでしょう（共存でもヨシ）

**Comment by mikkame** [comment]
ラベル refactoring を作成しておきました

**Comment by kawoka** [comment]
#658 でのバグfixで PageHeader.vueを修正したので、ついでにts化しましたのでご確認くださいませ！

**Comment by MaySoMusician** [comment]
`data/*.json`の型についてi18nから日付系のデータに関する要望なのですが、日付・時刻に関しては`string`ではなく`date`で処理できるようにしてほしいです。
現状（`development`ブランチ時点）、表示するだけの文字列は`string`になってるのが多いと思います。
今見つけた例ですと、
- `metro.json`の`"M月D日~[M月]D日"`を開始日と終了日で分けて保存する（〇日～×日という表現は言語によって異なるため）

という感じです（もしかしたらこれぐらいかも）

加えて、`Time[Stacked]BarChart.vue`で`'1/24'`を`'1月24日'`に変換するような処理ですが、現状の実装だとi18nしづらいので
- 全言語で`'1/24'`の表示で統一する
- 元データを`date`型で保持し、今ある「`'1月24日'`に変換」の代わりにi18nプラグインの日付翻訳機能を使う（英語だと`'Jan. 24'`のようにできる）
のどちらかにしていただけるとありがたいです。（個人的には、`'1/24'`で統一する場合も`*.json`内では`date`になっていた方が気持ち良かったり...）
