### ISSUE TITLE
TS@4.2.4 へのアップグレード

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#6211]
## 起こっている問題 / The Problem
- Renovate によるパッケージのアップグレードジョブで、[Typescript@4.2.4 へのアップグレード](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html)をはじめ、一筋縄ではいかないモノが存在する
- そうした場合、プログラムの改修を求められることがある。その中でも軽微と思われる Typescript にアップグレード・トライアルを実施する

## スクリーンショット / Screenshot

むしろ、パッケージ・モジュール群はアップグレードに伴いアピアランスやルック＆フィールが現行本番からほとんど変わらないことを目標にすべきである

## 期待する見せ方・挙動 / Expected Behavior
パッケージ・モジュールがタイムリーにアップグレードされることで、以下のようなメリットが得られる：
1. 新規機能の利用機会がもたらされる、あるいは、新たな技術トレンドを取り入れたモジュールの使用機会ができる
2. サポートが提供される場合、サポート・ライフサイクルの期限の到来を、アップグレードによって大幅に後ろ倒しにできる
3. 他の多くの開発者もソースを参照する本プロジェクトで、先取的な姿勢をアピールすることで、そうしたエキスパートたちの新規参入・協力を促す

## 起こっている問題の再現手段 / Steps to Reproduce
See #6173

**Comment by cutsortuniq** [comment]
[新型コロナウイルス感染症対策サイト(非公式)](https://iwate.stopcovid19.jp)では、スキルフルな開発者による、プロアクティブな開発が行われているようで、約1ヶ月前にサクッと対応済みですね。

[https://github.com/MeditationDuck/covid19/pull/1385](https://github.com/MeditationDuck/covid19/pull/1385)

**Comment by mcdmaster** [comment]
@cutsortuniq まさに、そこで書いていただいているようなことをやろうとしています。
まあ、こちらも私はともかく(笑)皆さんとてもスキルフルだと思いますよ。本当に勉強になります。
あと、申すまでもないですけれどもリリース管理プロセスの一部に都の承認取得という行為もありますから、仮に「サクッと対応」できないとしても、おそらく納得ずくでしょう。

むしろ、もしも私かこうしたプロジェクトでプロマネを務めるとしたら、ノウハウが偏ってしまうことを懸念します。プラットフォームやモジュールが OSS で構成されているのは、そうした属人化の回避にいくぶん寄与していると私は思っています。それでもなお、スキルフルな開発者に開発負担が偏ってしまうこともあるんでしょうね。人間だもの、みつを

**Comment by cutsortuniq** [comment]
OSSプロジェクトの多くは、原則として緩やかでありながらも、コアチームやテックリードに相当するしっかりした体制が存在することが多いですよね。東京都のプロジェクトは税金等を使った事業であることから、いわゆるフリーソフトウェア等のOSSプロジェクトとは、責任の特性が根本的に違いますが。
