### ISSUE TITLE
日別の陽性患者数について

### ISSUE THREAD

**Issue by Tomohirohashizume** [tokyo-metropolitan-gov/covid19#623]
## 改善詳細 / Improve details
トップページの陽性患者数の欄ですが、[日別]の場合「新たな陽性患者数」とするのが的確だと思います。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yoshipe** [comment]
変更してみましたが、よく考えてみると今度は累計にした時にややこしいですね。

**Comment by Tomohirohashizume** [comment]
日別の欄は本当に必要でしょうか？累積だけを表示するとか？
まさか陽性患者の数が8人だけなわけはないので、わかるといえばわかりそうなものですが、やっぱり`陽性患者数 8人`と出ていると違和感を感じます。

**Comment by Yoshipe** [comment]
確かに、そうですね。いっそのこと、デフォルトを累積にする処理に変更してみました🤔

**Comment by Tomohirohashizume** [comment]
良いアイディアですね。良いと思います。ありがとうございました!
