### ISSUE TITLE
日別の重症者数の内訳

### ISSUE THREAD

**Issue by nnawata** [tokyo-metropolitan-gov/covid19#6235]
## 改善詳細 / Details of Improvement
- 東京都が日々発表する報道の中で、参考値として年代別/性別の重症者の数がありますが、それをPDFではなくCSVやJSONの形式で搭載してもらえないでしょうか。

## 期待する見せ方・挙動 / Expected behavior
- CSVやJSONの形式で搭載

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@nnawata ご提案ありがとうございます！重症数の内訳とは、もしかして[こちらのPDF](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.files/0422gurafumatome.pdf)のことでしょうか？

**Comment by nnawata** [comment]
毎日出ている（たとえばhttps://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2021/04/27/documents/30_00.pdf）の２番の「参考」の１つ目「重症者の属性」です。

**Comment by kaizumaki** [comment]
@nnawata なるほどです。東京都に確認しますので、しばらくお待ちください 🙏

**Comment by miotomita** [comment]
@kaizumaki  こちらの重症者数の内訳（年代別）、json/csv等での搭載は難しいでしょうか。少し時間が経過しているところへ申し訳ないですが、nnawataさんと同じ要望を持っています。

**Comment by kaizumaki** [comment]
@miotomita ご要望ありがとうございます。返答にお時間かかっていること申し訳ありません。
再度確認してみます。
なお、オープンデータcsvへの要望は[東京都オープンデータカタログサイト](https://portal.data.metro.tokyo.lg.jp/)の[リクエストボックス](https://www.shinsei.elg-front.jp/tokyo2/uketsuke/form.do?id=1490076764800)から投稿いただくのが早いと思います。私も結局は同じところへ要望を届けていますので...

**Comment by kaizumaki** [comment]
ご提案ありがとうございます。返答が遅くなりまして申し訳ありません。
以下、東京都から回答がありました。大変恐縮ですが、これをもってissueをクローズといたします。

> 御意見いただきありがとうございます。
> 重症者の属性情報につきましては、日々のプレス発表により、
> 都民等への情報提供を行っているところです。
> 現段階では対策サイトへの掲載、CSVまたはJSON形式での発表は予定しておりません。
> 大変申し訳ございませんが、御了承いただけますと幸いです。
