### ISSUE TITLE
ワクチンの接種状況について

### ISSUE THREAD

**Issue by nnawata** [tokyo-metropolitan-gov/covid19#6236]
## 改善詳細 / Details of Improvement
- 自治体別年代別（または高齢者orその他）のワクチン接種の進行状況（１回め/二回目、日別・累計・人口比）について、CSVないしグラフで表示してもらえないでしょうか。

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@nnawata ご提案ありがとうございます！ワクチン接種状況に関するデータですね。[こちらのページ](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronavaccine.html)およびそこからリンクされてる[こちらのPDF](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronavaccine.files/sessyujisseki_20210426.pdf)のデータになりますでしょうか。
東京都に確認しますので、しばらくお待ちください 🙏

**Comment by nnawata** [comment]
はい。まさしくこのデータです。元データがVSYSにあってそれを加工してPDFにしている様子なので、簡単にとれると期待しています。

**Comment by kaizumaki** [comment]
@nnawata 了解しました。東京都に確認しますね！

**Comment by takainou** [comment]
横から失礼します。

既にやりとりされている通り、[東京都新型コロナウイルスワクチン接種ポータルサイト](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronavaccine/index.html)
にワクチン接種実績が表で掲載され始めましたが、分かりやすくグラフ表示されるのが好ましいと考えます。本サイトへのグラフ掲載を検討いただけませんでしょうか。

まずは、東京都全体の1回目/2回目積み上げで累計(初期表示)・日別の棒グラフがあれば良いと考えます。詳細情報(医療従事者・高齢者別、自治体別、人口比・高齢者人口比)や、調達供給情報(国から都、都から自治体)などは、まずはcsvで提供開始し、必要に応じグラフ化でいかがでしょうか。

添付画像は[神戸市におけるワクチン接種実績](https://www.city.kobe.lg.jp/a73576/kenko/health/infection/protection/covid-19_vaccine.html#jisseki)です。
![image](https://user-images.githubusercontent.com/63571899/116767166-4b818700-aa69-11eb-97c5-704bc46055c3.png)
![image](https://user-images.githubusercontent.com/63571899/116767168-4f150e00-aa69-11eb-9ff7-8d8aeb7759ae.png)

なお、医療従事者向けがワクチン接種円滑化システム（V-SYS）、高齢者向けがワクチン接種記録システム（VRS）のようですので、取得元には留意が必要かもしれません。

検討および都との確認をよろしくお願いします。

**Comment by kaizumaki** [comment]
@nnawata @takainou コメントありがとうございます！お時間いただきまして申し訳ありません。
東京都のほうでもワクチン接種数のグラフ提供については検討されており、こちらのissueも後押しする形になりました。ありがとうございます！
当面は「高齢者」の「週別累計」のデータを提供することとなっています。仕様がありますので、別途issueを立てて進めたいと思います。
