### ISSUE TITLE
https://www.stopcovid19.metro.tokyo.lg.jp/ にアクセスできない

### ISSUE THREAD

**Issue by Tomohirohashizume** [tokyo-metropolitan-gov/covid19#624]
## 起こっている問題 / Occurred problem
トップページ の `陽性患者数` にある `オープンデータへのリンク` で下記のウェブサイトへ飛ぶと
https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068
`追加情報`の`ソース`フィールドにて、
https://www.stopcovid19.metro.tokyo.lg.jp/
へのリンクがあるが、ここにはアクセスできない。`www.` を消さないといけない。

## 期待する見せ方・挙動 / Expected behavior
-https://www.stopcovid19.metro.tokyo.lg.jp/ ではなく https://stopcovid19.metro.tokyo.lg.jp/ に飛ぶようにする。

## 動作環境・ブラウザ / Environment
- Linux
- Chrome

**Comment by mikkame** [comment]
確認しました。こちらでは管轄できない範囲ですので対応できる人に伝えます。

**Comment by MaySoMusician** [comment]
こちら、修正されていたようです。
![image](https://user-images.githubusercontent.com/34566290/76134492-15619680-6062-11ea-83bc-625d3c2ca796.png)
取り急ぎ、ご報告まで。

**Comment by Tomohirohashizume** [comment]
今現在直っておりません
![Screenshot from 2020-03-07 16-22-16](https://user-images.githubusercontent.com/55556714/76146990-f2e67200-608f-11ea-86cb-a256441b5f90.png)

https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068

**Comment by MaySoMusician** [comment]
申し訳ありません。文面を読み落としておりました。ソースのURLは間違っておりました。

**Comment by Tomohirohashizume** [comment]
今みた所修正されていました!
