### ISSUE TITLE
FORKED_SITES.mdに千葉県白井市を追加

### ISSUE THREAD

**Issue by momorito** [tokyo-metropolitan-gov/covid19#6242]
## 改善詳細 / Details of Improvement
千葉県白井市の個人で立ち上げましたので、FORKED_SITES.mdに新規追加を提案します。

## スクリーンショット / Screenshot

<img width="1424" alt="スクリーンショット 2021-04-29 20 43 12" src="https://user-images.githubusercontent.com/22412750/116545612-9d23f780-a92b-11eb-8f51-30fcfb07398c.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by momorito** [comment]
後ほどPull requestあげます。
初めてのことなので、ミス等ありましたらご教示ください。
よろしくお願いします。

**Comment by kaizumaki** [comment]
issueありがとうございます 🙇‍♀️  #6243 をマージしたのでクローズしますね。
