### ISSUE TITLE
ウェブアクセシビリティ方針の掲載

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#6246]
## 改善詳細 / Details of Improvement
これまで改善してきたアクセシビリティについて、正式に方針を立て、試験を実施したうえで基準に準拠していく流れになりました。ついては以下のようなスケジュールで進行したいと考えています。

- 現在〜5月中旬：方針掲載、プレ試験官を数人募集（有識者）
- 5月中旬〜末：プレ試験して状況把握
- 6月〜7月：現状の改善
- 8月：非同期で本試験→結果まとめ
- 9月：試験結果のサイト掲載

アクセシビリティ方針については、WAICのガイドラインに則りCode for Japanと東京都で検討し、以下のように策定しました。
https://waic.jp/docs/jis2016/accessibility-plan-guidelines/201604/

（以下5月7日に調整）
>ウェブアクセシビリティ方針
>
>東京都新型コロナウイルス感染症対策サイトでは、「JISX8341-3:2016 高齢者・障害者等配慮設計指針－情報通信における機器、ソフトウェア及びサービス－第3部：ウェブコンテンツ」に対応することを目標とし、アクセシビリティの確保と向上に取り組んでいます。
>
>対象範囲
>https://stopcovid19.metro.tokyo.lg.jp/ 以下全ページ
>
>適合レベル及び対応度
>JIS X 8341-3:2016の適合レベルAAに準拠
>
>目標を達成する期限
>2021年9月30日
>
>例外事項
>以下は現時点では修正対応が困難であるため、目標の対象外とします。
>・本サイト外から提供されるコンテンツ（https://stopcovid19.metro.tokyo.lg.jp/ の「感染状況・医療提供体制の分析」内におけるサムネイル画像）
>・外部サービスを使用しているコンテンツ及びそれに付随するコンテンツ（全ページに表示される「【東京都新型コロナ】ご質問にチャットボットがお答えします」の機能）
>
>担当部署
>政策企画局（03-5388-2171）

まずはこの方針を「当サイトについて」に掲載するところから開始したいと考えています。
https://stopcovid19.metro.tokyo.lg.jp/about

今後予定している試験（本試験）についてはWAICのガイドラインに則り進行していきます。
https://waic.jp/docs/jis2016/test-guidelines/202012/

なお、本件に関しては 私 @magi1125 と @masuP9 がCode for Japanから業務委託を請けており、旗振りとして進行していきます。どうぞよろしくお願いします。

## 期待する見せ方・挙動 / Expected behavior
https://stopcovid19.metro.tokyo.lg.jp/about
にStaticCardを使って上記方針を掲載する。

東京都のサイトに倣うなら一番上かなと。
https://www.metro.tokyo.lg.jp/concept/index.html

## 動作環境・ブラウザ / Environment
すべての環境

**Comment by bakera** [comment]
方針に関して、2点ほど気になる点がありましたのでコメントさせてください。

1点目ですが、「適合レベル及び対応度」に対応度(準拠or配慮)の記載がないようです。
「準拠」と記載するか、あるいは、意図的に対応度を記載しないのでしたら、見出しの方から「及び対応度」を削除するほうが良いと思います。

2点目ですが、例外事項の記載が不十分であるように思います。
「本サイト外から提供されるコンテンツ」「外部サービスを使用しているコンテンツ及びそれに付随するコンテンツ」とありますが、どのコンテンツが該当するのか客観的には判断できません。アクセシビリティ方針をあえて「公開」するのに、どこが試験対象でどこが試験対象でないのか客観的に分からない状態は望ましくないと考えます (このような記載の仕方をしているサイトが多数あることは承知していますが、それらも望ましくないと考えています)。
たとえば「xxページのyyの部分」「URLに /zzz が含まれる部分」など、客観的に特定できるような具体的な表記はできないでしょうか。

**Comment by magi1125** [comment]
@bakera ありがとうございます。
1点目は表記漏れなので追記します。
2点目の例外についても、私としてはご指摘はもっともと感じます。記載について検討しますのでお待ちください。

**Comment by magi1125** [comment]
@bakera 協議し、2点目も以下のように具体的に記載しようとなりました。ご指摘ありがとうございます！

> - 本サイト外から提供されるコンテンツ（https://stopcovid19.metro.tokyo.lg.jp/ の「感染状況・医療提供体制の分析」内におけるサムネイル画像）
> - 外部サービスを使用しているコンテンツ及びそれに付随するコンテンツ（全ページに表示される「【東京都新型コロナ】ご質問にチャットボットがお答えします」の機能）

**Comment by kaizumaki** [comment]
方針の掲載、私のほうで対応します！
