### ISSUE TITLE
チャットボットのモーダルを一度消してしまうと出なくなってしまう

### ISSUE THREAD

**Issue by kai0310** [tokyo-metropolitan-gov/covid19#6255]
## 改善詳細 / Details of Improvement
- チャットボットのモーダルを消した場合、再度チャットボットを利用しようと思ってもリロードをしない限り表示されないので使いづらい

## スクリーンショット / Screenshot

![スクリーンショット 2021-05-05 16 13 34](https://user-images.githubusercontent.com/52205108/117107637-de4d5900-adbc-11eb-890a-03ba7754dc13.png)

## 期待する見せ方・挙動 / Expected behavior
- 閉じるアイコン押した際に非表示にするのではなく、小さくして隠すなどオン・オフの切り替えがしやすい様にする。

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by kaizumaki** [comment]
@kai0310 ご提案ありがとうございます！issuesページの上部にpinしてあるのですが、チャットボットの担当課は対策サイトの担当課とは別になっています。（詳しくはこちら -> #5455 ）
お手数ですが、#5455 に記載のメールアドレスにご報告いただけると助かります 🙇‍♀️
