### ISSUE TITLE
[i18n] 都内の滞在人口の増減状況の多言語化

### ISSUE THREAD

**Issue by teikan** [tokyo-metropolitan-gov/covid19#6258]
## 改善詳細 / Details of Improvement
- 「2020年1月比 ↓70 %」という語順が決め打ちのため、自然な英語に翻訳するのが困難

## スクリーンショット / Screenshot
![before](https://user-images.githubusercontent.com/115516/117293687-ade4e800-aeac-11eb-84c9-3ea032c9cf81.png)

## 期待する見せ方・挙動 / Expected behavior
- '{date}時点' と同様に '{month}比 {rateWithArrow}' として多言語化し、自然な語順に翻訳できるようにする

![after](https://user-images.githubusercontent.com/115516/117294215-58f5a180-aead-11eb-9311-3888bf0be294.png)

**Comment by kaizumaki** [comment]
@teikan ご指摘ありがとうございます！これは確かにその通りですね。修正する方向でいきたいと思います！
