### ISSUE TITLE
グラフのスタイルに統一感がない

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#6272]
### 現状の問題点

- 「7日間移動平均」の値は以下の通り，グラフによって表現方法が異なっている
  - モニタリング項目(1) 新規陽性者数: オレンジ色 実線
  - モニタリング項目(2) #7119における発熱等相談件数: 濃緑色 実線
  - モニタリング項目(3) 新規陽性者における接触歴等不明者数: オレンジ色 破線
  - モニタリング項目(4) 検査の陽性率（検査人数について）: オレンジ色 破線
  - モニタリング項目(5) 救急医療の東京ルールの適用件数: 濃緑色 実線
  - 受診相談窓口における相談件数: 濃緑色 実線
  - 東京都発熱相談センターにおける相談件数: オレンジ色 破線
- グラフ「モニタリング項目(1) 新規陽性者数」の棒グラフの色は淡緑色だが，他のグラフでは棒グラフが1つだけの場合は緑色とすることになっているので，統一感がない

#### 「7日間移動平均」の値について
- 理解のしやすさを向上させるため，「7日間移動平均」の値はオレンジ色の**破線**で表現するよう統一する
  - オレンジ色にするのは，緑色の線で表現すると緑系統の色の棒グラフに埋もれてしまって見づらいため
  - 「モニタリング項目(3) 新規陽性者における接触歴等不明者数」の増加比，「モニタリング項目(4) 検査の陽性率」の陽性率が実線で表現されているので，全体として「比は実線，7日間移動平均は破線」に統一する
 
#### グラフ「モニタリング項目(1) 新規陽性者数」について
「7日間移動平均」の値をオレンジ色の破線で表現する場合，棒グラフが緑色にしてしまうと緑色が強調されて見づらいため，「モニタリング項目(1) 新規陽性者数」の棒グラフは淡緑色のままとし，他の「棒グラフ + 移動平均の折れ線グラフ」を「棒グラフ（淡緑色） + 移動平均の折れ線グラフ（オレンジ色 破線）」の構成とする．

#### 「7日間移動平均」の値について
- 理解のしやすさを向上させるため，「7日間移動平均」の値はオレンジ色の**実線**で表現するよう統一する
  - 「モニタリング項目(3) 新規陽性者における接触歴等不明者数」の増加比，「モニタリング項目(4) 検査の陽性率」の陽性率が実線で表現されているが，こちらを破線とする．
  - 全体として，「比は破線，7日間移動平均は実線」に統一する
    - 比を破線にすれば，右のY軸に対応する補助的な値であるということが明確になるのでよいかも？
 
#### グラフ「モニタリング項目(1) 新規陽性者数」について
「7日間移動平均」の値をオレンジ色の実線で表現する場合，やはり棒グラフが緑色にしてしまうと緑色が強調されて見づらいため，「モニタリング項目(1) 新規陽性者数」の棒グラフは淡緑色のままとし，他の「棒グラフ + 移動平均の折れ線グラフ」を「棒グラフ（淡緑色） + 移動平均の折れ線グラフ（オレンジ色 実線）」の構成とする．

#### 現状

![スクリーンショット 2021-05-11 5 00 05](https://user-images.githubusercontent.com/23148331/117717447-c9862080-b215-11eb-8b48-87177d8531fb.png)

#### 棒グラフを緑色にした場合（見づらい例）

![スクリーンショット 2021-05-11 5 39 16](https://user-images.githubusercontent.com/23148331/117721804-44056f00-b21b-11eb-9e4b-2b49af4750ab.png)

#### 改善案1

![スクリーンショット 2021-05-11 5 27 28](https://user-images.githubusercontent.com/23148331/117720442-9e053500-b219-11eb-868b-932edfcaee8f.png)

#### 改善案2（現状と同じ）

![スクリーンショット 2021-05-11 5 00 05](https://user-images.githubusercontent.com/23148331/117717447-c9862080-b215-11eb-8b48-87177d8531fb.png)

#### 現状
![スクリーンショット 2021-05-11 5 53 30](https://user-images.githubusercontent.com/23148331/117723377-47015f00-b21d-11eb-87a8-414096d5b9db.png)

#### 改善案1（「モニタリング項目(3) 新規陽性者における接触歴等不明者数」は現状と同じ）

![スクリーンショット 2021-05-11 6 13 02](https://user-images.githubusercontent.com/23148331/117725396-0eaf5000-b220-11eb-8145-101e8f9e4ccb.png)

#### 改善案2

![スクリーンショット 2021-05-11 6 50 15](https://user-images.githubusercontent.com/23148331/117729010-2e954280-b225-11eb-8930-bb3d97e26f3b.png)

**Comment by forestgtree** [comment]
@nard-tech ご提案いただきありがとうございました！
かなり時間が経ってしまってからのコメントとなってしまい、申し訳ありません🙇‍♂️

私もご提案いただいた「改善案１」が良いと思いました✨
その方向で、現状の全グラフの統一性を再考していきたいと思います！

過去のアクセシビリティissueの内容も踏まえつつ
ご意見いただきながら考えていきたいと思いますので、よろしくお願いします！

**Comment by kaizumaki** [comment]
@forestgtree フォローありがとうございます！

カラーチャートについてはルールが崩れたわけではないのですよね。個々のグラフでルールを適用してきた結果、全体的に見ると統一性がなくなったように感じてしまう、というところだと思います。

今回、東京都からも「７日間移動平均の線を統一してほしい」という要望がありまして、過去の経緯を踏まえつつ議論していきたいと思います。
@magi1125 さんのご意見もぜひ伺いたいです。

**Comment by magi1125** [comment]
@kaizumaki @forestgtree 
お返事遅くなりすみません。見解まとめてみました。ご検討ください。

### 同意のポイント
- 移動平均や増加比の折れ線グラフが黒っぽい緑だったりオレンジだったりするので統一したほうがよさそう
- 移動平均と増加比は、どちらかを破線、どちらかを実線で固定したほうが良さそう

### 検討のポイント
- 緑4色（仮に濃い方から①,②,③,④とする）の配色のルールとの兼ね合いをどうするか
  - 現状だと、1系統のみだと②、2系統だと①,③、3系統だと①,②,③、4系統だと①,②,③,④となっている
  - ②と折れ線色が見分けにくいことへの対処として「1系統かつ折れ線グラフがあるときだけ棒グラフの塗りを③にする」で良いのかどうか。
  - 1系統のグラフが多く、また②はサイトのキーカラーでもあるため「②に対しても見分けがつく折れ線の色」を検討する方向もあり得るかも？
- いまの折れ線のオレンジは、D型色覚の場合、②との見分けが厳しそう。Adobe Colorでシミュレーションしてみるとけっこうカラー競合ギリギリ（添付画像参照）。
  - 黄緑っぽい色にするなど、別の色を検討してもよさそう

![スクリーンショット 2021-09-09 21 32 30](https://user-images.githubusercontent.com/17713513/132690289-0cba545b-cfeb-4772-9833-4855b45ca67d.png)

**Comment by kaizumaki** [comment]
@magi1125 コメントありがとうございます！これを機に、折れ線のオレンジを別の色へ変更するのはアリだと思います。
