### ISSUE TITLE
「都営地下鉄の利用者数の推移」について

### ISSUE THREAD

**Issue by J3rd-dev** [tokyo-metropolitan-gov/covid19#630]
## 改善詳細 / Improve details
- 「1月20日~1月24日の利用者数*の平均値を100としたときの相対値表現」について、「なるべく混んでいない電車に乗りたい」「感染確率を分散・低減化させたい」という今のニーズに直接的に応えられるようにしたい (#576解決後の改善案として)

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/61874743/76088251-0693c900-5ffb-11ea-8b63-1ad5043eae3e.png)

## 期待する見せ方・挙動 / Expected behavior
- 例えば、週ごとの更新で「直近週」の混雑ピーク時間帯を100と設定し、1時間ごとにピーク時間帯に対して何％の乗車率（＝実際は自動改札出場数）かで表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by J3rd-dev** [comment]
帰りの時間帯についても、１５時頃から夜まであると良いと思いました。
（選択すれば、すべての時間隊が１時間毎に見えると、なお良いのかもしれません。）

業務上、会社等に出社せねばならないという人の中で、ある程度フレックスな出退勤が可能な人は始発頃出て８時間程度働き、１６時頃帰る人もいます。
病院や工場、工事現場等で夜勤対応の人達やパートタイム勤務、外国の方や高齢者の方々にとっても、全時間帯にわたって見ることができることは、No one left behindの観点でも重要と感じました。

**Comment by NaoyaShimizzz** [comment]
ご提案ありがとうございます。都関係者と協議の結果、下記発表資料の形式に合わせた表示とさせていただいております。ご了承のほどお願い致します。https://www.bousai.metro.tokyo.lg.jp/_res/projects/default_project/_page_/001/007/425/2020030316.pdf

**Comment by J3rd-dev** [comment]
様々にテーマがある中で、東京都関係者皆様とご協議の場を持っていただきましてありがとうございました。修正案の方が元々の当初表示よりも読み手にとってプラスと考えます。結果共有含め御礼申し上げます。
