### ISSUE TITLE
ワクチン接種回数（高齢者・累計）[グラフ新規実装]

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6342]
ワクチン接種回数グラフを新規に実装します。

こちらは #6236 で要望があがっていました。ありがとうございます！
当面は要望通りのデータの提供とはいきませんが、今後拡充していくための第一歩だと思っています。

**5/31（月）リリースです！**

## ワクチン接種回数（高齢者・累計）　実装内容
横並びの集合縦棒グラフです。
累計値のみの表示です。

### 実装イメージ
![対策サイトイメージv2](https://user-images.githubusercontent.com/14883063/119625382-15a3a880-be45-11eb-8705-ed3fa62c92f2.png)

### グラフ
- 棒グラフ（左）
	- ラベル：接種回数（１回目・累計）
	- 単位：人
	- データ： `vaccination.json` の `cumulative_1st_dose` キー
	- 色： `#c5e2c6` （surfaceStyleC）
- 棒グラフ（右）
	- ラベル：接種回数（２回目・累計）
	- 単位：人
	- データ： `vaccination.json` の `cumulative_2nd_dose` キー
	- 色： `#1b4d30` （surfaceStyleA）

### テーブル
ラベル名は以下です。
|日付|接種回数（１回目・累計）|接種回数（２回目・累計）|
|---|---|---|
|〜〇月〇日|〇〇|○○|

### タイトル実装イメージ
- 接種回数（１回目・累計）
	- 注釈： `2021年●月●日累計値`
- 接種回数（２回目・累計）
	- 注釈： `2021年●月●日累計値`

### 注釈
```
・ワクチン接種記録システム（VRS）への報告を居住地の都道府県別に国が集計し、公表したものに基づき作成
```

### 配置
「その他参考指標」タブのグループの８番目（「N501Y変異株スクリーニングの実施状況」の次）に配置します。
「新型コロナコールセンター相談件数」カードの次（右）は空白にします。

![配置イメージ](https://user-images.githubusercontent.com/14883063/119625428-23592e00-be45-11eb-971a-0b61b38fb2f5.png)

**Comment by takainou** [comment]
以下、公開されましたね。
[政府CIOポータル:ホーム 新型コロナワクチンの接種状況（高齢者等）](https://cio.go.jp/c19vaccine_dashboard)

[ワクチン接種状況オープンデータ](https://cio.go.jp/c19vaccine_opendata)も公開されており、「都道府県別接種回数詳細」を用いれば、「週毎から日毎」など、今後の拡充に利用できると思いましたので、参考まで。
