### ISSUE TITLE
「臨時休校中の新型コロナウイルス感染症対応についてのお願い」について

### ISSUE THREAD

**Issue by J3rd-dev** [tokyo-metropolitan-gov/covid19#635]
## 改善詳細 / Improve details
-「お子様をお持ちの皆様へ」の主旨に沿う形になるべく近づけられるようにしたい。
- 具体的には、「3 その他　〇 詳細は、各学校からのお知らせ等をご確認ください。」 の対応を受けられない可能性がある人＝"学校"に通えていない人も安心できる東京都になると良い。
- 対象：（追加対象として）海外から滞在中の子、未就学児、病欠中の子、いわゆる学校教育法"一条校"以外の教育機会を受けている子（フリースクール等）、不登校中の子、等をもつ保護者の方達や子どもたち本人）　(#576解決後の改善案として)

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/61874743/76094506-195fcb00-6006-11ea-82c8-7c68aa9b231f.png)

## 期待する見せ方・挙動 / Expected behavior
- 現在の臨時休校は、「要請」に基づく教育委員会・学校サイド等による対応位置付けとなっているため、都が公式にこのような指針を出すのは難しい事情があるかもしれませんが、各学校で配布する「3 その他 詳細」配布物を、インターネット上であげている学校さん等がいらっしゃれば、そのリンク先を「参考」といった形で掲載するのは一案として考えられる。
- もしくは同様内容を都や東京都福祉保健局さんで掲載されていればそちらをリンクする等も一案
- ※展開するには、都と教育委員会・学校サイド等の行政的確認やり取りが必要と思いますが、No one leave behindの観点で「参考」表記等でも構わないので、何か情報にアクセスできることにつなげられるとよいと思いました。
- #595やさしいにほんご部分を考える中で、またWebアクセシビリティを考える中で、今時点でアクセスが困難な人を含むスコープにしていく必要があるのでは、と感じました。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by himatani** [comment]
こちら対応します！

**Comment by himatani** [comment]
ちょっと気になったのでご存知であれば教えていただきたいのですが
箇条書きに `〇` を使用している意図ってあったりするのでしょうか？

**Comment by J3rd-dev** [comment]
早速ありがとうございます！
コメント頂きました○を使った意味は、私の方での意図は特になく、都のサイトから対象部をそのままコピーして貼った結果となります。

**Comment by himatani** [comment]
ご返信ありがとうございます！
そういった背景なのですね。文言の変更が許させるのであれば、こちらのサイトに合わせて箇条書きに近い形で見せるよう、手を入れても良いかもしれないですね。

**Comment by kaizumaki** [comment]
@J3rd-dev ご提案ありがとうございます。こちらのissueについて都に確認いたしました。当該ページにある「各学校」の対象は1800以上あり、当サイトで集約するには難しい状況です。リンクで対応できるかどうかはまた改めて検討したいと思いますので、こちらのissueについてはクローズさせていただければと思います。どうかご理解いただきますようお願いいたします。

**Comment by J3rd-dev** [comment]
ご確認頂き、また東京都へもご確認の場を持って頂き大変ありがとうございました。
1800以上の各学校情報を、このページにリンク等で集約掲示する必要はないと考えます。

Issue発行の背景は、「各学校からのお知らせ等をご確認ください」を
何らかの事情で確認できない子どもにとって、何かひとつ、
確認できる拠り所があったらと思ったからでした。

あらためての御礼となりますが、大変お忙しい中、
ひとつの意見に対して丁寧にkaizumakiさん、都の方にご対応頂きまして
ありがとうございました。

**Comment by kaizumaki** [comment]
@J3rd-dev ご理解いただきありがとうございます。こちらのissueはクローズしますね。
