### ISSUE TITLE
陽性者の属性の「職業」欄のデータを多言語化したい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6358]
## 改善詳細 / Details of Improvement
- 「陽性者の属性」表はオープンデータAPIからデータを取得しているため、職業欄に書かれたテキストはTransifexに登録されません。
- 東京都から職業の一覧はもらっているので、それをTransifexに登録したいと思います。
[occupation.csv](https://github.com/tokyo-metropolitan-gov/covid19/files/6567393/occupation.csv)
- `ja.json` を直接編集すると、将来的にauto-i18nのスクリプトによって削除される可能性もあります。
- なので、職業一覧を何かしらのファイルに収め、 `i18n_generator.py` に「チェックするファイル」として登録する方法を考えています。
- その場合、どういったファイル形式がいいのか、どういった懸念点があるのか、もしくは他のアイディアなどありましたらお寄せください！

## スクリーンショット / Screenshot

現状がこちら↓
![スクリーンショット 2021-05-31 11 14 35](https://user-images.githubusercontent.com/14883063/120130642-a2fa4a80-c201-11eb-9a30-5f054b5c88c0.png)

## 期待する見せ方・挙動 / Expected behavior
- 陽性者の属性の「職業」欄のデータがTransifexに登録される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@y-chan こちらのissueの件、何かいいアイディアはありませんか？アドバイスいただけると嬉しいです！

**Comment by teikan** [comment]
直交性を考えると、"性別"の"女性"などと同じ扱いで`formatTable.ts`に
```
  患者_職業: 'アルバイト' | ... | '幼児' | undefined
```
などと書き、それを`i18n_generator.py`で認識するのも一案だと思います。
難しいことを考えなければcsvでもよさそうです。jsonにする意味もなさそうですし。

**Comment by kaizumaki** [comment]
@teikan アイディアありがとうございます！それはなるほどですね！
おっしゃる通り、jsonにまでする必要はないと思っています。今後も増えることを考慮すると、csvで管理するのが楽そうではあるのですよね。

**Comment by y-chan** [comment]
個人的な案ですが、いっその事i18n_generatorに埋め込むというのもありだと思っています(1番楽な対処だとは思います)
職業がこれから増えもせず減りもしないなら尚更ですね。

@teikan さんが仰る方法を取るには、i18n_generatorの大幅なリファクタリングが必要なのですが(指摘されている部分はi18n_generatorでは検知しておらず、`男性`や`女性`などの翻訳キーは古いデータを削除していないために残っているだけであると思われるため)、今後のことを考えるとそのようなリファクタをしておく必要はあるかもしれないですね...

**Comment by kaizumaki** [comment]
@y-chan フォローありがとうございます！なるほど、i18n_generatorに直接埋め込むのもありですね。ただ、今後職業一覧が変更になる可能性もあるのですよね。
ちょっと私のほうでi18n_generator.pyにcsv読み込みのブロックを足してみたので、レビューしてもらってもいいですか？リファクタはまた追って、お時間のある時にでもお願いできればと思います。
