### ISSUE TITLE
一度削除された data/tokyo_alert.json が復活している

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#6361]
## 起こっている問題 / The Problem
- `data/tokyo_alert.json` は 86d52c4c4d293edb6bf9669670d17b7b258c448b で削除されたが，`a44906a0f42733c4a30fb158ead95f4b65714729` で復活してしまっている．

## 期待する見せ方・挙動 / Expected Behavior
- データの自動更新スクリプトで `data/tokyo_alert.json` が再生成されないように対応してほしい．

**Comment by kaizumaki** [comment]
ご指摘ありがとうございます！私もいま気づいたところで、調査中です。しばしお待ちください。

**Comment by kaizumaki** [comment]
データのスクリプトを修正しました。 `data/tokyo_alert.json` については削除PRをしておきますね。

**Comment by nard-tech** [comment]
@kaizumaki ご対応ありがとうございます．
