### ISSUE TITLE
追加されたページのタイトルが各国語に翻訳されていない

### ISSUE THREAD

**Issue by yosukedoke** [tokyo-metropolitan-gov/covid19#6394]
## 起こっている問題 / The Problem
- 追加されたと思われるページの多言語版のタイトルが翻訳されていない

https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html

## 期待する見せ方・挙動 / Expected Behavior
- 各言語で適切に翻訳されていること
     - やさしい日本語も対応されているのが望ましい

## 起こっている問題の再現手段 / Steps to Reproduce

下記のURLのページタイトルを確認する（日本語以外の各言語2ページずつ）
https://stopcovid19.metro.tokyo.lg.jp/zh-cn/cards/deaths-by-death-date/
https://stopcovid19.metro.tokyo.lg.jp/zh-cn/cards/variant/
https://stopcovid19.metro.tokyo.lg.jp/zh-tw/cards/deaths-by-death-date/
https://stopcovid19.metro.tokyo.lg.jp/zh-tw/cards/variant/
https://stopcovid19.metro.tokyo.lg.jp/ko/cards/deaths-by-death-date/
https://stopcovid19.metro.tokyo.lg.jp/ko/cards/variant/
https://stopcovid19.metro.tokyo.lg.jp/ja-basic/cards/deaths-by-death-date/
https://stopcovid19.metro.tokyo.lg.jp/ja-basic/cards/variant/

## 動作環境・ブラウザ / Environment
- 全環境対象

**Comment by kaizumaki** [comment]
@yosukedoke issueありがとうございます！英訳以外は追いついていないのが現状です。翻訳チームと連携して進めますね！

**Comment by kaizumaki** [comment]
こちら、随時翻訳対応を行っていますので、一旦issueはクローズとさせてください。
