### ISSUE TITLE
モバイル向けレイアウト時のメニューを開くボタンで開いたあと、メニューの中にフォーカスが移動しない

### ISSUE THREAD

**Issue by k-shirahama** [tokyo-metropolitan-gov/covid19#6397]
## 起こっている問題 / The Problem
- モバイル向けレイアウト時、メニューを開くボタンで開いたあと、メニューの中にフォーカスが移動しない

https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html

## 期待する見せ方・挙動 / Expected Behavior
- モバイル向けレイアウト時、メニューを開くボタンで開いたあと、メニューの中にフォーカスが移動すること

## 起こっている問題の再現手段 / Steps to Reproduce
1. 画面幅600px以下にしてモバイル向けレイアウトを表示する
2. メニューを開くボタンで開いたあとTabキーを押す

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
#6401 #6405 とともに対応します。

**Comment by kaizumaki** [comment]
ちょっと迷っているのですが、メニューを開いた時にフォーカスが当たっているべき要素って、どこになるんでしょう...？
なんとなく１番目の項目かなと思っているんですが、ご教示いただけると助かります 🙏 

![スクリーンショット 2021-06-17 21 56 24](https://user-images.githubusercontent.com/14883063/122402183-354b6e00-cfb8-11eb-880d-cd2ee5d81303.png)

**Comment by magi1125** [comment]
@kaizumaki https://github.com/tokyo-metropolitan-gov/covid19/issues/6405 のことを考えると、「多言語選択メニュー」のテキストに、tabindex="-1" しつつJSでフォーカスをしてあげるとよさそうです。
そうすると、スクリーンリーダー利用時もメニュー内にフォーカスが行くし、キーボード操作時もそこからtabキーを押せばまず先頭のインタラクティブ要素である言語切替セレクトにフォーカスがあたる感じになるかなと。

**Comment by kaizumaki** [comment]
@magi1125 ありがとうございます！「「多言語選択メニュー」のテキストに、tabindex="-1" しつつJSでフォーカス」をさっそくやってみましたらうまくいったようです（この技はすごいですね...！）。
一方で、#6405 のほうがうまくいかず...それについてはそちらでコメントしますね。
