### ISSUE TITLE
グロナビの下部にあるSNSアイコンとコンテンツエリアのシェアアイコンに同じUIが使われている

### ISSUE THREAD

**Issue by kuma0520** [tokyo-metropolitan-gov/covid19#6399]
## 起こっている問題 / The Problem
下記のUIが同じUIを使用されていて、尚且つ別々の機能を果たしているため
一貫した識別性が担保されていない。

- 左のグローバルナビゲーションのSNSアイコン
- カードUIの中にあるSNSシェアアイコン

## スクリーンショット / Screenshot
![スクリーンショット 2021-06-08 21 21 04](https://user-images.githubusercontent.com/52491201/121183972-94fe9680-c89f-11eb-9d55-472529467f76.png)

## 期待する見せ方・挙動 / Expected Behavior
- SNSアイコンとシェアアイコンは役割が違うので、改修が容易なシェアアイコンの方を色を反転するなり見た目を変えることが望ましいです。

## 起こっている問題の再現手段 / Steps to Reproduce
.SideNavigation-Socialの部分とDataView-Share-Openerを目視確認

## 動作環境・ブラウザ / Environment
- 全環境対象

**Comment by kaizumaki** [comment]
@kuma0520 issueありがとうございます！これはなるほどですね。シェアアイコンの見た目を変える方向で、デザイナーと検討してみたいと思います。

**Comment by kuma0520** [comment]
お願いしまーす！！！！

**Comment by kaizumaki** [comment]
シェアアイコンまわりのUIを @forestgtree さんが検討してくれました！シェアのモーダルをこちらのイメージのように実装したいと思います。

![SNS_share](https://user-images.githubusercontent.com/14883063/126974462-ad058d4b-eb70-4d18-a12e-ba0b03e2ce01.png)

**Comment by kuma0520** [comment]
テキストも併記してあってとても素敵だと思います！！！！

**Comment by kaizumaki** [comment]
こちら実装しますね。
