### ISSUE TITLE
各カード内のキーボードでスクロール操作できないエリアがある

### ISSUE THREAD

**Issue by yosukedoke** [tokyo-metropolitan-gov/covid19#6400]
## 起こっている問題 / The Problem
- スクロールが発生しているテーブルやグラフのエリアをキーボードでスクロール操作できない。

https://waic.jp/docs/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html

### 該当ページ一覧（日本語のみ）

- テーブルのスクロールをキーボードで操作できない
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-number-of-confirmed-cases/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-reports-to-consultations-about-fever-in-7119/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/untracked-rate/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/positive-rate/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-tokyo-rules-applied/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-hospitalized/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/positive-status-severe-case/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/attributes-of-confirmed-cases/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases-by-municipalities/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/positive-number-by-developed-date/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/positive-number-by-diagnosed-date/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/deaths-by-death-date/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-tested/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/variant/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-reports-to-covid19-telephone-advisory-center/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-number-of-reports-to-covid19-consultation-desk/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-reports-to-tokyo-fever-consultation-center/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/predicted-number-of-toei-subway-passengers/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/agency/
- グラフの横スクロールをキーボードで操作できない
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-number-of-confirmed-cases/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-reports-to-consultations-about-fever-in-7119/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/untracked-rate/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/positive-rate/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-tokyo-rules-applied/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-hospitalized/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/positive-status-severe-case/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/positive-number-by-developed-date/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/positive-number-by-diagnosed-date/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/deaths-by-death-date/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-tested/
    - https://stopcovid19.metro.tokyo.lg.jp /cards/variant/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-reports-to-covid19-telephone-advisory-center/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-number-of-reports-to-covid19-consultation-desk/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-reports-to-tokyo-fever-consultation-center/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/predicted-number-of-toei-subway-passengers/
    - https://stopcovid19.metro.tokyo.lg.jp/cards/agency/

※ 各言語の同コンポーネントも同様だが実装的には1つ対応すればすべてクリアできると期待されるので列挙していない

## スクリーンショット / Screenshot

下記のグラフ部分、テーブルを表示部分
![スクリーンショット 2021-06-08 21 23 02](https://user-images.githubusercontent.com/1049052/121184115-b95a7300-c89f-11eb-99dd-c030092c3d8b.png)

## 期待する見せ方・挙動 / Expected Behavior

- キーボードで該当のエリアにフォーカスして、そのままキーボード操作でスクロールして隠れている部分が閲覧できる

## 起こっている問題の再現手段 / Steps to Reproduce
1. ページにアクセスする or トップページの該当エリアにスクロールする
2. キーボードでTabを押してフォーカスを進める
3. 該当エリアにフォーカスできない

## 動作環境・ブラウザ / Environment
- Mac OSX - Chromeはできなかった
- Mac OSX /  Windows - Firefox は操作可能だった

**Comment by magi1125** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/1155#issuecomment-613815318
ここでの残課題がプレ試験で再度見つかった感じです。
これはアクセス不能になる致命的な課題なので、対応したいところです。

**Comment by yamanoku** [comment]
`table` に `tabindex="0"` を制御するようにすれば操作可能そう？
https://user-images.githubusercontent.com/1996642/122643231-a79f8800-d149-11eb-9fbc-9ac13bcb7d30.mp4

**Comment by magi1125** [comment]
@yamanoku そのはず。「陽性患者の属性」パネルがあった時代（中身にtableがあった）ときも同じ対応でイケました。
https://github.com/tokyo-metropolitan-gov/covid19/issues/1155#issuecomment-602035018

**Comment by Foo-x** [comment]
対応します。
