### ISSUE TITLE
モバイル向けレイアウト時のメニューを閉じた後、メニューを開くボタンにフォーカスが戻らない

### ISSUE THREAD

**Issue by k-shirahama** [tokyo-metropolitan-gov/covid19#6401]
## 起こっている問題 / The Problem
- モバイル向けレイアウト時のメニューを閉じた後、メニューを開くボタンにフォーカスが戻らない

https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html

## 期待する見せ方・挙動 / Expected Behavior
- モバイル向けレイアウト時のメニューを閉じた後、メニューを開くボタンにフォーカスが戻ること

## 起こっている問題の再現手段 / Steps to Reproduce
1. 画面幅600px以下にしてモバイル向けレイアウトを表示する
2. メニュー開く
3. メニューを閉じる

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
#6397 #6405 とともに対応します。
