### ISSUE TITLE
最新のお知らせのリンクリストに見た目とマークアップの齟齬がある

### ISSUE THREAD

**Issue by YusukeHirao** [tokyo-metropolitan-gov/covid19#6402]
## 起こっている問題 / The Problem
- 対象: https://stopcovid19.metro.tokyo.lg.jp/
- 最新のお知らせのリンクリストが
  - 日付の部分がリンクテキストではないスタイルなのにリンクの一部になってる
  - 見た目やインタラクション（hover）に差があるのでセマンティクスにも差が必要

## 期待する見せ方・挙動 / Expected Behavior
- マークアップに差をつけるなら日付を `time` にする
  - さらに `dl`/`dt`/`dd`で、日付とリンクをわけるのもよいかもしれない

## 起こっている問題の再現手段 / Steps to Reproduce
1.  デベロッパーツールで要素検証して確認

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
@YusukeHirao issueありがとうございます！

>   * さらに `dl`/`dt`/`dd`で、日付とリンクをわけるのもよいかもしれない

この対応はよさそうですね！
