### ISSUE TITLE
グラフカードの右下にある「情報をシェアする」ポップアップを開き、なかの閉じるボタンを選択したとき、開くボタンにフォーカスが戻らない

### ISSUE THREAD

**Issue by k-shirahama** [tokyo-metropolitan-gov/covid19#6403]
## 起こっている問題 / The Problem
- 対象
  - https://stopcovid19.metro.tokyo.lg.jp/
  - https://stopcovid19.metro.tokyo.lg.jp/cards/ 配下全部

- グラフカードの右下にある「情報をシェアする」ポップアップを開き、なかの閉じるボタンを選択したとき、開くボタンにフォーカスが戻らない

https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html

## 期待する見せ方・挙動 / Expected Behavior
- グラフカードの右下にある「情報をシェアする」ポップアップを開き、なかの閉じるボタンを選択したとき、開くボタンにフォーカスが戻ること

## 起こっている問題の再現手段 / Steps to Reproduce

1. グラフカードの右下にある「情報をシェアする」ポップアップを開く
2. ポップアップを開き、なかの閉じるボタンを選択する

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by Foo-x** [comment]
対応します。
