### ISSUE TITLE
カード内の見出しがh3から開始している

### ISSUE THREAD

**Issue by yosukedoke** [tokyo-metropolitan-gov/covid19#6404]
## 起こっている問題 / The Problem
- カード系の個別ページの見出しがh1(サイト名)の次がh3でレベルがスキップしている

## 期待する見せ方・挙動 / Expected Behavior
- 1.3.1的には、レベルはh2から始まるほうが望ましいと思われる
    -  トップページでレンダリングされる場合と個別URLでレンダリングされるケースにおいて同一コンポーネントを利用してることでレベルの段階が変わっていると思われます。
        - 許容しても大きな問題ではないかもしれないが、（実装的には）同一のコンポーネントで実装されているがゆえに文脈によりコンポーネントの要素を h2/h3 で切り替える等で改善は可能と思われるのでご検討ください

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザのデベロッパーツール等で該当部分のソースを確認する

## 動作環境・ブラウザ / Environment
- すべての環境

**Comment by kaizumaki** [comment]
@yosukedoke issueありがとうございます！

>   文脈によりコンポーネントの要素を h2/h3 で切り替える

この方向で対応するのがよさそうですね。

**Comment by bakera** [comment]
このようなケース、発想の転換で、上位のh2見出しを追加することで解決できる場合もあります。
カード型コンポーネントが並ぶシチュエーションでは、それらを括る見出しがあった方が理解しやすくなるケースが多いです。
ご参考までに……。

**Comment by kaizumaki** [comment]
こちら #6415 との兼ね合いを考えると、 @bakera さんのご提案のように上位のh2見出しを追加する方向がいいような気がしてきました。

**Comment by kaizumaki** [comment]
ドラフトで #6528 を立ててみました。 @bakera さんのコメントのようにh2タイトルを追加する作戦です。
セマンティック的にいけてるのかちょっとわからないのですが、これはどうなんでしょう？ @magi1125 @masuP9 
（以下プレビュー）
https://deploy-preview-6528--dev-covid19-tokyo.netlify.app/cards/number-of-confirmed-cases

もしこれでいけるということであれば、コンテンツの修正になるので東京都に確認をとります。

**Comment by magi1125** [comment]
@kaizumaki おお、よさそうです！
