### ISSUE TITLE
スマホサイズ時のナビゲーションにモーダルの役割がない

### ISSUE THREAD

**Issue by YusukeHirao** [tokyo-metropolitan-gov/covid19#6405]
## 起こっている問題 / The Problem
- 対象: https://stopcovid19.metro.tokyo.lg.jp/
- スマホレイアウト時に、ナビゲーションを開くと表示上スクリーン全面に表示されるので「モーダル」の役割をもつように見えるが、「モーダル」のセマンティクスを持っていない
- キーボードもしくは支援技術のカーソルブラウジングで、ナビゲーションの裏まで到達できてしまう

## 期待する見せ方・挙動 / Expected Behavior
- dialog要素でマークアップする / `dialog.showModal()` で開く
  - もしくは `role=dialog` `aria-modal=true` でマークアップする
- モーダルを開いた際にモーダル以外の要素にアクセスできなくする
  - inert属性を利用して不活性にする
  - もしくは `aria-hidden=true` `tabindex=-1` を利用して不活性にする

## 起こっている問題の再現手段 / Steps to Reproduce
- デベロッパーツールで要素検証して確認
-
  1. スマホのサイズ・もしくはスマホで閲覧
  2. ナビゲーションを開く
  3. タブキーでフォーカスを移動する、もしくはChromeのカーソルブラウジング機能で移動する

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
@YusukeHirao なるほど、カーソルがナビゲーションの裏まで到達するのはマズいですね 💦 
dialog要素でマークアップするのが正攻法でしょうか？ `role=dialog` `aria-modal=true` だと難しくなさそうですし。

**Comment by kaizumaki** [comment]
#6397 #6401 とともに対応します。

**Comment by kaizumaki** [comment]
> * dialog要素でマークアップする / `dialog.showModal()` で開く
>   
>   * もしくは `role=dialog` `aria-modal=true` でマークアップする

Vueではどうやら `dialog.showModal()` ができないみたいでしたので、モーダルを開いたときに `role=dialog` `aria-modal=true` を付与するようにしてみました。

> * モーダルを開いた際にモーダル以外の要素にアクセスできなくする
>   
>   * inert属性を利用して不活性にする
>   * もしくは `aria-hidden=true` `tabindex=-1` を利用して不活性にする

モーダルを開いたときにmain要素に `inert` や `aria-hidden=true` `tabindex=-1` を付与するようにやってみたんですが、どうもうまくいきません...。どうしてもモーダルの裏っかわにもフォーカスが移動してしまいます。

ちなみにこれは挙動としては、モーダルが開いているときはフォーカスがモーダル内でしか移動できないというふうにするのが正解なんでしょうか？

**Comment by magi1125** [comment]
@kaizumaki 

>モーダルが開いているときはフォーカスがモーダル内でしか移動できないというふうにするのが正解なんでしょうか？
はい、これが正解です。

ただし、これを一発で叶えてくれるinert属性はまだ使えない状況です。
https://caniuse.com/mdn-api_htmlelement_inert

mainにaria-hiddenを設定するとスクリーンリーダーではアクセスできなくなりますが、キーボードフォーカスはあたります。
キーボードフォーカスを当てないようにするには、main内のすべてのインタラクティブ要素にtabindex="-1"をつける必要があります。

このあたりの事情を解説した文章としては以下が詳しいです。ご参考ください。
https://standard.shiftbrain.com/blog/unavailable-inert-regions-and-inert-attribute

**Comment by YusukeHirao** [comment]
@kaizumaki 

inert属性は、過去 https://github.com/WICG/inert というポリフィルで対応したことがあります。
しかし、VueなどのVirtual DOMを持つライブラリと同時に使ったことがないので、どんな影響がでるか自分はわかっていません。
Virtual DOMで制御されない要素であれば、的確にインタラクティブ要素にtabindexとaria-hiddenを制御（main要素からinertが外されたら、その子孫のtabindexとaria-hiddenももとに戻る）します。

**Comment by kaizumaki** [comment]
@magi1125 @YusukeHirao 
アドバイスありがとうございます！inertはまだ現実的ではないのですね。
参考記事も拝見しました。とてもわかりやすくて助かりました 🙏 

Vueにおいて的確にtabindex="-1"を付与する方法をいろいろググって調べてみたんですが、なかなか難しそうなことはわかりました。
ただ、[こちら](https://skysan87.hatenablog.com/entry/2019/11/25/011933)の記事を見つけて、これならいけそうかも？と思っているのですが、どうでしょうね？

**Comment by magi1125** [comment]
@kaizumaki よく考えたら、このメニューは展開時は下の要素が透けて見えずに全体を覆うので、展開と同時にmainにaria-hidden + visibility:hiddenしちゃえばいいかも（閉じるときは逆）。あるいはもはやdisplay:noneでもいいかも。

ちなみに貼っていただいた記事のようにフォーカスをトラップしてループさせる手法もあるのですが、そうするとブラウザのアドレスバーなどにフォーカスさせられなくなるので、避けられれば避けたいところです。

>

**Comment by kaizumaki** [comment]
@magi1125 ありがとうございます！
> 展開と同時にmainにaria-hidden + visibility:hiddenしちゃえばいいかも（閉じるときは逆）。

こちらでいけそうです！
