### ISSUE TITLE
ナビゲーションのリストの区切りが見た目のみでマークアップ上は区切られていない

### ISSUE THREAD

**Issue by YusukeHirao** [tokyo-metropolitan-gov/covid19#6406]
## 起こっている問題 / The Problem
- 対象: https://stopcovid19.metro.tokyo.lg.jp/
- ナビゲーションのリストの区切りが見た目のみでマークアップ上は区切られていない

## 期待する見せ方・挙動 / Expected Behavior
- 区切りで分かれているところをそれぞれ別のul要素に分割する

## 起こっている問題の再現手段 / Steps to Reproduce
1. デベロッパーツールで要素検証して確認

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
@YusukeHirao おお、全部一つの `ul` 要素になっているということですね！確かに分けたほうがよさそうです。

**Comment by kaizumaki** [comment]
こちらは #6410 といっしょに片付けたほうがよさそうですね。

**Comment by kaizumaki** [comment]
#6410 の区切り見出しとともにテキストを仮でPRを作ってみます。
