### ISSUE TITLE
h2が「新型コロナウイルス感染症対応についてのお願い」であり、内容とズレがある

### ISSUE THREAD

**Issue by k-shirahama** [tokyo-metropolitan-gov/covid19#6407]
## 起こっている問題 / The Problem
- 対象：https://stopcovid19.metro.tokyo.lg.jp/parent/
- h2が「新型コロナウイルス感染症対応についてのお願い」であり、内容（TokyoGlobalStudio、TOKYOおはようスクール、学びの支援サイト、その他）とズレがある

https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html
## 期待する見せ方・挙動 / Expected Behavior
- 見出しと内容が合っていること

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/parent/ を表示する

## 動作環境・ブラウザ / Environment
- 全環境

**Comment by kaizumaki** [comment]
@k-shirahama issueありがとうございます！これは東京都に要確認ですね。修正内容が固まったらコメントします 🙏

**Comment by kaizumaki** [comment]
たいへんお待たせしました。東京都に確認したところ、「お子様をお持ちの皆様へ」へ修正することになりました。
