### ISSUE TITLE
description の文言改善の提案

### ISSUE THREAD

**Issue by ny-a** [tokyo-metropolitan-gov/covid19#641]
## 改善詳細 / Improve details
- 現在 `nuxt.config.ts` 内の description は `当サイトは新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、東京都が開設したものです。` となっていますが、 `東京都より新型コロナウイルス感染症（COVID-19）に関する最新情報を提供しています。` などとした方が自然な文章で分かりやすいのではないでしょうか。  
(`東京都が開設したものです` という表現に違和感を覚えました。)

**Comment by ocean3fish** [comment]
@ny-a ご提案ありがとうございます！
ただ、公式情報としての発信であるため表現の変更には様々な調整が必要となり、時間を要してしまう場合があります。
その点どうぞご了承ください。

**Comment by kaizumaki** [comment]
@ny-a ご提案ありがとうございます。お待たせして申し訳ありません。
こちらのissueについて都に確認いたしました。当サイトは東京都が開設したものであることには間違いではないので、descriptionの変更は行わないこととなりました。ご理解のほどよろしくお願いいたします。

**Comment by ny-a** [comment]
承知いたしました。わざわざ確認いただきありがとうございました。
