### ISSUE TITLE
グローバルナビゲーションの罫線で区切られたまとまりに見出しが必要

### ISSUE THREAD

**Issue by k-shirahama** [tokyo-metropolitan-gov/covid19#6410]
## 起こっている問題 / The Problem
- 対象：全ページ
- グローバルナビゲーションの罫線で区切られたまとまりに見出しが必要

https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html
## 期待する見せ方・挙動 / Expected Behavior
- グローバルナビゲーションの罫線で区切られたまとまりに見出しがあること

## 起こっている問題の再現手段 / Steps to Reproduce
1. 各ページを表示し、グローバルナビゲーションを確認する

## 動作環境・ブラウザ / Environment
- 全環境

**Comment by kaizumaki** [comment]
@k-shirahama なるほどですね！サイドナビのそれぞれのブロックに見出しとなる文言が必要ということですね。これは東京都に確認となりますので、しばしお待ちください 🙏
