### ISSUE TITLE
複数の手段で各ページへたどり着くことができない

### ISSUE THREAD

**Issue by YusukeHirao** [tokyo-metropolitan-gov/covid19#6411]
## 起こっている問題 / The Problem
- 各カードの詳細ページ（ `/cards/` 以下 ）へのリンクがトップページにしか存在しない
  - しかも一部はスクロールして非同期読み込みを完了してからでないとリンクが現れない

## 期待する見せ方・挙動 / Expected Behavior
- 各カードへのリンクを別の場所に用意する
  - ナビゲーションにリンクを追加する
  - もしくはサイトマップページを用意する
  - （もしくは検索システムを導入する）

## 起こっている問題の再現手段 / Steps to Reproduce
1. 全ページのリンクの確認

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
@YusukeHirao おお、確かに、各カードは現状はほぼほぼ直リンクでしか使ってないですね...。サイトマップページを作るのが美しいように思いますが、その際はトップ以外のページ（`parent` や `worker` など）も含めないとですよね。
それと、サイトマップページを用意したときには、どこにそれへのリンクを貼るのがいいのか、アドバイスいただけると嬉しいです！

**Comment by magi1125** [comment]
@kaizumaki サイトマップ、作るならこんな感じでしょうか。

- 都内の最新感染動向（ホーム）
  - （/cards/ 以下を並べる）
- お子様をお持ちの皆様へ
- 企業の皆様・はたらく皆様へ
- 当サイトについて
- お問い合わせ先一覧

**Comment by kaizumaki** [comment]
@magi1125 おお！ありがとうございます！サイトマップはそれでよさそうですね。
「サイトマップ」というリンク項目はサイドナビに置くのがいいでしょうか？一番最後（「東京都公式ホームページ」の次）ですかね。

**Comment by magi1125** [comment]
@kaizumaki そうですね、いったんそこかなと思います。

**Comment by kaizumaki** [comment]
こちら対応します。

**Comment by kaizumaki** [comment]
@forestgtree さんにサイトマップのイメージを作ってもらいました！東京都にも確認してもらいますが、こちらで実装を進めようと思います。

![sitemap](https://user-images.githubusercontent.com/14883063/126925570-d2ee4b53-c5b7-44c1-be8c-1cde398fdf67.png)
