### ISSUE TITLE
readonly属性の矛盾（「陽性者の属性」表のページネーション）

### ISSUE THREAD

**Issue by YusukeHirao** [tokyo-metropolitan-gov/covid19#6412]
## 起こっている問題 / The Problem
- 対象: https://stopcovid19.metro.tokyo.lg.jp/cards/attributes-of-confirmed-cases/
- ページネーションのページ選択のセレクトボックスに潜んでいるinput要素で `readonly=readonly` に対して `aria-readonly=false` となっていて矛盾が発生している

## 期待する見せ方・挙動 / Expected Behavior
-  `readonly` 属性が存在すれば `aria-readonly=true`
-  `readonly` 属性が存在しなければ `aria-readonly=false` もしくは `aria-readonly` なし

## 起こっている問題の再現手段 / Steps to Reproduce
1. デベロッパーツールで要素検証して確認

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by Foo-x** [comment]
対応します。

**Comment by magi1125** [comment]
@YusukeHirao 

> readonly 属性が存在すれば aria-readonly=true

この場合input要素なのでreadonly=readonlyならば暗黙のセマンティクスとなりaria-readonly属性自体不要かも？と思ったのだけどどうでしょう？
https://www.w3.org/TR/html-aria/#docconformance-attr

**Comment by YusukeHirao** [comment]
@magi1125 

そうですそうです。
aria-readonly自体が不要です。
