### ISSUE TITLE
カード内のサマリーの数値と単位がマークアップ的に区別しづらい

### ISSUE THREAD

**Issue by yosukedoke** [tokyo-metropolitan-gov/covid19#6414]
## 起こっている問題 / The Problem
- カード内のサマリーの数値と単位がspanとsmallで装飾目的とマークアップされているようにみえるため不適切と思われる

###  該当ページ（日本語）
- https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases/
- https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-reports-to-tokyo-fever-consultation-center/
- https://stopcovid19.metro.tokyo.lg.jp/cards/attributes-of-confirmed-cases/
- https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-number-of-reports-to-covid19-consultation-desk/
- https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-reports-to-covid19-telephone-advisory-center/
- https://stopcovid19.metro.tokyo.lg.jp/cards/variant/
- https://stopcovid19.metro.tokyo.lg.jp/cards/deaths-by-death-date/
- https://stopcovid19.metro.tokyo.lg.jp/cards/positive-number-by-diagnosed-date/
- https://stopcovid19.metro.tokyo.lg.jp/cards/positive-number-by-developed-date/

## 期待する見せ方・挙動 / Expected Behavior
- 数字を主張するのであれば数字部分をstrongにするなどする。

※ 課題としては、全体的にこのコンテンツを読み上げ等するにあたって、視覚的な表現はさておき、見出し以下どういった重み付けで伝わるべきか整理した上でマークアップに反映したほうが良さそう。

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザのデベロッパーツールでマークアップを確認する

## 動作環境・ブラウザ / Environment
- すべての環境

**Comment by kaizumaki** [comment]
@yosukedoke 確かにおっしゃる通りで、
> 見出し以下どういった重み付けで伝わるべきか整理した上でマークアップに反映したほうが良さそう。

これはぜひ整理したいですね。

どなたかマークアップの素案を作ってくださると、検討する上でもとても助かるのですが、いかがでしょう...？

**Comment by Meiryo7743** [comment]
当該箇所の実装元はこちらで正しいでしょうか？

てっきり（適切ではありませんが）文字サイズの調整を目的に `<small>` を用いたのかと思いきや，タグに適用されている class の CSS で `font-size` は調整されており，`<small>` を用いた意図をはかりかねました……。上記で仰っているように適切なマークアップに変更するか，あるいは `<span>` に置き換えても良いように見えます。

https://github.com/tokyo-metropolitan-gov/covid19/blob/d8bd9d6e2735449d25fbd88318aaa59fe0a931d7/components/index/_shared/DataViewDataSetPanel.vue#L5-L16

https://github.com/tokyo-metropolitan-gov/covid19/blob/d8bd9d6e2735449d25fbd88318aaa59fe0a931d7/components/index/_shared/DataViewDataSetPanel.vue#L54-L103

**Comment by magi1125** [comment]
ちなみに、small要素についてはHTML仕様の例を参考にしたのかなと思いつつ（数字の注釈に使っているのは例に沿っている）、単位にも使っているのは適切ではなさそうと思います。
https://momdo.github.io/html/text-level-semantics.html#the-small-element

**Comment by yosukedoke** [comment]
@kaizumaki 遅くなりましたが、こちらは例えば読み上げにおいては単位と数字を区別する必要性は無いと思います。
視覚的に強調しているようにも見えましたが、あくまで見出しに対する指標の数値がわかれば良いのではないでしょうか。
（コンテンツ提供者側の意図がそうであればという仮定の話なのでマークアップを論拠に決定することはできませんが）

```
新型コロナコールセンター相談件数
403 件
2021年7月11日 実績値（前日比: -99 件）
```

シンプルに捉えると、見出し、テキスト、テキストという構造だと思います。
特段数字を強調するなら数値を emないしstrongでマークアップするのはアリだと思います。
また2021年〜のところが表示と同じように `small` で弱めの情報であればアクセシビリティー的には大きな差異がなく伝わると思います。

どれが正解なのかはコンテンツオーナー側の意図に依存するため、それをご確認の上で上記の考え方において整理いただくのが良いと思います。
というわけで別段意味的に強調する意図がなく視覚的にのみ装飾を与えるのであれば `span` でいいのではないでしょうか。

**Comment by kaizumaki** [comment]
@yosukedoke フォローありがとうございます！
> あくまで見出しに対する指標の数値がわかれば良いのではないでしょうか。

言われてみれば、確かにこれはおっしゃる通りです。なので、
> 視覚的にのみ装飾を与えるのであれば `span` でいいのではないでしょうか。

ご指摘の通りでよいように思いました。
数字と単位は区別するものではなく、シンプルにテキストです。
そして `small` の箇所についてはこちらもシンプルにテキストなので `span` の方が適切かもしれません。

**Comment by kaizumaki** [comment]
#6415 と一緒に対応します。
