### ISSUE TITLE
Jestの設定ファイルをTS化

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#6460]
## 改善詳細 / Details of Improvement
- Jestの設定ファイル（ `jest.config.js` ）をTS化（ `jest.config.ts` ）

## 期待する見せ方・挙動 / Expected behavior
- Jestの設定が `jest.config.ts` に記載されている

## 参考リンク
- [Configuring Jest · Jest](https://jestjs.io/ja/docs/configuration)

**Comment by munierujp** [comment]
やります🙋‍♂️

**Comment by Foo-x** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/5237 でJestを依存から削除したので、そもそも設定ファイルが不要かもしれないですね。

**Comment by kaizumaki** [comment]
@munierujp さん、issueありがとうございます！ @Foo-x さん、フォローありがとうございます！
ご指摘のとおり、テストに関わるpackageをいったん削除としたので、設定ファイルも不要なのですよね（package整理をしたときにいっしょに削除すべきでした）。
もし、Jestの導入に本腰を入れるとなれば話は変わってきますが、当面はないかなあと思うところです。

**Comment by munierujp** [comment]
>#5237 でJestを依存から削除したので、そもそも設定ファイルが不要かもしれないですね。

そうだったのですね。
それでは、このイシューはcloseして、`jest.config.js`を削除するイシューを立てます。
