### ISSUE TITLE
devcontainer.jsonのappPortを削除する

### ISSUE THREAD

**Issue by Foo-x** [tokyo-metropolitan-gov/covid19#6466]
## 改善詳細 / Details of Improvement
- .devcontainer/devcontainer.jsonのappPortを削除する

## 期待する見せ方・挙動 / Expected behavior
- .devcontainer/devcontainer.jsonのappPortが削除されている

---

appPortに関する説明は以下。
https://code.visualstudio.com/docs/remote/containers#_publishing-a-port

appPortはdocker-composeを使わずに起動したコンテナのポートを公開する設定であり、すでにdocker-compose.ymlが用意されているので不要かと思います。
設定を削除してもブラウザからlocalhost:3000でアクセスできることを確認済みです。
また、VSCode上では警告が出ます。
![image](https://user-images.githubusercontent.com/24248467/123022468-d0a56e80-d410-11eb-83c6-8d01293260a1.png)

なお、docker-composeを使用しない場合でもappPortではなくforwardPortsのほうが良いかと思います。
appPortはポートの変更時にコンテナを作り直す必要がありますが、forwardPortsはVSCodeのReload Windowで反映されます。
devcontainer.jsonのリファレンスではforwardPortsの使用が推奨されています。
https://code.visualstudio.com/docs/remote/devcontainerjson-reference
> In most cases, we recommend using the new forwardPorts property.

また、VSCodeのコマンドパレットで`Remote-Containers: Add Development Container Configuration Files...`から雛形のdevcontainer.jsonを作成できますが、forwardPortsのみが用意されています。
![image](https://user-images.githubusercontent.com/24248467/123022924-7d7feb80-d411-11eb-9ff3-adad123c5e7b.png)

**Comment by kaizumaki** [comment]
@Foo-x issueありがとうございます！私が普段dockerとVSCodeを使わないので、ご指摘の部分は気づきませんでした。ありがとうございます 🙏
