### ISSUE TITLE
Replace @nuxtjs/google-analytics

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#6483]
## 改善詳細 / Details of Improvement
- 最近、`yarn install` をすると下のスクショのようなメッセージが現れます（グリーンマーカー部分）
- どうやら、`@nuxtjs/google-analytics` が `deprecated` とのことです。ほんまかいな
- とりあえず、実験的に、レコメンを真に受けた改修を試してみます
- テスト方法につき、案をいただけますと幸いです（私は `Google API` の仕組みをよく知らないため）

## スクリーンショット / Screenshot

![スクリーンショット 2021-06-27 060618](https://user-images.githubusercontent.com/10361533/123530017-f3959280-d730-11eb-8e80-d1b7a3e0dbd6.png)

## 期待する見せ方・挙動 / Expected behavior
- 上記 `yarn install` 時のエラーが解消すること
- Google API へこれまでと同様のデータが POST されること
- UI 側のルック＆フィールに変更がないこと
- コードの上では、`require()` などの obsolete な機能を使用しないこと

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster フォローありがとうございます！これはどうやら `@nuxtjs/google-analytics` が依存している [vue-analytics](https://github.com/MatteoGabriele/vue-analytics) がメンテを終えたということみたいですね。
当サイトにはすでにGoogleタグマネージャーを扱う `@nuxtjs/gtm` が入っているので、GAもそちらに切り替えたほうがいいのかもしれないですね。

**Comment by mcdmaster** [comment]
@kaizumaki なるほどです。
では、後で時間ができたら `@nuxtjs/gtm` で PR 立ててみますね

**Comment by kaizumaki** [comment]
こちらですが、たぶんですね、Google AnalyticsのV3を使っている限りは問題ない（というか、なんとかしのげる）ような気がします。GAをV4に移行するとなったら対応が必要になるのではないかと思っています（[参照](https://github.com/nuxt-community/google-analytics-module#readme)）。
GA4への移行は簡単ではないですからね...。東京都からの要望がない限り、当面は現状維持のような気がしています。

**Comment by mcdmaster** [comment]
りょうかいです。特に異存はありません。

余談ですけれども、アップグレードと言えば `vue3` とか `webpack5` とか `chart,js3` とか `nuxt3` とか…どれも、ぜんぜん簡単ではないです(嘆

**Comment by kaizumaki** [comment]
GTMを東京都に移管しまして、東京都側でGA4を設定したとの連絡を受けましたので、一旦こちらのissueはクローズとします。
`@nuxtjs/google-analytics` はタイミングを見て別途削除とします。
