### ISSUE TITLE
「検査陽性者の状況」に「療養者数」を追加

### ISSUE THREAD

**Issue by takainou** [tokyo-metropolitan-gov/covid19#6520]
## 改善詳細 / Details of Improvement
- 現時点で都が管理している人数を把握する為、「検査陽性者の状況」に、以下の数式で算出される療養者数を表示してはどうでしょうか
- 療養者数＝陽性者数 (累計)ー死亡ー退院等（療養期間経過を含む）
　または
療養者数＝入院＋宿泊療養＋自宅療養＋入院・療養等調整中
- 対策サイトにイメージ貼り付けてリンクされているモニタリング会議資料
「【医療提供体制】⑥-3 検査陽性者の療養状況」
の積み上げグラフ最上部が、療養者数の推移、吹き出し数値が療養者数です。次のグラフ
「【医療提供体制】⑥-4 検査陽性者の療養状況別割合」
では、黒の折れ線で、療養者数の推移が記載されております
- 厚労省サイトでは、同定義の項目「入院治療等を要する者」「療養者数」が掲載されております
- 大阪府や愛知県の対策サイトでは、同定義の項目「現在陽性者数」が表示されております

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/63571899/125950693-ef5cff9d-f02d-4ff5-9046-823ca90a90ce.png)
![image](https://user-images.githubusercontent.com/63571899/125950789-d048a724-ee40-42d9-9a93-1c8a1d4ca6f3.png)
![image](https://user-images.githubusercontent.com/63571899/125950813-f0c5d504-ac6e-4c13-beb8-81cc0549f9b3.png)
![image](https://user-images.githubusercontent.com/63571899/125951276-1fc2d481-4fed-4119-b68b-23a5d9e51a76.png)
![image](https://user-images.githubusercontent.com/63571899/125951323-b111ed25-9c03-4299-97a8-e26b7e0fff42.png)

## 期待する見せ方・挙動 / Expected behavior
- 大阪府や愛知県の対策サイト同様に、「陽性者数（累計）」の下に一行追加し、「入院」「宿泊療養」「自宅療養」「入院・療養等調整中」が内訳となるよう表記するのが良いと考えます
- 「療養者数」が文字数含め適切と考えますが、都関係者の方が分かりやすい文言とするのが良いと考えます

**Comment by kaizumaki** [comment]
@takainou ご提案ありがとうございます！なるほど、大阪府や愛知県では「現在陽性者数」として出しているのですね。
東京都に確認しますので、しばらくお待ちいただければと思います。

**Comment by takainou** [comment]
愛知県は、先行した大阪府を参考にしております。「現在陽性者数」ですと、陰性確認無しでも療養解除されますので、正確な表現では無い気もしまして、厚労省の「入院治療等を要する者」は少し長いと考え、厚労省の「療養者数」を提案させて頂きました。

お手数ですが、東京都への確認よろしくお願いします。

**Comment by takainou** [comment]
東京都福祉保健局HPの[新型コロナウイルス感染症の療養者の状況](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/info/ryoyosha.html)に以下が掲載されてました。こちらでは「療養者数」とされています。
確保病床数(軽症・中等症、重症)と受入可能室数(宿泊療養)も記載されていますね。対策サイトでは「モニタリング項目」「医療提供体制」「受入体制」に確保病床数(入院、重症)の記載はある(受入可能室数(宿泊療養)は無い)ので、重複となりますが、療養者の状況と合わせて「検査陽性者の状況」に確保病床数(入院、重症)と受入可能室数(宿泊療養)も追加掲載しても良いかもしれません。
![image](https://user-images.githubusercontent.com/63571899/126648637-f0ce70e1-b2f1-4674-9528-ae0f61fdc23e.png)
![image](https://user-images.githubusercontent.com/63571899/126649796-eb3737ea-549e-4d0c-a09b-21e0e8011630.png)

**Comment by kaizumaki** [comment]
だいぶお待たせしてしまい申し訳ありません。
以下、東京都から回答がありました。これをもってこちらのissueはクローズしたく思います。

> 御意見いただきありがとうございます。
> 療養者数につきましては、[東京都福祉保健局HP](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/info/ryoyosha.html)にて、
> 日々都民等への情報提供を行っているところです。
> 現段階では「検査陽性者の状況」への追加は予定しておりません。
> 大変申し訳ございませんが、御了承いただけますと幸いです。
