### ISSUE TITLE
最新のお知らせの「変異株情報」の外部リンクURL変更

### ISSUE THREAD

**Issue by ytkg** [tokyo-metropolitan-gov/covid19#6540]
## 改善詳細 / Details of Improvement
- 最新のお知らせの「変異株情報」の外部リンクURLが変わっています

変更前: https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/screening.html  
変更後: https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/henikabu/screening.html

今の所、リダイレクトされているので問題ないですが。

![image](https://user-images.githubusercontent.com/12048864/126879462-4af1aed4-2740-4fe1-9863-ce06f62d99d3.png)

## 期待する見せ方・挙動 / Expected behavior
- 直接 https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/henikabu/screening.html にアクセス

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by kaizumaki** [comment]
@ytkg ご指摘ありがとうございます！これは修正したほうがよさそうですね。
