### ISSUE TITLE
LINEのブランドアイコンを差し替える

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6545]
## 改善詳細 / Details of Improvement
- LINEのアイコンカラーがリニューアルしたので、当サイトのサイドナビ及びグラフカードシェア用UIに載せているLINEアイコン画像を差し替えたいです。
- 参考　https://line.me/ja/logo

## スクリーンショット / Screenshot

現状↓

![スクリーンショット 2021-07-26 11 58 48](https://user-images.githubusercontent.com/14883063/126927151-abf4905a-df89-48fa-b5f7-10ae3ae08c6d.png)

## 期待する見せ方・挙動 / Expected behavior
- LINEアイコンのカラーが現在のブランドカラーになっている

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by knknk98** [comment]
初めまして！
対応できそうなのでやらせていただきたいです！

**Comment by kaizumaki** [comment]
@knknk98 ありがとうございます！ぜひお願いします！
