### ISSUE TITLE
英語の月の表記を短縮形にする

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6559]
## 改善詳細 / Details of Improvement
- #6393 で月の表記をフル表記にしましたが、８月に短縮形に戻します
- https://github.com/tokyo-metropolitan-gov/covid19/pull/6418/commits/310de0223c09885daa21197db88f260bb3497328 のコミットを巻き戻す形です

## 期待する見せ方・挙動 / Expected behavior
- 英語ページを表示時に、月の表記が短縮形になる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by knknk98** [comment]
こちらできそうなのでやらせていただきたいです！

**Comment by kaizumaki** [comment]
@knknk98 ありがとうございます！ぜひぜひお願いします！
