### ISSUE TITLE
宿泊療養・自宅療養者数をモニタリング項目に追加したい

### ISSUE THREAD

**Issue by whisky-shusuky** [tokyo-metropolitan-gov/covid19#6565]
## 改善詳細 / Details of Improvement
- 表題の通り宿泊療養・自宅療養者数をグラフにして可視化することを提案いたします。
  - 理由
    - 現状デルタ株による感染者数の増加により医療リソースが圧迫されている状況であり、今後入院したくてもできない患者が増加することが予想されます。
    - そのため、現在本サイトでは入院患者数をモニタリング項目にしていますが医療リソースの限界まで達した場合それ以上入院患者数が増えず、一見したところ問題ないかのようにみえてしまう恐れがあると推測しました。
    - そのため医療リソースの圧迫具合の深刻さを周知するためグラフで可視化するべきだと思います。
    - スクリーンショットで`static/data/130001_tokyo_covid19_details_testing_positive_cases.csv`のデータから作ったグラフを貼りましたが、現状だけでも増加傾向にあることが確認できます。

## スクリーンショット / Screenshot
<img width="594" alt="スクリーンショット 2021-08-01 9 05 26" src="https://user-images.githubusercontent.com/20264602/127755179-59707646-56ff-4a4a-bd09-a07c8d2537e5.png">

## 期待する見せ方・挙動 / Expected behavior
- 宿泊療養・自宅療養者数がモニタリング項目にされる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@whisky-shusuky ご提案ありがとうございます！モニタリング項目については、当サイトにグラフを載せるだけではなく東京都のモニタリング会議で指標に加えてもらう必要があります。それだとちょっと遠回りになりそうな気がします。
あるいはモニタリング項目ではなく「その他 参考指標」としてグラフを掲載するという方法はあるかもしれません。
東京都に確認しますので、しばらくお待ちください。

**Comment by shuuji3** [comment]
上記のCSVのデータ ([covid19/130001_tokyo_covid19_details_testing_positive_cases.cs](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/static/data/130001_tokyo_covid19_details_testing_positive_cases.csv)) を使って積み上げグラフを作ってみました。

<img width="1234" alt="Screen Shot 2021-08-12 at 20 17 26" src="https://user-images.githubusercontent.com/1425259/129188127-53527b5e-63d1-4a26-85af-a4379c697c25.png">

(Google Sheets: https://docs.google.com/spreadsheets/d/1NVngeYAbgiI_HdIB2sEc631o8Mv4SVSLxhXH_oNSWH4/edit?usp=sharing)

「陽性者」の中には、入院中、宿泊療養、自宅療養、調整中なども含まれるので、それらもあらせてプロットしたほうが全体的な状況が分かりやすくなるかもしれません。

**Comment by kaizumaki** [comment]
たいへん遅くなりました。申し訳ありません。
以下、東京都から回答がありました。たいへん恐縮ですが、これをもってこちらのissueはクローズとさせてください。

> 御意見いただきありがとうございます。
> 宿泊療養・自宅療養者数の推移につきましては、週１回のモニタリング会議により、
> 都民等への情報提供を行っているところです。
> 現段階では対策サイトへの掲載は予定しておりません。
> 大変申し訳ございませんが、御了承いただけますと幸いです。
