### ISSUE TITLE
nuxt-i18n から @nuxtjs/i18n へのリプレース

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#6575]
## 改善詳細 / Details of Improvement
- 国際化モジュール `nuxt-i18n` のページでは、もはや従来の `nuxt-i18n` モジュールは「[レガシ]([url](https://i18n-legacy.nuxtjs.org/))」とされています
https://i18n.nuxtjs.org/
- どうやら、今後は `@nuxtjs/i18n` を使用することがレコメンドされているようです
- そして遠からず、`@nuxtjs/i18n` がスタンダードとなるのはほぼ間違いないでしょう

## スクリーンショット / Screenshot

(PR で載せます)

## 期待する見せ方・挙動 / Expected behavior
- `nuxt-18n` の機能を、`@nuxtjs/i18n` に完全に載せ替える。バックアウトはしない
- `nuxt-i18n` のときと比べ、ルック＆フィールが**一切変わらない**こと
- `nuxt-i18n` のときと比べ、開発手法や API の仕組みなどが**ほとんど変わらず**、余計な工数を創らないこと

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@mcdmaster おお、そうなんですね。フォローとPRありがとうございます！検証してみますね。
