### ISSUE TITLE
[/flowページ] コンポーネントコーディング

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#659]
## [/flowページ] コンポーネントコーディング
https://stopcovid19.metro.tokyo.lg.jp/flow

（作成をお願いしたいコンポーネントについては別途issueをご参照ください。）

多言語化に向けて、/flowページ（「新型コロナウイルス感染症が心配なときに」ページ）のコーディングをお願いします。１枚画像の現状を脱したいです。

### コーディングの指針
- レスポンシブである（ただしデスクトップサイズ用とモバイルサイズ用があり（breakpointは450px）、それぞれ別コンポーネントとなります）
- 多言語化を意識する（特に英語はテキストが長くなるので考慮してください）

### ポイント
- 作成してもらったコンポーネントはあとで合体します。なので、コンポーネントファイルは `/flow`のページに組み込まない状態でプルリクしてください（ `/pages/flow.vue` には組み込まない）。作成中に一時的にflow.vueに読み込ませるのはかまいません。
- コンポーネントファイルは `/components/flow` の下に置いてください。
- 必要そうな画像は `/static/flow` にあります。なかったら各issue内でコメントください。
- sassの変数とmixinが `/assets/variables.scss` にあります。適宜利用してください。
- **css modulesを導入します** [詳しくはこちら](https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596044836)

### [flowページで使用しているcolor]
- $green-1 (#00A040)
- $gray-2 (#4D4D4D)
- 黄色：#FFE200
- 相談窓口エリア内背景：$gray-5 (#F8F9FA)
- 相談窓口エリア内ボーダー：$gray-4 (#D9D9D9)

その他、疑問点があればお気軽に各issue内でコメントしてください！

### 3/8追記
今後の作業は、 `feature/flow/development` ブランチで行うこととします。

**Comment by kaizumaki** [comment]
デスクトップ版の指示書はこちら
![pc_flowimg](https://user-images.githubusercontent.com/14883063/76134944-d9303500-6065-11ea-9389-fcc71bfbb981.png)

**Comment by kaizumaki** [comment]
モバイル版の指示書はこちら
![sp_flowimg](https://user-images.githubusercontent.com/14883063/76134959-f06f2280-6065-11ea-8619-3a5a67dd5204.png)

**Comment by harukakawanaka** [comment]
### 前提
- ウェブサイトのUIメンテナンス寿命はコロナウィルス流行対策期間中(長くても１年程度)
- コロナウィルス流行対策が収束すればWebサイトのコンポーネントレベルでのメンテナンスが行われないこと

### 提案内容
UI改善の長期運用を想定しないため、ページ間の共通部品を作るメリットが薄いので
各ページでCSSクラスを独立して運用することができるCSSモジュールを提案します。
https://vue-loader-v14.vuejs.org/ja/features/css-modules.html

メリット: １つのvueファイルで独立したCSSクラスを持てる(他のvueファイルと被っても問題ないらしい)
デメリット: 共通CSSクラス管理するときに独立したCSSクラスが影響して共通CSSクラスが適用されない（抜け道）がある

### 注意点
 CSSクラスをマークアップするときの記法が通常のCSSクラスを書くときと異なる
`:class="$style.red"`

**Comment by harukakawanaka** [comment]
```
<div :class="$style.Flow">
 // 描画される
  <div :class="$style.FlowHeading"></div>
 // 描画されない(´；ω；｀)
  <div :class="$style.Flow-Card"></div>
</div>

<style module lang="scss">
.Flow {
  margin-bottom: 20px;
  &Heading {…}
  &-Card { … }
}
</style>
```

**Comment by harukakawanaka** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/668
SPの１つ目とりかかってみます

**Comment by sushi-udon** [comment]
#667に、取り掛かってみます。

**Comment by matoruru** [comment]
#671 にとりかかってみます。

**Comment by Nyoho** [comment]
#662 をやっているNyohoです。紫枠をやっています。
この、紫枠の右側にかかっている黄色い矢印 (flow_arrow.svg) はコンポーネントに含めなくていいんでしょうか?/含めた方がいいのでしょうか?

**Comment by kaizumaki** [comment]
@Nyoho 右側のはみ出ている矢印は実装しなくてOKです！

**Comment by Nyoho** [comment]
@kaizumaki 了解です!

**Comment by amotarao** [comment]
<img width="326" alt="スクリーンショット 2020-03-07 19 10 55" src="https://user-images.githubusercontent.com/8909592/76141518-83c94780-60a8-11ea-9600-a1cc00aebdd7.png">
<img width="326" alt="スクリーンショット 2020-03-07 19 10 58" src="https://user-images.githubusercontent.com/8909592/76141519-85930b00-60a8-11ea-8398-03a1b961e1a1.png">

モバイル版のこの2ボタンに関しては共通部品にしたほうがいいのではないかと感じました
対象: #668 #669 #670 #671 

また、 #668 については #738 にて対応がされていましたが、
矢印パーツとボタン色のカラーコードが欲しいそうです。

#668 以外でも同じ要望があると思うので、今から共通にする判断をしても遅くない気がしています。

**Comment by kaizumaki** [comment]
@amotarao おおー、ご指摘ありがとうございます！すっかり失念していました。
@harukakawanaka 
黄色のカラーコードはこのissue(#659)の冒頭に入れました。
透過矢印の画像はいまからアップします。

**Comment by kaizumaki** [comment]
@amotarao コンポーネントの共通化については改めてissueたてることにします。アドバイスありがとうございます！

**Comment by emuemuemuemu** [comment]
コンポーネント化するということで、storybook の導入が浮かんだのですが、いかがでしょうか？

**Comment by sushi-udon** [comment]
コンポーネント化するということで、storybook の導入が浮かんだのですが、いかがでしょうか？

**Comment by kaizumaki** [comment]
@sushi-udon お、いいですね！スタイルガイド的なものは欲しいなと思っていたんです。できますでしょうか？やってもらえるなら別issueを立ててもらってもいいでしょうか？

**Comment by emuemuemuemu** [comment]
@kaizumaki 
承知いたしました！別issue をたてます。
ありがとうございます！

**Comment by sushi-udon** [comment]
@kaizumaki
承知いたしました！別issue をたてます。
ありがとうございます！

**Comment by Shagamii** [comment]
モバイルの /flow において電話番号がタップ可能であることがユーザーに認知されないのではないかという意見 https://github.com/tokyo-metropolitan-gov/covid19/issues/553  を出しており、また、このissueにおいて画像ベースのものを脱したいとのことですが、 https://github.com/tokyo-metropolitan-gov/covid19/pull/736/ では、電話番号は画像のままのようです。
/flowの各電話番号を画像からテキストにすることでanchorのスタイルがあてられるのでになるのでユーザーにタップ可能であることが分かりやすくなるのではないかと思っているのですが、いかがでしょうか？

**Comment by Nyoho** [comment]
今デスクトップの #662 をやっていて、電話番号は tel:***** にしていてMacからだとiPhoneが近くにあれば電話が掛けられますが、確かに元画像をまねして作ったら全然クリッカブルなのがわからない感じになってしまいました。 #748

**Comment by kaizumaki** [comment]
@Shagamii おお、おっしゃるとおり。私の意図が伝わっていなかったようです。もちろんテキストにしたいです。お知らせいただきありがとうございます！

**Comment by sushi-udon** [comment]
お伺いしたいことがございます！

```
黄色：#FFE200
相談窓口エリア内背景：#F2F2F2
相談窓口エリア内ボーダー：#D9D9D9 
```

なのですが、 `/assets/variables.scss` に共通変数として設定したいと思ったのですが
自分の方で設定しても構わないのでしょうか？

**Comment by kaizumaki** [comment]
@sushi-udon そこは私も迷ったのですが、flowのページのみなので躊躇していました。
@forestgtree さんはどう思いますか？

**Comment by forestgtree** [comment]
ご対応いただき、ありがとうございます！

相談窓口エリア内背景は、 $gray-5　とほぼ近しい色味ですので置き換えてください。

相談窓口エリア内ボーダーは、　$gray-4　と同色ですので変数にしてください。
ご指示ミスでした、ご面倒おかけいたしました。

黄色：#FFE200　についてだけは、まだ変数を増やす予定などもあり
まだ変数を決定できないため、カラーコードのまま記述しておいていただけると助かります。

**Comment by emuemuemuemu** [comment]
@forestgtree  @kaizumaki 
承知いたしました！
ありがとうございます！

**Comment by sushi-udon** [comment]
@forestgtree @kaizumaki  
承知いたしました！  
ありがとうございます！
