### ISSUE TITLE
「モニタリング項目」のカードに「病床利用率」の割合を追加する

### ISSUE THREAD

**Issue by shuuji3** [tokyo-metropolitan-gov/covid19#6594]
## 改善詳細 / Details of Improvement
「モニタリング項目」のカードに「病床利用率」の割合を追加する。

## スクリーンショット / Screenshot

<img width="471" alt="Screen Shot 2021-08-11 at 19 47 25" src="https://user-images.githubusercontent.com/1425259/129016568-9bf6580a-3f0f-43b2-a3a1-619646a86e4f.png">

## 期待する見せ方・挙動 / Expected behavior
「(6)入院患者数」と「(7)重症患者数」のそれぞれの人数の確保病床数に対する割合を求めて、パーセンタイルで表示して、現在の状況を理解しやすくしたいです。たとえば、「(6)入院患者数」が100人で「確保病床」が5000床の場合、100/5000を計算して「2%」という値を表示します。

**参考資料**
[新型コロナウイルス感染症の重症者・病床について　東京都福祉保健局](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/info/zyuusyoubyousyou.html)

## 動作環境・ブラウザ / Environment
N/A

**Comment by shuuji3** [comment]
PR #6595 に提案する変更と変更後のスクリーンショットを載せました。

**Comment by kaizumaki** [comment]
@shuuji3 ご提案ありがとうございます！東京都に確認が必要になりますので、しばらくお待ちいただけると幸いです。

**Comment by shuuji3** [comment]
わかりました！ よろしくお願いします:pray:

**Comment by kaizumaki** [comment]
上記のコメントにより、こちらのissueはクローズさせていただきますね。
