### ISSUE TITLE
「まずは電話相談をどうぞ」のメッセージのローカライズが正しく表示されない

### ISSUE THREAD

**Issue by shuuji3** [tokyo-metropolitan-gov/covid19#6597]
## 起こっている問題 / The Problem
- トップページにある「自分や家族の症状に不安や心配があれば まずは電話相談をどうぞ」というメッセージが英語ではローカライズ済みであるにもかかわらず、日本語のテキストが表示されている。

## スクリーンショット / Screenshot

<img width="1015" alt="Screen Shot 2021-08-12 at 19 33 38" src="https://user-images.githubusercontent.com/1425259/129183211-980b085c-bed7-4906-a74d-fedf8c3efc35.png">

## 期待する見せ方・挙動 / Expected Behavior
- ローカライズされたテキストが表示される。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 英語版ページ https://stopcovid19.metro.tokyo.lg.jp/en にアクセスする。
2. 上のスクリーンショットの部分を見る。

## 動作環境・ブラウザ / Environment
N/A

## その他

- テキストは「[Search · 自分や家族の症状に不安や心配があれば](https://github.com/tokyo-metropolitan-gov/covid19/search?q=%E8%87%AA%E5%88%86%E3%82%84%E5%AE%B6%E6%97%8F%E3%81%AE%E7%97%87%E7%8A%B6%E3%81%AB%E4%B8%8D%E5%AE%89%E3%82%84%E5%BF%83%E9%85%8D%E3%81%8C%E3%81%82%E3%82%8C%E3%81%B0)」の4箇所に存在するようです。
- `en.json` の以下の部分が該当するテキストのローカライズです。

https://github.com/tokyo-metropolitan-gov/covid19/blob/18e214b2e63892cf807f3c12c49f876874e76489/assets/locales/en.json#L736

- ローカルの環境で、このテキストの`\\n`を`\n`変更してみたところ、期待通りの結果が表示されました。

**diff**
```diff
-  "自分や家族の症状に不安や心配があれば\\nまずは電話相談をどうぞ": "Consult over the phone first\\nif you have any concerns",
+  "自分や家族の症状に不安や心配があれば\nまずは電話相談をどうぞ": "Consult over the phone first\nif you have any concerns",
```

<img width="447" alt="Screen Shot 2021-08-12 at 19 32 56" src="https://user-images.githubusercontent.com/1425259/129184126-e6082978-90c3-4beb-b0eb-8ec11db529b1.png">

**Comment by kaizumaki** [comment]
@shuuji3 フォローありがとうございます！そうなんですよね、こちらの改行処理を放置してしまっていました。
実は近日中にここのブロックは別のコンテンツに入れ替えになる予定でして、もう少ししたらissueを立てるつもりでした。なので、こちらの修正作業は不要となります。せっかくご提案いただいたのにすみません 🙇‍♀️ 
コンテンツ入れ替えの際は、改行を入れないようにしますね。

**Comment by shuuji3** [comment]
@kaizumaki なるほど、把握されていたのであれば大丈夫です。確認ありがとうございます！
