### ISSUE TITLE
カードが1枚だけ表示されるページでカードの幅を広げる

### ISSUE THREAD

**Issue by shuuji3** [tokyo-metropolitan-gov/covid19#6598]
## 改善詳細 / Details of Improvement
- カードが1枚だけ表示されるページ (例: モニタリング項目(1)新規陽性者数 -https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-number-of-confirmed-cases) のグラフを幅を広げる。
  - 現在のカードの幅はカードを横に2枚並べることを想定しているため、カードが1枚だけ表示されるページでは余白が無駄になってしまっています。
  - 幅を広げることでグラフに表示される範囲が広がるため、より長期的な変化を把握しやすくなります。

## スクリーンショット / Screenshot

<img width="1255" alt="Screen Shot 2021-08-12 at 1 21 03 copy" src="https://user-images.githubusercontent.com/1425259/129185846-6800e908-e2ab-4223-9118-bcb4eb8faa4f.png">

## 期待する見せ方・挙動 / Expected behavior
- カードが1枚だけ表示されるページでのみ、カードの幅を2倍にする。

<img width="1252" alt="Screen Shot 2021-08-12 at 1 21 03 copy 2" src="https://user-images.githubusercontent.com/1425259/129185854-f7217f8f-e077-4757-ad71-e26032fb507e.png">

## 動作環境・ブラウザ / Environment
- デスクトップPCやタブレットなど、広い画面を持つ端末

**Comment by shuuji3** [comment]
上のようなグラフを表示する変更 (PR #6599) を実装してみました。どうでしょうか？

**Comment by kaizumaki** [comment]
@shuuji3 ご提案ありがとうございます！個人的にはグラフの部分が見やすくなって良いなと思いました。気になるところとしたらタイトル部の指標名と数値が離れてしまうことと、注釈が若干読みにくくなることでしょうか。そのあたり東京都の担当にも確認してもらいますので、しばらくお待ちいただければと思います。
