### ISSUE TITLE
Sharepoint 同期対応

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#66]
@mikkame さん、タスク立てときました。

Sharepoint のデータの更新日について

個別のExcelに、下記のように更新日をつけてもらっています。このセルに フィールド名 を定義しておけば、そのデータを参照することはできますか？
https://codeforjapan.sharepoint.com/:x:/r/sites/covid19/_layouts/15/Doc.aspx?sourcedoc=%7B3AA13B37-447A-4793-A150-56AB77AC7EE2%7D&file=%E3%82%B3%E3%83%BC%E3%83%AB%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC%E7%9B%B8%E8%AB%87%E4%BB%B6%E6%95%B0-RAW.xlsx&action=default&mobileredirect=true&cid=64d0c05e-0380-4cf8-ad2e-337ac2b958a1

また、データ一覧も作ってもらいました。こちらの更新日を見る方法でも良さそう。（上記の個別のフィールドにセル参照入れるらしいです。）
https://codeforjapan.sharepoint.com/:x:/r/sites/covid19/_layouts/15/Doc.aspx?sourcedoc=%7B0FC0DD30-A423-421C-B6A3-4D7CB7941B13%7D&file=DataList.xlsx&action=default&mobileredirect=true

**Comment by mikkame** [comment]
> 個別のExcelに、下記のように更新日をつけてもらっています。このセルに フィールド名 を定義しておけば、そのデータを参照することはできますか？

できます。
G1:H100までメタ領域として使う、みたいな形にすればフロントだけの編集で追加データを送ることもできると思われます。

> また、データ一覧も作ってもらいました。こちらの更新日を見る方法でも良さそう

参照している場合にDLしたエクセルからうまく拾えるかが要検証なので
前者の方が今の所安全度が高い様に思えます

**Comment by halsk** [comment]
なるほど。では前者で行きましょう！

**Comment by halsk** [comment]
これは終わったんでしたっけ？

**Comment by mikkame** [comment]
すみません、まだです
もう先が見えている感じです。
いつまでに必要ですか？

**Comment by mikkame** [comment]
とりあえず #104 の退院者数データがボトルネックになりそうなのでそれ解消してからこれをやる予定です

**Comment by halsk** [comment]
いえ、急いでません！ IMPORTANT ラベルのほうが優先度高いです。
ただ、クローズして良いか確認してみただけですー

**Comment by mikkame** [comment]
進捗
技術的問題はすでに解消している状態なのであとはやるだけという状態

とりあえずしばらく私が毎日いるっぽいので
夜にバッチ手動→PR作成しておき、朝だれからにマージしてもらう流れで運用？

**Comment by halsk** [comment]
例えば18時に取り込んで、ステージングで確認してもらうような運用はできますか？

**Comment by mikkame** [comment]
大丈夫かと思います。
本日18時ちょうどにいれるか微妙ですので少し遅れるかもしれません
