### ISSUE TITLE
[/flow] コンポーネントコーディング デスクトップ版 FlowPcPast.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#660]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035047
↑の上のブロックの赤枠部分「発症前２週間以内」

ファイル名は `FlowPcPast.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by shgtkshruch** [comment]
#659 読みました。
こちらまだ未着手でしたら対応させていただきたいです！

**Comment by kaizumaki** [comment]
@shgtkshruch お願いします！

**Comment by kaizumaki** [comment]
css modulesを導入します。classの命名規則に悩まなくてすむと思います。ぜひご活用ください！
[詳しくはこちら](https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596044836)

**Comment by shgtkshruch** [comment]
わー助かります！
ありがとうございます :)
