### ISSUE TITLE
「専門家による分析・総括コメントの詳細はこちら」のリンクのURLが古くなっている

### ISSUE THREAD

**Issue by shuuji3** [tokyo-metropolitan-gov/covid19#6606]
## 起こっている問題 / The Problem
- トップページの「専門家による分析・総括コメントの詳細はこちら」のリンクのURLが古くなっているため、URLにアクセスすると毎回新しいページへのリダイレクトが行われてしまっています。

## スクリーンショット / Screenshot

<img width="537" alt="Screen Shot 2021-08-15 at 17 56 42" src="https://user-images.githubusercontent.com/1425259/129472926-f042b6b8-b70f-4739-9ec3-f395acab4112.png">
リダイレクト時にこのようなページが表示されます。

## 期待する見せ方・挙動 / Expected Behavior
- URLとして、 https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/monitoring.html の代わりに https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/info/monitoring.html を使って、リダイレクトページを表示しないようにする。

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページ https://stopcovid19.metro.tokyo.lg.jp/ を開く
2. 「専門家による分析・総括コメントの詳細はこちら」のリンクをクリックする

## 動作環境・ブラウザ / Environment
N/A

**Comment by kaizumaki** [comment]
@shuuji3 ご指摘ありがとうございます！これは修正しましょう。

**Comment by shuuji3** [comment]
早速 #6607 にPRを作りました。
