### ISSUE TITLE
[/flow] コンポーネントコーディング デスクトップ版 FlowPcDays.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#661]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035047
↑の上のブロックの青枠部分「４日以上続いている」

ファイル名は `FlowPcDays.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by kaizumaki** [comment]
css modulesを導入します。classの命名規則に悩まなくてすむと思います。ぜひご活用ください！
[詳しくはこちら](https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596044836)

**Comment by smellman** [comment]
@kaizumaki css modulesは必須ですか？

**Comment by kaizumaki** [comment]
@smellman 必須ではないですが、できればflowページで揃えたい感じがあります。。

**Comment by smellman** [comment]
@kaizumaki 了解ですー
一旦PRをWIPにします。

**Comment by kaizumaki** [comment]
@smellman すみません〜。よろしくです！

**Comment by smellman** [comment]
@kaizumaki 対応しました！reviewをお願いします
