### ISSUE TITLE
[サイトリニューアル]「相談の手順を見る 」のコーナーを「新型コロナ保健医療情報ポータル」に変更

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6611]
**8月末に対策サイトのレイアウトリニューアルを行います。このissueはその一部です。
全体としては使用感改善のための整理となります。ご意見などありましたらコメントしてください！**

現在のファーストビュー内「自分や家族の症状に不安や心配があればまずは電話相談をどうぞ」のブロックを以下に変更します。

テキスト：`ワクチン情報・変異株情報・検査情報等の新型コロナ関連情報はこちら`
ボタンテキスト：`新型コロナ保健医療情報ポータル`
リンク先URL：https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/index.html

**Comment by knknk98** [comment]
こんばんは！こちら対応できそうなのでやらせていただきたいです！

**Comment by kaizumaki** [comment]
@knknk98 おお、ありがとうございます！ぜひお願いします！ 🙏

**Comment by knknk98** [comment]
@kaizumaki 
日本語以外の言語の表示はどうしたら良いですか？

**Comment by kaizumaki** [comment]
@knknk98 多言語はTransifexというサービスを使って翻訳作業をしているので、このリポジトリでは触らなくていいのです。なので、 `assets/locales/` 以下は何もしなくて大丈夫ですよ！（ `assets/locales/ja.json` も自動で反映されるようになっているので、触らなくてOKです！）
