### ISSUE TITLE
[サイトリニューアル]前日比表示の単位を「％」から「ポイント」に変更

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6612]
**8月末に対策サイトのレイアウトリニューアルを行います。このissueはその一部です。
全体としては使用感改善のための整理となります。ご意見などありましたらコメントしてください！**

単位が％の項目について、前日比表示の単位を「％」から「ポイント」に変更します。

対象：モニタリング項目(3)、モニタリング項目(4)

**Comment by kai0310** [comment]
@kaizumaki 
こちら対応します！

確認になるのですが、モニタリング項目(3)の場合は添付画像の選択箇所のみの変更で間違いなかったでしょうか？

![スクリーンショット 2021-08-18 23 21 43](https://user-images.githubusercontent.com/52205108/129915491-7803cd5c-47bd-450c-9bbc-4b123306afaa.png)

**Comment by kaizumaki** [comment]
@kai0310 ありがとうございます！モニタリング項目(3)は、そこだけで大丈夫なはずです（あとから東京都の方から追加で指示が来るかもしれませんが...）。とりあえず進めてもらえると嬉しいです！ 🙏
