### ISSUE TITLE
[サイトリニューアル]「モニタリング項目」に「国のステージ判断のための指標」のボタンリンクを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6613]
**8月末に対策サイトのレイアウトリニューアルを行います。このissueはその一部です。
全体としては使用感改善のための整理となります。ご意見などありましたらコメントしてください！**

「モニタリング項目」に以下のボタンリンクを追加します。

ボタンテキスト：`国のステージ判断のための指標`
リンク先URL：https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/info/kunishihyou.html
位置：「最新のモニタリング項目の分析・総括コメントについて」ボタンの下

**Comment by RS3030** [comment]
はじめまして！
こちらのissueできそうなのでやらせていただきます！
