### ISSUE TITLE
[/flow] コンポーネントコーディング デスクトップ版 FlowPcSuspect.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#662]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035047
↑の上のブロックの紫枠部分「不安に思う方」

ファイル名は `FlowPcSuspect.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by Nyoho** [comment]
今日1名感染者確認が出た広島からです。これやってみたいと思います!

**Comment by kaizumaki** [comment]
@Nyoho ありがとうございます！ぜひお願いします！

**Comment by Nyoho** [comment]
![image](https://user-images.githubusercontent.com/118150/76139890-3ba22900-6098-11ea-8939-f8968122919c.png)
CSSの `:before`, `:after` で無理矢理もとのっぽいのを作ってみた。

**Comment by kaizumaki** [comment]
@Nyoho いいですね！

**Comment by Nyoho** [comment]
もうちょっと手直ししたらWIP PR作ります。

**Comment by Nyoho** [comment]
![image](https://user-images.githubusercontent.com/118150/76140760-ef0f1b80-60a0-11ea-9c0d-b8f33d5fbb1c.png)
だいぶできた気がする

**Comment by Nyoho** [comment]
commit しようとすると husky に怒られたことがわかりました。

```
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
```

なるなる

**Comment by Nyoho** [comment]
```
$ g cm (git commit)
husky > pre-commit (node v10.19.0)
rbenv setting up took 417 msec.
fish: Unknown command: lint-staged
fish: 
lint-staged
^
husky > pre-commit hook failed (add --no-verify to bypass)
error Command failed with exit code 127.
```

ぐぬぬ

**Comment by kaizumaki** [comment]
@Nyoho おっと、yarnなのですが、 `yarn lint`を試してもらえますか？

**Comment by Nyoho** [comment]
@kaizumaki `yarn lint` 自体は通ります。

```
✖ 69 problems (0 errors, 69 warnings)
  0 errors and 49 warnings potentially fixable with the `--fix` option.

✨  Done in 22.47s.
```

コミットしようとすると lint-staged が見つからないというエラーになるみたいです。

**Comment by Nyoho** [comment]
```
fish: Unknown command: lint-staged
fish: 
lint-staged
```

ここを見るとシェルが見つけられていないのがいけないっぽいので、node を nvm で使っているのがよくないのかもしれません。
fish を立ち上げた直後は確かに見えないはずで nvm use v10 などとしてから使い始めるので^^;

**Comment by Nyoho** [comment]
試しに `.git/hooks/husky.sh` の冒頭に次を入れてみましたが同じくだめでした。

```
. $NVM_DIR/nvm.sh
nvm use v10
```

**Comment by Nyoho** [comment]
今Zoomで .git/hooks を削除してみるという方法を教えていただいて、見事にコミットができました!

**Comment by kaizumaki** [comment]
@Nyoho よかったです！
