### ISSUE TITLE
[/flow] コンポーネントコーディング デスクトップ版 FlowPcAdvisory.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#663]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035047
↑の上のブロックの緑枠部分「新型コロナ受診相談窓口」

ファイル名は `FlowPcAdvisory.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by pep299** [comment]
こちら引き受けます〜！

**Comment by kaizumaki** [comment]
@pep299 お願いします！

**Comment by kaizumaki** [comment]
css modulesを導入します。classの命名規則に悩まなくてすむと思います。ぜひご活用ください！
[詳しくはこちら](https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596044836)

**Comment by kaizumaki** [comment]
@pep299 すみません！カラーに若干の変更があります。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596104190
- 相談窓口エリア内背景：$gray-5 (#F8F9FA)
- 相談窓口エリア内ボーダー：$gray-4 (#D9D9D9)
