### ISSUE TITLE
[/flow] コンポーネントコーディング デスクトップ版 FlowPcRequired.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#664]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035047
↑の下のブロックの赤枠部分「受診が必要」

ファイル名は `FlowPcRequired.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by Okahill** [comment]
OSS活動は初めてなのですが、こちら対応させて頂いても良いでしょうか

**Comment by kaizumaki** [comment]
@Okahill ぜひお願いします！
