### ISSUE TITLE
[/flow] コンポーネントコーディング デスクトップ版 FlowPcPcr.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#665]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035047
↑の下のブロックの緑枠部分「PCR検査」

ファイル名は `FlowPcPcr.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by mmmmmmmmn** [comment]
こちらなのですが、他の方が着手されていないようであれば、対応いたします。

**Comment by kaizumaki** [comment]
@mmmmmmmmn お願いします！

**Comment by kaizumaki** [comment]
css modulesを導入します。classの命名規則に悩まなくてすむと思います。ぜひご活用ください！
[詳しくはこちら](https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596044836)

**Comment by mmmmmmmmn** [comment]
@kaizumaki 
1点、相談があります。

現在、自分のPCからは、clone / fetch はできるようなのですが、pushができない状態です………。
おそらく、Write権限がないのではないかと思います。

お手数おかけしますが、権限があるかどうかをご確認いただき、もしないようであれば、追加していただけないでしょうか。🙇

**Comment by kaizumaki** [comment]
@mmmmmmmmn 一度ご自身のGitHubにリポジトリを作っていただき、そこからプルリクエストを投げる形になります。（Forkのほうがよかったかもです）

**Comment by mmmmmmmmn** [comment]
@kaizumaki 
承知しました。一度 Fork いたします。
ありがとうございます！
