### ISSUE TITLE
[/flow] コンポーネントコーディング デスクトップ版 FlowPcNotRequired.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#666]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035047
↑の下のブロックの青枠部分「受診が不要」

ファイル名は `FlowPcNotRequired.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by task-k0414** [comment]
こちらまだ誰も着手していなければやらせてください！

**Comment by kaizumaki** [comment]
@task-k0414 ぜひお願いします！
