### ISSUE TITLE
ボタンhover時のアイコンの視覚性改善

### ISSUE THREAD

**Issue by hc0208** [tokyo-metropolitan-gov/covid19#6660]
## 改善詳細 / Details of Improvement
- ボタンhover時のアイコンの動きにチラつきがあり視覚性が悪い

## スクリーンショット / Screenshot
![例](https://gyazo.com/60aa5042361c1d0e662c3fdd587dbcc6/raw)

## 期待する見せ方・挙動 / Expected behavior
![例](https://gyazo.com/3e3e2586b9004553c7a0260a3b010b6c/raw)

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari

**Comment by kaizumaki** [comment]
@hc0208 ご提案ありがとうございます！これ、たしかに気になってました。修正をお願いできたりしますでしょうか？

**Comment by hc0208** [comment]
@kaizumaki 
はい。
ローカル環境で修正しておりますので、PR作成いたします。
