### ISSUE TITLE
[/flow] コンポーネントコーディング デスクトップ版 FlowPcHospitalized.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#667]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035047
↑の下のブロックの紫枠部分「入院となります」

ファイル名は `FlowPcHospitalized.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by sushi-udon** [comment]
こちら、対応させて頂きます。

**Comment by kaizumaki** [comment]
@sushi-udon お願いします！

**Comment by kaizumaki** [comment]
css modulesを導入します。classの命名規則に悩まなくてすむと思います。ぜひご活用ください！
[詳しくはこちら](https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596044836)

**Comment by sushi-udon** [comment]
こちら対応したかったのですが、自宅PCのgitの調子が悪く、
明日になっても特にプルリクなかった場合、一旦assign を解除して頂けますと幸いです:bow: :bow:

**Comment by kaizumaki** [comment]
@sushi-udon 了解です！ご無理なさらず！
