### ISSUE TITLE
[/flow] コンポーネントコーディング モバイル版 FlowSpPast.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#668]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035102
↑の上から１番目の赤枠部分「発症前２週間以内」

ファイル名は `FlowSpPast.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by harukakawanaka** [comment]
こちら引き受けてみますね

**Comment by kaizumaki** [comment]
@harukakawanaka お願いします！

**Comment by kaizumaki** [comment]
すみません！矢印画像をdevelopmentブランチに上げました。回転させてお使いください！
黄色のカラーコードは `#FFE200` です。
