### ISSUE TITLE
タブを切り替えた際の再描画のガタつきを抑えたい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6683]
## 改善詳細 / Details of Improvement
- #6666 でタブにパーマリンクを設定しました。
- ファーストビューがガタつくので、pagesの共通部分をコンポーネント化したいです。

以下コメント
> @kaizumaki ちゃんと動作していて素晴らしいと思います。
> 一旦このPRはリリースしてから、追っての対応で良いかと思うんですが、タブを切り替えて `pages/index.vue` と `pages/reference.vue`を行き来する際、`cards-tab` 以外のコンポーネントも再描画されてしまって画面がガタつくのを調整できると良さそうですね。`pages/index.vue` と `pages/reference.vue`はほぼ同一なので、共通のtemplate部分をまとめて`components/index`配下に切り出せば、タブ切替えに伴う不要な再描画を防げそうな気がします。

_Originally posted by @soutaito in https://github.com/tokyo-metropolitan-gov/covid19/pull/6666#discussion_r697773770_

## 期待する見せ方・挙動 / Expected behavior
- タブを切り替えた際の再描画によるガタつきが抑えられている

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Foo-x** [comment]
対応します。
