### ISSUE TITLE
import/namedのeslintエラーを解消したい

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6687]
## 改善詳細 / Details of Improvement
- `import/named` のeslintエラーが頻発しているので、対応したいです。
- 現在、部分的に `// eslint-disable-line import/named` コメントで逃げています。
- 以下のようにすればいいみたいです（ @edamame8888 さん、ありがとうございます！）。
- 他の方法もあるかもしれません。お気づきの点ありましたらコメントください！

```diff
- import Vue, { PropType } from 'vue'
- import { ThisTypedComponentOptionsWithRecordProps } from 'vue/types/options'
- import { TranslateResult } from 'vue-i18n'
+ import Vue from 'vue'
+ import {
+   PropType,
+   ThisTypedComponentOptionsWithRecordProps,
+ } from 'vue/types/options'
+ import VueI18n from 'vue-i18n'
```

> `TranslateResult` は、`VueI18n.TranslateResult` でアクセスする。
> ことでエラーは出力されないことを確認しました。
>  
> @kaizumaki さんのおっしゃる通り、まとめてESLintエラーの対応した方が良いと思うので、
> `// eslint-disable-line import/named` で対応させていただきます。
> よろしくお願いいたします。
> 

_Originally posted by @edamame8888 in https://github.com/tokyo-metropolitan-gov/covid19/issues/6686#issuecomment-907724982_

## 期待する見せ方・挙動 / Expected behavior
- `import/named` のeslintエラーが出なくなる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Foo-x** [comment]
Type-Only Imports はいかがでしょうか？
named export をそのまま使いながらエラーを解消できる上に、コンパイル後のサイズも減ります。

```diff
- import Vue, { PropType } from 'vue'
- import { TranslateResult } from 'vue-i18n'
+ import type { PropType } from 'vue'
+ import Vue from 'vue'
+ import type { TranslateResult } from 'vue-i18n'
```

**Comment by kaizumaki** [comment]
@Foo-x フォローありがとうございます！なるほど、そういう方法があるのですね。よさそうなのでその方向でぜひお願いしたいです！ 🙏
