### ISSUE TITLE
[/flow] コンポーネントコーディング モバイル版 FlowSpGeneral.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#669]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035102
↑の上から２番目の青枠部分「一般の方」

ファイル名は `FlowSpGeneral.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by forestgtree** [comment]
やってみます！

**Comment by kaizumaki** [comment]
@forestgtree お願いします！

**Comment by yusakuOono** [comment]
こちら対応してみます。

**Comment by kaizumaki** [comment]
@yusakuOono お願いします！

**Comment by kaizumaki** [comment]
すみません！矢印画像をdevelopmentブランチに上げました。回転させてお使いください！
黄色のカラーコードは `#FFE200` です。
