### ISSUE TITLE
「知事からのメッセージ」を追加する

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#67]

**Comment by yokinist** [comment]
@halsk 念のため確認なんですが、こちらは外部リンクになる形でしたっけ？

**Comment by halsk** [comment]
中に作る可能性ありますが、まだよくわからないです

**Comment by mikkame** [comment]
サイドバーからリンク消してしまったのでこのタスクやる時に追加おねがいします！

**Comment by halsk** [comment]
リンク来ました！外部リンクですね
https://www.metro.tokyo.lg.jp/tosei/governor/governor/katsudo/2020/03/03_00.html

**Comment by mikkame** [comment]
今の所404っぽいですが大丈夫ですか？

**Comment by halsk** [comment]
ホンマや。確認します！

**Comment by halsk** [comment]
そのうち更新されるそうです！

**Comment by mikkame** [comment]
完了です
