### ISSUE TITLE
[/flow] コンポーネントコーディング モバイル版 FlowSpElder.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#670]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035102
↑の上から３番目の緑枠部分「ご高齢な方」

ファイル名は `FlowSpElder.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by jay-es** [comment]
こちらやらせていただきます

**Comment by kaizumaki** [comment]
@jay-es お願いします！

**Comment by kaizumaki** [comment]
すみません！矢印画像をdevelopmentブランチに上げました。回転させてお使いください！
黄色のカラーコードは `#FFE200` です。
