### ISSUE TITLE
[/flow] コンポーネントコーディング モバイル版 FlowSpSuspect.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#671]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035102
↑の上から４番目の赤枠部分「不安に思う方」

ファイル名は `FlowSpSuspect.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by matoruru** [comment]
こんにちは。こちらやってみていいですか？

**Comment by kaizumaki** [comment]
@matoruru ぜひお願いします！

**Comment by kaizumaki** [comment]
すみません！矢印画像をdevelopmentブランチに上げました。回転させてお使いください！
黄色のカラーコードは `#FFE200` です。

**Comment by matoruru** [comment]
ありがとうございます！
