### ISSUE TITLE
タブが表示されない

### ISSUE THREAD

**Issue by hota911** [tokyo-metropolitan-gov/covid19#6718]
## 起こっている問題 / The Problem
「注目の指標」などのタブが表示されない

## スクリーンショット / Screenshot

![Screenshot_20210906-205648.png](https://user-images.githubusercontent.com/38419042/132214197-c8b3b167-7d59-449a-807f-bfd3830187a4.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「注目の指標」などのタブが表示される

## 起こっている問題の再現手段 / Steps to Reproduce

PC Chrome で
1. Dev tools で Pixel 2XL を選択する
2. https://stopcovid19.metro.tokyo.lg.jp/ にアクセスする
3. スクロールできず、タブが表示されない

PWA として
1. Chrome で「ホーム画面に追加」する
2. PWA としてインストールしたアプリを起動する
3. スクロールできず、タブが表示されない

Android Chrome で
1. https://stopcovid19.metro.tokyo.lg.jp/ にアクセスする
2. ゆっくりと画面をスクロールする

## 動作環境・ブラウザ / Environment
- Android 11
- Chrome
- Pixel 5a

**Comment by kaizumaki** [comment]
@hota911 ご指摘いただきありがとうございます！
PWAについては #6155 でServiceWorkerを登録解除する対応を行なっています。私がPWAに明るくないのですが、今回の問題はそれに関係しますでしょうか？

**Comment by hota911** [comment]
いえ、PWA は関係なく、解像度（1080x2400）さえ設定すれば、PCからでも再現できました

**Comment by kaizumaki** [comment]
@hota911 PWAでもなく、AndroidのChromeでもない環境で再現しているのですね。ちなみにPCはOSとブラウザは何になりますか？

**Comment by hota911** [comment]
@kaizumaki Mac の Chrome です。

**Comment by kaizumaki** [comment]
@hota911 ありがとうございます。私の手元でも現象が再現しました。ちょうどスクロールが必要になる高さとコンテンツの高さが合ってしまっているために起こっているようです。
そもそもスクロールの判定をなくしてしまってもいいかもしれません。対応しますので、しばらくお待ちいただければと思います 🙇‍♀️

**Comment by hota911** [comment]
Scroll するまでカードを表示しない処理をしているのはこちらのようですね。
https://github.com/tokyo-metropolitan-gov/covid19/blob/78163071e5ebd4ff29830214846f24cbfd9e8353/pages/index.vue#L61-L65

> 対応しますので、しばらくお待ちいただければと思います 🙇‍♀️

よろしくお願いいたします。（自分でも直せるかと思って見ていたのですが、Vue 力が低くて正しい直し方がわかりませんでした…）
