### ISSUE TITLE
[/flow] コンポーネントコーディング モバイル版 FlowSpAdvisory.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#672]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035102
↑の上から５番目の青枠部分「新型コロナ受診相談窓口」

ファイル名は `FlowSpAdvisory.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by yuma84** [comment]
こちら、やってみます！

**Comment by kaizumaki** [comment]
@yuma84 お願いします！
