### ISSUE TITLE
重症基準の注釈文言: 都の基準を明記

### ISSUE THREAD

**Issue by conao3** [tokyo-metropolitan-gov/covid19#6724]
## 改善詳細 / Details of Improvement
「モニタリング項目(7) 重症患者数」の注釈文言の修正を提案します。

重症基準について、都のPDFへのリンクが #5317 で提案され、 #5318 でマージされたようですが、このPDF文書を見ると現在の注釈文言である「入院患者数のうち、人工呼吸器管理（ECMOを含む）が必要な患者数を計上。」は間違っており、都のPDFの通り「人工呼吸管理または ECMO を使用している患者」と記述したほうが良いように思います。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4703128/132290459-6e4ff0b4-c5d4-40cb-94f7-8b3779a6385a.png)

## 期待する見せ方・挙動 / Expected behavior
注釈文言の変更。
- before: 「入院患者数のうち、人工呼吸器管理（ECMOを含む）が必要な患者数を計上。」
- after: 「人工呼吸管理または ECMO を使用している患者数を計上。」

## 動作環境・ブラウザ / Environment
- Linux
- Chrome

**Comment by kaizumaki** [comment]
@conao3 ご提案ありがとうございます！東京都に確認しますので、しばらくお待ちください。

**Comment by kaizumaki** [comment]
@conao3 たいへんお待たせしました。こちらの件、東京都から回答がきまして、「当該箇所の文言は、表現は異なりますが、同一の内容を示しております。ご提案の趣旨は今後のサイト掲載内容見直し等の際に参考とさせていただきます。」とのことです。
結果として、せっかくご提案いただいたのに採用とならず申し訳ありません。こちらのissueはクローズとさせていただきます 🙇

**Comment by conao3** [comment]
@kaizumaki さん、ありがとうございます。

東京都の回答の方ですが、私の書き方があいまいで私の意図とは違った点を受け取られてしまったのかもしれないのでもう一度お聞きいただくことをお願いしたいです。

おそらく東京都は

> before: 「入院患者数のうち、人工呼吸器管理（ECMOを含む）が必要な患者数を計上。」
> after: 「人工呼吸管理または ECMO を使用している患者数を計上。」

の差分を「入院患者数のうち、人工呼吸器管理（ECMOを含む）」と「人工呼吸管理または ECMO 」の違いとして認識されていると思います。
そのため
> 当該箇所の文言は、表現は異なりますが、同一の内容を示しております。

との回答になっていると思います。しかし私が（主に）提案しているのは別で、「必要な患者数」と「使用している患者数」の差分です。


「ECMOが必要な患者数」と「ECMOを（現在）使用している患者数」は明らかに意味するところが違うと考えています。

都が「重症患者」としているのは後者と理解しています。それは都基準ですのでそれ自体は全く問題ないのですが、現在前者の定義としてウェブページに書かれており、文言が誤解を生むと思っているため修正したいと提案しています。

**Comment by conao3** [comment]
![image](https://user-images.githubusercontent.com/4703128/141049157-384507ae-6791-4440-b313-63d98e1e58d5.png)

https://www.bousai.metro.tokyo.lg.jp/_res/projects/default_project/_page_/001/011/435/7kai/202008207.pdf

「重症基準の考え方はこちら」でリンクされているPDFです。このPDFの文言の通りにウェブページに記載したいです。

**Comment by kaizumaki** [comment]
@conao3 フォローありがとうございます 🙇  私もちゃんと突っ込めていなかったのが申し訳ないのですが、おそらく「「必要な患者数」と「使用している患者数」の差分はない（あくまで表現の違い）」ということなのだと思います。
東京都には再度まわしましたので、今しばらくお待ちいただければと思います。
