### ISSUE TITLE
[/flow] コンポーネントコーディング モバイル版 FlowSpAccording.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#674]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035102
↑の上から６番目の緑枠部分「新型コロナ受診相談窓口による相談結果」

ファイル名は `FlowSpAccording.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by dmamira** [comment]
フォントは何を利用されていますか？

**Comment by kaizumaki** [comment]
@dmamira Roboto, sans-serifでよいかと思われます！画像と合わなくてよいですー。

**Comment by dmamira** [comment]
ありがとうございます。このコンポーネントの作成を試してみます。

**Comment by kaizumaki** [comment]
@dmamira ありがとうございます！お願いします！

**Comment by kaizumaki** [comment]
すみません！矢印画像をdevelopmentブランチに上げました。回転させてお使いください！
黄色のカラーコードは `#FFE200` です。

**Comment by dmamira** [comment]
緑矢印のカラーコードを教えていただけますか？

**Comment by kaizumaki** [comment]
@dmamira こちらでお願いします！
- $green-1 (#00A040)

**Comment by dmamira** [comment]
明日までには完成させます。

**Comment by dmamira** [comment]
「受信が不要と判断された場合」のところのの右側にある病院のマークはどれを利用すればよいでしょうか？

**Comment by kaizumaki** [comment]
`static/flow/apartment-24px.svg` ですね。まぎらわしくてごめんなさい。。。

**Comment by dmamira** [comment]
PRは、自分のリポジトリにForkした後に出せば良い感じですか？

**Comment by kaizumaki** [comment]
@dmamira ですです。
