### ISSUE TITLE
都営地下鉄の利用者数の推移グラフの折れ線の色が薄い

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#6745]
## 改善詳細 / Details of Improvement
9:30~10:30の折線の色が薄く、見えにくい。また同系色で薄い色なので別の意図（予想と実際みたいな）に見えてしまう可能性がある。
※棒グラフの塗りのカラーセットから色を当てはめていると推定するが、棒グラフには枠線があり、こちらにはそれがないので、塗りだけだと視認しにくくなっている。

## スクリーンショット / Screenshot
<img width="512" alt="スクリーンショット 2021-09-13 16 20 54" src="https://user-images.githubusercontent.com/17713513/133040893-e16cd97f-ee8b-47eb-8a65-cf8ea7f2cc27.png">

## 期待する見せ方・挙動 / Expected behavior
別の色を検討する。

## 動作環境・ブラウザ / Environment
すべて

**Comment by kaizumaki** [comment]
@forestgtree こちらいかがでしょう？どういった配色がいいかアドバイスいただけると嬉しいです！
