### ISSUE TITLE
「感染状況・医療提供体制の分析」の画像のaltの修正

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#6746]
2021年9月4日〜9月13日までに実施された、アクセシビリティ試験結果に基づくIssueです。
達成基準1.1.1に対して不適合

## 改善詳細 / Details of Improvement
対象：
- https://stopcovid19.metro.tokyo.lg.jp/
- https://stopcovid19.metro.tokyo.lg.jp/cards/monitoring-comment/

外部サイトへのリンクサムネイルのaltが適切ではなさそう。これ自体は中身を読み取らせるものでなくサムネイルであると位置づける必要がある（視覚的にも図の内容は読み取れない）

`<img data-v-cc1b0b78="" width="320" height="240" src="https://www.seisakukikaku.metro.tokyo.lg.jp/cross-efforts/2021/09/images/0902graph6-3.JPG" alt="【医療提供体制】⑥-3 検査陽性者の療養状況（公表日の状況）">
`
## 期待する見せ方・挙動 / Expected behavior
どれが表示されても` alt="サムネイル：「最新のモニタリング項目の分析・総括コメント」に掲載されている図版" `とする。

## 動作環境・ブラウザ / Environment
すべて

**Comment by kaizumaki** [comment]
@magi1125 おお、なるほどですね。ちなみにここのaltのテキストは東京都側の元データで設定しています。フロント側の実装を変えずに元データでコントロールするというのでいいでしょうか？

**Comment by kaizumaki** [comment]
考えましたが、やはり元データでコントロールすることにします。

**Comment by magi1125** [comment]
@kaizumaki はい、ユーザー側は差がないと思うので、どちらでもOKです!

**Comment by kaizumaki** [comment]
@magi1125 こちら修正が完了したものと思われます。ご確認お願いします！ 🙏

**Comment by magi1125** [comment]
@kaizumaki 修正を確認できました！
