### ISSUE TITLE
「注釈を全て表示・注釈を折り畳む」のアクセシビリティ改善

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#6748]
2021年9月4日〜9月13日までに実施された、アクセシビリティ試験結果に基づくIssueです。
達成基準1.3.1, 2.1.1, 2.4.7, 4.1.2に対して不適合

## 改善詳細 / Details of Improvement
対象：
- https://stopcovid19.metro.tokyo.lg.jp/
- https://stopcovid19.metro.tokyo.lg.jp/monitoring
- https://stopcovid19.metro.tokyo.lg.jp/reference

「注釈を全て表示・注釈を折り畳む」のボタンがdiv製であるため、以下の問題がある。
- ボタンであるというセマンティクスがない
- 開閉状態が伝わらない
- キーボードフォーカスのインジケータが表示されない
- キーボードでの操作をうけつけない

## 期待する見せ方・挙動 / Expected behavior
https://www.w3.org/TR/wai-aria-practices-1.1/examples/disclosure/disclosure-img-long-description.html
を参考に、button要素＋aria-expanded＋aria-controlsを用いて実装する

## 動作環境・ブラウザ / Environment
すべて

**Comment by ryokohbato** [comment]
お伺いしたい点が2点あります。

1点目ですが、以下の画像で、画像1枚目が折りたたみボタンにフォーカスが当たっている状態で、2枚目には当たっていない状態です。ボタンの色とフォーカスリングの色が同じためにやや見づらい印象がありますが、このままで大丈夫でしょうか。

![注釈・フォーカスあり](https://user-images.githubusercontent.com/67552983/133938726-485c9cf0-2d12-42b9-8b28-a6a7784e415a.png)

![注釈・フォーカスなし](https://user-images.githubusercontent.com/67552983/133938775-2288222d-df42-4eda-82b0-bf32d0a84d7d.png)

2点目は実装の話です。`aria-controls`を使用するために、グラフや表の注釈部分のHTMLにidを指定しなければならないのですが、`titleId + '--description'`として実装しても問題ないでしょうか。(例えば、`検査陽性者の状況`セクションの注釈部分であれば、`details-of-confirmed-cases--description`と付きます。)  
しばらくプロジェクトから離れてしまっていたため、命名規則等を忘れてしまっていて、問題があればお教えいただけると有り難いです。

**Comment by kaizumaki** [comment]
@ryokohbato ご検討いただきありがとうございます！
１点目はたしかに微妙ですね...。色については @magi1125 さんアドバイスいただけると嬉しいです。
２点目は問題ないですよ！idの命名規則は特になかったかと思います。

**Comment by magi1125** [comment]
@kaizumaki @ryokohbato 確かに見えづらいですね。
outline-offset で少し隙間をあけると視認しやすくなりそうですが、どうでしょうか。

**Comment by ryokohbato** [comment]
@kaizumaki @magi1125 
ありがとうございます。
見えやすさを考えてやや大きめに隙間をあけてみましたが、いかがでしょうか。

![image](https://user-images.githubusercontent.com/67552983/134086822-f2be2a83-3845-4f0d-83dc-99af300ad99a.png)

**Comment by magi1125** [comment]
@ryokohbato ありがとうございます、良いと思います！

**Comment by ryokohbato** [comment]
ありがとうございます！🙇‍♂️
