### ISSUE TITLE
グラフとテーブルにフォーカスインジケーターが表示されない

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#6749]
2021年9月4日〜9月13日までに実施された、アクセシビリティ試験結果に基づくIssueです。
達成基準2.4.7に対して不適合

## 改善詳細 / Details of Improvement
対象：すべてのグラフとテーブル

グラフとテーブルに対して、スクロール等の操作ができるようにフォーカスが受け取れるようになっているが、フォーカスインジケーターが表示されない

## 期待する見せ方・挙動 / Expected behavior
どちらの要素にも、フォーカス時にフォーカスリングが表示される

## 動作環境・ブラウザ / Environment
すべて

**Comment by kaizumaki** [comment]
@magi1125 お、これは具体的にはどこにfocusのスタイルがあたっているとよいのでしょうか？グラフ全体・テーブル全体を囲むようにしているのが期待する見せ方ですかね？

**Comment by magi1125** [comment]
@kaizumaki YESです!

**Comment by Foo-x** [comment]
対応します。

**Comment by kaizumaki** [comment]
@Foo-x ありがとうございます！よろしくお願いします！

**Comment by kaizumaki** [comment]
以下のとおりPRにコメントしました。こちらのissueは再オープンします。

> @Foo-x すみません！グラフのY軸もスクロール対象になっていたみたいで、Y軸が隠れてしまっているので一旦リバートさせていただきました（レビュー時点で気づいておらず、すみませんでした）。たいへんお手数ですが、テーブルのfocusとグラフのfocusとで２つに分けて再度PRしていただけると助かります 🙏

_Originally posted by @kaizumaki in https://github.com/tokyo-metropolitan-gov/covid19/issues/6774#issuecomment-923540797_

**Comment by Foo-x** [comment]
すみません、確認不足でした。
すぐに対応します！

**Comment by kaizumaki** [comment]
#6785 #6786 をマージしましたので、こちらのissueはクローズします。
