### ISSUE TITLE
グラフパネルを切り替えるタブのWAI-ARIA指定の修正

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#6758]
## 改善詳細 / Details of Improvement

```
<div role="tablist" class="v-item-group theme--light v-slide-group v-tabs-bar v-tabs-bar--is-mobile primary--text" data-booted="true">
<a href="/" tabindex="0" aria-selected="false" role="tab" id="cardTab-0" class="v-tab" data-ol-has-click-handler="">
<a href="/monitoring" aria-current="page" tabindex="0" aria-selected="true" role="tab" id="cardTab-1" class="v-tab--active v-tab" data-ol-has-click-handler="">

```
上記のように`role="tablist"` `aria-selected="false"` `role="tab"` の指定があるが、実際の挙動としてはタブ切り替えというよりページ遷移であるため、以下どちらかの対応が必要と考える。

- A：これらの指定を外す（※aria-current="page”は残す）
- B：tablistとtabとaria-selectedの指定は残しつつ、選択したときに画面リフレッシュ後にフォーカスが選択したタブに移るようにフォーカス管理する。またタブがかかっている範囲に対してrole="tabpanel"を指定する。aria-current="page”は削除する。

## 期待する見せ方・挙動 / Expected behavior
AかBのどちらかの対応を実施する。

## 動作環境・ブラウザ / Environment
すべて

**Comment by kaizumaki** [comment]
こちら対応しますね。
タブは実質ページ遷移なので、Aの対応がよさそうです。
