### ISSUE TITLE
ラベルのないcanvas要素への対応

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#6759]
2021年9月4日〜9月13日までに実施された、アクセシビリティ試験結果に基づくIssueです。
達成基準1.1.1に対して不適合

## 改善詳細 / Details of Improvement

`<canvas id="monitoring-confirmed-cases-number-chart-header-right" width="351" height="240" class="chartjs-render-monitor" style="display: block; width: 351px; height: 240px;"></canvas>
`

グラフの後に出現する上記のcanvas要素に代替コンテンツがないため、スクリーンリーダーに「ラベルのない画像」や「ブランク」と読まれる。

## 期待する見せ方・挙動 / Expected behavior
aria-hiddenを指定し読み飛ばすようにする

## 動作環境・ブラウザ / Environment
すべて

**Comment by kaizumaki** [comment]
こちら対応します。

**Comment by kaizumaki** [comment]
@magi1125 これってもしかして、すべてのグラフについてそうなっていますか？

**Comment by magi1125** [comment]
@kaizumaki あーそうです、説明不足ですいません！
