### ISSUE TITLE
[/flow] コンポーネントコーディング モバイル版 FlowSpHospitalized.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#676]
こちらを必ずお読みください！
#659

このissueで作成してもらいたいコンポーネントは以下の部分です。
https://github.com/tokyo-metropolitan-gov/covid19/issues/659#issuecomment-596035102
↑の上から７番目（１番下）の赤枠部分「入院となります」

ファイル名は `FlowSpHospitalized.vue` としてください。

疑問点があればお気軽にこのissue内でコメントください！

**Comment by knsg16** [comment]
OSSへの参加は初めてなのですが、本プロジェクトの趣旨に共感し、
ぜひ参加させて頂きたいと思っています。
誰も手をつけていないようであれば、こちら対応させて頂いてもよろしいでしょうか？

**Comment by kaizumaki** [comment]
@knsg16 ぜひお願いします！
