### ISSUE TITLE
陽性者の属性テーブルの1ページあたりの人数を選ぶセレクトボックス内部の `<input type="select" />` が `readonly` になっている

### ISSUE THREAD

**Issue by masuP9** [tokyo-metropolitan-gov/covid19#6761]
2021年9月4日〜9月13日までに実施された、アクセシビリティ試験結果に基づくIssueです。
達成基準1.3.1, 4.1.2に対して不適合

## 起こっている問題 / The Problem
- 陽性者の属性テーブルの1ページあたりの人数を選ぶセレクトボックス内部の `<input type="select" />` が `readonly` になっており、操作できるのに操作できないように支援技術から見えてしまう。

## 期待する見せ方・挙動 / Expected Behavior
- `<input type="select" />` が readonly ではない

総合的にページ送りコンポーネントに関する Vuetify の実装では、達成基準を満たせないため、HTMLの `<select>` をスタイリングするほうが望ましい。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 陽性者の属性カードを表示する

## 動作環境・ブラウザ / Environment
- 全て

**Comment by kaizumaki** [comment]
こちら対応しますね。
