### ISSUE TITLE
サイドナビゲーションの `<a>` 要素に間違った `role` が指定されていてリンクとして認識されていない

### ISSUE THREAD

**Issue by masuP9** [tokyo-metropolitan-gov/covid19#679]
## 改善詳細 / Improve details

`.SideNavigation a.ListItem-Container` の要素に `role="listitem"` が指定されておりリンクとして認識されないため、 `role="listitem"` を違う要素に移したい

### 現状の問題点

リンクとして認識されないと、セマンティクスを利用する支援技術（スクリーンリーダーなど）で正しくリンクとして機能できない可能性がある。

## スクリーンショット / Screenshot

<img width="365" alt="該当箇所のスクリーンショット。新型コロナウイルス感染症が心配なときに、という文字列の上に要素とクラス名がポップアップで表示されている" src="https://user-images.githubusercontent.com/6724665/76136556-0f75b080-6076-11ea-9ea1-ad17c4c4a3a1.png">

## 期待する見せ方・挙動 / Expected behavior

- `<a>` 要素には `role` 属性が無い
- `<a>` 要素の親に `role="listitem"` を持った要素がある

=> `ListItem.vue` の root 要素に `role="listitem"` が振られる？ので、root 要素に href でリンク先を指定するのではなく、中にリンクを作る？（Vuetify 詳しくないのでできないかもしれません）

## 動作環境・ブラウザ / Environment
ALL

**Comment by TomohiroHibino** [comment]
こちら未着手でしたら、プルリク出させて頂きます！

**Comment by masuP9** [comment]
おねがいしますー！

**Comment by TomohiroHibino** [comment]
@masuP9 本当にすみません！お伺いしたいことがあります！
①<div role="listitem">で囲む
![スクリーンショット 2020-03-07 15 10 21](https://user-images.githubusercontent.com/45650937/76137991-523f8480-6086-11ea-9e87-fbb9a3f5d3dd.png)

もしくは②<a>タグにrole="link"を指定する
![スクリーンショット 2020-03-07 15 17 56](https://user-images.githubusercontent.com/45650937/76138007-85821380-6086-11ea-95ff-d2d5fcfa2921.png)

のような方法で対応するのはダメでしょうか。。？<v-list-item>を変更するイメージが分からず。。

大丈夫でしたら、どちらの方が適切でしょうか。。？

**Comment by TomohiroHibino** [comment]
①＜ｄiｖ　role="listitem">で囲む
でした。

**Comment by TomohiroHibino** [comment]
@masuP9　すみません、下記のコメントしましたが、過ちに気づきました！無視して下さい！

当にすみません！お伺いしたいことがあります！
①・・・

**Comment by TomohiroHibino** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/709

@masuP9
こちらでプルリクを出しましたが、自信が無い点も含め、書かせていただきました。
お手隙の際にご確認頂ければ幸いです。。！
