### ISSUE TITLE
「企業の皆様・はたらく皆様へ」ページのコンテンツ修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6794]
「企業の皆様・はたらく皆様へ」ページの「新しいワークスタイルや企業活動の東京モデル「スムーズビズ」」の紹介文を以下のように修正します。

【修正前】
`テレワーク・時差出勤などスムーズビズの取組は、新型コロナウイルス感染症の対策としても効果的です。感染症対策として、東京2020大会時の交通混雑緩和に向けた取組の前倒しをお願いします。`

↓

【修正後】
`新型コロナウイルス感染症の感染拡大防止を図るため、テレワーク、時差出勤等の一層の推進にご協力をお願いいたします。`

**Comment by knknk98** [comment]
こちら対応します！
