### ISSUE TITLE
Principle の英語訳を作る

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#68]
https://github.com/tokyo-metropolitan-gov/covid19/wiki/Principle

せっかくいいの出来たので、英訳版も公開したい！

**Comment by hiro-ishi** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/wiki/Principle%5BEnglish%5D
covid19.wiki/Principle[English].md
をwikiに追加しました。
※注意ですが、新しいブランチを切ってwiki.git のremoteにpushしても、github上ではブランチのプルリク化もマージもできないようです。なので、localのmasterブランチからremoteのマスターブランチへ直にpushするしか編集する手はないようです。

**Comment by halsk** [comment]
ありがとうございます！そうなんですね。
まあ、Wiki は今後直接修正してもらうほうが早いかもです。
とりあえずクローズします！ありがとうございました。
