### ISSUE TITLE
トップページの canvas 要素の id 属性が重複している

### ISSUE THREAD

**Issue by oti** [tokyo-metropolitan-gov/covid19#683]
## 改善詳細 / Improve details
- トップページの canvas 要素の id 属性が重複している

同一ページ内の id 属性値の重複はHTML文法違反です。また、id 属性値が重複していると目的の要素を正しく参照できなくなり、スクリーンリーダーを利用しているユーザーに不利益が生じます。

## スクリーンショット / Screenshot
<img width="427" alt="スクリーンショット 2020-03-07 14 02 18" src="https://user-images.githubusercontent.com/710216/76137126-99287c80-607c-11ea-8e74-dd48e9050671.png">

<img width="419" alt="スクリーンショット 2020-03-07 14 02 38" src="https://user-images.githubusercontent.com/710216/76137129-9cbc0380-607c-11ea-8532-c5f26b3de1ed.png">

上記のようにトップページの5つのグラフが全て同じ id 属性値になっています。

## 期待する見せ方・挙動 / Expected behavior
- それぞれ違う id 属性値になること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shigeokitamura** [comment]
こちらまだ未着手でしたら対応させていただきたいです！

**Comment by oti** [comment]
@shigeokitamura お願いします！
