### ISSUE TITLE
別タブで開くアイコンに代替テキストが設定されてない

### ISSUE THREAD

**Issue by masuP9** [tokyo-metropolitan-gov/covid19#684]
## 改善詳細 / Improve details

`.ListItem-ExternalLinkIcon` には `別タブで開く` という意味がありますが `aria-hidden="true"` で支援技術に隠されてしまい、また代替テキストが設定されていません。

この場合、スクリーンリーダーなどの支援技術では別タブで開くかどうかが分からず、前のページに戻ることが難しくなるなどの問題が発生する可能性があります。

## スクリーンショット / Screenshot

<img width="285" alt="該当箇所のスクリーンショット。都民の皆様への横に、四角から矢印が右上方向に飛び出しているアイコンが表示されている" src="https://user-images.githubusercontent.com/6724665/76137122-93329b80-607c-11ea-88f6-5903d35520ff.png" />

## 期待する見せ方・挙動 / Expected behavior
- `aria-hidden` を `false` に
- `aria-label` を指定する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

ALL

**Comment by konu96** [comment]
こちら誰も着手していないので、やりたいと思うのですが大丈夫でしょうか?

**Comment by masuP9** [comment]
おねがいしますー！
