### ISSUE TITLE
ビルド時のアクセシビリティlint導入の検討

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#6848]
## 改善詳細 / Details of Improvement
- アクセシビリティ試験を行い、レベルAA準拠となったため、この状況を今後も維持したい
- 現在は #500 により[vue-axe](https://github.com/vue-a11y/vue-axe)が動いているが、あくまでコンソールにチェック結果が出る形に留まっている
  - なお、 #3177 によりチェックには一部調整が入っている

## 期待する見せ方・挙動 / Expected behavior
- [eslint-plugin-vuejs-accessibility](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility) を導入するなど、CI時点でlintを行い、不適切な実装が合った場合は修正後のコミットを求める形はどうか。
- 現在の実装として実施可能な状況か、また実行した場合のリスクなどを踏まえて議論したい。

**Comment by yamanoku** [comment]
静的HTML生成結果において Accesslint　を導入するとかできたらいいかもしれません。
https://accesslint.com/

実際にうまく機能できるかはわからぬのでアイデアとして。

**Comment by yamanoku** [comment]
プルリクエスト作成時に [eslint-plugin-vuejs-accessibility](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility) が走って違反していた場合マージできないという仕組みがあるのはいいかもですね。

ただ eslint でのアクセシビリティチェックについては「コンポーネント単位」で違反していないかを見るに留める温度感で運用したほうがいいかなと。ページ全体のチェックはそれで補うには力不足なので。

**Comment by yamanoku** [comment]
現在の[ルール](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/tree/main/docs)をみるに必要そうなのは以下かなぁと思っています。


| ルール | おおまかな内容 |
| ----- | ----------- |
| alt-text | 代替の内容が必要な際にalt、aria-labelなどがあるかのチェック |
| aria-props | 定義されていないaria属性（タイポ含む）をチェック |
| aria-role | 存在しないもの、abstractな[role](https://www.w3.org/TR/wai-aria/#role_definitions)の使用をチェック |
| aria-unsupported-elements | aria属性を使用できないタグで使用していないかチェック |
| form-control-has-label | フォームコントロールに対してラベルが必ず付与されているかチェック |
| heading-has-content | 見出しタグやコンポーネントに対して内容が含まれているかチェック |
| no-redundant-roles | タグに重複したroleを付与していないかチェック |
| role-has-required-aria-props | roleの使用において必要になるaria属性があるかチェック |
| tabindex-no-positive | tabindexに0以上の数値が入っていないかチェック |


インタラクティブコンテンツのためのルールチェックもあるのですが、UIの振る舞いについてどこまで定義しているか分からなかったのでここでは含まないようにしてみてます。

**Comment by kaizumaki** [comment]
@yamanoku さん、フォローありがとうございます！

> 静的HTML生成結果において[Accesslint](https://accesslint.com/)を導入するとかできたらいいかもしれません。

見た感じ、すごくよさそうですね。ただ細かな設定というのはできないのでしょうかね。
であれば、 eslint-plugin-vuejs-accessibility を運用した方がいいかもしれません。

**Comment by yamanoku** [comment]
> あ、そうか、Accesslint は静的html生成結果においてでしか意味をなさないのですね。

ですです。なのでそのビルドフローがあれば導入してみてもいいかなという感じですね。

**Comment by Da-1kun** [comment]
@magi1125 @yamanoku @kaizumaki 
PR作成しましたのでご確認いただきたいです！

**Comment by kaizumaki** [comment]
@Da-1kun おお、ありがとうございます！助かります！ 🙏
