### ISSUE TITLE
[i18n] DataView.vue 内の文字列をi18n化

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#687]
総合issue: #680 
（全体の方針については↑へ）

---
- `components/DataView.vue` の直打ちの文字列を`<i18n>`で定義するようにします。
- 各言語への翻訳はこちらにあります: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0

**Comment by MaySoMusician** [comment]
翻訳が更新されたので後ほど更新します

**Comment by nard-tech** [comment]
@MaySoMusician 
> 翻訳が更新されたので後ほど更新します

私やります

**Comment by MaySoMusician** [comment]
@nard-tech お願いします！

**Comment by nard-tech** [comment]
@MaySoMusician #872 を作って頂きましたが，ほぼ同時に #873 を作ってしまったので，とりあえずこちらご確認ください．

**Comment by MaySoMusician** [comment]
#872 および #873 で取り扱うので close
