### ISSUE TITLE
[i18n] PageHeader.vue 内の文字列をi18n化

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#689]
総合issue: #680 
（全体の方針については↑へ）

---
- `components/PageHeader.vue` の直打ちの文字列を`<i18n>`で定義するようにします。
- 各言語への翻訳はこちらにあります: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0

**Comment by halsk** [comment]
PR Merge 済なので Close しますね！
