### ISSUE TITLE
「このサイトについて」ページの実装

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#69]
内容はこちら（都側で確認中だが、仮版であてはめ）

https://docs.google.com/document/d/14ejrsNOqWH3Ea25SzJyQ7_oqADiiROEANtmLIYUW-rE/edit#heading=h.gqy4v4vakc2d

**Comment by kenshir0f** [comment]
対応しますー 🙋

**Comment by kenshir0f** [comment]
URLは仮で `/about` で進めます 🙏
