### ISSUE TITLE
「死亡日別による死亡者数の推移」カードへ注釈を追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6905]
本日入力のデータにおいて、これまで想定していなかった「死亡日不明の死亡者」（１名）が出現しました。
この結果、「検査陽性者の状況」の死亡者数と「死亡日別による死亡者数の推移」の死亡者累計値が一致しないことになります。
そこで、「死亡日別による死亡者数の推移」カードに注釈を追加します。

- 追加注釈テキスト： `死亡日不明者はグラフから除いているため、累計値が「検査陽性者の状況」の死亡者数と一致しない`
※ 上記のテキスト内 `検査陽性者の状況` に `/cards/details-of-confirmed-cases/` へのリンクを貼ります。
- 追加注釈の位置：２番目

![スクリーンショット 2021-10-29 19 36 33](https://user-images.githubusercontent.com/14883063/139421076-ee9991c5-8502-4af2-9f9a-d71803003cba.png)

**Comment by Murayu0225** [comment]
このIssueやります。

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！よろしくお願いします！
