### ISSUE TITLE
[先行着手] Node.js@17.x 対応（放っておくと動かないおそれあり）

### ISSUE THREAD

**Issue by mcdmaster** [tokyo-metropolitan-gov/covid19#6923]
## 改善詳細 / Details of Improvement
- 遠からず、`Node.js` をバージョン `17` 以上にアップグレードするタイミングが訪れます
- 現行の構成でそれを行った場合、下記に示される問題が起きることがわかっています
- 根本的な解決策は、たとえば `Webpack` や `Vue` といったメジャーなコンポーネントの最新化でしょう
- ただしどれもすんなりとできるものではないため、必要に応じて段階的に、あるいはコンポーネントごとにアップグレードしていくのが適切です
- 以下は、その「必要に応じて」を先行実施するワークアラウンドの提案です

## スクリーンショット / Screenshot

こちらのページをご覧ください。
https://github.com/webpack/webpack/issues/14532
具体的には、`yarn dev` コマンドなどによる `Nuxt.js` の起動時に「証明書エラー」的なスタックトレースが吐かれ、アプリケーションが起動できなくなるという、けっこう深刻な事態を招くものです

## 期待する見せ方・挙動 / Expected behavior
- 上述のエラーを回避する
- `Node.js@17` 環境下でも、`Nuxt.js` がまるで何事もなかったかのように起動する
- 根本的解決策は、別途探ることとする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by munierujp** [comment]
v17はLTSバージョンではないので、アップデートするのであればv18になるのではないでしょうか？（e1b2227 でv14からv15をスキップしてv16にアップデートしたように）

**Comment by mcdmaster** [comment]
@munierujp なるほどです！
今回 `v17` で見られた本件も、正直なところ `Node.js` 側の意図を測りかねています…
結局、`v18` で復旧（？）すればそれはそれでオーケーです。
ただ、より高速なハッシュアルゴリズムのカスタム・デプロイなど、細かな要求が背景にあるという想定もできます。
そういった流れも横にらみしつつ、ゆるゆるとやってみます

**Comment by kaizumaki** [comment]
ご提案＆フォローありがとうございます！munieruさんのおっしゃるとおり、次のNode のアップデートはv18を予定しています。
いずれにせよ、ギリギリまでv16でねばるつもりではいるので 😅 、そんなに急がなくても大丈夫だと思ってます。

**Comment by kaizumaki** [comment]
@mcdmaster こちら、issueのタイトルとしては対応しない予定なので、一旦クローズしてもいいでしょうか？

**Comment by mcdmaster** [comment]
問題ありません。

ちなみに、話がズレますけれども `Nuxt3 + Vue3` へのアプローチとしては、`Bridge` という中間バージョンのフィージビリティチェックができないかどうか考え中です。
そういう意味では、テストケースを作って自動化するなどというのは、比較的早くに必要かもしれません。あ、既にあるのなら、それを使いたいです。最近ほとんど流れを追えておらずスミマセン…

**Comment by kaizumaki** [comment]
@mcdmaster ありがとうございます。ではこちらは一旦閉じますね。
テストツールは #5960 でRSpecを導入しましたが、それとは違う類いのものなのですかね？ご提案いただくのは自由なので、別途issueを立てていただくなどしてもらえるといいかなと思います！
