### ISSUE TITLE
陽性者CSVから発症日のデータが消えている

### ISSUE THREAD

**Issue by nnawata** [tokyo-metropolitan-gov/covid19#6941]
## 起こっている問題 / The Problem
- 「新型コロナウイルス陽性患者発表詳細」のデータから発症日が消えているようです
- URL: https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients.csv
- ２０２０年１０月頃以降の陽性者から発症日がはいっていたのが、いつの間にか消えています

復活していただきたい。

**Comment by kaizumaki** [comment]
@nnawata ご指摘ありがとうございます！元データを確認したところ、データは入っているのですが、変換処理の部分で不具合が出ているようです。
現在調査中ですので、しばらくお待ちください。

**Comment by kaizumaki** [comment]
@nnawata お待たせしました。不具合を修正し、データが復旧されました。ご確認いただけますでしょうか。

**Comment by nnawata** [comment]
早速ありがとうございます。
発症者データが復旧していることを確認しました。
