### ISSUE TITLE
[i18n] worker.vue 内の文字列をi18n化

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#695]
総合issue: #680 
（全体の方針については↑へ）

---
- `pages/worker.vue` の直打ちの文字列を`<i18n>`で定義するようにします。
- 各言語への翻訳はこちらにあります: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0

**Comment by cyblue9** [comment]
@MaySoMusician 

こちらのissue、"worker.vue"を<i18n>化するものですが、タイトルが"parent.vue"となっております！
修正お願いいたします！

**Comment by MaySoMusician** [comment]
@cyblue9 ご報告ありがとうございます！修正いたしました

**Comment by cyblue9** [comment]
@MaySoMusician 
 迅速な対応ありがとうございます！

**Comment by IkarosuTsubasa** [comment]
こちらを引き受けたいです！ まだ誰も作業してませんかな？

**Comment by MaySoMusician** [comment]
@IkarosuTsubasa あー申し訳ないです。一応ハッカソンの方で既に作業中です...
本日出した[i18n]の作業はひと通り割り当てが終わってしまっています...

**Comment by IkarosuTsubasa** [comment]
@MaySoMusician  はい、わかりました！
