### ISSUE TITLE
「検査陽性者の状況」のビジュアルに代替テキストを改善する

### ISSUE THREAD

**Issue by masuP9** [tokyo-metropolitan-gov/covid19#697]
## 改善詳細 / Improve details

`<svg>` 要素で実装された「検査陽性者の状況」に対して、`aria-label="検査陽性者の状況"` で実装されており、支援技術によっては内部のテキスト情報を取得することができないので、追加で代替となるテキストを設定する。

## スクリーンショット / Screenshot

<img width="445" alt="検査要請者の状況のビジュアルのスクリーンショット。「検査実施人数とその内訳として陽性者数（累積）、入院中、軽症・中毒者症、重症、死亡、退院の人数が表示されている」" src="https://user-images.githubusercontent.com/6724665/76137680-0c34f180-6083-11ea-9549-9cce8f2a5708.png">

## 期待する見せ方・挙動 / Expected behavior

中身のテキストも `aria-label` として追加し、 `role="img"` を追加する（svg に aria-label="のみ"）では支援技術に伝わらない可能性があるため。

```html
<svg role="img" aria-label="検査陽性者の状況: 検査実施人数xx人、うち陽性者数（累積）xx人、入院中xx人、軽症・中毒者症xx人、重症xx人、死亡xx人、退院xx人" />
```

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

ALL

**Comment by TomohiroHibino** [comment]
こちら未着手でしたら、プルリク作成させて頂きます！

**Comment by masuP9** [comment]
@TomohiroHibino おねがいします！
