### ISSUE TITLE
感染情報の csv にて、2021-11-30 の `陽性者数（累計）` が前日より下回っている

### ISSUE THREAD

**Issue by yasudanaoya** [tokyo-metropolitan-gov/covid19#6970]
## 起こっている問題 / The Problem
- タイトルのままです。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/43776161/144158892-227897b1-e496-4f51-9092-c705031903ae.png)

## 期待する見せ方・挙動 / Expected Behavior
- コードをまだ読めていないのですが、受け取った値がもしかしたら間違ってる？

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_details_testing_positive_cases.csv  をダウンロード
2. 643行目、E列を確認
3. 642行目、E列と比較する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@yasudanaoya ご指摘ありがとうございます！調査いたしますので、しばらくお待ちください。

**Comment by kaizumaki** [comment]
@yasudanaoya 状況がわかりました。現在、最新のお知らせにも載っているのですが、昨日の更新において、10月分の修正を反映しているそうです。（同一患者の重複や再検査で陰性が判明した事案等の削除、▲42件）
https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2021/12/01/20.html
この結果、陽性者累計が 11月30日の発生21件 – 上記削除42件 ＝ ▲21件 のマイナスとなっています。
こちら、カタログサイト上は注釈を追記してありました。
https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000089

というわけですので、ご確認いただけますでしょうか。

**Comment by yasudanaoya** [comment]
@kaizumaki 
なるほど、「その日に急に謎に感染者数が減った」ではなく、10月分の修正が 11/30 に適応されたため、ってことですね

ではバグではないですね！失礼しました

早急なご確認と連絡、ありがとうございます！
