### ISSUE TITLE
「オミクロン株情報」ボタンの設置

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6976]
「最新のお知らせ」の横のボタン群に「オミクロン株情報」ボタンを追加します。ボタン位置は一番左です。

![スクリーンショット 2021-12-04 9 55 33](https://user-images.githubusercontent.com/14883063/144690540-96733d1f-9594-4199-8373-2f6321f5e232.png)

ボタンテキスト：`オミクロン株情報`
リンク先：https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/henikabu/omicron_info.html
アイコン：`static/covid.svg`

※こちらは12/6（月）にリリースする予定です。

**Comment by knknk98** [comment]
こちら対応します！

**Comment by kaizumaki** [comment]
@knknk98 ありがとうございます！よろしくお願いします 🙏
