### ISSUE TITLE
棒グラフのスケールを見ている範囲に合わせて柔軟に変更する

### ISSUE THREAD

**Issue by hokacci** [tokyo-metropolitan-gov/covid19#6989]
## 改善詳細 / Details of Improvement
- 表示されているグラフのスケールが、これまでの最大の山に合わせているため、数値が下がった後に最近の傾向を読むことができない
- 棒グラフのスケールを見ている範囲に合わせて柔軟に変更する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/47231909/144843352-e4ea840f-8fd3-448f-9ec5-e4267f77e460.png)

## 期待する見せ方・挙動 / Expected behavior
- 棒グラフの横スクロールを行うと、見ている範囲に合わせてグラフのスケールが変更される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@hokacci ご提案ありがとうございます！そんなことができるのですね 👀  知らなかったです。どういった実装になるのか見てみて東京都のほうにも検討してもらいたく思いますが、ドラフトでPRを出してもらうことはできますでしょうか...？

**Comment by hokacci** [comment]
コメントを頂きありがとうございます。
できるかどうかは置いておいて、今のところ思ったことを書いただけですので、既に開発に参加している方から実行可能か、可能ならどういう方法がありそうか、コメントを頂ければ幸いです。
自分でも見てみますが、リポジトリの内容は今から見るので時間は掛かりそうです。

> @hokacci ご提案ありがとうございます！そんなことができるのですね 👀 知らなかったです。どういった実装になるのか見てみて東京都のほうにも検討してもらいたく思いますが、ドラフトでPRを出してもらうことはできますでしょうか...？

**Comment by hokacci** [comment]
@kaizumaki

**Comment by hokacci** [comment]
@kaizumaki 
ソースコードを見ながら、少し試しで作ってみました。
東京都にイメージを共有するには、この動画でどうでしょうか。

フロントエンドはほとんど触ったことがないので、もう１日程度調べつつしてからPR出そうと思っています。

![Animation](https://user-images.githubusercontent.com/47231909/144915165-ae59f1ad-3b86-4ad0-86f7-b4bc7dab4cf4.gif)

**Comment by hokacci** [comment]
PR出しました。
時系列のグラフは、実際にはそれぞれ、（ある程度まとまりつつも）別々のコンポーネントで実装されているため、変更は少し大きくなりそうです。
今の所、TimeBarChartコンポーネントのみ変更を加えていますが、その前に一度見ていただいて方針を決めたいと思っています。

**Comment by kaizumaki** [comment]
@hokacci ありがとうございます！東京都のほうに確認してもらいますので、しばらくお待ちくださいね。

**Comment by kaizumaki** [comment]
@hokacci 東京都のほうでPRのプレビューを見てもらいました。ぜひ採用したいそうです 🎉 
ただ、グラフの目盛りが自動で変更されたほうがよい方とそうでない方（これまでの変化を見たい方など）がいらっしゃるかもしれないため、目盛りを自動変更するかどうか選べるボタンを設置できないか、ということでした。
オートスケールのON/OFFボタンの実装ってできるでしょうか？

**Comment by hokacci** [comment]
可能だと思いますが、いくつかの選択肢があります。

1. スケール自動/固定を切り替えるトグルボタンを配置し、スクロールが行われたとき、トグルボタンが自動であればチャートの更新を行う
2. スケール調整ボタンとスケールをもとに戻すボタンを配置し、スクロールを行った後ユーザーがスケール調整ボタンを押すことでチャートの更新を行う/もとに戻すボタンを押してチャートの更新を行う

1でデフォルトは固定と考えていますが、トグルボタンの文言は良いのが思い浮かばないです。

**Comment by kaizumaki** [comment]
@hokacci ご提案ありがとうございます。ユーザーのアクションを必要とするボタン類はなるべく少なくしたいというのが希望です。とすると、「1でデフォルトは固定」でしょうか。文言は少し考えますね。

一方で、グラフの全体的な傾向がわかるようにしておきたいという要望もあり（それに答える妥協案がトグルスイッチということになるわけですが）、日付フィルターを実装してはどうかという話も出ています。
そちらはだいぶまえに #4208 で一度検討されたのですが、グラフに大量の変更が加えられる過渡期だったということもあって実現なりませんでした。
もし、この日付フィルターを実装できれば、オートスケール用のトグルスイッチは不要となると思います。
そういうこともあって、このissueではなるべく重い実装にはしない方向にしたいです。

いずれにせよ、これだけ長期化してくると、横スクロールだけでは厳しくなりそうなんですよね。

**Comment by kaizumaki** [comment]
@hokacci その後東京都と話し合いまして、横スクロールを廃止し、日付範囲フィルターを実装しましょう、ということになりました。
以下を参考にしました。

【神奈川県版サイト】日付範囲フィルター＋オートスケール
https://www.pref.kanagawa.jp/osirase/1369/

【福岡市版サイト】日付範囲フィルター＋オートスケール＋日付範囲トグルスイッチ
https://stopcovid19.codeforfukuoka.org/

いずれもオートスケールも同時に実現しています。

長いことお世話になった横スクロールと決別するのは寂しい感じもしますが、致し方なしですね。
@hokacci さんの提案とはまた角度が違ってはくるのですが、目指すところは共通していると思っています。何より、グラフの見直しのきっかけになりました。ありがとうございます。
日付範囲フィルター実装については新たにissueを立てることにしますが、もしよければコメントいただけると嬉しいです。

**Comment by hokacci** [comment]
日付範囲フィルターの実装見ました。
良いですね！

ありがとうございました。
