### ISSUE TITLE
新型コロナ・オミクロン株コールセンターのお問い合わせ内容の修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#6992]
「お問い合わせ先一覧」ページの１項目目「新型コロナ・オミクロン株コールセンター」のお問い合わせ内容を修正します。
現在の表現をより分かりやすい表現に修正するものです。

修正前：`新型コロナウイルス感染症の予防・検査・医療に関すること`
↓
修正後：`感染の予防に関することや、心配な症状が出た時の対応など、新型コロナウイルス感染症に関する相談`

**Comment by knknk98** [comment]
こちら対応します！
