### ISSUE TITLE
最新感染動向のビジュアライズセクションのタイトルを `h3` 要素でマークアップする

### ISSUE THREAD

**Issue by masuP9** [tokyo-metropolitan-gov/covid19#702]
## 改善詳細 / Improve details

最新感染動向のビジュアライズセクションのタイトル `.v-toolbar__title` を `h3` 要素でマークアップする。

メリット: 文書構造が明確になり、文書構造を利用する支援技術（スクリーンリーダーなど）で利用する際のり弁性があがる。

## スクリーンショット / Screenshot

<img width="289" alt="該当箇所のスクリーンショット。「検査陽性者の状況」というテキストに div.v-toolbar__title というCSSのセレクタがポップアップで表示されている" src="https://user-images.githubusercontent.com/6724665/76138442-86697400-608b-11ea-8edb-3035c9d6f19b.png">

## 期待する見せ方・挙動 / Expected behavior

`div` ではなく `h3` でマークアップする。可能であれば、セクションごとに一意の `id` 属性を触れると、URLで共有しやすくなる。

```html
<h3 class="v-toolbar__title" id="confirm-cases-table">検査陽性者の状況</h3>
```

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

ALL

**Comment by af12066** [comment]
対応いたします!
