### ISSUE TITLE
Metro data is not updated for 13 days

### ISSUE THREAD

**Issue by RuijingZ** [tokyo-metropolitan-gov/covid19#7038]
## 起こっている問題 / The Problem
- Metro data is not updated for 13 days

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/68354122/148300564-e67efeb8-6105-4611-82a4-a7cc60b091d2.png)

## 期待する見せ方・挙動 / Expected Behavior
- Could you kindly update this dataset? Thank you!

**Comment by kaizumaki** [comment]
@RuijingZ Thanks for pointing out the issue!
That data `metro.json` will be updated tomorrow. Please wait for a moment.

**Comment by kaizumaki** [comment]
The data `metro.json`  has been updated in the https://github.com/tokyo-metropolitan-gov/covid19/commit/e0adbd13fe6a6c6499428b9524a31e9859815853 commit. So I will close this issue.
