### ISSUE TITLE
Loading インジケーターの実装

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#71]
対応 Trello: 
https://trello.com/c/oWCqXj18/55-%E3%83%AD%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%A4%E3%83%B3%E3%82%B8%E3%82%B1%E3%83%BC%E3%82%BF%E3%83%BC%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3

**Comment by osoken** [comment]
https://vuetifyjs.com/ja/components/cards
グラフ系コンポーネントのベースになっている `v-card` コンポーネントに `loading` という属性があり、使えるかも

**Comment by saladdays** [comment]
おお、カードの読み込みオシャレですね！

一応簡易的にサイト全体のローディング作りました。今の感じだとほぼ表示されないで済みそうですが！

[vue-spinner](https://github.com/greyby/vue-spinner) の `scale-loader` を `#00A040` を指定して利用していただければと思います。
👆vue-spinnerにメチャクチャなこだわりがあるわけではないので、似たローダーを使っても構いません。

デザインデータ👇（Figma）
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=296%3A377

![image](https://user-images.githubusercontent.com/1301149/75628192-ff934200-5c19-11ea-880e-f286604fbaa6.png)

**Comment by hkomamiy** [comment]
やります。

**Comment by halsk** [comment]
@hkomamiy さん、ありがとうございます！！

**Comment by hkomamiy** [comment]
レビューお願いします。本業のため、夜戻ってきます。
■PR
https://github.com/tokyo-metropolitan-gov/covid19/pull/129
