### ISSUE TITLE
flowの図を印刷するための印刷ボタンレイアウト

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#710]
## 改善詳細 / Improve details
- https://github.com/tokyo-metropolitan-gov/covid19/pull/534 を受けて、/flow ページに印刷ボタンを配置する

## 期待する見せ方・挙動 / Expected behavior
|PC|スマホ|
|---|---|
|![image](https://user-images.githubusercontent.com/1301149/76168108-b742c980-61af-11ea-95eb-5668ad2f96e2.png)|![image](https://user-images.githubusercontent.com/1301149/76168109-bc077d80-61af-11ea-9213-6d92d7bf5a73.png)|

- 印刷ボタンを押したら https://github.com/tokyo-metropolitan-gov/covid19/pull/534 のページが展開される
- スマホ版は対応プリンタを持っている人が少数であること／スペースに限りがあることを考慮して、認知優先度を下げてアイコンのみのボタン表示をする

## 補足
PC/スマホともに

**Comment by yubachiri** [comment]
こちら着手します！

**Comment by amotarao** [comment]
現状のプリントページの特徴

- 開いたらすぐに印刷メニューが開く
- 他のページへ戻るリンクがない


リンクの開き方について検討する必要がありそうです。

- 同じタブで開く（デフォルト）
- 新しいタブで開く
- window.open で開く

同じタブで開く場合、ブラウザバックでしか戻れません。

**Comment by yubachiri** [comment]
> リンクの開き方について
こちら一旦通常の遷移で実装してしまいましたが、使い勝手悪いです。
別タブ/別ウィンドウいかがいたしましょうか？

**Comment by yokinist** [comment]
「新しいタブで開く」がシンプルでいい気がしていますが、なにか懸念点あったりします？

**Comment by amotarao** [comment]
新しいタブの懸念点、特に思いつきません
window.open のほうが一時的なウィンドウであることが分かりやすい気もしますが、_blank とほぼ変わらなさそうです
_blank が一番シンプルそうですね

**Comment by yubachiri** [comment]
特に思い当たらないので、「新しいタブで開く」形で実装いたします！
