### ISSUE TITLE
モニタリング項目内にあるグラフが見切れてしまう

### ISSUE THREAD

**Issue by Murayu0225** [tokyo-metropolitan-gov/covid19#7110]
## 起こっている問題 / The Problem
- モニタリング項目にあるグラフを表示するとグラフが見切れる

## スクリーンショット / Screenshot

<img width="551" alt="スクリーンショット 2022-02-18 21 30 06" src="https://user-images.githubusercontent.com/37988559/154685832-33a55633-1cba-46ff-a0bf-d32355b08a71.png">

## 期待する見せ方・挙動 / Expected Behavior
- 見切れずに正常に表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 通常通りアクセスしてモニタリング項目内にあるグラフを確認する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@Murayu0225 ご指摘ありがとうございます！
コンソールを見ると `Uncaught RangeError: Invalid time value` のエラーを吐いてますね...。
![スクリーンショット 2022-02-18 22 21 51](https://user-images.githubusercontent.com/14883063/154690648-e7db5d0a-7580-4fe8-8cf4-bdf2ad9b2b1d.png)

**Comment by kaizumaki** [comment]
なるほど、317行目の `isBetween` の第３引数はnullだと危なそうですね。日次なので `'day'` と入れるべきのようです。
```
return date.isBetween(this.startDate, this.endDate, 'day', '[]')
```
