### ISSUE TITLE
「陽性患者の属性」の「日付」を「公表日」に変える

### ISSUE THREAD

**Issue by yamada-github-account** [tokyo-metropolitan-gov/covid19#712]
## 改善詳細 / Improve details
- 「陽性患者の属性」における列名の「日付」が何の日付なのかはっきりしない（公表日？・診断日？・入院日？・発症日？）ので、元データの列名「公表_年月日」に倣い、「公表日」とする

## 期待する見せ方・挙動 / Expected behavior
- 「陽性患者の属性」における一番左の列名を「公表日」に変える

**Comment by konu96** [comment]
こちら対応します。

**Comment by ocean3fish** [comment]
@konu96 ご対応ありがとうございます！
この変更が問題無いか、現在関係者に確認中です。

**Comment by ocean3fish** [comment]
変更問題なしとの確認が取れました！
マージされるまでもう少々お待ちください。
