### ISSUE TITLE
「モニタリング項目」カード内のリンクボタンのテキストを修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7160]
「モニタリング項目」カード内のリンクボタンのテキストをリンク先ページに合わせるよう変更します。

修正前： `国のステージ判断のための指標`
↓
修正後： `国の新しいレベル分類のための指標`

![スクリーンショット 2022-03-28 18 07 50](https://user-images.githubusercontent.com/14883063/160365618-83a2cc5c-1872-4aa8-811e-e16e52c33dcb.png)

**Comment by Reinexxx** [comment]
@kaizumaki
初めまして！
こちら出来そうなので対応させて頂きます！
