### ISSUE TITLE
130001_tokyo_covid19_patients_2022.csvについて

### ISSUE THREAD

**Issue by pizzsgw256** [tokyo-metropolitan-gov/covid19#7193]
## 起こっている問題 / The Problem
2022/03/31にダウンロードした2022/01/01～2022/03/30までの行数は359,600行
でしたが、2022/04/05にダウンロードした同期間の行数は859,336となぜか減ってます。
例えば、No「573635」の行が2022/04/05にダウンロードしたCSVでは消えています。
どうしてしまったのでしょう？

**Comment by kaizumaki** [comment]
@pizzsgw256 ご指摘ありがとうございます！
東京都福祉保健局のサイトにこちら↓が掲載されているのですが、 `令和4年3月31日修正（2月分　削除234人）` となっています。
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/info/todokedehcyouseisya.html
毎月修正を入れているらしいので、その差分となっているようです。リンク先をご覧いただけると助かります 🙏

**Comment by pizzsgw256** [comment]
早速の返信＆保健局のサイト照会ありがとうございます。
データ修正があるならどこかに情報があるはずと探したのですが、保健局のサイトにあるとは考え及びませんでした。

**Comment by kaizumaki** [comment]
こちらは解決ということでクローズとしますね。
