### ISSUE TITLE
トップページの time 要素に datetime 属性がない、または datetime 属性値がISO8601形式になっていない

### ISSUE THREAD

**Issue by oti** [tokyo-metropolitan-gov/covid19#721]
## 改善詳細 / Improve details
- トップページの「都内の最新感染動向」の最新更新日時の time 要素に datetime 属性がない
- トップページの「最新のお知らせ」の日付の time 要素に datetime 属性がない
- トップページの各グラフの更新日時の time 要素の datetime 属性値がISO8601形式になっていない

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-07 16 56 54](https://user-images.githubusercontent.com/710216/76139606-f8928680-6094-11ea-947b-93c38602282a.png)
![スクリーンショット 2020-03-07 16 47 42](https://user-images.githubusercontent.com/710216/76139607-fc260d80-6094-11ea-8084-ad59116c130c.png)

![スクリーンショット 2020-03-07 16 57 03](https://user-images.githubusercontent.com/710216/76139620-398a9b00-6095-11ea-9527-bdfec6a07773.png)
![スクリーンショット 2020-03-07 16 47 55](https://user-images.githubusercontent.com/710216/76139621-3abbc800-6095-11ea-8160-f13e1ee3faa9.png)

![スクリーンショット 2020-03-07 16 57 19](https://user-images.githubusercontent.com/710216/76139625-3e4f4f00-6095-11ea-9039-742e436e0437.png)
![スクリーンショット 2020-03-07 16 48 07](https://user-images.githubusercontent.com/710216/76139627-40191280-6095-11ea-8dcc-c4cacdb463d9.png)

## 期待する見せ方・挙動 / Expected behavior

1. 日時を扱う time 要素ではISO8601形式の datetime 属性値をつける
2. time要素内のテキストも読み上げを意識して `2020年3月5日8時` などの漢字表記に変換する

datetime属性値で許容できる書式には `/` がありませんので、例えば `2020/03/05 8:00` は `2020-03-05T08:00:00` などとする必要があります。参考: [&lt;time&gt; - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/time#Valid_datetime_Values)

また、time 要素内のテキストについても、スラッシュ区切りの日付表示はスクリーンリーダーの読み上げであまりヒューマンリスナブルにならないので、できれば年月日と時分が漢字で書かれていた方が優しいです。

time 要素内のテキストはそのままで、 `aria-label` 属性を用いてスクリーンリーダー向けに専用のテキストを提供する方法もあります。i18n対応のしやすい方法を選択すると良いと思います。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by af12066** [comment]
やってみます

**Comment by oti** [comment]
@af12066 お願いします！
