### ISSUE TITLE
html 要素の lang 属性値の書式が間違っている

### ISSUE THREAD

**Issue by oti** [tokyo-metropolitan-gov/covid19#723]
## 改善詳細 / Improve details
- html 要素の `lang="ja_JP"` の書式が不正なのでこれを修正する

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-07 17 36 01](https://user-images.githubusercontent.com/710216/76140086-1e6e5a00-609a-11ea-9a35-bf962a622d33.png)

## 期待する見せ方・挙動 / Expected behavior
- 値をアンダースコアではなくハイフン繋ぎの書式に修正する `ja_JP` -> `ja-JP`

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by konu96** [comment]
やりたいです。

**Comment by oti** [comment]
@konu96 お願いします！

**Comment by konu96** [comment]
と思いましたが、こちら既に対応されていました。本番に出ていないけど、開発では次のようになっています。
https://github.com/konu96/covid19/blob/6500290d1dae8f96e71fc0de628fc23b49e82957/nuxt.config.ts#L97

**Comment by oti** [comment]
@konu96 https://github.com/konu96/covid19/commit/3062f62860fedc8a4960b72ced05600a2786acfa で修正されてましたね！　失礼しました。ありがとうございました！

**Comment by oti** [comment]
対応済みということで close しちゃいますー
