### ISSUE TITLE
最新のお知らせのリンク一覧をリストでマークアップする

### ISSUE THREAD

**Issue by masuP9** [tokyo-metropolitan-gov/covid19#724]
## 改善詳細 / Improve details

最新のお知らせのリンク一覧が `<div>` でマークアップされているためリスト要素（この場合は `<ul>` ）でマークアップする

リスト要素でマークアップすることで、リスト要素のセマンティクスを利用する支援技術はリスト要素の数を読み上げたり、最後の要素にジャンプしたりすることができる。

## スクリーンショット / Screenshot

<img width="606" alt="該当要素のスクリーンショット" src="https://user-images.githubusercontent.com/6724665/76140187-14992680-609b-11ea-94f0-3ac516bc057f.png" />

## 期待する見せ方・挙動 / Expected behavior

```html
<ul>
  <li>
    <a href="https://www.2020games.metro.tokyo.lg.jp/news/2020/0305_3108.html" target="_blank" rel="noopener" class="WhatsNew-item">
      <time class="WhatsNew-item-time px-2">2020/03/05</time>
      <span class="WhatsNew-item-link">マスク及び消毒液を寄贈しました！</span>
    </a>
  </li>
</ul>
```

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by tatsuki26** [comment]
こちら着手させていただきたいです！

**Comment by masuP9** [comment]
@tatsuki26 おねがいしますー

**Comment by tatsuki26** [comment]
PR出しました！
