### ISSUE TITLE
Prettier関連の改善

### ISSUE THREAD

**Issue by Mogyuchi** [tokyo-metropolitan-gov/covid19#7247]
## 改善詳細 / Details of Improvement
- `.prettierignore`ファイルの追加
- コミット時に Prettier を動かす
- [VSCode] ファイル保存時に Prettier がかかるようにする

## 期待する見せ方・挙動 / Expected behavior
- フォーマット不要なファイル(特に`.nuxt/`ディレクトリ内)がフォーマットされない
- lint-staged で `eslint`・`stylelint` が走ったあとに `prettier` も走る
- [VSCode] ファイル保存時にフォーマットする。

**Comment by Mogyuchi** [comment]
> - コミット時に Prettier を動かす

https://github.com/tokyo-metropolitan-gov/covid19/pull/30/ では対象とするファイルの拡張子を json,md に限定していたようですが、全てを対象にしたいと思います。

> - [VSCode] ファイル保存時に Prettier がかかるようにする

https://github.com/tokyo-metropolitan-gov/covid19/pull/382/ に関連してますが、`"editor.formatOnSave": false` が設定されているので PR の期待(save時にフォーマッターがかかるようにする)通りに動作していないように思われます。

**Comment by Mogyuchi** [comment]
`"editor.formatOnSave": false`が原因というより ESLintを経由しているからフォーマットされないファイルが存在しているようでした。

> > * [VSCode] ファイル保存時に Prettier がかかるようにする
> 
> #382 に関連してますが、`"editor.formatOnSave": false` が設定されているので PR の期待(save時にフォーマッターがかかるようにする)通りに動作していないように思われます。

**Comment by kaizumaki** [comment]
@Mogyuchi ご提案ありがとうございます！（反応が遅くなりました 🙇 ）開発環境の整備は忘れがちなので助かります！
