### ISSUE TITLE
読み込みエラーの実装

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#73]
対応Trello
https://trello.com/c/GKjBNSE7/56-%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF%E3%82%A8%E3%83%A9%E3%83%BC%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3

**Comment by mikkame** [comment]
jsonは組み込みになったのでこれはクローズでいいですか？

**Comment by halsk** [comment]
はいー
