### ISSUE TITLE
FOR_DEVELOPERS.md のdocker compose v2 対応

### ISSUE THREAD

**Issue by goki90210** [tokyo-metropolitan-gov/covid19#7356]
お久しぶりです。本業が忙しくてほとんどみられてなかったのですが…。

## 改善詳細 / Details of Improvement

- FOR_DEVELOPERS.md のdocker-composeの説明をv2にする。

docker-composeコマンドが近々捨てられるので、 FOR_DEVELOPERS.mdの説明もDocker Compose Version 2用に書き換えても良いのではないでしょうか。
https://qiita.com/zembutsu/items/d82b2ae1a511ebd6a350

## スクリーンショット / Screenshot
Docker Compose Version 2で実行しても特に問題なさそうに見えます。
![image](https://user-images.githubusercontent.com/30145857/175754490-7d250237-8220-4f55-ac77-25649cc0c1ba.png)

## 動作環境・ブラウザ / Environment
特に指定なし。

**Comment by kaizumaki** [comment]
@goki90210 ご提案ありがとうございます！お久しぶりのフォローも嬉しいです！
おっしゃる通り、dockerコマンド書き換えたほうがいいですね。

**Comment by Foo-x** [comment]
現在の docker compose v2 はプロキシ下でうまく動かない問題があります。
https://github.com/docker/compose/issues/9034

プロキシ環境でOSS開発をしている方がどの程度いらっしゃるかわかりませんが、念のため情報共有です。

**Comment by shotikubai** [comment]
やります！
質問なのですがそのプロキシ環境のことは記したほうがいいのでしょうか？

**Comment by kaizumaki** [comment]
@shotikubai ありがとうございます！よろしくお願いします！ 🙏 
プロキシ環境のことはdocker側の都合なので、ここでは書かなくて大丈夫です。
