### ISSUE TITLE
firefox(102.0.1)にて、サイトマップの「お子様をお持ちの方へ」の項目が崩れている

### ISSUE THREAD

**Issue by toritree** [tokyo-metropolitan-gov/covid19#7373]
## 起こっている問題 / The Problem

- サイトマップの「お子様をお持ちの方へ」の項目が崩れている
## スクリーンショット / Screenshot

![アイコンが崩れている](https://user-images.githubusercontent.com/65443082/178408522-1ffd9672-9c7d-43e0-bd05-f427620dd6f0.png)

![デバックツール](https://user-images.githubusercontent.com/65443082/178408713-122af389-b5aa-4a08-b57b-df31e3e1721f.png)

## 期待する見せ方・挙動 / Expected Behavior

- ピクトグラムの大きさが文字と同じ大きさになること

## 起こっている問題の再現手段 / Steps to Reproduce

1. 「https://stopcovid19.metro.tokyo.lg.jp/sitemap/」をfirefoxで開く

## 動作環境・ブラウザ / Environment

- Windows11
-  Firefox(102.0.1)

**Comment by kaizumaki** [comment]
@toritree ご報告いただきありがとうございます！私の手元（macOS/Firefox）でも再現しました。
こちら対応しますね！
