### ISSUE TITLE
陽性者の属性に、ワクチン接種歴と、入院日と退院日

### ISSUE THREAD

**Issue by knoajp** [tokyo-metropolitan-gov/covid19#7385]
## 改善詳細 / Details of Improvement

- 陽性患者発表詳細(陽性者の属性)に、ワクチン接種歴と、入院日と退院日を追加

新たな変異株による入院率の変化や、入院日数の変化などを知るのに大変有用。
ワクチン接種歴については、 #6662 にて難しいということは承知していますので、むしろ別の窓口に要望すべき話かもしれませんが。ただし「情報発信の効果」については、都のモニタリング会議や厚労省のアドバイザリーボードに出るような専門家は漏れなく飛びつく情報になるものと思います。

**Comment by kaizumaki** [comment]
@knoajp ご提案ありがとうございます。東京都に確認にまわしますので、しばらくお待ちください。

**Comment by kaizumaki** [comment]
たいへんお待たせしました。東京都から以下のように回答がきました。やはり今ワークフローを変更するのは難しいようです。。

> （東京都からの回答）
> 
> ・現在、オミクロン株の特徴に合わせた医療機関や保健所の更なる負担軽減への対応が、国の新型コロナウイルス感染症対策本部等等で進められています。
> 
> ・8月4日に開催された同本部での決定では、更なる負担軽減のため、発生届の届出項目からワクチン接種回数を削減することが可能となりました。
> 
> ・こうした中、各陽性者のワクチン接種回数や入退院日を追加するための事務フローを構築することは、保健所や医療機関の負担の増加につながる可能性もあり、現時点では対応が困難です。
> 
> 　御提案いただいたところ大変申し訳ございませんが、御理解のほどどうぞよろしくお願いいたします。

**Comment by knoajp** [comment]
ただでさえ負担増となる提案を、とりわけ多忙を極める時期に打診してしまい、気まずく思っていたところです。

入院の逼迫(数字上の7094床ではなく、実質的には4000床くらいが限界でしょう)を、早い段階から予測できれば、現場の判断にも資するものと思いましたが、第7波も下り坂となった今となっては、「今回の波で十分な集団免疫を得たことから、もう今後はそんな心配をするほどの波は来ないのではないか？」とも期待しています。

ご確認いただき、ありがとうございました。

**Comment by kaizumaki** [comment]
@knoajp コメントありがとうございます。陽性者調査については国の方針も変わっていくようなニュースも聞こえてきますし、それに従いつつ自治体がどこまでできるかというところも難しいなあと思う次第です。
こちらのissueは回答済みということでクローズいたしますね。
