### ISSUE TITLE
github actions/Audit staging対象のurlをfirebaseに修正

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7388]
## 改善詳細 / Details of Improvement

- ホスティングがNetlifyからFirebaseに移行したのですが、Audit stagingのgithub actionsにnetlifyのurlが残っていたので、firebaseのものに修正します。

## 期待する見せ方・挙動 / Expected behavior

https://github.com/tokyo-metropolitan-gov/covid19/blob/fc898d31cbf7449dbbbe4150ff5d06b98b0513e9/.github/workflows/audit-staging.yml#L25

ここを `https://stopcovid19-tokyo-staging.web.app/` に変更する。

**Comment by kikd** [comment]
修正作業やりたいです✋

**Comment by kaizumaki** [comment]
@kikd ありがとうございます！ぜひお願いします！ 🙏

**Comment by kikd** [comment]
別件の質問となり恐縮です。
docs/en/FOR_DEVELOPERS.md などの多言語向け開発ドキュメントのURLもnetlifyのままになっております。  
これらの修正は必要でしょうか？

**Comment by kaizumaki** [comment]
@kikd おっと、気づいておらずでした... 👀 ご指摘感謝です！
もしよろしければ、別途issueを立てていただけると嬉しいのですが、お願いしてもいいでしょうか...？

**Comment by kikd** [comment]
@kaizumaki わかりました！夕方以降になりそうですが別途issue作成します！
