### ISSUE TITLE
推奨ウェブブラウザの一覧を順序無しリストに変更

### ISSUE THREAD

**Issue by sorairolake** [tokyo-metropolitan-gov/covid19#739]
## 改善詳細 / Improve details
https://github.com/tokyo-metropolitan-gov/covid19/blob/53c0c44827948e11b9a77af4b979742bb4d2e35a/pages/about.vue#L11-L22
推奨ウェブブラウザの一覧が`<br>`要素による擬似的なリストになっていますが、`<ul>`要素と`<li>`要素による順序無しリストに変更した方が良いと思います。

## 期待する見せ方・挙動 / Expected behavior
```html
<ul>
  <li>Microsoft Edge 最新版</li>
  <li>Mozilla Firefox 最新版</li>
  <li>Google Chrome 最新版 (Windows 10以上)</li>
  <li>Apple Safari (macOS) 最新版</li>
  <li>Opera Software ASA Opera 最新版</li>
</ul>
```

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by sorairolake** [comment]
このissueとは直接関係は無いですが、*Safari*と*Opera*は正式名称に開発元の名称を含まないようなので、以下のように変更しても良いと思います。

* Apple Safari → Safari
* Opera Software ASA Opera → Opera

**Comment by DJYoko** [comment]
こちらやってみてよいでしょうか

**Comment by DJYoko** [comment]
プルリク作成しました
https://github.com/tokyo-metropolitan-gov/covid19/pull/753

**Comment by DJYoko** [comment]
いくつかご指摘いただいた箇所を改めました
https://github.com/tokyo-metropolitan-gov/covid19/pull/753

**Comment by DJYoko** [comment]
こちら、ここまでやって気づいたのですが、
モバイルに関する表記もあるとベターなのかもしれませんね
サファリとクロムの表記を以下のようにすればいいかと思います
- Safari 最新版 (macOS, iOS)
- Google Chrome 最新版 (Windows 10以上, Android 8.0以上) 

他にご意見ある方いらっしゃればご記入ください

**Comment by kaizumaki** [comment]
@DJYoko モバイル表記の件、ご指摘ありがとうございます！もしかしたら別issueにしたほうがいいかもしれません。

**Comment by DJYoko** [comment]
おっしゃる通りですね
本件はあくまでマークアップ様式の改変に主眼を置いた方が話がシンプルです
当該のスマートフォン表記の件、別途 issue を発行しました

**Comment by DJYoko** [comment]
他の皆さんからご指摘いただいた内容にてプルリク更新されております
https://github.com/tokyo-metropolitan-gov/covid19/pull/753
適宜マージお願いします
