### ISSUE TITLE
異常系ページの実装

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#74]
対応 Trello
https://trello.com/c/tYC7Ev0g/57-%E7%95%B0%E5%B8%B8%E7%B3%BB%E3%83%9A%E3%83%BC%E3%82%B8%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3

**Comment by saladdays** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/79
こちらに統合
