### ISSUE TITLE
単位「件」の英訳を使用箇所によって異なるワードに振り分ける

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7410]
東京都からの依頼により、単位「件」に対する英訳を使用箇所によって「tests」「cases」「calls」「consultations」に振り分けます。

## 変更箇所
- 注目の指標
  - 「XXXX年XX月XX日の患者の発生状況等」
    - 都外からの持込検体による陽性数：単位なし→cases
  - 「モニタリング項目」
    - (2)7119（東京消防庁救急相談センター）における発熱等相談件数：tests→calls
    - (5)救急医療の東京ルールの適用件数：tests→cases
  - 「東京都発熱相談センターにおける相談件数」
    - カード右上の大文字数値：tests→consultations
  - 「新型コロナコールセンター相談件数」
    - カード右上の大文字数値：tests→calls
- モニタリング項目
  - 「モニタリング項目(2)#7119における発熱等相談件数」
    - カード右上の大文字数値：tests→calls
  - 「モニタリング項目(5)救急医療の東京ルールの適用件数」
    - カード右上の大文字数値：tests→cases

![2022年8月7日の患者の発生状況等](https://user-images.githubusercontent.com/14883063/183319411-d05d2d26-fab7-42b4-83dd-194b764d7330.png)

![モニタリング項目](https://user-images.githubusercontent.com/14883063/183319474-bdca234c-0d52-4bba-b9ec-2b27e469b705.png)

![東京都発熱相談センターにおける相談件数](https://user-images.githubusercontent.com/14883063/183319499-0a02c46f-b8e3-4ad8-b326-366196fe9cc1.png)

![新型コロナコールセンター相談件数](https://user-images.githubusercontent.com/14883063/183319520-62640d54-6d33-42aa-8735-eaff9614383c.png)

![モニタリング項目(2)](https://user-images.githubusercontent.com/14883063/183319533-714f98af-443c-42f4-ab26-eb969eb274d9.png)

![モニタリング項目(5)](https://user-images.githubusercontent.com/14883063/183319544-ccceebf1-4724-4249-adbd-a6ab657a635d.png)

**Comment by Murayu0225** [comment]
このIssueやります！

**Comment by kaizumaki** [comment]
#7417 #7420 をマージしましたので、こちらのissueは解決済みとしてクローズします。
