### ISSUE TITLE
iOS VoiceOverだと、日付指定スライダーの値を変えても、スライダーのラベルおよびoutput要素の中身が変わらない

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#7468]
## 起こっている問題 / The Problem

- 掲題通り。iOS VoiceOverだと、日付指定スライダーの値を変えても、スライダーのラベルおよびoutput要素の中身が変わらない（グラフの中身は変化する）

## スクリーンショット / Screenshot

https://user-images.githubusercontent.com/17713513/188339024-abd71cf1-1300-4f72-858a-a6e81bba59f7.mov

## 期待する見せ方・挙動 / Expected Behavior

- スライダーの移動と、スライダのラベルおよびoutput要素が連動する

## 起こっている問題の再現手段 / Steps to Reproduce

- iOS VoiceOverでスライダーを操作する

## 動作環境・ブラウザ / Environment

iOS Safari + VoiceOver

**Comment by heech0228** [comment]
こちら、もうすでに対応中でしょうか？
対応中でなければ
[vuejs/vue/#6444](https://github.com/vuejs/vue/issues/6444)

こちらの対応で対応可能かと思いますのでプルリクエストを出しても良いでしょうか

**Comment by kaizumaki** [comment]
@heech0228 おお！ありがとうございます！ぜひぜひお願いします！ 🙏
