### ISSUE TITLE
日毎の病床使用率等／日毎の患者の発生状況等は、divにaria-labelがついているのはトリでよさそう

### ISSUE THREAD

**Issue by magi1125** [tokyo-metropolitan-gov/covid19#7469]
## 改善詳細 / Details of Improvement

- 日毎の病床使用率等／日毎の患者の発生状況等は、divにaria-labelがついているのはトリでよさそう。見出しで概要は既に言えているのと、roleなしのdiv要素にaria-labelを指定しても読み上げには使用されないため。
  - https://www.tpgi.com/short-note-on-aria-label-aria-labelledby-and-aria-describedby/
  - https://www.w3.org/TR/using-aria/#practical-support-aria-label-aria-labelledby-and-aria-describedby

## 期待する見せ方・挙動 / Expected behavior

- div要素に付与されているaria-labelを取り除く
  - https://stopcovid19.metro.tokyo.lg.jp/
  - https://stopcovid19.metro.tokyo.lg.jp/cards/medical-care-summary/
  - https://stopcovid19.metro.tokyo.lg.jp/cards/infection-summary/

## 動作環境・ブラウザ / Environment

すべて

**Comment by Murayu0225** [comment]
こちらやります．
