### ISSUE TITLE
ワクチン接種数及び接種率（都内全人口・累計）の左軸をオートスケール化させる

### ISSUE THREAD

**Issue by Murayu0225** [tokyo-metropolitan-gov/covid19#7475]
## 改善詳細 / Details of Improvement

- 「ワクチン接種数及び接種率（都内全人口・累計）」もオートスケール化させるのも良いと思います．

## スクリーンショット / Screenshot

| 対応前 | 対応後 |
| :--: | :--: |
| <img width="535" alt="スクリーンショット 2022-09-09 22 58 16" src="https://user-images.githubusercontent.com/37988559/189367671-7896072d-cf1c-4d83-9638-cddf7f633bb9.png"> |  <img width="531" alt="スクリーンショット 2022-09-09 22 58 24" src="https://user-images.githubusercontent.com/37988559/189367870-9fb266c2-7805-4e2f-9f20-a0da2644558b.png"> |
| <img width="538" alt="スクリーンショット 2022-09-09 22 57 26" src="https://user-images.githubusercontent.com/37988559/189368091-f6ad670a-d268-480b-ba0a-e131d82d9410.png"> | <img width="541" alt="スクリーンショット 2022-09-09 22 57 36" src="https://user-images.githubusercontent.com/37988559/189368270-fc97444f-e90a-405b-a33b-639f94dbc489.png"> |
## 期待する見せ方・挙動 / Expected behavior

- スクリーンショットの通り

## 動作環境・ブラウザ / Environment

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
@Murayu0225 ご提案ありがとうございます！言われてみればなんでワクチンのグラフはオートスケールを実装しなかったのか、もはや覚えていないのですが 😅 たしかにご提案のとおりでよさそうです。
ともあれ、見た目の変更を伴いますので、東京都に確認に回しますね。しばしお待ちください 🙏

**Comment by kaizumaki** [comment]
@Murayu0225 東京都から以下回答がありました。

> ワクチン接種率グラフの縦軸は、全人口に対してどこまで接種が進んでいるかを分かりやすくするために固定しており、
> 縦軸のオートスケール化で拡大できる期間がグラフの当初期間のみと限定的であることから、
> 御提案いただいたところ大変申し訳ありませんが、今回は実装を見送らせていただきます。

私もすっかり忘れていたのですが、ワクチン接種率100%に向けてどの段階にあるかを分かりやすくするためにオートスケール対象外とした、ということのようです。

せっかくの提案でしたのにすみません、こちらのissueはクローズとしますね。

**Comment by Murayu0225** [comment]
なるほど､､､
ありがとうございます！
