### ISSUE TITLE
データ項目定義書のリンクが４０４エラー

### ISSUE THREAD

**Issue by nnawata** [tokyo-metropolitan-gov/covid19#7498]
## 起こっている問題 / The Problem

オープンデータカタログサイト「東京都_新型コロナウイルス陽性患者発表詳細」に掲載されている以下のリンクURLが４０４エラーです。
（参考）新型コロナウイルス感染症対策に関するオープンデータ項目定義書　https://www.code4japan.org/activity/stopcovid19#od_spec

**Comment by kaizumaki** [comment]
@nnawata せっかくissueを立てていただいたところ申し訳ないです。オープンデータカタログサイトに関することは[カタログサイト](https://portal.data.metro.tokyo.lg.jp/)からリンクされている[リクエストボックス](https://www.shinsei.elg-front.jp/tokyo2/uketsuke/form.do?id=1645658051783)に投稿をお願いします 🙇 

こちらのissueはクローズとさせてください 🙏
