### ISSUE TITLE
[全数届出見直しに伴う改修]患者の発生状況等

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7507]
新型コロナの陽性者情報について、都も9/26から発生届の対象を限定することになりました。
それに伴い、対策サイトのグラフ・表にもいくつか影響が発生します。

**こちらのissueの改修は9/27（火）にリリースします。**

## 患者の発生状況等の改修内容
- 「都外からの持込検体・他県陽性者登録 センターによる陽性数」欄を削除
- 「ワクチン接種状況」の表を削除
- 下記お知らせを表示
```
都外からの持込検体・他県陽性者登録センターによる陽性数」及び新規陽性者の「ワクチン接種状況」 は、全数把握の見直しにより、 2022年9月26日(月曜日)をもって公表を終了しました。なお、検査件数の詳細は[福祉保健局のページ](https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/kensa/kensuu.html)をご覧ください。
```
- 注釈を以下に差し替え
```
・新規陽性者数は総数のみの集計である
・感染者の濃厚接触者が有症状となった場合で、検査を実施せずに医師の判断により臨床診断された患者を含む
```

### 改修イメージ
![患者の発生状況等](https://user-images.githubusercontent.com/14883063/191774918-1ad7a096-0314-477f-9f77-b4c153dabf7e.png)

**Comment by Murayu0225** [comment]
このIssueやります！

**Comment by Murayu0225** [comment]
@kaizumaki 画像では検査数の欄も削除されていますがこちらも削除してよいですか？

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！
検査数についてはコメント漏れてました。イメージどおりで削除でお願いします！
