### ISSUE TITLE
[全数届出見直しに伴う改修]検査陽性者の状況

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7508]
新型コロナの陽性者情報について、都も9/26から発生届の対象を限定することになりました。
それに伴い、対策サイトのグラフ・表にもいくつか影響が発生します。

**こちらのissueの改修は9/27（火）にリリースします。**

## 検査陽性者の状況の改修内容
- 「陽性者数(累計)」の鍵型を解除
- 「自宅療養」を削除
- 「入院・療養等調整中」を削除
- 「死亡」を「死亡者数 (累計)」に修正
- 「退院等」を削除
- 陽性者数⇔入院と宿泊療養⇔死亡者数に 少しスペースを挿入
- 下記お知らせを表示
```
「自宅療養」「入院・療養等調整中」 「退院等」 は、全数届出の見直しにより、 2022年9月26日(月曜日)をもって公表を終了しました。
```
- 注釈を以下に差し替え
```
・「重症」は、人工呼吸器管理（ECMOを含む）が必要な患者数を計上。 重症基準の考え方はこちら
・チャーター機帰国者、クルーズ船乗客等は含まれていない
・2022年2月2日以降は、感染者の濃厚接触者が有症状となった場合で、検査を実施せずに医師の判断により臨床診断された患者を含む
```

### 改修イメージ
![検査陽性者の状況](https://user-images.githubusercontent.com/14883063/191775815-a5405fd5-f924-4812-ad50-3d2117e1e61c.png)

**Comment by y-dobashi** [comment]
こちら、対応させていただきます！
