### ISSUE TITLE
[全数届出見直しに伴う改修]モニタリング項目

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7509]
新型コロナの陽性者情報について、都も9/26から発生届の対象を限定することになりました。
それに伴い、対策サイトのグラフ・表にもいくつか影響が発生します。

**こちらのissueの改修は9/27（火）にリリースします。**

## モニタリング項目の改修内容
- カテゴリ（「潜在・市中感染」「検査体制」「受入体制」）削除
- 「新規陽性者における接触歴等不明者」を削除
- モニタリング項目の番号を詰める
- 「PCR・抗原検査」を【感染状況】に移動
- 下記お知らせを表示
```
「新規陽性者における接触歴等不明者」 は、全数届出の見直しにより、2022年9月26日(月曜日)をもって公表を終了しました。
```
- 注釈を以下に差し替え
```
・#7119：急病やけがの際に、緊急受診の必要性や診察可能な医療機関をアドバイスする電話相談窓口
・救急医療の東京ルールの適用件数：救急隊による5医療機関への受入要請又は選定開始から20分以上経過しても搬送先が決定しない事案の件数
・(1)～(4)は7日間移動平均で算出
・(2)(3)(4)は報告日の前日時点の数値
・(5)の確保病床数には、(6)の確保病床数を含む
・速報値として公表するものであり、後日修正する場合がある
・(2)(4)は土曜日、日曜日、祝日は更新しない。(3)は日曜日、祝日は更新しない
・(1)には、感染者の濃厚接触者が有症状となった場合で、検査を実施せずに医師の判断により臨床診断された患者を含む
```

### 改修イメージ
![モニタリング項目](https://user-images.githubusercontent.com/14883063/191776537-1e5e22fd-f809-4384-a23f-4cb52cb30849.png)

**Comment by y-dobashi** [comment]
残り一つのこちらも対応いたします！
