### ISSUE TITLE
[全数届出見直しに伴う改修]陽性者関連カード

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7511]
新型コロナの陽性者情報について、都も9/26から発生届の対象を限定することになりました。
それに伴い、対策サイトのグラフ・表にもいくつか影響が発生します。

**こちらのissueの改修は9/27（火）にリリースします。**

### 報告日別による陽性者数の推移
- オープンデータのリンク先を<https://catalog.data.metro.tokyo.lg.jp/dataset/t000001d0000000011>に変更
- 注釈を以下に差し替え
```
・2022年9月27日以降は総数のみの集計であり、2022年9月26日以前は保健所からの発生届の報告日を基準とした集計である
・医療機関等が行った検査も含む
・チャーター機帰国者、クルーズ船乗客等は含まれていない
・2022年2月2日以降は、感染者の濃厚接触者が有症状となった場合で、検査を実施せずに医師の判断により臨床診断された患者を含む
```

### 陽性者の属性
- 下記お知らせを表示
```
「陽性者の属性」 は、全数届出の見直しにより、 2022年9月26日(月曜日)分をもって更新を終了しました。
```

### 陽性者数（区市町村別）
- 下記お知らせを表示
```
「陽性者数（区市町村別）」 は、全数届出の見直しにより、 2022年9月26日(月曜日)分をもって更新を終了しました。
```

### 発症日別による陽性者数の推移
- 下記お知らせを表示
```
「発症日別による陽性者数の推移」  は、全数届出の見直しにより、 2022年9月26日(月曜日)分をもって更新を終了しました。
```

### 確定日別による陽性者数の推移
- 下記お知らせを表示
```
「確定日別による陽性者数の推移」  は、全数届出の見直しにより、 2022年9月26日(月曜日)分をもって更新を終了しました。
```

### 報告日別による陽性者数（65歳以上）の推移
- 注釈を以下に差し替え
```
・2022年9月27日以降は総数のみの集計であり、2022年9月26日以前は保健所からの発生届の報告日を基準とした集計である
・医療機関等が行った検査も含む
・チャーター機帰国者、クルーズ船乗客等は含まれていない
・2022年2月2日以降の報告分には、感染者の濃厚接触者が有症状となった場合で、検査を実施せずに医師の判断により臨床診断された患者を含む
```

### 改修イメージ（お知らせ表示位置）
![お知らせ表示例](https://user-images.githubusercontent.com/14883063/191779962-ec78065c-a101-4c1c-b5b2-e67710f18181.png)

**Comment by y-dobashi** [comment]
こちらも対応させていただきます!
