### ISSUE TITLE
2022年度版ウェブアクセシビリティ試験結果のサイト掲載

### ISSUE THREAD

**Issue by masuP9** [tokyo-metropolitan-gov/covid19#7539]
## 改善詳細 / Details of Improvement

2022年度に実施したウェブアクセシビリティ試験結果をサイトに掲載おねがいします。

## 期待する見せ方・挙動 / Expected behavior

2021年度に実施した結果に追記する形
結果の詳細はGoogle Docsにまとめています。

[東京都新型コロナウイルス対策サイト - 試験結果
](https://docs.google.com/document/d/1fQ6DFDKRO80vGKpIAXpLHP8DoIxOh8AVWshPA-6A82Y/edit#heading=h.ut335kx1oky4)

**Comment by kaizumaki** [comment]
私のほうでやりますね 🙋
