### ISSUE TITLE
セルフアサインが出来ないにもかかわらず貢献の仕方ページにセルフアサインの文言がある

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#754]
## 改善詳細 / Improve details

- セルフアサインの文言をけす
- issueないで「やります！」と表明して頂く方法にする

## スクリーンショット / Screenshot

該当ページ
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/CONTRIBUTING.md

## 期待する見せ方・挙動 / Expected behavior
- 日本語版、英語版それぞれに反映する。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mikkame** [comment]
取り急ぎ外出先でスマホから打ったので
ちょっと雑になってるかもしれませんがよろしくお願いします

**Comment by shotaro** [comment]
はじめまして。
こちら対応して良いでしょうか。
