### ISSUE TITLE
storybookの導入

### ISSUE THREAD

**Issue by sushi-udon** [tokyo-metropolitan-gov/covid19#756]
## 改善詳細 / Improve details
- [ ] storybook の導入 (https://storybook.js.org/)

### 懸念点
#621 にて、TypeScript 化を進行されているので、

* TypeScript化 が終わった後に、storybook を導入
* storybook を導入後、順次 TypeScipt化 をしていく<br>

のどちらが良いか悩んでおります。
ご意見いただけますと幸いです。

参考URL：
https://storybook.js.org/docs/guides/guide-vue/

## 期待する見せ方・挙動 / Expected behavior
- [ ] storybookが導入されている (package.json に書いた scripts で起動するようになる)
- [ ] docker-compose で開発している場合、storybook は別コンテナで立ち上がるようにしたい (参考URL：https://qiita.com/ProjectEuropa/items/5d00aa031e78fda689be)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux

**Comment by fussy113** [comment]
良いですね！

> - TypeScript化 が終わった後に、storybook を導入
> - storybook を導入後、順次 TypeScipt化 をしていく

前者で良いかと思いました！理由としましては、
- すでにtypescript化が粛々と進められていること
- storybookが緊急で必要になるものではないので、typescript化後にこちらを進めて行くのが良いと思ったこと

(dockerでの開発者のために、docker-composeでstorybookは別コンテナとして立ち上がるようにしたいですね)

**Comment by sushi-udon** [comment]
@fussy113 
ご意見頂き、ありがとうございます！

> dockerでの開発者のために、docker-composeでstorybookは別コンテナとして立ち上がるようにしたいですね

確かに、そうですね！
以下の記事URLが参考になりそうだったため、概要欄に追記させて頂きました。

https://qiita.com/ProjectEuropa/items/5d00aa031e78fda689be

何か問題点ありましたら、ご指摘お願い致します！

**Comment by kaizumaki** [comment]
こちらのissueは一旦クローズとします。
