### ISSUE TITLE
TextCard コンポーネントに 空のタグが入ることがある

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#758]
## 起こっている問題 / Occurred problem
- TextCard には 2通りの body の入れ方があり、body props で本文を渡すと空のタグができる

## スクリーンショット / Screenshot
<img width="359" alt="スクリーンショット 2020-03-07 21 46 09" src="https://user-images.githubusercontent.com/8909592/76143741-4de28e00-60bd-11ea-86ee-f1711d1cb4a4.png">
<img width="861" alt="スクリーンショット 2020-03-07 21 46 14" src="https://user-images.githubusercontent.com/8909592/76143743-4fac5180-60bd-11ea-90af-ff8262a8b89b.png">

## 期待する見せ方・挙動 / Expected behavior
- body props で本文を渡した場合に空のタグができないようにする

## 起こっている問題の再現手段 / Steps to reproduce
1. /worker または /parent ページを開く
1. TextCard を確認する

## 動作環境・ブラウザ / Environment
全環境

**Comment by amotarao** [comment]
```html
    <p v-if="body" class="TextCard-Body" v-html="body" />
    <p v-if="$slots.default" class="TextCard-Body">
      <slot />
    </p>
```
で非表示は可能

body props と slot が両方あった場合は両方表示される (元から)

#755 で `<p>` を `<div>` にするPRが出されている

**Comment by oti** [comment]
@amotarao 
#755 を担当した oti です。 `v-if="$slots.default"` を追加するならば 755 にその変更もコミットしましょうか？

**Comment by amotarao** [comment]
@oti ぜひ！よろしくお願いします！ 🙏

**Comment by amotarao** [comment]
#755 で完了。ありがとうございました！
