### ISSUE TITLE
[整理改修]病床使用率等と患者の発生状況等を統合

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7585]
「XXXX年XX月XX日の病床使用率等」と「XXXX年XX月XX日の患者の発生状況等」を統合します。

**近日リリース予定です。**

## 改修内容
- お知らせ削除
- タイトルを●月●日の状況に変更
- 病床使用率等と患者の発生状況等を縦積み
- 小見出し「病床使用率等」「患者の発生状況」を追加
- 注釈も縦積みし、折り畳みを実装

### 実装イメージ
![図1](https://user-images.githubusercontent.com/14883063/196895993-f2486e0e-9483-42b9-9290-5a679a07d867.png)

**Comment by Murayu0225** [comment]
こちらやります！

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！よろしくお願いします！ 🙏
