### ISSUE TITLE
[整理改修]検査陽性者の状況

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7587]
「検査陽性者の状況」を改修します。

**近日リリース予定です。**

## 改修内容
- お知らせ削除
- 軽症・中等症の子要素に「確保病床」を追加
- 重症の子要素に「確保病床」を追加
- 宿泊療養の子要素に「宿泊療養施設 受入可能室数」を追加
- 宿泊療養の子要素に「感染時拡大時療養施設 床数」を追加
- 必要な注釈を追加 **※ 確認中**

## 使用データ
`data/positive_status_summary.json`

### 実装イメージ
![スクリーンショット 2022-10-20 19 31 35](https://user-images.githubusercontent.com/14883063/196925613-d0239914-93c8-49ee-99c4-b952d4c41cf3.png)

**Comment by Murayu0225** [comment]
こちらもやります

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！よろしくお願いします！
注釈の指示が来たので置いておきますね。
```
・「重症」は、人工呼吸器管理（ECMOを含む）が必要な患者数を計上。 重症基準の考え方はこちら
・「重症確保病床」は東京都基準の重症患者用確保病床数
・チャーター機帰国者、クルーズ船乗客等は含まれていない
・2022年2月2日以降は、感染者の濃厚接触者が有症状となった場合で、検査を実施せずに医師の判断により臨床診断された患者を含む
```
