### ISSUE TITLE
[整理改修]モニタリング項目

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7588]
「モニタリング項目」を改修します。

**近日リリース予定です。**

## 改修内容
- お知らせを削除
- 入院患者数の「確保病床」を削除
- 重症患者数の「確保病床」を削除
- 注釈「(5)の確保病床数には、(6)の確保病床数を含む」を削除

## 使用データ
現在、数値を `data/monitoring_items.json` から取得しているところ、それを切り離し、各モニタリング項目のjsonから取得するようにします。

### 実装イメージ
![スクリーンショット 2022-10-20 19 35 00](https://user-images.githubusercontent.com/14883063/196926992-8c29c0a7-b783-45dd-ae04-f0becc3959ac.png)

**Comment by Murayu0225** [comment]
こちらもやります

**Comment by Murayu0225** [comment]
@kaizumaki 
更新日時はどのjsonからとればよいでしょうか？

**Comment by kaizumaki** [comment]
@Murayu0225 あ、たしかに！それ確認しておきますね！
とりあえず、 `data/monitoring_items.json` のままで実装してもらえると助かります 🙏

**Comment by Murayu0225** [comment]
わかりました！
