### ISSUE TITLE
年代別新規陽性者数のオープンデータリンク先URL追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7617]
年代別新規陽性者数のオープンデータがカタログサイトで公開となりましたので、カードにリンクを追加します。

リンク先：https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000103

https://github.com/tokyo-metropolitan-gov/covid19/blob/5178368063a54371e1cc8869ad9d5cedb1c88eef/components/index/CardsFeatured/PositiveNumberByAge/Card.vue#L21

**Comment by Murayu0225** [comment]
こちら対応します！
