### ISSUE TITLE
言語切替用のselectフォーム実装

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#767]
## 改善詳細 / Improve details
- 現在各所で進められている言語切替を行うためのUIパーツをナビゲーションメニュー内のSNSボタンの上に配置する

### PC表示
|通常時|クリック時|
|--|--|
|![image](https://user-images.githubusercontent.com/1301149/76144665-1d532200-60c6-11ea-9fd2-7f7519666fd3.png)|![image](https://user-images.githubusercontent.com/1301149/76144940-58eeeb80-60c8-11ea-96b9-bb0a936f98ee.png)|

### スマホ表示
|通常時|クリック時|
|--|--|
|![image](https://user-images.githubusercontent.com/1301149/76144723-7fac2280-60c6-11ea-8aa9-8a5df1d7582e.png)|![image](https://user-images.githubusercontent.com/1301149/76144943-60ae9000-60c8-11ea-9cca-c7c28867675f.png)|

### デザインデータ（Figama）
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=121%3A709

## 期待する見せ方・挙動 / Expected behavior
- 展開する前の状態のみ見た目を↑の様にカスタマイズしたい
- 展開後はOS側の標準実装

**Comment by MaySoMusician** [comment]
関連issue: #681

**Comment by MaySoMusician** [comment]
仮のボタンの実装は #682 にて行っております

**Comment by saladdays** [comment]
すばやく拾って頂いて助かります！！

**Comment by MaySoMusician** [comment]
仕様の確認ですが、例えば「中国語 | 中文」（実際には簡体字・繁体字の別がある）は、英語表示モードだった場合は「Chinese | 中文」とする必要がありますか？
それとも、如何なる言語設定であっても「中国語 | 中文」のままですか？
（ちなみに実装する側としては後者の方がすっきり書けます）

**Comment by nard-tech** [comment]
仕様については #682 の私のコメントもご確認ください．
技術的には select フォームでも構わないのですが，UI, UX の観点からするとページ上部にリンクを置いておく方が優しいのかなとも思います．

**Comment by mikkame** [comment]
確かに、UI,UXの観点からするとページ上部についていた方がわかりやすいとは思います。
お手数ですが今回入ったんカンプ通りにして、新たにImproveで改善していくながれでいかがでしょうか

**Comment by nard-tech** [comment]
@mikkame 申し訳ないですが，select フォームを実装する余裕がありませんし，一旦カンプ通りにしてまた戻すのは時間の無駄でしかありません．
UI, UX の観点で私の意見にご賛同頂けるのであれば，言語選択についてはとりあえず現状維持とし，デザインについてはもう一度議論して頂けないでしょうか．

**Comment by mikkame** [comment]
@nand-tech すみません、こちらのIssueに関してはカンプありきで作成されておりますので
カンプから離れてしまうとマージいたしかねます。
個人的にはより画面の上の方に設置されている方がわかりやすいとは思うのですが
これについては私では決めれない事になります、ご理解ください。

**Comment by nard-tech** [comment]
@mikkame
select フォームにするのが嫌だという話をしているのではありません．
多言語化を早く進めるためにやむを得ないから，とりあえず現状できあがっている仮のボタンのままでいけませんか？というお話をしているのです．

私とあなたの少なくとも2人が「個人的にはより画面の上の方に設置されている方がわかりやすい」と思っているのですから，デザインカンプにまだ議論の余地があるのではないですか？
「私では決めれない事」であれば，そのことをデザイン担当の方にお伝え頂けませんか？

このやりとり自体が時間の無駄だと思います．

**Comment by mikkame** [comment]
@nard-tech そうですね、とりあえず動く物の方がよいという事には同意です。
検証のためにも必要だと思います。

では、いったんボタンを実装し、必要があればセレクトボタンに変更していくという流れにしたいと思います

**Comment by mikkame** [comment]
@nard-tech マージしました！ありがとうございます。
取り急ぎこれでレビューや検証が進みやすくなると思います。

**Comment by saladdays** [comment]
処々の議論拝見しました。デザインを担当した者です。

@MaySoMusician 

> 仕様の確認ですが、例えば「中国語 | 中文」（実際には簡体字・繁体字の別がある）は、英語表示モードだった場合は「Chinese | 中文」とする必要がありますか？

はい、その想定でおります。できるだけその選択されている方の言語でも示してあげたいという意図です。とはいえ「切り替えできること」が何よりまず大事ですので、優先度を落として頂いても大丈夫です！

@nard-tech

ご意見のとおり「動かすこと」を優先しての実装で問題ありません。あくまでデザインはより実装を活かすためのものだという立ち位置です。

ちなみにあの位置にあるのは下記のような理由によるものです。

- 右上はグローバルエリアではなく右側全てがコンテンツエリアという設計のため、そのままだと切り替わる対象がそのコンテンツのみのようなUIになってしまうので、グローバルエリアであるサイドナビゲーションに置きたい
- ブラウザの表示言語で自動切り替えが行われるため、切り替えスイッチ自体の優先度は他のコンテンツよりも低くしたい
- 今後も言語数が増えることが予想されるため、それらを吸収できるUIに今からしておきたい

ですので、今のUIを活かしたまま優先度を上げるのであればロゴの下になると考えております。

@mikkame 
マージありがとうございまーす
