### ISSUE TITLE
タイトルがiPhone SEサイズだと崩れる

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#770]
## 起こっている問題 / Occurred problem
- iPhone SEサイズ（width: 320px）にすると、改行位置がおかしくなってしまう

## スクリーンショット / Screenshot

<img src=https://user-images.githubusercontent.com/1301149/76145211-de739b00-60ca-11ea-85a3-f877aff6f4d7.png width=50%>

## 期待する見せ方・挙動 / Expected behavior
- 改行位置を下記のように変更する

```
新型コロナウイルス
感染症対策サイト
```

## 起こっている問題の再現手段 / Steps to reproduce
1. iPhone SEサイズでページを閲覧（Chromeなどでも再現可能）

**Comment by shingotomiy** [comment]
こちら対応します。

**Comment by ypresto** [comment]
i18n化で言語ごとの改行位置調整が必要になりそうな気がしており、もしかしたら改行位置を変える以外の方法で対応しておくと良いかも知れない気がしております

**Comment by ypresto** [comment]
![image](https://user-images.githubusercontent.com/400558/76145566-cc472c00-60cd-11ea-9d6a-52e81f08a987.png)

なおこれはこれでいいのかがわかりませんが、左側のロゴも押しつぶされて一緒に小さくなっているので、右側のテキストが改行されそうになったら左を小さくする、という手もあるかも知れません

**Comment by shingotomiy** [comment]
@ypresto 
ご指摘の通り、i18n化の
 ```
 "COVID-19": "新型コロナウイルス感染症",
 "Measures site": "対策サイト",
```
を
 ```
 "COVID-19": "新型コロナウイルス",
 "Measures site": "感染症対策サイト",
```
に変更することで改行位置を変えるのはベストではない気がします。

一旦離脱しますので、他の方よろしければどうぞ。

**Comment by himatani** [comment]
対応しますー！

**Comment by ypresto** [comment]
ああ、もうすでにそのように別れてるんですね！（まだ見てなかったです :bow:

**Comment by himatani** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/701 で多言語化の修正を反映させていく予定ですが、まだちょっと先になりそうです。こちら、[bug] で優先度高めかと思いますので、待たずに修正しdevelopmentブランチにPR出すことにします。

**Comment by himatani** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/701 で多言語化の修正を反映させていく予定ですが、まだちょっと先になりそうです。
こちら、[bug] で優先度高めかと思いますので、待たずに修正しdevelopmentブランチにPR出すことにします。

**Comment by himatani** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/701 で多言語化の修正を反映させていく予定ですが、まだちょっと先になりそうです。
[bug] で優先度高めかと思いますので、待たずに修正しdevelopmentブランチにPR出すことにします。

**Comment by himatani** [comment]
これまで２分割にしていた文言を３分割とし、spanタグ等でh1タグに埋め込みCSSで調整すればいい感じになりそうです。が、ちょっとよくない実装ですね。。

Before:
```
<h1 class="SideNavigation-Heading">
  {{ $t('新型コロナウイルス感染症') }}<br />{{ $t('対策サイト') }}
</h1>
```
```
"ja": {
  "新型コロナウイルス感染症": "COVID-19",
  "対策サイト": "Task Force website"
}
```

After:
```
"ja": {
  "新型コロナウイルス": "COVID-19",
  "感染症": "",
  "対策サイト": "Task Force website"
}
```

```
<h1 class="SideNavigation-Heading">
  <span>{{ $t('新型コロナウイルス') }}</span>
  <span>{{ $t('感染症') }}</span>
  <span>{{ $t('対策サイト') }}</span>
</h1>
```

`COVID-19` で `新型コロナウイルス感染症` の意なので、これも改行させるためだけの言語フレーズ分割になってしまうため望ましくなく、別の方法を別の方法を模索した方がよさそうです。

**Comment by kawoka** [comment]
フォントサイズを11pxまで下げれば今のままおさまりそうですが、アクセシビリティなどの観点で問題があったりするのでしょうか...？
<img width="238" alt="スクリーンショット 2020-03-08 01 13 08" src="https://user-images.githubusercontent.com/4666330/76146863-fb639a80-60d9-11ea-961c-4d968c4b6452.png">

**Comment by himatani** [comment]
ちょうど同じことを考えていました。
フォントサイズをそのままに、余白の調整だけで収まりそうでした。

<img width="272" alt="スクリーンショット 2020-03-08 0 36 30" src="https://user-images.githubusercontent.com/37978173/76146714-83e13b80-60d8-11ea-86b7-9cddc835400f.png">

**Comment by kawoka** [comment]
最高ですね！デザイナーさんがよければ、多言語化の兼ね合いでそのようなアプローチで解決できるといいですね ✨

**Comment by himatani** [comment]
ご提案ありがとうございます！

**Comment by himatani** [comment]
@saladdays 
個人的にフォントサイズは保っておきたいと考えているため、上記の通り余白の調整で進めさせてください！デザインの意図が汲めておらず対応が適切でない場合は、ご相談いただければと思います！

**Comment by himatani** [comment]
> なおこれはこれでいいのかがわかりませんが、左側のロゴも押しつぶされて一緒に小さくなっているので、

たしかに既存の実装がよくないですね…
ロゴのサイズを

SP：110px -> 100px
PC：110px

に変更しました。iPhone SE サイズより大きいデバイスで 1px 横幅が狭くなりそうです。（もともとは自動で幅調整された 101px だった模様）

**Comment by himatani** [comment]
> なおこれはこれでいいのかがわかりませんが、左側のロゴも押しつぶされて一緒に小さくなっているので、

確かに…。ロゴの大きさは通常 110px で指定されていますが、ブラウザの幅が狭まると中途半端なサイズになっているようですね。ひとまず

- iPhone SEサイズのときは 100px
- それ以上のサイズのときは 110px

にしておきました。

**Comment by saladdays** [comment]
@himatani 
こちら追いつけておらず申し訳ございません。

`bug` としての対応という意味では「崩れているのをなおす」のが目的ですので、今回の対応内容で問題ございません。

ありがとうございます！！

その上でデザイン的な意味合いで言いますと、メニューを開いた時の `x` ボタンの位置がメニューボタンの位置と同じ場所にあってほしいと考えておりますので、そちらマージされた段階で別issueを立てさせていただきますね。
（ちなみに今もズレてしまっていました。。）

引き続きよろしくお願いいたします。

**Comment by saladdays** [comment]
@himatani あとちょうどよい機会なので、教えて頂きたいのですが

https://github.com/tokyo-metropolitan-gov/covid19/issues/770#issuecomment-596102819

こちらで書かれているような単語単位の分割というのは、翻訳の観点から望ましくないのはとてもよくわかります。

一方で適切な箇所で改行をした方が読みやすくなるというのもユーザビリティですので、今回の「新型コロナウイルス感染症対策サイト」を一文としてマークアップして、翻訳分の方に改行を指定することで言語ごとに改行位置を変えるというのは可能なのでしょうか？

例えば `\n`を入れるなど。

お返事お手すきの際で結構です。後学のためにご教示頂けますと幸いです。

**Comment by MaySoMusician** [comment]
- 今回しようしているi18n対応モジュールですと、原則としてHTMLタグを書いてもHTMLとして認識されないため、`<br />`などを入れられません。
- 翻訳文をHTML展開させる方法も可能ですが（検査陽性者の状況の表などで使用）XSS対策の面から推奨されません（現在はエラーを手動で無視している状態）
- 上記の問題が解決できたとしても、翻訳文の中で改行位置を指定すると次のような課題が残ります。
  - 翻訳者がブラウザの表示結果を見ながら翻訳する必要がある
  - 言語によって改行位置・回数が異なっている場合、原文と訳文で整合性が取れているといえるのか（Crowdinなどの外部翻訳ツールでは、特殊記号の数が原文と異なる場合に警告が出ることがあります）
- ブラウザによって横幅は異なるので、改行のタイミングはブラウザに任せても良いと思います。（ある環境で良い改行位置が他の環境で良いとは限らない）
  - HTML5では`<br />`は要素の使用は詩や住所など、改行の位置に意味を持つもののみに限っています。
- 改行候補位置の指定として、`<wbr>`要素を使用したり、inline-blockの`<span>`で囲ったり（[参考サイト](https://qiita.com/DaichiYamaguchi/items/02fe957c7dc201c2be3d)）などの方法はありますが、i18nモジュールでは上述の通り原則HTML展開ができないので一筋縄ではいかなさそうです。

**Comment by saladdays** [comment]
@MaySoMusician なるほどですー

スピード感とセキュリティなどを考慮すると、ご指摘のようにブラウザになりで任せてしまうのが今回は良さそうですね。

**Comment by mikkame** [comment]
\nを入れてwhite-space: pre;で改行させるのはどうでしょうか

**Comment by saladdays** [comment]
お、改行コードはいけるんですか？
「読みやすさの担保」という意味では適切な改行位置を付けることに意味はあると思っていますので、もしクイックにできるようであれば、、！

あくまでnice to haveの要件ではありますー

**Comment by himatani** [comment]
(すいません… いま追いつきました…)

@mikkame 

> \nを入れてwhite-space: pre;で改行させるのはどうでしょうか

解決策の１つにはなりそうですが、@MaySoMusician の指摘くださったいている以下の点について懸念が払拭されておりません。

- 翻訳者がブラウザの表示結果を見ながら翻訳する必要がある
- 言語によって改行位置・回数が異なっている場合、...

nice to have の要件ということですので、現時点ではブラウザの横幅に合わせて改行されるように後追いで実装しておこうと思います。https://github.com/tokyo-metropolitan-gov/covid19/pull/787 については現時点のものでマージとさせてください。 > @kaizumaki
