### ISSUE TITLE
「ワクチン接種数及び接種率」グラフに｢オミクロン株対応ワクチン｣のデータを追加

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#7738]
「ワクチン接種数及び接種率」グラフに｢オミクロン株対応ワクチン｣のデータを追加することになりました。
これにともないデータのjsonも新しいものに差し替えます。

**こちらは2/16（木）にリリース予定です。**

データ：`data/vaccination_count_with_omicron.json`

## 改修内容
- カードタイトル部「３回目接種数（接種率）」を「オミクロン株対応ワクチン接種数  (接種率）」にタイトル・値を差し替え
- タイトルの下のリストに「３回目接種数  (接種率）  」の値を追加
- グラフに「接種率（オミクロン株対応ワクチン）」の折れ線を追加
- 注釈の１つめを以下のように修正
  - 現 `ワクチン接種記録システム（VRS）への報告を居住地の都道府県別に国が集計し、公表したものに基づき作成（本データは過日の数値が修正されることがある）`
  - 新 `ワクチン接種記録システム（VRS）への報告を居住地の都道府県別に国が集計したものに基づき作成（本データは過日の数値が修正されることがある）`
- グラフ下のボタンリンクのテキストを以下のように修正
  - 現 `年代別ワクチン接種状況・接種推計等の詳細はこちら`
  - 新 `年代別ワクチン接種状況等の詳細はこちら`

![スクリーンショット 2023-02-13 10 31 56](https://user-images.githubusercontent.com/14883063/218352953-880287e2-e756-42bd-948d-43cea65bde68.png)

**Comment by Murayu0225** [comment]
このissue対応します

**Comment by kaizumaki** [comment]
@Murayu0225 ありがとうございます！よろしくお願いします！ 🙏
