### ISSUE TITLE
グラフ毎のパーマリンクとOGPカードの必要性

### ISSUE THREAD

**Issue by fladdict** [tokyo-metropolitan-gov/covid19#774]
## 改善詳細 / Improve details
本サイトを効率よくグロース、カスタマーサクセスに導くには、
再拡散性と参照性を担保する必要があります。
そのためには、各グラフごとのパーマリンクとOGPカードを実装し、グラフ単位で医療関係者がSNS上で拡散できることが重要と考えます。サイトトップの拡散はプロジェクト認知にはつながりますが、サイトデータの実用性や拡散性を担保しきれないのではと考えています。

## スクリーンショット / Screenshot
各データのシェアUIイメージ
![各データのシェアUIイメージ](https://d2l930y2yx77uc.cloudfront.net/production/uploads/images/20510725/picture_pc_4ab2c43dcc34e87511efb1290312f908.png "サンプル")

各データのSNSでの拡散イメージ
![各データのSNSでの拡散イメージ](https://d2l930y2yx77uc.cloudfront.net/production/uploads/images/20511411/picture_pc_86c437c837c738203a09eb5fcaf17efc.png "サンプル")

## 期待する見せ方・挙動 / Expected behavior
- 各データ毎にOGPカード、パーマリンクを設ける
- 可能ならiFrameエンベッド対応を行う
- 各データごとに、シェアボタンをつける
- 各データごとにデイリーでOGPスナップショット画像を生成する
- 各データのスナップショットとパーマリンク概要分に、最終アップデートの日時をいれる
- 各データのパーマリンク毎に、Twitter / Facebbook のキャッシュ消去リクエストを24時間ごとに送信するボットを作る（シェア画像をつねに最新に保ちたい場合）。

より詳細な背景、設計思想などはこちらをベースにしておりmす。
https://note.com/fladdict/n/n943dd83fce0b

**Comment by halsk** [comment]
@fladdict さん、本機能、先程リリースいたしました！
@yasu さん、実装、本当にありがとうございました。 great job❗

**Comment by fladdict** [comment]
ありがとうございます！
