### ISSUE TITLE
note:cardの設定

### ISSUE THREAD

**Issue by RuinDig** [tokyo-metropolitan-gov/covid19#776]
## 改善詳細 / Improve details
- note:cardはピースオブケイク社が運営するオンラインメディアプラットフォーム「[note](https://note.com)」のテキスト記事において、外部サイトを埋め込む際に大きく表示できるシステムです。
[note:card - noteヘルプセンター](https://note.pieceofcake.help/hc/ja/articles/360000338721)
個人として自分のはてなブログと2つのファンサイトにnote:cardを設定しました。
[note:cardを自分のはてなブログに設定する方法｜RuinDig｜note](https://note.com/ruindig/n/ndbb85b915cd8)
[PROJECT LYCAEUMとLYCAEUM WRAP-UPの改良など｜RuinDig｜note](https://note.com/ruindig/n/n16a5000b5c6d)

note:card実装のためにはHTMLのhead内に以下のメタタグを入れます。
`<meta property="og:image" content="*/アイキャッチ画像のURL/*">`
`<meta name="note:card" content="summary_large_image">`

本ウェブサイトの場合は以下のようになるかと思います。
`<meta property="og:image" content="https://stopcovid19.metro.tokyo.lg.jp/ogp.png">`
`<meta name="note:card" content="summary_large_image">`
> 2020-03-08 00:28 edit: 正しいアイキャッチ画像のURLを教えていただきました。ありがとうございます。

## 期待する見せ方・挙動 / Expected behavior
noteのテキスト記事で各種コンテンツのURLを埋め込む際に大きく表示される事です。

## 動作環境・ブラウザ / Environment
動作環境はnoteの[推奨環境](https://note.pieceofcake.help/hc/ja/articles/360008947573)に準じます。

## 備考 / note
本ウェブサイト上での閲覧に影響を与えるものではないため優先度は低いと思います。

**Comment by MaySoMusician** [comment]
`nuxt.config.ts`によればアイキャッチ画像URLは https://stopcovid19.metro.tokyo.lg.jp/ogp.png かと思われます

**Comment by RuinDig** [comment]
ありがとうございます！

**Comment by bookun** [comment]
こちら対応いたします！

**Comment by RuinDig** [comment]
確認を兼ねて以下のnoteを書きましたが、note:cardが設定されたのを確認しました。設定していただきありがとうございました！

東京都新型コロナウイルス感染症対策サイト全体がnote:cardに対応｜RuinDig｜note：[https://note.com/ruindig/n/nf2f0086af948](https://note.com/ruindig/n/nf2f0086af948)
