### ISSUE TITLE
一部のアイコンがホバー時に下線が表示されない

### ISSUE THREAD

**Issue by att55** [tokyo-metropolitan-gov/covid19#777]
## 起こっている問題 / Occurred problem
- 「新型コロナウイルス感染症が心配なときに」と「お子様をお持ちのみなさま皆様へ」のアイコンにホバー時に下線が表示されません。

## スクリーンショット / Screenshot

- 「新型コロナウイルス感染症が心配なときに」をホバー

<img width="222" alt="スクリーンショット 2020-03-08 0 07 44" src="https://user-images.githubusercontent.com/25548003/76145906-6eb4de80-60d1-11ea-9a16-f705312fa408.png">

- 「お子様をお持ちのみなさま皆様へ」をホバー

<img width="228" alt="スクリーンショット 2020-03-08 0 07 55" src="https://user-images.githubusercontent.com/25548003/76145913-81c7ae80-60d1-11ea-83aa-401681aaec12.png">

- その他のアイコンには下線が表示される

<img width="232" alt="スクリーンショット 2020-03-08 0 07 15" src="https://user-images.githubusercontent.com/25548003/76145917-87bd8f80-60d1-11ea-81f3-7c8e0978f474.png">

## 期待する見せ方・挙動 / Expected behavior

ホバー時にアイコンにまで下線をつけるかつけないかはどちらでも良いと思いますが、全体で統一した方がいいと思います。
ちなみに上記の二つにだけ下線が表示されないのは Vuetify の Material Icon ではなく自前で用意しているアイコンだからのようです。
※ CovidIcon と ParentIcon は個別に処理されている。
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/ListItem.vue#L13-L28

## 起こっている問題の再現手段 / Steps to reproduce
1. サイドバーで選択していない「新型コロナウイルス感染症が心配なときに」または「お子様をお持ちのみなさま皆様へ」をホバーする。 

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

## その他

別途、ホバーした時にテキストまで下線が表示されない現象を確認しましたので PR 送らせていただきました。
https://github.com/tokyo-metropolitan-gov/covid19/pull/762

**Comment by nard-tech** [comment]
当方，mac OS 10.15.1, Chrome 80.0.3987.132 という環境ですが，

*   (dev) https://dev-covid19-tokyo.netlify.com/
*   (stg) https://stg-covid19-tokyo.netlify.com/, 
*   (prd) https://stopcovid19.metro.tokyo.lg.jp/

いずれでも再現できません．

と思いましたが，#762 をよくよく見ると，確かに

*   top もしくは `/flow` を開くと下線が付いていない
*   別のパス（parent など）に切り替えて戻ってくると下線が表示される

というのが再現できますね．

**Comment by att55** [comment]
@nard-tech https://stg-covid19-tokyo.netlify.com/worker/ にアクセスした時に、「新型コロナウイルス感染症が心配なときに」または「お子様をお持ちのみなさま皆様へ」をホバーするとどうでしょうか？アイコンに下線が付いていますでしょうか？

**Comment by nard-tech** [comment]
@nard-tech 「新型コロナウイルス感染症が心配なときに」「お子様をお持ちのみなさま皆様へ」のアイコンには下線が付いていないですね

**Comment by asuchi0819** [comment]
このバグですが、 https://stg-covid19-tokyo.netlify.com/worker/ の「企業の皆様・はたらく皆様へ」の**文章自体**のhover時の下線もないようです。

確認端末：iPadOS 13.3 / Safari

**Comment by att55** [comment]
@nard-tech 

> 「新型コロナウイルス感染症が心配なときに」「お子様をお持ちのみなさま皆様へ」のアイコンには下線が付いていない

よかったです。タイトルの通り、この issue はアイコンに下線が表示されないという不具合ですー。

**Comment by att55** [comment]
@asuchi0819 

> 「企業の皆様・はたらく皆様へ」の文章自体のhover時の下線もないようです。

下線が付かないのもそうですが、https://stg-covid19-tokyo.netlify.com/worker/ にアクセスすると「企業の皆様・はたらく皆様へ」が Active (選択された状態)になっていないはずです。 
issue コメントの「その他」にも書いていますが、修正 PR 出しています。

- テキストに下線が付かない問題の修正
https://github.com/tokyo-metropolitan-gov/covid19/pull/762

- Active にならない問題の修正
https://github.com/tokyo-metropolitan-gov/covid19/pull/784

**Comment by ocean3fish** [comment]
@att55 大変申し訳ありません、デザイン仕様としてはホバーした時に下線を表示しない想定なので、クローズさせて頂きます。
