### ISSUE TITLE
トップページのグラフ切り替えボタンにARIA属性を追加したい

### ISSUE THREAD

**Issue by oti** [tokyo-metropolitan-gov/covid19#779]
## 改善詳細 / Improve details
- グラフの[日別/累計]切り替えボタンに、選択中であることを示す ARIA 属性を追加する

## メリット / Merit
これにより、スクリーンリーダーを利用しているユーザーが、現在のグラフの表示モードが日別か累計のどちらかであるかを知ることができるようになります。

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-08 00 10 27](https://user-images.githubusercontent.com/710216/76145874-390ff580-60d1-11ea-8046-0b200f642145.png)
![スクリーンショット 2020-03-08 00 10 12](https://user-images.githubusercontent.com/710216/76145877-3ad9b900-60d1-11ea-8f18-85aa23d312bd.png)

## 期待する見せ方・挙動 / Expected behavior
- 選択している button に `aria-pressed="true"` が付与される
- 選択されていない button に `aria-pressed="false"` が付与される
- `<v-btn-toggle>` に `aria-controls` で対応するグラフのIDを参照する

画面の用途としてはタブ切り替えに見えますがDOMの構成ではタブ1とタブ2が出力されているわけではないので、ここはツールバーとみなして `aria-pressed` 属性を使うのが妥当と考えました。

## 動作環境・ブラウザ / Environment
全て

**Comment by masuP9** [comment]
@oti PR出してくれているので後追いですがアサインしました。あと可能であれば issue の詳細に `aria-pressed` 属性があると誰にとってどんなメリットがあるかも書いてくれると嬉しいですー。

**Comment by oti** [comment]
メリットを追記しました〜

**Comment by masuP9** [comment]
さすがです
