### ISSUE TITLE
感染状況・医療提供体制のフレームの枠線を太くする

### ISSUE THREAD

**Issue by umipro-web-dev** [tokyo-metropolitan-gov/covid19#7794]
## 改善詳細 / Details of Improvement

感染状況・医療提供体制の分析カードにある感染状況・医療提供体制のフレームの枠線が黄色だと認識しずらいぐらいに細かったので太くしました。
また、タイトルとフレームがピッタリくっついていたのですこしmarginをつけて離しておきました。

## スクリーンショット / Screenshot

![frame](https://user-images.githubusercontent.com/113771739/230750365-b51938db-73fb-455e-b88c-479c5e328ca1.png)

左が変更前、右が変更後です。

## 期待する見せ方・挙動 / Expected behavior

- 枠線を太くし、視認性・見やすさを向上する。

## 動作環境・ブラウザ / Environment

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
#7795 をクローズしましたので、こちらのisseuもクローズとします。
