### ISSUE TITLE
「心配なときに」詳細リンク

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#780]
https://stopcovid19.metro.tokyo.lg.jp/flow
ページ最下部の「詳細を見る（福祉保健局）」のリンクの修正をお願いします。

誤）https://www.metro.tokyo.lg.jp/tosei/tosei/news/2019-ncov.html

正）https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html

**Comment by kebhr** [comment]
本件着手します。

**Comment by halsk** [comment]
すみません！こちら #404 で既に修正リクエストが来ていたのですが、確認待ちステータスだったので待ちになっていました。先程取り込みました！
@kebhr さん、せっかく対応いただいたのにすみません。

**Comment by halsk** [comment]
@NaoyaShimizzz さん、こちら先程取り込みました。
https://dev-covid19-tokyo.netlify.com/flow/
でご確認ください。

**Comment by NaoyaShimizzz** [comment]
@kebhr さん、せっかく対応いただいたのにすみません！

@halskさん、確認しました。こちらでOKです。よろしくお願いします
