### ISSUE TITLE
検査実施数を「都内発生」「その他」それぞれで推移がわかるようにしたい

### ISSUE THREAD

**Issue by jinka1997** [tokyo-metropolitan-gov/covid19#795]
## 改善詳細 / Improve details
- 検査実施数の棒グラフが「都内発生」と「その他」の積み上げ棒グラフになっているが、上に積まれている「その他」の推移がわかりづらい。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/34097009/76154918-e01f7c00-6127-11ea-882b-c58df0e205e6.png)

## 期待する見せ方・挙動 / Expected behavior
- 「都内発生」・「その他」でそれぞれの推移が見られると見やすいかと思います。
- 「日別/累計」の切り替えができるのと同様に、「都内発生/その他/合計」の切り替えができるとよさそうです。

## 動作環境・ブラウザ / Environment
全て

**Comment by Rikilele** [comment]
これ、わかりにくいですが、ラベルをクリックすることによって実現します。
もっとわかりやすくする方法を検討する Issue にしてもいいかもしれませんね。

<img width="574" alt="Screen Shot 2020-03-08 at 11 52 26" src="https://user-images.githubusercontent.com/17091013/76155725-537abb00-6133-11ea-8c64-728ab1ef3953.png">
<img width="574" alt="Screen Shot 2020-03-08 at 11 52 35" src="https://user-images.githubusercontent.com/17091013/76155726-54abe800-6133-11ea-933a-66c42acf7fe4.png">

**Comment by jinka1997** [comment]
@Rikilele 
ラベルをクリックするとできるのですね。確認しました。
ありがとうございます。

ただ、ラベルをクリックしても右上の全体累計が変わらないので、↓のように見せ方の検討をしてもよいかもしれませんね。
- 別々の表示のやり方を喚起する
- 別々に表示した時の全体累計の表示も変わるようにする

**Comment by asuchi0819** [comment]
[日付|累計]
の左右どちらかに、似たようなデザインで切り替えられるのをつけてもよいかもしれませんね。

[全て|都内発生|その他]
みたいな感じで。

**Comment by ocean3fish** [comment]
本件ご検討ありがとうございました！
#866 と #870 で解決されたため、クローズとさせて頂きます。
