### ISSUE TITLE
All Contributorsを導入する

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#796]
## 改善詳細 / Improve details
- [All Contributors](https://github.com/all-contributors/all-contributors)を導入することで、`CONTRIBUTORS.md`を手動更新する手間をなくす

## 期待する見せ方・挙動 / Expected behavior
- イシューやプルリクエスト上で[@all-contributors Bot](https://allcontributors.org/docs/en/bot/overview)に対して`@all-contributors please add <ユーザー名> for <コントリビューション>`のようなコメントをするたけで、`CONTRIBUTORS.md`の更新が自動的に行われる（プルリクエストが作成される）

**Comment by FlexiblePrintedCircuits** [comment]
質問です。

# 質問内容
既にあるCONTRIBUTORS.mdのコントリビューターリストの書き方と、all-contributors Botのコントリビューター追加の書式が大きく違うようですが、これは**Botを導入した後CONTRIBUTORS.mdをBotに合わせる形で書きかえる**という認識でよろしいでしょうか。

## 具体的な違い
既存のCONTRIBUTORS.mdは以下のように書かれています。

```
| Name(link) | Contribution |
| --- | --- |
| [名前](何らかのリンク) | Contribution|
| -add your name here!- | -what did you do?- |
```
all-contributors Botは以下のようになります。

```
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->

<table>
  <tr>
    <td align="center"><a href="何らかのリンク"><img src="GitHubのアバター" width="100px;" alt=""/><br /><sub><b>ユーザーID(名前)</b></sub></a><br /><a href="#design-ユーザーID" title="Contribution">🎨</a></td>
  </tr>
</table>

<!-- markdownlint-enable -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->
```
all-contributors Botは指定されたユーザーIDのGitHubアカウントの情報を自動で取得し、それをテーブル形式で追加する使用になっています。

all-contributors Botは表示する画像のサイズなどの変更はできるっぽいですが、既存のCONTRIBUTORS.mdに合わせる形での設定は難しそうです。

（もし私の知識不足で、既存のCONTRIBUTORS.mdに合わせるような設定が可能だったのであれば、この質問は無意味になります。もしその場合だったら大変申し訳ないです。）

**Comment by munierujp** [comment]
>Botを導入した後CONTRIBUTORS.mdをBotに合わせる形で書きかえるという認識でよろしいでしょうか。

はい。その認識です。
もっとも、このイシューはメンテナーの手間を減らすことが目的ですので、現在の手法を続けるよりもAll Contributorsを導入するほうがコストが高いのであれば、導入する必要はないかと思います。

**Comment by munierujp** [comment]
@FlexiblePrintedCircuits 
>Botを導入した後CONTRIBUTORS.mdをBotに合わせる形で書きかえるという認識でよろしいでしょうか。

はい。その認識です。
もっとも、このイシューはメンテナーの手間を減らすことが目的ですので、現在の手法を続けるよりもAll Contributorsを導入するほうがコストが高いのであれば、導入する必要はないかと思います。

**Comment by kaizumaki** [comment]
開発状況が落ち着いてきているので、こちらのissueはクローズとします。
