### ISSUE TITLE
[i18n] TimeStackedBarChart.vue 内の文字列をi18n化

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#800]
総合issue: #680 
（全体の方針については↑へ）

---
- `components/TimeStackedBarChart.vue` の直打ちの文字列を`<i18n>`で定義するようにします。
- 各言語への翻訳はこちらにあります: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0
- L147の日付の翻訳は一旦保留（data.jsonの型に関して要議論

**Comment by sssuzukirisa** [comment]
こちらを引き受けたいです！どなたか着手されているでしょうか？

**Comment by MaySoMusician** [comment]
@sssuzukirisa 
おそらく未着手なのでお願いしたいです！

L96のような変数埋め込みの部分は https://github.com/tokyo-metropolitan-gov/covid19/issues/680#issuecomment-596056211 を参考にお願いします
また`<i18n>`の空テンプレートは https://github.com/tokyo-metropolitan-gov/covid19/issues/680#issuecomment-596059072 にあります
その他何かご質問ありましたらお気軽にお声がけください！

**Comment by MaySoMusician** [comment]
- [ ] TimeStackedBarChartグラフ内の単位も翻訳する

**Comment by MaySoMusician** [comment]
Tooltip内で一部翻訳が反映されない部分がありますので、上記「日付形式を全言語で統一」と合わせて私が対応します

**Comment by MaySoMusician** [comment]
Close per #1108 merged
