### ISSUE TITLE
サイトにおけるサイドバー（メニュー）の見切れ

### ISSUE THREAD

**Issue by asuchi0819** [tokyo-metropolitan-gov/covid19#803]
## 起こっている問題 / Occurred problem
- iPadOS - Safariにおけるサイドバー下部の見切れ
- iOS - Safariにおけるメニュー下部の見切れ

## スクリーンショット / Screenshot
![IMG_44271A31D41B-1](https://user-images.githubusercontent.com/45027336/76156323-40b8b400-613c-11ea-9b8b-2d840e30ab03.jpeg)
<img width="1024" alt="新型コロナウイルス感染症が心配なときに  東京都 新型コロナウイルス感染症対策サイト" src="https://user-images.githubusercontent.com/45027336/76156344-778eca00-613c-11ea-8263-ef93f4f8f7d5.png">

## 期待する見せ方・挙動 / Expected behavior
-  上記の不具合の改善

## 起こっている問題の再現手段 / Steps to reproduce
1. iPadOSにおける手順
サイトにアクセス後サイドバーをスクロール -> 下までスクロールすることができない。
ただ、メイン領域を下部までスクロールすると見切れは解消されるものの不安定。
2. iOSにおける不具合
サイトにアクセス後サイドバーをスクロール -> 下までスクロールすることができない。
現状、応急策は未発見。

## 動作環境・ブラウザ / Environment
- iPadOS 13.3 / Safari
- iOS 13.3.1 / Safari

**Comment by tomopict** [comment]
iPadOSに関しては以下の環境において再現しました。
iOS 13.1.2 / iPad Pro(9.7inch)  横向き

iOSに関しては以下のような状況です。
iOS 13.3.1 / Safari iPhoneXR →再現せず
iOS 13.3.1 / Safari iPhoneSE →再現

どちらも高さが画面に治りきらない場合に
.navContainerに100vhが指定されていることで
画面外にメニューが伸びていることに起因しているように見えます。

こちらどなたもみられていないようであれば対応させていただきます。

**Comment by asuchi0819** [comment]
@tomopict さん、情報有難うございます。

---

書き忘れていたので、機種について追記です。
iPad 6th (9.7inch) / iPadOS 13.3 / Safari（横向き、Slide Over）
iPhone 7 / iOS 13.3.1 / Safari

**Comment by tomopict** [comment]
@asuchi0819 
追加の情報ありがとうございます。
iPhone6の環境でも同じ状況が再現しました。

どれもアスペクト比が9:16なので、
そのアスペクト比のものが同様の状況になっている可能性が高そうです。

**Comment by tomopict** [comment]
@asuchi0819 

確認していたところdev環境においては少なくとも
iPadOS横向き環境でのメニュー表示については状況が解消されているようでした。

https://dev-covid19-tokyo.netlify.com/

**Comment by tomopict** [comment]
dev環境をみるに、他のイシューで対応されている可能性もありそうなので、
触れずにおいておりますー。

**Comment by tomopict** [comment]
その後確認したのですが、dev環境においてもiPhoneSEは引き続き見切れている状態だったため、
コミットしPR投げさせていただきました。
