### ISSUE TITLE
[/flow] pages/flow.vue で「新型コロナ受診相談窓口」のグレー背景色を修正する

### ISSUE THREAD

**Issue by yuma84** [tokyo-metropolitan-gov/covid19#808]
## 起こっている問題 / Occurred problem

- 「新型コロナ受診相談窓口」のグレー背景色を修正する
  - 「コンポーネントコーディング」ではコンポーネント追加のみ行うため、親となる`pages/flow.vue`の修正は本Issueで扱う。
    - *ref.* https://github.com/tokyo-metropolitan-gov/covid19/pull/736#pullrequestreview-370802838

- `.Flow-Card-Parts.Flat`クラスで指定している背景色を下記のように修正
  - `$gray-4`(`#D9D9D9`) → `$gray-5`(`#F8F9FA`)
  - *ref.* https://github.com/tokyo-metropolitan-gov/covid19/pull/736/commits/603d77f6182aaa6e45fa6929e9bdf0403f18f9b8#diff-e3f3e4cc748b0a71fa2e93cd6f3f378fL271-R271

## スクリーンショット / Screenshot

![before](https://user-images.githubusercontent.com/19541094/76157224-57b1d300-6149-11ea-9bae-0eddf0938300.png)

## 期待する見せ方・挙動 / Expected behavior

![after](https://user-images.githubusercontent.com/19541094/76147158-cf95e400-60dc-11ea-9948-0c1b39c1f125.png)

**Comment by hagechin** [comment]
やります！
