### ISSUE TITLE
huskyのpre-commit hooksで、警告メッセージが表示される

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#812]
## 起こっている問題 / Occurred problem
- ファイルに対する変更をコミットしようとすると、huskyのpre-commit hooksで以下のような警告メッセージが表示される

>⚠Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatica
lly added to the git commit index.

**Comment by ryotsun** [comment]
すでに対応済みのようです。
https://github.com/tokyo-metropolitan-gov/covid19/pull/835/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R18

**Comment by munierujp** [comment]
resolved by #835
