### ISSUE TITLE
[i18n] SvgCard.vue 内の文字列をi18n化

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#813]
総合issue: #680 
（全体の方針については↑へ）

---
- `components/SvgCard.vue` の直打ちの文字列を`<i18n>`で定義するようにします。
- 各言語への翻訳はこちらにあります: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0

**Comment by bapex** [comment]
こちら、担当させていただいてもよろしいでしょうか？

**Comment by MaySoMusician** [comment]
@bapex よろしくお願いいたします！
何かご不明な点ありましたらお気軽にお申し付けください

**Comment by bapex** [comment]
ありがとうございます。かしこまりました！

**Comment by bapex** [comment]
@MaySoMusician 

下記の翻訳部分は、どこにありますでしょうか？スプレッドシート拝見したのですが見当たらりませんでした。。

```
    <template v-slot:button>
      <p class="Graph-Desc">
        （注）都内において疑い例または患者の濃厚接触者として検査を行ったものについて掲載<br />
        （チャーター機帰国者、クルーズ船乗客等は含まれていない。）
      </p>
    </template>
```

**Comment by MaySoMusician** [comment]
@bapex 翻訳がまだされていないようです。お手すきでしたら、スプレッドシートの最下部に日本語を追加していただけると助かります。
また、コードのほうはひとまず `ja` の方のみ登録しておいていただければ大丈夫です
翻訳が決定したらまた修正お願いする場合があります！ よろしくお願いいたします

**Comment by bapex** [comment]
@MaySoMusician 
かしこまりました！

**Comment by bapex** [comment]
@MaySoMusician 
一旦PR送らさせていただきました。

**Comment by MaySoMusician** [comment]
- [ ] 翻訳は要更新

**Comment by MaySoMusician** [comment]
@nard-tech #842 mergeされたので翻訳の更新お願いします

**Comment by nard-tech** [comment]
@MaySoMusician この PR は merge して頂いていいですか？翻訳の更新は他の component とまとめて別PRで対応しますので．

**Comment by MaySoMusician** [comment]
@nard-tech ではこのissueはcloseします

**Comment by nard-tech** [comment]
@MaySoMusician あ，トンチンカンなこと言ってましたね．こちらは issue でしたね．すみません．

**Comment by MaySoMusician** [comment]
@nard-tech 大丈夫です！ 「陽性患者の属性」テーブルについてはこちらが #868 で進めてます
