### ISSUE TITLE
[i18n] error.vue 内の文字列をi18n化

### ISSUE THREAD

**Issue by himatani** [tokyo-metropolitan-gov/covid19#829]
総合issue: #680
（全体の方針については↑へ）

---
`pages/error.vue` の直打ちの文字列を `<i18n>` で定義するようにします。
各言語への翻訳はこちらにあります: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0

**Comment by himatani** [comment]
こちら対応中です

**Comment by kiiita** [comment]
こちら担当します 🙆

**Comment by MaySoMusician** [comment]
@kiiita すみません！ こちら #830 にて対応済みです！

**Comment by kiiita** [comment]
@MaySoMusician 見落としておりました！
ありがとうございますmm
