### ISSUE TITLE
著作権表示と他都市展開

### ISSUE THREAD

**Issue by yasushisakai** [tokyo-metropolitan-gov/covid19#832]
## 改善詳細 / Improve details
deploy後にtokyo metropolitan governmentのall rights reservedの著作権表示があります。
転用を基本的に許しているレポジトリのMITライセンスとの関係が知りたいです。

I'm curious about the mind behind the MIT license and putting an all rights reserved license for the contents. To make it easier for other cities to reuse this idea, shouldn't this be a CC license instead?

## スクリーンショット / Screenshot
<img width="221" alt="Screen Shot 2020-03-08 at 8 25 30 AM" src="https://user-images.githubusercontent.com/1502180/76162683-64690380-6116-11ea-8d43-385ea0a05502.png">

## 期待する見せ方・挙動 / Expected behavior

同じテンプレで国内他都市への展開も見据えて、MITライセンスと考え方が近い、Creative Commons の Attribution-ShareAlike 4.0 Internationalなど転用をある程度許容したものへの検討。

他に展開したときに変更しやすいようにする。
https://github.com/tokyo-metropolitan-gov/covid19/blob/78dff19d6af0d740f92f590ecb2f1809365255e3/components/SideNavigation.vue#L57

...良ければPRしますが、考え方を伺いたく。

**Comment by halsk** [comment]
確かに検討必要ですね。確認が必要ですのでお待ち下さい。ご指摘ありがとうございます！！

**Comment by yasushisakai** [comment]
ありがとうございます。すでにある著作に権利変更を提案するという図々しさ甚だしい行為ですが...、提案までにお考えください。

**Comment by NaoyaShimizzz** [comment]
庁内関係者との協議の結果、以下のライセンスと記載内容でお願い致します。
・日本語
`このサイトの内容物は クリエイティブ・コモンズ 表示 4.0 ライセンスの下に提供されています。`
https://creativecommons.org/licenses/by/4.0/deed.ja
・英語
`Content on This Site is Licensed Under a Creative Commons Attribution 4.0 International License.`
https://creativecommons.org/licenses/by/4.0/

**Comment by ocean3fish** [comment]
@yasushisakai さん、この度はご提案ありがとうございます！
上記 @NaoyaShimizzz さんの示されている方向で話がまとまったのですが、CC BY-SAではなくCC BYが採用されたため、変更の上PRを出して頂くことは可能でしょうか？
もしお忙しい場合はこちらで対応させて頂きます。

**Comment by yasushisakai** [comment]
了解です、対応します！

**Comment by yasushisakai** [comment]
@ocean3fish さんの上で対応されているそうなので、こちらのPRは引き下げます。

**Comment by halsk** [comment]
すみません。こちらは一旦仕切り直しで。ライセンスは CC-BY 4.0 ですが、
日本語ページでは日本語で、英語ページでは英語版で表示

**Comment by ocean3fish** [comment]
@halsk @kaizumaki 
@yasushisakai さんに実装を進めて頂くにあたっての確認なのですが、こちらも日英対応必要なので、ブランチ `dev-i18n` から持ってくる必要有でしょうか？
あと、英語以外の外語語も一旦英語で良いですよね？

**Comment by kaizumaki** [comment]
@ocean3fish おそらく次の大きなリリースは `dev-i18n` になるので、むしろこちらのブランチのほうが最新かと思われます。

**Comment by ocean3fish** [comment]
急いだ方が良さそうなので、私の方から再度PR出してみます。

**Comment by ocean3fish** [comment]
@yasushisakai 今回リリースのスケジュール上の都合で担当をお願いすることができませんでしたが、ご提案頂けたおかげで動くことができ大変感謝しております！
この度は本当にありがとうございました。

**Comment by yasushisakai** [comment]
すみません、こちらも環境がごたついており、対応が遅れしまいましたすみません。@ocean3fishさんありがとうございました。
