### ISSUE TITLE
「検査陽性者の状況」の図の脱SVG化

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#834]
## 改善詳細 / Improve details
- flowページと同様(#659)の案件で、`components/ConfirmedCasesTable.vue`についてSVG画像を使用しないようにしてほしいです。

**Comment by MaySoMusician** [comment]
@kaizumaki もしお手すきでしたら、こちらの案件も取り仕切っていただけますか？

**Comment by kaizumaki** [comment]
@MaySoMusician お、ちょっと現状を把握しますね！ちょいとお待ちを。

**Comment by MaySoMusician** [comment]
@kaizumaki ありがとうございます。こちらでわかっている範囲ですと
- 「○人」はvue側で変更可能
- 「検査実施人数」などのヘッダーはSVGのpathなので変更できない
という状況です

flowページ側と同じような感じで進めていただいちゃって大丈夫です。というかよろしくお願いします...

**Comment by kaizumaki** [comment]
@MaySoMusician なるほど、承知しました。
ちょっと思ったんですが、ここはアクセシビリティチームにコーディングに入ってもらったほうが何かといいような気がしています。
というわけで、 @oti さんいかがでしょうか？ （アイディアレベルでかまいません）

**Comment by mikkame** [comment]
それか文字がアウトラインになってないバージョンのsvgをもらう事ができれば取り急ぎそれでも良さそうかな？

**Comment by kaizumaki** [comment]
改めてsvgを眺めましたが、これはあくまで「表」であるので、table組みでよさそうです。
私のほうで旗振りしてみます。

**Comment by oti** [comment]
確認しました。

人数の包含関係を `<table>` 要素で表現するのが結構しんどそうに思います。`rowspan` や `colspan` でセルを結合しただけでは該当のデータを別のデータが内包していると言うセマンティクスにはならないため、注意が必要です。包含関係をマークアップで実現しようと思うとリスト要素を入れ子にするのが良さそうに感じます。

**Comment by forestgtree** [comment]
@oti 確かにそうですね… #860 に
理想となる入れ子構造のソースを案内していただけると助かります 🙇‍♂️

**Comment by oti** [comment]
@forestgtree 元のSVGの見た目を再現しないでも良いでしょうか？

**Comment by kaizumaki** [comment]
@oti あ、見た目は再現の方向でお願いしたいです。

**Comment by oti** [comment]
@kaizumaki そうなんですね、すみませんその前提を理解できてませんでした

だとしたら無理にSVGをやめない方が良いと思います。mikkame さんのおっしゃっているようにラベル部分が生のテキストになれば十分かなと。このSVGをHTMLで再現するのはかなり難易度が高いです。

**Comment by kaizumaki** [comment]
@oti なるほど、そうなんですね。
@mikkame @MaySoMusician テキスト状態のSVGのi18n化するのって、いけそうですか？

**Comment by MaySoMusician** [comment]
もとの日本語がHTML上（Vue template上）で保持されている、かつプログラムで動的に書き換えられるならたぶんいけるはず（要検証）
サンプルになるデータがあれば検証できます

**Comment by kaizumaki** [comment]
@MaySoMusician いまの `components/ConfirmedCasesTable.vue` の122行目などは
```
<tspan class="unit" dx="-3">人</tspan>
```
というふうにテキストになっています。ここの部分で検証できますでしょうか？

**Comment by MaySoMusician** [comment]
上の部分で翻訳できたので、SVG内テキストについては翻訳可能の様です
レイアウトをガン無視してますが...

---
![image](https://user-images.githubusercontent.com/34566290/76178652-648eff00-61fb-11ea-85b9-35cfef5d65a7.png)

**Comment by kaizumaki** [comment]
おお、テキストあふれちゃってますね・・・
これはちょっと不安ですね。。

**Comment by MaySoMusician** [comment]
（単位: 人）みたいなのを上の方に書いて、SVG内は数字だけにするのはどうでしょう
注釈部分に複数行入れられるかは試してないですが...

**Comment by mikkame** [comment]
v-ifこの言語の時のみ改行 or :style={fontSize:lang== 'en' ? "" : '"} みたいな感じでゴリ押せたりしませんか？

**Comment by kaizumaki** [comment]
やっぱりtableコーディングも進めましょう。テキスト状態のSVGも用意することにしましょうか。
ちょっとどっちに転ぶかわからないですが・・・
@MaySoMusician すみませんが、しばしお待ちください！お手数おかけします 🙇‍♀

**Comment by mikkame** [comment]
とりあえず翻訳文だけあったら出来上がり次第どっちでも差し替えれるはず！

**Comment by kaizumaki** [comment]
#1022 でコード化されました！

**Comment by MaySoMusician** [comment]
@kaizumaki ありがとうございます！ こちら一部`<br />`ありますがどうしましょうか
すぐ除去できる（無くてもよいスタイルになる）なら良いのですが、もし無理そうな場合は、
- 日中韓など、改行1回で済みそうな部分は翻訳側で指定
- 英語など、改行が複数回にわたる・言語の特性で縦長で上手く表示しにくい場合は、`<br />`は指定せずにブラウザによる自動改行に任せる

で行こうと思いますがどうでしょう。
Flowとは異なる方針ですが、こちらは表のデザインなのでやむを得ないと思っています。

**Comment by kaizumaki** [comment]
@MaySoMusician 個人的にはbrがなくてもよい気がしてるんですが、見た目は要確認でしょうね。

**Comment by kaizumaki** [comment]
@MaySoMusician もし言語ごとの改行が対応できるのであれば、その方向で進めてもらったほうがいいかもしれません。

**Comment by MaySoMusician** [comment]
> @MaySoMusician もし言語ごとの改行が対応できるのであれば、その方向で進めてもらったほうがいいかもしれません。

ではそうしたいと思います

**Comment by asuchi0819** [comment]
フレキシブルに行けるようにHTMLとCSSだけでごり押ししてみました。

以下のコードでネックになっている点
- borderの関係で微妙な三角が見える
- relativeで移動させた分の補完
- 微妙なスタイル修正

tableを使わなければもう少しごり押し行けそうです。

```HTML
<!DOCTYPE html>
<meta charset=UTF-8 />
<style>
  table {
    border-spacing: 5px
  }
  * {
    margin: 0;
    padding: 0
  }
  td {
    height: 1rem;
    border: 2px solid green
  }
  .td-black {
    height: 3rem;
    border: 2px solid #000
  }
  .dock {
    position: relative;
    top: -7px;
    border-top: 2px solid #FFF
  }
</style>
<table>
  <tr><td class=td-black rowspan=3>検査実施人数</td><td colspan=6></td></tr>
  <tr><td class=dock rowspan=2>陽性者数（累積）</td><td colspan=3></td><td rowspan=2>死亡</td><td rowspan=2>退院</td></tr>
  <tr><td class=dock>入院中</td><td>軽症・中等症</td><td>重症</td></tr>
</table>
```

![image](https://user-images.githubusercontent.com/45027336/76333470-0a925480-6335-11ea-894d-cc3476bc75d3.png)

ご参考？までに、、、

**Comment by ocean3fish** [comment]
#1022 で対応完了との認識なので、本件はクローズさせて頂きます。
