### ISSUE TITLE
開発環境を表示する場合はどこかに開発環境とわかるメッセージを表示する

### ISSUE THREAD

**Issue by mikkame** [tokyo-metropolitan-gov/covid19#837]
## 改善詳細 / Improve details
- 現在、テスト環境でも本番環境と遜色なく表示される
- 間違えてシェアされた場合に困る（表示データが古かったり）

## 期待する見せ方・挙動 / Expected behavior
- 本番環境以外に開発環境だとわかる印を表示する
- 本番環境へ誘導できるとベスト

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by DJYoko** [comment]
「間違えてシェア」がURLベースとは限らずスクショ等であるケースも踏まえると
PC, モバイルともに常に画面のどこかに `開発中`  が表示されているようなものが良いのではないでしょうか

**Comment by DJYoko** [comment]
試作してみまして、スクショ用意します

**Comment by DJYoko** [comment]
プルリクでスクショ貼りました
https://github.com/tokyo-metropolitan-gov/covid19/pull/847

※他の皆さんで別に良い案があればこちらプルリクは破棄で構いません
