### ISSUE TITLE
How to contribute で、Issue 作成を必須とする

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#838]
## 改善詳細 / Improve details
- 今の how to contribute は、簡単なものであればいきなり PR を投げて良いことになっているが、だいぶ PR が乱立してきて、更に重複PRも増えてきたので見通しが悪くなった。そのため、記載を変更したい。

* Issue に紐付かない PR は禁止とする
* Issue を切る前に、必ず同様のIssueが無いか検索してもらう

**Comment by munierujp** [comment]
`.github/PULL_REQUEST_TEMPLATE.md`の文言も変更が必要になりますね。

**Comment by halsk** [comment]
@munierujp ご指摘ありがとうございます。そちらも書き換えました。
