### ISSUE TITLE
[3/8 更新] Issue 番号の無いPRは禁止としました。

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#841]
だいぶ PR が乱立してきて、更に重複PRも増え見通しが悪くなったため、Issue 番号が無い PR は受け付けないことにしました。

[CONTRIBUTING.md](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/CONTRIBUTING.md) を変更していますので、ご確認ください。
簡単に言えば、

* Issue に紐付かない PR は禁止とする
* Issue を切る前に、必ず同様のIssueが無いか検索してもらう

という内容を追記しています。

**Comment by munierujp** [comment]
過去に作成済みのプルリクエストについても、遡ってイシューを立てるべきでしょうか？

**Comment by halsk** [comment]
> 過去に作成済みのプルリクエストについても、遡ってイシューを立てるべきでしょうか？

過去のものについては、Issue 番号がなくてもレビューはしていきますが、Issue を立てていただけるのであれば助かります。(他の人が重複Issueを作るのが避けられるため)

**Comment by halsk** [comment]
周知されたのでクローズします。
