### ISSUE TITLE
「企業の皆様・はたらく皆様へ」の内容が重複している

### ISSUE THREAD

**Issue by ru10q** [tokyo-metropolitan-gov/covid19#843]
## 起こっている問題 / Occurred problem
「企業の皆様・はたらく皆様へ」ページの`新型コロナウイルス感染症対応緊急融資`, `新型コロナウイルスによる経営課題に関する専門家派遣`, `事業継続緊急対策（テレワーク）助成金`が重複して表示されている。

## スクリーンショット / Screenshot
![before](https://user-images.githubusercontent.com/23010917/76165085-8787c780-6197-11ea-9102-73643c3fcd11.png)

## 期待する見せ方・挙動 / Expected behavior
内容が重複しないこと。

## 起こっている問題の再現手段 / Steps to reproduce
https://dev-covid19-tokyo.netlify.com/worker/ にアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mikkame** [comment]
masterでは発生していないようなのでdevだけの症状のようです
