### ISSUE TITLE
[i18n] 翻訳へのご協力をお願いします！

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#848]
## 改善詳細 / Improve details
- 多言語化対応のため、[翻訳シート](https://docs.google.com/spreadsheets/d/1avT6QGInyQseYjoc_TxL8RPZfutyvrv4BtJkXfk1Nko/edit)の内容を完成させたい。

**Comment by studioego** [comment]
added and fixed Korean Translation

**Comment by tsuruchika** [comment]
A列「ウェブサイトの場所」単位で「export」シートにJSON吐き出すものって需要あります？  🤔 
現状各言語に改行が意図してか意図せずか入ってるものがあり、整形しないといけないものもありそうですが。
```js
function myFunction() {
  var target = '1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw'; 
  // スプレッドシートの取得
  const spreadsheet = SpreadsheetApp.openById(target);
  // 翻訳シートの取得
  const lang_sheet = spreadsheet.getSheetByName('Sheet1');
  // 出力先シートの取得
  const export_sheet = spreadsheet.getSheetByName('export');
  // A列の値を全て取得
  const a_values = lang_sheet.getRange('A:A').getValues();
  // A列の最大
  const last_row = a_values.filter(String).length;
  
  var category = '';
  var set_row = '0';
  var data_set = {'ja':{},'en':{},'zh-cn':{},'zh-tw':{},'kr':{},'ja-basic':{},'pt':{}};
  
  for(let i =2;  i <= last_row; i++) {
    var position = lang_sheet.getRange(i, 1).getValue();
    if(position){
      // 前の「ウェブサイトの場所」と異なる場合
      if(category !== position){
        // exportシートで出力する行をずらす
        set_row++;
        // 新しい「ウェブサイトの場所」をセット
        category = position;
        // exportシートに「ウェブサイトの場所」を追加
        export_sheet.getRange(set_row, 1).setValue(category);
        if(set_row !== 1){
          // exportシートにJSON貼り付け
          export_sheet.getRange(set_row-1, 2).setValue(JSON.stringify(data_set));
        }
        //初期化
        data_set = {'ja':{},'en':{},'zh-cn':{},'zh-tw':{},'kr':{},'ja-basic':{},'pt':{}};
      }
      //各言語の文字列セット
      var ja = lang_sheet.getRange(i, 2).getValue();
      data_set['ja'][ja] = ja;
      data_set['en'][ja] = lang_sheet.getRange(i, 3).getValue();
      data_set['zh-cn'][ja] = lang_sheet.getRange(i, 4).getValue();
      data_set['zh-tw'][ja] = lang_sheet.getRange(i, 5).getValue();
      data_set['kr'][ja] = lang_sheet.getRange(i, 6).getValue();
      data_set['ja-basic'][ja] = lang_sheet.getRange(i, 7).getValue();
      data_set['pt'][ja] = lang_sheet.getRange(i, 8).getValue();
    }
  }
  //最後のexportシートにJSON貼り付け
  export_sheet.getRange(set_row, 2).setValue(JSON.stringify(data_set));
}
```

**Comment by MaySoMusician** [comment]
A列「ウェブサイトの場所」は入力の仕様が定まってなくて、ページ名だったりコンポーネント名だったりしています。また実際にvueファイルに埋め込む際も、埋め込み先がページファイルかコンポーネントファイルかは様々になっています。
個人的には、言語ごとに分かれていたほうが使いやすいのではないかと思います
（特に修正を要求するものではないです... 念のため）

**Comment by tsuruchika** [comment]
@MaySoMusician 確かにA列が実際のコンポーネント名などとは紐付いていなかったりするのと、プルリク見ても埋め込み先が色々あるなと現状を把握しました。
返信ありがとうございました 🙇

**Comment by MaySoMusician** [comment]
**中国語（簡体字・繁体字）を翻訳者の方へ:**
Row 193の「検査実施数」の翻訳の確認をお願いします。この翻訳はもともと「検査実施人数」と登録されていましたが、ウェブサイトでの変更に合わせてスプレッドシート上でも更新しました。

**To Chinese language (both simplified and traditional) translators:**
Could you check the translation of 検査実施数 (Number of tested) (Row 193)? This term was formerly 検査実施人数, and it is updated on the spreadsheet according to the change on the website.

**Comment by J3rd-dev** [comment]
「やさしい にほんご」について、皆さんと協力しながら追記＋これまでに書いたところの僅かな修正が終わりましたこと、取り急ぎご連絡いたします。
です、ます調での統一等をなるべく行いましたが、専門家の方がいらっしゃれば、再度一気通貫でご確認をお願いしたく、随時修正頂けましたら幸いです。

**Comment by timothylin** [comment]
@MaySoMusician , @halsk ,
Chinese translations (both simplified an traditional) for 検査実施数 (Number of tested) (Row 192) looks good now.
Thank you!

**Comment by colspan** [comment]
韓国語の最後の数行を埋めました。私はネイティブではないので、どなたかレビューをいただければ幸いです。

**Comment by J3rd-dev** [comment]
「やさしい にほんご」について
3/9 1:00反映の緊急融資額、ソフトウェア補助金について未反映でしたので、今しがた反映させました。slackの辞書設定反映後かもしれませんが、取り急ぎご連絡まで。

**Comment by crispytaffy** [comment]
シート161-163行目のIssue #845 追加テキストの英訳完了しました。

**Comment by aki-snow** [comment]
[翻訳シート](https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0)にベトナム語を追加します。

**Comment by nuwaa** [comment]
[翻訳シート](https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0)の46行目、以下の訂正をしました。
地下鐵→地鐵
地下铁→地铁

**Comment by nuwaa** [comment]
[翻訳シート](https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0)の46行目、「都営地下鉄4路線の自動改札出場数」の件です。
「自動改札」のはずなのですが、他の言語に翻訳の時点でそれが欠落しているように見受けられます。
「切符を買って有人の改札を通った場合はカウントされないよね?」とも思えてしまいますため、仕組みの確認なり、それぞれの言語に「自動改札」を含むことの検討も必要かもです。

**Comment by moreta** [comment]
@colspan 

韓国語大丈夫そうでした。結構いろんな方が入れていますね。

**Comment by tomoshi0809** [comment]
翻訳シートにおける「やさしい日本語」，現在のところ全てひらがな表記されており，かえってわかりづらくなることを危惧しているのですが，もし詳しい方がおられたらコメント頂戴したいです．
東京都のページでは，「東京都（とうきょうと）からの　お知（し）らせ　【読（よ）んでください】」というように，漢字＋ふりがなとなっているようです．

**Comment by J3rd-dev** [comment]
@tomoshi0809 
都の「やさしい日本語」についてのレギュレーション指針を
短い時間の中で自分ではうまく見つけられなかったのですが、
都のサイトで、オリンピック・パラリンピック準備局HPに
その考え方や参考URLの記載があります。
https://www.2020games.metro.tokyo.lg.jp/multilingual/references/easyjpn.html

※都は「やさしいにほんご」ではなく「やさしい日本語（にほんご）」としています。

横浜市など、様々な「やさしいにほんご」サイトも見たのですが
・誰にもやさしく理解できる　　
　という意味に加え、
・漢字＋ひらがな表記
としておくことで、新たな情報や他の媒体（テレビや掲示物）に対しても
対応力が一部備わると思いますので、「漢字＋ひらがな」表記に変更とすべきと思います。

何より東京都の他のサイトでは、いずれも「やさしい日本語漢字＋ひらがな」表記なので
こちらにすべきと考え直しました。

【対応について】
１．どなたかがコーディング中かもしれませんので、
　　まずはslack code for japan, COVID19 channelにまずは連絡しておきます。
　
２．翻訳シートについて元の列ではなく、
　　今しがた追加したL列に「やさしい日本語（にほんご）」の欄を作りました。
　　皆さんの意見も聞きつつ、並行してこちらで皆さんで書いていくのでいかがでしょう

（３．Issue立てるかもしれません。）

以下、補足）
東京都のコロナ関係HPで用いられている「やさしい日本語」
https://www.metro.tokyo.lg.jp/tosei/tosei/news/2019-ncov.html#Ja
↓
https://www.seikatubunka.metro.tokyo.lg.jp/chiiki_tabunka/tabunka/tabunkasuishin/0000001389.html
↓
https://www.seikatubunka.metro.tokyo.lg.jp/chiiki_tabunka/tabunka/tabunkasuishin/files/0000001389/20200225_yasanichi_coronavirus.pdf
↓
(PDF中 本文内参考資料として)
http://www.clair.or.jp/tabunka/portal/info/contents/114517.php

**Comment by J3rd-dev** [comment]
【FYI】上記に関連してslackにも共有しました。https://cfj.slack.com/archives/CUX3F56LF/p1583789837199100

**Comment by J3rd-dev** [comment]
補足です。今回、あくまで平易な訳として「やさしい日本語」をみんなで作っているので
・「一般欄の通常表記にふりがなを設ける」のではなく、
・「平易なやさしいにほんご」に対して、反映できる漢字は入れておこう　という意味で
考えました。
　※例）東京都（とうきょうと）

こちらで進めていこうかと考えましたが、
皆さんのご意見、お気づきの点があれば、是非宜しくお願い致します。

**Comment by J3rd-dev** [comment]
例えば、「コロナウイルス感染症が心配なときに」の文書を
やさしいにほんごでは「コロナウイルス　が　こわい　ときに」
と変換しています。

元々の原文にある言葉は基本漢字＋ふりがな変換にするとして
このように、変換後の言葉のみに表れる言葉について
・怖（こわ）い
 と漢字＋ふりがな　とするか
・こわい
のみとするか、どちらが皆さんは望ましいと感じますか？

漢字検定１０級程度等、都のレギュレーションがあればそれに沿いたいのですが
現時点でわからないため、
いまのところは以下の都のPDF等を参考にしながら、
"頻出する用語について"のみ
翻訳語も漢字＋ひらがな　で一度書いてみるようにしたいと思います。

参考）https://www.seikatubunka.metro.tokyo.lg.jp/chiiki_tabunka/tabunka/tabunkasuishin/files/0000001389/20200225_yasanichi_coronavirus.pdf

**Comment by ym8811** [comment]
@nuwaa 

こちらの「自動改札出場数」の意味を反映した表現として、英語版を
”The total number passing through automatic ticket gates on 4 Toei subway lines”で、コメント欄に提案してみました。

> [翻訳シート](https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0)の46行目、「都営地下鉄4路線の自動改札出場数」の件です。
> 「自動改札」のはずなのですが、他の言語に翻訳の時点でそれが欠落しているように見受けられます。
> 「切符を買って有人の改札を通った場合はカウントされないよね?」とも思えてしまいますため、仕組みの確認なり、それぞれの言語に「自動改札」を含むことの検討も必要かもです。

**Comment by timothylin** [comment]
@ym8811 , @nuwaa 

How about:
"Total number of passengers who exited through an automatic ticket gate on the 4 Toei Subway lines"
I've added it to the comment on the Google Spreadsheet as well!
Thank you!

**Comment by ym8811** [comment]
@timothylin Thanks for your suggestion! 
I checked the translation on the web page of Tokyo Metro subway, It's also used "Exiting the Fare Gate" from https://www.tokyometro.jp/en/tips/after.html.  I think that's good modification :)

**Comment by MaySoMusician** [comment]
「やさしい日本語」について、承知いたしました。
ただ、進行中のi18n化プロジェクトでは既に「やさしいにほんご」（漢字無し）版で反映してしまっているため

1. 「やさしいにほんご」（漢字無し）を全てに反映させる
2. 1が完了した後、「やさしい日本語」（漢字あり）に置き換える

の流れで行くのが良いと思います。

---
加えて、「やさしいにほんご」「やさしい日本語」に含まれるスペース（空白）は、 **半角スペースのみ** でお願いいたします（ソースコードに全角空白が含まれているとエラーになる設定になっているため）

**Comment by J3rd-dev** [comment]
@MaySoMusician 大変ありがとうございます。
やさしい日本語（にほんご）の件、大まかではありますが簡単に整理・改訂を行いました。

複数の方々で追記出来、速く記入が出来た一方、
書き方や表現が異なっているものも多かったため、
漢字追加だけでなく表現更新含めた改訂版を
スプレッドシートM列に記載しました。（#872連動）

HPでの図の見え方を眺めながら修正かけましたが、
Git反映後、文書が冗長で見づらい等があるかもしれません。
適宜、ご連絡した上で再度修正かけるようにします。

追伸：（半角スペースにて統一しました！）

**Comment by nard-tech** [comment]
@J3rd-dev #872 にもコメントしましたが，やさしい日本語（にほんご）の更新，私がやりますのでよろしくお願いします．

**Comment by J3rd-dev** [comment]
@nard-tech ありがとうございました！

**Comment by paichi81** [comment]
179 ポルトガル～インドネシアまで {numberOfPerson} を用いず、数字が直接入力されているので修正しました。

**Comment by halsk** [comment]
[翻訳シートのURLが変わりました]
100名以上が編集しようとすると編集ができなくなるという制限に引っかかりまして、一旦新しくシートをこちらに作りました。お手数をおかけしますが、皆様こちらをご利用ください。
https://docs.google.com/spreadsheets/d/1avT6QGInyQseYjoc_TxL8RPZfutyvrv4BtJkXfk1Nko/edit?usp=sharing
（翻訳管理については、今後Transifex などの翻訳サイトへの移行を検討中です。）

**Comment by aki-snow** [comment]
[covid19_wordstable_0312_proof-readed.xlsx](https://github.com/tokyo-metropolitan-gov/covid19/files/4327480/covid19_wordstable_0312_proof-readed.xlsx)

ベトナム語について、ファイルの"置き換え推奨"のところだけ、置き換えました。
また、念のため置き換え後にベトナムメンバーでダブルチェック、および未入力項目を追記しました。

**Comment by halsk** [comment]
Transifex へ移行するため、こちらはクローズします。
