### ISSUE TITLE
[翻訳] 都の相談窓口などを多言語化するときの正式名称について

### ISSUE THREAD

**Issue by crispytaffy** [tokyo-metropolitan-gov/covid19#851]
## 改善詳細 / Improve details
都の相談窓口や取り組みなどについての英語での正式名称を反映したい。

## お願いしたいこと
都庁にて多言語での正式名称がすでにあるか確認したいです。
どなたかサポートいただけないでしょうか。

### 確認したい箇所
翻訳シートのコメント欄にいくつか課題として上がっているので、こちらに転記します。
（日本語のあとは、翻訳チームで訳したものです）

▽重要度の高いもの

- [x]  新型コロナ受診相談窓口 combined telephone advice center -> OK
- [x] 新型コロナコールセンター COVID-19 Telephone Advisory Center -> Tokyo Metropolitan Telephone Consultation

▽もしわかると精度が高まるもの
- [x]  東京都オープンデータカタログサイト Tokyo Metropolitan Government Open Data Catalog site  -> OK. Tokyo Challengeサイトで確認取れました
- [ ]  中小企業者等特別相談窓口 Special consultation counter for SMEs
- [ ]  緊急労働相談ダイヤル Emergency labor consultation service
- [ ]  新しいワークスタイルや企業活動の東京モデル「スムーズビズ」 "Smooth Biz": Tokyo-model for new work styles and corporate activities
- [ ]  事業継続緊急対策（テレワーク）助成金 Business continuity  emergency countermeasures (telework) grants-in-aid
- [ ]  東京2020大会 the Tokyo 2020 Games -> the Tokyo 2020 (?)

## 希望する期限
特に重要度の高いものについてはi18n対応時点で正しい名称で公開できればと思っています。

以上です。よろしくお願いします。

**Comment by asuchi0819** [comment]
> 新型コロナコールセンター
or
> 新型コロナ受診相談窓口

> the telephone advice center for returnees and people who have been in contact with the virus that is located at your local health center.
https://www.metro.tokyo.lg.jp/english/topics/2020/0214_00covid19.html

文脈的にどちらの日本語に当てはまるかわかりませんでした。
---
> 東京2020大会 the Tokyo 2020 Games

https://www.metro.tokyo.lg.jp/ENGLISH/ABOUT/APPENDIX/appendix05.htm
> Tokyo 2020 Olympic and Paralympic Games
東京都のホームページにありましたが少々長いです。

その他のIOCや組織委員会・Wikipediaを見ていると
Tokyo 2020 や それぞれ別の名前を用いているようでした。

ここら辺を総合すると東京都の表現ではありませんがTokyo 2020 の表記でよいとは思います。

**Comment by tomoshi0809** [comment]
新型コロナ受診相談窓口については，都庁のページにあるように，combined telephone advice centerであっているかと思います．
> Call the combined telephone advice center (03-5320-4592) (support in Japanese only)

**Comment by crispytaffy** [comment]
asuchi0819さん、tomoshi0809さん、ありがとうございます。

新型コロナ受診相談窓口については「combined telephone advice center」で良さそうですね。こちらで確定としました！

**Comment by y613** [comment]
新型コロナコールセンターのほうは「Tokyo Metropolitan Telephone Consultation」と表記されています。

> please contact the Tokyo Metropolitan Telephone Consultation at (Navi-dial) 0570-550571.

[https://www.metro.tokyo.lg.jp/english/guide/radio.html](https://www.metro.tokyo.lg.jp/english/guide/radio.html)

**Comment by crispytaffy** [comment]
y613さん、ありがとうございます！確認し、翻訳シートに反映しました。

**Comment by ocean3fish** [comment]
こちら一旦解決したようですので、クローズとさせて頂きます。
もし間違いでしたらre-openしますのでお知らせください。
