### ISSUE TITLE
グラフごとのパーマリンク／シェアのUIデザイン

### ISSUE THREAD

**Issue by saladdays** [tokyo-metropolitan-gov/covid19#853]
## 改善詳細 / Improve details
- https://github.com/tokyo-metropolitan-gov/covid19/issues/774 のデザイン
- すでに実装は進んでいるのでデザインは後付でも大丈夫です https://github.com/yasu/covid19/pull/1
- グラフ単位でソーシャルボタンが全て出ていると見た目的な圧迫感が出るのと一つのカードが縦に長くなってしまうため、まとめたシェアボタンから各ボタンが展開するようにする

## スクリーンショット / Screenshot

[デザインデータ（Figma）](https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=24461%3A2875)
|通常時|シェアボタンクリック|クリップボードアイコンクリック|
|---|---|---|
|![image](https://user-images.githubusercontent.com/1301149/76167725-37ffc680-61ac-11ea-8a8c-67c5e7a6f48f.png)|![image](https://user-images.githubusercontent.com/1301149/76167811-e7d53400-61ac-11ea-8958-907f7ea3a263.png)|![image](https://user-images.githubusercontent.com/1301149/76167728-3df5a780-61ac-11ea-8bfc-7f86a4720d87.png)|

## 期待する見せ方・挙動 / Expected behavior
1. 右下のシェアボタンをクリックする
1. ポップアップが表示
  1. 表示されるボタンをクリックすると各SNSのシェア投稿ページへ遷移
  1. 埋め込みURLの右上のコピーボタンをクリックした場合は、シェアボタンなどを閉じてコピーが完了した旨を表示する
1. 右上のバツボタンを押すとポップアップは消える

埋め込み用URLのコピーボタン配置はできればやりたい程度で優先度は下げて構いません。
対応しないブラウザの場合はコピーボタンを非表示にできるのが望ましいです。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ryuckel** [comment]
初参加でよければ、こちら対応しましょうか？

**Comment by yasu** [comment]
@saladdays @ryuckel ありがとうございます 🙏 
協力お願いできますか？

https://github.com/yasu/covid19/pull/1
で現状、LINEのアイコンを出すのに苦労していたので、そちら含めて見た目の調整ご協力お願いできれば幸いです。

**Comment by ryuckel** [comment]
@yasu 
承知いたしました。確認します！

**Comment by ryuckel** [comment]
@saladdays すみません。宣言したものの、急遽対応できなくなってしまい、一旦リリースしてもよろしいでしょうか

**Comment by saladdays** [comment]
@ryuckel かしこまりました！

**Comment by rozeo** [comment]
AssignいなさそうであればWIPで対応してみてもよろしいでしょうか？

**Comment by kaizumaki** [comment]
@rozeo よろしくお願いします！
