### ISSUE TITLE
「検査陽性者の状況」コンポーネントコーディング（table組みでOK!）

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#860]
多言語化に向けて、以下の画像（svg）部分のコーディングをお願いします。

![スクリーンショット 2020-03-09 9 02 20](https://user-images.githubusercontent.com/14883063/76173728-3b637400-61e5-11ea-90aa-f12f293f965f.png)

- `components/ConfirmedCasesTable.vue` の中身が `svg` になっているので、ここをHTMLコードに置き換えます。
- ~~これはあくまで「表」なので、**table組みでOK**です。~~
- colorは `assets/variables.scss` の中からsassの変数として使ってください。

なにか疑問点あれば、このissueでコメントしてください！

### 関連issue
#834
#309

**Comment by takuya320** [comment]
すみません。
このようなプロジェクトに参加するのは初めてなのですが、
こちら着手させていただいてもよろしいでしょうか？

**Comment by kaizumaki** [comment]
@takuya320 おお！ありがとうございます！ぜひお願いします！

**Comment by kaizumaki** [comment]
@takuya320 すみません。tableでOKと書いたのですが、[こちら](https://github.com/tokyo-metropolitan-gov/covid19/issues/834#issuecomment-596281776)をご確認ください。

**Comment by kaizumaki** [comment]
@takuya320 なんどもすみません。こちらhttps://github.com/tokyo-metropolitan-gov/covid19/issues/834#issuecomment-596298203 でコーディングの再検討が進んでいます。ちょっと作業を止めておいてもらっていいですか？

**Comment by takuya320** [comment]
@kaizumaki 承知しました。

**Comment by kaizumaki** [comment]
@takuya320 https://github.com/tokyo-metropolitan-gov/covid19/issues/834#issuecomment-596309877　ということで、こちらのissueは当初の計画通りtable組みで進めることにしました。どうぞよろしくお願いします！
わからないことがあったらお気軽にコメントくださいね。

**Comment by takuya320** [comment]
@kaizumaki 
お知らせありがとうございます。
#834 や他のissueを確認しつつ進めてみます！

わからないことがあり、質問させていただくことがあるかもしれませんが
よろしくお願いいたします。

**Comment by takuya320** [comment]
@kaizumaki 
力が足りず申し訳ないのですが、
元のSVGをtableで組もうとすると以下のように不自然な形になってしまいました。

<img width="554" alt="スクリーンショット 2020-03-10 10 53 53" src="https://user-images.githubusercontent.com/12983438/76272075-aed8b480-62bd-11ea-8188-cd537f57ff08.png">

データの隙間を埋めてしまえば、
以下のように不自然な部分をなくして表現することができました。

<img width="555" alt="スクリーンショット 2020-03-10 10 40 18" src="https://user-images.githubusercontent.com/12983438/76272080-b1d3a500-62bd-11ea-96a1-970bb189f8a7.png">

ご確認よろしくお願いいたします。

**Comment by kaizumaki** [comment]
@takuya320 お、提案ありがとうございます！
@ocean3fish @osoken 上記の提案はいかがでしょう？

**Comment by ocean3fish** [comment]
ご検討ありがとうございますー。
元の構成から変わるわけではないので、私は大丈夫かと思います。
あとはデザインをご検討頂いた @saladdays さんがOKでしたら。

**Comment by mikkame** [comment]
@takuya320 ご対応ありがとうございます！
一旦この下の方でPR出していただけますか？

**Comment by macropygia** [comment]
横から失礼します。
恐らくこんな感じなら #834 の要求も満たしつつ行けるんじゃないでしょうか。
幅可変(メディアクエリで細かく整えるのも可)、IE11対応、仮組みのため各所の寸法は適当です。

https://codepen.io/macropygia/pen/eYNyMYb

**Comment by kaizumaki** [comment]
@macropygia おお！すごい！ありがとうございます。[WIP]をつけてプルリク出してみてもらえますか？

**Comment by macropygia** [comment]
@kaizumaki @oti 

- セマンティクスを考慮すると下記コードブロックの構造の方がよいでしょうか
- ほぼ好みですが `p>span+span` ではなく `dl>dt+dd` の方がよい？

```html
<ul>
  <li>
    <p>
      <span>検査実施人数</span>
      <span>1068<small>人</small></span>
    </p>
  </li>
  <li>
    <p>
      <span>陽性者数(累積)</span>
      <span>58<small>人</small></span>
    </p>
    <ul>
      <li>
        <p>
          <span>入院中</span>
          <span>37<small>人</small></span>
        </p>
        <ul>
          <li>
            <p>
              <span>軽症・中等症</span>
              <span>29<small>人</small></span>
            </p>
          </li>
          <li>
            <p>
              <span>重症</span>
              <span>8<small>人</small></span>
            </p>
          </li>
        </ul>
      </li>
      <li>
        <p>
          <span>死亡</span>
          <span>1<small>人</small></span>
        </p>
      </li>
      <li>
        <p>
          <span>退院</span>
          <span>20<small>人</small></span>
        </p>
      </li>
    </ul>
  </li>
</ul>
```

**Comment by kaizumaki** [comment]
なるほどですね。私は `dl>dt+dd` でできるならそのほうがいいような気がします。 @oti さん、いかがですか？
でも、だめそうだったら `ul>li+li+...` で大丈夫ですよ！

**Comment by oti** [comment]
@macropygia @kaizumaki
再現素晴らしいですね！👏👏👏

`ul > li > dl` はセマンティクス過剰に思います。
`li` 内の `p` がレイアウト的に必要であれば `div` で、もし不要であれば取り除いてください。

リスト要素を使う場合は `li` の中に意味的な構造を持たせる必要は基本的にないです。
テキストも短いですし、「退院20人」と口頭で説明されれば普通に理解できるので、ラベルを意識しなくて大丈夫です。

もう一点、`small` はその使い方は間違いなので、 `span` にしてクラスを降ってスタイル調整してください。

`li` 内抜粋しますと（`div`ナシの場合）`small` -> `span` に変えていただければOKです！

```
      <li>
        <span>退院</span>
        <span>20</span><span>人</span>
      </li>
```

**Comment by macropygia** [comment]
@kaizumaki @oti 承知しました、着手します

**Comment by kaizumaki** [comment]
@macropygia プルリクありがとうございました。
@takuya320 さんも、着手していただき感謝です！ 🙇‍♀ またぜひご協力ください！
