### ISSUE TITLE
「最新のお知らせ」の自動取り込み化

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#862]
最新のお知らせについて、東京都側の掲載希望内容を自動で取り込めるよう、Excelシート化します。
都側でこちらのシートを更新しますので、適宜取り込んで表示する仕組みとします。

項目名は、
No：表示順位（表示しない）
掲載日：お知らせの掲載日（表示項目）
タイトル：表示する文字列（表示項目）
URL:リンク先
になります。
上位2つのみ表示対象としてかまいません（現在の表示方法は変更しない）。
サンプルのデータファイルは、Sharepointサイトに掲載しております。

**Comment by mtenjin** [comment]
お知らせの要望が日中に複数来ますので、この部分だけでも例えば1時間毎にPollingして比較的短いタイムラグでお知らせが更新されるようになると、非常に助かります。

**Comment by mikkame** [comment]
こちら対応します。
