### ISSUE TITLE
積み上げ棒グラフのツールチップに表示する数値を系列の表示/非表示に対応させる

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#866]
#474 のアップデートで、積み上げ棒グラフの棒にマウスオーバーすると以下のようなツールチップが表示されるようになった。（1枚目のスクリーンショット）
```
2月27日
191件（都内：110/その他：81）
```
ただ、系列を非表示にした場合にも同じ数値が出てしまうのが問題。（2枚目のスクリーンショット）

**改善案**
・合計件数には「合計：」と明記
・内訳はマウスオーバーした系列の件数のみ表示

例）
・「都内発生」（濃い緑）にマウスオーバー時
```
2月27日
合計：191件（都内：110）
```

・「その他」（薄い緑）にマウスオーバー時
```
2月27日
合計：191件（その他：81）
```

<img width="556" alt="スクリーンショット 2020-03-09 13 46 39" src="https://user-images.githubusercontent.com/4206675/76184088-ebe56e00-620d-11ea-9264-77a33445d1e4.png">

<img width="554" alt="スクリーンショット 2020-03-09 13 46 44" src="https://user-images.githubusercontent.com/4206675/76184072-dc662500-620d-11ea-9c53-9c9acba2ae01.png">

**Comment by ocean3fish** [comment]
@kaizumaki という案なのですが可能でしょうか？

**Comment by kaizumaki** [comment]
@ocean3fish おお、いいと思います！
あと、系列（ラベル部分）がクリックできることがわかりやすくなればmoreベターですよね。（私はクリックできることを知りませんでした）

**Comment by kaizumaki** [comment]
```
・「都内発生」（薄い緑）にマウスオーバー時
```
↓
```
・「その他」（薄い緑）にマウスオーバー時
```
ですね。

**Comment by ocean3fish** [comment]
@kaizumaki そうなんですよね、 #795 でもそんな話が出ていたので、デザインの検討をお願いできるようにまた別issue立てましょうかー

**Comment by ocean3fish** [comment]
@kaizumaki すみませんタイポ修正しました！

**Comment by kaizumaki** [comment]
@ocean3fish ですね。別issue立てましょう。

**Comment by ocean3fish** [comment]
@kaizumaki こちらのツールチップの表示の変更、実装お願いしても大丈夫でしょうか？
それともどなたかご担当頂ける方募集した方が良いでしょうか？

**Comment by kaizumaki** [comment]
@ocean3fish 別issue立てましょう。help wanted的な。

**Comment by kaizumaki** [comment]
@ocean3fish あ、そうか、このissueでいいんでした。

**Comment by ocean3fish** [comment]
@kaizumaki 元々こちらのissueはツールチップの表示変更をお願いするもので、途中で表示/非表示切り替えできるのがわかりづらいという話が出てきたので、その部分だけ別issue立てたというステイタスですね。

**Comment by kaizumaki** [comment]
@ocean3fish とりあえず、私のほうで引き取りますね。

**Comment by kaizumaki** [comment]
@ocean3fish あ、i18n化と激しくコンフリクトしそうですね。 #1108

**Comment by kaizumaki** [comment]
#1108 がマージされたので、 `dev-i18n` ブランチからひっぱってきますね。
