### ISSUE TITLE
グラフの凡例がクリッカブルで系列の表示/非表示の切り替えが出来ることを伝わりやすくする

### ISSUE THREAD

**Issue by ocean3fish** [tokyo-metropolitan-gov/covid19#870]
**問題**
グラフの凡例（グラフ上部に表示されているデータ系列の色とラベルを示しているもの）がクリッカブルで系列の表示/非表示の切り替えが出来ることがわかりづらい。
<img width="547" alt="スクリーンショット 2020-03-09 14 44 40" src="https://user-images.githubusercontent.com/4206675/76186277-31596980-6215-11ea-9861-085d6bc33f9d.png">

**対象グラフ**
凡例が表示されているもの
・検査実施数
・都営地下鉄の利用者数の推移

**解決策**
チェックを入れたり外したり出来る雰囲気のデザインに変更
（具体案募集！）

**関連issue**
 #795, #866

**Comment by TanisukeGoro** [comment]
検査実施数はあえて`その他`をデフォルトで非表示しておくことで、切り替えが可能であることを示すのはどうでしょうか？

**Comment by ocean3fish** [comment]
@TanisukeGoro ご検討ありがとうございます！
私もチェックボックスが良いかなーと思いつつ、せっかくのスッキリしたデザインが崩れそうで少々躊躇しており。

そのあたりデザイナーさんのご意見を頂けると助かります！ > @saladdays

**Comment by af12066** [comment]
`cursor: pointer`スタイルを指定すれば、該当箇所がクリッカブルであることが伝わりやすくなると思われます。
Chart.jsの指定は以下のような感じです:
```javascript
...
legend: {
  display: true,
  onHover: e => {
    e.currentTarget.style.cursor = 'pointer'
  },
  onLeave: e => {
    e.currentTarget.style.cursor = 'default'
  }
},
...
```

**Comment by TanisukeGoro** [comment]
ツールチップのような表示を試してみました。
こんな感じの挙動はどうでしょうか？

![demo gif](https://i.gyazo.com/37946d9bde0fac6cce50646827e79729.gif)

**Comment by saladdays** [comment]
皆様ご検討ありがとうございます！
僕もここが押せるの知りませんでした。。。

@TanisukeGoro @ocean3fish チェックボックス案、実は僕も検討をしてみました。
しかし実際にチェックボックスの視認性を確保しようとするとそこそこの大きさにしなければならず、グラフの見やすさを阻害してしまいそうで見送りました。。

あと、大前提として非表示にしたりしなくてもわかりやすいグラフを提供するというものがありますので、そういった意味ではやはりデフォルトで全て表示しておきたいと思っています。

@af12066 ミニマムな実装として、まずは `cursor: pointer` が一番手っ取り早そうですね！

@TanisukeGoro ツールチップも良い案だったのですが、「表示されている」状態で「非表示にする」という反対の単語が出てしまうので一瞬戸惑ってしまうかと思いました。

とうことで、@af12066 さんの案で一度クイックに進めるでいかがでしょうか？
今後グラフを操作する前提でのものが出てきた時に、ぜひともチェックボックス案を復活させてみたいと思います！

**Comment by af12066** [comment]
さくっと実装してみますー
