### ISSUE TITLE
[i18n] 翻訳が間に合わないままマージされた翻訳の更新

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#872]
総合issue: #680
（全体の方針については↑へ）

-----
- 翻訳が終わらないまま `dev-i18n`ブランチにマージされたもの
- マージ時には最新だったが、その後翻訳シートで更新があったもの

について、こちらで報告をお願いします。ある程度まとまり次第PR立てます

**Comment by MaySoMusician** [comment]
現時点までの更新は #873 にて merged

**Comment by crispytaffy** [comment]
[報告] 翻訳シート59行目と152行目の2箇所について、新型コロナ受診相談窓口の英訳を正しいものに差し替えました。
combined telephone advisory center -> combined telephone advice center

**Comment by MaySoMusician** [comment]
`index.vue`の「湖北省武漢市」の翻訳が完了

**Comment by MaySoMusician** [comment]
- 陽性患者の属性で「退院※」「※退院には、死亡退院を含む」が追加
  - [ ] 翻訳を待つ

**Comment by MaySoMusician** [comment]
- flowページに「印刷する」ボタンが追加
  - [ ] 翻訳を待つ

**Comment by nard-tech** [comment]
`components/DataView.vue` に更新があったので，PRを作成しました
#949

**Comment by crispytaffy** [comment]
[報告] 翻訳シート27行目と81行目の2箇所について、新型コロナコールセンターの英訳を正しいものに差し替えました。赤文字にしています。
COVID-19 Telephone Advisory Center -> Tokyo Metropolitan Telephone Consultation

**Comment by J3rd-dev** [comment]
@MaySoMusician 大変ありがとうございます。
やさしい日本語（にほんご）の件、大まかではありますが簡単に整理・改訂を行いました。

複数の方々で追記出来、速く記入が出来た一方、
書き方や表現が異なっているものも多かったため、
漢字追加だけでなく表現更新含めた改訂版を
スプレッドシートM列に記載しました。（#848連動）

もっと良い形に出来ると思いますが、
取り急ぎ、ひらがな全文初版のときよりは、少し改善していると思います。

HPでの図の見え方を眺めながら修正かけましたが、
Git反映後、文書が冗長で見づらい等があるかもしれません。
適宜、ご連絡した上で再度修正かけるようにします。

追伸：（半角スペースにて統一しました！）

**Comment by nard-tech** [comment]
> @MaySoMusician 大変ありがとうございます。
> やさしい日本語（にほんご）の件、大まかではありますが簡単に整理・改訂を行いました。

@J3rd-dev ありがとうございます．
@MaySoMusician 今日は今から時間取れるので，私やります！

**Comment by MaySoMusician** [comment]
@nard-tech お願いします！ `Flow`はまだ一部終わってないのでそれ以外のところからで

**Comment by nard-tech** [comment]
@MaySoMusician 承知しました

**Comment by nard-tech** [comment]
@MaySoMusician
やさしい日本語，flow 以外の更新終わりました
#1142 

flow の進捗はいかがでしょうか．

**Comment by nard-tech** [comment]
![スクリーンショット 2020-03-11 23 17 56](https://user-images.githubusercontent.com/23148331/76426611-a3d17180-63ee-11ea-93e8-fd0b0c6608b9.png)
困ったことに，スプレッドシートの内容を愚直に JSON に落とし込んでいくと，文字数が多すぎてトップページが思いっきり崩れるんですよね…

文字数を思い切って減らすか，コンポーネントの設計を根本的に見直さないと，この事象は解消できないと思います．

昨日，今日と全体の進行を追えていなかったのでよくわからないのですが，トップのコンポーネントの設計を見直す予定はあるのでしょうか．（コンポーネントをリファクタする issue はいずれも flow 関係のようですが…）

**Comment by halsk** [comment]
うーむ。まず、多言語化はできれば明日の朝にはリリースしたいです。
そして、今からこちら修正する時間は無いので、一旦やさしい日本語は落としましょうか？

**Comment by nard-tech** [comment]
> 一旦やさしい日本語は落としましょうか

その方がいいと思います．変に崩れて見る人の印象を悪くするよりはマシだと思います．
ポルトガル語も翻訳が間に合っていないので一旦落とした方がよいと思います．

**Comment by nard-tech** [comment]
あ，ポルトガル語の件は #1140 がありましたね．失礼しました．

**Comment by halsk** [comment]
Issue をリオープンしておきました。

**Comment by J3rd-dev** [comment]
「やさしい日本語」一旦落として正解だったと思います。
@nard-tech 実装の上、色々とご確認頂きありがとうございました！
@halsk このあとの動き、ご相談させてください。

#1126, #1148 確認の上での今後についてですが
１．文字数削減版の「やさしい日本語」を予備的に作成
　（意味劣化は止むを得ずとのことで、Local Gitに落とした手元サイトの見え方をそれぞれ確認しながら修正）
２．コンポーネント設計変更を待つ
の2案のうち、
項目１、ないし１，２同時進行検討であれば、
活動１を進めるissueを立てた方がいいと考えています。（一時対応・消える可能性理解の上で）

活動１は届ける相手に伝わりづらくなる方向なので、
理想は（数日で完了ならば）活動２と個人的には考えますが、
「やさしい日本語」のためだけの修正は負荷がかかります。

活動１ issueを立ててしまう前に、コンポーネント設計変更予定があったか、
一度ご確認させてください。

**Comment by nuwaa** [comment]
お伝え漏れがあったようです、すみません。
zh-cn: 都营地下铁 -> 都营地铁
zh-tw: 都營地下鐵 -> 都營地鐵

こちらに起票しています。
- [翻訳シートの反映漏れを直接変更 #1286](https://github.com/tokyo-metropolitan-gov/covid19/pull/1286)

**Comment by halsk** [comment]
皆様、ありがとうございます。やさしい日本語、改訂版の方に移し替えて行きたいですね。
@MaySoMusician 、どう進めるのが良さそうでしょうか？
Transifex 移行より前に、一旦アップデートを取り込んでしまいたいなと思っています。

**Comment by sidemt** [comment]
#1303 が「翻訳が終わらないまま dev-i18nブランチにマージされた」に該当するかもしれないと思いましたが、スマートフォン版では正しく表示されていることから翻訳後の反映漏れと判断し、別Issueとして起票させていただきました。

切り分けが適切でなければ大変申し訳ございません。
念のためこちらに紐づけさせていただきます。

**Comment by MaySoMusician** [comment]
@halsk どこかの時点で一度翻訳シートをロックして、シート内容をこちらに反映するのが良いと思います。
1. #1229 をいただいたので、こちらをMerge
1. 翻訳シートをロックしてコンポーネント単位で翻訳のチェック・更新
1. https://github.com/tokyo-metropolitan-gov/covid19/issues/1229#issuecomment-598456330 を参考に言語ごとに1ファイルにまとめる

というのでどうでしょう？

**Comment by halsk** [comment]
了解しました！その順番で行きましょう

**Comment by halsk** [comment]
翻訳シートのロックまで終わりました。

**Comment by MaySoMusician** [comment]
@halsk ありがとうございます！ ただいま作業用issueの準備中です

**Comment by munierujp** [comment]
@MaySoMusician 
>3. #1229 (comment) を参考に言語ごとに1ファイルにまとめる

こちらはタイミングがあえば自分がやろうかと思います（勝手がわかっているため）。
#1312 の作業終了待ちですかね？

**Comment by MaySoMusician** [comment]
@munierujp そうなります！
また development の更新に伴い一部json分離が終わってないところもありますが、そちらに関しては #1288 など翻訳更新PRで分離されなかった分をお願いするかもしれません（追ってご連絡いたします）

**Comment by MaySoMusician** [comment]
@munierujp 
以下のファイルの翻訳をJSONに分離していただいてもよろしいでしょうか？（PR先は `dev-i18n`）
- `ConfirmedCasesAttributesCard.vue`
- `ConfirmedCasesDetailsCard.vue`
- `ConfirmedCasesNumberCard.vue`
- `ConsultationDeskReportsNumberCard.vue`
- `TelephoneAdvisoryReportsNumberCard.vue`
- `TestedNumberCard.vue`
- `_card.vue`

**Comment by munierujp** [comment]
@MaySoMusician やります✋

**Comment by MaySoMusician** [comment]
@munierujp 大量の作業ありがとうございました！

**Comment by MaySoMusician** [comment]
Transfixへの移行に伴い、こちらはCloseします
詳細は #1509 へ
