### ISSUE TITLE
北海道版への導線づくり

### ISSUE THREAD

**Issue by Yfuruchin** [tokyo-metropolitan-gov/covid19#874]
## 改善詳細 / Improve details
- （あまり急ぎませんが’）北海道版がロンチしたのを知らずにforkして一人でデータづくりから頑張って作ろうとしてたエンジニアさんがいました（見つけれて幸運！）
- もし可能ならReadmeかなにかに北海道版あるよ！と記載してもらうことは可能でしょうか

## 期待する見せ方・挙動 / Expected behavior
- Readme/その他サイトから、横展開事例として
https://github.com/codeforsapporo/covid19

https://stopcovid19.hokkaido.dev

へリンク？

**Comment by FlexiblePrintedCircuits** [comment]
まだ誰もやってないようでしたら、私やります！
