### ISSUE TITLE
最新のお知らせの更新 3月9日

### ISSUE THREAD

**Issue by NaoyaShimizzz** [tokyo-metropolitan-gov/covid19#875]
最新のお知らせ欄の更新をお願いします。

日付：3月9日
都の備蓄マスク20万枚を都内全区市町村へ提供　　https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/1007462.html

日付：3月9日
都内医療機関及び保健所等へのマスクの配布についてhttps://www.fukushihoken.metro.tokyo.lg.jp/oshirase/iryo/maskhaifu0306.html

**Comment by kebhr** [comment]
対応しますー
