### ISSUE TITLE
静的コンテンツ用コンポーネントの新規作成(TextCard置き換え)

### ISSUE THREAD

**Issue by macropygia** [tokyo-metropolitan-gov/covid19#877]
## 改善詳細 / Improve details

- 静的コンテンツ用の汎用性の高いコンポーネントを整備することを提案します
    - 新規コンポーネント ~~、ないしTextCardコンポーネントを拡張~~
    - ~~各ページへの展開はi18n対応(#692, #694, #695)が落ち着いてから別issueで着手~~
    - アクセシビリティ対応の範疇らしいのでa11yブランチにPRを出して判断してもらう
- 理由1: 現状TextCardコンポーネントが静的コンテンツの汎用的なコンテナとして使用されているが、元々の仕様が「見出し+単一の段落」のため無理が出ている
    - 段落をbr要素で表現せざるを得ない
    - 序列なしリストを設置しようとして #714 が発生
    - #755 が適用されると全てがdiv要素に
    - 再利用性を考慮する必要のない静的コンテンツを関数で出力する必要性は低い
    - プロパティに長いHTMLを記述するとコードの見通しが悪くなる
        - [parent](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/pages/parent.vue)や[worker](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/pages/worker.vue)を参照のこと
        - i18n対応で更に悲惨なことになりつつある
- 理由2: 現状では表現の幅が少なすぎてアウトラインをマークアップ的にも視覚的にも構築できない
    - 今後コンテンツ量が増えるようだとユーザーの情報の取捨選択に支障を来しかねない
    - 他地域に展開された際に掲載内容の差異が大きいであろう箇所であり、予め用意しておいた方がよいように思われる
- 対応する要素は「見出し」「段落」「序列ありリスト」「序列なしリスト」「定義リスト」「画像+キャプション」「テーブル」「注釈」等を想定
    - 外部リンクにはアイコンをつけておきたい
        - cssで済ませるか #684 対応するか、そもそも方針はどうなのか

## スクリーンショット / Screenshot

![pc](https://user-images.githubusercontent.com/3162324/76189294-a630a180-621d-11ea-8772-3e62efcf7000.png)

## 期待する見せ方・挙動 / Expected behavior

スクリーンショット部分のマークアップ例

```html
<TextCard>
  <h2>{{ $t('h2見出し') }}</h2>
  <p>{{ $t('段落') }}<sup>{{ $t('注記号') }}1</sup></p>
  <ul>
    <li>{{ $t('序列なしリスト') }}</li>
    <li>...</li>
  </ul>
  <ol>
    <li>{{ $t('序列ありリスト') }}</li>
    <li>...</li>
  </ol>
  <h3>{{ $t('h3見出し') }}</h3>
  <dl>
    <dt>{{ $t('定義リスト') }}</dt>
    <dd>...</dd>
    <dt>...</dt>
    <dd>...</dd>
  </dl>
  <h4>{{ $t('h4見出し') }}</h4>
  <p class="note">
    <span>{{ $t('注記号') }}</span>
    <span>{{ $t('単独注釈、ダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキスト') }}</span>
  </p>
  <ul class="notes">
    <li>
      <span>{{ $t('注記号') }}</span>
      <span>{{ $t('複数注釈、ダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキスト') }}</span>
    </li>
    <li>
      <span>{{ $t('注記号') }}</span>
      <span>{{ $t('ダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキスト') }}</span>
    </li>
  </ul>
  <ol class="notes">
    <li>
      <span>{{ $t('注記号') }}1 </span>
      <span>{{ $t('序列あり注釈、ダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキスト') }}</span>
    </li>
    <li>
      <span>{{ $t('注記号') }}10 </span>
      <span>{{ $t('ダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキストダミーテキスト') }}</span>
    </li>
  </ol>
</TextCard>
```

## 動作環境・ブラウザ / Environment

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by macropygia** [comment]
北海道版がローンチされているようなので新規作成に絞りつつ、新規作成であれば他に影響しないので一旦コンポーネント単体で着手してみます。

**Comment by kaizumaki** [comment]
@macropygia このissue、ぜひ実装を進めてもらいたいんですが、ここに紐づいているPRはすぐに取り込める状態ですか？
すでにある翻訳の修正もからんでくるので、作業の進め方をご相談したいです。

**Comment by macropygia** [comment]
@kaizumaki 注釈のマークアップとクラス名の命名規則に問題がなければすぐにでも取り込めるかと。

**Comment by kaizumaki** [comment]
@macropygia 了解です！ありがとうございます。続きはPR #916 のほうでコメントしますね。
