### ISSUE TITLE
メニューのリンクをクリックしてもURLが変わらない

### ISSUE THREAD

**Issue by yokinist** [tokyo-metropolitan-gov/covid19#88]
[![Image from Gyazo](https://i.gyazo.com/192b0f398eca59e746a621243ab08b08.gif)](https://gyazo.com/192b0f398eca59e746a621243ab08b08)

nuxt-linkとして扱えるようにnuxt属性をつけてみたりしたんですが、ルートパスだけうまく動作せず・・
https://vuetifyjs.com/ja/components/lists#api

尚、`/xxx` は問題なく動作します

**Comment by kenshir0f** [comment]
最新のstagingだと動いていそうですがどうでしょう...？ 🤔 

<img src="https://user-images.githubusercontent.com/8067258/75627358-c0152780-5c12-11ea-9bc5-cd9deed6a441.gif" width=300/>

**Comment by yokinist** [comment]
本当ですね、、動いているのでcloseします！
