### ISSUE TITLE
韓国語翻訳 - README, CODE_OF_CONDUCT, CONTRIBUTING

### ISSUE THREAD

**Issue by moreta** [tokyo-metropolitan-gov/covid19#881]
## 改善詳細 / Improve details

- README
- CODE_OF_CONDUCT
- CONTRIBUTING

の韓国語版

## 期待する見せ方・挙動 / Expected behavior
- 東京在中の韓国の方にも参加していただけるように

**Comment by moreta** [comment]
#882 上げました

**Comment by moreta** [comment]
すみません、読み直したら。
間違った部分や、不自然な部分が有り
追加修正しました。

#893

**Comment by studioego** [comment]
For the first time, I changed Korean translation at README_KO.
韓国語の不自然な内容を修正しました。
Check it, Please.
確認、お願いします。
