### ISSUE TITLE
最新の development を dev-i18n に merge

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#883]
## 改善詳細 / Improve details
-    `development` ブランチから `dev-18n` ブランチを作成したが，`development` が進行しており，差分が生じている．
    -   現状の `development` の内容も取り込んだ上で `dev-i18n` の動作確認をしたいので，最新の `development` を `dev-i18n` に merge したい．
cf. #861

**Comment by mikkame** [comment]
お待たせしております、本件ですが現在staging更新のためdevelopmentに色々取り込んでいる最中です。人おおり終わり次第こちらにマージします

**Comment by nard-tech** [comment]
@mikkame @daitasu ご対応ありがとうございました．

**Comment by nard-tech** [comment]
また差分が生じているので reopen しました．PR は私が作成します．
