### ISSUE TITLE
【検討】 [i18n] 最新のお知らせの翻訳・リンク先

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#884]
（総合issue: #680）
#880 に類似しますが、最新のお知らせのリンク先はほとんど日本語のみ（もしくは機械翻訳のみ提供）だと思うので、翻訳シートでもあげられていたように
- リンクの最後に「日本語のみ」のような文言を入れる

になると思います。ご意見よろしくお願いいたします。

**Comment by PichuChen** [comment]
「日本語のみ」 => (日文網站) zh-tw

**Comment by MaySoMusician** [comment]
翻訳シートによれば
- 英語: [Article is in Japanese]
- 中国語（簡体字）: （内容为日语）
- 中国語（繁体字）:  (日文網站)
の翻訳例はあるようです

**Comment by halsk** [comment]
こちら、了解です。その対応にしましょう。

**Comment by MaySoMusician** [comment]
@halsk OKです
韓国語は「(일본어)」のようです。これで反映させてみます

**Comment by halsk** [comment]
@MaySoMusician さん、こちら、クローズしても大丈夫そうでしょうか？

**Comment by ocean3fish** [comment]
@MaySoMusician 
こちら解決したように見受けられますので、クローズとさせて頂きます。
もし間違いの場合はre-openをお願いいたします。
