### ISSUE TITLE
サイドバーのSNSアイコンの形を統一したい。

### ISSUE THREAD

**Issue by rikupin1105** [tokyo-metropolitan-gov/covid19#887]
## 改善詳細 / Improve details
- トップページにある各種SNSアイコンの形を統一したい。
- 理由：FaceBookアイコンとGithubアイコンが丸型のものしかなく、統一感がないため。

## スクリーンショット / Screenshot
変更前
![image](https://user-images.githubusercontent.com/41769991/76384738-1f0d3600-63a3-11ea-88ab-6519c9b3cdc3.png)

変更後
![image](https://user-images.githubusercontent.com/41769991/76384721-1288dd80-63a3-11ea-90bb-8fa7935f077e.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by saladdays** [comment]
とても良いご指摘だと思いました！
Figmaに素材もご用意しましたので実装を進めましょー

https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=121%3A533

**Comment by rikupin1105** [comment]
ありがとうございます。
Figmaの使い方があまり良くわかってないのですが、
Figmaの方から素材を使用したほうが良いのでしょうか？

先日出したPR ( #888 ) は各サービスのブランドロゴのサイトからダウンロードしたものになります。

**Comment by saladdays** [comment]
あ、もちろんそちらご利用頂く形でも問題ございません。よろしくおねがいします！

**Comment by rikupin1105** [comment]
了解しました。すでに PR を出したので確認よろしくおねがいします。 #888
