### ISSUE TITLE
[/flow] コンポーネントコーディング FlowSp.vueの調整

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#891]
**このissueは、`feature/flow/development` ブランチですすめます。~~プルリク先もこちらのブランチとなります。~~** -> プルリク先は `dev-i18n` ブランチに変更になりました。（3/10 0:36）

#659 で進めたパーツコンポーネントのコーディングがみなさまのおかげで出揃いました！ありがとうございます！
このissueでは、モバイル版を合体させたコンポーネントの微調整をお願いします。
（デスクトップ版は私のほうで調整中です）

合体ファイルは `components/flow/FlowSp.vue` になります。ここにimportしてあるパーツのコンポーネントをそれぞれ調整していってください。`pages/flow.vue` には組み込み済みなので、すぐに表示は確認できると思います。
### 調整のポイント
- `font-family` は削除してください。
- 太字は `font-weight: bold;` を使用してください。
- 同じような部分はフォントサイズをそろえてください。
- すでにあるclassの命名については特に気にせず、そのままでいいです。
- マークアップも基本的にそのままでいいです（後日アクセシビリティチームにチェックしてもらいます）。
- ただ、 `h` タグが不適切だと思う場所は修正してください。とりあえず `div` とか `p` に置き換えておいてください。

なにか疑問点あれば、お気軽にこのissueにコメントしてください！

### 追記
#550 も考慮してください！
#895 の反映もお願いします。

**Comment by kaizumaki** [comment]
元デザインはこちらになります。
![sp_flowimg_design](https://user-images.githubusercontent.com/14883063/76205781-43033700-623e-11ea-964e-a35c5b232264.png)

**Comment by af12066** [comment]
やってみます

**Comment by kaizumaki** [comment]
@af12066 ありがとうございます！よろしくお願いします！

**Comment by af12066** [comment]
「2日程度」や「4日以上」の2や4は全角数字でよいでしょうか?

**Comment by kaizumaki** [comment]
@af12066 ご指摘ありがとうございます！半角に修正してもらえますでしょうか？
私も気付きませんでした。ありがとうございます。

**Comment by kaizumaki** [comment]
@af12066 #932 #931 でflowページの多言語化作業が着手されました。今後、こちらのスタイルやマークアップの修正作業は `dev-i18n` ブランチへプルリクしてください！

**Comment by kaizumaki** [comment]
@af12066 すみません！先ほどのプルリク、私の手元では下のような表示なのですが、ご確認いただけますか？（こちらのissue、復活させました。）
![FireShot Capture 011 - 新型コロナウイルス感染症が心配なときに - 東京都 新型コロナウイルス感染症対策サイト - localhost](https://user-images.githubusercontent.com/14883063/76269077-aaa79980-62b3-11ea-91bd-e78bb21eb2d4.png)

**Comment by af12066** [comment]
おや、Netlify https://deploy-preview-822--dev-covid19-tokyo.netlify.com/flow をiOSシミュレータのSafariで確認しましたが、とくに問題ないようにみえます。
localhostで発生した場合は、`yarn clean-hardsource && yarn dev`してみてください!

**Comment by kaizumaki** [comment]
@af12066 おお、cleanコマンドありがとうございます！表示正常になりました。お手数おかけしました！

**Comment by kaizumaki** [comment]
@af12066 あ、すみません！２点追加修正お願いしていいですか？（私の確認不足ですみません）
↓ここの部分、背景グレーのシャドウなしにしてほしいです。
![スクリーンショット 2020-03-10 10 02 49](https://user-images.githubusercontent.com/14883063/76269844-97e29400-62b6-11ea-855d-4129c87f4fb3.png)

あと、一番下の緑枠のボタンを左右中央配置にしてください！
![スクリーンショット 2020-03-10 10 03 13](https://user-images.githubusercontent.com/14883063/76269893-bb0d4380-62b6-11ea-84cb-99fe8b9a314e.png)

**Comment by af12066** [comment]
了解です! 帰国者接触者電話相談センターのCardのbackground-colorが抜けてしまっていた。。。
