### ISSUE TITLE
ナビゲーション内の「東京都主催等 中止又は延期するイベント等」のリンクが古い

### ISSUE THREAD

**Issue by noritada** [tokyo-metropolitan-gov/covid19#892]
## 起こっている問題 / The Problem
- ナビゲーション内の「東京都主催等 中止又は延期するイベント等」のリンクが古い

（ 昨夜 #831 としてPRしてしまいましたが、
　IssueなしでのPRでしたので、改めてIssue立てさせていただきます。
　お手数をおかけします。）

## スクリーンショット / Screenshot

（リンク先のスクリーンショット）

<img width="1552" alt="スクリーンショット 2020-03-09 19 44 35" src="https://user-images.githubusercontent.com/20850/76205945-8b225980-623e-11ea-85f3-ac8304e41101.png">

## 期待する見せ方・挙動 / Expected Behavior
- 最新のイベントへのリンクも過去のイベントへのリンクも簡単に辿れるとよいはずです。

（リンク先のスクリーンショット）

<img width="1552" alt="スクリーンショット 2020-03-09 19 47 03" src="https://user-images.githubusercontent.com/20850/76206485-75616400-623f-11ea-8f07-e6fc78c6dc77.png">

## 起こっている問題の再現手段 / Steps to Reproduce
1. 「東京都主催等 中止又は延期するイベント等」をクリック

## 動作環境・ブラウザ / Environment
- All OS
- All browsers

**Comment by halsk** [comment]
修正されていたので、クローズさせてください。
