### ISSUE TITLE
とは言え、IE(できる範囲)対応

### ISSUE THREAD

**Issue by kobatakuJP** [tokyo-metropolitan-gov/covid19#894]
## 改善詳細 / Details of Improvement
（いろいろあるが）**とは言え**、IEでもそれなりに表示できるように・・・目と手の届く範囲で・・・IEも、まだ生きている・・・

from
![image](https://user-images.githubusercontent.com/36495393/76206519-87430700-623f-11ea-8aa4-cdc49885e7ad.png)

to
![image](https://user-images.githubusercontent.com/36495393/76206541-92963280-623f-11ea-90e3-2ef4293fc173.png)

## 動作環境・ブラウザ / Environment
- Internet Explorer

**Comment by kaizumaki** [comment]
#890 でissueが投げられています。

**Comment by kobatakuJP** [comment]
@kaizumaki 
本当だ・・・わずかに遅かった。しかもオートプレフィックスのがいいですね。
こちらはクローズします。
