### ISSUE TITLE
相談手順中のPCR検査について、保険適用に関する注意事項の記載

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#895]
PCR検査が保険適用になったことにより、注意点の記載が必要となりました。
手順中の、「新型コロナ受信相談窓口」フロー中の「PCR検査」の部分で、
「PCR検査」 → 「PCR検査※」 に変更

下記文面を直下に追加。
「※保険適用となる検査は、当面の間、院内感染防止等の観点から、「帰国者・接触者外来」等の医療機関で実施」

想定イメージは、別途お伝えします。

**Comment by yukou-isshiki** [comment]
こちらやってみても良いでしょうか？

**Comment by mtenjin** [comment]
お願いします！
想定イメージはこちらです。
<img width="795" alt="無題" src="https://user-images.githubusercontent.com/54087276/76207818-d5590a00-6241-11ea-9232-0ffc8e397a81.png">

**Comment by yukou-isshiki** [comment]
開発環境構築のため、Docker を install  してやっているのですが

`ERROR: for covid19  Cannot start service app: failed to create OCI runtime console socket: mkdir /tmp/pty118023924: permission denied: unknown
`

となり`docker-compose up`が出来ていません…

あまり、Dockerは使用した事が無くこのエラー自体は頻繁に発生するものでしょうか？

**Comment by yukou-isshiki** [comment]
`Docker version 19.03.5, build 633a0ea`

Docker for Mac を使用しています。

**Comment by yukou-isshiki** [comment]
すみません、解決しました

**Comment by af12066** [comment]
モバイル版は、 https://github.com/tokyo-metropolitan-gov/covid19/issues/891 にて追記いたしました。

**Comment by mtenjin** [comment]
モバイル版の画面、確認しました。
よいと思います。

**Comment by halsk** [comment]
@mtenjin こちら、多言語版リリースの方に修正が入っています。うまくいけば明日反映できますが、最悪明後日くらいになってしまっても問題ありませんか？

**Comment by mtenjin** [comment]
承知しました。まずは多言語版リリース優先で行きましょう。

**Comment by halsk** [comment]
@mtenjin さん、こちら、対応済ですので、クローズさせていただきます。
皆様、ご協力ありがとうございました！
