### ISSUE TITLE
最終更新日を表示する

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#90]
そもそも今の json データに無いのでは

**Comment by osoken** [comment]
これは、表示している各データの一番最後の更新日になるんですかね？

**Comment by halsk** [comment]
そうですね！

**Comment by mikkame** [comment]
#141 で実装中

**Comment by mikkame** [comment]
各グラフはソースごとに最終更新日を表示するようにしてしまったんですが
もしかしてMAX(最終更新日)だけでよかったですかね

**Comment by mikkame** [comment]
@halsk 一個上のコメントの件仕様確認をお願いします。
今のままでよければクローズしてください

**Comment by halsk** [comment]
都の方で確認中です！しばらくお待ち下さい。

**Comment by mikkame** [comment]
#195 と合わせてこれから対応します
