### ISSUE TITLE
[i18n] PrinterButton.vue 内の文字列をi18n化

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#928]
総合issue: #680 
（全体の方針については↑へ）

---
- `components/PrinterButton.vue` の直打ちの文字列を`<i18n>`で定義するようにします。
- 各言語への翻訳はこちらにあります: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0
- `<i18n>`の空テンプレートは https://github.com/tokyo-metropolitan-gov/covid19/issues/680#issuecomment-596059072 にあります

**Comment by MaySoMusician** [comment]
翻訳待ち

**Comment by mkfsn** [comment]
すみません。

このようなプロジェクトに参加するのは初めてなのですが、
こちら着手させていただいてもよろしいでしょうか？

**Comment by MaySoMusician** [comment]
@mkfsn よろしくお願いいたします！ 何かありましたらお声がけください！
https://github.com/tokyo-metropolitan-gov/covid19/issues/680#issue-577278205 にもありますが、PRの向きは `dev-i18n` に設定してください
たぶん、作業開始時に `dev-i18n`からブランチを切ると楽だと思います！

**Comment by mkfsn** [comment]
@MaySoMusician アサインありがとうございます！承知しました！
よろしくお願いします！

**Comment by halsk** [comment]
一部の言語を残して取り込みました。
@mkfsn さん、残ってる作業を記載しておいていただければ！

**Comment by mkfsn** [comment]
@halsk 了解です！

- [ ] 一部翻訳待ち
  - [x] 日本語
  - [x] English
  - [x] 簡体字
  - [x] 繁体字
  - [ ] 한국어
  - [x] やさしい日本語

**Comment by MaySoMusician** [comment]
Close per #964 #1060 merged
