### ISSUE TITLE
[flowのi18n化] マージ依頼 dev-i18n <- feature/flow/development

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#931]
flowページのi18n化を始めたいので、 `feature/flow/development` から `dev-i18n` へのマージをしてほしいです。
開発フローとして問題が無ければマージをお願いいたします。

**Comment by MaySoMusician** [comment]
（今 `dev-i18n` は `development` にあるものだけ取り込んでるので、そこに `feature/flow/development` も混ぜてしまってよいのかどうか ）

**Comment by halsk** [comment]
@kaizumaki さん、取り込んで問題ないですよね？

**Comment by kaizumaki** [comment]
問題ないです！今後こちらで発生した修正は `dev-i18n` にプルリクすればいいですかね？

**Comment by MaySoMusician** [comment]
> 問題ないです！今後こちらで発生した修正は `dev-i18n` にプルリクすればいいですかね？

それでお願いします！
