### ISSUE TITLE
[i18n] flow.vue をi18n化

### ISSUE THREAD

**Issue by MaySoMusician** [tokyo-metropolitan-gov/covid19#932]
総合issue: #680 
flowページの進捗取り込み依頼: #931 

---
`pages/flow.vue`の文字列をi18n化します。デザインの都合上、文章が細切れになっているらしいので

1. HTML(Vue template)に合わせて翻訳文字列のキーを登録
1. 当初より文章が切れてる文字列について、各言語で分割場所が推測できるなら対応
1. 推測できない場合、分割場所を明示したうえで再度翻訳シートにて翻訳募集
1. 集まった翻訳も登録

という流れになると思います。しばらくは @kaizumaki さんと相談の上 @MaySoMusician が作業を行います。help wantedになったら再度 #680 などで連絡します。

**Comment by kaizumaki** [comment]
それと、デスクトップ版とモバイル版があるので、多言語化作業が冗長になってしまうと思います。ごめんなさい！ 🙇‍♀ 
何かあれば対応します。どうぞよろしくお願いいたします！

**Comment by kaizumaki** [comment]
とりあえず、 `FlowPc` から始まるファイル名のコンポーネントからとりかかってもらえますか？

**Comment by MaySoMusician** [comment]
> とりあえず、 `FlowPc` から始まるファイル名のコンポーネントからとりかかってもらえますか？

わかりました！

**Comment by MaySoMusician** [comment]
@kaizumaki 「新型コロナ受診相談窓口による相談結果」なのですが、
https://github.com/tokyo-metropolitan-gov/covid19/blob/44033cdcd51fcd5c5c0d30ad44e2bad78478d7f5/components/flow/FlowPc.vue#L17-L20
デザインはそのままで ↓みたいな感じに「新型コロナ受診相談窓口」を大きくする、というコードに変更することは可能ですか？
```vue
 <h3 :class="$style.Title"> 
   <span :class="$style.TitleLarge">新型コロナ受診相談窓口</span> 
    による相談結果
 </h3> 
```
「新型コロナ受診相談窓口」が`<span>`で囲われていた方がi18nの翻訳キーがわかりやすくなるので...

**Comment by kaizumaki** [comment]
@MaySoMusician おお、なるほど。ぜんぜん大丈夫ですよ！私もそこらへんのコツがわからないので、どっかにまとめておいてくれると助かります！

**Comment by MaySoMusician** [comment]
HTMLタグ付きの翻訳は、XSS対策の都合で特殊なタグを使うのですが
```vue
<a href="hoge">リンク先ページ名だよ！</a>を見る
```
を翻訳するには
```vue
<i18n path="{pageName}を見る">
  <a href="hoge" place="pageName">リンク先ページ名だよ！</a>
</i18n>
```
と指定します。この状態だと、翻訳する人も「{pageName}を見る」と「リンク先ページ名だよ！」という感じで固有名詞と動詞がわかりやすいんですが、仮に
```vue
リンク先ページ名だよ！<span>を見る</span>
```
になってると
```vue
<i18n path="リンク先ページ名だよ！{toView}">
  <span place="toView">を見る</a>
</i18n>
```
みたいになるので、翻訳者が「リンク先ページ名だよ！{toView}」と「を見る」を与えられる状況になります。
これだと翻訳側もちょっと翻訳しづらい（文脈を読みづらくなる）ので、前者の例のように
- 「○○を見る」というように名詞の方を穴あきにしたいので、そっちだけをタグで囲う

ができればi18n化側としてはベストです！

**Comment by MaySoMusician** [comment]
@kaizumaki メンション忘れ ↑

**Comment by MaySoMusician** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/blob/44033cdcd51fcd5c5c0d30ad44e2bad78478d7f5/components/flow/FlowPcDays.vue#L25-L38

- （可能なら）`<span>風邪</span>`のような症状に
- （必須）i18nモジュールのほうで`<span>`が自動生成される場合があるので、意図しないスタイル適用を防ぐためにも、小さくしたい文字用spanはclassでスタイル適用してほしい

**Comment by MaySoMusician** [comment]
こちらも
https://github.com/tokyo-metropolitan-gov/covid19/blob/44033cdcd51fcd5c5c0d30ad44e2bad78478d7f5/components/flow/FlowPcNotRequired.vue#L4-L10
- （必須）i18nモジュールのほうで<span>が自動生成される場合があるので、意図しないスタイル適用を防ぐためにも、小さくしたい文字用spanはclassでスタイル適用してほしい

**Comment by MaySoMusician** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/blob/44033cdcd51fcd5c5c0d30ad44e2bad78478d7f5/components/flow/FlowPcPast.vue#L4-L5
- 「発症前2週間以内」の方を「大きく」、という指定に

理想↓
```vue
 <span :class="大きくするstyle">発症前<span :class="$style.FlowNum">2</span>週間以内</span> 
 <span>の出来ごとと症状</span> 
```

**Comment by MaySoMusician** [comment]
![flow-pcpast](https://user-images.githubusercontent.com/34566290/76254122-41159400-628f-11ea-87fa-36b925c7c855.png)
この部分の緑色テキスト(`strong :class="$style.FlowTitle"`)についてなのですが、
- 左: 英語では語順が変わるため、`「新型コロナウイルス感染者」と`を上に表示できない
- 右: 英語は「あなたが渡航した [改行] 帰国者と濃厚接触した」になるため、1行目（`流行地域への渡航・居住歴がある方`）を小さくできない。中国語も英語と同様。韓国語はほぼ日本語と同じ。

なので、緑色テキストについては一律 or 不都合な言語だけ表示しないで、2行目に当たるテキスト(`span :class="$style.FlowPerson"`)に全部入れるのはいかがでしょうか

**Comment by kaizumaki** [comment]
@MaySoMusician おお！もろもろありがとうございます。お手数おかけしています。

> `<p>`タグが無くても大丈夫なようにCSSを直してほしいです

おっと、すみません。そこは見落としていました。

> なので、緑色テキストについては一律 or 不都合な言語だけ表示しないで、2行目に当たるテキスト(`span :class="$style.FlowPerson"`)に全部入れるのはいかがでしょうか

ご提案のとおりにしたいと思います。具体的にはどのようにすればいいですか？

これらマークアップの修正作業のために別issueを立てたいと思います。 `dev-i18n` ブランチを引っ張ってくるようにして、そちらにプルリクするという流れでいいですかね。

**Comment by smellman** [comment]
@kaizumaki @MaySoMusician FlowPcDays.vue を作ったものなので、このファイルのi18n担当しますね

**Comment by kaizumaki** [comment]
@smellman ありがとうございます！ `dev-i18n` ブランチから引っ張ってきてくださいねー

**Comment by MaySoMusician** [comment]
> これらマークアップの修正作業のために別issueを立てたいと思います。 `dev-i18n` ブランチを引っ張ってくるようにして、そちらにプルリクするという流れでいいですかね。

大丈夫です！よろしくお願いします

**Comment by MaySoMusician** [comment]
> @kaizumaki @MaySoMusician FlowPcDays.vue を作ったものなので、このファイルのi18n担当しますね

あ、`FlowPcDays.vue`も作業開始してた...
作業被らないように一応各ファイルWIPでPR立てておきますね
（`FlowPcDays.vue`はどちらのPRを取り込んでもOK）

**Comment by MaySoMusician** [comment]
@kaizumaki すみません、上記PRのブランチ群、さらに一度リベース&force-pushします

**Comment by kaizumaki** [comment]
@MaySoMusician 了解です！お願いします！

**Comment by MaySoMusician** [comment]
一応残りのFlowPc系vueは私が担当するということで良いでしょうか？

**Comment by kaizumaki** [comment]
@MaySoMusician マークアップの修正は別issueを立てて募ろうかと思っていますがどうでしょう？ i18n化の作業で従来の進め方があればお知らせください！

**Comment by MaySoMusician** [comment]
@kaizumaki あ、そうですね。マークアップの修正は別issue・別の人担当で大丈夫です！
マークアップ完成後はi18nの方で引き取りたいなと思います
FlowPcPcr・FlowPcRequired・FlowPcSuspectのマークアップの確認はまだなので、そこの部分はもう少々お待ちを

**Comment by MaySoMusician** [comment]
既にお伝えしてる修正点と似たような部分であれば他のファイルも直しちゃって大丈夫です～

**Comment by MaySoMusician** [comment]
#957 などに関連してくるのですが、`<br />`を含むマークアップは
- 翻訳との都合で`v-html`を使わざるを得ないが、これはXSSの穴となり得る
- 言語によって都合の良い改行位置が異なるが...
  - 翻訳で「改行位置」という文章とは別次元の内容は含めたくない（翻訳者がブラウザで表示結果を見なくて済むようにしたい）
  - 原文と訳文で「`<br />`が数が異なる」などは、今後外部翻訳ツールを導入した際に警告メッセージが出る可能性がある
- 画面によって横幅が異なるのでそもそも改行位置はCSSやブラウザに任せるべき、という説もある（HTML5としても`<br/>`の使用は詩や俳句など意味のある改行のみとしている）

という感じで、i18n的には出来れば無い方がありがたいです。デザインの都合などもあると思いますので、方針を決めちゃいたいです
@kaizumaki @そのほか

**Comment by forestgtree** [comment]
`word-break: break-all;`

を使用してみてはいかがでしょうか？

**Comment by kaizumaki** [comment]
> `word-break: break-all;`
> 
> を使用してみてはいかがでしょうか？

@forestgtree お、いいですね。`<br/>` を使わずに、ってことでいいですか？それとも言語による？

**Comment by forestgtree** [comment]
適応してみて、違和感がなければ `<br />` は取ってしまいましょう！！

**Comment by MaySoMusician** [comment]
i18n側としては、ひとつの文章については`<br />`の有無は全言語統一が良いです
（理想はどの文章でも全く使わない）

**Comment by kaizumaki** [comment]
> i18n側としては、ひとつの文章については`<br />`の有無は全言語統一が良いです
> （理想はどの文章でも全く使わない）

ですよね。`<br/>` は言語で分けず、さらに極力使わない方向でいきましょう。

**Comment by MaySoMusician** [comment]
#956 #957 #958 #959 #960 #961 について WIPの内容を書きました

**Comment by MaySoMusician** [comment]
@kaizumaki `<br />`除去の件 #957 がマージされてる状態でも作業可能でしょうか？

**Comment by kaizumaki** [comment]
@MaySoMusician マージされたものについて追って修正作業することにします！

**Comment by MaySoMusician** [comment]
後々に修正するもの（随時更新するので要チェック！）

- `FlowPc.vue` (PR: #956)
  - [ ] 「新型コロナ受診相談窓口による相談結果」再マークアップ -> i18n化
  - [ ] 韓国語・やさしい日本語の翻訳更新
- `FlowPcAdvisory.vue` (PR: #957)
  - [ ] `<br />` 除去
- `FlowPcDays.vue` (PR: #958)
  - [ ] 「風邪のような症状」・「発熱37.5℃以上」の再マークアップ -> i18n化
- `FlowPcHospitalized.vue` (PR: #959)
  - [ ] 韓国語・やさしい日本語の翻訳更新
- `FlowPcNotRequired.vue` (PR: #960)
  - [ ] 「新型コロナ外来 受診が不要 と判断された場合」 ・「症状が良くならない場合は新型コロナ受診相談窓口に相談」の再CSS
  - [ ] `<br />` 除去

**Comment by kaizumaki** [comment]
@MaySoMusician `FlowSp` からはじまるコンポーネントもはじめてもらって大丈夫です！

**Comment by MaySoMusician** [comment]
@kaizumaki `FlowSp`の方については、マークアップの変更が必要になるなどの部分はi18n化せずにそのままにしておきます（そうすることでi18nモジュールの仕様がわからない人でも修正が可能になるはず）
その部分だけ翻訳できない状態にはなりますが... よろしくお願いいたします

**Comment by MaySoMusician** [comment]
マークアップ変更の要望です。以下のような構造に変更し、必要に応じて再CSSお願いします。

https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L3-L6
↓
```vue
<h4 :class="['mb-5', $style.Title]"> 
  <span>新型コロナ受診相談窓口</span>
  による相談結果
</h4> 
```
- `<span>`に大きくするスタイルのclassを指定
- `<br />`の除去（`<br />`が無くても改行するように）
--- 
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L7-L15
↓
```vue
<p :class="['mb-4', $style.NewCorona]"> 
  新型コロナ外来 
  <span :class="$style.NeedConsultation"> 
    受診が必要 
  </span>
  と判断された場合 
</p> 
```
- `<br />`の除去（`<br />`が無くても改行するように）
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L17-L21
↓
```vue
<p :class="['mb-0', $style.InSquare]"> 
  <span>新型コロナ外来（帰国者・接触者外来）</span>
  <span>医師による判断</span>
</p> 
```
- `<br />`の除去（`<br />`が無くても改行するように）
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L30-L35
↓
```vue
<p :class="['mb-0 pt-2', $style.NeedKensa]"> 
  検査の必要
  <span :class="$style.Nashi"> 
    なし 
  </span> 
</p> 
```
- `<br />`の除去（`<br />`が無くても改行するように）
- 翻訳の都合上「なし」の下にも文字が来られるようにしたい（`You are <span>not required</span> to be ... など）
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L41-L46
↓
```vue
<p :class="['mb-0 pt-2', $style.NeedKensa]"> 
  検査の必要
  <span :class="$style.Nashi"> 
    あり 
  </span> 
</p> 
```
- `<br />`の除去（`<br />`が無くても改行するように）
- 翻訳の都合上「あり」の下にも文字が来られるようにしたい（`You are <span>required</span> to be ... など）
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L51-L59
↓
```vue
<p id="pcr" :class="['my-4', $style.NewCorona]"> 
  <span>
    <span :class="$style.NeedConsultation">PCR検査</span>※
  <span>
  <span>東京都健康安全研究センター等</span>
  <small> 
    ※保険適用となる検査は、当面の間、院内感染防止等の観点から、「帰国者・接触者外来」等の医療機関で実施 
  </small> 
</p> 
```
- `<br />`の除去（`<br />`が無くても改行するように）
- 「東京都健康安全研究センター等」は出来れば改行したくない（言語ごとに改行位置・数が異なる可能性大）
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L90-L97
↓
```vue
<p :class="['mb-4', $style.NewCorona]"> 
  新型コロナ外来 
  <span :class="$style.NeedConsultation"> 
    受診が不要 
  </span>
  と判断された場合 
</p> 
```
- `<br />`の除去（`<br />`が無くても改行するように）
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L102-L107
↓
```vue
<p class="mb-0"> 
  <House :class="$style.Icon" /> 
  自宅で安静に過ごす 
</p> 
```
- `<br />`の除去（必要なし、下記参照）
- 「自宅で安静に過ごす」は出来れば改行したくない（言語ごとに改行位置・数が異なる可能性大）
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L112-L117
↓
```vue
<p class="mb-0"> 
  <Apartment :class="$style.Icon" /> 
  一般の医療機関を受診 
</p>
```
- `<br />`の除去（必要なし、下記参照）
- 「一般の医療機関を受診」は出来れば改行したくない（言語ごとに改行位置・数が異なる可能性大）
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/37856fc6e6308b949b5f025dcf0df1975d223f5b/components/flow/FlowSpAccording.vue#L123-L129
↓
```vue
<p :class="['mb-0 py-4', $style.inFinalRect]"> 
  症状が良くならない場合は
  <strong>新型コロナ受診相談窓口</strong>
  に相談
</p> 
```
- `<br />`の除去（`<br />`が無くても改行するように）
- 翻訳の都合上、他の言語で「に相談」の下に「新型コロナ受診相談窓口」が来ても大丈夫なようにしたい

**Comment by MaySoMusician** [comment]
入れ子の構造が変わらなければ適宜タグの追加・変更はOKです！

**Comment by MaySoMusician** [comment]
`components/flow/FlowSpAdvisory.vue`のマークアップ変更の要望です。以下のような構造に変更し、必要に応じて再CSSお願いします。

https://github.com/tokyo-metropolitan-gov/covid19/blob/dev-i18n/components/flow/FlowSpAdvisory.vue#L3-L6
↓
```vue
<h4 id="consult" :class="['mb-4', $style.Heading]">
  新型コロナ受診相談窓口
  <small>帰国者・接触者電話相談センター</small>
</h4>
```
- `<br />`の除去（`<br />`が無くても改行するように）適宜spanで囲ってもOK
--- 
https://github.com/tokyo-metropolitan-gov/covid19/blob/dev-i18n/components/flow/FlowSpAdvisory.vue#L30-L36
↓
```vue
<dt class="mb-3">
  <span :class="$style.ConsultationWeekendTitle">平日（夜間）</span>
  午後5時から翌朝午前9時
  <span :class="$style.ConsultationWeekendTitle">土日祝 終日</span>
</dt>
```
- `<br />`の除去（`<br />`が無くても改行するように）適宜spanで囲ってもOK

**Comment by MaySoMusician** [comment]
`components/flow/FlowSpElder.vue`のマークアップ変更の要望です。以下のような構造に変更し、必要に応じて再CSSお願いします。

https://github.com/tokyo-metropolitan-gov/covid19/blob/877c3696d995e5a2d8b45aea007f0aca65a390ca/components/flow/FlowSpElder.vue#L25-L27
↓
```vue
<li :class="$style.ConditionsItem">
  <div><span>風邪</span>のような症状</div>
</li>
```
- 「風邪」をspanで囲って、大きくするclassをつける
--- 
https://github.com/tokyo-metropolitan-gov/covid19/blob/877c3696d995e5a2d8b45aea007f0aca65a390ca/components/flow/FlowSpElder.vue#L29-L32
↓
```vue
<div>
  <small>発熱</small>
  <span><span>37.5℃</span>以上</span>
</div>
```
- `<br />`の除去（`<br />`が無くても改行するように）適宜spanで囲ってもOK
- `<span><span>37.5℃</span>以上</span>`は、この入れ子の構造になるように（翻訳の都合上）
---

**Comment by MaySoMusician** [comment]
`components/flow/FlowSpGeneral.vue` のマークアップ変更の要望です。以下のような構造に変更し、必要に応じて再CSSお願いします。

---
`components/flow/FlowSpGeneral.vue` も `components/flow/FlowSpElder.vue`と同じ箇所を同様に変更してください
参照: https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-597034032

**Comment by MaySoMusician** [comment]
`components/flow/FlowSpPast.vue` は少し重いのでじっくり書きます
重い部分は大体 #986 の同じです（予告）

`components/flow/FlowSpSuspect.vue` についてはi18n側からの変更要望はありません

**Comment by MaySoMusician** [comment]
`components/flow/FlowSpPast.vue`のマークアップ変更の要望です。以下のような構造に変更し、必要に応じて再CSSお願いします。

https://github.com/tokyo-metropolitan-gov/covid19/blob/5d309972aa15cbbc966db2a1e82908fad8f59bff/components/flow/FlowSpPast.vue#L3-L6
↓
```vue
<h4 :class="['mb-2', $style.Heading]">
  <span :class="大きくするstyle">発症前<strong>2</strong>週間以内</span>
  <span>の出来ごとと症状</span>
</h4>
```
- 「発症前2週間以内」をspanで囲って、大きくするclassをつける
--- 
https://github.com/tokyo-metropolitan-gov/covid19/blob/5d309972aa15cbbc966db2a1e82908fad8f59bff/components/flow/FlowSpPast.vue#L42-L47
↓
```vue
<div>
  <small>発熱</small>
  <span><span>37.5℃</span>以上</span>
</div>
```
- `<span><span>37.5℃</span>以上</span>`は、この入れ子の構造になるように（翻訳の都合上）
  - これはもしかしたら修正しなくても大丈夫かも？
---
https://github.com/tokyo-metropolitan-gov/covid19/blob/5d309972aa15cbbc966db2a1e82908fad8f59bff/components/flow/FlowSpPast.vue#L7-L10
https://github.com/tokyo-metropolitan-gov/covid19/blob/5d309972aa15cbbc966db2a1e82908fad8f59bff/components/flow/FlowSpPast.vue#L27-L31

https://github.com/tokyo-metropolitan-gov/covid19/pull/961#issuecomment-596884381 のように、

- $style.FlowTitle・$style.FlowPerson バージョン（日本語・韓国語など）
- $style.FlowPersonが2つ連続バージョン（英語・中国語など）

で表示切替できてほしいと思います
より具体的な議論は #986 にあります。もしかしたら`FlowPcPast.vue`が完成してからの方が楽かも？（その辺の進行はお任せします）

**Comment by MaySoMusician** [comment]
@kaizumaki これでひと通り1周は見終わったと思います
マークアップの変更が終わったら再開します

**Comment by kaizumaki** [comment]
@MaySoMusician ありがとうございます！おつかれさまでした！
