### ISSUE TITLE
オープンデータの取得を GitHub Actions で自動化したい

### ISSUE THREAD

**Issue by yamada-github-account** [tokyo-metropolitan-gov/covid19#948]
メリット・デメリットあると思いますが。
（デメリットの方が勝るようでしたらクローズしてください）

## 改善詳細 / Details of Improvement
- 現在コミット(例: 9cc8abda)で更新しているオープンデータの更新を、GitHub Actions上で自動化する。（日時ジョブ化）
- 元データは、リンク(例: https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients.csv) で提供されているので、CI上で取得することは可能
- データは、アーティファクトとして保存

## 考えられうるデメリット
- オープンデータが、コードの一部ではなくなる。（コードの一部として保存しておくことも目的であればデメリット）
- データの表示をCIを通さない手元でテストしづらくなる。

**Comment by munierujp** [comment]
GitHub Actions上で取得してコミットということができるのであれば、デメリットを解消しつつメリットを享受できるのではないかと思います。
GitHub Actionsの仕様を理解していないため実現可能性を無視した上での提案ですが😅

**Comment by mcdmaster** [comment]
原則、私も皆さんに賛成です。ただ、二三お尋ねさせてください。
* 元データのありかとして示していただいた URI はあくまで本プロジェクト上の場所を示すもので、都側の raw data のありかとは異なるのではないでしょうか？
* 仮に上記認識が正しい場合、都の raw data を poll してプロジェクト側のデータをアップデートするプロセスを自動化というご提案でよろしいでしょうか？
* あくまでデータオーナーは都だとすると、オープンデータがコードの一部というのではなく、データ・カストディアンとして振舞うのが本プロジェクトのミッションになると思います。この認識に相違はないでしょうか？

**Comment by mikkame** [comment]
> 元データのありかとして示していただいた URI はあくまで本プロジェクト上の場所を示すもので、都側の raw data のありかとは異なるのではないでしょうか？

その通りです、そのデータを更新するのに本リポジトリの更新が必要です。
将来的に自動化を目指していますが、現状は厳しそうです

**Comment by yamada-github-account** [comment]
コメントありがとうございます。

> 元データのありかとして示していただいた URI はあくまで本プロジェクト上の場所を示すもので、都側の raw data のありかとは異なるのではないでしょうか？

> その通りです、そのデータを更新するのに本リポジトリの更新が必要です。

勘違いしておりました。
都のカタログサイト上のリンクは、本コロナウィルス対策サイト上のデータを指し示していたのですね。（URLのドメインまでしっかり確認しておりませんでした。）

おさわがせしました。

---

（そうなると「オープンデータへのリンク」が
    自サイトへリンクした外部カタログサイトへの誘導となって若干気持ち悪いですが、
    本 issue とは別件ですので、なにか思いつきましたら、別 issue として提案させていただきます。）

**Comment by kawax** [comment]
そもそも元データがExcelファイルにしかないんですね。
派生先はどうやってるんだろう…。

元データをGoogleスプレッドシートに置けば
1. スプレッドシートから取得
2. data/などを更新
3. プルリクエスト

まではGitHub Actionsでできます。
プルリクまでなのでそこで一旦確認できる。

スプレッドシートでなくても自動で取得できるならなんでもいい。

GitHub ActionsはGitHub APIを使うためのトークンが自動で用意されるのでpushとかプルリクとか必要なことは大体できる。

**Comment by halsk** [comment]
他の地域のサイトでは、オープンデータを見に行ったり Spreadsheet を見に行ったり、違いはあると思いますが、当サイトの場合、
Sharepoint 上に必要なExcelデータが置いてあり、そこから json ファイルを生成するスクリプトがあります。Excelの方がオープンデータとして公開されるcsvファイルより更新が早いからです。
しかし、そちらのスクリプトには、オープンデータ化する前の情報も入っていたりするため、プライベートリポジトリにて管理させていただいています。
既に自動化された処理があるので、オープンデータからデータを取りに行く形に変更するメリットがありません。
