### ISSUE TITLE
お問い合わせ先にメールアドレスを載せる

### ISSUE THREAD

**Issue by kmizutani-p** [tokyo-metropolitan-gov/covid19#950]
何か理由があって載せていない場合は却下してください。

## 改善詳細 / Details of Improvement
- 問い合わせさ先に電話だけで出なくメールアドレスを載せる。
- 東京都生活文化局広報広聴部広報課のメールアドレスはhttps://www.seikatubunka.metro.tokyo.lg.jp/info/inquiry.html
によるとS0000004@section.metro.tokyo.jp

## 期待する見せ方・挙動 / Expected behavior
- メールアドレスのクリックすると自動でメーラーが立ち上がると良いと思う

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ocean3fish** [comment]
@kmizutani-p ご提案ありがとうございます！
お問い合わせ先のコンテンツについては、都側で大幅な改定を行う可能性があるとのことなので、確認にはもう少々お時間を頂きます。

**Comment by halsk** [comment]
問い合わせページ自体改定されているのでクローズします。
