### ISSUE TITLE
[i18n] flow/FlowPcDays.vue の i18n 対応

### ISSUE THREAD

**Issue by smellman** [tokyo-metropolitan-gov/covid19#952]
## 改善詳細 / Details of Improvement
- flow/FlowPcDays.vue の i18n 対応

**Comment by smellman** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/932
これの対応

**Comment by smellman** [comment]
以下の点が対応できてないのですが、一旦コミットをしてよいと思いました。

- 中央のメッセージのスタイルが僕が開発したときと変わってしまったので、 spanを移動することはできたが、文字が大きくなってしまったので調整してほしい(TODOとして該当箇所にメモをしています)
- どこにspanを入れるかわからない言語があるため、i18nの中身は修正してほしい
- pt-BRを空にしたけど翻訳されていないのでなくてもよいかもしれない

@MaySoMusician ご確認お願いします。

**Comment by MaySoMusician** [comment]
- HTMLタグがある場合は（`<br>`以外は） https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-596655583 のように`<i18n></i18n>`で対応可能です
- `<span>`の場所については元々の区切り方ができるように翻訳シートなどで再度募集してたりします。またi18nモジュールの都合でマークアップ変更をお願いしてる部分もあります（ https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-596697737 参照）
- pt-BRは今のところ統一した指針を作っていないのでお任せします

**Comment by MaySoMusician** [comment]
こちらで作業してた際の辞書は https://github.com/tokyo-metropolitan-gov/covid19/pull/958/files#diff-1ac72829bc7678f0522257b07940bee9R83-R95 みたいな感じです

**Comment by MaySoMusician** [comment]
ちょっとここのページのi18n化は複雑なので、もしアレでしたらこちらで引き取ります～...

**Comment by smellman** [comment]
i18nタグの使い方がなんとなくわかったのですが、ちょっと<span><span>ってなってるところがどうやるのかが悩みます...
マークアップの更新があれば一旦引き取ってもらえますか？
(今日はこの後仕事の方を優先します)

**Comment by MaySoMusician** [comment]
一応
```vue
<i18n path="{pageName}を見る" tag="strong">
  <a href="hoge" place="pageName">リンク先ページ名だよ！</a>
</i18n>
```
という感じでtagを指定すると
```vue
<strong><a href="hoge" place="pageName">リンク先ページ名だよ！</a>を見る</strong>
```
になります。ただマークアップに関してこのファイルも更新があるので、差し支えなければ引き取らせていただきたいです。

**Comment by smellman** [comment]
お願いします！

**Comment by MaySoMusician** [comment]
わかりました！ 一部着手していただきありがとうございました！

**Comment by smellman** [comment]
いちおう`<span><span>`の問題は `<span><span>ほげ</span>もげ</span>ふが`っていうパターンと`<span>ほげ<span>もげ</span></span>ふが`みたいになるところがありそうで、`i18n`をネストか、HTMLの構造自体を単純化するのはどうかって感じです。
ちなみに、元のマークアップは僕がやってて、SVGからの移植だったのでベースとなるマークアップ自体はなかったと思います。

**Comment by MaySoMusician** [comment]
なるほど！ `<i18n>`のネストで対応予定でしたが、もし構造自体が単純になるようなら（デザイン・CSSと要相談？）こちらも結構助かります

**Comment by kaizumaki** [comment]
こちらのissueは継続中でしょうか？デザインチェックが入ったので、別issueを立てたいのですが・・・

**Comment by MaySoMusician** [comment]
今作業してないので一旦closeでもOKです！

**Comment by kaizumaki** [comment]
@MaySoMusician 了解です！
