### ISSUE TITLE
[i18n] components/DataTable.vue を i18n 化

### ISSUE THREAD

**Issue by nard-tech** [tokyo-metropolitan-gov/covid19#965]
## 改善詳細 / Details of Improvement
総合issue: #680

- `components/DataTable.vue` を i18n 化する．

**Comment by PichuChen** [comment]
Assign me please~

**Comment by nard-tech** [comment]
@PichuChen
Thank you!
Please refer to https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0, and make pull request for `dev-i18n` branch.

@MaySoMusician assignees の設定お願いします！

**Comment by MaySoMusician** [comment]
Close per #970 merged
