### ISSUE TITLE
[/flow] ページリニューアル／デスクトップ版のアイコンが違う

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#968]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

`components/flow/FlowPcNotRequired.vue` 内で、mdiアイコンが指定してある部分を `static/flow` 直下のsvgアイコン画像に置き換えたいです。

`mdi-home` -> `static/flow/house-24px.svg`
`mdi-hospital-building` -> `static/flow/apartment-24px.svg`

正しいデザインはこちら。
![スクリーンショット 2020-03-10 11 17 13](https://user-images.githubusercontent.com/14883063/76273243-c2394f00-62c0-11ea-8b53-2b7b38a797d0.png)

**Comment by shgtkshruch** [comment]
まだどなたも着手されてなければ、対応させていただきたいです！

**Comment by kaizumaki** [comment]
@shgtkshruch よろしくお願いします！
