### ISSUE TITLE
staging環境等のrobots.txtのdisallowが効いていない

### ISSUE THREAD

**Issue by daisuke-fukuda** [tokyo-metropolitan-gov/covid19#972]
## 起こっている問題 / The Problem
- robots.txtの構文が誤っているため、disallowが効いていない
- 対象は本番以外全部
  - 開発用
  - ステージング
  - デプロイプレビュー
    - ここはそもそもrobots.txtが生成されていない

## スクリーンショット / Screenshot

<img width="867" alt="スクリーンショット 2020-03-10 12 46 28" src="https://user-images.githubusercontent.com/32258949/76277823-2f52e180-62cd-11ea-8541-8b1ddd690b77.png">

### 現状

```
User-agent: *
Disallow *
```

### 正

```
User-agent: *
Disallow: /
```

**Comment by halsk** [comment]
おお、これは恥ずかしい //
どなたかPRお願いします！

**Comment by mikkame** [comment]
おお・・・ミスったの私です！ご指摘ありがとうございます
