### ISSUE TITLE
Typo: クルーズ便 → クルーズ船

### ISSUE THREAD

**Issue by noritada** [tokyo-metropolitan-gov/covid19#973]
## 起こっている問題 / The Problem
- 1箇所「クルーズ船」が「クルーズ便」になっている

## スクリーンショット / Screenshot
<img width="533" alt="スクリーンショット 2020-03-10 12 58 20" src="https://user-images.githubusercontent.com/20850/76278440-00d60600-62cf-11ea-960e-53261da59c26.png">

## 期待する見せ方・挙動 / Expected Behavior
- 「クルーズ便」を「クルーズ船」に変更

## 起こっている問題の再現手段 / Steps to Reproduce
1. 「都内の最新感染動向」を表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by noritada** [comment]
しょうもない報告ですみません。
この後PR送ります。

**Comment by PichuChen** [comment]
Note: Please also check https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0 Row 39

**Comment by noritada** [comment]
@PichuChen Thank you very much for comments. About this issue, at least English expression has already been correct in that sheet.
