### ISSUE TITLE
JavaScript がオフでも情報が見れるようにする

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#974]
## 改善詳細 / Details of Improvement
- #846 にて JavaScript がオフの場合に警告を出すようにした。本来ならばJavaScriptがでなくても
情報が見れることがふさわしい。

## 期待する見せ方・挙動 / Expected behavior
- どんな方法が良いだろうか。提案求む

**Comment by mikkame** [comment]
OGPの件の画像を引っ張って来てくるとかどうでしょう

**Comment by amotarao** [comment]
yarn generate 時、各ページは loader のみが html に出力されます
mounted が走るまで v-if でコンテンツの描画をブロックしているためです
コンテンツの描画はすべて js で行われます

そこで loader に v-show を用い (描画のブロックではなく、display:none するだけ)、
コンテンツ自体も html に出力するようにすれば、noscript 環境での表示も可能になりそうです

**Comment by mikkame** [comment]
これはむしろローダー外していいのでは？
