### ISSUE TITLE
表現の修正の提案

### ISSUE THREAD

**Issue by asuchi0819** [tokyo-metropolitan-gov/covid19#979]
## 改善詳細 / Details of Improvement
完全に表現の改善の提案なのですが
https://stg-covid19-tokyo.netlify.com/
> お子様をお持ちの皆様

を
**「お子様がいらっしゃる皆様」**
もしくは
**「お子様がいらっしゃる方々」**
に変更するのはいかがでしょうか？

もしよろしければ修正します。

## 期待する見せ方・挙動 / Expected behavior
- 表現の修正

## 動作環境・ブラウザ / Environment
- iPad 6th / iPadOS 13.3 Safari

**Comment by mcdmaster** [comment]
保護者の皆様、ではいかがでしょうか。かならずしも親子関係にない人が保護者の立場を担うこともあると思ったためです。
英語だと、Parents & Guardians のようになりますね

**Comment by asuchi0819** [comment]
@mcdmaster ご提案ありがとうございます。
確かにそうですね、そこまで頭が回りませんでした。

**Comment by ocean3fish** [comment]
@mcdmaster @asuchi0819 ご検討ありがとうございます！
現在多言語化対応進行中で、文言の変更は翻訳作業が発生するため、対応が一段落してからの検討になってしまうのと、公式情報としての発信であるため表現の変更には様々な調整が必要となり、結果ご提案を受け入れられなくなる可能性もございます。
その点ご了承頂けますでしょうか。

**Comment by mcdmaster** [comment]
もちろんです！
公的な文書であるからこそ、文言の統一や仮名遣いなどの細部に気を配らねばならないことは重々承知しております。
お手数でも、PR を Reject される際は GitHub のステータスの更新を漏れなく行っていただけますなら幸いです。
いずれにせよ、Accept/Reject されるにしても、チームの方針に従います

**Comment by asuchi0819** [comment]
一応reviewしました。（権限ないので特には必要なかったかもです

**Comment by NaoyaShimizzz** [comment]
「保護者」の定義が「子の保護者」とは限られないこともあり、庁内関係者で協議の結果、変更なしでお願い致します。

**Comment by mcdmaster** [comment]
承知しました。では、PR は取り下げることといたします
