### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowPcPast.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#986]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowPcPast.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

なお、以下のissueで懸案事項が提案されています。
#961 
#980

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by MaySoMusician** [comment]
@kaizumaki すみません！ #980 はタイトル間違えていたので関係ないかもです

**Comment by tomopict** [comment]
@kaizumaki 

お疲れ様です。
現在上がっている[i18n] コンポーネントリファクタリング 関連どれか対応させていただければと思うのですが、「この順で対応した方が良い」というものがあれば優先度順で作業をさせていただきます！

**Comment by kaizumaki** [comment]
@tomopict ありがとうございます！ `FlowPc.vue` 以外を先にやってもらったほうがいいと思います（ `FlowPc.vue` は親コンポーネントなので）。中身をみてもらって、簡単そうなものからでも構いませんよー！

**Comment by tomopict** [comment]
@kaizumaki 
ご返信ありがとうございます！
ではこちらをやってみたいと思います。
まずは #932 熟読させていただきます。

**Comment by kaizumaki** [comment]
@tomopict ありがとうございます！

**Comment by tomopict** [comment]
@kaizumaki 
お疲れ様です。
一点確認させていただきたい箇所があります。

https://github.com/tokyo-metropolitan-gov/covid19/pull/961#issuecomment-596884381

でも言及いただいている緑色テキストの箇所ですが、
templateで分岐する部分としてはA,Bどちらのイメージになりますでしょうか


A.  `<div :class="$style.FlowItem">`直下で分岐

```html
<div :class="$style.FlowItem">
  <template v-if="true">
    <strong :class="$style.FlowTitle">
      「新型コロナウイルス感染者」と
    </strong>
    <span :class="$style.FlowPerson">
      <em :class="$style.FlowLine">濃厚接触</em>をした方
    </span>
  </template>
  <template v-if="false">
    <span :class="$style.FlowPerson">
      「新型コロナウイルス感染者」と
    </span>
    <span :class="$style.FlowPerson">
      <em :class="$style.FlowLine">濃厚接触</em>をした方
    </span>
  </template>
</div>
<div :class="$style.FlowItem">
  <template v-if="true">
    <strong :class="$style.FlowTitle">
      流行地域への渡航・居住歴がある方
    </strong>
    <span :class="$style.FlowPerson">
      <em :class="$style.FlowLine">ご本人</em>
      か
      <em :class="$style.FlowLine">濃厚接触</em>
      をした方
    </span>
  </template>
  <template v-if="false">
    <span :class="$style.FlowPerson">
      流行地域への渡航・居住歴がある方
    </span>
    <span :class="$style.FlowPerson">
      <em :class="$style.FlowLine">ご本人</em>
      か
      <em :class="$style.FlowLine">濃厚接触</em>
      をした方
    </span>
  </template>
</div>
```

B. `<div :class="$style.FlowInner">`直下で分岐

```html
<div :class="$style.FlowInner">
  <template v-if="true">
    <div :class="$style.FlowItem">
      <strong :class="$style.FlowTitle">
        「新型コロナウイルス感染者」と
      </strong>
      <span :class="$style.FlowPerson">
        <em :class="$style.FlowLine">濃厚接触</em>をした方
      </span>
    </div>
    <div :class="$style.FlowItem">
      <strong :class="$style.FlowTitle">
        流行地域への渡航・居住歴がある方
      </strong>
      <span :class="$style.FlowPerson">
        <em :class="$style.FlowLine">ご本人</em>
        か
        <em :class="$style.FlowLine">濃厚接触</em>
        をした方
      </span>
    </div>
  </template>
  <template v-if="false">
    <div :class="$style.FlowItem">
      <span :class="$style.FlowPerson">
        「新型コロナウイルス感染者」と<em :class="$style.FlowLine">濃厚接触</em>をした方
      </span>
    </div>
    <div :class="$style.FlowItem">
      <span :class="$style.FlowPerson">
        流行地域への渡航・居住歴がある方
        <em :class="$style.FlowLine">ご本人</em>
        か
        <em :class="$style.FlowLine">濃厚接触</em>
        をした方
      </span>
    </div>
  </template>
</div>
```


例示していただいていた方は`FlowItem`直下で分岐しておりましたのでAのイメージかと思いましたが、
その場合`$style.FlowPerson`が2こ続くとスタイルがおかしなことになるのと、
例示いただいた書き方の後半が、濃厚接触をした方1,2という併記の形をとっていたので

```html
<span :class="$style.FlowPerson">
      <em :class="$style.FlowLine">濃厚接触</em>をした方1
    </span>
    <span :class="$style.FlowPerson">
      <em :class="$style.FlowLine">濃厚接触</em>をした方2
    </span>
```

この場合は
「新型コロナウイルス感染者」と濃厚接触をした方 = 濃厚接触をした方1
と
流行地域への渡航・居住歴がある方 ご本人か濃厚接触をした方 = 濃厚接触をした方2

という意味に取れたので、その場合はBの方が意味的に近いのかなと思った次第です。

こちらで言及されている以下の箇所もBのほうがイメージに近かったため
ご確認させていただければと思います。

> なので、緑色テキストについては一律 or 不都合な言語だけ表示しないで、2行目に当たるテキスト(span :class="$style.FlowPerson")に全部入れるのはいかがでしょうか

https://github.com/tokyo-metropolitan-gov/covid19/issues/932#issuecomment-596765177

お手数をおかけいたしますが、よろしくお願い申し上げます!

**Comment by MaySoMusician** [comment]
> 「新型コロナウイルス感染者」と濃厚接触をした方 = 濃厚接触をした方1
> と
> 流行地域への渡航・居住歴がある方 ご本人か濃厚接触をした方 = 濃厚接触をした方2

おっと、ちょっと例が悪かったみたいですね。
英語だと、「流行地域への渡航・居住歴がある方 ご本人か濃厚接触をした方」の部分が
- 「あなたが流行地域へ行った」
- 「あなたが帰国者と接触した」

という感じになるので、この例で言うと

流行地域への渡航・居住歴がある方 ご本人 = 濃厚接触をした方1
濃厚接触をした方 = 濃厚接触をした方2

のイメージです

**Comment by MaySoMusician** [comment]
今Chrome開発者ツールで適当に弄っただけなのですが
![image](https://user-images.githubusercontent.com/34566290/76309905-1a983d00-6311-11ea-8f4c-f0f699c7f465.png)
英語版だとこういう文章・語順になってしまうので上手く表示できたらなぁという感じです

**Comment by MaySoMusician** [comment]
`v-if`については、左と右で独立して分岐してほしいです

**Comment by tomopict** [comment]
@MaySoMusician 
早速ありがとうございます！
諸々例示までありがとうございます。
理解いたしました、お手数おかけしました。

A(FlowItem直下で左右独立して分岐)パターンで実装しつつ、見せ方についても考えさせていただきます。

**Comment by MaySoMusician** [comment]
すみません！ 言い忘れていましたが i18n側としては
> その場合 `$style.FlowPerson`が2こ続くとスタイルがおかしなことになるのと、

の件については、2つ続く場合専用のスタイルを新規作成しても大丈夫です
（一応 @kaizumaki にも確認）

**Comment by kaizumaki** [comment]
必要なスタイルは適宜追加・修正してください！
