### ISSUE TITLE
入庁者データの可視化

### ISSUE THREAD

**Issue by mtenjin** [tokyo-metropolitan-gov/covid19#987]
2020年1月1日からの入庁者データがあります。
入庁者は、基本的に平日のみ発生する（土日祝日および休庁日は、基本的に0）というデータで、新型コロナ感染防止対策以降、入庁者が減少しているのが見て取れるものとなります。
（添付グラフ）

これを可視化しますが、添付のグラフのような形で、
1) 月曜日始まりの1週間の集計
2) 第一庁舎、第二庁舎、議事堂の3つを積み重ねで
という形でグラフ化をお願いします。

なおデータに関しては、SharePointサイト上に実データがありますが、
オープンデータ化が検討中のため、添付のサンプルデータをご使用ください。
シート名・形式は実データと同一ですが、数値はランダムになっていますので、右肩下がりではありません。

<img width="509" alt="入庁者" src="https://user-images.githubusercontent.com/54087276/76280573-aab89100-62d5-11ea-921a-61fbf32d8b1f.png">
[入庁者数.xlsx](https://github.com/tokyo-metropolitan-gov/covid19/files/4310364/default.xlsx)

**Comment by shgtkshruch** [comment]
こちら実装を進めてもよろしいでしょうか？

グラフは「都営地下鉄の利用者数の推移」の横に追加するイメージです。
色に関しては既存のグラフのデザインも参照しつつ、見やすいデザインにできればと思っています。

![スクリーンショット 2020-03-10 14 14 54](https://user-images.githubusercontent.com/5207601/76281956-b1490780-62d9-11ea-83a2-f49e69b226b5.png)

データに関しては添付していただいたファイルから必要な部分だけ抜き出して、既存の実装にならって `data/`ディレクトリの下に JSON 形式で置こうと思います。

**Comment by mtenjin** [comment]
よろしくお願いします！
JSON形式のデータについては、日付、曜日、休祝日、一庁計、二庁計、議事堂計、合計の列のみ保存するようにお願いします（それ以外の列は取り込まない）。

**Comment by mikkame** [comment]
データについては取り急ぎサンプルからこちらで起こします（ここに貼りに来ます）

**Comment by mikkame** [comment]
サンプルです。こんな雰囲気でどうでしょうか？
```
{
    "labels": [
        "2020-01-01",
        "2020-01-06",
        "2020-01-13",
        "2020-01-20",
        "2020-01-27",
        "2020-02-03",
        "2020-02-10",
        "2020-02-17",
        "2020-02-24",
        "2020-03-02"
    ],
    "datasets": [
        {
            "label": "一庁計",
            "data": [
                0,
                6505,
                9691,
                6928,
                9565,
                10556,
                9456,
                10151,
                5740,
                6913
            ]
        },
        {
            "label": "二庁計",
            "data": [
                0,
                10149,
                9001,
                9835,
                9222,
                6648,
                7373,
                8691,
                7980,
                7710
            ]
        },
        {
            "label": "議事堂計",
            "data": [
                0,
                924,
                864,
                908,
                953,
                996,
                983,
                1175,
                801,
                626
            ]
        }
    ]
}
```

**Comment by mikkame** [comment]
ついでに添付のサンプルデータと突合して検算いただけると助かります

**Comment by shgtkshruch** [comment]
データありがとうございます！
検算してサンプルデータと数値が一致しました。
データ構造も同じようなものをイメージしていたので、この形で作らせていただきます :)

**Comment by shgtkshruch** [comment]
@mtenjin 

グラフのX軸のラベルについて質問させてください。

最初にご提示いただいたスクリーンショットでは、X軸のラベルが「1月06の週」といった表記になっていますが、今回のサイトに掲載されている他のグラフと揃えるために 「1月6日 ~ 10日」という表記で実装しようと思っています。
（都営地下鉄の利用者数の推移グラフがこの形式になっています）

- MM月DD日の週
 ![スクリーンショット 2020-03-10 19 19 34](https://user-images.githubusercontent.com/5207601/76303367-f6366380-6304-11ea-882b-60514acb64ec.png)  
- MM月DD日 ~ DD日 ![スクリーンショット 2020-03-10 19 19 21](https://user-images.githubusercontent.com/5207601/76302885-19acde80-6304-11ea-967e-4fd57e381eca.png)

この場合、
1. X軸のラベルを「1月6日 ~ 10日」というような表記にすることは適切でしょうか？
1. 1 が適切だった場合、開始日を月曜日、終了日を金曜日として表記する形式でいいでしょうか？（終了日を金曜日か日曜日にするのかで迷いました）

**Comment by mtenjin** [comment]
はい、終了日を入れる方向で行きましょう。
その際の終了日ですが、休日とか振替とか考えるのが面倒なので、月曜日から日曜日のスパンでお願いします。
月跨がりの週があって、例えば3月30日〜4月5日と長くなる場合で表示が大変になる場合は、
終了日を表示しなくてもよいです。
3月30日〜
といった表現です。

**Comment by mtenjin** [comment]
こちらの確認不足で、データの項目名が一庁、二庁と省略形になっていました。
こちらは、データの方を
第一庁舎
第二庁舎
議事堂
と修正しますので読み替えてください。

**Comment by shgtkshruch** [comment]
ご回答ありがとうございます。

> 終了日を入れる方向で行きましょう。
その際の終了日ですが、休日とか振替とか考えるのが面倒なので、月曜日から日曜日のスパンでお願いします。
月跨がりの週があって、例えば3月30日〜4月5日と長くなる場合で表示が大変になる場合は、
終了日を表示しなくてもよいです。

承知しました。
それでは、こちらの仕様で実装を進めさせていただきます。

また、データ項目についても承知いたしました。
「第一庁舎計」「第二庁舎計」「議事堂計」というラベルに修正いたします。

**Comment by MaySoMusician** [comment]
i18n化（多言語）チームからです。
日付の表示形式ですが、どの言語でも統一して表示できるよう「M/D\~M/D」「M/D\~D」といった感じで、言語固有の区切り文字（「月」「日」など）を使用しない方向でお願いします！（具体的な形式はお任せします）

**Comment by shgtkshruch** [comment]
承知しました！
それでは、月や日を入れない形式で実装いたします。

既存のグラフの軸やツールチップの日付の表記は、M月DD日のようになっていますが、こちらもこれから修正されるという理解でいいでしょうか？（もしくはすでに修正済み...？）

**Comment by MaySoMusician** [comment]
暫定版ですが https://deploy-preview-822--dev-covid19-tokyo.netlify.com/ で「検査実施数」以外のtooltipは既に修正済みです。
全グラフの軸と、「検査実施数」のtooltipもこれから修正される見込みです

**Comment by mikkame** [comment]
こちらに関しては元データのlabelを直した方がいいですよね？

**Comment by shgtkshruch** [comment]
そうですね、お願いできますか？

**Comment by mikkame** [comment]
```{
    "labels": [
        "1\/1~1\/5",
        "1\/6~1\/12",
        "1\/13~1\/19",
        "1\/20~1\/26",
        "1\/27~2\/2",
        "2\/3~2\/9",
        "2\/10~2\/16",
        "2\/17~2\/23",
        "2\/24~3\/1",
        "3\/2~3\/8"
    ],
    "datasets": [
        {
            "label": "第一庁舎計",
            "data": [
                0,
                6505,
                9691,
                6928,
                9565,
                10556,
                9456,
                10151,
                5740,
                6913
            ]
        },
        {
            "label": "第二庁舎計",
            "data": [
                0,
                10149,
                9001,
                9835,
                9222,
                6648,
                7373,
                8691,
                7980,
                7710
            ]
        },
        {
            "label": "議事堂計",
            "data": [
                0,
                924,
                864,
                908,
                953,
                996,
                983,
                1175,
                801,
                626
            ]
        }
    ]
}````

**Comment by mikkame** [comment]
こんな感じでどうでしょうか

**Comment by shgtkshruch** [comment]
早速ありがとうございますmm
こちらでいいと思います！
新しいデータ構造を組み込んで、この後 PR を作成させていただきます。

**Comment by mtenjin** [comment]
[入庁者数.xlsx](https://github.com/tokyo-metropolitan-gov/covid19/files/4315518/default.xlsx)
念のためですが、項目名を修正したものをこちらに貼り付けます。

**Comment by mtenjin** [comment]
グラフ化ありがとうございました！
原局の方々は局長以下喜んでいたとのことです。

別途Slackではお願いしていたのですが、補足の文言を入れてください。
イメージとしては「都営地下鉄の利用者数の推移」の上にあるような形式です。
多言語化は後回しでよいので、日本語の追記を優先的にお願いします。
ーーー 追加する文言
※土・日・祝日を除く庁舎開庁日の1週間累計数

**Comment by shgtkshruch** [comment]
@mtenjin  cc: @mikkame 
グラフ化、喜んでいただけたようで良かったです！

私は Slack を確認できていないでのすが、
取り急ぎ頂いた文言を日本語のみ追加する実装をいたします。

リリースタイミングについては、コアチームの方に判断していただければと思います。
