### ISSUE TITLE
[/flow][i18n] スタイル修正 FlowPcDays.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#990]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

スタイルの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowPcDays.vue`

### スタイルの修正
・真ん中の縦ラインが無い。
・右側の「ご高齢な方」「基礎疾患のある方」「妊娠中の方」の上下間隔をもう少しあけたい。

↓現在のコンポーネント
<img width="562" alt="スクリーンショット 2020-03-10 12 05 20" src="https://user-images.githubusercontent.com/14883063/76282260-8d39f600-62da-11ea-8059-3c0e44ea88a3.png">

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by kiiita** [comment]
こちら担当させて頂いてよろしいでしょうか ✋

**Comment by kaizumaki** [comment]
@kiiita お願いします！
