### ISSUE TITLE
(ui-test): use nodejs instead python.

### ISSUE THREAD

**Issue by justintien** [tokyo-metropolitan-gov/covid19#991]
## 改善詳細 / Details of Improvement
- use nodejs instead python for ui-test

## 期待する見せ方・挙動 / Expected behavior
- I did. But when I PR see that no issue number can't PR.
(so..If need to, can see: https://github.com/justintien/covid19/tree/ui-test/nodejs)

## 動作環境・ブラウザ / Environment
- macOS

**Comment by mcdmaster** [comment]
Simply, here's the issue #991, isn't it?
Can you please elaborate on the denial of PR that you faced in step-by-step manner?
Thanks!

**Comment by justintien** [comment]
@mcdmaster 
`関連するissue 番号を記載してください。 Issue 番号がない PR は受け付けません`

So I create this issue...haha

so can I PR this issue number!?

**Comment by mcdmaster** [comment]
Why not?

**Comment by justintien** [comment]
@mcdmaster thank for your reply, I will request this PR.
