### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowPcAdvisory.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#993]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

i18n対応に向けたマークアップの修正およびスタイルの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowPcAdvisory.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

なお、以下のissueで懸案事項が提案されています。
#957

### スタイルの修正
- このエリアは、最も重要な情報なのでフォントサイズに対し可読性できるだけ上げるために全体的にfont-weightはboldで良いと思います。
- 電話番号部分も気になる。。。

↓現在のコンポーネント
<img width="239" alt="スクリーンショット 2020-03-10 12 12 59" src="https://user-images.githubusercontent.com/14883063/76283377-c6c03080-62dd-11ea-965c-964848a008f8.png">

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by kebhr** [comment]
こちら対応します。

**Comment by kaizumaki** [comment]
@kebhr よろしくお願いします！

**Comment by MaySoMusician** [comment]
Close per #1044 merged
