### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowPcPcr.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#995]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowPcPcr.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

なお、以下のissueで懸案事項が提案されています。
#980

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by mkfsn** [comment]
どなたも取りかかられてなければ対応します

**Comment by halsk** [comment]
@mkfsn さん、ぜひお願いします！

**Comment by MaySoMusician** [comment]
Close per #1066 merged
