### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowPcNotRequired.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#998]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowPcNotRequired.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

なお、以下のissueで懸案事項が提案されています。
#960

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by nokazn** [comment]
こちら、対応してもよろしいでしょうか...？

**Comment by kaizumaki** [comment]
@nokazn よろしくお願いします！

**Comment by nokazn** [comment]
すいません一点確認したいです。

以下の右側のタイトル `新型コロナ外来 受診が不要 と判断された場合`の部分が右寄せになってるのですが、左側のカードのタイトル `新型コロナ外来 受診が必要 と判断された場合` のように中央揃えにする感じで大丈夫でしょうか？

![screenshot](https://user-images.githubusercontent.com/41154684/76308816-f3d90700-630e-11ea-854c-7b78d7904d23.jpg)

**Comment by kaizumaki** [comment]
@nokazn おっと、そうですね。右寄せはどう見てもおかしい・・・。中央揃えでお願いします！

**Comment by nokazn** [comment]
承知しました！

**Comment by MaySoMusician** [comment]
Close per #1058 merged
