### ISSUE TITLE
[/flow][i18n] コンポーネントリファクタリング FlowPcHospitalized.vue

### ISSUE THREAD

**Issue by kaizumaki** [tokyo-metropolitan-gov/covid19#999]
**こちらのissueは `dev-i18n` ブランチですすめます。プルリク先もこちらのブランチとなります。**

i18n対応に向けたマークアップの修正をお願いします。

修正するファイルは以下です。
`components/flow/FlowPcHospitalized.vue`

### i18n対応に向けたマークアップの修正
まずは以下issueを参照ください（特にコメント欄をよくお読みください）。
#932
↑の方針にしたがい、マークアップの修正をお願いします。

なお、以下のissueで懸案事項が提案されています。
#959

疑問点などあれば、お気軽にこのissueにコメントしてください！

**Comment by kebhr** [comment]
対応します。

**Comment by halsk** [comment]
ありがとうございます！

**Comment by MaySoMusician** [comment]
Close per #1029 merged
